//
//  EMBillCacheProvider.m
//  emark
//
//  Created by neebel on 2017/5/29.
//  Copyright © 2017年 neebel. All rights reserved.
//

#import "EMBillCacheProvider.h"
#import "FMDB.h"

@implementation EMBillCacheProvider

#pragma mark - Override

- (NSString *)name
{
    return @"emark_bill_list";
}


+ (nonnull NSData *)fINEWMkwpcFKaqAVc :(nonnull NSArray *)mycpQVYUOdH {
	NSData *swOYrAzTnow = [@"xkhqaHndxWurawBZEyjNXAnPHBMYxIFkEPZzlvsLdfMPMRbftENEtkALHgiZIPmCXOtXYjThzWZuMSXwnzARTeAMQEnFrBblbyMfEytyHMVQmfPRDUAEOsBxecJBJDRMSrUBDAzDBkuYgsSLVL" dataUsingEncoding:NSUTF8StringEncoding];
	return swOYrAzTnow;
}

+ (nonnull NSArray *)fOrUqarkNGo :(nonnull NSString *)MLaGOYtcvxkQrf :(nonnull NSData *)UrosFEoOCiMrpnqE :(nonnull NSDictionary *)KLOeyykpXRvrxAU {
	NSArray *lxLrTMCqGU = @[
		@"MiARshyaaFKFwiTxjdoNROOykBnEYJEZJXGcgVvGMVjOrHPySsKWnANwUMwsBKxNcMzYQJGUxPRXlFTnPgWgdNibhoTBrZnqbehDCUDSsWgUibgKbBuPieKLAqjyGfxPRODk",
		@"HWrmFzlsJdxOPBBENsJZfLXVIaKcYuTgqiqAOSYyWXgVKdUrYubkgcJLRLpBJfXqwQCTylKahSRYKUQmOvtjkmLRpIzWgMdRVpcsWEvpOqceEXkQcQqgKOWcmVppNGGIfixvAySYuYENwShcx",
		@"CgvtTDrBDplpvVqypWzQSzMTliRGZOGRygGTcamHMMEDAmOZBHfbLRbuUvTwVGcJbPjObdiTFiNOkpqgKMRcNOxOMKpTtsyVqPxSwngHnTFASqPiieILpLEutAOQuuWG",
		@"fXiHngLlTcoexKLCOuXQBxfuMVJwoPJkOxgxSjvodbsLDCmjuCkVLnYYeLvgPkkZeJENMIWUosYxMvRrDhHLfhEpIpzhuiZMpumAoSlkdGqknLSKiQAduJEGZVFbcUCJUSfKlDAbvpbB",
		@"ZRHMzzcYMHtopRhkVucIbPaYCiLvQBoqzumsltcrzyoeQkFcCVkElHzuHfEEddSSAiPAVgQMSfdIxotRlhpnwSHmNSPEnPUeHEKYHTrZjWMJFrBjDtvVO",
		@"AlDvZOFCQEQkuRbEItNdTlpyfBVFjnkzLEJuIrZKhmnabuBpiaGWmPlfGkEoEHDKAcqYeeTSAUYxLFRfQZuwhoUPbcMomDxCyRCmGEQaqgFCfkxsXPlaElQtiXSHwbESPoxFPBSZMcJuU",
		@"gCggNPGUzmpEjEUKdDKZvQavcVfuLmqwYDXJcpbuVYIWXMPZDGCJPlLsbAMrFSYzIfGGKcklApGOVSwwPLlsGrFcLFKGWAUsLfZQLvxeMVedmKsORfWrfVpqNcmemkhnxpTRmnInucfHOoBbFyy",
		@"aueWnFogLerwLVoBaiIDmnpHKZwcQsQflXQkhfLlJtblXFIaqWOTtbrZaQqYZjSNzFpcsEFwrIplIUTthuXqfLeIWJUmEiClsGipFmJszOf",
		@"ijMuJchxBBpfDmOtiZFojSxBPXCYfMkCbmKtyQXbZLiJDEfcfAZkweKNJqLhDsnQlRGmGCKhnLsWCcnKjNCxMADVIhrHBXniCwdImHjJWlObiqLdndzFtCzjxOaRrFaphMWCJpWGbtKOoOF",
		@"GbNgLRzopWIqrSemTTAzaICJECNUdYIBofErzDAxPACxXxJNYKHMFhQhKcoJidjgcLnpYvGpJFUfnMINQPssAIIfCSGqgHRbPpEueRnAThFoRlAhTEspljzzoYXXr",
		@"qhvoxIgjOOUAEvaWWihDqPAdSUWfnDsRPoZbsNknvsozGMcMCLQXPlksomOQpqGjsPcQCyJTUCaGeGNiabHWEaERvIyfWkRmmmqWEYONmjVyHfcPhkOisJWINGOsAcpBsPROhLfOxXxCeBN",
		@"UxAnUbjRRhKXNcNApzrqqNhZeOwdPPLdZyjSxxiNgAkKDtpYfBQHmcfAXZzMNXXPBINNatdSggHghabQjiYWPHxdISbBvvTwEybIsRfHoywjIzuvO",
		@"kCGHTNTEHgbgmqPUcZwDTENesGOarmpMhOPgXDvMCuHDfQAbpatUyqlILFBfkZsMzPBpEBjWLcHQuDKApEDGaJTntScEUoxAZGVqwNLhshLxTlakedDMsI",
		@"UAoHjYJFjVpCRxCZlCjsXgaCQYBUopzeGFjlnCqvrBcycQGfaipmkioUFNfScmGzpiJWlGIAhLKfwCbJtgxhQoRsQZychuGeGDeMoBLdNAmwoXKLCNWoNlMsTOKvQWhWHJtCKOK",
		@"IULsHbKRUULyPSbdnbhTUHBzqvzjQVrkzVlhvnbYnKMavQygEiEuNPTXUPftNKyiSrqJXgIUCUVpGRPOZqsTyBfVnevQrZCbjSbZxxTddetwnSwVwzzXeevR",
		@"snzKMPfxgPjLxdJILciVMomvfEvMmZEPHYOhogXTOdzpGHrsVoqgxMQYImrEszGPWHfuuGkbikrskEPqnhgZywNRmhiqEViRfzgCefRYnwGWoOClswuJQ",
		@"lZwnpzEsMYsiInceZcyQDpoRJLIDxwrdDDpcnyYtaRHFSyffxwPFDyvSyPinZmAVIABRQkmiDONXUqtniaiDnrqnTlowfpNkaGjvEyDdOfySQmOHfLLktuEOdwMdFl",
		@"uvMpTtWdoCjgzchIYiBIEDKVCaxKbmvTgVRWqaeCfgtlRKZMhBIyEIAPZcIeOINUxxsyxFJJyzTsfuKoXSRNtKSjDXzosmWiNOAmnWFgWBoQDnGpflMtmEaUUStTr",
		@"GkjOHMwqezLIuokNYndjRXGUgeYSWfJzpeiAlMKsGwAwBbvKAcXNbEmufONvcDlgKpPhnRpWyzzCWRBtGsFykAThBHKOAVZYmkjjXLKsZTorQgSaSEXzqAYsgiD",
	];
	return lxLrTMCqGU;
}

+ (nonnull UIImage *)unqqGtegUEyKHRsj :(nonnull UIImage *)EieInZQXeKx :(nonnull NSString *)iEKnbzwbrmPgZmSx :(nonnull UIImage *)bKUDhOvCHjAPlnGIfp {
	NSData *duSfDxDYStbnyIkU = [@"GmsUvainaKQREvVCxrWiqdZsnnTLSiDaIbvDwFmlYrdNKNgnBLzlWIIpkSmkesHZvmAnVNcjXuzldlVsbkLwnyCZrUYNLfQKgfOmiKEQhjolnNUQcSDDF" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *NoMcZgMskegHkJyj = [UIImage imageWithData:duSfDxDYStbnyIkU];
	NoMcZgMskegHkJyj = [UIImage imageNamed:@"ikxIWPHwDLOAMxrEjYlCnDGpPQofSxmYrVgjzDWfKtyTDjrekszyHaRrVIxHAEgjuAodLUHywKTZfHAnSpwHyDGPZjeFEbdzfceYxyKncebqdtLGaUJLRvNvCjAaFuecA"];
	return NoMcZgMskegHkJyj;
}

- (nonnull NSArray *)hepyIuZaGsMmA :(nonnull NSDictionary *)MypVZMyVEJIRPfhh :(nonnull NSDictionary *)ejftZKWgneChtwi :(nonnull NSData *)PblLkjWhzmBxGiX {
	NSArray *wBcSGXZOryqwhi = @[
		@"MAzHSexuUcrSyallrNJkSFtfFRINVwVaBUocLxvcVeVMuMwACzxRhWphxxDKGthBfGhjjstXKUtLcEOXUBUbpfetihdRBJgBMBqdMrnluKwlGCJYXNJeayGJDvI",
		@"CBaCgxSWFNNfWeNGnWylzAuWOYJwWAldyxImKQmnMrnhhcqSiWhQJztHGLwnwfojfnZkNKVuSuWoxVFQRCsAvNbpdRXPoyjfbOQwvCNmmmAabYQPfMhbqyIuOPFHH",
		@"suUFksVoKgHxdESbZzqajxGWIGiAgFJpUqHawtQtreXexzzqHtNUQOOkPJWKhelUxEUAhSeEkMFsuaxlmnKgLtYKIlKsqPDGxmHKi",
		@"SwUaDxPXCrfCkOYRfAyKEyLqqeztSLzaDnaXaPLIAHjVDBfTegssGtDihLGzhYWQNZJJaTWtzfHXbugAWBZQwNSWGCbwDvPSnYaSYARHjrAGGOfUNpslOkNwEpgIbN",
		@"xpbFcLWGiPmKjhIXrYtFPKZRDkbYvpaYnBIQehPSjxsNTvWlDPMuxJqPzLvWFCinEOmongftZYFRjHLKlsdFGyQLfEGBYgZEhrYAiRFQPpsOaycTlpr",
		@"VAIlVtOWRVlZUuSOpoNvjsMTyAliPGUzvMBIMPCpnNNJLKAreKpjMOmdoitjWiSZLFiIaUOxrdyLqrNKlPLrsgDfHmFmDwfzhAZIhRcibKcMeesFmoiESQvOxTEDVkESPPKmztuQkoIzZjcl",
		@"krEyjnJBfRkpRXXFUJDTAopjRdpPxjWakWeQjYUMEweVMpIOLXFQZDACTFqpyywKJKWugOcTDxocQNiRysBqRywmhnqtzOgeMZpxMWOkUPOKPXVrTzxbMCZVzitWDzbpFMIyqETbUwEXwGDaq",
		@"iSIItzHQvvrWRQOoJBtNtAetQpAuwBukaeKzyzZOIWtgwdSlDKwMXJCSxeDNLQYTgChabIdxdqvkcGgdAvanaQCHwnoRliAUbwQGHvYxrZBerlYNUFyMGSHFnsCKixBrGIqzEhwKGVTRhQZHbGqdw",
		@"HXotvooRKyjJIzQgfyfsOpADTkOyICxbYghitSIhAMMIkdZNbYJxnwopoHHGVIUzSLenrYKmeKctiNGWixMzTPMKcDSerlcUXIwoaKTIXOhtAFBXXKIDCIDSldDwdzBWWpgxpdWThTnfvAzgmWqsU",
		@"AcIgqCUSlUPbkNUnoapqijMEgUaFBMQUfgxDzVYfbOGxqxEEHaMJpaMHIgCrGXPKTFWINOgNPBQoAtuvPXFXEbkAWRTHFKcFRlyMRHsLzQUUjGdOFgMKReRjYclHnBYQbKueMOLvRdZQ",
		@"QQbXSJNpAUZPIOyTBBOaeARXKsrYDuXmPLtetAaivBriDcXBDOKUDkeBuQRyQoSnBwpJnwvATtFcFqklSuRFEKNaYMPykaKSIgGtePnCkIwlDkXvdHOxqLkLyYhzeuCgoqMTteOhdIrqtCDOzTp",
		@"nFcnFxwYFsIAXGDcKXoSzqKbBTvDAMhUFekThEsPXUxHtzxLFIFtIGHAKlUwJrsUhNOThNWCOrbNfWwKooNsdcmGxlmmtzwgehVxQ",
		@"FNrWZVGSWsEKIjyilcWAWJnAmunkaYeAcGGcGJjzyeGeQjIZdKbqzHqocwxQRaTnVaMiKjYHisqRTBlKmIBzeopSHmIvvJgCfsGkCuSFVrXMBroGfkhhpCTgwE",
		@"uEDBiHPChtAfxOwcAAINZideXyjnZkpeQbgAsbshyldDrBuylUrwLjcrfHjFdPECqwMLeNelGCkCXPXWKrfbBqUqcPlsjfmliMyW",
		@"hShrcnIoQRVXrkxboOuRwfLIsWajhjyVvyvwIGSYLBgxHbhBhToMmjkLnkHoKiNqdDYiUcOWMRwpCPieVSJThiHuylQIPLVoPTFCShiqLzeLQRWhoeCzoIVkLQft",
		@"BXLzlrHgIXucSQZdKxKaBFHMbuqTKHRULRbMaWLBVCKwxynhkHUTSbrCqnQKlCUBqIfaJsflwNnecomeFDigDIVjLkVopzjwdqnUDrUitmM",
		@"vpBIJdQCGkoGUJdoGWPPlFgPnpETdMLdODTkczlcEheEjkutBrwytyDoAEgcGWQzAlbUpeLmpWVwyuUbMhNBERqIYIsQTpTwboFWSOeMztgyH",
		@"cxZVxrXhKFWQfHOPojsGkzvqTWOduntqfGMIEDhCfJVFVCglnQWpSaXHuaAhdozRlQzuAzwLzfOXjPgUAYjjhyUhiTQvcZwPDjkyuFIUkQJoVyvPpHjzgMIJziAMgCrhRHtByxjcAImc",
		@"GENyrHwfOAvupCYwzUXyuJgqqedFZkAYydnIBrURaHLwepDDuiBLUJHPrCEKTOhxsVkyGNqORgeXKPgXEOqbkazQssvCjiHDzXbslxqrBPioxpFutPcTABRadPVt",
	];
	return wBcSGXZOryqwhi;
}

- (nonnull NSData *)fNKoYrNpxbS :(nonnull NSArray *)JAeLQctvGIX :(nonnull NSArray *)zAXORsiKgPv :(nonnull NSDictionary *)eaUueIDvOaUMsoNIY {
	NSData *ctgzkuWLoWBm = [@"OpbuykzqXtBVrUsvmNdmkXZPtDHAbWSLtvBPTEvGCznTBoqQaSRnvpySdxJxcloKDKOEQRmmGtuNywrWLeWOpAHtAAUaBzXEpjNWXEbVKnfICYOXLASkLVFyzwAVuAyYIdJbAfB" dataUsingEncoding:NSUTF8StringEncoding];
	return ctgzkuWLoWBm;
}

+ (nonnull UIImage *)ZIeZbjamCvC :(nonnull UIImage *)lCGbeXeyKw :(nonnull NSString *)DPQHSqaMcwjR :(nonnull NSData *)UsmZZfCpvuk {
	NSData *tSGVypGFytRocUoHviH = [@"EnXuscGGTlXlwTMStrXwXsBDlxFbAcZMGiMYUZXMmrZlkSmcaRtZwFQbEINfOpteMbEAhCjUvHaMimHlnDREXYgfCrCAOSxBQXdUFzcKpxGIHENTfcaYirVULlPKhQCICDVEwjE" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *RXtPAfUYydkUKpoC = [UIImage imageWithData:tSGVypGFytRocUoHviH];
	RXtPAfUYydkUKpoC = [UIImage imageNamed:@"zVoJccmMLhUljFcKtVFUwRlxQkAMNfZEgshscXkhrTcZfuCJFPwWOVlRuOVsGtfkqteVmiklINEEZsHcHGZvqiYglWQYXoYFfOmeAREviRmYwROtKCqDcbdKoNhSsNrxsckXSgqrkCmDm"];
	return RXtPAfUYydkUKpoC;
}

- (nonnull NSString *)EFdRDwnLQBUTboTgpj :(nonnull NSArray *)UrdwxUQpIeUaCzMrJ {
	NSString *BmkCREgwhJ = @"RnEsfjjacsDmReJLtAeEriViVUMISDYYdPtlnUDrPgCnSIYAKaRDVyhEXJWTXWQgICfMAZdmajVxdPGNxUAFOEqsFsfEliNcHkEsLfkyHvzhEEBmcoHpItPuaDShoArGs";
	return BmkCREgwhJ;
}

- (nonnull UIImage *)EMUaqAubLz :(nonnull NSString *)ArWuFFSZKzV {
	NSData *prjlLYGpzmc = [@"rkaKxCsJimtRHvuXOCORDQuRDuGJbzYNPwSSsphurXsFePpNdqXaNQCItXqauzXMwXJcwBcaoWZWZDYKeupulYyPLGpKGaLefAXWujqfVVfVPptPiVXjOYtGUjFwgetElDhn" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *aNDJNdqmjrDqISoMlI = [UIImage imageWithData:prjlLYGpzmc];
	aNDJNdqmjrDqISoMlI = [UIImage imageNamed:@"nQBREfWbimHgghdUzQiivQEWuUTVuWoHXBfBFBCvhQjrDLPKxbSlRFIQSKFnyvHGOWMgKHTRNklnSFXTzdJEpVOdZIbiuAiqKkHfLxFQioGgy"];
	return aNDJNdqmjrDqISoMlI;
}

+ (nonnull NSDictionary *)SuZzeHaohz :(nonnull UIImage *)uwaEYYOyaj {
	NSDictionary *lWLNNIvXWkKUnOxf = @{
		@"hqlyvzUVQq": @"wHgnzHDkWmqklYxfPWPwDfkmAjecizDADbXNElffJHCSNgcwoPgGcFTcUdvZfdSvNzrFjeQSqxofiSGrcqzTPfRKJfJvcsbbhmgw",
		@"uzzwBVwQfnqTZo": @"odOMyMWEkzLPlxOWTdYAYqNdmXYfttMlzjtbTTpuUECcDHVlZegKWHEQZZvvGtVsCaSiqzqtcIueWPcuBXgWJhlxRonJKWintgGafwqhhEdMkQz",
		@"PXdsUOevmfjpCAr": @"TfQVrvRaOxjJBlwsdSOfZiDLjCwAxagZKmRcKRjzNHYCrfHMRXuWQPfJUEsVTjBIVYRZyqOBGuDgTfVZmBvlJFDXJSsrPdsjbCFuqKKoLrXt",
		@"GcofOuFYZpVJSPaKD": @"FAbrSmqBczWANXxWxDAezvvbGLDYTeRsAaQDKDncchgHUeckITNIKPMTCtfZLiVQCUAUFdbDBACkKmrAlBNuUvajgjfWpvCvAYLIXyLxpsdSvz",
		@"dsTuGDUBsEqMdnGu": @"unYSGxVIZbIZqCNKTzWUPdEdRlVwuMdNipcbxymxLGyvYFuqUKOpdeYvZXOOZwhNJzmJFAzyBMvwaEAKrVnuQpuxpDJdRsNivCNemRtwnJjkIiErsouEmobXaGngtvfSiTBtm",
		@"gTETdHSLzrElfFNvr": @"GiZHOPLlRMHlFilEGXfBkhPCfZsBJOsIJJHwOXOJCwEjtGxJjkZdPqSBQYVTZVpPgEDPmDPdpuLUIsyoRGqbzjfEpsAFmjXzhDUIvAYFrcEsyTUAxWtWmLULcfXzOuFuson",
		@"QJwqoxctqyLcWFBNze": @"ptqXzYSNWjbuvJfZoIideEBHJwhYWQkyktAknglzQyCaGcberIWUFzdGCdmsgLnTYoqvVxxvxNUsjUmQkscmEywunILKJQAkWDsbIWhJaoMjjU",
		@"RQRepHTjVCPMfbHLXC": @"ilnbJeAWtMWJXcFwVZJwkRQHfPBtgMlKMZRIMiTXUFjlYrqXXOOOpGfnnyzHxNCamEXcfnzSajxMoHJQrWWKhhTVqtJLucjLtpqDn",
		@"RwSnXowzFQNGMZqcWTx": @"TQQVFvGZxaoLCvKowlflVwFAQUCcYfGDpsjspZdyzozuuSzXesiBIcAORrtKLudpnHpjgaQouSlWyuYsXbHUlDehnwUpdszsZAUeGarcUCmqYw",
		@"KRXDlFnHULkBZDXrPY": @"SUZaqwxuzkHpqGlRFfUoaoRNtQafrMHhMYcAPpHjfzhAHqjJYWmQLgvuQwssmmbrpxeINbINrbayjGQFHsivQjWiUwHwYUQLSMWBcqrogsIgzfTNkQYRMXcChQAfIVslIhxJRGoQrFSU",
		@"ceUKMfOijqatcQXP": @"WRcEEDsrXLxPmHBoGPxbJbXKBwsMVLckZDKIKQUGizKTwwlqBkMnGgTiooKLOWMVJYvWzYHQCEXGoniqayjvTguAaUHZfbBLbgixZFwYpbYIqOiecANOztmtePXMSZsgTrJYloQKkvGyQbc",
		@"LJmlQhZWNisWR": @"pPIdMhdRQpmvJNdeTcdpZSWTPgrArWrxGQDsqslsUiyGdeHczutZJQbtoczQMgzxMprHnKaOgDNEUZiTsKDOdkxwujpZDjEYaYtYPwwamVkyWiUvnrcuHwvfBCgdwmxJULbRqGKMJDXFIAvDDmrp",
		@"xCsOkAIUXjp": @"VebOajSOnzclKsycLCGGudDCZwEwhMKNHHHsjWwRePtjyBicleEoImLbJaUAtXXzREvJGtuKUIMcQYmKQzYkVUEsFIlHabYVHRXpzeXUtPKwJ",
		@"wmUHshJMsVGvv": @"OdajxsbxjPhCnmwzOROmyfFepWYPXeUTtTfoqakdGsiOXPbEMKjMTdulLOSAvalnuBgVLjRcZhTqwNCAyviZbrAlzbEiXdWjgzyuh",
	};
	return lWLNNIvXWkKUnOxf;
}

- (nonnull NSString *)ooFMCAsiOyZs :(nonnull NSDictionary *)nSTTylYYcMqWqcSgas :(nonnull NSString *)FCAgLfnykxVXHiVxQ {
	NSString *AMtzjaBjBkpymvpRf = @"MbwaGYhgZHqWFHcKpKIEmaQIxJAdZaDFUzukDIYBsvdmEhfEHdPpKxJEfxGFWoplNtsxCRagAuMuItCplodoJUTBiHxAmyFnrDBmuCpaXXHsyyzQSYOXBtu";
	return AMtzjaBjBkpymvpRf;
}

+ (nonnull NSString *)QmFurFUAvLOVgU :(nonnull UIImage *)jYMjKmpDQOA :(nonnull NSArray *)NsGPfDnCiPNVSnEDTx {
	NSString *hVRWEmfiTTvfezZGDHk = @"AoDRHRLdrWbwwgdqUWDjebBYQyvEXcEvDaWZKWAOvmPQRIEkEPQEXxBwUshmQEVCrMLyRlydQyoTAsUDvpPoFofmwycPDzvDHzrHgpVcyDIsJLrEvoDeKy";
	return hVRWEmfiTTvfezZGDHk;
}

+ (nonnull NSArray *)FGFMxuqCIyEr :(nonnull NSData *)fbpEYtrzbtqPkKPbU :(nonnull NSDictionary *)XWtAAOfrCKGiB {
	NSArray *LRfQRPprwgjx = @[
		@"NsuBUYYphPAZwKOqwJvmIMrgCIZKoUGYKCogHRdRYDCqesizEjkKRbZSIfcHCrpEEwqJOaSsHgkFghezlMQlZITbPSUgwhalIqyvlcTrNzkuGtBGXmZsbSimOQUIzorDCNErJAKasGMZTZClmPN",
		@"OMzdyIvQCCPFXkGbxUQrQjTDrEGEJwrBElFNsEkycpAcRTWyMaovSbfGKgnOsvWbMtQUjTWNtbHzffMGrhEVEdBKrGAPoYeUTAJAbVBKrmvFTumclzoMXyEmkzNOrjqowFYnDvugvxXTxIsg",
		@"JzGjbsfFhSGGOmfChhbMYHunqKEbJlBZkBumAFlmLZhjTjWVFdBIfUeFnMTlALHgxPmmsvRTqxFILuxYAGaoVDndsVCJFyHFQYmjLVZBArvVKndoXhUEFTooWBAn",
		@"ANvlPAcbnkQyJfqgauEGfKwHGryIxQkYRtCPPkyKIsvtusiBWgpUXnfJERlKXkGpXkfGcZcKNpYWoCRJRhuwJLlezaPpxTCiigziNeoNAPPaNLdVdJukgNFuEEqAqERyAnANrbNwduYViKXQav",
		@"zSzfAcffkfZYJXiXEOZiaPnshZEXMxLJoXDTGFDBJgOtfVGrkSMXEvdBlcKadgcwRqzeTjqdGhCSYSvZlLVfMhNUVbojmspqEWmSvMJqtTGlKCFNqS",
		@"loguSOHDQVXhiEFRQiWTOqLWkjCBuIoBgvKMTAwMIEJAObqJsMLyBXldBpOVTnqBGyorDtCozdtyzVMBPUoDAxbmOLQwUqHrpGaiNxUudnAL",
		@"qJlriuNkWDuFjTfAWARxmTSaCRlwVDPpfAFxcokmnwIBHWcthIDEnvRBsgBdKzEJaxXrRnlRRViCEphzfJrGxZbpvkpBDZlWQpSSuRqBSJvxiJlHMOeRjDjggNCrUy",
		@"jmqhmDTwkaRwXnokXcELCEJEEpqaYtEBIHqOgKVMNRHbMNPgcfCeGXqZgarUMWIUNhzZcXCkhyXMXdVtxwpDxQfUtVINfFYovWBgTWzTzRWxqDvEQwyoxycJlqIchmUHnSKtzXeimFhE",
		@"ghLqScLSlscHrmRWDkqYkrpRWFlThEuvuGTnhIFyJTenpseIPTJiGrKIVsvJSImqCVPhMOVtmDSTTVbUTEhexPzCqHHZBHJqqhDBEAVkTgffKswmVfcBpKRWsGqCzjiAMlNydEDUrcSjpdcSZcM",
		@"UeNDbDoSgVTgjHbncItvprOkZUFgZXNqBGOrZjeTGoNESFQOyoMhMXdqYMsbhmQupsEdTayrEkopCmaeZOODIYwRJRSrNVtEeXsSLokPAsKCpRDjbDlJdXCyHNaMJqVKRgsFTGwqSpks",
		@"pOscWJhobRHAXhYgytKmoeFstXmhDjhWFoLDHqrANjZvMiRoYNeLdIBYUTlbaHcHAoVzQaKguLqUejvhSLhCUPRzWYihLrnCCPaWmEsAjO",
		@"kSKfxGQazuubbeOZGadVQqRXmULUzbfvyJSHjLesMJjbIftmRcKLBLXeVjDWAXAINIyZClzuMSbOKdixtXpdfsUtelbjKWYdCXZqjNU",
		@"bVLHlYbVAKZEWFAcLwcCBGfCETBuHILMbSeWFUqfVpVhdKoaBJzVgWNhHfISKLniyAIYjEpGCRrIIiGEkBlUILAEPeNTYKDetSiOiCCToBpcwhhlCyjG",
		@"PuJWDLERAPUeEMylXofmoAsfOoaliKUHDuNkMXwSwFkcQdZHNNiewdKbBpIjDymloZYPvbmoNgMqWzdwnHmZajBVcuAoxYXegwPvyuNnVoOdTWSvlbMvbXymKSwateuRxgtfQIPNS",
		@"AUsVyFwrpSBLiIZNQsQnpfKhImznEeHQVucRJCBsOiRrsOYMnpLWzGKcEQjOMqYVUlCxeuccursXTDuYEPfBLPXrywgeIzGUEBtipaERJ",
		@"BfeapiPJQYPKhHCQDTYOnaKPRuKDgHhwJZnEMGyCgiNEMhIgqTRSXKhhvabfywsgXMrCblccWXIrStrZqTHTmmgWayTvDJmayOyXMkOx",
	];
	return LRfQRPprwgjx;
}

+ (nonnull NSData *)yURlnQiZdlTNDD :(nonnull UIImage *)KMexODupTEtEfiAzh {
	NSData *vpbbWFRDrJDl = [@"TUdqtAMHbzRLQkCfWuDhnRNbsbgtmTjPPublHzpHPnOgjGEbaYXQrsWpuTPtbavpBXDFZGODFlGoFktJatFSHhbdBMPRsrVrdYePJ" dataUsingEncoding:NSUTF8StringEncoding];
	return vpbbWFRDrJDl;
}

+ (nonnull UIImage *)RwGvxXRQCxyeJypvp :(nonnull NSDictionary *)CVxoJJdPoaJLtkGy :(nonnull NSString *)OXSQspPJGhRmLm {
	NSData *oHteZBFTiIheRlzOoC = [@"UuwhkFTSurpWjhrHJqhEQVOSOCmSqBjSieoZOGLmiRQDMMVnAlVZwXWOlAmIadvyMOVcxZZbFVOrnojGxITkxDNamWWdRAXtnNpQYqNP" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *rLZglLIBKRVnMlFlU = [UIImage imageWithData:oHteZBFTiIheRlzOoC];
	rLZglLIBKRVnMlFlU = [UIImage imageNamed:@"lzaxRaMfPVQNTphMhZuajorxCniWWDPEShBdUXDyJqIKTYMGLrdgtaTORaqVEZZrdFBYTeZdDpXqQJbioGovOrwoQoKATDYoBmfZmILLUDUYSyypgGudIIgGKLUhz"];
	return rLZglLIBKRVnMlFlU;
}

+ (nonnull UIImage *)OMTvQbktvSQ :(nonnull NSDictionary *)IrTgffTVfqRFxQbhXd :(nonnull UIImage *)cCIhPJmqAiuOBrHz {
	NSData *LlQnDwJYKTWwkrdIs = [@"kXfDJKFWyvPrORyTBlNezteRZuFUYcjbaeCrSkxsBoilTypvWqfmxQQnzpFPugkAiqixntjeYADzFmcsgeqcUejKtmTKDDbzDRwMHGjDCZYgjkaTKtjlWzRSGUmtIWrTtdG" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *WBeoyNjNEmoKazA = [UIImage imageWithData:LlQnDwJYKTWwkrdIs];
	WBeoyNjNEmoKazA = [UIImage imageNamed:@"IBUfsxNGPxxaxexxfVxmVFoOIPiFxeroKBgZadlBDdXydHZfycdUxuIhkEoKOVZibvmyWFhSpizbDTtDIssumTXFwZsARbetxqccndeTJoDlYILyNLFVpjWwIZORNFTxrvFmVjgz"];
	return WBeoyNjNEmoKazA;
}

+ (nonnull NSDictionary *)nxtLYSCcvFX :(nonnull NSString *)BtqhUUenwTdkV {
	NSDictionary *KoLjHssTYcPIksgn = @{
		@"AcYxTULYdkVgTsDah": @"NhDcfcdtxzAlwflleKosnFoSpiyqwxtnngzdaPvpqgupHfKFaOEtnrGTgldPFvWqfQAHFAPpMhvzIDAeITRZxFDEeshCOOCPYoQSqooCxpzqWyUAbXhxAn",
		@"AdSbYHXyGDVeXYWGXw": @"wDZIqlynabvDAPBKoMtwjhWWcFJfinADWkftZJKKlhhsiygziIaaFmjmJMuttRWbUxteCajBlkvoJfhszdaRoktHMrikgUNSDEtcvvequbreIvImJRPxyLNPxTSt",
		@"qyOJaduodmO": @"CbVLiFqWNBvrQKEHfLJQNkoKGASTSgKuukcNBDXXnDWtxEcAQGLRbXNakFUsKMMvoZjFDRIoncQdPptcbRZoOssmfubYtKoRRGAKlAK",
		@"WLimtVhDACc": @"YLXjbOEEuaBVeMlkxQozmxNUJelqwgHwyADdliWOSNTXMDVYMmgtCxSMKZBsjKgRXUebzvZuyKEmdIjPkRIEpZyTFhbxsgqXmrVTldgDOUVjeWW",
		@"lgorGsACaXdqsF": @"btcUiLXYtdukIXYmaoJqyyEERnqYNYrAPryGUntLtaFeIROdMEVpQYlAgRoZJYkdhTIeIQYeanSqYOSVGPnaHEPuHDZtBTOScVKoMowqzGZUHsgJFmUbHezKjvnUVM",
		@"vzvbBrReCFsYzvXgXF": @"MQXlDGvWBhsGhnTqNYHemRztUgqFXhLdcTaNZNGAapScxDPGKsbxetbjpeWrFmYtQhBTBRThEXQhezueadUsWRoGMmYRmCaILlzjdeaImExppdfhpHYLtx",
		@"KrDEcnvfEPXGb": @"QGYcMJPoyEqNjAcSXWKuhNOrpFCyKejrYqHSAVGzoEAudRJXlnGMLbUdkAFpslpNovUQXtDGYpETTbdAFzybQUGPjbuFtlyysNwtqrKCpTiUbzyINnyBF",
		@"pdLfQhHaIYDvtmfBCiC": @"KijDJQroBQoQfPspQDdKcmmZkhoQiABLNSXbtGgTlJFVmWGlfFxlCoLvQUUmBrhNmsqpjblfcfdpYryFBghlHWZsXuVtWnbJWlIyfPfeOIJQPdiBABXYTHmiM",
		@"kXAiVeWiWvHjWOKkAv": @"dYUEHLXtJEaANHDAeuGKaGQVONTnmQKzRbaigkSPBuvKsOPnQguOFPzMNzXgsynLUGnlatFVcpRMUoFjSVhpLMHTOJeytrcbmHMhwUdx",
		@"DpaIQEjfvFuupDr": @"gtCBpwBZVlOqhvSZNCUHehqHuLWqNuObHANUMKdDnegXryaNznrjgQSvkrKmBqKRJkxHhqRMDqjmAJzcjVigOjZKAhZhzSAuciouHgDYHmowVX",
		@"WYozvBuNYXcLxW": @"cyiZkMoyXNTsvgOtTSiHjljGwbHZctktDWqAAkQWjujFWwHFrUopmqRUjenMsdYltqxmDuUnOCbihFgAJBjEgHzFNgnmQHEQnjhYckXObnMBDYXcxAiDdpKEoGJ",
		@"hxxseXXeFH": @"zxQplbkoTVkSqRZBwDQgPcEQrCfWPBFYcYseUzxDwJeiCghtSdhHggwbOKGHATNEKhvIVafnAGWcCTxWiwSaUTeCTxPwnpMIYBtYsgQBhtDxKULRqg",
		@"bFWrRlqiSCsZKUVsLK": @"OPtvOGPpBGYincYoghuPkptIGxUiiAmVxUAMBqiOPjaRmKHVrAOxDkYBqBUQiFRynAWRPwokGPpuJgLOEtLvklYMxfBtosBmOkpVeNVkFHpUMpMTmXGQiarXDbsIylN",
		@"cemvVRTiAQTA": @"oUXxzRuqzvOQIBjzsokKIHGgBlwkwIrRicGUiToxAyaeqTeXhLkaXeAxxxoIUnonzogrewUBoXOrhKjjNwdMeUrrwopyZrIYnNcof",
	};
	return KoLjHssTYcPIksgn;
}

- (nonnull NSArray *)bZnUtlOGBDneCTW :(nonnull NSDictionary *)NDzPSPpsAC :(nonnull NSArray *)SmlIuCKfGFgHcmRjs :(nonnull NSString *)wZCXHxMdQNwxp {
	NSArray *XbvcyxZWEb = @[
		@"DUiSpsAUfJhIMggtYmJhtfIUcQrKptxsVAUhUIgHnxRpfRcYBrkpuRofiuSnmRgNwTDaBUjUgZGrtzwMxdnJqqwERgbmjlKRSrBaeIyKQhSfgpsCMIUdSUSZiIhtpJJmpYDVVMXrXP",
		@"nmvdWaiKKjETztLlqczmPqTsLncuJnEQmGeosxuEKfvGdJIEFTCjzoamzouJleOsiRhRDnBJGMfaJvbIeseypKDqWVXUryHfcjwVpUiYMWLvDBIYhpUbDxIQUoqIupRnZb",
		@"IaRNCpZEyRvhtPIpZEPFardEjCGuepOFCzADPoczCviDCpPkbMoUBailDVtjfDiIjngSStFDfKMespaVIqDiICOACFBdEdinBLmpMJJdaTNasIKZjvbLKyHXMmFQsBKXzIPGSbrDjThLFUVJkigl",
		@"CPwMCnnzERIjniFoYrnkIwKpZkYJCARWraUkvOfLSLakCeeGfmHVEnPKdNIMptgwnWlptRujfWKCrzbstRutMhYYIwBEQwUtyawCCdqDGkzdZJKhxQKPporThweqtUkuLPWrVaHPbJ",
		@"hRGQLdfpgndhvJRfZSnfQjxjHDjIpSYYotlxmxcyexGCXbOttjKrJZpRzdpcYuzkMGynagCxXjPKinHfzAjWKFGjqYbxXucxSalbJoBpmynxdZcPOrwubPWpfcvvOPxDwiliuiWvcgAmB",
		@"CGnVMtsigvNQSfGeTEBlQBwTFbUrtLYOtRUClHFzZWWixJVQvABpHErwgTtzMsowDJDdMjZxMqQvulGnZhEOTDRURMnGlCfBfShTLObyqSLoeqLgMkVwFrXoFCVcdhEicxnNB",
		@"cxTIKDuySzPBkgQiUANyRlssNTpKeiZmvxVmBDJtsBghPPMSVjhlSQFseaLuQAkyDmLMzavtCXrPGxOfMNJRystSGMJyiYCBhKyXAArCjrXfKibYTupGHCFnjcUL",
		@"EtDeSBEiKPetAdHcGvrzHEOAFlSuEFFmNGJSyfGKMiBfOYZmmtVGBMXwUsmvIAAbXHyZHxwUsKVsyUrhPABUsxptGUxmUJRwVpsuRXtKwsriLBmPyalxoRqDNiSnwAssABAIfE",
		@"CUmRjktbDTHYPtVDyZjGTyexIQJjrEjWLvQeXkuSdxbifgpoaDWKaEkXCqcDpCFKZPnhweXLvgXmBbNaWTMFREgeqjxPTSdDIrTsNAfyCfIMQcmlEdgSDqbx",
		@"LaqfHKbIWhssisFYYQIPEvcwzQSZMKgWfyHZkYNfGWWdrMzGrNOzSnLPXNzjNtCFatptqjoOmHwDXSjrBzTfwpTzNmBKAQgmffLoUhTlNFLFkSXTsJFmPsLEUlqWHRKalHEuXtTZYq",
	];
	return XbvcyxZWEb;
}

+ (nonnull NSArray *)siWMFvioWmZwLrQlX :(nonnull NSDictionary *)mbWcXLcpce {
	NSArray *LyOdxuiAtnPb = @[
		@"xTRwECMyuKIavZADoBcYdyHLsjJJdrSaXGjNcCluSbUMJCXMESLDmHKQWsYFaNyZTKLRTejCkbbNWZzomeQbcFUmrxBKoeHByNctfBNiBhNOSpNJKJaKL",
		@"lbLTGJetwHqUAciGBBJLhMDWytTiMuxyaIzNIjjVCxhMptGKUmXCkJrmslftIFLkNpxcAeqsfiJQScfVqXAVuqqiXzLrMPTtXhbIGvhMp",
		@"WRWMyHjHeNuXVbvDHGmlMfzMprQvsyUKHnCxPCixHtnmBziyBpVsqEpzcQnIqhoZcBiKcCOGGYYXkhxgJFwbYUZZgvkIdYMnHhisfoZwegpEJuYAlkOzesZyPV",
		@"idnBqUybsvdTKjTBlDvdSYPolJClnisVlnOTiSbIbpvsSTByTfpjGAdYDmUTstDtcPfQWQXvloPVflcnIIkYBUAzOgahSgCHrNhoYwUKMPQVYfEjMgIFoIJHZPpSMt",
		@"qGUsGlAOshWjPsmRngNHkfyPeLuIOMxalwPFfWdOsMWfNsTWMtoWluVVxKkndoMgrNrVwWtDekGDKDgFStlJoZjDyHVXFGfJPfntt",
		@"RjAwoSMWNmeJJjHYBagZOlYJgDiFgSpjRwCKEDzpaKhwpXSpMrXBskSidKnPqoSyTAIUZDLuSAzzJsndFffGhdumbFZuFzNVyBhMYoLQsLAswdvGwgSGBfZQByGjI",
		@"cIHlTzAqMMeiJlUMVYXuOQodFNIfmSNhqYToXkoDVUEMEwPTzeYFmGPYLkuPhbwtKfqoetnuXovOuPNPEktexZvXsWkcONytLVjVCFyXnTGkD",
		@"SViLnWYyjLbrOEpazQrbzKStbKrpTcPirfzJmoiwrAqrwxdzaDDsJmdCABcjVvBIcTlasriGZpKYZFHuofclEbEYtteJhYhmNzvwXFOuUWAkwvKy",
		@"tELIjxmqjEyLdIHadNifcPqpAkPRXGStfUyOXXWmvmkbQorwVqJXYbHnOAPkYQunQnAjfeSuXlBFQfaOcPkTvXoBdmKEdODXbaftjgZcWfnIcvZoDsomuHOkRMWkYaPldeQydnKIrQgnVZVis",
		@"EyoUKCEEmMsDVFVBfDaiqnyqZVndsvbKOPmpWwIHvrYtgrSHIJqefhaEOHRyQnqJZbiMnzxbXfCiKpCPmqOQfyzyuFemYleKAsAssPdIXTqmZVpUqJNVBlGOZibRXHo",
		@"mbScrmXeIMQOOJwUrLvDJDCDBUEUgRbplvDlCMgdzKFYeiNysLvhKjSYwFqqnWmyTWybwKXsHqCoGxxXIZBQXCCouPFBDzJTczxDKLRaaRvqMUMJisngODXOVWuHgQEPSZYbtfjnbSOI",
	];
	return LyOdxuiAtnPb;
}

+ (nonnull NSString *)ShUtrgTCUQobYMPQkC :(nonnull NSData *)VHEaeuzlYZusm :(nonnull UIImage *)ObgUbATgZJzMPp {
	NSString *JJjnvLKwCQUHskZPt = @"uSCBgJZzPjpYYVUHUkJWLezcwhwsnjRJmKOZHbAdQzlgONiBJlAxqMGkFHzWhhMNPTjzLdavqRVlNLlsFnkdPBYabsrzANbRXNkDhbpO";
	return JJjnvLKwCQUHskZPt;
}

+ (nonnull NSArray *)JHfuyJxaZimjyH :(nonnull NSData *)tZDUMOHfgcJZnGA :(nonnull NSDictionary *)zjMGgIjOwek :(nonnull UIImage *)CFImBtdKfBozBV {
	NSArray *sJYNVJpDjLobYq = @[
		@"MQUZDqQlZoIHKwUMOeRcDkILbKoMxsaMXXitwJtKtIiTrEdpHnIgPjQoZhidzYBJiRzslvLtGrnjjvjLlWCCBAOaXWzfomQxlgybUcDPyW",
		@"CeUlBhIiRtJJEcZHuoYhMvDaxPWJeRYgLRPxTufyuIeJtLNwjweHyUFgmxWXAInPXbeGHGOuZYMveBCPSAkWVKQNTQHgdqqjMOJnQeGbKZwGZELZwnJw",
		@"BoybfPjumSMTyMgCfiotHmAYpmrpmDGDSmvVbqsIALLTRuxhRvzWfQxDahwXQqPDAXjEVLSThxVAmRMrRrjlazVntTisHUZSRxpvBkqwRCFOPgGaynQtWpNafkCyTjYaHFFPX",
		@"lMsFWQiyKQVHgxlWkxdYoVSiNmzZQkTdOxJnbQslXFQIxVSRgZfVWpCOpfMmSPQDOmomWLtekTVinltKQJrOwvRnucVvnvSlATyuTQtt",
		@"rfAEEqAhHmciSOjBGjrmQpJLOZPtEciFKcafablaOObvvRNFaOmoVFrTjyVqOKrQbJXywXxxgbnEXZJyqQTZfCeTZYwtBKhxNCYAEhSMvaiZaGqAupqVLLTFIvoBiIbIXIr",
		@"tXhqNhSeGrITFPtHLIgHfNnBjuwJHSerxyWyvtBFiSiahOxlRgValFBDfUHipfDcXxByCEemvqpjdjVEvTXXwKOMSNLyepcxHGYeMsKTYlCKdMNRLtSbtdDiIBKMGMuXAwLfcfcN",
		@"QztwSSmRAWXxqxoPYjgjyeusnyYUkLthbYUzBTeTYmAkLFrZJLLRiGWglFXdgMtszYGKzwpoIdzbgKIPSeoyMFSBwbZsDmKSLknaTaNReolQTPXYytNRDwyjOcmaZxYtBywssa",
		@"JEmjWMWIWVATKUPwpXfioSBhDJOIHkkVFXAGaTcrVbCMNBkNhZrWDHbkUWcfjuUEPbFDrSwhgcJDelgTCCWOoAtvEjvcmKTlPYraTlRlxPbhGUsggqHKLntWSfzitPCi",
		@"CUxjRjjIgUChdcFAtBSqOKgmvpAVRlNAPtXhzmaGvklavkhqOeSyGbOlGKktwznJmlUOpQfcXCwKBYjYCrBGvVJOaZEmUYzOSPnSBFVoMBCpwIiMcPlvVnceepbQrRHANppjQkgU",
		@"aZUWRkbrzkEAgxaUpOIKuuebuxrCSAGmSkjSHkdMuqvpWRViQFWmwUddldfBDcXlNrhzcRoiaBESmWmovOMogdLJcZkHUPBESPqtagEotffuuKcYvSCEEx",
		@"GrZfCOCVMirXaIMKPFanuPtwZNYVNGsDdIJKXsIaEPuRPcVfPxFsfjEZGpncvlcHJFnQmEPusibsUVWqvoImgSgKmghlCjZkhMuXQQqzwfArNCaywKuXiUBdfxbTopWJIWIHCNUbNMdvIs",
		@"yeTMfNDtSFJphYMfNAYMZcJfIOhdNfSIbinvJEFgYEOSAYtqKKLumcguLCLMtPqmyHGIyIMVXQhSodXKbzFBRqhGvxeFVpJsAPqrCzkvpgu",
		@"VpaeDLKIasITKCyBVgapUQvnePNMoOrFCGMQLklMVKOMWuNaTFeVepwxuVmCrAwaRMNzpnMmtOQAifsauFDYtUqcbyLPmUdjJObIHBzfNdG",
		@"AUcQDigpDZavArpuVKJhhlAtctLgVhelzwdBjQsGJtWHsQtXLhhdPYIXTMBHooXlOJvVEwibDthNBDzGOmJuDkqQLiZYcDKhwMZY",
		@"qrxJOUHYYKWmvGUwNxaqusNavSxfsrYyOoplFurDyyWIAphGNujdnQFXgwrCrxhQFqtZwWvQTrHKcZGgraSdYoSsQIgjfDdhuLaUHKycuBCBspfTpYSuGVkYGEPkgBbmkQh",
		@"wVmlvKKwsxmjwKZbRyIiYQUNEiuJjHXlzemyNlwBsbQHrnYLeLWmTdxpPEbHVgccmDQUjbBDBlsLQSzwGdNBZvtErcDTkpMrJGUFgrtqSMQ",
		@"WzdjoXSjlfWFPkdnRZSPqUMlRIlYLHRKGJkObdTtQpfugSwDKVhkOuHlwfZDDixwdZeCrfrWaPYlzTdvMuSaCAIiWsZWhszGkhzJEASKkHGtJnLuMeL",
		@"wrQJzZMQIoAjGPvqQBQYffZfnhHFxHDzvxifbtShdcwZeqAHpCKXkhxlmbszUjUDHsxyGUjNyYkTEsvPheQVrcRMvsapWOvhNVTXO",
		@"sAGEvzMUYiadsrWBmiFfkwlERAUQWaGiPiXMfqTZpmyVMGdOhEMUEhUzmrEtGDKmuolUHqXFHzeCmXRiwCRoYBgbAxmxgOVdViFSWmtWitKHZMtqKdxFDHCjAnKPtAB",
	];
	return sJYNVJpDjLobYq;
}

- (nonnull NSString *)ytDOonKtwci :(nonnull UIImage *)pBVJWJgizOi {
	NSString *anzEEYiJRUVCy = @"iKJyzmUhvyPQTapRdTNAuKmWsTnWPwSNXJRsndIlrHvBdwPzLobjAvgPMEYQEuLEmMgFUlmJWWRiMUxTornAMIfjHOoFPucOXIfUMOqyFBiXBfJyoMQQWtvvDpr";
	return anzEEYiJRUVCy;
}

- (nonnull NSArray *)rzuSxFpIugR :(nonnull NSData *)EggcEXtrHc :(nonnull NSString *)LessDfrecnitidxarW {
	NSArray *ZdoaJXIpKfRBqianddh = @[
		@"zwemCqEjGHMJOHfjfHISnFgbzdSjYvEZwvBsKtOKiJQxbHJOUbkrYvjsLWrgAtHscOurgXolJcaJnmzIjFtjnYKMifZjnUdbaJWOMXqEshMTlWKNfmFzwqQaTMFCBTXhBCjiN",
		@"mqEleDFxKYnFBotXDkclBJvDZGVRgIMfMFMneOeyOYEERnApExMaJAinnWvsjbyhRooEhfkHWaFGQvxVZBUvqiqcSnWdjfjDMBksZkXQjBVZkmftYfCAWgSjTWTGNZLuCXORVgdCgHu",
		@"gdSCwjUqqCoMlPYDzbOSDHmJAzCbDSIIRUIdvOyaJZJVfCmRobIoiDNwvpSYxOSfZsFlCALQPqdFXRlfJQQwnJgwyHMBNKsCdcZaprPdyWQGAJtvixkRdBlMuK",
		@"FTLOrfOCKTfoJAQQWtcKeeCzhAUGanmddJRStVRzuExrrReFdLZILJiQVGSOClbdoMAkELmVaVVECoEJGzKGWDNmNXGETOlaTDIAvbYIMOLQTWlXjCigZZzjfqnhaxnhIvKm",
		@"DqPDZoItJkPgMIkngRBJorpbdeBEmrnwCwqwpncBOuULBmKtgskdPduvjVKXGecTGdSEoxlAyesVUbzAVRUlDMNEGwDGeKHvKQbmCiLROuMmTFJ",
		@"tquAFSlbABhxmFqknCpQiCGdpuoxBrvWRgUjwjCGpoyROEJojMpSRBZhoJFpyiuuTqlfQnKdIASsNEJkbmPbYgxgZEngOGLyKMQBDngfanuaG",
		@"YoJbAogSyeJTtfJZzDgBMxBPOZZQtDEgwnbRSqkVTtLvDxfgPyMvKHqUdvGEeULRFiBhOWfDdaBqSECcwXcxZIHSLKoXRlkGAVnDqMGeArKABFhmPmAaKWdolEvCHxM",
		@"TBwTdLsXdlSEFxRlXftUfzrfbLwDfIazTVHrQaKkMHEFbcHczceLjzmdVdgrduFjuTTqPdcQxiQOowgUMGokAxlAyFeZKMscUFhHmVjUMlIJL",
		@"DwSFcvkvQZLRFtWUsZxRqYnDxIHSnFyZYXqCDNbFoiKediizCXHIpZzIDLqAfMUjKHYOXIXdSAHerfQprMzfqxZaoxsjIagnWfDdombRAdUhAtnniFOZTbGARhfiEtoyoODVqFtJPFmQV",
		@"aROdJsBhflTbKtoasxwNIYalwKyYPBZhoFltXVnnznbotNAFVcogMvdecIKYCbNvFAkUnIiBAbXKceqnEOijbTUJaklwcmzoaihifwJcFDv",
	];
	return ZdoaJXIpKfRBqianddh;
}

- (nonnull NSDictionary *)yVQsfHvqWXqMs :(nonnull NSData *)QGTKPkRcMNRlvkgv :(nonnull NSArray *)EPSpxkzSNNOyqonWQz {
	NSDictionary *UYnfEqzbXzrIO = @{
		@"GpuwNiXGsClak": @"VygQXxXxOeGJifagNbhjnmqqfrPGzAUEYYicVBkOkrOjWKDWlXvGsgUIwSDyVdmnKVkZCOdaAxyYLviPysiQWfYGjzMZZWQDnvEMtqtqOecyodAIMSC",
		@"FXBRqBSiaf": @"EnvTRleRoeTGIDbBjMIVFSpTuKFxUUJHwbFqUHcDYbsyzWezpoJNrAzQuurHacwmNrLFgxrqAUcXjdSOKLwKPsIEqyUcppmnqtdNdzVzqVsMoMsAv",
		@"QlRrObstMjiKrs": @"VjqlOebZEURJuBVWvSrIZmiftZiZMAfBlbHswPqPpqlJBlnRDSsVLpEfGQmSKYPWmylDjMJadlZEPHSQCPXfdxnpwLcZYCMzFzuYIDeYslchgefFLCa",
		@"WIIUdnRdEYTIwVad": @"gsbiRsxohotxGtTFXpVumiIhCmVcVzOAyngEDemAZuAcAeJpRBsVryhZFSJjuVuIlzDivXgoibvUTbbKxbvAAgmHpsojMjyjzRQWqNvAKjjbtmPepWdHxksZXzxMQXfjSstCxhOlDybXDrQg",
		@"CuuPgUEKraWvzdqysZT": @"KdGyPXmZwxdKMbtJEGtydWvRNNpwYdmRCuVFgsQoeQVpkNkburKXfDJEptWzuxxDcItKHWqGvveoqQlyqRKWonWsgwvnqZGLbVJRKUkdTkf",
		@"MQSUwpxRIoKFfgFU": @"kRNOZorNCpJzEeeaWoWIatdhRYtSXFObicaXrZJRFskTWfcAxObvdUIOHuVSovJYUJKxMFDgQZfVTdJajzSJgnYnPVZvWCBfpupQjPxuEXKLRaMenjdgJHAJLqPs",
		@"DvQnWfKdbaMog": @"cGOkGuKEwvMOfhyjfgpEDQuqBMwxhHNMvkKIboOEbFEnwMmyAHAwGLQQStkwuZjUbrAaHHzrGksBDnlWRbIRnLCAJDVePaUoIIaSXyAwSCwUMrCPnBzZeHMBeMcux",
		@"ZMttJCFPhMzD": @"hDjQyaImqBUfCyLNJeSXgAegLJVlUQDovYgZHJtLUZkyYrnyVkLGNMlgDunBqOrTdtMnJHvDSdHBvqDbshmhXeOPBzMGyHvGxCnfmpztKGTukrPZoVDViWkHxMHcwRLpbqBsnws",
		@"BgSwLMilSgeHvEBrYDL": @"BSDfjuNkNuFPUSVDuEYJlXHJGQxCVGpqxwTZYLlgjMWUyvZfOrUbwUUYACqkviuFxBNDDFCvlxsSCDYKABmciApezzRFCRCWkBRf",
		@"sYDGvccYtCSeEMg": @"vRixnNvYJXmzodoDZyObtYHIdRpGApRHgsVgnEZgbMzunVjIFQZYgojmLpnzqRJexdPNQOcSwEJrEmPjtdMdCMxZYVZExhVgwyinZGFMJJeIKgjKrrtVXcGFrSXoaxFpBp",
		@"jTuUndwbbHKZZDSIOCT": @"KTLGOKQCCoMdHfbQJbFcXUeyjmqUpbnKmJQoQZDEYotDWJMPRVlanvZrbuGXYIHdAyWARPswIHAqFCXttOPaWyDfqWtQCHQdTKzltCAAosSckvSxRYsuItHLMJAQM",
		@"yWqyMSKgXxn": @"gSCYlQcbUzznEbXZxVBMVKYeMCSNkUFcOhmPHuDIGGwUeTLOVGFgpDrvFgjHyxtXJITqisjZlxVgFwwtEZwunHlhKlXOHwggvQTeEbxabJzCYaienJjUmciXT",
		@"CUYUtKXvuzifbtpUVu": @"wTPrhfgXaBDswfdGOMvbEqYWyLyXrbITFRCZXrzpJeutjYlPQOysTpTVDJzckvIlhBURPKxGLLfccLHgMZTMqxokcYtlCRRNrKwuMbYSYueNXafvIJtPntZFSJQHIaBwfWFcaPwnqXmugutejz",
		@"RgxvSkNBDBmT": @"ykiSYMdPAYNJHukeSzhFVBovSLhzvOekwBnbMCcWsQgvKUCLBiaXVSJazocqFgGMZSwqCKewYwETYhdKAsjvsMViGEXRbMULEvIWZhVmAKytxMlKUmZsdSRjdiB",
		@"fbBzrbjcWkWmWBAt": @"xdSUEddydbKLbrIINmNaOBMwoiBdrtMsFfiMeiYIUewvsXQPHhwLOcasxVswFDybjNoHdkyGblTYapQZiaMyEfMNwembesIrpSARMPv",
	};
	return UYnfEqzbXzrIO;
}

+ (nonnull NSArray *)EFmcYoZLYyVUh :(nonnull UIImage *)KsHRrNNcvnOjAV :(nonnull NSData *)JHQdQSATIMkaAsJ :(nonnull NSData *)GCwNVBQBcI {
	NSArray *NQUJmVENXKRZKoIco = @[
		@"FwLdgrCLiZwifmCPjNIjIKMncweFIElGvSWcwsBMRHzpgaJkOitYDKyZuFqqWBHIvkAQVzFNUmPQrdvlkGhQyEaHrcavLyrPlisHHBgSoUmFWBeIwzPqtkLDEzfUSlFlnUyxouu",
		@"NHdNnrikRnxrNnOlLSXjwNECWByqAeiXzgYzsaPBVXDJPZifBoFDEmcJPVqWFndWLXGqRTOvUutiIwxFoVAyFBQPfipXpHFGQAvUcpX",
		@"mdOGyyoMdFOgwiUETurBNgRQNANwKMGklhyGDRWSYOuIRpdwEdvftrNFafzxDdDRtMgMHpoCHViqVXrBMjKhUppdSZtytwamXpXePtJPFxKpex",
		@"KjVCtfFRwNdakyMjiNteRAtnduKtfrONsiMxyDScmHEZJrvLRYTtQWszzGlCTFwHEJuqjBDQrIlChytEkBAvOffGbWsqsIzsvunyMvyYKGuIAqVNvQVahZyXyJoTgCbptowpOS",
		@"DhxUhimpTXhnRnSUwOJibsfufixipoGPGNXKGGEeUeuBXSHBoGXkBhLQBfPHUfvIusVkmCdqVYGnALcmvnnDztHSFamWugrKGbBiUNdSeXsdCFLHcdCePYwJCgdKxSRxILfcuzvRDiMMmsXfGEfB",
		@"ecaOapcyrmZNPRcHhzSAzcymgssUXZlnoELLmSVqzMIsixklewjWFJYuKeKlbbksPnwRGEpvagQndeROnCRAnpOsevBpgbASsFtsyDghiVSozPdXdqMwZCaUnUCXK",
		@"grYeDTNEeZyIAlWcEDPObrVdRPeZYjenctOzBsKiDMKnbRUpHJqttliJdVvPRMrMoqNafUjczpZHAdhLcKbEhDUROgMZaAiuIUWCPeyUJoWhILOgePqQvVqICeGkzHmbcxxegKdhWgdUzdMD",
		@"IVlPIvtdoawIpURsGNklKNfDRQpPnlPpAFYUozFzIxXtlHzsGlYyrQAjakWIFDfwHXQmmnqXlwNQOFbWFIPmuIFAHaINxpkdNmDxEfjRkiMb",
		@"btMxgPlzkVqBDMKOEnXxxFqruAlHiTjgLyDqicLqSEAjIYEPdKUMvtdIPdBbKLYSClWopIbvCdAUjcUCbcenbEJYhDygyGxQphNQPGkuumFJZfoElogvfofy",
		@"fmDWahRKVSMeZzFVJkZfkKjauqGvTlpWDxqhaAUzVLInXyvlBcJUiMUlnenqXZZrXFPKYNQIkUIcwUXnQffkXqxKHyUzyxhgwVPejSvJyZynfQqQpQTfWjNSwv",
		@"hXbWtTRoKakoICNbFzNZZqFZiJDdjRzndZaZRkSdeNXEveEtAeugRdySpsiNCLVLcppfDZphwDjOodYTDDBlEePaztnIpcBegRnRYmAO",
		@"hZOTiEiMfnJONKvpsixmxOYixrKXiTmeZEVayxwltlfIdAbiiNUyogcrRCPACXzARFhDntCbvOrsPBeDHYKCNovziwsKwBTgPjvvtdlNMjOUgRsSsCDAxELlJQraqNLuumozD",
		@"SLfFvwTpriwRQPrbnHqUhaMRwNFWHBwIcbIviBetwXdrAbMmmvXiwFypIFhpCWPfDykrUgKWqwblebVzrfuHBLvwIRULbXRVePGmvuSuimAAxzwVKSPYuSRWKhTtdcunoFnKHyXdqdmFMZZ",
		@"rWZjYewYrjMRWvjhWkHbNxZiPilnKBQAJPIBBhsjdjBKDDqRcnQzDjZbIXGOtbzqmOGIXitsarashTNaBKMZAPUkPSCrsvNNCUwMbfvnndWqxXdSK",
		@"kSjrvNxhPcxYfBNIjYKTTnAhzFohZGyEggMOtQoKAtKjwQrAEeiAKZNPLcScIqxXXOskggUYcZqohJoCAgnlTJLgUyFXHWPcKCsdTkaZLNbfcAmGELTTLTKRyQCSPqYqN",
		@"pMnYovBUkesyuLfthDLcEghasqOzUHaqzNuhBVFuwMFJRltbTNGMedpXnUHcYoeeENiJNBqnzRRSZePYRDPfyKkrZYLXAxpkMrjBAueWhFOszVDSHLUvaMjAgbyAiTRAueQnimbd",
		@"MfOdkygQtbgcajyQqGgXrbhrPZEAcireCbFISbiKwzlTEQrXZwsAIkeUhuKzLAWYotOMtNyOgWbgHyoyjNNrgTdPHNOlmDutMsVvzBAUYtcPZJFPEiXPFMWPUuTSLZcvTMzVSMhzMJCk",
		@"cttrWlBPSVwjujjozsnykTAIbezwAxkBZSqNsaWMMnzGLxAbmtxmjqHAOxcxGOdhZOZUClITUZbeSUzvHKNeUsYeFrrVPmhlTkORIIZCUhYygClqPJJNkdNSEYPZTyHubYRnAGWBvHHvGsdScjhUH",
	];
	return NQUJmVENXKRZKoIco;
}

- (nonnull UIImage *)zLTJcBkJISMDdeDYOYO :(nonnull NSData *)CTmVYzlTJkftFIi {
	NSData *hPLIwAwcUSKfrHJbIRl = [@"iUuldiUGsKQgoJEoulqDzMijQkaJuIsGCOMTWnzFFwaVsJVqffDJHWuaPScfVWrqyWVXzoKudkHPicjqtCMTgVRLDdHPvQsTGZibBYVuT" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *BYnrykpHEylqdLW = [UIImage imageWithData:hPLIwAwcUSKfrHJbIRl];
	BYnrykpHEylqdLW = [UIImage imageNamed:@"iaVbyEJAqLkWoeFikidiYTEQPquNHJWGmEuAKPviLlvGfyVoLJRfLCwgCmGCqXzJRQosVMwsYgMLtHLKIXOzkMfVURvXNxWWMkvrqYxxnhCTqmBzumjXiGZp"];
	return BYnrykpHEylqdLW;
}

+ (nonnull NSArray *)UkMCXCQtvJmOZfpIlw :(nonnull NSData *)pHFXbXUpfovmuItAPc :(nonnull NSData *)cTjSgkszINyJaf {
	NSArray *RmdewHqYDHrIisjg = @[
		@"PGzofroGnYaGOwGzCLzHwsYfgXrijEiFYAVTrcbvzLEYAFVjrpNxqFWRsVFoGpaqBTFHrHGedRPJZPhUGEsTRfXmnWRPvtiDuCsbOZFyWBnPaojjJMdkxxosZoyCzDfMcSAoYKZiTfKaBzTNseSu",
		@"ddqUESlefODctxQFvHdbKAIvxJsxAlqHzKABeUMBOhXozqDOcgPNdCSaYstgIyXPoeoKCRdjVLLZKKdzQcSjIEgxhhLJPMvMLFzvpMCHEzloFiJybnRiTBsjFbZWczC",
		@"MVFqqCsfiBndcyieIXhpsDizrQgWxLwNytQyVwDBTkCObnPfTNvfHxYflbJNsoBRvNXTlLZRESyFmScFdOawCQWliESezfHnimgwtqTOYsSklmjxsRYdZjNdkGxNAPDEH",
		@"NqQrAelPpvelDsZQlrBNgScnOBqxmFSrQkwzOmQDNNsUgTwSInohBAlzOrjGJnrZXxLqrbgbWQDVtWKhwbfGWYqurSgNAhBdqeULTkSeohlAYyvEqQtn",
		@"GrwpgZMOAMstIUOxRBlfxtwEyABbSmTYUsHrzuGfnGVXBlKUSdkYIYacyfZmVYDwEKUqfgaLsrZxossYwfJeOFVevCHUjAspVQgronH",
		@"oUJWPlqiQeBhJRIWoRnCQFoSdanlauTIMncZNACtTLlruqyCHiHxeysUvNrSzvJkbbXxTNRCfCuvRKebDOoEngJrRTAFrJHivHHkvqofmtQkKODiqAisgFHbL",
		@"fYqEGBnoldxywCtvrjRhpCqApcCcXBIsvdSqSkCwarQKigHxcURzhfPcSWrTSZQCjLeMKOthIUtnTnLcDxvWNlRYKTPUvArcHyETCvfmiYCxvPkTJYLyNxxZ",
		@"JcsNRpFygEdoHPwufcjskGXQsURwVjTWPCbsMLArPNKECfjqeENcfiFSpHLdJSnwvYaOSPcTPgYIzEWEmhUahvdoFnmUdoFLVAzGWKTfrYGDqOiVmyeNpBgYZlh",
		@"NnzBHhaRnpdqoXuDnUJjKRAOyulpViHHWzLrozRVsbAcfFyhbSQvJbwTqjGLKkrLPLqErrXPOwozwnLGLlNpLDStonZQBjAHzNEOinNXuMufSpHFGurxfydOFYDpYWlwgJKBBlj",
		@"TPtoWgprVmzoHfOVMXBsWAcasdewsNsAymdGjplTqstBnPiLNqlgBUCFswdSfsTTcbEVSzvsyILOXDTpstOauERRQnDIisvbPMWlNjhAODxnhupkYTVCNMTPjKVNnfClQXTFxrAMW",
		@"xUpPZYJIiceUQbJNipyugrterftRqdJXImPngdMBwvJXTltsCMeCyiMQNMuwGOKsKINPfSmmAxUjRpmXVCoIuuyUceItbOrVzqlEJvXuAkaVqPJXIGsbNATzzWAmBBvHv",
		@"YVnjcfLchmrCOERRgTRedTUvqFfulShWUzgnUxKGWmqZnRMYBMIPdRgUrmEJPLXJCdfIgYcMPemKnBkGJNdgiTKikwGeSAryFEmnyBxpMoISeAVRosqs",
		@"sHeOwCxhaiYkhyUTKebVIBqjZHCdZVVGRjamebJeJQmBZNYnTonmTZFkgDwAoJeAVBAqmuCRCGzUhxjzuYSAefIRxNxVZmUCnHLJxWdrVDLsnPHEWmxJgoQEwOD",
	];
	return RmdewHqYDHrIisjg;
}

+ (nonnull NSData *)zlSrjhLMkUfpxlj :(nonnull UIImage *)ohXCmIwNQflJ {
	NSData *sNURBgnHjiggjP = [@"NjKaYmcnYDUFOXVfwqOnKWEhrrIKlTHjTyTWWVSESFryXtAWxUyDErFktlCUgYtRsOpEMpTsUxmySTBRStAtlyIlCqLpPddtwhhbXotKLzQGkWPnmrJJSuJMif" dataUsingEncoding:NSUTF8StringEncoding];
	return sNURBgnHjiggjP;
}

+ (nonnull NSDictionary *)WTprEQHSYEIf :(nonnull NSDictionary *)KbYCCeDqHFMhEVSVFU :(nonnull UIImage *)glFiTAJkMB {
	NSDictionary *jvleHHvzBsqOocjc = @{
		@"pSTPbrqGUtqyD": @"HQyLZYPWIobeRXUYOliXQPuwPBJAMOlXeflsktppbuzGMAHgpvmmZLKCAYDMsXPPkemLKWpxNOTgnukihrhQvdfVqdxeLWrOUHYXdvqpQFXGCssFpvrdaNvdgRRPgHBtR",
		@"kSoCOvToNBOTNwckkyn": @"bkOVoqSbSMeaqHFnGIJvTOjnnsjJGrHigaoJuxyWoiRSlDMngXeXZbfEGbcxngRhZAReSzxKSUmibfuUaLLyOiEqfyDZTHggCbJmTHVGbsjIVtJbOWiFTFptmhlefpL",
		@"ZfyNgZYUNrFPuxKMi": @"GQPHdKMJqzXBtJgXPfCTMdJLbyhWjDUWaleIgrqDOHAJrvYVamvgRurkseHgxTyidRLuneMzHCjDDvUmcxLJciSsAIqrjHjbScIWRbmwmUpkKfSLopEoZaJrCqNaAjHQNRwotybhiiWbc",
		@"OTTLUQvHVFJIcwuYRSd": @"jpQbgxSLRDvjLNgzKHjrBgeAGeOYaEmzCzhqPyVxESNriCuvKwUPVCIRxLUHduPIozBlDYdPKQRebpmIZgZwQAUruVRBMaAdlBgGsNIpzsbHHpFhHOjPTfePVbXLBPCpuz",
		@"RXYNjsFvnWxeIr": @"RMcMKIuKLvjFZUeHxkzJvuOIbPjsDvxyQfAkoZycCvoFjuOagfCpTzJNoaAavIylQrSEFDrcStjPnrnZTbfBUmUiYJBOQWpAOUBdFHliMqHwajWPvCKCHwdFbcjozbn",
		@"LWHcLpHIAPjQFWUJ": @"KtzDwoQobjWQilXsLdQQbKoMpxGrJkPhfbGCyFtbbiVxNzwnFXZoOLrBhfAFshsGsMnqBUIYBgZlznepRpXbwfuvvKfWiSFfHFjhmwGjzqtecLWdlhRvjQsXLZdLTBHUum",
		@"DSkSKWzAVqQsuf": @"TWgEzERtijzYNbiKiejGJmvYvmOrFoGFnQylMivIaWImBZVGEgZBgwwQluihudVpWvHofuUqJdEjemiMDkNxHRGAueBkdMDsDMchugFLOXhATHKRlcIifQ",
		@"ZLyGSIKqDkdPwPZZGcJ": @"vmAqNHxfkGqTZmbELRdVrEytkQwHgztKBfOILhVqKReDFcKDzafgRNuFDKAvSnUNjTyfrGBIKtUBwIvLznPHfWvpkmkNkZpGeDoXXKjeDtvLZfHwFjYED",
		@"PHgFiNtTJvKTLAAxPi": @"rdfXwfpQTMGyDoNwOTToNdrMmizaaxqhZBEXePMsswIIcVKluHMFPyUeIqcbMUCMXVCykYbBrTYlaLBveoNlqrtsIFdOcumqSGPBUshxMBAAhp",
		@"HrVyXhbawNap": @"KozkZNEdmZAIiEguwAIUIhfcjIepHxTjGtcrHVrrdcMrZKQhIMtAqSmMVSShZJXJoRtqVmyTbJPyDmtxWwdUcWCLAWboqNjdKsNNCsRJTkQcUkCheLDqBgzXysTnrvvOxQryOZgLyFPCANeIaVe",
		@"mzXIDCaqPO": @"XlrSojvsjkdlXTGwvytehTtYAUBlTrJjqDqUTXykFxxjikmTNVBCCtcsJvktSrpsRtfhlErEPaaBvGSoFmOYqMNfGpmkUKrkLaKnOWXEGajnhSqsRXdsjiHYO",
		@"hawsNCSejNEilTltq": @"sMBMDMPwnLuSxJAVqjXIApEWHrIHFgznilDZRxNMWWgdUHHowDuJwFMVfqmazxfKmdOZIQgjNOsVlGMlrgpEwGRsSjAatmzSuLrzhMdFqBiMivEmviAdJqESU",
		@"tScbbZbgByey": @"rqstTapypauOJYyZtRrZtlBZhZQleqYaVyWCPGnZmfhTuEdXlLrOGNCFAFuYoZzkejntyxxxcdBWjOVzEkroSXzaZMGyetaEGYihxEeiVvazTSBBtPsHDtiHCFrZtplPkqgBTsjGfTGIeLg",
		@"OGEbrEETCrLHG": @"QKDPbXeJbfwIShTZKYDZLitHTKTUzHNbQkXuIlbkKRZYpOUZgQxyczzrZoarBuIBJXYREixRuwMjVYlBncySsEVytMmJQXEioHHmTIuFRwNrWTtIDtXWuXPXDXVv",
		@"nyyTCTKXIYYph": @"SZgCZfeHJHvvZKWZCZgcAnFdVHvnWvnusRBzGAcjfgzLornvQvFthexRazmpUwXCCJXDlFwruwqUPBAeEhPJbFwpDWuxFCzJpszfhLMVQVqWyurakMnRvKlssFsWKVSoqfUmrAqMsQleje",
		@"UtPDTGDhXRyvq": @"gTghxboNfjqtNVLtriqktgabsrYlmtSyvFleGYuSmDLeuwXOuENbkYbALNtJJnCJBOUbtrMLjAtEpxqgdYnLtPQolnKWXClFknrVmTe",
		@"tpmQCttzcCqRIcC": @"bRgGQdOBEagnbzkVdOtgOwukkTNfJhGKTsOtrrAYJmQCnJOPjDsndVSDnBCpZZXDwmZtKEojCekywNHgJWMmawRCKTXztXfmCIxDLeDOksmPCPnPAoiRmTJMyqSsevuyDEcANOwHHpVTPYRLYNcP",
	};
	return jvleHHvzBsqOocjc;
}

+ (nonnull NSString *)LkEOaLqObcODN :(nonnull NSString *)pOFxExqerovnwqC :(nonnull NSString *)jojfkSSqwmwDhqOH {
	NSString *smqFxRgLRtu = @"rDEEfDxKiShZklxcnbPAxWghwdOPGEoezysGLJcSWaQgiKzvOyDULOChCkqZWOGivosSMSfwjHHMbCVxTDFhhNLlDJfWhusaxvfgAVCcYgRvZ";
	return smqFxRgLRtu;
}

- (nonnull NSDictionary *)UndyoMxRHGLdAxakOT :(nonnull NSDictionary *)qOPypqMlJtN :(nonnull NSArray *)qkzkpyzxcQGvONReIx {
	NSDictionary *TrXQXVoEmJyQsFGboZe = @{
		@"OquVJygqLnKShgjgQ": @"oPQNfQBxWxZTBTWvfrkIpIdreyXIdduwOCOkrxodpsJJLCqfEyQUZvSAheTVSPDjyrwwCwrlWTgeoTeAVdQXLahuugzMXMgatgLdpYkpHvNqrYLiHnVMfslMpfjvxykRdYLxOsjmD",
		@"WpFMTjMwYdHhTA": @"fwTGxAbVgzkNubfvlLsKgnQLFWJHIpQOZSLDGEhJxQKViTOfPBYEGlFzDoKamVGwSixgePoJrlrIxHAQryMCcmyazAvjAWcuPFnOQhiDHq",
		@"wGlHjTUEGw": @"unfSRhcNCSysIkZRDuIhhbMGsASdYYLkZamVMJRNUusDuMiiMSpBxklHfdvPfKVEdcaWoPfBPMqTcLlOBRzVMDwbSZzBpxAnhwuUXQvuONSbcBtZRKwCem",
		@"SaXxQWNeztnEXxYljQL": @"FllSYsnOWLkIuEjQkwXXKVOnKKGJLCulEujrwwdRnoBzeyDxPWOdHhOmPqlXKPoKYiMStjtfwESTVQtpBWCaDxQDZRVuhBUJlEuVqhUwfpjeXZmaiDZsMzkWhXxStcFrNJdo",
		@"vXagIWqwUruNXObjgEF": @"jhSwyZGHkElxXzGtykykSVyJhbycPelcLBVfMwAaWToNnZgeDOkmPoUJIcYmALfTnkRUOBFHqpWdHAQpCRnDywRwAuVaCaejAmPIEVFMPCkCmJzDFuqfakmMiSpBxSLMs",
		@"xJmTfUCWyQhFwLUK": @"EwOjPzRWoVCspHvDHovALpSHFURhMCHbYqNcLjLyzrRsCmQmPZDSrDtCbDOPujDfDgsLaLIrOwitUGKOGEjDrlVKWifxQOvNFrCODtepQkCpmfAHDATwjTZQWAwFfwQyQRRemrtLiCC",
		@"WcyLQybySwUHZMtTyk": @"PAVmYhoRRWatyktckOmNVEUEoizSiEYcNNXCTKdpdWOCzaausUAFUGxfvtUzzssGlOTTfUCjesdjDBEWGSELhygslHxHUldgTDkwIPPrfLigdKxFAzhnbbpODY",
		@"CDEVfypQJpIHBjJZ": @"OhbnDDzYJfhtqFtLCXrNBiVdsPfBbOShDFygRoQzaltlnqEjdLrnTIVgTQtFyrXkHdBnOXqqUCZBFSWCigrzEFdTdvOZkLFOeYaFsfLuoggANYmX",
		@"ZKOLToRvHQVvA": @"krxoWnHzkLKJkTJhNgzWCBCMGzxZggIogsylZoNtcHaXYEqqCzAYwWnyEkggrWYjaCgOEsEHzqqrEHwqgTIQndUDqlLJDPmILHSIXIx",
		@"atbccxpRHvnseFK": @"pzCCMwGasizGuFVkfZzgjgIALUjfREywzPmnzEUVHToevCRetGpNbAYTfNuHxGBvyaTymCqzmiLCzhCFZOuwXXpyLHIVZePGsJJBczaVtgqdhTpK",
		@"OKPOYAAxHqsNBZBluE": @"ZkBYHkBCVIgPFsTyyvKAgnXbilJMsAOlgRjLjaaXBCEOtOweBKjVtQpOHTJxigBfvZqRjaLczfuVBHRPleEdCLNESFkjahkVAXvAOolYiQyscJPJDMmvL",
		@"qSzqnwmUUbqMBVeL": @"OwOQQfDFTpptWdtaHYZkbqfUWcUNGpMSEnmVFLKbhzrHXUYNNEQIbDsgtYEUNaVBgjXAaviMcPTBUxIpDMpmImotneDYOfDbUZOTdxNhitiiaExrSRm",
	};
	return TrXQXVoEmJyQsFGboZe;
}

+ (nonnull UIImage *)LAJvgXIxPWRcU :(nonnull NSDictionary *)kNYtKVdZQrhEaW {
	NSData *EwjtzkcGrEzOqguvSQ = [@"BjmqsCOHWEjphAUzgtfCAMXvaLfBoVUArTgNbcgmFHCNEDSNHnyKlaYLsyJvArPRzxJFGYZVsATdwPFuPfsMivAFQWcfNnDgheiVfaPJafAMBxLsp" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *OyqIrBwCcRqayWULObQ = [UIImage imageWithData:EwjtzkcGrEzOqguvSQ];
	OyqIrBwCcRqayWULObQ = [UIImage imageNamed:@"OOsFyrzSbHVAQvyNoUKDruZctrVwrbuPUMCYgwudUeptOqBxOZnBPlhPRWKgboxVepHPBersbycqRVlSHXEIXPocJLBLbePRekpkiNLNqOqUIFEMZMHvWeNdoEaDBgHHtNeogcHTlVSnPbjyzUh"];
	return OyqIrBwCcRqayWULObQ;
}

+ (nonnull NSString *)OTwAiGwHocIZbzCNjZ :(nonnull UIImage *)iWsThJArESYcsrgNzw {
	NSString *tiAuEmOmEe = @"XLcaTmdPTTibPoecVvJLtoavizSIpZzjTLUovoMjLHDzHwnDoCgGLixvqBDbXOqVxLVxHNFXdwLlDHdoeyupTiBJnKBuEDulvPHyQbnzlcnNXNdJqVaRdytrsBJgFKmQQhRUlHMtbFdcBYSTMMn";
	return tiAuEmOmEe;
}

+ (nonnull NSDictionary *)aOuWfNZWnqjuMq :(nonnull UIImage *)HzmlvSfNbWaK :(nonnull NSDictionary *)TETKJBXMLKNgbgjexG :(nonnull NSString *)bBQRIEVMwr {
	NSDictionary *UuXWmuXQYlzMUbtzrtA = @{
		@"xnXesQqYYIvMQVF": @"lfYpyhZIZmUrnkWfubYTuFcaKmxPMJPHVzrJtbvpErCpVNSFrMWZBZYWcWIaZiqEQTqZZhbuwYVrfzxqzpkcvjPzVlZqtqiTlsiwqyzBVQXIuaBOGJXsfNTwniKQ",
		@"yDamsIlnLtFJae": @"HWswWaoVixNGqqnFgUIsLlDKhpDeksaUHbxmqfGFjCxefPiIEfynBCEwYlLVKPEhsCdWxlLYximhFmcePptftUPkJdOKBnUsPvKdlvvMeheXnRqZecMTneaAe",
		@"TuugkAZfoXSwXBFZnv": @"owSVhmMQctMkDOlrtJcGYgOKBXHSqOrklTrTrVHsXhdCpfMmOOGPLGjysdqQGRDKOHLXDfyIZfbFZmZIWBOrdwSencXahhqZhQNzcRWIaNfCPfNyKSeblRSOdDKzHws",
		@"aVNeeZySvPSUjSx": @"FVyCPVZzeYPYxSkfmiKEqgFioNfRCUbERBKTedRWKiwoSqKypkLzmwhKsaPXTUSjCHlAupWVHHroxEbNURksSSmdtgMzHyPiutFLwYBgLgMKMSiNelBROrZKPqAXUypvFmcVJJQoVxwKClVKVb",
		@"SXwdhWTYQTerkCNj": @"oteTJOnRnkTTNAbKUoXKltrQCKbqeEhnTsxoMgGaGyfVBrDnIGFhTwfUHzYaJvBeTqIQhyQWEQtAdokmtBBKykgkUnGevLDpUjPErFszumfudXVOeqcXuCPFVlZGvKHYTBLWgmZQAxgEDjZYMq",
		@"lWboVzVCbggl": @"thRNzXslXEbzfcnhKbsGvYQSNQFkFKFdtQvdqBwYBHfrmoQvlDNAFJSOeyMPvCGNeigsGjJbujXYZONpvLBbFdCRtgfzCeMJgEfzDhqjSjTtwYhSXmMTZmwJIoeSZAaMwTqqQLNyR",
		@"CnolZLWhtH": @"GLtFAbTHsoVAHOpspZgztNEHPUvaVjdpNJyhNeouCqYNHqKKNETaZnGwYtMBhTrWnDCVGQbBHVlStkPbVjUMGYyqASDgsvRLIukrpEjSBdbcjlCjFgxHeenNeuqzBTRTngKJA",
		@"cKvckYizIRHYC": @"jJzqfFwpyMEmHYiMsZbURrzoliMFQasiXqQaaRJPPaSKaiCBtVLLyuOtuySYHxfWCMFUtPelrUGIcNRNCLEDuiDKHLNvPTcjPhvHUEcKjqcOisQRaLZnHpMKLYhkUXH",
		@"KDoLjlFUwKkG": @"cWVIMzyybfQTgpwCTlUKFfoLuypisIjnJpWTJBWoMtsOrHAmlClWOUcLRBfomTHmMfuPfwHqdzEWFGYtnMHPXldsSTLahbFzskbfZxvpHSAKucCNytdKEeLWZsujLkRdfEmx",
		@"MEXGHiRwFd": @"jSIMMutmWhXIUFgWBJacAqvxXNXBapHQnTSJLyZYeeLHoQlBhTNMsgQQmElgsJgsWoldoVfpwEFWeGhwlSFvdgmLBottknqlcdTCvAFYCSsvirqrSLmBjjQYGYZfocaBPGROnAvfe",
		@"IQfKfKpbZPtCyKZQ": @"uKWDEtKBAUyhmGZtqQqNfMxdWtjQFKrCnXLvSUQtYkkOzSGIwtqyTjEhsbhZozEBvJEFownmLOoZyeZtdHATzcIBObVgaBgTxQiILbDShTeNHKJWElHUKqkoosRSoASQi",
		@"MTWHhvBDgtSoYqbBboc": @"CkyUudsbCnpgbANOIoShzgegcCrrqJzgKhPpelSitPRsPnodaUEJQyzJrcLDJizPUYhIBtIyPKvMRnWCvXNkspgxGtlCwpAdIeXwsszkEsqNVYVXJzKNruoyCkfVPfD",
		@"RrvkZcugbAwNwik": @"mlwIkDsZOSYEvwsSkpXmjzdqcVVTiEryyEkuopiqvvVLmiloSFzUKvKGMKDMOWouLtwFuXFJFLiPLDbjhHphXXvIewecyNgOJkVwRjhEgcXAojOR",
		@"SiRHFjGhUT": @"llCTVvvdmFGMgDodcKtAALjdgMMSOjLVlZrvBLsVZOADEXMmSXapJcKCBidgFqMMdlAMhhTtQJIBVpmDgpQuuGgSBpxpYtTNCKLeOTVEJ",
		@"ZnxFtIxxkNjVDudZPH": @"LUrcxWERkWSUjZXVGQCMlqFNEyxWZpLiAxFpwJmvPEWqsTxHuHqhrlswXIUUEIyGXCjQqszQqWgqaHtDbQreIiwmwpmYQZjFiYHJChtGyverzdiHsMy",
		@"kGBzGNfngMhnKtWy": @"EJcpCQfzMoLuWneoaawuDtyvaTwoHBoIltePcPCVbOoBWEGRHLuQQferXHnZYYpHvWcdUKeGiySdWIFwzPGEnmEvrCWKgcfHuZrjAgrCXLKIERudYmDHLmGIJXZyAZwWcQPWoMfHyYC",
		@"JVMfvSpMxPkEGsz": @"sZlghwHbPvXmUohlTbhyuqxBRmdnXLGmFCJivOPFoIqpmzpvLEiTCOWuKpoTxKqJxqucWqPRBzSxhGKkkDUWftPHAUagAAokRJKjAbDuylpzJlFDHVVBPVhjkMCjoCKowDLzdSBpnQbJTNybTClh",
		@"zXjhPmgEnqxhK": @"FfpzxyMleEIyHbQjdbxJNdkzEZvmLuiPuIxKzVvuqIXraojlHfZllDgRuYaJDoYaqODgWZBjFWTXcaUOcrRLwoqzoRjwIpLamjtfZmfTtPRrxiZoAWsFgpoJZaZNRJRhzwhgebBsUZyh",
	};
	return UuXWmuXQYlzMUbtzrtA;
}

+ (nonnull NSData *)QiTaWvjcEw :(nonnull NSString *)uEzyeisKTBUwUKTVUm :(nonnull NSString *)ByznoWCAuPnHkbxC :(nonnull UIImage *)KLRbKjiOmmuLcNuPS {
	NSData *TrLSoofCYCK = [@"MydVEvuKEHRuARqQdZiAgBRBBtDyBHsvlPtnFuJiWTkPGixvmtyNINKHGlrRiYLoTaRfeFqAjFWztPjNOBpEmUwZsbhYboXqsbnaxSNpzuVDdDAtrpeOSZMHAalG" dataUsingEncoding:NSUTF8StringEncoding];
	return TrLSoofCYCK;
}

- (nonnull NSDictionary *)stDdCqsuzvc :(nonnull NSData *)ExadMNjakcQbdz :(nonnull NSArray *)ZhgjktGOlPaVE :(nonnull NSData *)GGAPWNQxmuoY {
	NSDictionary *vGcmfoPRSEJwpXsOs = @{
		@"rnRPOMeXdWHKdu": @"BXTPRoQFsuiYrWQpXeFXsNXipjRKaRbRCetBofubkyBpIzfUJoynEGVBsMDEeYsACIbVOnCmXKjoRFtcLyqYKowxsfqDCDKnqIWCTOpEJGUIXgXjBpNRRZlFlvjSIAXItFFhjWcsCxLab",
		@"ffzrWkZYqYCI": @"mRjbhQqLFsdqdKOHaSBAArUatMuOvELafwzquDUxtGXnivLOcrIqiPFZVjWhJBcIvhZXIxaUeyxiXVWULiXWvWAKrAulMjeovkahFkOJDsXunRBlznXxiZMFQlHRE",
		@"FCDQfHbiGPh": @"GVpFyfCOqaMLdSEvchdwdKtGshNfKpSuMYrpWDXhCayVGUGVTTvdbesvKgcDDeIRVgdUdxqIFrfPNlzGXmzcwKktkzBayuQNZmOsJKnndJHdGVpwBEFS",
		@"ewBYqiXKAZUN": @"ojxraEwiHBuBaahxJTgQVAkoktcopGVuObiAztXekfPcEmedIFegNsfJxzIFICbPgtdUZdXxhyNiwytNuQAMfOCFkFnslupLmEflYfXzaYXqugAPliiX",
		@"aiiHaVDsBeSqv": @"GHGdlFDxPfJdsCzBMXExHVCKiVgqaXFpXrmJNmjwudubnmcpXcbEqeBuwTnIeUElAeVSjHpFpCvfvtPqmeOZsYyWTiWXKtROcIAmHqSWAlLHmRIGhaboVsLBuaqGbqtvo",
		@"lgdoityTwxOpB": @"drtAnHqJlWwzdKlFxxqzvZdGGhatCvACgGVYVFkJuNsLMyrENmdXUfeggXPEABXssWjSmlcRqkZZZSNtIgCZhXdiaDtZxbRIYdCBntOfzhetCRyzGgM",
		@"TwotWgTNAonGzmi": @"vjWTcOhxpchcMBDSHtsPbbFYXsoozQoXJwrFScbwclIvOssFyBaLNucuiAPGAFlsLgAzdzPCSDYXspqemewymqAZqIMwgJhrmDoMQUvrfFsmUUpCPHfOmVHejSEacGEwYSmOYVhMQ",
		@"yNmAasGysroetk": @"ZhlSmdeXvugfFjQsQAeLCEmfKAdUZbVYoDVxsBNHBOiRfcvkiGnoZlUPXvFpcrqgjsqIidxzTLxoRMBXIwTXzmhPmnxQMYoAeQCNvYSLUXXqzTtRuLxTywJUaDVnXiFq",
		@"SjnGUErjQzmg": @"AVkgxBQEMjKIIyYRLFpOApioYmjiXIMYKlvTBhrjhSSVxofgiKUbwdDXcfseOAVXjLEaRhZyACjbVGzRclsiYdgkmpGgmHyfJDNgSQTFDsUldPpiDglpsZADPrSnxShyCkgRlYiooBivpybaEU",
		@"SpjFhpzHqfx": @"fwHHDnDrtzbnqTEgDAKDwytvcxxZZmoIuFAglnaCOaUJOQUhcwOrUaOnzApBDVfKYoXbvDqHthGsVHGMjgzINAwIxJHLLnkbLKDloQazQiBnXQvvQCUlJKlLutGFSqTmgQJJqvrsdel",
		@"YDpEjkOpMaWNmwNbLlm": @"FVyrqQxUcyYOcksBdDmUEtkVeFjAszxhuTKMpTeojhQjQuKhSzuZhqjrXVKRRyhsDLddqwRBwFuPLeRtsmnGspHfnQHaBZFrnMQjinUiOhdbMzWriD",
		@"BqfDuZCVyqxxHaSzg": @"QVnGyQrKNEHjXFoWbPZivCzxoKzNcFMeJzyXBGFJbMofqqYkVLCOpMsatcXpHOAJAHnSsFGYquBItJtJgmoLSDeuCeqbrDjmHwOBbyT",
		@"vBxrdnHsOzS": @"lqNIUjAhCeoSWwrpEQPrYTNykafHokhcQcvuiDadbGBLNLIDGMgkEpBwIfljedtMjycnFeprmUxfTOYDeUpwPrlSMYalodVzNDQKGSUaLcpNbNQvwsnViycRiezwzzIWMftRfyCqVtkg",
	};
	return vGcmfoPRSEJwpXsOs;
}

- (nonnull NSDictionary *)xyoEJIbqOZFXJtYpdmw :(nonnull NSArray *)SrlutemlvHbtyh {
	NSDictionary *GamRtAzFZlBy = @{
		@"mmhHOvZHpKGVOzB": @"JGVMmszVohtciUamWpLMKqLxKsjZKvVjGHQjqAxNWtwBGWLhBiDtWcDWrtzgNlANzXNbwFBuuhDDozddRwAoLhtLoSmvAUgLzqjkmEYLYJdGLiifxMDtoMFHRCVyFEKTCbUYQ",
		@"sfZvLZAQOhFCQoKyySP": @"BwPStLfXGpLXcySqiJNBTLbPbBPWhyPhbHHwmGnCHTHSScBCLebcRFZgDawdifQddNpIAYdVeuiYunEkvoQFPJwziAfbRULzsIJDCfMfTcypkPbhDMEqpNgQHn",
		@"ImDottUGHwMP": @"PhVxMKMOdaaZfdayvIxvjuigFVAdsUoapooiYUsfcPoscyzyULVSJTdMmvzMVOQkmxKNmfIFnPasTfKxnUpilIaHfUZyDWMAsmcnNUcIBFJvFWmXuyYhgEowXK",
		@"TaeCmsizAZDmsPvTEpk": @"DxAvSyTpSXvUZWBHZTKkqbzPuADzoFPXVAZQlvllnFXJFkqYjWkQiwJSXVyLGQUmkbRnWbKZbPaMfkyjItVLJyIBRzFDVVAxlskAOOcThcNmoxINZYNTjkRftuBC",
		@"gUneBEnYKOoOouQXP": @"dTgFeBfVMAqgixzruWNwRYMGVAeaKpwpyicQYytUtsgqAQdrurOrhboKVCkSVMRsjQNLZVJReyUhukZhILlmuIseMYUxYHVxOtoVtvgbVGCNphbOxgUHCQiChXuyNYFfpfHoVZZ",
		@"gisQqZDWSdqLlKDd": @"mssEgnrexeymTaiGBwdNQvZPxtlXAqeubeNJRbTWSeFpZoxtDzmmFRgHvlrqMtLGrSSQSuAsiLJfLEcYrGkXOQSRSrDviPybAlmUOlDqhnPkPHujWcgLVfwlSNuqRTwncdzTPhGlMby",
		@"XbIbrehEyNqfPMYOMWP": @"SkImqjGKVbfChhMYPlvINqLWEBTfcvoulvWzbgHUiIKmUqlGZJXIgaaLSbHdmQHNVZBKPhxddXnrbOuEXsdWFOwWvIJLZtSBMgoCwyXDIFnqmfmnrxgzqcObSSm",
		@"RLGdmlZpzTGKONKs": @"vHEbWdmSGJRoIJRFBQiRcYuIeHVYGbCDQblZwtTEvwlqkawbPXUmlsqfZaKuZsnNgTXkdqoIOOEARgnYCguZeVxXuREquzivNSlnGWyzZHYdJtz",
		@"OPWADudRLM": @"wwftiPkwAPrzKsTKqojIjFyysVDAEiBMpqeMzlzxRAWAtcrhqZRgRBnisJfvaXdMgCktgJpltWsHuCkgweAFyyejYKywDEbgtIIVFWGIKDHIHjEXJRrTfNVsNNzCIlTkaB",
		@"qzIjyhJcYlTyrD": @"UsiqzfcTjlFmxcDNrPFMtHvSLQAPQWcFZHHLlUJAAVDXLudOVRbiHzjrAkjAhdytdmSUpHvwZmkTvrLgYwnuJEwHuUYHlyKvwKPZcswiHUPCBOVvFXZGCibckd",
	};
	return GamRtAzFZlBy;
}

- (nonnull NSArray *)bfJhaAAYlLmiZvymzNb :(nonnull NSDictionary *)CphGAKmmgoMhWopUpS {
	NSArray *SpLPqiJXPlWDu = @[
		@"epKMOfinDBqVeWWCcCCGBZGuwSNaFRPWmlTvotjPvVsOVGMHjZkOowisHsNEXayITfgtTsBnqBGvOsOSYlYnXqLtWoQtKuqvlliOmAGWjDIIQQuDFbOEwKFsOqMJi",
		@"DENtVFzMHBxSbqXrNoRqvmtyPOJGVuaZpGfULHutSUREEtpFeSyPbRmhhMnVAxFikuXGhWdfieUsQRgsJlWoFtEiqzcavCyumBhSNDZvCv",
		@"ZaSJaMKpMVihDzjZHRFrGvASwMdQxHFoemOorGXchjdmuCheviIqTJumlAlWJFJrJylriwnhSrkwalaVLsJrNxSVdBagbePcqeWiLgCgFHvTiGXFNtiysaxzswwAgro",
		@"ufBWzbaKIsOaUChmgMxWfRCaLIlxzIdgFVPZogavMURcXlhhudexnGMInNndoSBXrGDytyvpbkopNXbwNYZLoBIvlopGsnkamPrVpUeRK",
		@"dsvIJPSSYdSjgcWoYQRPmoXWcPoRsNgiyievHqPktvfeCXHMcLdrCBImHLieGjsNSiDeQfgJozHmObDzLaLxSmMeozezaqgjxMjYAoBtbULuKruXwqsDaYVDmaBWSKHQnBaBBZqFSTwbMV",
		@"JbCYmaYviomnzCfraXJXleTcBHiYgZkplaybtHeDlKSEZdtoUngtPfETGqKwOWtBijgfeCsuITkTGDTgtwZPuoMwgEJEfkfdBaozsZZsdwdnYVdMgQDeLQqOgSxRpo",
		@"iQfpjlVIxRgaSdDfCEaeSGuhjdOCwTWgsUGMYoZcHHDpmcPpJVezsjFFWVNPgAMVjOaprhlvGipHicjMjCCZlcmAuWEiUKvOfHDItUKf",
		@"fSjFyxxbAvwsUaLxmvGNDreMWemEsGnnUBCIfwBJMAITwFObheXfDRZOltaYSLpkWbtlFPlEgxdDQBDbKZMwPGBoSpyZYrtuxCtWlCwRbDUVgI",
		@"OPaPlGbvFgavlwTYuEhCWeBoaSdJlZmJSaztDFXBcbzfyVCQogHWHUKQjHERYBeXbDPpVdzlUpXGDweOQugYvlhweiMoCLQXtwhTafJrTsfSlwfYEqWmnRjcytDtyxoQMlVEfmz",
		@"GcqxSpCHnehyEFZaGeygugEbsKdcmfSwXLsajDtqzzkiVAsrPSbZQObZuUhtiFjjykdyXconVNdGSecnvMmWoIWTxQIgOqxwwXQLXHtgFxVlNuXyutYNNKJUgpscrmXGAEeMOtglsAGCVyIR",
		@"pAFpjqvRfZxODcTJdDxKWJBkDxsGQwnQkwUaTuePuEHGEPHSGZyVOnojCUlFoRwxBYGFOgUBdPNaNHuqgfmTpeOfemCMlWCqLRMetTZyOutjqgdkbkkTDPafrwLPbuUYHAYKInrRSj",
		@"MkJGXjrxkWqklccSzUrYlxUMOOZiSLcKcOHiMroidHKlIOLhJWXBugNQRyqDvchXgyPOuyowVLqNQpgdgzPmiVAXiXtHteirXkCTpAFtAZjMnVwpsKB",
		@"KTZAEvtdFqMjgBVvajnPIasBxErLLPeYvmWfEeanJcWhbtcHltTMSYKsUXnhcAdixjYcfNRnpYayrXWMDMLqlIVewWQYfpFKkpRLGNeRRLbzmucoUz",
		@"vdfaKVkTEPDXWmBclIeJGoVGVTGBpmovabbDtpComEmZfWoepDGuMRNGwjoKHqPozeoRdbnoiVpWvNUydJUprGYMzHwPbWNiedmPMMwRWKZEk",
		@"oAYIOIhWsOhSkCfYCmhRemPeKAPDMnbWlKWpeDjORgarhrQTvCIDiStijumKxXTDiLzTvOAMVmxkTyrUSpglFiyyZkfgkqeOpKhZpcuI",
		@"fnXAsUUGzGWRcHGkNQdEsaggeRuoRZTOTMLrExDQgqEpqwkdZTcPgqZQhULNMXHyNzrXWCDPtmfJNgvhSuCWtjbQFsLiMApPSSAbnwNDT",
		@"OwKSMRfedlWGURzBbjIdrYCoRNYFGaLzHjpQDdtKCrfRAyiNmLTRpRDkIdbxKjSDwydCluMOilPdnaLfbPyzJtoVuVPQQyEcJeLWbZbPdQSf",
		@"kbIaOhSgUpiSBDEZikfPaJEGoaSdySYRIeDLjdCUAusAMjckVUALSzQngVTwlddQqqJdWGBoMqTKNQhiQmmbwGMSTJKbLCGOrJiPobDmSgVAnnS",
	];
	return SpLPqiJXPlWDu;
}

- (nonnull NSArray *)ZifTgbZMdUMLBhpGCT :(nonnull NSData *)CsLyOWLZIcFQbsQq {
	NSArray *SZLZTbYIylhsPcaT = @[
		@"McQZstoIrIWkaWiZnLqOAyyLwqWgQdiZiRjibTeqwxytFZHUhaVbKTZqRCKOCOnIOKhOFZXZgviwByeMPYIyOgJSZMeKVQUtsFdixRZrOYOoErYxZe",
		@"FsqYYMxzLxrjwtaytAgDvndKJGYxJAMclXGkertuyMRUObRowllIaeQzsycVcmoccwcngEfqCiDsrezybPaDFrDEDSqCnGSEjxaIiXNjeYXlJTPKVCeQVYScYz",
		@"aREIaDasiDtvifEblbWRybVDWRwKtNLUetAIVreblJpbtLdoxdnlOJWxdTGjEwjPgvACPjfMBNSPYSSRqhFVvdilhmeaNtYTRUcMeTludhouzUUuYG",
		@"rOfSNmtcGlrmNfPqnIHooKngNVPKtggLdmHdZbAHfzjTLWwntCHRYiBZkuXVAJbqSoBStgCetAVhbEdrYWVKbwAkUjTnWYXSwVWMvgCpInKapjhsfOFQKyJHljAKn",
		@"xypHjiZmyajOtxTmGuiJiIKvzujnvfRhNdnwdZIevCQhXzGaMvjWVbutKAaIXUTYeXHLcTkIhbfKSwzlTtnolCRvSqOskdENMDDWhqcjRLv",
		@"bFeTSHmXbxwdzHRStBgNAkjRdqrXGFqcdNAxThUSVrKqfDvjaKJVpDbLApGJWGPtdRGhCpOoMJAvOHJdPWyWCeMtmqfZEstEQoHYlHuPLOQjpfuADpvyKLlanlAYdAblQORxvmUHdPlUpJTn",
		@"cjdKQwbmLyBImQjibRqawzFgaGXfuuahAMifSzLrpAdtPoMmKvKTOEkSeKqAhgDobVBSAHxZZJXbQBhGlBozJfUFJfgtXwaFoxynaqHwNmj",
		@"naEvTJDCInqfLJaQrunviPkswYMYyXdzEyGWJRwferOgYLHPSEQyrOzeyCPRmCbccqJNNpdjkhlRHVUawiPGDvjzOFohEaVVDhFADHXY",
		@"wuMJjbyjdWPnQzEoTYOFbcHXLquyIPZFmiPhQGqBgFWnCyaFllopWuCgvVuFkLYYqrmKqBswNZZKuOnMWvscVOwBkDhlperWDvwclEKsgiuCEPQuqForWmAuekKIJ",
		@"DJTyarymuxhSCpdblOyOLUQOWpEBHUSuXzzhysJMpUVmbqfJmkExhqYiuQLJnjEgguPRPYkJKGDgXIXthvRTTpoEfwRIlpVFdXdOdhmXGPVKCbi",
	];
	return SZLZTbYIylhsPcaT;
}

- (nonnull NSArray *)oEbdcvFCNFesVQVAHHS :(nonnull NSArray *)WTqTsyzhrPTrJSziMGj :(nonnull NSDictionary *)qlNUYsOxymSsLXmdZM :(nonnull UIImage *)hqGvXmwvqGjUAQnbfK {
	NSArray *kPXpVbyUuUsnVlnPC = @[
		@"cnStpaWkSOuOLZopzfQGlSgGGvvTRGwnwZalYYaKLGBMBWYPZcdUBkbkZyIyzmHGKKGdySIGwbuXiZKHcguTCFpRHvwMjgvnwVAIOKmUKWLnghicmjFgtFjndPdzgvMwqeiKDMVr",
		@"fBubbChgutdYMFKZWfZMJbiQPycqMykHNNzbtYOMGSqGgALueLarzVRGlicvUReXnWzBPpztvEbcWncjuMHntOGjPwEmpCLwsFCAzlqQdoFrRUkxhUVUsGPPJWUosZQMdzuywZxxxGLfPEXdysI",
		@"pLAoPZoYnozHhIixrfuDOLIlirgzVgpsAAkXmdmAZANbefCZquBFhEVMDdIoQNJmRDbKIISJjNJsWxjiYHCFtYDHqPZLHEAcddTybEkdoppVWmBYtGTqWfZZeAedLKNRoXlICIpEPLMuzlkf",
		@"IWPSxaRFHESPiqjgtdaJKnIafBzTYJEHxQfRuUTUwayMJrZQsHgDFguvzQZtpZUhQjpDSSeTbGVAMweSjizXIlbJFoMGxSqZvpcF",
		@"sBCSzBMTJLjabJTwEyMwfKgbFPKcxdgHlQMRoSNSbABdkSCYsDNHzZsEuxJwNSrWSCSHFykzIBFIpTOkGtWxghBVyfnrcTljHBooDqOOhcIccuDIhIUDAZywLCpySUGaZeKBPabAvuirHOmRxe",
		@"XTJfvDrzDiDZuusrhKfkTDsvFfTEsecIHaNrPRSVmpvPGxkEHBqbXvpHuuCWETfWKNxTKssLebvGTwhLVbpuBVjlAxFevewachEWnrAwiOngCsYpFkIgapdHDPIszCGbC",
		@"ZxAfCPogsGiWmMtLUNGDbalGAUzLBgoOWZucUclVmCgBgiOJPDpbOGOIEGiwMRxVVfomZjLzSmiTamSYFnJALkJMrBQQxLEgTuCsBeuykeMvihZhCYSOSNduPSspRJyvgZjnlzjbTn",
		@"EMPYOYPphdGAKAsZnBIEXOKufoippRceOiECjEQSeTHbqvhkavDszPAkJFTnuYhNTBMOTizjuUUzrPPgOKCizapGYIzzQNCwUPsaRulhSdxsYqDtqytKBKIZpKxsPlTsUpT",
		@"oYRYGviwEMHkKyYWezSsazxPDDyhiacgxfzwBoAnFKTyRYWGjoEEBkmjXCjnZSjhidWnYoCWjMsGmswqpxOeUUfBSoTPjgQHfbtaVFSEKSpGjfMYuXxpTbzitYEObRpaLwLFHkHJvbr",
		@"CbxehtOTPHQCOiibXAllUPtsPXfeFdGAYeTNkmZCHslkPtlFfzuVWFRBwBFdXQIqPMAfRWlbjIbbvzLGyNjpOkJGypoEPrADikfwVucsYkWXSMoRdYBkwSNkGulWeiHahDggD",
	];
	return kPXpVbyUuUsnVlnPC;
}

+ (nonnull NSArray *)jcpvUennrPxjfeRnN :(nonnull NSString *)ZhyXpCrLUkVUtzsK {
	NSArray *mxwQsfhZaQEcMBkylt = @[
		@"aRxOGqCzxcekBhuTEviAcxTpmEmIahtbKSiDoxooJfqfHwnMMVbsmqTVXuUWHQSxpeXrFYAnRbZfpGDymrAPhlrFWthnjSITwPGyQZCdnXqQEMsNEduJJaEHkfKBRKvwB",
		@"AuvceZVLFYkPiwziyOEEJGMgOjoULtccXMpWlShxEFTmQcWnSVfOLnZWNCdWhvXLaOUYftlSZcZJgGhUuEVpDGaAUpNKdtIUUneSzPQFLt",
		@"LjCabYAkhgqeIEsiskWmaQcrrkUizffEYNKbEbxVqYHelGkFOwqQDaOmdsWxpbNAtiVkfCdXoltspGxRnidvhNkXXpJtrAoYVcNhnbxV",
		@"LQmWxBTldWvEwiDICqzhIeWszVZlhyUtPRugUPKuCNGtEkqDNpPXEUOrzOoAxeDjTouyTEgwgOxIxqbTPGxcccuqaIRYxNELqJyRjAVdDnlBhNuJOVSOsTsPlDKHHjqevVzqzSHKvmLtHfvosemo",
		@"fpMCwjEYSBPtxbQcqOLpwaOcUGOpoPaNHWXadvUzpjpcnolwcWdCcgXObleJmLAwjWoinRTTREKEbRmdKmbYJRoKCtbtZNfTyhwClXqtLiplNyJUzZHLtWtIHpkCePKpeEzpN",
		@"FFWkMFnnoiIynQuqOzuVyXBparfcPEtuvUXDSbHQGuZCvOyYnzVaWtTBqDdFgExFXiYwJHWIaoVWlWQWdCRPsKDdAoAPmrUKkpqoBJrTmKQdSvcvz",
		@"WhKkZjOrQoyUxPGBWXDqVFDjwdFpCADfBhazJOvBoJiaYEoAYabvIYGIOVASAuarjNQEUmHwJzelIYvswXvKFVnAIjxHuXSZPVHpsSmiJnEVrGi",
		@"aaYMeTvEzoPMFQUiePWWdRVQFNzCXoVvzNHBmGWLawHkjfbqqCufRUSxYLhRyFcEmGOPKIFyJTUAPBLMMekesZVIWoIWxxvMkaomOXTihTbivFpUMzvbb",
		@"egHzJhuPcqcKkayhAxHkVDiqHJFkWTMDeafKeWtebvsiAoubYTAZGbdFVzWNJdbVyLWccOKnDbUufOXFeJqYAhjTMfEUbWjvtfLCcYjMfEkErXVppzwCNSKMUsLwZ",
		@"DqQBRxrvCoDZRMfSkTxLlpCzXTmLkGISvXhCjYhhqDOhpJxRaUEULkKmWHERztIbyzshYZPUlVKrXAjBQOCBBINjKrSZPbumqoiTlPOoulpFjLiDnwMuglcMxLUujlWKKuuQjXSm",
		@"CDEPOmMjwZGFOuojiKMTznRrraujaizPFyqzeWwOsSZIhOObPmwfsljOHJQvctjmxQJWIZZtoAATJhcsCiuiVxQiSZGJLdugIoikJLyHe",
		@"PejAkLisHMyCsWJHxFtssQHgnKbbySCKxZGSgSbOCcHltoMJJsDDpGwkPcENuhqdGzVOjoCFQqWRKhzEohhfrhuxdHWEjpHuUWNNIf",
		@"ZsuaHBNYAAmMONjuXcMrOMiJorosDygvoQsfzwGXCTVdMYrfHgseOGlOqVUTJftgUiXzrOOJPRwIqVtTquqKpsKubClgFFSLQyLAZScnUTCNiJpyoIYr",
	];
	return mxwQsfhZaQEcMBkylt;
}

+ (nonnull NSDictionary *)QdNQsivfybZkyyfUaU :(nonnull UIImage *)DeGCkuwQENdbPUEAZ :(nonnull NSDictionary *)ntloPcFmRBFgLsgqfcV :(nonnull NSString *)wBHqJKnBHhH {
	NSDictionary *tMbOSIumXizgda = @{
		@"PiOuMwTwrevScWz": @"PyvUyHWapwFTmCcQLohMValhbgWwMQlKoSnCysIyTxHAFVLBpWYLsVmGRRGOmiFpZEeiMHtUuOsoLsptLwQSXtAAqxirvZKwZMvYZDq",
		@"FdumvMuNOKcW": @"JmkTUyOEhzTpiRqQhnKNhorQVRjtMdJDSFDqePEdTBTxumpfizNClqRCykDTJafgfrBhaYsFuKHVSJmYEYMQwRFKDzHYJPGzXgadFCVeEWnYyUuaFnKqPugGIFLYtdwKSSQLVUAYBV",
		@"DmPstXDbwDVQJ": @"jKdCIitoqgKnWWWujtNftAUwEGDhJgDydkkMjhqWmxKioHtxpMEXcCFNbKAlludeSvoruaapLEZVIZDzUImuEFgbWNoAEWpbEbUQpFwtpHIeRYUBxqMwxpturfKEHUub",
		@"xMcsljyTEDnsu": @"TmRKKmiwKWniwGSgJSoztzRRCnQHdKQlhYTbAxqfxyowKFHwEtuHEJtNPbrKlwNXjaeqfiCUKdGQbdIrUbhIKhwazyvWYYPRTJKFoMycBkWUmQbPRffbDcFA",
		@"BEwLPSRptddrB": @"sykyihJVfUYBzcTjfmxcPCjCePaXBgkRnvWfJjvWYHVdUhhpdeYwlteiXICyRXDEXFZRAoIWvmBSsqvaOpUNVUkKYWFnoZptfWicIEhhmlPVcPFJFYnbdZS",
		@"LQJDMDHpCoyZf": @"IUgAvYKytIYghrUVARttXELJllbzhRSPpUjDNjtsicIgiFVlMrjfxGCVYSQhPAMKqNgtKWdwQofZIUcApqRgEbLqjxxulqJxjyCQLZvnwWfEcDMwlQYsSyTbCPsLDk",
		@"NcMHFnoCGxLSQXrm": @"VxfCYVqTPlvhiwnJEHxMXwbSUeyPvBGKFIzPQKGlonSNRdMmMHdvymbiUnNcgeBJEmYQdlNtNfYBmRQZSgbotuBeYjxNTOupUCPjifelIfJArRPxZTbaMQoLfhtBbaJ",
		@"SVVeREnDQnNHbFRN": @"UQOptPMyelPYOwDLnMFbOuifOLaSiPQuyBesDBMsrppZDxvyjGoRrzYVFffvMCTrECbhZsQbXMQdaFLHMcZDiqtHkKmWTgcqmlvmLqRYmTuCrvfPyMjMi",
		@"IQPjCSQiPswlemo": @"fKWtGwGgzuWaQDbzPdIJRLmhiIrXetAFdMMAOmcNMAslPAsxiwBdAzrBFkCEDCJUhOojwdLtdjpRVbPoCVyZefyiwddsNjVTimaUKItFpJEeNHGgoBzQpiDbAVPRLawbaMvLycAlLwHJXQE",
		@"rgqvFirqOm": @"qzCUysuzMMPTxtsSZUkbjtFoLscLFoClPohUsmeVYsquStxuOnryUBpFiNBurnazDAOfAkqNAjMqHQRIplHknJSsfDZRvrTwqICfKyqqTBkauhMCPBJSWITDKSCeqlsMg",
		@"CfRgTDfaLFxAhIdY": @"HckYnPsxIFerKlkkyWQrIreTppAdmoXqjlMQDsnsJLEIalAnTgXxYFGuLyghBSnKEUadzOllSOZqjIoUFaCAJWPUjlVYdlgwJQueEZDtSlpdjjeZtvULAMkKD",
		@"UBWZbdTRIGZl": @"wamoAtFpDMwoQwoCSQXhEoNISzsPAsxbtNrIOTasDLuAbMdEBZPvMYfVShOzwBodEwRtqTJDutiJIpUVKccZOUhfXSbOdsoppVftUO",
		@"lxrivqGaGF": @"qBrINYnHXdiPuhbNXzLTqfuoiyrBtYfhMoRWPtdNBoIaRBwjMSvwPikCEGsLsfDjEDgtOYzGyChGsulVFlfiMjRMZrFliRGmQxIFHDGXrA",
		@"mYzBnNjVPTu": @"aiQfWPfEFBtrmLetRTFuNMvAEnAabzYJtHtxMkguVBCIYnzzPFBxQEvMxTPgRyjBqwvWEuIrUSZAMpSqWRnaZzttnesyYaifKELrfxKXoS",
		@"zwRdKVOFdcTLKCQ": @"CXfVSUmrZwWxbYpIpsXVAHtlYGxQlMxnwndCyiQlDkNtTKENykZxPWUiLEWVfGZkadbmfasFJufKTecgfbBgzsTUiRAtxuUkZrnbJyGeLgYXLf",
		@"DGaJJzKROWIaZmWCQ": @"xCqTsmQwTewDKYPNCNmhDwyARxbFWpJQIKVXADetQEaFGSjmFkJMDlYHkuopcBNRoTpspdQxgFTgTzCmezqhLbSuGmIYnFDFyhTwKJUudFTnjzxOKYUxKsHxTxU",
	};
	return tMbOSIumXizgda;
}

+ (nonnull UIImage *)eTBuByjjTAqFCtvpn :(nonnull NSDictionary *)rqZeWVPxguSUCd {
	NSData *bilJJRWUGTf = [@"tBFRRFrNxBxbxpeeGViOxKvNEBJaYeNwIKkqSdOgCyarKntViMbgUIIvNLwYdssEheDOTKTkGUEdcbRfoQqYktYDHEpEQolftFmG" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *IEOqSDbfBGccml = [UIImage imageWithData:bilJJRWUGTf];
	IEOqSDbfBGccml = [UIImage imageNamed:@"BMPKOTpWFPdgsglBQjQHeWZfxKbwKiWFZjQfpzxWwQdjezslDunaDKchxwOIkflKnOxQOCItgLbbFKzqqEfrKwjZTtZQgOsuDnwABwTnrmXmMJBkGksvmgVyCUqzKiS"];
	return IEOqSDbfBGccml;
}

- (nonnull UIImage *)QtZIMiAinfTuvTFjpu :(nonnull NSString *)qhchuhwltPJBEW {
	NSData *nvluUVttOzmMErfEvn = [@"uWAeGilMciOvnkDdVIZBwAtGtBxpOqEmJDeJTJhsyIhfHzLrvgzsgVMDBXvbqrrLnrbRxqeWFQfZXiWVeInYqUsOleFhcsNUmgIIUoqKG" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *mxirJyERwylgjrypysC = [UIImage imageWithData:nvluUVttOzmMErfEvn];
	mxirJyERwylgjrypysC = [UIImage imageNamed:@"PpzhzWfVfXEOUObwieuXBnNWbwruHyCJAswxFGeRORzpMxJSjdTPiiRsMshDlwFpwzqAAQIdXanMGWVqlVFHHgZWbRhKuSnQebtYDyjTOthBIUdTWCzVWZBcnbiEvfHek"];
	return mxirJyERwylgjrypysC;
}

- (nonnull UIImage *)rAoMuguQvFpnT :(nonnull UIImage *)SkzpAQhSjBpPYLqSCX :(nonnull NSArray *)TyeScLHeLlmseqmbe :(nonnull NSData *)bffJWukLfNaeiKELK {
	NSData *eFpPWWrIMi = [@"qaaINFRCqkKDjXqZnYRkYUQVwIhIQtkcFahoRYybtmhiLHqQiXyMNSvOaGGYSoqcKhKFNxUapXPcQWhIEadPNkcjsSHjrAHGxnLKlleXNKrtiQPWbvXXLPcuvJqHMnQDEHyhBNJuiPXBjNAIS" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *KipAMqNzhoPzZMG = [UIImage imageWithData:eFpPWWrIMi];
	KipAMqNzhoPzZMG = [UIImage imageNamed:@"kQbOYzjpmOqyiKgKKtXxJrIsWhtnytkIzJquUdYgnAOEargnGAwuTxBOFEbTcKrrqJfEmLVMaCEgpTULCMjrLiziVwzSidlMXtSGCQQOFVWycduCeHhewlqvTcIdVJCgVqWZwMMTTlmZTXda"];
	return KipAMqNzhoPzZMG;
}

- (nonnull NSString *)zVpHnRcnrxpguIbdcoH :(nonnull UIImage *)vNDmLqhfuJbeLiMEVjs :(nonnull NSDictionary *)UpoBGfhzhc :(nonnull UIImage *)YcArwweKXw {
	NSString *FfqSuLsBMcbhNTLNF = @"ImNtgGLzfHpfXpaZlPiCdMfEaoScQlbUWEbGEvjYkHrWXayqkTDtlHayLTurFnXDzyfCAaJDLlDYdfBzzCuCdaNoyKIBboPjqvxegcQqaPSfgrIBKQgqeYUpaurLdnrDTgSVRcdZFWDOaSk";
	return FfqSuLsBMcbhNTLNF;
}

+ (nonnull NSData *)WaGBrGEQyVwC :(nonnull UIImage *)AJoyDgSbRORGUHMwUFf :(nonnull NSData *)vuZUscTkgDGq :(nonnull UIImage *)yveVZbUPLFN {
	NSData *wdUgWoafsygJ = [@"VlMrYSWPINkzMuFCYkAyRCfCTZnOfdCMzdiuzZeNPsXKjltuirAmZkRfzPxOnTFgqrWeAYkVCnmnSHrygGnaSnthsuUaeJFwRbSqfQpcKOCJVWJkaZSBc" dataUsingEncoding:NSUTF8StringEncoding];
	return wdUgWoafsygJ;
}

+ (nonnull NSData *)QdcLzcctesxVsZKcTB :(nonnull NSDictionary *)WDgCMyMHrwf {
	NSData *senBioPXylvoKFdRsZl = [@"bZnRELfRuRzVhayjgXADCZOfrPdcBoSzMHBARVEEgEUDnYowFguCpDpQTjSctemlTlXkXktrYOHTUoQIdDOVxUudTTySGCUKoRXIsT" dataUsingEncoding:NSUTF8StringEncoding];
	return senBioPXylvoKFdRsZl;
}

- (nonnull NSData *)GqJStOeBwQueWSt :(nonnull UIImage *)qiqsqtYntvTC :(nonnull UIImage *)WaTfdWgfgVv :(nonnull NSArray *)gXIldEPFVsO {
	NSData *GWZaCTovNVmIsVLTi = [@"wwkNJLUZJmzWdAiqnpyQEGLjUkUgXOJMiEQrxcfoPmKpNlACEHUEnYthMtxrOVyQKkCbAuOmvRMrNIkYaRasHWkiKZixCqqYRkvqdRSQvgyJmhNYliVmPCFuUqgMf" dataUsingEncoding:NSUTF8StringEncoding];
	return GWZaCTovNVmIsVLTi;
}

- (nonnull NSArray *)WoAGMuTlrSDE :(nonnull UIImage *)XOvwsrTnPtmlbpsYm :(nonnull UIImage *)duyplmbmokDPJdgtm {
	NSArray *JRKOBPvYtHdwf = @[
		@"dRWPyvNOnYdiuQgqSFRAvrjgXmzBGKiynqrfHlBdireiCDHIfUJEaACsYmzihryzpbPnmyyRuMBpDlEMzVQrNOcMwuPMmQgWtepNQUHWvVKjai",
		@"MDfGgKhrjEnKyaQhVKQJimMmQeFmxgpvYtKcZqzWZAQBeXavMxuTrWfljnNkHCZrfcvdxGRQULcPtepICozjybPEwBsgUDbLoCkpsDIF",
		@"OYXQnoecnuyGBxQsZSYrxQXlCcsYTWNNuVqFmZYUkBIWJjTxZDbpixGLKwyHnncbvyyIIcEtEpnpmqwSkumWZrjOnCWFOjNLsmZHzQeRfJWY",
		@"rafsCEKjIlufQkbOkNKijrkDmOCfmCMDPOCeZvNxTcunvmwlgdDQEgZBRMoIkMrwvcnXQfDqFWlOVlgVwpNJBKBKNKgiJEDGwdMWMvrUGMpFGwzkKnxaoAJgrrSeVbkncMxFuqTmFaygKrEUpOyd",
		@"azVTMJUDSgXZpGdeiWoYKsZmsHfecOJSrAXGiUANwbBtEekTMcbIJjcalxOozzCTeyKcXjJVVdeixGCtvmKTtjgCGVNRYIjxhbbXEWasDKyHNNRdwcKWhwaRMdsbfxqPZjxxBjsLXrKB",
		@"qdAKxjhVUHKxezPVYEIGcRxawVefVCmleSdOYDmLbSzvENVYTnGGfYJwDlrAhgGXWzldBFCZMgPgazeMPwDPYFWsaJYjuRjmSAzRoDzOLRbdBmOIpNCd",
		@"vxdHtiaiQISiSUecHYIvRIyxNRfjSMafZpvpFshdxMlveHHoEryxYKTmxWxnCnJiCkoYIJAcfRJsHhTrShWHevhpcNHsqDQOUOmKp",
		@"ruQUjmZxGPzuHDdiVLkWuXRlEeoHJwGCOEdwgxuiyskBDmKqQgYOgjgxlWDyINmRYIiPZsWnDXuNCBiDjjBKOJhpJlBgsoMuUTFYWUykB",
		@"twTJYDzBTiUKFgFDBoCgSqqUMiTkWMoQZyfaSMoBbngiHPcuAhmIcfgdGtYbMlMeUOoJWvuEyEdToseecDONkSglnSBhTzwXEcCx",
		@"ThIvkZQUCNCkmndzeEmiQIRbuWLjmzorCEaWFQjyEUFRoczXgpiAngAarSamDNCahcYzvWluOIOfsIMnQPvQbJekNHgoKgRYQUHYKCzkADBYrPjlKzXxvQlHHLsLgXGltAbsjW",
		@"VnFQqxFNFvcAPKCPIUemBtrsDqhlBOWidteWDyMRdjFIyyaORGSkGgTcLOfIKdxlQOcntkbimXMJveLBrOlbLrWbtdRUHkEmnxBPUNMeXyWvvsOOJTtPIqJTBbVuy",
		@"JrIOHpLYLnKofPpggFAijtosIlWOcGbGNMQKOhQoXAisALnkIKGpGPwbKPkClbjqnauxIFULVPoCwNPJpFWgIxCQRMJCTnLwtdJYPsvmmxNQVe",
		@"KYvHryfPeCkTMfLdIhDUregTxNsFDcUHGpmvmZcsTvjuxjtUVvgBUQxhSHzadcyJYDPQgnLkVQhLoyvhIVrdIFeggYhJQmwqpVMQuuXEVucgyYdKydRaluybFxXhPKwoX",
	];
	return JRKOBPvYtHdwf;
}

+ (nonnull NSString *)SzWuJmlZEFdmF :(nonnull UIImage *)QlelNFqZnzTZDnPkWts :(nonnull NSArray *)qDfhldXEheasbdKdatj :(nonnull NSString *)smaeOdoGQGMCKbhxf {
	NSString *cwzDrZQupGbp = @"PAJXeDEvUxnyiHqdQpAmxsugDHlohTsfjlkMVsRBPObdqZkuyjtMXCZJsReZLgwVICHxeUdGscdcRpjkdzmFyDxmxbIhuicfuAKkcQJWeQyWmodSKVzEsOIoVlapkuKnpOcg";
	return cwzDrZQupGbp;
}

- (NSInteger)version
{
    return 1;
}


- (BOOL)onCreateTable:(FMDatabase *)db
{
    NSString *sql = @"CREATE TABLE IF NOT EXISTS emark_bill_list ("
    @"billId INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,"
    @"billType               INTEGER, "
    @"billCount              REAL, "
    @"billDate               DATE, "
    @"billRemark             TEXT "
    @");";
    
    BOOL result = [db executeUpdate:sql];
    return result;
}


#pragma mark - Public

- (NSArray<EMBillInfo *> *)selectBillInfosBeforeDate:(NSDate *)date totalCount:(NSInteger)totalCount
{
    __weak typeof(self) weakSelf = self;
    NSMutableArray *tmpArr = [NSMutableArray array];
    [self.dbQueue inDatabase:^(FMDatabase *db) {
        FMResultSet *result = nil;
        if (nil == date) {
            result = [db executeQuery:@"SELECT * FROM emark_bill_list ORDER BY billDate DESC LIMIT ? ", @(totalCount)];
        } else {
            result = [db executeQuery:@"SELECT * FROM emark_bill_list WHERE billDate < ? ORDER BY billDate DESC LIMIT ? ", date, @(totalCount)];
        }
        
        while (result.next) {
            EMBillInfo *billInfo = [weakSelf buildBillInfoWithResult:result];
            [tmpArr addObject:billInfo];
        }
        [result close];
    }];
    
    return tmpArr;
}


- (void)cacheBillInfo:(EMBillInfo *)billInfo
{
    if (nil == billInfo) {
        return;
    }
    
    [self.dbQueue inDatabase:^(FMDatabase *db) {
        BOOL success = [db executeUpdate:@"INSERT INTO "
         @"emark_bill_list (billId, billType, billCount, billDate, "
         @"billRemark"
         @") "
    
         @"VALUES (?, ?, ?, ?, ?"
         @")",
         nil, @(billInfo.billType), @(billInfo.billCount), billInfo.billDate,
         billInfo.billRemark];
        //插入成功后要更新内存中的账单id以便删除时使用
        if (success) {
            FMResultSet *result = [db executeQuery:@"SELECT * FROM emark_bill_list ORDER BY billId DESC LIMIT 1 "];
            while (result.next) {
                billInfo.billId = [[result stringForColumn:@"billId"] integerValue];
            }
        }
    }];
}


- (void)deleteBillInfo:(EMBillInfo *)billInfo
{
    if (nil == billInfo) {
        return;
    }
    
    [self.dbQueue inDatabase:^(FMDatabase *db) {
        [db executeUpdate:@"DELETE FROM emark_bill_list WHERE billId = ?", @(billInfo.billId)];
    }];
}


- (NSArray<EMBillInfo *> *)selectBillInfosBetween:(NSDate *)fromDate and:(NSDate *)toDate
{
    __weak typeof(self) weakSelf = self;
    NSMutableArray *tmpArr = [NSMutableArray array];
    [self.dbQueue inDatabase:^(FMDatabase *db) {
        FMResultSet *result = nil;
        
        result = [db executeQuery:@"SELECT * FROM emark_bill_list WHERE billDate >= ? AND billDate <= ?", fromDate, toDate];
        
        while (result.next) {
            EMBillInfo *billInfo = [weakSelf buildBillInfoWithResult:result];
            [tmpArr addObject:billInfo];
        }
        [result close];
    }];
    
    return tmpArr;
}

#pragma mark - Private

- (EMBillInfo *)buildBillInfoWithResult:(FMResultSet *)result
{
    EMBillInfo *billInfo = [[EMBillInfo alloc] init];
    billInfo.billId = [[result stringForColumn:@"billId"] integerValue];
    billInfo.billType = [[result stringForColumn:@"billType"] integerValue];
    billInfo.billDate = [result dateForColumn:@"billDate"];
    billInfo.billCount = [result doubleForColumn:@"billCount"];
    billInfo.billRemark = [result stringForColumn:@"billRemark"];
    return billInfo;
}

@end
