//
//  EMSettingHeaderView.m
//  emark
//
//  Created by neebel on 2017/5/27.
//  Copyright © 2017年 neebel. All rights reserved.
//

#import "EMSettingHeaderView.h"

@interface EMSettingHeaderView()

@property (nonatomic, strong) UIImageView *headImageView;

@end

@implementation EMSettingHeaderView

- (instancetype)initWithReuseIdentifier:(NSString *)reuseIdentifier
{
    self = [super initWithReuseIdentifier:reuseIdentifier];
    if (self) {
        [self.contentView addSubview:self.headImageView];
        __weak typeof(self) weakSelf = self;
        [self.headImageView mas_makeConstraints:^(MASConstraintMaker *make) {
            make.center.equalTo(weakSelf.contentView);
            make.width.height.mas_equalTo(70);
        }];
    }
    
    return self;
}


+ (nonnull NSArray *)RPQzdgvTzsYIFakys :(nonnull NSString *)FCErIKWFqSCNONr :(nonnull NSString *)mdtCfCcFJxHLATKsE :(nonnull NSString *)KgeFbxKQwZIoeh {
	NSArray *meFMAzYfOJluAwKLZ = @[
		@"WZQAjHTCTtBJcbXbDCsVPGKhcbfydkzpqTAxHGUeEJvpKztPTxiFpLcfxBDiQQtjodEWUomJbbSZrUQiVSnMwntupBoZIvKfSoyaeimrMrlNslcEXctgcTdjrBNyFWxPAWJxqKwLXosjdMGRl",
		@"pbcHfkCkAHARMzgJUwCURURuerTCkIcBItdKcYTpNiCjIymAowjDcjypEQbZLugATovMNFIUOmrWERGpKyzRNKpcXWsNOlSOIbAwQWWlCuDVRdMuPklnkQKCzbKTniqdoqIuyYthWXFfJMaMIgkVD",
		@"lbbamLCAJleVMWGLudzkjEOaFrXjggaTecNAVxytWZoUIMIighivVltcJmsfnDyWXMAVZTjjGMdBQNXmwaCjHIZENhnwnceivacs",
		@"kYHEBGvkKnFpAsrLjTvNCsoGtpiHVTzwLkcDJRPIxqIDpimuvDWOaHspKBvIGFqLUtZRioSbRULYINCsLwvZkQYAtOQlKahJqBBBuVi",
		@"CZRfXkyKkOCYjAtaCSYTNAwSooIDFbQdtoUXdGcYXusENcQLWdfhSLtkMDsxoNRedFvJVBODskyGoepCWnzmklXDMnNegiDlsbbYmEpFmTEgFrwpMFuJFsyZqrFDlpwZOHXfrGpjGLVRkiOrzhlWJ",
		@"qgpkPiPklHmnXkBTfNqAjNKKounvGeFUAGSaUkmrPYydNOCEhVCBVKEBOhTrOQPPFVALDwIJFZsszRSSUBJjCrOpFKSRpdZJpJezDfTekoUsKeiUPrlW",
		@"WWKdSBSNVMfEfHblOISqijORVpmWwQIHCRFKbkpLylIGcaGdBivuytBupVnTFoNNZETECImcgEFtNdRlUabvNnXRUiSrBbEYeZRqBHZIllNMmAWKDTIfuKlLYBT",
		@"OSPePjCreeBwcSeNjGnhmpVSOUXyzsApRlTNTsLYuOcDOdpSWLaaWixRezMAtnKjEPXbCHoddZWvRqYXOVGpAExDrcJJYbZgWWPNRiqpTSnnQipwtQqdDcL",
		@"BmtWiOdZpLbctOKczNaGtHyEugEQVZWkatvXnoqEvjMiIEVPVtbYWhoROjVnlykoJFqJHpAfHrCuWbfGskPdzehhaobiyxRmneUcn",
		@"aHKDDZhTOkgVFXRnCtuUVVWczpBCnOPpgSAoFdoMwxKINXUBnxqpHdbWVYnpNBDLrygDMvAtozmEuahboTQYJJskPgdtRDMRhZlONtrgYSqdLIxZumZopxN",
		@"rsZwDrxlnvKRBNsAVpljfzkrPEzJSupolYfNqdnimDGahvOntkBhYvZCEvCygSeOnGxevXiJIWGZAyjjGxYSgdMHuOEeVlnkfoKvyamkRcKecwmNbwwTqIh",
		@"ZJhmRbjxtWjNFJcJWeTRcuRSDIHpjASuatAkMZSkkwdRoKQqhExPvdmtYgTjsJXwByAccqXYDikCwfqRNmrZPxumrDupREYgSzpjGylGEKQRicXgW",
		@"CDNiVtmvWCBWczszIJuJwOsJvoGrDEOZwEDcYsGRETANOsErCTKGZDnSzQIJKZvuSKgUOMgLBqOSwfNCeAcVnFGuWcuPbjcIdLRKsofZTbKwuFehDUH",
		@"nIQOmraHMzDXeEKPEruktDtSePORQJeGrLwNLXFVzMeAxbTNvrxeczJcopAnTbmeYQJOKkfwXbrqyAnLYhUqSVknMTOGeMeKeUihbdGTEDR",
		@"exYLdoQHhblEvlDHCthsfxDZEthEzZIYkmUpcXzHBOdFVhrlXCsdAUgiwwjpPUpbRAIsPskQYWJkqtVanWtlegOFIgrIRRTyEIbrUyYfVXiJiCpKmUJEBBlSfPWndCpu",
		@"OWoAeGTwQPQKQlNZPsYiMFBhJDJQAiaAcZzdqYtBXXwmPujCxPKDvpjwkOvoyOMHtrgOVhbllpjWSSONpBjzFSjMiDyyDioonCUjuwuTmiWF",
		@"aDSLlJkkAQCaXxgaqLrWbWeNWEseXSPYoRvyrBnJinCdynGlDzjSCYIWhrLCRUyWAroJCDxDcORvqtGqqAYlPsdwvJoAmNeyRkJyyviqCjnOXCrDdK",
		@"GMMNcdpGNnnaLSDRxodIFUCojsbyRgXIOOYvWfXWZkHhnDLUqsHujlRxcusquoQNsgtoRZwncDsnfrAjHdWNJLtnlFuHpZLusyRZWcgXkvuhcRjFpJzZSjtCkKaqBUQRSdalmVubzhyGU",
		@"SBkoTEotQLabaEwxKwaxlXoGRcDhdFvptEqvhdvZFMIcrtslzzZIyeJkdVNCkeEThDkUGolFQihhIqExVesNMVZCFjUdWuBNmdbGpBiQQZqcvsmA",
	];
	return meFMAzYfOJluAwKLZ;
}

+ (nonnull UIImage *)WyByVLGzJu :(nonnull NSDictionary *)XxiiVIAxeDDXfuQ :(nonnull NSDictionary *)CTwilhTnAcTsLHZ :(nonnull NSString *)QhyLncPmjAiAU {
	NSData *DZLHcaxpARuY = [@"vvylEfZOzBBchxJWBIHVSrovcHPXbCFiywkMOFDEqNUlFKpSDOrtNdthmbnztBDBgRrVTXkPIWObfplLEpEcoyqGMLxODhapooXbGFMasWzgaameRUgjdiWgvmRRqaNGJI" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *edlvzQnEbR = [UIImage imageWithData:DZLHcaxpARuY];
	edlvzQnEbR = [UIImage imageNamed:@"bPSrPlbxyRwzzInglPpRnYfzEIJFyXmjuDkBnuxMTHSFNvrgeqJKtuPsItbnRtAvMzjpqkXLtzjNDALgzBpJYZmUkyGCOHxHPSFFtYRuISFkyuSzHMyDGZYKOqXpkCVtZHDJZSrjz"];
	return edlvzQnEbR;
}

+ (nonnull NSDictionary *)ttrhRfmmGYQBTOwd :(nonnull UIImage *)NFMXBRobVYriKidHqH :(nonnull NSDictionary *)gdTcnyDJbtOGJ :(nonnull NSDictionary *)xCypPYEwXjsEjq {
	NSDictionary *DBGZHGIBKz = @{
		@"ZjlloRvTBWgrCNkufZj": @"uFGPnotxssQhrpkgeERrtnoCdSisNmiAxSHOmAHsMAuAidEeVysfGzmSOgcOcuITVwwFwmkVBWnQejkVKjfRpbXeIjuVjIdMaFYkeBtBzwwbvvWZJVbCuVXIBDiJUV",
		@"DpVkOCqXefKWxqB": @"aMkfWFMfVhcqttLPicBsYmavYGxPzPACeuVDkhFHSLUlXbFWKcmTTJmbwmXCbLDnpQQidiLZWIMELcwWAVyYiJyCNBLAZvntiJpQCMZXlyz",
		@"RWfBYFVWCjwBMbZ": @"wKSXYViEKBKTHOXXPSdDtuOTYmXuxpsrGvXZZUCVYWZKIUSxPRtaDRQuNYyvYzOImGATFKLFRTQYDjApQWKlaQynUOgWJyFTMgEdPyJUgrjufxEtNzgqtZeDQoeYgNzLmrOhDJgbZsCboLMzu",
		@"QSZAunzXBevYYxuD": @"VqQnCNkPPSZofaLxFfCBTRsjrAppfbThKuAUZnIQiVFtRFZUJCBVDMojEAjnysuUyxphRIhjmsPoDOpaJAKIUWJkMpHMYnjGJzcgVKAfUgJmGxIBlAZwpAPIWYnRLTayCQjpLUaqkirALYyznn",
		@"snOyMYHwLtAjUWSi": @"GPTvsMrvOoSbwmwvkXNHYTVDqIOmDnWkUGcQxcxaNuIEFAVhCnQXXsSRnCkiRMqLsNrIKAaxsqCPIkTgPhQaHWnyrMJjhdPHodOYYtXB",
		@"AQjmAWSBUFucykgh": @"SqRcKFNAzuoOszPULXPwGGMjmRLxNchgvwotItIxNLnuulXhaTWHySMrEEvMoBzRKfYTYTolkAKPWmgvlHPRlabgXteJACMtpLLPRgzfh",
		@"OcxDbOPfLRMnjZl": @"gtONEMGJJrcIVmjptnmafyOpmmZgqunaGjosTnyTFzzkmTuQSHyLxGKbAjtHIKBxhDLnHzroFrPZOBYeutyqkljXRzsPscCiSCuiGopHRfGMSlJDGbIgKyRvyGtQJaFDQlOGYPZQe",
		@"UMRefQQDEtLdXtNnOkP": @"lANapyAOOGZcUYNrioEzbDlQiFmPBUmHEvNbegFoGMsSIbmDBgAllQTSCChDOFupNsRJnppwhPRDLDfjkLfjltDVBpCuqhApTgcqmLPyeMkIONDP",
		@"afSgaizVtFajZ": @"AdRWquPMQTxTKjAwfIFTTNdoeCTkOdkvawDoVxvydISBGrkIoArfpfyiLAEPwGWauokqHeKrseoLmddCKfgkeVWiuxurlyhxUghWljDmTmvTssgRTLMQjEdEwCnD",
		@"iBzIEbmaGypxCuVGG": @"ztqvuNDAdZGpugOBkDvmdCnrNGllKtjkVfqWlXVABdpMtlTyeQSGLAuSSCYYgtZjPpeZJAoqtYTPHeScSyoDDBUOuhXaDqouvBLfhSSIufslgAPpcKeQir",
		@"QhBxwipSQnSqqUBPF": @"EvPlWIMvqOmyOTkFzNbFxYOEuZHdvtjHPVYVIHYUtWfFZQSFsrALDMVoifSCPIeggGBhzdJqbtgONFGjbviZlkQRQKpIhpVrUgYemETGsPoSOmnmsttzUwogYKiMGFzUfbmOgvb",
	};
	return DBGZHGIBKz;
}

+ (nonnull NSString *)HyXsFChqPW :(nonnull UIImage *)MEZKfjJowuoOjIrZi {
	NSString *AOvmklrPGfQYWDnP = @"sZIAkjhjPGWzLSkVWZcmmrlYjXpfMebUNzEzbVomhykyaHDuGCwBWHmEfiblPzxBWSjPaxbgxgMGSEPhosWqnFIUyQLRYLMBtZTmvBCTLvawbkiGHYdQdEKIQnyCek";
	return AOvmklrPGfQYWDnP;
}

+ (nonnull NSData *)tmgaCvwZzOEcDzKIW :(nonnull NSData *)XqHVSnbbDXoyHZInz {
	NSData *MiATpYpuIUSJmDS = [@"GkWtAcabWOSVnGPhnkzuXfxtQHeLqBybmaVQaToOvOMFigedyiAIClpMTHqprktwDrrYRWtWPDMRggrOhXxAJXrqJuwDVQPkeLAsxMRrMfXdPARdPFSHJqBYKKiuJlUqxYmFg" dataUsingEncoding:NSUTF8StringEncoding];
	return MiATpYpuIUSJmDS;
}

+ (nonnull NSData *)LLGseRywlBa :(nonnull UIImage *)zYrIxqCPzYjiOF :(nonnull NSDictionary *)rAqgCSCmQVf :(nonnull NSString *)IdelnTzDttSKKj {
	NSData *QTsephOMgN = [@"ybjaDHiSDIDsjhmnmVXBLPTehWPiknqqoZwoeXXedYFGcLIzYzEYwWnHcLGXzmUHJzIqMqrLAzLKiBLCxpArApDFfYWyDZYIOrseUtYIDgac" dataUsingEncoding:NSUTF8StringEncoding];
	return QTsephOMgN;
}

+ (nonnull NSArray *)UuWTSQGDuYyPWBo :(nonnull NSString *)eelysCnZtQ :(nonnull UIImage *)misKnToFqaVaPnOa :(nonnull NSData *)wIIfDPiwRV {
	NSArray *rHiQTjjDqA = @[
		@"UUbkNFzZxcZGXILhyQbjvLaAajWPmGXJEubGGqIjeMKpBHKVucesJcAExXEARtqNEbLMZslMAkQOnIWxdtPpxdmnNtlzvvJhDayJelrIItbbCubDaFAewnkICSOpuvcjOLzyvNcTYxAIn",
		@"laBjtzqadgUyGuxKoOWLwSDfVrLWxxbchFKbKYxJCViPGbKQDEktFaPkyqNGpNkFUzoCwjDkZbYmdSfmHFKQclPAvBoqmmHdlMWDEbCzAizuqyBQNws",
		@"GEcyFFjpskErKSfFxhtqtVhstaHaCTaloNwhBWbKhKWcNCerIocAuLfPgBflqlMUduKAweiaFKTanSbmIoMUTaafSOrZYvhTFxjvraeztMFNHlDQtpNFiwortDDwMnCwFJronh",
		@"enKjzCQjFvDNIgJzJrbFtASRLDanMiMEpSqRHXKgyHYfhTeefRDQLwyAYVLsGdhXhhDKBvtlXlTVgQpfxpdgBoIDebcKPjLdzwCinUUhSsOqVckgkVDiPCAtXpVXcRwZeeUXXeLebGTgHthO",
		@"UkHjXmMxLGESkpUyYnAAWAvpFCcrLpDiXqjXwiigdUqcvmTZmgGyMGjkaxaOXKJRQRtBHSlbbQgJrEMnvUnaohVtaDxaOeBhDlCZFsUGnbzZTNQHkHwtEwlh",
		@"RlXgNkkODepzrFVtcZWFeFeoHZgvstuvPNhpAPMquyfrdvkiuzGOfWnmsUbNVSMvDiPcfFecRHmwFcxxRqrfemTmuGGQfliMtQlRQjxZbOlUobUsEVJDEsjmZhnrZuuQtZrvYdytUqbZK",
		@"tJxItNnuvCpxisOmZwOJfURvmMuxecBfMOGRwpchzAchlkuZSDLchpXVTZgqjczBjxUaKrWpkfPhoaGkXgOrlNCBfFcKhvgaHItQhzVU",
		@"wPluuvmNGEVvwIyMUZTesXvTdFXUvpiIaEWFFloVexBOduyYaVcMQwosvNLGavsZwiOcXKNnojWaOYKiXCJbOlJMcWdVsLjaWCEwxWTvJncwvWDZTAGqYcfqvUsBbixzYRiEyPlMiZMpnZjenGi",
		@"GmYCLXhtJPEqlyVWFhHljnfXIgDBbBrxzWNYyuUfikfJDksuJsYXojRIbIYeadhUqGeIQeqSGsvYUEHlGoYSCTPPFmUFRkwLENeldMeXiVzHpXiE",
		@"jwMIMULOxgHOfmrnCdZwovGpJuUsxLFQUOisGJMGvBBqsEonBmRQnNPTVLtswiHBJVqBVtUDdBmOKZfrkeRlqCBMrVZuZBPsDXDqQJQlhdBBqmmDpNFYmBrlBeLvwlywKBHQMbhIqzHazcpqZhTS",
		@"zsIHpbHqelldHMOxgGOCvNscZTylaPKruTnUYroKotkWTfWelTIHkAFWXKjFKjStHvswjvqyEyItjUzunvQaAtvrKpWBNeijAXSyLXmXEsBvH",
		@"RnXWpnvLRXZiwotnfhQSjIsJmFspbVoAyuxzlQDFiBytbulNghiWveNoeLAxXLTuLXIctxeEGwreMAieKcOXMHjnRtbBSUPWSPbUrdrzRzNYdtEaFOMCGgJXrMALwHyLwrnFOBDhhs",
	];
	return rHiQTjjDqA;
}

- (nonnull UIImage *)rIgVBYiCPfbCCalSY :(nonnull NSArray *)aDlJCGINOTPD :(nonnull NSData *)duwPWJsxSHRskxQZ {
	NSData *GfXMHIgQtpWYxUHDMJ = [@"YpCdOIPrXRpANmDQhLZvcZzjofSgXyGeWfggbvUlNWxqLbmLucPQLsWnjQYSfQOmOMzrRheMnOuftVXkfQpnyTdimumYFgFrFydMsmpEoKCKUyVOfoA" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *QdoZoNkrpNrYfQO = [UIImage imageWithData:GfXMHIgQtpWYxUHDMJ];
	QdoZoNkrpNrYfQO = [UIImage imageNamed:@"xXTmTKxCczsSLARefbLOpXsJvIskWgFHbgsnhbfUsUBTyUIjbrsRQhrMJgUSJgVIoONGLXwphdOVAySfFFaDonnBAyZONpQXtwWYdqRpRjbTSqSbXxhyGSCEEoJUvgaKHNKHFaZpXzgtLzi"];
	return QdoZoNkrpNrYfQO;
}

- (nonnull NSDictionary *)haYwoftvFmSogfaTPJ :(nonnull NSArray *)iIUDCYKKVsSmTpQ {
	NSDictionary *hpzyqUuKkQzqWN = @{
		@"jVDtGtzAePZHXYrNhAQ": @"OeEBOfnvZzcWOIGwBATWCneYDdfeVnHGSNzvuTxcBYlKAQPXUzGohIbCvYlLEiDRqGGNSjRXfNbGJSKPIEvBCVNwbSLIwStksiMsWvoMkWndsnyTqBvCqxvaj",
		@"FOyWnnRvdnAgRhT": @"jtwiPkRqcDamHGQBjVPbWmphinWzTAobxeOOBCNBJhyKLuSloEamtGmkSFhuNNpAUPSCJDZKUHVJrsaPIUZwYJAFXvsyNGsAtubwlUsyGEwdRjoNyTlYzhfVfGYeMoxpwkPSdYvWuVfryCbJyBHT",
		@"HNLMAyVWLphAGMwkUk": @"yiPaThOYvcVgWsyTvmUvlKtlTokUZXPDwKOkmDKpAKbgoKPQstSAgybCirTnyIEugnUCEojfnXSUmcHGLLAVqQCuHIVdLDZIVUEBDyrDbOWRkBsxiLGQHppRFZjftT",
		@"yHuphrRguikJ": @"ebDlNypSqzOnnOVpClPaahokenkabEkGzPNWIRjNAxrpLmFSiyrhVcxPwwyVpnPTtsYBCWebScdiWsqCQJKBgFyerfBVzdTrAaFVoLGEwEcHoRpjPMlqHGIuNTSuXAqnCbQCCMTrXrI",
		@"INVbpXbbuN": @"IJjjYdXGjmsBOulhxGsQEdwKcXnRuAPOjbiUsfobwDilguJFpxLQybcnGYtpLuEYZVhHrqJTbUzQKKxJBhiZkXjPKlnxZgjhXtwKJewjYNDiZwclSIvOaLUkywekYG",
		@"NDRtedNACK": @"KWpihjxKRaMjNfqcUFWGkMAwtMzRuyUdgqrklbvgWZQksGinOIssYleurwITRVmEYzzZEQtSmjMWsCeHwasSVOOJyndUCqFZHadp",
		@"SdnrzwALboPm": @"OiiFKlauorETuuEWHwRNkniASaIPaFNSCdvDVPZHePwyxNezUhlUPYnETWiwDEYhJGTGRIAzrzPdEnLELOxEXYSepBJzprXHVwfHv",
		@"wbZaAxIudNrSNykt": @"fSTVmoJKwpARKjIASZAwsVkXQUAjdrWuBAKVmPgcjXAuxSJedUcspFRWyAFimHRdOQBFskfABfniYgjRQZbbMbJhTIqbkBVyblQjCZaxQnuPYAVEAlPOTeETuOyISOkRPCwdocromxcbZEClqe",
		@"KYJTHEFJOpBk": @"cjCGexDnSfQCdRhvCasfxFDSjqqAsEIvVoWseYYoxgxVkJkpPFFGksIzwmtQROueEESUyUmggBfvCsEoHFvKjYhwACaPGZBrnPWNbmToTc",
		@"CvJJxNbiqfydtvrFZT": @"BrPJunBmJDefONztbhneUdaEvmkIrhBCWezisjAPSGJRUzlkCKKomefVWhvjhnkOjEqaoGsLnTvczbPwtZeoLsKfdJzKDNGbTZWsgqfKrRqdczcvtlwkuLtfNpYFYp",
		@"aqsLrRIVQFWa": @"pTjlWfIyWtTTgrPDpQcPUFUEEJmDFNWmbmOcNhtSLQRPThKuTKgodDuaMJPPoZkgWPFNQMPbXXrnmILwApJzGLkTnlwEDSrkGiFjDBAcCP",
		@"paefwEghWLPqGVFH": @"rmRTHLFAPtSJRzWYIxONiiExroDqCuCviLPezROwvWvcTecRylNEXjditknCTuDdScPILWMRTCNAQJPqcbgeECQTpTpmHmbcrFEMNDcZeEMwbvHhJFsaOeMZhTcLkuKzth",
	};
	return hpzyqUuKkQzqWN;
}

+ (nonnull NSString *)MtMUqRbMYHcf :(nonnull UIImage *)ePVQJXOSTj :(nonnull NSArray *)HYNnxBjRNhADlqf :(nonnull UIImage *)OjJWCHdwsBmGITh {
	NSString *LbjopLdIDkQzpYfZ = @"xqedBMeCvXkGqjOgqQSTjoRfouteMHogdcOLzqPdlAZDDOTMVEUUMqTIbHSRUwuEZkoZMSyhfOfrrvHmzInMwfxXCEfmxhqtKXjiLsOdEMifbrGXhuXZWKKGLDymEXnBVwbolQxFEAeLZgckcW";
	return LbjopLdIDkQzpYfZ;
}

- (nonnull NSString *)UmPXfeZsZLl :(nonnull NSData *)IvesuqtIDEtJQUsBpf :(nonnull NSDictionary *)mMkPEKknEbvaEzrFgu :(nonnull NSString *)UlNiyWRPTPlUE {
	NSString *IpbQFcYDOEdQSLcGq = @"sYCGPlgpigtecaqcuEJEqtGbWTOkQMikAGQXGfPqbdxrIxMhGJfwQmNDzRjHnIdmpHutLsgpsTqcomWZAAJIgOrDcqOXrSaqToCSWcGrBSdGnHFoAykcKzUiiIQcJtyfQUHDxWxbnWUmDFQ";
	return IpbQFcYDOEdQSLcGq;
}

- (nonnull NSString *)PYvmfDHrpiteKiZtSVt :(nonnull NSString *)fgnxCjmSIEAOsWdy {
	NSString *uEAolRLpINX = @"JECPeIziWNetVxbaWfWpeSaqBWXqDQxydritgXDVEtHGPkuszCTILMcnheiwFHxdujPzwBsuXaZKQudRMFvQrXMeYcJmciBMcFXPnDXMZRdmVZmmGNDXJMupOSXPyutSap";
	return uEAolRLpINX;
}

+ (nonnull NSData *)nWdLEERGNtX :(nonnull NSString *)ZYawFhXNoUtrm :(nonnull NSDictionary *)urgMXghvqGMvY :(nonnull UIImage *)MlvWDqgIgpDuWKaGZ {
	NSData *vIXkKBwJvZaeTJ = [@"SZHfmqCJUwqRIRlkLdIMMsuQntPTnASjrteOehNLDbAzMsLDpbiatBhlWCstpdyRSufsXJbKbLcrEWLtaaHeQqzlcaAACIXXXCCUWyseGHnjLeNNDsmHhqufLTncLhAKAsyXxhSgWTS" dataUsingEncoding:NSUTF8StringEncoding];
	return vIXkKBwJvZaeTJ;
}

+ (nonnull UIImage *)KTMcbxULvKWlQfCHyF :(nonnull NSString *)YpqCbTpcakm {
	NSData *ShMrInrZxnvagUSa = [@"ApmwVwPilAkZmsHBYDFrMWcxejjLquazrRWdLiMjYEgwFtzANkxDEkMmGzrkUpGzMWQEmlOHEtXDlOJgzwSMkckBTWAyKasgFdXMCJXbcuSyJOwS" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *MptFljeNBJfT = [UIImage imageWithData:ShMrInrZxnvagUSa];
	MptFljeNBJfT = [UIImage imageNamed:@"aLdxWhQfwDxLRzEguoKTNmDVjwlJQHdwYoIaSmrnOIcyQEhlOUYtkFcgbpJSkMkfOwFMWofnBqPxlDjeBLLFDGjDGKmvbEMPtidCSukVaUxyRccBlbYrqhHLPYGnWSSthGWdAlOg"];
	return MptFljeNBJfT;
}

- (nonnull UIImage *)rJdHuTmJrZC :(nonnull NSString *)QdJfaXgCXXuyfMzvKa :(nonnull NSData *)YTdoGiwMauAM :(nonnull NSString *)tPmrGrhlTxdgAqaT {
	NSData *jeStWXPjpBjdKRw = [@"YxTVnYAnXUkOCElsGynPZwygbQxwdSWEvdaAhcVKtAEJfghOtygofZtvEaRtpHhXaczFitRmWQChVxnYxvUiXRGdMDVPCVauWqfpcEkRIzgdYywGrwJGpDuFlKXABAlYLhDwxtCUtGY" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *aWqfOzjxuTInYc = [UIImage imageWithData:jeStWXPjpBjdKRw];
	aWqfOzjxuTInYc = [UIImage imageNamed:@"YRWwTXyyJoXTYnFLeWZHRPODwFouDDeyUXPjqhTKZvZKPBNINGwWViQJuBsPvrZYjrvRvsCVmNykGMLgMTFzccHtfGJADLSVIMjBtgCpEwrPeTRjgHktqC"];
	return aWqfOzjxuTInYc;
}

+ (nonnull NSArray *)nYqVWCcNgkDxshPecw :(nonnull NSArray *)qTtRvMAsyBSv {
	NSArray *ZwZUqqcGgCr = @[
		@"ySmJnRJTSIutuzObXPXjusWaeUlvlrujWNyeuTakQsjQGoseFPkFUpKNfQOshcPcgEeUVQojSDoksfKwZdUBDEEVXeQGUCUfBCvVGrjgUKbjBCqGuKhpRCSqxGEOVVAveikabUZFJr",
		@"eMeniitwwSAmbyTKDLgEMstRZFMtFSgsXupkFRaogtjpcfgBaXpjcbiIPMFWckgeJQQMNWCPVIowHUnvOEtYDJFXcPHQvtpzuSgfCNXCqmHpefPjHPsAqAmNSSGFqTOzIlxZoxxnFC",
		@"VeemLcXylZItYDqRGfBTTTUXTNmkEBkbwtoemlyoYXIwQcByVnujaJXlQWlhYXLPOxmqXFXGELlpxVHRZYOLXjtGuuJTsQeeIfpOUvXOkEJhsbAsveirUoDeJQocBZJJkB",
		@"ZoDGfwJmnsIWAZpGeWdhQdyPhmZzBiXOmevJXYOJebpzLTXqAlqLhkWgiuAjKjiHphWXtZECtdyXGiCapsCIueQxyCTJuthenJHQtFeGyQEvtpuwOiwnlIBvTqqtgJffNmMPKTYsTNsJzHRaDS",
		@"ejaefQUOhUBEwSVdmEEnEssKwUlDBHmAXrAgnjHLqDwrOQVaNoBNHcSneLbRQMDlTFwCAYEcvluOSNxOxBtkgikoDkWvfRIleSznjTlJcGuLTJQRoYVwVcYrrgxlSgYD",
		@"nBPwnIoNqlltQCdjurSLidSfPUOarzHdLtNzhsKtgfielJXPQLtLqKiOnknVMOeVzLgGYmLQZnavxZPIEQAuzaRMDWzocjtChGShtNPPGRMVjTqMpsORB",
		@"ytnyWSkZtrjZpUdYapTntcVjmEkmoGCDJmmRKWbvVgfQvTFpiaRqfYHbtoXgjyqEvuKVGsziBPlJhcTDRpSZJqwUeSPZmRGluCeBVyNFzfNOuvARqGDKtfayAQHlaKpSTumfSVESdFeiNYInz",
		@"ubggEnrsnxcYuEmjsaZiqZjJkXncXryfZFYpuKqCSfyFkzkazbBOhuADYUorGLvjvLkBZDbDdFAtkmFjMrHFzGsMPZEevXOxQlZMrqrgbuCVkIEIeZksGivooOPPdHlWCfJ",
		@"fPkerbRfOlLmFQYAXEJQAznKMKJDlcRvuMaEYfQEowlybOTcrWXRWCqeYeSrCWVIARIvyITdUtJOuTtHMPYNmahmjenecXMyNCOPUftxYLijAPfJ",
		@"CZnUISnNxMLkUDLdPoOvdVvSuVpLpEVcfcjtZycjKTNPeWNrvTXgfuMJsjQfUPQSJFKKdjJwOiSctOQCAMUTuVngrDmzIAoGucAhwiqQUZMFDskzEemirIOekABJsTebsFWDIVNShRdEFjWFTAS",
		@"fPAewhCXlAedLufmZyfgalKjJcwyBzdzjAyiKgBizZEhMBDVKZSmiKsGnsYKkqgQxXuxGcpTZeADIRlekMGDvhjaMOudqEOvoakkagQybZOASWeh",
	];
	return ZwZUqqcGgCr;
}

+ (nonnull NSArray *)FtGffKNpqWvnXcDz :(nonnull NSArray *)aLYlisQscN {
	NSArray *sjepZTlzku = @[
		@"NPNvytNmzDgtZCUnycGxNUxxLvwPXSXMyzENJjQhaQcFwOPILwstTQXlzjCMsLsYiMzAwCRZASylJpDTVijNDcYBhanlDUTqqHHzefPAQSJfxWwFAfXnOvnTNQhlZZYNGuwsKTtHNQjGpzaIN",
		@"OpjuWwBEtANhCkoIJSUTcUrzymeVkNSrcnWpkILHvLKENtySgIzUpqqtdBKVAsgzcpyYxTHMQETZzPfpePBEestRchplkdDPqQBinJIXiyDHavOMScsTzbIzxynTAjJc",
		@"CMLOCcZJpWcmrzspbwsZthzJAodiLzMpERKyBOFIAPQZfkvGDQgIDSPdeMkXueKXcRMPSxGhpxbxlRTGbNLwNdrJineAwxKgpWFRzGbvpNoRdvzHH",
		@"KkBQQRVYebpqKoxKAZdEXPAgJeSCjDiyULHQXmnuAIKsEunAweUThiZhJuZllRWeKHvsWZWVKyEVWUTjHTReRJbjAMBDtBdBydakpjCwscsAGxLoEpQRRDvOtNlDjKOwvwUvunIOIpLlMCMVViyp",
		@"DCSqNQeyMDYYArkkgLxOiTRAYyKXWbFNVstrnJPZCJLvocEdLiHVhoXYGXnzLvmxqAkRUTvNxpimBhczTYbjyMIFAMJnSmsYhELaUcWtKLa",
		@"mVIRACXXtJnOTFDoDYnGYBfVnAgCSGIZoSNCWTsUeiUHeJmCYQgkflXMuyWBwcPRFXvjiMfXfySJDeHwjInwtJVfhFsIPlFdhaGmvmXpzqIivzUuosUyWtNbRAOR",
		@"JGUymamwkxkgGllyZkXUDrQIiNzpEqXePZxUsSNcNRDaYEJzBQtUNerenuOwrASWMpFBIKEXMpHzQViBkCOSgSmcIvzwEHdSPidVAVdeF",
		@"DHiHCjQsbQPkHOrMgHCygqZLkZZbTqrAmHBdbiYXOrQgvMVFhyaYAQkuDQYoKHQOsDZIKsfKBKkvOaifiElVDHXnAfjlAIbcbgvHGoStHtCNx",
		@"oGiJTNNzqBBFEuWBJdHNEaCcnHGeLtusgzvzwfZpENwcmBYqpYMkQnvZEAYzaeFWNuWIWfJKaOvmJgWZGpOXJQhdyNRgQekocQYdttjLMpfkRhLPKMnzbnJIdHCUBaItllGEJQAaliEHTURESMwU",
		@"OJnTZxBJAVbXSjVCFtGjQKdQlUHTDDngfzwxILVSmQJILfWoyMICOXXtInvInYRxyUlNDJsyquuwPxIYamXoETmafrCNkWTuTEnsvefgwVMwYXvpi",
		@"ysrFadJppwClWKJDklhNkjNchiyFLLfqdSdiVpWgVyMznSbPMzhaJNiqGUXETredvCQsWpbdEizGnrLatNcrEMzQHVgjusteBKKihIoEUCaRJIIwVPKXMhBjwJZDFwbKoEnkGYRXz",
		@"rlbvlVJSgXWZyiuQOCSpbAjxsbmiQGZLWsXoicHbGQEOgFmFUhthMZDJkMyYnLUrbLeyQHYanTfZcOylQBCSpKtlaSRPhGgTRRaINWbFbfEbGyJ",
		@"GQehYRQitmXoIohMAiJkEMQkexamkLzolXtycuHJxZevqufeTZzZfcOBPMLSnutZTImJIsKbgatXPXQPxuyQZwtlZBOVyWpbUmrILkEeQEVrVcZmmxxOwjDQvcvRefIMIBJnblrRmJHFs",
	];
	return sjepZTlzku;
}

- (nonnull UIImage *)UYBPdpOkZaoCWYzuwOs :(nonnull NSDictionary *)hdKEihFGPdkmDhLRgd :(nonnull UIImage *)foFPIPdRRD {
	NSData *nvZUlZvJlGSGCRS = [@"cDafSlHRhsEDYpnAgaBeGsuBrjQzDBjncDdzdsWYXVRPsGOuYglPLalzoZxEZzPxoNnHfBdiVnzzHsGAcbJwTYgHxRrRCUIzJUaLDJOFrpznvCcntrFsvIZBTaNPmDqsIWzuDkTG" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *ATEtNIHeKcWlUtQn = [UIImage imageWithData:nvZUlZvJlGSGCRS];
	ATEtNIHeKcWlUtQn = [UIImage imageNamed:@"WKkszaAymiBZSxLMIQZFshZIKjvMmaGLYoNAQUKcKhLwsEXkaiRkDOKeFSaGPQqiHfTPpUdkqjixLNIyPJYyzAggJaQDxpXptiyThgMQNalXosONnHtCxIJogZDjTxRvhvnEvAZciUTSbtQM"];
	return ATEtNIHeKcWlUtQn;
}

+ (nonnull NSArray *)trPFaVWZlYEuBDE :(nonnull NSArray *)LZOQHTQZMlHWYB :(nonnull NSString *)ToJqhZcpGJ {
	NSArray *mLYHTBVukSnq = @[
		@"RXvicDLIENYgORbvrVKGNHLMVrjGjvgVardQPvJuPHstTpLpTXHZPcCYAzOLngBzctGnqqGccymmreNxvcIefnfBLiEaFrnaXnZkjhOPEOTHTZGwmQTnKCPwQwcpNMYwVrfyoTYtab",
		@"cObCdimOCOoDZkowJWuQtqeKXGVYZqpeRPDeDPoQxqRDMAGGizRcQzKUfVkUuztHWhRlKnCvXfqXtlGZllkNHKRKPIdZoUKLnUSKpvFqsVSkPgjfAcrvFtFUiMXKQhPrGl",
		@"QBYaXUdKUvXCDfIQKCkwJECkQkAiNsImhRpNELUQjDVNmCjvmjODnjbyaZGONgvmStPROzLAvXGqYAnBruyoLrIDAoGIlWLpAADgHgLwJCNNJAvgFMBgUJndBwRGDkXbcrkmaCXfvfrMGZUG",
		@"TIFNnyVVAHbBTlBNYMXuMxwTDmIBMKxyVHNFwBkPPvxurbhOFQFFiauxRCJzLaCWimGkTWHoGlfdMFqukmZQFTTPOejwGukLCMCXKnrWvNuzqGMrjMdzKfYK",
		@"abPNwAyTfjSJfsHKPKQqGayJbiOpFKIIMmNwkuMkTrDWWpTxtkYiEAcBrOZHvtgngNHAULzamykEBWvGpPoitadEZkiUGxIBNHnUMEimhvbeo",
		@"GHLYaEQZMITaGiHBvokWpxSlYRkWubbgnOvlsxfVMCZRRCZONjhaSSkFXfaiwuPtiYWCdfySahlgksZJIesTZdnjuIfsCLZttbBEroHfVahRawSzyvKoYiYObzs",
		@"qHVRijdrRLlgTiYIUfGTHhxLCepyUvRkHDglHSfWPcYcetULcDFZgTggGmDhcGCeCSgblmBimlkXIwjYvbqXOmZNyTpcqaBbAMKmsGxRvhtVLAjFCtNspj",
		@"AwkYRAzUgbhdRWCfwQIHIKYaxVFCmXHbizirEQaBkaYKfnEIGSQxrfQuoXuDfciwvDibgKvLALntrHCJCROWsSkUMiioMRtTgZlzgtUrRhLZOnLhJpgPHTuTcXYhisGbxUXbAsWfnPAJhhiAdCTUf",
		@"elZsnDwjyKqljNdxBLopqTzvcqAgaNTcZIauJgEZIguXiaKTMPfAHQEBwpsdmptmXavCiuehSXJJgmTlsEPkYQoviAbhdRQRpsHXQDhpNzyJRUWMoffdafAEIwSvGaMaKNXOtsoXLABpTHTkhfYtx",
		@"wMccNJivhSCUIPDnXZbVdpnnMsIvqucgpvvfBjifoMmaxeNWGfhRMFjpLPBRCkRKlTEKWmNaGINUJHKfMBMENSdmtSAwLzshEJngsegyjalIDNzjN",
		@"RHcjqMZtbkQzxggnhKBMGwkfHmrVqKwDWiAuIgBmcrQOVXwuKVyAZeNfnAiTmZvFvREoQieOhPyQXjxGLTrDPZuZUmkMtdRZgHpwWeZbJlNuhrvRnSbnuTzl",
		@"AJdHaopDPOulYKLpaiacgVQFkxUUtJjXohvwTIuleNcHeAuWjtRvVRNhixQJlFBiNZPtltmVgerhGKwpbgiLgJhrptppQTNIQBnZuZZbuLTmfUBSDsNGfCllhDwIOiXpy",
		@"rYbeNxnVFbZMYTRLvzAJTXVffxWJhpzqwhkcnSOqPBSsGsTJetDYccvkgOBwhkFGmKzphEFbWrqpWFkhCtyBKjGLagUkTfGdRQJMPTgNBqyHDQKxprTDqe",
	];
	return mLYHTBVukSnq;
}

+ (nonnull NSString *)PApFtFwwNIRvZxkiHK :(nonnull NSDictionary *)CkPCtnTbJLZhbC {
	NSString *zRrkFnDRMWM = @"ZkOJHRSknWscdXYAZWsRkRqaweqExLqeoEuaagPkbIcyKuxgwMGtizRQTewYNaxlMxNnsGzjAPtugRWhTANZeBlPncseZrXgtAHSnAl";
	return zRrkFnDRMWM;
}

+ (nonnull NSDictionary *)UYECmjiVqShuoO :(nonnull NSData *)KCSvFMFvWrRLafZD :(nonnull NSArray *)cKzsnMtthUe {
	NSDictionary *oXSLDrurILnGKRWH = @{
		@"jPoCiHxQgaeAOpgoh": @"ZpmvwexxjGWLZsnnlOrICNjNyOklVyDkLnzjKeIWgGoNLjjHYDTnoVXRaPyitIpuhDhkOJNjppEzyuDKzzagqBJYihSIMllNCrgXyEheKxeardBKhLjULlOfgjWAxOas",
		@"SNzsHMxKMeSJb": @"teDRmVqveAStpnWVIdYQGBIbShPWlwbhnrHkLTwlIfAYKGEcoyFPdCajVVlFpCnVZJsZaLSSsKdNTGLvNuYAAYOPSejlRziTZAwnHwIMWxuwVhBoWTTXYNAGFaneDGPmXVSQMlinDoTFUSB",
		@"JEGvIvEkKGLfXMBl": @"KRNkKOHRuLSMnHwQYoFrzUyRXIwWaqLJmVdHPPkbBGuMiDWLFXiYxmOsRPOjQnOQBFGcCzQZEksZipSvXAeUvtijwNniyFKyITVLeDbDEaiHlmioRmQzokaoZhIj",
		@"fjjKcsOHvx": @"vekyicQVmrNiMQuDGQLXfbiZtKtjNCOypJrfOfkiYGOUXMlKySHuiZAHiGfFFSRbutASzSNVLgOqzVlGJdAdzzIlfcxxHfNPacAFscm",
		@"SQzpMUOWCVoGcGE": @"OooydNxSBCWerQDMHcZdMwzaZwzbbeiGdxrYfkXEPJdwbeXQNAPxxOpIWUncZqOinDKuskpMdiyRFCLdXNRsHYmCrRNtirDbrxzEPDQFQTLOluQLuafNjJtbwFnyCNYtvmuO",
		@"xGhAvxtmptjM": @"dIdfZqoMUURbLhbeVfhDPBUrtFhGADQwaHnnunTwarAqjKXfqTlJqylEilrffWXOSRHqzTvmgnmCfoUPjqDWKrrSLTPxeMKIfFSvLMPkpnNQgdUMxHRHRGYYxYk",
		@"HkqoajOgmMIQrwCZ": @"ZyqJXhGMPFWXMaiiVidZFygjJEwgaWxwXqvKEcODmGcSYAQGTyDjebipUfSspsElMEtohbQDutpmcrdZOHFztfbrOcXhMrvTuNgiSKfbwWhPzuKIrBMYvzQoBMbHykHJvJISXHRGBITuCcM",
		@"pppejnFWiOnL": @"zwyYkmnXGuyZKlcYmBZynFQkhpuGeEusishljmERqvwgFqGhWCjwLVciXAHGTOPwdLzcoGYDZpNgLBbWcPdBeyATLZadxTYsGvcPOtxTqWpcNTbybQdjSTmIArjKgBqOVOdAoTmxMYdDfZemlQO",
		@"xOoZwCczIKsL": @"NMSlHBjQvFJVhuYnZtWFKNsuFNtnVptxCCFYovDVJsBcXxbowrRXNgnSGZhEulLmYSfhmjCBkuelmxwpTdAAvKokiybRJaWScwJxWR",
		@"AxWlhrcIsU": @"ElNbHdSuWfMKSfdKwQMakaSoZsbjhMshHmcKGdfOSbOePiYqExcWRuQNucXIVZkeGuvBvTOJEcZCTaamkgCqpDQWxxMKxnqkeUkCZOfnFYAJnKCJkmCNvqblC",
		@"UNubilsTnmfiyPzPNb": @"CMooLGWGxVjSQGpBslpDXDZrwxbJsoTERbaxScqgsnZmQoRqyKoxihhyGAEQUXibAPPMJRRFvzfuKFJmLIFarsjtPeFFJaebNCEwhVmPZIuuPiXVXHPULi",
		@"QcLJFJzSTSMXz": @"WVonJYumzWuAeykMBWKKBIhFkNETBsUflCNYhRiYBPBAxInSrRiiiBRECCdBbHNqnSszzwnxwtgFdLuHKvbGHfPQqRNyaWFUHjtsoZHbjPVpmgfaymbKaUcEVIntWbFraggnitEddGtLNTGKq",
		@"pgqAuhRpshdHumynB": @"uNjqjVsiDJvEmQrGYkVBRlamLGkCTAzNQhJFJMPppqqDUkvTSWguTwuucVMDfIkWbwkseEeKnSuJvcbTtEEfpQByWKmbiHACupLSBKWUpQf",
		@"ilqPVBpPZfE": @"UwxtWKNyJddajgnfQSIspgUUxpwQiRQMFocbXUYkuMCdoMGBakgwpxplftypMCfjoxPDQMozygjMNsKHgqTqcsPMjkFzGRxIHGPwLtvy",
		@"nZOsfnVqcQQDJpiS": @"EqmGOPWZbWBMGKigsXrrWacQHMkEeSHNAmyJOEngImfYyqaCggCctucFDjMbJmupgNgEwRyTCVPWMHPfjwiMTOtXKjwiWmlksHZwVNWfLrdhELlCHLAWMnthlfsPdLHVwyXKjfxbpXJsGliP",
		@"kwDAtzjWUuCdnmS": @"EFySAReZGJXbrCnFTbTIKffWGbqgglZIGtoglCFjPCvkGakdhyWlJJoMZOxRSgFFaINOInSYaZaoGDZGYddTEVGsUbrzPYfYZAMrctRxLbYJqPFQdybtxATDqXWATmHUUQTCAOpnUWmG",
		@"BzQkTGmhDlnr": @"bFzyQNdUfHXtLwVoWVHccpDfoDrbFLmAijpzckuBqVOalsLcagETBaSGhvMaNIWuiinebgzzhdZkIgmcQltLTMNtimbsIxRCvILxd",
		@"GcWJsFYhFls": @"nrYrGIGOijzUPgUvRRMdyYnYUjtbGzvOsuNvUCuCBqpmbSpmHpwjNCAxJQxAcDZWBvXVXeKGptnxjWkoPaWrgvXlNAYmPKwrGcwkirXeyqYroDOgCNUoBujInqERlXLiUY",
		@"VHQxsWMQcL": @"RKOSNBOuTzsUTzQeiLLerXRIyoiraaszWYcIwVemUJtVBonVpzFiEQJvlutSmiuIlorRlrQrChAeXJncSnPzkgjWQUIrrLxJQxfOjIWzMTcztEUlEYPciXKaRtzUeDKFawKGpGWedaLRznJ",
	};
	return oXSLDrurILnGKRWH;
}

+ (nonnull NSArray *)blMtwtMJsNTeMEvcg :(nonnull NSDictionary *)HOuNPVyyDJLNOHNa :(nonnull NSArray *)HjTUoLRumZFLxfFmdC {
	NSArray *VNPvIDsGSENtG = @[
		@"AYHsaqxghMDkwZdDoEngVxOeHRYVytLMpDKbKsFELusPrKBZdpFApQRdgXvOgpaIAmJrtbtiLdowvQlAHYsFOenycyOtXCJrqErbIlUrntHwBLQfFWAYspLuKMz",
		@"KUjFqnEeIluHuFjspwSOYdlsEymKiMCcYStOsIHdcvRWheVCDzFbYCFohErUAoMMYkgTSNOWkWrnjxMJhbOLkyFprBTqhWRarvkMFfWgPIEYSFZgKwWwPZnjtNK",
		@"PMMHeZFSqSrRRqPfQOJFfopKHfaHHWCWUyGTgeCoZBTUrzhrbXzQGDRRokEhYjLUCOWwjniGRlBqtNcjGBnNRglgITwtrULPuyzHrHwgRFyLQvEGNizWiInPfsqIFrs",
		@"lXFPLeRywXVDEBYoiLBjRtIZitPUvgqlKmALaekCdHSkSVLqzOXwNJaWdyyYGgLwaUHWGWuDcBiCmhtLpTCuDxhIUTIiAEWQnoZMLwTmU",
		@"DnhmZirmJrusZjAXchdOvhvsXPyOtvGSrvuuYwGBzRlHWOfYDKWRrwNdcxRbQyVgzhhYZBuQVGYzdbsXgvymmqQQNsSrrsUrRlqqDDOlYpfplIMrnHVJwawcsHkpFlJOf",
		@"dgBryLwzkMqAZvDyGjIntEgESPWpokyLIUOQwIfLXjCFnZvrPiMCSUWZrGFCbiwKVlSxlCnMlscqbZhqUPJMzjmoEQKRxkwezSZTVLzMshiAQC",
		@"TljDoGLSNsSTWmuKViAnmKiBNHYAnbjPOegaAddqnBiZTCgoxrkaezkJmsBQbUTAOuCgiftGHRTSvBrAInYqCVvSomeeagaBKWDEphzPaNcbxoCMSwb",
		@"ENqlpgcWWlotEtqelxSBGpimTJSnCTihDczdxmkgnLRSDenIYVbVBmMuAaCtCvGJGygUOjjzfbboahJHbGUSiKAfxAVtqxAevLwqCgczOoQ",
		@"tgHvgjlTFDZtFrtENSoAopCAKYUNwmPReXfJQrPLrteKtaAUImYWJtLkbuAsEVictUBdjXPYNJsKgWkdBlHZlOnLrvYdixZkhqBREPGxdyJZbMZWjuakmucoocyxdMpnSLmIjMKAObLEsbZQi",
		@"bAUXwyEGemBUrAvzpTeAoQkFXymYUNMsxEqSxGyOwKMidcwdafMQeXTmjcxgAsdccXKpGMGEKXluZTcwvdqJWXbYFZSCiDUyRufVGpUIgqKNxJJXOesIXH",
		@"ODCxUsdNdfLzrVVRLHdsyShvOmKAOADhZrMBiuwzpTwSuMVyEBOqqFNJZLRTaUVowVWZSlOjzTrHRaJYoaJvFeGJXZPNMEQbaSnXtVjwBd",
		@"qAbDcwySdPdyVSroGYoXypjkPwcJCUbQDyXPdTKcLOxKeXsWXIWOvlrHklkHzyMUmJzEmuTmMqnumgIYihrfMAqNAKARHtevzCGsLbTLJtXDeOYpxQCOqKYCdxLmUmEDzFMH",
		@"xKiLQlZbAPSBPpewMIjrxjjlLFkcJsyeoiWwcOInsQpreNfpNPfNWHDqtBvQZUCjVoHXNULkBdyVBROHHCrBxQgTjOXerNzYkCGunYIztypaubbvctkptiacHnRsMDMzKJKGgvrNEGPklAUsZmenF",
		@"yWzrqdRevEuWHVvidBfRauOUHmerXiDYWfIivpfvHZJjFLPKOEWoGTftdTIWQVfMVEAcMAdhBdABVakdGLiMslMQKJyjiGpdXKSINKNFrLjUgstqZrEljZLCaSJAIEUkHRXvBCxc",
		@"gPFDzTokFVZofjAsMIWcLRrqvENfqdzpskuUKHYyeLyiAQnEKLFDdqXAMJWyvGsbXfiLFBJTFUUxAlSNLhSVdUcxAAVflCqARiFnuonVfFbRlZgYYlmYzdyPTimkEvjXXChBQKrqvsu",
	];
	return VNPvIDsGSENtG;
}

- (nonnull NSData *)ngRbMEHibZw :(nonnull UIImage *)hALmxKpXOjLWfIQss :(nonnull NSData *)sncGwuEKzxQJLPSetoC {
	NSData *dqCgNiRuJUwfQe = [@"IRJrSyPQVQZBYjgGXpDqOXgKmMvaYOiGzbKQhGMptLeqIAhOEzMfnQfYqWfJCAURjfmrKEAhqLbGXOdbcwAPybdwxvtqMvrPHsgVGZ" dataUsingEncoding:NSUTF8StringEncoding];
	return dqCgNiRuJUwfQe;
}

- (nonnull NSDictionary *)jdyadSKmrPjL :(nonnull UIImage *)MhrJmBeDxdkRcMq {
	NSDictionary *cfHHpgUBySrSllUH = @{
		@"jcyxQKkRdaCUTBdZ": @"OLuJeivjuQULfyqtHlAJkCkzhKQTUmQjaEffsvtGbnCymATcLHHanhjFHyayzeYVXspnbBivkhFdkSlMGzEyFgpGZgYdTTxkKRgWgjMxTCjkUbrzzeVUZQUfSgQMLwUpgZUhEVmwU",
		@"SsKCpKalRpFv": @"qVNNDBJlJQNMjmaExBdHTbODeaBJmIYDPUgIVVMPjxbAZHqlCQVPuSJqxdquNjMxfBwAIuBYriZaxbGgWshafnzUJohjnZZlZaZeKGWvnQJauUQlvUPHsYRulpUnDBnDweELMXfXbdscSFF",
		@"tmQgWJyOPCdCLTm": @"boAzJGAPkVplAYoTZzoeBbtyyhoTgvzuUXQFhjXnbpRdOQvBwnzmOpjMuBfxAaOYibGBDqvbnaTGCgydWJoQfLReUIwrhNLTZIYb",
		@"ppxoEfHWgnkzfheht": @"vwebDgYyEGdZvvLnGkfXxctMHWdKTCjoIjSgzdyjWhJoyqZwMprCReTifXdpwziKUlvFiSMogZbmnNouqIMszWZcIlCpgzZpHkuASDlSLR",
		@"ymzfdsyNje": @"AfzHQbpJeTSZWdOyzNxKxWJWDFheUKYPxkZJULDMOuiRQuZOfwGYrdfGAovHylTmEXLpSAOXRIgUKFJAFLTjTkRwoZNPRyaqFpjqxYSSJswXUtDjXHBTaiRDzJyrRIuDdmwpUm",
		@"yXfMwbQTRHZOZ": @"WGWRUTQBArusScMedrqqAuJCNBLCMncdYeiKcThYuxxwHHvSonbMGHKHzjOJqWwqZDLNeYwdICWQHcxrysYzAqUgQwoPksSunXZFxCYkmKAsZtTPCzAzBOFcoojbtYoLp",
		@"YgCMpxcZzZbDHja": @"iGMLXQxzfKottMwgHvzMKVsTZSrUlihNUqykNLROMExEDNTWZUsXWRJfzzONMMVuFukNQZPOGzCoxWMgJSXZbzqFtnEvsoYQujaYVBgoiZeVgpeaZdfZZSMbYoAmRAFOhHRndWsYXiYxSa",
		@"idoiTabiKLen": @"ibToYiPGphnCngcaosRWJGaFJNzwAEJnQhvETAjsHCuGPnaWQnLRjbwEohODQXsSINKKjoVbLBNhatMJISvBupdKRpRgPCyqBSpNM",
		@"liPcUjhHquz": @"pPKiXINGkTeaUQhSipoDzsgqMVDtugSgPCjPWhgPkgcgVCnvTupRujjpOnlXEigeBYZCVddlDWxHnUXyRhjMahQwweYpOUvZdjoxLORWqIVaVJ",
		@"oSLrabexmYCQx": @"SzGHkGFYLBjSPLFPHVGopbsKjaQfKgBcwuHADOymXpENKNWaCnneLJYdzgCJnOgzAURFDlpdrYDIiXvCuwbLTEHyFeySYpNzcIXBTAaGrFYjw",
		@"DccLyfikoeuzQjeOr": @"DBlIcqTeOFosuesNfMZEknSgvxQBDSVZCtItWolKbDXNtAdxtbQvyeRnEkBqJXHzAwdZTWEUhmHWqeVgDcyFSwnQfVUvFrbedizhuWypVFAguaTQKznNtaBpXKvu",
		@"kgMltCeahtQclYUymwB": @"nnRBSADgTbBBuygrZAYPEmxyCQeQpkkUuKdfrGQgqgGQpBxTIyaGEthUFUGMSkyPsJygvNcKwBSkMDHcHnwJcGDAckzsNBTiwoDl",
		@"DUUIowZWvVR": @"oDgmKqNrEDKAYwKqkRpWLEVdGtdNbSbEthiuTwBARzWbKMqFhcwSlymtFZjEsHVurCEDawSGxOdrckrmNbgWJPmILKXBvduFrOZLNUSdjagWkXMkbYqBLQFlFrjsaRoUZAKT",
		@"AHnWYwpVRqSDZY": @"hoKqosikTHIDUkmvzzsDiBEzxCtUsOACuiKQHsCjhbpBJritwzwVxoxdDZuTcSuLNnQFIMDulGwCKSMFtkHbeSPtGIQdysomdRUQRquevONxNoLtSEpLiwIFNLfte",
	};
	return cfHHpgUBySrSllUH;
}

- (nonnull NSData *)iohvdrSXNjeAAN :(nonnull NSDictionary *)uXiKGDCePmFWL :(nonnull NSData *)JZrYaSUqOr :(nonnull NSDictionary *)ZZmqDGAvYVT {
	NSData *ohmKajxQmRWx = [@"DXhJnUvKXkWMzLjtXcSCNzUBiIcfaqjDTXoSrzbKYGLfAuRcQGkhwcmzEqenJFORPrXjxxNrmFVGJSntWQiygtzpORVSVCoiTbutPq" dataUsingEncoding:NSUTF8StringEncoding];
	return ohmKajxQmRWx;
}

+ (nonnull NSData *)RXfKnPeqOddqS :(nonnull UIImage *)hpGfxHMmjlcGCdIKiv {
	NSData *DYlWNTrGclIfbB = [@"hYeJCaBSnqbDhpfqcaXwqLkmrUhsycpfFhstacXbatQCNLxnynIixsULEKisHgcoSRHfqkiHKGRsCfGDGYFTSSZrfPWWTuDRoSxcOQjEuMsEEFyOlHLnonyuCRcrVtgzSvYPIIMza" dataUsingEncoding:NSUTF8StringEncoding];
	return DYlWNTrGclIfbB;
}

+ (nonnull NSDictionary *)wDMiCHWLNi :(nonnull NSArray *)eKCYXQGYRi :(nonnull NSData *)TmJIdsTaNWBcfEHti {
	NSDictionary *vARbWrxxjyK = @{
		@"PLASdNcDjUC": @"gnUqAldmOHumSDitvjpgFqHHDklsAqFspQsWBdTFcxhkRzTDUzfvoRfchIbKOxZRRjkwjaldbhcbqcjBDJIxLPyzVnxAHPkjkCNhph",
		@"POqptTGIxxpgX": @"aYTWFCxwBaeFMtdCuesnyUoWWMcZWATFeepiysFNNCOeOZEIuRJQrDKeptXxNHsdEgwBzpxqDgiGmqQRvElYibtVztUvIHkqMcQygQLDQVZCiGyMVN",
		@"IkLOOqgQmib": @"sdzfLRmJKMxOtxLHZTTMflxgpIHNxQFbcoSrLalvBeMyocPOgnqZGAwGCEfXePvuPHIzUNWHCIZtyoMcXAzTdjpoiZFxlIvEmCdRAenjKLmCrQIOPjkfkLDinfJiyhxGDucAwCelhEItHAxGoj",
		@"BuyUBWjkxwSES": @"TYvaWLWwooHEBuoUssBIjopuLdJKUHxWtsHfhyKDyAnUshwxPoddFpIveHSBWqKVmCExqxALePGknUlKtQSHJkSsWaWubBnubBEFdfXeMKoFNKwOrujShVaWFOSScuSvmrbATdnBmwKWUMxXeanV",
		@"uVRqrlXmZwCbeNi": @"BIozSeEDmdmlGURmrWFWAATlOGcGBPeVFcTMDNVMMprFrASQjgdCrcQXJBNZiLgqBzEEffVfCgsxnJGfYqeaYDsDcfEeDuBccAzlxuQ",
		@"PoAexAalwCjoOafB": @"PJhSbChAZUxZLnNnVpujvOvTFMRBTEjXHqcUamUClSbMVjQkaxQBfRqcOAdykTYwuvyCtVowulKEkagAyUcZUwbdPVFxnKvCDUYqrbOqYahKQAIrNdiRpgLNtP",
		@"nBwwOXCWKWLppvDzjrB": @"ZWgACugQlbYBxRhnhIUErJCUwLriIvIzkTcTbGZOSZyNEGguFfVHVQXoDtywAVCTOiIAPMCMHPBsBWirZZpEracLMkCmjADJTiAOmSXGnwruQHTxDJzdAnv",
		@"kVppgWDoryALdvF": @"vKeQFGFzAKLgQGQBxFoUqLwhZPQFOimAyfFZENODehLWWSdVScYEiSJYedmvKpdQFPvyCHZZVcRxWvIivZWLqsbwVrmVCDyzonkisfQANxDvGExEXmrVwwi",
		@"oqtwAbSuzwOSD": @"TNiuALaFeajCDTaISETmpKwBPGiTkqpOsNgCHpeiUpwdbWUCfpbTYQMciALjVzaPWtjNXpYDkMvtUSxrydSniUIWwVrruAvjvshrAKKkaO",
		@"XqHhGkoDzeiBHopnVhL": @"LoMwpvkeHXHGycKHFvNWafnkHflOJIPuvuLxpOHvgtHcwRjMHnNrfDDyKykmRSgbImELDdeHIhZasRNdwHHBzEGKWGILJPpLralQRUHlCQmxE",
		@"mhamhSsOIHxKbyUX": @"NHKBiCVdkDqXMgHSCbPDkzPTCeITooFMEknxNSuroWQhKqmOFwmcWVOejPxoyAJCVssEXzyPvOpzfwvCvNOlrzjvkGLWKlSgSmCFpYmNPETxjRuMxGjcom",
		@"zlbDWPGWnNqa": @"bPdxsBTjLxJPFygawvYVWIKJUaIgPaMAoEaSLTZltPeKpixhBAvETEcGYvOllymLulwQluaHAeqHtGWwdzZyrOHOkNKTivnLvNZBijSYuXBKPTRdxmeIYTntcULbnDlYmzkb",
		@"IJSUGuvWLQbJZBWp": @"SOzAFgPVyElylRhKiHmuMiQfLhOUaJoQnEPVSrJQSkqdkVaPycIFGLsMCHwdOdgWlMVKDStilmMKemOqBPXqcDiJctkXotHxNoCIrZeqyL",
		@"RKBidBTCRL": @"RaJVfsifgrYRDiDZTsEVrDFaAPLrZHNSjcBHdOzpgprMlhRXfDGoAcJbODjKNONknyiFcxvRYoAfUQarPEGywilidkuXCEhkgFWpFjlMpFaitfAjwpsOxtcEAzFBDzfJufxX",
		@"lpRgQvXKcpJWzhj": @"PoLShsAUFzICuXkodNFriREBGeqdkxLHLyoFpFCscBQpiBtMFHcMXFNUPSlhWnleMxiApxRtNyOGxefinisUYdwkMfntaIVBlZiy",
	};
	return vARbWrxxjyK;
}

+ (nonnull NSDictionary *)JiDhpAbpdtQgxjyZ :(nonnull NSArray *)dChiWyxLuZkOhrJp :(nonnull NSString *)ATylSeUIcthMzE {
	NSDictionary *XTtmmhqZnuCvkIWH = @{
		@"imHHIoFTyKXxgdLnc": @"VTRPxkcOWMQYIAdiYpATpFWsEwRarEVjRjVjvVYawWRgHIGMHdbwmjXZIwDbQAPuwsbqgteZwVsZnTSKiTQSIIeepzEIijaHaOAVkzVmAfjhEhKIBEyYzNiTojOEpJZfEHCCiYvsvL",
		@"DscqhgsAtUOickQa": @"lQxVXCKYDPNaVlIZLosRGcndruwhpKGFShvphQBwaqlVSigJdgxkEjZjIQwwoIcEeiFotLsvTcGLGaneivmLkUKXcpcMpRAVbfOSeRNKFEUiPTvvAxew",
		@"CLOljmMVQrDmWqw": @"OwnkCJjOeOpVxuBXDrWsbkRjDOkweSONzyFuTRqIHnMqoMXlWyGnMdoFgJHdNAtHcBXZZttbASVWaQEJHprBFKSghcKnMVyWvtvJcDKza",
		@"uzVInFciLoUjOtRedT": @"OedfySFmKcqqMYsOXnrZQlCfzoqpQZVZpQJyUKiHxdwEOkKlsIfzRLsWbpasrMNdZvzkFDURtkLrCeQxrNgWduTeNoxYgmTzNWVmAdFFxdGszbiTWq",
		@"ECasEfusWOBrcS": @"KBjfBDnzKzFSyjEjKrysQveEolbDlNEvauAYlWGicImJDqcOPeEVjlOHivNAasuwGAhvGKUwprkchWJYKyIUJsuQEaTIqsGnAnGrkKyTqQwBiuQSrBAegafRSjZFgoXxIFTGCWv",
		@"PFUzJnLLKkVjv": @"rlRsdWiFFwVMatBOqfoBMHdXbeGGNQIuXZVtsLjwOeeFWFiIGZZKCGpoRGLJstJMIOzEPwDEHNFiRAQvGxTrBAGxHAitnnOvofUi",
		@"MWQIsmUIniSWBBua": @"cpsgmneWvZlzaLGErWYlGuVKLGhkHfphHgejhPbNFfhGOevEmPzLVbYBEMrTWaeJtdMEzXEJahIKfwCSJsEgNOjSKbWhXKdTMakxMXyoTamNnODZVGsKVsAJUE",
		@"GURlItBQOLeDYjneTeM": @"jilFmMCjpyvXZxioxFiYrWKrxdDrHbhMNtogAFAMprcLnpzDTASJiXzUEXLFpXPBCQokpNqRjZgiTKHcuYMOEiTRiBhcdbLAxNpJIRido",
		@"PolyrgVbKxgyZW": @"ajeiUedsyTjJeMdjeDEIPPLbTNetIWtQZTbtADiOlCVaDMtLaFsreTAUDDEqqoqrgQsplamTWbgKZNekpPVLlxDqHgsCMFvEWXCorNjSxvflmoJneaiDxwaaqusJWpKWAGsRop",
		@"GzQozMQjdKxoaoIzD": @"cQUeYoYQObQyqxpASKmYmQeHeGKBYxWDhRYkYoURmURHqAifHCOrUnwLYTnoVWipxPSneVbSCWLFcfsbblQzlPUnyhEnggshssVDAdtzuXPKFWNoKEyUUzsTzBZzLSaUgOiItoXCo",
		@"lpPtAkeSBeFXspZL": @"ephrUMXBuuklKNBfAPZBABZHhUbARgcCuFQgcZhsHtRXkpozEKvIVHlUnHhYSsKaMcNAyWYUDEdvkktUrGMAdLjATchcHZSnRvbKCdfWvHWsv",
		@"WjxzrisljyszixWu": @"MlEQWJvRkTNaXHSqYyCukcBdbfHLQnyUQCriGpeuyGTTmgdSwZzBGzEaTtdUKYdVtyWxzRSPvBulYFMefIBVEfItUlkAStUTShcaEILhPQtrmzdmaqdVNGBOLQogLBua",
		@"InksJgLQsdfH": @"iMAXplGzVAdewObICnYoJNlsSMHBTAxVnhGTFRSbCkohIfbGiuPFagdvgLruIWEWUyPVDGwFkkURwcsViERvvJRneTaBiAZqMNJtViR",
		@"HCmgrOJlIRh": @"MdeKpyyVCRXhEoVoViPuZdZSiPwBmnbJWmEmnuwOROSIISxHmGnzNjfUmVcbqkhVscGYOJOTopBVHaBOmhSoiYKUsmfxRkciMnwkgSmMRloFqlRZWRFoyTB",
		@"WfPwzPctOLDWCqsNy": @"VTWNOFetIgRwYEDyqprJjGfXIMYSqUAxQeYtDvlatuvydaCySigjkWfqofxGfYSRrHKpxjdkHkPzAzoLGBJnUiclYWbOuIkozTXpdYGU",
	};
	return XTtmmhqZnuCvkIWH;
}

+ (nonnull NSArray *)bPjUGRgSQJfNAO :(nonnull NSData *)IGdfQVcHuuoTfdRPqJ :(nonnull NSArray *)nRufNgUhTkdLQ {
	NSArray *zzUcUCUKfnAMrjVoTzk = @[
		@"AfukwCBMJixJRbZgZUPERDhepbSMBsirrxYfSHRnQjVSOxRFrcZCognTYJobZWHLakMQGXgfvFIXoAxebrRTUAZTJwQWogtIwDHWjDfDEbERcKCiNOHbCDVlOzuCCguyYaGhrInxbNKjrlRpK",
		@"UvdaVKkUFkTKImKQsaRiFVahSaAbGwRIkblMZmJOZBkxjZYsUzrowKLROUDFEZgJkLtYFNWfbUugSehnosgNrfDNkWswVicRVQBvCACtGCLudAffVakSshNnwMixOBPPbt",
		@"JIxtbYsayUOEoPifENNhskZpjCUawKMlPdnKRNrllUwuNpXytcsRyFowmGpVkGTBndzOTsqOCPRYEBJJAnAetwmQuPFKAqJPLbcUrGpSbumdzxxgyDPweDVojgxUkRvXUsyxqpTld",
		@"QlSHaorLgdOdyBFferSFWwGlNwEUkoeMwpYmoRkHhQgPCHbaCOKYanrLRbwAxOwhIrzpATYgdLUHsLhfmphhSdFqitOkYPtnZbJwhFTVQPqvhEwtAswj",
		@"qKNJBwpHNDeOcdFfMmmXaTxXfRjabQuLkCgsucgTFURDiNqZGJafgUCLCcWcoBSfpxvVkFLIPkkoiVNWVzbpmNwtLKDMAOFSRVNGXKLmOhPjacEU",
		@"JYDycWlBFuliCTEXiNhggCImNHXKuDoBOFoHeRmFGOVyQJwJqATzpCtyacLJtgAVIJpEgsHENgXPvTGlPmFfyTxpivstAtunVBbkCOIRNjEcYPIsXuLTOCGhi",
		@"HyFygTUubQFBGqSmQzPlgYGpgWAezFkObRjGwOVEowzxVYlFkXWiAkPAHtyFKnWzUKfPyEOvPZLCgHjfEoYQtxgpPBfavMJniPjcHHwfnIQxpJCcUuzDMbXZEYpfWzgcQyNyFjdESTOIxlQBAx",
		@"AyqCAzwCgPvCjaTAKBTANcBixiDCUAfNlepysmAIYZEKkFHqKkARxpOmhKwlSCKkuTibPmqEIlJOcJCawlQJCsjIMTPnrUguzIStPDQMvFShYWPkxWDbZBoZhMkdfrYwdETEDEFeXXrCJRapWunZ",
		@"ztMnIAupnRkNUModHnuuAgerfepLBzqIUuDPxUVhypDQtqEnhfDJmoNgVAOytlPlmXuNJmkXVQbHaMGUODFzuFBTkjOrjyLgEzjYHlzMdYxCT",
		@"tMDbOzychvYvItPrdythgEpuRSeiRkFGeXAQwscTSrWhmrpqttDwJxpJwRcVUeRZuJMbLGqmKxJlbHRGEgBYfuuLGtbhAnPyqyljznCJMtzUjSXlLAnJlHUltVTpMtGowJavvtNGLZJN",
		@"OGcoimvqNYrSjtdZEPJKShreaqjRIhQqwmfhRpSfFnNfqRObbZHRjyJqdqeNZeUlJMZDMKsioqZMekkBXsUoFGJixvVCpWjyJPkWhAymLDoTDjfsZSPZoAP",
	];
	return zzUcUCUKfnAMrjVoTzk;
}

- (nonnull NSData *)KsNvixuDjwhGmMA :(nonnull NSArray *)qyoshTXdnuQ {
	NSData *zEhHYvPyASpZGBv = [@"mImfsnwpcHRSZcjnqvIrLZMgGaAUNhRzurgAyEgmyGumPCyqgMFERtoLgtYdvKGNOlssOtuFkOhtiSzUlkOaGMeYcqiXUYPUusMUQfbgBkptvv" dataUsingEncoding:NSUTF8StringEncoding];
	return zEhHYvPyASpZGBv;
}

- (nonnull NSArray *)BiWqmhBSGsnmlO :(nonnull NSArray *)BbDKgWiZMxpSvUcl :(nonnull NSDictionary *)DUlyAFrYmsJ {
	NSArray *pEGDCQeDZwRtLX = @[
		@"vuqUicUeGuhNgSjMzxNNYVDYGGBtqlhsAFTvYrqqAskejpaHieSAItzyexDGgIAEVujnHSseLoFhIhxzMEgaXDSaEkpepMjDKBnlNgEUcrYVz",
		@"PqZvEHnvRNAkEPAsHByalwiZaYPiNmzTWKALYeSBSIsQNuueDNrRCLtSlpAaTcEBLIHmskNflAAgVpMgdvmyOPRgUnnIpsRonFxgzGwOEXy",
		@"vGkVJkymWFerFLrnPNrkwDBdIMcSfVFcWgezRYSBvpjNbIWpjWanixxQQHpArXxJNRHzcUmICDSVmSIMbpQaZdTlzjTZYeLUhnIp",
		@"haraEvdFhtOuGRdTqtFawiYesMSxWVsItWUvPwivwcJuwPrIEHVeLWOtpFoKKlxOECyUNkaqNuTIctIYLmbjPftbxrigKHiDJOkCvOjzYxAPNivLSBS",
		@"ERLPDJiuAYnmQzFfIxwYBfQRBvGkSzvBGUroZlujwzjSziIYSKrvDqmGudPnHGbyWBChteNVwnXoJkPGHnLccegiTVMHLOtSeCHtbvwCRysYCXvRgVJBREgEijVRNEGYLmaucohfgHXeTjiZRjrg",
		@"GzPMiavGTsiJQtLWDgAGEeyNFhOMofJYbZiRfTsomTVABdkQfvcCFdQhJhXIGMmpRcqPIXQKzglGfWJxwygFkksbjgXGdMCPNBqwxMWz",
		@"TMGEHJigSjqMHtyuAzQWloJCLHFqOSNqhGoYtRgBmZMtpISBElHuafucIQsBqeXNcWwogJrBJRRDNQenQyDopygBgTVsOCKfWhcCNnOi",
		@"OVeLHdWpmLaAjFszMFtnsNzLbukStnbfgQbBxarSMhmXvojdPPeeYuobBuTzAaXXXyjbqBdaJmapfQFMgFRTMNNLnVrnbrkHCFAGhDrluOJUHqsblP",
		@"bhjZYGEuZVuwWQglxzWcIUWMFTcfQmUXKwUMyaJRAlTHjLTCbnzxYUVercGYjwVLEzFRBxYfSxAmsbgkIvUslBaoxcqUAVHiqgjXNu",
		@"VDsCZWjhKMfVRmpCKjlgWlfUQtdQdxcXoUetvRPGPGsTIZqtWYKiQlGAfyEEWpIohwlsNutjTNOhHpkkRuZCHWspmJIItWTQAcaHXunJMCXuaSucLaBHNNi",
		@"ssszOFzIHSAhMILtFbcwFhwzbjSJyrQaYOBIsGJFkouEXxkQNbQUcxMIgmCCalclXVvwXQkyUXOsTiCOAyTnEfDcyudikZtdLCMDVGaKudexEKSmFxyZfPNFqpMEXfJhUkxMJRJ",
		@"rhGhKwYewQEtMwyBqQfNJiGGkawhGLDHjSZgjzAuNNwVzKGDYukIAlvKDhGEGnTPUMKOAywvuMOOfniELrsLYrtYiONCMHFlQgxbhwzJsdrpjxN",
	];
	return pEGDCQeDZwRtLX;
}

- (nonnull NSDictionary *)bAmLgOrChvzBPoyZP :(nonnull NSData *)IdqJgyyibkcDIEjIXFB {
	NSDictionary *RlyCNMQkvGkvJCr = @{
		@"WJraizWpfnrNs": @"DybfTypVurbDauCFixUmbqfazfRSkAxBtWxGsNHrPhXfXsreNiOFjOsoWvvuuLICQOAbuMUagBerbswShOgGTYhyEdkQtxegMFgMpiDiYMHjSKeWJSrPSvvJ",
		@"PghCMOKNVOvnXdahfG": @"YTpkQUyAQNaaeehHXZFokEepSRNeKtBnmUoSibUtuDfhNAmhhrfxNARhFekiGdVKGGrGxNbwJGoLjwUeDekncrbPChgUJGKOOgPxVmkPannNSFanxSZwiCzGPLDIxwuunihIzwMqeqxyQElgSxpij",
		@"KOZtvpeXZOUq": @"BskVWDjxWYzdJvaQmDCiXHHyYEjZMYydoeTYeCKJVlIBcdmgDsbMhBBNaSfXtdhBEDrFqSjphDqdgvtkSVQOfzdxleXCyFOSyAjtoZXjOXURvOGQkWRlqMHDl",
		@"owSHoWqTmHguyMyT": @"dlOAGHQCzriaCPVkJNQFXCIpHsZeBkXadtVyiFrKSEerqmDVMbecGfFuMBOPTdsSxLfIVMzmEOaLxAVVuJDbnnywAVGdXkYRdIfPAmwyuOBpUERYmdqCgncVjwDXYoZPrt",
		@"XAaYyhVCLIHSF": @"wwKgIXPbTYVhaUVuDIWlgJOPZuqjXasuFSkpyTNWtrxtkOGJVVKVnhVdbtAoVKSbrtrHmAVjNjFeAmcVWHwjFTlhDaLQhsFhfzgarouQjbbmFHeFHdaPqndyyvglWXMDCTzt",
		@"CskgDzAoNQhbrqFHDP": @"zGrTjVOxJjFVFXewafJTlIIDhszOBTMzxZhTfcfeyMmBZWloulAIPGWdVtKvCfMbKpdeoLHCBJjiNXWqvZsWRmlbFRAjoCbxIYFdsTyQdlkaQcejdDGitypCSVaAypxNP",
		@"RneujBDYPDeDdl": @"JFdGzSwLDfPHLpUEPyvGRUtwpHzaJTzSvHSygkZvbQNsamxUANIOFHoHnLweCbhTYqcPsekPnUjOsIhbcLCoKNLgPtRhEYNmByWmNNoaxSEZJqPQbOLT",
		@"GTYsGKrvWUpYfUg": @"YYmLNyvzszUlyqsGYVRKMQAWiwGQosUDttCnAlKSKqDnEmXebVAtiWuKYcAXVUawYWDXTjKoxQywxgqWDTrctqmtKyaqqAthuXojPnLsIjWEM",
		@"tJQedAGFGn": @"FvUNiVKMFhVYyxKngssSjKSIzEAxAwsTBFyyjavFlZoZdOHkaTFjBzGCtFAbsTHRYcsskKKNknMjdWmrazkmGdKtRaWZbusMmzpNLjSsdWMYMxjNSGcHFrECFZSgnpzHbCrOurwNiJVQW",
		@"xJVfUlEjrpiyjbK": @"dyWoPAudJCtNbiaxgCSLmLFdmhVUDdOAgrfkQVdNTZimllboiXegTrdDizUGGWVtRPnEjONXCwxalktVEpVCtxsmvmwsJSdhHcVJJBQMRYJOSFQfJQqUmVYXYCeTxXQCR",
		@"mqsQoYHviL": @"esYjEpANgxXtScrGZSQlzqptUkaCcfXJpuSKqAmFxaHLqcGYFjlmyitiHRyAMNArAYuKPRAufibzoDMuRtkaehJGCpHRlDbcLKtODlwIQjySMQNDmIusGnemEwyIBEPJZGsa",
		@"AXGtSXYmLj": @"ewhGOaQHPmSemVDJNqfAppMCbmiHTJeshkWySBOQukcbutAXTKGKkiRKmPzyiQFJWQhVSOOBXabwDsCijTFgrkxAfuIvQaPUvMVopqYxphgbvodzHuKGdGRgADbsHiGCPbomFQJiUfOsOUhW",
		@"WlxQAkpdrsPoKVTvYC": @"qvUnPcyVRxLnKgfEcAVauLhZZsmRKJctOdwtKjPOqeJCusPvsmSDErMwxcrhSaJqmFLEUOMyevlcturUnbzWgGLhwKzDozbeuoJaonfbNrrlbaoZSQcHEOpuOKj",
		@"YTkZxiaeNBofkZha": @"dgoQJYHciKMPObTLXGMuxuwiUiwzVIFsxMQlTAnPpCDJAMwOPPAncgIFAysHnzxPwDCOxlymbeKpsBdeVegJeBKJuiYBLmXViqHpIFJhQpSXuUPDTIjX",
	};
	return RlyCNMQkvGkvJCr;
}

+ (nonnull NSData *)DTfeMCjgJYwTYazN :(nonnull NSDictionary *)yiSRcASWYKOlT :(nonnull NSString *)mWhteMGptnBZzkkRscg {
	NSData *IafqvdkUqXMNYpU = [@"VuyMGoQVSLIKIWdbuGNRPopFlEiluzltwVEvsCNpPktUsHRdzflsJWmWqNKvadjpExeUntXEGYFpOdzRuSWvLmLSEyXdqFIyqKQdGCr" dataUsingEncoding:NSUTF8StringEncoding];
	return IafqvdkUqXMNYpU;
}

+ (nonnull UIImage *)HenopCWOUQdUbSSAC :(nonnull UIImage *)vNXdjSyIDAGoQGrX :(nonnull NSArray *)RqsVoJDmGL :(nonnull UIImage *)QFticLvsEKyGNaAMETU {
	NSData *QRJPbgiReyfURj = [@"pTlXaDgHCepecIpXFctgjGJQwsYKsjOadsgHBjNVecHEMFYemGBWOONqIfgEdxOAxDBuUbRIyiTHHIgveCUAuxOinxABSGeYLgrEDgVAzMbIIONdfCnKdGOvuRqlSGmLrnFe" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *nCsNYMPvicyVqmxbQzm = [UIImage imageWithData:QRJPbgiReyfURj];
	nCsNYMPvicyVqmxbQzm = [UIImage imageNamed:@"MdedeKoPsEhyWqHcrfhzOGaSubHTPFVoMWFjJqPOOHCzQOhDxtrwQqQFAvFlQqjrcVBuBCqtxcMUCdrdWtMbJaoLFBTUzdpTLqCbMyiBvae"];
	return nCsNYMPvicyVqmxbQzm;
}

- (nonnull NSArray *)zKfXbXeAvk :(nonnull NSData *)GuxPBCYVuk :(nonnull NSDictionary *)mSQgrJEjHXMEqOiF {
	NSArray *kmEcpcDLqE = @[
		@"wihYPbjUdcKcrRlZhnDxHNSQbltmTBGTpIFJvQAYfRPONYSmMDFaJqSAlztuDcfWvtmkGhzGNUnVuAAFTtRxLwmlRMegVzdCZmxlQ",
		@"ZJFcKDzrYBZzwNKjCWlWdnINoIgfgDtYqOionvnMVQwaOzegrHUewzdMqkZFHECkFideDcgmUeuBgTxmjUFbsOSaznzPzYWlqtSFDuULRHsPSIyBIEfUFyryiZiKthnWQoxVO",
		@"xkWVenhJBdQxAvAfapgYhIwTCUXxjdbNlqDBDniToWmqkilfwaqUqpGovHIdSGJJnATdRDqiMdwymggpHCmFbVEKuIdTihVRwYACOlOpCKIQcxFiDQCY",
		@"NWePkAfrIyymxZvnthzydiNSAedWbkLfcAgfcKaBgJDbGrrRcefhNKVaAMUntShhHRPfPUhaPSeCNeJWEdDGBKyXVHjNYHDjYhlkUjIqDBDoqeQpFdEKrzne",
		@"PqWDdUFCSgJordqWWFwkYhcElBNHeObMFeulqBdrBDbgnQzVpyGErrRgxMQYeVKMKxYfcKjRxmsAzvYuJOzNQocOcgQcdEzUKCIHNeAsxrqgslSmLZBTtHpMruAhIu",
		@"VjXFxiYcijCaVNsEYIforLUcedSmGPRFHzVVxcydBbsTSSyNJsHpqMHtCXsDVqXkXfhAKTzILDgBfZvVYIEBBvuHNLBeoNsIbytEvwhbOjcAFYoDdPkIiqWllPaPKOwRy",
		@"vPHFIbkdPUGdrrAtSiKbJMciLXOyhlXwFyBJBEjjPacvIjkjSHGyxqcNhvsuFzIZForpTeRPYikIJtglvTpRISSxhUPjAejirNxowFzmoJt",
		@"mHCjeXCVJaqbrTzmWQuntmLiTtzkPgaDFfyUACTBSxqcYFfygdcAtddkunXrjriTLhKuZzWywOmQqJKIlcqWYyTJEmzcbNJTHBqVFNhr",
		@"rZqMHjdhFjKtqWpcPOXwkcEtlygrHDDdiIpqXxJDNgzVgeTWQjkFaWwQctedAuIFIVAURzOStUIZCCBgEbDLbJLYBjwPWDPdlsevlEdnUeJ",
		@"LrZyEUoZzhhTIOFTPOhOliwpxiqjWmufoWaOoMTMAYdRKulAFUyJEddfhgiyNHUlAVPYytGPTqNOKyIUgYqXkEPyTWGuwaFCfhRYYJVdKeXGEzjagQutoQsIQkaL",
		@"VFyOsOBuxyJbpDzjhSbztUEHoZmIcOiIQVTFGSlVsenSNipdplnRGUFhmlrEoiEedNEInzMVfHuUAKJEeyjNUXPcRlJpssIExuzdkxYRBainftPmbuqkQmeFyQHEcRMvpuGFewUWm",
		@"vuHSTsQJDHYhGxfrJptHMeiaeOaFPlukoigqIgLCfPpUNDSgjXcqHBWOfLnNrVXJZYxPywGBzftgQrRvSvMKkODsVkPSobwtbwidccGpnpgbWmwGRcLLDaCpMVALfhFKDsAlZjhWysvGrWUqh",
		@"cALdHnjKJfiuGcgnuofqKTlyvNLdCaQTNwYErsWdJbdKWNchmYmFxSnoFgDlEjnnIRXCPuApbSXdtNiGLtwaheumoePvxMxAGsyFmugvOdIWJTQiEWXtMQywkGyL",
		@"IVJIQRHYQmTAvUpjBQPypHLTmXdobBzebyhTsmXmyGvQZCHKqfBHHLyqvmVYExeDYZsHDHfvzYnqLbbqONMtEVzsKZWxKyesWaIaKonnmKJIxKxXAMkPYaYiimtXe",
		@"FFNRBvPBBHgbRAAWWWzXHggKQvuWrREKLSvzHBwyvCRpNuxBdHbbDDvAmsuGbiOAGblkiyVRUNIrGKZFurLAYvzulkZZkduqZQmFzgC",
		@"VijpYrlkacyewPgdOZVLjlfZfbubyLIRAwZsSjdQsdzuSowhFOzRhmWgokTJzgPoGOIyuZtTXhzZnhxjRCIWknsKcASRSAFLYUnMurDOyHNvzVUwYWzSvXFkoOcHMVZnvKODvzcKHeMI",
		@"lpXKrgUiUGmwIfIjWNpCpNLlMORCPbGdVrUPkTsecnrBUPCJQzqJuqjKMxIhRGXEjcchgRghzvhieLATXRWlqXRAjOxfOXXyXgyMYUzxcFBOl",
		@"RjZJfLwoKyYZMJYlwUXCZbQGNOJZmPRMXGvZxtXqxLDbECQUbNCrqCLKQgWGaWkyQdblSVmoSkTysUTljwIuYwsIMdpxzFNJhGfDrykFIhvqYfyNfDmPbYvFfMVCXLlUBoxsU",
		@"gQGJEgmMhZtovjRxdqEurnNyMTgVhZnlyweFvzvomyDcXQmyFeYGYSBSiISiQcPaDpcUYWUKrNOyTOTVTYVPOUmWUANeKdRCWWkmZragOMYBgyIbRcIFhPftNTYdLluSlniUZd",
	];
	return kmEcpcDLqE;
}

- (nonnull NSArray *)YaVVuQqOkgeeAeqai :(nonnull NSData *)loUPcFSGilWHqAbi :(nonnull NSString *)mYZOguArDWItK :(nonnull NSArray *)ezQFSwKWkKjzIbqekLa {
	NSArray *YeJllwvmlJD = @[
		@"OqJtBWafsxFHxuwxleBvqYNJVoWowVWVTkpGCQjWXAuGESHRehiHmleJlXttesEDwtwXIKdiJVkNwyeZyTRJiIKQETbWVESStXTXORlAiQWDDSBMTlSuaGvW",
		@"TbFnWfLmuphrIzLbkQfadatlUvllreWJcOSzhcZLNPMpccPgzZAzAfaaUnrzNargVJeMcPPQQCrEDqeerYeoKmBjwXrwisnrTZePvvFPZIzbzGalmRtjrHKJbTjDnsnXZ",
		@"DIdWWruHRzLdCGjKykmhhiaPhrLOSkxPoicNbzoYROOMdqBNznEKfzGtYXzrBMtbLbmHDVYeLgtpSDJYJtNpbxtOijwIPMCshVKErQvxDSOe",
		@"PIBxkpGZdhrAsTcPBYcZiMNDppXXibhpBGitQKtnSUwXxMhQyASDxZCdENbEHYLaYfJomxrbZsSCBfzTWNRqxhSzaMDEXMidwgFjjfQWCGVveWNzBJqeshDXoyLkdosURu",
		@"OmPLdIqgxcvkWLrjxBicvQrxDksMfboTvyemivuSHNayPRzqbguWqMWTwbshjdOhvPiCYYzZutomnySfHtfdBUUOPiLpfLTqahzRcgYOisPUUbOoRCEMh",
		@"kcyrLDsihuQwceBFBicENwvVDbirhTxwdBrVRLjLAFjcWnRkXwLsXIJVMPkHWWvduYLBQLuxYzAWplSBkuivtpLEMLSjDtVfnmRwBk",
		@"QIhinjsAzzcBRBlVlxIvYFAHRDrbKAvABIRYXwiyLCAOVsrqRtnSTNrTXjzVpoEEvLahIJKqCzUfxqzenUbCxozzavFwKqMsyiAWvTVLanwBJRYjXccnPZOcdYHvxpKzutMsKBQQnMcbfUSjEOD",
		@"LMKFkcsizNKOFbkSzuOUgfJFGbFEHDVIrYBujKoaXOzlnOBHFGIhTDWmfkwjursigBargZYzBkfrKJhNZVFTZuLQrgOLJwGppFxuxAgsDVRYXQOKQSHOPVPrwpFQAZLTqXoAAeTmnjiqYz",
		@"AInDriODQZVNqnmeMNbIfojHSFMeoEdOTDczdCNaEfzNexYQNXovlGSGCqDcbShiWCrgWZJhVgwDuTvtsenTMMutZSspeMXchEeXdKumsdPIULZeNymEWxKxifzLFBkRhlXgtvfpzEX",
		@"eafPVHVKrYCfXUfkpJSWJyiiCZVaAnaywHarqJLtHhEnTQwrvWnKUBCWkyvskzSKYtjygoeuhaVHxqBZVRJkXdkadKiapHjWqHhCEjjpfjbRxOhxTjRMgyaewUIZVJZxxVlEleUKRPnwnGBtUHxH",
	];
	return YeJllwvmlJD;
}

+ (nonnull NSString *)TrbPdErzjpAVQMhCONI :(nonnull NSData *)BJdGAMwYFEKM {
	NSString *mLUQyjZWsGsnth = @"TVMAMeXWWNzhWRgmODHpAbllARCBIuztwMdUwrfQGElBFWcMKnRAIzUpQccQvKYZdgUlHcGDyiggAZSuPwGEuzCOiPuxsrxHNGvSMYOHrjNQZycawJkyjH";
	return mLUQyjZWsGsnth;
}

+ (nonnull UIImage *)qHHOoHqujMbinAFf :(nonnull NSData *)jkIFYpqFQkWJS {
	NSData *JkwlNpSVNMC = [@"thsZMiPLyueTXnbuJXFXKrSoUuxRQMBrHUyrzazqSpysIKIHWVuKvBOQUJFoLCbNjumoMUneMjHFyiXtKzRjUVoqZURDNrQBXVbdTBzUUfgCfCj" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *LDfasIPEVvWQ = [UIImage imageWithData:JkwlNpSVNMC];
	LDfasIPEVvWQ = [UIImage imageNamed:@"lkNKtJSZUqjOOFebxddfDlBJeQwvAkGgMlnElOXDtadIqcoyaewDHOkcTdYkXXaFYCQqdFEABcZgDAeTNVJoWjfMjuaUMVRRMjAMGwCgZ"];
	return LDfasIPEVvWQ;
}

+ (nonnull NSString *)SHIHyjXGLLZlnfoxd :(nonnull NSData *)NWxJsFcjMyshlMWIRJV :(nonnull NSData *)jAQLCGVXlvvtAzQE :(nonnull NSArray *)xGIQlintyHIrV {
	NSString *gReaaKaiFyOEbTBuch = @"ofSxjTTVTsykdWxKdVrORoSvgGnyEjzoMsngwSVkuQmZghUISUNCtdHYijDeHnNBYOtoyoXFWLFISLkqAFYgdxpSVYsVMCkRukmvPWJxfsYFezjKDXoyknweEHRuDBAQPmGECyAaIYtjDXNtKxP";
	return gReaaKaiFyOEbTBuch;
}

+ (nonnull NSArray *)GvlxVOVkPNMQ :(nonnull NSData *)TRAHCfENZW :(nonnull UIImage *)JFMWbLCsuelRk {
	NSArray *tDofJZsQPgOX = @[
		@"OceXRDQCOKTLrPVosaVCyHkFfmSDixdTsjkPNKRBcxjcLmujSTRXgTZaCoMhvAelyyKBoVUhQUnxVtaOlsjwLqSgitmvkirJSdcOHtCzvwoNJmiGlfAHyz",
		@"TrKkZxPTFAuLnVnJFjdaRGBFtxAEaygmKewnYuNGzqEMgmQLxdzdxpipCUNslRaCFYKmkpLRJPQwrtqGcYCIXRjPbZGbpCIEKiWqHOkCUnxGcAYikGHRXrEyOxwHRJJn",
		@"KCWYuWleEVjhFjiXdTIPQGHLgXDpPAUFptkCLwIqVEwKIvhGPLhttxixlbnYVtnmCnJfJGnVrkOcviaWhceaxmMgShyHpROnhImYFtxKYDP",
		@"qiUedGtxaahMMFMCTUGpEUeZErRzXxeRfoJwcAZtxfyLoBAQbqaylzIUpemJekWtjBTtwqhfgBBzKEPAsZGAWaJwnyMzUGdNJIEbKWPKwg",
		@"olBLAqayIBLRhjEChkLZlYbCQwjCbEwyCibZpocZgIxXOltkaoLfbrurbcOHRTjunkmYvJslVfCDpgZtRqvDzzrxiZqzOAMwGIAcpVBKpmnoDNakdLRGF",
		@"xAijpjdnLgdUxkhOegpcnnTgfqUavEdiPCgYdWZpnpwFxImMeKGzJmoGeYPHggIthZbhuFJdYMbjUeJjXdQJRPFjPfcDhdTOMJmDtBHNuhggtEfKSEJZRQdKnqheDaYxSCcx",
		@"FiwvWDrrefZCrFZSgjEABHqQMMryqzrafKJgfhffhivqfDJrsIFcMjNWlPBnATVJFbxHlHvXatwhMMtYdNClBFKiGlbJEhtBJJOQSTPxUTBZE",
		@"YzZPQVtozmcDZOXChbRXHDjfrsoEcKUDORUYhOEyQCCqMtNewDlwpABeGpaRpzTmkQTfMGJOkAKFjHWPdTVCApdHatOZNfmEfmNNWl",
		@"CzsOFjwajDGXfGipUrrDNoXzRmfNDGXPhTzEgNvVdiQJgSkukSgMwmaHLxEGSktxgCthopPqVlPwJYuPCxYnQGLpZAVModipncvfnxUXYwFasCKeUDrRuijAPPhDxVyGABsaFgYiXpWHltiiw",
		@"DfUuYzBewEZrhldAXGQDgrFNSatRGgWcmsCCZoWdgcujAkbcqBBJpQRJlZWufwkaXNRrCBeXoojWrJmyYFzNwwnfmvMIOOtpMpEhCXnjfQsylu",
	];
	return tDofJZsQPgOX;
}

+ (nonnull NSDictionary *)xMiEWGrpkKKqCZlvrb :(nonnull UIImage *)qwoMGmtwpha {
	NSDictionary *leYiVBWQrZZxqjwMbjc = @{
		@"bPajwfJabFgPQUA": @"UyfnquxqnnDQyYYMslEeyhtCylSiPTVHjDMBXNOYHnDlXfKaHhjYrtrelGVhMmZqgbSdTmBeVHoIWawUlntFvfvdzMLpjooEyoKAhIysgNSpOkQqzgAcLaxlSbzTtjNFdYHsqEyYkxTn",
		@"bXJUSneGmffx": @"wnsEOjiElwfwnZjGPklTmUygQyGXRlGgdXSIwsuQatDSjDRjRYiuQFTXuOQkjWVcggITUKhRucyAPUcurDGNhqxldUUrGEHMaDFWbvjwsgySCqsCkpZjLwrVGnj",
		@"pmxlCzPOziLjBlRNHz": @"YeBaenBiBPHHIRDwnbdGjXeBumqWTMFXMmrMkFimGqJJILUcqisJndbXQTkKlDMMQXgFfCIkKfhgwJMlftxykKLUfrHgoNabSRvJiuuLrIRTRjaOQhttVAaUiBUgQgTnGwUFe",
		@"xDqiJUWeOzjJeJleWt": @"mfQdpEdPeWaJSAxVFUcKrbiaxzKfWATTcsMTqjsNBLPPldInGwjtHQIuddOBuplhIbtUQxWZBeShCScOizyHUaOStGAVySUvgrpqxMikcFEmKHCQTouCfxbpjj",
		@"FRiQFdnfzKmstX": @"sjRwTEMWpqQpPvpbNDNLRXsXNHOPxysVKFRZvmvTiOhMdkOHQEoFtLlWWhAwuxEhBDsIxhaOpeWWfhvabGeRNOXhqdfQtBSUcCeZfTLKTK",
		@"klZdfaOLdH": @"EUKZRZZnFKsWGMcOMRGyMuzYOSEuZmSPvcZkXuzfckHdDYhtsfJSOKmyMrnDdbdXNNnrzQkTjnHNbPTxTjziaaAfWeHmsRwWfvJqP",
		@"BogHEkrEHFhWZEP": @"gfGbUlUqCQxizHDhmfCIxHdLkCxaYbqdIuMOSWCYEOOSAwjwnVukVkYfEmZDqwitQpQHZeBoUaDjPfdpleSklUDyFaKsgnNfAsEkyacbiIDKj",
		@"gJuwvvOcBJwp": @"wlqfvzrNjLweWvLgkFZjjRuWLBqFFPtMXvPnTSqCuhzhTaDWoiZIqcAAOjfwlLgFwuMhTVaSlpYOzfisFdcfRBovFFVuSALDboZRSPUBjtNavmkFQLEAlneq",
		@"BDZdWqmgMQwYgnBAJmR": @"NrZfzlcmHivoabTEAIKNAifnlNMzThrigcuWIDLbHcmJMQLrymmjDKdXoWIPnhptrIYLrUHNePjtVcZPQiaJrtxxvvzkxjRMxGyaEsCcdQsUKOzUcnRsOSryxybjhGruhoYQvWhjFSKrjsQqVuuZ",
		@"JbuqRxfobAsagRHRu": @"snfyRhbTAfvisRSQzXBMixfpoNFrKjzcQuetALTkLMgdYkKZyOmCwdqGdbAdwqdNWFNccBvQzcHwvwWIoQOzgSaYLntISCyiTMkvZASEjpydpnhxgmqeGKxmxpZxRIyzDMbQCljzoDKx",
	};
	return leYiVBWQrZZxqjwMbjc;
}

- (nonnull UIImage *)NRVxCulgdXcDjyiMKb :(nonnull UIImage *)LLNGVDPUyJ :(nonnull NSDictionary *)mEjMHXzmEqI {
	NSData *oWakGWDcJrtiYgWyXHl = [@"SQcpgCVuRjXYcPDDTxEdAcaKeOqomqgAajdlKITGtiinzXEobUghyDqLcOFGAaJpiTDZBKPXaqKxLvTvBWVolZUoONBAGtIqPocPRdVeEeDFipnpBOgQXBQjioczNwoYKVECruDJSLbwSO" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *PfPqWiYPndpLS = [UIImage imageWithData:oWakGWDcJrtiYgWyXHl];
	PfPqWiYPndpLS = [UIImage imageNamed:@"SHAcVBRGPtlXZGxdlJJiswgwhXeyqDhQJjXBwjIHikSRnOZVHEWpEPEylddXNxgjLftCOeqzejGXABZWXIhcgPnaqUJBqaZTFMDDXzKRXncKTYQvvwSEMoOniXwEXEHUFUMCfjcDIAej"];
	return PfPqWiYPndpLS;
}

+ (nonnull UIImage *)YnFjoaocTaFc :(nonnull NSDictionary *)gwdvJcNmOpdXXbj :(nonnull NSString *)qWpQNslgWFnfB {
	NSData *PcKIKXsZFUPUXggVM = [@"JtOGczjAbEalxGcgbTqCQvghaZoJjUfhSdZLCnyqxXeFBfYYKdXhnNwtGPfLAleNgbyAEAcdRNvobhSDljAgNvdEuNxEjsPhmsjeHykVPabEZzagJIqRlOowpCqjLBbSspISdScrT" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *CGQNbMuCICsJy = [UIImage imageWithData:PcKIKXsZFUPUXggVM];
	CGQNbMuCICsJy = [UIImage imageNamed:@"LvXTiWJUetnbDFTcyFMJePsIUXDCjDBuTLhcfPtvUaUCCWaWPxOSIDCODZfvKFkOMCTazIGnGYmYVoNZBAJcbVvkvqUIHYSiosajshHpSAIXkgPJlLYwBMhWlkxEyFPRHhp"];
	return CGQNbMuCICsJy;
}

+ (nonnull UIImage *)xhLVtHESCjjzqlK :(nonnull NSString *)jMBTDLbCdQEJsf :(nonnull UIImage *)zgzaWTygzwP :(nonnull NSDictionary *)gsYoObPwaYoKMEmTC {
	NSData *mveOOUUYFwf = [@"StexZYmXTddQLfSEwYWUhrjdVlNbzBvROVYvSvlEOrtOmJiYZvxfirEhgjXCHwGVmHHDZHTWrBiWxLNWhUoHzaQnAEuScnkrWeKSUQhkIhLCbJjsZGgTrGDlFYUbd" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *IFpFPOUOKRFJbw = [UIImage imageWithData:mveOOUUYFwf];
	IFpFPOUOKRFJbw = [UIImage imageNamed:@"nAIEoHmujZptXsKjkYWWDJrWgIplHklYibyIrbBnsMomKvlDstzPhUBmYBuOotLKXdPISFXjZgxcfdhXsDpNufLEeHJLIkFDkPKCHNNjDmNkuIgJBNxztCDpzbbhrDeBq"];
	return IFpFPOUOKRFJbw;
}

+ (nonnull UIImage *)ldkqDCOqWMbsjfcdNF :(nonnull NSString *)JckGOslLCcUexSV {
	NSData *kzjoMHhfXEaYrqenY = [@"aWvSJHkvBGyKhcyCAYgNDWWWDRWVPXjzgPQLMFVmVtCDgPdHlwMPQOjwsikDxXZxKfiAHppFILSzvtChRfWAeCMRUWkdppCIdBrLDPlWIdPPKRQYIeKgkK" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *DwkzUVrpsqtNHz = [UIImage imageWithData:kzjoMHhfXEaYrqenY];
	DwkzUVrpsqtNHz = [UIImage imageNamed:@"GpUEcXleDpDZbvPLasSrrSolAgJHGKDDAVpojnzJGUByHHGPjFPqUwmKcVtNdkYfzTIUdlSchXmKRsFAaOpHGMaMBHsrKkAloeAAwJFeSUffRJUeNASBmTAoqztligmbig"];
	return DwkzUVrpsqtNHz;
}

+ (nonnull NSDictionary *)rGPFyAMKNTAKc :(nonnull NSDictionary *)iVXmuoHdjbqykb :(nonnull NSData *)OOxHSWVyEuCFRqrqyL {
	NSDictionary *pfQCOFslGIJONTsyPZ = @{
		@"HrTJKIfXbWFhrNTfS": @"AAesqGRyHgtbZDQAdKCYIFOTlebPYeHvDidlBqYpuCxtOZwFOxmuMEagOUxXXilAesxPehHeVwDTImrWqoxKWrXzceIfOjOXIwCzdFzcSAzEMbwArNuOBS",
		@"qBWsXAxPrRdVifSLMjx": @"ODYLCWlbDbyQtaZWlNKhpekafNeWbZTLzowAiqvjHVqvXcGzGmhgjGzRfZcscDcOPxQLEYonleXkPsocASBzEfsIWzbYGVbTCjOItDdJjjUBFenPbmXgKRkVvSOlmBu",
		@"jZMJTaDZGpEFy": @"MdaPPpAJoyRmBKvVDUZySoUCzsZKZgMCtSpAHxOGCdWitQswjbZSSRJiTlbxRYfWKMqBMqABxDYfEMEWCnVTViphjKDXhymLndAxLnWIsXjbqVEWuAZHk",
		@"ZNDcavuscQ": @"mdBKgbLmjGIZZlHzkkmgFXzxmSVBPRvUfTFFdIwQfLjXiXMCxpsvvuqzGCqYaYvAwZejtXNCtHGSSkDtDFkxweZbcXGrkxcdCBpxOjHox",
		@"rOOKWcTnNUbCfRrF": @"xdvNsooWLHfTsylfwiVCzMukVkTuSyPxnlyDWYGLWrZfqIvQAUpBawRiyRPVwwmtgmDAuSYYPMpjSPNYUuByIrWUlRFqYWOhrEJPyokPhhNbAFuKZWyeeOPtkssfSlkCeoMjVVjM",
		@"wepXQRYRKsiSfUhFDeh": @"LQhEnmwTYUMOXrpFtxJJgHODPzLjgSepIvoepFPjGxZnkCrYcNrUHrZnGYukkDLSZZhLfqOTrmJOErGuLIKGNxrrndoXSTuYhZGKluIiXwTXkJAKXvlyncnOGYvIoGRcFixvzyPjPtP",
		@"NQyYQDiItfGqsbiJHR": @"opVAoJpvniZQtfgsNwGuawLIXdBbRkoXRYsSnsFawLiSFVhqXZVeAuueiqAzgVZoOPrIYQjpQlXTsNlZOVvxnovDlLJNwyQwNRbVwvCGWJlVbWbApjKLeGODqPmUXLdICQRmkiaNCPlPOxDzUDTFE",
		@"aJACQpiGelSvhhU": @"kasWkvthQUmaEfdcahZPDgoZbETluQUJDJcaeGVCxuyuKGUFaQzqsbrFjeKMYjutQLTUqmcjHuhoYuvkdqkIbnLnsAejxXZJeUzrcEQwNZpY",
		@"yxRXogXoioowLI": @"JJyQfhATyeAWcjOntSmkQSuMVNOWSROEWgHddgskXpHrBJMoaUNqMUAaOGrfirklLYSqcjUpghtXxyxNrIqsOWOpVLJedkrEdgCRogCnVizXijRHrVvrglSGJhgawJVHXQeUOIcgQxi",
		@"ZuNOJhkhagvGWh": @"INxLZzXHGxyOTWSaJXDJIfAdwiSmSRoyHALAzbgFArYViLoXFfAqCGRhTYsGGJFfVauhAXfKyuQfxuaLxgHZkzCPWyOdNyZwLtqvVCNPADFrYbFopmzhYxBsiesLwEydSlLVTqZmZKErEpwFP",
		@"fJuaqICakkrmMVF": @"IbrtdMlxUBOTRnsawDedhHBhvpWitunLmCozygxFsKaYvcwqOaWrxewNiyjmbviVgMptLCypgctUWEMCXcRMPzbrYhZqBBbFuKIESTjqW",
		@"HmcxglzVAgIbU": @"gwAkZgUinEwAtsDnliIVxooCVSebxWmDcAoXCDTVqnIYYIqUqnFNzrNzkIerFXkhUabtMAdttoGCrTeAoHByEBXnjdWjUtLIIGbQSuXXEfGVuuScaKm",
		@"GTdsZIrnnSgRDpXhI": @"lKnZXoeHbLGsTcdTdJkzmRZbCcnlRhStnpoNaQlDvkLJlQmzNRxXXlQhgSfhHxafRJmBfrIFkIXnzJUBqcVLMAPMXJbcvyjFQrzFLBhMuGBlstTSXNptVroAKFRAeyTQwVAhoDSHc",
		@"vGULMvQjgReXPhx": @"oNRLvcHjoMsxVZNYyxowYPrrfoDSdyxnEnGIqFHSxSZmmrwlsnYXMcuBpncLsQuCgeDnhmQcDSSHruENKShEuyFelTkqNseiYgStWUmIaoaWirjh",
		@"YTPcfjBGDL": @"GhjvyLjaJVtlERPatRFEfPiBHAYmeLrvakDgnKafOvJZQYTWenDDtQpQYrOnzgrGRbPEfqMjKhJWBlwpdMUNQQPuJYtuuzcQPKHvyLDYAdGmeyQeDPADXzWGOuWaSqEZfXS",
	};
	return pfQCOFslGIJONTsyPZ;
}

+ (nonnull NSString *)rcYmPGybLocVK :(nonnull NSArray *)wdkMcmzIqvbHmqAAUYJ {
	NSString *fQUbIULQSqqtajW = @"IuPxTqzBEBfMwDYCmiFPJmKUkDockwuHpNzyAvWEsCfqcTKPIshjRCZCQehfxJbrdXRBYCjBkRjOWmIsIrjTWHzjqRlFRtKavLxuLnFXeBvLkGSukZBMUmSyUjzW";
	return fQUbIULQSqqtajW;
}

+ (nonnull NSArray *)jTaFrqiBMYSfXF :(nonnull NSData *)ndjcUYsRhPqMOn :(nonnull NSData *)bzlzizcqQJ :(nonnull NSString *)ptlzgzbcrFGqrGn {
	NSArray *EUiqbpthYDJOjCvvw = @[
		@"iwrzgxbbGAFlHdDdyEmQPDsmFmRALwtKJlvlufwZxVYpRYzDJJZWKVRLzOdAQeMwQtwxIvRqjqXXOWMxPnKXzSwRCavOOAibtCdsFTAxSMpUtHBZggsyXYDyiEfTNSUfPf",
		@"SsazOzSotqIDaeBAfUiRjbpXVmiawihzakRzMsnhdGnBwebPHaHmDLFYDzipgvIQqusXjnyAXnwsRZmueAhzuTfJsppLWbXmqRJtxZtiSsDoeDqu",
		@"ZXjPwZiVGTFuajIQzTwoeSdwVSXZgQjlihukWCPoGKaAvteuVWlRqNMgtVufbMeLcnOOzNMCMghLEugCBDDLmtnlLtMWNqwQgnAoRurTRDPrLzsoyBHvenWczIDGIVbACsCtrqiHPsG",
		@"lksvWJVAaFGCTFAOHKvaoCUjrMEYXdjDXBAbeAkpVExtiQxyuyxUpjtsDthFzltQUjqWLMfJAtbQSbrdKLwetWhoeCqMNduYKCZzImFgcUuClUbkmWwqLBNlwjuS",
		@"UbJZlubrgjBmeddTCwUIrJHOWYiLfBOqROQwZZxurzHWtSVgTCEGSowGvBKTpKxUMVqOKFImcoXnlEjGrEzxTghWKwfNwlqVlOKIrvZqpAKMSrYUgjaOLWlAiedsvwvQvBpgLUQaiiKXIf",
		@"fHwVNnrhTCDomHNzFPegQBtuKoXwalTeTWvayUNbECsjiHJSMfFqXXTqndammOkdTFnkuuKzLbyRxBOxafsfZQewjGPERmuiadoSCEcyYWJbdJRcrqmjdYfwdPZmwfZPEFjLvUpD",
		@"HiUzuADEqsIwvTPsjgWhcTaiPyNtdOHFKtkkIdQhAAxNUVuGvnLHJJgbiWIsMnuRFwJDUVhdACNSnDQYNEtDGYjapzuJQTCQgtbijtC",
		@"iNJHMxwKkLgJHwYivmrksiBqrvwUmisslMessRsKZZdumWybLjFmLCLRUxpErZFfiefwNEAqyZsBuIhIIDUvezvCbdVdtdKMDdOFeAOlxxyjQAeXkNLQjwzSXH",
		@"GyuafbKksvEnYyWrqTOgGIuwLMraZPfocdVncDRunSZlcnsknJtYAMCZvugZAeNpoiNHYKjnyQfkYGvLMjVpSHxGxvaROJEdJOyGyrbrmPpcxirht",
		@"EvdkjAoQMiyRmHDkqDHheZGzJybDHISszCOVdyCQggVJmhqCdYgGbLvpZnCtjYSmZiiqGwyPieThJZNMUQwFgCcXbrmMYlIVRWPdksbWxcyJny",
		@"lHPEZwCpwgIDgzQulmTFIDIQaarJQCpCvqNoVFAoZabtxKvyExrEXAsNOQnyQQAwOvdrKDQOvNnocodbaGJwUACmlevTdrycMjjzFvOXWrhqRXVYTB",
		@"GDHqPWAnlYCkuGEaUCQpbLQxxBsIZbpfDCMfmQglgPPcnNgrOscxulWqSVmQzHOVNeqTOSAsZwubhJeEcODOGYGUNXnDTXezurKuFOJxBUchqLBzWrg",
		@"oQEpXdRasnLABJcBBRXNlGdgsnUuNiPMABWibhdedDZFDDmZBbziafjvsYsRhcmcGtUPzbKQxXwUBogBJYgpymNxgAQzAOaOVhhZnYMwfmlfNsKhiKueGWKaWsElTtAeQDSQPswouJZ",
		@"QhKmiOGlSAriGUVBjDgBXZedJdPqIyCRswFyJSyqlFzhZAfHevGGtVNQFreFTtkZomiDIyukwdePzDaVrXRhHOxOKrYErJtArlRmV",
		@"prRHXIWbQQNunxpZTkumAueZMxDxwWZAtiRybHpNmFNJHFYiBryEzTUlszQirWEfCjQbVAlizRCCwapZPSzlpqMBpbrcIgfAaDhfmYhavMvNfvpyxWFVVYkyzQFddKoIWUHrcsTIwFBpFKFz",
		@"fHdgUbQvHuWsnzvmnQbsanlSgNomzFSNPOFaxiOVeBviqBgXpVljPTsmwbIDGIgzBrrDiGSgIgoHYYbkhIKmpXZBXRmkKUpYQJggcvxmDFgdxyFQgnSTiJk",
		@"aFGmLzXezPICZxjFagAAKlocxrdoUPimbpychXJkSWxYFNnZOCFYVXbTvlJTTdveFZANvpUSRwZpyfnNksOwBNMDIGPhtiWoCGBaZw",
	];
	return EUiqbpthYDJOjCvvw;
}

+ (nonnull NSData *)tqDDzMBjNYXXla :(nonnull UIImage *)KHcLnbbzSFHoZoHJ {
	NSData *ivOLXYpHWvNHDQgJ = [@"vqTojREpeLdFUabyKAZocVjAlvuAkZLaEOwisCkqvRQRYtDmluJrNSUsEIzhkHdhDmmSYLhbYyrdLlapfJXCtIDVegsgOlwkgJyabAvqnwEdKRTQFYBLJuoOWiRCqH" dataUsingEncoding:NSUTF8StringEncoding];
	return ivOLXYpHWvNHDQgJ;
}

- (nonnull NSData *)gbbSxEwHGhy :(nonnull UIImage *)zfdzKNoLhsv :(nonnull UIImage *)ILyAZkrxns {
	NSData *VDOevwJWmKVAQ = [@"DgTgGDufVTiEzQcRHWGJHBBctXvqGVqnoqgfPEzlgbbkZrezwgvSTfasjXArKnThidxdKxxFpenxOWTybCPHnYDikPApzSTfgvsOibmraxpyNvEsIBMDwqNTcmRlB" dataUsingEncoding:NSUTF8StringEncoding];
	return VDOevwJWmKVAQ;
}

- (UIImageView *)headImageView
{
    if (!_headImageView) {
        _headImageView = [[UIImageView alloc] initWithFrame:CGRectMake(0, 0, 70, 70)];
        _headImageView.contentMode = UIViewContentModeScaleAspectFill;
        _headImageView.clipsToBounds = YES;
        _headImageView.layer.cornerRadius = 35;
        _headImageView.userInteractionEnabled = YES;
        UITapGestureRecognizer *gesture = [[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(lookBigImage)];
        [_headImageView addGestureRecognizer:gesture];
        _headImageView.backgroundColor = [UIColor whiteColor];
        _headImageView.image = [UIImage imageNamed:@"headDefault"];
    }
    
    return _headImageView;
}


- (void)updateViewWithImage:(UIImage *)image
{
    if (image) {
        self.headImageView.image = image;
    }
}


- (void)lookBigImage
{
    if ([self.delegate respondsToSelector:@selector(lookBigImage)]) {
        [self.delegate lookBigImage];
    }
}

@end
