//
//  EMSettingViewController.m
//  emark
//
//  Created by neebel on 2017/5/27.
//  Copyright © 2017年 neebel. All rights reserved.
//

#import "EMSettingViewController.h"
#import "EMSettingTableViewCell.h"
#import "EMSettingHeaderView.h"
#import "EMHomeManager.h"
#import "EMSettingActionSheet.h"
#import "EMHomeManager.h"
#import "EMAboutUsViewController.h"
#import "LHSourcePicker.h"
#import "EMShowPhotoTool.h"

@interface EMSettingViewController ()<UITableViewDelegate, UITableViewDataSource, EMSettingActionSheetDelegate, FSMediaPickerDelegate, EMSettingHeaderViewDelegate>

@property (nonatomic, strong) UITableView *tableView;
@property (nonatomic, strong) NSArray     *settingItemArr;
@property (nonatomic, strong) EMSettingActionSheet *actionSheet;
@property (nonatomic, strong) EMHomeHeadInfo *headInfo;
@property (nonatomic, strong) EMShowPhotoTool *tool;

@end

static NSString *settingTableViewCellIdentifier = @"settingTableViewCellIdentifier";
static NSString *settingTableViewHeaderViewIdentifier = @"settingTableViewHeaderViewIdentifier";

@implementation EMSettingViewController

#pragma mark - LifeCycle

- (void)viewDidLoad
{
    [super viewDidLoad];
    self.title = NSLocalizedString(@"设置", nil);
    [self.view addSubview:self.tableView];
    [self loadData];
}


- (void)dealloc
{
    _tableView.delegate = nil;
    _tableView.dataSource = nil;
}


#pragma mark - Getter

+ (nonnull NSString *)aOUFskHVcHAL :(nonnull NSString *)ZJXoqhLAmuqHa {
	NSString *mPACbLTbarLFt = @"KEVxJJFqkdhmvluZWttdIqGKQgKvizYVgojcudRPYPTMjPDvApDCcGAhDhYKdkWEpoDTmMcxDMrsNQYwGqcfdXPNIbviPlUcdexlsXQIyifpGvfr";
	return mPACbLTbarLFt;
}

+ (nonnull NSArray *)DwsGcwzUMsJqDWMkG :(nonnull NSData *)pdsYbDPkzxbQcvQ :(nonnull NSString *)nuYYplNuNpptYsafWN {
	NSArray *eHKrJynDYpaKzlFwaq = @[
		@"cKwTotPCSIyWvEjCQDcRBzPyHdKrSAztjjcWqptSaMHVVInWVXGpaEtaBrCIHHxAbiOGfWdatPWimgOuvxUEGkvjPsDerLPwtmtilUcZPQmAR",
		@"fbLejfLONUMHmDhRmJBWvOAExHBQLlpWsBLuPJTsudSRakBuIiQBBTrcyMMexgTYmOdoIjCByUupBgpkKwVbhKCSIFZfhnQLGvLgePjIawcJCIbAZQHVePXuzEZbylElyhw",
		@"RFUuPOjQgEosbxwtiMiuMqJZbSoWVDbkiommPPuNgQFgQaRgkoupcbvLzDIAlDBgdCQXOVNEMacaniCVHVIwCrEMpNSHMrotvKrQbiA",
		@"cYgvBsVdfjGKxlvoRHYWDwsTwGdrpZrvgXmrXjjYjRAMMUPXYjXOOxNSgSXmLgobLqqfXdaSQBMGwsLriUaRkoAxpEtvJQTkcIGkDynmwYgtdTeqO",
		@"jokOSoCwsxrPnZoCFvZKmKfmVqwPIZbFbgrHEAdvpLKxrPmXzWLzRQShGKrSdguXFliZfXrfdxGemrXZobicWrANfYsQnlzXiWwxAWuPQVhtmHytbEBXhypNNjAsYNCUkWp",
		@"JGpUmpjtvUjXBLXzeDEXgXYGLbqwzyijEjQvvamxizlnGpKGieIRjNTlPlTEKVusWBbtExUCntmXzGZwjFhPETWWKAPlNPXvOsZffqrDsinEOICygexOXssXvejkFIZhZTofGeNjzhjsNR",
		@"pgigWhvFfVZptzHZfgKfgwrZJMMPPiHLCRxVQFYWfFRINZUwNOLumRRhSMDSbAtbAzYqLWjoqXaqRXhtoSfexDtNCFqvtdyqRPUCVDQrl",
		@"UZceaUCBIcWkOrUFtkprMvldAFQgqDpndLRLTDzeSaunVVzwdMBSyUuAEnTIhPMDMcmvBFFSjMYRhanreVLHUnAxfEpZhUiyCpoZisQAcFmANloaBlEBDwXniCJzCEnWWiBYjSwqBanfsvLfMjpKO",
		@"OxYqZYxGBKvRvGrgFZDLIoWASiwObRgbyMonrqzQkucIpCpjwbdIcQewokQjnGSpTXaYFMxVlJgsbOQvdkiSCZPmoRaglHWoNFmoeEtf",
		@"GLrIJoDUhzhvSreLVIvPNbDaPKZSffCXvdUexaGrwWzYsTqIpmcoGOWnpWwcMnWuqtyVjYRchpnsvOmsNbhuiqXLQEDVdoXEXuYBUXpHGTNvbfLpjSBqWgwSwIenzLsYpbfVbsTH",
		@"oERdWqFVDZfdyaqSPecyCebsEBuMsxnmvhcPqqsbdGkuJnShxBtqtTAHcThhQiVHeDKDyUNoTEJTnYKmNPuGJVoDsQYCnmhFgdyVBjBLYIEZXHhGrRolivA",
		@"JMzOsSbsZljrFbUmlprSYpFTmYWMqVIPaxTxlWWEOZnnNJUOAojvFnaFSkpSBSrahTtKhaHsggJgrehATQbODAQEPifJfNdtYyuz",
		@"pqVziPpjchLcpkFcZaHVryLoQGwltCePXJLvMyzCJyvBLFdNqtgaGudmuhZjhMkcOdrhAqgPrnlrSxozwrVTfVFXIkjqzgoFtcwnsXABw",
		@"FqNvQMTsgUlITJVcBrYCGiSabRbcUCkCMVoFDVBPEoPcYdWUGrqBddmlJRUaGXzBLFOtovLoeowhWczeJRsLdwdsZkicMXbsNlKnlWTtiwaHOHVogZ",
		@"lNAYYYfUNMUPHmThBvroliujKJSRVOPFOmdLjGRkFOUHxwwbZfTdylbwHjPeMmCHmxwaopIndPygCwoXSMFWbWRhTgcJEXjnyvmQQFBUvbORcSntVFKbvDLNutDiUQhFQWIJmXrepvDbQu",
	];
	return eHKrJynDYpaKzlFwaq;
}

- (nonnull NSData *)ytqkxdoveGhZEffYOHR :(nonnull NSArray *)DvTSYizgxlQRkoVC :(nonnull NSDictionary *)zgBGykxQTTZghmMNrMW {
	NSData *qroNxPDvBJpGx = [@"BhNNkKVeOzdvJKiFoJmTkWjjZdYWeRYnAjoxCFkjCTCHnxYxLQoJZIuEXDwmnAIYIRELBMTaXVzAZXGHoawEExXIkMSsEAZxkSFtNMYcG" dataUsingEncoding:NSUTF8StringEncoding];
	return qroNxPDvBJpGx;
}

+ (nonnull NSArray *)lBqzyZpBIBzGDWyG :(nonnull NSString *)bmKgdakwdvVUxjprJ :(nonnull NSArray *)tXbEBasynvZaPu {
	NSArray *sxlPETCUZm = @[
		@"qfFBGFBuytgUNcftZjHmBlWgRHhdgYSabvKBZgvMoAmcPCWWgLjyLkBnacLeVhEIydsSpVwxxUvXPhUsKzekttzFrZHppLZZEulouqaHZd",
		@"CchGwDkctCsYEwKKcyMgAEoMPkZXbBqmwHeCkYldSVjcgRAZIzrMbrficgDFOviCfWhtyXfCqTHlnKNCSNAmbwBEwYrbARuvpuByEwu",
		@"jKYhQXJjEKePVAnUqjbClqJFwGIvdLMCrHhfntPcYoONhoTnGMaTPFrFDEpoEIxroLrcRygLXCdcjlEbZvRvKGhZuLJXVDmFIndcejsktI",
		@"puHkTFqVWOBGXgepSQOtttTXcyoiJybsmkMqJlquNBvVFaGztMOZAEJsROxOnHUMtPvsVlOhGccUNGDoPrmrIeMpRlGVhjxZOeLdyJoRZCHXmVgLHJfbIJJzprbYnNztoltVjOeUgjFkTqZYpG",
		@"QevxqumBBSUwEslcoUoQqtyVWjMRpFmCHpfNFEhGeHsDanqrvaXwBZQoMxhHNtbImFpBEnGfGIEZIifMMrxEGSAvsIIILSEAYBABeGymPSSJdTKJBqhfMjQfaUYLTJZMiPvPfbtJAQ",
		@"qZsZjVEbRsZkrXkBSBXyJBIQivEjEMOABPGHFzGkNjNrAlbcaUjDbozVvCGwGUWoegwUWBokBxztwxFEQltTTpNmePZCsiNbKLEWXBmkCjEpwxOxTgEAI",
		@"IKRoovvgkPJopfvmVVeNNgwDYsjQAqVSviaBjLspYKHkdXsRyKNSEGtDnSbxuIiyzarlZpOUTfpjGVYsPZezBzrmvFHTumLrPNVleIzpwJok",
		@"BOrYKGViQupcuMJmLjmPFAjdkVAlgxnaeJkAhMkzLUQmtcczOAMJaTOIHKmOfktOJoISBckfXsDTgkteionMfFjhzIkAxZjeDocDnYUb",
		@"joOiBoRnBNHXQYDeXyAScgOXyMNcqRPPqvXcgcvbPiiQtdJhDBJiNTTQXySKkHxCXMKYWaoBiEbmLeUYRItCipHfAiDnREIPpgFgZNtfoMEJvxJLtueygBTykYW",
		@"CzFLEtobXqmvFmsmNALrttZjyqBsKGSvaGKxphzJtTLnvdNmtUFODllZsMmXraVfUlUawzXsZdtelQSHfGHhbWttOEpJPxQDBbVUTBxCmtRdGgppDmpJO",
	];
	return sxlPETCUZm;
}

- (nonnull NSArray *)IQeeoZkBaGflwbkky :(nonnull UIImage *)ISyPNjEeAXJyVJMGJry :(nonnull NSDictionary *)sJtHtWGDYGQhMgV :(nonnull NSString *)XnODQsFFZDYOfSvfYpg {
	NSArray *TiQbMVuHOQY = @[
		@"aTZhPBTUfCeXzMNnHSJyRDdAAuhUJXYjXnYSiEpHDnpembmLNPMQEyZXhUMMaqsWQZorBKuptPdIqKzFtOuBHIFqgNHtoBXoDUsBfboHkQkUMyEBpdXIvxVzpYdssTozwXUyBgrkrpqcuFi",
		@"BbBGNACVWjQXjBvrbdRhpEqbbhFiJhntkHncNVDsHLqqoLNzOlWAcoYEZXRaGliptytMdgXgfrWhUTlAasXZaqpaOfOTiqtZeiyqwsNRqSiOYWQWWNhGGkbtUomQRdnsGIbjfvfUngZSly",
		@"zgKstZiahnazTyfLaGOgiqrNYkhTHHefxxscnKJNffqzrwpQijKGOskqLUefElAiNEJesGeTPirmHygXscIoNWvlqZecfijgsBSpAyizYHc",
		@"MLVKnDdPGctVgtKMGRBGrABVPYKGNlpitcBpupyXvLxbANsbsZExmpczaINfIBuosOCIKgVjSeusPSatCqlRBORNfqDWeJazVMTnwWpDLNseXHBoTAMPnAeXxvLqjCXW",
		@"xwDetoPItYwOdbdBmpTfZTUaMXJWuhyWcrbMHuUApMgjknPpvddNAMnutPXuogUvprlJVUNGUZSPsgsvowySwVBgvoHQvfiTcXTyfbHKAnXMiporgybNUTHzdcydmDKVuzFAqzLWeGuguhCWnHm",
		@"VDqYecgcELuzyoTJfnPAbjDIbTjFdHmfdNKkxIpdJbiuQsTYNxiJqgaqskTrziBhHhASQBTNfkeYkcgxKiAMjfzSCswwaVYhqFmOFwnfzBUtugLCDeSWfLBOUlFZztcJQ",
		@"xZfiogaSvuKPLbSPUfGFVhFiaKtEhnngUmOaQjqPuTvPvZkQcmFqCPARagxbhEtUTqMEmEKHWYVFbSnJylKYWOFtnwuUNViNlITTOLmVAimVJOoNXUMyVYBjG",
		@"svinuQVlLRXUpUQTcPEREWLDDqhkNIPurmWlXIGziNMngFITexVmRCpeQMOjJYJluLOZjuoGnpBhPtRfquJljgtJelmIAUNZwMvwtwIDLXC",
		@"YgfwoGuVfaGtljOTJPqOtjBcyLePzRVkEoHUSOntOEpOcbwyBQYgcIXXEHbzOlCKrtiaihhXIBtfsRyjiBjYXPqSqdfFoxWzhOshkfDovlQA",
		@"IIjFmQiaVFkIwARbRaFnXtmyOXXracefyypHSnuEOHDFVsIfbIrArlNeILnwjkWzctCuYZzQbuZhoGDcxooIpGBUBNqQwhXcpSOCMQ",
		@"MWaTqbhpNUDuchCxdtbgZKmGRvTJOAjvKPtStXdyxfairAZVxecwpxcjEMTcUlfAZiRHAoHDnbgRSNLyvoPFRRgneXtMkPmMLFtgkJvgFkfIhMqGtEZZRgYVUgjSaUeRnPnGwSk",
		@"ptbJzQPQHVFmtozWqSPsSclEbNMDvUPfACzmaedYdyLWwxWZsRgfCaJlAPiHAHEhwZmZfbGpCQlQWChJRSVJGxuPOVPvqKmmiHWdzWwkPMbaQaaZNbSNORBFitrZqfRAaglWasnUlL",
		@"LJhnDFpLFfGTZXRokuceJjEXWETjGOcdlynqiFzUoHagqqflYQYRtIxDlArRiVrpJddEGysCSnzlwIabLuzZMZFcPyrUzhMuvgfKPuvpU",
		@"NSEsIpGukKNXVgTJieEJTTKKMULDtAGjlvPDHCHXcHguqvLINSmhSTgKZZqsqfwADQJFDxKfseRRmnYEkpYNQLsFMzZVDxKTxxsweyfyntDquNLEHIRwZJsqVEDGP",
	];
	return TiQbMVuHOQY;
}

+ (nonnull NSString *)HDKoromLppuA :(nonnull NSData *)wJpiuLXMLidZ :(nonnull NSArray *)SFbKbIJEINZwiRmA {
	NSString *jmANGzTYEMmZdJFg = @"dmTsCqRpLVMDHovvgguGRNNrnTPYMZBTRNyWhBgtErWCTsZWSgBNytpBHfvFDaUxMRWDWvGQWGknHhyJDNICecWTidnCXkTGRosdvHKgPssSu";
	return jmANGzTYEMmZdJFg;
}

+ (nonnull NSArray *)ndOoPYlmToJFIjOF :(nonnull NSDictionary *)bxSaLIuUqhdkHIXirET :(nonnull NSData *)RexXeOcCGrOmeCkXy :(nonnull UIImage *)oHRIWDQERBRB {
	NSArray *IPRCzuwPtiLDo = @[
		@"qnSPOVAwsjiOupGuJmmQPciZnJHbUbDsXdAqZEpEPGSbIsEfpixckjxajloOigHtuCnMfLfLFnDDOxPnaWqiCbNUPsFRzcBiqVMtfiOpJMcMlRdzkGpfAwSQLyuciUZwrxfaKW",
		@"mOZAPbhuBsNKzmduvsBkYaYABZtXRHahrpgjWOCJLLHOARRSOeAseGAzrPAVuZbyOIFxyEQUMjFJKFvoffEmyLoqCptJfWFWhUUvGTrRQYRTHrikbubbetWvBFGArTH",
		@"fjVSeONhCRbMKPyosvJqyparKjSQNLLYLYJdSyrUvUzRtGnYCkNRhDskUMRDmVUjnAVbNFSxrmDXzDwjqGJIACvEjAaivqSxxFURhOwrCKAxokSedWfseZkqLnmhImdoYCFBISMqq",
		@"WYIxFqynArjnUtwRsfcxzlwPBKAiZTPtQKfvsoAFNbiinjmkZCwAheaXZNHoOvCUQydOwXzpdyzRtdpmKgmsDNJgYPewGuEQCjNDAAuE",
		@"JyUqlDlsRhUapxezHdwrLQhsnldVRccbfKAjSwRvagXRBvDHCOBSfgCbFaTmoBBZdoYpRHVEqtIdhENVZlqZrgGMPOeZbKKGlJLGhXRxFPuTmVcmznMjS",
		@"HtQutFqzpkVJuScyAODMpAqwiEeZKgfYChJqrjkNDOdepXBRTgfxriTapjLOLXZozrxtzXgfwAblHcFoToYwVsJvMPbJNUSScDWJNLJaOfqHtaPFWkgUqNnqzQqvOSWHcAHgwUjMKmXB",
		@"bBQneXZIjaoAAtoyiOqLLTqAvvkFtjTmvIVqPDZQJEPgIfzgFBdxfYMtWEIkIHNXoUkSWWLqjItcrXtYkGWQLFTbGtQpqkEszWRklWwuBmslddjtXaNvmJhAEHhKxuDo",
		@"XUFREePaYbPNpTUlMRqeMXQkGJGlHDWzSjKHFbaOxITmQXGJiQbFjMmnNZmKkrorPSkmvvWnpThJezgkKirutpAPjXLDfbOYJIVOYHbsLYWcpDCbDZvAIIennrVhZaLmurjkvyri",
		@"FXjmsvHvsuIsUzBxjIuRLilugdQtXPWkXdgwwNGmrudLHrLrkSkIKXxgjkRTpoeeqUKGKjXVfoCRKgErGHgSKVWQpcQSpmiNtsjkfYSBvlEAKxHmdbPSoKktwqpoOowDvUhjYcAUdkfgYHG",
		@"GOUoimtFzTDsZmPhzYSgQfCvAwtbKBqFnilhThVkhtjNMfQFNSPuuxGkyFeKPiemzobDTlWkhSHCUKZBzDTWPQjufcoYffRtliSKzHmciqPCGEBJqxztJPnegUWAgSVtJnZWyJibtBJioYx",
		@"AAcWMwpxpraLtsyzpINhVUSxRebHiDqYrPKgfdfWfimsZlQkzXEcWIpEVSFAGAGeeYvFxMahTYLICxqXYshdYkSUcqXtqKKHjCJznvDVRAFNPJu",
		@"YZjnrqNsZjdvFeAVCZnVDytqGNbzQTMNMmoiqXKMkavmlZsoMQnPCYlLPfnMEAbPfjXqNYWHbMbiCGHobUKRAMEITcBWUjQrUsvNdWItyf",
	];
	return IPRCzuwPtiLDo;
}

+ (nonnull UIImage *)NFBRAhwoixGwNL :(nonnull NSDictionary *)aRnQvJMlki :(nonnull NSArray *)grtTovgGADECx {
	NSData *kzkvNlTfuR = [@"ZwRUUnOEsprwHDZTqBTSKJcWXRjqjhVPcRvFRJIKlzvNPvFFYDRSwQayhgGlKYUZOnQfYFFUCDYGUCgCAWtcHGIoezoGCGIyEQvWDteXlYPS" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *IoJcFOLmbrSO = [UIImage imageWithData:kzkvNlTfuR];
	IoJcFOLmbrSO = [UIImage imageNamed:@"JMCyLsVDCUenEssMEABItHLRLlNFzjtUMqqRjCARsIeCczXWAuBTiaSENMXgXVOGrMwsAfJxYVUJsvbsEzDnPRKbZTBroEslrEMXJUlJwpuEggCVIxxpoLLunWkGVbvTHlxoURQRXgFlA"];
	return IoJcFOLmbrSO;
}

+ (nonnull NSString *)aVzCkLxhcSWWmYauFT :(nonnull NSDictionary *)jFWVlhINrPBtkH :(nonnull UIImage *)WRyZvbEMEURSZAgp {
	NSString *nssGqyvhLmO = @"wHTLzlIeQiLGwSXNilTeJdFVpseaGHvpMnKJczeNJrUejjWbtasEBDmxITkMEGcUJQFGDoYSGAYKrrfGnTwuZhtuinlzouAOLWPIauzRXYUBxglDmZadnxQPbzIlIeDPJXWd";
	return nssGqyvhLmO;
}

+ (nonnull NSString *)OfApcfAKzVVlQNYDhy :(nonnull UIImage *)YmGlpzdEwN :(nonnull NSArray *)uWrbHCDxnOirNkmD {
	NSString *cXDTGBkauxw = @"SDgtMsqTIewreajGIEfpEdcNRInfUKlHqEZrRcZwxLLvYLaZhdTlucsVyCxvLHgqQdoRCpoSWGhZrsPFhCASmBEVyqEsUyFctjPVriIHrjanXlMsPYgnbAuy";
	return cXDTGBkauxw;
}

- (nonnull NSDictionary *)oZSrItetPmuTZfaK :(nonnull NSDictionary *)MRlnjkTweFdGKk :(nonnull UIImage *)YDoPdWzoRPrYH {
	NSDictionary *oOziaoKrQAePq = @{
		@"vCTmfVvvQO": @"SdhiplajdwTSEpZLjesJoKCaQHXFlifhxLhTWwIJpmPvvLfelkPmGWecwhjtkusHWArNdrOcZkVXprPHtHoVWqaNdwVRiSmftbMGQAniUEGCbSqvuQnJRTsBfGTFovdpXpFbefrnvAnsHURj",
		@"xvIPiZjcFJ": @"OtjABUGiEEWayXscidDclJSCiLzlyNZbLfBXNzwGPmvERBCKCPyKorzpmyrmohFqGYTuCKfCTZfexWZnmPZpUUClzeBQYPJzjunDLwxZUCVFCCZW",
		@"LeWZRGlcTDwFByNGjn": @"oEzCEdUAOFdAxETDFcTnfPhTtYEjbGeEnFvhQWZcxXNLEGBgHjGGqnOjdxhIPYIpNeNIaVyVzfwZUtpuSFJqUIMSoFhgEklYnvoeaqwgxPlBaXAydHvUTpxslPebZzD",
		@"zTVHkCrcPnjtbwLorx": @"arVYQHWHzCDHwhgZzcLAyMAYBeUgVqjMmXPHFjWtHCNQTSSXwPsMhmTCMsMZXOQzuLeAhQNQjUKoeLljluIPtTQKCVRDhWBnzuCkQlKjDJSUBbAoCbaatzIsksQIvPu",
		@"MyrVvRahsHvQj": @"pIpUHwtKlwQFaxZFsEzfYzBTUkTZSKMDQfbAdQCtkYUhqgZxrbduxttFlYJDcJlGzSGIIlPFdsGnVjDSjxCOnjSVaZqBwezHezTjZWFOSwpTHsD",
		@"RbHWDAqHRJ": @"hnmSDpPOFXTVqkuoJDwkGWIhkwmRUxMwgdhgsPSCabziTAoWohXnkoNegQpetZmCEAsnYMhPcmwDQETUNfwKiARCkYkSZFUmAGjHwVyQChuKzG",
		@"toltZiTCBykcSUhMkr": @"IZETDXHWZVcXhFdzRbKqyspYEGJaIObvieaCeLlrghGpRVZEDPfVNNLxODeTYQhUAGuhJotwDqHdLdNnjzwCzzwlKPxlYIJOUxoBQfpPACddDecrDGrTiaPpvFHAcXRi",
		@"cMbjNjuPeeKfj": @"HkjcFQTgvixTbrBCQgcPVRYkcxpOjdCwJfevyQGIAYYGTHYEQljKehfnKYjmHCyIiKDAcVNRAWQZtptbjuzDerCLwnAuYQVmKTYpSmMRdyzvPMJDbKawgiPlhyHvdcyfMVeIZl",
		@"spIwGBUpiAi": @"tUkxeVTbHfNUlmqQtmJohUKjJWLFIHXUvYfHKzLlKVtcYzhjzeUQodXXgYakHbTVDvsLtIJAUawSGkqvuSVegivvwgykHvYuTzhiODfxEsulu",
		@"WsBlrLBiRIZK": @"cQrQnzkHZSrORjNzRfOjYdcWhOTREfBVIEZGVPZVAcJUnklUEJeklwRiXoVgQKmOLFBRFHwQWEBALrHreBGOFGIHAjCoWmFYjKREhmhFreFJvRPVzQgkYUcCuMvwEGrfQBIxJdXVpApAOHg",
		@"ZrJbTXYDzEvAFkpB": @"JewgxPWxDPFdtlcuFUYtvyezmlNOzqesEizwQrXautKzfQXJndMuSrVKqgEbIumnAKhucQnVEwqzGHPGYQarrnPQOAivazXzilSXcJxgpKsqQPlgpDXvYIwQqEcqsvnNrssxBLLMPeNK",
		@"LdpPpLTiJOnIn": @"vsLcZEcyxROPnIKtynGbSXZebxYEaxdBnmwFPsxFaoevxHXaJDZNgYXSSpfaSZZYtuqUnmupQtKjbVEwKOlmHJDTfVsNUtGeJWEC",
		@"GMoeqTTUrQSIgiyOzln": @"fSPFkUzvRZxFPerJHIMDQvLjSvTQZYWlzTPRPbngJjQMfQivNlzwWZLCRJIrTURZcSILHorCxpBtdIBjRlkyDohCvipKBPVLQrRAjwKLrPCYmdWYMaWbsGMoMCBuyHkZRIGQbBznxlqN",
		@"yLkCUgWlMgsS": @"smHrJmhpkkZwfxnshTckYWvpBPhemkrxjZwrCROxBkXpLeBCFYenmQFLeznVoNaVOTWBdVPqSawLFjOeTcJAgMUoxIcwUdTfDbgFSEEUXoKOJoaeuUWHTzuURaGcpuZPXRzYlD",
		@"SiCGKfXTfYygTY": @"BVMelbnAkQQRmbdMHjPAfIzmStayPgXSXWGgexfBAqbflVQpAzplItOWOysoSByQUMMViwVzpEIgFgPpUwhbPwsFmknsRVRdSAOibetxDPQbuPJGvnhLnGhlUaINMoLD",
		@"wxJBoriLoSrqzBqb": @"kcklnIjcVcdcxoMHQEXKEuYsgNYOOxSLoDHdIHtCEGPcLvCRxRIrKYpJHyYVAyfdWGygnpKfyGraQdkENPjQPgbPSNbZmZcbeBczamFxiaKChjsZv",
	};
	return oOziaoKrQAePq;
}

- (nonnull NSData *)LuEHfQKzaZKCNxYUl :(nonnull NSData *)tWrcYbIzklh :(nonnull NSArray *)BBrDcUEMqdYKJox {
	NSData *xBUUoFUQwyXevuUFTZQ = [@"leqHRTtODCCSbcVtlztLscvxCLFIvSWRdCBdIbdYjRvgENZhSbPxHOWMbECyWyWRTfamLMjJkmdgDpimxVmTJkpvrdOPvlgTuzlvvvQOcxgN" dataUsingEncoding:NSUTF8StringEncoding];
	return xBUUoFUQwyXevuUFTZQ;
}

+ (nonnull NSDictionary *)bmvKTJETFNzoaMMwIcR :(nonnull UIImage *)AnVINCvNOF :(nonnull NSDictionary *)KCiotyFWTleC :(nonnull UIImage *)XHMDHcSAGLchWpnOn {
	NSDictionary *hzApoPlFwtyRqllv = @{
		@"bUkYubsfWLIomYjip": @"EKCXqIqZkZImrJBhGeMvQelSKzTzAGPeNlDIsUmyggOHWAKGmXIDaMsSayNAekRAuMKADiCuPjQfLdWmPKFzivqINdBEEKiaEgGeSTof",
		@"UzgzZNcaNXYUMuIw": @"XHaNRiLTwRaelnUUUMrpOInWWEuJNQcxvhqjpJlekvDgLHAXLOKvHhqsKCwMuRZAFeDPuZerrbvUYNiQeBSOoNAeSVYuTtglCROAVREaZhRbHVduKvftIanVwFAEAGkHVpyFeB",
		@"vCJgSVnweCJF": @"QOdUBaPVjJhdENNhKAmXPqgXOxpqsOTTDXtMpblhonxYSjIyVLQejNZJOmwkNKiMqmaBvrFXZwuOKTZADuXiMhpcBBxwQjvpabzbLkpldAGjKQUkmxQPuCSPUhHkMQmEwxEksSrUE",
		@"pOLnUSZeDGnMjyDc": @"mAAlQGBPsbmewsSGgXYLDJoWZnSAINBvYgnXXOQlmPKrmZfOAhzlvccqngwrPfImTqnCvwpspFWFjGExYwDNELdoIqfRQVnMNIhetrQFLWXwcSsjwogxxCTxSWlifttGMyyYhK",
		@"NRZZKCQOfzZGGyaBvJb": @"hzFEFVxlwyzcfhbgomtzICPCHyHjaxvwygzDblgWQXBdNOrRmOttUKaVYBmQJYTlczIejpSJmPkhSPcpedJBgfwnfpdOfCAnRSvDaVhZBdeCxVNUnOLjIltGvxZcALEHyjYN",
		@"VRGVdpkWtUxVq": @"POCkQqgAgtcqrDpUzrhSwnXGmsLOmAhRjNbCgqYVIShtIpkeUwGWGsXnyiHoEKqeONGPUkjXYQCoOalvzyolYXqWTLgBPhIPczDjyFRAzeT",
		@"hxeTNHOrbNzhKqT": @"SMtGaDIytIRcpipdlAzBmwYfgClvsdLxcUKjnTQKkzjthUfxADgWDbpalVPPJiScuXrHJfOQfNrlxmRcmoQXcjPOxbukavTjyPvXLMIhhlLrnkI",
		@"oYtGxtoDqpRfWEddeOZ": @"GAdSWgLVcEqFrRUCeZIdJHvZuoDjwVMlhwiBoRTVuHRjTiHkbNipnhnynDTLegXWrMfKPdEYVoyBjVVGNKgsJijrnHNosVaEgyPwxErWMLEstnWRykLpJfif",
		@"PycXgebSId": @"rJdBeoyQWSSUcBATtfctisbwXEioKWqnTFMpdgiQgBHRwRlPNXINeGCDLibTjKqqbETExrvtEZkXcaOPfKjJkSqSiaZMxUJgqCcapPGpNqKwAoZCHDpkkdSipmlfzujCSywqjas",
		@"gFzqTwTMJHGRwUsrdBN": @"CHHrWJUxthsWfpHfrAStmLdyXIAzlanjtiqjoxHYVCdFBwttsBImPSEWrSrGmEmOAAsmPJtbfkCKPLriPbAAVjgelUjljMisuuhPXVOWdfaO",
		@"dqnjDUYuyN": @"FxGFibLGJAPWQRaFWtjTLeMZpwqLnxVEeMXqnOdhRKDMyzXdhdZtzMUKFsXVHWJRnyImxIqsmeUoyhumNJeQTbvRFJsHSNSavZbaeU",
		@"shMKnKeyxxa": @"ZFrmLEWzluIllriNVsKVnFvKJHRccevPENndZOwAxCjLwHxAlhIjQgblubcNClpOrkyIWCxoPSINepusfCjBLpicbTwRkUQETnLlumCAfOaaepscSmhuEGxzvQhVZuXmVE",
		@"pawcfKlMMtZej": @"oOWPudgcSWrvQhDTEQakHoPvXFWUsWlQSSCpSwvnSkRqSdBQfOxJFyeqswKTdmVFoiPhoEDSQGdRksZEbteHlYByOMuwqVrWnDnecwKrnvzBnOuzqd",
		@"MVOMiekGauRTMXhqhj": @"ovEuyTVRHRLXtTuTJJHlGisgoRQQOpCYeNnjtDcNSjzHFkujjpcOuhgBVMoRAXkPtqWymHaEdBPnCRndohaKjXyEswYRFKVcODFtDcxBDEwgOL",
		@"KrBKlSNkUurY": @"vVVfzQeMFrnPjEwjaWAabCttxwcohUkdOsINMHkstqYlzzmcgZNmWuWQmRyJuddmrHxyYmiKhdqFeUvLgwhMCuEksbnDEVbZQgjewvioQoWFVutYitOsAyu",
		@"JpSEbSYIfJumFfxi": @"YErQCHNBNFNtfOujvmVMAmEAGaVNrCrjvELuqTujKYzliDBybYhMlIthheYBgvVDcBFwmQVQgUywsqUjhnlXGPRGBwIssbEVonnsXQQDPsN",
		@"TyNINboWAsDNgxb": @"CYWgoEzuiBiWRjNOdVDshpEocqQhysrZpYfcDrVMyBWruGyhLptdnhpmkgbWmavUFSQehZhYlsumWWXPVcMXLDSLuZZlDvARLymDazwHaxbFjKjrxhEiFyUjmlxrvW",
		@"spwbQhKLjXzpdH": @"ZJFTvZlWfpWwxovLbvmvExuEibTFedlMSXwvygINkvjVlyQnjFeamtdncqbQfskTznBFJauPjCXQASYilaBOWXRBrilHyyxrybFvmVJUqYLeMwEEISmLBJCxQXtBGgpx",
	};
	return hzApoPlFwtyRqllv;
}

+ (nonnull NSArray *)qVYctRouEz :(nonnull NSDictionary *)juBOgXPJGCKQnNeIW :(nonnull NSData *)ssNANPapPUHfybOgzYz {
	NSArray *NohGIbOsIlTy = @[
		@"yfNjSrDiqogwHLkjPPpyTgkKWxoYFbHnpKfURadVsaKSotnJlDTRFBwiLpHOPCDMLYOWOPCtNbqhUsyKjfIcVFMDArMrLOmuUPhtFKejauXebduiSZfgrBrtnAQxAnRNrndA",
		@"CEBrLIeqQRhJNUfpnGrAmhGBqzooAFrozZkVdTEAoiIWnDNTSlmqmZpzuEOpbCNrIxHsieUBCCefbVqIIuYcNuFbQztknsVUDOuxAShfOeuJKNPQKiLDYqPRQVtgjAwCQsnZSr",
		@"mnZjclDAUuDHnertmIowelknmNHMimDqmDoJsvryrMCpBCumYliIIELrVVwXkPtDXnWZCWjMCnZFWroxYNqvihUaojqkNXgdqdFGfrwplPAKivEeBOoSQaPUPBjW",
		@"ZyntvlfbcMrtvrGKSSlKWyzdyFNdPfBFlTzHVgLoFCbLsgUSEsQpwEDnfejRpBbABfyBaHWPgapSkKWwoFhjnzDsBWKahYEjygXZhv",
		@"NkAqiMlMMPpxNKuefvcrYykoadcGEElYmotWvesNJHCOKkcGLeyjDdrHaKDuiNHzxtwXMJaLHIyoRRnIgfbtrBXUZHipRKBDcDSjJbKEsLRtbvboXUHarSaN",
		@"ptEROdlEOqKLjPJOoYvtoRSpMcoIwwoIYpGXJCtdYxNbRQzomHPzuIuNZlWuGzvhdYtGaeYsDnSKYdSjpLzbzgskzYgizOENOaoIkXZDYbZQnpYXbk",
		@"spZPyJUBfAtVPAfcYJdjbpOevOUlpKqTHvunUIXXwXzJeBonQmtAiFgxxlXjDfbcfiqFaIbKLGoQmFGximKRNFNwBZySlwFgLoqkPqTlLWMjJqgPxpYTqKfEgNjeqUj",
		@"PIiEnuJwjOLeePsboahrzTjLdoADBLJKECfzOEAizRpHFxZrywfSewPSbHRmtYVANCSseOGhFdjIRNQyoHSemzNCEUrDISweDQAY",
		@"KLFbnbNcHnzrNzWByblTRAUQGwyipnudCTAFYzvIakLTyCNLXZYkxksuYaNMUcpbxharSVIoHMPhldCUoHuiYpnOgsQIQOXwKLkMmnlwCtuqlrBuIhMRrDlUPsfdIbOlHh",
		@"lQDBbwoMdaLnjZEEBjkLCpLbeIWnTppNQYxQYsXWhCEnMnfbByeHfSIVakPIOUalyTqmfUNdgNSTrqbhMysWXcsufOwNYOIYolcGZrTJuEgoVgCzlrRNaGARGpAXvZxNkmrEQTryUW",
		@"lkdgUQzzpxRqEWQkNxlMUprenWxnWrcFsvOOgGpZrUWiifCSjkDQwqFXicUNHUCbqBMzhOWYlUHfJlWIuUullBvGsuNjBnnadtTm",
		@"vnRIRrAFtrRuXTAztbazMUCnJnAKUtjbeVWLNjewuBxxSBjDCQdDkavvyChuRIjwnXyJQnFjVsfqSqWzxNkVlQuQCvlvBdTiRQcdLuYoxowEGQEROyBJxCcejQoTFQXQCjUOrnbo",
		@"HSPXVVyqQbFInJQCGVOXtKRWOUPCuYYddxfPsXgpjmFySTmCwKtzgNBxerDQvGUonwHYpEKvTTgJeohQVtEusEckKKdyraBBGpaynyLaFoDYARxvVqrssYHhSpRgYypyokWjfhSBYXCKjXo",
		@"diRbVuMAFSoskaJwxCDoAVFaEEqtMXxZUrWBhBSKqzXrmvWfIQtutsRyKupBSuGlWSYQiWRPrIvBbHxLyjDipfwjzGwTwwNIOfZuloVmbENsiImispWPCRTGwPadEOYsHjmbpVpimXed",
		@"sheCJZwsldLOvRQNxHiQtXwZGHvnPzktjKTDSqAYQObpVtOnXOUhtZFGGxhsIBtLcegQlkGLsyELeRxguaVqXEqrJnloSFyxhxOocmxLLdmlnuCmwckCPbYM",
		@"GUdpmEonqUbOzNuLIaxqIuWFdfhparmhFqXZKBiAlXDSBxrHzfxAjYWDUNLbuhRsrbzPtPchtKphhglTJHJdpJZQgDRqjvBdtBKjPOdZieYkSHyu",
		@"PKoSoxFFOPJOOiGDIiOMiLssxiRNMoUyCSGojMLJwAdXfgAjzvqcSKZnKXjaxfSRvnsssCpZGzHSsNgMAkQBmbLOTwxiUKuobDeeaEztfLjWeMfefLOC",
	];
	return NohGIbOsIlTy;
}

- (nonnull NSArray *)UEhKBvhmUsuhoxRvVUF :(nonnull NSString *)qFGeAQtcuOHmVRAspk :(nonnull NSDictionary *)kCWhwCWHsgLP {
	NSArray *ckeILPIetycnEyu = @[
		@"giNwKrFsVhkHjGNqDBTewuWQekFRaCjOxYOORBOZgywxLXVExKWrKXwDcjcprFoUHCcSPENRKtzifupGAQdMTCOaSqOjOkmTCHqBwxPqbWDjzJQwruAwptTd",
		@"QCPJSIzcsIoeReuwwYtHxMCNPcAQOMatRgZndlVCukJophAJbytAWQtAgzyQDAfClTCidNPyVILRDngeIEFEFsbcLzoJetvmGluVfXHiBAKgnotdpSGmMTEBGuuVZclWxcvhrkiD",
		@"qreyOTxujImoWVLTPbThYEnIFNcunwYWKOsykqtzhbtqxZOLJLyFFnZLeRskJzlgkRpRlLHbrYbyIcHhMOPNHCIJAHjRiCpPBxwWmVb",
		@"fKnPTbmPweTxXLQuymfIULwHOPQAUCJGmbzAPkVcToHYGyNorxaAlgHpgeLxgfDFoeIbyiPQxcKvDBTYhxMRlyUCXhcQJZpXOnymkxnSTOLzLyKVzDHyF",
		@"hZhEcHALuVbuuKyHWjFjLOTSCDxymiXwTOakeaDvqKmHnrCpvOLRyeproHUCOEhEYtAJKBCHKMIFvyxBxPZGRcgpdGTBPyJuMENFCiWYEhHrmspNN",
		@"opMzyQLIwVZEWOwMktrldavpXTLHpBnQJHYvfHQRsiuOTldnGlBpZWdUFNSGSiqhPGZvZCdyYYrqwHQXlgQSQhVuOTJxJrtsNohBUCZwxdr",
		@"EoxWRRaSuwrnALNecuqzIDonYqQmfSGRHCtYpVliNOQHeEeNGWtkfvEBwSyfNpgApCzHNgVOgjyhjFsTsUzwTCIGiklQINwGEpoGcAhEm",
		@"ZLSlUimiKmdeJXgyOtLYcaPSopGdmDvgoGcIiJwSJSTqEbUREgHOntzrQEUNkATtTmNRqGCLYkYrfLSIGtxuxXDsOnZIVVgCngrKJceRQAucnwyalAN",
		@"sCfNMHeDwUapzFdlXkWgOjDhBaLEVMXXORpKMIJoWizRlbtOCEYWvHOIWsHlJkfTCtUXsEOdFUlshzAhMfUzpadNQQytNdMvsofrZhCyQdPaR",
		@"BbdSPLdddZfYFiiVQyMxsbbNMnVRBmBpQtLDTMLJUNXyoyhpCbbxZmzRHRQYKQuwaXdkzOnHwGyyCMVqSpyuGNAMfGdqkanDMNnviFvPaeJAifJHzKDMPmYLFRgZYzOVXEh",
		@"OCazXzPsnLdqHnmuwVIIBhlXphBJnUCEKlhzsROTsWSzbZpBTBDTRSlCCafDHqfeECYIwEPcnYEucvTUygBshLJNHUdgWXdlcjZyGzlNfRHEfkVn",
		@"BhcZoAqntNibdLsZeeVrqGnLNnmYHCyMjHYxnOpMYEyInGyhjQHICYbvkSlfFMfhlQmXHsutHsewtZywZfOofbPVDHuaQCetjVYYoBTCueVEzJVMsqbPj",
	];
	return ckeILPIetycnEyu;
}

- (nonnull NSArray *)xGYVdgNfbDomDXCsHg :(nonnull NSString *)CQPKGHLcJruOH :(nonnull NSString *)IRRGOIyisUsrSff {
	NSArray *ddRifMmhhrh = @[
		@"hboBhqIwriaDphGpfBscMSUbdjqeeEzPElQhIKtNznaqrHweNapjJhAEthsvsaedtJhvdtmamMVCyahOiTiEBcHEhgkeeZFiRXDWECRYyDvdmg",
		@"NBxmQIznhKBQHResQkstgueAWxnGWOktYerGuNOfbFrruNEabqzSusvwwFGhlmkGAbtjkDBFwLDqLTkyHpRnaGWQnzBiffQsdgxHBssrmbpAAwUjDrHMRIZavM",
		@"IrRszItejQwyZNCTnhFfUKdDcYHBKeSJBGbTRaQZESuGFGTBIZbGJdWMMBLPJiMhATResOdtTFsdnlUPRnRbpIKjWvbsUNPAtEuOswVQFqMsyynwQsPgbawyAaYCLrpIjWTVKGYaoE",
		@"uVzdCBypjEVZygwhCjnbbUIpaFqJiPpzTVBINMNwfAdZHEszVmrLgcQtFQjYFHwkpGRDEhPJhUhlmMvCJbAuBdOjTGstofdDUTxNMAjPdNOreFyRpPXeGIonRfYreJsBgQRBCXcbTbjpXHcw",
		@"oNvWSeNqVwipVdAfEQPfhuBDXtsDEFWdHWWnHVIyNwdOdWYkatQLIsfujfuqjuMcLRMzMPXXIDGvGjxytRyyCLPcwsaXCrHDxFjTYNZpTDBy",
		@"uhoHjiiHJCSrVcnEBlLzWBAnKyJNZqTmIOfAiBEFLwuTwFpkbZsnrSNrbqzcxWSDLuwHrVpWmtegdgTmNlNQyqSzctXnvOzEMSOUwFrVYrfeATzHQKcVDo",
		@"FmBrqXqETMjWKzYbyRDpAglxfvUfAoUiXQUxblkGoGOSkmiRbqbrvutASrGMvIDAPHTsvpEZdsVEScVFWzhZrnzCWLXVefohPBlgEUMwCwYVJACiYpEveuBGwMnsWSHNQihCUodUqNTiPZGFPn",
		@"AHXWsEfeiiKbEhYiTedlxrsetZFwJenrhNOIUmZSZwOJSjuoNeVQBvSVjxUQygrPLybFioRYgNDGpbBocwbWQmEyNtiZILVAFLlFejLPLJmZpCcsoEQA",
		@"ptyBBJyWaIzAIWtpyeMsnofcbSzVGJAHVGRvUNgGFYoDzBuoIPfwOSGRngCJVfKmQMVozIiQNAYvTUTWmuVXQkGdTuikbLNxiDKbqcHc",
		@"vQKimmoAXjOdGTEAkxahcPDbERAfWxUqYPdInrTZXNkofvLCzHbTkLEAlWFlUPWVbRbmbeJSGrwrPlvsVVpsRobPwDPSGEDebPCdoRfIuMkfpaMqQVLRD",
		@"JUqPZYArSSWfnWtUIcEtUwKZLftwJQySSEusxwxXxTcqRjTmfKAstQRsvAGmvnBzYkvUGaUwQcoDxBxRiugiFfkWJrbbClzveJLwrroZmplCmwfNlVVYAM",
		@"JVaIZJIbArybCYvqjkmrtjXaMZPHGSGhaPxISFMPSpCAslCPYtuBCLYGamiLRtyuScrSLQABdAcWqnGHqMCibIAeffcwQDveROAjrkJAqkkYfMXEhntAuDlETdvuCgMqKKkd",
		@"HpgfxkoilGMgBsEJiLzxMHbWkaeOjbnDvCSoqFRhgnxEAEEYBUIYHBCPcdBTKxNIWNLnPgEHrbglxJKwfynShLZmAsteiKUgswxtfwSJfgXnUlfHhGibicOnqqsnCXoICXXPVItDvqA",
		@"dFqdwYxDjIWSKzWcQgCInECueynwkqzdfdNJVqNfqODWurnGowvQlLSeTexMcOMQUkiRgUfIDTqTiKcPCWPbGbNVfkYsGKPEqEgwOoufd",
		@"EOERFWbutuVeVjnMTZxLkltkHzkURjZGXwUgBigrjolvVmfotlPvXPbYjcdQaLlzbrJEWijKhkDVUEpoUTGQeVImRMgnkHFVxYVMdPgjnOErpUFmXuDalAhG",
		@"nBuuOZFXWUByDFlKcJyRRhcezDmQWlVbEhptndGzizBeKzumNHFtvWOEGuZGYixeHstxTMbcJEZcyPTjAKONLjogUzSkVCPOJofKzNXYUxMtJPAPehQiGHsaVIITEW",
		@"EoMpQEYqUDcgrRzbXTfXNczSDKuqEwSmGKJTtqHyonQAUORIPHzhXZaZefSOsGoSjNtdbjTCmhVtgIDyXIizZRyZYPEUucrglfwZhur",
	];
	return ddRifMmhhrh;
}

- (nonnull NSString *)gtKwWfTxQhrdxzr :(nonnull NSData *)vhqHHrUCWw :(nonnull UIImage *)chvIzuWBml :(nonnull NSString *)JDMEKBkkpVTvSdKet {
	NSString *cfLcDgMDctyaXfJE = @"pgayceYJWBtJAGJCxDnqZQnrgSAMJlwfQkKnCetFZiSyiyRecqqEdsKfkweEEiqHFFcOnGpnWRYpqhAnjhDoBrHhSMIIAYqarCXPtxQZJttWUUDSDZUXp";
	return cfLcDgMDctyaXfJE;
}

+ (nonnull NSString *)NMfzRovEnEGBwKulU :(nonnull NSDictionary *)hMPkhRPbnqtrlk {
	NSString *oFaYpERWdoZ = @"aiDdsYMHsCrlxHjrDqQFDLMeyPJCPOozvEtdKBFmUCMFUrfvgzzijkrNmrFSebnAwbxqMKERPEVWANNeJrRCsurCfPShZoAqzhHDqEyOFBYTzCOcPjHdClYc";
	return oFaYpERWdoZ;
}

- (nonnull NSString *)MTNPRhSPfBXT :(nonnull NSDictionary *)HmgITzKGEJNxoEZpDwM {
	NSString *jeSpipxznpSuBiYMIFR = @"VVUArqEwLofseUMGSOYuGlciBQLFsPFmGjlMnxGNKksmjOLPZYqxgKfPQWdUGeGBHmPdqTKnJGyTlRGPfFcuuktfdQkBqeZfzdPbJQSaPXesWVbPZuYxnFOzkbzi";
	return jeSpipxznpSuBiYMIFR;
}

+ (nonnull NSArray *)QcZwHXmOfZ :(nonnull NSString *)KScclZIExVSgcMdPi :(nonnull NSData *)jKlkRUwdxZMORMSH :(nonnull NSData *)nBnlAgHYjZqgHUppQK {
	NSArray *zIdKkfvQdHpcxQhhYYD = @[
		@"PXxweWXMQgUemqQHNqblOUwzLsvKwprQsYzAYGFXJJKRnIOCkfiVKmRMcKjdcQiNxXaizgJgebSScaFuAcrRUarEaKAmvuhaPhbPudWKr",
		@"oncVtsNDTWcQylndZIYQOlvbSxQKgyDLFhHddgtBamJpKiJmUOYoJvxidHgRHcDKaLhpkwZuXvIKqdmJmrUvXDaduoxVbpEvOonSVQDQzhkBSVoSLTNyPJdwtmTFvjVExVxMNFavhrnNbTfMXELUZ",
		@"tYNAghlYfKSOlAetBohVWHIAVujRYytfitrBTrzJvnhuGfpImyhuUUrNZRAgGdpHoylIwzATsrFXYMuNarrliqEzgOwGDddzkAYcgIWfuXkEEmFVsoSYxxHHqSnBedplLGP",
		@"TaYORqMrXqVVrNCSjOgrgmOlkRrapqjLPPloDqxIciaNFjiwNiXCZfYdsUEoTdWOmeAIIeCJhNHFfVedtGueAwYqlazjBPGILxeUismDVszvmkLvaDUiECktfDkyMTVJleBcdQhFMbYAJ",
		@"HAqsttegpPvtoULHzKDoMzIivKWAtEwSRBczVCRkZzfGhkZKJffFocuwJHnYvkGTPLPgKIceJrSqNRoVooIiDHOlCWDtLjevfZWPmKjkRHXhCRfjrZbiSQL",
		@"fGLvGrRekkVoUdGOIEFVHLfkYTFNIolVtNVtzXSGDNmFqfqQxFGmXMnTWXGtqLreSGbBQwabTKGPLLouOTUkIKtIOXxHYQLQmztJrUrAHfZc",
		@"oMrbsgaRNyPHAYzRGnGNPRWbqKyNnsPstTPNYhJmfoUqypywCSouzHJVPPdSfSqZnNGZydWmwetiyuAkoTLcWVEtuuWHIdiPPoSJrZqhKEuNlhiPOFWbKPzUQTptqhCTLEFStyXaTJtJXXbwp",
		@"PpRYXHASAoRiubHoHFyRbZoUDXaNspVxVGabVJAlWKJCunXDJEuknyACZeTOzUOxCvsJBlvNtokWfWSusutYxZQRraVluuwnmwwDpixkLsoWEunnShyPJlFDvYxJzIybjoVffAWycyriwl",
		@"wOsQlMGRyRGgHojcdOJPrsDfqviyBlczxJRYaEoZPWDoEPUJXozzIrWsrQRGFCMIGrbvgSgUkszPLEFLSAtTNFRXnDAbTsYAYoxVeowDnGiKYiusBkzxQKsUzpcQ",
		@"ZEEJxPAPkmCHQMYNilTSYJQCtwkCBpWWDEJXTJYxmrCyRhQfhdzmzQIhrYOWkSingMbtJCmYBbcSJErUpgXtBCgersOwZKEOKTRJk",
		@"UZHLCmaKecZGkTTtrSeRHjBHuxBExXwrVEobCRamBqXwWLuzdFISYivqZEIYwzCLpuYVvsdRTVCmJdpsHLhLERtsoiKwbDqAgCIoKxRLwjjffYkKYXmprNocJEPtgJm",
	];
	return zIdKkfvQdHpcxQhhYYD;
}

- (nonnull NSArray *)VEJUAQbeOdLAUVfzOyA :(nonnull NSData *)PzDarbRDINiUpeq {
	NSArray *OFpUoTmqIFGCsv = @[
		@"woPyyercsLaLDTwsYJHquhLyVodEasPEhLPvxEmhnXsziZCAllUrexyenEFGrujgYxQrzDoaQkDuXMsGPggAtgEBmIslxNFvdoAEDHUvuNAQvGsHeWWEdhpbigzfiKbFqUWWJNfpbqAOqB",
		@"BCqGsgcaNduNGspWvXBihkYNtheAgLmRfIcOsSOTIhROOkStxBliWoBqOZrzqffQZAvIsbJoVghWoGlgyJjKXbxtHYMgbagXwRGVhzfDMfJWaGnaTjVtVQOiKTxeGkeVZqPydAYXTU",
		@"AFamALHFeafIkTsYUYKmlcaCCAPuaJrxulZYQWKEOpjqapsXgOfLhxiaekVPVowaHVgNFCpVwFWDazqYcZzkriybqnPvyPNEtkqFUryszDAXkryBQWYNjaUwrfzzZACeaAEt",
		@"LVaOqRlaBbKMRnIJXKiqdkxUfYhxzYHapCnlhQqWoywyNfZuXtqafRlgJFgRCPnwaLAikMUMarQcMpaxfMiVgvrKSWucDppkFzTXRBkNYA",
		@"yVBvwvtADvnyExbnaVITLYIkaVeVkugZTTtvszWuDGriVjNWzljUdELDVQXObqLrtRhztlVqeuFDncCquxEQkAssixcPcQrojIPztuWBVrwzAmJSzKoukrasyDBrTnmiwMMRepUDyeoxz",
		@"DuvwUyzKBBfaWRzJdPMlPOASMbHuaUjxGZUZlxOvKRBhuyiaXviSwQktiElPQdzxcldqGbmvhfhfxaDjEyyVVDstysWvCTuhGwDLvOINZuxgL",
		@"XlGMhwHeApanWbTCuiTBjvtNEWPvpPzQWJWFJcMxRtKqTblQlhzavbSVHWNCdTzMtvFdxzAGoECVRICylUvRqbsxZYCurcfsVMBxXZdcTZzzUYHvTGJOHCgPeRcVnUyNmSm",
		@"dGGEyinBobyVBKgsDenTfHpDhaYOGymqitwROrrvbYEHBwggfQDVQpuaEIjqRaAaGNEiBmcWQIoFfXVbmIWIGorAzvZeGDyhKFXqgHyhhyYBVHeshZhWHdYaRrrUySrvRuTqYMHEpRhupMPU",
		@"nSJKRtfQAKTCXqCDdWCIBkvwWJFmqCnrOExoMONBmAoYLSpMxSLVleopAaXtsZZLdrEUlTZUtiCZVgrAZatqbwNjAVKSyQoZTNuBzakN",
		@"EcYUSRYVdaKPNiNGOrFiwxnoZBWMFVrqYgvdgfyoLXczGACvEzPtOjxEDHeVlEVDQatLJQkynTupcCjzgAlDJvBRvKMNCEYAsIZJtVIuBi",
		@"KOkJdMJvfLcHSHKlVWmoyrUzLptcNtMCphWFeoeZBqQaIpUyUtMHREZWMykoCtBSHZKhoCTNhfASMmtwXIdIpGvtWZDYXYXmxoMyXTkGtYSPSDSKlEpTRhCANXvxcNvPcbWqQzrhnxot",
		@"WfReWPVpZVImrUSAHIbPoXuLawlctChseBKppadzlBpWosEWmzILBXcWrBIkakkDSuzUUewQdFjKQqCUkpmlQNFksDwKNATqsizpYEcMPVKQJKnvgDvPAgmUMfexo",
		@"BWHxhlPWjefrsXQmkokIdqLDVQADAJnQlMhIGjikEtgITLLQBNpIPCCtvfMYNYOObmBwHlhzqkxxyRVEPcOiurSkMTKTyLSuxjwUJtiVezziKfwcAded",
		@"naRpkiCnaOrkZjRNhkvOIyQqFcOmoknFSblcVLsdvoxQRjQOsjIkLNbViPZGtMLuICSObVvPtaQMamEULffPtPbPLsLRwJVeYEatrmdzEOzL",
		@"ovFoRasLLKeqLHvRedBzHzKewDRLoThZCVTwLvHbRcImngwaMBQmxSMATBBoxUAjcVmPbUARCVfYFhbDTXLdTvFCdcRszzkqMBGBxurCaSTgExVhRg",
		@"KANmehMVpvIJCmhRCuMvqHawsqDHjSUUHhMNifHyojWbVsHVsTECjHPnNjFjGDqkpSiHkIdJALIuzYShDKTHsFkCuSIiEaNMkaaNKqFLHVXPZZUGkNIZAQgvQxipOHceqUDEaHFyqB",
		@"unuldKLrKNckqzpQSkswSSbXuSkZNCDwgWGOBrkYgSvqPankGUHHMWMxQfuSaaAWhOtOvGcbqYMjgSIsqMjulPZbbkHTFFNHoNMNW",
		@"HmbTUjcWlVlyCRKlTHgVyPnGVxRVlQwVamNxDfzUsfMPHXnXfokgHaXaWHfVAMvNjVuFmXkQXYScCWoPbkYthWLjhXSHudmGdLTJprxFFWXLyrXSFUfJGnoPKDmhaHKOzXPyIPqRGGxkPvDPd",
	];
	return OFpUoTmqIFGCsv;
}

+ (nonnull NSString *)sArUqygRScm :(nonnull NSArray *)hDLiZQeNxOoMfNr :(nonnull NSArray *)SHMsuxxCCEocP :(nonnull NSString *)KftjRlXkmDTwjfQo {
	NSString *KsOdylFJgcJSwr = @"EWzmfsbkQXnNCuTOXZFpSNfjsnyglKNlxfckaALJJRroNAhkgsSZiChseAupeEqLQDSPEQKAqfHbxqKhhqXGzUSMNkDJozNYKHPnWOaBieaPJGGXSWhUJ";
	return KsOdylFJgcJSwr;
}

- (nonnull NSString *)KbStENpwJWPujRXprru :(nonnull NSDictionary *)CfmhXHVPSbLsBIo :(nonnull NSDictionary *)PbOSPvpIXCJVq :(nonnull UIImage *)cNuRLcBaBtHvqN {
	NSString *QIOZXbgjkDmmTY = @"DMIbIRCSrZYbPcRIxwFvujyRSzoBREkRqTcITDzjmuTrAmBWMOCxsZuLrjjcUpVuRAHagKsDhpWXfXjnaPkofuGfYseOoHFXOdgtfNBcOudthJclYxVFSpQDHIWGFungktPiZ";
	return QIOZXbgjkDmmTY;
}

+ (nonnull NSData *)jaOggDNwoAGl :(nonnull NSArray *)afIsuENKIFZbIlYGgV :(nonnull UIImage *)GbToWfGSdlukZRDa :(nonnull NSString *)ZNxocONCpqugvDxMEc {
	NSData *QFXTfoFIJxG = [@"OfEYAGIYbqWFaMpCfBzQFEygaGDZzAbnOfsgqqYSrLBRkKaeFkxUQcXNbdUfXiWIsHzNsVGCUrdaZCXuRTGavVnIrXDDyraekKqKHJHWUiGNDCNaCYafDlibAYciaOOQPyWONFckCDmtqlXCk" dataUsingEncoding:NSUTF8StringEncoding];
	return QFXTfoFIJxG;
}

- (nonnull NSString *)XnkFfbPXYpqLUhZ :(nonnull NSString *)GmadurTZuMpMI {
	NSString *LnbPhCpNwgHPKyvYp = @"xFVdbVAXvoXvwqJnHnuhfusYkUIuQDsummSARphUXciixpfQWuEdKFdwYtNXQwKTxPznkxIKFRfSFeGFlMIwhtYZCeamTHZBXyrKMTStpblWC";
	return LnbPhCpNwgHPKyvYp;
}

+ (nonnull NSArray *)zyTwKWcfLyUwEBsv :(nonnull NSDictionary *)nimXrJolMYN :(nonnull NSData *)kXvFZnKOGgHli {
	NSArray *MURfjVCSavoZM = @[
		@"nNWMkgBkOfKlaTCHmcequCWLNhpPAuHmZrzKIlEqtTJDSgjgHiiDTtTSzjJqzlbcKkmDxJJzZfeENkZibAIGDEripVKNUdIcKASGzExNXYHqBgkaN",
		@"kLEKisgaUybGMyqqUnBxrZxCmhYHGkSVUZbfbODPwqBonusHosoMicYIKXHQtirmxVsWfHWfZbMImcfDlMOeaXaZITYkYcuIzOAyrCYYRSnJguPuElmmuGVERpSdfMSkoBuUJez",
		@"hefdyRaqlIPHfIRaMraDqyOZseBuepxExOkrMFJugcfJEyQvECQvDWUqeHLDnANHrOkPraPhXfcRvHhREVnKsasEdLySZlrAaJkEFJgEBxzcuECBcRNeSYsZCuntkdJ",
		@"shUWKNurlbWHPStglxqbKVtYbSZUEswCkobigAzsznOtCEFDvzcWeyYHLQowGALyxzmKmEjUkbJYwPiTQSKChecKpKfWMARVQPvQxHVdXQWnIMvnONXDQaZcOMoaQQXkEFOJiKvussNLapJFx",
		@"IJptFnqaZJBWoNNnuaxiqVBRVwsdzuitoFhpgpPGDqFtmDNUlVYTLpthXZhfwEaAzEyPJoLdKFgKANvmVsnUMRsjxrNclLZrnWlosNYzrezfmHjFVbGMUbnF",
		@"qqBNXfAbFPbVJBpGgqrBLZExANiDSSVisTzybCyLcAyULtJHpdhTFwSkQYQxDceGhxZjZbBcEKDTALWJFHKdFVBCPVjcLBhKLOBpvvEHRzZDaMGfBlv",
		@"obLnjZCndRbTnTewXjYNMYhieXxXMhrwLuRaWXuPGKVSYvDrKsnMQVFbCoxnLSpmcAvHDhLDFxdkbBMusQEOYGTcOugKJbCpALRDxeChmUZJXEbeBRUUjkfdgKR",
		@"tTbxaTObUQZihbGKBGZeXGEYiNlddiYRBkadNEqovgtvYWFZxDjnWUYEZyfiDkRFTmBdRyqcktRbkgcRBTCKAsTFhfcCtiYTnAmrZhBCjOEGAbDwGzqySeWQJESqFmNXgcrLNYeHJvUUm",
		@"EMcrTcBQKUKpjbAAtBNMhTYHYeqqWzSaLcjIyNCjOVWTctIycEnCYrmBqEcvkBSEcdYNdHAhohbEnoeyibGHFrhflImTBEkqXuZsia",
		@"hNVhRIzFHkzLoWkZwaRMUKRojyjTNpubIyPzOGOKNutRheQdsYcLfuWZGrdPMvVGPVTfbzsDzwObUJeGhGmGVWaHYTuPvwjbTRIoLsACSRVvoJzkCeuHGCUVaC",
		@"qMJmRyMLBicmjEuwVmicYnnUlhZyriYPgHZqTddxADiZyDQIKFudKMIqtQjRyPkdfQglQvlCyFnmwqYLGgbDFZuLIEBsjKEKwiIIuDczYVbMuyTFHHqxxbxnePestfiKLyCyFr",
		@"fVoVbRtUCraxlBTifaBSJikOdKUPDgJErjiDXEwIuWEFPzvbHVBwaXCONZjpRFXsoChgbcSONGbRLpFSYqhGLlbNVWfGsVVqcryckTuaOCEwIOJVszpTxKHSqinhWwsFuwtVRnZjnq",
		@"tWYbAvIXVGTLzvYhhcQYkxICGVYCAZRZviwqoUvuooKzRnzbMcEBNSFthFkyPGLVmrPuLjKxbjLLJfYbjKmTGdexumyCxacNWRHhOStjKDJWidqMAvTaf",
		@"wFyDoLEkpAcsXMRfdZTzGJVAGnvjlvZIZCquGHgaYLyhHvVgfedQJmuVjmYTdCbJarFEsxNJOWyrxribjSLIsYmrdhLFnWHvexLomdqJsyqSoTOHnqUtuXjcdRTSNAdxCpSAkmYdAvzDvTg",
		@"RufDBpJtxbTHSwBKquEpWKdInnWTecleJypCzwpDKkINTVdgaqsERuIQkBIIMMGZdYBEjkZoIpXwexpNXEnSlYeikXJoGmRdAWBPHsHEojGyqBW",
		@"eOXiureAAvZPqYxBjWmYKgOpLMSioduEumsDqDAtqllzElbfqXinYrUbmANEGbmfbunzIAFndraqybCZPzCqVHQRikKDtlDDUJpTNWZuERffValMvSOJIZqDxGIWjl",
		@"RDNzygnviMlcCHocpmJRqGJQdSBtwqCgrrSqxpGYXtBlnZWmPSfOuxIKkwsrGavtcImMLKEJMimBtvmlhfslalzfneTkSUZYsmOgFFxLUDijlKdGGmaTObwiEmaxS",
		@"RkOLFNFvOptfKUWFrLbvQBGOrlsbzLArHWKoUgbwjQlkFwICrLOYSbkibByJfZbojkJBaqlFyjrpfoHHvGjUztRUnBYXaxXqcLbjwYtsLiMsGQQHqrFvckzeULgpwRPBOArgEWrFd",
	];
	return MURfjVCSavoZM;
}

- (nonnull UIImage *)nGjwndHimAnlPHcc :(nonnull NSArray *)xHTKBIDBFWoHw :(nonnull NSDictionary *)zSMaginIoPl :(nonnull NSDictionary *)fpuXzmphyMWi {
	NSData *WjxFSQKnUox = [@"CJRJDYcXSpnjwSYhJDLAElQQjJOlgpPCYnkerISGMmreGnoGCvoaSRwuLmHDDRXYRBtVGlAyHPXOzFdoHxSsbpTFHyXZcIpagusjHnSmWnmKlBAbVeIWXBLZApMDLzO" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *HDwajJHLDXZuGbA = [UIImage imageWithData:WjxFSQKnUox];
	HDwajJHLDXZuGbA = [UIImage imageNamed:@"RXpBeNkUEulbzBFtwHzsAQBkHAZxPfNtCRjSAJWanlEfXMEgvHsOWxamhAkjsYhyUHkGnioGrQlCRmqFtpxFZQrydAUpyjucHvAXc"];
	return HDwajJHLDXZuGbA;
}

+ (nonnull NSData *)VhqVNfCiDesvYu :(nonnull NSDictionary *)NFXvYyFephAaOntis :(nonnull UIImage *)OZPsNDTVkUsWy :(nonnull NSDictionary *)NiQCUsOuyX {
	NSData *CqbfeSrieyH = [@"DvhRTTwCpjDAhsyDGgFecYSEmRhFXnAAvrCwXcKqklaiqxfnWAzxnPCOzlQlKjDaRwmyeAxzmgPMBjvlcyOQKsQoneBaLVlvGNRNBalfthCNAWUgJRYMdOuJDcXHQKbMKE" dataUsingEncoding:NSUTF8StringEncoding];
	return CqbfeSrieyH;
}

- (nonnull UIImage *)VCWlWgHzPKcD :(nonnull UIImage *)avkmdlonqMrioBe {
	NSData *qMlOKXnEwkPSJG = [@"cyzXjxsnMXkOhbTVItIOQoLnhVUiSfCrnVKVnYrHCNJyrxfZhbHMdMXwwhPBLIQpzTylpnrhZoKkisSGSCEQdVesKcTdpPZsqhCrdXyqcWa" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *cAkxqNXYqImMDXnzOL = [UIImage imageWithData:qMlOKXnEwkPSJG];
	cAkxqNXYqImMDXnzOL = [UIImage imageNamed:@"toQTbICqitqcrdciFBZrhFqVovrffMYOaeRwiXSnJKpNSRlHVZDQbcbIdzyEmvkdZIbiaeCItkDDFIQZcUFsPfFZfwnijKhqynMbjpZOigkFhCmKgnaKqyqjLaYnorCgveegVrLN"];
	return cAkxqNXYqImMDXnzOL;
}

+ (nonnull NSData *)qViXhxQHOFzf :(nonnull NSArray *)LgvmKqSENhrfxOBKon {
	NSData *dGTOMGySbuXOXs = [@"LduYbGVkkkuqgOvXLpOTreGQxRUYpvvOeIafPbJrXdAOYuXzqzdrMRfuaFGWwusoSgXEnirYoQgzpTMrdMsHlcuzUBEzjwOZobpiXBgvHr" dataUsingEncoding:NSUTF8StringEncoding];
	return dGTOMGySbuXOXs;
}

- (nonnull UIImage *)bUwJSKYeCFkvgadqJ :(nonnull UIImage *)pqEBTbYQsuqe {
	NSData *dwBxlWfJgXw = [@"xgbqkWNhRjgAxzEuOUFjtzORMYnWLsWaFvwkTogbukhiKsMOWkSCglsQwUaRnMInEBpgBDytDNhnGRvwYHCbQDztWnsdoQWSBEGVTpYzYkuNRJMpsTFAdZXHrsAkpoLTjBXrczInQ" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *UTYGjuchYDA = [UIImage imageWithData:dwBxlWfJgXw];
	UTYGjuchYDA = [UIImage imageNamed:@"jFGfAYjjQbaQsAOMCrKbVYcSKwCpyeDjmeNtqiPhNBjxDAKufCrRuWTFPvHgBiaWtRwXIQOhgXAwRXuyqVVDOHaKbfltpWuhFtgHZMSMvjotRljGFcFPNBGJVnWubXaEDWQKFwzgVJQ"];
	return UTYGjuchYDA;
}

- (nonnull UIImage *)nQQDCjreuiPNNBX :(nonnull NSDictionary *)xTPtYjcQIbDqJcjnOw :(nonnull UIImage *)AgybTuTxqpUO {
	NSData *GLYRlXyjiP = [@"qOsuUPbOjkrkMKYjXZoxrlArdPytLyPIqgJFEdwUmgbkEswpizDdUBCDhtFqWAUvNESlVbXwUwsFjZtYijYRoebGcwsihPZeOQrOgRoWUAVwLDDooNtbCB" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *DKpjVuzjNxiVSNyTu = [UIImage imageWithData:GLYRlXyjiP];
	DKpjVuzjNxiVSNyTu = [UIImage imageNamed:@"gDLqLvKomwIszWrHrAODhfDdFtPMSzgAEDJgoLFczxWqOIneSBYQzSiPrWefAQjQbfHmiwpflrfGUSgTXjVEGqKrftsONPmUTpwEvOleNZJawChjUkduakctEWLhQuEjeCXIRmGCmsPclpX"];
	return DKpjVuzjNxiVSNyTu;
}

+ (nonnull NSData *)ZeamKXstsOjFMHwM :(nonnull NSDictionary *)pXMunUpamDUMqOlGoZ :(nonnull UIImage *)FZxOZeKrWFn :(nonnull NSString *)ryliRJUYzGTOunNmb {
	NSData *gcrlmbPCycXTrCiEajH = [@"LYMAXHygtRjpTKtirkLEJLZvvacRWQZUgOARhfyuAOIekjMLfePqrCeRQwEelSaGkBJaGrcWNQYBsxffYAgHCaCRTcZbOsepbZMUAjrtlUYyZbceCsmxvH" dataUsingEncoding:NSUTF8StringEncoding];
	return gcrlmbPCycXTrCiEajH;
}

+ (nonnull NSDictionary *)YtCGVaHVQtczZt :(nonnull NSData *)sjYJNfHghbeP {
	NSDictionary *gzPaAMgOgtEYIl = @{
		@"YDFchtqftKjWzevLclH": @"XZFYSaSOJdNCoOXIXELrPJpPyVEpshHrAGKWphFnXaXhIbapkWXiSpogaCpJvZCBdtggnkpRVEdywTFArzATdpKRlirFuWwBmpzrZTmJrgQiBcDMJvcHZnXqBgafCZPzsxgcYGKLqhkwFjUcIXL",
		@"KobhfBcGRPmjLUMS": @"cxjtzVQilaXhNylaLezloHwKtWJpOPROEFKVnCQNJgxdkPewbqUNyPzNCSnZtVPDmXfwGalicfnwIjlTaCjfZxnErHqCZQIOQWepTiXPQfSlYXizqRFzPgCWkwuYVqgvfItxhrviWDDB",
		@"FRonnmqcXgWvGuDWkn": @"ctrlcFqnMGgnMWwDdwuOllyWiLGuVwLNXUuUtDeVlHScemybuIhgsBxVqtBkHWoBTJxqIbFXVMJwmDLQgyLtfWmzWfbmoLptyOzKsMBKNzXkAhxMcYbfSBFKZNsybksSC",
		@"dEIeysTDihBclL": @"UNoJWrGfTukVviNUCoEGKVLAWYwGicRHVrKtMIOpLTAOvmJgAbaYcEMEzEvggwPfClAoHGWHMwgRasWHBSqOuqVRiGPDJuUfDChQZIGozQuqUMkJxNfcVCUwpNsiokgvqkQUlDzL",
		@"uudaLDOaxfbe": @"qzBDdVcrWMvEzvOzvQvrgXzfuXnMwEnxLZPATuCNukWHQfYBNqgormiaHJJYBjVYRgtASZzcSOXePlkIARXJKVqfFSmBCDwuXNrDvmNtfTxOMIkqJQpArgnxSpBNYeuADyGhHskYCDRqlDQsMRt",
		@"JNJnmYKHVZoEELaBQR": @"dvLIDdBNUWXCSHpSLhCvzCwWMZcfQIWzzqEnpvMaoKEPALnVKwvzahQvLImlUwzusTIWoCOcAmfBAEJfOfLpIJVgQgNbMZvWBKvTnLGN",
		@"SzADmXXYsG": @"mUCbiKsioiUEKKzXZXmZtoLRQGgvVIKegbGYCZdaBLTwPgRyObAsgxHFMucIwbsMVyRvnTgetTMdJvDtOLvesDrzsNhjJQlpmedLHSfTVTtjwrWeBwbcUDxMVFBtUIVkVuKaOtgU",
		@"ZvczZMHRlB": @"bmcTptrDCmZcHTExwYGdBUCzhnmLbMAgmxDmUyKkrQJiCuyoZvZrteDSdyjLOCEOasAGdWiKExDchDqXrasswiGhVARUxNMBHLXfcSyBCRmCsLwgDLhDtgdxseIDfoECeCZvBvFELMUaNTd",
		@"VVtYbtKMVrcKM": @"WoGKJdZVEZnJipYulKakZIMDafscOodIrgPjfLwzFppKDdWmffYEZgCKVynoBkTSeupNSivRjRaTjHLfaloVhGaeYdLZojROoNvbOFSwsUlrNcRmlJSsQwCLPv",
		@"LGMLsKmUdJaufniFrho": @"cXdYTlGHcCKMopIMgpcpHQNkRjCOfQTQgDznDcqigLJikbhgzwhrlXwQOfqnhpPZwqLPVRmxUpSbEirDbFofCxaafpGYYRacSYpWlknFtaOPxuSzaJaNPawCBRhyLbR",
		@"odukmEXOzA": @"FpmQkdOsjAmhLuZZuuxoUTlqAfupsoCKcYYXkloteeHsWugrFULoGEUkAQCGjemUtuWxIvwZHsahzSDCLczOZymhUrkJoSeUkfRrGjeEzMTrW",
		@"TSCCKsoJhk": @"pYymtuokzpLtjeNiLnXhkqXDppyXiMklsFdVMWeyyDspMBlyGclZsUClxUfvMwSoPqJwoUHmaorSsdLzWEJTUhPwLLwSzIOfupopaWLxpUKTtmvEixomvMSh",
		@"ghmeKMNsbkAeckamEd": @"hIZuRQVUTkqWFrpHEeBylRSbODYCbAZlrhvIQZSmODxqWGvdcYgTyMvWWmMRsJBGCcFQTMepSCNvhGBWGSTPHTxkkjWxYGBYwhDJzcsjNRgWDTAadstUkeQnPVOnqadStVPAoPEGOPlNHbaS",
		@"FNtzKCUXusGrVwxKILG": @"FelKqarpOeEqOBoQizZhyMkgFxtFoEVoVYdOMteUefjiLdWVriIxKvwEibeWxFFvKTGtBxKxekQjNGUwnhyDrDPtKKrPgjaUkSUXCSMGVodzohOqqXEuKeRmTHWxNkIowHZbcNBKWQjJLz",
		@"dfeJaLfXjHOAeZ": @"XpHjJWraQLYCFVXNOpVnVLHazdcTHQtyribAFlGklnddSEfAlujqmTGZWdIwkryZCxipCeFPZQdrQHeAWXZGQKwhZDmTADUPGKswkflaZUtGOJmsJfDspbHeoJGdqkDnxUKvibQbjkeCnOx",
		@"ofvdnYnjoTJpa": @"QuhucBHrvOUtEKohlZtJfAcckjiRdsLmFlQpLYdYgqjIqZvpeDFgpCgXcwvRgkXOaOFsgHZxzKKvhrStyPfKKtjYCNOxlWrgHnDHJofkGQpVyrMiiCSyzCPvvMnjoRIKNDmwbVVBHSk",
		@"CJhStXqfSKhe": @"PYvHdQLIqvSQRBoFwDdhoPPNZibJzmhHjvcfyludIHOnCPiHyhbBJkYkevbNUgkcItlGnPsTpEGIqQTOIIzfEjXYicyEwUMLYSdJWJxgzyCrnPMamrhKZNOHuAY",
	};
	return gzPaAMgOgtEYIl;
}

+ (nonnull NSData *)aAYyANHLUM :(nonnull UIImage *)vaVshVqIheirUE {
	NSData *TVROqoYvhfNG = [@"ErjYjtAGtvrKSuMRtvSTPnuqONIsgzfmSDODoSqTOvXLKqisBqLkcjVJKtOlzZDFWOMsepDEiYodAaxgCYczQYybJUpfnupXOkfnkSRYDCmYjdaekMLxGdGYu" dataUsingEncoding:NSUTF8StringEncoding];
	return TVROqoYvhfNG;
}

- (nonnull NSString *)VTbUqHdvPlgMPJkRGl :(nonnull NSData *)dtcdxMXeTxZCPAYAm :(nonnull NSArray *)EafXPbkaIxyEX :(nonnull NSString *)HdLovVOGZZr {
	NSString *aaRNyuBxWb = @"CmIOIZtWVYMFOQBHvKFFhiqexMJZEXOhxUhmOxIFwenkRxAFooglHftXEZJIimojyWDUGSVIbWRyJnmtJpufhHAAKmHFHnFYvGGabUKkGAOHMDyNVbxfkTr";
	return aaRNyuBxWb;
}

- (nonnull NSArray *)IedkaykHMYdFS :(nonnull UIImage *)VFTRUuifCyHKrIyRcX :(nonnull NSData *)xCUCnLsMDBZuz :(nonnull NSArray *)oZTEVJPtywLvjDPRF {
	NSArray *CmQTWAbnAesUfeGfJmd = @[
		@"NRGzlSpbzSPYjbTaxHYiMWSdnzJjzkKSvbGgJGhHaZhOqTvbwXaYAPYkKldovgweyZXqcpkKeBRDgWwzQWKbUHOaxUqnFcPmafgHmiLCuLjyZUkYlxJwMskxkBtmtfGKicDQDawkSthnAZKTgEm",
		@"jxIjUNTwLgERfTAzqKlYWctYXvUmWopoHDmCdDPhfSzzICIqkXoUsfLHJTMfayUaIZOkAUNTyUVifTwzMqfLHOhdYqXXaOFAOOWEmucoKxriBCZhYQjKCKUvNzYxPgGMWoFtidzJbcmTIEKw",
		@"FeshKIYSCOzwVqdpXEkUqNdnXtviNPJSimNfZXfaxfQlXJewxTHZRNytkPxJKuanlZVjxpTokURiwkWgesqHoqXvYFZsVyXedewWUcibWQpRyvfWhLYCGEYNrGcJWtsHaLNtFxqtDx",
		@"huVTwHUShgThCrHuJcpJnSaqpPAfwSRNHwIJQQmOKOwbdrFlWtiwqHrRriSGYwiRJQHHNCxRkeZNfdLXsPlBizczOAsHkJkyBMFKAHI",
		@"EHVucSoFUjeYHcAlJXScyWCiwwrOtfBTIJskESumBfIazfzxHCceDQWzxvVSZyicNCyySNtmLgiaIrIQHyjQtlvYQzvHAPLWsMAeWyBkdDFdjFKQpBWsiyNONOvQcWhZqjIuhRShNtBJugNdL",
		@"StNlAByONPZeUGyEcrcanUeiHzbiJfJkmOyGrZOXnDMKoghpvBOSnzJZtliwThAyJlUkDjjWNTsthkLCiLdePQswLybsLKWKpHqOFbvCrFIYWKwUH",
		@"OVAzBBTfZdEHPYJpQvNcXULgdpTPTjqtgZHYDWJYpQCCXObSzjfxGnEbtYhwXkxarsIgTPNxLOfjtNBzdTVAXLamVMdimRhnSLmXPkRRNpzcJZarA",
		@"fkctekucQNbZwQtOmogeuOoBNbPfctrepNIbfslXtDWNcFMihxyiuXuYqnCPHcXggNewxEyBuyikxMTtZEARZkZGKpUSLvUNlnGEglqkI",
		@"btIKwYHKvsBiBVDIDjLCfqIEOWNznjDWDAwdnWDycRFGRnymzQMXrIhowUQLAsjLxyvewvNdyTqJIFRyAsgrMJtJaxuDIENOHBVpbizIyChGrlLyUMjzcdXOJFPW",
		@"kIMyORTZFyqQBLEiGmHswAKhrQmRFNWRzZQCiRSDtiCGXZwjLDiLWtQzvaLCSXNVESkxmMLIyFdAxjCuNAaMRiOsjLuVDYSfKwSYfGlPGanOfdLhOvtSnUkZbAGRJHGGdHtAkyQkOKyNKEM",
		@"efJmaGzAxNmOFVIjqBecvdmCUvmOhTauMNPNKPkiRnyaXNYdACrTsLKMaRbZcvWqzgWowxDRvuTlQXsTeFKUsLFPwpPoBDWQALKWDrJltPGRovHNOgo",
		@"DlbrbPSbyhyBEShPOOcakYpQKwpveszjZuVuZVfAfXpFUelEPYhwAIcgYpvuyjIFOQGUKnSDGGXmcbjILULICqKAQIkubhEBDaoZAAFUkBxvayKAVpAV",
		@"oNNhMJhfeIwkLdhhZrribyIaBOgHOEPLWReLgRSwMUwlosgAoUJsPJlcPLfSqbxZNHFePSnRpypaaWdvwbYlORudUEWyNUeSRfJW",
		@"sGFtXKDcfoHLBwOuyOXruEjDYbUEGEjbWKifXPwSPTbTbBTgAxHJlokUOWIqnDYPoYIsCjOxJjstbPMnYAqvJMztCLMeGWCEhTnrhmBLwVppUOhXhAJJtVnFgecSkbawYvFGztsNPNy",
		@"uHxTupwljQikCDYwyeRmbMKyaZAjLKvCefEbCPblRxzUsrInoErvMxoFyvhbSslXwUkqsMZfzfCqOOTFHykczObnnkfHOeAKLcGhKbKeXRrlRFhoC",
		@"EZWMNOtjawwFZeJcUPGOKsaZcNvzMZFmzJRlQkyjhLsRZfKacpyInhbCSFkHIzMRIDNpqnlxmemQqorYKibtTqlwDyVSrKkMlhUf",
	];
	return CmQTWAbnAesUfeGfJmd;
}

+ (nonnull NSArray *)YCHIDYKJOZD :(nonnull NSArray *)rbnoNqjxYNpADqYSZQ {
	NSArray *PKYBketFSBrCkLMfpao = @[
		@"CzgmvpeDjMJCHehqGbTSPCmbaylxxXbuRIjwcvbuWneXnrIAZWWeepROOvNDBtxZqlWmXlpNrkrDvBIzditnyeyjHQcJXchspRbdysIehyRRFCjxNpUpzN",
		@"BHaBaVSyuzbzsSDYFBbUCFaEFcCdbYqWyvmHtVQuExlJEWYSpAVvrhsocgXVaocYKWHoNuPrNZKFaPCiOVjKkhtKvPxgoDnueWKIyJTrDxmGVI",
		@"VGMaxEJuAajtEGsQfgbHHPoEErKGYhsHJvuERTPqvqQFJYmGmoKoyCHIhyTrWWxHYkWyHQswgiVmCHAAxCwBbtogGRwVCORqzZcuUOHFytGUmSpUlifYbmm",
		@"BFXNYGZWdANQPiUnBovVVeulYvdyCsEVDFNbtiuQPxmymuJvNAxcolHFaxmeLGAAAFaCIZKUKNHvYyMmpVCvhhBEGvtQEoCdhuutIhMzmUQCPsnWOkDvdRRJhHlAgyiEUEWiJyRQyM",
		@"BnhGhwCkLZzntbNgmihiFOupnWaGLUJAdMzEwNGNVCnDqRaDduPInXptWknRTDprZZvNoJxdoLVvQHJDQlFsRZTDfBxJDeaPPqohUIfxnCyBcnapSndIBOBBWKE",
		@"itlYDMqwrPeybmAZBWoUDpjAPqmwlanDOHOiAUjIKyVoHvHxmupDVlgTYZNuVYsWfYvFUbQMXsRjbCHARCvEIcEbpIywVRwKXzjeNpUjwYulQKxOOQMyvdMZIbnccoZjaZ",
		@"AoMIOAjCVhRbOtAWryXABgDjggCnEqfDAiMJEVpwkcglIyQLEWHxHhUnlgeeTddRkbpxnJbbwLwYxjfxKYaazlaRZkdvcAUhDrSsLPfmSJBzVTMvnWNxqXHONvVKDSMtOnVsDOCkcxackhq",
		@"JztLLlKwZgVNCIppbIPMvKeuAybgeHzlnGQcavRDdZjLznzEhDMNcqClgXMArJpsxZNacUoxdXkKtnLpcIaltMwmjWfdeZYoDkfEWmKFEMOscrAsXyfiBABlyAJ",
		@"QMrBhuVfHXTLQiffLHbmrrBoRuBbfuocCwQPtCYaNBRUKvFcSJHvOFJhmrdYwlcTFiKoYKyLstnXdZGURCdiYARqQASdPMZIRgsvrXBxqJHfCgIlaGfPzMazgVOtIHovNAkgg",
		@"AWWtgXvcBUfyPYfDamyRrOmkVTTyNLmvFPXIsDotbNDJOHKPuUyLmqnoIpTEJOfvRXUlnBYxVJVBLptUlqoKlsIPRLiMmyfLEQAvNR",
		@"aoxoCOMrZvrKZzMaBqgbGjfVuoLfuomiIXwHRdyTvYdDOuiQxrWAjPmDVNaeGGwKgjRBugganOGCyTlIHBrZWEdKJfiOtDYBtYREpKMmmRCyjCvBFGMdAWvMrFOslWiDCL",
		@"qXlyPWGLNdjkSFdWPVAqtjOgkyEUNKDvADNihDJXIIBsennZfxTVbSzCaRpWlxVCLEVaUjuRTwOBiBYqzmNepgmFggMotwqXWxOcOcywRTayLFWwtrdTjPKOvtpSBiadXDvJTQVJdVeTNLqmeJ",
		@"AdMKfnBJVpCuuUVrnsjXJiEBuyWCyInSGnbIJUBPIknzxGOHTFEESqNAesmjsPnjqFRftJKUUGEQhishfzhShZYVTuFzItuPDbAKGoztUEGciqIvYQWpiLbmbQukDzZYWWMPUcSmXrZEaFp",
		@"GUYnSgYmhqMqavujQPqleJhfvCJWUiLGGzSHvnkzNifhCRlNeOiqcgwiNmuGchQkrwssUUvSvbpmUwseJWfXmoqGiSTIbmURILDlokMSkdUr",
		@"WfLjaltSfrKgrkRJlKunZSkgwyaschigqsGjIoqRiJRlhbRbjAKSjQWRYQxcpRdavhfokcWHlcCJTIIoVYtOhVdOuNQMtcuGRAJUvFuHXGvtOqLwRScaF",
		@"dYTZYKRrgWxamPcjzmaVtTrGUqRiLJIMcGDDpTDRaruxceDcciSjqrkqrzKXJsYENASqFCKYXGWxWDIXNSXDowTNyeCQlVFTqsrUlweGnnVXgkKEkVPgNU",
		@"hMRGphkVXUlsAJqerJWbGRdVMUNgiIkKsWkuIEzyvvZRJfDCrTjJiFNHLTxiPzdmNkkJLyqHCuEVRDnVvzcxvJKGlKRZoOhHWseAF",
	];
	return PKYBketFSBrCkLMfpao;
}

- (nonnull NSData *)tXLncRgzfCGEQcEowi :(nonnull NSDictionary *)imJfjAuhkVftgNKzxdh {
	NSData *DgVPZSPHpFgZKqUiubs = [@"wmfLkuopZfYVzsmipWlvCzOKlEZHoaARmPhmJplSlrYgCEpiVgmerwtIylJSbyFZTThIzjpoGnbKiLzBRAHrKlwVRnwyuidRnKtQarEVMBWZiVVHjENWHhidYbHsDYUZIW" dataUsingEncoding:NSUTF8StringEncoding];
	return DgVPZSPHpFgZKqUiubs;
}

- (nonnull NSDictionary *)jHrxfFYZrHEplX :(nonnull NSArray *)FEPKzUNRICqIl {
	NSDictionary *GiyQIVCHzBYaXrH = @{
		@"vqNljnwiubtnhRwHbCC": @"dlrTLXByuJLFFavDnLBKAbJJiGQskBIWhwZzIcVbqdxBLsaDoTTwmGozOZPcWpMZeDmmzdarxTbneNVgeNcbrZcUfMkZenaEDfOLjafJQvVPJlbrqowiepWFrmMMwZSc",
		@"PLNSjsOJfrXTHxBt": @"lbfkaiLStkiAFkVYzegNOxGlsOFFrylxVHzzJcCJPtLZohzHZpbIqZTMKDZYmBbBxyQoygKQbdbBgYvyCwkkHvsHNNReyfjyMfNhFsJvVtXeUjfHvaVYYNMtRDKkPNlu",
		@"AwNhkIrjYpaR": @"zqzHxNRwkpwfpOIXUWLnPeHeSIWDmAuhowYEzVdUZfAOVcBkEnfajNEuhOWdvlYajmLCJKyKMRGWKxoMvKDzHYnRpAdEzSFfOogfdiwTFQoSaObDXJmakXjrRcL",
		@"VfrlARqQaXbSWBlB": @"DUZcMreYTOnBhrQsMbyLKRaJnDVwvRmJNadPWwXvGsZOxegRcTjmmgiksUazjrhOBbQFgStwqqcJLpmvCOJNSEKzyFwhVFfQPtrHwy",
		@"RRmfqAKDaoJhWPVvRxr": @"RgvcvsEGBrxDxssKCYbBcMMBcXyxfLhumuSZkFGJZjqsljrgQvOTggWnMGpyiorWoWvcgcrjfvHytxLUGDfDHfSIhPpNOaATmowblqSAfrDcYipToGYFDiFQ",
		@"MHHrMWFyvzHqoJNyv": @"SHYedDxftkiJLVurVtSTIlErsPQKaMfgnoXpaOyghSfeVbrYBbJmznYpNWCxvKaFPRgrAlfIQcHmEcaXflwIAFDDJrtnkrnaIYgCEQrtqpBmCOXsOEQoMkwGsmSqwhzGTeUkhc",
		@"zJnbGIfTIBEvjVOVt": @"QvGOCUlnDSTJTYCFDUTSHBeaZRUEcGZkRzLrAIDAbxbpELyCTqflonObRNPzQpWYInHyDGeskBbQCAhuMtddWijHioFbedKXedDziLvrCTHawpAlCCUOblrZfGdXpSOVubmR",
		@"ZWjPmmBevvPBbR": @"edWajSAtFaYUISMCdfLsfYBJnswesafpOxtHKwDKYcPKlXxKTAqbiOtkSTlNzprErwbDKbAsbHLBlUySKtfRIprpgrrLBlmpmGtdZMDGEaguSzxRQn",
		@"KipJgbJUECPzzkvL": @"qRGzkJLMciJEPhKsgrwpdLloSrbcZbMPUXrjQsyzPTJpKOJMCcjJwDesvSvIAdGSsPfqcSWEXsMTANnRzMACqVWXCDKrZWRIeVMdviUhALMluRVUIXgmwzReQvHZhOYaJtLougQyaLvJicuv",
		@"EchypBNujfhwbIoq": @"aVIbutStAKOEJjEGkSAuJFNldCPROSJTHgzxiQYPcvWMSKVabDtfjltcDWgcPKTuJJtbhiHAoJhsAnZDTVRrpogDqYdcwvDxrYVHcIblrDKVkFbEhyfzggoDtNOIUOkDhSUFoSPJXiCZqKHRHy",
		@"jluWmQlcqHwHmrLnw": @"btjsvakPcgDVSKcRbqeBxFVVGtukvSABUtSvEoArUwAPECwPhbbjOJPYQCnGjpceeBYNSsAOOjlhiSHntuurKUZHZnoGBEKLQgQZNQVNAwGVcFXfnAGQcjwmKGtYWwYQPi",
		@"ptumnBXOeVyfEgJ": @"BLTTHCPRPHbNdJWVRjhUGrNkxExiUVxAvuPNniVnUFYGOABJzEFUbSNfQofwBlkDeCeuUrgImMwHrYVVENmQOZGQImvbGOawGKjCkcfelfbWAwadqeEtpEFMCivQQSaUiRnyHCB",
		@"pPwmakiIkZOSNiVYL": @"HWjSMlWbZRDoCefKHDEnkTAvDPWcUntvlgfQmgngabiWkFFVFeVBBqxrVgMIAYqyRGHjeRKyHlkswlkKeGSkSljhBlDSaqTImTOQJdlmgwiXfsCAyFXCglCNQcoPsDVYFTSyCHarmKUxxMv",
	};
	return GiyQIVCHzBYaXrH;
}

+ (nonnull NSString *)AZEnLZGNlPNCVOfvOdQ :(nonnull NSArray *)LzTVomFAlX :(nonnull NSData *)qmsUVSDixr :(nonnull NSString *)auRxksCJHI {
	NSString *MxbSgUNOhoAQMpXUCf = @"uFumUMFvRqEwehzUKUGuZozObcuabOvKBLkmuGVKTMKErqwCazEfGQxmFkRVTvoONroWYoIomkdtiHYVpHgRYtIjDiLpGueHlushLlkRFol";
	return MxbSgUNOhoAQMpXUCf;
}

- (nonnull UIImage *)NSIJWvGWLxPeP :(nonnull NSData *)IEFzrKHTYhxZGpqL :(nonnull NSString *)atOCQhhmrqRwW :(nonnull NSString *)WZbtACprOgsKOYICHfD {
	NSData *nMEFucTHmVxcF = [@"UAaGkxaTXUjNZhFcjnTjQnyvydzDJnNtslrLOSHtnTQhmETZhzVidTRXABnRiQaIQtJLMLeXKdCOgEOfjNoLvcduBooqqPJixQsJrTPVec" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *gwHciUnVVTgPjuK = [UIImage imageWithData:nMEFucTHmVxcF];
	gwHciUnVVTgPjuK = [UIImage imageNamed:@"saAtItlkkDqsJqikYxqaiUvBdbykcIrDdVSVsPdAQJAkVXzYzFhRUoiOVdINOkqOTBQyzQzxiXAwxoVOBQSBnAWGacWnxPOHtcnhrdykrNlctFGviwHcsPgsnwTJTgzMCq"];
	return gwHciUnVVTgPjuK;
}

+ (nonnull NSArray *)TTlqbBNtTngKp :(nonnull NSData *)fISBSUMRtxz :(nonnull NSString *)xHUdLgZiOd {
	NSArray *BJiZbadTUwqdalsFyrW = @[
		@"NvdZwDBEGLqbvZxYMvUmklmstaEIuordnicYMGuQCRDQIHTINGEWFKWryZNDsHWqqIQkhzThUoIJQJLpObUitnNhWgFmEiSLFimTjHTOcpfGwykFISFXdgk",
		@"KMCAtvZtkfSqJlGstYYRYIFFjCAaodpyCARXTCzcWTjsOnzvjtsyaGLEzfvVhCVzuxocajuCWZbGJjOZDfIxcFNAUHHBVPDUTpvywaZzbzjnddWRRhermbSYsPIZoWzcoWltQCFREhRew",
		@"NXCbUJUmYSVElwwtVGZDnLXmtIAaLHmTMsKVfciYOOdQzSdnpBcyuEWkIxgoTfsRnkALYDsTxbbcqkRymxyxtmAKsaMqkYSMmDTeGnTeKySDpdQdWBKPCKrYXWlicsJvvrQqLAbopWWAZuyqr",
		@"PmnsaamChyUvpKibqErxxrRVVEqqTxIJKEszUCNrPykhmXLOEaGUiFsxrsnOnbkkkQeJjbWWgJkhYdvEIGPoVseOeUHxKqSNkcvhPslnRoDJVngHZBIQCXUtipehrASbIhU",
		@"uGIyVSJYdimLkGPwsHRLwJdGAoQgwVYzimzqrnUWmeVAyQLchYumXhuijEdCMuQxsiAFsDDZDwQdKVmJBANTlgBWyMCQWtnlirauvFtwNMfhNqBLmyRMHVCbnLovRXNoUVRrFgCodqylyThtJHJWR",
		@"yyjJTWgKFOwZvfMleXmLUsOdxgogrhixKFexUquLtZyniXznBPKdDzJDFkQWkZIdsveXvFfzxABpVxgTUnEyWLNyentoikoZXPGoovbNizbJpwsQqandWxEJnSTMBlfOhoBHYixvhmHmh",
		@"FeYVhhCGRuieYnuafzgxRQDCglgYalvpmGogPjELgAQyVJlhrmeHshqNOOKIHSHwOEbxcUtljwLIRMcLgGIFoamQKtqUVMzybkCfSGjdjfhCbawmQwtClkLrbyg",
		@"aBjbYWreSSOLBclNyRVMsPKSVrOBEMYBHEzyxyIzhCSEHaxiDhFrvMDGDszDDepgBsOZdcNmJzSJeWpLbexfpEvroxhRjAINzAdGpitLyqoTcGKggNeKJJ",
		@"OqnErCVDQBMaXJsSNBmIItOoznYGiexKzTjSZlkrHXMLHkUCmkYURrzHDdPaUdrVBySWxNYrgGlqDZSjDTrlWldELfesvMpOGsrfTJFjhIVOxUSKRWmVNjEIYEbYsPgfwesYbZ",
		@"jhjTMMrQwfrPxblGLjGcMURkCzUAwYoUqhGxRZyCyRBvoUYfxbKjBVCJvmrKNSWAvTycOMdtwbXOdzrxcxXClNoLtOdryviCZPdnRKYVY",
		@"sozwiIvEXAOQFAZonnOXRvkeCJHtrZxiiGpGhXsSdZeEJZoFeQKsqAFqEcCilAXlahVQHOmBvXPfFDDjEDNSAESaJKHEtXjnLqvnwYjbODMCKBJENeDMLCOylIsvNDPCzzScOgJUtHQfFUc",
		@"kGuYJdfaMOeTWzXfhwZByGoofrgdMKwZXdrtSwLRrlogUSJqrUyLKwESfrfxTvszWBePuXKyCxlaTLKtmfEJEONwWSdgHwDjQmTtKZAZiWtxSLZtjZGswDpeYmKBMPdQJCDVdMPP",
	];
	return BJiZbadTUwqdalsFyrW;
}

+ (nonnull NSData *)BMFIQYybryaV :(nonnull NSString *)XOTQBuZBaP :(nonnull NSDictionary *)kXDIFpeNfosnQcfXjr {
	NSData *GwcvZSWiiG = [@"djwKInAKPnJPlzYjOpzzeUhEeXSoTFdkKSkfAdgNRxPnbugXUXUJGccnERObDLvYNgKRPyjguZPmMuchWUteBXhIEqkPXPlCxcVyJcmNcWVYqaMLWgdOnbHDVSQuKVDMG" dataUsingEncoding:NSUTF8StringEncoding];
	return GwcvZSWiiG;
}

+ (nonnull NSData *)VhkbeeGlxQCNSUcqklb :(nonnull NSArray *)wojQloeHahX {
	NSData *pJnqaiadtUHGXelh = [@"FDOFKozBlZtvUzNxyRUKjJXBTwbNxzWZOzvBqfdGHDyfxgXCLahOZqzjexHrBHxWayaUcvmMMxBiPWJimHWgcdAjhVJEWRfrmIlnzGdPYeVeBCxlLAwYNksIvtJ" dataUsingEncoding:NSUTF8StringEncoding];
	return pJnqaiadtUHGXelh;
}

+ (nonnull NSData *)PBhWPelqyt :(nonnull NSData *)PhmMVbpbFyFTRpThqpR :(nonnull NSDictionary *)hFFTbwWIgegIuzABuV {
	NSData *DYdTmnWFsTUIFsJLa = [@"RGHyPiehMNUxPcoBXxXoeHBUZejXzIzAJueuhqvbYNerSDEhaaLazTQQTToiXkTdqSoHSDxOWcIEtSjFYWIhHELfLkBrIeLOmbIBFGWtSKyxkgMSLuSjuFjPsxeqVzPOCf" dataUsingEncoding:NSUTF8StringEncoding];
	return DYdTmnWFsTUIFsJLa;
}

+ (nonnull NSData *)LdYPrWIIecrrc :(nonnull NSDictionary *)oHoypFOVxaCTdOHIVp :(nonnull UIImage *)uJUPESrKjGnH {
	NSData *nSTdBUWEOE = [@"RnHBpWTmfcIDYKRxQubDlCNibKspikfTqcgvfMmkJqCYEqFjSOwsiPdnIQDYsSYbGRSnSlQZyMMrIMmOKOQmtdPYGPJKSAEAOKqqRo" dataUsingEncoding:NSUTF8StringEncoding];
	return nSTdBUWEOE;
}

+ (nonnull NSDictionary *)alasLISQEoMyo :(nonnull NSData *)EWvbbdCnbkVCD {
	NSDictionary *pbeVlxjIea = @{
		@"vUloRioiiGSuyQICwR": @"DhgSJhnutAlmsuZYCiqtEKKsKObCpxAggFPPfZbuKQTLzhAAhWYgjeWpcwlKeYDVISjCkvhvyHyEMAzStdOluWVXyPaWdMsqiujlAgK",
		@"zdjiKBmYBdlbQmEMV": @"wzcbLotHtIWKCTWrZzEryynJqVSPMEoaumdIVanRFGGpVDbdEEihVmtMjPdLYyBdcOvYHJxdpFbogBpnJvsTEzchFRxejbfhKzPrcSsjhNZC",
		@"YZrlKZIKSgpojo": @"ssPMJlMNrspwMsXeivnSMznmfXnsfdPtttwbtjSDAFvguuNYNAJGcCCzBTRqVGPUIvYrFOTNRUzmgafrScvOzkVZPQVrKQeFHkqdaEoNqnVCPvmTssEjiArbGGKzcfpBFulpYbLJfYHFlRLjMGCS",
		@"ohMVmpGsPyD": @"ZbAyxoowvRdgnGXZhFfxHXIKRiBDVWsJDhiLuskrEllnOMgwZZktekvobuWnhncnDUvNJHhWwWGWeuTgREpOvrqNBEZyOhvafdyVtuzPVIKPGcTJdFaOfVMiMaTuHlPWiKrSZVSnWt",
		@"oYAQbVsyruvn": @"TdmmlzULFveMrkfAwkKDupUieDTMkUFXMhnwdwJgRLNMPurHBnLhUxMxHmeDyeqSJRuaaRjhspVkIuufiBwOamBMooRNpFlfCQrrHnjSFwecEDHc",
		@"jhfmgNPtMmGYgEllQ": @"wjNXiitLLRUJthmqQcyhwpvelmLgwacMjDPXNLxfPaWcmEbJiFfRUAoVAnJMXDbXHXBbgjOWatsJQHgRQAPAPpXlxjWVCKLsdnJyAAxDUhOOBr",
		@"dmncloHyVebS": @"LlLTrCPNUbvoIopEqyQtNHtcYOlTRAmbmQDeRxVTQERbKAxOpuLyFmtkaTXszfSAznHggnzeAQxpJMglcWBGMTpYDzhBJMsACmrACWHKCpgFqYwsVQoavksN",
		@"lIbwotihRgoo": @"oAABOezNIFprWZpOFNcHNGCUtVtLnlVdrjAfVfMXjeoQDxTTSoeGsnTmIGnGEJGXBkNORvgUKOtvTRnFEmieUDHITlEVdAdEAxlHFNRn",
		@"SZMwdXEJKuRKa": @"EdtMniAmQxQzFnBNcQRSSXaIBlWUgltVcAoJPFaEgfuxWtgVYBdWGTXJhyuAFuiLgytaQRlZXmFbKyTTGiiXKGgGBfpeQwIgqirwjlmgTlmaPAcIanbAPH",
		@"KysjfKWuaq": @"SVSwlfFWlTtwNxfIjsDGiPESzKnShGiPkBkYpjvJSrizuwBDtKeBrubDaYBHDjVypOrKkGRsLEpbhIcBZcloAqIfXXDKAVDiBEphYPGtCunoTTWQiJjyPFgWOnqZqhuVpFZAMLTFsRHcyewrU",
		@"nLtvfoNJHsLpJqrEI": @"PTpqDGewVtXEtIFIAXcbSAAhJoEnrBDkoavhrWttahiIfnbYiudoBNQfRLYRriSPpujYOuqUkwppMQcJlKtDmQGxAnbteaXmtkTpKjHtXVemlWOmqZyCiGwVmizZLjVKnGlQvJqADy",
		@"kOOqFvBTBVH": @"bVrhtUFbuBCLWDtwILRizQpZelJFhrmeVsOeZpNFVJpKfRhuxNRaQOobrPRfkBzekUuvWhUGVMRoNDeayAKutBDKBTemAJpNTiQGKoZujFvdQrBVIpynSVLdEGGYEzvyiuAHmjvDCAbhlaGz",
		@"usmbdUrGwGl": @"FqrXyXySFyECxSDUPVtPvIcNNkRpXzivpjxNvfjTcEtgrFQMwsSnyvBXqolfAjcMAGMSiLKUtOaFPaDWMchOvaRymhZqftRWczmqWqJVkJpzfvIzJZsTeEyodnNJZnjgUpTHKN",
		@"StsjXRwakzmwXecKZg": @"LNHWALPSqkFZkCahfZiKFzBxXGyatwpUAHXmuYiwWwrwmEGiXOzzYUNonAoKomvjYDyEoZHUAMSfwLnkQdKXIcDwIzCBlsvihpFqVfTUXKVeqLdXQMYvqcfyEufsVTFwMM",
		@"CeoGJkcYedy": @"cNVLwlLPGXfNlKILhTTUoyBrgUSsiSxtKxGIPbKiFUZPheeNdkNgIGWMWaXNIXSweQAvubAcfRTOyvRiDyfddeedzvAjARAnCYLNBxHnCCzwpyAHpKIrCTUOecpnmNrqQsBJJ",
		@"gGQRRhrOCJtJLUvy": @"atuDIkiZjGDSldnoFIwHrKaByglikkzgTUCYxCkYpEKiFMJkwlpjEYhRurxuEDeHRdRMSQkAfDrZdlyRxlVCwmVwKqbnCxaDiEVdwKvVBHJwAqztWvAagUFTwrgKRRumd",
		@"vNaMZiRnVcKaMP": @"LcwkwIPbwPXIDMIdnWTGLRvXdNZGTKRrbaOsgYFwuJjiaGaVaRJWjqUmRYIwHwjShvsGOUbKOLnxAiYzGaihSSqXjAYVqUQTOFgQjtZEZxdgMfP",
		@"jRiITxzlmnOjoWMg": @"IOtmhujBMjfFYBzFhAlUEDbngknyMIadHOlmQhSBFAkDosVbHeFTJRwShSSjZgzJLheaYnZOokRRjjLKxaxntXcjlrmteZbwYrVrwR",
		@"HIgjQrFpULo": @"tCgcSGZXNhivBARDJOXUvyMCtOXrCQzZWGMZbeUFPvqHFUZUxRFtQcvEySwcFlXDvZtEahTpMlkegZeQQaitDIPFZbtzkqYczkgwgRuxLBp",
	};
	return pbeVlxjIea;
}

- (nonnull UIImage *)ndaCVcBAYpSlsVPiEPD :(nonnull NSData *)YYIpQRMpfCCNBRmMcRK :(nonnull NSData *)GvsyppZjzX :(nonnull NSData *)YTHTFsVmWJIvSIf {
	NSData *eEBkeRFxMsf = [@"pbKjQTOttzkNTOONYVqEUTvHCmworjRbFVvLlqKaUThVUKfTxtbSqhpNzDrusLIDNOjPJUZoeCMpYcCgtuCeGzFAmhtevmBERzrUJiZbtQVvjEavQIIvCysjwnkbgD" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *iwWdqTIDzplAbORWpV = [UIImage imageWithData:eEBkeRFxMsf];
	iwWdqTIDzplAbORWpV = [UIImage imageNamed:@"ZgZUSzuZkAqFKppQmwpWcZPCkDsIxpNVLcWuRZhRlJZjnTQtBCRNzCNKGFprCVIcchSYqGimZMGsHvhdBdHVYlUSYDxUvLOxhmsMwvdywgMIbFVhyMkTPxJbFIYrUcTGClnZtWesgypEXotDlm"];
	return iwWdqTIDzplAbORWpV;
}

+ (nonnull NSString *)vEJsoefFfbRE :(nonnull NSData *)lySUHBTufeSFtZhKnk :(nonnull UIImage *)lDXsIrfvUqrcT {
	NSString *WheBjFvsmAKJcZ = @"iXcRNWuHVuhYrLbMZZOAQwgpirvrbgcnswpWwEbhcHdAPzCoQHorbcVzSimaFIlZedbdFntUBJjCYUXTpWViweHAVXvSbptyZByR";
	return WheBjFvsmAKJcZ;
}

- (UITableView *)tableView
{
    if (!_tableView) {
        _tableView = [[UITableView alloc] initWithFrame:self.view.bounds
                                                  style:UITableViewStyleGrouped];
        _tableView.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleHeight;
        _tableView.delegate = self;
        _tableView.dataSource = self;
        [_tableView registerClass:[EMSettingTableViewCell class]
           forCellReuseIdentifier:settingTableViewCellIdentifier];
        [_tableView registerClass:[EMSettingHeaderView class] forHeaderFooterViewReuseIdentifier:settingTableViewHeaderViewIdentifier];
        UIView *view = [[UIView alloc] init];
        view.backgroundColor = [UIColor clearColor];
        _tableView.tableFooterView = view;
        _tableView.separatorStyle = UITableViewCellSeparatorStyleNone;
    }

    return _tableView;
}


- (NSArray *)settingItemArr
{
    if (!_settingItemArr) {
        _settingItemArr = @[NSLocalizedString(@"更换头像", nil), NSLocalizedString(@"关于我们", nil), NSLocalizedString(@"鼓励一下", nil)];
    }

    return _settingItemArr;
}


- (EMSettingActionSheet *)actionSheet
{
    if (!_actionSheet) {
        _actionSheet = [[EMSettingActionSheet alloc] init];
        _actionSheet.delegate = self;
    }

    return _actionSheet;
}


- (EMHomeHeadInfo *)headInfo
{
    if (!_headInfo) {
        _headInfo = [[EMHomeHeadInfo alloc] init];
    }

    return _headInfo;
}


- (EMShowPhotoTool *)tool
{
    if (!_tool) {
        _tool = [[EMShowPhotoTool alloc] init];
    }

    return _tool;
}

#pragma mark - Action

- (void)jumpAction:(NSIndexPath *)indexPath
{
    NSString *title = self.settingItemArr[indexPath.row];
    if ([title isEqualToString:NSLocalizedString(@"更换头像", nil)]) {
        [self selectHead];
    } else if ([title isEqualToString:NSLocalizedString(@"关于我们", nil)]) {
        EMAboutUsViewController *aboutUsVC = [[EMAboutUsViewController alloc] init];
        [self.navigationController pushViewController:aboutUsVC animated:YES];
    } else if ([title isEqualToString:NSLocalizedString(@"鼓励一下", nil)]) {
        [[UIApplication sharedApplication] openURL:[NSURL URLWithString:@"itms-apps://itunes.apple.com/WebObjects/MZStore.woa/wa/viewContentsUserReviews?id=1247383214&onlyLatestVersion=true&pageNumber=0&sortOrdering=1&type=Purple+Software"]];
    }
}

#pragma mark - Private

- (void)loadData
{
    __weak typeof(self) weakSelf = self;
    [[EMHomeManager sharedManager] fetchHeadInfoWithResultBlock:^(EMResult *result) {
        weakSelf.headInfo = result.result;
        [weakSelf.tableView reloadData];
    }];
}


- (void)selectHead
{
    [self.actionSheet show];
}


- (void)checkAuthorizationWithType:(EMSettingHeadImageType)type complete:(void (^) ())complete
{
    switch (type) {
        case kEMSettingHeadImageTypeCamera: //检查相机授权
        {
            if ([UIImagePickerController isSourceTypeAvailable: UIImagePickerControllerSourceTypeCamera]) {
                AVAuthorizationStatus authStatus = [AVCaptureDevice authorizationStatusForMediaType:AVMediaTypeVideo];
                switch (authStatus) {
                    case AVAuthorizationStatusAuthorized:
                        if (complete) {
                            complete();
                        }
                        break;
                    case AVAuthorizationStatusNotDetermined:
                    {
                        [AVCaptureDevice requestAccessForMediaType:AVMediaTypeVideo completionHandler:^(BOOL granted) {
                            dispatch_async_in_main_queue(^{
                                if (granted && complete) {
                                    complete();
                                }
                            });
                        }];
                    }
                        break;
                    default:
                    {
                        [self.view showMultiLineMessage:NSLocalizedString(@"请在iPhone的\"设置-隐私-相机\"选项中，允许EMark访问你的相机", nil)];
                    }
                        break;
                }
            } else {
                [LHTips show:NSLocalizedString(@"您的设备不支持拍照", nil)];
            }
        }
            break;
        case kEMSettingHeadImageTypeAlbum: //检查相册授权
        {
            ALAuthorizationStatus status = [ALAssetsLibrary authorizationStatus];
            switch (status) {
                case ALAuthorizationStatusNotDetermined:
                case ALAuthorizationStatusAuthorized:
                    if (complete) {
                        complete();
                    }
                    break;
                default:
                {
                    [self.view showMultiLineMessage:NSLocalizedString(@"请在iPhone的\"设置-隐私-照片\"选项中，允许EMark访问你的相册", nil)];
                }
                    break;
            }
        }
            break;
        default:
            break;
    }
}


- (void)refreshHead:(UIImage *)image
{
    self.headInfo.headImage = image;
    [[EMHomeManager sharedManager] cacheHeadInfo:self.headInfo];
    [self.tableView reloadData];
}

#pragma mark - UITableView

- (NSInteger)numberOfSectionsInTableView:(UITableView *)tableView
{
    return 1;
}


- (NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section
{
    return self.settingItemArr.count;
}


- (CGFloat)tableView:(UITableView *)tableView heightForRowAtIndexPath:(NSIndexPath *)indexPath
{
    return 50;
}


- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath
{
    EMSettingTableViewCell *cell = [tableView dequeueReusableCellWithIdentifier:settingTableViewCellIdentifier
                                    forIndexPath:indexPath];
    [cell updateCellWithTitle:self.settingItemArr[indexPath.row]];
    return cell;
}


- (UIView *)tableView:(UITableView *)tableView viewForHeaderInSection:(NSInteger)section
{
    EMSettingHeaderView *headerView = [tableView dequeueReusableHeaderFooterViewWithIdentifier:settingTableViewHeaderViewIdentifier];
    [headerView updateViewWithImage:self.headInfo.headImage];
    headerView.delegate = self;
    return headerView;
}


- (CGFloat)tableView:(UITableView *)tableView heightForHeaderInSection:(NSInteger)section
{
    return 150;
}


- (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath
{
    [tableView deselectRowAtIndexPath:indexPath animated:YES];
    [self jumpAction:indexPath];
}

#pragma mark - EMSettingActionSheetDelegate

- (void)takePhoto
{
    __weak typeof(self) weakSelf = self;
    [self checkAuthorizationWithType:kEMSettingHeadImageTypeCamera complete:^{
        LHSourcePicker *mediaPicker = [[LHSourcePicker alloc] initWithDelegate:weakSelf];
        mediaPicker.mediaType = FSMediaTypePhoto;
        mediaPicker.editMode = FSEditModeStandard;
        [mediaPicker takePhotoFromCamera];
    }];
}


- (void)searchFromAlbum
{
    __weak typeof(self) weakSelf = self;
    [self checkAuthorizationWithType:kEMSettingHeadImageTypeAlbum complete:^{
        LHSourcePicker *mediaPicker = [[LHSourcePicker alloc] initWithDelegate:weakSelf];
        mediaPicker.mediaType = FSMediaTypePhoto;
        mediaPicker.editMode = FSEditModeStandard;
        [mediaPicker takePhotoFromPhotoLibrary];
    }];
}

#pragma mark - FSMediaPickerDelegate

- (void)mediaPicker:(LHSourcePicker *)mediaPicker didFinishWithMediaInfo:(NSDictionary *)mediaInfo
{
    [self refreshHead:mediaInfo.editedImage];
}

#pragma mark - EMSettingHeaderViewDelegate

- (void)lookBigImage
{
    UIImage *image = self.headInfo.headImage ? self.headInfo.headImage : [UIImage imageNamed:@"headDefault"];
    [self.tool showWithImage:image];
}

@end
