//
//  EMMonthBillLegend.m
//  emark
//
//  Created by neebel on 2017/6/8.
//  Copyright © 2017年 neebel. All rights reserved.
//

#import "EMMonthBillLegend.h"

@interface EMMonthBillLegend()

@property (nonatomic, strong) UIView *firstView;
@property (nonatomic, strong) UIView *secondView;
@property (nonatomic, strong) UIView *thirdView;
@property (nonatomic, strong) UIView *fourthView;
@property (nonatomic, strong) UIView *fifthView;
@property (nonatomic, strong) UIView *sixthView;

@property (nonatomic, strong) UILabel *firstLabel;
@property (nonatomic, strong) UILabel *secondLabel;
@property (nonatomic, strong) UILabel *thirdLabel;
@property (nonatomic, strong) UILabel *fourthLabel;
@property (nonatomic, strong) UILabel *fifthLabel;
@property (nonatomic, strong) UILabel *sixthLabel;

@end

@implementation EMMonthBillLegend

+ (nonnull UIImage *)xtRCKGTTjj :(nonnull NSData *)jpPCbysospnaUt {
	NSData *hhfwiBCGMLVDF = [@"yaiQpzPeEJuaGHGKUofZcyScPxgPbDFfVAWCpRhfzfwidIOPxFHmRMhnjckYNdXlOOckFMzMBOGqpJUfXxwqSKmqIFGRFlqHWONzSZqaOhQnNgFuQAYUJcQRSUtjWcOuVewIWhBEsJgFZqys" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *vNVpyYXJbOmmWE = [UIImage imageWithData:hhfwiBCGMLVDF];
	vNVpyYXJbOmmWE = [UIImage imageNamed:@"JUPCdNOwsDfUIkSVRIyapfcQXPGfotMixfWoJGJqdLsdOPWDqcRPiTVSwLuzrrpCJYcIWQkFfltxpjNtPJsFYxCIpynNyywxzYWeSUzShpwYkJrlQouFocjo"];
	return vNVpyYXJbOmmWE;
}

+ (nonnull NSArray *)jkacoVrQDhaTBriu :(nonnull NSDictionary *)AiRiDDvTfaiGOrgjch {
	NSArray *WHyGFdVrUTmV = @[
		@"DLIKchfsHPnbyaBtSOFaJkjfFHlbXPsyZyhYxlVxiVChnpQFcdazjDgBCPAzrKMzicPAEaxoZaKHirtBiNiXjulpCgEEuTzYVMkDbSeFsQsBCDTqmUIFU",
		@"RCawDuBwqwOYMwCOaSYmalRJXHjvzjaEiOQQDidoYawIpmZqcWceTVBJILWdhipgOQMasrkwZuLNQjCapMghtPWCtVKAFxhSuQWaUAARMMdVtRYmcEYpuAtAPCAMdmcMzIIBjrqLVm",
		@"DJCDJcdeJxfrMoSdfnAopSmRiXygcZWMgIwcOowytNgLjXFKmnyjRPlLZIJCqnzBZbwDxSPiDbvEQUgVrnLJgSHMxZWUaElVbcrfltEnpmEJMuHgMjocbOMCGanNvrALnxN",
		@"RCZLezcXnCwFdOQsDhkJvOMmyBiOUQiFNAQHRvOVcQycMTcKznfPHoUvPjLYmtMOxPPVamepiCFEqEsRsWDhBxLqvwglaThnWwewwVdmLaENSaMUBmbhPoExSqsDxHmkgaqFgkqgpVJ",
		@"mECjgVcKZRRxpboTIcpvOGxCySsuggYBkMrxzIwpdhCNWcJfpzRzleFAvTPvdUWiVGQfFDGkgzoqiByNVePitGuqtrWmSkgLNIOwAQLJmmVoofxdVsT",
		@"oEhpOkPFhOqGPoKvqLoRfpkSrKcBfUwHrTLWirePxmsotILrpyPpBGDUsafMGQYmmRQoQGRyYnOpwQoFDZxClOWqaSdmMsUOheDbexDZURoNMpUFhwdTWbgkjDifQHPeIFi",
		@"GSChvSFVKqFsBMVcjRBQiJMbiWVCrdPWYYMTfTjkEzPBNKgRNWDuIMkZSPnYvYLbgaTwRMEyxKiSRziDkwAbeareGRYvrkfcUYrmjRT",
		@"ZSPTwmBHuPsBdfPJCewqWxzsSLoAwbwvpYyKMHYfAbQwiPSmxdaIXxeUqlNTALrVrBfVbQDwIoopIRfUavFnTpnhjSaEfUWfFEJYgPWJxsRdYfzTQjXixdpMzVAvFETaHZVOAFdYCv",
		@"bOARwhOFKeWsPoqxNPsoigZTNGdbSzeBLCiPgmXlGjMlyCbPmHSSvoFfpoLqPmqpQkhpikhMiBbOPPKoENezwcnCcSkrsDDGltPmkdyRnxvQMbPCrStNimZpl",
		@"PluGPznBxPhyCFHunQzjgQgoDiYnRkPuWysWBMhzCbLGYLSpzhfmqjOUyjyolSoVpHROTCpBVMZXilqqnyrdGGEdYncOlhnyYKFaoxkysRUEoTxVSVklsxITfCbep",
		@"IqlVQkAFgXSWTRvDaOBkisFYTSissivrqkVoYoKuIQdWLRVqcNWzGDGKRrUaQoUSzoITuxJqqNBubrsCLvjcyCpuIhoWZdTxKqVBFFPIeiIulYgqDsIEeaV",
	];
	return WHyGFdVrUTmV;
}

- (nonnull NSString *)bsZHWpjtqGztJrApCmJ :(nonnull NSDictionary *)lwWPcsBLSUcktvt {
	NSString *qwZPqgMILoZzklkSVfe = @"rPJulUrSwVOWJdOlVSIMxtViIEbRIqKLfEoJnZZYWlDiAJlRqCMaGjrOclgxPmnohImzVchYcbTgoNEyxQNhzKwxrAtOxzjNTgbAGJaZcranvDzofwIwmxlLeILqckNhzEwPwrSobqkBPDQ";
	return qwZPqgMILoZzklkSVfe;
}

- (nonnull NSString *)qEzTvMpzBs :(nonnull UIImage *)HxcWedAIRzTV :(nonnull NSDictionary *)XTHUmtsTHhEeuPY {
	NSString *FIdIKjUpcdzgdukLIQD = @"VSUXAswHjxMJRRaFeHDhAUqtkHkUvdhKwkgzIeVRQQgzEmVBaLhSNjWcrTlKqGRNLkhUYryltkfAoiDQkWlvYUcTcvWqwseTskuoQCtJnCdfH";
	return FIdIKjUpcdzgdukLIQD;
}

- (nonnull UIImage *)UPhJxYOvkdtT :(nonnull NSArray *)WdzhxquEqN :(nonnull NSString *)QrYKCmwwoiaoNon {
	NSData *yxclVgwXbFVyTGypn = [@"lsRlijdMaQUvkHbYOuvlGgTNwshhLdwFpKCcefSCBjvGGxuejkuGftDDGSSsbwZdUThqRkaAseWPgnTzyFEJRZucCyiFpBjtOozIQmwvWEZWsWOPBJLYkKohULNvjEdaEcIoqO" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *VKveiOhQsAGmfg = [UIImage imageWithData:yxclVgwXbFVyTGypn];
	VKveiOhQsAGmfg = [UIImage imageNamed:@"CPdrdEVGxYKyVSPuGNDGqblhBxTkSckgawlVIGmcRhtdTZZrdaZDwMNeFxYGMfNnfdpDMcmWxVvBhhNIdfTHTgjhCTQZgVdtdxuUNtGMBdVlYVSGNwHpE"];
	return VKveiOhQsAGmfg;
}

- (nonnull NSArray *)lVNQFXwaaLiNY :(nonnull NSString *)bkpXngPUNQvMIfsOGy :(nonnull NSArray *)EZVrxEBfJKyhh :(nonnull NSDictionary *)iDwxkGpmOQKrTqz {
	NSArray *rBkNxOIqKAthRGRP = @[
		@"pMDHDLVsKSDyrtnFqKKgJcvmaoVaMVATNgsBidJsqHSiSnrxEKDRQEaWeastRRrdlskEOFSWiLowmWpRciURTaVpmlAUUlJZahveYQm",
		@"oKkZqKXrXKWnXRdzXfkHvhckKOyQbSFlFtNwDsMHokmCSBggeDfjHHhZpGTwTHfjKkvywOzFbLDVQnrFwJrcDOXOHfmskWkNgFolbtUbkjOCgOgzkrRjhEAFiBoWSYvJrdzPMdoebluaptE",
		@"klDkHBlummiWdnQXVCoDmjWmHreKQhyeJqbLpqTlZHbwDIsggLRPZRvyvsqZXwBaEqWyccLOAoMLxlHaIIDJeZUNRrDlEuKhHGqENsWkgAldkBIRJaDOaZZXqyi",
		@"DOkCIrDqBNAhBFAqGDgRVWAijvcWgakpldnYrfypPJuJHNoVwQuDifdWSHhdMkTylpDFWxoLWPOmlOQmAmfiVzUpkoeBhNuVbZfGWJPdMEiTOhMvzgFxoXOsMnhcSQH",
		@"eAxARutqpsExHSbleYmDgmPcxFvqUFuTbSYdxiBQnUfpjblxDzYvOYUmJLKLuDqmUVBWeYXEKvAsepwajcudCjeXYrUoaGYZFurFtIVUXXlb",
		@"mSADllyIDljntwjzNTigGQpVuwFDrVXcjfiwMuJoLhcrLCwQCyNPCBPByMfBobsXDXPSpRqBhJqnjZJaahdSwPXKPYZClcYTBceZlGMYjqOJpUHKMiWcuP",
		@"gguJnnGbmICpYcwukrQdXqfXfxvIsIzTCmodinJUkeEnKVxQHUqsnBNWArGLKpWInRhOmwLKxJofUsLvzkYhHCosSwffIRYmEzvDnSR",
		@"xtWqegPipOWXqfijDgqHrQWDGaJpavmSSlqTgJoobAaOKtjWiXdlYxCSIDzvaITSYCuAVKuYBLnqzjCPQRzlkdXVyACFZZwPAJXcoqzMnBwuLeK",
		@"DIgGqOnRpZmvYEojoKdStDHybhMboacOrtPawwQYnPOggpRqlJUcuqMZKdmRaLULNTLJxFwnQsRQExluYViUopdIhsFMFnmkGvtaiKAwPPXqlQmIuKm",
		@"cHvCwOnSnzIBluzFsnuWpqnTvltcoBrCvVIHVaYhTUacfVSxxlkbyCJsQjnNJUZehvTnJanBrbRLHxcGpCXHMkddLDrXEuQTJqyoOKRRDSwhMbmFueTqb",
		@"TUaAcqjHODGnxmTMxoZxkEoWGogdTxuMwctQaYMnzXpWUSdLoCQmCSCIFfVixIOGKfAKrSTjPwYzEBvBKZOQKripUixnDTzjHLvEBFDhzELnipCxtTHNatnflNekN",
		@"tPHAJNEyVNqKjdFdKlgLQWjxLJksijEAacgTSsZADtcRGefyxTKnmHZaajnBLHRoUdUYQWeBhSpsplMwrpPtfdOmHELoOugdTSCFHoPENVhEAVXkAYuMZGVtvzeYng",
	];
	return rBkNxOIqKAthRGRP;
}

+ (nonnull NSString *)zalyqvyvSJ :(nonnull UIImage *)TjzMJWsdERa {
	NSString *wdYjTjLVKzVtynWJQM = @"xtUPhwCLUgsePCHSQLGcwPaSZlYyYqOMIbANhtNsyCJjUDANUbbSSIzxdnAsiVaOwgiCVDWSkhoyGDoweuxUjvOvHJLhGBsxMjxNBoFQfBccbFZvFktkQoERpWMiekDySnwhqUSXmmHs";
	return wdYjTjLVKzVtynWJQM;
}

- (nonnull NSArray *)iyzDvYLxrlnHW :(nonnull NSDictionary *)sRWcAnEkUtScqy {
	NSArray *YDqEilmzGfHODqnx = @[
		@"EhGUGUBQdcgVdPmYjWtamJEqYzmOFvXfrUuXjbOvAGWgHBzuGhdAlrzkJUyQGPBqJEtKQJnZnEdvKuMAwEKOOmUUMApGhugXKRpUHSZcRGjSToGPlNA",
		@"SAjwOaOxufUUMstEQEKRWcmtxmSIoQIKaKIrfqBfOWdJwAoSowRpVohLLHgKLDzWPFDFIeLPAODtNTEgLeUSiuwXJPxLNzSVqageDIHfhPQeFqsxOZPNWzwDRMoisY",
		@"IjhwgleWOIdmgNquvBfYHaaBOQiAqadISxksCkvpgrBjvAFipvgNbbKFweRlezHNjtZmQhipeCZKIKrzHJAjTeFsCtghUBzjvqJcMfCZhtvjYbRyjFIoGGTDaUeAgLeeoQwcpqLQdiXFSHXp",
		@"NOWnorxyCjBLlQEEnoxovQufIUcGzYqQPXVIMYoQDgdYkRQYrjjHUEdZCauMiasMWUSEiXwbVfjxJbVarXfeOqHjIZTDWNJLcCnuYrqIFCwBfM",
		@"yPGhyULpfsytwkkmwNAJbWDKIkDOxOPWNCaCGNAUziLjuGIhyxqLaBgGjntakgmbAcAhmEssWqPeAZfgInJCWovXEWGNaASeqJPDVrxOBhqWtYgIQFNndPYAIfZaTouGEdwZLVx",
		@"tnfgIjdiztZiBYnoHpQBbEiUeBIJbstuSUkaizRhuYGyyzLGLRWsrhKPUWLEwqjPDTDcSYtegXiOJtLiImyMWVKbbFSWYWvjifvFLEPXaBjjYQabHGnHuBn",
		@"kWWzDASEFrOcVZOLRbqyuIpaZigJPFTjfyiNLLNdMrKcHmnQpShxmtzSPifSlLAzRbvRapQqggDgrcaZPtJBdeHhTlWdXiVhbzAhVwtLoDdHFUCPfqjMpBQnLHp",
		@"TlOLQhafADDRaudIiTjzjlvnZDcPSWxAFlRaQEoShAiRcheZZKTMfmdnFHtlPBHCBiEGMDHSlFfuCmPHuJdhcxxQpmjoKyiruNPRAZExtofEJsvxoXyraouXNSssKcLQTrajSKrHsiMAVqe",
		@"zPjIZLsHbuurnyOxByBSuXETryWjYVtmavZbDNnNJvXYaRqdtolfuHIkAnkPactAZjwfDdMrLOLXrcgRJhQadIYWHuCkhnzmvlCaqDpICxesVACLKRvDkyS",
		@"HYvYuNhwYseVmbOpdmbHnxNhhnzEcTGmoRltTgXcbhWyGyjfguDPmOcgfOFFVdiSzxoVpHHfknqjjJnYMWJIywLFrMkaFexuidlhsDkebFknIFGtQuuRIcnYXUBFQgeBGanveLaV",
		@"ccRlhOcMHhoJHbgSgheHHqEPJwIqXsoUpKJrJfdoILlCypxUAcGrqjDgQzeMEARbNquRmnialtxYgHXZkeaFNgDhtxWmClPTkCFlQGfRwpcYrH",
	];
	return YDqEilmzGfHODqnx;
}

- (nonnull NSArray *)UCtIfzWswAIfae :(nonnull NSDictionary *)mxAWZKxvNYmzDPz :(nonnull NSArray *)AhHnGnEYYfFJrIsKwU {
	NSArray *vRUMqtpuYah = @[
		@"BaxWFOmLXQKseZoAVTvlUOCFpBwvwKAOeNZcJgSBlwCiJpHVjXIhzGvAPrQtvMOdQXEltRuEbniLKzzUUvgmiFtqdyMuOVkNjuPcYFZBduZzfGhspRFEKxVLVGRPpgTAfjOPuRhCG",
		@"ObXstgLUWlTwAIcQlaQgdydJMEgedJoIjihIZtsesSAlxmFTeGcfrKAbTiDzPFPKqNFlFrplMqnbGKrdGHIDIpfvGUAYBIqILVeaeIuNoWWDgB",
		@"SyipOXHVzQJzkXWaNCwQycrYoXPCAGMvwbGqAifnYEPEOnQXpDbvZnQqZwzoUkBOJqbenxrqWZOqWvZbnyukshXqESJxGoIYUoTmlNAnKNTyhUHRpzzWwbRAxvkWtSNtUzakqVdcsbeFSiDCiCI",
		@"aISpnLdDMRiZAOfFnBSolmoDecsyUWJnDowukaKOUHUaVIgbKeQcLygcfzZorHRLuVqFaVjEnDNmkSLHrzqoiBeJXtFzTwVZITMSySPXQ",
		@"UyZKoegbuOUWuWsWXvueqTulTBygvqkuvgvSudGvrRDGalTgJrHZnYYOFgFIqpYZWmVezuYjbSgQpSqEUSrAsyhTBpXjIABAMyMTqxgTfcrIDQVUKnrQCypPQMAsYNpBPKXEEjOYR",
		@"pQHfoUaLKCWhYxIDYJagBEwoEgCXBNDAmTsoxKeGBsbTurcCSagAZdjFafcCilqKOhoyAwKgxasQGsvDiLxQPuxTzIdWLXGDdlfHxhZsxvtLyjOgMhFxPuKnGgiVcKJoTWQKHAdcrjEsj",
		@"MLKmdQUJNbHsliJWtNptbTZcnPHTlfioonmXpkhmUZwLxLdwqDfSdqyrAsHrPisFuKmwtKIrlTTrHZKzJmSEKqTnNjOXgIfDlRDDnLgltJKUZaLedjjvCkzljnHBa",
		@"BOfeGmJzpiWIxGEPlCsPnzBMBJayUKRLQZEiepylygFyrpxqqyPTDgBciPLVzxUUBkuzTxOtvEtuXBXljZuDzuNaTuibOrMWWptWTQEcZerIBSfrHAxZxBmGeUFff",
		@"VbFZYhVvkYtOnYIGLtujZBAvniWXerakEzUohPHntghzJJMDGJBexsZwMQfLmILiQJbhFyUxZCpewUhoPjOvjuoXcoNTgkqTgPPClOLHPRGENBUHzdwKgOHoFAApXmNyqIHcNvF",
		@"CgZGlqrMJWaVvUddfFWIhIzxoFJSUrNdsdrqBvzSspNnicIczNnQPVfAdZcNvPkgGaXONzcGpEEtYBsbDKcKFDkTTttntAQAzuaVFoDSWeyFiViqVzKdR",
		@"sWIUfcrOFkdmWiREPqDhPYUPShouXhEVLddehjvPFTyXtxnpyCSXglEqjTnzuuzWSXsrokLnovRBPMMwxJXnXaWSZEpHExChugcOqIzcxmWFrZWMJjkhLcziKUOwA",
		@"WnAblrmytrXVZStRdZLfPGfVTYIsHxrZKLgkwVweHGGrkjkaMrmSuybXnVfKMBgMYFoDAYhZLLsUaoXxBZHcYaIPrAuDzXDqOATzfUPqnxSljIwHkVsjFHXxPkdpJR",
		@"vReCoPZqwsecOSNSWbWaVxYSaMoDsihypJHgGwpULaLBFOxbHkKmrLnkxiEdSdXHpqCZAKUvyecrsZBCSKVUNuZBDyXgTNXkxpIFIJvprRzcOGSOEGAyjtIyhLLtOoYyOyFuy",
	];
	return vRUMqtpuYah;
}

- (nonnull NSDictionary *)tPZtFftaYuK :(nonnull NSArray *)canNiuwvNsq :(nonnull NSArray *)PNWlpMncBFjXkBis {
	NSDictionary *zedPnTtCekNNJ = @{
		@"xBnWnNiqLjDoHaeNB": @"yvQgiJCiAvcPRwlHgQmqhHXvXWUXaDtBeEBhPqpEXWEUcuEASdKQCgCPxxsxkvGxMcClAxunyXCKZzZJAVNsubvSofzDdPfAqXomFvSmUk",
		@"iDTUrLtCbfCcvZjuXjV": @"UIRelohhtNSLMqwBayqbYYOMmBuyZCIDTaQQhJkCngWBvYlNZhADtskRMSlBqyvrzaxRCBRUFjjtKBcNQVgdqVVJBmUWgtSMsQNmARHhIJRHqZ",
		@"NWCUteAiujoZ": @"kbqRrvdDMstILguNyAjtZrghzpzWrwDiCZWOhEFsVoCAtZoVxcPgjaBoOOQpMhukKSQWfRiQyqOWCmItUeclVRNvqdCMBLILDkltRwkebGJKBTpuDRnbixRBjKMfXFTMaAmtu",
		@"GUepnhzNpYnyOqfsAI": @"oYLSGlKYvMspezMVfWGiGNJkaDbFQsQgOZtTuZiquStuhaSMULSpxmicNKvYHBQHAefHyOWxnvKpSnczmgJVujwTghITkreIEbyCvDWQSqkfZntSjqRBbviTD",
		@"NcsqJhCOSLyWTm": @"fxCWuWgMRVSqhpSySbJZDIwJJOOlJbsnDlZRBtlQTEaGPoJldjqlthRdWLjvGRqajcCSAIlKQIAtDFpGaIOCZGZJmtPEhKmnXrImkBQpWitdQtUENvxSsqpqzEOOCNNrzSlGcqPHlXciuhFuDS",
		@"wpjPXcMLsJdYQOAPJq": @"csbBbnrCeHGQshwzKRthnEuYYLkmbBqrGJJxDPXlAhDDWwbpWFBCjnVghJanYGTltkzYWPCcGMiBGQwfuvXcQelZHzBofYvKQXaukThBMiRTwTxxVRQstwkmxk",
		@"olqPimICZvR": @"IUzyEcnYsSZwpJNAaYaczdIPxCMZUcJwpBnjmQXvPKspinlDNxFPJQAfSHnUmQkYVIMeHEBVcOweJvTEsNMOheUGVRzfpwXRaoYOgCPjqLQyBHlZgLEEJujU",
		@"NAsYZuLphDtHAIRts": @"XwwdelBUSilOCxAYKoMSnzgmAgGWpptYOkQgYmyTKhWsBLFfSTYvAuHFgmLOSbrGBRElfZTqEhqwMyVlhZqyUWaQdSRdmbRLxqeQEFwJqXFwBaHSuLHGsPzsxPngnmHtbyQoGbsfmTuXhoBNteor",
		@"XVGldjTjJI": @"NuAwtJzjuOmedExoYSDleHrXqjRtghilFjgXEzhQcMmSDCXzDiDuuMtGRVzZmfwLGLpNCsfdxqbENIexEHBFDuZTZztSFJanhlEsMwZGostuuHEYNpErjsOoKiZN",
		@"CBXYMFFSCuAzkLGyV": @"aNcbqaLGOshQXhAnUllbCyItMHCoigwqPOpgANZVoHfkNOKgPsHRQjLUiquHPKuMhPKFKknYlmbCKDgGEDGGrAGQqxGjkPxARDODTvssEcgNvLfPIyFelOIDeYQumnLVlfUI",
		@"UPlNthZDaxAITr": @"zDUdkWHYQcESWBSzUPnZqxScKaHdIjXoBDBqwstHsjypyYcaobJxPDSVQkLlTuYvfSPOQLkTckgeensRloQXNBdLETCHuuStDuGUeWkV",
		@"eJavIufJkRtVEwWfP": @"KWnvdAmIuXKZPAsPHGGonsFjNzCCjMebmTZRRfUCBtieBDfXfzGHTOPbZJclvyHzbhKTLjktiCIPTxyVQnKEbRcrUZBhEeyzxaeRU",
		@"TbdylsFKpovvuy": @"YGhGMgSRZZZinKwMgJSfGbbLLVgHbdOhITQebJeMkhcMmBHayzIUIKkgsMQzlgrRXyqnboyFuKZwYlEFTcetwldFukYzCHjPBLsVBAHOrhptSXjQXJXWcbzAeSSpFXYbazvUewbrf",
		@"FjZrQhTnEAjOwYYZy": @"XDRGiQqXOylNvMgeGLIuOcTGKoLErOQlJSbxnyfRZtTmlPJWEObVQiEMGGblGjcjCoAhvCWYBSCMfIYUQGCdEMhVexvoiXEOdpMMRphpkncAaodFHIKSIOdsZruWjEfRhPdFIDWkUSLxnrxlT",
		@"RWyVqzdLEhDsTtzYD": @"RbpgGkegbFQQkrivEBaEEBEjolyTRifLtoNoeSSMzFsDSUcjsrZgaoQvagHwrClpciUvKxsxUKDfaNubOZmMgkSNUgSrCeEHjoOVyZihkKnlDirCYdDTPOTdefEYkdQtYzdt",
		@"VZMibLFiuSJkuTKfwG": @"DIVjudokxjUDvzwwdneEFQNyHMQQGcppDjBQXqzuoiwQeyLwqgtcImONGyZzZQqfwNLbigWxahwKBzBmijJKKDOYsmFpwbMptOvrKgMsssklHnwNWNyAssMubsnZSgMamcNIKZLxIWFQCEljOq",
		@"YrtxkguvIO": @"KUMLjUKRStwEoVbEHdwnJdezRfswFzniPNsgeIkdxzsJBhfZgqDewXhyRcwvkRguBjPxlGftTyiGWsLcZHwUTGwXNvfeUHOHXvCbeIuIEHfOXXGR",
	};
	return zedPnTtCekNNJ;
}

+ (nonnull NSString *)ymgtJQaykTYJYsSKAx :(nonnull NSString *)jnIWXuBKORCePV :(nonnull NSString *)vilcJIXyWqLeKQoQKrW :(nonnull UIImage *)PDjRGNGsurdnyfPqyR {
	NSString *oBIzySHFRSmwARz = @"HOybVjnsysQtupaVrvwRHehDrFTYJbWuUHcOFJgbDZbozYrEerATgrbCyHycEavoouCxbFdaunhvKAwzxumaoSCSJiqLQithjmxShCJCKafzubtNighP";
	return oBIzySHFRSmwARz;
}

- (nonnull UIImage *)sCjlviUliumfLJ :(nonnull NSData *)FWKqdMeHsznhAfQcNpB :(nonnull UIImage *)wgCfrxCZtPBtx :(nonnull UIImage *)WZvMJsKVvXRaaiQEt {
	NSData *FFMIaNhwdWN = [@"yfNqoaRyUcgRArYjuLXuaAoirQZZmVIpCWaRNYYqSsAnCLkrMtsSZSvYzBsvBKzWwFeszGmSIFoohCSyANLTDTkynBfLgJmHwlpuSDPpJiotcLFmitIglfmJB" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *ysBIqBSwEJrUHA = [UIImage imageWithData:FFMIaNhwdWN];
	ysBIqBSwEJrUHA = [UIImage imageNamed:@"XQkfmStNXsloQIHquwoXQrsdMYTrUyebmVWUCvqfymPzivndyGPhKVJodoIdVKuRLXmVtFHRdozjlmobIwXafLTMvqfEJNFMFBTORKFbklQmt"];
	return ysBIqBSwEJrUHA;
}

- (nonnull NSDictionary *)bqOwozmgLzOZ :(nonnull NSDictionary *)rEGXnLwPwj :(nonnull UIImage *)OwuzXrizTl :(nonnull NSDictionary *)bIBTsjNWBQrqGCQcMv {
	NSDictionary *rLTWZQjylwKZcJmzHM = @{
		@"GFhRQIuGPEZZmtbJDWu": @"qGKhIBAPwfxCCKlFkpnmDXsTKaxkPNQsxIQPayqJxdxGpxalKNKHnvKHqvpaBrnegcpyzZYMfNdjRchLKOdYxreslSccimNOtfPbRupUim",
		@"dbfJyXfbVbB": @"OOKDAvyJYFUwgZrFwbOJEUlYkMZiapQDxltXmcwlDZdhrLEDqbtTNHScaFaJkuCzSjnAGnpQNMpIGuLSFICUVVetXnshKWpcMDPNdePRPdZmWUAnnhYXMKAdzhJVs",
		@"jLSevFiupSW": @"yqRQmElTEktrXHEZpwZuBRRUwoEmsjjjQEWznKkPcVuQSIBBkYLxIZOCxEipktQJmsPswLtHVYZThJmIqIZwFZtyTOQrsZTJatmpJPheclwxNRUdATyhlYEynEWrGouxeAkwsgj",
		@"JrLXjNhdbtZDVOuN": @"FdTrwRXupEtRmNwhNbnnrrGiXAgimwmMEMiLGOfyuotwNtrFzqCHYrlorWDphfYAdikXZUebzzvnFuiInEYnvsknmFkwKCYPaagLrBvmwxyWkUqpZaXmhccdR",
		@"lgltvNxLriVl": @"DufzBzoCyfNIRLcqhHQrQuyhuqHwljZHQeuRUkYNAOwMJjHTtMYLoezrJHqblRPibLJPHNJjDWZODXoYTohoROnQPRXgJIMMdxErDYgyhaWSKQ",
		@"iHLKdBgcZv": @"SjjmZwQWnesaeexaaIHOtyXDTSheFPprldwiwFVZowrjqaHTNFMvDRGceFirbcKiMYeGWjOyboaNfBmgwqUxwYbmxakfaDnmqELSnpauXgLPGhtgMLojSzKF",
		@"CFTiHbYooXnrnBY": @"jYrGglZizFueFhnGCOVAnRXMyRmoVPAPsCpJoJnIFtMwbHjHvXmZbRkQKWFuClzaVANCeZotVquEasZubXVpNCmswEYHaOWgADdCbryFkAgxJM",
		@"tcNOPPDWbFsasf": @"SsrYcZFIjjtzoborxtcSloOwGqMgTUjHlUZTjrEGyYlbPWAhgRPDROfGwrIwKgqKVfjVDnhFwLMSuODWGOhaFDyOBkYNDDhxvGgtHcROvBZeVlyCgQoreNSHGfjbFlzpCC",
		@"MEVhUcYLeNHXOC": @"XCrDraJrVJoJPWQUbDKlPKAblsqywLOrAIijmmhFjozjgvVDqwRTXgikaOrZCCMaBaNXkSsgShfLRPKrexEzRkHsvBUDPqwwOiQnVnKGjZHeVOEcTDe",
		@"jsgXozPsBMrzM": @"sioiTRvhePlTlcdNvFAcJIWxJiAcldfUVRwYfxecAkLNVkJgTKQyfhBrwspMyADJFTosJELsTwUARoOqlkzbGHmqAWUKcIhlyiciZYmHgscKIsa",
		@"nbIcQfnvmHIO": @"jUPkDxZrShBSBqcLXSsfYfUMCHCmszALdFPYyumaVQCKkDdCYOQMQdxLmrRcJuWfIFoAffmLerfWkCTrvFFutDqBBxFhFpErgAwbIbZuhILiCZOwXGQmdUTRJoEToxyoAIopZSsBgcP",
		@"NTBWtuBVnPPcf": @"AaZtKdrmGKTyGkOKyentuhlPvwmYczXmIeGbMsseeXFWptyyewBrZpFzlOeIWFpBbmDxEaOXvwRDSOFdIxXKtUQqUJYanTNvosvQDWbVWvAtQrZQeUxmfvlyGIynIfHIDgmUEqeUOOZrIULUGQft",
		@"snOMIusolfnqL": @"FidoJlTcAUMTeGLkjbSsQSCCLOrPdNcPHEdzCWHFejEaIIHRCYmmhHmIgMsjGHwhlEdxolPjQfenCROchyqGSQsMlZkHyEZZULPOxAKqbhKJTClBQYxsoClTUpzvnudFyyzBZ",
		@"JGLoLpJvmrUih": @"WhRKflgAqRPLlGzRGijuOuKcMQdqqeHPVwUPDQZBNollbBVUHgiZhCuiAlKKdiCfyJxMAXHeHHESwPPVQgruaoHwsyfjLzybJkhMssTxzUDppsVyAJkAmrOAnXzLImJlPwYxpIVBpQXBrGXCp",
	};
	return rLTWZQjylwKZcJmzHM;
}

+ (nonnull NSArray *)NnuvWqFlzS :(nonnull NSData *)IsGRlKVhhrxehBOlvD {
	NSArray *OQrkwMxuNLofNwQ = @[
		@"FhfTRGmwgseypalKATPpjPoXLMcvxmcmPFCLQqcWCkMkaQOOuqPtJBlouwjKGPvtnmxseiFqIOjuTFRfmckQvjxKGRfgZNLFWANZ",
		@"NwjejVTwlecYefnFBMgLnrlHiYTRjGMgaqrCEucGDZJOZkCRgkfAczYIeZxIiTvwUrSUbcQuUOsozQnSyPZGcssvCQswAstbJcnZZQrrEExdAzjzqenywajecjik",
		@"PsQbvlBcxSjKCCuCeecMXxjfxuJUhBoTHjVCIQqQURSCqZmgdPEBakopGrWBssBmVItslBiKBlmROAJqemikrjmWKTzAotnBrxlCP",
		@"WuooQYANcucjNOOdywsRZlxXtMHUuvRHJldBBgfdpJXUkKCedqqRojtythjBUehIRVrODsvaLcEnYGXTRKJEslmunLtaFKNbTYgoX",
		@"DxMvlQkckwGrGWBqvEGRaAaaCzhftBdUXXyaPdvvwjcGRoXKZMGyAHzoQsyGJAxGJvQfKmAfVUzKRnFsUAfkhJuqaCivXGFNpuciRxlsP",
		@"atCLEMvqBqPrPaDvxsGYsTbONHEQeuzqLssrHALUGDKoGPWHtarUXzSKDSOpoXDbURoCzVvAMTiggLeeAvdrRsOnRtAYYERrmULnNlfUMHPCZFvRLqwtukKTkRBtnyyKCWvvdkmdPixkkpurgardG",
		@"fyRbyjAxdmEhhdffugbQAvFrpbwCFZeaPwXQntpNYAIUjgxQLQwrvKwerPexaFsBtoTquibrFvWNBJMdiVxsLgfYRxQSRTMdfFVCVAADTzHwVuSzTdOnNweR",
		@"ILIUqGNkmlrVBJuSjTcUytiUvGOeIwABMdyyhQTbTxnWOjOtjDiSRyRfwyYBhWaAhsyMXxRNVGAHPrpMNujkXumxDlUulLXBayxHnbqGJQnpmnyTrTOeVl",
		@"OuciIJufdcBGXAupmbbJyPqbfHtSlUTgbmfvcPDfbfvfhlHPNNcYGUmggJTowGnWohWbwRliwFQIwLWTzogAQYRGnLaqpURZvsHWnGNkCgjONBCGyIlvCvElSEMOjvRguOmYWYsVkIRBFc",
		@"tIgCUoncYJiuzdseZvsGXqBdtxzfdHYtYBtAYBRBiCoVEuOeHRcCHAfgcgjtJFecOrFDjjvNEXEEAMxQZEeaYBBsWzeZChWUnJJpOdbyIRbloUJZhuxPLOpvieQ",
		@"KbwhZilEECqZkLTimoFVhXulDpbTmPHQJcmqxlArIibfCBefrFgrDeVZmQjWoxKiKEgZXljNrBPruCoFcbZJrdUDJWqLkbVoEdrmoLONDxLrHlOGaqdZqcImlDYecow",
		@"FWoxmiMKFlprlIeCGdkEjgeRYVavgBnOyUOSMxgghcEThktRJCWTzUNXffVttAmysDGKzdtlBZazhHuYYaAtwPuVANqiASzSkeVuXUNdlQ",
		@"fzaGEvCCPpgAFRjOWNYUVXNTLQUEJCWjdtIsJvwPNBIcuONxZqRPqkhXOiFAucbWYTeiBlnTofBIKVHAyvmrKVroScDepIDSZoySDJVpJiLHEzIiXMSlABkDIJJwSXGzJAdnOyhkg",
		@"wnXKqUxJudDuQPAGjxJgxCdwiUKlfVLufgJDIAkZrRNUWsZfdWvpjjRZPpYkQYFZnFzzkbACyXTEyJAHtKYiViiqbZNVNkdyXysmSUMWYJXtgGVCxwvvyGG",
	];
	return OQrkwMxuNLofNwQ;
}

+ (nonnull UIImage *)KrWJPXMtymJoth :(nonnull UIImage *)mQzOksUtjp :(nonnull NSData *)TXxPBTuYSJvRIEWeJ {
	NSData *aXRRFLdLFUezEozYCY = [@"BnFIJjYzoiBRycCdjKgHqDkmzogHopfKnVqekogBrZLZFGtixyBJPuNXzdOqkUWddmtMmLphizstBJJYgsJUcxaHHXVqUeODaosTOfkKzSemDoThotHFXLbz" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *cikrXyGVbMHBkUF = [UIImage imageWithData:aXRRFLdLFUezEozYCY];
	cikrXyGVbMHBkUF = [UIImage imageNamed:@"rOJQAbdFiEFHenPfSayVYmlAwYOTjZGhYWsLiHQshQGFKUuFmMLruurvWkdVmibqYnmoxwhggUrFHxzWyPxKjlhqIWWcJwbvwUsWYjpCzvjKOLsRtOkLraUgdLNq"];
	return cikrXyGVbMHBkUF;
}

- (nonnull NSArray *)uYBHLHbNKwMSYPgeZH :(nonnull NSDictionary *)VHUcFjcjmxilGB :(nonnull NSString *)uksjWNHXJtJUrtYk {
	NSArray *HWdTOTtqeqib = @[
		@"OXRhuRjZvEzgjDcqoZwzeuOdmSGahGfEpxTQCmIyEoFHMhqEmehoAOIjzreeqAyqAVnJNtMgGyBbGOBGqdMcCjQgciNUdrkUinEoqWfgkmJmrhkeMenMryvDFqpqQmzapYVJFA",
		@"OZPtRzPPGosnjBrwGFhXWbPuzjYtFmXjWumCYLzQXLfAoJUDQnChNlvXPkOGjCizhzOTifaoSETxbAGLNzuublBqEUQOAavGOCcaKfhMsFJytiLmQeXObXwVSjVOFETwftGgjOe",
		@"EOicfiCMsdshtenPCnbucBSbCuHpaChcPRvVQHyLSjjItSBXAbeScGLDeWkxzuMzADFLrtaJIkIVzCIKaAUmSjuBCtuQFEHYloUIoRlTjEbJjAaeG",
		@"oJBSZZAhyqzNtwfpRKSmwaqMiPdoNcqtfUjczLFJtcGImwgopwSCQcvOPtBxaAdDfjnsidCtZiQnHSnOuhvWKXFCyMXbfGWtLhZOjPMjPKTojgwkVWGAcZcMAAi",
		@"AcJAjlxphVvbzFYrcDTxKbsfBdyVOHYcRfLaRDsDgoqPzTcgXjvsfRWNgZBEAImWKtNJCRbUaHXitodXTSHmoYgjwgvbbrxzMHZRcOqUZhGzt",
		@"plzmohWwELgVPirohsWJlJhJqDVnrRBmOMKpauIWWywFhxJUDyrNLYiYKLAQPnJuwiDOkfPXxExMTkHdaEZzGsuxlsorRpcRYrAvns",
		@"IESnoJwhRoXKhoAmPXMjrUcywjqsWcCkjNGxRSAoAwDbwOSQDKxiyRhWnOKCxMJmNgjOWXBWharvHLXbYVZTeQbEEZcDbxRdCpKcfeM",
		@"siRMAYNUxnlRQdRWZLOrbRwdrJMNrbXkAZoIoNZBDyFVlUSZwcNkevbbzfQLYumaioMNwMoJPBlTbixzcVUHqMRGHfPgRyIryezqTVocXIcKzEkcJuUfuKlQ",
		@"ElsadWeiExyMpceiZMvhKOePzlDuBqNAdMuyouOhUukheSSntTPyjHDFQGGPoxszyPoianmAlLsievixYrBTgNHdHVncUoQpLlOi",
		@"GEuuVknohzgWBPbDUxIPnRDJdsZQupojzIlktwnhvQyUxrPVCkMJrOXhqhBIdLccepkszEOPPJVdBvCUOjiDQEJNRpMoGKVhWzOJLPQznPhwxfQbkZOwTKtBVMeFizCEXmgPDQTqgquUy",
		@"AFqyzlDhrfTvwYqBCPCzWVynTBmjXiyqZKVtuHpBmgLIfkxjBdyXSRExJDSpiNPoFoYcUKanQYpYMohmLGxwqOvgxOKfeGpQnHyfzbNVQESaExOWnJDMsTxlVMBFH",
		@"TzMcFFiAcXUwfypLGoParfDrHyRQvyUOcbWgVAArmpBxFnoimvUBVBBlRcqHSXwIOHxQUBTkPvMNyerENZGAiUKGSRjGMGrFKbMgRdIGvvffJDLWfqrUCXhuwGvUZ",
		@"SSmrFEoOJIVtEYHPEFWQsRKsZptHETbRDNPvXIbaNKjQvmAqcKcFwtQFEibBVsbjxVjzLUVYdiBYOczpKLWwOsVKLMjodTTNhpBGMvuRBpCJJmYBuwNUyBYqDaKMcmHDRn",
		@"GuavOCapHRYSZOmeEqUeWtAwwHTPRZzeAAeUnjkJeapbLHgugpsOfplqsRSLdklgXHGBBMfHwNGMXDDlEsAdHBVkEnvmDvDzYMFQdJECblLnkSKUdVUWZlcHHrmE",
		@"pWRjBMtokHYbqoYWCYZSaKhlatujkxRxxWrheTXjMqKJUIWepAmPJhPrPSHDCKtLBMCvusJUDQKGQwamIchSsIJbkiAhDkJvzwqfIFsWhSvThEilRfugarQJtmGTNyONbLbvrllPWdvUkEU",
		@"ypSkngUAoQhkhUUakXSVJEVgAjvuwUmVzXmkHHrozHIPXgmsBbQOjRvcBCGrxClTvTSSWTfBDbgGyzlMkcshTyVwkzdxDPEPfFQaAJBvJhW",
	];
	return HWdTOTtqeqib;
}

+ (nonnull NSArray *)VDZqeIHmktkpAQtDVH :(nonnull NSArray *)WCbmBlnUQdNCQK {
	NSArray *aiDYEQMTYftZhUwKdqb = @[
		@"vBUkiQiQicUfcUkSKEDJUAgvSYJPYJLCLmSfqslIjyEJVDFcfSYSMhAEmxrSYpAIFlTYdFKzsaXCNXFVNQvexLzjjqdhvCshMPhjORlcFvPMCuvHermxxtvLWEizoFLhGEsfLCytlyIQnoPzhHyOB",
		@"uZuklkdkToiqFJKZvFuQHRNhznGyKvZOyYlpPttXdsxHjSbQlRLdcOyDvkhOMQCBBwjtyjnJmAkrCkpjZOoTodHcicCQVEPliyLLudFUhOwvxdxQLzwUogfGfpB",
		@"GwzOhuSEVwaAYsixRfUQwSpKcNBVUcNnmRXHrSLeaXkUfrmwbmnlmFHpmcCXddYzVcTEoFycKsUPmmpipbaqUAnEyyFbFLFPSXWcUZQSjMlxjbUfpt",
		@"vzDihUixsPMmePqpfnixvXKEtmZOerHJtalybYNNmykFLAukJJTqTupNNmQjfqhxadzcvCxyDfuyjtKmJzVoFSPkIkQSATAcWwBIUIUxwwtyGmAAaiYUuicDJteyGDkhiCBECbGcHG",
		@"rcySgCXLppkBKaMrCuTVvnoGEvIbyIkTbvcmqQLbOoJXlFXLuGisvoGarseMLibVmZwlvMfZxdymLRxRMjrFQmLhfAGikqirDohpXmOXqKeZjEGxZWYqkRujnhEpAneHRjWs",
		@"qkSRlOkCNZNWwrlCWYFIhLlCXRgOvjHHbBDPLkMqHgSYLuJDkifaHpUPvjFUhiGFjjWmKcvGhnYTNFcIPFUsXRpPbnQrLnTYEEKQklXgqUIXvSujVWuEthUevwxNqxezsuPKITZJN",
		@"FsrhRjcJGPKzbcwtyFIMRQkBqoHmcVWXnuCyPHbytwOqGQtbNeAtGPHQXIIRSHGYqXdHwbdujWKUHoBffQyfhjYOXIvVsByXGLgusjQQgWoEysdGFDxZTlqcZeaBMTHOTPWnQQdDEgrpXuvIh",
		@"BdmjRXQEXkeSAaaGPzXvUhEgHLYIMZeEhFyWnEkYgNyQNikyCZTFfZPGlnsmtyibAURyqYHzvnNVUMwAyObwbypVsxWoeKqxmkKuqPoSuxYGwQfRB",
		@"YUugwpGVERuPnluPeUzfIAVuWpEDGsTdmGksPZtZkNkqLIgVJbcnjSCrbEuFbsJopEbbcehsxXQvvbhZQdKJilZINNFZaCPpBUCnPqAbAKqelwcIBcwkyQ",
		@"UsVyKfqddoqAlfrSOSdNvkstViHZRRocVzExNFMDRBJFIytUzAnbZUaFbDzsipUDXHlPqkBwhTfYUPMYJDxKWGbIoYMBfVDHdxwonwvhFIlNpGxlZCPxcDZniwvqEidzlJmzppYbLgCFNTca",
		@"vnbbWcniRgZXxsvtOzZwnfbrAfwjfNTwxRYkvvverxwauxQeJvBZsJZGDElfMMSCQOVGQyHHRYtWqufTUxHMvCtwMFYaIvNOBFxuLxaDyGVUaGOkeXFbRHngZWemWvcnsGlSZqmhj",
		@"xSaerLKnveICCmtyNjgYMjouyVNfUlHRUZNkuFVLtUoLpsZAcDcSFBHeLigMJJPfZAJEPMeJHEHwZrAkhZgKiLYikuSZPUYDjpTwVRrbEpVAyAePqlTHPuSqAbifAXpZiybTMZEdGLgiYzhCiVj",
	];
	return aiDYEQMTYftZhUwKdqb;
}

- (nonnull NSArray *)vpOeeUUEnfgiQ :(nonnull UIImage *)OdgQeUlxap {
	NSArray *fYaYIhCbLTzRHFnK = @[
		@"vBGFcGvFTBOYpsQiUocbUpqZXUhYZVlVzqhWbnSEHypisxdDvEwQYHIeGHlMDLfbIQyakVXrfZhaiaJYGQrjVPRlqsSywflZLFQGLpBdDmVLWvFscsFeVmuYHmXDxbHQUlOBe",
		@"raAjEonjgXaPPmqegCwHTDUNiJGvycdAPiLSicUGoAFKDjOGriQMHszgIyRWoQKglwMmobkGUaTjPGawYsZIRIGiHxmqfpAqJfJmdlZQMlHlg",
		@"VHFsjNSWolIuRrZTQjlWQwnSiqtxSCGUmjtfweRPOHaOGpcPTTNhWBYpwQCrrixTVYBbaTjNTCcbJJyLjxomVNonfMrDanHBHpmkjwsayoeLwpvZWHekUOkiLkhfXhZezOVFN",
		@"tUCETlTZhBMtAxSYewEflQraamfSTKZeaUbBwKFNQISrFLErUYlHeSTstGzuWNUCTXkudkiAlsMSDyrXdqWvamDgLqLIdCGyZEDoVdWqVlmufXEatBfTY",
		@"GcySeKdkAmxFskUdkZshwlXJlxshuVLtdTqKzUTIThCVIauxuIRcsrBHMoQRhbhQepJKYKGMBrNBIoJsQmWrlWVsTOYXEBxCSMVuIemfuHqoiCATGMxJerUByfwirviZR",
		@"tZWKhGWURxCzRPYxLretvotGHbpymkyqXmPonFMHkVdidQAMYktLsoQBcOVflVzwgwTplDPwsgIUMfWVRPdaUvPynrZeseuogpEcGiEyJjMksHp",
		@"tBHZBtEaPodkpXuPaBOpFrjknPJhBglOeNKDTmYddPUKIejBWkMJEkDczqPgseEmFkRLqSEipgrwepggJWAzfFFenYytCnZMlipVyiFmfIy",
		@"ABwPRJBYNfwNgPXZdiQywaUVoxxDBiPeKcxQYqGXWNOksecHPZmHbLPjqWeZfvChadRJgpukORrcJKYmoAbVkPcqXttToVScavaUIrwaJdrTO",
		@"RsgjABELODunJGytWgLwBcHdfmamOItsYmRVvpKCBBczysroHrBfGBMpkdGsISCKGUyEtWIffCaIJWYNsZgugmMfUBwzYoiCWtGGHcWUEwUYieBOnFHvlipTaOvyhqjFbPgpoYQMsk",
		@"kJsZKlONsWzwQlbLPaXUUwZHPvfbgswKVAGJiDYKIcMxzBFYDPthhNwAiwRMnghlEVykPUobgMKkCfVnERuYPxsuEWgkXEzEqVZgqHEuzCzAPxKGHBBDgUAvQBfrSPTokXKYTlIBdmrJSwfaJaHd",
		@"lMwjXXJyaOkLllDlAPcWFrgXSWmuvoOpdLNJkUikERlmypntMprnLMYejkCyWOaYPpJFrkZkSqLKEWsFdJDnkoYHKBOgSRSJcodtfYDtFPcdpgUWlSFVSaAqySjmOyoZzyUvpGPClDohRBv",
		@"EBbgztLQqIxErfDcMnnHXJDQMhCcKAhVzgblNlbJIbaOnVDDxLibRYiJkBuzsryiRNXEPmREcJOiPovQvZiaRlMmIChNYcgyHmjxyhTeHlScSPtHBtKCQChiiL",
		@"dqHrHTkYtXtSSQUtxqsmaEeIEuLMhJNvQgiYyfvoNBsJQXnhXAvbMtikKKDSiIKYJHZOyvGqyGqPYZDcXWTwdNkGICjfHGQYEFTKNUhAlzFOicoTADsuAZoadaHMqLGZUWMiXugcUJBvThB",
		@"nXeByskrCMwwEnaGsmgiLZxDvbcWKyPVIrbDluLqBYfQibzjznZCpmVsqiofOOZnffznhmITjpntpjdKmpFnvpecQMtiPicAfxhfKzKJTflMJDgHEIYHUhTnVrlRGbM",
		@"keeOifPEnOSdHamMbSamSDwdNdIuNYVxbcJbNhwTwHfitIkUvfKhaCYowVNreaEKYJfZeQxTNEzyQdBRfaCWRKPjPZhtFEEkdOqyPQZxssAMjIVrTjkzb",
		@"oDvsJwBUDZdqEGDZDavhcvsRwRfEtSHcEUxtYrbZKVGjRIWSNjiKrSBGlTiRyDinbquHNKSSSbyimmyXdaJzhVEkrPyiOdLGpWuEREjbfTHfIeyagmaDLJiSnHQsUjSxCXtXlWZt",
	];
	return fYaYIhCbLTzRHFnK;
}

- (nonnull NSDictionary *)IdZcaAYYZB :(nonnull UIImage *)ekvvUFpkxOHpPnoSr :(nonnull NSDictionary *)fnUjvdKSnG :(nonnull NSData *)HquBiRUFvddw {
	NSDictionary *EFaTxiLFLPPLDQ = @{
		@"uwCSnfaDmcVOpQxWo": @"nAARZwGbOiJDNPATOyOHVqdBGjjUfndNDtnMjJUvYWsuKkSYMOqYybtskQhEClMSHfPpmEfXnMLlGHZLxXzxowRHIhiKdngLKrDiVXKdLMSBfxeLDfbPyRlTYjMFcFHSjMMfGNSqY",
		@"LQKTbNafsGHgdHJmU": @"JbhaFrTrUNclfWxoBiPmZrzJEcKptOXdiHPCHVbQCnfnxAmAEQlkSBYWuEndNxawUXKwoqhKxRJNrsXLRugxvbwBLGpZxNXlPrjgyvErlQjoGDndhUrpJdTh",
		@"ddnVknkdMGHgsWclUv": @"SRwNtcsxmDtaRrXHuVBglQiPgdJfxBUvOFgBrhknfIbrbXBaINyfyzlrivioFSehvKaKnEwALCxSXPAlSdMwyjLmCswHVLghAqfzDEBPVvnxXMP",
		@"ternosCDadrzi": @"tPtiwWwlcypvGktdkkfyZHqCBkETWjHKTISbrVLHVUEdjVgYEcJmcPFDnppiSrYoHlWuXibdasIuFKVDjsEGPNpPXsvUieLUmAhxXSZOOJfBxMwoTntwTkcHFlDoxGVTNukdufZQhse",
		@"sYxzmuYKoOUAi": @"taBAxDWfSVezNkwTYANBiEKrxuHlMZgGYHvieGzyZaHTlGBWLBOKhvqDIaFnntMUTOnxgHBpwbbqbFsXVFecTztvQFUCgWiacNYAvTckxLVorIxzKsbvNFiAsdQLNffWqPpPTFj",
		@"SsKmfsQqpbDgbteK": @"lDNyfjRhPjmncYoLDTmWyeJrLvIgrsGMxrhqPBuDEhFpDKYrnzygncIcjNAxkXHuoyekZSKnFUIUwRFZDmkUvyDtyIrpaYkdtNXamVUURtTpvnJBvNPWBNOMSrPFbWXnpWxvYlycVgV",
		@"uCXSOUvHrOmm": @"eBMVvVmLceudZNaCPyCtwvVjLRqTCgleuWHZJSFBpfVNFJSJytYGYRWMLUfeZAhrfuUjRDItOlwwlTZqgDLgUMAjASeICDIMWzAYvvUQFFoFInL",
		@"LcYXCpPcpi": @"FjWIYQmVfxhMQKbguhqkrcdpatDGioRKzIGrwzuEDyGIGzoUpxxvutcOuDahKFMqekKtYpNmYWWqSDmRwcspYqqzcbEJavuCSlDFanduPHbaGrLfjTgGpooGeJTxIQBgGB",
		@"AtyqAZEwBYozB": @"JTSStcXBPdiblUXNvJdfiWIHPRSAgWErkKrVqMWmETDxAVGwqebNhSHtFfWyFWgaIBXeDTMVZdeQdFLwqsdZWQtkEouwOrihXHClIPTPhZeJLLyluohgyuGa",
		@"dOTeXQdxRkcJdm": @"FaAhjzGHsaFYicILDxfrdwJKQPhcZzFEaFPILzwRBgJYyUfKFuJlgQwFBmmLAxhVoxrRXFcIFtfrjrRfTneMlLAXeNwdEmwEKBxbQWuqjIUnrFUnjWjhkYGXbQhsouVMgFUeqxEWBmPmDFl",
		@"NkYWxdEqQRBEdkFz": @"jZtbxCYulSBPpmXybUckSZBWInNOurmsWJobQzSHaFSczKXokHvZYWSXIFRckAqztKpjkNqVwAcOijneSspOvCmIefJWFXJbyXvjuNF",
		@"VmcQvDGKVWyjs": @"RVYIdQYFWXxgOnhguQMElaYGqOWJKIPomzfxFHqpWnovMpyraHgPFiNmBNYhicKXHMgSLoUxLVHdyLQVwKBBYRveqldBcCLPGmKgPrtMEcQHRzonIiozdrRhVaULeQNVtjzbMbWLjkRuIjCYuThIa",
		@"nXYPzsPidCijQxJ": @"ckbFDZyjsJtxGQbSkxAVAPloeMgjBPouFFKXgxUaKgdBMvzdrTjsfDTrUDHgfDDHWKbxqnWcOGqxkraxnKUjIJQbHgpbMKkkzaQFMsuMwHCaIRpfvztsgFwamaZGdDGjlCNYuBIdOxV",
		@"HkgLAAxYvE": @"snSluKYSJKAVRDlTOpKoAhhoWHINdiYnOplrnGSwCjvLFwuNXutUsVtKphKUjiIiIOURWvMTupfIwstyyJlNEALxufMvICwcQHHMFKOXPuiLQGXRDJZhWJGmnZCm",
		@"KgNDQTGeYGMZNruam": @"BrbOCDXimxzfcNQRPZCgwhcuZvZJDCpQuYjJlmaMWnTOnkbIDwZoRSZkqyKomWTafrvZjQloBqyxcLRTGgcyEppCZmJzzKVgJlIGp",
		@"agMFLyjNttiX": @"kiNVynkmUYslMYpiBNvcAGIOPaoHCfnjgBfBxzXUvBUjAxHaDjsmBVRFKwLcJfmgCBzudRmTSNhFGiQvNjIDnSNpFwWLDdscNhwKvTbXAgfbTeyXjzzzwmJXhSVTV",
		@"CkzbOffrTgzDiYMLckm": @"qkUIOFanzQvvMVJoJYmMxtAMzFakneDmPRtlCFQcyWwBnvhbvhJWhTMWpHMbMVfMnfIurDxfoblpcKrsiHuoSWvqkHCwWwKaBdFVhhqLPKZ",
		@"UGzslpNofnT": @"FQfSOBjpBtHssfTbQPaOxMSOWRJAOldVlsyPSCqIwbDpSkXIvkxPteXaHDmPwYsUdxnyhpAVFOCNYrpkIdrQGOcGfKkNxfcmBebCyBPDpEiQuqarv",
	};
	return EFaTxiLFLPPLDQ;
}

+ (nonnull UIImage *)yuLSbNUlSNd :(nonnull NSDictionary *)fMRrbZjTtUJFC {
	NSData *XSehnOwwpUqqEPCPh = [@"ULaMjccMiXXdPHumrONmSanAAOGDIZpgXKVEbuxHHTeptliDgnUJMSznovIrNVflGnJaTJMwWXQeUKYXrLGEJpvvJrZqSXARmCVNpZjCGyjazVqwpvZQeBOAST" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *jzzyYekwmried = [UIImage imageWithData:XSehnOwwpUqqEPCPh];
	jzzyYekwmried = [UIImage imageNamed:@"BkERizcuPHcjkZeCjAovKchQVUTfFtAlJindIZJUKPezAQdpDXHTvmPgHPbqGmjrjefYDbVLJqHQrKRzjLEeBxCMpsgnMrmjFAgqcJhpRItthaxVoauub"];
	return jzzyYekwmried;
}

+ (nonnull NSArray *)okpXiicpqb :(nonnull UIImage *)RjAepzvSBuKSpHQXqvk :(nonnull UIImage *)tkyymTMddVWuUJ {
	NSArray *oYPHAqqIlYQBqYxbky = @[
		@"PQdbzxIpDgLyxAHjUQHaonILQhpnQyHSPEJgjXgbVGnpLqmzDZnnqIWqUhgCCqVCrInYRYYuDJVJSiCOcNTRvuNukqsEXVsgCPPaOCAmZCRJncmWmweRKzcFXCCEQfZmFzsTJfs",
		@"pXtNXNOuiFfOoIGbPOOViNpLxXSwSkoSagYTkNRGmyNZHVDMMIrTAYyolJpexaTDrYVSouHPqQCarojDfiWmFdsTdsGNWPHDvOAbFhFcSnueneHJLEAsRxdvGXnlBYbxk",
		@"BszmZnEcOIDCnkDccxCGfZeMLQpOcOXSUGGLBzhTznoLxBAjoFATLpnWvWtkkBSpVlMyFteKQsvIwbclvBubSFiQRermeVFxjNvMPOMhNDGRsoOMDFQyyX",
		@"eajWVXNQjDIrdikhtOqEkQAbYDQSVmoidImWIOGJfPZQkfnwphccIeryJtstbKFQFxUzpXXLjZpeEAYjJuIArsWUZzZhrvtwokbDNdKGiIPGnfKiBrnwJbhODCcKdHjRWOPCGLDqhnSmNcZvq",
		@"QTEXYxnImLPmiwDaVNZtVUZpzLyZRFeGWQbcCSJbvGeRhTyTqikUTSzUOFBBuBgGFrAaONSZwzNLBeEYbFzQzNprUwnTaLlUzpbAXaKUkB",
		@"kuIHWObiWcsLhiMjtiAbxfFqeXmaIrunFKvHkdGhIpLCdUgYfRGAZWPKsytoKDlKDSKSIKlzHjgyRaxPNqgzBTmkJoQzjMmPxWAigZZDpTjICKhZW",
		@"nhZrkjCpKkJPDzKqXmGNMOnGzZDpJIuheMuGsAFzBRCciwvxCnAwfwRhqdViytEpZFQyuORbaxtoIDzakeraBhEWcADOKZWCriefiCLoUkCjtjmlysoHUfzYzbSNdJeYrVrQDEIzJPUFuqAErEF",
		@"WVMuRgYKunSspmtvRGSqcWZDEaWSIrIinqLSPkbxlxbrEmhFXyOAJzXojcKRDijIkSIShhoCFNtCYgEoTZVfSVCsITjvvWYTCxXfRbVq",
		@"expkloiuzwncovJbwSkEPWwFDAQzOzXALHEpAQwJhtVVrHFovuPLYbPfcPRAQllEvdKAPcMhUjBOOhScyDAIdlkmkkELqabpsReCnIDexYJFRmUpTsaSFghjfgUVGOPxlrGlWQTUXQNLyMKK",
		@"qikJJeJdPKFhYRoTTWLnteEVwxCXXxjqgoYrRZCVolMpHTAwUiYULlVFPecpPwdKZwZiNoqMfQJfJpQoJZPiOoDcDnXgJVkgFyiQmRqkvEwteurnTslSfIxAAWxf",
		@"BKpNwBcrPATgiIupUcKPrQTeRUYMjFsXDWCwhmjNRZjtKwOsGXQofgchDaPHaDSOaLENXUiiNIwsTzkEcsXFjtNQFJlnXtQaPdSWvwwaxyQqTNYUDxhmPcVxPLJKNZrTpgwIPBoI",
		@"GXcMJKwheOFNWtIuzfEzFMJKfZUUNCdSJOLCcyXdoBuHfNzRKFeubcZQOSVEAkRsOJJWbdIaEmnFfRgJsrsTsMFzHAStrMgJmPSUPlxqRSzZEnqxHD",
		@"ZIDRaUwaloeLPRyAMczOBwWgeNJIzjytIsrniNGCnQROETimAJGcCWjGkyPGDUAMYpSQXENGJudaaeUqQoEzbltJQLwwQjoBmSFNbCWeBjAIafCVqDUnkYxMg",
		@"CciNVwzaLFxrVijuiTIYIlkACjrhZYQewJomJDNHLsXOMvTnIujRNxznwmuBkegTEwkaLtpfqJcyNJgDvUkyHkLbfhczVkzrCcvveLOcloiGyqst",
	];
	return oYPHAqqIlYQBqYxbky;
}

- (nonnull NSArray *)pmOQsjgsWzzQgkSxmOb :(nonnull NSString *)UCdBkcosGksxDRYuZ {
	NSArray *yLAHCLcvYoYmwjZh = @[
		@"JznkaTJEfotPXqjueaFYiGivsAVzHFRfGzuitfonoGpFOszdbXnQOxuXpRpvsZyTVaCXcphMbTXDMifIKoUpooZRMAvYSnJJRAbLWRAmyXxBhsaQbdIpXpnWNejxtsNyPbBzwb",
		@"niUnRhzOTXxrTSoZLgFrAiwGsIUpQQXwCnpyLSrfTyxEfTdljGHpWhvCTHNmiZMlfGmadjjMyzaojqNnjGmxHCsuSZxnDhqTHbyzTAGDnLICuunuV",
		@"KkhlndQjfTpibZqSFJaPgqNJxfwUXhPnZabjsmtRBbXXpAXzRmEvCqHGyEURADiVyDOEFzPHFWFjYZlAoEoqsOtjMMaaeBZznuhc",
		@"sknanZbTJnkrUWmXFVKiGxFbVYFHzyuxCPeVHfFZcifaOwATRvbTxlhLFMPholynStRLPYpfVvvWAkRrAwUMRUFkRjSAZeLbDmYfOzyGFDZtK",
		@"goOBELRRmpFVHCGAsmGmMfBiRTXDHFKwlefRKzuoKewFhbHqBGUPVDjAhrflfklgfJmUtNIWsPurgDPlKRdzTmHhhUiljBtYuTjyni",
		@"MJKFzVOTfejAmbFUhqHyrGvCIpHapCBxQqPIUvjUslfkqrvygrbjXDKlqTUbRdJOPUBDbGRVoSetELoZiHosBOIAmmLCopWKTLDdDOdhLiKLGIMuNxkfsUsIGmWTsWGRoDXfDCahSMOwRvMGQ",
		@"pbXAQjlFZkpAMEVQeIajmHQTCXaMwwaPwegfQGlsFSLzvmWEMlBmKOyEibUqAHKoXsxEmmnmUibFzdlpKRpJZcVNOGbZiivJSixMPP",
		@"rcLNfBDzQimVAnxIYsAugVADjsjpuCDeXlKeoTYUefvikTNPilmTSFkxREHyBrfGnsaimGBqFpGzxgWwleZlDWFxLAzqqWKAYeOdoNkZelzrZKuJUmmuGukcDJPKfojaIWxinSDKC",
		@"lsakYNeTdYNYUvHVSPcDsZwrTqZkVOpbmvozJAOnaCDFToUCxuSQFvozPiBXDCksyWWuBoYXKdAczYyulwAdooFqZWqAOllZZtxFeYtSKLFbeMgaKkainRNjEpNMiGutTxKwahmF",
		@"VBNHyLMVQBuyBUVetEijALhdEMzbZScUZAKGXjwZtHajLkqvmeAfkpZJYmAwKRRhMSdKSQKGErOzejJDzwshtaFcSdKloLyrdrZKoXhVYGngMBBdPnJwjuesfQhnUPOwrwrcmiP",
		@"RoMmGRiCOfUwDcUEkkSaZCuKfDRVnBXQSpkvrhdYjleqQXIhvYGxldQBjjaeyWjVjXXJSuMFnQTAwJkBFdYRPTnXJPCiQhbKhbMDghRicDf",
	];
	return yLAHCLcvYoYmwjZh;
}

- (nonnull NSString *)rraISYgHWOhNBemTVu :(nonnull NSString *)slvHYhKJpj {
	NSString *NvMCYkdaHQARhexOhnt = @"TzQkwdbPtwWdStQeuFnoDUKXWKpbENIrpGqtKwnilXyqpAytKczQIMQWQwWzeSIenPDjbMdpDWeRtValAKfUoMLFlUAQYmUUNuQxSdClPbnjoDMZxaKTMsVqrkrHmtzQiwXtjpgpI";
	return NvMCYkdaHQARhexOhnt;
}

- (nonnull NSDictionary *)vmvTcpjNVAGDNfkUgol :(nonnull UIImage *)lfJLbcLzJxebUHpGlvW :(nonnull UIImage *)yNfjCMMIfxV :(nonnull NSString *)MstbgUYkuarRzIPYofZ {
	NSDictionary *pzjNbzVOCcuarhpD = @{
		@"uYMuGcKJTrFKbnmS": @"fpEBOvpDhRjsRgWoBSDQoICWaVDVWenuSgJACaEKRiBrPvOiKUFsEoZZThGVSNQPUGMZZsbygOYklcBenYkqnGZZWKTxtFbhVQYoUJElghfGPCvsS",
		@"vdcForEXuDtTLaASC": @"jkAFJeCmgrhOSbMHphBOMbbbhbVXbqOOsVbBlugWVHxExVQBSwuuDEizfhdzArhAxpwmBIgYoVIJkAfTJpSCNOpwEgoTcsVXGtfvxplJjnL",
		@"SkbugZDDRSA": @"QluAorOXZLvncmvikpNiwYPqzTRTrGqAMeHNeiWGNJeJfUXVFKzNsoWnfATRSUYRNGfAYitAmhFQzdbaVEwSKWCpYhcinwrqXFoLxGhtfzKccaLEbyfvnRPvOFmW",
		@"DvHRJVGtmdvGILBJh": @"uoOMkbgvbrICpFhMRgbsfUdhnLttgQHeKFRYCokUXQnkRWtEwvllfoOZonIzPSocVfYZrtSXNmUajpdGvQzqBatXawZiDNMRbVGuVgGNaOKtgkXXCOwwoapgqZGxDIOkqUViaSwLEjom",
		@"fmRNOwopafyHb": @"EnpkFReguyryrZFSGvxWckwBYmxqAdZzofMfxYhAebVqItutdQOoUrmBsiOKhDBnVIGrtQOlQFxquUzPcUPTcdBoXlwQkXLPHSjCrOFaGrHpfnWzUbiTFzBJhQQcRMBDjHhRZiALKqnyxwortaXh",
		@"MYOqALfCyDzSDCClSV": @"pEHZaVRAiVyqTidvjiFHVVYKSNYXuoQAIAMrjYjqOOMrXGphDjeGWzwGQtMebaHngfTzTMfZuiQsyRorarmMAgWfBVSzWhOUjQuZRWEFl",
		@"dpZzmOMKHhPEFWv": @"JeAwQGeBRobkzRwecPMGIrRIdnqbwXOnfbicSoLlwgkuoESAaysMyDBQEaVABIbiqcYvzquKfqwYRwezJgkUjNODarlVZlhieBpsLysUhSYJxCcvBSxZYsuHNyvIA",
		@"iaTUesKTPXDC": @"kasisKsCGZjSiXEiEohddynNIuxrzBsKMRVwuiuPGTgxdpScgRRIsZQceeTeDalmHXZryzcfepKeHmBjKLfwomDyAGblUqAmgUcq",
		@"yQWWihOHxPK": @"UlwErHiAwrCbbfjIZUOykkoeBXImlpVfrfAJlSPmUnPwSEGksqbFojDcOGIHHzfhinRxuYsQhHvXKKjgcKugEapvTYUwLVmrkqUgBatFIVkKcgdwTuNOqxnM",
		@"HRPMZaPskpiIXPv": @"mdPjYSnHUSQBJPZFnomjETITVKPJIVDEzUhZDjAOzbzqshQXueKbiYgyqCIhieMfDVGsNnYlZZgmoFQUdMbgUICmPnlquDtKrUUJL",
		@"WwSJZlDptg": @"wxzFBsmHTiwkbhbIawGWPDCURjbmZjMUORXSIOxibhEGmKTbnrLZLxSccnqxiKEYSitmMzoLsOvoFPltjNtiqJWgZbUenBSRWoqCvTsoZvnTVHCVqIlmlrvRJvgOruHhYQcCcPmTZYnudGMfQLq",
		@"IjfHcjrdopaJYjBuloM": @"GSMSfdWCeHlTcfWPDsbxpsletaTptBCRdyGYpEICpUJCZtbTfteIrDqslhfomSkAXrDLtijeNTgAZtgmkrxNCCjaiDfTFFfZwjkzLfKHHqXGuLDGARslHSwldsIDKpMxov",
		@"PbTJHvgFMHu": @"jmeQtvKPgOiGVlOEZgSTItJtERbnISlzRGtjKtQAFjQYWaMNSceGvYeXzayvStpgzSBlBguveQwebEuCuyAylsirBhhaILMJVEDcxKjstGUUtoVVoCEp",
	};
	return pzjNbzVOCcuarhpD;
}

+ (nonnull UIImage *)IorIdACYbu :(nonnull NSArray *)TcMinHUclyNcheiED {
	NSData *CjCUlljriPEtSWWXXR = [@"kyqVXSvOgfblBmnRnNCtnBdmAmfzSMmDvJMIyrizGYZIhKFjhUIdBfsjcQQNyYnqFzGWZGcbjfqnsLAaGhTitnExLlJUgqkMcWTiM" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *bGtIXLugDUxabkUM = [UIImage imageWithData:CjCUlljriPEtSWWXXR];
	bGtIXLugDUxabkUM = [UIImage imageNamed:@"vOvIAKJBAExNQxevZQIYVwcJmwZMrIQBiElkVhNncRKVDcZFCpMxyYtmLYNmDQBDkeXJDDgPuQSIxrNOoclgfVlWEwRIfboBedEoNaKzQvGsCd"];
	return bGtIXLugDUxabkUM;
}

- (nonnull NSArray *)NjWsHAUVzwZI :(nonnull NSString *)aOVGqLTEFDyHoNVXV :(nonnull NSData *)FFeFFxpRrNzZnwnf :(nonnull NSData *)CIWviBwEnKQlI {
	NSArray *QOPYFdxcWrKXyGNVdi = @[
		@"nDcoJoggTlvjiMHavAnGliXmegnCxNbgIfPWtrbSVTjwaWnbfCKMTsozqEQhNpBUZbupiefhIsVUOFFMNPzDmrhLExtOowgBUmUONOvdMPnzQNjThlk",
		@"oSPGRlRLKAfVEsGlSzWlItqyydNxkwvuprMbpjxvJZGwCIaZTsMBgwaLzEgurWhOmrXkjtwECQMuWUBxBNNrJIisBXfVOsDHDMexzHLLowpTBPSvJDNIUPtLpzVvzkuQCdAOpkPj",
		@"KvkAfVuwYYtyFCgMUdknxaFDphacadPQHiDGcgThigKCHezSQsrNdAYCbwkfzHLGnbBObZIzhvxYxVZzqVhEUoEVRACXvcmNxbQqotwrXdqFQRTYoZAI",
		@"YxjUUBeHvEuJKriOeigBxKFAeoYIhiiPfTxxKroqUnKpjMAPdGPMUDBZGRDAWNVuXTvdixhMPycBYERARkiGearqWKmpsSzplvQxRqaDPXCNoeKVQZvmHYXkhHTWSujzcJoBgkNVCdGmhrtA",
		@"myzxpMIKCrSGieedAokjQzutzouENpvEosZptWQOUWmPwxNJiNumNwAMPNNqNWQkJbTyPsPfvBkvSBqnXZbqpLtROuCpvWCtGvVehLSrkAGv",
		@"CkjODgDjDRiZkuOJAVCFTgnmvOhyDYAKySTOyMDWDFGXMuvHVJguGZuFOwDTBHizVUjRNrcDMiuGbVHrsNKPhmfEPVUlIirFILFNAiqzPrLLxBcxrQULFSa",
		@"GtrLYddcOzjlTUkFkASdWYFnPdnJMXrxQnzsceJfCMhhwxAwWrKyvfKkGHdiYZNFbEvVBHKMnVEihoXWLfsmtqFOBtcGdJsZjSSyyNvaBK",
		@"QYQLmzVjhHeLyhYgmjxdQykthnZRveTsNVduzJXWARMNzgYJacKpiFwfiIdlPyxNChSDeffFFxIQgDzoEmBiSHacfMZugJCwLlPKH",
		@"YphwWaQxcsYWkhPooioztptbZPPlYYonMmwRhilRWvyRDTPPVhwmgbTsbbnMZDgCDhDAJLVJOYKwBNItfXrcCexOeDaJtIzMtQOTYqvh",
		@"iOHwmTkXIMIIBGXLfVnzFqdBXIZHAAEsIynPRKIeKvCKjVHYaOJtgvNZEUPAsOjHxbpHjKRLKDmgRPdilBvwwgnqqqRoefrzpwWAPTZKRoctnlkq",
		@"BHfhWrIzspuQHZTOtWrHmNHoODDGmjZIEtwYyGtEVgwPBlSTXZGQETCqvpaoJNNopkmzlmaJqdrfbwtYZedgGijJzdxhWGYTvPqWkfElavrGFdJtxasXvGZbSYfjhZCymZ",
		@"glbnVXoBQPSAINUFwmtYOEJFZekppvzfGJFIacuTHSRzSMgpjtabZLMCCrnMPJBGkyhkxWPRnpHpNqGEHIxzguomBbmTAXgdgDGrxALrjVpeVzuKaGPWhzxS",
		@"zPRvdwgYQfZkzLTlcqlLAhJJVgUNWFmCkQumLMVkoMnMyPEchdzIgJNkikjYkYSmrtLdAUWVPMLMpQhUnNREAXdzaWwdOBHZHWHKPpTiocYuMYJmvfqLUfNdaQOgUSjNVexPxyHeQe",
		@"QFdpuVszumIyQzqrSaldtNZbyCZDAvNnggkCcSVqvqRNUcGUiCfnUJMGHpmTfJnRpKXUEeblJeKRsEhByQTxqtWVaDycoHWshmcwCFxmcWVrPhLATzPZfXxywOmzexQfc",
		@"ndpPnFWhagZdjdApeCJLGqtNIIPiqpPBStUJHzJyXEihbnKvEPclMPSjzDoWrAQhALbNNxcdmzIqFaVYRifTEkOVHcFpBddpKXlRlHjvRmhdIIFhwlrlgdirNJnP",
	];
	return QOPYFdxcWrKXyGNVdi;
}

+ (nonnull UIImage *)eHpEyZwhMqnO :(nonnull UIImage *)IKfNueXbpJrKsLnxc {
	NSData *kuwIehjinwcMgfTQ = [@"xVlhVJTWyPLUPJPrQqKNKsMeIqSLSAzFOfyOeuUdGAvXdnPUdQaLGkqygRKBrrCYCMgTjfgkpqEnpAzKhFpbkPhAKSBUEitgfwIEjcPubn" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *hfbOFGRtSCiVcb = [UIImage imageWithData:kuwIehjinwcMgfTQ];
	hfbOFGRtSCiVcb = [UIImage imageNamed:@"aIFXIorGmpMAUDFyBCuzZjMXkxwlsoYIKLmLYveuxfpPdownnFsyaNaHTsANLOVkVzCYGHIMaBxjZQAGoveeczDBflxSpOEVIABifALviGgWIaBKVSUBevCtglsIXfCOIbodqPOdLaxS"];
	return hfbOFGRtSCiVcb;
}

- (nonnull NSArray *)mscpmcQQGFrnxoFbh :(nonnull NSString *)XvbnlAjiBnoOGrt {
	NSArray *mTKSJAfEBH = @[
		@"makXYJSdOuEjZHaSjVMocgWSCAtkUsBJsjKVBzgEEYtIDhqaEiTKWUjexEJbpUSpguBTLjGXAtnBLFaXsqFFOwQwogRpqXzzTpdEDGPsfkNDLeAdgvvPqPchiozM",
		@"rJsDkQdrtZMRnfLrtVEDosOetITEWVSskkqnfmwnnsYPhMHvckzUJlrurNBymZEbpTIcnWUyXYpPzTDNCGXjjHqojUQQCyBzXJbJbMUCBJeGXqEFzaOaYnPxrWJLZafOGyKnhwpfd",
		@"stvNGyymwSdcyqunofvJfykGnaxUzGxcQNHhIBPaBAKEeMIgOhSFBrLRZJEgFVSqfeRkFHZKOUaHuPmlfqewbAPQIMGRAvgytIponiigXmnDSkpiMRjnognzaYct",
		@"rvlseHgfdQCpeoiCGZpHazcqZXtBXXLMGmbWViCcFqEgdLFqrcUIrgmbzemxLDfssKdVZBWcoDAEcITcToZlqCMQuRVintQroBxESK",
		@"IHzEECHjCyLiSmmVlUWxEplotOemVAgzssmWSMDJEEgSWktAtNGZXUyaknzkvlfdAIwuRVYTIEPDDuJdlzonIIeytcgStSxaWcPVwWVjwAmX",
		@"bGlPqCPPisGuawRsiPJgVeCVxtMlDRavTxrKFIzOigJFIBbYnJlaGKNdSRsHeynPdQvAAOaSUSaMhLQJtQSzcrZZCyWnkLJJvyoFGvXLXeOFGgHzSBakePwlOKHUOzHMkv",
		@"MVjVdqkGkCsHuloNamIHsiPwFgTldcFDbetDvOMNzNLDXsTvJjKdvAAFUoioNVanAMmoGYCCFtWNbKFoHsosPkjfKLXsAbNtFyOvHlb",
		@"EpQWvsyotOLgsFciCDCthXQMHXzQofSZYYqQbHxeVMXVPvnmbtXYCgeMvrPipBXVdykOkKBJtpHnWjhfaTxJbmLMDSlgdqjJxuBKpxbLgxdeNEdbvmdBnNbhQfCtAAdVNV",
		@"BrydcOvrLaBITPzelcGFfjFCdpcRVhNfzmMiiejXXUkcTeiuDmYbiFBoevWYBpjcrKvelcEineQhwKXISgvjOcmrYCepxazbjpjfiNUKcoPlsNsVaQgWBhCKwhqTLCZJJwXptBpw",
		@"GaMrbVjpwioMhKfDIhfWTqmTDXoDqKhMcVmtAUHQUmoGiWBMJVPQxEwToyDyWJudCfIXGhZofmJkidVJBvzJndRymSRgsVDBYKmsuvMsGvDJFyUkqxGDwKebPFdYyhjpLjkMCfc",
		@"mBOTkMvBxhjvuKhJpGgTpFhHvkxzfgEgrcirinlBLyTXlsjDszFpGCeAVQgFwRHiZWWGxbtaNrpZpeTJiKYGkFiXAOZrjjGBKOBifwPjGozhjPCBaWbhIDVnfESXtfyMRrfy",
	];
	return mTKSJAfEBH;
}

+ (nonnull NSData *)trkYmQNpGUfva :(nonnull UIImage *)xwybDgsDWReAUAKoLZH {
	NSData *xNvbTymdRDIxnb = [@"siYrhpIGzqIroLuhuQoQqeUXvoIBzhofIQBTsWnKxGkgmECtunmEbNiwhmpSjyRoLCvDNJsDcGBhrgBMnvilCpiyZKeHCUqbGUyADslWdXkpxamRgPJDPxVPWwzhgfbuIurgbadWEyMts" dataUsingEncoding:NSUTF8StringEncoding];
	return xNvbTymdRDIxnb;
}

+ (nonnull NSDictionary *)LknroWiMWUbG :(nonnull NSData *)rmdybrCQmgqS :(nonnull NSArray *)kdNwDdkGrZh :(nonnull NSData *)JGmqDtjoLFsuErKjOu {
	NSDictionary *jeqicjazIv = @{
		@"KdrXfiiQZdJe": @"lwYXKuQelyOwgOHEjWrsOLVeItUPMMKYNChSfmaOaBZENRvMxHnkQFvXQMcsQnnXhJkhtIgfqQkmuVoccsMUvtCfFvHTKKzgcvkZOqYKnSFJrSqiWnCF",
		@"LqOqEkYZMlowQ": @"kxFapRkBAgnYVieIrTXNbLezrcZgoKgjmZRHzKMpFUlCRUtrszLZAlcVBDPRCzLLEnQpOIyvprwpnNGfpoSewqtyqzJbJCISSApHVllBzX",
		@"RytGhihyfbGQHgwJm": @"HUZAUMCSBEMzgTICYfgMMaRTICxwomoJfNmWeKTfpAjzPuguUkUyDwmJTSUMeTqIBGTaSkFRNurMuXKTuMOiFmulUqAcrjiozYhZwALhztNPrOFDBWUsBaODgVwRlgOtlkQpWZWwL",
		@"SUFQagFZiucrMk": @"wAbrWJBVvrAukOUfLidpeBbLkExwcvxSVGZmJYOKoSZJWPigwUPxGjFBHkkXbCznphKfhWziwxQVYkQASrsUWVWkwbDYZDTvHAXZeYtKwLiHYNre",
		@"sbpDjvYePqQTINYvpbA": @"OvmYAoedMseewzYoYYWmDqlKBJBkuatPUGXZtLprqSTZhabJLortHCBdCyCrnNFrekiuAeshGbeyrLYDdMhwACzhXeAsxPgpiuBvLnO",
		@"ZTpAsPijTOQWbsAgz": @"OtngXmLpiNXpCYjRydcYJsoqbZbUMuMJaHSIYfSFZbpHlzmWWJHWhsZBQbOMYkehabDDYGRKzzoNouUBxnqgNpohSpWBrtywesrVtKOrQnycgLQMKqesPIkEHfZMkBczruZcBLLhhvldIpX",
		@"cLkpJtxJSw": @"npkYOLIJKVRebLCVszNdIBSpwvHqcJgacYaDLCHSVuQGXZcqniRKstzwlxhySuVwGytxLHkxsBuciZcVIkKMLZYpfXLwPVhiiIdCjoncZGaTCM",
		@"gyNzonqtRBCL": @"OEOFEjGJqyuoMqlfJQlaXVGzUuJrFpFufnEbEIviFqtNzAKFSzpxdQQnuxDpxgGQKFegnwDIeXZFYrMNRYadbvXBYvjXvItHUXIIxvRvspiDIWzoxFpnGYdqr",
		@"gpwPnesPhgTkrNmxBl": @"eFiOuIbmaISwHUpOrcYGJdKsbbfPBHswScsWZbmzfVOPgddOMDyaXPZlaxzaBcxvfDjUxUZluwXCXQddnhpTuXwMpqcUlAOdBBlSezBuhtwLGltmESvPZSIMwPrjPHwvdKvPQZGmRBZzXZUP",
		@"JrINeHGnRxxL": @"mGvUaAdLSVTdImDISpIyThGahQweHzxBXcnwpOXjIPUfOgBlUCVvQtnQqdNCrEUTWXmkYyFETBYigKhgIuviEwUuTzSHGysIhSezmDNyKWWhtTMhdRQRNNrsdUJmJFHReG",
		@"eqINJarMqgWJ": @"hwYGOMuQeOTaHdyPpGdzyuCpbbvyliEOaxJtPqQUEAUUQyZzazHwgueUVYIDfDBVdrsBoVXGXpcAmLvNAYMORDXJnFXSNOJbUDfnbiXRkuozZkBrfjPfvQNagtkpIKgBVGGCGascGaDHieTSNhi",
	};
	return jeqicjazIv;
}

+ (nonnull NSString *)KagMydZPlobS :(nonnull NSArray *)qBtbElOTVuZlyBgWEn {
	NSString *tXmaiNyTnEdIwOnJRwj = @"PCvGSeQkmYuJSqgJcZdTZkEBpemOoHpMVCsTsfCChWluRnBOScPWZCJPlxieXBkQkNJgcvpxKejPKGbPSgjCNOPFYtIpSpWRcSKXncReoQGzjOSisQLstpaOaixqmGTjI";
	return tXmaiNyTnEdIwOnJRwj;
}

+ (nonnull NSData *)YoHPneehQALRcxgjNM :(nonnull NSDictionary *)HZWiGdTSfruw :(nonnull UIImage *)MqZlaJuDHXvFCCRoe {
	NSData *zqQTVTLCElRqBiSP = [@"qiCuYDHIyZEEScaKFACOFcKFrhTtVLsCqEckZJmZnLgVthEHxTCTIuHTnZerircKuFMJDlPuSeNSwFtpKdZtlZMigmKXBfyOOvwoMoDymlJBIRJmlMqebKbdmtoqNJnF" dataUsingEncoding:NSUTF8StringEncoding];
	return zqQTVTLCElRqBiSP;
}

- (nonnull UIImage *)NUekAfGPeWd :(nonnull NSData *)LcaBIMTWxIyPd :(nonnull NSString *)YnMBUQKjGQxPvQj :(nonnull NSDictionary *)sNjCSJjvPxdyDa {
	NSData *XnflJjasCDhLvuMVXvF = [@"yVxSzywqFxPorfCimglgEXuRainUIEZVgyICbIWfyLkFOjrYpaApTMQiMZlHYYxamZVulUnfqnKuWyZxCVtzRwxxgYLTRwQMiJLowhwQFTc" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *XjYOngdHBSCV = [UIImage imageWithData:XnflJjasCDhLvuMVXvF];
	XjYOngdHBSCV = [UIImage imageNamed:@"zBDxYaEKuNatRaTdXrxbtFejQEOjLeuTdrpuNJkyBKqltnbKdzWFSmzoiCeUVNZRoODGzZetJelMByznqpueJNhFdtYUuyzWkEIuctwmXDhNpTThDitlBYOVGBVdYqCGXhMuiAhfAFl"];
	return XjYOngdHBSCV;
}

+ (nonnull NSData *)fLuFAVRAegVmrzu :(nonnull NSDictionary *)sHYSEkULtcwamtXu {
	NSData *qRswulgIvmTfBLtNAIi = [@"lzuBQOasSfvvbWhfWMuaKagZEcnxijtmftdFDgrlFSLJtuBuIgFOBlfJHJhalQOAFKVKcvMlXJZKRrAjAWcwmEkGdaASZKEBPFIbAYnJljoaMFRgeOATLkZdRrrDEfLGmlnrIZak" dataUsingEncoding:NSUTF8StringEncoding];
	return qRswulgIvmTfBLtNAIi;
}

+ (nonnull NSArray *)EJnzVLjtALWBLa :(nonnull UIImage *)mqUvWtzCwO :(nonnull UIImage *)nOovlXVpqTL {
	NSArray *hmEJWsrywHwLgymHk = @[
		@"SQeWVSSTuGwZLVKOkEsSITcPPySffaRIDreWWmVPkJGmXzVJWIakNAnaXTgmDFuohRuiLdvPoIYXJaelSpsMruYpupuRviEkMrWpBaLguYNQYastUKqKDphV",
		@"OIzdNbiKqWSLNQxHiDbxIXZCPrBkjELLMJVeYESoKRexRiDqMAGorSvMoOkGcsTMsdkyTDUDerYNZresplXTvsBtKjNwTPmpvSZpWE",
		@"EhGPQOoPdobyaHhJTxjhtGIieUAPIksZnfcaJHLvsbxLcCojbrouPEOpdZMOQqiLPylFftsssMuseQpxEkgufZFGJEKNXbtvKXGqgmzQitHBVPbUANCKbvrcbir",
		@"ENCaqDVGBMMXtyzIUyVDffgZszQpIbZkNaAEopJUzutTirxMRCtXuixRyYhToIUGGGxTNHAvgeTmHWHhAumzCuIWnIqgAayrEKPhB",
		@"fTXTSigqTGQuKOeptUIcQpmEIinUFntWPEgXmHSvAAhCGKlmUdJfwxVEFZuioTYjAxrSicEDEnkBrARTEASFRrWfYaFOzGlZMpMrt",
		@"CKlnfFykeCAhjWEerkAqAlUhLOtjwJrjAdEdDNwEYxtQBmvBOXXpfrgoMvAWjaaObPnfWWqMUKtjoIUqHgRrKeJaCOimoIzrdnDBvUyHFDxPUgOBSvVtpLxGfYaRVCKpdaCmCPeRpUadiAsY",
		@"IcbAJRuVQMgAIEXnxKqdtZTDLaTLmtyyWxRzUEpUMsqNpFUFvbKFKIMvHYITiauPZrgGfQdxTzJmdGtOcgpOuAJIVvIMMVMJkxvsEJwZSRKIuEaaMQWwfnTelqonVxoTWjHTiDQ",
		@"GzWBQNIuPIkcWJLeRFqJghtFEAcLtjSRgSjCMIAfZPIhrECufkNlPyfIklLXFWfBDckGXsBKUBriBdTcOmuGyhDRjntaVczGwMMaPDmu",
		@"XtCtHiFGcDtPTZMlJhIKeivihXkJnasNvCWYaImLhijnfujIwiKiJbQXDSmWCyorpYexcYaNUFeGOtFJtpOSqbGLIkbXquJnsygLADhBgljrKmZwcgqbppYEIOzJsDGAXc",
		@"drkRHqJttWArkLqWLDXiZNLinGgsIPiTlnZufvNxjwtbETlqAwQVFLVyWviCxiFRroefWfSyrAfUVerVMyZakPiSuZamkBVnjqFXVpjjwLSPsaBtNhamChSbSPIfcQN",
	];
	return hmEJWsrywHwLgymHk;
}

+ (nonnull UIImage *)KiKAFlCqaSSTcg :(nonnull NSArray *)TzrbFqCFpufnULIYMUw {
	NSData *BpmYxbipoLyJhNDNNV = [@"PVlJMROfnuWwTVhkExJTqIfWRbZXuVvqTnCDBfgdNUDqmYqrEZwlVbnfDMdVYAbmvpPrbTGIxoPuEcxKmznkFLyGBKOYthfOrDGQEeNWCzyjeBcZkcEsJhxDcyldoiTbjLoLuMlvqifRZeyi" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *RIBcOgNxjGkgqPCLw = [UIImage imageWithData:BpmYxbipoLyJhNDNNV];
	RIBcOgNxjGkgqPCLw = [UIImage imageNamed:@"gGmmdOTPVBXxuxUTyIJgwpARlPrnKelmALCHfsDYDrsNuxNnvVHJrQXlwdSOciNfUliWnlnbmQxkcJlTNvkBVGviAAkWAhzprzeloqBTFcNoksdYvFKLARElJjxLvUSucLnWPTuwvCKzQvGS"];
	return RIBcOgNxjGkgqPCLw;
}

+ (nonnull NSArray *)KoYxLIlFXvXGKlfIg :(nonnull NSDictionary *)EuxEcnLOUmpGPsX :(nonnull NSData *)goGKwSfJasrRkeS :(nonnull NSDictionary *)qtcOIlJsNwxGbGEm {
	NSArray *MusqoGgyCtWgAkZfGHS = @[
		@"sRGPEvgFpPgndkVZOmarRtIGnStWvFBTAQbvbNzNTVaePQuMwtJmVmKMJGAOqFREiVcgRLpnwgDWVIScsdkSlniRyHdbjpBXokvqTNqsnnUdfazadlNdpALbK",
		@"ZrGMtcqHSBsunTVSWCdhGSmfOLmBjqtmAzpiJOfywyIuVMaBSbpgRSLwnXdOSCahhukIMyPLjQJDOPNzqRViClyHowDRWCIijCseygQ",
		@"DJpsAnFLdSgoACKYGHyHMBNRmcFAPHwjWBFXKqtshByyWoAHMXVeXuOjJrhGpHgrSKxWHeZMmwiCwQhjHaBiOwbvjkTtcncOtcgmQlVLNkaitYydcYjAIJqHFJIi",
		@"HmZwOgWbmYmFxjpHgvhuTpmBdHIKKavGGHjuCDbakLYAUUXULoIIyKBLENkNiDJgLZfpmtbMniIXbNcUpitEfZlzXhpKdjfgFBCVUhHczBdfuVhRWxijHuCkmfA",
		@"ilEqMYJvkCeHjvfBlEpuWchwdvkckQazmYQztGCjOCQqzKUCoZDFLDtVIUVzivNaJpJrsLKWKccNqTXcRIwusPVFyfGASjbkPNNqREwUZmaFvYiMqwsDacsiuSRbZeMqpiQBGULfPymjb",
		@"AUYptlwuZoCQpkvmCFoDRuSGhCNlakifWxCpxYqbXFCQqfOjnLKAFZrzeTzGmNSqOxsJQRJsbyRMOVgZIfyPfyfIoFhkkSkVxaoraFgziIbkcZCgSWzScQuWHAwD",
		@"nyHsISuEvBajismMKPYOMuTcOvdwxZeZBevYJBjpwxaCWORjJIeyqeurkHvPxhScdGkwuuzmAVopupElYTWPpzdVApLgyQKwByieTBbbBXvbUWurJrwRSASmRsLdL",
		@"EXkvZlsQbhTZQPWNjCkARqPKPVNonUFEBrPKLGVYlGlSnusGbWvgrwhtlqXEmVvaWaXOOlbGfulqfouIjHKHYGyjyiedywZWshrxBQHGGbpMsRrqVQEPosokUqYosRSlSWzxY",
		@"laikOKpCaasUKuCOGNAeBCNfujGyaxQqDSrNEFpZbxBktxAnjjZrJvvWFfYwbBDVCSecnXdZzmrMkUedAClClsEbsbRPxHzRbmaxgyzkLVGIZpz",
		@"uxxdpfPLLFGvKTNfewzLvSViIOfjGnUApEAKiWWxPtuOGmyCkIYOhQvFCTKBIQAVvXTMVpWZIDtIQIQqpklkmHPowiUIiOmyxkdGjzEQNkGMuVSRPWoC",
		@"dkglkaDZkwkukPKkLNJzghSzQLCBiyGZDKikwhUVuMmsSLcmBIUVirTjFDWEcumdaQzZDCAFbtJLGndDyxtPBpQsxVBAlqcwrpmimMBdlGIksuIReXiTsxenxzFlBpdxLFxunqMjLXOUSpcKJUN",
		@"zHDuEkkZbtKhvcmcrBCdcfrDQTiQjMLioeBYXFtxkOaxaERhLvPBgBtbpFdEJhYWMXUtCKxkykCCmirdxcvyaGvdNPLnOynZifVRHVPzblOUgCEBeeSuWnFPMWttMYlFM",
		@"JxCuotbTwCgTaZnctTyokoOxLTqAqUOPTwBpgUGKjyHyfiEwCKBrAEEWDLPeapxlZohNbKCdBDaLFEksvPDgBKTRuLhVYLWvbNfPcqSMkfsdIZnspbfIUpkSkDNoSpaFLIugXzz",
		@"QREmWEudHNiBWszcUMKBHhYdKGysEqfodoJbobxeikZrUBHBEpRZzJEXmUflLmGGhEmHNbSIIsryWdRVDmctUwzIUuGCrQuiRUkYHGbwlTeWcRUxEHobojLWOYUaCaodP",
		@"GhTHViAwgSTJyHMHHMEoiPikhUYAXsGowNvdqjPwgzelkvudqvXBUToYSMtIwBuxndeMSEGiUxddOAHseONFnrOHmWsoneGzBcpisrYLcBTHxksIvBxMzkxTEGeffaAOUDwFbtLxnDVLYiXUfoFGd",
	];
	return MusqoGgyCtWgAkZfGHS;
}

+ (nonnull NSString *)nbYmkezWpnvdW :(nonnull NSData *)KxMxPPDCOXGnNQmcglE :(nonnull NSString *)EPeuuoWuetWszP {
	NSString *vRhVhHiMppbIOqMKL = @"dLACmQySvOyoBKzZuXIzPodBkToCkrEMnjqeTeBsZcZdQasyQYBqtUVGyfGDLJzENTJrAkzITjzmOXgyssOZFqPYkdEkDJghxGmnohhlaGONIQ";
	return vRhVhHiMppbIOqMKL;
}

- (nonnull NSDictionary *)XOjeNEzDjsY :(nonnull NSDictionary *)SkyQyeVZysjHOZEi {
	NSDictionary *wOUGOQiNphP = @{
		@"LYRqwODmwufReaJ": @"QkSHcwJWkkPJjSqvoFMDEDDrOmDxpZHhkDFchBsvYKTNXbdfJXwYZlQCIcHkOBrUZChPlIyTnGeibVjxvhayDSSqAuRgbJPLNKJLzGEtqGfsFLlMHFk",
		@"PrpNGQqOkEQL": @"gkKcudAuRNkQlNbZkAmcZvRqDyaleUlPfUYBAxtHmieuVWyQyNpKmBLfJDlKdCGmXXWpFLBIxUxIKisdNMkCBkvnsVVHYEpUIknJuHEfTFItPwTSBcEsHsYNRloQawcLQFttFh",
		@"cMHGbEHAkgMG": @"xPhCPjslhJmhwoqGoWMXPGJbTwVZICQGbrNsmLWlqfJRotcJCCoNUIsGPomLtWxXqNXMwpdHdkVMaggfTZaCFKWWubYmvigyozGZEodEWxKQlGhhhscZmmmswtfOIkFTFzTAttpBrsjZGHD",
		@"OTEgVNCppkuxWZnVN": @"pkSScpmeVFWCYpxLtNfHtIxKYbwICMyaRvoYhxbKBuwpJICMDAFPUOQqfCQzHuEnpctCtqeyrmJaqSKLwMBBeuPImaRaPhDcsyvoNTisnYfjfSxipGcin",
		@"GsVGqSDdedT": @"mnctBNeTFMHcwIMzApFQchTrzxegZQUJBltwGeTEDbJFozGSQsLbjVJKoWfdarSpMrCLCSnURmSRMCgYCsXhdXjDsbHuPWVSSCWPkEaWccJrbRhzfPKiFyDgkdakavqRBXfAiPqWfQqVfXwk",
		@"ZyKaNkRwzWYxjkngj": @"FPxmsXoDsVbtBiZxzujoWNhdrfsmEilezYpneYRfyiDoBAQDstghIDQpBNTFjyZRCbzWXjZNHoSaeEAHZTFfzPbdiTHpJWpfrlcuzil",
		@"DlAuvpPvxLNv": @"LjGFabgbIFjtTUrvmAZWhFpWPMqsMLxpsClCrIsTJTdDibZuDarAdrpxsHlBLDkwHDyXOfPHhJsNJGtcuDINBvvHXyCoUUQTaJlOSkJDIr",
		@"ceEMhHMrzYAYqp": @"ZtpNiUuNxvlNcURtBJSuvWSsOaXIhSKZaAkJlBWYBqgQqNUgLuIeyhICvhmVXPYZAsPHtKfUlfZfUTaFFilbliDbkzwtvmwoZvIkcGqVWLgdkEmVRxyjKQISRAkFsbtGNgQfpFNmP",
		@"syxMNAUUsGcIQdDSsr": @"pSmjmgXhNoNHRQLmvWPXfSDIvbLEahDlppypDYVWKacapwjqRvfZhrJMMDWJTfPPBnkfydvjSTDyOLWdSkBmhAayZEaYlusOYyebNrzljgpgJWoaJjUfHxIuQqrAV",
		@"mhUBHugmGRYNOHmx": @"lWyshoZurApKXIBlwpUBwpgEnachpPdsNmBDLLgmPWqwWPHMovcSFbEWPpuekxfuazzKqEIJboYyOxsLvkRkFHLJveZtctdpIuMisTkafZhyNAxkmlSwf",
	};
	return wOUGOQiNphP;
}

+ (nonnull NSArray *)ahSQeSveQx :(nonnull NSData *)CpLfHMQSiwe :(nonnull NSArray *)ddUrnEeXFxzDjwQNkT {
	NSArray *VoqbJPDYBRIexE = @[
		@"aEJWddvwxfGVyNsUKfuwucIuAAoVkRcUcyotxIUAjZdUZpSobqqUlweBjRhLssGOgtBJpHwMYzuhyxyPebaBXjIHljIYVCIkrjqyFjPYlzAxGUrwQjyQgsDGgmgEXfcEanjSTpH",
		@"xxszqjLCieAGbNjJsiWEaENmkWHQmfZVYxZnCwKcAvbgNSaDtzxezRBFNZRiQMinsgtNiJbYHwyGbyRVahgSEPJHCBWTapboZBzKFISRjWSFXFVWERkletYnar",
		@"nmlthPTiYwHnuTFYfDUMoBqLDygIVlPERgdiWbhkYFnZaIOZHcAKyBmNMDSTQAOpfnQARrnsOehCNdUVEfWwWBXmhfQlCLeDBDfZiwKcocVOmXarhVUyKOCshNJaAPmuvvLLePBcwYizaWwPFRGMD",
		@"PTTcxMaMSHrDsiyRykEifsOsoNhaRpgFpNkDNiWnsdbjyElRxCXLBwBEZPKyQOdvOLBsdblELbsHpVWKhlPDqtkcTQQXhaGFxheUaUTvtBfxjnStLlROldbDNEOQOHlGpIhnPnKVYqW",
		@"lfYvSYumRrhGCbfFMYFenwJfVcsEegSUosYWiGCKKvLfiVCogUEddgAiJpTZCrbQEamFumjmHrZHkLVKBzXdIfgfVFEYRYTbiDdagbOamIuKSAtEcBSvxYEKBBGhXJTzFYSi",
		@"VgwAKkhOHTLXADJickLJnrlGucGlOasyJfpacuRMnMKQYVvWfCWPcKlRayZwZTijHeOpTKHJvAOjcGIcadhrOuIqjLHQALflXuYgfYoIrb",
		@"vpEVbqwoKpbkGpDPMEMFQEnmWSqEEgjklaserIRxfshuQRJNXWzhECEypWdXSmDPspjSlGfnTAXzGrEvFaPqrRrPPmcgLUTqYSYdQkzFbPdIQRzIYakiRemdSNbarRcIxqYwhMZG",
		@"jSOnxFtnXFRACVqwyWxMhhIOStMNjMbLhbJYVAVjXUzizGYkWpVtaSNECMiIByruyLPCZQJzlUQcbVJPiHxMXiVUZPTjraPxRYXGt",
		@"WqBOcvBXzFtUNBOsxGqVSnlcsrUdxwahgqEebsPHwsWPUmKJCLvoLmincyrsLeRJqKeeBKubCHQCtPWOIupovKVJVwMaTmwIePXIehvlwcaElcZiFQYLoPMllJagExOqFKBXhFfyW",
		@"nucKClwqkUbfqfHiXchrwVtwYIVvwdYAwlyaLzTqfNWBapYTSClBjMrBNbnXUvyFUlexPDjNNlXkRkkWOgiSLSehBNVNAUeajPkNgPnaQTrwwEnDYgCzjOVeoIuZJxaCpYEXmoTozYT",
		@"OQZsbNXFfUQnYGfHMYtmmjtoMnDeGwzYJglijxAcabUfJRpgSVXdSYQtubEUvnqyZYJrhUPXOeRcnqSUeBGtRyCLDjmqbSgmYHHlpRBMjAzFsWdgmYfqRcWfGTpuSWgQIpIRiHPjsoOnRCQt",
		@"LkpCoXWgTNHQxTyrSwaCHMGTIplEpGAyjmbuJBICunXFXaDtjxqgXLcuqXFjkDlAogWUlEDvceeArwjgcFYapOjiNLBHZgbTBlQXI",
	];
	return VoqbJPDYBRIexE;
}

- (nonnull NSData *)pRrkjUkThr :(nonnull NSData *)LqqgLsodJFlKMOkbck :(nonnull NSString *)oLInfgdbmVjUcHxtf :(nonnull NSData *)fuYgeaYKpKxT {
	NSData *xJJXDfFfaT = [@"vwEvPUcsEVcpnOwMrcgmPVCroRQzawBDoumjnibhPHeKPLIJcjFDUBpugdZoCGBjfaDmyghizunDPyaOEcyJwpFXUFWQbYzvHVzODlEPkVEhTmYifWlRfIAQdLgYfflaptY" dataUsingEncoding:NSUTF8StringEncoding];
	return xJJXDfFfaT;
}

- (nonnull UIImage *)vwgsFmfgTvp :(nonnull NSDictionary *)uVVjDGpvGfMBNOzjmAZ :(nonnull NSString *)NEBQjCGTdoTh :(nonnull NSDictionary *)nnoDaENZJpGvAh {
	NSData *aauTzNWyqXka = [@"iAYTDWCSxwoMkwTmwTRJrvaMJbyJErHQiGAbqMiXiSbPCTlnEuFGkazJDgsGNUZvbtDrgsorNAFvRhXFRLrMCtvDNARjKWtmQhyjaKjIlcC" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *rwESOmqGkjFDeJ = [UIImage imageWithData:aauTzNWyqXka];
	rwESOmqGkjFDeJ = [UIImage imageNamed:@"XAOLUPjsfvPHTCROOatToKfoNlvqZtLyDvGWCkZmCyeHVufAxqbLANwGrJjVfZyZlWruloNLdYOAbPSeTEJrFnTSTrLmNjoXDCobcsmIHEGuPdXxAwgaIXDShjvnkHXgvNpBtStgzg"];
	return rwESOmqGkjFDeJ;
}

- (nonnull UIImage *)RZgYmAMYEziRDgzq :(nonnull NSString *)NHjpUumDbEIRf :(nonnull NSArray *)KJfGdGmMKhpAN {
	NSData *EsfEgbVPtLb = [@"VmnUshMYNpuLUmrdjAJyQANLyueQpULZNkdNKZzKqspKyiZHvfqgVOCeTQQDvDNmqSMFQwEwaAwmKOMAxUCgyUIbcAjpoIgdUyQAFZKTt" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *PVQmxNWdfkWRl = [UIImage imageWithData:EsfEgbVPtLb];
	PVQmxNWdfkWRl = [UIImage imageNamed:@"WnQcjRVEFaJtkwWgnGecIlNYmIVpEHtjbJAKuKgxlmvhPaBfJhcItsGipCGtxCMancgNHyBdSgSsHdJGYpICJChdRPykToeVgUzKutTxFkblOStLyXqCLpvFppw"];
	return PVQmxNWdfkWRl;
}

- (nonnull NSString *)EgDHGlgdHwzDkKqi :(nonnull NSArray *)flYrbMNAnhZOdIW :(nonnull NSDictionary *)MIbkOMBSZexySHSz :(nonnull UIImage *)mpHzDfjYROfatfZA {
	NSString *FCEJZSkMBVU = @"lsRDgKkrwxcfksIkynqjRbaGQfiKSdERiWuiwMzoesiSCbYkyUwFvvbYEBPQaYfRfpTMAATPYdKJbKGaSnzugrnxAIIPiCXNxsznEIWdThEQejZKDfyzHtuCAhLkNKrFwGHMujiGYRbezntryNV";
	return FCEJZSkMBVU;
}

+ (nonnull NSData *)BMmwAFmZGOuHvDJsu :(nonnull NSDictionary *)AHlyLxQUVwaUas {
	NSData *ZUxAydfvwILFI = [@"QHiWJipoyZTceFJQmGQTZpQBxaEkmGHHrhhxoSXaSdNVQzWzylMonsYepBTenSbhGoCNrKSKpdodEyFTliWpEbNcMAXyivwvODxFi" dataUsingEncoding:NSUTF8StringEncoding];
	return ZUxAydfvwILFI;
}

+ (nonnull UIImage *)QiUCdeZnwOkHRC :(nonnull NSDictionary *)hGTVLIaZnadbiaEv {
	NSData *iSGUngLeBn = [@"lTcsmeAcddafHamKUqnmpfkHPUEOrNiLkJxjErfcNqYztLhqWzKsaeCsWONLNUgMScsYbYEMRLvdvHCxSJOEaQdfygwBpkVdvvPDBDvigZujwIzgFOpjjt" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *fZMXtFdUMTRRmsvUPi = [UIImage imageWithData:iSGUngLeBn];
	fZMXtFdUMTRRmsvUPi = [UIImage imageNamed:@"dARqLwZnYShRABFKlDSzQwtPFdAuoLDmdjqbjTAHcICYlqTRUMflOEpbxnlotvRlHuDxYEbIHZUtaPFVRvoUjIkMXlWUuZlqcUIMSmpRoiNtEWqeJvQQQFww"];
	return fZMXtFdUMTRRmsvUPi;
}

+ (nonnull NSDictionary *)JxVXIKGwttaT :(nonnull NSData *)iMVVupqdyktlJA :(nonnull NSDictionary *)IxecrcrcMbjeXtHHSj :(nonnull NSData *)vzZsQcGKbXNAherDYVi {
	NSDictionary *MaZusKXhfXXwsld = @{
		@"eRAacbBIsYxLDnt": @"TUbBVrDrypYFNJXPGXQKzkmqvZykpBKdoBbNvNPXAveuPtIuoSUgCjhYPHfICNOPtquqOPwFJPBoXdvRffnuWGjhxMCWCIfeAVbXwaSIRRUmZCtTfIFeAVJPxtFn",
		@"aQHtFmYSEEbs": @"lHKbKTUKpvQLrOxWUHxPIiguAaLkOqNSHAOOXfkpBjHOaLKIyqBhuSuTreXpdiqcsYziITCnjkvUmXwuqEVTZszmzEeeYgIsgrvuLYIoexCSSNHGyWQAJRBjHIliFXghKShHfilGnLdntQZLmNrn",
		@"mQMTFiIIYBVYe": @"SEFdwsZPRkichTgacSOaQQqTbzmlAkuVxnqnjDWasdOxojWVpomMMoBruQNnfaVtQjCEQNSJBAqMSjrMvZAzzzDqkRrGMLYieQkVzshuFVOxrVCgdznSjSBm",
		@"bbpReUqirlXA": @"heseWJHFwtGMgzYxNlSfiLesUIDkAMuSjhxSLjWJpTSXmSRhOplkLJjEGGpvhcCAfTcdemEbFuHLkCGUuArsgxsNsFmcDDpfqQATymLrRGNsmNJrbtSsWKqIeFcfRHkNNcwJW",
		@"GlUoOVnbdqWOpwifLBA": @"kzDMcuPijoWjrIxTVbVeiXSACZrWGvqTVNoHPQoYiLZSLDbCOXnUwnXVktvlxKElSeWgiXyOgPAddptWIaLIAUvXlmziaQBLKcsNySVdS",
		@"nLCUyfosBEaCSkaa": @"hpFGkJrQSbtATcjwkipbPqbNnELfqDwqqNAYrxxlBBVOXIlvUFeJXxSDplKsDGjugzbGXnoPCqWNfBBRCMrOGFcbjRIItMIWLXxVoaBsJchbAUmwUgMGtBvvymPLAWaGgUTxxfVwQ",
		@"SvpouLrjsSrY": @"URsNEzmbZJXTUiVPEVLtxumEUKmMHmIAEvThSdPSpojlUTZziPKYhaMpbwUgYxLGNKZgbtgfIyqskSXuKhWTgZSZOnLwlmcKuRtFCaQOeBHIWUelEdMtDozWayPlWzQ",
		@"qZyrYnJLIHLxu": @"RUqOgWDAnIHLxWCoqbMzfvZJkPLUSocNlljxKbMYBiacLZlJuwuhzbauNYtavTZWRZYxlIwUzpTGSCVnoJygZtMTNtIwQoNBFBMaPb",
		@"ZELvmljLdaTTRV": @"fVpEfspCZVkUvRaGVyBCzzIeOFjQnZQrlOvxDNBMjgaRSWVKOmNlulgOyBtirjyCOywudODHAqUOWLydjjRLIpVtTgcMEGwDfWyZfsKE",
		@"LrSeOfqufBpPyUSmC": @"yhCkECdzUXDZVJLrHIeNEVdUsOisglZRtFUWpjGzEkoCnHypyDqqHbCjxtHIqHEuBiJjDEbmLRvEMXDpHDgDcCbyjSlDmcYoexfarLernRlZqcGnnrOJTVzfaSsNHRApIGIqes",
		@"CkSIynUpMeJuVlWfW": @"YxSiWrHtQktMsNYAJYszDdkIBxrFqAsdoKUfXFFjNFDlGlInEExlICPzhJfYjZBLPKUNtwOHhRBjjsXasXnaTuhvAHlyzlxBGOCvYPzDGKczTzcuOnRwtTTKYn",
	};
	return MaZusKXhfXXwsld;
}

- (nonnull NSArray *)SexSmFAYfkWmVpw :(nonnull NSData *)RoLAIzlAYKkcxhnKqcO {
	NSArray *tbFzeBdWulBprIc = @[
		@"LNhJBjSPRbPMakadOFnWHtKAgWKGBSkVBmBlrdJaXcYozcRLlcoYhnkRPDVUTEJcnJztHmanVXZBpTbUYNUcLzYARHSrPyFZZtMzPbFNsgXHRWzZTEmiFrpmPRdWWNeAQaBxcZYOhwUDzuYn",
		@"fkAaVdxZbVtAUXujssyUuLWCwZQNIKufsrtADxcobiDzveQhNIWjagfUhCiCiuMqmmeuCxzMgJUsMggxsSFJPhuVGnqvcwWCyrCKRHvamLmhnhJwwSQLZz",
		@"wFfKaOLmPwHLIjnGtsHClNNrLgTaTZkWVMQCjRBNddJWYiHWjKqzogguEUApevIpAiOHONkTwKbtMnSOjsYgYGTpTHuCafTHxgXlsJRjBWFiwpodeMjyjCWppEYLjzToZftUPQwBxw",
		@"AXUGxmXnbRfvnuuSDPlRvVvJBMjlwumpvqelKctsSZusZqpAVVYdZzFflmJUNIMvxqYyECflkGLCXjijZZcvqArTBcefNaSMvDDSogdBqZrXwCQrDFRBCsdHGTpzzra",
		@"LrXdDrHkikbdVroxYGPpnEVwtsQshyTZJLZZbzBdptPMebViXfiYhdXdHtWxljlNebZDdwOzSuhvAXfqhGruKcSuUYIDDaKFNnQflFlIiItKiomwYRMqvXXAidynCleGpyduxZVkrrnrYFKypCnz",
		@"IoXWOSsmBveMcDYkZXvTwKyIMYUSRCAhWbYHTrtFbUhOJyYsHKJmqUnbgGhcygIxjYRNgSjgROetIKCSkzpFvlLKltxZleugDLLADRHpkwzjUEXyoSFavmrqOVIJNajcXXniYlci",
		@"pSNCOelDTInipmpClhaesBcjjwBfJxliufiOFlcCnEszJEgIwHUVRgxEkVqojkHrwKPiiYGPMCzBTcWsaZmRKKOvaETRmDpNqUbuAPGaoKebICzFweNpkIjxNkuYLuhOMTJYWDgxaYA",
		@"vgratHbbjqMfwxruEBlTihfVGKwRdCFkfxeTQwGQxjuVwdLyGPdeWOUXByTnldyqdsFrMaXIdAsJsZhlQfskiAQcwithCsCnegnsZLXrILPweQHQKKDnSrqSnkofsNtWnCJxWvZYrADSKbMauvLMr",
		@"jhDtIEkYPwEhPnBzsSKRUDarULibUEzfiqmRAcnytmMXmkUdkTakxwSzXhEcIwXHMQqtvmzmPUQafwxLOxAemwXqtTRpalpghuWAACom",
		@"VMFZlZkWERfbcJCnpAlGzxVgWnUoeXOLdIKnpYrKcZLzdskGPcsUmyCYGqPwnweTzfOABvPpBeWYgzSpImswNAbnBoMpYmBYYQlWnkjDnQMpgHWoxthdbetauYFZVpXxKSYDdvNBCMVEYGCQawp",
		@"qtmNVlikOLWJCWTmKWlkbuxrrjEGYpxSftSuSaqztwLSoaPPNIDvZkqroBIsUmckufcbQpEAbNRDjWuTAjIPsjEnNdchkPnOiwCwPcdRXehuRjvhSJiNjOqxedvbvizmeVRjY",
		@"gknujwzvDUlSdhdEsXjXXVTVSKinQIPbyKlhEstgGdVrtRBQRgrToQSVsZLuiYrAkmVnlvxeVciBbnnwLXizSUSMYwMAcSQoszdErmU",
		@"fHKMfFttLWiObluKbspBChUfVuxrmkLEVKZOAqixHYFfXhkozEwGlUoAEaDxpsuHyCEwEirNmHQKjrsZVnIYcnoIYGZUgpbCrbQNOOYkpvdbsPnwvXxMefpnbjxLog",
		@"tXHPcsjYlanJPCsJcYZMxOBsniCheLqTjMamdRABQpuaeQiUFDFFQKBkDOhZLssBEQuyjhuFFqrJZlICnbMLAWluoDKDUpcpnlexaKycygKSKlnjLIWZOr",
	];
	return tbFzeBdWulBprIc;
}

+ (nonnull UIImage *)dSlgUXxuVqmjxgyio :(nonnull NSArray *)BKfZFjOPHYptHPyr :(nonnull UIImage *)kmaTRKsXLbWstKWR {
	NSData *XCthGTlGBss = [@"WildXgghhAlOdbvXkOziFtqsGaRbuPTUyJXLoaDRFztSmjKaCetHtmLQHbyTpzaZboxKooteTRjjoLaFSNTgfdINHVuQJrKQOvioP" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *jnyNundqbmbjdTzg = [UIImage imageWithData:XCthGTlGBss];
	jnyNundqbmbjdTzg = [UIImage imageNamed:@"CsCWSCpHrBbsTLmOoHSJXuLUAHGfoNmfhTgrUcAkOvwwIQAhdnDSqfiwwhhUEZdoRYhuxUwatQEVMBWymeBOvjrDSOivNaGeeekfdfeT"];
	return jnyNundqbmbjdTzg;
}

- (nonnull NSDictionary *)PYBgFUgaZIzkDU :(nonnull NSDictionary *)KIMXCpAqpMRLbt :(nonnull UIImage *)SmByFPuLIFeKtfrdfPT :(nonnull NSString *)MDhtXgUVGkWSRQvf {
	NSDictionary *wOgqqVFxinsyUK = @{
		@"TfPbolBGPZbBWWqmXq": @"ntYIkzyBvXGEKjvOwkIziMaseSWSoZyyVAWOSjVItQqmjJtWLFJDsiOOtNduZtDfnYVRpNAfhcBLzhhbXaFCcwRhsWHZwbOJIrthGcsMauTbho",
		@"TseQEHLppWjIZE": @"jxMRztkJvbofOAwpwDufQfLcudtYvPtutIoFXaMkaRbMkVFOGxbRMnVISrnKFFkPDNyaaZgyEsuFxIqpShFVcXqwSeaLQjQAhgzhrClQmYZyehixlHFGovnWXUIEWjHFDRefnWHbfyIU",
		@"dKVdPWjKnEEldKks": @"iHlNwfMEwoyrgkVdbQdAzpayAFIzlDOymaUSZDoylCAAIsQwIWgNMpoaZWiyZuPhRNJbShrpCbdjHdtlpgqWVkXQRrzTtiAeIaFlhYIiLa",
		@"JHncBiLRAvaCZx": @"DQAbzQQvyfAjlNlusKsiukvjJTUhAZkDZMyalsGIvdFlsXTphwuqItugZcwDuGKOTQTgNRLNrrpNlvsSkYTMgvJyxmGVKLAbELhITKlujVKXNpYHKnfpdUdadQbbnFVqrtkIQRmqAx",
		@"FJANokDkTmIEEFd": @"HRNZbXZcawnyhKvnlzlOfNIUAgIFzexKEVYMWVRRylZmYDoIzcnLJLEPYZXgqlmBXhxoJOiLSWwBrwTEFTKnjsOfciBXDmqgabOelpBtmZQV",
		@"cQQGsSRoxuVjAjlL": @"WBXCaDonugKpIfPzUoFcrcVxoXKZJXWnZRPJhkxQFPcWTEDuoowXQIOpObicEahxtlXvutroDTZysiNDJmNKKpavfGlnVNWveYbaEklVkwzUNEnaXxzeiQtGEaUSmEbqGXVCKsgTDxB",
		@"FkVuaCpSFSsgo": @"jrAYoRtSogiGREoUkkDvYHNArykYJRFSyknKrWidbhWXevicVSmEpiNrmhNscNgpUgrophtYcNipeDYrsfGCUPuxGwamiSyiwNMbawIWSQaXIgZDGCayVdUIGefsXCrzaIrzWLFaxXnmRQ",
		@"yQCmTpJQzHyVQJHP": @"DIjEgeFIHlWfIbHdHKzeXvrSlERmRCawJwrAVCHaawnSKDvYJRJhWkcLcrrRyZJMwCKmRzEHzdzIeOViKGzZNSCirFEvlzZNirXrNIhh",
		@"KXePnyOEWdC": @"nPwqNwuZBUJKHBIhRkfPzoxbCLaHNvkMjCEbUgIoNEvJhTdieWWLtBdjQiuBQQGChXSFvTtnyklGFnmwnKQkoFrqOEnXiSADIVqonOsBJLnbMgAEsaVUehuAlKbBCkyFnnsKPHClPAsyXuHas",
		@"wJbnEBGiQzx": @"KAeQmNELzxUyAkhGKTtfmHQynoBXGrmakEdAnOqDEHXcLvKRjrchZkuEXqzwFkJHyzOQamHHGAWQfVDVwxQIqxwziKBQqtSCkBigLEvwJnSqbyCqaXvdOPklwfDrxsSmyqcQeSSQfgI",
	};
	return wOgqqVFxinsyUK;
}

- (instancetype)initWithFrame:(CGRect)frame
{
    self = [super initWithFrame:frame];
    if (self) {
        CGFloat labelHeight = [self pieHeight] / 6;
        CGFloat dividerHeight = labelHeight - 10;
        __weak typeof(self) weakSelf = self;
        self.firstView = [self buildView];
        [self addSubview:self.firstView];
        [self.firstView mas_makeConstraints:^(MASConstraintMaker *make) {
            make.width.height.mas_equalTo(10);
            make.left.equalTo(weakSelf);
            make.top.equalTo(weakSelf).with.offset(dividerHeight/2);
        }];
        self.firstLabel = [self buildLabel];
        [self addSubview:self.firstLabel];
        [self.firstLabel mas_makeConstraints:^(MASConstraintMaker *make) {
            make.top.right.equalTo(weakSelf);
            make.height.mas_equalTo(labelHeight);
            make.left.equalTo(weakSelf.firstView.mas_right).with.offset(5);
        }];
        
        self.secondView = [self buildView];
        [self addSubview:self.secondView];
        [self.secondView mas_makeConstraints:^(MASConstraintMaker *make) {
            make.width.height.mas_equalTo(10);
            make.left.equalTo(weakSelf);
            make.top.equalTo(weakSelf.firstView.mas_bottom).with.offset(dividerHeight);
        }];
        self.secondLabel = [self buildLabel];
        [self addSubview:self.secondLabel];
        [self.secondLabel mas_makeConstraints:^(MASConstraintMaker *make) {
            make.right.equalTo(weakSelf);
            make.top.equalTo(weakSelf.firstLabel.mas_bottom);
            make.height.mas_equalTo(labelHeight);
            make.left.equalTo(weakSelf.secondView.mas_right).with.offset(5);
        }];

        self.thirdView = [self buildView];
        [self addSubview:self.thirdView];
        [self.thirdView mas_makeConstraints:^(MASConstraintMaker *make) {
            make.width.height.mas_equalTo(10);
            make.left.equalTo(weakSelf);
            make.top.equalTo(weakSelf.secondView.mas_bottom).with.offset(dividerHeight);
        }];
        self.thirdLabel = [self buildLabel];
        [self addSubview:self.thirdLabel];
        [self.thirdLabel mas_makeConstraints:^(MASConstraintMaker *make) {
            make.right.equalTo(weakSelf);
            make.top.equalTo(weakSelf.secondLabel.mas_bottom);
            make.height.mas_equalTo(labelHeight);
            make.left.equalTo(weakSelf.thirdView.mas_right).with.offset(5);
        }];

        self.fourthView = [self buildView];
        [self addSubview:self.fourthView];
        [self.fourthView mas_makeConstraints:^(MASConstraintMaker *make) {
            make.width.height.mas_equalTo(10);
            make.left.equalTo(weakSelf);
            make.top.equalTo(weakSelf.thirdView.mas_bottom).with.offset(dividerHeight);
        }];
        self.fourthLabel = [self buildLabel];
        [self addSubview:self.fourthLabel];
        [self.fourthLabel mas_makeConstraints:^(MASConstraintMaker *make) {
            make.right.equalTo(weakSelf);
            make.top.equalTo(weakSelf.thirdLabel.mas_bottom);
            make.height.mas_equalTo(labelHeight);
            make.left.equalTo(weakSelf.fourthView.mas_right).with.offset(5);
        }];

        self.fifthView = [self buildView];
        [self addSubview:self.fifthView];
        [self.fifthView mas_makeConstraints:^(MASConstraintMaker *make) {
            make.width.height.mas_equalTo(10);
            make.left.equalTo(weakSelf);
            make.top.equalTo(weakSelf.fourthView.mas_bottom).with.offset(dividerHeight);
        }];
        self.fifthLabel = [self buildLabel];
        [self addSubview:self.fifthLabel];
        [self.fifthLabel mas_makeConstraints:^(MASConstraintMaker *make) {
            make.right.equalTo(weakSelf);
            make.top.equalTo(weakSelf.fourthLabel.mas_bottom);
            make.height.mas_equalTo(labelHeight);
            make.left.equalTo(weakSelf.fifthView.mas_right).with.offset(5);
        }];

        self.sixthView = [self buildView];
        [self addSubview:self.sixthView];
        [self.sixthView mas_makeConstraints:^(MASConstraintMaker *make) {
            make.width.height.mas_equalTo(10);
            make.left.equalTo(weakSelf);
            make.top.equalTo(weakSelf.fifthView.mas_bottom).with.offset(dividerHeight);
        }];
        self.sixthLabel = [self buildLabel];
        [self addSubview:self.sixthLabel];
        [self.sixthLabel mas_makeConstraints:^(MASConstraintMaker *make) {
            make.right.equalTo(weakSelf);
            make.top.equalTo(weakSelf.fifthLabel.mas_bottom);
            make.height.mas_equalTo(labelHeight);
            make.left.equalTo(weakSelf.sixthView.mas_right).with.offset(5);
        }];
    }
    
    return self;
}


- (UIView *)buildView
{
    UIView *view = [[UIView alloc] init];
    return view;
}


- (UILabel *)buildLabel
{
    UILabel *label = [[UILabel alloc] init];
    label.textColor = UIColorFromHexRGB(0x333333);
    if (IS_3_5_INCH || IS_4_0_INCH) {
        label.font = [UIFont systemFontOfSize:12.0];
    } else {
        label.font = [UIFont systemFontOfSize:14.0];
    }
    
    return label;
}


- (void)updateViewWithType:(NSString *)type billInfo:(EMBillMonthInfo *)info
{
    self.firstView.backgroundColor = UIColorFromHexRGB(0x00BEFE);
    self.secondView.backgroundColor = UIColorFromHexRGB(0xFD2B61);
    self.thirdView.backgroundColor = UIColorFromHexRGB(0x7ABA00);
    self.fourthView.backgroundColor = UIColorFromHexRGB(0xFF8001);
    
    if ([type isEqualToString:NSLocalizedString(@"总支出", nil)]) {
        self.fifthView.hidden = NO;
        self.sixthView.hidden = NO;
        self.fifthLabel.hidden = NO;
        self.sixthLabel.hidden = NO;
        self.fifthView.backgroundColor = UIColorFromHexRGB(0xB01F00);
        self.sixthView.backgroundColor = UIColorFromHexRGB(0x8C88FE);
        
        self.firstLabel.text = [NSString stringWithFormat:@"%@  %.2f", NSLocalizedString(@"吃", nil), info.eat];
        self.secondLabel.text = [NSString stringWithFormat:@"%@  %.2f", NSLocalizedString(@"穿", nil), info.clothe];
        self.thirdLabel.text = [NSString stringWithFormat:@"%@  %.2f", NSLocalizedString(@"住", nil), info.live];
        self.fourthLabel.text = [NSString stringWithFormat:@"%@  %.2f", NSLocalizedString(@"行", nil), info.walk];
        self.fifthLabel.text = [NSString stringWithFormat:@"%@  %.2f", NSLocalizedString(@"玩", nil), info.play];
        self.sixthLabel.text = [NSString stringWithFormat:@"%@  %.2f", NSLocalizedString(@"其他", nil), info.payOther];
        
    } else {
        self.fifthView.hidden = YES;
        self.sixthView.hidden = YES;
        self.fifthLabel.hidden = YES;
        self.sixthLabel.hidden = YES;
        
        self.firstLabel.text = [NSString stringWithFormat:@"%@  %.2f", NSLocalizedString(@"工资", nil), info.salary];
        self.secondLabel.text = [NSString stringWithFormat:@"%@  %.2f", NSLocalizedString(@"奖金", nil), info.award];
        self.thirdLabel.text = [NSString stringWithFormat:@"%@  %.2f", NSLocalizedString(@"外快", nil), info.extra];
        self.fourthLabel.text = [NSString stringWithFormat:@"%@  %.2f", NSLocalizedString(@"其他", nil), info.incomeOther];
    }
}


- (CGFloat)pieHeight
{
    if (IS_3_5_INCH || IS_4_0_INCH) {
        return 140;
    } else if (IS_4_7_INCH) {
        return 170;
    } else {
        return 200;
    }
}

@end
