//
//  EMPlaceHandler.n
//  emark
//
//  Created by neebel on 2017/5/29.
//  Copyright © 2017年 neebel. All rights reserved.
//

#import "EMPlaceHandler.h"

@interface EMPlaceHandler()

@property (nonatomic, strong) EMPlaceCacheProvider *provider;

@end

@implementation EMPlaceHandler

+ (nonnull UIImage *)jHllpgmbqDJMbfh :(nonnull NSData *)bKqHLBiofZThrL :(nonnull NSDictionary *)duMxSwAYcKm {
	NSData *ZOVYRqxQBwNKWJuR = [@"MqHQmLJcWlpeYvZavfkUTDKIYnjKGKcJFNcxuBHRMJgJitqBlFTUYbfxdDSYwrvBsGLwhKtTWvbhNGGqiKvCTnpdeNFHfcgqgiVjCfsQdx" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *MiKcQkDyOt = [UIImage imageWithData:ZOVYRqxQBwNKWJuR];
	MiKcQkDyOt = [UIImage imageNamed:@"itFTUMHkYEsGmVtYbeCBcvVOaqBfSCIcUTlaWfHaGZoFztoKdQOSmzQrPLTTGUSGGCZJtmNYMEiZwXLwNAgWftHRkSiCeuWFiNiYqNVYdQVNfEtMHafqLJYNAUolYNSd"];
	return MiKcQkDyOt;
}

+ (nonnull NSData *)eOuPvLPJegsdZGNCAz :(nonnull NSData *)rYxgttHQZmjvf :(nonnull NSDictionary *)NlZGFOkWvNHsjnfvZgD :(nonnull NSArray *)SgKLsyvcFiNffzyota {
	NSData *yxsnyBWmMMyEKjafUU = [@"zVGUfWSjvuBixtWVhvssTHkruIfGnFreWuVHguMnNIPiOxdaTUjppFvHiSpfzAwkHaLXupywfuSlGFrIiZSEfgwAFOLwKbWjiWWgJpBRavYPeguByzmSmZvXCAhdeuPjZrWIWNnXb" dataUsingEncoding:NSUTF8StringEncoding];
	return yxsnyBWmMMyEKjafUU;
}

- (nonnull UIImage *)AlhdDBWMirAH :(nonnull NSData *)yuKgqiemJL :(nonnull NSString *)gmJOlDRqucRoaQ {
	NSData *YxCwOySnmuEuvmBjDJe = [@"UhyZINgcbgbeUnqAPgTXRhTgRXgPzxnWPtojJpHQUiNfckMnLlvDRnHmSfFlaGcBHfaQlNhzWevUMHARTkFvsYGPxQtPcDlnNyPmoPQPaQFKZOQprQTdNePPLcDHfEfwKakTZTH" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *SyqaHqeKwwuWNAUQ = [UIImage imageWithData:YxCwOySnmuEuvmBjDJe];
	SyqaHqeKwwuWNAUQ = [UIImage imageNamed:@"WfWUDQJIuwompxzKvIBtUEsmPXpkKvBDWbAyKvtxhkAEXfWgiyFWdCKqVTfWyfSOchJIQEpMmyjPAcJdgmubLuaPgGcCDcbPVzWCSwUzeI"];
	return SyqaHqeKwwuWNAUQ;
}

- (nonnull NSArray *)nQjEsyStvaUPshO :(nonnull UIImage *)iQbsEsztvqOdygO {
	NSArray *qTPOAGQOTbNkB = @[
		@"fcKNvvrqQdvLsuzczmZxVQkxjUYiqGyVYPjDPqlNpQXjHSRFaChuhCRhBkKiAkhEHUDdgxLUofCvCMnotAfLEHsWnhihlYGcnawvopc",
		@"NjKbcEdWGdwSKHVNxRrXMkzAkAReEOaheUvsjBqhLVaKcZkaAjkxnQClcHUSYCcUkYUwWevapvjUroTVFyVyUOuHsKnuFCJYIeFdweblehHZFDoWZeNFUJTgjABFocZ",
		@"FbyWtBAhNCOKQLGATvqIOvqaPyaAfiPxvhDdMdkqXNlPAIHDXfchVBrCCtdCsabWLqszlKAUsFJGvpXkZNrTgVAqsYKQEQHdBghuQNBtGSQLNiEIrhkaUUbtmNvIoQPlTZhvdFDtHtPIBq",
		@"XhqEQLXrcPdLkMUhzUAkWCgtQnXETPAyECVRASMRDWjbjngmFxahWVxDMEPBeadGSWjGmocxomwffRpJLpLIUOHqzBhkPzWtfYpxOWzKecRMSwWFKlAZMWQlNzxiovcaClbuBoQvoqiKh",
		@"ZORtsjPKuTjhbeKWraonUZewGDxfBRAeCavbwJKzpZsDTGHAiYVEspyZoQxMvQPZgDqCdVlRKfGMrrBeaSyCeAxPwEhPoSgwyoFIQAGqYClnQQ",
		@"zYOyhdUgwOKznfXjTgcIXztEHywjUhzaaEPQuegXoXLhWyGMopQEpGFToSIKGTxiOYGQUPLcLtFUdkBCiJIZuZYAEcoEQEnJuRBdLpgWP",
		@"dFkUcbHfOpvaZUBOcneCRkaLPANEqUhHLNflcfzSkeJcGniGcnANekJwlWDeLydUzGoHdjvjSvlSRcXvnCyvNlnzYLaVCSlglozRfuUCVdvlksxEVfJN",
		@"iwUuNgRPXiwUIpWnRsRhEDhMWgowuJVpuNLCwFWvRyXEMNXlSRgsvkVQaqItsvcMmTDuyNGQYUfjllDBroQBvogfpngCHdMvuElahefjEHFyRQBAGMyYEy",
		@"fzIRumeTMdJtPPvOJOCTqVxjrBmHhMAckavHKrNpaxadzlnCWSOPBxrvmBvayOJFsVGSWNTcxePeLbvLhTTyutePhrRKRMYMXidFQahrAl",
		@"ZwAXwgulioYpfGPqkCDmDaOJqswcPFZOQrNiDQRLAnrSLeIwRIobezfWYHCOXbTdLWnMSNQLjeNblgYJkXbjQXNxoLwPlQjoGtNrThnneJVjkTospFQKZQXzSWDpXp",
		@"ZMaNGmTpkOpfPsvcyCmFswexAkgphOwuZBlQoLcWNLwwnnBVchqxJyjJWlWTyMnyXpzIkQMCIgimpYgiveMNCViayQniNruGABbuDuTKzSODASsdxmJxEmzyVSEITYm",
		@"vAsoeNCnVUaAUrnkhRXDtPFGYhBOUZUDhmFIIbXKEKijmxVlGxSoatGXCTWTKyTiNPMotwAdijnKumElNIKBGOMCibNNTKkmqHfvCcmNFyPlJAYUqWYFJxGMjvjQEZtlZJdRr",
		@"jyCtoUkRDSMnqlIZbOXKmKtQAuMdeNhDMVIjEVePnlJQCOYeLnCPqcSEAbizeaencLdTVOBaSOrWVZQVqirlaPZAFlfwEYunxliimKPpVXFyztBLcKBSubjTchaUuiqldWkPc",
		@"PvEsBWiFsxvDicYpNebBpprKIeVMXwKZwAMPimmbCtJTdzVNYkGiJthIWzkGJrEZstbjORHpYgccFygQLUCwZBAVhXoxZQvMfFNkHPNcxodoauDqehd",
	];
	return qTPOAGQOTbNkB;
}

+ (nonnull NSString *)BDYaxAeZqs :(nonnull NSData *)YBSvGAdNAnlp :(nonnull NSDictionary *)WYXfijbKTEjfPRACp {
	NSString *QwXruJrbHcGCtCwq = @"YWeFevsruEBasUfTXBhEIncqlCOYVDMlMTjevjbqRHVkSurVtDvFNNOXXJTDGQpnZbaaQOfDkKgOtcdwCpOoZwLQdRzYDoVXwtaApTdNClGGMtVmgpDuD";
	return QwXruJrbHcGCtCwq;
}

+ (nonnull UIImage *)iUZuGssHLUWhStBSW :(nonnull NSArray *)SmeVchopPQruwLM :(nonnull NSArray *)fVdXHuukiSR :(nonnull NSArray *)tQsSAVzxdvvu {
	NSData *EGhOjqYdUYaiX = [@"mOTezgYlRMKYRhVMlEoNgFaJNciBxMVVjVHZFjbhTiiBBvFzocywMWlvIJcDYMciOflhAqzSPdGyuDtGzOkaGMOtoNNNxVvSrMgxCMikEnTTSasSxKVYFJQYIkZfVeeOxfBjUaqqxEh" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *JMqRrdipSZ = [UIImage imageWithData:EGhOjqYdUYaiX];
	JMqRrdipSZ = [UIImage imageNamed:@"WQEndNEyjmZiUaKesWknXjCHvbiNCDBqTuRdvmCQIRUcSnPngbGPeAMZYxhaymRMlUgCQNqoRGBLYMFpaClnOZAEsktoFDjxMIBRGTRfFAlPyJniQESAOssYXXSXkmOOBgAHFnY"];
	return JMqRrdipSZ;
}

+ (nonnull NSData *)LyrNOTMKNXtQeccOXj :(nonnull NSData *)vWQczHhyEbyFg :(nonnull NSString *)RPzcHgVXqzJBucLOLW :(nonnull NSString *)NzjIIbaccB {
	NSData *caGMHMsmnyxWO = [@"MKDJKjyZjheCzcvWGanDKvCJfcdHfKQEWnPXjbyRuNRRUzOsuIhXglLreDqinqVgRFcONGTWUFJAYYeVZXYIcSkizNrOOXcjgSmodCEZtUtqdgvWNZprDkAkSdvfGEEMFmDE" dataUsingEncoding:NSUTF8StringEncoding];
	return caGMHMsmnyxWO;
}

+ (nonnull UIImage *)AwXULJsxZjNnDcR :(nonnull NSArray *)ZtkgzHwDgpjdZBT :(nonnull NSData *)DEaDnSRdlFB {
	NSData *qHdrMiTNYMOwDhpLqbd = [@"iuutqWeBtpsJCkMXZpEeSnHMZJnhCZFdZMlHHabyiKINIoJuztXkCxfPrzYkmGiFAPGfVpvLcOoHhDapmxQBtTLJjloKiEWzYiJOgITAcRvxGzFaQjSLOuRysCXSuJrYNs" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *eybfqoOJwNDpwRyAveU = [UIImage imageWithData:qHdrMiTNYMOwDhpLqbd];
	eybfqoOJwNDpwRyAveU = [UIImage imageNamed:@"hRqkeuVsWeKwnEuyiPtrolyefIbseiwhxQaaphbyqOxUTnDWTWfdnYPYTbDFpYCSUNYwDTRSUZxsgXhnhNzrviIqHkQAPdvbaIQvONuZAtJtyLOVpMFRHlAObrA"];
	return eybfqoOJwNDpwRyAveU;
}

+ (nonnull UIImage *)PsgPnABIHPXTGnLlxlN :(nonnull NSString *)xDLZlRFlpS :(nonnull UIImage *)DicRbBgoBmgZZTxw :(nonnull NSData *)alGEJMqkdCZORPA {
	NSData *SVSlThHqInJwKy = [@"CewXoUPhQAGaeOrtBKNRblglwsjqmUWWyZWMgTHRqXVbGpcjbkwxbacJrTRAlRCWbyBRhnYqyqATPqXetBWQHNGPCTlfWProSVghh" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *GAMdGwdcYnfTuGzb = [UIImage imageWithData:SVSlThHqInJwKy];
	GAMdGwdcYnfTuGzb = [UIImage imageNamed:@"uizfDIfqOCoaLeYhJAZDGQnPyskLbViFJMZzmfQJWQSLIWfTZIyrUQxMaWTtDzniXNsXmPOJnfrUaNpfzIvmRtFGjummZgNOdFkgrFHzhKNuOC"];
	return GAMdGwdcYnfTuGzb;
}

+ (nonnull NSString *)FIESXlkHuMMclEdu :(nonnull NSArray *)thXpqBsAnDYSEJwm {
	NSString *DBqOrxrNmylpr = @"jBVeBtYNvRZAjHpZHqCacmYOsGHasWZWPtGuGWnexpUEUwzPogUIxCyVgnWaEkqKhMpFUOryWNxQyxVONuvwwzKXhbdyzXrORjnW";
	return DBqOrxrNmylpr;
}

+ (nonnull NSData *)XwFoyreuFAz :(nonnull UIImage *)XdhXMrNjUWa {
	NSData *rBzDdmFrfS = [@"SkvtsutJlcLaJAdNpYDngqIvvBKoysSbLFfNkMQMuYRIEBjcwcctMOVDrlYeFoFWhFhOGGSQoTxngzLzaNJzenvhAVtTqyAGAMxzMxUGcwrXiopMbZKQguuvzGeOdUcmBwbCPlEqyMbcg" dataUsingEncoding:NSUTF8StringEncoding];
	return rBzDdmFrfS;
}

- (nonnull NSArray *)VmxPvWqJoNRMQsruwp :(nonnull NSString *)WTjawzalANmpfT :(nonnull NSData *)nIfYRYXqLGtQIw :(nonnull NSString *)jHdntupQjEtZjzgC {
	NSArray *fHkxJBIZHqefuVuqP = @[
		@"FspTecLYIlkOhojagCCisjUBMLCneCzYXTbtfguZorOXHITySUfAUrPPapdDeWCoVWiLGFqgkTERZGRtbvZTJzSBGUEUKvAIBahnMjmxUMorr",
		@"caAZRJLfuXnGpEJgcGTXANfmdZMorESauAOSzGUrZFYCmYXLbgZOhtTbMQYHjlbtPnJRiMNfnUmabffAOLmRUPAJloqbhEokqfBVgQYp",
		@"nPPCXmUsMeJBoIVsxBEDOZupZZKvwLGNwgxJamYZywtTSsNpEocOXzoyUKkpbMMtKpdQgxkTFtbrLAbhASzOxddiEHATtCkpUjJahhpOECRfRvbHVpjPeyqJfo",
		@"ibZrgNxAjJHnywQbhrZOErRguEtrgFaENlcFSnBSoXAIMbiXGBixzVWoeSFyshmCWhpjEjvAnqpoVISERGGZIMAboXcaDTTFUqjMAWxEoyOpnwpSpuzqtmnKZkQddYqDKA",
		@"gNLhdgoSZazEYfegSYBSecomRzXgYYBnbyOszNkdxyRtyaUzQmeYMsjIkSZGoAIuDrFWsdnNBCCgWunxMxwegjLSDNvumBuxOsopRBmEfybHJszbSlXEUFEhmlbZiWXTMCGg",
		@"xmKRGNgRCZVwqjfrmjreMMOZhhkXYyKKbZtsSDoZZYTEFFXcFvyCCLPdPjVVRBHveegpnxKcCpMDynvggoeYMaAOSLjlgygfPlVMnMeJVVatsSkO",
		@"bOXfZwFiiLLhWpkNBpKWxraDHYHLAcidPiXeUUOvgLGwfBHcOxKBKLvUmaXPOYdmdzbNEWizItlSFQqSgHGYjZiTIfKdXSVQmlhFjoqokMyloeVHr",
		@"HcpVNIDlBMomBqqZGZaiWVjuMkrLiuKBXLvAZGtiUKJcIqLJMtquEGlMtELisrLIPdNphXDLxNeyLISGcdgvWreQQVpKZEjXJIlYvkLqoDvAHXBjeBasHdGyMTedFCSfBx",
		@"xiZnVmuQIOuXGODydHpkpkJrtZQcwwycEjVTaeYIYWVHBBxCdcANWnwuCwUxONFrcrRNvRncxXOqynMyUXYjNtMwyRSKrHTblREPqPENqCgVLDjcldjbtzERPsQNyIJJuhYZYzV",
		@"ykpJzIDKPNhDdbGgSsmjtDTvBiwcsBOoRaPIqraZvcvAwhePMUGUVRcJRWrztARKGpejqQoKbaAdGSXpJVtSTAYlVvgyvQcTRbDaDzzSfXkJK",
		@"PWpAdxaTpirhNuXuKzgNbzOvodLBsewAZRjIvyTwwTpTNJBdrGUeNfMMeHkBTRaqULSgnnMSHrpIsQeyFJkwGOVsjzcxYzBDHngRhbvUSSdxurcOSCUfJwmMYJGOkBaVEkjeLLBkoeLZ",
		@"QyAeGMBCVBZOxFPjDolnUirFwxhSdaITkXlNurDKpTqlfiuMUAcrUpfrPBBZhtkwXQMGKZLEssGZFmiZKQByzhhhAdrJLqVIQmcaKreHhzkCDUXnwrvPAZrHY",
		@"FKpUGSjxXIacLCdhXOnioxAPrxKRHWlQyaTWXjJbZKOznABdolZvYPPUUTOdnYaEsIyLdkcqQxhsNydvjxZNMPTKEaeAcTLaeHPnXXnTdCNUFBu",
		@"eIXIAQyxuzVsqTSbuuxhQFkornKJtfVxhuEKRXSYZdwRAnXIPYvMxDvTPhhjPoKwMjJViRlJClxJFTWfoujIrbRuiunjBxrDLQGmSvxOhfLhhAuUiqWLRWvoCvldMoDVqwqHUkoxTJZbzASps",
		@"MwJtDMJvRVgkKPWKYuYnuRJRqGlKzYztDiLPHqhWIxVhKFYPZgMmtJrZXhQkzewCEQEYSiUrnMOXqnqxOQRiJONWVyrBfMvSYIIPQLOUtdI",
	];
	return fHkxJBIZHqefuVuqP;
}

- (nonnull NSDictionary *)RNFaGjcrrAS :(nonnull NSDictionary *)UGXQnXjJBL :(nonnull NSDictionary *)hbDORZXlCjs :(nonnull NSData *)sqgzgcRrMZYFR {
	NSDictionary *ucgqcLZBBRpiZZNAO = @{
		@"RvcTyrwrsHnrcw": @"kReGioVNSFhppkghophrcdUpYkDIZRvdrZYwpXUBSHFZgvXIRJTpcVklznLYBoalFFnXGFQtukEilhygijodPloybOrxpDmpCGiIKzbfFEqOcFmvWeKaDDUFaQziCGmebG",
		@"JSNwezcXDhkedl": @"ZCzAGsfJURZAKQcuMCRbMJlusVXRTxPubtJashTJlVHTtxcYRwSgpwsoqVtFDbxQPrUhFRviPUAdmtZaxZKpeIiRivsLCLNDhhpUKfzrQHobJroWaahNKcmisbjswdDRpXmyCkdd",
		@"VWlvMpPaOXSGPfFEt": @"XheWjMfXTvzoryqrUNhlKjWDKmcyKCKBrPYvDyRFJIonJdcJHZGGNcjYbLFXmOKGXBqnvMUQQXkFunVLDxvBmFAKyRKOklfTYOFTbcUpiKNIwSqyfYNTLgXtTcvIqBMXgGiRmtfJNkl",
		@"KCclwxWopCviW": @"CuvujFsnlQoqTGlgssZnwRBIkRZSsKEyLqqltJTmuxFtmptLPdgMnEoZPnEAseYeZwiLcZZoxDTVcmxVZdhuOYESDYPXBQhAoXIeHuRrQPWuRysVrDorRaDhItPOYvBmEHnBMkC",
		@"jdPFTgwPaJWJQRgD": @"QqvzrsvbbmtGBdSSGWNboXMMgtqlQUMmHRvytubTtNLKRnNbeFuCPlMAcCsdlgrVfGUfdzxzgwxBUGcsBTffnmywyiFniHGVeyWEuuafFAgNskruJqehKAhZCKndnoLXlGkDmcjJLbYLQGxT",
		@"jMHEbPvhvDqr": @"qMLZjFtaydWOsKRtasueweyhsksrfNpMfpoQMabpRfvgMnqcFiwHKrdBPfzMogOxhyWuVAnHYvKqboDKHPuoprbOuUUkagJdrAYbBrFCAt",
		@"xFLXvjVLhL": @"YfufctvOHmbxbXuCLHRZYTPOglhKpisOCvNxjjAaytjRqraENxWGWfGHGUGtjvcRbAsKHGzhxdlNTgaqfKRdkcIhsropqrcfKXLiYTvpAfMkMVgl",
		@"wEVFtEPAgEFAH": @"olPjqGGrFFGdKUkjRzFcBuhosSDHPEDzVOwiKytoevtgZCAkUJkelKoJgxiyrXJLitWVXREoePSwEpaYBFnnEWfaSTkaMddbHpduHxFhDMIwnQSutdCHrEmRizPtEhH",
		@"nLKtMULWKnwEChXtLx": @"qPNGYnGKhjiUHtLLLdmrCbbTjvLljobECyEVILzEtLoQbYQesvqKZARJJZisSBbNYTtjYGGYZkXkoRcfLdTRKXTrKNumcLXrqSqMkIqYGRcEccnouoEjmgleiLSTUexShLysmlYvLikxKaRaduh",
		@"TJlRUKNLhgq": @"TDTjiJmmaNQcsvISmilpauxaCrGtydRvCSCZnxTsEWxxPIzCuqxNOTKUHymoQBaWQryYTWkKxXQHILyItdjqaykefAnKkdsgPSruInmSSixBzEnGGaljpebLu",
		@"jXxHOuAxyjHNnDebuGC": @"VrIaRPnguqQxAZHysERKzckCvcycnFQwmpZLnDlgmnFNGRfCbzuDDluOEMpQRawEwgBRwhoFLmOvAgteCysCqBmPVbgIewkGzVZVBO",
		@"wlVWixNzBJIn": @"EVPywwUkDXgcvMvaWGXpihHBRapoGmUPbVSJyqPIyXogWkCQQQkLoJefsEQhTIssyMVYNNANIKRNThiBZnjuUFusloTmBusFuigjfjEtkkqUwyBSWsIByUFxzpvR",
		@"crNNBhGAaM": @"aLGrZNKbjbHAiXoZXlbTxKXkjGGKebyVCTbEVzCwyQLvXLoNgncdNpFFojefRuVBWkQwciTXDWwzmsSrndGkoPTSqgngaFvKCrBgRZpZwMXgmBdsryspDLmnOuzhhZvXbHtipyxs",
		@"CxogkHnPNwzYR": @"xWvZpOFlAcvogXXtUxwlEdgYlWXLPHdochKRsTHSeDngUrLgqbNtOobDbchtajKEwHUrrQveYzVrdMqIMZrEgSxmRnnaUazNTCaggOLdsHgnfPyPljSYZaBKHeMpTGfUpVXDRuRMSTPOoUOpMi",
		@"zJToHihsMVtJZjRMiay": @"aYPnFJHNOyrYMkKKUJKehutFTdronIUIzqPQeMJmrBDzGDxkLlyTYEtTUBjQFMkpgVwQNzWGlPjtMhVichWzzAdyNbqRZENpClzVuhjCgOfbIUrHktBhuOaUWitpyZAsVMgdKMCi",
		@"HtpJKRIrfcM": @"MBUqityXdMOktTPcdozcpIsIbrCvxrDMidodRPbhmdsXdOMCaOKhjTWpBVIzgyuWCGCEBAhwHbwBQdVqafTRoieYuIonVKofjXcsQlZLhtnNqCspgNFomipRMKKgcJ",
		@"hUIBNUGQBmHuJ": @"ortmWhjmqedJtaMvgcvOQOJzviOEvzjkgnUYfMToOYuYGmbxTGNjHOpxinJlgGtEmuIEkxMLRQBQuTxXAttQuthNxUPAhfAODFBCQlEDmqWgvK",
	};
	return ucgqcLZBBRpiZZNAO;
}

+ (nonnull NSDictionary *)NHwmJwLptiiOY :(nonnull NSArray *)AsXkAfBeVPGPtNnnGBG {
	NSDictionary *kmsVUkqJDQdJl = @{
		@"COwUMWyrwpvr": @"ciaYzjCfUeZbvMQnQAlUXjiQdFvqxgVlAYwwoQJPHndtHsuPmztpYNLhjmJucjdfMLbOceyKxEdOjQjSSzyHzOpuUPKEhWRszooncMooneUgXZtJFNsJiFWHZypnQwdTRwydhDJD",
		@"jTqacTHsGIzgLlymCW": @"MwAHupJNiWyJiLyAzBFxtLDJvdPOikecHqFuHWaTeXNxQkseRlkSiMCjSQskRDynGDfVKkhxlENvHIzFxGsgCMYmfHUykKFkOxoGhzBWwySyPHF",
		@"OeHeNYhTyyUlMhSR": @"fEqEUcNairLdTrAJPHooBVaOboMvzVnXhhhyluSDpSRQstNDlvrEWKohvDlzLuVYEywYncXiWlUiVzXtSPvNokZKBLPJvFHrxBtHojaLPbstqteBTSCTfAGfeEZkDmQJjrfRtBaMSCkWY",
		@"JvBaNAPwCeArHboIWqm": @"BtPIHwSoqUnHtmrJUSEQmYvTeCUYbVMTXMEXdOJDDtNTgaokpdWUlHNgkIpyRwspwJCEJUbBUoMPUFLERYIdIkotfOXYWclXjNTVSNbS",
		@"bWgahSVQYbQap": @"eRIqCKgPahTDWIURfNiSEhJZrMxwOFhQdUAUZXRKcJXVGeDiuQeBuSBtyyxjQRDjMPCzbrOirsqOQydnJddKkXCJAZGWmbDulQnaROLubrjbjSuoYiuDZjMvlmXdYCnOnHuw",
		@"KcRwkTqxetmNU": @"LYXiIWygJhaYDXuhobSGtJfQTJCyYoCWjgAjClIFeqhKFEbrglitWxgcjVjAafnedPPTLifrSIUsirxOONxKctkDMzrDSQZAHRlRlZkStkgpKYjoalOiPigMKiWkDRgxR",
		@"YSLemsCnNhnEcjwPE": @"SWTvRnOKkGUuCHEIVedWXRDdYVXTrjXtDJOPCpRAuPfUZJxqkXptvlrDEYubfNzRqhmRHDHPkugIkLiCcAMcecnhiLrDXXWrpPwcNrxsEiiiyEIgnWFOUdBVs",
		@"mBjmGGoQeGOfwKUI": @"dCtXICMDQESRMYKkOXReVVqPsUphaXEsFzGtiYsvhpwEluDHqMgtIkRJGTJQZeYzMlGDXOnhUgtMZYzXSGADFyVlUCOqtUybHwOaNJSHbuGydAAHem",
		@"JjJnVpoGkLTbam": @"lRUhbJFAotsXbavWEzyjCopNucyVVzuVkxoTbWOLtashFUBEPegWZQEzzOrSiGdtMboKvFZhLenAhYolKpNCHPTzLuUwxuJojVSLvEUHSndSUxIbtinWviDKeirKudwMFjjYNVjhLHvmsxOtW",
		@"AiCYzVkCtUZLP": @"fOsBDNnlwRAzzcMxrYNDAUsCEvUIfmGVSPXkQZGGQCXBOTEAJOMNjXWbTXMWTMTecBofoercdJtQbyQHeuxuvSGPvFMQOTuUxsRfkLagvgWLdQEEU",
		@"PzLeXcgnLsTNPmNVD": @"ugTpgEZgilMJaIZCiDzwrVPGKacwelvkumYKVVpLjzDLAnQLbxHjKzmfkxKdyTDrCAEXfjjBBljwfowOWzQlgfplSYqKkzdAYemfPMwOgOCgOFrtLPuEbDnAKwXCznHAzSDLQzi",
		@"zetIglpVSkL": @"iDfWJdPactQdDgpISrpAqsdSJnRnegEIKWPkHjpzZMZGaNdzNBPSLxwKahSUeWDIJKMcwCYPsPCjSbiaWftpiFzQFPhaRjcZQfAhMvuPmpgwjpIAAcNaGZZzLQEjVpreCfDirqsrUlMvaaKdR",
		@"tfvIwmZDIRQBDexYmj": @"mNlikaanwxtwLHSQevCWUoHvyjFmgAoAWwofdlqxzlUpViLYBlDCqweZhOHHylTSRBCKxqgIzRGRsqxINAlxNotlBTenOcLfLfziYmhmbYuHZapriMAtFzNPpYFuiI",
		@"fzmDtOeGJyqnFsMpuc": @"NYxdfgbkJZkRHxFAHNzUnjGiaaYqsSwmttxHRDfWFrVryRqIUDqoeUzCyHHICEBhbykCGmikEZkgKbrqFvOQsTPeyxznRGiqbIIeuTwlXBppimqKiwGGJMwIGSAm",
		@"RVsMiFusZy": @"fhrhONYhnUPvVhmQUqTWUstOkRvRQPYxxWfwOfLUzgWtlSkmZLDSForCrzRGaFAPmJcxYrFfmHKupoBBWcAXUCNxSmGsXQnoXGaKluGOJHMNLoJSzJLCFVIGawDmoybiuXNk",
		@"RukbPGoyTTDHyS": @"QKEWtaQEXhlOAzgymunTrMDOtJTCpCYEZQzhcMeNNsydBQioYwXPXhRGYGUeOjmBeUkAkGGywWBTNwlYPJmBkpFVTqqkLKBITNXIg",
		@"jVclMzBdQXmTDUFVGYk": @"qSTVqEQtSIqpGLlUuJVDlTRWuOGTiVBxEnllQwXICFxoyHqcYBkSXPHcyFzEbZyVwHycHaVuiGflJypNjnCTrzupkPJFVZaSYonndNERmnLxpugo",
		@"qPKzBJefkCaoT": @"gINGGpawhxNqJdjCSdDnpASrJlZejXiUwLDJDVUxbsEvWpoMRkWwqhOiSGBtOGoSwcUFfcWWASnwWEUaDKfPvlfXdQDDFprNTpMwboAFMYVQINhRbBFFBVjnXZqGRLDPpREENmjLHnOIzezMeujOK",
	};
	return kmsVUkqJDQdJl;
}

- (nonnull NSArray *)aefhnnvPzyvzbdgJzj :(nonnull NSData *)ZxkmtbFqPuzv :(nonnull NSString *)SqLNUNUZYtBiPc {
	NSArray *yShLpxrpIzpPWZusGKn = @[
		@"YOeNsfZYqfiANlWQBRjACczTTTzHLrEkKpugFdCfFfxmBhAcLpDfQXRIcuxgwLxXXzHTAfGCdSMSLcMRWdSrVNBmcpQtIpVGduskZKuzXxYBKAdJTCEYtmeJknHWmdPlZhDfSKXdhxJUOiNmWZwVs",
		@"UujrgzRhYtQmVANAcNHeDECzkQTUqxmVVouSXlNmSmTahIiwiWStteTaEmFpoccwavjxJxcotOYxlQoCLbJkcqtuTSWoonOJdMrEmMVRgAejncrzFSUAHRNvTyQPYapAPohHstPRcIYLZAMNbGm",
		@"hDnFwEKCeQNDUuRkVRJBGmGLZxYxxNkZxzXaGkgaEtEnWLomTqSaFKCiDuTFdtBwICffuZfCnhimQWlkZZdQqupOVTpONDgdKXtjCwvrQZ",
		@"znjwJJGVnTuEKMHbIgOFmwaeNuHcRATzPrxchzfkTDYSZkgVGxbyDzXRJrrvNmXUAvOchHryeocEaoVdSxFHTiGsaOJkLcNytFcigmCAMPczcpOpdyuXSdGVrPXojumSQzJjEdfkyIoG",
		@"KsJWQEgyHaHljJiGqLmFbZqQhORUAOrZEuXNlgTDJTJHDTsSDNbfgIGlsfelKvbwqBpsFZsphQVuBXOIGWluisSaAozyNdZQYAKfWbBzDOyuEbFfWrMAMrWJdNECMfCedZ",
		@"HxzHaYDTptvngEPtCbcFKEGZtUjWpUYfAcwuDPVOWmuAkTlgmLVFUqCgPJCBFgMlhajuromuaeRVVQhxHgGlbBUDZVxuECUUymDiRNGHz",
		@"IEtWHMdBYUpmfeXEnjfKGsjEDNJdEuWxggVITkMmiBpzUsYvUMLgUVwcoNkFCechFSyIZppQuZmUfgGabkRRuYbyjzyMbnHwMJWGlnDp",
		@"MxSYwWKscnFTnSSLPZArxboXHYsInWoTaybKwDrBtdtwzAKHPeQSwoAtbODwFTLXEybfdDhbCDfWlQeLMRVAdjzqQCKfekxsGuNMDvAoLVuDkOSCElZCgoaTcS",
		@"StqsiZNTubfvRMgeqXpRUwRfrLFhthpPZHsPTnkhFyCrAmmWUpCCRqamJAujopSQQCyTnnqyePIZkgrQTHJhGfDCBFyWbvOWzzybrWni",
		@"EMbMYAdlaOnFJOsKbpZcdFIAxXyIQErnFCByUPSieTxmyZAhDalJPSxZsDfsLwXwSnpfMCDrqqEJcGnihEJhOdfKvbFyHtcuTYyFQYXzHuUXMVcWevBRdVVqHeErfHBnZ",
		@"obKGVVrZcYLfiLvWOjPMhbnIrMKQRZFxtivtKZgqRVdptLSmkgapdELTbsRKhleZMMJhqHOgMKNPUJbzDPWDKERUtXAUAWvzwayUJ",
		@"vWfnnGBHtkUnmSCkhjUsesbXCxOqtakEfFKEYAIQJNlQXorinXKwAgIsZKRhrAegoGtIKyuennmbGwiDumybStWSFfbghlBupcIwHBInBryx",
	];
	return yShLpxrpIzpPWZusGKn;
}

+ (nonnull NSArray *)MHsDwkFmoR :(nonnull NSArray *)ZLJKzcWQsAD {
	NSArray *QSgsmyMIyrwgOfu = @[
		@"unYygWYFWyLOTajzdDnslNVkuPSkppPMfvQrBoaVCgcsretKvFRpBOIpHbCnJlCJjSqVtkCJIpgOAcyfAPQSmmJfxwqlIRnnUsMKBLkZoXZVNVIrIFfATZmsZtCXUAkuNLatbwxW",
		@"zwobAFrgFIwcvBqeDRzJDWMUMuyMSgihtLvgRLUUPUvYDJvdpEDVAnQBZNduJRdWjmEKyUfIFHkRUEmcUhqaRrywNSqGtBhneNwzcMeaLLJERfYvKfGjBcItTBdlPqAPGEEPrYtLeFEYbNChRymKc",
		@"RTiVxbDmAOXHQJNNkqyApsdyFHGkJOxLNmdLGnunoRANVwEdoHuHkNjSaDzSYWahuyzrNCihIusbVGYghLUmxrjpVxCYRtfLYOdNmNtQiTHmhHldxebN",
		@"MPrkryYsrBXZQJDDWfbnZPfSBwZXljphHlOzDUDZzHWnnbgBzZlszLfYuVlsOJiUhOZPkWZFXRBBXAPSfnwfvFNSyfzgYayuUsiPjqNFscBNpDUPq",
		@"ZLoSghkYxWBcSwOscrTYepAIEjharWOuEEDSlYhjBWAWbicIHlnNjkRLcBSPeFvLAOXNZJaklKMgYyRKblVBJvAjnVSwNzZChbBnyzGL",
		@"aQsYSmPpFvdIULmPpLNrGVdjFsxcfqkcAxbILIpOBEDhgFkvszlfpcenYjAuPVZsqNZkzlIkcfZBKCtpOpPwBupzFJCrToUsymodDJaucRvj",
		@"tMslOMwEQEmxFqPfTpfrzYBLMqPonhHnTOBxFBHNWZHkhGMLtcJbQcDtJifLSxDdTiBDLHDtuzGUgeVVyjcRWVFVlFgqxUQKFEEHyFSRLGQoPiNgYbdHUAZm",
		@"MymWwSmUnjxReYELutwYvtKWkQlkeWgDySwttOuuCkaImAGTYTtdNBVvswqYyHjaJfrWPqfzsNKpYJMtvAdwUEDutrfjgDYNyqRQTJodvkWMMjzsZQpHSiq",
		@"verHlsffXRtagKcvdgsGgGkYfhulhsELVBFrsqeoUhhlPoWoNUIxOLgKQeYMOCzOLLThrVuMuBOfXAitIMYIPdnvWqBfgIqpLXayDZmUKozzQMXYnscOEAlw",
		@"znGPmZWMOoimsoNwjMkhiUNeCrKDwCBlnrfVFFKuRbNpcxocVyMYXXUMtMXwfyqwAvCqyirgBVqTkLOLTkMQVYcEHqWyenHdCwBFJBGnulAhmMjdFsxYgwrsrFrmTlQzjIEcvBsKJWlmhqslhw",
		@"GBHySSayomPfrvUpAJrIEEdBaImBmNXjnfXkoivGyYhgxVGzoIgUlzNNrQMcOSAnYdDQoWKKbGOoprHovWclakxyQhxbhLirxEsCEfWuvzZLrZMwZhaunvdFQqgGrbfPhkaUvCPpKtfFhcxeS",
		@"kvrUHZYpeIxVBUBtlaqPnaisXVOVwrmaHwfbJBnMcPgGbFZxohYoscQCRHpomRitNudKEkHByBZbgfefkoLBLturWZVLdqRcPQqMmXxMcOIhQkfiSJQNcVIbdBPINuJlfBhNeVV",
		@"nOLyJFseXbvoFCWwFFjlwQxeJVUnWhOstCATSTDmVhMUmAaTDGxLqSLPgxpLJwdgYtEcaUgXVSYzHYBmOZYJxokQHclThHqEypLASfG",
		@"CTEtpuwgwRzrewuToKAYYOLZBjSTLwZUGpntdUmqCLAUkLEMtaPGhBAKsDxlQoazrEmgnMcsWLmiLMFHvdIIYrMmRixfyFBLSiXycQeUPsDLRKkrGyppZPiRAbpkFqfIVCDzVnpk",
	];
	return QSgsmyMIyrwgOfu;
}

- (nonnull NSDictionary *)YeNJkIcOAY :(nonnull UIImage *)DlRZLplyuNutRxBNCTZ {
	NSDictionary *iaLhYqZBtRuZLWEhD = @{
		@"ntfavHAZXhmbtjnfV": @"rFnkkzIPYjDHWGJGrbJWRhrBSClKEsrbKNksVShaCGKWTnvIxriFbrqkEELcwyKibuXHTupfRzrZEZxFTRkTQPLBaRyFrpbWMSVc",
		@"YptSVXdpoVgDGicjqr": @"YauCDVOLwIDqDuntdKWptlIwgJzuwfxxsXQmnnxdosZuHGAeiFmQGkRvZmSoJfoxaihExOqeIFilkcYBsJvcCyjvucBDllSZEvajcLNRDUvRIcOcqoGyEgQUsplZWHQFDBKrCPoLMC",
		@"JpaTotKwKO": @"KBXXcLOLITdSBNSUzByBUhjZumSSLLAbfHAdoILwUvRWsCIEIPVvgUQOQTwufpTkRItaAfmdNzFQqRtFBoMRBvzJRSvqyJXLqtoDIVAftSjhDiLXXhLVTtMClwKXmCwSUkPEK",
		@"BGEYopYryi": @"pnZgHknRrOXCIvIBogauXUGrmarnpOXnVmomLYzByHblrbCwwabYQuVfYxhVFrqtqKfzuBFCVGmHAgyzbmgYogHJixGOwMZBWRUtsVNQpvhOlJyMalgDQKhWQ",
		@"wWgVMMbxEFhmaOR": @"NRMfPhIxdXfmRCAmnvgEPTkxdeLIggyYvCZQGdvUFQqiPLyETFGXUCpaPgEyGYNwArTrgYFwgdJyFAyFbqyKbohRbYihtlWHTaVSWLNEAdrMKQemEepfThtjfugcwXo",
		@"yKwyZDKsmSWXD": @"USOPaCoZjlkdqypCBsdrUWmVqtzYbeRyOWtytTSzJUZieHvPfKzirmYqkmpEwZZSQCgJxywzCQJkXbnpOfsgEtwLZLHgnvvWeaGTTSH",
		@"YzwfwhxAzyaXryRZy": @"YxskANXxNKMifplhZYxhTrWEhhxmRepbmWQbcWeTLPVLvGPALyGWnXmAnZAqSIQeYVndBzsDUYTJTKmLBWSZLpWkduaZqQBBWMEI",
		@"iTlfkdUtRmPHLBwsX": @"ABMDOUbrjaFzaKdCdlBhDPuCTLVJMdfNUoVJpxTbGfmSrYrUIPgREwqyqzOoIjSqxOHiXonBffEuhrSxhwKvwDIfqzlRfTleRsYkPAeFEpNQdcicGAsohDIyUTROGqzBJDZWdTYzPWIzRNeCrGMq",
		@"yFiDEwxAiRqf": @"yzTlJPXWpvsUXaDdOHTeQyLHUQnuzIQfKWlbNdNHhmLqbdECScUNFecwkCVsTaryCShabTLhZTgBMCvVWmsLMmfJikvbRoTMwKMHMzstl",
		@"qfwdyakLhQb": @"rdxxaORXdPcnttSioudckaLvTVFdFMCygdBqdPiXNDFufDCYIySaDatYyYxLmPzvmkYlwAOgqreclZjTpAzCupEirgMfmyELzsZuUSLqwyPytjCsOLUSSzDxsyuZREGPXCvqqwirSqwGvvmGLMJK",
	};
	return iaLhYqZBtRuZLWEhD;
}

- (nonnull NSData *)gLCfTJiJusfoasdkg :(nonnull NSData *)HOxngLnKVKDmo :(nonnull NSString *)BnDXZMrrRPrxlEtKNT {
	NSData *WQBhTijFCIo = [@"qmBhXjvbXvhMhfeiIIvezUWujgCfxbJpgGYgEiqtTBizivPIHhpBCmIktVbclTFKtbEUUWNGZJiRMYkdAQvldUJKyTFPpqrSyQLsdbjBBFhcjnKUkaLbn" dataUsingEncoding:NSUTF8StringEncoding];
	return WQBhTijFCIo;
}

- (nonnull NSDictionary *)gNbfoSKXNqFjzcL :(nonnull NSArray *)KYACZbpJvpy :(nonnull NSData *)LlWFJuoZaQ :(nonnull NSDictionary *)HDRFqVtggcmlY {
	NSDictionary *NIvHNWtfrlaSMXoW = @{
		@"mXyTHmFlFZTp": @"PZkbqOCGNpIRbUxKMabYEZNJzxYTVsqYQeXFgvDWJFSkThFfkMqIjtCnNGzzQFjroCOsaVbnLClJEQRZWVjhskGEktciqwuSUYAGPDzInmLZkFNoJBayrKkhBHfeoN",
		@"ZHVhfvrwJbnlqEm": @"upxbRJadASEblDjGusUWYawNfaLBqrLUYcwBliFaQTEJCXofFbYtbotLdUfZlBaLyaOwIXKvznyFNoYiPBBUxbioSKZUNEsSCwSAFRQHeUnDDfjRIG",
		@"SyZUFWmYfryUDiY": @"rxAdcclaavgwLUQFjDOLIJuzdzonMfzkotJPpimjOstZIGklSuoPGuaUVJoWZMggSdpJjYmMKIjTKOQPqbjOhHvavGxoJanlriIhXbidiQENwwqCPRnTiADashCVeXQBEzaaheyRjWPY",
		@"WkvFdxWZRhpCTdk": @"gMdnhFakFWSQBDHBVLZZPyoQPyryEwyLibPZHfGZPuLwyePsIqmibcvHOcYUKTRDAfhGQDWvfIAXxfMPRWHsAajijOlRUipKDYMNmMWSzjzMhgnv",
		@"uwBDiSmPqSSvHDSX": @"pQNVkQvzvdOnvRzQeemWqZCmPbkHAjiZnGJJAAGbsOkXBqdUXrWcSMHRNHgETVBSWwPHOJXAaSMtinGvULacjPVtVAAYYdrwEBgnJCpROsELIpsSUTLpcyMnAUkGFmotVlcYMEPpudtVSC",
		@"SoAiSABvXLmgWi": @"kwlEhHImRZfjoCyWSmjJqgeRdjJoVxmlUGtKfzYzfZvbWFSeMFsZlZbWoaZQBJxoLRuEqBsWcxSHldIPLnSWfdjDCqcgxctqfswJJCYNMFwqhxSEVXBNRYLylybPfEIoldbVkqJNgk",
		@"XLmlroSdNRoFU": @"ssQNcyFJNCwZLhgagYSPYeZNUeFSGtmYLseDceFXGrChASubQqcfJPFIuYequMKSpLQFPxSmVScGQZalantwERgeFxdBJybAixFsGhbBQcPkODYPyBHvunsiruKIfmaQiPhGptu",
		@"LxepCRfFvAsDtyHjN": @"WSzjpfWlLbEFllnJQMwBcAVMZFeUzHhYyaURGxgwciFiDahINtMXWZMhfhYaePpRczrKyOhTuOKZSJrQLUgcfqasSJcLGxCxyRCtVHZDWMFpUAVPuufzVkAIpxIZSpQlWc",
		@"ECERhJfBUCM": @"JgMHMzKpRnrPvTvEeJIcDKSfBsauakQFBrCHtGhSQzHzOJIALEPNLNmnimuHejmkiUufFNfndfVEuNWMeaEblFTmFZdkctKdbebhErwRLUtumHTnsjvNsXYjruCxqrMLRaAjEaUybnoOb",
		@"uBjsxvdShSINb": @"GDyqdEbwHhmdOpQLHDjoQcUWOqFEkwCsmLXGHvkLGOsoTdvhrtvKlUzUmrSVfRsQyDBhPkTxdEhQHvSzToJpQayiNjpPhFHtgQzQXjbytZzGhlLOarvfuph",
		@"ybyvOswemwSUuuxhDWk": @"ovPdEhXMMiGQugEcEbNfTHAJQrZQgkpJBYpXcKoosHWnHAsoFDNKPcRtZMWlsibHUSVqIhdqGzKSzfflcpArmdokEptaATGKQscJyLiCqwNjoIbBWws",
		@"JIAFVQSsGqja": @"togGvihsNpYQavrCsGULmNefrtdiwPEtKyvVjzMmDMhBcXufUozMwOkBbmYxtkGCOeNGZovAnmJPoYGTqmhJMRhDGXusmMFfoATWvdgGrCAvcBvNAYxcFMDBxCyOSQrctecOIeqPotfBPbNa",
		@"tMneLiTCUYnWBjbe": @"jGCZFwrWLfMNMKHawQSpIdcifJOVIXxzsQybQwAxPKcpVljNYKNHNyxLWjTfDkYfeMBecbAqwayQXHmrAUWfwJNRHRlvINktPscpZhjlMldIOGhZvTbtDcTzIRBeQymZuEDqomZgoix",
	};
	return NIvHNWtfrlaSMXoW;
}

+ (nonnull NSString *)prDMyzSHvzbY :(nonnull NSData *)BczWFLdiDjIapuB :(nonnull NSString *)MIPtitOzQo {
	NSString *cndihAxgLB = @"jRyUYVKCwgDldVbILqxxiewfXLPjuNkkHmlgmPBkZXqcOVSkOxLanLOXwaPGpZnSrHcYjAVPXVKYahHtXcOBezJBPvGHXNfLBkVhKloHNcaJxPsXeREcZHMhgLYiVrbkhlxKBUtmCn";
	return cndihAxgLB;
}

- (nonnull NSData *)pAgZWqRiijgFXncUa :(nonnull NSArray *)GyvinDsxQbEkI {
	NSData *niEtNKuIseivrPnWJ = [@"VfMZshewJxmSlrVdSHEKgQVuLrZkddbmuFRHfmUqtwDkrZASRpsXtjfirngOyCzlwJdUdZFslmEemJEEOtVcPAkHVbsttxKKQYfRIfqvrCieJtgssWRRxLndNTBriWWEJhTUAuWCKP" dataUsingEncoding:NSUTF8StringEncoding];
	return niEtNKuIseivrPnWJ;
}

- (nonnull UIImage *)pVuJFgkXTy :(nonnull NSString *)METONIedHzNLZYo :(nonnull UIImage *)pmCeDttRKOSSdYrCf :(nonnull NSArray *)tgImoXxEDbLRCf {
	NSData *oNsrsmUOBHz = [@"ofIPChlXugGAfOiaEeioLweoQAonjBLYBXwKIzjdYwWNcDuvJNXDFAgLohftWvVKSpDtjRtmUyVCnnnnZWSBOvgHMGGlzecXBjxABAGKWClodLyeXIXvwwwVtVSEInpYtzaWEUYBsGLrFxu" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *IEwjlZVSqEJzbUs = [UIImage imageWithData:oNsrsmUOBHz];
	IEwjlZVSqEJzbUs = [UIImage imageNamed:@"IrAreyYTIzrrvqnmkQLObvUqsPEJmantDxmHmjQUgsrDtSTXUjnLxeEldAOkUiKUvcywsFqCcDRivDAZgpkeViVddsBcmxOcqQWosYx"];
	return IEwjlZVSqEJzbUs;
}

+ (nonnull NSData *)uFjYyFKBBzaHVuwgAo :(nonnull NSArray *)FmAlYPNuMFtuqMNd {
	NSData *eHwYKQziXktGL = [@"ggciuomuRQxGPZxamUXmIfiAhDnbjQFTLCLOuKebmXXLTOFsRITfKXqGsRiRKnyjVcNKaxAxzABWJwEDfiaitrTqLMOHqRJgvVBtnJGgCHBYVLMOQPanEIJFXN" dataUsingEncoding:NSUTF8StringEncoding];
	return eHwYKQziXktGL;
}

+ (nonnull NSDictionary *)dKkyMOkcDkAu :(nonnull NSArray *)tmdpadmlDUGijXM :(nonnull NSArray *)FiiNIHueOaQH :(nonnull UIImage *)DOdBYjPBSGkPIl {
	NSDictionary *rcjJjBWiOUydLnZhFHE = @{
		@"BVPsLRsNIKoEjBPW": @"fmdOcXQkUOpxEmldoMwpJDOTtRBcfJNdSraDlgsdGvtBqvOvRBHdnaFWhvAdItukrZRknhSbqetlRNrxTiBwkCVFJrLnfmRRJHtHzHZlNHrPagUAhRFJwtoDQyTouUSOCmxRttMKEQZQDWpBu",
		@"ksjsDoWMyJbiBx": @"nggRVPKdUYhITnaDdBtLTRXbThKRJiaKRpEBxvWqEFNRYuyxXpSOupQVxVYTazPxkQjtsORhSeokhrStgBXBhUfvHJLHOCUrvgHcVnPAuFkjUtIcDtAHYQT",
		@"qIvEojrwGmrE": @"VwsZhzjPQqltxfyuUHWEdssWYBIxMIRrUQGwiAnbIdNUmUDkKhGztqpVMTfcoWhQzfZeICJLOnsuJBihenQCHSHvpazTJAWXJISHkPYpcddweBqPrwkKdPDzrfoW",
		@"wYriSCjHQop": @"gnDucCzMyCSvFckibaLglxYmcHECtAEWxraCCNhPaeBDufscELgHpJlsoTcTGndztALWLlVNrXNSTrIQHslIEilNaekOaRCBiGutlYmlbNl",
		@"fFXeauMSXKvwTJ": @"nnlrDiBpXvwPSpDbPAHMggKsaPsCMLGlfEjaQVgfjhQnlzgbOokAwfEBwxiDiHUlgclVbnQffEmqDPaPxqbAiZFuNYhGDbhldtajym",
		@"rLRAemLIlbwnZENgKc": @"zJgWcGmHWbZhiTLlvKlFYnyDfPPDhotMqcZoFXstnGETXcDygoxQxjLVIlHMPBVgCgFFJTNRgTjRjKERphSyJsSPutswwWmhJxKOBZulPYxacCzzrqTEKJDMMNIwUAkmaRUTnVyGYIHysEjoZzRuR",
		@"nWqMPdnQyMWWBOcSQ": @"coVkAryjPOQxpQEwloGehhmTTwCPasAEBzwcsgOLbhuwxGtCJVcRdatYeejYAzWnmgUXNKdJegrDuBKRMDRmNfbygRUvPtVvLwNGQiaSmGUqaKIoWPaGlgGBpecFTXHsVhmSIP",
		@"cBQcatCpeuuSHfedd": @"fIRJfAamcjtbasejhlvpMeGfGzSdGmMsjutsRhUEBzBOsGZNyvXPZApYZYFLQqRhMnbaLyUSRxQmjGQWtyolHPtsaPNXtkGLMWtzmcIuGuIsrkvHCazRxtzuhX",
		@"OnYbvHRpNAJKKIMrP": @"EEdSBrCyawNxpCKAscQRffcZTNbaitHLOGgfGhfnAheQwUDgqlpOIkndFjPLGWWuOYAfdcMiJjjShujWLaAvPaZkfrgteoyIIgQcszjvHFCaxjXMdxRrO",
		@"vvZDsXKyIDXu": @"yhfnWCyRrLiKjtTWcKrQTgYPCLxucvuLoRBAFCiXgCeKmzwnPZfEovvYWmRrpVGiVfIDzBMKVUtLlfdROCdmrAOOzQADiMPTYWtprVIMpSUKdunfgsKUyweiOSRRI",
		@"GhMzGiwsZuypYIYLRrZ": @"hjjVoSVyrRfgUucyiDPnYFFixPNSjGyNebwEVkKbOJWKhKuuUaLwVsyOlWFSgaXvFNuRCMWyaWtpyMuyWzBYXvfJMzNkDmTXNlJlRAhyUUmyxgpBIRTKwvmtQUnKvwkW",
		@"EfKTHDlVcaJKdXL": @"rVYyKYChPnVGqWMdnADBqIcCuPAJNVYpdfRuamUHEVQZyDPJCCkBbOUdaesPtnfrhHcDuHhpUKdkRAQXyOVYheKcUgJeHHLyDYqfepJT",
		@"GMIySLsWVoHQTS": @"mqumkxjsBBOlYQJAVBtdeQhkIiOIMTmLLloAIZYCMNllEBtoImOazfFiOnRQuMrGItKPvvdrQIkvHWfOykfAuJbvoCsoEUwUHictPLSUnKjjgVORcQxBbg",
		@"rggtviqRQoBvHWdkUM": @"ikFPNFBgkBORyPsHeFWkKsyHzTcJcvYRYdVBKSoeVUbHlErRFxVNdEPBufEkPAPWJwrarrnXZFpVoITtkZpPoWTSWcLjiVlEIcaiAiUEGjmZvQBPdKeFliLalodlxYWIl",
		@"JQrOIYNPsPxgkxd": @"pGBRASeYNIXaeBFQXxebkUuUIoMlTMrpdfpvmFUJcpwfSrgobpcoVFUCEBACZTkrCAvjetwInMAKwqhwSjohHdmkzUxgplkbgJFSdSGoAK",
		@"hEiZHEBFdaJcRRC": @"voqvGcvULEnmIQooiCVdnQOhEfBaimdMNRxWIDOsvvutDuFUgyjkDICgvbRAYEjqQxeXUxuObWVpVjHAbLTTAcfaOjVdAlwmVDQVwKEylQnuGKm",
		@"uhgAWgKlDGeCC": @"MLhjCnhsVOgUcoULGfgxsFgzmpuGxbeCmAUhZHwRZoqqbATVzFKxClLxfrjVBzYrlLtrYdechFGZOAXMfafndcyJGFmfsYKZKunVubHExzaNpfZzRncFvOqRpBDSDKyhGRMvvncVnSmwcirQnGW",
		@"wGOKjxqhts": @"nckXHMOJxfvNPDKeXSEfdUmBIRplgTsaocljlQxMujgxBHjVloNhwcQgspqtAMIoopUBvSVICVmdgvdRdPmKwgCtKZHQexWwQBndnpwedxAAZOnZQGHvjB",
	};
	return rcjJjBWiOUydLnZhFHE;
}

- (nonnull NSString *)jJSVXpwUxayNhFeGY :(nonnull NSString *)BQbPjpudXosa {
	NSString *DgiKHzePFBzZGsLPz = @"wjnxRaTUPEepVPwSDWWpJBgozAiAqBbRNtAXAyssxsDNPSoRRfAHMoGVkUVUfKBgPUkKiitlJzDJCnWHlxZGYALRpfXcZNiinZCHpxtHPHYnVlhhFT";
	return DgiKHzePFBzZGsLPz;
}

- (nonnull NSString *)qAmAaqLwHigyfMgIRFk :(nonnull UIImage *)XqOZAcfOIcpL :(nonnull NSArray *)SDMNvcBQQFnRKaqjNor :(nonnull NSArray *)lLsuuMtvaZwrEyPQrPM {
	NSString *gFhpkbvWltKUdXv = @"kqtdIwpHVmMSAEPIavudbYXDYVtPhNXpDEcvMILDnBAnpZqxaYvjrShkRGMbGvpqXcUzJtYvpwjNsqxBagZPXSTahhakEwzCyVndWyXcwKIyxoRhW";
	return gFhpkbvWltKUdXv;
}

+ (nonnull NSString *)kpxsEOFQBaUoDDqlys :(nonnull NSString *)UcNPYOgfuqxctAuOXn :(nonnull NSDictionary *)NaVfOmrPBccwopA :(nonnull NSDictionary *)bGFgAdkSoXhW {
	NSString *ZWZNaYiaCIfLCoziCEm = @"wNXBsFNEwvHErsHRhTgFUICZuikZwldqHWJFUtnatYnOPrZzmHMMHPORhcEKEALCqDbioZguuVNLEivbuccgLxfBcQfirdSiTIGGvpLdsZDFqmfvgfttuwheGg";
	return ZWZNaYiaCIfLCoziCEm;
}

+ (nonnull NSString *)TFUCnfayNoHOciwshXc :(nonnull NSArray *)AFBYSdScopuGb :(nonnull NSData *)ZHDsHNGRtnaDHsNVJ :(nonnull NSData *)NstMLZvpuofjPRFSeF {
	NSString *zCjsSbZGbwNWzEd = @"nPbsNamJntZqvqsrQPtJangmppjYfRpEBIiNhYheVXCPunbUlryUwXgCOBvsHflkdaEMjOsJNgOhfNOPMSFhDPsiOhErMRWYmaEgPKJMvZbjHuCUgQYuXXABMnRYvSQEIpphDHZYrhpjaNY";
	return zCjsSbZGbwNWzEd;
}

+ (nonnull UIImage *)mwOYpLMyJKcAfAiHJOu :(nonnull NSString *)YtWcHKgZbLXWg {
	NSData *AAGNBnwZbmyDF = [@"sCDTKDKTJlwgGuatBAwkVMYMusWDvbqiXWJlWUwYpTlLgixlevooukrvimylVkVOWIkqZqVDpqecbyPjkwZpwfCBHYtJvtiNyCurOMFiRcaiwZbcDKIoJAbRZwVoYQkkILgivrkHPzSkOSZJquyoz" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *acavjqppdF = [UIImage imageWithData:AAGNBnwZbmyDF];
	acavjqppdF = [UIImage imageNamed:@"wMyYqgsyVmvSPMcGOmjEdeaFsUHDDMIuntjZSMflYzgnSlFkPApuuxqrvcUxrEiCXoUKQJXIfmZGndENZqKuZTtIkfqBtjQEslbCOE"];
	return acavjqppdF;
}

- (nonnull NSString *)YEeWoSylXjR :(nonnull NSArray *)mOjloFcFyfDCXpEvBv :(nonnull NSDictionary *)zTyacBTxqQXDQzJIxB :(nonnull NSArray *)cTOXHnXnqenfmnqNaj {
	NSString *ytvBbVnypUTTUCEdKV = @"bHsQFbxtnhKHeqcndhxigFbDVuGEeopOUjovxafjBRigrbtMtwCBFnITgiHlSytvDMfemqsolVzAmIlEEQfkQtKUnZxLXTDKrUKbXykkPZFlprxrdbPIDKEBJ";
	return ytvBbVnypUTTUCEdKV;
}

- (nonnull NSDictionary *)YMisUOfPBKkjble :(nonnull NSDictionary *)CHFhomkAbRZIZTXr :(nonnull NSData *)DFjQMWuMoYUOjkvY :(nonnull NSDictionary *)RlaaUXqKTQLivPeTUMB {
	NSDictionary *ARgRpFsfjgtcnVJLd = @{
		@"YbLYsYZZZLE": @"IRLIfaUsoRmrBFhEBrTGbBDyhQkQgCufulYloBaHFhmUuptlthGMuetxPmVGlnosTmCViMfpRLyAUZqeknmLhHyVNUknoJDbLJzPXuncKMspyMwcpOgBUUhgRRCWWqgoVmdrTvQqFYYrE",
		@"xQlfTvcQCnzUlCylfp": @"ArKICrfnZrHhTpPQYYQPpwodUiForDgttuXVmDoJeIvmmbKEgYjTqUAsjRsyTVeHjkgMPFuaARbAjEbgCdYhqmyYUGtgrYJYmMcNzOvIGYMcKcoIUFdql",
		@"FQcgnwjoialRTiqPfx": @"owrFxJVHYAYMqNHyPIrQDQhlnERGYpqoVVkhkpwSowfONVQAAVGBgYcWqJgfzpwwVpFMkJxilLjMRZVIpxLbNFiVbpQoeARNrbgU",
		@"yJkQQEVSKzQ": @"JbAqrCOvrTJISVuNglxVmpnuGtehEHwNoGxuekhvekZumGJtyHnGURTAVPKdhLsINlCeNMfzVplTQkwKzlLOtSnWYfwkyVaZQgtlshlRSqlHUzBUHfEfLWou",
		@"ucHUkvRUZlqHq": @"QkHhBxXULjRwLJQxyuTgTRGWqXUJxnosiRODbWbvMpPhcgiDmJyZaJGqHppKvhbJGSeoUSCfCBziLhJRKNxBAsXshgZedmWOymTnqkxekqbSnWd",
		@"QKrVBorMxHQZXTFadRF": @"aEdWBvsUJyctKTcxTmGhLPkmeKJJPOekNoTNdULbRvEcPozNczAzMYrVsMuQHKygQBpDNFjJNXJgziVxplfuErUVuYkKqRQAviWkLFlQShBYWrLLNdmCMuDmBHZ",
		@"ooiAoNsoGMuXz": @"jHjOuwemsmaakaShacFYInmdZrfadUoiFIpliLXWmUBBXytSxSaIpCfpMMHgBThmgkXZieHEULnpCDcrwWbipQnqCVuDBAtnExKGFakEbue",
		@"cwJOCSIykGFykk": @"rLuOpoFDxDXAoNDFiQsFUFDQSgPwYuatSoLgNxhrBBXWqjnuqRUFmzgDFcXFYpoXyyCriqlWaqGGhDyKGczvjzVtATTZTAsvgMfSceUMjOJgbLojbxygidwpMiGhqAUjTlHOXZw",
		@"CTLMLqqgpUwaX": @"gFcKVuqyOybLtIzcJEFwXuGjhdkjNhJdltDqswWzGnAsFgGpmafXvYkGmMtXLASMQFgQIXtlJIqdBksqJYhmjOxHAjcmDSQxbpfBuIgttcSShsHBsjJEudRJzuucHhefvlqWsaihJe",
		@"jzJRrcMqRFBXJc": @"KyeqeozQTKBLSSmkQDRyeRlOXyRyQevINrVcsPRwIriryBhCQWQRJyegvqCySesOTZNIzxKStLaSdzNWDWZShxUNFlWRyWBIIojIzbPHxw",
	};
	return ARgRpFsfjgtcnVJLd;
}

- (nonnull NSArray *)ilCtUakFBPZB :(nonnull NSString *)HHguobexgBqXLZKpR :(nonnull NSArray *)nCCAqxLTpAkNeQtzdhv :(nonnull NSArray *)jmjpYOWhZyg {
	NSArray *jNnnZrizakRqUKyrMym = @[
		@"MSqZRXwROssUKwtLRLkyzLkCZEgJoUZYmgvLJZLGKtKJiVyRrwNVpLREmzcsqXWCClzEGIgASmqEuYUUxKKxmyOpBOXJGHBLLeATDxFAvfXuPRSLTlFDLvOxHSRzvXuFqSNcxX",
		@"tQlTwUQgOUPIxBabhBRNcfTolTrWCeeMyLjDGJbZAjsWYvdpuosmyllfyOEByFxqZwwkNVVwQIKPIEvkwByYVXEewTLpecmXwSCjUKxHPpq",
		@"iwmCTsQRIWDwSfoJCGbCZqRgapOVulxmJKWuYqjFkMLFEqgFRhGHIhQLAhEIghVAWasXCziZeXsjcdtlRGpubFBwQPBkXgClFmkMHjATrUpm",
		@"iLRXtoEAibCQoYLILlnBYtVSMnCrdoivQhySBOlBDzJQFASEYEeVaPwJhCmnjqBAunxRotaEmNWGOBqHafQuhokGnVrcCyuyZSNBRazORlRsoFgDotFMqKifokqvzNaAni",
		@"hibbcdVrTeOPyuVHWeyMiBcCjyALhyPAyqDYiztNQqRQUSEHfmFDLAGUTxSdipQqHJoFCJrXMbnlGbSxNqRXSMDPgMcXaucrVdfCSrmkKKUOEXOI",
		@"XAyFOaPvruhPOZofKWHatasRzfWxmZUULrjZwncnUtJAOfEPaQFCiTJvaHTyawUSNEpibTqkArRibuAMVyWzcZOeQoeRqszqwRjRJQyIVcVLHgtBENHkaUxTemdbNZogEtYJYYgIaT",
		@"bYEcNXfPjuCYEAYVFVntCchBaPNhhoZTmxwNexnzrXdezCITMyTifVFVUorQjpprSQTesQcZvMvXTzWhnZwrmrndEIwDMtqbvWCSrSyanzxQIZAEJWNSbyiN",
		@"qewbfmZRiOUSqfgUlRAlcsHZEUISYsokaCcoMbXYBcceCNkPFjggYsmNbMejmUyBniyyERXxAaGgAqCEyiDwtioFEVQNpYLfshDiUHEoDKQZIv",
		@"aZITDCuzPNCaVsmMxtqtanzYVQcYrvUuQUpXSaXClQlKQQThCsJrtteTNATXcdPZqWOQeAjHFRBnrFyZuHpzgFlFxXKVnmRnItcNmuLvayEEqoWnw",
		@"MGHGowOkYkpPECZjZqbywAQOnQSoqLdVbUcUtefUMfhxHprZTVMVSzASyIUKoapWugrPfpLjEBOXHETWPFzPJmBhQtByzhXlyaLJKHEQPyfdAlm",
	];
	return jNnnZrizakRqUKyrMym;
}

- (nonnull NSArray *)wIfeNbDRdcNhwiRCvS :(nonnull UIImage *)ZKuPSNABQyV :(nonnull UIImage *)aLgNLLWevQRezRVEKa :(nonnull UIImage *)eqtTJpgplwCmQ {
	NSArray *wcSShBxMTezLhA = @[
		@"khSvwYJzYHNsGRdlUgiUjQBWlaLKyyhPnmBxHyfTmgORtIjKqqSSEhRDcQqQDfwNbNSwtjiTkfbUqTTzUxinOPwRbmmRpVKXIkBYAVTotjnFOJUcwXMFGyVZIRBrhmfPDmExvZa",
		@"LXBlWWNFVihYIMjUFLSfxokTrvBZBUTSlSeiaTokxVnuzzvyxkJMKhRFjjydlkzMQkqZxqdqclSQoBmXxwKePMIYofdkntnPqxHW",
		@"ChvpxDYGsNDpbuyHBIarCAxwaNTEgOgttsQdpTxWqkiKNLvXTPmpaOQyisCxfQazdFKnpmZelLmlDgVXOSyWMDIbcCaOmGDxZXMTC",
		@"MymWRQvSmaJLJOZDNhQUKMDcdlthIipXyStMrJYzERrhkDFBWbIGMJkWSHzZeZqtApuazibIFtCQDUEYeEYwezDiHSofKRQHFCBlfK",
		@"PmsRUBDlKDJluKGbIhQsOxMjSmHNQoZcgoEQrjlIRVTBKpHbyoZzrMgKJfObqlnJfxtjKkPvIpkHaGLkeZfkhkcLlGCLOWlFFdBHBJnEhwHkVothTyqzjFGHjMVGewmEXEaEaHuyGvfzmDVYVQdu",
		@"xenlqsbCyGmsJQVlMeWELAgRDVyURHhIRHIQWxMZUMvMuqvWvouQtREXzboyYBeUhfRAlOteIOYQXMqFTyZarOIkZYcUGdiHWrDhQXhZqGCRUlgKfvmLIPOKyjcUXMSMVPOUEHMSbIM",
		@"YeppAhPWfuRXQioxFYLviBlxFhRptKQyRmoUwbWPAgUZnMPKZsqAAxUeGSZbhhKSEWCJjpyLhsyvBdvMnLxvmHfALIFIjBYFjOesXuavxsPjmpRpehcpPnFVCnfWlSvBdMisdQZv",
		@"LXcNsGzYPDJERuPczvNDEmJCJwRbQCWHPNmpROPUyHvzbqprZxYWJMnWJJHZNspcorEIOhplwqBFNeYYjCLgQpoMVIDVwItGJeAPyfILErIPIwlqVUMdbVOZYKmMsYoYWlaOhxpiZpxSEzjrG",
		@"ODDOtOFNQtbDIXYFQkBjwOhyCCeEjPXHidYFXQbOyVYUrIqRHxpEEcJBTmMiQXldGWMUVjKcndxfbuMkhSHmyCnMfAeRBhuKdwlYABcdDhOTBAULszOOZYTPpnSGdmdNxHiOaJvIfUoIvYPHe",
		@"eDAMiMRkzQDybrPnyAWIQMbIwspjdjInmYepsQcqZLCszgTeSolcCaEVgCReVjABdzWLVnxnhGXEuaUyQHfMgLpKxMAEPDXSHAkiMDBEYEHrNiFHZaUobBawMeAIhEZSDDuIfkgMfLdpym",
		@"xSzMDOplzqWUqCWCdQpaKiFkhlWhcgbXcEjdQFhTJQnEUClmFXkPZTRMuGQFhqreXLbpsnjrmtaUfZGvNufUttxlfnqebyxVkGJZTOpARODryLBUkjmtW",
		@"AcvMjIYrBKwncezNNzEEthsByDbBMlaCcUfrYbfYPTjJlKggIexsrNTETEeKFYiWiNnLDOVqXhqmMMWBdkaXMNDxOfSeGnBOhpbidhJDKiZH",
	];
	return wcSShBxMTezLhA;
}

+ (nonnull UIImage *)woPOlDGcKvLDm :(nonnull NSArray *)dUuWKEBiFkoTsWfAf :(nonnull NSString *)FKTnUluQFWuO {
	NSData *MQDwNhZOaqZdVQUIKAv = [@"IFffINzPVNaRpeoDJNmuIzzgKcxyHZGijJMdIESBcnRtHcxIoBBHKKylnwjcjRAMpVeyCDEgsopLnOjUgbLaNFjJItwPalpCFbWfBVnHOAHmQCeFdPPJnSaocvkHJ" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *ZWpkFbAYOgBPVor = [UIImage imageWithData:MQDwNhZOaqZdVQUIKAv];
	ZWpkFbAYOgBPVor = [UIImage imageNamed:@"BQbUWrBxtJKQDFqOfwYgUdMGIOhABxHSRlWHUQMGaViHhDaiqVSkXkRAQuYKLOvhbcjMGZmXidmKjcIgCzudPTdqejEngVBsAdbGykOarGMRGvwGFR"];
	return ZWpkFbAYOgBPVor;
}

- (nonnull UIImage *)bLspTpgUDSUrfkXXH :(nonnull NSString *)FuOAkoDjARKqk :(nonnull UIImage *)WFEggyCFgCe {
	NSData *oHDdhkPAuPyE = [@"KJpKNiQOHhEoUULmzUCQFGwxZaIipeLeZoqbhpCynyNvTVJtqDWsXWaLOGdKhQnIsLoPuWHmrzBeoXJBLBjeKELsZzMjdKXheyPrgjEsCLTxrJJFNZMLWHeiZq" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *CfvutQMRCd = [UIImage imageWithData:oHDdhkPAuPyE];
	CfvutQMRCd = [UIImage imageNamed:@"SJrcWWKIYBPhBGAOcunRmgHRqXKMowSrwmPAjUhOACPpVwnlUNqqXMwqarUwEczNvXlyoThhewadSpNWHWtgAByyMgtIFFDpUeEsTBsRCRpYBbycgKwuKUKhVgISOSNcS"];
	return CfvutQMRCd;
}

+ (nonnull NSString *)qiuivhmXcbwNKCQmq :(nonnull NSData *)EWKAVLMVtB {
	NSString *CtOlBqDcaVqRVFaOFHa = @"ErFxtWWfpQyQFoIRnPvHyKdBmAZUISbghPssFoeNZFkxNyRthOGEjzTedhdMfqWKUbaxNVFsbzrGUklXoSgTVzapyUIVUbigEOBwEUeqVDmLpuDBewcHcmciYllWYdEascPdmVI";
	return CtOlBqDcaVqRVFaOFHa;
}

+ (nonnull NSArray *)LwoaMdKhejrM :(nonnull NSString *)altIbkxpvFJE :(nonnull UIImage *)SxAVuGaLsBnkI :(nonnull NSDictionary *)mokyWMveoFiuPeSyW {
	NSArray *BSqCCsEJXMaWw = @[
		@"jDYpcKeWTzvtTCJVSeSwVQnfiqfwAqmveIsFDBdYSvVSRStvhLugvzwKoqRNRhsHZnahUvwHiRgONcDgOBcfaTfIidyOejmDTDxkfBUCtjfdfVyXaxWUpqZVBYY",
		@"YJlndYvYmIvpATlRmUXbGIuWTCwyFRNTfZiaNlGpLRpWkpSDuDDJkGIzdbZIUyNsKRPoeOBofetDofGAQvmjMInpxdUezurQSNuAuMInXUGSQMFCxgVeI",
		@"JpVnWmixaHaLGZGKanobBndqBoDUjdhrLFLzTMWpaKLcaOODFLYhcaiSmbxwKEqJSrjGtYanEQQIwDQTiRIVYjUfpKHADcVGtbYxFJNNWxHtySvHqQrBN",
		@"xyCjLFcfSvFuojmkzLSbxlaCCVbPpLuqQFPuvpdSWZkYVMPjTCNgIIybLBZOOufybZBEDCUAZBrDvgWcMQdeSqfUQewxgIaDprCUZGfbihaUWaUbCqAlEbJVILtQBZXWlb",
		@"THpkfkuzJiIcoavqtCUiPsvqKoPoncgMlTJgodHtOvxZAbuflONovVSoMGeiwfDKpRBEgOkBReGlfYFuQkOCNCcDaDMAtjLcEqYguqfhAyBUchiu",
		@"nxJQLUlkdQhkdyvUSEGmhGycNQGcGEZjKIDLwSfQkVrsVFquKntTlZMVTSyiOEEWaDQJQpSYqhQfOLXyheJhoXqzKddsITRuneWdVDijSxQSHZPdjhEArSghIVVaUNSQpQtkc",
		@"MylguSimJzHyZbNCvVzsPZOipHGlOGdsKrkTfJTllaFnrIyAxUVOjHYXRlPMGRlLngIrInHHcjLVhzIplcfdAjZtqoDMaMxftMmFqqRZlxHmtKusXarVNZmAUREWiTqbTHgx",
		@"QgKixBioNSQCDaiHzZrVDsiAveChONCIhnCdlpCKXjRKpZoDjpgPSBOsRTEcDbBhqXpvTxhGUTniViEfBHIbGSZWGUOFuWoMHJKiIdgnkrpjRdP",
		@"gfOGmToKmHOuplJNHFZwylmNbkPecyQxjmvdgrgDFytDkkrPpMqRcSEAkTYUfcPvNlRZoeJiZfLvGhExTuhsfrgLCjfagwTDkPHQzvswxcPECedgCIkxebllBaUPXChBcUbvsFnFOoqav",
		@"bHRFHOPygeBvzEJWHSivqAeZKdMnIwGPLYjKbJaGRCGmwIsrFVIBnjGcJHBVeQXCKGFVslZPaDufZtoYuYMYsGQEsISZdWDCBbhTGcmqwhSoCvjhSCUPANuuYbjUMSDppTrgsLeEOCI",
		@"fREIhCuAHaGMApFlZhcNaBfMGBcWuofUlyuiMPWBLIxtovbIQmMgIRXCTlVknxjSSXFvsnvaExCujictdczOBjezSfIMHPpNqlisWWZMAYUPJhXTdN",
		@"WnOqHlDDQHIkdyHuuxdASKsFqAkRtpMmmbZDGOdTWqTRhiFrkqQLbrwYGPFvxrauKszynbVSyUNTiSPNPfMgDNYcdciofnYAYUIssLmaUUR",
		@"qPFzUazUleuHRFItCmcdEMGfuOXSrwYVciyhAVIVfqgKngBvAODzVbWXkMqMdzcwrUViWsuAGCbnumEwVZnDcFHLDFvxwwcaaqKGNMJxFzGNekGnSVOSyPxMEkGqU",
		@"NKFWuPEaWApQIHztkhvmGjMbgPogSCobGjiCkwmSIWoLcizTeqvVvIcOMsaRwLFuvaUKeFRWSGgcjsllkDmofzcFVouNXRgTxnJFvzYFkxW",
	];
	return BSqCCsEJXMaWw;
}

- (nonnull NSArray *)HUTsevdijWwwGhJZ :(nonnull UIImage *)muQEoZTZcPXXoWV :(nonnull NSArray *)fJHYRJqZpMUMuBtD {
	NSArray *TLALcBBvxcnUFBapP = @[
		@"ZmBBbqxdSrdiQivjKHNdesaXxRNtWTcYOuerjuvkSKaAaMwDqFwQTFQMXOPczwfAJFvSqylHzOlArbeaDzSsklbomrLBIxpsxEtgwfkqNGNlYWXoVgrUUyTzrIaZSSSKuSznmPGwzyMrw",
		@"EqEilZsYyrguUVZwZCpysYKSXWVKRoGkiojxKesIJXupDytMMLyyiLgaAsjnmPDhgszmQfYLFdLeuLRnPQPpqMEKWATSIIvhgckFuHMnAAQwkVhvjuehCyDI",
		@"SrOmTdNYWPgwZxMDkkEQhgtgTrnrSovvtHvISWoVwGSEClZtnluVWhvAOSfedplSLspsbCVxcIVOzYRCHOFhOpJNAhpJSCBMtgxGUnaaFXlbGePyjWgZmPEqZtvwoQGi",
		@"qrhvYbazJVfYIUCsUCuNvqKZiSrGkYcTsDmjyxWqBsZFYeVecuMwoLtUhpWQLtNsskFgEyhwpFUlJykQRfDTdItQcoeGaNfznNfLJhtKLFvjbjUSWFnLUeolGGecGWHb",
		@"iQJHsDLXwRqMZmKiUfnBfSXWGdZmmQDjFLSvbbNNOGCWMLBFycKKghJsANnOTjeUEYFpTUViPUMpJlNvpBFIktKMntsRLPLVlgfJevBTyB",
		@"RotkppvdpXigZjMaKiOIOUYOoqVLCoVHPhFvOnHnLgYVxDZEgwJkFXvXFekKFvhjImrDyGLUPqkhfsnxYqOlkTnMosJkwhhiIRJxLlCcZlrJXKzskclZStfhHFqWHPWLrTV",
		@"cyPHaFMLBGBauPJCNrPJbnNCxQIBKowasKbpNAezSQIolnRwsTEOjzUKLvMvaRUobLqzavxiAduCVmURmmpDEOFPOGrmDpQCQLpMZY",
		@"hkFMYBYwFPsizEACxNQHLNUOZWrxJpDquERjzXXXqeWLpywjbnFbJxWjcaKbdqqeZtnYpeVAfXmwYXkYfnSXjQgpVoHNtLicoBMEfKNJNWkAqfWVXcCTx",
		@"IOGtSiGvtOJxtedGOwaBPSXBJLgJKrwuxVlSHFPSsDbbnPJJrWietcxKYROxIaEApsCZhnbrpIshLITMJGHigbqqogggQsKfLDddabt",
		@"wnHJMJjNsuIuHdiWQPpqDrXZvOqIgZEoFCHHBzxdjzrryIMPRUufTjCcNsPrGzhEcpcdpzTEIsxRWohYbKyWadeBKgQHJXHyENTTNxARtTdEBDINICXCQiubfmECVGQIwQpoZXHarvi",
		@"HnpgtXxSMzCqDlOhImMUZKnCnxnbeMxpuPPgtpKyiWtCiGDwyrpMittFpWfRrFuhDYlATXPYiidSohHlQGWXcygNPOruiEOjyHOeTPhBNFrFzGVGlcKNUz",
		@"lProoYgdGKCsTPqEAnQGeZYOXonimpHqdYMZqWSyUOSZXotABURjWjeEOdmdbleQpOTtXSLiMqFdLYycaWCxpWcbWEamKhZonCJCNeXBTOkOuTekAPHrhSsPASdApJdwGEdYCuU",
		@"AKqViuyqMJVFcCyXzbPZLsowWitAzKryZVxcOgMpQkJaGGETytxiFUetuoEBuAQZeJLthUKwpgcTutkWuVZOacvlSgaJDdCapQKDkBiXpwVxpIotHLjHceNJVHelcYtEUMvOZAFsnmSeyaowff",
		@"KeVHWVrqUCWfoNKnHJYVwlmKXbFRDlxqFtZpzxvtlPocSNfyoySbSFUsmZWlmdWEMqNRRusgkjPUhOMHVlSbFfglUlkwXhVdsxzyASkkqFKCjvexhXwTjGFKdJwgi",
		@"lHKSZMSQZZnWgaGzJuLfbCjdZoMQDSjztwMfJEInsSmDWzmHXPBGOvYRsDZNWIkhHUuyglQxVpCgeIyKenElzFgkpKVVYpCviDvOnLOuyHSPUyqgUvQgSFQsFFwqoSeaYmwDUVxCMEPmwdEJmv",
		@"texTiJElgSdXjZPdemEHSZavZwQBqSSlNcdAmTrYzNSmdnrkpMIirYLoftsHssfJOpZibAaLkkvkijLBtCXhzXFeZTuLyWhtbiMEEAP",
		@"JPltUNfrUteWdjesSrLDPKAVJzmUHWhpnmSQdcpSwNnfJjoBtHGcHGkxsBMkvIHxZjOoEAtXuoWqSfyDRfvcZrUeTpPzPSWGOjIUIvBWcjFUumXEqaeVH",
	];
	return TLALcBBvxcnUFBapP;
}

+ (nonnull NSData *)VqXpKYIyQiHDNfYfdUe :(nonnull NSArray *)hbFTdMGRWK :(nonnull NSDictionary *)ZubrkxCWukaWJCcv {
	NSData *jeGmBdewMiWUtBk = [@"LewPNOIowCubMBrVLTXEIcqipZVyMhudekYOcXyCiESeqwdRAWEAgbKMUMvpPkRmqRXvnLssJTrFEsUkGBQGSKcOnkAAzeoZIKYizBCbLKX" dataUsingEncoding:NSUTF8StringEncoding];
	return jeGmBdewMiWUtBk;
}

- (nonnull NSDictionary *)nNpIUJlEmjETVQ :(nonnull UIImage *)ZFeNBAIGuPyMZCeDDSo :(nonnull NSArray *)gExoVuJmATlAFUl :(nonnull NSDictionary *)nXLfiJKZhoTo {
	NSDictionary *kfugrKySvhDPZ = @{
		@"unaQDCvkTsxOv": @"gtxJHFNekvCSTSUkCVJDasZUxRQTqrpbbkmAyWcoEvFbVWHHGvlJkKEDRpynKtDulsrzlhNuujlJErVagAxxNeAXlYwOsyBOQSaRBQrPBZZc",
		@"AlfsEEpeOyiG": @"FtnsBpDAKLXshJFzFfdTtJtwLuOBcRsdBPEjSpmgFICOGlHThTcdDbdEOyIEJwlSblrtwKRFgrKcBSOOBwyQrufwlBhpYmeTcFjlF",
		@"HTnTrwOKKVmfdGmO": @"cSqLAhczAryeBiZUKnrctkfOuYVunsgYUQBkuQxGgOQrjTmkElOIRGBjbqEqjbiAtdAjdCtbIUHDucgYCLVfJdQyfyCgJHYGyuWCMMKdYtrUQowXVnCXh",
		@"ObaKjnfKWKNMJkHASH": @"NtZaVIQyVmyalfFUMzOMNIGXMWnsLErkUCbwvWHqhGDAPobTXeyeiAqvlQjhpvJzRDehBdztXItrDrdCYgkLvOOKjfIFuTLXXDJdgatPrHmQdYROpPFqvGYYjqsYuiFBAWtdfmOQyAMoERBZhh",
		@"WTLTmxtgcEDzeK": @"aNaJEdFvrQTNhlGVVjjlpSRGecWVRjCHYpCKCJixaBFwfxVruNbaJzswabjXoNfAFsSrvPslZdPnceuQMXPqKiUEabTpJccIygBAdIMtcQpxcPrCKPxDJIfqHAkStTRezWpuzqoYfk",
		@"euqsHiypSBKV": @"MaMGrTlTtalTjsQoCIXrKxcBUyFOLHIQCGMiVZXPQOstpQnwZOlHUTcrYNAiEsOckUvgNQnNsQMjFyXdilAqleHblwjmyhTeOthMDMECan",
		@"RZoBEfztEuigHa": @"VOOQrwlmEwntxdAGiiGeHRkGuBeiXFVZcjMmzdOxBxIyZcIxIBhcjQErKOsrKmtOJPTtasYjGCqrHTQiYItgkEGHHpwonEcMVSlopoymXluWNHszTjdBRKAQ",
		@"uhzwMOhXnRFW": @"vjRzCzwDnGGTeaMghuchTurCDGbMjAOnQMHVWAsKfAlhQCveOAXZwqRrWTDgELfkTWQzaoQDllcmMfUGvjivdWAiAkyhgqAcTsZDisyebsIoZsBzDPFAhVCz",
		@"jEhpPpQkBTvfv": @"pNAtaPFjnxUFOOgEibQJSuSoqapWZahcgfqXDrwTDbRQtmzxKbldRSjEuUNPINEOBrTEoVuwyNqbYSaEPPMwNIoJNsZWmOfRaYgjYkZLZqZXYWLHHnovEcXXXrNKBXoircmfK",
		@"uZRsfxYBpAV": @"SdcnWQofbQtPKORLqsuaLzUqqfNHBllGwjdnFRotXGkACVzfzQWpvyZrPApPmziQummpEEpFppWZwlKMrnnwgIVLxAMfIPFegfWqJUqCLxRMyuBnQgyjIVvHXFZWNjJpravrDSaOgGgRSGvhs",
		@"vXKrKfDbwimedN": @"pvsuSyWlCDyRyYdGyRHBJaQlFfAGfUNdiCpcOhVRjODEdEqnFUPqqgbGwYRAwntQYyUarvhOFFBjVxRiArzghQfmkGAkZUYQxGqQTTvrNRHXTIdEloGXGpeusXVPXZxnk",
	};
	return kfugrKySvhDPZ;
}

- (nonnull NSDictionary *)qFhQvyLOCgeq :(nonnull NSDictionary *)HzzselzFOskZ :(nonnull NSString *)HDfCtQDlkQ {
	NSDictionary *oadgoacJiKcKQU = @{
		@"UVjnQFAQRbZO": @"NIvxbEgPUDqFGMEKHJuHDKZfYSTPYNbILoMfcTdzCiBWXXOzjyBMrbHvTwwbKettuEDVpraQeJPHjyXWBjjTptOArFXbVjtxLgbNjiSb",
		@"ugAVdFUvSgonQC": @"DbGAHNbyxfjTNjNghwISSyldeYScQqeTYxFvaiPqsFDJbgbzjiuLoxKjtQpXRtrhUJuTvDlwHiklttZJRqAVTCXpqWOMNlmnYVqyIHYmPpCiTEkWKnUU",
		@"fHAJDhkkWJEvf": @"DpihszVhMBtNqHFBByDsYKUTgWZTIGngagZTyYytHKGEjDlzChjfZuGKKNUjEXWOpllUCGIHXpZvRuNDZfzaRCRjQroZSTonAJBOWJxvsBXKtouBYGxgqXwT",
		@"VcRHODVPLa": @"pQLxRAQGgQCXxMCitnLZiNPXjlQzImDVWvksqDPyRGBJhjLRovzSHpVCrxWZhIXtaQPAJzqgWrrmxhbzcDXzyPEHqLhRFiGpldyxxsZGQKdxIfLtQJLZiyQqpXtWrytQDpQCVpoNFNQdr",
		@"DRYneFmoUTSev": @"pVzzqzxyguPlCRsqSbwMvyrgQkYaVclQaqgHlqdJshTirxIKrDXUlGqMvnCXtfkTUzGqlOIPJkwVQirGpECKjjSiMmQJZgkbZHgToquZENhARRCVmMmbReoymxAXwlixHDXyioMYXifLva",
		@"xLfIpAKDmvlAWw": @"PwJnlCrzaYDvVaqlyOXOksvPoklydJWZlxZtHvHuCdLQjyALggEJhfNKbMXWarNMRjAEnjggJvTUxPSThQcvFjbAwuEQcnQhTKhGzabCRTuctwgVgyXIjqPLM",
		@"HgOTmPrAbCMsMFQL": @"ipFEgQMhcZrIUcZvnwIHIGlKFeIAsJicrfXdkpJlqtKhqHJyqfOwXDIvnEweaoRHcoMlKmrAjiEDObECMvJfuvAAlSVBUwIyGORsYjRgdRT",
		@"ytCePQvyfoFWwpEryRQ": @"sObYpBoYayFJLanwtgGjpKTLVTzkRKRnWpTgDKyLLEHjflsiLohuxGcOrQisVzsvCgGrwynUqdzZYoJdlETMliJHCRkCYMnhMRGnzLuUQaeKJZlKYupSPNWJnWc",
		@"pXOHJrNFFDkHxwoVzBO": @"EPMESOvuaCtMeaebeIenUMNtpQbpNePkGMAhNsYtRpHyXeSohAGIGxdVDpVZswawmIdxUJcduSUSnGEYXaQAVgCtOstCnHHSGZofLEnYKyDBRxHcezuTv",
		@"RohxGeBuFwQw": @"rAbeTOrJTJwCnPyvoDPPRvteJlTqHVkEJeuqpqxVXpqQyKRYVKCUknFHAimHjjmfAyNsKMifOqhowptbzQFFQogBcaeExsngqJtkmskbSmJnpFWlfuw",
		@"AKjXIAeBiNF": @"QCoeUQrVzXApzrvQnecPEftiKGnytlQGBTLJyAiLgVlgkjWxtOMxpYDALrxQbrmntYbNhhcKDCQHkfYIuPgNLrDWrYNrCxKePhXWsrZJokPUTj",
	};
	return oadgoacJiKcKQU;
}

+ (nonnull NSDictionary *)htsuhTteMFCOK :(nonnull NSArray *)cGGFqZxuJIR :(nonnull NSData *)rRyKPvnkRWtY {
	NSDictionary *DehQhRqgJeUnbRbp = @{
		@"wtjOfrNBXtETCZxw": @"UXlwZluSVlMArmOrBnblbsKxnbEWEbzlJwojTKNajWXhVTFkMoBEwPcnIkCqOaldxCjqiznrtlTYbjdcqIDOqAznufMqvRhwlDNthyXSgokRdaoymQMRHIrqgnAExgTmesYAriYsFkTgrqH",
		@"hwjziuxwgAe": @"wnSLFOBwyMjbBjPeDrTzQcmAkvVYXRTsVLhSmsZKlrscUksWEuqzyAGaYLprmeVbYMXWSbxgnTPiLQxdfWrquILbLjyuhpfRYEwaRdCef",
		@"AftAUUIpsQlyku": @"ASXgWWKOQcCbQekGlMfQCypDQAdcfGunSLxtbFIysOQDFURveRmDuygxiWFvBMBUAkBDVTeHeRogiMugnbwFAWwBjLrlgUaJYumpuTCsEGkrFpAVyMOjhAtZnWQGwosrdTTGqmAB",
		@"pNyyadoUBTojkC": @"mRBIaAXCFdXUXazYwJdwgOVuoMiYbiAXlRftPaBEvOnxwKTseMleuOwQCAzIXIeiSiKhKltPlaRPVnkLANFWfgqWxsYwkwiWnBAUScZJ",
		@"MZaQoPLJhqJhkcZZJLV": @"PEshtrChSMaVhVkssDyYEkgBDMdLhsWXtOzxDxfZHVxsPbPQAWltLGJzEmCINHcHlqFWIaRHipJnTWuVgYPjlPRGpawUQYJXZDQNmqZCZbItaqVHpqZykMXIKdBCVcJAoXWqNPwWZUPqNEPF",
		@"peooWisrFLigr": @"iBfYtNVcMfZZpFriPNeAwByJQldFdwNwkXNHdUmiQdfcDLGcQDayyihphulDPacmFKXYaRyusLNgcSvGjnrMchdiWPxJBmDJeucDcDypUEQvrxtsICgatiiRYofbfF",
		@"jHhBMfExsStlN": @"ulOyxXdVfRfOQiofigxuNJZIwuzmhwsmezMKeOLpLKSzWKZTWHhCZGktFsYyYzyexDpeZxivGvHmusvhUGYbkewPRJAxdFDufOCGnxWkEJBFnSDrsLDxZZuhhliIvWZxBHy",
		@"dOSKHDcchffd": @"TserurvFdXfZmiJCTCAzUOokrbElfpBjSYWwHXVceSEQBUnbLIhecXjTPCFcTcWTdBiVnRQPCVzoOmZXPdMmGadyEYiDOjrKDrWmfFqPtZixTKmMmxTmgfjxCTsxmAFpKbVu",
		@"JNpHevSEeXqYdE": @"QhPZPioKSbOcTaKkcDSMgnKXoMLzoSEhGkrilcbNzeinPAfESUDsIuctRMlmchTnNMpedunRrCQDMuNSfvKLlJNDqPjgilIOJTUELiEAoDQgGtyHrnWlDtHEaTM",
		@"OLjSGyPrVEjie": @"XrnghNnkmaIGXnoFREcfGtvIlwsbZAgpJgUPgFLgPKpCAKzTgtYGSaqodtjvxFVFRwvoVhwXmeTbiWFBZQRJIhtZvvcbNFGEUjAduDphuQbIUKTvkLfAUjCZqCfsdfViDkXDQqESiGp",
		@"lRcHzcsoJliXnTniE": @"XukzSRHhDwDrIZKWMNhpWxkisDmBYahoEulanKpAUVBJMGaScFbkedNBjUbxCuaHeDMLnZdsfMaWcIzWsexqASKZntIRUyYnUDmqGnnhcQYGVlOOoqygtbgMEIlpAkf",
	};
	return DehQhRqgJeUnbRbp;
}

+ (nonnull NSData *)hBpMMvxSqsuGuElpQn :(nonnull NSArray *)GYWFhEtIQUKeU :(nonnull NSDictionary *)ulFCqjTvVsm {
	NSData *QPxoOYniiYqwXEWHTWg = [@"HffDoKsEtFDUyVgsEgoOUWaGZTYLQWStrPefnlCplTzsLxcwRMeGwJzxbtHOodzBlfKHOfrpfoKkoCiXxeEOwQEvNyGUrDZmbuGMuRFJ" dataUsingEncoding:NSUTF8StringEncoding];
	return QPxoOYniiYqwXEWHTWg;
}

- (nonnull NSData *)jIhCioEqvuNfzhdLHC :(nonnull NSString *)XWBKrFmjPHfa {
	NSData *zYtjevCYIhUy = [@"leJXJQFYgGUPpaKOpoJIbzcOKOJaIWmcgXPMeFoKWVMZJtYMdPsCXzQOBLJONBiYAaqlBZNSWALKZsuxvKRFDTwioRyaHPiAVTrwnZdsEanVvYkLqgWTVmvHPuzEEIMyrVfgVmPGkAIDzmK" dataUsingEncoding:NSUTF8StringEncoding];
	return zYtjevCYIhUy;
}

- (nonnull NSString *)rAoVqfOoKWKoyCRKz :(nonnull UIImage *)oiMYqnEBQs :(nonnull NSString *)FgWTJrPnrgp :(nonnull NSDictionary *)YgkHkcqOUsn {
	NSString *wAtjoCvgoSDEeekbLQf = @"vNsZrAWuBbpZGSujbQGFVZRNxHvyLSCigyEUQYnlCiDVvzfcrlyRjUNtuaQtzomfOptLqRvJnAtQfZxtykyTVTboNlAIjDSqplWNNwCYBfyoFmWXKSXAFcFNwjpveUGFZyrhPAA";
	return wAtjoCvgoSDEeekbLQf;
}

+ (nonnull NSDictionary *)fTuNcaquBr :(nonnull UIImage *)vFxyJOzyri :(nonnull NSArray *)uRwSPalWtbiCaG :(nonnull UIImage *)aZccrROsFooKKFqMaC {
	NSDictionary *MyBGxZGUrcDdKf = @{
		@"ustRrJbDNWiqkhw": @"uCfXcFNUVPhbmoPrNaYjrmLxoQtxnjBGHicRnQtnGsNjNynmcqYonYcByXVpFldWqmTjYfbuBSOFoAkcBlrrWeuffYcpOcDTJbHOzkIOqEaqiyUYKMnUAtckYmRGpDRphsZwB",
		@"WqBUfqghszLkWoIhK": @"SdxIOMlqIWqsTSrspNZomEnlOiVUwoqlZUxTGCyVqDJEoLteqdrxqiAzfNlwQPxZkjdcVHSGrGvQNDVZDgXTxooRyZSKsZHQOylCkfgpCWSxdciEahRDWf",
		@"BxjUTrKjQSbomCRSK": @"PskWHwBnHdXhWTfQpdfUQbCEgcmXpzoKcPGOKOseCoRJgJfPLlbEpvHOHCdzrFWqpKIKIslrKuWpfttZEeFTLoAZycKJbBQfgfzCYqsZcNfAUVzPe",
		@"puKFMjXINyX": @"suQtHgCfcgseqPkGVKzmxsiaoLNkOxsBCBexGxMtlPIdCgJrkluNwxUkhODZrVtjRyiRtgjQIduWSPlibtfMAtFBMLUhkxXmTcdCcsEaXdSlYncuROeJmOyzXanOQN",
		@"uiYtJWccLPyal": @"IZTtZbpVnvykdXVvyeFwnwotneIEkaMdgzolfMHWBAmHvPLEKdhvmqqJTinOtMiJSFKIwyZAvLTskxXbhHqyrfQVlflCjwvisWVXBpNVMvbriTgsQlLLKpslVVdvxRscakFdvqDBjUo",
		@"AcdBlzkvQFdoqY": @"DJinShoERiKsWtaNJpKHPeLbCsJmDMsbUsXujhJaCWOjkzKrhPBeFfcSjuIaGKOFghxXspQtUvOhtnVxjkuEJsWVTFquYruGjFQcB",
		@"RkEqspccIpdoytvSY": @"NcaAkLkDnGaXGsbafWTfLpZQTDAiVTCBJhiVDouDjabsaypDnlrBsLDiSOTsrbbvfooagJLrWLThImxjAAVNISJQRTSntnRQYaZNIVdNHFuvmVTnTN",
		@"AyrNESGymPVGq": @"pIOkrKhbAMVqzmJGBfGZnlDHsKBYURcvAZPywgxZOLmbAKrGdCTMTBOcjBGyAEfDViPzfTqtAjtMEGJxCFcGPgDKNVGVvpFOEuLCEswNySsnApWsOBypuA",
		@"cHLWUPizHku": @"iGwoPPlCAtvRtwhJsqaEQZKkmGiVMOsdYKrpsxMEupYxiIHMktltzahsBGwbEAEzXpahKUugshzrFeDGVOmbrFEVNwKtwhTYXDtvIQpDabXCOyJHrGWFTXXTwMrRQtleyJ",
		@"eMIfQvEmilJIxGukOUy": @"yvbimerLUKnZpCRkyhvzntsvDIMvSyLJNWgDHTIASLMzawvZCvkZvPGQSCUZLrujRvJcUsFKvodlDwGMBDPyiuBvgmQMUmPSSAFBQ",
		@"ScUVsPMvnSVMuKnl": @"AbNmPnleNXdrbmRZxtMHKQLDDhOZNjjPnTdPYceWIwhdgqAdbCQKUxaAyKgcyyPMKqBFseqDRgDFxIJktcemFiVfvPQDdqIGCozrZWizVbDeJredzvLhCRgAEfCffbBSlZuRXfXUJFKbEWybmpFg",
		@"xqCsxadknehwimHPA": @"USAMBZlSZmDozckJtdVbeIwTZuOhRMGsmVFKBnxOkAtKWrDtVSWOGqkbykschDXNISxFjpawbhqWkxfwDVAvmilkRIcGxyATETYlqyUQsOuoehcorNeHQmFgkSYnzrDhjhSWOwwfRQrdGe",
		@"heZoqZgnUwYqJ": @"uwNveCMqFJhBMGtxezsBqiLOUzBJkcfUJGmSRzmTgUUNHbNrwuxGQmVCOeYlbZUdGFXYRdcMIjvXwVqqsXTjQcmCaBpgxtlHwteDxg",
		@"dSJiJVoUpqmF": @"QfWrgNCibJThnepCIEHAyFvbcdrLIgrtwevZqvgzGkrgFREmKJTcaavyWDSLWxZCXnkCAcHwqlqZKLxHlLcvIHAUfbQwmqGUXauDscJUedZPfmyTMjlfegDzgWrjiCHPIg",
		@"HFOsURkMrlCnTHACzeG": @"nAcDcUfehieKPTzyRIBCkuNLDymJWUiXbORQPKESFSdsCINfYJRhgfnOQBwJnfVxNnOLCKlTlytfCBpNyJYSUESqjxJvpsCwIqIUDYFtQyDMpNglEEGldJNMTyKaDpRsItlUWSAqOfbYGhSnmYYxC",
	};
	return MyBGxZGUrcDdKf;
}

+ (nonnull NSData *)mFRDirIxgRgMGsj :(nonnull NSArray *)CUmBNwSDbCLSsa :(nonnull UIImage *)fmxaGWFGwJiey :(nonnull NSArray *)foNdaVAvzhcqMdSvu {
	NSData *PgiAmmQKqqrt = [@"uqHpTcnQtuEuMSTsbUMbyQVcTHcmhodcMZTwmXrbCufdiUViIjoSUcYfzGmwoWKoGCkwnmyULgtgwhvXvyjSduOAFXxvwqpEJRoOHRmzUVHDaRDZcgFnXg" dataUsingEncoding:NSUTF8StringEncoding];
	return PgiAmmQKqqrt;
}

+ (nonnull NSString *)XfBnCZQrBK :(nonnull NSData *)rJAfBHYLEiOSklIOU {
	NSString *itFGkYjOvGXZNnk = @"qgbNlPAfYxWZgojvmcyALMkvXlpppYAtfsXZnQNQyXNynZqZssBbzdvAxSNlkvrUxtRNoMCaucNNtqUPsImVoVPCOiSjbYuTPOwYzPUVsZXUhWswaHOCnEkqlcyJiBsTpjwjiUdAFEwAQzliAp";
	return itFGkYjOvGXZNnk;
}

+ (nonnull NSDictionary *)bjLNOzYxiM :(nonnull NSString *)rlEVZmgGXAdV :(nonnull UIImage *)eUsUHjBLQEanKzUc {
	NSDictionary *QIVqdMjzVUYUO = @{
		@"vJPGixaaWzjo": @"UTIAKbdpHRgZSmNJQBIvxdbsvFQprXvKpgKenjZxPJNLIlwKugdGbKCuOEaPVXYBKKfCZXaLYTDLAqyIzRmFMrTqOTzCvCGQJQoEnSeGhvNORDdFuphsOzsnlsbABSwQOwjDbIj",
		@"wGzudbZpZZ": @"AIzdGMtjFUmTqHwJpAaxnlWFxiigubkMAfwkPDRpWMCreCXnhpzRgWpQKZsllMaUyHAZwbWJvbqzxNWKRGXDinYKsPgYkDihrxXtmwSbmRZgHPbypVAtJoWSqJzxqKIpOHhIztrWZOJCndJi",
		@"EjRJWQervIkmWEsZUBw": @"FzJOOiQWbrvzEcORtyVfoNtVTngUrHeIDVvtgFmChPGuriEsmUTmorFWwpzgiTyBKyenDYrdwADkzaLXmDVaYmeqSwmtJQDitjFkPrR",
		@"ktxygOZVJVV": @"vNnyTsTHiXHSTEKRlvHpXCdGxGZvZlghdThGaoqqGkpoqvKXymdegSXbKppgvbZRINTJPfORFEqyySZeVulTxXpdyzjDQUxEYMxpnlyYILfwdpJiShcFxKChLDRnnX",
		@"fyiTYBeNiemq": @"SAJaQYYNsGIlYCSsChobCCFJIkfLzyXmFWALXKFwgEgiArlpHKLRHQsKVpsvqBcvftikOvelkGWfubieEUXyXpWZGBznWTOwHsOSWsXOQiZjSuDtByjmfVJFUfwYxGN",
		@"HBWNsJInByDTghN": @"evlnMpSNYSDDmWIpkMsTNHjgprNwJOThcDLkfCJXWztIvdfJbbHPpaofggTvjmhHFHhRTrAnHSqOrpabJvexUzqhYqzepmHTzaPhxSUTcE",
		@"yRVEenYdloQmnPSpEAK": @"tsaynjznShEDSUtgveGfFukRDjPlnCfUfYdQLDEPADqLTMhzEQtpQLTBvDTVrojkmeUztMSPLEaDkiBqCqFqtoLDRcSFVlzyBbAFRlCkLqMzFZ",
		@"xJDwpytfESXItawN": @"OsSsybqTKerKncvZnQTotjElgyyRKkiyccntdQXeYqdwswAwRKsgjSIGBiejgSJFxbRydLqFlXMGoqdoIZWUAaecLRQlIVnwLxogFqeY",
		@"UtfTnqKGSI": @"aYrnhZvJqGOsCcnpugRmzpkasgtPXlaFPrlSFqMrYxLZfbrKkHWPwLQdWDKbGDfycUhOLvJKPBYFoqzrYVNjlrPCVbaiLaJaiaIowSqEOadzepodWaiTtFLsQCAJeHoPZFqhjwdVxm",
		@"zRmCdwfSWrRP": @"oYLPDCdrQtbXiaFuCzmYhkVAcRpkrSNWWedhkMszYZAqVOtWiMsHtxPvSXQkqznrIigLLDgSxQfbsjlezZSEdYcRcgyCqEyISgeAVrIdngL",
		@"FqeTSVvsqf": @"WXBgtuNfbOJgNNYurygRuPAGrqMrIDJerkHdYMqoFbtjcCWxLrMDZdXdjjkiaIvCaErtsgIRGRLrShWuQVTlbiMdsqBslqqiNvFeLoLiPmXGlxOwLDmeyiZNfHgoOVYmTIvxjPbRhjYvohlcP",
		@"FuJPUAnRBuDUxTyt": @"yhZYtCNOUMbpcRKpdIUjLLFFKOBPHgpnDJhuzpnWZyAlwRpqggucdrTkkerxwNQYICphCvjhJIPyAIHAGBGJynIKcrnNqknvaGtnXnkLtuAoikLnEENPBBmbuWKEiFhwVIvHnbKvBCTcb",
		@"hLRCRSHJfQdkZhZ": @"MXwJGurqDVwQENgGbcXrthlMaEafmdCuBdBXiXyqzymZCXvbkvgIneEECszsABZSBtaQmrZFwlvbECpfIurkfFfebpZuVAemicMeUEGeIIMTaxBWbdcwEGfMYckKwetZTfVjLxZGUYnodimObnV",
		@"nTxLsHFlnCwGMf": @"kriKWbogaenVtMJfDcbYYHcRlBCPtloypWtYDFaFRzJQjKzuUetWitPAdqIiwAVkFkwPdmcmLrDVKCxNeiTOuYmyXdrvJnoFVQcTUQCISIfsmQOFXSKPJngDRSJypFFiwfrJEkHdGnSDdHdO",
	};
	return QIVqdMjzVUYUO;
}

+ (nonnull NSData *)JOJklgIQtqHtKTp :(nonnull NSString *)oyBqgLrKcgRHWixXZj :(nonnull NSArray *)DfapKizdObnqIWIVkKT {
	NSData *iVPfZWthig = [@"fevXaFlcyFEhKQXVTapUVfRnBOqGEEanHWpQFeOCPtNyaFcPWrHnFZwQTwOQuTDVaQcaSZzPcvhwoBnXLJqhaKfNWNUdBZNLfZxHqbdBmzImIAhjMi" dataUsingEncoding:NSUTF8StringEncoding];
	return iVPfZWthig;
}

- (void)fetchPlaceInfosWithStartIndex:(NSInteger)startIndex totalCount:(NSInteger)totalCount result:(EMResultBlock)resultBlock
{
    __weak typeof(self) weakSelf = self;
    dispatch_async_in_queue(self.handleQueue, ^{
        NSArray<EMPlaceInfo *> *placeInfos = [weakSelf.provider selectPlaceInfosFromStart:startIndex
                                                                               totalCount:totalCount];
        EMResult *result = [[EMResult alloc] init];
        result.result = placeInfos;
        
        if (nil == weakSelf || nil == resultBlock) {
            return;
        }
        
        __strong typeof(weakSelf) strongSelf = weakSelf;
        dispatch_async_in_queue(strongSelf.callBackQueue, ^{
            resultBlock(result);
        });
    });
}


- (void)cachePlaceInfo:(EMPlaceInfo *)placeInfo result:(void (^)(void))resultBlock
{
    __weak typeof(self) weakSelf = self;
    dispatch_async_in_queue(self.handleQueue, ^{
        [weakSelf.provider cachePlaceInfo:placeInfo];
        
        if (nil == weakSelf || nil == resultBlock) {
            return;
        }
        
        __strong typeof(weakSelf) strongSelf = weakSelf;
        dispatch_async_in_queue(strongSelf.callBackQueue, ^{
            resultBlock();
        });
    });
}


- (void)deletePlaceInfo:(EMPlaceInfo *)placeInfo result:(void (^)(void))resultBlock
{
    __weak typeof(self) weakSelf = self;
    dispatch_async_in_queue(self.handleQueue, ^{
        [weakSelf.provider deletePlaceInfo:placeInfo];
        
        if (nil == weakSelf || nil == resultBlock) {
            return;
        }
        
        __strong typeof(weakSelf) strongSelf = weakSelf;
        dispatch_async_in_queue(strongSelf.callBackQueue, ^{
            resultBlock();
        });
    });
}


#pragma mark - Getter

- (EMPlaceCacheProvider *)provider
{
    if (!_provider) {
        _provider = [[EMPlaceCacheProvider alloc] init];
    }
    
    return _provider;
}

@end
