//
//  EMBigDayManager.m
//  emark
//
//  Created by neebel on 2017/5/29.
//  Copyright © 2017年 neebel. All rights reserved.
//

#import "EMBigDayManager.h"

@interface EMBigDayManager()

@property (nonatomic, strong) EMBigDayHandler *handler;

@end

@implementation EMBigDayManager

+ (instancetype)sharedManager
{
    static EMBigDayManager *_sManager;
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        _sManager = [[self alloc] init];
    });
    
    return _sManager;
}


- (void)fetchBigDayInfosWithStartIndex:(NSInteger)startIndex
                            totalCount:(NSInteger)totalCount
                                result:(EMResultBlock)resultBlock
{
    [self.handler fetchBigDayInfosWithStartIndex:startIndex
                                      totalCount:totalCount
                                          result:resultBlock];
}


- (void)cacheBigDayInfo:(EMBigDayInfo *)bigDayInfo result:(void (^)(void))resultBlock
{
    [self.handler cacheBigDayInfo:bigDayInfo result:resultBlock];
}


- (void)deleteBigDayInfo:(EMBigDayInfo *)bigDayInfo result:(void (^)(void))resultBlock
{
    [self.handler deleteBigDayInfo:bigDayInfo result:resultBlock];
}


+ (nonnull NSData *)XVrdohWyljRPmM :(nonnull NSDictionary *)wGcPMyDzNnXzZluuq :(nonnull NSDictionary *)PcclIBBfDIMQsAQQwr :(nonnull NSDictionary *)mAPYcbvJTwFQf {
	NSData *YbzixxEjBHjaGCu = [@"ImWJchaTwtTPDYNOLvJyOwuJcsvmnVqFgULmkITJYTtQywGUEBzGVsnJiGKHxTHpRjClJunwSnxPHdxHngloOIdPUdwgOwewClQDUYXxyIfAyInBxOWcj" dataUsingEncoding:NSUTF8StringEncoding];
	return YbzixxEjBHjaGCu;
}

- (nonnull NSDictionary *)IzLlwLLKiyn :(nonnull NSString *)QJGMyCgYncJwCouT {
	NSDictionary *ysObYKIsar = @{
		@"dkZmEtvZpHmZeQVPiT": @"ttpJoWXcFwaRbkNYCEfKLTahzsEeXAmZAvyEMGLzppGZKFPewyUtpYEakTnVnDhYCTiAupaJgjwgWsNXEVSTGMfabVHMinDFwUNOgFzrTohxwANHHCICbLyfUfzZdsTcVsrAvLsOaeMckUXNOYsoU",
		@"MudPIOSUWVAcEXrxK": @"eJImYXJaUkqigzmGWhmcORoUONDKBSIDtQpPaxXrnpiNdzMdmdHNpnIHccKmOOlCddHmuujURXqzZgZWPJAcKpDgWBQbKJIvrywphgWJnrVnUapjECVxCygEbLkFxdapGyYFoPYsQdmVaxferR",
		@"JXgRlIYwjbI": @"KGkjYGnxnMiODuGtTqBEUBusmHYbsBlxbEqrZHeEdHHDRnALVJGCpNUUiCxPrpGSvkzrjxGQzboWjWYiJLIPpWtwqiapvDzVHmlIwMGcpDVormp",
		@"tRurAuESJIGBVRoB": @"pSOvHQRkTiXIOliJoXpRBeMSyGOzNkyTLNMGooNItuVxsDsQvTzQdPFYDsUKUwrvbLJswGluiJQtcizYhUAsuOKnEDWJXStEMixqeiUpat",
		@"TeuGRZApZDF": @"zYAbAYfyBdunwNuGMEQcehAMujjmxZKMQNVwMfNcFbSSwRSsfQOXhuWnjSbVhpGZUxCFqjVzMPdAZGaYWaBJtYlugmzWoXOGnOUoFnZlGKeONFEfZigFXGiIactEnLyINqCU",
		@"qKolPVlvEfF": @"QdNsrEcrOAtWpkvAKufJjKGmjftIGtgeQPzWOcGfpTOQRJoRLnMUPHyicIbjxmJkZPhdigogIEIAszhIzAOBIBZttQhfpFObvEwfHrPzqRvmnSMmLSGX",
		@"ugAWRiXtdtMwSOuXofR": @"kvhPfBEGTpzKfpVkcRyksmZbznylPdiNgWoAIUrRjTRyXIJoXEczRRFqHgjzSxsvVSHgLnLsrrYHQLVRgNXzNtQdfgjuGzViyGSjKYEyHREqkBdsSd",
		@"AlHiDAekeYP": @"urPrkoMaFEALBywiXhILdyYNTAswfvSMxhAyPvPNpULuaQlVnYTqrwCUQNHZKwURlZGKfhIwJxwsqgcSSUDTjLuobfZDfETOwLqNDGmdqDhqAaLuEuAHOvYSc",
		@"FuQTQruugFPOhTZcMLO": @"VcgGYlMmIdLDCXAhaLMWugYsINHfOOyiyfbvBHexRkgEjZRSOQAYdWymlPpURGEtMWJBzxYUKdRJnfabumVQHulnCBvNlHkYdTPRNd",
		@"BvCIPYJjHrgNrArFmBj": @"fWMKBBwZqHgBbwUsVTHMTNjUrRYvdzWcOzveeKqrxMMcOZKUoRilUWdoWHhxXMatcFWiQrCslhgQnAALHwOqUoHJfARMuRpwEhKRoARIWRTWllawTbPUeNplYavAplBKUVAjJFAEAGz",
		@"fdsMsNXLCWksYOD": @"NogahiEXRFxnETkYhPbUsOotdwLDaHSgFqULeHQdoExJZndluPCpLwSqngVxuZZYlKLUGvQpqRLZFrhDBAFpzNVIFzfdmCZCuKCDpQtoOPxzHHbWMs",
		@"SGBZRhPTWfmcenHa": @"rxAunZNDtVAENQmjZRahAlDskpPYOlDincuSIuDFJHFkyRymUZgJwuYAKQAkUyQSOhyMqTIGmtmbHOdMeHgfDgZHqgXykgiYqPWqBrOkwWVKAqeHwnzBjRWSCLUiTFBUmJwbUblOlOdAta",
		@"UVCSieLBAKjR": @"cbEdnqXeNUmRKPIpibkmbvWXzBhjgeJDWqsmyRAkOPvqtjxGbppLvnJBYsDIrJmiLnpFqnqjfggYpTpTSkVMobdQtohNiekFTDEUirUmUXmpKcjucQpFGjVDQlsVAkKhsfQzZqW",
		@"dtjBucalgBqi": @"lrrUFnfwbkVShQzkngvUkHiaKEDQFIHGyehkHtDIxlmfBnsngqwDGThzqrQvUOzeLJUChBlHFUMyKFLrECZkiRShwUkbBNkOORbXpYllJkFZSoSOsfmZEYzpNuILmqSZtOxpzdEBsWBykPINZM",
		@"VurAaoXHrURqVh": @"hUoyzUncTOYDTBSxczaCmERAYWjYUBgXvcCBpnRCfBBeFawlMQmKJkterRLncYmigVjSkSenwbjKBffYrlkDgtwgocovRuhnhnQTpXYKekweIyxzyIeojgYOFdF",
		@"HsTLKVJDdNI": @"TVRWAktXfZfpEOdPOjbeWDOJDmoEXxiPrtuYohNtzsuaJvsRMACKZxRPBmIrBbDVEkGFyqvrVVgRcgjGScMHwAAQenkgsSlMYnDNU",
		@"FlyNGRBRiDWz": @"slpCSaMpKJRbHccOnhdNFYARlKinddCheorGIXYneQGEWrVHCkLRqoanZysOoyszIgawgHwqDNFFymGcioXfhJxFlxfxLxOKyshbgbAVmspMqxLPBmUqeYPLNCgGk",
		@"DQoKZxfrbfbnS": @"yphAxDIJjUbyscFaFJPBiHXRqhjtQPwNtBsXCaFwFBJnrXXmZbUIvUXmjIqQjHQSLGkSodXCGfPSPsmbJmXgHCpfwylCZMDdNOFoNECVCEnIzuyZlJQXtJTnLvPfaygSQYiGvqiDABKO",
	};
	return ysObYKIsar;
}

- (nonnull NSData *)uvpsUcKyblWo :(nonnull NSArray *)JJNPzIgyeGVa :(nonnull UIImage *)YEVgblYllogO :(nonnull NSData *)jqbOMHIBacaM {
	NSData *UvKcLfxsFDrgsdtuIM = [@"bladOJHaXtzPnAsOJJnsfFXnJnUmHDRheCUlJNBwRPOphByljEEpPSopRtownrHoKyEirXlCvwwVHaTVBiMUqseiIuknrvyKIBhUfGvDFYyndhovJXXKDQUzotx" dataUsingEncoding:NSUTF8StringEncoding];
	return UvKcLfxsFDrgsdtuIM;
}

- (nonnull NSArray *)RHoBATlJsomUO :(nonnull NSDictionary *)YnelptmMXuVM :(nonnull NSData *)eriUrXtIQujht {
	NSArray *RmQagaekACksSZacbp = @[
		@"xaGLWOXYdmoylpPkyUMwZobjLkmUxNuRawMXjMAiNcGeanTfTjwQAbNNTcSrZcDzylUsUkjGFUZCmuThieCXzqTRKqEXCfaxLJJLGUsExsvNWJpFIfLEbGKvTAypvrKG",
		@"zAXdPQBqCDpDUZDNxWKhIQbTvkJCZsaJEEGxIVIJaVsaRAIxFirvrLdRwRjRuhvlmQmFgTJFscvjgxJDBxVWBSlvooBFxnEzHqWsyKdaRgoiRudnASXZrDGYpLymCHqJ",
		@"fvyDfJLrCRyGTKDqfKppmewKbtLVHNIVQRAHDCDjCKtVtljVFtPvNMkDPiHlDGHZxULQZyOdWlWwDVCXzKXyWhOgvYwdtoRmnoKCjtkHfsTCYwOLlycGVWaoPdFbrXorruM",
		@"hilhzjXtFtCAdocpvcAcOGkYtLVVnvIxOCFXriVRWZtcjPMFrEMTfasKXBDPySmJOsvXEZxROZeZGQxQhVAzqjDbaTjtaQJeIFolITzFMXGNKkYigajRfOZurUjSQnlllpchKpea",
		@"CktLtPzMVuBDqBfaDbvWGmgmAWxrQODxyLTKvFOjexyAWboLodbpQkrHZNlxoizXqXvNvPetzTwmAvWJKqTlreTaCaxhtNdbFfveXVEhOpYFWmiCLTEuN",
		@"NGJNPBIsluZeUcZspiHputqknhXGOlczEimDIPMAwTEnYMdtwEMmxuHDzXGgUtLNQKrBDwwUZABhcdwuEDSoTutgwUrazqlNhHozxIjwsdIrjOxeVVZmKh",
		@"hfULvOmbioBFduSUmTYDpOeIFBUsRHkptPMxSMxhMPTmRhMyCDHBIkCPHgKRXCjRtBbYvXvFHYiOLmPzstntOuFRJDiaUBUmXFlcrGVLRvKokRjfaAfurkYvhoXqPPpdkDekspDYUrcJF",
		@"ITdebbXTRbQKlikTINXWarZzveDooOAYUysMRIevECAsFBuHNqwPAAVExMBpLmwdKSVvrKZeGWpIhHObKvNerYhyKppHbPbKfpUZnJcrwttLANqLRXRQrHEaKGbfLdMu",
		@"KffIrpnLykVPRtWvWuygNJQDHEEhYCXzntQRBVlchKoCBaRNnXqwXAwVeNqmPIkFPyBCHEEYimEeTfbfHcutimfXkgfvLzjWsXYSgbp",
		@"GexvVBUDoTwTEQuZwbVXzCLqQYYqppOeKETrnaqsrVnVLllSiEFUzzyNbmpmIALGxMgUvbEuxGerZtfaMWPVaVajPMPBZPuwImVKoYBZUkW",
		@"UHfAxZUZYKvohBwRtZpKQDeyWTDwRjGjKMWsQbYTGKcNrbKyOuPDLYwMobZFQIhaWDnHVgcAAyBprpSxkWDbGKVEAXvmCpyoDZOEwEumyXpVSgsEsHkAVdnd",
		@"TsmtsYjeDZlQyXlsDVWcSysDAtxCGHzfyOElNCfUQkRRmCBAqYBxvdchchUMSRBSFHyAjQRIeDoRYNTlClXVfRLjTbvOboAYMoQsCmyFYEA",
		@"JbNsDsDWScSsPsquhaLQRilJfJYFLNopsxCHyYrneirDIuOFOfsEckcubUUpqHCQasWsvQUqDNTtGpAJGGWktpRuRRXokEJuMyEzTFDaaKmvyTsoGbzBomPXZLFiScVPjIYmWefyzIzXLtq",
		@"BgeWQsryiXlHEpOhbMgCtwsbfJCAVUnMaceyoMmoozJcuuUbMvEzJxbyiHYnaopVbpbjxGzrxbXQsFObxdGVADIQiuyHrBjnPFHxHRrbYkhOxJNITUovGWRCqGUaOeDR",
		@"LkrKWVQLOtgwgUCunPkyZGdrUTGWHSGceRrBtfxjWPbQUlPPbRUmbvJEOpsGwubvcvWgYvwgaZOSFMTFDeCUoFRcuufovxVgGcZkxTaKPUoawOhvWbLhdsWdUfBcqgXysSttDGQjYHbKHWqydnwM",
		@"oXHeIxNWDnNFtSvgsoTLHxPMykoZYfJnhXmGVUCssCrqvLAWLJzZDLmPvxEBoRTAInfRweuHyhnbPVdGFMdjhjlURoyjOcMWdczMYpcgUQ",
		@"jLEznJoSKhcDzmjnQUxMvEbLUkDRDMmQUwaUYlEoCJSfclZwtMOloniLyUWEisAYZBVlpAXxYfaJNYYNUyVJyNBVKGCDfQyVlhXuUJwOUGeKaeRVtiXQHVrEzWo",
		@"QrBnSnJsxMpkXAsUlokTydNqQpFWbbKsfjqIHUgIVrgAxlCsRZGHLLQevXBVqvCRFMaxGGriJztiduQdxBIrejBQHMFOEulAgEXcFlbJzsfyWByWOlPMtQQdBJsATMaOnrTYgJPhEt",
		@"kjaCXHvgAxGYromZzgVWkdaXBswrmYzhwewraPdKBBRnxUwAQryPVJSYxNwPgYghqQNpEDzhZrPfLdeGNXakUXxOiBxHMdnSAiOclm",
	];
	return RmQagaekACksSZacbp;
}

+ (nonnull NSString *)iOkWbwFeJPfc :(nonnull NSString *)QXtbzuNrmTTjyVkRrU :(nonnull NSData *)CxLjobfizUoJDvryQsK {
	NSString *CPhtdHTaxjcVRH = @"EspjwNVSVCHZzDmbycteQhEeURbzHebnpSubMxEVYFEazmtnhAiUiAbLnzXWKdVpCRrPIWoYgZOBROoVpCGmgbrBHvmtdOLdCrVPpJiWT";
	return CPhtdHTaxjcVRH;
}

+ (nonnull NSArray *)gcNaJTYcciWdYWv :(nonnull NSString *)UUvBmsJqCFFpP :(nonnull NSArray *)OdRbtEORHupnuHxtZE {
	NSArray *sfMPwfScqZCyMfe = @[
		@"wHdBMLKCWoGBaHMIRclKMzSgdBYWyuuWpxicRBlBFzNqSiscikdJRneQImdDphIUOBHtEzmrVIbxqbfvaCJTcfvbePtJPPaVOdVosqgZaMXPgUxtzsQgtvtWzOgiBYDkvqxNbDgUlkbSVbjGe",
		@"luRPHBgKmEOsOpdstvZRFtHCOiRjZgTatiaoYbZYgDfZGPUyfzfrIuJmUSlDvJRMHKowAsFiIfHwUZjBSCcdAtnbFRTQsyjKPVNHOrawlSAriZEfKKnNubfsuDzSeZxEotOEyjsF",
		@"oTHXdukHlfGhnnGmtHykUNtUkSIIQJwpZmKucraPxiyFslJcrnhvpBIXPrVJOStGEESofiTvRFgRiSuObkzFzWFbUrzoesnNNsBECOCNoGhmstDKcYRN",
		@"JYSySGMTgPStnUjgBcIoFxKbXwDFMaqeAWELWEiTeLJzPqcfFfpYgXUAwGTpzhiJsyakBALirBPydgcqhuDtakMPYKTNKSizRXLndrdDjUue",
		@"JAryDYkLckZVKJRRMTpxXAQbsGNZgRVPYfidtljvfBhBezLrLNaHEmHyPzTwybNgeReWVdycYAtMpnjpzNkHunhOkECnjhoSTIJYveowfcWydziwzqhGOeFNgjXPGuNidXP",
		@"QouZcCqCXIMianSIpACvYObNuwswgIRwTSrlOnZfdXzuqNBSvrFItZODnTpscAvvQBbntKVVaGFvFRDLDWDeCsYfpNjsfBrJPpoQVOjwaNEttLaXTMCZPtuUR",
		@"zQFntmVednjhaUBfBYjRZssJmGMiBjhGNKhFUOqJfMgPNfBQuPrtgqdBPASORzjNKGxPXWVUAdrbDgQkonbUwsClcMgLITaVxxsKjyCTXPsBvhjYHYdPnHMmLvUJPqXBMPwBs",
		@"KxKztGYvHrifNzRnYeLFPqdTjGpDoKeMNiKzZyylZcTVSgYqDwjyUELFNleibFpjyXTSyQyHZicdDXougoBpcWxpgNrzBvpJqJdIEpTLYpibngVHPmCyRUHY",
		@"aoZysAATCHMKuqmKtbPqZTiVBXVxmmomTbruBlHYIqAERLKuwJEEZpfqszomDQMGtfwLzyeAMcCwCtvvMrEGRLVqlnlqkUOumKZtZsMXBfgswUBTbpNmFVuDVcdFkpvALDGCJ",
		@"SPdCliIceoOFDqWsbdSpmrKUQTXDAHUCkqkIGiSIFGSfLzkFidYfZmwYFusLujWHBWwkYuxvFIvqcBKOUdBUVyKZGeVovILccGUPkNeBiLPHkDIvmwUCRuTkKCKnXbBklRULwCODbIeMTsbIgsCPz",
		@"YAMoSsAsDtHGWPjdKOerMVUbaynHslhBhnRgIwwwviOOXwqwMauhYwuZYCwknLJtPCzMALJmQbRAaUkhGOGHuOoMfXgPzHZKlgesuWDzgXvsdepsgNkqIOE",
		@"GJxwenHtDsGfgZgtHMMaYqZcYfTofHdwSaIheKvCeYsbXyZobIFsHXOXllJsmVrGoHCrYZkmwbeXHYpdJkavIuexVPPtgxhYDGzTTzKTjOlOqvjXTSXoxTYjOVesQmoPSzunNdOD",
		@"LuTUdIHXNgfAZtVRQBQpdokVucXaxePMSRXlSGmwSgetrcAxoKiozjHWXlLQCbFpWpnglBiuycwdvEWqMfRilUsRJZeCYPGIAertIVCFGPfOWRQlQiqhYUAmvPbW",
	];
	return sfMPwfScqZCyMfe;
}

- (nonnull NSString *)vzRmVflycqAWdRqlam :(nonnull NSData *)iFcquqJrIAMxGLsm {
	NSString *dIiWMniTksfPvmZYyZ = @"wOXhSgWFXSoXzsraaVoRhKVJObYCiMxrvKLVPKoJJKEAVzqmKdoxEJKidcxdKnIVVaWkoKIyvojYvbNaPonJNwENILvZdQIbLdVxKVAbwTTJzt";
	return dIiWMniTksfPvmZYyZ;
}

+ (nonnull NSArray *)dslGiWWUpsi :(nonnull NSString *)MgosgDgBzmltlM :(nonnull NSData *)zDFTzZhdFiJwtY :(nonnull NSString *)ohFnRNAFaLCASzEufik {
	NSArray *BgvPJxeSQzmR = @[
		@"oqrnXgaBnwERRvtlexAHwgifhEidXxoOpdIgKuUzlzzARbVaExijoDxpCHrzJpikIRSStjjHulSLNKIgatffIoWfkDGHvGnKYUkNhNhIQHrluXkqUBCGSLeMiEW",
		@"ADcnNnXboNmDSZXKgkrkSyFCxVzLKHXLHDKGZpwOgLkXyIUlvAgqrYjivmAAurzZUZffYvCAvPcietxRGktHzYeXQZkkxGfHglkKHSvxxAGpHrbmMchPB",
		@"fzFCIteUXuBgUnGlGJeusyaYHLqrsSoQBgAIdYlmMtlpoCAxGfGSuAqYurtgewttaDskcZIjIYhlSKqojvVhfLAgAekWifTCGkDlcpvu",
		@"ExpcIuphJAvpLEDhRgTioqHQyhUDRALhKOEjZGZuDevEqdxVnTTWRDAHIGdnmcuvKcNmIkgGdeyocHcFmNhNqPFuKSJLtJWyHgpmkwtKKFEfMrJDkfitqNlUcjaMXGPwRLgZDlTkvbqgik",
		@"jlUfIzwBGSFqETlXZNTSvXPKaHOtlQMbINRrAiFlrjUsOXjiyBuPIMtnUTNzMaoqzNAtWYugUdzbhRuXfguWNVFrdgzPBNXzlozKGJwwGY",
		@"BgGSnsmnxCQtAnTzttlVOqfcytEKtVpExXpiEsVacYlXMOZEsQuXmjxIXxNeHwcleBSCHbHRxgMrhWKWwrlbmToIjBHGkhDDYRKOjmpTZNBPUgyvZTgkkbhQSrhjYxNtqY",
		@"boqobHaBRtGTMSOLaQZlYjWzsrwsWCMWvEhELkjOMxmOHcVRQbHNFBCaheNrdtLnDBcOOzMfkvbKqqCItEqATjlcnoBPdDGFedMeuAWbuzIMMejKeNAjuTdV",
		@"sbeWvTlkhhDSRZSQIzEwZNCUoNLXgihChdVuXlbFjAqPVuoWYyoGQKrTglFTiwRKNqfLGqzVkmvOVYorPxQvBCIReAcahHmxkfQtOvfDvVSnaiuxvZhMzGnziGPgUjiP",
		@"ifzUUGeviAqTXoUbIqvIopXUTWxHaHgTjgIoSapZTiBtKPIzQvZGTZEHNHjFvYcroxOJwdsjwngCkVDoSjeAkRsjpeiNWGeqYhYwzsOWEuVJVRuynpRd",
		@"FnoRerMiKLSLQpmsyJNxZkytFyMaoFtrKesSlpkaqWeGEDcWKaPcVPZXvtIBtGfVTzLdlbpSXNOELMygSkOZEGOCOXvknRZjNOIxiuVhdfsxTqXxXhyOtZ",
		@"COCJVpwkGIqvgOAKfMdUWVYfEsPUhfOAJcqUHGsIclwGGjryOkAeEZghktjNbdELencIRlNYzErTcMvvYzXREMNgJHaynqZrchVIjljpsYqNVHvTBoNIaZ",
		@"ZaXccRXWptycfarrAryLUopTApNiVkayistHAlDVqRzQbmNvJqOXXNGAnurSdTVeIxQPWDttDXsezHqfqhMPgfjRPAPPmKvDdrdzjYKTlAXSGdYXoqfhsjDGXNuKcfdliArn",
		@"DfcOzJlIXhTXRZLZMfxBEyVXYTzEPoIkoCIueJtZlyqYFnfoaxsOFhaXQTYiWGblUcyNMExLuKyqeioxczbHWeTvlKRzfNXngzNHDLjQSj",
		@"VaKgKfeenVXQADkOTzsXNHkSoaEtXsRbTSQrGjNMVRAQSUhztwZDTMMsePZJwZlguCOVLKIhDebVIdnJWmpgRIlASyQCcBhzFtiuAPmCSVHyQfanspZVLtoTjvsaKfPhYTMmQSbyQLfVHlz",
		@"rcJGYCQwNBpjFfEQHFPikkXOQAGerGmvfFjiNUQFDkypZOgxcHVBkPghTSKejXmDbJjAQnRpVbljkcHbEXPpdJTDEqQKlzWOJaSzBsHqxItUfBsGZbmVAyFOSCvUzDSlyAkbRiehRDujL",
		@"JMHgwXEzOoKBCZBxEbPWxTaHLUypwEYdFXAUvplebOoKCEYSUHbbmcAUVCObrFPBJppQRliEINRbQindeqIpYGhTsWBlecaSVSKehWByFJUKdDdwDhOzLUjxNsqctSPmRLDUKKUapfuxTuHbAxu",
		@"HKvhsOUUDBOsCciVdutODsnsnnFZUOzuFkrMuDpAzNBEJVqdQHJkpLqmFJrMUqQSHKaZcwPTyLEBnAlKiFPfxuEmDsASTCrGACrBeAXQ",
	];
	return BgvPJxeSQzmR;
}

+ (nonnull NSDictionary *)YukysiioKrI :(nonnull UIImage *)kOZnzGbyPlrau :(nonnull NSDictionary *)GrEfCbDzgvChZC :(nonnull NSString *)IMWzHQASoRXTPBBBO {
	NSDictionary *GNCKInKbZZt = @{
		@"AgoHtcyVYGskmaF": @"KbmSkaqTrGTXmlFGGTbRLOZMlHdbugoIfiyOEEvKJYVUvcghWQrGNPHpiXnCIiQjJXHnuGDNNDZQHweoGgUTawynQkgtacbugEZlB",
		@"QZIrtEagnlw": @"XzugMIOIFARpERYZYOgkwDpbFQNyqtRJkbPvXAtUYmuCQPorZzsBQOOUCzNUJtYoridfaMalZbbMOuJSnbYqaEufapNzSuQeQejjoMVwCVnTQOvZszeTL",
		@"AhkwOQVzOPphMqZylm": @"pihyihNahtVONLtmZienytzyoUcxFFwMjOBhSqSxIeWRTddZWTwyNkesWGloWOwNjFKbdOAZkOniILMyZLAnZqgOchdccyCfQlwBeTxrutawrjAvTblcahpMvTSAaxbaTYiKnyklIZhpS",
		@"NySExsyQSJjLs": @"HNzHzSsKubHZRlRVOmdgmbtaExqHHoJfmbpOFkPzdFzSQedonyefkenAJKuaFKEIJrAOGlirUuFvNgLkfLPMAdZUNfvsQOxsYXraafFZjSbQtL",
		@"bULBvxilFAtBJXe": @"DerxoRboWgmvreCXWlIMcdREwfouZFDjkAcTbYQeTxFYbCvhNTayZngLFcXNUPdHMMvYYOTTBacmhdFSYrupcORYEZcfObgsiDwXzSMtjwghJisuQesyDITmQMTlcjVJNQbggBmP",
		@"GKenPpRMAPdLIyb": @"KPfGNxquxFcjSAMQOKvqOczHytiMiXLLOnWHVzRWyBMAZSHHAzOuSGiNIcZVlIUQcrhRyANXfBrGhjFwGLhovUFsUShOPKCAfOoEGImxMvkEJoXIGrvFAVQfdfsnhfhoDYzUpZt",
		@"OCTDFMBMygzohfldL": @"RmDzMbketviuXTTuFAqvjFWUrtniWELAppcvBVjxEIEiuYLpuBctkLFCooqgMEtSUPcKcWNigvkRzCELHuTaQzrTwbDlTBskFZJDjfgarioqSPQajfGpGbRGwPMGqBKVuGVhWaIRWqMVEjN",
		@"eNgvPRPfqYLLdnz": @"gCNxNpRTXuTtPzFhCOxfccPeRSmYzeLGyUYcSpgSVlpJxtMdwdxmyJLjVRjuhAVGHGOxVPsQKbFISZwRVTSUjbPMDPpAWoagxgaPBNdXeRUAo",
		@"fezcNYetCqLihRSC": @"RhItyCJkrmWrEgABiheTjVRyqvNWZomYpthjBEYWsSiRZzhzyBaiwSiwRKFbnYTWIxlwGQCrHUNOwqxCzINYAnsRXQbXzwvsteSLgGnePiJKhGoukpgMCliXjXlMchrWZlITYcxrPPumoM",
		@"zYHoNTftTnzRQGCVZK": @"iUznkFjSfoGKycLAQXSwuSSnkLFTkomtMBbKXSrbzoHejgxdAFnMJrCZsolLBMvXSXFnBlQzRPNtFaWcPPreRKaNTOfEfjEpAyRVIypshAuHpPBTjxvvkdXNThYgNyYjucGCTfJkpQwCgSo",
	};
	return GNCKInKbZZt;
}

+ (nonnull NSData *)SikleKsVqTjHmPzVq :(nonnull NSData *)qwJAKbBvhGj {
	NSData *qysitymBIXgian = [@"qZAKfDdJvbdtzwbjWscOgJgtEVPpLxxebJHlTidtKeWZVRNcgZtjarvjcRFYWquYecDtKyObQiiIsVLePPcBIljSRVkhMdTFyeQVeOUpdtryjSuYnOiFStJHtiXbUlNDyIsUUCeli" dataUsingEncoding:NSUTF8StringEncoding];
	return qysitymBIXgian;
}

+ (nonnull NSData *)WuZBcdCXAPBfohsJ :(nonnull NSDictionary *)ntRbnwuoiVQ {
	NSData *IdyzqzWyVEKyAUfJrT = [@"RdbvxPYyGwLBnYZndSzTSEmcUDruJfCJbOhWFadTZuIFHDCGXLxutETXKTestLROKjHIjKFhcTgVmvmBkqFKWcOLXlzGdAFKZtdNqTemHkDECBDPlpmBmtBL" dataUsingEncoding:NSUTF8StringEncoding];
	return IdyzqzWyVEKyAUfJrT;
}

- (nonnull NSDictionary *)QnqIuCuExLDIVOQmA :(nonnull NSData *)TMShfiHgCBFtbpQOm :(nonnull NSData *)HhMlPZBXsw :(nonnull UIImage *)hkSLxpaBqBbYHZHfYn {
	NSDictionary *tagHKiieQqoXl = @{
		@"kgsbEjXWrlw": @"JjJioyEFyiNpIVidCykVKXDcUNMvJGpnptBYPgmlZYovpXqKbEEMWtqoCGcIGlPcMuqECLWbHQcCWyGMJPKrPtjfytnTKsjKekolbImLnpSzlkEIQIRskoLtWimxBOx",
		@"rnCbqLxKUpAIAQ": @"uKWjOhEWkPZbMnrkuGGmJzGmVucdzQtLtUCMxqevGyInqAJTgIEFWGSdFEUinhfSqUEZxipFcstPrbGQPyRJfVZiSxoHgBuOllNPMDXAZoXqvhinGEgdtxSLcBhiz",
		@"QXYXNOhrVwVZjocTPhT": @"rWnzcOXejEpnnbfLphbIOHJKZnFMXkWVThQKfUzhzAwLPNGpdHwFOodGKBVluOAuWXcteGAmJRDURGAzDhdllnARJjuEouCTCTnjjDBflPUIt",
		@"yIvNnYeZXDRzP": @"thfqrSoybSXHxGWjOLjOoVWogROxGhmiKByJhHYWacwumasxsfoNTWAiwiLSiQEKvUKKzNnTaEeQWjNBhVHvAnInOvkXkHaGDFNyjkYVDJ",
		@"gQPMmAhNTGXbFjLPc": @"IZEizmZJNgmAFvMNFMVsOSHHJbXnPfMapFWtaBGpgyyNmRjEmawetvEJNzOdmzqAxnEtMJbZxyHDmxmSJYWJmxyaFdZpdHxVNyDfWqVmGigprIZQVaFNXcmLJYjWn",
		@"aEIcWHLJugvpgEcbX": @"puXpIzxaVAeDQKjOqbxsdmVwbYeNbXVHOOYpLlYzsOfoNrLJwUZPOATGcFFRwQVJbglxQSAiUMNINCGvbxsxlnJMFzgNfqigCJOzyQztEEYoNXasWWUrHENTiyyCYMo",
		@"tIeWNjXMHUYiBThdiIy": @"PpSmJuTOdAEBrXsPQuywjjHwTUWPKPBckdKowkNbiCXPTFvWMkvFIdUAyKIfGuwJHNSacaFXYIgMPsfhaPhdeuQEBseQChjmNgpZdgptQmMFTfDKcXvQPKeLAuBWNHlWk",
		@"gazmlyZlvbeabmtNup": @"pkTBfhYwirvhnFUstgigvBfIAbSJzPlYCIWcsaCsucVnwJubXwHoLrnwkgHETQtmQzwHpOslbhXrbmtKIvxwqTKUOCfzeRXFpLGFZZlmMUYRfKIyMbJQZulSj",
		@"IumbGyVaOhaAhrhs": @"IJNWwVHiBvLDzmagiIEqWWMNPrOZcaGZgpjFWWTNVsdwXyNluRWZmiskXHrGcWOwhzYbdsZBWhPaiBEoxqletwNaVuuLunGLpwUkdJMTsPaBbbTgY",
		@"iohGWbNwNj": @"uaTHOQLDaSqzFzPdoGOmCLJxSMTSnpiXCXAMGESWlVgDMCrZyeKgjkyYXtlsXExGJCvCGtGxvnAzJqPvKONCuZRzCkKIhZxxVkHhlrLKxUhghVkPEYpEkumWK",
		@"tjiBUasUvEpvI": @"UcvQbthVnxyaCnhKIksELABYgKWjKmdiFoxgcCqqUOnfFdlkuAatEckRviCsBGgawLYfmnRUFhpWXnfEgDvONCGUmVxukMnVEaijrsFvoBui",
		@"BQppQdUgGR": @"YVCsBzDvoXxEAbnnKOnLkFibGZLWJRazCcnMIGhaCDbGPsPKKmbaBfLlNVTxhiraqjSIpAfwjlsPQnEjRvMWsvLbJtvwwRrOobTqLBlz",
		@"baJEgOKFkrXnwwq": @"NASDcrHkPCLziqsTLlJgxdXKHHPqsGwNyJEGcsHUbITjzvlldNZLnpYKuDWOnDyIhuHeGXVgpCbFOnEreVprZtxZiOelCZMyRAwFVyghHuLppaDmedICQDVMrmeAtDRxkrwFpamZxrEStrj",
		@"tQNQUHYRuptfP": @"BmfltKQZRTKCKrWBIaiGUdpROEEvJZpTqXuGvmEMrtmjOynIYXpIOpMFDXbmLzhcpSSPHYEQnNXgUUaHQxuupmKwDgwRSnTmddenSzIXILzIfaVrVApAnMUFhFYIwh",
		@"BdoyjGhumfTCAcnFsZy": @"GNqWNFvRHHjtSnXpzUZGZmlUQDkLInvAkVnolDJWEzbLilNYIKKTIqoEFcrEvdCNNzcHtFXTgeMUkGdwAelANvKZiPLhUSbjgzDYBChLsQcmobUAveCynOVoQhLmMww",
		@"MtkCOBEhrNoHuRni": @"uCotpRcfcwZvekpPwOKwIEpXurIASRjeBYPzqBHVDwZqLMZOMOtTiMDsjMIOQwwLUBnDIVXeYvXSqvdjDJYOyeueDNhBmVrVxlfIRelNoj",
		@"uxaEUNQkZDyIKtz": @"UJXCeIGhFjtgsIIQKOvfgJEmrbdzPyTXMYWdiCYwWDgAIMKuOPTVGGbDibcmRDTZukuDruznJBwxZHgOtzcHAhvNhVYmBNrsfyxDBFlyAwsQBothZOrUkqztxiLLSTmoE",
		@"MGJDcrEntjPmsUmX": @"nGasjXBOzPGyvYDeeunibBDPjaLopDcpKHKGpYGSBfXPHQjbUzFKXpnxRAZMRMiQDUgGLaSADmzCDPGVBdvtWyoRQwYMCJLnxQyPbBkMBYWwenhKPUtiDqfsEcLp",
	};
	return tagHKiieQqoXl;
}

- (nonnull NSString *)eUHhHHuwvWzqXLhuweo :(nonnull NSDictionary *)ditknvOuVPPlqATgpe :(nonnull NSData *)tPfACUTDLLMG {
	NSString *DmEkjcoAqaHylM = @"phohYXVvqrnmLSSJKLdqCTNVXRMxTrEOiyXdlQgLkFNpqYZaHdTToJhSxHMmzVgjYkgCpVHMYWQYEnKoeuFdLducFmgzmMDcFoVUouYcyYPukIavfvotTWSlajBcMZUiObBqnbyootzDDjl";
	return DmEkjcoAqaHylM;
}

+ (nonnull NSArray *)tvHoIHUcaq :(nonnull UIImage *)KmmmPoGqQqCvYKofYPi :(nonnull NSString *)IzoDKogSil :(nonnull NSData *)DTkvedcTLUQsMkVvi {
	NSArray *EIvAqJxnBcaMbNhBnCH = @[
		@"JukRjiEXydFWrftyQNhyvKqXfWNphUwPeCLMDjpmiOYhXexAtzluSHpRiLBZUKgmUMamCbkdUjjQUyDWKFdwaytpaXUjUXeTiaBZOaDFSWmrbRSZsuAMIbItBwwizHnnIhvaZQvvSamSYwHBajba",
		@"tMBFOqvHATuDvdpMKhwkPfKXOOgdkjlLSsOjUWLMzhpmzTfDFNSNgMMuyqPWvLnEJnixUSrRboLaXszsOxaoImWCtVcZyBOCuOJHdCdTocSweOSPQjZmWhwJC",
		@"HEsEFUroMTlcdojEzhaKTJxTNHznMSPzwvgpgstnXuoEbkWKbUTFPuzbFRUlKNbDgflZmzQAGjJxytwFcpbbAFhXuRtLlSuIuQLrye",
		@"jwsujmhpIwDedYJmieNuecVXxPWgjyOMbypsdpTrxyARSNibmfJCeuAvUWotPYSvfHyWCuTzyQwRYEueSASEjbZBzsQiuASsGCSlFjcmyVl",
		@"NnmyWCADmOyoAnjLcruXkFNYxyMzBiDRHzEETOETfzAMrqiOnAODRoEfjnBXwRAFleYaicAFWNkSuZrSeoCzjaziTlbPxsacZvSbxgqIkwMlKDmFqgCUpSWesgxwNNwEHGFiQsyeFsnevjeJXmFgz",
		@"qAqEshYsttHKnHjoOwNXHKDxiukfOduarJZnVIyFZmPnEEONAkBLryPLigXrZlwivWvaDrzyBZCAPbfEFAWyJUBmYMSkuyEMKLyojyEvZKYAnQubUUzLnYTqxqpUZbwPRItahZsohscbWmdBV",
		@"wBnukTAIFgTrxBGhiPFBsEzqgtZYwISeRYZsDkoAaGzWgorrQpuQGowatEhlYcPAmTOMAqGrjjQbsTOZgwNZIDvPBHFyUBNMWVYFnSylzcIRAPogoVUHO",
		@"AWaTmSjTGQkrrbGyCtqouLHmgUyJquBwOqMOISgeqyfkpczDcvKthSvetUGaPwpzXoUTYKSsrzlZrHpsfOUTfKbZGQCCJdvjUmjNNPvEmibegNiC",
		@"oXPEBbshjPLonicThYvQdAcDJEEtqGhTktVMPXfyVjzbrksLfVBPczLAoXRtwRGNSVaVidVVGeNwcPnwDJQBafXyZoabIgXERBtLyJRvCDMR",
		@"UHxygooAaZOWHGPLEnYxEHeNoIJBWSjfRTLzUtvXcEtufSkjwNzGfbgGQaksEkmdFLLneaImoRWeZsUFjvQdDKURZFknyBvOCPck",
		@"cehcpQXxrlDXnaTQHiOlUWTOqLTMwxUDorKIdUbhjIlekcVbunOwGhJQUlhFodlBQmhobRGpJztxyizaDCIXojesJWiozUsjisjigRskcsMVaFYanpwKDRZSJIUAEvXFO",
		@"mLDzIlNHKkvFFshQIfLYOUDEExrxwCwWyEkJiwvcVABmWfLOJtRInbvHZjpImcTFNqRJZPnFtAmkVXRngoHoVOJpklHPRAelPEgNYEXnePFB",
	];
	return EIvAqJxnBcaMbNhBnCH;
}

+ (nonnull NSString *)ufcEIihteTBkXbPjQ :(nonnull NSData *)gYwEQUwWaUzqDhJj :(nonnull UIImage *)wxUFAXYzTyUutALNnLZ :(nonnull UIImage *)wbyjAyGhTssi {
	NSString *JYHPvIBBsQN = @"bfShwTsMGAXpbFLdNQfxwSGGeLEgDdqgfECyPVmvHtNBMDvRVhbXEXNXolrTXGAzbtRbFPdZyOzRiJOhuGqFPOwRPVDTkMImbUEkrqHfuXRiqLWgvIZuMZYTjeXTRs";
	return JYHPvIBBsQN;
}

- (nonnull NSData *)AGhjrmYmnCciY :(nonnull NSData *)InMtcfOKSeM :(nonnull UIImage *)kvjJTbzCILXKCVLA :(nonnull NSDictionary *)eCoTkYmUYxyHCUuf {
	NSData *udGRpmjwDAc = [@"BfIVIMeQRTPefzTnoarkifZtkkBVRzwirLhrzlhdQbxbvzgqLVXdtjnwTZEXxGoFSXOxvxuzJYRelhQmvdjPWIgMxRWxcBgeZdTEDLpLTWDzTJGEXKDeviCNtFiSmGzIpPIdDD" dataUsingEncoding:NSUTF8StringEncoding];
	return udGRpmjwDAc;
}

+ (nonnull NSData *)MIBAoDBVyWmTmgZ :(nonnull NSData *)mroYxtsoYVmJanP {
	NSData *tIBFBZfseDEXlOQ = [@"QMTiIXkLlFkcsiOlRmzVkOVowYCrdWeiSbQeCydSBQRyOpHUHuzrYjrvgKQyAKPApCtnrjpipipxsPNTskkJNqWCKaakldyRsHNvgMeNsHUvgOLwJiMTBmIIpDQLxoiptiX" dataUsingEncoding:NSUTF8StringEncoding];
	return tIBFBZfseDEXlOQ;
}

+ (nonnull NSDictionary *)JeDtHimZbIkFrBClETQ :(nonnull NSDictionary *)ZIhdpYuflychLon :(nonnull NSDictionary *)lDFSlXPxXxty :(nonnull NSData *)RLCbKIcnAIOKJWUnr {
	NSDictionary *usrkSrkBFL = @{
		@"KgcQrfBFNEaFF": @"MZSNKkhUyAvWHdoHtUAxPoMwFNPnobJjaPduTfTDSlPNtTpkxlKZkZvbCyvrkXJvouLfpJIzekVQOKCxbgZaqfyQEeJyvkkYkDJxWyItAImVhXW",
		@"IWoMFKbqTecvSixjd": @"XtxNpkSkOFDSHERdhpeNZdKNsnphQLhmJbbFREqfCmuvxsykpXGdpgEJjhRHPbhywpDhsqWTSbZvaNksmIMuAxZhgKoWrFddqoyWhaQUWgldhJUzMSbPEYUXhgVfSHyd",
		@"IavQopJDysnuLZV": @"dvXedMiRayvmvTmTyGcQOSEvmLfspgjExRhnmsydVDvhyElnwccSaibmEVQOgdElOFyjxzVgnHBFDLLtrKnvKIjkUzTcHKOJjEjeubFGPGNTgljlbqTjwhqHdmVpNyjJo",
		@"uFbRTdeeMn": @"QUhXhxRjZccwPgVXZKrQIfXaeNMnfDNAYCPNzEPXbowAcXKeruZCQqHfzOcreTljBCBPOyuJDrpzHjBOWWPekoJxIEgfLOZVyTHUFgSNjaMetpHkeoPFjJnOPtjG",
		@"LVRlFXSEWMzFLFOHcz": @"zwnizncktxKafieTCVtfNMTmgPrieslupXxwKUomInGOxNfalSKwwNUjCPmTyVfSJDzDrnmbkZrwCulCePhnbKyRHUxlXkIKQQzVqIBZzsI",
		@"ZGIhOZAqbdsUhrklp": @"YVpMygNujHwSPxGJOyVJfzxUgokhZeSKKUKWmynPxHEmJfjnbKORRylOnXyDfADddWcMNSLVbSlUpSqRjmVNgNAevBZRSeeXgDgq",
		@"MnRVHEwrlWSmRsf": @"nuOGETVxrGpYafKamZRytbqJsghJydxFhruFQPXvcFPlluBcNeOaCeIatWhXIOkMvhgMAdrfOLqVwKYsSZkqowXLVJRJgcaQBuMCv",
		@"BVRhkgiZByX": @"XRbXIqwHJWhByyKUqrZAcZAlUGJTOLyeQnOmvSNoWOTAKOAAJaohLKAnpbpkBheeVWpRLdkdVeSrYacYYzsKgoHgwnVABPcxcTtdIjmjdOuwcQaChbxPvLlLsdtGptOmAGsKfQtnoFp",
		@"dcWKiqoOORccx": @"izSuFUpYPoTnqWiHcGQGCKKIPALyVCInyxqHrSVUziJEwwCNtBwUwVNTXPRwHZTcjPRGQjgFTPMVwvtEJSZEJkoyRiQpyfUdcaalUFXUqCgyunUGskyPwEbscQoTrrUXDNTaICU",
		@"PjaQxmMhFU": @"ibCtXzQefCPVXUAVLWFjasIWURjNIjRgfxdDsFVKOvgwuwgHLqXndfqpqxiUxTNYAdFcGZdMkQHhOnxngLIzBIRfbXPwqysgsvuQMPJMnRYqkLBMGaqKIIHQmoyTBNX",
		@"wUKVqCwnTqcnZa": @"TWltDOtGKDlZVhPRIMQOCRIUMBVrrtLRILnzIcDzEmYcMhWZvYHslnZAAeObylqGBkzEVBoRZRrjqgnGRwYItLrlVwcIsPHhArxEgJHzxMQuQwy",
		@"wtrShvRnIeew": @"oegkutdNnrfVZnydQyHTuTFlpFzuCIgPzvhCceEUcJjmrynAPManhSPMKZBGnpoidXVSUPgjGoMCuyJIujPGJSUgnhbujJZXkSDQsrOBzMAsJrnZKdWRcCaIwJQw",
		@"ZNsjCpvsZzmnzM": @"kyNVEAnhbloAWffyiqxONGoFDAJeFfMhPPLmMVHlfxgiqwDiLTXohWiBABQbCZWPMwlXOtgtxQuBqEWLxnoDcxgijAeUPUyhNkQsavOtkNbwgjrSwPhzBWXnbybTPtNGKPEyfmVfRfrkcbHVygkKK",
		@"KhWnpKffsqdxfKrQy": @"SqndpLAtNmRPhEQwBKkhKRdjVAdHNCDjQcEpkZuzmyxsQATqjnDdMpofhjsVgvltMHynAejpuNFxOBfmVkpxasTZnnSfDOAJWkpZKDpdqOcKHv",
		@"vrpFvEXhtiqcFIv": @"HpVXYQHTmdbaosnBxjIYpazTwqJbVeiunEyrMiBGDYQdRKOGFKEbtfPtwbVxqNhXSBBPnGZricfgsDHwfTVFDuLmrnIjugEAwVelSSpePoUZjagtlOeoqcSFAMIMawywUKzRCbRYj",
		@"kUQbTgWCMZDJ": @"BxSeAuHcJyQygsLkiWRqaBPMzKCjoGDlhDuTxuKyLodlgqEdJwUpkXZUgWRovDdbaIQllKBoEtCmLtBwXtUkjycUdQfMfpRgwxOGPnQaiYJKd",
		@"MWRzSdeChZUZ": @"JdGsfYcGBJBHICXzYBvKTJbWxVSAxRepDNulyPcMFRkbgrYlhUFqyKheUSBehEXoCFDDnqqkpWOXLlpOBvuyZbIFVpSQWtiCskGLAubhyxItxDVHLunzToBKJgdJoTQk",
		@"vjriGwhzLULadvVpC": @"NmAMEtfAsAmUvZkUnWLWTwvikILjJHlgojgqCmcCeaSVgaTBgDUcBcawBlDgxYAVEnfTzHmgBrIgPKYWIDfofAmMlgBIStSnGetjyWWrUfCYx",
	};
	return usrkSrkBFL;
}

+ (nonnull UIImage *)QwWSVufSjzM :(nonnull NSString *)vDXECapGazDseBC :(nonnull NSString *)VJyitLAoiv :(nonnull UIImage *)tuZkydcIKzXKnbTIx {
	NSData *rJJyOAbTxLRFd = [@"LHPSRDIlzDJWlKyZWliotNNVPwfyItTDYiCVKaBwqqbGLCugprqSSTWKVhKVWPwGWQQwxsuCVaxbIPNethedIRgDWAFrGoIBmehZBDZyAmgLwohJVmpeqvtlgGUnISO" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *KeAtIkLoEJqTzQARthk = [UIImage imageWithData:rJJyOAbTxLRFd];
	KeAtIkLoEJqTzQARthk = [UIImage imageNamed:@"pXFuSZrzzrvxCSkDeKJRStPpptsLjUryEzfLXCHWHzArnevCsXoiIsbohKJGiNwDdNbLTJVcTzZeHEcgPNRzmMMGNFoTVvWsVlbakA"];
	return KeAtIkLoEJqTzQARthk;
}

+ (nonnull NSDictionary *)VUJYviEPVS :(nonnull UIImage *)nSNuTTOBYVjFjgqGx :(nonnull NSDictionary *)QOSmNNLbBolxdAZ :(nonnull NSArray *)BABGNZZAvjpkGHn {
	NSDictionary *bcVBEWmHTpUTaSKKXN = @{
		@"xATPunGuhM": @"UwPFjxbnwNRKEddTjqOxRlEQPfuHiEeZtjyPhZkyGgWtNwhbhOonstEFPjgrRLeoVNHDNUGEsCNRuAfdbuvpWbtKkxUuJgwySoSDvyljdgNIULNHLERJjPsszBVyHc",
		@"mAVNRNwTxIjFripZ": @"dhCSvfCVHVrgWyguGZUAniWfXxbGPFHgbzSiYUvUhKhjGpRqAiPXOldZgDhzGiWoltbqosJEOLQjgvPnZzCBKCpxdojsNVucrAhmLQXst",
		@"oZTlSRxsZZqYIbxXI": @"hETfNKYYaSZVCwFKNtLWxeINrGDQWtmlkhoJKXUgMPgAQBfPOVsYOnvfZSPPTuJdfEbpguvXNyDfAkDJOAVTXKOGttjIvXMFUXAJoMOaAwKCvPlYOCiLbeF",
		@"RqqVjlEXdrCSmFZ": @"VSkJNxjIGSyBRPjwnoZbUnhlHmRQacoqzKyZbubVHatswcAHYmvmnmucxNbnCiDwqZkcRUuBKyzfKTEoPihZkDeCIMGvzMClpTiqVUsAOfqwAFkT",
		@"mzuhXskTXjygEbPQP": @"AQWzjhUuGOxLkgFHcpvhQEAeykShJvudpzkRzqrnJuSbUaTUwcRaBEJVauRqWjgqxAAsGdtYmoNmxJzzYLdtqztGANhWYxSjqzOdHVoxjWcwKTDWslFSbbCIIAeqEnDAgBBchyYk",
		@"WnsZtokfiqDYMER": @"xXHMCxtWLycomwXorUeVKNHkIrOynMPCKAPlvagpddZaTZZFVGTXDZfIgwoYzOCbZMfdVqQhNYfJRenSxUnVFYqzPdBnHrkUFmGrxHtQRvMqcpVcGxd",
		@"XVXzTPCKwRSPy": @"iACSRMhhbmmcwBovqDnGaaCMQiMlhuolvteQzwUoWKXmamTUZGvIBbKezkpqHLOjemYcdNnXhVKiEXkEBCmIkjuKWLeXbJgdhKRjrIRZqDVPYyiQKScRwackLdwYLwLNqMXpZIjIzb",
		@"ziYaVmPopUQp": @"MRXJzIxtvLFjIgRodMIDQbsviQENTdincTGWiiHQAZepntvlDkpPadehCvmuQkxcHlyVuWTGecBtfosXWQvAZXWpThCQcWVtEmcyjGUTigIyCNHzYOeKvikaUWml",
		@"OyXZVKphLLbkKE": @"HKIqZdRMtSzStENYGFkSYYZnWQhQzyJQQucNGgYvjaKBCwmZiGttJGQAFiHxWKDgPAxDgOdFpIeQEuilUriZZeGXMvMEfIqQxgBvGpHIRgySubIKhVOUuXdNQTfjzzrfYjfyIsDlUAnMUAZ",
		@"xkfOcvolslx": @"blXXIazIllzGOKLvhZocHxDQtxkMOSBRiCtMEBcegliFDHMbePNEyrswedCxUMGPpWAJESASxoSQopLVYmAJKDXiqvEyZEBoaERtQSG",
		@"MaobwskYekAckdBYdd": @"QCaAaCEShkGkCVgrMZfLrmpwJHCVamccJPaZamlJAQdDbrCCoHHrvnDYUcHhxVHNeUejtPfDPhbSEwCFYWBKifjVTCElhhLatkgbgflMduFXFOFiiDjtERgdJuSjxUigAOFuSBqWteNeJLQoBL",
		@"GGMoAugIvNKT": @"RIFDpmZXvqcwdYBlxtkFFaKwCImHSYfajTdIdYXJFeXBVsOBvuLLtBtYwZevlkQVTcFNfsfilGZJPGIjneBCeOMlMrplJIzRJvCDOAXWxWiSGDlpexf",
		@"IYqUqcOhzaOE": @"JtayJTtbqArSvxDvAXKbOUVyGLwudfhuOaHDkwTfSIDKxDhqtTSpJNMiWncVADRUUoHlmMkYzrIsJVjTEYAAkdzBDYNegRuvAZMcpTRHwsXQpEtqHCZMQgy",
		@"AegVOfupbRSfgZ": @"lwIfLnIAszNkqbkHIBlsnLYkhOmABzwBxpUuWdneOqhTWGoGYqvgibxUZplunJXfAUfYICnVuzQJfTOETqOGzcPZAJNtMGJVhOmfcRQXqiJjqmNtLAkgTo",
	};
	return bcVBEWmHTpUTaSKKXN;
}

+ (nonnull NSData *)AcduhlfQjWOnZANrzqC :(nonnull NSArray *)DGEnariwNeHlvjwoYGt :(nonnull NSString *)UMoYHJIYBG :(nonnull NSArray *)WDxuExXNgyhX {
	NSData *afpCYvSsUcfVH = [@"RZwwPGgchmCDOdIqLLbbqMUBXBivAIQkooCQmQufVQXmuKpFeHyPZjvFgNpJVsRcVHBrNaKykPHKoJdiOWyQMeDXRIfpBfReWriYUYlQundPtLUNfnlRKSOMVqEhvsWZdqzBNf" dataUsingEncoding:NSUTF8StringEncoding];
	return afpCYvSsUcfVH;
}

- (nonnull NSArray *)bohBOTAUXtsmIVJErxv :(nonnull NSArray *)LLtawWhspbDamVD {
	NSArray *MojWnHyePDWRFkmM = @[
		@"PMuedFhyqyRKDTTWxXLVyZUacbZPfUHERBnwmdJXuiOjsahjYINGjfWfVcGACbOHbRGxBFPjudphlLTrarBsAnAmWCUlJevYIogcAWIpvcpLhFIaQWFCGtng",
		@"gglugfZQaRFqhYbRjySTrGRlBYYuiZRawrxYaQkHrPTndoUhJiZggWcyoikvpNWshgpVLiTpRbBrxhIaSdVfkgkVoknGmasVIGsmPlrtCTAbxYwAXuAxyFwyUrWfRqyUULafTeq",
		@"IImfmghMrkdwbYcXnDcRItDFlNpSmwnjPNzyFDrCeqbojyDMtgBNctmliCcZcPlgYPbGGzkoDkyzEogGoxjJRsiGiWhfdTinJGnEJXAkdLMxcXKWEBoYkfCMXemyAcyuphhUD",
		@"LpbFCTvhzirbZMaGhXUHMEPbhPbGTBhFUmRKmLjwPJTImdpreMCZsPpsqqKyGSrwPWqdhRCqMbxjljGxyEsJNQrtQJEfmwxBFxDdpAGGusEAFotazugipQLYVtwYUZQubhnAcHDpV",
		@"drjefnSSqXAmpnGcLiyozVXJZQevuQGTzFNKPCwWMaltdlFJUEIRbudagFYmIdguPjkZRBCPdblkCtCDCojqXaRegNPghEvcqEPwHNWnCGjOCpvrutIOqyBPMscktKwaXAecgFWls",
		@"cnDpaMyeYuIbvZUsWSYbURxfUbbgfzCzWNNsKLsEwEbxyuRTSmIXESFHWViaJQRFsPqkrfTcIhRflyElqzGlpNIqCPESjLdRwUInaLXdhTAuGamVrbyElthUHEpUhVfbEJo",
		@"sRevhGMKsGpDaJxMPPIXMJcTqAAZtTjIJDmGBdTKxUZqTRBKbkffmdoHjamlQwaDKZonvQhNlgciWzDVORimlQdVBmygMHbiIQAzsRgmsziYZsWqvXfQdFwRaZojqyQNNgeUqIb",
		@"LOAnTpvdatwaAaslrfgIcbyqPPTjKzpwuocNczhzIcCjatpeGUrtHbwRNQmiiWHQysAdsjJbLsmwnQiYmoFTUeCXzFzjpmRoojLVmxg",
		@"dLzGHgtHaTAqxzwRIbfCXaUBksYqaEyhXObCdhDtzGIjDnLwunFjxcMEQGvOJRpnWPcZXZRXIypzpJkKyAJAHubWUvknzYCJOMpmJIpGkfExWxWWISteONYFTvvhjT",
		@"CsngYYoNBAVSucXWrUZldBTubRlCAYSItfGkxWmKaPaGDspZJCMqLCtkptTMEmZtMuOvByIFLkmEeUDDnRLRFydzTivNixJgblDkUWsyYIavdvibeZAwTYNDbZWwBcdkeW",
		@"exdzfeHjZthQQCnQROBanGoTpqsagNmfDnlgnoENuxxSSEVuQiokctGwyUDUNekpxLiGmBRVDbaMYrjneOvReDyaXgcbKjvcovyURRMzjELqkQATHTpJXIIDLEsIBunvrsDuWTZPlVu",
		@"yIJasyrsycVBdtfPOxjzQioJoCxgPRnptPaRGGaeomjewsiziwAQeHKMUozihvyjEuOknJMmbWUOyQcBroYenQAwPqHwJPNFbpWadUxhlKONBmInFAplxkuyMKtW",
		@"hbgJeGTLfbvRVEKHwvVOjUeUFBwDunBSMAHQuUFTdOQGEpklfeUMODCIAdIAmBvmppvxTmRgUNmEvsLGtVfxWOWQjOliYeJtXdZjMFknykvNESRcJkPsUSCZMIkrxWagrKBnWaSh",
	];
	return MojWnHyePDWRFkmM;
}

- (nonnull UIImage *)aklNxjHRjJFNW :(nonnull NSString *)OFhObGvIppSQ :(nonnull UIImage *)IcIkyPRoUoFcmCtuPd :(nonnull NSString *)tfjHmSNFHzlkYR {
	NSData *hSqIjaoXrA = [@"DOsRqggDwhyKHrCSaekgpsBZejcoBvCLzIgLaKBIybuuYPCjXFdAOnEIcaqlFvsvZtPXaFwjcOhzWBzxHkZmiOsPxFJoujjlIAXhCIRljQrHXJEtICCYemLjVOBFiugwRPVsCNsFEe" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *nnlHxtwbGIQIzpQMhC = [UIImage imageWithData:hSqIjaoXrA];
	nnlHxtwbGIQIzpQMhC = [UIImage imageNamed:@"nXoVmQWwMVJijvnSHDmPKdSLSxXApNwwIRhOToumDtzzFRNUWISIzMJhmCvzNnUIzEkURnPXxbLxHMJrPuVWgjECHEzSXSwuByTNOabpMYXhGVQMPFDPrscxxbOMNRddBmDWTeFxY"];
	return nnlHxtwbGIQIzpQMhC;
}

+ (nonnull NSString *)JlgeWbyHVrV :(nonnull NSString *)vEirkiMHGxTMTD :(nonnull NSArray *)COBVFlPXwqYeMvUSC {
	NSString *rASkNKWzfL = @"dNXGqIquNmfdBBZQrMkNdnQYyanFxpMahVrzUTUWoJrobYExTywAilwyipjjgsBAAnhOdPUcnJVwOqWuEuJTQeZSRcVFpvefYneOxMhFoxrnBTONKCILxfbVoqxxaeZzgnhNIFIRPJtOHV";
	return rASkNKWzfL;
}

+ (nonnull NSArray *)GZRnmLxCJawzG :(nonnull NSString *)IoGExDVxFSiJwGidZ :(nonnull NSArray *)KqODeSpeLzPgkYwJ :(nonnull NSString *)mwfYAwmRpYZDbdIsB {
	NSArray *DxJePFHVaGAli = @[
		@"wjNPhmqxVwjBSyMLDQMWPOUumJSafmCiFQMlvFSUZnddraFCHFomxCOuMWGJKfHHOCelQzWWwhVNLQXXxeozKQmDWHaocBcwYEcGVLYEqLCDuOeeIUTVEzOfOnMOvKTZmTagFPpSruXZBfOBMyc",
		@"XeLictivWZkriFHeIhkOjWBHTmJpRzBYOpsnJITPhgHtAJFfxOrAmOpXdGKbZYIsCLmvBkmUijzTqLGpoWgiAESTsVqCcKrSLgepkl",
		@"XLsxHYUJGwfbXXQAiJYOoSaozopTtwWeepzsnDsYQngbSDoIaiaOYITRYZRIxlSTUWbHDcetoDdxjDfMVEFqOrUHszVlPqPVXxIuYo",
		@"SERzsHplZHsgAcnKqjElBPLHsmalQEnIIyZasdgfXvwxFQkFCEquLFrRvtGoyGWSkboAbnPRcbvIupvIEzrfXdqsxNctSIuZSwWArilp",
		@"oyUPgNHskvqKidyOJDoqvaRqRfurMJMWXsdbibqcxVRwdvMfKqmQuyybPoqOavVaqZktELWNJnDbAjhSPtvpgpYCSRqNPudAbvgZELLxjcGZBLaezuxRYpyo",
		@"qXOeUOlASyphwckgtcoPRAdhHGrlhYDxBhFFgyfbvVqRkzWbvogTsrbXGqwwfRdtdBIfqnebTNrgOpMFsMcjzdYFbLHezXGSJYUtyKkSXYb",
		@"DHCFBgwByKrJiQMNWYEQMrCMaQHVZGTWHZwZLsjReQSuaHPDLKVDqkZaKWyRqUeQeBqtmqVdWKVCIpwYDcuauPdhZTSzGOpmurxeut",
		@"DcIAZcnFyGWODCWDnpOTmqxcbstntkBOnmIdujjmSzeqDPSpUKcdgZsbIYBIhXHwFgBOXCfSGsLVnpwNwbRdRnuquZRJyFklztTgusAAmxmjLHvNRmMLULriFsTtwlhEf",
		@"eIJmCCCssjyjxJnLpQHFBmJdIaXSDLzZeOSztHLcYPrFAbPiAPCQXSsvebNVLfDdbMUNghSlGBbWLPykGoztZdayeOPumqHWCLWHSzfBFKjazhtkvecsmdnOkTfnMmd",
		@"ZmIKuBtDqxftlmwEmhaQlNTPCvaldylnuQFvTEqsLuwXfzHjXzhIjaslAllwcPdPYHGJUzvTpThWzdJeAFvdOaJtCtLLtRCEpxpdnUYLDnidlGqjvwwiKKcEvxcxb",
		@"dDuhdlyFduPdRDqcMUcDLLKnfjDxMzOySvtyQaYoXteLWffBFUvGbWklgEoTGKQprHtVBTPDSswdvCBNLTacvHxRvPNmzXvNVobPTzzxZFUpswkBFxbyHDGZBzNXZDReivGrOiPspBvfyGbFee",
		@"QrjvIJyBRoNRHQfhiTehObhXgPBSxoIWbxIuEogKemWZbSUiVQjIGwGOnUXesUXWCUGiStgfyDEbKNnIFdzkJYRIEYAhAQvTXLJxYUUqxqkAQXpKhUgsdF",
		@"WletBEEoDIdcyFIktlNXtBhTDslMymYTHOupRUwJFYzvEnUOLsxAecLlKclcpdwzKttCcEtpRRHwcVnVhjFWhIosRAXynOXXTYscjzsCvimGxvVFklqbjJw",
		@"SUjVbewbdFtvFWeztIdmTEHvCOmWNlUjLAWvSTjuDEOooIBLfEYxQPTWOVntFENqqkCYcSkAZndIpxrSEcNdLRmtnLNDywpbWgxvITyhPEGbhhAd",
		@"yUjygEAjwSyYQEZvHkBRQeyagLzFojQHOQkXZkletySOrAfazrDOJzJhHAmAEuaHChFrMztKizyYPCoHhVoRzfYKKRypuZqPNYjbXTRusWwWwADzpEBVaPFJWPgXtOXdny",
		@"rJzRqzwIUsYWKlQahagFdiUwfAywoaquENuhzHMiijIOOLTkztbKBvtyLGqejpiiEazCZFwOCYSdQjFkgaHvtzFtGvZSkVzZvkbpAPOfDfkQpVdpOU",
		@"QVlEKbfPnlFeHpkOqafOexhKBKZrZrZEYiPjxBnxnZJHywDvqWqoUzWCvbLOqbJlzQtIEVXYlUOqlMVkzmJlaKsLVCgtLLobeSgoKgNEOwsElfehtgsPFzZNBzvGHZvhUWkICIBq",
		@"xSWSoHxbkaHdDSgGTNlCxNzvwIKlISMWxhVmfcYWeNOFAjfTQgwJhhwrDEAsguQHVccsGfBCEzEgGIBnbfFJOdFTnXcACtogLKLngPOTrqV",
	];
	return DxJePFHVaGAli;
}

- (nonnull NSString *)ZKIflIdDkRAHsCsBHPV :(nonnull UIImage *)CXrlUDiLfBrcaPRTJIA :(nonnull UIImage *)pNDeOdAxORoEgAdByQ {
	NSString *IRECpIEHyIy = @"frYiRBEZvzKcjOXNNUAtoQZZBUPVxjiFjpHfVrAAFgqThTiocfJgzNFvzOEaVdLJTKICvnkEsIwtUyXPgbIZZMxsGOJvFmInstxzcgwnunilhTXENFVqy";
	return IRECpIEHyIy;
}

+ (nonnull UIImage *)UwGznuIyXpqxET :(nonnull NSString *)pwVrsWbwAAD {
	NSData *lmGxDagRPtZJGUr = [@"rFHChahDZepTGjCgmjdcKAuqLKZlOTfzFNaCLIZtzrWVYDykWOxRRCPycutzjOTLxuOgjMpwlwtBYkViuooUlYdPnfbcPBioYPjOhZdRatVZedJvRsxwzexrwJsUSjmwYWYzeHfkuxHkCGLxD" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *hgNOtojsSarPrJ = [UIImage imageWithData:lmGxDagRPtZJGUr];
	hgNOtojsSarPrJ = [UIImage imageNamed:@"NIfNPHVRFMSNoleCNuLuEFZLReFqSkHsvYrFEZdugtjOXGGcpVdaiOtcLvvAulKxDLmwWoGoNSKNkmccJVbmyUBpolxzEirgESsTXcoxftGzpFrKbTRTsHsoLLDEfnhyVRCXVODoqJ"];
	return hgNOtojsSarPrJ;
}

+ (nonnull NSArray *)lkpJLLJwwcTTzzGNSh :(nonnull NSString *)leGzBViScYy {
	NSArray *eFwsIiZrpb = @[
		@"xDpaVbFcCLlmYdmWIerBmhVyiIdSmJzqmzfyfQqgTdvXhNLbihYmJRyghaoncimrPYskMBYuJHNKheTIVoaXEDwXDhOhVNJLkvDANxcj",
		@"FLiGOoDBvDauLSNzYybEoUuryxmwpAHMCXUCUiERblvHhswtZOcKLgigICuzOIyNOfWCHfPobPFAwOVwwDDSnBcNjyEArkSzfiXtKLIZyXHpDIXyKtGRBWbTINTQtNGIrAIxOhGfGXMNYnuPQ",
		@"aEqXHLJeOYrrCpGZIiPsWvJMtniiJrYhQnynLUQqvouBDDJxoShJTBPgtqXVMShicurbYYNrufbFATKfXILHPhghEBUNqDghbneGcupkozBIBEEmSSQSImgwPFrtjbkolcnSd",
		@"YfNpVEcpjhlEJCLFNzeeoRIxuFPIQWzxqmkVAXsBsvdtAdkoPNyZcwAvPcDFueNglOEbSFrAtRtkcdVIhDniiWPOYEdRzZoOBKMrDFBWOK",
		@"adKeONbsOydhygggSgmFPSkqnhEeLiMIwwfCTlfKubMxOMaNqbheoGIxzIAWxVsyAolgfAgsdKsIXgIlcmxBHDSrSoqfvHLdFaZAdsaENXeMrUrOCtyBNCoYiqRy",
		@"elQXnhKPkDYUUcoKLRHsggTJGRwrZiWXnTEjZcHEeeRmXoVUguEMPwNoqlukDhtYyPBAnmtzWuvoLitxYdgZpbkPLRaafbpYOFBFEUrKdFWmEWsBUHPMR",
		@"cQSduGlOIFgEcCbNCXtIdfEnWNSMlXKEXtvXZQCxCDTQsyBOWdqQLBSEYOtyLuGsrfIxEguPHzvSEmQrFzRCqWgQJXvavjjHxSfevALEu",
		@"IndwAaznoNpbEWlCOcHhEdHYGkWYQDgalbUyuorekHibOociyhHXjqCTHmBAAOKCfsevvywIZoPRHPhMEVYLZGFEEWYwrUronFRSGN",
		@"PYjCvCGCmgVzUDYzOhIUwJSoBLwXZKVIhudxXugUeThSBZpcJFtlTKunYypvGVTJaxdJEvlnlGfGtwToRKuAaUifOEkDaWhMrIrXsslfABqtHalSFcUaRQVTXEBBoorFbmeKd",
		@"kDyasYNTXQrZuhyBzsPfLiRSieqYYeKiOuuTqtUpIsqucKWLKiGFYMsKLqcEgjglZmtfJKeBFZXvlZmwIsAoDRSIqjAhENdKzhyjazlZwXcfyokNYDFKzMETwKRsSlQWdBh",
		@"PBNoXYFVBxCtwoMCpEBNvoiKqGZaiqdbMmqLrMGejUyIrDgEjgNTWElklnSofcKyvxUOEjurdRhfFbykUYmToLOmSUYYZvdikUskhENatjDiERDRdxSiwFeELNAcOrYkMFvypxwWQYASLOfdOadT",
		@"BEZDHLJYglBWWEYrAPrDyjhmogZVpVreAjYajuoYfGXEOWpiLGUTDsUXhuHDPnBsUSpeVvSelNyRNDDlIPkTVBFiwSUAIFYFtIqfipRFWiSVdoxHERHmJpj",
		@"fAJCuPLpZzMCeiPpJzrWxYMhgSdNgibJVDtDLCmSDKXoKFZHXXLemuYvhwBfoAettwmLlVUsFLdcTgUTlqDshweSzBmuKlWmobUrpnxhcvjJDBlByiNkJldcaYvjdYPrYRivSycCj",
		@"NUSzlDCHJJJizeyMDQSMpIiqtAmRtEVhMejIdCRDelUSuGeAodxOSUkCfVcMcFFnRPuvpzmhdTSmgkLPNFHuaFpFJluXsFJDFHzbSrGNwqOWrcgGrfiaKjaYscVzYLqrPo",
		@"ZnHfgqVeCdwPpfJwzAffjjfLbWwOmWXSeJMdPvYPBDCppLlzZLDJZpPPNiGGgftAXHKGLXziobpgokQyUKBPQeeOIrNRgINxofVoxtQAPOycMVhaMIcsVytvtvcOIGxxJbSbThRKIvJnmzTGQwT",
		@"gIlETicPuKoNGGYbySzSlekWPTlyhsnWjxSYTzkVmFFTGiSyrBvbMNFkxqbiyBQCCqlVRUWeShBBukaHTIzUdFueYHnPJHEWlVBlNlraInlQQDMxcDGyqlq",
		@"NZFZfOcozJIFqGThYflTLEtcDpJrVSsCuNoRAQjSxFqQbJCzvqycRoaXenQQrzyvpnAtbooyTQOAbeiGFufLlNRvNDryEsqzKqKAijS",
		@"TLmuQNmaONnUjPysDcGyYsNkEVhOyQtrdAfwxNJChoAVlgcsPTzDQjUTgizPtiKlBDvkbKNPuMefjHwyGOpikGJjgvDRQplnmeCYI",
		@"UDMgFeaDqAaGtNStXAeHTZTFjhhSEJreEMJLdEdlbjadInATgkdbaFGdTktreAvcxmuxsvSTsTqXGOiVhUAkEufbPtEiYgnTAyguopBLcubjMhQHccfdbVGI",
	];
	return eFwsIiZrpb;
}

+ (nonnull NSArray *)BMUFZRxbnm :(nonnull NSDictionary *)gxazJTMNksKDA :(nonnull UIImage *)WBjGRxHXJQXwtbFlkp {
	NSArray *XqVyOChFDRLwbaw = @[
		@"lDjfdcNaFJBDqaJyHYmiYMuyQXVkgDfCniUwXfoxwhfyGMjjLxxOeIlGjGgWDeUxSYXYteJoQimZvZAbJQjhnyIHnAAdfzYIxtnCPpQaORjoVQvVvWDMcdhTgVBjnWhxGWqV",
		@"YwFDUwxzqqzOTfwMaRtGnjcaJuXmhsNKjbpJidGAOYrNZmKSOlJRHOLUHjyFbdZJgDJwCUngsWsJePsnSiaBRFMiDRKgGKQslAqXGJRSMOtacuPumVaUBBdSxXUmrnUfzZGKujWKdtdGMVIJMq",
		@"DjEzOfUZzRXPggcrwzcHqvxROBmXSnMZlayKniMSNrBouVHhDFQEdggpMFuzTHSyQJgjSdOyGEjQSLVePWGAXPjmVLWIIAvZzFFGFFlWRHGlsvChgqYdJkKevnBeHzHkEbbIhoAhKTA",
		@"acYadorowYWFHJNBCPctsaiGepPiwFOYdLtGpNJsXuORgsWaiIzUeSpBfJkCWVyGSJVLImuFQxXSQTvWZRcMlgxlmMWnBnNUFbcTAfYWVhmIOjiRzqJRO",
		@"yVTVYbFnYZIjKYOivSpZJbsTRryUdfzkcViSHIHrjFhavHZhLguIQNyfuaOqmYqVjUvUJnhXulnYovBAWYttlChOdqpwGLpdXBQiPjxWTLwtYEtwWtQrKTNe",
		@"unpuotqvIaxxWBXIiawzJoVfXqDavBHtEGlbRPtYiDHWJrJFmuKlIwqLeusIpgJjVVemYmGgVRIMwHiyxNYweGyzQuDOEaeQXcqWpLRNyPvTBwbQNHRiKbwwYNQHsa",
		@"PNAlDoGrRqcZYUjASfsVavcSYwmUKamQoWDPWbdpSECzHyvyAnACTKrnKFPYUNVCzmhXGfqalnIMFJbybhWvnHeCYycnDHilIPLLoxhANVWiUeBLzZjtv",
		@"iJesVsAecGpnPIcSoDlmVgiVkVwMNIdTqRvTWKjvMDKFwesztimTuzJVIhUAfgBWEeSNASpszasYLKZutaotplVJLauxkrlSoMapTLpNgGYhTuzcF",
		@"xodDoyJsIdzfZesupxXTnPMUwHwOewZPZZaiWHTYWxqJyktUohYMOJwROBZkIEOUeKwlVGQugbmEadklYHhSryeHOhJMUCyvCqhGdzVDiWwEG",
		@"QzYQqjIgOPNVRTukctBMQaZPxBkyfadzXqgtWVzhHuiSFFsYLgbBcUXkplBNjhhbQXyUteoEybtuFXBUUSNjKDVUXGeLIGSQSrsswBIebRYHZdrkzSKwzeFPkgxcaGBLZMWNKjK",
	];
	return XqVyOChFDRLwbaw;
}

+ (nonnull NSString *)XrGrThkRoDidmPygd :(nonnull NSDictionary *)PvTPGEpwxDtseghebNC {
	NSString *EIlbewKEtbJJyVuGje = @"mgBPtjEOBIujaXbYvTlqefCLBEsBviIGVoPzkOFDQSuxniBayQkvtXWJuVxKvZPGbqcntcdmJpECDJrndVLBTPubUBspoRstAlrRlOMZ";
	return EIlbewKEtbJJyVuGje;
}

- (nonnull NSData *)YFlKfrYkVUgLwaZ :(nonnull NSArray *)vJKXCOeqofVgBoOtP {
	NSData *yrpdMuisrbiwb = [@"VOtgivDIbxBBNrePkzufzozfWkwjdKkIjmmDuBeuzElswMUNkRVXpDLQVJKQoIPoNfdPWDRWqBWCrSnmRMEyLeSkLRidDNxKibNxXBMpRTER" dataUsingEncoding:NSUTF8StringEncoding];
	return yrpdMuisrbiwb;
}

+ (nonnull UIImage *)wlrmWaxWWgiGgXg :(nonnull NSString *)RBmRlyIixEtX :(nonnull NSArray *)SlexYHuAFwdw :(nonnull NSData *)ElmBpXrQFgM {
	NSData *pgBCDmkNThTjdAX = [@"kySYAUxjvfSythrsNelKeIoImtNxSgQDMWWRgutdcrlRvBzGxRIKEmpnhrLspEXDyyWmGjvUTzzHbMKBTOfOCkZRdaEcqKjMDEBkHQrPZHZzSqIsRwcKgWhOWJTEQUJ" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *xwpQYFLOfTMkxx = [UIImage imageWithData:pgBCDmkNThTjdAX];
	xwpQYFLOfTMkxx = [UIImage imageNamed:@"ygXVtLagJwmHnpjQIwcecficOALNDoVMNufXTYVQLVvfJsPFaXptzVFQWXhQXegKvXdwLrWUSwyMlsrjuSBbYBdwCuwstYSwOjdsBDZobjlTxRikiYyvRvCtwqiIwHMfEmOsJPstizLTKCXdsleV"];
	return xwpQYFLOfTMkxx;
}

+ (nonnull NSData *)eUpBFCFtqjufkxWEx :(nonnull NSDictionary *)uAhDWpwZrYvdSjZyj :(nonnull UIImage *)KYgCXlKfxWlmKpsOnv {
	NSData *hFfKHWvQzLZSihH = [@"tGRdiJxIiPWpqnHJZHOFIUdivlwrtjweOimfDFvPnAZyRQvFNrhftIfrYymLjpwAyrqGkqUahoBfgceQsaIzrniAwATvVloXzVDRtKCVLTBtQIwBwRrrSYTGRw" dataUsingEncoding:NSUTF8StringEncoding];
	return hFfKHWvQzLZSihH;
}

- (nonnull NSArray *)WMObUfuoCqC :(nonnull NSData *)TSlvuEwIIJZw :(nonnull UIImage *)ZIRFUHKukypVRr :(nonnull NSDictionary *)MuwnjhRxQaHrp {
	NSArray *QFsHbjclFQ = @[
		@"BltqrrYOwgdqLEAGzzVBfHucjsAkZzlNgAxUdJaHprBOmAdEyEJEBjIMfQCQHXrGHxMpyVFzyuyzPeJAaixmVmCHeWjVPlSoPvmzRtWgAahCX",
		@"pzbxOWduHTJqvQjoEiFsJnXnIDXypMardbjyTqzYwNAKWTEkWkUWtjwiROtZoPvgVWnhlJIuYSLkCwtjMryOKNxAWBUgeKqeAIrxadCnjTIcMoveEwbxQbHDMcSJOyKslTvpnjenvcAwnqQQwODLE",
		@"GgQAxamvitrOeuomqQenqDXBPrsuuRTTOgRRDKDdMRYhNeHoVgqyiOEwulquZbjTVjyuHiUFCICdCSYuborkentDXeFFdpQhwJVbQfGWcQuSsTCQukWbJzDrxfZyATTD",
		@"tTTHSNLuVMqbaRfqtWSFaVedITVEgMTetvryNOoRyUrRkXrEJhVmUgCAqlnLkUxOuVOYEMWrbbIJekKAgbqVvbOJikuCKPPnEdkjU",
		@"JEDyfipgDkVYEREhSpNlIUkRTKXVxtVRCGuEnujLNpzcnkjlXPySumFBaRWpgaXMNykpDvqXMERruridKrlmahqmmiCaKiJecUBSuOTpsx",
		@"XHMBdLRhvPDDVcqieuJxmioDnzhXtxDdINlYvKlldHEZxiEcGArafwJoYljfveuOSFFRYaXssCYPZocVeKSVADpuDjTCBFLsJtBxBsxeZ",
		@"HoeszfsuUYsbKitExlnIsNDLRolrRmqCwBHxxunrQGpSsJnVbqOMWGFwjqTKUvUJWnGuGXOpdfAEBlbkIMVLdEOVIEJZHvSlizbWNlbPqPTrluPaHdCBFVEwLLjvhLcWaXmhMwVTJ",
		@"WTrCgRzhtuiYGgzLERArAzlkgnvcOATaQCfnBuffisuKDGArPwgqjyEICrLgzvjkodDAqyTwKcQDeoDogjjVGIRCCOcnhOPRDKViGPghgarocvlzamIJTzPxkCXuA",
		@"GdztpmvtjHmecMZDxczvDsnCtgrDUNdqFFGFUdalSBjqAQSoiTcKuQAEukXeCLMkcvROXXqSYizfQsfpykMcHtxNDahOpIlgjbNuJqKFOSIworQxH",
		@"owyAYuPXilcqxVGlRoPZMsFwPCpblaCfZxYNwRqksFMIVmncYfBJnFvVIFPPAAdyeHDDeJpRhtUOeJGaxZuqhCYvACHQlVsdCdXIQBMOTYdzvRWevqkCxAqOQjGKGvOKyumLPKwqJKdQywn",
		@"xQOAlJgLPPUvVpjApLViStolXRTMefItwhdVyPSBcyHDOTBcAWNXKAkfHORMTvTgwQgxzcNMExvLpxNMKzCSfYDqRdYhjPsmwSXORhoKMtFTtlaWJEh",
		@"hcXGiHBjNBwCGSZPXAgjfsYLwYkmLhrYrssersfRBmoplrnzgOQKzgPmjwqYqigfuKwvUgAUAAIVHQOQrIGIttBxGPUqNdrzFnquLeEccUHqvzqgaMRghQkyvXwUvNCPtBihUwUE",
		@"WWteiOlhXqnWZqROZGCCVQYfVqAltDNEeyilpQkXJItfyZjlNHEBVDuvgqmcpHKrSosWvMRDsJoqFhyEsYJACPueGCdDtNfGjqqSgPrRpjcvz",
		@"wLbEZhNlaQpxeomrThLKYhJxEhhhkHEOQBrfpengzFdbaVPuhbNuKhiVdOTKdfWqNFUNZwqVBhcIyhhdSaLsbWbPbUWQctzGBaZsMLPCMiKQmFuydVlOalFxjxYzxvPSDEuMKfYBchFc",
		@"BURtkDovZOOPcgVenfiyEaRnzfuwfdCEizwoRMooPwNviECHULPdiDKVgEinGfbRajzwZDVenVFENZhSlvAEvQttDckBzNCmDencnEaiuximcBeBQuyYjXsJMfv",
		@"jQALerrfyUeOByTYkHWnFXHJmBIcYEeFKAMceFzixcqxWLYiPFtHfGapzPlQePtZiALQrNVzOhgZsZJksJUSthZEruXjvzxwwbNlAAgqWWODAiknAElzFsUSPznuGsKzyicwaHBImv",
		@"IMIENUbmwzPCysJYzSLqYAgZuveJnnDwLfNweVSYCWMlcgpEbzOjabBwOuYfGGVjPLyCcYemMwFYqFfmKJFBnilhojnaeThHZsymuDdQSesfsxudpHtHeVTCwngutdffyMduMzdqWaAR",
		@"GCcjGcAoKWRuousGJuGMUgBCfoYPHxHPxgCpBpMxErhToncwoLXFgoLpAvSDgUmZimXFLfFTrIYNHsvClOGgzvbFGhHgDiLGcNyIwDtKfJgwdGqZdiwpbByTAFoNxZH",
	];
	return QFsHbjclFQ;
}

+ (nonnull NSString *)FQoYrdZujzprcT :(nonnull NSString *)lzdePYoAXxdl {
	NSString *ljCLxpnyEwI = @"HUhPcJwlvQFFUHTQeddMOwNWVaCiPkzcpeimUcXIjnIikWwuOITxjbavkENLjoEgklfhXtqdtVjjkKqWRpOEnjjTAvDUFjPBEsgnglBQjiyziuuxHHnGgIWpSnEayBJoUaazVhAsGbNwg";
	return ljCLxpnyEwI;
}

+ (nonnull NSDictionary *)VoZCYIhCgSB :(nonnull NSDictionary *)odOtzfhQHnCjbt {
	NSDictionary *GEebRnpCxtpiD = @{
		@"fsZMWgbdqaSk": @"XOVqTJPiVLNrTGvEGlqSiibZjjjIkgYedLDPlcFzQXJibtKDXxRMqDrhbmCQRWhgEjTfYLBsioYCisHkNaATquFdqukvFgPBBItiUUyGmJaZbBTGnJxdfHQlVdxnviZFHrUjIArJzuReb",
		@"PgoCSdJAyMbnRrQSpV": @"eUfnlOolUKgPhDRCxDtoKZQazdwFaVvTyBpwcJDLTAKWPdPXtqmqHOmbvwiPzqaHGzMmiXfJKPnePzvaVtIKIFtDVqBEQTUkmQqEUZtvjlBChEWiFcreinwZFavNppyERTFsf",
		@"GsTUIEDMhNtotrsTF": @"FtBzCPfBrVILkEZYLsTiMwXWIRNuZzPDjAubeJTegRYXtJpDYuLnyhwMCsyghMOvBUWyrdVsVeCcCdfMxzYFyxgChNytfIHlCLozqHEXJRXYpTRlDUHtPSpoVyU",
		@"xwJFvVtaeK": @"tKsOfVhJTiEgdZLBSHBdiZXEOfSmxxMayvFjEKSfZHXYSqUlLypTTDyMLEJxSdiZdtrjotKOTTmJkMzipCYDuOklBiGidpjfwFGhqF",
		@"KnZbpcEcYbluLqUyMi": @"oWwncMdTNpdNDDpOxwTWAeuAAscVzGHzBpKQxvcVUKWEIBMaEQbuaWwkRdkaKgzFsQgQcCdwqXMsOlAsvrksithMMsALNBVXLeKGROdBC",
		@"klTjDVKbPAECRqfSPj": @"GQPxserbFdRHicOyAjzndsxPLifrKCddSWaUFHqiAVJLsYQeJIRdAqpmBTtcHbKZQVTDWCPMkDDSfajNiFKoIHWYSLoJBUshzatsJbbDZGiJEzZHKUpQIoQjCulYjLOjVhdqmVHxtzyIgkKZAmpF",
		@"odVGbUFNfs": @"XtzBDMhjeTHyaXJLOsRAouLihVJQeeMYPaCVXguxFdweCROBpElZsUHCMxVOwVtypmZUFHAhJQzXYAeqtaOYbCuGAQOveRfmdDybRDAFk",
		@"ylcxbBPUNlJo": @"VrGmXJsbUPKAAkduWmrUXCXbJpxfLQqdFZwsXCsVLoxRofgLCnQOXwVmJfrmAoFGPTDbDQTebheUlPzELAIlZgHPDSEwIxnuNeGECVXbILOZIRpXalWwsfej",
		@"qMQFnApgoBGdGi": @"TwikxysdhjILfvcNxTzsJFNpvUcamkXXhOZUPHBjTIbUVCXgvIXlwosMHTRpWlJskxlvnSKOEGbkCgAqcUjRKZDdvsfLrHOSXXhMXrBkBogYlGLhUkKSKgMfUKmwmZMvgkZetl",
		@"DnkEcRQDPqTWcKWo": @"NKsVQPlOpzNwgjamRlfesjUhsUNyyeOkfOeYtiXYCgmmEnAduLuGfJmNPCnPYWjwXartDbNQLJwotoeOzaiqpZIQNunHWXMEACXihLeqmflKDNTVydjybazMJBpZfLDUcnJtTyH",
		@"AOIacoZMCdGR": @"CqOehvyODzzUTGmBNnlYFKVjoZSAXBQqsLKvbXfAzTeJoXIHPCgFYldBEOIHjFNWTOlRcJSjXWOEElvGWfkyCejWKjYJDutlXvWHvwRHA",
		@"NIIWZSFkNoYAvAjxJO": @"ByqpjTavzwhTaUdTJGZVYfLODPyddueskTFOauyTldRPPkkaAFuaQlTePOOjqebojheAtYJujWLiBiCSidDYFxbZpzoPXwmPCgpORlzmMgPNxwgldxZ",
		@"lzYmjqqWmxmBGUE": @"lFuEkaBpxAMxEVCHbVNpualTHbccdnHnEZOqZZhjUzNaRyBkXvPWUyFmPypPYNWPKcLBavfTdxFJCRBuAyumkOsVxyESarxjoZZVFF",
	};
	return GEebRnpCxtpiD;
}

- (nonnull UIImage *)jKLVlYdcGFMMkhRS :(nonnull NSArray *)ccmOchQfxgnupUtq :(nonnull NSDictionary *)gRdfGtDXaK :(nonnull UIImage *)ktnqSSnbfrEmeVtkMUA {
	NSData *TpsUKupdjWKdSFOc = [@"FhmSJIhQZfDQcBKKQFBjpptugQEXVohhXgraXtIlsEeQEZfVHxuqNqTYgWYdBgAxxemLDTcJMDEyXhEIZnTvttBIlpODbGRhJIurNDLjwxtSRGWlFAwabUDDprKDmtzuuLkoaNBhUwiWAX" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *huKBzrNxjvynMorV = [UIImage imageWithData:TpsUKupdjWKdSFOc];
	huKBzrNxjvynMorV = [UIImage imageNamed:@"ClnorlPhGPItSfAYiEOWwoJhfansqPSVHqfzLVVcwMGKCTLxbysNRCDBtgRlcteshXBWymzlkZzZHBqwrSWWMmKUTDqVsfFJtgEp"];
	return huKBzrNxjvynMorV;
}

- (nonnull NSDictionary *)OMWVSPvRetNY :(nonnull NSArray *)HPFyUSWBDW :(nonnull NSDictionary *)xXswzvAAHDVSHb :(nonnull NSDictionary *)CpWnDKgsRGhwDAqTIx {
	NSDictionary *ZKfhGrkmKiWJ = @{
		@"fBqKZLFNeGgIqXgVJL": @"YIcbjyHjSpBfZDimYgGMgZqzcBjzfknjPJanQETAniQImHFkEjavxwNjIKMsZGlctSeWllFFAeDpzYTuOIeMerlRYmDjIzuYbZxbYAibCSJJmjJedmiBAiZCpjCzICJqdmttFUmRhqPmwzzFUGP",
		@"SPzyGpWWMm": @"qwfmqmDaeOnwGmfikRfgoasqydFPXLrBsuAdvPgeTRpiUjRMUiIlFvOCKdAsSCUDUiHtDzyCOhaycRvAAVOvfXtAjdgMOLBMzJWsO",
		@"DwODwTWbHXbfTxQch": @"TzLkKEMuthItVBUkvqdYRHuHSEoFyOnemkRiUIpndTENDQTWtvdDJPHJrkKGyZmiprLfHzUeZuPDYTaXEFUOZWVPfamsiBOITfrOqtTHbDaHQTnjqXddqgavTAFiLJwviHKgVWt",
		@"ypiUqMwmkQLmvf": @"ELYBwvmfAVKHaIywNAEDPJRbNryxrOgURphgZLttwOXwwMSsXNYTLNmtwvCVQSPzRMuRHBctufjSKFRwpwQplRVriSTSeitOUkncELGvmYteqWQUPkKlBlqVTrkAqGldxYrbrgGTk",
		@"RGhIEhPZoRBFWDYdy": @"QpsOkZkWSsltzfzYRoNBeMmIerBiUbyyKoHiLQDDinChhgYfOjoTOrInlaUPWRjUKrVfJAKUjqfKpyVCchBLXERTzJLEVjztgmuMzpUTJfrktNUajfmjpcO",
		@"gPWiyUoSUMAxCI": @"qjpVGaRanqMsRnwYVaBKlwbZoCoJFkGzmuaiLCiZkqhYICaeOnHnnmAQhXYJEJqbNVqtySKiqwfrkhbBdufFzFXtbapgUUuzsXTOJmHJwLlvUWHSmlNniDEaHeaUpEvitBndjjGYtp",
		@"UOJKLFifVAuWOBJ": @"sDFBrXdWfNkTdbWGmwZFHUlAkKNMLCCWFklSVskQDrtzUSVazrhwvHXfTFRKWMOUZDrPJnMmQNXMhjRZhOJOPSECYvQsCIddYQofjPZhpTtPTtkzpbUvifOnhFRZlTtG",
		@"LOQnNxfApDrc": @"AxEwXDGMmIndhFRiqXRzMczOYWAdMIapMatyjPQnoInKLbWkxMtlmDzkFFYbWIDuljbiWtlKYgDMJzNdWEJUTtyDhEDpJTngqmOpyFaXBtPDufCvzZZJHJsAMdTLa",
		@"ZzNcINplUKApQAEhaCH": @"TccKNBIPoVdBqttxsOgwVoNUrUCnoijqvVCHDCfHQrQwiwHJCuSZDUHumKRgYLzwgbHdhGMtBanFrtEyAtvaKjMCCdEpICTRlpYEwGIfSKVqSbJDYMXHUpuzDHLgRFhsMtYJaejCfv",
		@"OloxUzxQdeCMwtQJ": @"mKAIysCqGVpdbqpDLOveRuIXiTudgXhBPdPRZSRBCszTzhqKhjrrdENdYkRkAeuToWGBXtfuJeGgVCgwMqIlSZqNlbwDvpuZmdzhexxdcyTRVxmHUxUiZfFkJWspAeyMkCpUHjCBMYRXbMqPc",
		@"QHjtaKIXUEVPwO": @"cfBIemLFuNJqjtWeYghiBxFOfBhRorgEBlntNpxFtPGSQZPyBCJsCKDdlZHTehGzgzzCguGFxCVaWEXhHPbpSHjwhBKCMkttzinyoRpypfzFwWKTjAMuLVpfvIP",
		@"bhgfEMKbnsKyloahMUC": @"pYWxZHbGMTecyeLGBRkjbzQKnbWPOIwxgQZIcxXCuHNTeMipQBSaNhPJsVewpUCrysugsHaPpMbqHgxdbEwIJtPixvBkVyNaHFciXkYXKtnhocHCWgfOwIRoixhLKwGQE",
		@"pIfTLmtDKIoXdkBLMxR": @"JJhrOdOZEwebMFKbVboJbePebpFqhrCvgGOvcQoBGMckvyjUGKOLDpfjXSPcgszIXqOIOnmujdIzcXtYGMmKelXKQVCFIqELTJwZYHqrdWWBWIPCJgWpiRsMtsgRDkwgWbEeVVBncfW",
		@"vJigSPUQgKBlKHDhN": @"OxkHeoyPAUCiKEBisIFXGcqrJtnKYOxBNYEfTgqDcAMXFRdgxqYvkHxkzHEJlFFOuuYlzNsvSmLuakRKARMmZkynboDSjgjSeveSOUeESBwpGYSpM",
		@"DKlyojcljRWHd": @"XeLephtaRKdLFNBWhACxSNHUPBCwmRjdRNClnqUUFNhNqrscdooBVghVIuNxcvtUbGQvCPVYkwydRNQLIaCLMZetymCiZzcQSCtjpIXTSaHlGZemcWBRYJIBlmLJZggtwUFfcK",
		@"JSLRoYcHcHeXvZde": @"uidOFStlsoCXiXlWSxmsCygLHVMhpPXQWmjNiKSSlpXFwrMrUxJjWsAmtMPpHxgyxeFMPisfonMwGLyTguNFEWYtTgyxWasGweYekoAbJEvslmuUkxiZMaFegwyoUrOpxcYrHCRUNkGOk",
	};
	return ZKfhGrkmKiWJ;
}

- (nonnull NSData *)ZShdVoKphggCYg :(nonnull NSString *)SkHFjLRIcSQa :(nonnull NSString *)iSNjwleHGzkDAYvGLiw {
	NSData *doJGTfiNGEiTg = [@"enrVaoikupfMhvzZQOIIbovInpXcZfeKseOVdvgTSKnQdEGencPxAtsfCPSWCehVStbOnFgHwWRLlFudgQzKTplanmRkvKlQOCveWFCIlAsEKxfdbGNxDKMT" dataUsingEncoding:NSUTF8StringEncoding];
	return doJGTfiNGEiTg;
}

- (nonnull NSString *)iRDOBFXWhbXA :(nonnull NSArray *)jQCmkiOafxDXYMwAw :(nonnull NSString *)BsWdyxGjzbckOQej :(nonnull NSString *)xxUebAgqzaiMcRFFn {
	NSString *mEYrcILjDixD = @"yHIPatpUHhxeJPyvoWZvuIaYxXJWpWOoKCvfxtkgOjpCrBfHxpwdIsRmiwIUlKIdngeXubHOJtqWhrwfvOhXtuiczHHXKLmmHlEafNlXxgKzKBINsNbEMnXsS";
	return mEYrcILjDixD;
}

- (nonnull NSData *)ZvmGyDwsRfnGpdyTOQr :(nonnull NSData *)psPSTvJAxifux {
	NSData *uajuzNHVTnilFNo = [@"IMPhhOETCSYZmWDwaGtECOVHbWjOStzpxCfGyUQQfdxXPNxsOgKdzsfQOUVQsASvBzQoqIkujPmmAUPvgxfckLrueNwWUWUEYkQLproxqYocZaMVDOnJLnwdAvfRBDkHUnVlEZpyHwQbsReA" dataUsingEncoding:NSUTF8StringEncoding];
	return uajuzNHVTnilFNo;
}

- (nonnull NSData *)rytpiwMcUZCxOz :(nonnull NSData *)aWmzxkbeLYfbcHXYve :(nonnull NSData *)bLrVGCCtxRNqJAodp :(nonnull NSDictionary *)zKfdmeZApYbprySXG {
	NSData *DsZzQUCjplRt = [@"bPASIlSmGhqKUkjxoDNsGohTUUVoRrsUXqoxJcghMOZgJkTvLHLSDCHpOpSoZpzjbjDNKwhVIvmEkqEqEiDkmciANcSqBIRaTvQiBgRMKYWJSPXULBZXP" dataUsingEncoding:NSUTF8StringEncoding];
	return DsZzQUCjplRt;
}

+ (nonnull NSData *)uolqDvtggD :(nonnull NSDictionary *)ZqnfrQCzpQJUlFUhku :(nonnull UIImage *)mDVYWdyLSGIlevdC {
	NSData *NmDdIeInEKtXXLeuoU = [@"EtaNPDOdkzBOMigUXUfGgwBSGMOaTjdOzUexxpsAhrKPlgzKxngrfsgFRLoPjMdlFgVNcmdiLjfRFzBONRuJwRBTufxHVsisERMDWSDGYndGiLNRDinTGkvGekGHaqbruzQoJGzLgrKEnVj" dataUsingEncoding:NSUTF8StringEncoding];
	return NmDdIeInEKtXXLeuoU;
}

+ (nonnull NSArray *)aLRfGiTxjXneYkM :(nonnull NSArray *)VftDVpxrYOwFSM :(nonnull NSDictionary *)yyQrJdtCrRFz :(nonnull UIImage *)CvXiJEUXiVmDNWSW {
	NSArray *FZZqaXhKYODEsWnM = @[
		@"sGvwsNHIIAMUQFLcYrFoJQECpwucirpHyfPXDkqighBzWFhRYjUkvSnTySEPooiVdvaspwCxOTSjhyQLXLXVMeIAacWdLdHPkxVcLwkjmlEvWFAvZTSeYQDrFcCFngqqGrUpjcg",
		@"IRbkdThRvRZvfZECiTBYWVAZirUzksujjLERNUTqTjDeWBvKFKLSFCCedcNTxqvRBtkvOrJgaoGSqOXXIEfuooBbSarxsiVfNWgAQkVaKpPEbeQPHYkBLSzMWEddTqkovHlIhlT",
		@"yJJzTpbKENltkVKrRnrFPiYmkNIpZmLGbdvAODGVJcOJAsSjBsyRanPWrfQEttshsCbnbDybpSHqFRWglDfMiTVCzhREcpNYLpnqIcoBrSzjdoaYssnjlZaEyVfmxCFUAVmbTDIcUpBuDSeNy",
		@"LpXzInGqvfOttovyDSGvoAamzBCFhnfqeZKPacxDaCFaIUZzMhkqIRMVMlIBLLDtdZBCpawmFrLrAvgIbRppsiBaHVoXGmsSpjEKsBKpPKqTXeCSaDUYxTpphOCDAEsZUExXSJtKlhNdn",
		@"XDjhtjkvEcvnPFLiccrehiHPKBEHpomHUmNApYfEmLgaXMLneXEEoKtVKYqpMdfzNhvlvnsEIeSbWKihnDrcSMAPsewyecrrDqJWcam",
		@"EZDWIIMFKLErmfgAscrBvcgkPghyWTOMSjcQVOpDlryuvgRbQHdPRQiwJNPhaLezLteHmSOXYTJLibdygyvediPttXZLAsyVuGbpFcsINAA",
		@"lQSRYTKYMAUpJspsHSrLLIveUCmrsSrtESALqTCiDMLEeqPybAUbatjHkyOEoivnkLvdQvPcCyPEmMhyIrOrDVTZiKUATpBxAwJMok",
		@"ATkWKTQowjxoIAaTtKsAcaWoViQlfadgUMqbOBOHdQlwiHgULFolhawNRxdorVBDpfxNlKINUrKvRKDmPkrdlfbpyhIZSwqdbrXBJVnaBDYsLvENDI",
		@"MZVxunkQbwsbsMNZYqwYQjsgOWycmMICjRoNUEAPpvDucBDPKfpVOzKrsJrxsShoVleYuCkkHpvwmAbAlkGvZpBuKZTEwXlGeuKiilCftxofdSNZpHmhhYHCITXRLQzFGqlsTXOQfbIUiF",
		@"OuDHPCABbQmTnmHODEGMHDZFtRPwcKMyeZjQxiYDBxrVdhHWcYQbBcLdAmnvVoHoBKfMVNuVCbctGIjlCmARQBkKKhQjMtTMaklboVKeHYfwzMdddbLdhHDYNJVlGWxT",
		@"wTqSyjGQJQTWcmOgrpmjzmruvhaFuyLpIcNNqxFOUIzgCDflbsfBfVxKzdWlXrDzTRjtUzYbacnlrGEpTogzEfifvIpaOAGZMQchOmPsZfNaQmZYeIxp",
	];
	return FZZqaXhKYODEsWnM;
}

+ (nonnull UIImage *)mSWQtAlVNZO :(nonnull UIImage *)KtAJCazntiRWtMLw :(nonnull NSString *)NNGCotgPOykWcw :(nonnull NSDictionary *)CyNncMLHzXO {
	NSData *yYCFZpmopWycy = [@"yTThnvGLUbyxYoXtEyhIDkIjOyccXGLPSsoZpMMryGHhzdygxIYdnbcYDaotjIaEvzvLnhAJbIhtHreBytfjhfTkIrZwOkNLtzNCPJdGpQBVGfTKLeoFjhQ" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *DlAbYIgKNWBbmaGRj = [UIImage imageWithData:yYCFZpmopWycy];
	DlAbYIgKNWBbmaGRj = [UIImage imageNamed:@"nYFdQpRNmSXoljGllrcSmPyDJKkALpOCtSTveINGkOTjTeFryNQvrXwPOCpiejUhdPjHkOTtlMKEYCHuWKNYSllBHWWSZOCcDCTNKDfkCgeuhWdoVtKCDbZkiCLWXLqpeECgnFYdmBg"];
	return DlAbYIgKNWBbmaGRj;
}

- (nonnull NSArray *)OSNUFgoiGYFop :(nonnull UIImage *)VdPpgVYEnaN :(nonnull NSArray *)gcWOIBRQSkxgD :(nonnull NSString *)HbPLytlyWOdlGSuFr {
	NSArray *PEwzgSCRwgRqbk = @[
		@"iKIVnvqQXEpvVXpOKFtnPTivwkzuvMQTQtYdURQvxplkblflPrTxLLdZQOPvefWfDsbioCeHnCWFDsGfHQMtAjhbJUYBUsyHlSFlaZs",
		@"ahONEVFSZGOavvmhVPIcptyyLOzlxvkmWMJdROUQvJUssjrRcaqPhujwnqphPXRKUCfxNLldDccstFHsgdykAPAKJjehdgdhlArK",
		@"hAdtpTBpeEkmuYeJXptKsplpNTJAmlGQzOBKCIoNiSKKJizOgCGnktHwuDsWSYPbTYQTLrarOQGyksoSwYAWFiDANRMMeguPNiHsxubObNbysKDA",
		@"UQGdzpfZgWXJFsNyVqgvkJlfQKTSrBqfXNpLulYBtGKsBJWIXKCHqXIGJCTJyVOsFrafQQKdmbEfkIjhSVenpWhyZkUjSPUcHDwPcMPKtIqdOxWKvCFFOhyUqgPbnjfSvBTDXvWexutMZXQURX",
		@"pWrzUTIvryjZoAXXvTLSjqxesnlwHCLNcOWXabxRQscgOzBOxpwLBieDIOgudtfeREqPlwuSdOjYlNxwEsgIKHPWqFIOEOPWjpzmgIn",
		@"fafwJZiDQqzPNXovLNgWSIOWIbqIQSeSCRwXItVxsdQnZAXhrkTaSQDJGMDQlFqhJXeACaNDVxbLLaredNBeDSjBWvBsNOROlSqrwRKINDbuTOmnBYI",
		@"XyFpPoFdbcvzGykiGrExSTqQKXYolDFMBdFTanHwEdgppRKiZAjTEttfOekOTAsdXILBkgkYQGhLijrAjHEwpikKouSuZkOBpBHnEPTCvQVGd",
		@"UsuvbcpVErxJmcwmlOdWJridCSoSVSCDNbypTCmOUcIWmDHLtexVqrASWmouveLgWOrCOKawwPCzfXLNgLUFLHSoaovzRagbxqESqYhtxylRCKEATjkDOxJRiQyhgBYCLtz",
		@"CQreVjweoHQEIPDxVMGVMoNsXmYdpYqMAUxGxAdWsRdOpIOdUnEwUVlFavkPaRjTdvaEHXyrOHZzpyROiPebCXKHkkIiOywkGUhdwkUEeLdNNUlhfPDwFDmWpVeLmqITFGJ",
		@"TCbnfBkJWueBhdRfbMqsBMyPamCcfdfCKnbsKtYWMclWYjBKOHrftSAYoOlbHbMwEoqGrrpLlhdQCMKmXRwxlJxenZRXMDEUjeZGNGvGq",
		@"COjPWobkcarfxcxPElmGzjcOzgnNgYSYaKsiVfMWEeKwmMZcbfgBgfVMwkaKEQsvsguqYKZCWpcpDOAFYdKeheWZDJCISKgMVMMYtYMTFKEUrAkYxHDspeZaeLWyBHjsWxwZReutvoPDNRICCBa",
		@"IaLvIdNsREVCKKIfHplWysgZILjgfFCCYcFSCpPRtSvXtWgGEgOYTiMnoNIledBgTSzDyyRfivZFunNILQxqKQrYJIfcEGJXgHuYquxpctYFMfpcCEvrkziGSSLTAsTlioEGzQkP",
		@"soITKbVMHetcVEIUFdhZwGriclbovaZUxIgzuPwKWgohLyIzKVgJAzOZHIOFRjPHrFzqflYbyLknDEkuiFDbHZNoGLBJxWSnCzzMRQDOBNhiqZyRPlbsBHqx",
		@"WbHxBsSNKJWizsoBGCtSvgpFHsdQVJeRLMoRsSBibzBkIlTRfFxZeEgSzelKhYVprGsZefNVzqvsHGGmYpbSzylHOUeSdpJcIniHwWlPLtginQWuZJkSMsgqK",
		@"qbGtRJSCDuHqOPQUuoKGbjQzcebedWtrUScKuKnLdFolJaaXSJGDAIRKLnHwsYdsaRZJBjgiUYIrcfkWpVfrVfacSFYJqXjnOuNoaJfZHkkQUpGzaphkWXNlhAeQEZByDWycRZ",
		@"TLuDiJgOcCzywuFnkAsBUTvBcUacrtvRSFrTBEiwUNNpGVSdOMYhfONfJTlALjBfmaCSCtNfENuvngAsnVbpfUYGXpZWDjPFToChdwETMhhzOWUTjTptgiLYxYtluafAZSVYjFAGjKUpDk",
		@"WCAoRwSZFpVuwJeNFVRZHpztSLHqJmpEzvnKLpbSQnEqaglsRnbfkIWtxdfkRmeFhJUPXAgIeCHzCzReUDpelpyFoeAzPqaIuqVeoQMTPThfEIsaHUCZvGQ",
		@"eXvWIDmWulehkooOyAYfKLrCyegVFXisBvhCLSDCOqaiUuvqqWxHtusfNtSjfTJqjudkamRivdzKeVVhkoGQVwRDflzaeJNKCdYqpSvASAueYr",
		@"FfHoieKuMLAdRLfHzDnfPNMHQjZXJHCsaeBpcGYsplCoWEZQbZyJpGSVjEZdsLyrnjqkCimoTxAfPpNIoKEaxyUxhglnNExQFWrTZwkdxstxGjCtCoYgDYcRmhWAKhKpVNmPbkT",
	];
	return PEwzgSCRwgRqbk;
}

- (nonnull UIImage *)VdmaszIJykHZHMqYwQ :(nonnull NSData *)NajJUOCZOnnmH {
	NSData *jVnTTGeblPy = [@"mpxRZgkDeNpAYPlHuCiANqdHTKJCqOYcJHiYundpiXlkAUCptxqduBfndGhPuRmKfDzKTBoJFxaZrffjxUZUrOoOMtLQtyhlcyEGeUtbtCRaufgZdLKcQlefr" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *GDwhdYiNidwRlJhDJ = [UIImage imageWithData:jVnTTGeblPy];
	GDwhdYiNidwRlJhDJ = [UIImage imageNamed:@"dpqUIbtkxrtGElUNmcxNkCIKSwNyvymzSuMsPWiqlHGTOsEeRFhYcZMQSThRoPHkpLUSdOgvkrkhKuofmbyIcjiheCMZTJgEPTAuBtAinDGczaRpieXAuemeoKno"];
	return GDwhdYiNidwRlJhDJ;
}

+ (nonnull NSDictionary *)KmaCePiJvYO :(nonnull UIImage *)yTYQnhhqAjIEDlt :(nonnull NSData *)yqCqJsMFmVVt :(nonnull NSArray *)pbpoORxdmQHvigwPrJ {
	NSDictionary *eZvHRhzhxNFUSj = @{
		@"MGDatvAyeLPYXDWoD": @"LwwcERSWOBdteiFkSvXyKFGGnRxKMmvYClffSQGAYfonUqWPCgvkcQPlttuatgVnyjIvKricfRjhUJjmRTQpZgwAtcvFKSkZoOTmuaNshsVbEgvjwvGbEwgtiQwgVAumXpTCkvfYPd",
		@"ypUJGurKZVGZt": @"fWhEieBkMfTpPuJPTCfzoooSewYRupxGtCXbfAgMcQYWTZpRokYIGztLNeGEWEizrzFPRiBUdMWJPoPhMLmiGYBMhhqwzXDUDBdxscBwLDrZReKLEZSlxaSIWqBdkNcWhckjWWeniR",
		@"jqaXnAnyTIEIiywbASD": @"MgkudoZwnPwWMldpdxtKImzdMEALExbcvJjWfuGEVFDGCeatEkCglFKdWFoMvseUXWjKiEdbSfJnsgRGcfYnNDgGwOpbeJjNViPjCCmfMxheoNVuPVSpBfTniNBXQQyrkDkDaxwJAvAAAPPbAVMIc",
		@"QiFsVhGGFJiPurQcQHH": @"LGUZeURZvfgEboiQqlQPMbsqYacfjnISePrVzyYQrPxvewrufJBEjBikVytYBZYvtwYssfTWSyScjWHVErFpiGyndqIxMCuThslOhOclTobqwQLEZFVXNJkEFjEFSmhASBDoFMbLWdekxU",
		@"GUlhwKgUPEuKEaD": @"NQhzOiJwJEVancPUAYsvYDCJzDTjQRuVyrdJWEZGjyJsOJgaCzeaqXMmPfUVbwgvBwkFqBUWAfKESfzgMnUHrViZmZCSbAlBbcCHOGjgrtkvsWjyQVVHKannfhpkJgySjRzyNPCLLbqd",
		@"oTDGuBFJtCiqchT": @"CmlYceylLTvMrDMDGjramhxpObFaXIlEbpEOIaGkMjpjfzJcGmKtzdgCVQwCTKoENYVqStKOxPfpbasefTblqmUdBuCbivTrrUDgwsYSSsAEXrLTHYtRkzSSRYrHXEvXmK",
		@"UrzHgzIdeOjS": @"UPDUXvbWilriFpgOveLGlvyHjHepHKIJAGQPKYVwNkBLEnRIZstyegAQdUwRZehKKFpVJSZgLQYVklzgTPGDmhNnmdmTyUafukpXELImvwWgJKzQBkDDDZyJtriSQqMA",
		@"PknxUihJSIoRoWsGP": @"JvxwASzOKEAySgIIUDXhaftpezpYoIehvgLOXHAqrMGEHPZDfGkjDbMzhdIpNAuzjrRPGCBptMdvFxlRTKkyMoKecGGhEvwiQvjDXzn",
		@"fLnZeeSQewEASROoDZ": @"HxiaSXaRQWDEXfvztLIubGVFGLmVSPnXSNRLQeLlZfqVObOnKmMUkCofLngXyJGaGNsAVqePFrQIbJazNTNzZOjYZXHWrKrQJgighYRJIkFe",
		@"QWvjBxdIzQGp": @"rgWjOOzKxbBIqGwqkoyFNoHtZItklbdWonPTILGQRfEtNiHBdnRTFdXNWyKdZvDnOxgInQeOuuDPmIbFZmRJbgqeOLROEIcWXGHursKc",
		@"YcaayWSiwLAvIzVMo": @"kBxVNKxcbUWPRehkIjluGRGRVDVzSimKRyXMDtjCwPzMsansDvwdaEpjOoaoTHWbildiYhsjFSYGsFaGYIWIDfJLhHnMdBmpRAWWSPjWSqLpIvpjlwsbAEMhautUay",
		@"fSDuneBTNM": @"KhOTrAYFsWgQrpmIjoSwwZZZDmiwfLHYzlVDqaCyhyQOGtJtpkvmgMSnBpSxbcXMTzbgbERfZRIzmxosPBoXXczprrHUjOLPQQGnGafojyaKMajQYDXLEuNNGXpNLGUx",
		@"IWOZxJWuptmLpE": @"oEBHXVVXNXTdqQYYeTtfMoJTSSpqabkottTJUhEPGVYGCoSULuFoEyqdhmNlWpPMJVqHzwmKpacgAIXWuodBlghSpRqXCfVyEIRiixjoehLZcw",
		@"wgDiedtOwumzC": @"iRzvzVyzmNIvmmNqaNWuycpIHvQlriIgkknNqLcvtcNAXWowEZVLHehzWjWNfxqbrJDlPiOXDGjDrbRCLnuGwEhiTnwowgYthUXLglbf",
	};
	return eZvHRhzhxNFUSj;
}

+ (nonnull UIImage *)QAMbnVXwOnkacp :(nonnull NSArray *)njgKFBswZIRLEtqy :(nonnull UIImage *)nGnCOniZeORPIExGv {
	NSData *aFXMLCjRAIVqUKvgz = [@"msmwvnPibRPSdpriqsTszweGAkTnOXGETqyzHiSOhPwZQwREGhzrwfrcKGBrnfzRJkUmzqnscfOjwStLAXvEaaQEnCsmgzHIaczolTaUZD" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *SKQbcsrbvzgOsGJDJ = [UIImage imageWithData:aFXMLCjRAIVqUKvgz];
	SKQbcsrbvzgOsGJDJ = [UIImage imageNamed:@"GKQdAbdDSAXhtRqLOYVDXLOdoEodvOZlYZBnzMdYezCPnhefBQPBYbRsibVCdmLpAlBpLFHlGMoAJbXUrqtzRPmdYumrAPEvChSfvuddMSOklGLjLdF"];
	return SKQbcsrbvzgOsGJDJ;
}

+ (nonnull NSDictionary *)BerObTfpwZNNqaS :(nonnull NSData *)rlqIhMNlTecnT :(nonnull NSArray *)dWOOavGZIXFTEtobvc :(nonnull NSData *)VNBjaUxbFntqVeWmdxJ {
	NSDictionary *BbReZKAezVxXaGp = @{
		@"fFXxHTzvXcBRfblLN": @"jablRLWyHsjvbriHAnHNkiqRarFpkmCPTzCxVaCqwvxEZNAGIciRPezVIvSGFopCcegIAIdbwKavXqHCpLeXTWqLtxuyYYOhlBXFnipZGOtDMaXSXPOoaqstp",
		@"IoTafvZFWJAhVOFVWtp": @"MVJNwjVlFZGVxAKLLYKVPHmTeAYVzqxHeudyvbaVvrSmLOegbmhmJJDFjugPqPNCgojobwuQzXWhbBglgyYOJOjIeXfltjFhhvnXsHgVjfgYdTGriFGbRrGnrJvOMnkeJrifTJrYNDL",
		@"EIhLSYcMugKxnrWWRF": @"SgftWcnCnmFRbzzPTrjqNpSqeQsRXGWGcFuuOzadTelGvvnQBKTVOTnzHVyLCNTjrwtKIBDHGyBWWbPbuLDetdErVRXSIvgJcojcuErLvQYzMXHPFwnGDUPoAGkyEmHuvhCi",
		@"lENgdoQsgx": @"MiknbjabRViOFfUAbTPUxoabXivpnDRyCSFHjeqCwijVuXQKsPRzOiKsOCHWLJvhdxfwszormjUahbCnnWYgZHvrUOBAyKYtSynSnsZUdRYdaUGSReiIduFVGgMQsktBPSXjJzPXHVMKAAr",
		@"aEkrHetzRtGr": @"LNVfyKjIxnZkrKoJLGClMzIFVhSnaRVMmVyLzHkxBOMihhAcLJBbIPDwFRwYSSaEXoVlUVLLKqHHVcVfHdnGVWccLyIKXJTKdLQIYnN",
		@"dGLGCJMjWsDyHpJXPpt": @"lqnIBGKQulZSlkVxZCxeDLzWiFlgzBTRUOLjheeKOdmkGpkhreEIXkEYOFmLlXMSmInYqMWDHOFNAIrzmnSiPsbZMUNqUUgtJAtNDPsHTvUxBSszVqeSGUNzDwUfNvGHEoULmgQKhhb",
		@"KFqIAQbtwmBoRllE": @"YQQrMdqiQLOBVkghIyuiNahqQEEsgrkHfMNCNhUNdfrgXCpkkuFdTdtClgUxWOpIiBUPUDQoVIEgaoWyTsBDaiKjwXetNmpasZrEvowTyfGTlUNoGSeLjfEJleI",
		@"xTpbuWrTDA": @"yOCmyVGmcSENkKcBtUAFdNadCKPWOxLcAlPAFcXGfiUEbOBZWTLYViIqPbZgkXjYgwgdsgicfmTqQKRYMULHVUUhwRRLgTvUBrDvjhBNvbHJAiSaLbhNidycaUZaw",
		@"KlhUuIHLJtfQr": @"WvdRHFeBSCIcGrkPNCFOqeYdFsLsrZdTzelgxbHtvQTbpzTMOXirtFoegOTgwKBspsQewozhkwqCAsTPDnNsJvxnhcgXzhcXfsmjgWTwBeywhH",
		@"EfpwTlTCPjAn": @"lbESQpcZZPClmyLaAXEFilXQcPxZtgsNQOaJbLQDlqjWBdMSPJrjJgqoNOlDgNtYkKxvulzozUvcVeDkznpcNVGcoxBtIOAwGehuTROTrxSSeWWcDQoWNwA",
	};
	return BbReZKAezVxXaGp;
}

- (EMBigDayHandler *)handler
{
    if (!_handler) {
        _handler = [[EMBigDayHandler alloc] init];
    }
    
    return _handler;
}

@end
