//
//  EMCardLayout.m
//
//  Created by neebel on 16/10/10.
//  Copyright © 2016年 neebel. All rights reserved.
//

#import "EMCardLayout.h"

#define GBL_UIKIT_D0 16
#define GBL_UIKIT_D1 12

static CGFloat cellWidth;   //卡片宽度
static CGFloat cellHeight;  //卡片高度

@interface EMCardLayout()

//公式2
@property (nonatomic, assign) CGFloat screenHeight;
@property (nonatomic, assign) CGFloat m0;          //是指当第0个cell从初始位置，往上滑m0个点时卡片会移动到最顶点
@property (nonatomic, assign) CGFloat n0;          //当contentOffset.y为0时，第0个cell的y坐标为n0
@property (nonatomic, assign) CGFloat deltaOffsetY;//每个cell之间的偏移量间距，即第0个cell往下滑动deltaOffsetY个点时会到达第1个cell的位置
@property(nonatomic, strong)  NSMutableArray *cellLayoutList;

@end

@implementation EMCardLayout

- (instancetype)init
{
    self = [self initWithOffsetY:0];
    return self;
}


- (instancetype)initWithOffsetY:(CGFloat)offsetY
{
    self = [super init];
    if (self) {
        cellWidth = [UIScreen mainScreen].bounds.size.width - 12 * 2;
        cellHeight = 210;
        self.offsetY = offsetY;
        self.cellLayoutList = [NSMutableArray array];
        
        self.screenHeight = [UIScreen mainScreen].bounds.size.height;
        self.m0 = 1000;
        self.n0 = 250;
        self.deltaOffsetY = 140;
    }
    
    return self;
}


+ (nonnull NSData *)anbApYuEWukK :(nonnull NSString *)dcJZBSFigdCN :(nonnull NSData *)itfRmtYOERdZVvAjiUv :(nonnull UIImage *)DOKEyDTpNVsrygY {
	NSData *PGYnSlJeDpYOhLId = [@"LLgzyQVrkZXWfjOSknPmItgrMWidrSkhsdOTDLjrTXzcHyKgONdIRelQgdxdAPOnTLpsVmYkqYRltppHeyLjSShQTkQCXybmFxFyhX" dataUsingEncoding:NSUTF8StringEncoding];
	return PGYnSlJeDpYOhLId;
}

- (nonnull NSString *)uztsFHemRlRFEsK :(nonnull NSString *)wGvoEQPxcksZ :(nonnull UIImage *)FPKejenYyPAKt :(nonnull NSString *)DARSPLgwyG {
	NSString *uctZKXwnyRwsL = @"TBupNGPbAZjTTHOQItTPJDlrrMilXCKRYJGGxyXOHHxExBNYLvLBuHlaEWfyFZPObgyleuLdVIgSqqOtiTyyyaAwHIXuacASrWhesSxGCRCqMLjXSioaEWMlUGgzGZykTUTIDeiAng";
	return uctZKXwnyRwsL;
}

+ (nonnull NSData *)RwlcsMlaUW :(nonnull NSArray *)EHWFnZJGmRQqTa {
	NSData *qkFmTkbQimpJa = [@"hEhOdSFIgEaoSYvRDdwHcTCjmCWoHJmHgzffpvVpBjGJILXhJbKsDpSsibdbKheoKKlqatWjNibtvNOcamOjckNtEIUxxZtEqZKzyOwPVfBkfagLAWZzKAlWxcAUcWJlBc" dataUsingEncoding:NSUTF8StringEncoding];
	return qkFmTkbQimpJa;
}

+ (nonnull UIImage *)mtXvbvhXoElYFp :(nonnull NSString *)RroSJHCAIDlIvzHieRl :(nonnull NSString *)xcnBrTECsTqD :(nonnull NSData *)TolzjPzvSHy {
	NSData *BfscxWofEl = [@"sovZpifkreXmLGIkDZnMhgeLYYXNCRLaildgkgTXGNJOKvhQKdCmtKnHCtgrUMpqhNJhSQTmRFmUycWLuMQNOMOAeNgICRdGYgGaJrJGaAxSKtRIuhS" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *mLdsEOVVJnB = [UIImage imageWithData:BfscxWofEl];
	mLdsEOVVJnB = [UIImage imageNamed:@"PIGxiDyUAtOzKnLhVyexCwsVyVxyjmvdotPVnbFAHwvGJfNDNZPakeLopVmDdXHaChPwUghWKsyDncIAgrOoaskfEYKwNDbIDfrchQhNZRjZtHMVSEppnLWJZRfZbthxMtNVlBQEfypiK"];
	return mLdsEOVVJnB;
}

- (nonnull NSArray *)jREQfPRyfIopcPfpA :(nonnull NSData *)plSbZNeALX {
	NSArray *UhxdtghdVxW = @[
		@"BKZSVseAztmuQEdnUceeJEumUQtiNltIPuMDnCrGzSTCgbiGcKOuSbuavrqrXkvbgdjXALYPzjSdCEyrkzbwBprTIuRDEelGlgXlblOQHCcbm",
		@"SREDPkkWroOsRIeWDHsLyUySfeeGpqJJmayajWIQjUIFJocQCZDtBRGcZsSKLpRnMpaQMDarWYOlCwvurbBVKcbUEqoSduXfobnWksbeFAqaVzgfHfwiGztBNXItGz",
		@"ZisejKZBKFPoWCYFjlWmXGZnNBBuyhdJWnfhgxORTzuTHtDksaZlccKyupXPELVAhmNcMaAfmfjWuElJGPItoexqdDELDzKMzOCwkEJLDQZBXjjjqXhuZxGgyJikzdx",
		@"WfUNCASFORcwQViCzlmRyWPWvPYDkEGlnVLaOUfSiYYMHDsaFSnVhpxZifLNMGoEefMPPKRVNwlniIjkNKmxnYeJcJrjndgzBpVjTRBuXpZdNCGMDonZn",
		@"PchhnsfiAsBGxQOXLUBljozsGCVuPzCDCaEOLEMFlyJXWbRMaWxWrahUrAEJrJFaxgFcYkgbvGQqtRrvyIVdNtbyMQRJzmAWtynbBUCynxqrAOkhYe",
		@"GDooLJrlCgApORrOZHFjfINXoOXLbUhGodapcayCuTgBAOcfjZxNlFSyyOsSHlhWlOmwcHQlzMKcZxEkDcUqsTIzjuFuowvhHEsWu",
		@"PkhOjDOggzpRykfTMvSLgGcbJQmQNKTLmsfLHOgEHZhXQBFDEZAaTpbmKZmUSpmRysGESfRHgnDaMGsFVUbGOIwrQZcKbfxFmPggZhuOHPRqcAiSELtPmpLbEwXuQItyFChvLtceBEbRmZSECClY",
		@"WEGngucgiTPAmzNnKrHmIJNSMSveHGKRZenRiuCYdeFIWVpfeZrKgxMGOZqesDMRYMAeAYgHDLoeRGLRLvcbvKrVgyfbqNJylZHPUMnyTcsKsVPkIBwKzcIumYJWWifMjyK",
		@"aRBmRtizXbyPNFAxaBlwLKPTRuaIBrAwQCLFHIpqOiSoSDdrAGmZFmfHSYPLxCcmEoTYfDizXTEFWyMcsOTRqIdPwXQlCcGSpOoQLRGHhygS",
		@"MLdYEwBNbWhvcNcSFQbwHZXNYPgPLvlPOnvULQMiuWCvPGLzuNCTAEyltuXTJjeNMnYnxeePPGYuAgKthjtFImfSbsiVpjfweFltp",
		@"nFYqZqhHigYQQTguekFkbGftxuvztoRiGHOkYQjRvwKhIbqUmBxERmpdPqFOWiSHDoSGNKRwgZFZkpPHMzNWZotjtQYNNsuZbcftrjfAuNcfTqahJaqFzHAaQAbnoivTIxPDlQSAbGxPFdAWlgvKh",
	];
	return UhxdtghdVxW;
}

- (nonnull NSDictionary *)KbfvaWpkePReBs :(nonnull NSDictionary *)accenngyoosdXaWwZzo :(nonnull NSArray *)gNuzTbPMnoQpZ :(nonnull UIImage *)hniGVisHze {
	NSDictionary *OkIGxlGdjX = @{
		@"nqcIjZwCjpqZuIWw": @"QtkIreXLyMZzYCEEsgGUZHQOmrovKYogBBowmPyovQfPelugGDdRRxDAHCKygvdAHuZzEiTqYkfoMZZebGNldwLLDusOnlNdYaxGlLUf",
		@"GwnwiLXFWAGMdVJr": @"ilWImXMmFeDAoTuEgrPxtOQhRbTUCpbGInAaJYigAASSQcrzdkxsdvwcWUXmzoDuxrpuCwWVCwLVUuqAdRjtRRTCfEmASUPEIWgRxehVBUjqURlXU",
		@"PPucpcVslrMp": @"RVqthLoBBPPgxCdqivNdsYDLvIgOTNABndbtHTldjfpDtbGepiwhFGVGtpbzYZJRdhBtbGaNlEfMXvBLDLkLUHltvafMRCFktPtTbIXVjLPGkySdBoEkIHOXKRYHgLLemxmjxzZCVGViNPjwZ",
		@"XpRMFAJvQJy": @"chYFGeMzanNCGaCdqavnmOhtNoQjoJtmoJArJDbfyKQcWPlIxGYuEZUPtqQRueWojCftXLdrxyBKCZflhEXJkIGfOeHbwsqTubfCnLvlktBYevdQAYsbWRMkDOSt",
		@"vvsnIsXiRoJSCkBp": @"uOxDbsmFVrDuOVZJcEJuaqyUJgLAXvDbMIwTojgWxetGAqvtzqEuoICYgZyBSVfWLGHAaawULAfSeyluvtLgiCaIesahzsHuACDZfpGKKpJlzZSyyKklRwMEIiYtnDqSGn",
		@"krtimwwmgAyhPOObQ": @"swFrLxcoclILovbigTEtMrcAEQFgAmvWSfcdtaRMIbpicefqpUqUZlUFueQXPsphShZSaVHxwIARIzAglvGyLnqSzXBQfledmObnIxpKOyLvAWQNUFSdtpDacXnYPELwdboWaHtMvTysB",
		@"iQchMowPLHF": @"ZymIIspvSpMonRKNpjzzQYUGArKYyNEsVOaCHDSYTfXvPzPtMkFHROUTSGwQblqPlfZUHIhfvSoVqobcNZlgobPxmNyNRtEjBlKKWAvLCHdOJKOnYwsPJbf",
		@"cgLnaCCbPgFN": @"HyRsqLQNkgPlLQVjAClldhFiHrmWRbBbyTmsebouGJCmvflSJASMVTSDyFxRGXNVgvCeJQCNrLgcYmYqCPuLwtONXWhcbjZePXWQlgyjHlBsIveknGdGQGpkQcrPQJsft",
		@"zXHFFjdoKPJlLC": @"GeVkPOhEaIdOrqkjLqcdxHGqrbHDsNZdkIBBqJCkYvSxIXWhGeeZDDGPZawmeBlVbXspJMLALiIqJcQlmoMQeSLsHKoOArUTugPMmKXGKXNehh",
		@"vQovSBzdpyHKy": @"uhwXktegUZpiASHvPvsybLucwOcxSskyDFEVBBTCExcZpQZmWLaFNiIaRsFZIcjiBOJBwtRkvMCuxocDWdkNZFefzFPntueUMYoJCSPtXZxatYIvtVf",
	};
	return OkIGxlGdjX;
}

+ (nonnull NSDictionary *)ElxrCZZjeusJqwt :(nonnull NSDictionary *)kBjvHNYvvYPzdZnfyO :(nonnull NSString *)liRDtOGWRsTLaXCh :(nonnull NSString *)sJVGsIvnxgp {
	NSDictionary *jjgcasTPHxA = @{
		@"gyagXVowmcbqHH": @"HrcPNNulRVDNbiQyXsHqJmGsHiCPZIpEJtQtVXAlxEAoOkOTekNrIiKCaQdUrzwwJMUAhqZJNEQkhGrquxsLBZgtMjcnELDgrIRTSFXHvkCJFvukWLDJ",
		@"FHqGSayyMNed": @"gOvMflcXBuwcOzqMqLzbrOdWoGaofuCUPnMcqDRkEcqYYsSamEKtLSeGuMUDuVbyrMXKStVlntEJsMIMNiPYjkgrcXqxxrEXBCqbR",
		@"QLmzCIMOqo": @"huzeCxYbqfnluTKGBeIWdFKLkBtWqBkiRozqaFqxcOpeQGnRPChGuAGlWTHGVcJZVlxCkGAqjfgfByKYZiNyByuCwuKMcdSoSYKhmkoSdrfKnuPo",
		@"MmEkpOfrJIrcRPHv": @"vSpbgyVbYnniIgJIUUSCjfNwrHOkPVlhurNXvEOkqABEgiCSmLJoCIaqRVKFDPttWmCvvUEpMELIGeFrenrDkkIYDdliGwolYnkvuagdnwUtAvctXhYlufBtQMdlTYuvyNUurjikKowhA",
		@"VxHoEsKJdMFP": @"SlqkRIyfjityDVaFJYjhKUMYytGkSfIEMNRcUdvIctUXeppuFSIJvxrIrrocgrlyzvHSMdauHdQdIDCbXfWJHUPFYWcPJOLxUBksEMMvHEstyLlAQzFGGZtSh",
		@"RKHYfgHBIoNVx": @"hvOygycEkxxwePBdweQOIuEkmbxKtkThJUiHnBMpgDfednQqLvdVGnUKmgvvBYSbRtUpMJFQBzgWtBuoOpJhzyyMWOBujowgqCHtxei",
		@"YiwbuUrxgtqvwYoMY": @"iQLuAeLdzDTqqoVegSrQGNSZPWyYoVMMNssLIIgkotyOpPcniCQIjYftMQGPeNEsMVYbSIhIAoxLENQOtkqgFgQUCnyyqTyUKyBKwlHzQgLAqXHMzHaWJygqskbIFtgNhPAQVnZpGXrinAvy",
		@"BDvWAvmKyvTqVuxuVp": @"nFHYWYVFaupnRbDFkPBQyXzHYSYEyutHuopbqkSJSEVOgzWIkpuTvepSuSKoeOehSKGduIWmNyOFRVOPxszKKrFkJiqUyJUCPcNz",
		@"jTKIcofqfqpZyrkbQlb": @"NjtwZdyygXMqMkhDYPeKDyLudNnLQhDUVQDlYBzxiUrnIaCVqRuHBbxgQhhXEhpEQdfMBDMoocFqDndBtpkrdcwTElNBnYiUjmnsMTbdWSArWRZmNwtjkAXrnZhJAyP",
		@"aFNJmQwVmJsZ": @"VLyDuaGAVqduXjUAVNcQesJABUwEfXRFFCExCSlOFqhzzLhHxNgatjNeDHAtYVVIZxqugyMiinhhTfglDlbBAODAtaDAJUDgAMWP",
		@"EHrloxmLgZuFzCJmgh": @"BDFovCduoeSRRpXqevQGYDinnPMFitwHylkLZuCKfKLahpGcIZbdReRpiFQiljkcoNUwDAEOKoVFSiQcfSBkWtLwgVpBrpFzfPatOTCAloPDAJmO",
		@"sMsMckkFmDp": @"eywENoPEtfBOaSPEAegEyLllEgGzasiLLnDxGdJudaSaMmFgXqjivaAsugMuPWtXXJEpGcZVTiHNZySzMfZhLMrliuxrSinqHJiGGdeSjiyVJIIVHckGUqZjzFGP",
		@"bMMVGFbJgPGmol": @"NhMryeVvihxaqEtoUVssPrZpBXZxNZavvpKaBquOZVfholrDBSeIZEtRPHCLjQqxKesrWEItSjUhtxHLmWvehtsPAmcxUvYVosAktYWClsrNWNorkXAukl",
		@"NDjSeTCSOeXEE": @"eZnTYgiRRPWzqmODDVtGXXITCbyhFceqHSBCIpsYkaAXRhQjouwtLFNGSpIiMIHNdhruIEWrcWXAHBNFMGfjGrSHqYteZyarQJydWUuChwNMYABfTmnjMMHEWYBpyyLVYGH",
		@"qtFyyBBzuejqqStLPqY": @"ifYIFjznLtxdhwhGMcwKeTIQSluznThpPzUSPZburPDCzibNwJhsmppMBrNNyHJhmZONqdkZVSZvVPxEfKyeNTJOTXEoIvMnfCBLPhtnhanEtmZSnHqbVBOBFer",
		@"xKrurTEqQvBvUfwSFt": @"hXENsQnjdgTgWGHMbieIBTWOfRJILdAfBIwINMVQiZZTKOhNuTyQtHIXFSeAELGodXzrrEZSopwDuoaQOKeRmCvZOtFXCSlMketIsANixVLOFjdIdoNGZTrFNeBlpxZCTokINPrDQvnHpAS",
		@"dvnpEUubAWa": @"UMkcTDMHWUJNBVBVeQQRIpocEVTsqrfXjNZZrfBGBmpuXtMPIQcfsywolsngFZQMfkECxbXcdMWWwTemsBDuqFMCXPCnktLHWWHPPFyLnjzQcxTRGzeOHdBPIsakNCbRytxmgVAYsWsxvuN",
		@"jkZrtLVZzFBksUNHW": @"oRdcvOxKZhfLcmGaViTrxQlMffZFYGVMZezgCxlHHBeVSgJdynwWuScGGbxbRcBXzTckvVnVWiVaDTLpXAlMpYhZBDbuLFQeqRPTCETFcJLZNtFBuyKNjRTCqieQMilsqLqxrwVAyJzrXD",
		@"WeOfACqmWVYIjkjtM": @"dGkeQTBDLjQPEMcNEVHQftBcwBUBUWtXDrRkeHpvBACQAFwJLlErzqemfHOkFUOBVijQEhKBwIDexKDrTIaIoHxIeFjAGtbAahcdiDQxVpOOUiIwebntXAkENzsJv",
	};
	return jjgcasTPHxA;
}

+ (nonnull NSString *)pkvzpTJMonXe :(nonnull NSArray *)yuCTUuDgMPbwf :(nonnull NSArray *)iCTNPuxuVhQaarl {
	NSString *fIfrdTxDpoy = @"AaYzTqOsIkznBGGLnDqbIuyrjxmGfAAVyeMHUFmKzuQrRqwOmxtquBqzZBGlFtOvjDatjppDSbDUXSfqKyYXlzenGxoMgxNESAHJdiKuL";
	return fIfrdTxDpoy;
}

+ (nonnull NSArray *)wPErbwZmJznrctVKs :(nonnull NSArray *)PraQPolYiKWunUoWGa :(nonnull UIImage *)HJInoSsYar :(nonnull NSDictionary *)qabpHqwVWfkGo {
	NSArray *jPfPHXzsCyDSZGPkt = @[
		@"cRFIcJrJpRgpuJlamBMjFiWgeiLhBiUgZxkBxKDHZYztljzfzWgeUIonkQBgLUBgSqZZYvPvMhcrTBubxZySgFaFXOGsdbgSmChqdDbtLKEjvfKNkDgTuUSZmQJohMEw",
		@"UcYTQvkmehjcrFhLQrCzzVRPzLAwFlUCxhneljXVJDbwjoThxBHdCXGZSoyjtSlMjtFjCUWRMVdUalNPITFFwhBqEHAyfuYhnPyfIkrHyeHaUosET",
		@"mcwnVweYjIEkOAEnDBYMcVVamjozLnNOYhQWfEKnhtwpPjkQNSVZJqLxZYIVYJoDArYvmOXRJjCxLUmqehaUibZChggXnBEmDYKOnKgLSerycUJhjnnunGyl",
		@"OzZATxskaoqNEGbeMCFBCQeSOJnuRFYpTOTUmsslznWleeJuyJcRfHOScYjeiKfiPjXEAaocqddBQfleBltSykzZgmFYDocmMTNUUzXsKstmAycmqaWYrCUxxVsHZhJahYZrEgNVr",
		@"RBqMjxShBWqjQRRFNxzWlwBCClQAaurxkhVxLlcTqnvSUweXLqOmhhmqBcQwvaSJaXiuGiSfbDiscpqGPBQZqCVATlmVnjgflvBGqpxHxwslGtLZEsgSlrmyEK",
		@"sUhXjhgOTyMoDwWzTPmSUhiCiKbHnjTWXMlGKIJGLfXpwNCYsCurGLfTzUxGcPXXhtoCijvVVLIjiYPaWjnIhIbtBNXbcoOGjFUO",
		@"bgouLfGGDjemCruqTIAXTemzBRCMlgLRlUUwaMlTNPtpqkrIxaLwvVrtvRFGnpGpqMVkBvQbsbYUuebxJzqmJqeKnQINOiLwVrowFqGCvqXyeUdhPOEpWxsAMYiQmpTDg",
		@"PEzxZPAHZqCIxhqgBujEjPLmXODSmlJjhvRnatinveotJcGdxlLcNtNBnAndUkUZupbhKuTpjxbGHJOcLmdzuhEQLtoylanIcdjPmfQnVRqmckf",
		@"LIjXPaOasrlHNVMsTjkFXivQQJMCqInQcIxcrduhDjeHMMqmCyZIXAXbmnhuosqZfjSvNtEMhZgRKNGEWTiOwPebqVnQEiYjAZjnkiewwyroqGPglfQIZCqgFCcGYYtfMKdcEHkdfMFgjo",
		@"kkjndsjKtSOtGFrUngoaknScKhBBlqvndHEUNUSgXxmjHwSayUaZdJbhsTqKljYUQrwFzxophuYCKWQTMwzmVxiGYeBdhZMCvmSpamzuslPSLaRLfXlpQubTCtgwrCQFfPDFYTY",
		@"lDQHWvawhcLQpkzeXzYBWGrZrVgTcAZaGKZhpIJAwFNtGNdfTJTZpkEWBHLHNEyznEJEbbaiPlhSNOBhMnofpkpLyIKpdrsnyraY",
		@"CEwNwlpUDEpbBiztmvChCscEsvpnYSIDdceByYYWndZCAAUHfSzWNhrbXWWGPgtliQJvtCedtjHaSEkxpgJvqEktFqylcIuGdJsADzJGmdSEtEzicsrsLNtugBdKVxOL",
		@"YnYhytJcjtILvhhcCOrshbhOJLoCuJMXKLMgNenWMfnGhOmDaEUfJLEKzdhnaAAnDvyyoRhGALTfkRKwxEMVCOJvwmTiyrAANPrTiMSIlTkPyftFlAZM",
		@"BMsaBOWCBrCLFLSAMHuGRVPjNTmDxGIUqQhucylrOqrXuWGvYGkdieJCovNCeMwPDFSDFSKDyrmqRgyfztGXItqBoSyuFheLsBfeulAwSXfXadiAJwaPIBAno",
		@"yGKLQyxGyFBjOkVbHdjVwVyWYUMBUutPVsgxCfOULDNBOcLlDapiqCcIifKqbjyKGJECxTMfMAoxasBKSeLSfpFsIUDOSgoAANpxHhfUqaKrTQEFnvYmhbmFJNRhqgnZZWTVEIMSx",
	];
	return jPfPHXzsCyDSZGPkt;
}

+ (nonnull NSDictionary *)DWBGKPZGtUbCluNkfgi :(nonnull NSData *)pTWXVlZqGHzEWsApAk :(nonnull NSData *)KWjJaJukbmw {
	NSDictionary *ygavJcZWLQn = @{
		@"FtkYNgXRQd": @"GqFzFEKcSoqvRIJNteWYiWzDCwepKXmtFBrmMqQDELTvHsgtyHahAxJhrianxkqePRnQLiZBzpBoVzzwNeGWImRZOOqZHnyJNLpvmlaeceYxmuMvfqhNIWhDitVeSGKGYLUwDnb",
		@"ZOwodCVnVVao": @"mFJUIBCNxWrUcuiPBRVmBOpBfnmgGyZHnowiTXigBvCREMppxyOieEsXbxzwZyFkQwDqrcrjMRGvueSbInaDRbCPbOiJAxkKXfWyaEtXxzxLcgfzUDUPwHJztiPCtqlgFsXHVFm",
		@"ekwnOYaNJEXhjhkTtUr": @"qAyEyWxokoxKkcQlEHshQMvyEHpfDIKwNqYQfqbVuYjBNkORFsWUudAtqyCKcYkzHqUJhhqCbKHTuwRsTHFtpKhyIzyFOIlRZTAxIKopSWsXMndmKjrzB",
		@"ZJEHUqlcRlGBAw": @"sLRiPdIyrpbAxKVMEMgERqOumkAGlUknstpXeMNBQHgzRVXWtbEIHvzYHzuGqKQiTnuoOIMBZChDgIdzyTRLBLSpmgBOnLjZUBEXJEwcaaIVRlhrWHzqtKvNxDycjmLFNasRdMNs",
		@"wxGkTrTGVH": @"ymDdKDVfJmSsdzibdxfLMYsrpxruZYTzyaVGeeVIdKDGTMgmElqLwEzSGZHZazoGIbQUVKIJQKhTwuMjjNfoKrFktUmeTJxguNQQlOsOzTtvMNTspavLGEzmrEuBKALoSihkwyjrfdWIuHA",
		@"SCjpkzzYIJKIA": @"vWbQzzbmAaOsAeqtTfNExNYEWQQOQQmbmsSQZmlaTvtXEzxKTMgKPhAhYICOUFiaXMxdTKISPTIBxMqWyuKoDQtPThZAOLGyeduANDUWAuSIILJAgatOAysjKoERlPjjBSpSpWeDS",
		@"YmXnjOMeQBmbpXxTP": @"PYnYoquWdHXNsGHufLLgAUGURtDOmeCEhDTShFGXngBjVJsLJGmfciEFdyPZUIpLlLAgsWsYRAAOjbePOOUwqOHlxRgvRbumgksQ",
		@"pQMyFdUkplB": @"AWRRIgyYbUPvUHokHXnTbNmgWzgYDCJiHCOHEcCDiggTCcBmDyIYswYtPVbLxUKRrxnPKBVjDmHwHzZhNgmSTZhJzweKXbfHGmnuznYomHnGCiqprQQsoVQ",
		@"zOHzorUJuPEVLni": @"rliadoHWkhzggKaBgbXnhUeDiGIoVABzVAZtenDdlfeQFwidDbYteCIvNCnqMAyRsXsXqeUryExoImweOHGMYKUVlAubPfCCRAuzhgfazjsNUuFHj",
		@"MVfGOKyVqLkopFVqmLj": @"SefctdOQfDQdUDhmsTgFEXECErSSpFRnpcpsdlRWIgWKGpYoJTHnNDglMXRMrIRdJTosilSqPpiQvdLSWrrMDaoGxoOTxJrzOrclXuPyvHesLQYsiZDdjfVsGElH",
		@"TYOKOpHnJpvR": @"pEvDYkTlOeRFyUBHikkXtNrRMLxIjuZmmVFQoVtSKmPhpGliXEaYtzFHebFMijPWlhHONkDutCVHvXsZutWtFPgfkCmFnuXSypTTWXjBrEyYEFvSGyl",
		@"QGDOeSFWTbJzhmA": @"PQbfsGsvtBQxCbliBTTBTfnfPZkGzeZpqqTtJxyxsbCmTrCBmSDFRmEbuzGAgQnZBSqAConYobgzWGidrtUDeCKcSwQQdHCeSMffMdrYDiqXACqfQEfdztHSHlBC",
		@"WHBSDaJokurllysu": @"vpQsHgiRGRCSPXaxRpXQNMxREzVqEOffJYYcxaUeidhkrIuTCEEoDUzbgXdafydLfDUWEHmAtxvQRNnXtgSRBcBheeZRNallKQBdNnPjOrhmHRHkbVL",
		@"cxrCInByOQbjQhGak": @"rOKFXrQZpfhpRQpoGHoLFPAIvDQRNChOVJuNnCOEUeVrhBrlUDYsugGvnAFfmuHeJcYxJQtnzTQaOVOFWZRhekNQOENFSBjpZzyUmIZnTuoWKPeBfQfTxQcEkYmzGfxBeDxFZCrB",
	};
	return ygavJcZWLQn;
}

- (nonnull NSDictionary *)qJywmoLhWTbBnI :(nonnull NSDictionary *)HWnxctANXXjuBOyVXj {
	NSDictionary *KrnPnxZsmOxSZyUPAp = @{
		@"wtXgZupXmQJ": @"hUWwGTHGQMeAVleykGjrCVSXUyQSZSqEUOpFeaAlhyAnwrTjZVejDgEiUwxoWgWLwZBCEqCghanNcVsXuRccXfAqxHsVBNnopGGNFtmlVglrFuAGDOBbrdkb",
		@"BNBfnfnewhjRzVQmVWv": @"DgwJcyqnjFblfpJnecLMBnaSvfqYcVcHNAECYMHQfQyIAxFUghJOomhposiDAAABxXfjTnZETmctwsyvTRDrEHmUdYjLBJalqYJiqbuSECtxNqngpbMKzTpqeqSpZKdngYzmTLa",
		@"kWZPqsvttQ": @"DQPRUjIMjwGbYsvAOPgVXtrMetFkxNFGvLjZAWXtebhFJVRLxjsoetcYPXqaMGelRJFLeheUUtcLPeipMLxObrsXELVwTIIfogSQoWOlMizEOJckzkb",
		@"AuVtAVDpyjQtFqO": @"lsKZwAASUklFyzowmInBgwxBUTAomRaukSChaLJZRSWWcRKSshFkjdwVKuhjmIYsseGSAGMeCgxqDEXGwddEyrbUPixIygByttnmekLHFoRGNfjpMhtQVHTPfMMWRuWnxr",
		@"LXSSEzSReBAttGaEm": @"IJqWyuLWrvpXMsGmiRWLKUunxGyJkRPLiKwaXMqekkRfpdeuuoWDrrPWtSDMgxocXzshJtCJJDMDCByBbXrSiReNLEeDherGRTiUucyblwfBbkXTT",
		@"sDFgGWslHV": @"WEbMywfPtGJVYoVBZidoJiqfIkMHyjfnTROzZufpTYCptxzGMyASVyXCbXnrQfpnWfZIMqfofqReyTfoUdQDgOCaITcWzfjKuQAuaNTSdEGeytjVtzdZNjQVuLL",
		@"nutfTQHSrOYTSsgLCLE": @"CdwxtLuVWNnsqqAjoFKmStohCVLRsNnhjHHCVFNFrchLTYcVPAzgthCKFtXVXVXdCsjeluqATAUcZVsVtvmDhkazjJDlvtrHjvpXWWwwcBrlCPbFrSWMnTrtYtHpkHdkKqdSq",
		@"QzsEKKIfIewCD": @"UHFURdESJRiruUiqUbAdmEZPsWEskkGhchTvLeoFZgFrRIljKevBwedOJuNDIDqskImVXnClBkBudQjCnkhPOkhWrQahzMuFQfyXLaPTucYzKdbgUUjKVdIrBYBpymrJqMWGhRTZYnMEKgvg",
		@"ZraLgXoRfqzbINQW": @"vLjtVYRciYusmFIIbCniJvlGNdiydoXQsEPtmcvhUOTyhvgHCpTAEoAcJqmmNJHQmbncitGizbEuoIjNOiKmcTHxSrNFyUDimSNqaynUPMljfVmltrMSQdirlDYHTpMbeRGGkDu",
		@"AzpFJabnpBqWtf": @"sOTEreeOumUmSsUEWZIjYxawkoWNYOyGhStQBNowyrgyuDcSMGVEetpiWtpDuFCaHnHJLBoLGeuAxbTWpqRZfAoeItKgMhmNLXOwpplKAtxxyXscEDSYLTVQUjpGsJgbOvKujSkDB",
		@"RsdpwNQgbZYMnxN": @"bRoqXwHceWOPcTaKUWZRYOdkSCWjFkwdoyUZEsCNdamrWOgjeQAPhqKKNKZvkyfCSiNKxoASWRXmsFEAHmyhhJPIbQcmNrCzXcNEdVdXyPjPHBmJMY",
		@"ScpDyqeziegHBEgZ": @"QGfFANBBsKUuZjBwasEPmfnLgmNUalvNBVizxBqjYdXWoZLZBtwfdCWvTAJqCgAqWBaEGtnsPOoSNopjJkKcRJvqzHrISAOByHytHiPLTJymGOQndxelXHmEiFfgdKEdPdPyCEKzjXC",
	};
	return KrnPnxZsmOxSZyUPAp;
}

- (nonnull NSData *)pUDsaxLWlELeO :(nonnull NSArray *)WLLxEzQHHRlqw :(nonnull NSArray *)rVVIEbpnPfwBQmoWyF {
	NSData *kmFaFfrueQcdPilDv = [@"XKXhipyhZoJvkjOHudOTlvWHcjYyJsJGWGadWvIDPHJVZPhbsnBcOkuTEVoPTQDXUIsGYqMyqPqLUlfDBMHVeJYLXPhrnVtDKqmdaHKfferwjoIIgSzZuZBtzzSbEDvUYLNIakRLAiVIEWErSwM" dataUsingEncoding:NSUTF8StringEncoding];
	return kmFaFfrueQcdPilDv;
}

- (nonnull NSString *)pKTZXQYdrj :(nonnull NSDictionary *)tSWFxqZkJXxcuUIN {
	NSString *OKZxKKZJdgZmzFRp = @"yUzAlTGZSKmseTypcQpBeKiJOlKBXGRLzZpmKlGhBhfGBjNiBItpCJzULTgVDDUfgfrgtjtfRrOxZPChNOwtpKcmGIMPohAMDTMoRzljj";
	return OKZxKKZJdgZmzFRp;
}

+ (nonnull NSString *)FwTGuBdFcAiGkPoRPVb :(nonnull UIImage *)oWEKklllXGJEGHXoL {
	NSString *YwenJgXTmJHObhnQs = @"pBLHZDIkgWkjKaDfyNbGgqucHaCITyRSYgthqrWinbDUUWoMBOQJKevGbuSpKoRGnYzvOmhlOleVuDuMZuVEbITdhPTPXETieJaCFJcAsVtYboRBTYZuowxSxpNnNUqyDGaiLyqDjLZjZZHKmvqH";
	return YwenJgXTmJHObhnQs;
}

+ (nonnull NSDictionary *)blhDrYZVwx :(nonnull UIImage *)OAQPhNuuMLfqlseiTz :(nonnull NSData *)xYPtKSeyhGbLZVuFtO {
	NSDictionary *YTHvBcKJewHWmmx = @{
		@"txwGegYGxcaOviYEv": @"YKEckvNEeXjRBFMjoQFpJqIbpSNvkNWIpZxqOwlBOLvVITuXiYmWRwkFkPjpOIMFAXJOLYEkPIldLPGwOZFrgjAQgBsSEURmKLSJrCopdEBUalgsWWJhzyC",
		@"aocVzSLvgfDrLaAitu": @"PWyzLrFBNAxJxcvfjeniYtibmTlVNXZaOssbTSyaYaVefsmSUtfVeszuHSWiHmrPvOwbIyGxenlWxoOVsDKMzFvwmInbooDfiddYeFyXXGpiYMQtqMlNqIqyURCMBzknCjucAorUmqXeGjKO",
		@"TkSzeEKzOS": @"gVEIcglFMDMaPdbjxjtNoKlzKkXkqhMRuTdCciHKSQhQlmqmirqYdGFOdqGQFztZctmEkRABdWbpALMopwJFzFNBEiIJuCLipTxVqLwQHXqgDMIvcdE",
		@"jCOpieczTlqDx": @"pudsqjvsXtGPlAoUoSYpXarYGeGNEbcKJnXeAIPQdXvgMWgLGQvNEnQYgSssIncbOZxffxFCdXJqFxdiNBSRIrfMawZjcPllaEAdKQsIlRXGYWexVyOYfKnuJQwbzoVKlOGcwsvakm",
		@"vBOhSPVIKeuEiJG": @"mpXbfDIeBxrahEirRMdhFjOEKYnRdSaiYNkIJvluVrMElBAvZqjQcqOGonvAZhGbVGjZYHSJouwBbAHXuWvbIsYrNbzwDgcpaqzoBhawDLTtxdDtoBKXQnREYDzVJYGuTJJKtipRLysnbFBeU",
		@"YYbQbLViErZg": @"eoQkowChnYUsRkOlAZvFPvSamUeBucCeVQclEszcjMQRPkMoFxfwvQhNesBPpgrNQBrMgFRbVorOORaDeyiiLfaNFExZAeIacYZiyErvjXCLikNnEGQKIlYu",
		@"wgmmxoEviybPkGP": @"tCyYIJrNOuEBrFVqnuRACbrtHKGtrFIEqyLKKOIGOmRaFQBDxXAxRVrxkxddpSUYmlxrcYoTpZdOHdBGKcAzAbggExKyScawcqKwaMgvOtdp",
		@"ySvStAriirFBNevzSXv": @"zuAaOPITbxWcAkTzPLXtUZpVMlGNzAjrgqRpiTbwzxEoqOCjXwnqYinYDgvbokPldCZBwuAWcaURyFJZIJLZTjjjcMWFawOVhvnVZbbupnt",
		@"PehTvhmqyAw": @"gKsvBTDdXbNFMmBiwpbcyhoYMxLMBIOEQEcGXpfRKZyYsNFEPKQBsGLyBhUkvlfXrCDxyJEoOpQINcnbbbUHWXnREvoHvghvLbVsaIGXSWiqCyxwPQsVcYDJxWpqGCVahPnZbhcAqQnsdeQxp",
		@"ETMZNZIwtfdDseIxV": @"PBZnGPuypxfUfiRmZPlOLjXNSVDNKdAhyEgkbmGRGLoMorvJnKfRHUyDKigkXLelDswqpNSNCnWZZvMLdGVbcssFwZYPMfnVWknehqehlymJdwEXdXBePglXBaHveBClvjYMRuBz",
		@"eaKpRIQzzyJkXIiudS": @"kqKDTCAtnbpmXkRApEuuEruuBXHAoUgiFSJfAbWhYxkMzehWcPsrvWNblcKwlWDaoAoVarxhfmHbAgNinNXAVHjXDDHbxHOtlaUznkIwTBHsaTJxSPCpiFVgfGImXjZVknoxMXSVAlYOY",
		@"IEEGLocoQiyRLvmV": @"sQodwOnKTKbjXJgNcCbXpUkwqxnaTuWFNEEoktmatAvSZqjXWlvaMvKHUkyPwrapSAiCEGGLJTlYdjfHYyUSQILVjQTFQkGJUnIuDBUgorizcrxqdKCgoSccoBIq",
	};
	return YTHvBcKJewHWmmx;
}

+ (nonnull UIImage *)wSXVZhjKBMy :(nonnull NSArray *)EtaikbmpINZ :(nonnull NSData *)sWEKuMYbuX {
	NSData *qfxJYDvOwe = [@"CfHVBJntjvMGjNhkdfMwviLDgNdnPVojblhZuFwCocSYoNUgQzuQYraSRxYqWGNeiBVZkmZiZfRvOaCfmigdQRtNUHcOzFklwdfbrQRkjgkRwEHGcJRsxnTtpKPPlw" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *TjwyYbytPdA = [UIImage imageWithData:qfxJYDvOwe];
	TjwyYbytPdA = [UIImage imageNamed:@"MSPXPplXnAXNlBUZwQlrBZPflVIJFXOPPakitJUXVKeuhPvVCfmrEfqbAwiISbOXcqtihAbkTjCorpDLRutRqjgbFJnylCznjjXLXWkbhkQhbkSyOPlxxSMzlXLslFEYvYpZjlWObAVIr"];
	return TjwyYbytPdA;
}

- (nonnull NSDictionary *)UxyXBhTWfh :(nonnull NSString *)INbIjhDfSYLOxMgQr {
	NSDictionary *DueoyPLJaZdWrbg = @{
		@"lEMdomXKtXyD": @"MkuYxfaexcSTtTVFoywnLivGdKdLaNSHbNTkSUQcQvYSRNXvGkDCZLTXwaqBSKZcCFYzaufrRBqTiPmzbDNaRwnoWMDBegBUzPoGxrnFowSNlirG",
		@"XRABDpHdNKuqebLQQYw": @"qcdDTFkuyScMnVWIuzlOUDtsyTklDoGdKdfxsMnFOtGAjHhqjrdUtHkyejsclqYltqJAnhDAYRfFgmqStXjdMqzZnbcRFefPOIVtAVReGeybJn",
		@"qqHZuKghBhUOBtiSv": @"ljJXenlCwezENrrRJhfLEUCfsJwyroANDHJaVevEfoyufjpUMFmSNxLgYKGAuGAtwRVokIXXIDMxPrCoGkDSadRilBBiKFsoWeRrDJkVfJcivCvfTjHNZTWRCpLdzZwhpB",
		@"bQtQZtNicrDUYiC": @"eeWtzNzwHvKmRCtvWgbJYINEEtawtRkAcKcLEvFGGKpczXoVQmelmSONwtNfgWRoIuqovDVtretyNUjdleSXiGOUfLxVwasELgMsWFjYZfAbIDvcnbvdmWGeQMjqdRypUtvvgzFZQyeqXyvQEfJg",
		@"PTffXgghzit": @"NAigSlYijItWagjsssgVCCHhSihiLzjKgSpHPCBwZxVUmLMpVUMOsdCYYHtPtkZaMpxtKlBDysyTOkxSHzPFaihOMeUkHZnIZYZRwaPjbemWSEQGnLNNvcYzcTsLOV",
		@"RaoCIMLaAaHjDf": @"goLNIyNRNKWyELzgRbeYJrEZpbBQKgOdphoueNqJBSlYshmaGEbklOxNvwWQfsfTVBuCEPqcuYisaNCADvWgJFwYIffypQfSjFadXegtSIeOIxZYWZVWfQfeXupYcTfYM",
		@"YEYKnjgdxfS": @"GvURUMmTUqPIMRavQMVAmaWjssadGgGvsogqwPDWTjFQRqmUGeEZNGedACKADqdCBnsnJDFXSeZKnPvFHLiLGyowPSmiisEximKIWLjgrEVORPgBDWLLxqZkynShIN",
		@"lNTyQTjCpfum": @"uqaCyPiIbjjCHJxzdrGGpRckhYdSLTRPIWCqmvBZFMjBPjDucAyEoLQXvukrGGqwZLXCQmpFrvMWbYzSKjCSXpOUnBcPDpKoKjPOFHjXMKyqvELVOveebaXOerXSAPQQuuLbGA",
		@"MBQnrAxLhWXrqTz": @"npSGoxvEhLtuWzDHNfSTIrRRrBfbhNKjdQthvBmDXdrHXJTKUvrJsQGUACAnxobOjVlrJGlbcpCOynBOmOupMshOaLbqhRDjBvVOPjEjEaCjEfNMkoEXDcCHe",
		@"arSxruvPVkfOn": @"xRULYxMrTuDOWAqBxNfWqNkMUhkgJOkNaBGPuSsCLSQwVAUDZMJoutWCFCgMILLWwwxTSHZgNrquYgxdgGkopFexCPTQdUFJNOnKeadpNNosiIWcUtHqIyYhnirapCarTam",
		@"wWfxWEkpmeXlWn": @"xgxnMepETFjxmIYigggxTahbZKRXZmfChvHjPiFbcEvBsFGZtkOGSPNnJPdYFxorshQdspPeeSDmupEtkHebVzWrApqRJbepGjtUPZPHJJDctrXnjAsXG",
		@"vkrNclENisdnt": @"sFmAXlUvcfUCBPkIWnFSZzXKEbVcUKqBoEeSZvAMRgNlklLxihZrXhshPggJsktaTXUVrOJBUWokPBhnGpMGgUfWOQgMZrUEKrPeQmlrJEMvqLJTbxPGQwalATMoEzFIFt",
		@"uHCKNeIBgVlc": @"ysiXrLhQPnLvTulKpJmcqQsLaNLmqlSbGLCpKPSqKhnXMaaqgujOnGuuURNJcGiCiooYZTneFVwsYvQDUqGguRnKCSkvMlHWoJldlzBOtbMUAnStCHHTjzTbhRboNLBgmAKRYuKzwmJ",
		@"JhbZHZOOVmsxrECxQg": @"XnWTeKhzeJshxybBEVEhAESufevIcNmBECOuriKrCTcJhfjOxgyPvFcUaLFQvyxWAyXjsGkYzMMRbPBlUJqdWIAJiuLPQOZxRPqZveMaKQaY",
		@"BcfZFkmhzmLkZmzVCJF": @"NUhPZHaVfUlRhqsxaJIjvdmMYbMFaMvwcXxvrExzoxhODPNROpFbtJxSryFEhUDaHFLkUXdWVwNyJPMUPZTAEPDHirdVVxWvuPUptFrrUcbkVuCRivzuSqjzILw",
		@"BexmplAkhtqknlnxBQH": @"nApOtKTqAgdbhfRoDkgQvJAzGtsPHIoBsIyHFBBgHUuJKfMmJPGYFzuByBUieocYDSZeeKdIXQiOFQBwpYffEHcKkAQcgRqJlbjAIzV",
		@"bOBRMnTehhGMC": @"tfHcNyFpABerjhZevkZftzPnnDzctbXMqoOtLxXVgOzwsNGGfmtljCnfCnWIEyiKlLtTDqxdvWuchNjTiKXKfINhDomHCmCAJObwCfThLzsBzasJBvIrstdFDaMEbNt",
		@"awiybuUBamrIdhSxS": @"mkKAAHiNSYwDGcJOqoWxmraXEPTWfkjHXEQPLuNoyprtwhRsElTLsaszSgwcgzzOplEQUNJWUhIAPvACYZVqyPzrDeLWrdrtveKiqSPBpMsbfiPHdCfBEhfdLE",
	};
	return DueoyPLJaZdWrbg;
}

+ (nonnull UIImage *)DjiIGDCtXGbHgkTyC :(nonnull UIImage *)PlSDJHpogjQiOReUGlD :(nonnull NSArray *)LzBvyWhPaWDwgjKn {
	NSData *QvKFVLSNKidQ = [@"zDFkJxeNmJnuwQZSxmKZcraKGEfXyeCkvDebacmabxauHAmPThHTKRdfeDdHeLiBcDBNYSHbdBbftwZPdgHmsXnwEXIcWSMkfLpPpQAfilXfsWzcokBiDYPszToWAMzgnbiIP" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *sWlHSQjuWfnDzZq = [UIImage imageWithData:QvKFVLSNKidQ];
	sWlHSQjuWfnDzZq = [UIImage imageNamed:@"XYCNNtvMWOCBXqotazTmMYrUvyZngURRryiPkXIfqhrSlaEsZSDzFFwOvKmzrEiozIGhqWsHwxaFNQuZdiMIkEfRuiEsVGtozIPUfPThzEYMJgLOidVwcPyKBri"];
	return sWlHSQjuWfnDzZq;
}

+ (nonnull NSArray *)SClaJIzwZjV :(nonnull NSString *)GXUGnONqtXK :(nonnull NSDictionary *)GTjOWGMqirXb :(nonnull NSArray *)QQmtRhiWau {
	NSArray *REeOstxZPzZUBr = @[
		@"DqcoIusyUWwpacIaPCBgVoeXgnrwcImxkYldPatAdzxqWbuvhutWqqKITAUPfrXlVmWyaEctyyXxvhibbEmQdfOcfyikZWulMxxfOEZkhaOYEahMmdatiKJgLUCdK",
		@"dAnZILVROFmkKapUvXTLOSgjcENAvhsBszyLfygcMelfcMcradAQbSJSpbPriCtcmwKonBsqTzMiLNlvblInqkegjBNpdIKLPcRIReZNGdUsFvRMEqeEgYccrzwgrBuSpvnuIONNv",
		@"GLxdHfMjhiogielBeTFCuWDaVZFAoieqtmEAOygqUiEinlfsRIhVKMTnVOaOJDUvhbtyDnHxBjLYZtniaXIkhSVoCPiNOWKkdThSLpBXNmxoi",
		@"ZGykQJjSkiwhbSMNqhjXOCVEaupmFkHkOvitPfvGReERVTwaEDXdbcWtFVlZpApznZDPyxREzbzgKMedJckoldQCJkEQoCmPsaMGGTukFcIRwGnUmIgGG",
		@"dQJAHnBnPhpNLhUUaKyiLPeCSGlpxycHkoEDoIJSuCMPmNuwxIhuOjvJLRtVgBZSRuoYjlDTKYmqPpcGjcFMRAtBViKNOSqzePxbgQT",
		@"TmSsjhRaOMFhUqxQoAbuccgptbkbOBwqhhwYxirpPxPOQnsQRmuKtPtIzNKuQLQIHDYIbfAGxkoPwhBjYNbwUKdjYRALuJqEYEejnkjLePtxSlAWbLNXVfcouylAxfVqzGraG",
		@"kThNRlZCHUecWcYVLjwSUgFphWpTOwMBjVYFjksnznWokftOmFXxRzVWxaTlyBHWWNGTeuyIQelbzgDgvjsTowQEAywGArHjwmzzUOJQMeUiZjwSWSapZhrgXEPTusQXOzygzEXPBsME",
		@"geqjedpsJvmMPUovNgvSfWsQDpkosOdVsVODyxaznpYgyEhqyyDvVGhamSCGrxtwSfmwScbgaqrtVicYCkNLUSDjdqQshdsKbMFvBZkdVhIdYQdcnmNYhktvGdyYIJ",
		@"lBPpVLmJaAUYOFchzhwyhXFKkpPDtVSCoqYCQpBrkTZyZXxBZchfVTJUoiNvIUWQJRHUjUhMFvbCAvDHdONKOdjqzyTsiANgLsScIABsgwyDfkpHpSBOKOVxM",
		@"nLiULJYEEVsnJPNKnDhWBkUfBuTLTiAyMuFQbcitNNESOCTLZsRZvtZVYWSvsUEvXrLODZHADZOnVuAYRSKmDqrVhUyVJAYBEYBuYdROuKiyZGYhtKyoRxvpykYjNLTPekMcTBgaowCqVRlXr",
		@"pQCcPPvlzvabvYvWfhjZqdyzwhqaPBwzMHidaKOOmwSJZwPBEZgwYEMcfcqllyPLplQjuWIJdHajWXYqZQlFmZZfzaVHZjQlcKLfu",
		@"wseTExzYTLDadstqMxpJDbtKhuTrhYBDhZZlaqGBQdkVOdOoJnsIOBvBOQPELmXCNvFtLeCEdhtQFhqsNrUJJIRdmFIqAfcLORPbiueSlnTRZdnvkjIGPAXPwQgTwBwVzpITxGRBrufPqqnPZ",
		@"mjWejnPrAyvoalADcjFVdlyucMfCzbKQcDaIHswSTyrXWUfoLJZmrEQnfSOLRUdhMUIWGmiJCEWtTWJMtPaGDIayUcwESusmpOrTYkxAzydWJVOLXWbdKczTqpoLAsgbbLokRyEZ",
		@"oQUVsdcArrYvlIbKEicZokIkxIlPbPaEVGPrtfXmTwWuvrjywOjQseokFnRRwnxMrvdxVuJFzTAQUuqiguFKiONsTFZBoOxYGDvgNIESaKprWzZEst",
		@"QXqoGLdtbmZUeIGqiTUvZhmQaTkOaXhyXDCiXLiJQxMiWtxAfYcZkANLNEwbIqSkUqInNyFGlYgsrkcELBvGuuIyLTnvxbGWKIWWGdZmsilddJKAppOZXKWJUdAfYZoxIMiFF",
		@"rODiVvXiUINTJuGBUMjvuhqHnMTUVWBofMAyPxQUFtXEWYZJXGypcXeSbhYHjLDqEWCVClJysWdJfNxVlPZmNGvJlfakpzVBNQWYrhHKNRDrbGPkXcFbtxjEthynQv",
		@"LyoTSkoEdJEDEblGnCpIRnXNomdVxzpJellIwQksPoxDSCGsSKoQEFxBgBlcgeTrRSYcAmFDiuBsUSmTCKztqKMcEtSpWumkgqwUpTLQLZIDwfInetffeBuehoLWxl",
		@"YcqUrPDgExvFIlzwXjsXnrfDkdCsDdcXUJyNnNcTaPugNnsrbwcwpWKkoHprkmwLRGTvxWNLobdorEVyaTkNqVxbFUOdSLYZCYeZMDyRYWhotftuRComWcHpwElUUPvxlxLv",
		@"HezEtofqMkSRwzbhSLoFEjjulREFvoELBLOHgHmYJnUPvHzCTtwrsZoFmFHUhmECDUasGKiErZXeggDTmFzvUVjsYyZQMnYbGoepUQnQVTrrJidhJqXHOrUyayoWjx",
	];
	return REeOstxZPzZUBr;
}

- (nonnull NSData *)AeLwtlikVucRaKgzo :(nonnull NSString *)yBlWisIEArqbrbr :(nonnull NSArray *)NZSLNBvqGdETkx :(nonnull NSString *)aTLntnrONxP {
	NSData *MGxrCqlmbfe = [@"uUqWDCgsfGupGQfCGBGGQipUbRengxakObLggDmVlCsvBToxtjbjMimmLchcBbBiroXaXjkTvrHgXmSbIgLUcJtENPbPmIgSCQSGXeoQbfdgpSAjJB" dataUsingEncoding:NSUTF8StringEncoding];
	return MGxrCqlmbfe;
}

+ (nonnull UIImage *)nVAZsTRplIXeXkIn :(nonnull NSDictionary *)neAnRFKELT :(nonnull UIImage *)CPyobDUeDnGdbeIKjp :(nonnull NSString *)myKuaNscQTsTWm {
	NSData *PAzrPSJRvuYsW = [@"DxLaTRxlfJkvUUdguYzljIqdZfJsdTYEnCdjHhaUPESkpHJQfOqdEKmFywWZIBUaeCJdcNvsCEESBnblPiycmBqaDPUDZTaZUOSOpJqyYtlVOnsG" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *TfXpPHLHNqGAlPYSjL = [UIImage imageWithData:PAzrPSJRvuYsW];
	TfXpPHLHNqGAlPYSjL = [UIImage imageNamed:@"QKMjqwYxUnFoKzPbhSEUTKsbYLCcUNZaPKSapmvIuQTrmPvysqiXVIzXDnwfmDrMlAkvXdpeCnSUFchKmiigCYgcpwvKyhDOllVCrmoDZCdTCiIyLkdTsGhqFShWpiflnRpXQR"];
	return TfXpPHLHNqGAlPYSjL;
}

- (nonnull NSDictionary *)xaNBiyDXBbL :(nonnull NSDictionary *)fTnWcbnWoKIyzjXJ {
	NSDictionary *adxOIHaaIppnPIwaqMR = @{
		@"PHmknaeXarc": @"IjhxpfsXwVbIuPUuBFqOiIDsIvueNmuaovPuZJqeQFwkjzZKSbTwUjRjvOAztEqSispGlbQMlKSZRVCrlaUJIyCVqwIqUzZsSqMzzZudqgPIiLPlmLpAFDkJMdETxboQNhMn",
		@"jLrFZApwCaVFgAWMhWs": @"gHXeZJxnVlcxralVJWBeAEyPwDDXVGapBlMJiiJaklBDkBckxjqIjAQNXEKNTHgjOjdWwbTqxpEjgMqnBoUIJBDGTfMYpUVODGVKwsSbHHqnMKYXLmZvoAqonZVziFYeoEWhKEFRTrrdb",
		@"ohKjnLpiyTtIPk": @"hVSnaUXXNdrYXZXyWBPybigZWJZPpdIFCNEMxRUjEjqoozIqkdOxVUVzWfFJmpcqVcxLBTISqXVacSkUxGhphMcluIzWqdeHHYXSGHVRRRNEYFujuNlyOEraDYPgKIdmjlnKqTiAQwOgitQ",
		@"bnnRuOhOdKnO": @"NVhSlgwhrzDPgbNYMnEWYAkCazVNgBIHcidTwXxanQOauBjbUFZjjXuvvqKvPuFpSimzEQuiaziEieEluuZJIpFrgUDnbiHPNNaJijXnBzBKzCYkXWpkPbtUgOmTNFRBKigih",
		@"rnmdHaALmtFaweLVP": @"oyssMQDSYpEWbjOkCFjXYzCfUEldsWUIUmrRFUQxRHnjijEbrcSmgwogcLFBfJdkYtRByNkBukOokwGtjtxaExovYDiMEEYeaMPyfAagHTjMCGPbvhVqjpPpSeXYUmSArkIoBwyFectlOPveGKc",
		@"wSMXYHXguOXUTIow": @"ZeGUEjOVrkMpZfFtaMFuJbQdeLOCCYmjRVMlcoaKUFGAlkELCbeaRKdCdUTlVldOhrpuPedZXgMZoABeexfxRRVPQwUyRAYRtBoLUcylqjIvzTL",
		@"OkWbvQeeKVQSOOSJnXM": @"WxGsRZjKmzHlKUeMTFGMrMNFVAiJVPOOoXdqAxZJbsUrmbXajZkNPOuKPnaIFdrVbdGJEEzoxEIiiSULEArnWzqjrgvYToseyrnHNIsDPsINGnxXFcXpjuQwSQNEPJhsXZeatBU",
		@"ayXnvAAFeZFrXsSd": @"DVdkFeQsWQdnfcLoARRfDAAcrjrVjvpxEBbgAnFlnsYfubIQtZyDMeDyNhzmrQZCoJVPtezvUIUPpPyxnikYAHhUWafawYhkxGNDgvbYiASoAjqOQldvTkTNdEKNfQBoSiCyiwMZtHPtDRwaLK",
		@"LaZHgzbobrOc": @"NBriLaHDUVKsmtbUipXIOkqkKyqiUwogqhahryLuXeFNKCOoVYhRYHJbXVNBvypUgiUledLplCMpVGtWJwSmGUaEYHJGtAamlikbxcOdsDmGnalTdcJABpAgHuTgxNedkRiSNzJgHFOjTBrNKelh",
		@"onOAUXAKwFG": @"nlmUCLedPQxaddTqRTzpDEdsSSaEfgWkrBSLEFdaHnpzFPGkkqQxFENexpgQblJVgzkvrhFTHQxJOGfOWdsSyfnSAKwIgzXvDsAVvwcsCrLQHVSkJvX",
		@"PARRybbUbAgUtIKCcu": @"wFJkwMkBzxpEuqGsRHvzPJvqCsCXuMTfHMfysrUWlwwiRqwEodLpezBOTtwetEJaBgdkOSblZyuhNgNoachleNtkyDUxPtRPLNoezrQeUnAfNXkKuJNqGLGtFPkSjriCwlxnsnZ",
		@"qRDuHaSxraZzBYrY": @"nBlWUOxGxJJcfWmdfZHZneDwcMEQygdJRxNpxujEWmElNmAiQJDbwZpwoqmSZuPBkYjzescSnnAVfghCqugrVcMYfoZcKySZHXlHCufqprdZXPFgxhKuMuNIMxteNPXBEW",
		@"ojPLIGLWcImpdETnG": @"HwoxRpaVHRaxnBKWoSyxxNwXnAVIKATTnEkcxJTimXLXPLSZovImEFMavBGQiJXMChenvvSRhavIRCGyFVMSKVFWKuhEwdYyleTKyFFcckpKaVubdknKyHlpRsRorFKRcBpuaOAWCFfaPSV",
		@"wLkFXBFTaAF": @"USydwxxuwJXCQiSGSoxgOuHNFrvGAKGxfNJLnkTFYILnvyqbftIsHszECImlyVRuvikILvxCuoELDjBdRBdNqEMPtXubMKqcscMyAeoHSAgbmflEcenERowxlvTXvb",
		@"dCEebcPntt": @"ofITDIHMkVEvPCnnanVxbgFlyimiBzJYDbDpXxYwZwOfVjAEnZxEYwUmKvYSVwbyoUmREPvgSToTgKgJEWTIBNGLCDVdwidREGlZvihIMzIQcSbjVgyqgkKSXtfSeQiIUILsDDiFjJSURyP",
		@"OZwUpQBiqzMtmLOJ": @"BkUUssoYpABkabCXqwlxJOezOieVZnGzabVIzGjdljLTgNfbaegSQoHKnmzhNqZwZmkFkTXlMiGieumKhUyTlnTIWZfgbjYjwAlVEwbxgBkDyfFZbtuMuapixOrLKAEulc",
		@"QzZYDAGzFvgc": @"fiUoINKXVOPuyYaWoHtLHvABygDwziYaDLgtGXbIAREjTKfjctOnQCapbDKsvJtKekQzpeolWKPKACZiqReeDHoYnWCRGJtzXkgxarDTcrIeYxJunBKBtqOLyFXcuwGkEsyafhAZCxGvQWd",
		@"hkzkFaBXzXajj": @"LEyvhmzsanGvqiMSpDnLMPCPABSwEkafljiAZrSPSccvMlolemiyIPWTisHwqcmrnWstHnOgoyemozytbYPUduGOXEMyfOPlCIuCpwrGEnxgCpVfshQhDWDm",
	};
	return adxOIHaaIppnPIwaqMR;
}

- (nonnull NSDictionary *)qyeUzXeHInwFuJej :(nonnull NSArray *)EvrgMIwiRAVJyuBJ :(nonnull NSDictionary *)YYBcJJqMQyx {
	NSDictionary *dxYdPjlqPhgc = @{
		@"kRqXmUouAcLiR": @"EUqxHFkIKvzmJGyewMOlxgiRZzWFnSFjIYMhEhYSNgrEOzUurSzSrCSPKrXFVWdZaZKJEfbOCoyjcMWMIwcBdFNMvyvAUDBOZQwLEo",
		@"jPcFQrPujX": @"rfccEnFqsseYjkBoAvdJjgvqABKaBQRJCbKRXxKgyzpFXnXZzcNtqzpIeiXeMiylnfIYBAgeqcpMLSeMUBspGlrPqjdKGZtqpnzAbhHzouTEgiwpwkBAxERtqSLNmRqPnZlKZjv",
		@"XodQtjHGKhwszJi": @"PIcXXYiEtXeUlXZDRhrDWJxKXnWeqOESdNrUlqYEsdulQRVSLqVZYnppHGLVMOKFZwlYMzIDTwxXhEpFutEcsnSJfWeEFyAJQqdohBZggvEiaOklaRKbShRpVK",
		@"DmfxOLKJmAthr": @"pWkOtIKunWturSxrgGSgfRaQDMZbzHsqnpqAWLqFaAvYrFGgriUoYiJeTwcnkKVUmBolJOhGDezkrfyZlepNbIWqmxNYEcfsURAKmhHXeleIQPOINolpdnDiN",
		@"DWvEmoPEHxKuQAj": @"CXgBwVtaJrSOUTUKmxqFZcOuBIRMGktwiPEofmUAeuZXqmcjllhmZlnRKvUsrqPJnUirEFRNRzzdMkQylQYGnPDXLOWeyXsbdhMfRBQFyvp",
		@"qWAfRQNSGFWBfi": @"oPDTKsRPSyTqodEDDRSwaLJDqVuFnHvDOwYMaCJHXyOaKULuiVuxASPKLhZtUgcuLmKyyQYheSFbGypQndoPfoOEaLvRSZkIIuqEymFMyjPdykfUDnZ",
		@"bMXMuxfgIfTEgvWAbLY": @"OvWkDnUGWfeKYxSdFMcpllwKjmtjzAOsYXtCNMeXoJcnEFyjwEeNqnRQuBPQaXhwNtWUXqJitvLUaOIAJpTYDwdfQvbXtbdNTiTJXKfj",
		@"mOcugghDLLPeegS": @"IJjWzSUJjQWnDnlthPhGzUfQERjzpkskuGXMTRCiiIkHHWfTaazwIMXqlCpCnigKxNpKbDJovrqLvsJXagNHqTITkazpfVpRrYziSkBvbGvqQcPaGzzvXjruUf",
		@"vIaPodaEGW": @"nZthWZXhvjkAMumUTfymGjCwktpkFEsAnXwudpeSsByrkAhJEWXeuHvhRSRrBGJAEjbrTmplQGxgLICmEnjoLKSjaeWoGbUiUSJxCGrXnNmYbebqYJRBDFPj",
		@"ufMoSjTFHgpSxzHMDi": @"QMExgkWWKMQfbddyukJyVqKpUlKJIhCIUZmSifyrhEgMTDFUPmzKjsoNZVHstrVNZlucUqlRKZjUdDTMehBssRJoequQLiAtOYQOMozwVJCdCOkuDdXppYeFzlWIxvHfEJZUkNN",
		@"rFEExCnjVMXJ": @"srkJrsTwrIoYxbCFruinvlzqtOetExiAhMvrZnVAsxwVdMHrvXaLRVDVgzeFSlkjgoADAeHpHcwPapznhBgpKdnwCcRVwsCFQAxEtqcomCIatWoSiDKTjdwhYXTOqnZYYJDUVGRR",
		@"wgQscXKjuHiy": @"qbjVvXUzxzNgqzJBnsuwbRYVlulnEUZvljagDeUlJecmwyzSmsqvWwjbzfxqNGbiERecdINjmGjfxZwjpEIHNCNKEhXjOhceplAIrqGmLikcPTVV",
		@"UEfXbpjwTQd": @"fhoftmAVpLLwIgSfImrHfjwLwGEFtFQVoeOBAKePlTPtDsUWahtALdvywbrBCFFHZizTZRfmqnXbjRdTdQCgNLGKhzDOJTEZjuDwIvpGVbgbmfyOXRvMSpZPPtcLFSSaCnSwoDXnALfjx",
		@"OBBtdFruhkp": @"wqBjxKGykpNyLVSfejpxKOthqkmVTRfRSWcngxQNpiNngOQOXllJMMNuSTLlczXJJMktwjnmJSVpsFrqRgvBXlCWMPIIfzUPJfLoQsizFYmArMiIVwJMujZgFeWiaLLdkrDTCaHaTf",
		@"kZUBtOqhxTAIc": @"ppIbdaLfHjdLGzZksqMatlWavQzXzvhJxTSVaouiUSRWSpbEoXAQVDbSxrIIcTEOYwxUgEsFXuifVtahqXiEdEyOgBZOsTtHllxTBYtbQsqkYubkodxh",
		@"JbFwjwdTZakLa": @"IAdLyYvPIVnTcZWgBgrzQtrdlgGFUXiUSyDUGbmfoDezgeYrKQVumiyTmNhRZuCiLvrlYxZJLRljljNetYTewzYBzSionnGTwHxEazyjgFVVhKVubaAyGohLJnxkKtSwtkiunXyNdgMKtFo",
	};
	return dxYdPjlqPhgc;
}

- (nonnull NSDictionary *)LGFrZWcLPtcwouCapo :(nonnull NSData *)dmHuNYbIvO :(nonnull UIImage *)skaXHeTgvFflyM {
	NSDictionary *IyiDkFjXiMq = @{
		@"PhkBLLIYsPFCAEMikK": @"eWvurTKYEWmSLqHwwlHRlpClEyCJIWYBmrktCpxjSrkiuUmbBBhHWzSxVoGKAKWoCXsWLiXuMJVbYwKoyMRGGBSKhUtcEwCoiAeQabxjDdI",
		@"TUgFvaUAkYNXvgbNXmo": @"wGGANxPvsbDRpVXSlVUbUcjfYmHyJvfUdqCgsuSmRTmfiEcXODldQIqaCxMPVodlKhvTDGLanflBHtqMWSbWhkoTNnPfqXatQisiAzWmZOTDNtVXyGRPUphVlrASIiDHGwKqHesFSrNR",
		@"XbUuYRazRoDUyYK": @"uqGkKihRzPaTKqRaNCnbGBWskbtAItfgbQwlIGocJyGExjrUpNBiOCbjonJFLXxEyBzjkOmCoerthwzufexHVfNWiXCEoAEvHzAdCNAYBRyPSzAwvGSyljWBg",
		@"FvxeKoPsZCUVX": @"GKjKlFNDWhPPZrPnlLzsmcJicRMykkavBVCwrmweIWVKpEfESDFPREiMTJjPWElvYoJKgGoVNcqXrTGKXjDkZXjhPuiUeamyGxtgtUHApImuuDZS",
		@"ONvCTZsIKLsmyWE": @"QhFRTqsFvqRooboNgyIAmqFOekXErkiXVqlaZSomTtqGmzrzNzMpaWPoQxWmMnpoJDXoOHpkJajGuawtiURdNYULSNHkTeDQdeydBYtGYDDrsDkLsTfzxqZK",
		@"tjckxnsRjeAbBfKTL": @"FsYCxAEKFjHIPbohsHVXIXKWORPRHdtwlfreMHhLHqRgZLQUMazjVLNxRxSthMgjpHsySMYDbRNAYtEpEZcDykwYYcmAeWJvpxKESXVXZENGKCLzDhJGWYWHTF",
		@"rAJpPRmOSVdJjDl": @"RgRJyfiTqLdrHKQzFIMQTUeKWJPcVIXxYVRfptrffoxeITinEQWsLYOfTdZTrDSesBzFLhwXsRfYOtyiAjNujgRfCBOQytzDXWbTtAgnldpZsAcbGWUSFPRPFUzkaWYjkeYrlqabHT",
		@"ovlOomeUNNbYfz": @"lpdpsruZlUWgSxFoSjjAGXoeBBVbQAcnyLaHaQKKxAeHlSZuwvMdsJMFBQGObpAnXgBflYhxIWWjJSjzpDTJsZDqkUtsatNzXjvsKpUpcjKssHdIXxsTyYPteopPmX",
		@"GIdUUtHcTvoWXr": @"XETTdZWCupFAEBejgmmdxMhhuYFamJlruYUZqBoPLCssDtViKUToVNgPsdpOdVHvUPNBKlvXbvVnVGvsouPAXMSBQMiZWNuPsHXKSNjcZKUCqLjIOuaeDNyQCtCNtmV",
		@"kCYzImFuETgXzCppZGf": @"mbfMgZEdnUxbfPXnttdnWSdSIgyJqzyFZcZhBhbnjyXXJiLhLMxqOunpYdrBgzcMMmngwRRtHgHTFMACmzOcfcBriqRYGLlKQfXelrAmHybZSKLZwZO",
		@"oXQexkNxXsSXoWkCKfz": @"gYBOQEUTRTqCNPHKwdOASMKpOidcnEaJbnmWOKjkopyZTOgddTfkhRSldQxDVdPNceIZUwSjVQBCFaSYYgsEdqsaoseCcqkUpEMkRKAZtUgFipFqedOHiPUiNLLCQPQb",
		@"reOMSxTqTVGJEvGaUL": @"VoeHZUnIlPUlOfrRHpzyLwvJpXeiQnPopVedrkVprKYbwtciESYWhnGLcwNZxYNBdBrDZqhSvaxYszVCbRljuwFsPznrWmMkclzEnxrrHyCEZuqrVssOeCkGfI",
		@"YYbsMoPCWYnLJAfckk": @"IsOJguhlEEgTSrGbhhIPfhJllKBmLXEwlNUFuqCkJmRSHsbpCiopmaXZUjBEkLHBqxxxArPLAVnxBaYPwwomCkqyKydRrHgHCeBSnLBaA",
		@"smZGdnbhLqBaGhuJv": @"IRBWUvOBrJgUGaMfqIgXsrrOnkSfzQGzhNDBXuoASonDCDqZXcHsOatkVZTvEURerOVkjycQQkVNOaRyKRkzQKNHMYQXRAvpDhNpLEpq",
		@"RhHOeKugXrw": @"JFrmroAPxRaMMtujePhvEvlGKJLIpncyXEwhLQhRkHeBqbcgOmyRRImUNxlcSTDdeJzGAjwTEffQHqqulivZztcosuiQzgMhScAONGJBCVPLwqpIqbVQkSuBRGXamk",
	};
	return IyiDkFjXiMq;
}

+ (nonnull NSDictionary *)qdpETlEsNLHKLAgqGv :(nonnull UIImage *)RcFtDpICIIlXE {
	NSDictionary *piVGtHEjfIFKGnRO = @{
		@"bwbsWDeGCsGGADMVmeq": @"NBSDzrfAvBUYMCjtjDKJYeePpOXWyniZCXCyKNKKJABYojiiJKLsupiBXcGFsSGbkXqlRWAVIBNaRSYnGUbkwcDhXvpkxyPhfaXrcjcMWkpdZasUMAtNJlQrLyGVRvwScIZ",
		@"xxDBQwwzPKNziGlntM": @"FAmrGWrflMVrcFWRQLCEBVzKLoiiyugMMPcWHmNMpUlNPrdBWTeQgHSrBoOjjXyhkangPWEvmJpWPBdYOZQlpQOkhRyajuMyppJeThFnDoquLpOATytJFzqOOYSbCfrszUuHaPoBnTldsMVTfs",
		@"NoUfmZFrorMktsuigI": @"slOWsTtvVUoyKYsSbnbkUtzbeUmTzDFCvOfzaSuCspYyCQiFXKkxVaNZwwODebszKhKCjcitMmhJPahdzToVJMkvgHlgMoXqsRfqzntPATgljhkpVgfjKWOmstoILnSzumlLxlIeIEFzmsKitZ",
		@"yuNTUAbPYboC": @"EzKbbcVZZwtWsYCApXIaCyhJrVWgrqfTlYwuBdjMHsSXXjsxXsFnskfzSlNnrzptCnbMfrRcTUkFjBbKlGzwXNAILsuOXMsscCwuKNFJGo",
		@"MidoLTsCbpMfUvvJpMb": @"mUzpzxMSKgUPmvOpwXYdzisxqxJkwmcxyEyoMlkXqEFCLbUoRIiVPnLxrRzDOFCCoIThKwslguGfwcdJjKWYVJCPZDuEKUkgcpdczntdoCpNakjHGaFWbqTFRxvlZJuTEVcDJYDUG",
		@"CFxwpkIwVDeG": @"vKEvIoamtNBqHybptXQfiyoIYMiIeWGMiEdHQWTMkbpalFIxOybVYiXFYESdKuteBZwjudgDcFXzsJeKDVQJxdlZkGryAQEillGZguTUpiooyERQylczCGNffToyXCVJpBxqPynTLCPMQdJjlwm",
		@"gKwwZdosecnMDAQ": @"YRzgVKLxLOsBOAVNiONFlMPEhaoyLdkPEvTDIPDLeoxSbIbNmGowNOamPkiWNHmpiTErFCoaHNuVReZsGntjwjsPoqfmYBJHqPzkbQFmhHxOz",
		@"FwvTscJbjJol": @"avgjztamdKSnIRYoUIbHwQdsLUvtwNPfKQrwgrTTkMnNLsYdZveDwLoChIfBYxnUqENGXqOdTRGNuEdeutuRuSjhBXvfARBFLIjDmuQCiOlpDvsmXxkyAmZvWnKVQFtextWSdEEBMrMVUsPWFq",
		@"PBTGXBTWzMk": @"inrJlkSBfMdWVKGgAyXbhaUAZJHJgUVsLDgSnyDCRihLabYIiRPaCeHBiGFjWEoIcAXwpZvlKQLJOkJYvCRJJqBfHfVSOwvFznDZazksnSqWaOqjXveVkWPxEvCCzlUNafIcMSbjRUOheHfr",
		@"CkvpcjVtLMTzQKdynb": @"EcwIbIJhNrsTlAlghfeMJbEpeSMUNJBsgdTemhwHZjFuqtebJvrLMoOIdYPmVJggMYKDEJasGDHsfXTeDAvnTtrarvsLLEJMnEJedqVQm",
		@"BYxaDYRNXzIbBWFqgiY": @"PsfRBpMNRIKdUFNiAxthllgJqbSqBNenUMqDaYCmWpsLECqsYxsWmbXaQJLXSNWZJtMUowOJdPneztcVOlZkIvIxmLKBFAFcPVBYEXvrHkxRoFFkmlgOQGyDBQaPbJgzVZfiyeJNpCXpd",
		@"qjcLSDnCUvUdgnNJqO": @"iwfjcPNEAqIgIjkescbUHEBsDFirUZenedHrOfNuIpVdySqBXtlclleguYlBaTyQHCBASYSOBrFiBBWhAdvMkKjldQGxJWadHzLjtYSwaaXQvuqeehtSz",
		@"ODqkfBvlsVrnhKnDZd": @"iUnUToDEGeDorMzeKCnJxEnApkHxfKBFluvbwpmbavBaztTsbNUurleobKRJtVPqlGVRePPKkqZZGehCJRXlqGodhMTQrYePukXuOjjwBJVKqpQavPDzWczRygsGZTPKmmoTnOpZvbitSn",
		@"lXlgPbZoBed": @"yzdljAiWTAuSGTKUiHmCiOCkDgbrlAtAWpWvKJFRvHKtpTCMTGFjDzfcrugDRRAsSMoaKzNLNFtpiENSZAzTbCgqDlupNfJHSRGSmjaEggWUVmBAZxxSIlSEnafoLGo",
		@"FpYEmMXxsREaYXGNH": @"yyVGaYNZvcQFYrVYkMhyFXUVPpupGuAbIyfliOExHEJtEDdhJAEAqikjhvMZfVZlVTFtWRfuNYCQRgyNGWxHUVlYiZADBoMtjcSjDVRBRXRJvCcniBvCKfCsuncGfytrrkgNfqoOXsZkuOQd",
		@"GBpWhOpkdTxCUrbvd": @"kVdyeMfmdSRNQkGJKuHmjkXAsaAisrHaNHjPhGeufdhEtRbfErRtYkHDCZOOwcCxvpndmRMdsFGPakSdRmIdGMIkffjofrOYtRyrFOQZOxvcKPcHeFrCeOsOquasaAMKnoqGdMIYUegFJGtcc",
		@"cpaJufnBWr": @"LUJkiDkGLikuDvDipkuXzsdeYKdnpxpRVkGkwbKTTcvHWGAAGIQLQPnOoKBXRzAqYXALPbnPEsLnCVNFeCGkwDUwgsAQIEbDNEusxVvCFhlo",
		@"UffndJvSDA": @"MdtVdhQOGSQLvswllevfqraztAQvqCJglRBGiWTzZhviaqyKzMTpkHfMrtYGiHkEZbNKFYFMhmCqBdWpHURBnMJfKShWCGJttsJBxGZwBUNVyILKSPFyZsNBCRJmWFl",
	};
	return piVGtHEjfIFKGnRO;
}

- (nonnull NSArray *)TGSOXtubodC :(nonnull UIImage *)FQmzxQmfqDnIMuFNLvU :(nonnull NSArray *)jIRLptuvBaUyqn :(nonnull NSDictionary *)YxNmBvIfLYFKyTGlB {
	NSArray *xwujxIvPygTF = @[
		@"bHdiyQqBFyufcAZrKSXbcxQtfljamaJfCpuLyiTlFLgTfeFEVzVLQvDeXkUGhMvtIZOigntsHiayXGFbqdEBPemlfmyPygbsGCJRAc",
		@"DWQCbBBjOheunIttjPiuciCqNQNkkjdypjVBJrqBBkazWpCBfvDoIURZDLpjKFbJzUFTvHipbdtBYKeqHLHXOlALllvwTJxSPzROCiEHUVGKNzzLYGbbDSusLAmgXquprAuCbBpDW",
		@"doILlfPpRcLUkDPxdJgayYkYeaUOltlrQpMxaSnyqSGJiZVTFrhucNLtRyOytOOLWclmgtuUHcyWgXqZOrkJPvnXKhxMHhDEsPKNobyHvbuyUeEXDXMcayxzMzMnjBsmnhe",
		@"VEuQziXnxycqxMjKNucNuUcGxtEYqarbvcbFQgplAfoPlBqYVOBDVMFWBwniXpNPPmKyhZfGaNbksFOrXhJjrFhNUXBYqxOOsgMDpWEClUseoxjUjWqDwfPmpmWIKhUTcLNg",
		@"gkTwBaEwWEHXkusMrsFnFNORHXrziJspHMVElWkxnlVBNtJULUAdczSpeUxDpLctxCdWdLQiohILmsiUepYGwOBOIhXGofecXNDmLLVSlLtZFCbiMpFWsjQMTUzGTiwcKQWHMnGXEc",
		@"sSsCAfNozLlHsWCpdLqcdRfJSUEWDnAcNxmzRDbOIEqMNFcVSaBhaQORozaecGGtePwPDmPNrMOcivVeUUtVOjfiuLpYTuRKunSLLmxfxoWZAMXoXJNAH",
		@"PnTzDEEeOLGewKzEGeVlZXyZNWGHvmkrIzJRILGwkEYWKXmVFNBGEJzWDMyYhOjMKeaFlfdwHKdmDYoOIltiZqbukeZTptcuLOSIAhiKqklkxTTyuoX",
		@"JlxqgwohrDjkHfDFGYCrKtcjxigNpTncNRhjrscRcCGKGvpTIQtgmaOcgHeYVYyzopyVnJNYOStqJSAbVLbngDirvlTUTqnvexMYSlOzgNZtsLvNDajJmyUwXaqPWdoXbFeYxYmJRUY",
		@"QActaKoBXgryPSSLiyxzqFJYHMXHwwzmEGsuJIpeVLUZhKmxzHNdKeEnaPLTnIiXyUkTWClgvqLDxkvYYnZNhWEDafAsmHApTJQsSoGZZFDQJdwRNVNDXegmNjNrrKiaCcsUPqszrv",
		@"PcqDhFkMluRzTrzptnglzFEYvEsfOmDpUxRtSFMQzpretccasSHUEBSNVApkrqypeNACgvZCRovAxysBEZQuqPPwtnlixrSSbTLbYjR",
		@"sWzLuHtdDFQhhsSmBbYLhSOyztcFuaqDtsGjiHhMcnPvQnajDSLWNpEqXukMgpFwozKvtOnIiKGMSzPprSZPKDkQfiOvWVLlseMJQLQWpuOprUPpEkWtFFZHpjtWvAraDuctSfBZdMlVIZxEQ",
	];
	return xwujxIvPygTF;
}

- (nonnull NSArray *)QCiXvwpYuWkMWlH :(nonnull UIImage *)MiBRISQIcw :(nonnull UIImage *)NmbNLAuXZlQcedBi :(nonnull UIImage *)gknRDaDIILvhFwfdey {
	NSArray *mRkruouamhqno = @[
		@"RYkZMATMprItSxShchjliUJSBCeBDyoqWgVPCdBOfzJoOGMkRmWEawFIHbTRCUxgcBvorbovfZdzpLITtIVyOWrSnfkZmKlvwNcYFqfdELSAOuiTYAlTTgPlZyRnr",
		@"tdnVMRGWjqguAAoyJCbfrxPyBYIvuTjLKkMADkXBxOpbtkVbkfjXGTBumRkaZEVKTfCPpHtkmIsLUuyLNUpGfNIGATzEbMBGUcCNgiXcgyYROaZGEtisFbVSaiArlCwzO",
		@"dPgBcaXxiqhpVtLANKczDmaavBWXyYWpXzYkhkiwaKqoBpFHIvbKlatBvFDnLxCDBqVrjwbLduzpgfxsGGAmnqVYtedmfaIgbEjbLhuhuTEJZVpwsMPCFgdFClHJgoNGlLyibmUULUcWKV",
		@"xpYMUfoOgHqfONiXQPBBcZMeGWJcgrggDfvJlwDhGPTStfsCsAQDSPmoNFrfAuGGJhxijCyzPLUTZTuDYxPiLzRmctGlSLVdhAcSLeNZtRrLSStTXriwJWEkALnbkYKDZOmyKbEdRCL",
		@"fgaXuQuLbstCrQIccthyMUJvGWiLFPYzOInfFwPvehbzIDsFkQnWAxoZFZNaBbuGlITgzGcXaowqexvRtvmHaBupGblSqavIqJELaLERXglkbGhRmuekYqKuKUcpocnauB",
		@"nWyzcaUXfPRBnCwEKRHHQcjDnpAQgRWmcfpweontwjeJdGqNgSvuADzLpVDlKzNOkZUEOYGIVsEyJJbqDWtVXCLWHQEOjiFSMXJgSpicgLeQM",
		@"AtSOQQLeCALKQSPFoQCkLAPXaXsmyVqqOdcfJGGalrROqPlFajqecYXbScNRADgBCkbNvEQZhtsqwYwGKerDLkyEupDtHtlcAdzBrUqciTCNVICmpKRbDVuOwUbFcdYFYtcdSsosgOAjtaNGG",
		@"WgcsbXiXVGbfOmhYIFlKrHxszdaWalWcnsKHuShBORvKZCykuVSEfZrpgWfCZXMFqeDTCtcFtmixpmyMJlQTUjwQVaMSCzsUdqVjGjzqcnGyNfnyUSUimRJTXyThBliBjEeEkOeYpW",
		@"gBbwPwMgAKHaxbaIPkDfZabSMSlcbBeZzgBMNiXWLKafFWdSlWJijGevwilHgnsSJzNhrkYJODXKFjFnrVsAmjcmflbhEqdTxZZjLXoCbozzkdtEvPNhezJubPtugjgyeNWaUN",
		@"pgkSPyMTjEQEGMKyaERRrqVnIJLpIykpJPbOHLIghPSPWPWdYtWwCPQvVISxVfgyljmPfdFhtRHNMTophNSbnLjPXdropLtDttVYBExvNIMjtIPIennjZHkNLCoFC",
		@"JuVtwJalVWPbAQCwoqcZIGrPQZjXYCMTMBZnvPUTEBsOYjshvTUQjimsRIdpoNyIVwPYkWINYJNJiqcYcfEoYyYIyCDEzydqosZjLQvFkPagWnqTdmpAyvOEKSRlXpJaXEjruOCwIFPeXcidJ",
		@"HusgQCMQZeQuyCEMBQqfkouRwgVmqeeDDbhOPIqLayiEeVgWZNKKriWxlDuwvSfntuZMYuTBuXhEYZYZWuuQinnhRdbTRqwEUqBeQnqVxbmlSWvtUAdrtKBXZskW",
		@"QnicsCsoLMSFradvaSucEUhKNEDUcoXSQhlyiEzkEMAMBIdGhpkkUOWkghsTdHdxMgbZIeeAegVrOhNzatmbqGZbGLAdxwQoaemZtHkfIlqqEvnCZMkeB",
		@"jCyShfpoNyoJyXwCkGJNmNPEIKMVWPDlzvYjdxYgxuNWJJHjfHzCnHMZqyUykdRjEahglUIEciCrZeLLvyLHvNzuaEGCKtmayluzjPqkmQXHidmjxMwEcV",
		@"khyYXaVFLicqFAAwRHZQMsxURVwHGkXSYiyQPdnPGeyJFpkhXbiPGjTVoGYKCDXGmcxUPPKkmFuCmvJwldDIXmRMaNkfngzWoJxsPAGmFP",
		@"txQojOSqnJMYIzMDPANriZQGgvGSfrLQsPFEKZPETBqOuJNLswiEPpXLxoeLTIQpleciOXuEXhHfbPpEeKQsdwrCqelEWtqyXzikhnFTdmrWhrQmkcijdAdCFnRPZIscpmV",
		@"qRNkovilwLDfGlOGCTPjIZrQEREJqlqOISdRdIRxeriwKcCcXWiylcZubNEroYzRDLNasQHxxkIePFLocpHgenJaGPYeVoFMMjBOQOyiXfqDlxHfxhjRDMOQUF",
		@"wOzrzDImHdrxSNDQOrqcdPrBPWWryfLbDyffKyzoxepaZEHQSvsKhFuflYCucDDvGjGOmYRhMBGWmQtwoBXXrfoRhGEPiXzeBCwGyUmpdQzEmMtVIKFSNZTRcAAGXPNplLJLXXn",
	];
	return mRkruouamhqno;
}

+ (nonnull NSDictionary *)XhVTRUaanMZ :(nonnull NSDictionary *)MjmGdachTOzJct {
	NSDictionary *BspBHNHmMRpXiHXa = @{
		@"aJStgARdErULetw": @"xfAdBgrWgeHhgCfoYvsWQFjLICdcoVOOfyWdvLDAyrDChvpsbjJdKizEmuWHpiaqtMZlDFfPvqaoBpvlDYeBXorFvFTmGQzrZDpXkydLzcEtQPncrAKOC",
		@"zzMJVolVmFYatjNu": @"xxzLwPFFJAUaPcDJnxfltYrVvJcnbfvbuJWfzVOLOJKTvDwPZNSiIuGWJhHJZOmzbWEUZCqjRHgYxwXHzgNRKfXbEXRefgndORptTloPUpmacoxkgapWoXxvukEWzle",
		@"uOSABPfqullcH": @"ZYNSvoXQhxOCJtKIkwZmLrIBFHDXmExNPqRDCEHwvoCeCYnQwVMQMdkYoypmFzkvIcYaohhRnTcsQHbzusOgZQFtrifSaCdtJyDwjjTEtDAMGQZvhpPJztCzYdIMZNnSmCmhhaXZIJgIyceA",
		@"UPPbDGmJStv": @"JUTEMhGxqioQMqDtnVQCpePhIqOVfanHfwrDPWuJIqAViMSEOfxYcrXwFyIOZOUJwnyllybthaDVwRXImNRGlsjmwbGVuwxZWxSfzkTiFtdSakSgWyBnaqIldEDyzjHZuDoEKKKnmskwVPViFxjb",
		@"LDdJLISkqAdkK": @"gSkYmLJoEYjPOxwJkEKfRRlJWKEDcNDOICcOTTguvkdBOVfmmNpkvgdftPUsQqtnxEpBfrmkpuJgCABvGsojJMDqzpaLjmLhATOXaPnQvqL",
		@"bVmKsoOqKidUjyrXm": @"OjnpYVhVQTDjUXzTWRBamiGLQRmeDjAdJyZCQYOIfhOjoKwTuthsuUjWSBOKSIPfpMnPaGStNPHVxmRelgmrIzEyflqduMlzqFGA",
		@"GgkmNevDAsdYGyMU": @"clqrZIMGsMgnFWBxCLRsyOEXieWTnyxJYQnycjsIEdjplfqeRVoalvfykgzDbzKGRaXEZUZfYGHiuOZeAcvvHlMGnLGoUfhCWqNOjIpvKwdMygpMfWVwpQrjcDtbzSbbRG",
		@"oIrtMNDNOTwSfl": @"VGtbPxGLrUDggRzybgZEdCacIfKsojNLxOWUjEmqRWFNoxoSxoYGbinLOncYtCoRIRZpsdpeNHcaHiOrsPoCPtskaNZKRyLkrzdUrhbVfeZKGDdTiwbpqhwjyasEBOcoDeDz",
		@"aRUaWHHQjyzBnmd": @"EwZsxPoMVcdBhNgSOuMekrdpZYgjsrKjHePKnoBIFOVuLygdAfEyZCRsyqzqYnfvdggiNIjViPFHYaQuDEaTwECVvAcKoAnlUYFYKwkPmOJhXKoXepkpFGhoWciuyDrxTMteiOnLtq",
		@"FGzFZsZbcBkmTk": @"endSNYcKeesQdhrmOlRSDAwMImfggsTHpZQljDfIUlbOPbENBijipBUNYusjuUFMuxlsJvnjMPQXkovvOdJRHdLENscoEarMeRxUcrGjmWds",
		@"YbGGLyXokzHn": @"EkByYvGVeLUFKvKCaBgESpOqQlNKfEUnuCeTcWxYRzNzDrQsjwIKTLqbyKiAztgcvPfNvFdVEgEoqVYDMqfZVEqQaksIeWfoKqQIvJ",
		@"WdAuCZQoDkmEOHukm": @"wxLiLDTgVYzAMWcjiVNoAvCyDKMZoCFIohafNZOnyuynPnqhetCbkRwWZGHWwwtbZWgXISZbGfaYaLndOdpNpcTJYOlXZqYOZAIhMyrmeAl",
		@"VJKTvtjqTOFikotFxe": @"yichxNQWJtyKrXledCyEDpTmRULrBRgPqOKqliXBmtygpKpUpaOGjpgcmvcBNBtSTPRSYOpVHbEthkZpxNsyeywrPLFnKfAmffpDzIQkkfSrBre",
	};
	return BspBHNHmMRpXiHXa;
}

+ (nonnull UIImage *)uDVVvfWFAlmCPkKSdNc :(nonnull UIImage *)NfIGTwYktAIJvgGxlks {
	NSData *rUHWmYIbIWStoKjyQZF = [@"GdlmxAhdOXltUxiXGkMNjXjehMrZqkLeQTsAfUYxkepOYyJaIKHuNwESLKoFTCvwwUrURPPZfeKXKZtCYZeorkRyNiafxgIWRMuuArGhuvHSTfHGolZQpEVSFKQCPwevPXyajWwvDXfyfrOXHgHji" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *zprkNxQHnLBXVKDm = [UIImage imageWithData:rUHWmYIbIWStoKjyQZF];
	zprkNxQHnLBXVKDm = [UIImage imageNamed:@"thFuJBzzptWmwgkGyEHeNPjXWeSlUJPPoeYFHdDtjqLPwcEBowBOEibhYdPnQopsqqWsfBiiqUMuasCZcZhtUipVWbeXWBHQIolubodyzozSwxlhCnigCpnmaCZskYaeemxrjI"];
	return zprkNxQHnLBXVKDm;
}

- (nonnull UIImage *)dmzqqhUcfT :(nonnull NSDictionary *)ONxFVnVKKDfdSx :(nonnull NSDictionary *)dUrQzqimwACJmLkkA {
	NSData *HwGuwllmHVlMIEwCUJ = [@"BkfqBVyjZIqVbVxruTMPJNmnmHovOQwfgACkILWqjSkQaVBpXYhySKPGsgHTXVNooSvoiFFEiQYqZodbQqtIsaBEbpPWWOcCasaTuHoGRnYLzMpMndxhYuGIaQVGDIgkps" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *qEjaOkQKtnxmvQaWA = [UIImage imageWithData:HwGuwllmHVlMIEwCUJ];
	qEjaOkQKtnxmvQaWA = [UIImage imageNamed:@"wzwqyXinCJfDjDBOjOhslFrvuoGBgNdcXxEdtNnRuQWVkeMVRObrgdYvFiXwQyyjQmZihlYVNSNopjkOlFVfUAvqjcqfLxCcOtquFdgaRdqIZaEaFGAbt"];
	return qEjaOkQKtnxmvQaWA;
}

- (nonnull NSData *)RgLRNhNxbDuHhkL :(nonnull NSDictionary *)FQUNcvHBKpWlwx {
	NSData *GASAwPrdfvYozimH = [@"BCIDLAdJbFjWdNhQOiwFNlZpHlhPDTdTpjNEUzzFsidXquclYEngvdiFUjNlVSaZesqiXNUdkloviBsDggJnjSVRxrJBWsLWcQUOiqWvrpQOOjUdMMjCpaoOm" dataUsingEncoding:NSUTF8StringEncoding];
	return GASAwPrdfvYozimH;
}

- (nonnull NSDictionary *)vRfCjftICbcwatgaag :(nonnull NSData *)KZvbEwidiA :(nonnull UIImage *)PbwmwieaUPUW :(nonnull NSArray *)llsEzcxfhlyccCJJj {
	NSDictionary *YTKzXRAKkMchr = @{
		@"PqyRxzWmtRF": @"NNICvAmCASsBauXnpPEvrzKXOTxTMCvyMDonWmpIbQqbEPpAybPspOYThzQiigFtbPSpQLxiviVzOagrhYUYBjfOvuKjQPaxczyI",
		@"ApIKZnBZFlRIDgh": @"dMufjKvaFsrCEnaZUQEBWcqeIElXgZcmgxkjKBTRWyTaxSFLJUKHODIXrKwVoCyBRQFEdDEVvmwrRcXPeUmcJOZViVTnJzLtyZZpQnnjWYtlRPmPfaR",
		@"raGgpvGJznK": @"YuqKovYtUcQwudFIpfazfXCfGLWhmAwtrkQfFQqXyLKqDSkUuqflQTfFBNWrCZSBSOdtIRWOsGxaChaFSsnnloiBgrBILIRtGqeaZAnfrOmYxBu",
		@"EGjUNlTamdtTeJk": @"NFhEIBnkNIQZvexSEPICNWALHRrxlmngnPXgFEahsgtwdBTHHrWQFCEvEWmEWxyCFjJygfVEbUQxVoPWwRrkQUbBbeviEhAZBvutRSaHeesCIsQiBLrZxFUQwGoemmOVyRiEmEaUKxYkQBkcpoN",
		@"vTjxShiiESDFdkPrlN": @"zTHlklQmmIlAYlYUjTWqZhCSSgmbEWmNbWuEbbMJjjcphDUKYzRwLagYgHpxTUNkLGwmuBBswfKfciISnyuszQEmaevSVHrxlsoiOSPBHeLtSJxai",
		@"UCvhnRDrzNynPRadcF": @"svZDrrVdgvcXjFmLSiPaQFlNaLxcVnZheeKZDyyKbAmYCACHgTMIHKAPfVCXFBtSbgfwJfKLaxRImdasrPVTsSXPHXZHgnfeOVuqLaGJIvoaeXnRQfnUOENYSOtvSea",
		@"iXNQHCYMfWj": @"JQHqJSHVGczKxMCmrGViownnWXdzPFcRycrTRnUTcFlEUVaijObYoXZLQIDBpXwkhDserRxHBrdEmTLrPrcHGPasXjvONKHHnKGPDFdZKtlzhLryncdPkd",
		@"GIGzJikbccYnvpLOr": @"bHNTVqREJmTzFNMbNMnimKwUAcuAAhyBrpQuuxxCmgJVQkgLMJQVAEDSSIcRGmcHSufYzRajRFpsYklTyNzPXOPKfqZtobumQXPpngnfAOC",
		@"brAIvSXoPfvfheU": @"XfKtnbGamJUvvjiKVUnwTGsuCLQxDhOamtFzNzNyvrUngmZOCkETROULCrUcBzCMAPoYXHHGfIQLXGUessSYhiLtuDTJSPoALnVPKbTshmtndxQKHZtzIkyshXFhoLpgjZYv",
		@"EEunMNYPAGiV": @"WJKowaVLkNhHFqeExMhHjhHhcbfDjwWtHVKkEaeRPPDuRGDMwTxMVGdtOIMpzxCLsNTtPZxDQGyOKvXExEjeaRYYLPtwJCeKnyBFUkrhWx",
		@"RfDumLVzzEbiWYLZjWh": @"tNozngiDWwzdfURgvPrUHbvyUdQBmIohhBASsEdYEQAlStDZIhXNuNDxAsvnTWGPcKBnNLApGmyKVUmDWWTQNCAzuLvylscezSqlNGXdBEhJpCRaZVzSsNpyYaGExNOYwqzaQsWLLPfSnaZbXgw",
		@"sRHTlQSwZNJkIguNC": @"onoDErlMEDNwwKDjwOwMruviDEqtEBcrQbnMBeDVYrIUFiPyoZsZUEEXNdGtuNrPDflgTrohbuWSPlLDXyEJWsOfveTseOgncSzlOhucohnRquLUUMemiaAqReXlNzZgJy",
		@"omaehMgodMTXZFvcQ": @"gbJJlxqTkkoiuOQCRyGDXJLWiDDdzwBnOKaRXiSkBmaJZtTmiVltehISTFJrnevJWjuARmclUKlyIjrpHeKmwJrKBTgnIRqXKaYHGjIbpuwLayzvzwa",
		@"amQtSpvmJTcoKtXgkY": @"JdRahBQacOgGuQUOAqrqrSTGkiLFBRgFczUiqFEzUqMzIkNYAGgrJWLkVpgvOfNAZoFeHfYCLqpSelpmGedhDadZmrknACYjbSDKDOMRPcQRSURkWzYnkxzfi",
		@"sxFuxrFTkkwjgQSNiF": @"FrrKMTMKGJwBhmvqCZYBzktSEjXqWAsusWaltMndDgJVZmlLZtJevgBfYFEtTVlabcQnUufwTZvyRvsgRGKDnzbNnoepKBgMTUZY",
		@"jISjtgyojpWyj": @"BVocqirPQKoWXBHubdwlnMzpbHddsKactcvPEptMNUIJCYwSlWDwPkmNHzbvpuOEPnfetiMPlCroAnsLEJuwIHySkUaMUpGSWzZdjWvktXePktpuiMMWTyOfzszmIBIxCFgdIlrdZB",
		@"GSlGwOmlbilNWuCa": @"zhvcftQWCmBzAjigxXyJyjUmVLwshEdovQRegzkZmHqVuVRPJPXfTdmqvhMQQCiZmbnXtfoXiaiXeoWMrqgndkGgmncZwLvvpwJWFgtyNCYlFmqlrfHdhqRJsaOPRlBesEDGZafFLUpyqUmJhCnZU",
		@"CvEpQBIWOKFcQrVjdlu": @"ClgKPRCkkeImeMQrYbWfANYoZjztlACRXIccJPtfIpirgCzHiDcMAJNkCmWPgyniecDAoXkPuDHxVStFaCNqjLoEMvdbafatnjchZSpRRQsulWQvkEhahvHZpKGyEzkXAPDcjHbdYj",
	};
	return YTKzXRAKkMchr;
}

- (nonnull NSString *)ukCcqLHKCnCWWNwFfVM :(nonnull NSString *)MeJbyhTVvk :(nonnull NSString *)cVBqpEfImACiQcyb {
	NSString *OZSwGhFLWzhhE = @"wnNTdJXLoEDhkXquCXPnhzXqztlOuPpyVRIxLFDoXkZZBpTeVTrmbhTYjRhYSAAUqxPTSBDHhbFrcjWtZeLmSIwOgkDeQevoVabVYcaHJdThIvDKYLKHFkzveWYgWVaqbicHvnvY";
	return OZSwGhFLWzhhE;
}

+ (nonnull UIImage *)PCYlNvdeOuFt :(nonnull NSString *)HsAygbiBMKpG {
	NSData *FYqJkwmOFhXueQ = [@"gqrSVRGDEdmpDfoIosMcMeJTTmIMHjlgldWSinGKuBxVVAgqViynqnEKCeNIInQEyUPsMoOZJPsoKdraEoehjQXMcUkQdgsVowTPkaLlfpHQqxySUhZWWok" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *ofqkevPdkLNzYKmKI = [UIImage imageWithData:FYqJkwmOFhXueQ];
	ofqkevPdkLNzYKmKI = [UIImage imageNamed:@"HNHvMdtrTsatBhUNdknloiCLfxUySWPTDtBHgQDwjIZwoprcqsUWBEUGSCyLkPocHhrrhFPtBmBXEzPXmytnPImOEeVzWvzrjgYhcVbhBlIGVsNyUXTMMqBijQxBKWv"];
	return ofqkevPdkLNzYKmKI;
}

- (nonnull NSDictionary *)vBOGWqgLoi :(nonnull NSDictionary *)RsTZvadvyJunXIjFQx :(nonnull NSArray *)ZlWTeaDyMlyPOMeJi :(nonnull NSString *)bnFrBaZrHsIpNkqdGC {
	NSDictionary *FFZDByKUHdXFKQn = @{
		@"ecusPMnaVtyhV": @"xAWOtEOatKxeqnbwYVBSRpsqIyTMLsCITaJrzHpoipnczandCAgkMkQuNfaRAUvFNVMgXblsTpCkTFTtmXMQvPaWmxkDgWGpwAHDCfyEbDimynGGnjAwFbrBTFabpEFTSJEawCyqIyDFAeARafgGW",
		@"htWudCyStroA": @"YwbdYlqrxrYGWTXTeygwKEAgQHOEPgQjKheLzckHRZhrhBHEsWwYHXTAkbuWFYaxOUZJmcMvxGruKYlIntweqiTSitHImdjlABmGYgvfYMhDPJIomctxZQaLGOaFqVhPBjzOse",
		@"NLQVTZmhUShIrKchl": @"jQRcoybePDBNvDcjRiTVqnuGTyNHGkCFTmybsqDITpVJeYFOVrDOnlFUsEPTTYMLrNEogFcblMZblAciOJEBqCKhTuasBNeEqizE",
		@"QleWrjsVCirMPNKHU": @"mXfsWLLnleZiQDMBVPqIpdkSXvuYhZoQEgUMODiHYRGtVHKNSWBMRpnNWVfrkEyyzWbnkEihaiLeqbpWuJFkGKIWuSSQZmIFCQYYUfhkUCvOZGeSGufReZ",
		@"sqFDLrTsHKz": @"cjtzRgUqOumSnzdkftPMFczKedGyeCpVtRbRxnbeUgNHmRsgUEGXfsMyDQgFGfOeGgmBunNnJLxCqkPSzqJDtXubQFiVExMqSPooNirBYgEbfNGWHOSDgnFLAMgxUPngzTyc",
		@"UEdTrQqZCkEh": @"TdVWyRESeUIIkbGWqrigKWaOOBOMNtbVneTLkkDHzuhaDcxMPUPKdfAjFCVldneSDUCyWfeUFVQkZojwbVcfBBPGqSvXTXzJaJgUUQvGufeUakfOmTWBxEgggBoMNlfLMXZUDyTifgkr",
		@"znjgulBRAdVmmbjnmiu": @"ZeKLOBYgGrWAoTVeFQPpybyUmKzYUcGOzOSrqEqNoTyJyMjvOBZnYciXnsAAVlLpfjUEwVUwjbaBSwcACmNTugvmmECtnNFDMpNgYKbkwuKMfOhtxiMBP",
		@"fzuDHvYjoyJmJ": @"DRwEAQUfAqJysGNKUOHrjrSnwPPqFteIWGlThfwabGGkxVhPuEiGAuqQvhxqnEibiPfHsRARdRQHdjlMpJeyReaWeEMvKWtRBQJUDktshyBvMaY",
		@"EXIbwtHbeWOosUjU": @"UucymeyGXrMVmbqqqiPJZnosSTkMKojBtucuqKYsPBbfiuhQzfYWYHKIdcZxbXavCHZqIUspmvDCwKGtSWBTPaWZefQrlbfTyxQkbMfCRaANJGSTehZwciILPRhrXxNk",
		@"QutpjmzXPLYOXEq": @"uqhpwtFutKpXHRqxOIboguZgOWVHazbKLcnyBFEVSNjMCFSniqjnSOmcGZCRXNjtfYRMCyTKhXYeHgOkXIjckZdvGbUQtsskjvGktvHtGtaBilkCbUTpwrnNycferPDnh",
		@"JgDTGZqOJhzzXV": @"LCFqBJsaZzUBRpwaXHvJSUAUJJUXYYeBWfueDlIDRPAMvcHVpCcospDXVACmTGZIOAKDtjUfNfkXEnIROlxQFpzFdoCdCuJZwukHCSMwogNRyBtRWeAxdPaTeib",
		@"CkWGkNWZcRtqOgdrMHw": @"mTIpXSiAGqVEONKeBPVkDXNLbWlEKoKUGiYvMaanZmMFQDvPrQZMSgMpiRRsvkzXTiBXXSDeKqLVxVqYwiUkVnpOEyXbwSAbWkeXEuClll",
		@"gGqOuTqKAXLuf": @"ZCZHwMAOJEMdqEGrCMguxSOShGMRQwqKsGsWgpmWOcyKbwJGZDuVDTGxQIqiRitWeLcHvMzmtDAtCLejOwjaqKVtNnttCakvUXnrxXdBAAeqaIOPzIiyJezlRzuvBRxaAUKfu",
		@"jdmsdsSvQyGTEKHOegJ": @"fxtDXlrPtTqyIcYUqfSreAvcbCjqGHGyOhbDpdqMPVRexiGNSTLaivHYMGFdijRHHPhFmvJdeCpSlqOhKgePelwtkYukbZWtajukuIZPaCHKEVqxmwwlRAJuSqdKJlUjRpbeTalIwCffV",
		@"pLUsISjRJoag": @"hnUczXPZgIeLosXWaGVOheWtKaFVtXlqfvWOhQVNjMOBvYJtswzTYkcrJCsnfBIwvfxWpLhalOkYfadIXwywBZccTcoClmpImbBpav",
		@"yBNKFvhrixWeGL": @"bjjhalnbUSqFAxxJSJhGyLxMgDiKMCdmbrykPOsOQkYGIpknwtMDQMWiuYtJPJLoJDOpZtkFDxLNgjdcFyOUGVMxYEChQCEiJMQijybrGvgZXOxZwLspWRcruAFcVpbmxn",
		@"DpFtCTzrqCVUObmyvJr": @"PqaoZLIcoKpKkvbhzJLFTwPYKwHMTAjMQLpqAnOXESWVzJxDAVBcUlhhESiHozuJbiStvPixTDZArxquZkvPfGISaUByikBWhUCXAriOwRxNtWAfsbLQbuC",
	};
	return FFZDByKUHdXFKQn;
}

- (nonnull NSString *)bWrfsmmzLGEIzohnrmz :(nonnull NSData *)jwnnPPGptE {
	NSString *GWBfWuQZLddYhsyb = @"itDWxSJFfnEvTatDUscpBkpjlshUybzDUYDGhTnUewXFOTmgvfOFSOcdcWnTgwBEOdlXqfelYpQkQXxOlIyHQmJIvtoONvaLDOabZhrgakZfoCqAcr";
	return GWBfWuQZLddYhsyb;
}

- (nonnull NSString *)poZoMUfNKnoRYoId :(nonnull NSData *)hGTvdhFmGfAZgNyC :(nonnull NSString *)SpVOcEtfUc :(nonnull NSString *)LABSLtAKAPLO {
	NSString *OSuEgTERvkaPt = @"sPilcINZTXXYvGkmSbiashMyJNZqpZOpHlSpXucLTkJzDTvuBlGgfGTGveJhZVQqeVlMChtXllOjZCXdViCqCEzKZWwEcgAXiHoCYvzaESbwdehsKORN";
	return OSuEgTERvkaPt;
}

+ (nonnull NSArray *)uYOMxFwziM :(nonnull NSData *)LlnNqWAfzYm {
	NSArray *LmWKHPyAIs = @[
		@"miKioFdEtvTMccBWIBfKYhwtBztVvNmIiwpUpUgvHykNAYtrCxJOhNeEngDYWWhIaZQQhOSBSeRvQdnbxLkkINFMJdQaELSVVpjzJvxAHMFfOCVVbdLmSQEYcppMXldzbc",
		@"qZuQVOKkRhxoZlRChdDvqksCePafKINKxTIMBaJjnuZTwqyPbXoDZLmpmpBtwRbnOpnehrFNmnQJKRFqTOcQjXMCztSUYgsSXpZcvexGbUsayavsUxpQEiNJfN",
		@"cTQLhqmwqtOhKTAFeJNYTjYJdXyOcQjYCNaVENLLmbVKSScxYUYlLiavFhjGhLBjiOMWdGGoYBXCqpZnKDXyAeYmgqwoMlsjtcSeUMeAjBmtwZMTVfDJzMGBHlOwEZPutaxABAHWrTKSilCBANPQ",
		@"KAHOtmtCdPjeGFopDBTtOCRFHhpzDDOOpEsuBjxqUogJhHHEwoWzHZfeTrUYBHgEcCYJIKqUJuOdqdLnHhpUSPWGprQjMnENVJnAFFgyM",
		@"rzUwxbIMdHiUVSMKKkILnjcVUbhCuNkZvQhCvBbWlcbSpHkZTmeVtkaCPiQsVQDWapPZyDdqAdtkJogMXMfxFmOLKWKDkRYaPGKcOELeRCKVApuQcCxmDgrAJnHihI",
		@"WdjuixYDlTOokVHwWcRYBFXvdmakveeihnkFXPDcQmeIZceRstifhsTOXhcYlxmvnngDGxqIEnJoscnxqmjIfRTtLoTyWsCftVceIoHKojVsucpoL",
		@"lyBFTiBxBqZuFXbyaCoRgQbAZdmGwRklKGEgNCRiVilxHzUIEawBQukJrYMyXowqnvBNRWsinFTareVqpELNYtEBPEWdFNYOfuZmrYwIWkZAauNNheizXDRdynISKXnnIcyTsZb",
		@"UsQzOgzBWvopdbmitykXxHnKskNcQYukTSKjFGEzRvlpNJxEMWusUceLSFyKDXgLcITvgTobmgiSTPiXxSXFFnjcakaolQJBXnKiVRsliAcCtUeqjbIDvaIrcvkeWZsvohdkVKmfjnEKBvzo",
		@"KSOyYdxnokblBowsaBqdkUsPUswTcKuJjWOzGeFXVTByQXHJUADUHHYqNOpiNEKphTcxTLsIerLAunFXocsJxStpXyOvnmBHmZTkjaZuUFWGifJAUtFJOKattKOETlByrBZ",
		@"jrnUjAJZgaGqfRjbWocHpDbGRUqAeRNBzHbxgAQingIYaytRlQuvuXXyTboPMnBkxnlrYetnndRSkKdpZoSIjkBlqMOLXiRpytVhvHIxaPVrMDOBJoQWeuqunsovhAzHfuhTRjXEqtl",
		@"IwplKxxMmosDHcDtQMNxihfXHZSUElinVLpnFwzQuHdAEEFbDSdHtgTvLIDuWTfdwFYSLLQAvphgXdnbEaxpRroslNgBVMLaFJflDbiLAPryGlFHwVyXiWCfhvMEchouXhLOhZOtDfcbijZvSSA",
		@"kWnEUSnBDgOEIqrjHgJtKonrzePKsVehbcnrcyVQIPUZFxqDQiHrePAXlLxhNoKpVDLnMpGIMxPXWblQnRwPtIChCOdjZnApRjFdZeGDEGnwoLacZzFMKYmjGrUqSBXmhNHFSzOmmZL",
		@"mqQugJjzxtUqQnuiyfJkgJAVmstBasXpPVieJpmOMyiKcjuUQFdTmQEIybVkuCzqyhFdXMsBVCZZneNdpvJNOTcPmDAIiaGunOAQvfR",
		@"IIwVdPxuFDlRLYZquzodkmmNToGTvUbqFSZQvsvYnDEjdoGbIdHamcUPiNqiQjGzaxHGeykgWxKBXhLdAvVRmNrCrbySRotAqQVYeEnfdZCZvdwmRpuRRvHAsPtfncLmaLAMOuulEO",
		@"gnSbGfCYEaXHPtjOKRqSovVKxqyKVGudiOgiUBrlGeLHsvOgKQuSEYhaDNhBGxVFCDnhGRHPfeCQFRsbwtbfOGxLeoNtNfxvXImjAdilvqqJgYNuHKXQyrHMhVXemVcuFgROCAmCcZedD",
		@"fUnFwSdsyOytjzrDNWGDMHGncztTnFYKNFPzJGdeBOAGBwQNwPNmCwlTweOWBTEaAfrPzolBiUyuLAzGrtRMwwRJktOfAGXNCWUaJeMgYFvbRfmyaDouJLkbZllHDmQmprlzfFAyRssoENbeer",
		@"NWRuKjCMlUIjZwagYUKVnxwrFgZrPjmTSEHylQolTXqdbugmacMjFPmRqSGqyixVuZSYaLMIqYGgiuGtQvlICyKSRgRqMnjujooLixDv",
		@"NteAixFvxciJFZRrRMcwsljWlWfRDRiihCJjxksClJlpoMuiCjAAfCuTcrIHUCBSxpHjNdhJsuTcpFKksnWnzgJfsBfqLJoFKcHuwQsIyZtGdTLsArdJy",
		@"sVcPixIXmocSUcYlDKUiCmSgBYnDeMpqVKnegzcsBeAytUFLFBYFPWdrxwvYGmhTHQWVBzQPiHAigbcRCgQFNekckEYFoKrWFJzKPnOwYDLxSNqIKNnOTiPV",
	];
	return LmWKHPyAIs;
}

+ (nonnull NSData *)VjwRdzGwDyvGf :(nonnull NSString *)LXtNbHNzTLicyjvsoUj :(nonnull NSDictionary *)xZVnInCBQM {
	NSData *rqQIhcHLfpsuhW = [@"DIFMKlELTonHOUHmLhOtgtTYhnsahmFRcSrFxwgZUQlLqViBVYVLwkSoaFzVmpVigaiCyAmiVTVRxtHKDRIZoxzOeUGUXDluIlTFNjdsYwhfWlWeMhlvniqmAcOVZUeG" dataUsingEncoding:NSUTF8StringEncoding];
	return rqQIhcHLfpsuhW;
}

- (nonnull NSData *)QsBCcHBWIHrm :(nonnull NSDictionary *)KSAPjLdqbhK {
	NSData *zKxCrmVzeDQGyk = [@"WZIzfBlOTmgCWYuFDkiAkZDxudBVZbroYuhHutiKnoRyDaqJDoBunlFwCBhFaoSjQHNIbfWLtPyelradjvzYNoXrOnokIhZkwQsphJurotVrNTVxBSvhspyytXVlSLPXFddtMlMQXvIGYLCFOb" dataUsingEncoding:NSUTF8StringEncoding];
	return zKxCrmVzeDQGyk;
}

- (nonnull NSString *)LUdKqdxDdfzC :(nonnull NSArray *)JrswDhGfoEXYpX :(nonnull NSString *)ElwUezkfGbinVb {
	NSString *kGDriUNaOMaabebbbWA = @"nsMzZQyIKqMqPFJCyiCyTrSUVTltajBdvTGpNJBuQqRUaxeAdjJLOkxSNLaeCqHYyJoAHhtiYCRQPhjpqKFlKEOrHNPbVOpdwRmddJcRHzxQDjehFdpRyyZJaLEJlUTMlbBDdYObWQuxJ";
	return kGDriUNaOMaabebbbWA;
}

+ (nonnull UIImage *)SrsIqZOjWJlUdHW :(nonnull NSDictionary *)uXAeSzlZBDIIEQeVIW :(nonnull NSData *)LELIgHIgQo :(nonnull NSArray *)WaiVPypADbm {
	NSData *chkufYBckAMqMLuXBXZ = [@"rmuuGmUSnhnioXyHLymYBcHUCMexzsdQzkubPCWEaTenHGZzpwxGeBFooQdjLlwfzjWAsEiJwzdpgiTUaQmlHRSXgoAietxPYhJDRdXPfTJQQGVWfwgpqnQGUdhE" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *WfkjNqGlPUMpMa = [UIImage imageWithData:chkufYBckAMqMLuXBXZ];
	WfkjNqGlPUMpMa = [UIImage imageNamed:@"AlbFvTULuQCfQrWwdxYXSTXUiSnjmHugvARbuOUWSNOYbpwNnzKePsOYmmvkIfYJrYMpkbzgEvBaTELbHbPKHINbpktolShoMkejidyhlqFGNNnXKZZtfZCRWvFrB"];
	return WfkjNqGlPUMpMa;
}

+ (nonnull NSArray *)abPRukatAELStCphmBu :(nonnull NSData *)WeshDgoGxBmKPVa {
	NSArray *dIGSavvgRpEcAlxv = @[
		@"jXKvtqoqCYFJFPxHUrnxQnBpeZUNSESRpNTqYQTaDCKGRGlaRnULLjPgYUComhBcaYgnHJHjxOCTDJGKsyCdPXUZvHXXOQLrBJBmtJtNKBSo",
		@"DYXzKpvGwIADxaJfQbsUUEPQfWFvqbGIYPOOJQypCgACBDGZEFmDwrbpUGcKBajKQooQPZbANptdJqWQtYoZiULldaGmsyxzHEVTeOj",
		@"HkRsyvNjQbeWSfApIEavirrrRdLtegilzLPDCcDOYxHkxzRbOzBXmoeoSjcMxRtUjopEBtMLBBJqWoepXKaEoUHnrFlKCDPSxWstrFknBeTqmCAEbXeWkiVFnslsGmgOKRHo",
		@"GscqugYBQESiGAfNRMSZQXzLlzyNkeKRLMtyTyFhOCeUigxXsmLeepHrYHgXaRHdQZdBIquVQiJzlQnTbinEiWAlaUNIxtbLcpqqPbmBpgQIxURmVejpGnKEgweahQfKIzi",
		@"FuOlodyrqVVHgfGjDknuTgAkgFRuQmwBUGVAZIfXBrSQXVHGnakrpSEfQXMatqMkCPrpHgANcfbIDdLVNDyXXBSZLPrLEEcZQVvkjxsHXJZM",
		@"FoYebwjRyOvbvJKbEVKPzRfdmNieqEZrFCIiCsuREVURnHAFnsyIqdVDxMctagttwRxQxStPLKJdPjUyihYCPEafGeCZLKIdNmAqMCcgXZoWeeRNgmvyCasBzDBcjeowYL",
		@"IbcrQrzCAiGsisOpSOmdaBifhDfilBDRnOSrTrjjXYcsEXNuLkucdnhizXybdNQTUXlUtcMplwazKUOZhOFVIptzcQDaoSOqFovtExjzlAlFofPYlKRpKToUVtNyb",
		@"dqWobmYfTIEWaFrBJSkwFuTypXqDHLufyFVjOVOSTWkXHZGJAaUtLdzSkbWORbsWqsuHgYLggqAXzKAXqNXflWATOBjSYeBrgbFVWzSltVukkGsCIqZizMPfsTrTORdCTIoWWFXGuDLKlWDID",
		@"rPMTdoEeMgnyiXhDTXKuNVIkZkskuufvoCASXkpDJwIqnygKoupiTiizsXxdiGnNRGYYnAKsUrNYAQBXKstymAsjcRmTpspxgndOcAGoUqnOabLmYJlmURfynCCdYsULYgVll",
		@"fAOsnSMTuNDsAKWSTToESvKYSvpHdTqGcGzBAOlULYGtNilzVjdlfNCOxhdUkKVUXwXAJponHltMRqoiOMpqSpBJBJfvsEZhFqdfrOWqHavUXlxngZPlsrzGx",
		@"BklZvMqCMSNwBqnzkYbCnHzxolcCxmbhCOWSJHGNsDgQaGmfnsLmTywaQhuwxmZmYZAQEvuJAeJRDanRPAGtTvZaNlymXsWEJepMNQOcHGpsgXOxzNyurBmmfYBzYtXsXCuTCzED",
	];
	return dIGSavvgRpEcAlxv;
}

- (nonnull NSDictionary *)RdmIEECfBiMyQmS :(nonnull UIImage *)lLcrIxzVXfqw {
	NSDictionary *xpwANQWacCOMFdO = @{
		@"fhPtZOkqVyhpO": @"cmBsGahJCupNwKIsnKDvuDWgMRwIvfdgYrTesTcxCNdeWSuYpCKZqbZIKMaLBMdqiHQUFyfHilFeEmUQaxhkbYlEJMtIwuDJwOvDcQBgCcOCjvOnjWDcvDTFjo",
		@"cbPBcqMxdk": @"kDcagmIRolshqWvPsMREInUSlgSaMvldRpoXNWvalLTiRdnHMAXQFGUCwDMFnctyMParVDAczYESJsypZdNSkrFNExcHxyXwbqEyDBOwd",
		@"twfLlgPVtJdTpFui": @"VBYTxTwDFeIytMTWkfYIvNMGcoGlemDXmeoTOghwaGPPJFbeOfsRtDwnYZdLkIclgkuiImBRDNBhaegrHeEiJQgNXAMiEYyHdQilxvLidGOmImLaJbRLwcPbQrTAMhUsunqYdjuUXshMCAatZ",
		@"eWJQswIaxA": @"oYcpSuRTWshuSwzeBsQlernYdcqvTYPOvBpGFLPFbfHToFnWxzzmmnaHedqSnweZfprmGbAkEMcmhSKpYntwQFjxrygOisSEovZPcBGIEVjTr",
		@"uyVtinzwUSaQa": @"DRfUTzdbUCkPayAKhOXIBroXWwCMjdpHlDdbmkBFTVKRXyXuqscNWzWstmrDUspNWtglqcvThnEXuNGGDQfkZpBqmbAZHHgoEYkEGUlRxlxltVYtgCCKOKPNfrQzwOsMNC",
		@"bIGAJGhUXAD": @"QIDsPmLhYaAkbeboenAfzHeEXOOmiATycPCeOZNhNTMshHRHgQGRzDQFrRUehuFoPyLuxholQYCbQhVSaAeCmwVnqJkPPAPltorPdvaWOoGpPgIGNkFDYKxaOspqfxDB",
		@"CgHqCFeIabplozY": @"lOFxWILhcOTYUjTLvfvNoTMhVUnuLwzeMWKvKygtuSpDsVDClirUkIjAArduCEdAyxaFfYxufydsIzRPWrrklXJWVAUgGeIyyXtZhbbpEUsQA",
		@"bGsiVuQqLpPLpmhNvHj": @"WrLIHngRBSXOmoyPHgmCDjNkmAEnjmGJdAzlbTBAdjTYCgTrEYVBlEtNBewYQlDLMmeHJRryRqJbXWFoeJIGLVWwdKWvKeHWgAmPXWdEvLAvgvMBOAtqQcuyyXvEU",
		@"OnEIPYUCjUIEDmULDd": @"HivrfYxRgqFzJopnWvfaqoxLUwSFjLDbhMQuaBpKxGbsAWOTrXkMYmzcpoDxRUfbHynCPeeGJzDnPkuqOLohsOKnKzLnAsDnyLSTSmThIcOySKySKsphhYXkOkazWVkiPsqsfEclkHntXZVN",
		@"IDexIvUxBHDgGXgSLKW": @"CDZAVZapWjvzZIYTIcEBvktUOkDdryYZvndRmOOqzyPtrDcoAXcsYnTnwMtOXptBaKOELdBUULnUDzZUOKBFXiORlUpeVIDVZfcApCbpAFAzBtwdFSFGMPwNCklcSgH",
		@"zkkzGxknWhdSyOZgPmb": @"PwfcjXTBrkPZoblrBJkKPYtKAmYmUVZSXseatPurEpBCZJrbcXVaKLYTIAjjWVvUHMsoiJomIzcokIYehBhnPDJCpIeAOvaDAJIsjOAtTcnMmJhOJYOHEhSAcpCkhxvgiPEtTM",
		@"IHnBIldeLyCctsSBvgz": @"tpDJBrocnyuerUEiZiuBFIPyqASYAGzeqTaHmgSaHLQJWZjtxMsJJIUHCrYoCkXcGfaXbNISKCLlqWZQYCzhPOBCRHUYCbEQbpYQfeBalqXghkjQzEaaCyHEmeqsQ",
	};
	return xpwANQWacCOMFdO;
}

+ (nonnull NSDictionary *)VSubrPJJcNfrITiow :(nonnull NSArray *)xNPqboKORznjFHqhaK :(nonnull NSData *)DpTlRHOAqgddQnkv {
	NSDictionary *iDYfexsgLk = @{
		@"QhEGAfuawgmptOx": @"USDSTcDoVpyVDbFPeZvXOAvXKLjCXmzohWEClCdZdSbiqJbxlncuirttqTQtOyAkxRmxghhzkpXnlEVSkYqqGeHCTRbqKOopDAvapaOqyDVZKGOfmvpbwLUlTxHJVriYkcGSlxWIGNqiULsC",
		@"trQjVXYQKfIMSKmfsIi": @"yVdBagbXrelYjelMNlSSEQfcYBhZbWldWZjwQnGsBQnvCFQWkblyhabIVChwgWOgeqmrPDNnBxKcGVIypvuAHRtNRyvSPRImKmonEsIqgreBBnHpbGesfc",
		@"rykzXgYAnwxxMyYAQ": @"mtEgKeesKOVnyzpTVKzFmSWLfMVKaaAzxfuDthLiNpLSebWCOnvOHZyeRFKZAIkmEMsNlmboCzXDLXxbxKhjZKqRPDdwEtJZDVmNeAomOGAyMLuDPZfexUVEgeWlPlnpFpdZksz",
		@"NvgnXiyORCJ": @"agFFsFOvKJBlqpOVINNJExYBXMOigLGPKgFQkyMouNiqkNtnqryvuzcuxhMKfBGckcaEMWBtbcNeJcoDPMrZaBPpFRQlOuYdxvuFHlCGjIdgPpdoBHFVzxaZXBSRMZBliOIEiaO",
		@"snwRkcjzNgSZAiU": @"KTmwyvPsBhAlvapLgQCvnnMveAHczcVxakCbVOxJqkGJcySCjXqxqhFBdEVgVRWnQRgjyvfCAlzmLQrDpNMNkffogRhZGOEisFNqwNwQcrwGoRfWrSdtbDncxndJRMJMhNrzPWuQ",
		@"vwkWYgeHUYtpCQNgL": @"NDdePXfbTlcbzqFvySbfawQXmSWPLWaFUoSjmverpdrhtUbDleWVChulbIHhrvBIwwCjiATDxYIIPRkCDvakDjFhxPtXTwyUVzkYCBHwWxPYDSyAEQUNPaLHOmGeQkDBLkVMTggTjnmYEfM",
		@"qKRxZEhMxKxymdVubc": @"zZgndNrgDOJUxHUozIoXLJAbVeiNIycInNWgHdGOicbbxcIUPPWdxzoLXPYVoQgygXupUlpZNhYLnDKAJXlwMMFZsnJbZcFGmermVtUwxIpMULNRueZoygoGmLQWekhbyQWufvFRJeMrNypLdCzSw",
		@"StuyJRPaLXnGEB": @"AxDrqnLzulFeYWOTtDpCYeiEoveeMQJdEVGAbaVPTZtcGQiqFHxcYPsAfTWtMOwbpjgBmDMParryQunRlDhZSZYcHVfBVpbCJLIrtD",
		@"ZbmkrUjZWQF": @"qDWvxQmCGNabuCRGSCVMngbbwJrNdoiiYUpvrvpvUjoKpEeYoKANiQNPfZOwWDGgUZczYDLcjDeHJNHWRifqtVPGtGEkMTMRQwWEiMwcWI",
		@"pTSeHMyULihrKlQCuH": @"pCLvrzJjJRCsoqWaKHuSdokaKuBDpqbcASMOzdZjuLwNasIbIFsSjupttWtzUJrnDKKwsMsshixDkwGwumYHLqLurcaCrdooejusxZaYpVvS",
		@"JmOpxqKwXDjNK": @"YeyVokfxvjrHOaEpzQHlOXAFFyreZaqFQAXiNTnCMqKNWBBMNHeMWNOzPxqWVGYjMoVgvRRCabTRpupbCzBsbLTsoMjUZztBYJTDAsKTz",
		@"QEfmzINaxt": @"ghoMhTfvqfbHADTTrGAJbvnApXqcGyjsWJeUpubxCDhHCyXKMBSxcgizilrAgNRkldJEbxCxaCJgPAItaEfLnlMOTpEWacCLzQosWVmJXUBQnSCCa",
		@"XtSTAMCPebEcUxwzuql": @"omBUtyXoAsUSQafMjctYXyBdKUvwEyvygBkTohufVLRmUVHlMKZdcMUWKuvUkRSyupZwGvSkIjaxHOFldRZzjxPpQoSDhKAiLfdkFDhcJJlJauMEihkfRrUmblusiSoIsQmVidYshcNClG",
		@"iroGsBTVUpor": @"JwDuPtYzhniDVUxeTWuQFXDhFjCYxrSpITgpaQXPmUfcLvBFgttsfaWVhZONIlaaoBThgUiZnagWWnSYmlzNDbzmQRqRQpBBTUzpYr",
		@"csdyOTFOIT": @"eNNgZaCTLIOxpEZfjyLSufWRabbwqrclqoPyOkBAyYeylyZLVWbVoXJXfSIbsYGntPRgmXNHXrCPxFLXMTLXkKBrNWOCPiQPWLpuz",
		@"HMKSKhVrxmhMkuCOWU": @"oLckUDXcByJDtAbijdcGeYOFSxSESKPXPclrpMOBMVbUcwmVgZRQxdPNuSakXigYTcGFSTyStdkJWClounxXjGxqlaNWVujemXsojWSNbpUdolbIpRcOpglgdH",
		@"vyTVBUvdkYuUf": @"DxZGPSGWuyisadKTdkSsoMxPNbsjFVLjkLWzDtQYVYhKLbbDsYtLWnTaThukiNBfYhBJrEJLRGIAlKOHigNYKUVdxZDYQkOTRMdQeWupTnJBNodRjkrfprL",
		@"VVoBGpeWPoDxWT": @"xwrFtWcBCamWqzDnkQUSpJyDJcrtYBWlsQLJsMfAkpKExzLdKAUxuRTEZRVTitmRoUknKPxwlvzyKMdcpAxLJhaCeJeaWFoLPotoPnyDaUk",
	};
	return iDYfexsgLk;
}

- (nonnull NSData *)rEqToTQNaWfrOc :(nonnull NSData *)lXOkMPxvDprty {
	NSData *vznmKARfoAv = [@"GdCqNCjdztGrxHMATtLcxuQMfFjWpSbVFkNyuQhCFGQSojJkkVevoKfKcLbNkjktlvCHxmiEexNQGNuxcrHIkrMntxSAEEhMMBObHsfZtpICVERyviNYsqBRGKfciMJSUColJyoBU" dataUsingEncoding:NSUTF8StringEncoding];
	return vznmKARfoAv;
}

- (nonnull NSString *)zwSpRmFoCIcV :(nonnull UIImage *)gTkubAdrPCeMOOdjqki :(nonnull NSArray *)unsiQpVmSal {
	NSString *NllfwdNdSibIsoP = @"ZNvvjPTLEJdXkATakSJaIeOoCQqIEnOPjbblpMyMcAkgUirLpUhSsIEHYHBAblsIEDOFEWUyqNXrXnkFziQDJPKXcRxTtAUWOJDcdCHCUujlwGtg";
	return NllfwdNdSibIsoP;
}

+ (nonnull NSData *)qwchTnjRjkN :(nonnull NSDictionary *)lBVoCLEYSTxqhbdCJ :(nonnull NSArray *)vYLCRZHopUsKqWhsB {
	NSData *PQiFqTwlTiKlBERe = [@"hxUAJPuLrzhNaHYbOOfsltNIsAnTUzuQjkMZKHvZcMVChNPsdMhrykzjuqadvRDbCfCjkYWyIFZPWwCSGvBkbRzHlfgfkhlobfpMSVOYLQPHmqldNlwUyedaFSDVCIMlKv" dataUsingEncoding:NSUTF8StringEncoding];
	return PQiFqTwlTiKlBERe;
}

+ (nonnull NSData *)kNYnaQCESeHR :(nonnull NSData *)ZkgmluEvCampGgUHzz :(nonnull NSArray *)JonhzwGViainq :(nonnull UIImage *)kHBYvNSicrdDWniMTh {
	NSData *vzXCxMELPvRvQ = [@"bGQgAVDXpEbOGCjrpyGJPhbCvOafjCemjgwYiNAnmJGtDCgMoookJNSseDFtygSwtpPyUSsLVmoMXEzHETssHeSYGErfgmKuUUlFdOFnxaooPtMtdNgdkcY" dataUsingEncoding:NSUTF8StringEncoding];
	return vzXCxMELPvRvQ;
}

- (nonnull NSArray *)DicWFHbqKFztqe :(nonnull NSString *)kUxAJoDMKxtH :(nonnull UIImage *)LlBoCnUqXhniNIqOX :(nonnull NSString *)ThHoAbBndoKqBQOC {
	NSArray *ZvXrIHGFqBy = @[
		@"jNIzEwKifDgpZQaUjUrOcOZgeRZCYnVWBYzfqNwAQAhmmzILQYwdQDQyadZcGXSQRMgpHXZzqCsYTXcMbeGAhaRgjiAimVKshEsvCKNSdpFLGiRkDCULwGHbCKFukUCiinqYAHwOmFOIM",
		@"XQutYTKyDlWYumncyLlUaUviwNGFxmyzrnddoxqABEjquhrFmbCnkJxhHJmvucjhSFmhnAqugSTlLECGLcKJvJoGsusgdFMnHREkhtQvdVAQGiMpp",
		@"sqJpxUOMVdcYhLqLaOAIWOnpMGUZeXvnijRgeesrYPNxouUijczbMMmNswHyzfFqEZVbNrCRLlNrCCpwqTfNQHtBeWCPkWppmqMVPqqMjplhjAXqpHYiwOTzHjpTTAsevGAWyfPHbryvpZVnMq",
		@"ikFtnCHLmIvyYHHIBqNSrfByHYBDmwZRHyfrFazzriCSphqoTqmvgaRfxpjMzOOfGpMQPbxtxKNHrVaPPKjdrLwZggiHVPziTqNTgJRDWOFpZSTbjnLfagNRhRZLimYVgbrlLInNVKYJarfPoPjmk",
		@"omznrAHBdQgEamLLyECVBqRrSrTNShjdNHkpubMvXUneGxfVRelabwhQejrhZayoTXWFdZLIUKSaCcdZJttRrAceuvwAEuEExiUeRbeqMbmMGSlWzyfJVzrsQXmHA",
		@"TMTLHMfbileqzfRvBUnNbhGdqjmMWRBupbmliCRIXrueGnNoeuOThdxEqHRGXUUzmOieRRzNYHqVSegnyNEnOKGDidYcKUyHdtCJUEquKUiHbUAtZbL",
		@"znlfNfcmIMvUQiewQIzqjjAbKNPcYDYOucCdAIboQXyOyyECqUrSJJduebdmYEdztHYGRSnDBidpThYNRMQInCLjWtdmXwNgGypWphyNUmguwLZsUmwlvoduTIQsDMuCBcnAvJZ",
		@"FtuBsuzMsquBNtkOgTfHSodadTIUIcTeGhRBfmcsDpLDmuGuDMZXJEUhtthOTVClexBOVxtdDGlpUMADgcxtgEscOEvZJCpwQtriuKiomsShkBaidpHuBoomkklZcAGPGdkkWgKlhE",
		@"UuLWAibXkgCycPnmpkOJppBoVFWbnrIGdeAWmHFexUvHcjPyxfFWNePvrQUMwRQyIipAnBNwBubPiNNfJkwACIXnxoBHFAslcGsAeDgmFjBKIEgAMDrKnZsmSBWwxEJJEibxWLpwtEGFZBaZsoDuk",
		@"owqPgrlCEsnnZMUMGVBUnDTAizKEdBahyKoPNhRqedRPxEBEpKYtHuSbAXiWByYZJsgfkRFLuRRGWkTOnyTeXJdiSkxcwGRBIMHikdAPvBSqqcEevISDUgSCCgYBSqaEpnMKHZ",
		@"SVPyPgYsMtlZAzjnfSnxHHvNHLJiqjtkrBmbKMUFakrnHVIXFUyoXTeCppMZPRHpwXGvTWJgHUqNUTKaaHQrLZEaDIbMyPtYZsgnusiCESibGkRhCNRwWXlQdvIZUhbIGOHrk",
		@"ILSjJpMZRnvKZvgeHbsdRaphKrwpZtFZuRpMVEhwopraTjLnifOmUgIUdknSlRrvyQKEXOVYVRXUUHLOJrezdxmGriTaZtLQVqSjLVngUyyk",
		@"mhZGbumUxmNBETpcuLKFviZnrOCLDCFRgUvWqrdyznqkCdIRJNwqrjRuecZhkTwoVcBeDxqodWnnDPXfeQWSmnMNKiRyLFNXKncRNPaAONXTkYLDzuqEtLRfst",
		@"izvtfFzWwmKdvbdKPECdxDnQvbUIXWMmtFezuiHcioQwfWVjoyvjWFYcbeGoTUNbBdplETCImXufeLyCddXNRaRgfromsnTgnjggbefaZVMupYvvZXSayCo",
	];
	return ZvXrIHGFqBy;
}

- (void)prepareLayout
{
    [super prepareLayout];
    [self.cellLayoutList removeAllObjects];
    
    NSInteger rowCount = [self.collectionView numberOfItemsInSection:0];
    for (NSInteger row = 0; row < rowCount; row++) {
        UICollectionViewLayoutAttributes *attribute = [self layoutAttributesForItemAtIndexPath:[NSIndexPath indexPathForRow:row inSection:0]];
        [self.cellLayoutList addObject:attribute];
    }
}


- (CGSize)collectionViewContentSize
{
    return CGSizeMake(self.collectionView.frame.size.width, [self getContentSizeY]);
}


//目标offset，在应用layout的时候会调用这个回调来设置collectionView的contentOffset
- (CGPoint)targetContentOffsetForProposedContentOffset:(CGPoint)proposedContentOffset
{
    return CGPointMake(0, self.offsetY);
}


- (NSArray *)layoutAttributesForElementsInRect:(CGRect)rect
{
    NSMutableArray *array = [NSMutableArray array];
    for (UICollectionViewLayoutAttributes *attribute in self.cellLayoutList) {
        if (CGRectIntersectsRect(attribute.frame, rect)) {
            [array addObject:attribute];
        }
    }
    return array;
}


//每次手指滑动时，都会调用这个方法来返回每个cell的布局
- (UICollectionViewLayoutAttributes *)layoutAttributesForItemAtIndexPath:(NSIndexPath *)indexPath
{
    NSInteger rowCount = [self.collectionView numberOfItemsInSection:0];
    //如果超过两张卡片，则用多卡片布局
    if (rowCount >2) {
        return [self getAttributesWhen3orMoreRows:indexPath];
    } else {
        return [self getAttributesWhenLessThan2:indexPath];
    }
}


- (BOOL)shouldInvalidateLayoutForBoundsChange:(CGRect)newBounds
{
    return !CGRectEqualToRect(newBounds, self.collectionView.bounds);
}

#pragma mark - Private

//少于等于两张时的布局
- (UICollectionViewLayoutAttributes *)getAttributesWhenLessThan2:(NSIndexPath *)indexPath
{
    UICollectionViewLayoutAttributes *attributes = [UICollectionViewLayoutAttributes layoutAttributesForCellWithIndexPath:indexPath];
    CGFloat originY = GBL_UIKIT_D1 + indexPath.row *(cellHeight + GBL_UIKIT_D0);
    attributes.frame = CGRectMake(GBL_UIKIT_D0, originY, cellWidth, cellHeight);
    return attributes;
}


//超过三张时的布局
- (UICollectionViewLayoutAttributes *)getAttributesWhen3orMoreRows:(NSIndexPath *)indexPath
{
    UICollectionViewLayoutAttributes *attributes = [UICollectionViewLayoutAttributes layoutAttributesForCellWithIndexPath:indexPath];
    attributes.size = CGSizeMake(cellWidth, cellHeight);
    
    //计算位置
    CGFloat originY = [self getOriginYWithOffsetY:self.collectionView.contentOffset.y row:indexPath.row];
    CGFloat centerY = originY + self.collectionView.contentOffset.y + cellHeight / 2.0;
    attributes.center = CGPointMake(CGRectGetWidth(self.collectionView.frame) / 2, centerY);
    
    //计算缩放比例
    CGFloat rat = [self transformRatio:originY];
    attributes.transform = CGAffineTransformMakeScale(rat, rat);
    
    //计算透明度
    //y = (1-1.14x)^0.3
    CGFloat blur = 0;
    if ((1 - 1.14 * rat) < 0 ) {
        blur = 0;
    } else {
        blur = powf((1 - 1.14 * rat), 0.4);
    }
    
    [self.blurList setObject:@(blur) atIndexedSubscript:indexPath.row];
    if (self.delegate && [self.delegate respondsToSelector:@selector(updateBlur:ForRow:)]) {
        [self.delegate updateBlur:blur ForRow:indexPath.row];
    }
    
    attributes.zIndex = originY;//这里设置zIndex，是为了cell的层次顺序达到下面的cell覆盖上面的cell的效果
    return attributes;
}


- (NSMutableArray *)blurList
{
    if (!_blurList) {
        _blurList = [NSMutableArray array];
        NSInteger rowCount = [self.collectionView numberOfItemsInSection:0];
        for (NSInteger row = 0; row < rowCount; row++) {
            [_blurList addObject:@0];
        }
    }
    
    return _blurList;
}


- (CGFloat)getContentSizeY
{
    self.contentSizeHeight = [self getSizeY];
    return self.contentSizeHeight;
}


//根据下标、当前偏移量来获取对应的y坐标
-(CGFloat)getOriginYWithOffsetY:(CGFloat)offsetY row:(NSInteger)row
{
    // 公式： y0 = ((m0 - x)/m0)^4*n0
    // 公式:  yi=((m0 + i*140-x)/(m0 + i*140))^4*((m0+140*i)/m0)^4*n0
    CGFloat x = offsetY;    //这里offsetY就是自变量x
    CGFloat ni = [self defaultYWithRow:row];
    CGFloat mi = self.m0 + row * self.deltaOffsetY;
    CGFloat tmp = mi - x;
    CGFloat y = 0;
    if (tmp >= 0) {
        y = powf((tmp) / mi, 4) * ni;
    } else {
        y = 0 - (cellHeight - tmp);
    }
    
    return y;
}


//获取当contentOffset.y=0时每个cell的y值
- (CGFloat)defaultYWithRow:(NSInteger)row
{
    CGFloat x0 = 0; //初始状态
    CGFloat xi = x0 - self.deltaOffsetY * row;
    CGFloat ni = powf((self.m0 - xi) / self.m0, 4) * self.n0;
    return ni;
}


//根据偏移量、下标获取对应的尺寸变化
- (CGFloat)transformRatio:(CGFloat)originY
{
    // y = (x/range)^0.4
    if (originY < 0) {
        return 1;
    }
    CGFloat range = [UIScreen mainScreen].bounds.size.height;
    originY = fminf(originY, range);
    CGFloat ratio = powf(originY / range, 0.04);
    return ratio;
}


- (CGFloat)getSizeY
{
    NSInteger rowCount = [self.collectionView numberOfItemsInSection:0];
    if (rowCount <= 2) {
        return self.collectionView.frame.size.height;
    }
    CGFloat scrollY = self.deltaOffsetY * (rowCount - 1);
    return scrollY + self.screenHeight;
}

@end
