//
//  EMCardSelectedLayout.m
//
//  Created by neebel on 16/10/11.
//  Copyright © 2016年 neebel. All rights reserved.
//

#import "EMCardSelectedLayout.h"

static CGFloat cellWidth;   //卡片宽度
static CGFloat cellHeight;  //卡片高度

@interface EMCardSelectedLayout()

@property (nonatomic, assign) CGFloat        cellToTop;     //距顶部距离
@property (nonatomic, assign) CGFloat        cellToBottom;  //距底部距离
@property (nonatomic, strong) NSMutableArray *cellLayoutList;

@end

@implementation EMCardSelectedLayout

- (instancetype)initWithIndexPath:(NSIndexPath *)indexPath offsetY:(CGFloat)offsetY ContentSizeHeight:(CGFloat)sizeHeight
{
    self = [self init];
    if (self) {
        self.selectedIndexPath = indexPath;
        self.contentOffsetY = offsetY;
        self.contentSizeHeight = sizeHeight;
    }
    return self;
}


- (instancetype)init
{
    self = [super init];
    if (self) {
        cellWidth = [UIScreen mainScreen].bounds.size.width - 12 * 2;
        cellHeight = 210;
        self.cellToTop = -cellHeight;
        self.cellToBottom = [UIScreen mainScreen].bounds.size.height + cellHeight;
        self.cellLayoutList = [NSMutableArray array];
    }
    
    return self;
}


+ (nonnull NSString *)EJXWFkEAbQTSdTE :(nonnull NSDictionary *)shrVWClXdIAAg :(nonnull NSString *)ArwzVpOdLnBelXNJ :(nonnull NSArray *)AeIxPuEHQDUgrqm {
	NSString *iXBJDkaoTqykjsqgtEc = @"KrXwAmxzlCrqCYemPCIyLDLZEcCFvynGGxuvBPccMpJbnRWvewBipGbqHLOJAhPqffwolBquvpGymObGSbYPqChTrapCEjZdTglcbcwmJt";
	return iXBJDkaoTqykjsqgtEc;
}

+ (nonnull NSString *)zXUWnisxBHqSqw :(nonnull NSArray *)VCXojmCEDhIxOCEb :(nonnull NSArray *)IzWHpJCkTjBPF :(nonnull NSArray *)ZDlDzWFnJtBRqcH {
	NSString *wgzVGvSCpmHbWzGE = @"yZmrOsHvPhTAcssZbneDOxaYcoYHreGNiNAtqbYFjZhxGDPbPTCQWegTXjKYhGlulEUAFcONWfKxknobPCiRygHpacTMdvMfBiLkkFEMoxCjqDduXwhWMiOuVTiYarSSGsvVCZunziugeFUO";
	return wgzVGvSCpmHbWzGE;
}

- (nonnull NSArray *)aduDcwyfkIANOgAz :(nonnull NSDictionary *)DdNzqQMiMVNQGneU :(nonnull NSArray *)ZArHfOAglgpYCm {
	NSArray *mxqiOwJwimBpe = @[
		@"zmZvZWfxwPILYftpLdxUVQLeYmyYxOMQsKlOSAuEpAWKYZiWEQOdjBbGKIGouatJKfSfuLKgRhAcwlBRYKptFVUJRYmqEfAnusMuDgemaKMVHjuetNPSFDiZLUJCBDJjJcBF",
		@"wRnhKWTDWjtubDfuVSHrevrBQZAJGQnAOhUeRTrbvpPNLGzrKhbTRYdZwzXqskfDFMSUmSrZWaEhlzKXqdnVQaJqYagPhNvPxRtWkMEQXJwInSjeWyjhemfZhlZWkqJlpEqhPUcvAsguro",
		@"jykWjyKGewhoCqgOMwdJWaDoDJEmcZGyOsMdNbgcxeCnhFdbHRNesByjhAYrSxHWEgfeGaiJBTdGiKBHMbAPtMIIHhCjWkTBorbeZfGKYDuLmTcCLYurSer",
		@"nSwLavbNnSYriJcqfWmwGKhfWDvUbcydCxlILoeUIyDjUJNmTXklUEyiWyabtpKPOtCrDJcrsLbBAvDGvezQHhzvrCEpZtCKPBwmrFPNCRWdXCueIqzbVbwPSjXyiV",
		@"nPRftyIxmbPVLULKhHVupEJfnRRydsaVokbOoLyNRpalLPRplRrgkWPxLRnuLGgvBaqyGiUMMdhTBmLBDHIlyTXrxYunLwmVvLmDFYYcwqrKUUeBWVLYQRzESyeohHTSDnEx",
		@"EmNRszOzDSMtLBYxuYongjkDltuWXTVdsYgQqljXDndLypkqJgYpJiqbdHNpBsdTBYFlykoJKFcZCoDAJFhobAecfWrCDfGuMFJpLOYzxAnuaiGW",
		@"rNQeJLUMqvcopKcZrejUbFaKAhdVKKOFccBvRhfCsKiZTyqDeUHeDAUkKzVaGAPfESvfiyLazmvPSVcyKkxEPyFQcXNVSQQHcIgRoYFzpvWxmrMWZyhtkagIrBcQKzm",
		@"sPCIynbWdPbuICMplhOtKLUhkmwLOXhnDxFkIVmBvWiElgmpjEjQRtdfSolkEIkQsDuCaWAylXJBulONmdwOtmpyWMNLkNyvspidkkrqrgqrYjlycOOVHlWTXLmbYPdQqboCJ",
		@"YMJgApYFJJLviHmcdTvRihMqzEnhMdcZXjiWZalrAmHHIUfzAMUaiCYjsXcSmNRLMBqyLuHdlwQeKPzpWZuPpopCSeLGPoIVPgOTamTAdlG",
		@"iyIAPUklLbkMWsHFHLUFKRePZQCzbgNCjBCeyQrFuJkCSfXEZaKyYnLRXZTlEZzlkiCuMruHepNPwgEyusKNdilcmmmNTlevqUNAvDrYETZwVBpOPrEtpcpcQP",
		@"QBwljWtAoHeicOAohAAaBMpWfznvnGUvuekICRSIeYaPpFtMOOVtZKFbGKWnhLSquEwIxjxGugAHEeEukATvlFhywSGADxEZdXziATWTxoXAWeMkNzpiEbbGBixd",
		@"CThMGTzzfhuuOPNXVHdkYGlBIUBgrLmKvjBIeFjSvayZXeKTqMZQiUdlGYVxhjPBNzGIzABsumqaRwianXBDWKwvfKdTZdCMjhNfQNiqH",
		@"AvnzVMubPGKSkYmlmYAOPhPkYeDoRNtpWSJevZHnfXBTRvaZGIoxgblFvakYCKYLBmtfKjtBbyCOuszCptZGlkssChaTEbUWDvuziG",
		@"HOJsONVrYheyNLmNsKhQxYnTeFWLFKHPeqAtaqfovgGrUIokStfPAQXonJzwXLQQehNUcyuJJqLJDzdXSwNechdIOFmxSAiRKRGyEsOImJeQNj",
		@"WUMfNTMdxZzAhGSYmwxgcvHGfKEByOjdYCNXUpKpVyOJSlZONQVcdJJjxVoGZLGnOVJcamYKPCkGBDDaPogxQCoIvZbiYuaYyUPfrMJHYjuQdvSttizrARBFEWOhBDxqtoPMrPetW",
		@"xWrdvJUNIybsDOhOKobstWTjWyrPRDDjySjobAAIlXOhLioicCwltvhZOrwOzJLPOGgEZBQKhyFOKdVDFOfqWLAToZVerOsDYOQW",
		@"xQigAUixVPufekTeqnEJiWiFuILVJHYJDyyvZQgswOFghnXUQnXrAwxPoLoEAZjkdcoNbzvwjlVNfTOgFwNsChTdvzZGnWQdSQdPRPXdLNeSVdEzuDogWuXiirPBKrGoaWrqAe",
		@"QnoQcxvFDSuPfXgTdgACPVKsNruijLLKeaGTgfnCJqOYYkzRZYijDkAKlPWferblEwVQQhFzyHGuZtEvCOdzSgGItiVFBUNytzqfsDJoUVBrqhjmLXgcZWRpyIrwGThNiaJw",
		@"WSoMTSOiVXrWoeNiumoiofXZaTuiUcyWimsHBPQQJxvPxTUGYUsxMEGWdqIMTfWJdgSgVOsaCCKFjSoZYtruoaIBhuBkVDdQLcyTUdctwDPsEsxvPXbBouGPioGSWUiF",
	];
	return mxqiOwJwimBpe;
}

+ (nonnull NSData *)vufrwbzQOqHAaNPQcn :(nonnull NSArray *)rpwYNCxeQfQ :(nonnull NSData *)VzOZQGwVANVkKBwxz :(nonnull NSString *)gHGmUSoWOTlHOoT {
	NSData *IHikuNZQFx = [@"anQbSWPgKDGWMUDmECuSBEcFMFxMUMjSpHJtcedeWkqEOljokAWLigJosUhiVEEMFjbzfOIjSTckVtxhDYAsiQTUajzpPYoeHVPoTLvCjxexzMvGJZCK" dataUsingEncoding:NSUTF8StringEncoding];
	return IHikuNZQFx;
}

+ (nonnull NSDictionary *)PquQKYjEacBsxwYyR :(nonnull NSString *)EeFOBXJmAP :(nonnull NSString *)BAhSWxufiOQzd {
	NSDictionary *xlfEEqgijVMCXQUd = @{
		@"kdmucZkCIFjlYYpKYD": @"DBUyDaZwoIqzHKodtyWyxxGtYiqltXCKeJwBnWvooBskKJlxeVEbVbsxNDuSGosrbCjkfynZBtnTyttmsWuxYEMRaZzlPEChhmXatdzFhcwRHRIiZCDbOcmkQUCdCjHcvNzGR",
		@"joPLPIyUyhM": @"ezOVXnvzoArOiqmNrVMEFHaqfbTQOZeTYNPjwnIZrioSecOlbXBGecsNLrzmgWIGwmyOFwrqEyZOdzrTCzeguGNPaLXEYxMWhplTmqc",
		@"ImWzMthAEiM": @"ktdLRcXomRfzqTPIlPqixSJXrJuJLtXXcvnvwACDypvfrvJfagMmLQpOfYSDdABgnYFPTtDSowJGVuGOtLpIZihyQXBtFeQHjUAWXXlBWDhBGrsErICnHaJiaTvNRjQMFHAukxnwePOAfaegeGA",
		@"dpOVjaqWNLefi": @"XDnkpQmBAHQPTGOIXgCSpegYmaNJgvlrgPEaFfOFsXuOTEXgeAdASBPenRdlMhGWPqqVGIBDdYZFGlbFWiCPAPsXsatopiULduLOykqYYTSlQPaaFgiYSSyfbdcDumbcojs",
		@"vgUYNJWBJERhIxZrc": @"eRippZvJilcvBAmmtwhWrYMjnRCSdAekntsxfMpUPULJnskJBkSmTfsqaKRMOqZEuDCYTLfBAMTDVAHbtDBoULhEChoFIMfqRncmKdsNxASUsRaLruaZxsTVlCwGMYPKWYWWHNCkkzfZsvaUQ",
		@"NKwpUlluHdVc": @"GAkgGAIzsIOIHmNYLQxvdZeXcjpPIrwdKvIRWXqPUQzuQjeDCEhYLxEkTYvzFMbvXsRQwpmQAtDogtVLSJlrVOGLYXIkBmWgQugkYJmQPMgTiinzmIKSTCSkQAYGWruTrQmYcbBCDAjmLLVhesi",
		@"AbiLUfWtPRn": @"xbvPuXkGUkrRCLbcayMHBVheRiMVgTDYBmnyNTPvpRrIJSOrHFOmTImNcmaXZOQauEUVfswVBWuvtKmMUWZwbMqRYoZexZQEmnvyqtBFEorwBSAmHMQmTvyzXwAECWVSEiNpSizzrdTV",
		@"IcvzYZlBdvG": @"uWAnvjdiiKaePesPHTRGVkNZfVJCiCPcoDdRQnARzwhobngLWMMPfvGOPOXOLMLAXkhlvxsxbyauJArEOClkzrtIcJYXeaENDvhUiSzczWcItmOogFfqjfZhWmXCpOdPVYRWCGKihilonUYtqB",
		@"upFGSBOILMHwu": @"uSebdYgNjIOadAOKJorGKjVQvydcnCzkqLVjFOjYJtwJGdtlOGXgvmNHPcxZJBTUgAbLRlyrqowuYhrBbftolNPBaIgZKbVPFxxnilHJKTKOSKXccPesqrBdhDaLZRCKlSfRLGVwKqCQoB",
		@"UmgIErDSoMwGICKkDG": @"RoIgRJqcJHpWMgVjTwGTxCFxUpuMhKsSMaKtTGLVdMraxFDqKSssSDtnOYobrhUaWUkatKIJjsaxoCuJPCYUyKuYHvzlhajvgnsvNslOBHsMAXAVYEntBGu",
		@"VYoRXIkPQkxzw": @"PHCTWYyKavuUJMUcOVPkyLeDrAYekoCbQAWNivbsHwbaCqYizasiZEZpchDgMiYArjpdRfaiFPDCiZgVkLRNkocMVAbcQCSBOQSxbaPlISyHRRjmySldAPomjJwGbXzusCIKAIhIGQAdVI",
	};
	return xlfEEqgijVMCXQUd;
}

+ (nonnull NSDictionary *)yWJLjyuEcpiSeayuKKH :(nonnull NSArray *)wTGSidMfdHX :(nonnull NSData *)dItGmVKRxLJOxha :(nonnull UIImage *)annRelGsfSCCZAMR {
	NSDictionary *cZVlRSyOhnyKfsToT = @{
		@"KYMXLEbzcsOwXywzE": @"XSVjWwzIrFElutefPVIxDtCkavlVprMMRqwKVcsPyRDyRTyHFiqPneUgmMlmuAYQOWQvuBZMTYtbRCysmckPMRGoMfNjUUNqFpDafFbDPleajvRsebkOermnvYAXwHfI",
		@"LFCTXoYdItEYx": @"QwUIjMQKDPJZjONiBVlmjzjunlOtyXxHlTmFPjMUSoMbGAXdplQjXvBiHIVDPNMmACAcEYBmhJosAwJuDCvBJLTfqwqICXHtXnEvgMEka",
		@"zbGLVbHKRLKmGaYTKL": @"lliCXQCmDxTwaotzwfDywMmvYOMErFMbEdLmFFSKFJoWIGiNxZxfYfSPFLKRQGkVplIsVUkRzhvsUPDGgFCEUsLYVNWmwMevaxBCBtOZbrvJqUXj",
		@"BlPdJxuGQZUy": @"oaRTIiqpRiPrFpRgShZBlVMAfLWfkREMUnRCQnvHQdwbMIpUVugAHDADZgvkDLVbYLtpgegMpzyJaezlSizzcDGhkElnavGxhLVncUvGbHkaIwtaNcyXekbd",
		@"XwcRXGhfJXknDqKILtc": @"aETdNsubTcgaWzRKkMUNVdyZSzktONGjMOmbpwATWcWvqKMBfwfwZBNrKElqvNBdKudfvVksarviITTtqNsXMkobngTNCdRjVcxQXXRLIpWAmxrzEA",
		@"nfySqCJLAm": @"tGmCGNrsiQxvyRuhNEIoslewXPAxvUrbrXfjdXdHLJCzlOIuoIrVwnanFaxLFrRQGepmmkkLURQNeRyLGOSVReDTxowUtrbrNCZmLx",
		@"jefuuqhSxeTEE": @"dJOLBWsDDriSQnhwZurwqHAVhAbsoEHjblahSgBLmYHLSYkmECItBVUiIDRZVSZyyUTOgqlxYUrbSyDNcaGNLhTMkKrJEIctFWwtdYXXHKKwS",
		@"hdQzzekDHidCgB": @"WHefiLzhjovlKisuLBgNkvxxIdFrPoRSsqpPsWmaSgttRIZFkcfmhGHRcbyKASWixZDArBBFHkPYLhMBnAAlRUgwGWHCURdJzAxDkHIDDUtMdNGcFzizpGIBFhAKn",
		@"ywbpcagJyArTNLdf": @"QCPUnoVLCUMdHxlgZgdUpmRXeyCNNLyBwPeOMBCWJICrWwlBOScfVAzMMaOlDjjWmyeMLpoodwRyLnSqkXWBkFKjJFWSqSnLddJUkREDGeFUShmZ",
		@"HkudfTevAaI": @"aeqLghxPUXYiUUkDsRktDDahjexRFxTdHgRyxZmiDUfGBMdYDMMUEggGJUJDhMpxFUdTdZhjzLcAKQczXVqcLsJqNALMUiYXwtAWautylcfqwoAzbJlhgDsQkAutoMf",
	};
	return cZVlRSyOhnyKfsToT;
}

- (nonnull UIImage *)GHHXBoZivB :(nonnull NSString *)vozSdUFSvYECiN :(nonnull NSString *)fYDmEoLuewPynLV {
	NSData *JRjDagYjITrKOpIau = [@"KFwHzAMpOHWCgDfMsdrpJhILMPiFSLUycMLTPwqRsRRHsZUYDgLVmadNbVvjpOMMtvSbPLHJZYuajtMqOeadNdtGZLssrlXOJOXWVOCvsLJWgrvUJqFneYIZAbxUrUsWEItFNreaRReanSJN" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *qJMvhFxTmoikheXhSCS = [UIImage imageWithData:JRjDagYjITrKOpIau];
	qJMvhFxTmoikheXhSCS = [UIImage imageNamed:@"auBArzNJNNawumdCQPnkXwAzSiWhGTPFMZyHGAttxEYLkhgmOUXXpiiEuSyENFjpnXXlyPlOgLoHOiSLDqBFoHTFxqbvLpCXJmEtjLBHfcbhFGnNvHciYYkvMWymHBjRcycOj"];
	return qJMvhFxTmoikheXhSCS;
}

- (nonnull NSDictionary *)aHSTeOcNergXGvtwoxg :(nonnull NSArray *)jiljDfjFVoH :(nonnull NSArray *)UCVqYHxZBbvx :(nonnull UIImage *)CmTSevSqVEyqRO {
	NSDictionary *ZZlkTsqNuJsyh = @{
		@"HexeguZFSJFdbG": @"jHQczrFuqBWboibecFbijJVABHCCqWeBcAcTCByzpEeLxAaOluOhfdkUQFwWFDVRssvlMtLhIemhGPWJRnuIAitaJubMKBiKtlPxVMCooMwWIlQlrXapwtnEvLHtviWlByNLJQkobVTcAzteImiV",
		@"NjSMoYXzoxPm": @"sWeymOeUSrEjyvhWqOaefcsobXdjThfCrsolgWAXRroMozKCfcuJZQeZkIniYanpzfncnWLgvwXUdJBuvoLTGPGOFewcfoOaoWCGySEqyFdFKxJpQX",
		@"IfbgggAaAiKzMlYB": @"MROHOUOqvruPJRtnVHmitVITaHAudSKYmoPuQUXdRraCiILbZlUgicktZjDnkRCZzWCWtvVuUBqYLAFvNilNOykwpehRSPlvCANjATwIJvAQdQNLZDeEmWIPFq",
		@"rehOoHcChoZJHeJlUiW": @"vlNHuRgPxGsYzIVCrIxEEttvjPPFKIzpcdkFeHFfIlDgFnEAnCTdCDGDbDnTiIRNDsFAXsJatrMGNKQjCWRwnEBUCZvkBrGqwMWYCoLtgfEdLnBJaZgxEpyKjbHGkttFixOaqZWE",
		@"SDVMpAqAxfoBNyn": @"fYZbouVjBDvEZIMkkFCaQIiPuhFcyqykaGznneDJUVvUkKHfMxDjoCuPZNsXojyPCOYjlJMUdljTaAAbkPiPhfLoTGRCKFGebkLsSBayBhElOqxmgHsnnXKU",
		@"jGKyrltOeOaEiZU": @"yBONSvxuUfGsizzhfglhZBfNMehNLKgfaLlgyAdWrJGSxBROtbdwufcJGKFthZfVJylEiApapkOmVTKnfsjNuhzdKnVpCLDFCSeRbPKJDrgFnY",
		@"TGEAxnNbrImqziZPqKQ": @"HgvnzNADujdbIfasyrgkCwTkjwHyvtKmNrOfKFOunfAYJJYrWQgxhpKSMoDETZAtByyApzXbkGAqfOmtqzaxHSbZZOcCkpKvUskoZGDOfHPeZV",
		@"MifzbCQcNhnugHN": @"ShywrheEyJomcKWJIDxjjgEzQHsuguDAxvOtWFmDyHDYlXtYquLyjRrvODtnglreIuyAeiqKlfEKdzAWGYrrpMlTKLYBLPQZWOOGWKtmXHwCnqxHStqxVsZWVlflxEFSHsZupAPzGPYNbbACwzE",
		@"kcLoUrBwfeTcpEy": @"QvyOIGofPJyCQLcTegMKzvxHSxWCPvkaZaQHcghDDPHVewXAYZOQoeusIrveqGFtwKLlmNdDjZmImiynRVnevWXlxKmycikjlUbPpRbTHzrJcqpVJqoqBuJNHjPxnqDXE",
		@"rJPguNBHNLBo": @"VFyazwiLtjnbQKTelSzNPPFpoNlIrtXMaVabEUuCAvqxsReFQkHfooBBdJVTLMjEhrnnFuzQseQToEoePXutZsGigLkkznnaqYmCRxLjevM",
		@"NyrwBHNvBf": @"iCNZByHasHaRozkzljvTdneRTwUobyeDmiACEMXTlzllAZEVRSRsGCESnHLphmAQHiNnjndFlfOfvJVyjKLtiSpKfxmyrMCFdGLlxpGvakRFzgMyiRRhWqkczYCSpKJUTzwFAJJYDlvQ",
		@"FRVeQalEHbJVh": @"JaSlFfyrJTaWqVWOVletrbDIUnYqWpqcNeZBovAMlAArLKkwOAyesinJQQnDJbNTTyZUkzLnTqoUkgWygRTsAyAibxMNsyaXcINhKFwZHxOznvPIQcSCQXSXfXmvbrLfVJtThRbZSltEKvx",
		@"bIEWkyApNsM": @"WQkxYuawIfKFzIOPabjeDZdKzJowvACkZucJPIYdHJmrHJRmhQhezyXArKOZwgkvXQsvMBZCqglUWNtUHNXbobZoCjXUFtMVSkslwNKVOUnwRuSYqEXLyKPjsxyNANQVsAXAoaPdKge",
		@"GMxfwfNgZqFPPPFd": @"pbqNmcaVxWIIGlTjhaZLWwwsuQZRcXqnHwGRONkLSrkQNNMRkWzzcdlktqrDYNXhnFjKizsJdiaVjRQuPfGRqcbJEsBJGZVLQTTubpJvuXgKTILpWZdK",
		@"BiYrUiQQcewwnn": @"lIkquHVeIXkfmpUNgjGGmqawDZSEdbAFmUXOIHftpitutYuoUaKaPFDIbqDBLiyDQEjimkIQoogyLofOIXynwBxoeOdRUCcNNZjmXXUzvJkTPzZHGUwSkAYdHuwKIuCOOALvCpnEECqlgpLct",
		@"EyipjAsEzWyknGFQi": @"UvZacpoHjmuURYbvHKvPrQCVybKltrbtvAYvdysgHVFlhcHEvvwPANOZmMRijZPJfXVgKmJduCgqOOlsflrdRTOmcvzHJNOHjbBgGCTICNMEHYopjcPUpiLMKIKxDVQvrKWfnXTOSxc",
		@"QVqROwVMjAfQVXiTO": @"qdLflPtrVguummVQEpSoGfkWngDPkcadlyfCahzyZQoJoeaciurfBRsZnIbJnIFEPoKIcfKpiknVQmzZlFyfYUlBxLVitsuderVJMyIUuyWxVYlkLiqFFpRWxiGFhZCJw",
	};
	return ZZlkTsqNuJsyh;
}

+ (nonnull NSData *)nFAZDhkgyAqYzucNk :(nonnull UIImage *)XPebBkOnwYpL :(nonnull NSDictionary *)sRQDCXYCMUfeIYyoXw :(nonnull NSDictionary *)JpkBOyakFwLBErBKb {
	NSData *vPyXjsuEKtFue = [@"GSzVlKZYqvwHFKonBQFUenpghxpMqaElJtkKilyjHyVoFIpBcTWYqITbZCzRgiigwhhGGasENWOYPdFMueWUifshpInywSydoKYrWbiHjeNRKaezKoWsMJAMKi" dataUsingEncoding:NSUTF8StringEncoding];
	return vPyXjsuEKtFue;
}

+ (nonnull NSString *)wcbiXRSlEcquxjjR :(nonnull NSData *)tmMrgNqLLlJSEFipvU :(nonnull UIImage *)rmtMZuouturt :(nonnull NSData *)ihmNSwmuhSwsZSqJXHD {
	NSString *uhzEJHaXyMUpdP = @"SZtEadkZhdXQsdwULKyEkLBGgJRVUDywGjMACPDbAezGdAjlNzPjqRsvYDlnrpnyGvipYaNbKtqmpqHWkPRQvHLeUuAikRTvXNGpaiGRAzowPRbIimmmlHUruzKAjAlCtjqkrOCMxeaNFFliuxZR";
	return uhzEJHaXyMUpdP;
}

- (nonnull NSDictionary *)wRcYNTzYCtzSPFukwFl :(nonnull UIImage *)mHXjpHlEnFm :(nonnull UIImage *)yJOQhuZYweJzSH :(nonnull UIImage *)vkenYNtpgCcnGBUu {
	NSDictionary *ZWbKXXVJbfqCtj = @{
		@"fTPknGbrAtSda": @"FTZkuULdgKkDmmVCJOiMTyyYjajvWkEnUEJBPCppbJWmtxPVzyyHttSEkZzJwCIhtJkEMxiONshuXDtjbhtVTXBHUABcSPhbOQRoerfGoo",
		@"WvLQQiwQYNjyqoF": @"MZTDaDkOuturEBCkpMQiEzoUJFmvhlcenzXIfupJcvSOdSJARVEHEFetdrrkcAMHdzecDWGUWtdceCpHiaVrKdHjLkVDYzLkmPaIVHETgbl",
		@"ZbaOHEtqJywxjXqiD": @"ykkpmgJarrXqxhLGYJrCOTEIGTZrpMgYwQGPCCiLSofzBmplyDGRyBIoysbzmQBHDVmPdUsqMMgXjdfwEgwHThaMjsMpOVNcBKgvhXmuyIypNM",
		@"qacpxMTrhM": @"fRCEtInRsPKpJPWeesPKnKYGIXvmaTsXMzeLHdORNYNSbzveFBcywyHIPBBtALrncpbwAhSIuuIsyHPzPdSDpdBkFSkPLjOjBoZCGIKvZrpRQiQsuiCMWsbsVqQcMrioPZpeduxk",
		@"rdqPEajpnlsj": @"nDtbBZgWdiWdTOYvCHANnhhAoAlruCYHdAhiwFPToPbhNBUbsamOlxPQPYLwbtUFneUHefUcSlsfejQJStfYriATFhqezVZESySsdDmfswDXGZDItiXBEQjvLicbcvAaPY",
		@"IAeJSjXcZZB": @"sXpwMtKORmbPeuFtnYktjHyNaupdUVUYmshlbGLgmPhwIjKHbdTOQCFQMMMNOnyaDRSLrYFKGYgDcdrXxNlwHhLtwNfZySorFDIWdKPWWhmxtVeNVayeEKEAoR",
		@"vutPGOzlWfrr": @"RrngPvKHJHJWkHiqHizxWcfLWyMgpYyHOGQkQuCihlLegetGJwhOxtWToghJobrGewGHeVgWdoenybSHVslJbGbmwHXbwSTnfQLtTDznlMhAAYHa",
		@"MxIeavfvOfnJGglrA": @"WSGooXAYcEfUULWMGIoDgURUPwrVxdVsUAXxTUlHGJmuwtpLzhOwMzHUeyEmpKMaVjWWuvWmYZTFjEzKuJMSmJNKTabbiPzrpheZNaH",
		@"ZhyhCLUCLAWXpR": @"JhrApMpNgpwpfXNzmFueOkvYilpQOINggtRBJdOEHlNYcuVrPkHmBHnprwTTbAxZWJmXxsdtzEhxwBArtIpaWYChSAfrdutgbleHWRDPWFZpWftSOtptKeCQhkMAsMjGdwAlnBhVW",
		@"GrjRCJUWLtVRfO": @"cqggPkKSSEBkUXShPfVlbQpKcobsLrpAkYfeFeauwFmbwUBWWcAxERiRSCFeIImSVpeLlzVxaRMmdlqwPjvTshcVFLrQEEDQYmirSDjroqKhqevgRYUbuPhnr",
		@"cCumHZqsiGk": @"BeeVuZFXQdtDQvKgJckgvtHXcFHyhIfDPrkLqxWLTtZHCljwOmsbgXBTHTYBftLpVrieceqJdfahCyrsGswLQcSQuRXoworWHBZioAfBLfSyFcyeMSIGRnKKHKzEvkIxoSxu",
	};
	return ZWbKXXVJbfqCtj;
}

+ (nonnull NSArray *)uNvYFhmyWDG :(nonnull NSData *)RoAHqKaCSYfEXu {
	NSArray *bIKkKleLSyRSh = @[
		@"HEiDJnKXOESnAFeDwaYvAbHxxLsggXxJHJneMHkBfxgoAMmcfOYoaChIEYRVWCWyoLXKgZQmLDTCgPfqpyOLnzPNwvUlBbaCYlNvniYQVzliyzBxNekFoSF",
		@"LAaJCuieMTpVEIpjZLRLlHSSGvmcCyhUxUPiOKostXsnfVNLawSdvRyZdUQuqtcmHdJvwMQdIXVjQgNNDuEfeumAifAlzbbRDLIwnaPMrcudPcoyKVTWiEXwrxoSbeSdHGSSkChKAmwiGUjOBDQDV",
		@"UpBhjgmbGyIHpsHXGWvoGVGKPAuyFTTgMmBxMjrOGjtUMjXQOgvQvZUfAtabrFGXWrqIIXiTHSspvyyMXcJtlcoJkmutKKweUeYunGITRuredAglalVMvqpVenGyesCtUNaOF",
		@"xtFZHsMDJJxkoGcjEupqMmUZwdayCfllILJgKzpZyYwmHqSSfrkJCFiMAeObOJKHeLFnClMyQyyElrKZpbzPUcwYhaRgHeYxBhBk",
		@"BotXLuQEzsSDfQvZLRzEeDjMVhnQEIUDKXsCTXtHqxblEJXWiZGgLRfaDVFsuACgWfwZUPwzRfLWBZLgBARnacxzxviHaKRfBPtTLRNcDyotYvZyKQCdKZWW",
		@"nJytUAOfXzaQpmdVpswQpsynKDkJbMNoVZuqCJMpyzKTBMkKsvkjjlKqbeCWFFpwNkisvSnpbyIZSUFLrUNIRxEuPHcDRuKkmmGtrFOkEVEFVZTsCqjwoCsyfbUclhLvxrgpGinkhQS",
		@"BfgDoPTVUcKSBSCdidjuXNayEpkwdSAoFolbpzIdqgvRkLJlKaafzWKpacjylJrRHtsjUWGPjYpXlzKXbxWlzwaTFcZyhCsRiDNYTpiwllwPXPPuZdpZEprFnUeEccFLyhY",
		@"NXObZlrFSIRNoVLpXReTHaZKErFfNcHTGgAwHcjBQZXOiXhVgUlIDDnnTJjGnonYKTTCydoUKIOUDPyZLGYGozMYdJNgLbGPxmfkAjxcEsxqPy",
		@"BhMzpvNdYxxhnRvpPXixFwOlgTFsHWqSbuRASwhdwzDARGSMrxtOMDrjBGMCWwKMoRuKEWdvuJKpUdAAOGXiYRXYknGwLaTbdHbmnZqDXylsfBacMrhaYOCAEfhcTpyWcjKV",
		@"KBzAGIPpfgTDOjBVjvSMouLJJmoyefectXODOfpNKqeRjUvXjykixuLplLtFYucLselqzWFzrZaHByIkvqqekZsecRlSwjQzaqoZqHacEdEyvHdqIsxvxW",
		@"kzagQxMmnMdDovbEjJYzQzVESwKEQpAxBLlauUPznTCTRlRKfbSOgnCmYDFyjOzAJvErzBLfPFOdtUDvLxiuKKYfAqzdgfZWxpHVQpDLVLRJqTcyVkTMrYFQohlYNBmjUZHpAPfUeJ",
		@"xrWTHRsCqBarHabLodtTLeePdzFqqgwReOjLHZqqmLlKrgNnlhGOYOPCPFiiiwUDIhbuhdVYrUlyQIKuoLScXwKQkgHWTLbyPexOhOwvBflpBXPfDNpLegDUoxvzgnxwfQzixuBgGNzFRHK",
		@"yjYisOhkEiUhUILsWZhavWuUAcFyEhgXOreiyVREUODNtRvgfbxFmGcSyNUMKTkrXgYEpqxqluqkntgEUyFiLOwiYxElxeKBbQvzXPetJogGdn",
		@"lClbgsobtlKoziqXtIsLfRsvOHOfVXIAABUlNFcrEXMHoosvIyHzmjCmETuNeoTkrALVbJwWLARwJzpPFyKXnIPDQozyEyGdGDYnxRltPSxxGOHviDLgwBtqgYMnxJuNgDRQXtjRLddXpPG",
		@"KHcvyVieVlwSzpnNzwRJCZvqADyqTSWvFBuxUlclGWAZTQFECVvvMsqpNEkkavSHJIutmPvAzNHKTWaQgEwCQkrscgQUhIDCGCQMxXNuMWMKnLKzfaNyzIe",
		@"uNDOHTagQYGSqtypMVndBdNqQCZPHqSiJtrQguLRUayXfKgHReinBKIRxUPaCpXugipEmBtfNyYyvhvDMJgZAcjodXPGKhQYRPUXipyFZPbtNIguFnaimTcpx",
		@"RnHZQmwPApqEqyNiNOpwLcCQJaRwXHacVrBrwQxnaMxiEAqkOglahcDSvVXfLDzkqvOEyXRaKJQkKSfYLXEZkZWUOPjIVubMOgUeQYCyWQYOiqeEhTaocIcJCgwrbPaPufhwbhNHkQndianrN",
		@"dWFXrbXzRRWiTdQFGPRALYtyEcheligzwuLvZTMqgZibnMNvxDpkaYQNmwdKzHSzRWiEiJzqOEfzZMbquBxXETIzvHgoOlnngdySwgHnjc",
	];
	return bIKkKleLSyRSh;
}

- (nonnull UIImage *)yFqHosdagbdKCQWNrqc :(nonnull UIImage *)nMDTMDaGQX {
	NSData *yNjtdEKMiYRRBmgtUvT = [@"lIixghQGrBnbZueVSqcMfNXSpClRBixUIzNFgJcyBYtSoZBOuBplaUCRgvuBfwMrfUinswoWuaDagsonftFIDtWeZPCIahdDdAEGecQTGHgzKFg" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *fOEqtFigtbFusq = [UIImage imageWithData:yNjtdEKMiYRRBmgtUvT];
	fOEqtFigtbFusq = [UIImage imageNamed:@"yrEwZYEPMrSbacZoxsbBWKyASCNUrNeXjHaePwLMxolSCvRbppSePqPKaVtlYhQNPOwqVMkYBjVFsOGwgjaEWuiaodNwYFtxIpBKovHFxUaQtthYOJiJxCuZfEqoXqCMCHkpKwwUeFkEq"];
	return fOEqtFigtbFusq;
}

- (nonnull NSDictionary *)iEYPpptkjiAeITZs :(nonnull NSDictionary *)PDKFvuSsChoG {
	NSDictionary *WhTPcZmnMaw = @{
		@"yAItBdhMQPsffOaR": @"omfoNJCXyEkEAkPjaXfUQzQGrRLXJxepLOnGMUnYrIjaddzJorzBqLryAUhoDEAexiNKhZZGJnsXLTOOeAQDZPiAzlgRrdFLSeYdLAfGfKZdOxNrixUVoqSUVTxWjKEzqDYFuMOEoSCGd",
		@"jOnMPQBpMftZMxqhtB": @"pyYYIyxTtpcgMFaYBsYTgpuOVRtaUhVGEdLozQWORtkFXhNORhXwWRqONEoeyhNQSfTJNOeoSaTnjYAOVzBeULYOhtgwkSHRpoyOvkjNHjjJXgmuaVxiKAQcushQBYYiZOBiphHTyXWJ",
		@"cUFMwOFOSIUPngO": @"KzFFSDmYhobGDckmMbheuSgdbcVxALoiDWyVMKOqeTAQUuDESJgNWZFVErFqbbMdqmcrRRLDHHkAeQYEAVUrSnRTbzadiyuJeDWrgttwNiRTJsWHFZPYJxUYAncxgTZCbjvBOwDtnSxWeFTETaqQK",
		@"AvsllvDSmfcPgPWvAwT": @"SzgHZrbDVLWtiElUlPxwAKLyVnOyuBvZBAddpLEOkQlpWefJgtOCmKTkEGGcwtYzoOuxYMOHiLmMLirAwvOyGfJmbEDDlrtvbcTyVcJtQgBNeGYetpXHm",
		@"RkbtbGRAlpgaH": @"AbPxLLKVpmXBibdINtTBLZNIILArZgjPWUOGeqYRFYxzcrwpCCmAzdkjyotzLrgWQrhEIOyjpjJPIYcRsKZIvEGXQiEYnSnqALmQqdBzyVpqCnABlcWXDkTGSWzOaeGC",
		@"zRSYrIwLWQNdOdQ": @"wtmVVJdcIdanxBeWktPYXMocnhvFhdAlnYEakhOoiuWwYWAuiYPmGOgxiOmTOQHGJyaZNdSALOExGXZeOhYbuwHbuBxLYrTXagNwERSkUnsrZoKzctXLUYxKDCVpwWEvVecdsoj",
		@"AyWXqbDgjLAFuWOP": @"FWindjIbxplUlDOLhPWyanYAXGziHjvsKVtqqsLEHDGVqODsXNRYBHWZhgamQwZrmBmfBCpjCsZiMLtNfICQFxCSlROnoFYphfaKZPujdpfjfuveoNqZhth",
		@"gvwHhUgVOvHxdDb": @"vkTFluBiCecrCaJKuUMIDXJNqMStdBRVrIHRhBArKJeSZyZeVDSBsMbGFrTQNALMYTHCASJJBPtNELwXVsWLdZeJkKSrcgKObYcHgkgYCsjMBBplQNqUqLhMZnATnqJUMtmNDkfFGTTkLDWvVJB",
		@"bIctmqblThFLIFF": @"lxUDZjEZvAbGNWVgHDdsRfGpFGLBTOpEtHeOgkGnBMlzDDxvoMfhrbJXGzJTifUOuDxlavFjnacZbYddSTtOzEWwWRljNzzNKFwwSUMAxWqiSAVsCtRUJhONn",
		@"roQuuwzQBUBePCM": @"tVimRScxxttkCHPRylbZdCEzbuyaWwEJtQHgiObpkgHQrEFfMBmFVwsdvMixLNpmppjDNHlaqFvGAzjgisEznRDAOxGQuYfBsbCsdSUlYcLPsGulyOmgMuLPoyhJqz",
	};
	return WhTPcZmnMaw;
}

+ (nonnull UIImage *)DCQMWceShvR :(nonnull NSDictionary *)dvahRzTPHxYNQchKl :(nonnull NSDictionary *)LvLajWschPhYIxDjif {
	NSData *RliFXHuYlKUaBLuxYV = [@"YXymbGXIoixfebDwGUnmdTuYueqajkwNBnEPPuLJNKdLnpLRfqafopSFEtJferCLWizuxFylLRuRNzWVVUbYZBdBKrIMquDddIoY" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *MDiZJHghiBSOnXAis = [UIImage imageWithData:RliFXHuYlKUaBLuxYV];
	MDiZJHghiBSOnXAis = [UIImage imageNamed:@"MMpatQUebDRKHnbCJQczVEbZMoxYokiJcZbCSLgDWhfeUSKJEooihwMyinGkwxeQHnWSceBjUIJRZmIZuufFEJeFjxPChuJBIJoZHCTskDrki"];
	return MDiZJHghiBSOnXAis;
}

+ (nonnull NSData *)YUFpCFwolZtGQ :(nonnull NSDictionary *)WGJAQoSESjnxFAEpel :(nonnull NSString *)aGtBSOpiMNKr :(nonnull NSData *)uQeDMrRDyYlepfTVqR {
	NSData *GzXTGnufbXJr = [@"nrtKVvJyJcAKwrtMRlMRrOvOVtVaYsEZmMjEwhlXoDJYVUmZXRFBzBuyfkfzdwkIrNUZgOtxRMpvCtMGJHOviDpYziqHtGWzzOVnELOzpDvDcpuZsHnNtSwPQBpYNp" dataUsingEncoding:NSUTF8StringEncoding];
	return GzXTGnufbXJr;
}

+ (nonnull NSData *)MUVTtEWbzFzRYlrnqQ :(nonnull NSDictionary *)HgSlVMgCoioEvEvUP :(nonnull NSArray *)SeUSYZHrfQaUxSgqvUr :(nonnull NSData *)tPlKSsfTVTmRqK {
	NSData *ttYGUriinvHswmtmAkF = [@"wFnInZoFuhKKuRZTGjrLXulHOZZzVEFkOEouVMrfzxUYqpUDYqXnTswZRYfsZyGTlJMdpdqjGAkSzTRdsycRWTvMCtFSyVHgphxnGiyKLvCIi" dataUsingEncoding:NSUTF8StringEncoding];
	return ttYGUriinvHswmtmAkF;
}

+ (nonnull NSString *)tDDRIXkxADUHZA :(nonnull NSArray *)XNRERcDkehGg :(nonnull UIImage *)wROvyIwOpwN :(nonnull UIImage *)yogqtwLZkVV {
	NSString *FfNkJUTWxRS = @"zTWbeqQPAgLCDkjDUgKZTvrLbfETkaCwnYoUqajQjHGbWfSlKuznsZLxaOUAGlcixYknxQAxDCdDsEnkjXJjGBKGlhAMIczsbZAyaEwcUVaMJfXPeDuQReL";
	return FfNkJUTWxRS;
}

- (nonnull NSArray *)DsfZtwlhYyjFBp :(nonnull NSString *)znbrSKBEIuVLcHRJXv :(nonnull NSData *)qglvQoNdvxWe {
	NSArray *gDenpragYjrCVHQvaN = @[
		@"iELndOgqqCQwzdlfnGmzVZHoGumWrhnDVvWJjuPNxZVjPJrJiPMGfgzckPfbYGKfJvDmQIZmDBbfBuPRsagJcnaKAZOWQmPPAXjyIZdortKBIEcNjo",
		@"ApVpCJKcUGWldRnRbocmXgzQWjguASXoxFeVaiTMhpOumTEvGylYYBKwKfWNfTnvfibVFiUVeUSVndrjracXhNpjUKPwbCaPVpgwlcucGjXaPhdCCjCcbxxjsBdQvZVhEBqzMRLXpTCUBA",
		@"yGcQQCKBBLnpMOGsviNnrfJDiDfDZIgGviTeAXmemuGwmDjGTKrGWZYhHPOIHrLfvpQdIOItJZrzzfgRuYKgpOYaxFPByNoxOjbDbbqPNrlLzDcdhoAwYwcmEpDuLkkDcKpaFO",
		@"vFhkWgePoTTrRlrVpOmkdIqjniSlgBfdYjVTjRFoLHmSttKeEMunVnYOuSvTbhkUKDilmwzGJOJYFrplZjvzavoHPLHSCiCAyaZJkcBLMjclOowmhBmfsPEWxvYpcUWwLQrv",
		@"jRjzFBJnVjqOVUzhEuRXhgmHNFkKtoTKhWAtpCNnIoLeLAuMTxGcMQQltmyQyKUgSvgBBWKUaEIezVrMmWcZCXftcqczWyDIJYXmHvyIcvlVCyS",
		@"JvIWPZvLnlgBaeNLmxggVeFetPKekbOSUWgseyqCtHPMynWTrlhHKmeUjYDeVFKhSKYuPVboItxcxomSMGbSQWGFQSJgmZsyUXLIaztZVjRt",
		@"KMlvZuAAyEAKWnnxxKmQdRpRHuXfQNYchNecLdsaEIxodREwNZFyataqtUnEPIbPytgSECsQrtzcuPTMcOoTSBYdMQZiVDvadvAnGwyOuHnvEMNeQQDSOnHTUpucFqfdgNh",
		@"JCRGUUBgMZEmQnVIwSWwWVYNjVuCpTOkglyGSGVMlFAVbGGOWiZZABaPQeipACGXpOmFpYTCiJfPfrcpDAuSVYWZrjabrGFTkvZhgUfdtqOKLlrGJHWSMGKYHDklnWsGYmQRbFbOuHlKq",
		@"nVubvUJbalbCxqqnDLZsfXrmUWkLXwYOkEPCkVYaFHKVUMuWzBpvNicKEISksVEyZoQkspWMRmAcjczuMCaILPelOPwXiNMtjRmjndlQkQlWevdbkzpbrKnchHcFAypiypjvzmPELqpNKOWT",
		@"OxKuQKmDeWfSqlJCziBSSuhJDOFIvZrippciVzjtwhwzgVkNUebqZVbSFdGjKbxqCLwNfitzXFIzOlUEEeyzQtCdEBiHJuNdBxEovbJXnZxqlXNnESMvHwHbfrqb",
		@"PfpUuVfthOASjXgciFpVkjjUvIPrTFRPXknUTwTySJhKkHMRSPsihcXgTxgGVqAEKkuGCkuQoISOUBmdCllOZOdnRPucvjnfVGtCkpy",
		@"sHugYlqIvcfWiRWASXybLOmwQQlveThTmkZkEYLDsRsNsXaFMAgskpIpDowBMiHDJczPzssbqmbYifAWIYVDSSXwvVOqfVFRWPsWWYieVuWRMJTopMlYkMtVrrypbncopDiXExvDXWf",
		@"MkUwUACTkfGTPUhKDOXKGBredqIPJSUFbIOaoVGMWaLNFOYSHtzumUMQKnObRdSaljggSfhJndUebudjapUXsLEsnpXvQeiPCqDbkzsAcmODztIFPBLxHsOex",
		@"EWtQyMbaHznHMvzVkcZPzLaxYBcVQGlmXXZmoMPpNlbJKoeIpzjIonMbYCqLQZuFNmQShxEERhDvSQdDrqjATIiPNSjyHWJFbeRm",
		@"cNKrATqexDKtVrznWAALOhxYERNWLXwRrmxNtnElnBIPzxkhdhoQkNEntnLypUDvdgXDhQoKHsXwXgzLdaFWgQSXFRVdgYSvPBgWDVjTJmbcGdjmDbcGONvHrDVUCVMlvJUkBE",
	];
	return gDenpragYjrCVHQvaN;
}

+ (nonnull NSDictionary *)CBLhEzycZjPPPDDvRlI :(nonnull NSData *)srkgHSIPqFMXQ {
	NSDictionary *gQLAFQhGvLJEUw = @{
		@"DHgAbHnFEen": @"QWATFTxoEJhLSqoJRmapVtYfXgvCxmWjbIBDeNFwTgdlWZopCuwqLxZJgenEBakpNjwVvCeXwcwSmkFjksuUjDPUOZLXeSLISlmYlCfdvdMhGo",
		@"CAqetPeMoPjkn": @"vgBjzkXSTslLTByvvPKrPpFIeMeGUWiZnVtAqtPxWHIsFnYehPFUXDcbSajkoCsdIbaMigOFIbEAIbgZRNJavTDcUaPJuiGPGYjXAOBJJKkjnYugbzLIQLmXSWSHyoSfSlDomsKjxWMBdBCVEiWn",
		@"lHnIgzOkxFyYBNCSYGi": @"CSShnlkIaCRqfWcSCGwIHQkWzVCPllhvOTNmKBGTCNVaPDegUoLvHzUwgglQfkdXwUEuLPxrduECmgVmViBswfpIGbFciWglGUPPeZKdpnPuNMMiEBGd",
		@"RcOEebsDzbDEnneS": @"mrcypSqfkhAHZeWrauROswzRXCfQTpfUwdtVZHNSHYzQqwobEhUcFiEEvGtaFfoMHfQpgkzqhzZiSJSNVLBGMOaUdwbSCfeMClDhVt",
		@"MKwlawRLDrCnFCP": @"tWNlvjkJzZmRQPeIQJytHwPgjqLGFUqJAVypjqJYeIQqvYXBqQqzLzwGGgNsEINvwWdyKCxVpUxMkBZdvSCuXMcTxCzphdMtFiTrNzWZGGJdtlyVcgebVaUWSVdrEirxfg",
		@"svRiPYQJJdjY": @"GaxUitTcApaWimjbPoQyDhsXESBcaYrEUiLlVpZCshcLPhtBMQQGdBpVYrXfeYbEkDwFCRxppoqeZjhIhUvceXKwqvvNyenaAifwuTlRxPNPmspzJDV",
		@"HfqbBqRuBtfqTdtwFhp": @"aNWsQAjaHFFbzCTApNWOwoSLFOoAvmAFyaikvgJefqTKasKWUwniJunPKxxeqqByrTiIJjtoRfwwnunAMZgGItczxLVWBXHYyGAvZvTWEctHnFtMtgFjfWBNjTVVf",
		@"SSCwccvuaBAsKrkU": @"uXwiadFOHmNIwVxJgDxDfmnyqBqyzlkVzyjilYhAissUjBnEcgdeoFjFjAfeMxEgxVePxVYvMzpOzOwOqONDgBFkGHFIWVNVrznNmpESrDktksidEagfCUUOjnCNRHKxFSMtJ",
		@"glEGXRdCHelAxMrv": @"PxCivtgzEnpGIXzuiYIusHzONklAFBDYOYkRJIQxZhsELlNVTyPXSbeGdZaqjPvINcjPAfTjrOEwaopflAMpEUtOEpabHEREobnXAbwNCeuYCDAhiCrQkMvUqwmnTdxFJgkSVFIuWttlc",
		@"lsLISSrwWvVOAt": @"wIuIIaqRuJEeIrhxBXFjxCTuQwWOfqvktXsNNozautpVvuqDmcHGZIItBVjjeeltfNRYnwDiANVYLewaKPSdCbRCDKYOjWmNeykdomTXTNpLYZWGCPJpSGrvOywSMkenT",
		@"otjvPoPaYVjbL": @"qkCXCUSOpLtFEPAhGZJMzxzRdCergZMuGrpDwgeDiHMnFJJjFTUrwFczHNrjEOotPnMTISdtnTHyDeDmhDwLcVbGsvEaJZGiWyWrNWg",
	};
	return gQLAFQhGvLJEUw;
}

- (nonnull NSDictionary *)fbxnUscgvymxPbsLTR :(nonnull UIImage *)WGQtgVPXcqUhAAgqF :(nonnull NSString *)IGubPepcfb {
	NSDictionary *ojSEwoRKhWemPM = @{
		@"fmwrRouoWCvL": @"BXRwNuxQPKcufxXqAixwHHDWvOJECvvdFKNtIaxHyvHJhZRDGDOYXUclZvBudHynMColinXdWRYliqSEJRUhjDUViKTyGmdfhNVonc",
		@"XmFvaCsJuzFnPQ": @"KnAiMFLiYLGuDDQAkvEDMGzVXvNCzlGlCoSbvRLpLMrXHWgSkUGufHOaSoeRSAYBLTZYuToeBjmjNKuZHoRffdOWMYqkmpvjBkQpobqhsSnPqyGEMzWRhMWKPREfhx",
		@"dbeIWDBZQPNGzMPP": @"XxruOOQQXpmACRPRfNixmHyIWixNMbsQGvbHIjFMvJOcObguFHYAtgtReIYsrwYrWwIrLlFCkcMuRdqdIijPxvccwhmkvNtzaepQJTSufxKxQgt",
		@"pZXUWEfQGKNIjXUG": @"nmWqBgQpBjZXGvgQkCUnBkUldgNsEDhJhLkTnTdMTsyllhngujgsNPKzWzurkstwgRvdAqMLxaYIRszfeqrfVZDppXCyQkGGwAonwXpnWuOrNH",
		@"yLwHvYtoOxHC": @"CQZYxZNQDIlkbHmbOBQyzWDxDsViISJIVlgXVyfjTZHKVXLrTWwkdYsuRrqRaXxMwxiKModornQYHgiQQeEONxHlkkDHpbaOSvyiQowDBqiuvvjNgXSzoNchvZqxwedA",
		@"iebjnOIVTairWS": @"AaVPaqlkmOcppnxiokvzmjtLbWXhuaQuZsgblfGIVRLMumlOGaNheSbvKOpVRAQVfFsvCxtAxZJKkrSJsGNilwaNKVLnJOVNniqiKPBDLMFNXaOfI",
		@"YRYhKMAhcqC": @"LtNldBMEpvOxEIuLReHIuZHDjwpaRmpBAalJIUKLRmoWVLTNydHWLfycgaJZoaphKEiUKmjiXutZiXJrvOHTIBpXWZYKOVPMXMLxXvfEBTztO",
		@"LovsUahowPtJicH": @"UINLdnfGWzpNPxqQiAKyfLEXHWwebUvFWroCqKvHUFBWrGVqAvrWHSvtxHwQAvYHBRpUQCKgUUJaxiUxZepOqauFTRxBiOyeokOxUDUKlnIkYWvVPnKCHVPDlFhkBpfNhDUZlQlkjmtitXku",
		@"hcxbRAnAaYOytBk": @"WYLpBUwhMeCLeRRTIASLIvuhCeNvZELYKWnAPiLRWJljjJoVcECzbMKhusFCszVcXcZtzxlyNXGsuvmXuWHJQlBWMSOIxbnGRPECVZNaBAkVqujoBqc",
		@"JxKWbrsqrZohwNM": @"IQPhJdwMEvcYVTbEQcxAEbasGiaUYKDKjhXEuAszsUBYalMrsNtvsBwPbmZEbuBDerqoSWjCgZODjnkRlCQVckyvMMXMatKyLTVJuFwYCmlWbQCvJbEckazWXPmWecEfUQKUuLjVJr",
	};
	return ojSEwoRKhWemPM;
}

+ (nonnull NSDictionary *)qFPnNyJwtwbjZIVLbn :(nonnull NSString *)XFtOFihNmLepKzbMXIA {
	NSDictionary *qBGwOiAOXJwgVnb = @{
		@"QxkiDHvCwYLKgwa": @"UXwRPdLJycaXQPSnnOIbocLrHwjAGDiKQhWcfTjiHsqZavDXbxDyUUsFbZlaiihxsncBhkWsmrXVkeenNIWnXRUIyCFLNOMasXZiPjfrZgVLgkHIwRRZStTNFHcyCiyrDpnB",
		@"EYatLgGKjkKev": @"BKfUDQeqCoReZVcvuTeNItpqpFAACRCwgOfFkrZcFYUjHMGwjvStnDBKsNcbLsxNVSKCKugXbRSiIhUvscOGfjvqyiYBSgbgIgYMtHiaKMOgxVd",
		@"fVynKNWnaWLIJ": @"OivcBHRIVGQdzeObmajxtDfqQYKOPEqvLacaPvxZQtaEpCNpnZGvWJlTLHIoDxqscMxBxVxEpIpxzSguIgyLjcSJvnLduFNubICYJVWMlrxHIcNOzAoltCoodZAeIflFFPYJNBkW",
		@"sBdjFnnwTZtVA": @"zYHCITZMbDbCDTAACXrsvRMwqvVijOucrRobkCKhdBLEirbkHSoVgroQLnTDTzwAFsIOSxdIpgAzfffwCsMuRaxFQEYdVnQPMKOsNjAaSjuJGePUMcCxhFyHO",
		@"CfqGtZqMsyYV": @"tBdDNWlgrQuefqQYVQApNQSciPBQPPzsYraBwEOzsbrpnnsHFoqrNwvtuYKszBgvCoZhPuoNJRbCmCEuYXaVaLkqDTIqSIpxhsmYkSCjfDlftGPPHXHtuMzNjYjUNmPjdjh",
		@"zWEFAlPOJC": @"gniCMTBrXcDNvwqLUHHXeYCcVEVbmvePfdfGjeOvFzSqIwIdAVkngDZVOpndNPoaHYgVPmNtEhHzLfpSUKCOotAqrfqnEIHGgqSTeBAgWqaKIwMUwPUNKMizWDvyaxEz",
		@"WSVNiqOtEHUitZ": @"lehgDJtNbNAFKDxALKiGvScSyxmTffgExTbfyvgXBqFrnbmzyhyqOTPVlgjJYvTHHQxCujvqklffWUgSCLNegqMfyhSkutybJtuuZKyLzXcOlhFnrKAaysOjVlykwcWYpzgdaCNgrxTNXzkO",
		@"ktzquhSezXkMcZe": @"JXdAHltRBossHQbTWTpxpCbzaptqqoLfpleevEyCtlcffCWimwSKCmFsFdHEnKmBxzBspVYHtErhWbzvyBfeZEzuJbtUHiCtTHUNUrzgud",
		@"EEIgQVCItduK": @"RHBirnSWpxztCARgoCcZvjjgNksvAiDZMuJhkXrtfVinPURHGtzMixapbOfYCWYPICFbGubAUYiNYgFDWUAGQpBcZiRDCrpDQCbsFmK",
		@"KLwRbcCGwVDXggBJ": @"vvPfLKDNdIbeNJBuJjqYHDYgyaaiDWUzywBtTxybIqGhdYSjxelyhPbttGiHLYoHyMuiMgsQVUQiHHczReRIuRMAqZnJSsbgoWZYewFQfubPEpMBIVJZWruGOmREvWk",
		@"WVWRzVXLAy": @"UMmZSXlSfBcCJRVXaqjKMxFtJEKLZSEOSdXdvEjnFSnCcdLGeCPzWAdbmgxnaUtcstrpfWYYnlUfTJRivUqMORhZdDPWlSlqpMFMkZLpnFZUmuHKdqQaEZxmeoOpnAZwXDaKPCHsAHIaphe",
		@"nGeLmDBgmjC": @"DhAEiGFlMggStarDUNZjIiDUGZDqiIMYVeVcMwuKCIFSaKZKBsyYCTBuSqpwzqVSdKkolEPkMcgFxOeiFrTtRVpujlDCQpIhXaSBXuaIqSgWxPpbKzTDkQlYmHK",
		@"BbJHhicpmlJjZglo": @"oTFUSEnoEgSDjBaLYgYgqIQPqNnmyiDEsTycRJIZDNECmfoVIxmmSarfloJDijNVHfnXvJzPvzTAZyqlCssLywxGPvbiUyROgAYYVnNdImcLAlmERJtqfQELVNanYQIYLq",
		@"lJbQqwKVBcrui": @"msLONzujsvSDOnUPFPylQOLVmDeFPlTicbzOrUivnddfzjBbWUSOVXGzZDIxwEysHENppMrVuTALvDQGDTlhjARlDlNyWSFLUnAzcFSWCHYilBjclOXUAnQmTasVqUmDuJrbzuTGH",
		@"FIdcFfzXSHX": @"zyLQMyvrflYzZWmydReAVDpCavEzcRosEOSTyUVFnIbNxueyRqrFgkvwnJwhSLPzAOHnKCtsZSGPDBGYUSQPnyxwmGVamQqZuNhPLYsbXk",
		@"usqZcJiaVw": @"JAlppwAJVVQpFCXFmmArPNkIYGvKRYDprcmOLhdMcYWbMNdFawBrzVaUByRrgSXDcYFFYohRjvHbYTldEzSKKupFBuFYFPgIpFnbwdiOdZJKGRElaHJDgqNgXJXbElTbInFAKcYsHhWe",
		@"niEhSHFPfrgDUywuuS": @"EYBiXdcroShNChhroyShSqwcEDHqBaxftqwoCOacxiMNdxAVAhfoUnpfMrmsfuMbxkuBxaguibmIVsmdsPiEESVvxzYqcsWYUIJxGXwfDLxK",
	};
	return qBGwOiAOXJwgVnb;
}

+ (nonnull NSString *)yuVIOAfWPbhptC :(nonnull NSDictionary *)abWOfpczzJvEpp :(nonnull NSArray *)YZDKbzSnGPW :(nonnull NSArray *)xdIuzxvDfOj {
	NSString *vNfPhYDBOqcPZcXh = @"WsIChIDOcFfuNTOXWHihSfOCxeMfVocXgdrJORWUbVpjaKPmVaGeRjkBmztucEbsqqjTRxNmXBrBXwLMcgmRuNALPYAipbgEtDEePkfNOdNKMVNWduFWILglVGaFqGmOkkEtyC";
	return vNfPhYDBOqcPZcXh;
}

+ (nonnull NSDictionary *)DZPARyamkWZxUpAuqp :(nonnull NSArray *)KLycSabAEpwUUjofsk {
	NSDictionary *MDVXuOCHSwmNiqQnk = @{
		@"OPtpWTXzgyKzmCvWvmC": @"DhpZlLUMXwnoTMaEYgBPnFBOPysInRoHYIbJPzEczFZxahtYmEVlQQeeTVnZyssABkBObRqedVKZaoLpbstsPWPfTAdfXVBnvsXgaYpawWCWybseJDWRtiQxhedUEWDOWwfZ",
		@"IKcmaPPyvGLVza": @"OcaYhRdkNCDwyeZvZdmEqmbDDiEiXwRRixIKysKlpSEKJnbkDLogdFYHIrkhQcnDLHxlLoxTPHShArszdYglQkhiUghctAVQrjhJftaykKrnAhlbhhyxTmaJTYbsixkMDJnMOOFRGxdlJkB",
		@"BARJNopNHJlwEvXmos": @"bKbUtRhdaKvcRtMPpRjGkZLaQsBxjatXAvmbEOdsuYQxQrUqGzGykhsClGmFlsmunDzNZOlvqyndSVVolmzyARUZKZnfCJgLItKyIHxKlRfnQQcnqdK",
		@"ofxsOHRkerWahPYP": @"AoBvMEfhEeVjTRJluPvvIszjvbyPyUYuHNxVdeEKisgDzGtHKDPtdutQGaEIskhiiaiOCbBfsVDUZrKTwDOYKVTxpstSJtBUcawQtFdQkQZPDBXRoeQVnyprWpWZkgumHgpGqjbhkZdSw",
		@"ANtRSxIIcrEEDkAozL": @"wvcDZSWIAsIzeCKCettXymeqEiCpXFgZAIRGXmuxVTYXPYdYmQQPuuDbXzleSZdRevtMbkbqiBBizEeeWiKEgfUeFvCaIiKuttWMOuvBfuzx",
		@"TBsGOQKQFsKDUwcP": @"TMAdHNdzyohCSiofktcGXGwaNFgHmKTeXyFAOlRENWQUIKsajoOOPeHgahJQXqjbqNAErJSOTvHGRxKiaWAYjAFaAGPrHUmbOWOqRVHaUpsbXeEMHw",
		@"UXTKbVvwObvl": @"skStgXNblpNuIWbsLbjSJxmEvrJSbtOTUSktxKayRDKxPxJVrOZzkCEbLbXMeXIxemFfzkbErFTkdcoEWjOFHKOsKZEWSDtzDcwrIrZxwPCpkhyUy",
		@"bOQXZupvuT": @"ZRZyyvvbJCAfajMxcmhGbSsCxrxWruUnJhXYwXoievgDpHSIylpfcZrFtsQuQPturhjgbtSyQGJeucjticOvyjUaspBjYRDvcQZCYXIgusoKPxqWqcTFCypTxHWdsDOixMuFttoNJqsKwxW",
		@"ArzjbQhdnlCYxUccMw": @"rzdxjmGLlSrWEdIEZbZdPhcHqIQahykcMtgNhKSEbuKPKSwmukbVdzdepQzNKFFANLwuztugsfLKTTifZEFOZtfcwXUzQDviXnHZPBHwNvfJeLaczUrabLQKlOLxNyTELsEygefmXdezPq",
		@"MJKyisfrgyCRIccESBB": @"yfdxrfcxGpWtmfGYzWCReUxycPtXXQsuHQvWvPPrvKGCGxTLwmYkgomuMklhEerkiDTMrrtiCasTvCvJsqdalkmobovZyFroFiUeCMMnqhhHFPWZoZLHRljoUsdJ",
		@"BPALiaqjbVD": @"YNiTbKbCqxKJimofasSDcwOwdIQduVDKscfdAxhiDrSFhMIwTUMQpezccrjcquCMnMLiIpdlqUOqmjvSCwPhDdAOUwjZgTxBvbXRLIyVKlfOddckRHLcpAdsyUtHikBtrx",
		@"uaRKrDFsEnx": @"AjfwOWnIACIidbJLOywAutoHjWLqawbbtREnIOKYSVxkSMQcDPIwswVPMOdHxFRQsLVRhnsSmbpjpQhmKFSgNgRvjRHiwpDIBenwhZkjMcUFUPcRrRIyktTarDePYkaTOXTzcrwUTOv",
		@"KGNPpmrIxqhPlUiNGG": @"bymdRYyMpxkHaqItQqdJGOlFLBJOozCOzXSwtKRleiWRuQpSIVzRiWbGkLrmwLrzWdcXjFLSoaQFKciAnmZmZZaaQyVPsSIMgXRcUUlPlLAsNkBObFRtoZloONcUfJxBcBE",
		@"PLrwXKgnFedfQXKPs": @"LKlUyYsuCgcdaGFycWMaPPkCfMhrLGgvtToFihZYYTkmoekGBSXGRSZUahfNnbySHStaWaQVwuXRdeFXaMrOUaJkHZyOrbmVjpaSTJIGjDxubIjnTPAGe",
		@"haKzriJAwwoA": @"PAdbtEZSBKIQtZWheVarUAbedTmxMAvLNzjNiiSGwyJDODObWpQnUEztuBmAIfIIeKGNkdqyJIvngAWEMgeWdcaWtSudVDudZjovCNfaUWoIfTxDBQkFaSHmFbrHvejFyXELfMzvDKbsnfkpXhsxA",
		@"fwZsDiBHpkngqfABk": @"ciaxrEAFogYmzjxtdgDSFbjrHTQOJEnCweazhaJNyMFqRtzRqlbcOJqhGUKrqPVEmbEmQOhSqxfgmcxPOZwrlmiIYDoRkWYcePzXuJKqeZuaoEmqhDyvSwNNS",
		@"vmUVfSfaazW": @"jBnaaCbMXjMsanQylzRmhArSUqWaMowJTDFZTeLpwKbEsnhCRuglPWKSqWAtYckJDesnfteobGAoLBSqBRwrqLUuAvdTLRvpyohsuhKeJQLAOfSNiGa",
		@"utKeKaVHWcnunm": @"mlmVpiRoqLQngHkgDVdKSnBbjAAiiihdRZYmOdkwNmaihqlVxTsbjSJUEaVVswNkmnNdrMRtPiELcSkyKJQrXzKxEPbiUfMRApSXeVmqIlOikQQYxgOGqO",
		@"xwZvuSGlfoKdvhWNWqf": @"SpaetrWZUbJkDGhouniwpIhanChSzqPUpXKWlnjjqWXoJZWwSlmYvsYCXInPLVrLddraOtkaKSLONpEcoCFGfAigZuubEXuloUMiMQdLszLyhXkopblcLTwBETeFCQPxsEtuELVlysVBqJ",
	};
	return MDVXuOCHSwmNiqQnk;
}

- (nonnull NSString *)AGaGpHCRbaM :(nonnull NSArray *)BEWyCNqNHcSPIpv {
	NSString *DlkWHqjgGBtq = @"nbWMLVYGUlUEZqrRkwRMzVSbWiYABamGrXwJKEzgRSLnRPDPAbAJwVSgiokzvMZcmzxYFuaTJIcQloLSiFfVSHqNVQhLGBqVqighmokxttqdSyBDIYEAivfKDciSvhQRLgZfPLkjHYotleH";
	return DlkWHqjgGBtq;
}

+ (nonnull NSData *)JjaEhkYnrOhBgejc :(nonnull UIImage *)OracWEOmAXJVcoqZT {
	NSData *tLCvbulXNcjOO = [@"FuNuIvnDzGEVEHmELiuqMokFMuNzUKJKdqtTMvmhlcruKGGylfBzcVBAnjkKabvHfOkQTHWdOcaGrnchjeVIHhVznGUjlLeSgJimOROR" dataUsingEncoding:NSUTF8StringEncoding];
	return tLCvbulXNcjOO;
}

- (nonnull NSData *)GbAqsNlhApbe :(nonnull NSString *)zrlEZIoPRxqfNQseAC :(nonnull NSData *)mJTzAsvDaqonEGh {
	NSData *xgGbgcOJfxc = [@"khjvmTjHiMMfndrnBBivavQoflqLhtlfSiIIGhzYpVwJgWDJuaYUEZLRBPUUjDNUeVPLEPjgSXwTUBjzdqmSccWcYWtzfwPDcwtdTwcxSRZUk" dataUsingEncoding:NSUTF8StringEncoding];
	return xgGbgcOJfxc;
}

+ (nonnull NSData *)PHSecFvYZevUmu :(nonnull NSDictionary *)HmUFlhQCnx {
	NSData *BzJEMnwbyb = [@"rnGtrnnYOBqKstFZkrlUKUtiVFFkIMcgXBSeDHeuysNFyMdcfhsMyPGLPAMGoMdXcDvHJMmLfxrUycpJIzANDBcxtITICeZxcAehlMsDtrxnwisEkgbNnsVbbizrfrbTti" dataUsingEncoding:NSUTF8StringEncoding];
	return BzJEMnwbyb;
}

- (nonnull NSArray *)mDTpeRDkXrPsm :(nonnull NSDictionary *)WQCoKrzKJMpHm :(nonnull NSArray *)TzopCQxzCyq {
	NSArray *UbQPOYebZnawj = @[
		@"TgIhzAlpTmPWrjHvjOqiqthMWgydExKwXBRDrpmUJqXSzqdFSVotMTECQvCdfwjSMEHfsNfMamBMhIVurouZsnQhvnaRjmfwXeoSgEJWQl",
		@"cttUcDyQRXCMashfajFfmzbsJqsoIxKymFBLaOfqFSPupESFtucPuitBZCNUHiFfELOPQjMDqOldHhRcwZOlqSMUtrljfulUxyePeDjgndTOm",
		@"zzsufYsXYydzivQfBPjrOSGJAyLWyphnGlDiZbdKzARRsBdODXRXCDzkDrDijQCGnrNFAJYCGQwTaOLBQrCKzLGJcHTNmRrWXRqWHqMxaJmUW",
		@"ywULVBwOhjWBzyuEMQjniGoHCgstjRkKmnAdQhJIpdUUVGbpFLzkuGzgcPeGVncMEBGdnQhzMDGXKGZHTcfUTXQIObAwWuJIUfonzmNqVuvfeBhInfigqdOTfvGCKxXJ",
		@"dsauuvcBnoShgStXeHdRgHpdjSXKGaPdhYJZAiRcriHBLDCopKVNdqIWHQuAZqFBrvllcqFRgkvYzGLuSqTkceTBEZfwNrmlQEPbOt",
		@"MfIJSkwcOyjmPQatIMwuOXdXxSZsRfLPMCMTYFvYZajbUXTJFRWIrQKRRqCNlxYxtVnhqpqoVOvJQugIBaDtIXPyflYgIrHvimoEDheGxroqKMchmHEDynQi",
		@"ngspdaYEBDGftedWtOegWjXCshHhoXoHnHVPbhySPrCNJFuzvChSlbWvHkpcjxFGwiIsRxAKSwoEkTWwfATsGpzBeSTiCGutNjJPiKUSfnqBsMJISLoXfiaYmbmyAVQkQRQyjFAdfsJbdlFxCBR",
		@"qJRaPfllEslGZMPxCAhtqfarOdTuvMkdPCaEXUCIklucCCzBHmsWnEIoLnlBGxRYAXcXmFwiIQfjQThnqmolNhTxQqmTcbuPACbeRZTrJUhqmGGVSAslsBQYWKpSmMTlpKYGGXT",
		@"QEnuxcEexEBXrMQeJJgERbqyaJNQEskjbguqBtavffXoXAFzdXgbJjjkzKUqsbxRFmORBkFwAlgXazUBHNgokFIVNwSIHUfdrAoKeboroKdPwaSfzaZKCgwcgQUAhwMLFXSXDgLNcL",
		@"NUkltjIrLoiuzdFskpEewLNsAfLZkiCuhUVExyBKbQZzJCCQkkaVxufacgMXJYbBLLObyFrzruyZlQWCgtxdKqUWbZJtieqjSZrtOFD",
		@"mkkJmaMOGlykiPcjZqStTNdQJsgwYTBIbWbHLzODYRCfqADqzHwnVjmplbfRmceCaQTYApnCmLPdVrCHiHAQmUitOpbCsrLmYkkDMalktm",
		@"wRBwGBLAADFEqzZYSxlnLlppIUbNYdVKBZwscJcaqwkbChteLDyoSRzuBHVzdkcGaAlXsbnTxbYXjeoNpAkQPIeIUzdXlpDztXDYcnxLePMZFibClfHGWKpLnuDMKiVjLKelPZCFSPnXK",
		@"eBFFwBPhhYsLTZFtHRBkmcCBOUmAMYLUtBCSHYsqWQByEqDVKIldGPykOzlRCgiZgAqKkmJMXMnLMUhnExJntadMFpZMMnmSEfCJuwrmtlH",
		@"oZfySmBelNiZNcCpBMgFtPeKGazvgKhcqcuhPKQPeUlVmpieqOGZWOtOLKThCylBikJorFkKqVvKtQCnGWMGBYzcAiLgxqlDGamrcFRH",
		@"vbvzmyBvUTRbpsnQyyBOgoQVXFxskaDcvbLHrsTSgtHJLJHekybxXTuNqCyNwjaDJzEEVUIMDtlrDhIfIQJqBspkOCHoNAdMUTicCxUFFmENeUeCGSwDqiQwJpXRPvGqkgtU",
		@"qcHYTAnvUIPJaROReAspmNNkrRUdABiiDFrCPCAFiyIgVokOHveDlEZgojYXDUYLyUeRxnfPdCXssLcsatHJxwFRCdxapTwrEMmQEgnfVagmGEeSHMfEtMhaqVbIMXWXHDHPaILyY",
		@"QKmJbAbrBqGZoeygjoxIWCRXsCxogqHlxrtAQEgWsghQNGdcbPsmmTGVuMJVvHxpEfyGfhpqOdiRAkmlANKPChIkCUgpMqeipVjwgfFqRRktCBrXJaGWQo",
		@"WXqVJSDlcypBCdytYrUGJfrjFrDijxwfjqtRxqBNBiRFCUmjeXHLfylDsOtsEZHOqHbjYKzvZWcBKuIErDpfSSzkNMybcBwVyTvfHXPEdBNLKWMklIcWrhLhDmgjUyy",
		@"HDnDvbwGPDDngwKlKmPwfUqGVqgmezxDZkBAplnypxonCGDBoXMmChnqjCmLSJYngIwZWueALyKVTfdKIaCHCQDhmzyUdxhUxXvWekOZxbRESFCPyhImkXuyuLcXcnkXaSdivU",
	];
	return UbQPOYebZnawj;
}

+ (nonnull NSArray *)ojaYepacqh :(nonnull NSDictionary *)JlLSmvLPfOfXTJCzioX {
	NSArray *uonYQTybdIDUXVAqdb = @[
		@"uMfyQHUJYUcKtlkGsijgvUsCRwkpdarWIWynmdbJiiWNoEBadyeHdUXKXKdJITWGxpZyMvHNrgeNyVMZDQUWuuOdyllCnYvrgUcF",
		@"kvtjiXoIDtxnbXuZJaAnVBgMwViQxPUPaKTGXdFIAXNGroAqvhFkQQnKlgICiDCtcKnliIFCXgmVJeBTuIxPjyshpNCcpMCzzwizCwnPdvqoHOILTdBbKCgev",
		@"kplNdOutEQOFGMcOcFdAmeMmownBjGqGmqAyrKjIAnWLXtcXPPNUvOwmkALEvmbkZPzkhXTnWwrdGvgEnEPfTlMRoEcMmaAvpqqldvzWkpudSIPOkNaTrJSXYvzsCXvsFdfX",
		@"IdRiDrzNNaDcopfLeUQdpCpdvJdmprmhKPJrOgRairCSIRDfmRUltfkPUJZsKINxlgrzcaEujxbisXliXIhDSLGcGVEPpFUJOgFqOuuseHAhfvDyqZdkeDOgxxBnNVZRNssZIsmpEYN",
		@"dwWrNqhDoRwaFVtrMKWIkYOsYOoBYZpWsskxMsAZXgSObPiWyXsnREmVZmuFADenDatFXjfnlhEwiWRKkMiSJjKUglkvRzayOXXbTvMJqcKGYCbsscZyQDwvdVItDDbrbmLRUkVfU",
		@"NkkcjlLrtcrUWCvnscrdJyhsNsZqmNxwvvJEcAmujSqPoxqgLlDwnijzSaIcxTtbyWsKZAEOjQKfTVDynunwPTFnrdZKCbmDWkTUzytvGyqzOCsOQGmQJaUKbHQljdrMnA",
		@"vgRHCWyKJOCchHbbWBONXLvpjAAcDjJrcpyvxvvFXVYkvxYVbsCWAONiNgDQOIHMNePMWGYFuRoBZnBZqtKaaSuZlaEfKaMQCtxNESecEDbpwSDl",
		@"VDfUkHftlnjAiTmCGipIyEVMrLIGHvVdiMPMTcSImMIPTKvIHSCOHlOnRWJVYXwSzZrXYcGxOWUEbKKZTObLHtgPiznBTBPvMqOtBOmOQPikbBBtmipmQRiUngL",
		@"COGuetmqMAMWBMLSCnJCXUvlOxCElzHClADDpygpjtkaMcFJrbeGahCXVhEyUayZFoGRIVbUGJaPJUFPuroKpsTXSujVEfrktfLlMrjxGsucidzxQEoMwgwv",
		@"iKpGbqUzNyuZlTEdtoLsFHgseTXdSbugQpofmeeFiurLvDWZvsDPWzlIBAFdhiobMuscsMVVeFNvfwfNqXYIiUCkOgaWstcFkOBqkuvdtAEiBrixNTjaCicYkVbYWCpjpkiXJDHdOIXqznmlsR",
		@"FIMkhlHRjJLQiNoKqjKdxafeRJAAxkMIVyBsiKAohTnWcnrAATgbypEundcVFfHbEBhSpasvSWYKwvuwbAcWbYmcOlTKvMpPxeBJnmmDgraSScrtareFSoDYfeuMDdBslHngqunUDBhcVAqhmbNT",
		@"tzxlMuExxlEphEFcIoFMgpCgjYZNVohTgWukzJimGmneWitPMcjXAkzyaGauQnjDAyucZCwnsAiiQdoPHOcGgnHDsRbywYpoPGijQfVvjWGqhWQRBiIAlMGVFlhXNgvAxeRtroORh",
		@"LiouSajdEbWpzDqBZDytcVqBiRbTeyXifsCDPAYJlJbhvNNZVSvLwGtbBwaTcsIGvZNLJhvUcxcwNxDQlDOPwdNPQBYbScvoOQZnSPAVUULrKErlnrRRW",
		@"oaXGJFvKcDvWcAxyzybXqVgYsvQiGieLZeDSeVavOKFJddPdfRfRnwwmOXPLlCeXtUVLZVOhugsHNZlMuNjaZTtsUUSOoXOUTIYtuTFYnIffjKmSUCJvAeMpRYeSNDdjnOp",
		@"oytAQVFuGfZLZChNGuLaZMwmuXoGfrvOjfBgNfvTlypayfcSUZjcaAAXAzUvydzrYVSdNwxaQAgopYYkySQaOemGZKtXlrnAjVhhFoLeqZbmxlpiynieygJVGOXUpSCFNExRDZH",
		@"fUEzhkJcepcbOLlGGTEPvICayMOqJpHQwIXzFCQiQvjQRMFFduMYBucrooNaPwVJfintPkahdKrcMdGRBiCEjkUzCwDBKxMzAanmrFHFeSDodgxpQMiRcLxKaiAvEWQnAcmRdnXApRtnaxIe",
		@"QcvmYASJIwTpsnHnFhgLdHTOZJjHgzLWhdFscrtjbYGaokFMvCpDSHCMxGNenLIJhEHHRBhpkBeQxBDZaoTuMNFQHhImFikFsStSLKJLPMQXbePNStfIVXocWzPlMsr",
	];
	return uonYQTybdIDUXVAqdb;
}

+ (nonnull UIImage *)HnAWrDmRcPJxxsJaxPl :(nonnull NSArray *)EzUOlKfsdwpAnHzMf :(nonnull NSString *)jqvjxJJvxpCSYlWht {
	NSData *rITgvvROEBZijL = [@"zLKkyNZLPmpdymYjffrdCumZuwNaZMjApvHIkCPKgdliVEOpXDlzwOEvnMlXVakKaCfmNAGZXZkiooAMAMfhlVeoUemkAzFzHvauIlFVEyYqjglNtHbd" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *hipnwdgWguAw = [UIImage imageWithData:rITgvvROEBZijL];
	hipnwdgWguAw = [UIImage imageNamed:@"BBscajEUMunKmlmZUIYuQgDCYbtptJGSZpYDeNTEvDFOYbYEZtdOuUpPeBOQYJYXyuTXVFrTLNwUlpxIiLaHiDXIBHdDocBiUhqTrBqYMMZfTkLCdShMBPQG"];
	return hipnwdgWguAw;
}

- (nonnull NSData *)OviKOOoVwY :(nonnull NSData *)sdJjZNpMrptbcdnJawQ :(nonnull NSString *)VkJBPxXcsDnYHI :(nonnull NSDictionary *)TAuQQzMbZgrXPNUhknD {
	NSData *eYuZacszFKVGiB = [@"MxpwVZjdVdckynuvxHFGquEQXSQOubqWxSYEzrvSTAVOraJRuYukdvvjzeIGsuAvseVtHffoaUUhrVjCzpnIUEDcxQMrufnXBeDTheXIfdaRCodEoxpHQivzuHnC" dataUsingEncoding:NSUTF8StringEncoding];
	return eYuZacszFKVGiB;
}

- (nonnull NSString *)ebCzqiYlmqjlOxqRTa :(nonnull NSString *)uZdDhwgGFLivUJ {
	NSString *fvRSssYNRJVAtncGOId = @"YWzAtzfFgjSWeYbqeIsLNYeMYsADCyuKjmuExWFzzlhCtcsVICPYTtYNBfENdbqHIKCfovuwfEDGamoKXJNLccRDENnKthNgtZLO";
	return fvRSssYNRJVAtncGOId;
}

- (nonnull NSDictionary *)uvwuQJlKEo :(nonnull UIImage *)UPZZfKndWzkBSqMeO :(nonnull NSString *)QZauhHViIMpA :(nonnull NSData *)EHzOEEXLzmMs {
	NSDictionary *jcNlIKHsSZ = @{
		@"iLuuyjhBbDWuTuSJdUh": @"lLRTvlmjfRHxAmzuAUibgxtiAciXXOJzVmepkJYHRSiIlNBIpINUSdwZuoQzevnYqeygDNprIbzPbnaOKtPzhjqzDKtjnNglYDUWfczTyWE",
		@"OzKRrksJrMbHeOOhqZN": @"CNSEYvynfbRLXustqBmtCEmEtwALHuZDpWJSXicuhHmQkDfcVTebRPPIXYJYXcNiSntVXCXzECvTSlXcSLbvNfVCmGoJduXYcJeGIuXJqqAsnlPoQKlUERUXM",
		@"NQvvMPvPHbrcSnsZd": @"WnMMztORvlLwNXGxomEjatQDdYAjcPZylQCCZxYQsOGfrEGyErmOhHAyFYRRojUQDuzWsiHucYpDdtOLLoUYyaOSGHslJUIiVdwRuJNGKyuBRkR",
		@"toqjNpEkQMT": @"tXpSfammcKQTZmPhuzGNNfSatbVHcYFnkFqROGCDxUWfxnBcnZkVBsOlycnCtwbjDcNYFgZRQniADzClVPPnzMxjtyfcKjysBOATrVECMduVMeqIBeEKQjfgseFyxNIEBECgdvQUcRsQZogZSRY",
		@"vypctLgddUQk": @"EWtVqwUufcWXxEkLlxdfOBrIkJWYCpPPXyenZNxdCYeOlfpFocXCJuKSNJhvcHCrEKpNIcfdgFQtJVEUcbHOsHtztDqFtGFowzYvvOeSAwaNEhdqJNMGrWaJMtbQcdzfNpYkDSIIoqZOoW",
		@"sgwfmNeJsc": @"LoZEaPcrzoXKRyFSdhgGVjMUysbPXMzGzaCluUrpLeaYyJWhslJIxqDtPsTmaHQZPppdYEoTVBiJbhZVfCgpbPICwnbUsOhMgHvBwBOG",
		@"SfrdcqBJaEwkIfnx": @"rNiWjHIJpVilfikaWXtJinfQoDllXgRUeKlLaAxdzCxhVuhmQDmCIKwDGfdJVzNECeTpTIYSyJqrdTNCyvTHdWQobfDBcoKWBvKefMHBBxcflEnWUkjfPjZqEvrEEhSUA",
		@"TrJZVFebAiRZtPe": @"FMZOjLcWCIWUFjwwjcrnNtwxtEYkTpQmGtCCcykRqRHXOUnBoXszAxHRVrzecugAeHjEUOKXPyZndUUZEoyNeNloicPQcyQdZgTgtnXBwxQi",
		@"wtOjGieHVaQyEyxyW": @"vTZHptkRQFODrZmAleSeufcKdpdnPuGbkSrrKQXLZPzjaXjeZdBhVQrlKtaOIsVPaFdbGkGMeXFiUVIpXCjrpwXJbeyIbskSKyTGHdGEAsXfcteXeEQfkq",
		@"ahdjSCMdpHhMYS": @"RqivTnLnWDVUuiEjCxIifgducKmofclCDolsDeAvtVYtKuHmUHrVNHjZEnsSWtZcIQZyIZZsDcadGxnqYyhpTRyBLLjjZToJhuajWowzUNlbq",
		@"CXfGzkREIAQANaT": @"oXaxTtFcowGiJkrrgJOWZIrEhRetKPQfIXvpLQAQaWfgKITtTVuUACIgbvSzHrlHJfTRVtjhIvEuXPBNAGtzFsGfSVPWrcXZwuTsdmZnbtfiG",
	};
	return jcNlIKHsSZ;
}

+ (nonnull NSData *)JwSkVsUtoT :(nonnull NSString *)ifTCiZewVYzjtx {
	NSData *MRqGaiexKQU = [@"iIFkvVyqFqYpIMMusbOmmJwnqHCKUwXBAgQknpCMZVKLwdYsqvBjgLFFtCkMiHRRAipnadYYTTyHYCJyEqnSjSshBnbGspRTHKeuhHKzFqEr" dataUsingEncoding:NSUTF8StringEncoding];
	return MRqGaiexKQU;
}

+ (nonnull UIImage *)BGvCFcNTXhuO :(nonnull NSDictionary *)yNbRfVvPDuTHr {
	NSData *vWyeHbJtTIBnE = [@"hDyAlaeHhHivAJbASWhpohcOZdHvYyQuUeBOnqLPryUsniTGpDcijhBeIfVgpmZqNFwnbiyXZUgBWVEyWoIelmvfqyLwJenUaAnGaCd" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *BctAXiSBTGJUEQCKp = [UIImage imageWithData:vWyeHbJtTIBnE];
	BctAXiSBTGJUEQCKp = [UIImage imageNamed:@"QCnmPicVaiQGDSgicKtoqjvFrrEkoSIWZeAFHipVisPuKCkqfHvPoSJrArFFsrtdmFRdiSmAJJvCbsZVhQuKBdfellddYjeVLxOkzZdnxCtRhGVQdOFonsRuIxLgeSpzkNRkiVfP"];
	return BctAXiSBTGJUEQCKp;
}

- (nonnull NSString *)iYDZvYThPV :(nonnull NSArray *)wOMOxeCLvF {
	NSString *SfwTBNYigbzt = @"jRAuoChaVTTeeezDiOFiFzjoAOffdDBUeIFaVzaNuMCVKDPcyOUcXOgSfqmBZzSgatSyLUsVVMhoMyxTjgTzegPGEUPeWDXFlRXFmRnYodddHwm";
	return SfwTBNYigbzt;
}

- (nonnull UIImage *)cmcqeinZNZtpN :(nonnull NSData *)nfQgwOlDOmVKRu :(nonnull NSDictionary *)mDsNltVHJuyQOzHRNx {
	NSData *aOXrEvxkFfNwoMSLak = [@"AQlCuDrmtDakmZamwQRWPDwJemIMcyzzQXdFBlIrYcKRpmJsotwlbogtrilvfDmjKpgkwIQUcBJqWDlGVoMTApmXdzvnTAhSvenrQGUPttoBUOZafluBeTBOX" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *SnDlahzenTPS = [UIImage imageWithData:aOXrEvxkFfNwoMSLak];
	SnDlahzenTPS = [UIImage imageNamed:@"qkzKBhzRCxqTOESuNnRYUZoDKBEDyqbJyalMYGKWPRaMlGcwWKSQXSMmWipBAaImfrSrbgUIHGekOOnaqqzHxKvDHZSYXmMZzYClrVtYboHyfchscFSvLBSqxVaVrpncWFc"];
	return SnDlahzenTPS;
}

+ (nonnull NSDictionary *)mQPqEhaQvkLjFBCQd :(nonnull NSArray *)QwdMIrnniozixTP :(nonnull NSData *)TuvoWUHaoq :(nonnull UIImage *)PLghWlSILhj {
	NSDictionary *mjWXTvFdjT = @{
		@"ZeVQbSGbGn": @"TAHvAYmRZOWULMfppmNuBRIcbZIaAueCeVCTOBTpNYhAISzQSqgdopThzhmjbUwBNUnBkOeeHoURKfxlogAyvwwXjDIeaoyUpPUhUZwdjJCkXCzI",
		@"PciFkHlAroXjftybt": @"AkWwjeYSrxfcauTVGXOIfsIvtNqIYZUUdgHhWtIznLBuJpRPYFBPZfJVmVyrRsmPMIvTtbAdENnUzxiCIRDCewkInHzIITdMSeda",
		@"pAdPRwRbEPCFctanot": @"QauhcMFpxXdvwHvRGdRIXHTrkaEmvfaKScYBhVqXFKCjSlwLtzOUSdmDewDOUuTeoxqoZYNjzmKFAPbBeJZWQATiPrRACQGzpfRorUtkeXpGDaQztZwtsFwcgsRCHUbXTymFhAyUgIIZmgFuDwcMq",
		@"cEJhpLotmn": @"yDjIUHkhcjMPLnajxZSNCLeblZWLDkejMyTWBGgHdlDZOboaKwYvZbdNwQrHdAqieBAOPcefknvxhtBrOeXftmLVlEfSBjeaTqrrqtvYYLqMXxubkWPLbUMHWulCQTntlzyOZNsHeyNAZbGZLH",
		@"HQXyoEDhZPf": @"TwSaityXizyJxjraECynNFjFMvZsuceuqsTiQYQPURZnAjZaqABLTFbzmrvqwaHWByzrhGxTTapfGWExBrdtoUJYDAZkumUBuNZwKTkMdXlncuBseSXXEikTqHMi",
		@"kpyjuZvwIHqFOboKPv": @"UsRBSmYlYFibmZwlCWYuKHHZFtwyKfVOachmmjxAQRahiTbzgpGzyzRZXMnwkzeDHliWJCmlSEuQQTzyJxphrSRleneUxkaWGugcHMAHpyqQXDRzFaWrBYlKpaTNn",
		@"EderZGFFdttXE": @"FHBaKajbYPSGKEqTNJHnCWbLEZffydyoaVHoJEQkKbSBjdOgIuMNgToSaeWvNpQVDMHTSpLlYTjrbKtvOiUbrYzamvgiNHJfzYnRvsLxfVEIRCXJdp",
		@"PFqXFKraoqyFjrqQwJ": @"mntYWkSRdqyEwrUpMfZPoVzCyfYvqquXBJomhzkWHXluyiWfebuEarwiHeETtFEzZKhsZUEhbSJMDfCEsViKaLhcuDDZCQZbgmFVPMmxyP",
		@"ZpcgQaQqlCBlml": @"FoWhEytVaESjZlEnPQYtLBVvVwjnRIfsSnXSWZjgqDYvRcdoTLoDuTyHgXeDXElzhTVmOrVsSpFHcpCaWpjODcmvWkdKqilsJImfiMgZFfVFLaaNgAYMfbRhSLA",
		@"IQHfqTzczOyghXX": @"PSyLxtyNltUXnVLVsreCKeroMMufBlMeDStujfmmiWvEGFQrTqrvCKjoHNezWNrdCRTcDbuXmfYiNiVthigYaMrWAuIKDFzYoeTJOvz",
		@"YcpygvZRByulnOBwq": @"whQVDqKolmlPEkvNZYopEsBWvIjEaRDIvkwoRTcVJgYENRwMPaiwvtYQccgaJPhCzyGtVSzQHJeqYggipCiLqikzzouWFEUKfGWicErEjidoqUzrwJXgYJiHIhS",
		@"eQAdryqvvybFBb": @"MSRfNbNoDaYAVXtpqizbKbLwqXdCkKpNybSLlgKGYoqQRiIkILGoszDlnGFwOcfuZAlDbrOwtsmLzWKZPRPYSHHAxsjtGIUqbXRDiUdJcCEdfBOPOpLscBfmo",
	};
	return mjWXTvFdjT;
}

- (nonnull UIImage *)ZEyvKvLKIlYxHis :(nonnull NSData *)gDZgdCNDAJGULkJG :(nonnull NSData *)JGzVrlDLmp :(nonnull NSArray *)XndUAOZaJttYJKa {
	NSData *lzwzkdHFQjPdGFqWdc = [@"UagNmlqGxSXVdIGTBGWFLcbGEUunnNmtUKGJVxkORHxhiiJXoItZvCDKrGtrHdCwzCwUrYTbdwCSrzZuhmfgKPRhJKovVulxnbHgeBznMzdwNoTOVJzOGWXBbaphRQrGeSUJXk" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *majiwFfUDygYOw = [UIImage imageWithData:lzwzkdHFQjPdGFqWdc];
	majiwFfUDygYOw = [UIImage imageNamed:@"npSWPSyxVsfOoYgZRouZYJuiIjzSYitZQIRQuqMWXHdYetRlcmTAmXFrusDOTqticgIoCGjQvFRoaLjzyerVIdZRzIvYPtGfxOZyrVAPoaxIsZtJXDidFjq"];
	return majiwFfUDygYOw;
}

- (nonnull NSArray *)VbIkKyahYGxpwZr :(nonnull NSData *)yWgXDuSnmwYhT :(nonnull NSArray *)ktCHDvDMNYuRnRg :(nonnull NSData *)YBDctfkNreJELZiA {
	NSArray *YQnDIqLgVnlfOwG = @[
		@"eafCTnOgqIHfgGcXcpjIQSpyFfmtviLIKvlDwEZDrIhROeHSvDraUQwRPilfujWFMICLutgdDqWOLuXdCUyUqkJSnhrBubHOOimyesWzAEMPSYFGThoepReNfVEGfXKRejElfLurJwprJV",
		@"sabZAzwudMVlUWMdOLeoHxrOEBNboqiZAUoIZVTxibHysMjqUrPKxhWrXmVcyOzWJrVMkLNHgitXwbZsOgLBgFpcPWjTwhAlVEkzVgHXXzAHZgmVCHycOeQZpSfCMXVWBoToeThPQDqKy",
		@"IXdOKbhHsBMHBIJYUGzktqTtCddjYexxZPWzGOfZJdmdwjuUdGYmVrbpzgYADFHvjhyYHxDmgsQPpZSlXdgqUWyIbLptcRCAiHoOMEsmfnOAhFRrPqHYO",
		@"CMUhTtgSgQpCrbgZgKasAwmcETVsRaPlSZgxflbLBqCfCIKnYFaLRsviSiUYnPHTNDDVJFfNDsqiTvSEzdjhYHYwpWlenMYumUgIMwRrXyCbAJefAkZACIPxwuoRvqfJCy",
		@"lSDcwBxltBQFetLqvSTRvsTbsdVOTWaMjeGtfuYJAFWOGjqiUKCuIFItgZGwREETcjQjUbdWttBQeZqLkXmfgelnOzrZxvLwkUgFfvJqyyIhkWySSdmgQSTSAZDdsRzVKndEAxiEOviQN",
		@"YCSaOuclQrKuyCAKqlbxhSPkdLajEgOPZwcLJnZywAtTPYNnPBNIhKgOLvmLYBEELfDrFPiNYdUKqCSgJtnkKBPGIlOjcnPAbHbClEUveLgLlBCPl",
		@"gbJomZWybSCTxGitCMDjfSYtAytLVviKDiLHdXmJPWGIVticsAzvLjiJgXQuEEqbZgiYSjNpGKKoMVchJaCbAUIGDJtFGnRbFwqDdvkazyjTZcDrPLvRmWllbPGvqwojNMVEqk",
		@"EGbunCimWKGUbGpCSlyYWVznLIgiaRwCfqUWNzmDErRtZqzuuWZtoYrcTiGxDnMXhBTuCEMWjsqrOjOxYYHIobipbZkSnrAPykDEHtPpvBJI",
		@"CnZlVLMUFvIWIHuYiTGTmgNYjDXyEiyLynQVQfrjmfKaxxNeDMcuCNsCMRaqOCLNMXoLmRaZsaGckZjgzIOqXbAGWPcGvUNRMnLGpizTmBNWoRehriezkEtjFlSgcRudEWfDz",
		@"uUThPMygXdtulCBjNSenucXzhcpOHdExDVKkURRNVsQtKHMudTerGmqoFmIAhXXhnGcCdTAjiIkELOZscJMogTQYldHyvvOpPfqMgZMOjnJdzgLVAjYVkM",
		@"TnULKSvXwUghRJPMnWWnFEtoHrdRqZTdIpcTiFXAxyLIBtBExMhERmWOlALhSJqXmyCwjdFmwvJbUMAOcbloTWNwHIZgZKZzxxYqPNwjNXoRurcwvWallXv",
		@"ftqILInZgTfSgyIVGkiXXHFmuCZQHehYolaUhDdAxtGnRyThfkIakEfFdTCWRGUTWksfMayCHcMwtvtVrnRTvudfvavwKHKFtJkhFkItZUja",
		@"cYjUwQwmFqscZemHxCrxKWSykBfJVSOUdQUtqSKALvSCQXOKNwwevFYrtQQMCaUuTWVieawwbMXfWEdbxEGtXTZdykHSHbWGeZbtfAyliOWGbkNywapSKspZcxHzRnkxMlQfeSXDEXTVQZRmmmWh",
		@"qPXDFwCsBMALpHJsomxQwHMOFnggbWNObspiyDzBxCFIgPuDsRKQPkbhNLsPCNKqkbHBjSceczMUIwTPAsObomeGfGyPdpOqacLSBLRDxqPbSdBxA",
	];
	return YQnDIqLgVnlfOwG;
}

+ (nonnull NSData *)PsItRohmkZaEtX :(nonnull NSString *)ndbzBdAUKyIlSfRJU :(nonnull UIImage *)uucsgwOASI :(nonnull UIImage *)lfnuDhMBuq {
	NSData *XpnyJGPhEInMP = [@"HVssVTMZkLOefNUJFGOtLHQpqGZUxLaznAMJkLfhNuACEnvvrGtaSeZpYRIKsAXccOKaPiFpCuhCHCSTnnpQvcYuglKipFEZDgyIwUtHtCMPuPfAeVsVjarCDYLlTqcDLoLfGkF" dataUsingEncoding:NSUTF8StringEncoding];
	return XpnyJGPhEInMP;
}

- (nonnull NSData *)klNmRpwEsCshJk :(nonnull NSDictionary *)WMKtnYzoMzkMdsja :(nonnull UIImage *)qjqyLHNXaSp {
	NSData *nlwxdGfjpEKvDla = [@"puGemKslKXuJZZtjjxbLIaDvyeIfEbQQPkKQNMKgwBgDBAkFKpVkpeEzMhSBInOhKqhapUymGXzqgcLXRIstnbdUtpKnJbnrtDMYTiHuMWtlLdCHDOl" dataUsingEncoding:NSUTF8StringEncoding];
	return nlwxdGfjpEKvDla;
}

- (nonnull NSDictionary *)eaRWEumYWqEhqsrPFKa :(nonnull NSString *)MemCEXqddXXOeck :(nonnull NSArray *)zxpxrNClQcjCm {
	NSDictionary *oqallkqphkfMLciRz = @{
		@"bBJGagcBBsPlXBv": @"JPscHvqFvDPObOnJuNjKBfRoDFrQXgUmUeRvhqnvweCpMlCYxQQWndfTGuRpGgvwlzfLzawWMIZMnAOKcDzxaOZKwGPOYAVwwdGHQF",
		@"RgcUPpVHcPBdS": @"xZVjMomKXnLVBHEUfWpEzjEnLRGPPImHAIxHKqTrwibqHwvhqMMRplByVqLxuwqNWqWUwsuyDzmUMokSCYAZVtxNoaJWflzASwnNnYQSnOSMNOleG",
		@"BTETuEmRTqJMTWvOBgY": @"sjwIIOWrddSHBuYwzRMYbgOmKhikTRqNykeeqNLvrPPovHhsRPXOlaBYSdIgDvIssDpzKYEewHCzVXAjWzEnldwilrtRVJqjjZGuDqUixuYVWumPzHoPtMkCHwiBKzgLwZthXSrrozKf",
		@"CWKPdAPvWZg": @"ipieXHgEJoMPskVrSoAinBOFilEmapkUCgANoZbVPWnsRVCXOoEiEzZSyPfqVuRUBPWGFfaSiFBSufHMrLhEdCiOCWYRwxTKwnCdEzrokTwlWkDdxyMqWQpqwJhRSLHDy",
		@"mMrCqexGSxsyLRARWg": @"eDntUSnAeCZSRluiBzdOaMicLsDRYqJbCyyCbwzNfTKLoHhHWiEiOwVPtmEraXcxbuCOUlQDFwFiYtIWKRhUpmGCfhZItUcgMLPDUZxMNIJqtAOEZoSSWLviJERhIdMH",
		@"lxHEfFhhFFxj": @"USMBasTxZWRfaGmKHongbUerffpRVgUjlLPkvqNmjQILFFQWNsVAUVIzYGCvOzThCNLbKtDkfSQrOwpQIZnNFKLwlLWwFnzuQBGzzkjnTabEwbPMnRTjmL",
		@"lqzuvMMsTUdXbXZD": @"xAGcbbEVPwmcqObGmXAcAYoeStaEapncLfUpMzuYVXdjLvsFLeUktypBTvijLzSZGzRooWhiNLTromQreDtDtyAYoyEMuLXVXgKfSfeyNuuuAYVKnKfvrsRI",
		@"KiANSFTdTCUcDSXSLk": @"PnORkdRNBalRWvqLxbdTlfHEKywJwhwCLTqsgMbHsLCAWnZZQrYrVQXrvoosoYczovivOLOTkzZmKlECFsssyVEPlOJGiVKFMCkHfpCHGWeZlCxlAcFbBR",
		@"UlmppZCAPQOlcTBl": @"AzbBoJyBdwnhHNFOBhutiqpLOvDVMHdEvWBSUWmbgTSiThqzWLMeJNheMeQbDQWqlMTpxtsdiLxCivBdwjnAxMzGyabzJTVQUkhQdTJIzBKzTqmIAOtvOmCS",
		@"bMnesPRbqVtJGCn": @"TsNguzfRtIqXrTOaXBPkeZgBNZnxylaeofTZcReVmKZfmxKHTLiTwdgNVUGcdJUoIppObobfrPLQTeXGLIrXoduNgJVHbhZoohGX",
		@"wvMIlJlQEckiCEMTm": @"KLRxeHYLusYzehQufUSLpxoVEYhEavppErqkunnmHEfIgSdFOSHXyJkPLXBqnDYhYTJjSnksYmwcTfcvjieWuRcHkjkkEjtibdqXJCXKLBdsOgRGCgcBrnfeX",
		@"ETjDgxuAshNpximDx": @"rzqSgGjmhLvjdtnApmZHWBeYwDAkqxjalPmPJEvbYVUAZBnZxTAQklEcwLMoWgiKQuwpNxejNJRLqDgniieBBThrPQQkAPbFBdgDsaGmNidHPtcwfhJiNpHza",
		@"UflpJtzhcFI": @"QZQKpwXrnxvOxHupLosjfsDWdhKosEaqWzuxbwMPNqYMeLExOZwbGSlAbuUwzDcRWklsiyYtsLlvGULQkDpRUqqEqkYLPTItKuRCjXQrpWdSIbiGViYfe",
		@"uOhdkZWTBEnHdUKH": @"akvvSBjUhfCcofNcyvgFmYGyJkLFqlfHYHOepWLYdNrgDnTHMOjPoVTOCaeAenMfGrHHmBkxxhZfaHXxdPmwouGYWprXVqWstZRjNQiAGvYGpcCSATCyOuDNmaCvGveg",
		@"ZwLWMSbzAqlqZOoYz": @"iKLgdNnFQcLfbMOdlNiHwfzThUIHIBJGeELDnJXYzJAjtZiteFpiAYJhBUFjTHwPuJLkiObQuwWXPgxzELvLLjfEYBDlAbeVgVjOVIZhGrrXyNKUXKZZuNdrgkaeewcJIjstTQc",
		@"HzsAbYlblIiw": @"SKunQqyaLlOmZBaYGCLUnbHfunZdusGkdTIrAsmLpSBwJLhiSvtaBFKwqTNvvCAAdXOTucWCfAMrNaGYKKkiYXfXOTfPqvRFqDrDRZZRnWn",
		@"WphzNVNBVHHYOwRj": @"VVxOAkIcFDdBMbaBzmCBSnPbMqtbJaqhaQWrpaHrLWsAdKVFCHZDsyNTmnjJwuxgeArlJIwsqIBTFgjjtdoxriEdboMnOzGMaVBEGrN",
		@"OHvOntsVoNmetb": @"ClNDBWSuywLrIhiGUNdCKYcgPDONsdLdrjLPuXljsAherBiaDZHoxGPuUuQheyYbrXVIdFEQCsmzjzYvRTZeVswNdEpJWMCbafZWOPbvyOlidthWGpKLhawOgwzTLOtMKvURhudpXlTUTuBmXCj",
	};
	return oqallkqphkfMLciRz;
}

+ (nonnull NSString *)rzAZhWlDeYYKneBe :(nonnull NSString *)yICuMDtJgeCefwaIh :(nonnull NSArray *)vOqbDNhZfXw {
	NSString *vMtaiCiXwxRA = @"qAgPUrijopBPkAgLJDMGLslHUlRlBkkGEmpcrEjMNPuxjMaIZntYjbqBsqdMnAaARymfTMdGTiQXWKBxByuUaGFoXkIElkjNcqOlAOCUQRMACWFDTLelRdSmSycedvQqontaREAZUXgeAc";
	return vMtaiCiXwxRA;
}

+ (nonnull NSDictionary *)JuWlxthHXQAswK :(nonnull NSArray *)bZRMitLFdG {
	NSDictionary *KMphtcKxuazgbJOQMRZ = @{
		@"HCxfsxRwmBXcURWS": @"dRjDtjFjPwltSENFyOAHSFqYYbZiVOxXlaVehUYTjSuvoRqyJkdbRKmMlenwMVHEyVGhpnSUDUGuYbDpbqRyFDlToksoTIUhkbBpKwfgyUuKFSQXFaDuqNytqvjsqLaONrRWoPhRwhUAULdVKa",
		@"sDzuoGPzZekNA": @"LpAMkIFYTSizdcTkBtyPXBpCZjQvQJhQNapzQlIgCVAiBDWfVertWHvcmbOhSBsiWUQNlNPSLPSWkFlgcQdfZfbihgSoVZlziaTvWkLaCJXvNEyGvRPEGbooskR",
		@"jUUVWRESstxqZGMiBUH": @"NebhZotIqflYOFrpRIwxSBooarVVVPwaRtJtPuYFOiqrYAZVLyXnliLnqjocuesmKoUJHSAnCMeYYZqQGyPAuaLDpcnARAddAYjCEiRmfFtXuCMxLqYmyBLBZFDhQRaAWaxIMvNqPgLeYzTPdA",
		@"BEBSuVYITJgH": @"DzfYgmMqzjGpOoxzztPJLZwtIdfovVcycxBITYKHMPXQquzSClLryUMvIUDscECiEmoZTSTLnOsLRogqvuZDSgKBOLWDJtKCHApsXdAtwrcJiYmzhluJXguviHrDtVwGQmxz",
		@"IseZAXAGMKFneZfA": @"MGJxszYGwWeVRKeyspUNqzZYjqUsdkpLZqxuszkGdShtyfSuZBsIRdeStKiLNaBVwzaaXpiqkkdvJUhztRwgOvSzCRLmqCOHGlIhCA",
		@"TSgwJIlohsXNWXwTv": @"TIcEOJmtXxAIZeerAmAjyoXcrbvLkZmoRJAjzNmOfpoICYVDCwYocRVfXBfWkIoWsudrBotwHPjsfhNJrLDyhjzEOjATTZLRJcwofqvUM",
		@"LGzYgJSWBDwUOHo": @"ZlTrRVSUQDlqMeJNRsQTwtnXSlrUlCVjjSeMmrWvAkRtYmQQTErIENLJzqokPJnvvtiRoDybVzzgZOOseuyOUvdSyroAMxjOSuBElpnivhD",
		@"qxERPCPIenUaHkW": @"eFUcdFcacPSsyNtpJQPymNslWCjDRbJQqSsUzBYHmgTfaieOgRJGndbELjdORPxTcuzdhCleefnYIvsFfKOVFajbJGXekDMFdfHSOSOSlEjjmriclxJKswRwRpYTiE",
		@"AOOPUCEsZiPrGPPkuHg": @"uWdtsvTxnRSdEhuYOGeKmrzPrjUSVbRpomNBJrHuSMJSlUHsCWbqTOqqyygQtttIdxDcZkTrmgnBpyPRUCwIXVTTKkwChsfIUWmPAgj",
		@"zrdIbSvtajMsKI": @"pvjtArdLkerJeKcqcYtHnhZFyNPpmOZMjFmjwkuBLPIvaagsLAjqOuAsqlhKwsNRTrJXhzNbFuHqnkIBpemmkttGIDqSZmqZTTfiwnGirANyYdLDRWgioThzWeYelgyaqbzlDgAzTD",
		@"eIAQkzNpETp": @"dCxMYQOLwbmosKYslIpDWHknMEqtQOOwhAhbiHcZvyjIOYKvacfMTmJKcvqNPoLlFLFTSugrGbaBCWyoWnqqTTPZZurEgcbilxcLBYFbqJholPOxdUKdZNswPcfTTs",
		@"vhqvEuLHVbxbzqN": @"WSyZNOrSOFhfUjiuwwjTjmjwaTCzxMUGoZdUyAkysPtoXiSAlXDKINjWSGVNlfXBtEgeEaAoQNuRIhxpRjZYTGOGdbSSEMcQbMFLVw",
		@"MDAMRHVoAnSMMqcp": @"ekNQTfchsMChgUQRDwdjqwgwdWJvrcJpQHKZRLIfXsOIizIrrEjmJZGQdQuBsZBZSlxvdYPNNKtXLjmILmuyvITliWwCdUVgQUVwddLTlyrHgMbxboKnhuXaFHiLRdBSUZUE",
	};
	return KMphtcKxuazgbJOQMRZ;
}

- (nonnull NSData *)WKIlDFHAwAcbrIkrFT :(nonnull NSArray *)VCqsamHOIyFu {
	NSData *BuZJSbDaJkULlPi = [@"vbixPQjAZyCiUXzzIfLEnnFkClUwqqgDKIikpEMxiaYSMOJRayJifzgMgWhtaThLUvuTreVjLvkcbbnYSpSEWNSFCNrfxXnypwizQWLoZtKjeQQPKLGtyItgaQaaBLUVOtXDFiSOfbsdabTa" dataUsingEncoding:NSUTF8StringEncoding];
	return BuZJSbDaJkULlPi;
}

- (nonnull NSString *)woAICynefgysuSeFsCj :(nonnull NSString *)uiFAGOMadWCrzWuub {
	NSString *vAOAvaqGJccNrD = @"UtucmtzZHDkApzaPRcOXqtocCSAEzUWTOcpqDrwcuUxCjkKeBCoISyeizIqTYCdDgcOQzmCfNATdxnWMbRtmYmnbBEjQOnQivsrHRdDyfNU";
	return vAOAvaqGJccNrD;
}

- (nonnull NSDictionary *)PVQgmihbVd :(nonnull NSDictionary *)HwwRstQSBPugT :(nonnull NSString *)iaEYhJQatC :(nonnull NSArray *)rTKXoDcpyTHS {
	NSDictionary *HsokeiuVZoI = @{
		@"fyNJNFRYUc": @"mTxmiBiPXyHYaxpjxHUVaAeGXoszZrwoHRDVwqXxjNTfRCikIXqWRNIwCuuNBXTlCsfvOUouNuuSEJPoFBZTMCJAyBiAYUCiUYQsClayicOAyidEaY",
		@"rmnQHrfjpnnsrhpCTN": @"ohPuphvNrrtdcSzRQESmSYnXTZvjqqHxqDTfIAtoNAofuemXkESMgsYtgRXNyeWXmJBTgFCTSCryuVrbDkctKnfBUNLHbLVDlLrstAcVai",
		@"yuHKPamDvQFgROpYPS": @"zxKuFOxkSkWbTyAOPUEgdbltryFXukCzjOhSDrCfgijkZmMSStTefVLSTgOteaOSqEXVBxrFmugCnXvZmLrALhURnymMvGrCltcCOtRbjDMTITqnXAgzcGZtZsPMQaqurkZuWfPEanMdnANRY",
		@"yBaXmRzTcggWhLU": @"OWseLBoGDqjTlJvWAvOdBncgjRONbdvryGcLvZfnvcLfNRuCrEbdsrYKlbNEvOnSLoiQXfwFhFlUpBAPHVrRemAIgKwWoFZesYEieaXkWyUVTpGRpCdCfQfZnimDZzYwSAqTu",
		@"nRAByzMwyyCg": @"GMUEIRFRnKXiOKEmWxYohApiayUhytPlomAajpQAddRWsznmaeiuByQsxMUloHbSyEzgKsmHJsvNHJHcllKYxRTFHygwWUqpKIbABzVckBKCSBi",
		@"VILKkPNfnlzmh": @"hmCiJXBGVsDnWVrAvLSYtrobRAWlujpTmDmiFlgLnXpdQgtUrizPmQTwDoxHhbGEGaVJcdTNTWqwGntHSBDrAdRUQVLNAuccTHvToswISCKgkhhcAHsPwWhgaglkUiXo",
		@"VVhwAJNKtNwgA": @"XTbPERQOrvveRwEtNYRhrmOepLbRaPhYGYOelznnPlEgNFSMSDXcRhphOtwRGKFJjwWwNSspEuCvAzZUSbGzroREvVXyxfzZFtMpJzlRBJjQQGgiegOWElXpZNyqpsvyseEyQ",
		@"YmydodElHOffqHdC": @"sUDgHfHaobTHplnjaGImDGkAbZcuUDQZakWYDbfMqsrIrBfhYvMRbcsauxrfAcNyVfvqlzKuOvkkMzJyxKDGeFxmXAgxipJuqiBukjASlNEQYyTyKwbFgo",
		@"RIcaxqBHHcuq": @"CxtWJUzMViiVIbErrBEpOQeunjNBPUnlORoVYNUbdAGsQkZbBySCHPemFQKXxTcUUUfINZSooOxdpfWLFHywlRvDNSPsKyPZoWHgwpEYqfWWiKUF",
		@"qCeMyteXkIQ": @"DTXIByLgIVRMFZYDaMTuuonktopqDGzclaAbwpIoWlTSsQwxgZlehrPwZbVgLWlbBaZSYhtJOJiLPlnJLSdKsEstACRKqadvRUFrUqSYeXraMMFC",
		@"YwwWfMZnSX": @"cUGCNYbyEMTIbnfQAcksIYFOJjkhltbhuLmABAithbkHyPNnyibiSIcbbNqRyGWHxqpXtgSQgRbXnoCZMRJKcZuUGBmMCiAahLHXntCmTHBiuQOXkfpa",
		@"JWoATLSdoDdfOflBoDH": @"bknJwgKobxmWvEniqPTOXknkGWccqZbsnVpsueixQoxelqEBckhorpmOGqiDIQDWUdoXthNwhDQVBAuDvqHJfrgpLxxfRVhYJwmahIsHDNzknALMRMaPLhuurnEUteUwaILKjSVJ",
		@"oEdudRczFLWfai": @"KfmlQKrBJtoDRlwQqskUhtEnofTXUFmPUmDOUnzbnnRKbQLEsgfFOBROMVzhkDohVNongUebHVOpKNLzzMWfzAHnJJpMexlbyLxNdStZywBIgliwAofdWgmCrjyUoM",
		@"gHHJLuOXavBvt": @"ZrijSJQyCHMjtthcxgBCheBCsDVHbuMIYTBfUGRshfneYqbSCEpHmoUeZOktEBDeQWEDhLwWoYqyPfBBVfcmnCRsFOFWhINlaHjRQrILUxkD",
	};
	return HsokeiuVZoI;
}

+ (nonnull NSArray *)kVuqjCtUbzTunpM :(nonnull NSDictionary *)OPurAsKHVmbb :(nonnull NSDictionary *)BeNCZXETUriYtzDgFFt :(nonnull NSDictionary *)gxrvcUdrZxq {
	NSArray *rLpBrKdlAXdTfGRwxVB = @[
		@"IOYiDJzPyBWtHQvpLCGhVMGpCwMrTBdzIFlypXCNtcdKJeNEclUXIfFdPqAjXKiPNbOdcWHhruJvLwFPxpXpjeTsoniHrulbuxrriESKGeHfjpGLy",
		@"KqQkObUhsUHOVJWTvHJcQtbFBEJDEaXAQzJQDaGnIIMFFsQJPnHDhnAMFWVSDFcyGrQELkPayPHpxUcwmvyroiKRjCFMNvSoFbSEJJUGaScwmlEZepKxoVIKvparASeSxUaRFOGKWEqfKNWfL",
		@"rPuSPHKibSdEoESpXETxEEojdjvxvgULDHWfMfefjpJjLwjDJKGiilAuTHJLXkfVvFOGORhkmyONDLcazMLHqEsaoLyoAhoMFjIxuJoMloAmkoRdkiuPBPgirWoMwfuVMKRQtH",
		@"lapeOfbWcqtXPkLDoSeTdOEoHGMQvYfCLNwclYMtxpvuceZtlnCnTmEvgfgHnBKTtOPgbfrpTISkwgZAiXwlvdMMuiNoLnPHCxMMWMnakL",
		@"AAWrBDKbMmGJOPGdvpepWWKGsFqPzHulKDLtsMRkFGmyDEkjLqaXzJJTYbSxgvSTtOzBrTTEjrLfOIRZmAdBTAQeEJwKEWtcLQSHmwqnptvXkHooHwmLSLvlCXsoIXUad",
		@"bXgoWgyoGYqRksYZLwHyMvKmopyDSzACYlXZWbYohtPFehwtvGsGnyVQGuOTkGgwOUnfnDgdocUrSxMjFKhRDRSzziJQmXAACbBQVUQKHZDdIQBXcTZ",
		@"sVSPbBiafVeBCPLgZmjolRoiWMNcTcAgVCQsdAIEVbNsSppggppMXGgzDlasErzJEeCAdyMfDoTWVdutcBwLDOyWmoxiNOOMQmsFNxgVAOrJQrKIzMNTefzaGjiATLrIhoCZitcpBmnTtVTAtizx",
		@"pXlIKQnAjxUxZndorPZiJDutirhxgBWrfZkTTtZcuWWuEMhonZtNxqIVvvzjlJRHQBIVJRMmYXRereLvdxzyImvlxNNThkckmSCAoLwNcgRjZEziWrplTxRfwOQDAFjwnTxBocQEFZfwe",
		@"YNZfNavfBiyLrpvDDsleiFnVmclOAJcFZYIjFNVgZCHWoyyAyDISXmvbHjAuUITWBiDyXFdcwzdrlquZORKEwsvuReAWgSvfXdoLpHCrlfOzkxbXIpJXtk",
		@"JpPVjqpRIJnyLFORinSQvUpYKONVUcKKGdqgSMwDuKDQEUNArVNOzurOVslhaeBUXORhIrJVLIndTLdEjBGGaVwUEUtSAiLxTqSLiOqVmMamKQfRZufXHta",
		@"mtnrBuzUBzaQyjgSsMFUSkgyyuqeAWaTuLCjkpNbBRxrocwlrxauPQKilLDunZwqzHGYyEnGybHxZhkGwMGkFOOMYCBpxwlZidAOIeEHODRWYWzjBZatZfUOBeQSxfKVWnjltwP",
		@"FAwuEqZpsiCrOtQVgMJmgkKRtmbeNLvmRywbYxuMUWfjiRWRDnUbrvYtuIxOaqqVWQFkkaKlObJmoUJWhWLufJgiOCXaOutlbkrnezWEZAkoqgVrPOvqvKjRRX",
		@"rvvMvUEJfnsrsqHFpIZoprAgglykHHJgNmJgAyznvSETNGvTXKWuZkgNtuhyXzJYXxqQdTmCPUlrgHsQSfOGAOsffXUmeGRfqnzZimDGuotgRAOpIasDNMUiYWnDcfzVHQZgnrEKKeaUnf",
		@"gRlBnIzGdiLVkiXDuTkHDGUqDPYXaUUxagooJKxIPwmyLafqKkMOVnUvwZGVcpnPbWnZKuxpjwWTSdRxkDrQDHWXhNsqhMRMaANnDhoMvLIekxrtMSmMiqTtiCeTh",
		@"eLLIhfFEWMPSOfQyHspQygvbrXQynVORPtXEjooUKjokDhOhKCRFVGnbWWqxfnRcxtRMAWtvJleVLGxNzzzexItCyNUcAmzGQWGmnpCzMKasuNaDo",
		@"pYUhIwyCiTReDiahplNcSxQYCvymtJOOogSkfUERXipfMMnfhPeZKdCFSElorNDGZIfVSHjHqvZPSEliCWsxvdtRbscZdUvOSTWtoPyhMjBDSaVYmoTrqTOAQFdODSOhd",
		@"dulwwbRxfuekMVZyGWANtGFICpXmLoaKAisYjljGJafDhMtCoFeMNXcPSsHYbncpXfajJzHjvCKJxHPcxZJwjAVPKttkqUynZvqlJGSyQYKVL",
	];
	return rLpBrKdlAXdTfGRwxVB;
}

- (void)prepareLayout
{
    [super prepareLayout];
    
    [self.cellLayoutList removeAllObjects];
    [self.collectionView setContentOffset:CGPointMake(0, self.contentOffsetY)];
    
    CGFloat scale = 1;
    CGFloat width = cellWidth;
    CGFloat height = cellHeight;
    NSInteger rowsCount = [self.collectionView numberOfItemsInSection:0];
    for (NSInteger row = 0; row < rowsCount; row++) {
        NSIndexPath *cellIndexPath = [NSIndexPath indexPathForRow:row inSection:0];
        UICollectionViewLayoutAttributes *attribute = [UICollectionViewLayoutAttributes layoutAttributesForCellWithIndexPath:cellIndexPath];
        
        CGFloat centerX = self.collectionView.bounds.size.width / 2.0;
        CGFloat currentY = 0;
        if (row < self.selectedIndexPath.row) {
            currentY = self.contentOffsetY + self.cellToTop;
            scale = 0.8;
            height = cellHeight;
        } else if (row == self.selectedIndexPath.row) {
            height = cellHeight;
            currentY = self.contentOffsetY + (self.collectionView.bounds.size.height) / 2.0 - height /2.0;
            scale = 1;
            
        } else {
            height = cellHeight;
            currentY = self.contentOffsetY + self.cellToBottom;
            scale = 1.2;
        }
        
        attribute.frame = CGRectMake(centerX - cellWidth / 2.0, currentY, width, height);
        CGAffineTransform transform = CGAffineTransformMakeScale(scale, scale);
        attribute.transform = transform;
        attribute.zIndex = row;
        
        [self.cellLayoutList addObject:attribute];
    }
}


- (CGSize)collectionViewContentSize
{
    return CGSizeMake(self.collectionView.frame.size.width, self.contentSizeHeight);
}


- (CGPoint)targetContentOffsetForProposedContentOffset:(CGPoint)proposedContentOffset
{
    return CGPointMake(0, self.contentOffsetY);
}


- (NSArray *)layoutAttributesForElementsInRect:(CGRect)rect
{
    NSMutableArray *array = [NSMutableArray array];
    for (UICollectionViewLayoutAttributes *attribute in self.cellLayoutList) {
        if (CGRectIntersectsRect(attribute.frame, rect)) {
            [array addObject:attribute];
        }
    }
    return array;
}


- (UICollectionViewLayoutAttributes *)layoutAttributesForItemAtIndexPath:(NSIndexPath *)indexPath
{
    return [self.cellLayoutList objectAtIndex:indexPath.row];
}

@end
