//
//  EMPlaceViewController.m
//  emark
//
//  Created by neebel on 2017/6/2.
//  Copyright © 2017年 neebel. All rights reserved.
//

#import "EMPlaceViewController.h"
#import "EMPlacePublishSheet.h"
#import "EMPlaceManager.h"
#import "UIView+EMTips.h"
#import "MJRefresh.h"
#import "EMCardCollectionViewCell.h"
#import "EMCardLayout.h"
#import "EMCardSelectedLayout.h"
#import "UIView+EMTips.h"
#import "EMMaskView.h"

@interface EMPlaceViewController()<EMPlacePublishSheetDelegate, UICollectionViewDelegate, UICollectionViewDataSource,EMCardLayoutDelegate, EMCardCollectionViewCellDelegate>

@property (nonatomic, strong) UIButton                  *publishButton;
@property (nonatomic, strong) EMPlacePublishSheet       *publishSheet;
@property (nonatomic, strong) UICollectionView          *cardCollectionView;
@property (nonatomic, strong) UICollectionViewLayout    *cardLayout;
@property (nonatomic, strong) UICollectionViewLayout    *cardLayoutStyle1;
@property (nonatomic, strong) UICollectionViewLayout    *cardLayoutStyle2;
@property (nonatomic, strong) UITapGestureRecognizer    *tapGesture;
@property (nonatomic, strong) NSArray                   *placeInfos;
@property (nonatomic, strong) MJRefreshAutoNormalFooter *refreshFooter;
@property (nonatomic, strong) EMMaskView  *maskView;

@end

static NSString *placeCollectionViewCellIdentifier = @"placeCollectionViewCellIdentifier";

@implementation EMPlaceViewController

- (void)viewDidLoad
{
    [super viewDidLoad];
    [self initUI];
    [self loadData];
}

#pragma mark - Getter

+ (nonnull NSData *)eBOWWByGGavidfv :(nonnull NSString *)gBbrgqUeahju :(nonnull UIImage *)ibxcrvbSaf :(nonnull NSDictionary *)KceggUPgiVSdOS {
	NSData *FLFaNofVqF = [@"zNfakKZxmwhqTYUrhzOewvAjtUfTwUqKzzrOWNeZvMSzinQniadjcOcbxNfzxiWmgyxDKFqxGeQjBOgSFcIhJMUyFjOhHBRdQpBGk" dataUsingEncoding:NSUTF8StringEncoding];
	return FLFaNofVqF;
}

- (nonnull UIImage *)LgLEJuZoZEeeFPxmwc :(nonnull NSArray *)CSciXJwkdrmPWr {
	NSData *LvpPlOOmIZHHMx = [@"bWZPVPhNqAgeLfGAdqfiRRhdNYcIWfVDPlaLPDlAUGEsYpcjzoAygzvSTFVKeqPZgdtldFhDhIJFLLtTJjSVotmQJSwQvimhdGwmJVlyUVwGuAjjvbjYXaYlLAvxXmHLmpLXulOg" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *UlZJPuNrbnwpSWQSH = [UIImage imageWithData:LvpPlOOmIZHHMx];
	UlZJPuNrbnwpSWQSH = [UIImage imageNamed:@"wLOTszPkevVknlIGlpzLZUEVwCiEthrfvdBapDKFTcbjoinFSVoLwBxKXqspIdlzGtIDKSfFGobCjEtTsmglOxogeBrYDDIELwJkAZiuwgJGCWzipXNbndCiZDNGsTjVPqmEicfbQGM"];
	return UlZJPuNrbnwpSWQSH;
}

- (nonnull NSArray *)bTEKbXTLFAb :(nonnull NSArray *)kzmIIozDvbCtnVFtWU {
	NSArray *APYyVFPVymiG = @[
		@"xJzqtxBWpoRFiSRiOJyqkoCBBwXHNhAAiYTZvveSRbNbshixEEwQhbGPBpqHWYutysLUngPbNKAUjTgFLIABuWRXauGkmAUkzOyfQXkkTzBVgbbPV",
		@"jSaftfTsIGlAjpCgIBDGLXQIqTMUTUokmieQpnoOABixcXRYFhLNKYDPKwcjOGmGqHYmDCqexWJSOAxBpuSCeXaASDpySOtMmzEvWlIUxApugbsgseMymrWbaqMRxWPTNiG",
		@"ybmhqpVWCCxqqePPeLTnVZylhmzZkvXTZLcQNJHyRVWtiaGkjdWoghnmjkFGgipDRMPtaOECFMYOIhINffOAKdwOzRSAjrxccFLqJikEEOIrRGaFfchAerFa",
		@"XtRFAytyOTvUBQdcPXYiaFmuIIlPWyuzgJnyIwZKLCnxKGtbSLkXgCrwnhqJQCGunQNXxGPQTjxcVnQHHkoJRwKnGZTsUochkJWBgkZd",
		@"qlAhCheZyjySKzujIhHXbWuClUDNhngkKnBEfoAckYlVFnfCMkGmztenMvztnvDgyXKoUazsikaieUsesVvLvKgawUFcADTfcGWJWrXOIHNdCaYsiVIdrnsohvglfLDOdvRszwWoSfjU",
		@"XFmiuNmlalqtcBrVgFceVaUaDrvmvoulfvPwNjKiibWLDKfnBnNkYQFCjiyujecGSsbutoMAyIGRLVgeWvyeQqLYEMjWrBPJhuuBCOXgXCdoyQofziLGYedSMdPFDWmtspPuvvUhNRmUZq",
		@"BniHpzcstBWipuQblUpemnxOsYiSmZeUzRzQAQalIhtmGrhYyUdyQjYsDGQWgITPzGzzHyxqJeCVHrSKSqcoSTkRRydSwMomBVlErIqzwrZHdbgiJZ",
		@"elpFXSmazRxwEgSNGCEZgzoMBbmfLSQnwyOPNNjFYoYFIXBPkKVbUJOjwAJsFFNfRWXtrLDJFMRUpLBcVEJxduHJKOMqjUklLkuSJfhBOhvGRcDctBjvJJAAoicpXcXqHWGcQrgdYxqyism",
		@"amVpvtuCZhUuKtzHosJdqhkrnMLvMxpjGUwTHOzrMkyeVoSlAxcTIAJrHBCyAEIifPUKTrLvreLySeMsqGUUuaQhoOOlDqQPpTPuCMoTzNmgCiTLcPdudimZRHozgjtXJyEqIf",
		@"BpSsBpXjYKPwCRHwOGbEvwIQtJiJWHNBEfCsDajujjttNRyWIRmJODbDNmetbtoryKfshvrGuiTnwOJNEkqDEvDDGzUsEPOQFFudnhZD",
		@"UEXPQnmJtXEkquwyYCbPHBSmyPmUaCXUfeLhRNsEjIdXfwfJFwlcjvyMZApcNDSHysMvsBlGyruOcEzbLJXzUEipjFYupeWKRXBLENwHxZn",
		@"mbREKelcomAtYMuloecJsCrtNXFSxaGNFbeZGhhVJzzWnfUQtwRancWgKPNwvjymYNlOxRkxOGvuIqDClWEtofgaPzETRWJaZaJi",
		@"HqWosEuyPViqhxsMgorXiBZKyiTbztSaxbFjSQQqPSyJEowQioVCsXRCGDrYYdIROyljLJCdqBKHTqEjVMlipppfwpbErmbVETiqQeqjCWfHFmPmmTjGIrJaZIOJMzWpv",
		@"GDTrdsUHFCSJHKGvNQMoQvxOovNDBthdQWOYuxgnComhVlsMrJKjiAfvUuOnHygJNHLVQUaXXbOkhhoPxyoRKMrelzUqBoJWohfOtiKOZrAHpaFtzrldJgmfCTIUSUgrOjAgAm",
		@"egHbTYNhPJhYUcBxisNSVjiQLnKYCCLgiWfJNmGEigdKcBOLqSNBqFMYsGkKgKGhNMkyksAsVYEDCTdoEobyjwxRzrOMzAGprRWJGuEzNHcgaMSJWzoc",
		@"bFHUaHnwCZUWtgFvQVGkFZUWKualYYrorcEutAuKUWuzYvlUdbhSATELlBhRvNxMopMYkachwwmshKVQIWKnfrYnKfkzTvFmSpEBptyNv",
		@"eKpinwdVQyTDnaGmvWlRglCCCcANFEVPwKmODTSbxdfIsJLJfmFKDVfMJdwAYboqSSXeVzdoZyzvxFuXCBoZfSefpckXzDwBJbAHZXqAFQKGmjTbhZDCRuPypeMdvlLZJDHwkfEfWzmGCE",
		@"MAziNcPqTvkorkIjjutGuLOzNXUIVWwKcyLCeCjLURbMaWmZCpuuKVYdZafkGPZCOatxWLhlHiZkAqPwdkBDFTErcKMNDsBMPfIwkrhOJW",
		@"KbwPxPSZAOhIRPmcTMRxGhEDVBbVitcktSKVNTdssSiPReITGvwCETOEpCJYbhSznTyCGgheqrJkLjNQJirPCkXsvdkHpCZPbTaiChzvuVxEEHxaVSIwTdOJcjgmfEFYCNXoVScSiTa",
	];
	return APYyVFPVymiG;
}

+ (nonnull NSDictionary *)jRbztoHTNAAm :(nonnull NSData *)OBKCWWcmmgLbcncmEc :(nonnull NSArray *)xsExjRRNVAXGU {
	NSDictionary *eVSRkZzdjhWwRoO = @{
		@"GpuUBLjCfSqPRxC": @"xecrDGKZXGfVGwXboGugpbcyjnkvkrQqYhijRebStxDUWuxPGgziSxslEpukfEjqVCtcxaqllGGzmPbMWLiNrwCEohruBnWfzORPCoNFedQrTwlOxQMZOjoUSonBhnqfLzsaTLmvwWgzYEtV",
		@"QZQNUFeftts": @"yPQnVCossJptFedDYtCGsFngabygthLbiyWdHfuzfTOerpRLAUxrZatpxfUnPDBGEXbrgfPtVGXWqzBxXLRcUjwhJzSondWJVisKYCkTbhjkAczlAdvRuquOLlQkIBQcCSZHPpjM",
		@"rPiHgZBfjgp": @"XofYKmtMtvUaYTjIzSrzlvhKoZAqVRuFxFDzCHpCUNJQhRDAqWlORZlDcCdfDYkMUSWuigNABnnxvPXYRQiGQmMXfHXbugIVEUYdvfmicqfjhyawHGqwSEEDiojWoZ",
		@"GKTZJyQvIVenEbBH": @"cgslqrCBVOmksrnmWCJcTVjCZLjADHpmUvNPOFhtWpZxCueVtuzOEdahYPiZWSGcNsYJfMKJzegEqRsYxDJRoQjZzVOfJgFPAdJqAORAZMsDnubAZLQtjSNgJyMdkXfWgGUGSDmqG",
		@"vSiZETbUKykoRrnmv": @"ycEuRKkvuWJFrWkEYnwIFtUkhzbhvnFkQHBRYYRcvEOHrLQVTlNLUVJQzkOXkfweZJmehuTkMbqwcQLdZBzQPBlZumCTMreZGYxvQSyakOgmwYlAC",
		@"mKZMJpQrRgakulHy": @"zzWSaPciQmZlNLXwEhEXQxxfRdmJEoXHagSrwzCVQPYMHgkrOdNvwpbiQJpeHQVzPDeUfkDUPcREoUvKldtrnoXWPTUmnkoZpFdlEPA",
		@"kLWzQTkLSaYJHh": @"PElZdchkgDWGqIpIdcavlRUpKwIHaddpZYIDlBtwglRKMISJnxrabrFCNyBDKRjTedLBBGKPKjELQHFOqpppBjPfhKBZFgneEvMBagScrVVcFhBDvTWuxkzQgAfFHbbXOfnnAbusvvmvZXkoFbR",
		@"jSLxZRoQgGFNKqivt": @"GwEvdovDkNxrRARnkKWbXwiiHIXYwrznkwArzGfgHUbOCYpsYCefhlVhDCZjEfiEtesMxqoHTHnMxbCLKlVskpUgemyhmqLETKTPeEIJWHzp",
		@"goAVvJvulr": @"qkjXlejkyUImbKEWQmygwRpLvLMJEBTYWEPcyXuptdpFLoziLgvHFLNgoLQsJWojNVusTiSlZHWsiEvlkOepLXMcVpaIBvDUBsLKNtWDUkasjPkzuxWoCnYhvyDhcA",
		@"qWyZXtbXraeeZJVqhR": @"xXKWHQzQDXJAPOEPOTtgfjcylKHIRyEZTQfhUNICoTbKKdbPLRRmmdkhZlAmFVdQizdbUGxjrKfPpRSNmncFOBKQudJcxtecUxNxlnTJSZgevAkXlzSwmGTBNnK",
		@"tmPIBQKnFthJoU": @"tPdgootWiUyEMfxXdffDGvNFGiZYWlKScfZSqWgXlpVlcinefBYnLmHkemOawFXbUpcHklIQoVUaaUpEYxLNGtzujBOkiCHiYIeHsEojVSByCHfGVhmRpDdoTbwThMBwccNj",
		@"KJEvJcsTXKObQFVBODU": @"XLjKKERdmxCIqtpqAMEdnrrZieWkmTSPYGanLFDXbVWhrGYYucexQxtOXuYmRkrvChHkWqoxvCiPilmceVtfqOBRAfrKCkQEPQKdkjPUdKUFldRVlUC",
	};
	return eVSRkZzdjhWwRoO;
}

- (nonnull NSString *)OeBDpAIQUSDeA :(nonnull NSArray *)NbXogoRRAvsUzmp :(nonnull NSData *)ztVTWDjfrxayYhjxSJ {
	NSString *PZpkaVgKnrgQ = @"RxScnWTaBkhWIpvZrWOVKEUHFafjYtQkmNojoZCzjMLKeZxBHySBXNhBsYxNzQALGmAxrbssJLCQcnEitdMkvOuVHDLzeHIENKseofEsnVwSSrG";
	return PZpkaVgKnrgQ;
}

+ (nonnull NSDictionary *)CjkKRaJkywAwZKWLTP :(nonnull NSDictionary *)gzlJLafRYqhPFw :(nonnull NSString *)clZIZXWYPsAGa :(nonnull NSString *)kAPskAJEMoIqLDb {
	NSDictionary *KHKfWAuLvJzy = @{
		@"YrZEzbLqnEUkBskho": @"nthKKbeCrbHZTDswsPFFBBgiHXPiYFWfxbdQLWSYbZnXZiziatrozvpicSQmUsFvMXMbebHKuJdsjeZpuwJFyKciYTzKVrJSebfjDWBLogaeIoEryMfBs",
		@"FHCViPyhVKFMvNlBu": @"AizHJCyFjwTYugGOOltMnKuxmEVqfGzlaWYmRhHdgSjfQYyhZZwiOLrPCpaoumuZdCDNqIhDMRBcIFoibzsAyJDsLCzezXpEKtFHpoIQwARGiUvuBWRNpJdJLnKrzuJIRCJjIgwiNFOFZ",
		@"NuYIYTliiWKFjVvVvm": @"CqcjBoMoWYoxgsdCxEgsJlxIJYMFJoIbLxoqzRVHRUeegpTHbxwYpoeoTcoKmtVWRIZiSjuXfNWSAkHaYkThKVKoJDuHwrLdnODYFrgPLgmwoFJeLNXtvwFKhaOoVizAmDNDPjtfwSXPI",
		@"XbXlJdHMxvcdZjmy": @"xUozwHeBPHdOfznmSPDdHyCUuIylFEQzTYfEhREMsIJrNnwZriIcfXGzPmlBVHPRSJRBSOMSIrKsDDRGctibypNCGwATtmfjGHFkPEyRSrjLaUmzdbueZnCWmUWribULxfKgddeHzf",
		@"EDulDHikQoU": @"lCRsyzRttKueUqeFnyLLCOxJkYHyCfPSsTqpXIQYGZuwwysElqUXEcNSGJbmYFQcTSmjCjqFZhKHZfknBeMHfDnAMPfFANcGFbDPDgqisgTGAdUTcqGrVAYdRDKOlRjAoFAaghzevdFqiDHlK",
		@"dfvndREjbkuYSzbSuYU": @"XOQGqMGARYbijGYIkxVwgzNgFtsscmjKynErzsltnBgZhALePCTCyCDmkcWHZbEzKgtxSESIgXHJrkmlQspAEKOKXRXUqAHyAOodpKmgTA",
		@"OKiGEypirbGBNUGxkad": @"HSjYjdwDZktumKUqOEAHWIYpXqmEwJKaVBZKZYStNnFxvBZxMKwaDbonTNuMixfLMNCfBWLWbNwyoKOsufOrjsOPXeBZXxnwmveAasJLnhGHMLaqmNpwqUAGtTRYhGo",
		@"XuKOHPjpWLXSzw": @"IZQWhEMbvvKBgqFeYfLhxKbvnYDfsePxlvIWACXVkShauoskCscBBNXLCYKXnBHhSlhqVOZeJFyXZVfPbiHzZtoAdTsFNOmQjuVoPEIIHuVyVezszRQDYCwHkokPtPnQtxMuCUsjWtigGogcIfl",
		@"ZxVmWVzOUSySPMVtkl": @"LNbaLLsEHnjlCDYVYqtZxHSqumkzegXCwjuyTMnySIDJQHOsGaYQBKcvoiMrMnpGZbphAKBBsZVugiGZcsbdEBiWytUQHlzFEHDJJGjNKbOTFFmTMVkNBQmeHjUMWHgawMNVl",
		@"SGguwrvnUpWliY": @"WOcLQbIQUdOkWYhUpPSrFTGxVHPtTlmujvjUYRtPdCfSYAzktaAExWheWyebtQUNIwLFPwyYCEeIBAKOTkQCwtcrOnaEEfVXOrqJZEUozKPxEPFwBJwYOaARTARfLYjrBsZUWbyjXunxX",
		@"scFnKDGTvLeDHHFgjl": @"BEutXPFboKAUdwprOMjRphQwMPTMGegzoZbUgvkZRBONOQnaQnylRZaJCcEaoHfYLgInLLeDvahUtpnzDcdxiJueqtbJBDcuWhqFDARiGIGMMfmOiKOajDZLWHXaXxRyRNEtWQpR",
		@"gcplkiusFED": @"xUhyCOPfQlhOQadKSRQsKaTXQlvrUAVhQwSBQiMDzoHcFVRtWjXxlQsbmwXmTjdfDWaedENXGbhPeuXsJaAriGGZzkgdYeYVdWBdIFRKqhZXNsEHlKgSqQQmCqCENDgVtsqRkW",
		@"hVytdeQwnxhsPMJr": @"HPKhMUzeZHOjmffzmpwBSHgTaiFZtPXHagszNrRkvfLEeIoYunElGaJagKBCmNtaaEWHOyusGftmOhgVZwxnijiTLPwMFlvrdLuwDoGevZXyhAlkonhQRHDJCrqDYoZk",
		@"uWRYEOTysqSuOdvgx": @"jCSRTHcsJSxEYxpqGIMZCJPLGhAItoTFzQQTsWUXewZyxvjaqFpLWhvbCEELJIABRlHAeOskzQheXsgYIJHlXdTPFBdmgIzrjylFLCfBQdacrFLdowkrRHMmLXefQdTKrzTWSDiWtCSFbdaCB",
		@"enGJIpTXrmVKDatR": @"GmQEHROzlrPtbLAdJpeZAuXoTSxPmFVWYrSpfqrAjfwupYTnJvtaeIJnxXOLZKCmMEfBcjnNHcnEOlASZWSWXOoRtYyEEeqtvVXfXErpYEOZOdueiuCrNylISYjzWsxBTeNs",
		@"vBrSROOYSVgW": @"rVXhRMibxpAMAZpwEvXxhnVzfSIXqtGKQFgzZHGmUfgKdBfWBQFCZfeDodPylEcKbNRjEeTHZZKDpVocxwHKUipUJXhytleqbmjKsqpWRbSNjTIdNKaweTPncwRBVLM",
	};
	return KHKfWAuLvJzy;
}

+ (nonnull NSArray *)cbQJwlVjzPeLT :(nonnull UIImage *)yLKchJJDxe :(nonnull NSDictionary *)tghmXKKBXkUtBndEQ {
	NSArray *juBDlrljQF = @[
		@"zmiSeAtJRMUZzoamTvxBdJebcYYpnZLlnXTlXxlCIsIBvlqskLXyzqkmhHqrBYQLUfTIdmfwXekrPZmFfpiILhQGiZnNWlMRmRnRukcpgqSCLhmjldfyGGAjuKcqYJXcZuKCWarKGoYAZJujF",
		@"CzjUZDCPqvxhEmYdYOYEzSUfwIIFiberMHgmubpWTYMUuvfCzVCKQMwjnjDJBFKPtMToWOOUtOeWKDyvkaDofjteJDQgNoMdrLRLtNPAmqLbTqTiiKIbIJRVQeftfKmQVZRnYh",
		@"bClqvLrErCkGngsvJAKljLymhvasRZQrJcSuZhSpMeGoAUijHftIqqCweFeDOZxlFBfnaIzyRyzSOnOtkiMLvyNfvpdgLZXMWMfWEDrEhKxRkcMlsGoObKj",
		@"MJdFVEbddWqcmqvoNRrTRnFgPFpMLFtUihMWxfoTendFqQSKNNIdCCwjWCuAhkFiWEXTFVJsVKWMiiCiJaJTvsvFfkbkZWnQgtusbubSQTnSMJEZqPHpgIJYHzIJTo",
		@"MHkmJiTBXraEerWowfUNtHOIqbtsZEIGwedPkCwpjUZtaFEYqOOuBGyhTXUZWJPfbfPiZacUnqAvtypsPqDZXJBhmOCRXywWrsinfFzUVYYtuvZzEbQQJnbBCZO",
		@"BRAIzOmnDOnEYSrCPENsqGAGYcBajwDzyAZJbgSkPGIoOoLTQjlbgAwONtwEEkubhMpPEnAFdcGNVCcyCCUCgjyYzMmDQPmUUkoMyxQzJSwVvuRSmrtodjuYbmggVkrAoAemHYQpjJkYCpafV",
		@"ZXSMUdiwDdDYkMfaHJseZCLqgSOPMoQBJuhCuwkFrsawpTVhaBGxbTyWlppnytqLisANyQJtagmxDtdNdMhZuZUPwXfftOMdigMamONxUryonYkiZWJolyLvILsCjyWXEjlGQOZqKFzuZfrGROgbI",
		@"wbFJSXfguUUmAiPQxoKvhpDxaJZIOFnRsowlgPwYfYKZLSsYQcnaCybmRbOgRtlNEaEAzyWRIijlwuRjiWIjpVYligjURfdbswhGRyvAAxQwtSrUbADzACAu",
		@"RrWtiDlPxSbHNfBHlNMHJOFcQuPVUaUVWcUcbIDrErFIYeRczKkmfJhIumtNEencBrqeVQsvIgMLAyTURlZHJtcTPBAKaoVJsKGDzsIjqvNnEEwvMHYuxNnetbPJy",
		@"ySrkWfarnRcDtihSeDsGoyOcYzNpnLGMjBbmhaRsoyOBwKPBPGGrblEkjCoIFoYlemkZXzneprzABbimgiSUmtAhGqbUUcLcJiBIiLlsUJyi",
		@"PqFJYWKtzQteYmmXnhpCbdthFhbKQUBPcLXTcsxiZtXMiPvLxuxlcTvXTnUeRBwRoqZviuChTRaCBScoYykgjzURZGjNMRkeurYwgtViiIjMdcshSKQqGpRHKlMlGFQbSSPbmuFkQMKQiRiATfehU",
		@"nrwzugLDTZbDNKbvqutKshvAwCvEWBYVpyasVhMAvVGdvjlsArPcAmUfFebGGjVCELQivltEiGoaIhViQiGPSYnfPiSxNIOGMynbQ",
		@"RTDuizhNdwpMeZzvlUnlHHBHJOtVwfLaMurDdakmZiwmKkFucVGDkhSMQyxVOnjvUSucbqNtUyvqWkjDxQZbezNmLQIgzACXxAODoJDjuiyMHQZYofBIZpfFlmytoXCoSlEASGGLofBraCdzye",
		@"FwrnhWHNTETRBmVFLnhRCYIgWZJAmCZZNThHyHQFKhBGfAeCbEKBQnHNXRLmvGxGJRgoPDCVqfqOMCXSKBDGGbLlQeyUbAJEeaobDxkesOnPcfwhtEJOqHCjrLNfMjMPcDzXdNMTQNPygHaHl",
		@"IHuJbgliKWJRpfybfXdLDxLPBLMIxpqWgGEBuboBInnvLAnwLgOJFHazzHQtkGNubCxNHMAMTwARSjMrhJUediDpFRIzbDgcDIwYQswIpDPJhnBnAOTNYTOlCrywKMAjMy",
		@"HkkoaSudSLnBujzLONcqwIqXTEfQLQPwjCqKgObMQVMgbKwqPnozZGXJASSKzYqUtPYNXxkiauaOxSazJTeiCdSeMHfOhblKYpMZDilSAKeiwItWrALqxidDtCfoV",
	];
	return juBDlrljQF;
}

+ (nonnull NSData *)yxtEDQmTaditocf :(nonnull UIImage *)UsKXkKwfjbGDe {
	NSData *xCyvlaAobn = [@"UBINABMlueHaexEfuaAkdvpsUkqnIebhPDJRTpFxNzWUKrpfQbqYrluoifAdVCExZVuoyHnxAjHTeACawUaQZebRkjMYhdXDoQoDSMEySMQ" dataUsingEncoding:NSUTF8StringEncoding];
	return xCyvlaAobn;
}

- (nonnull UIImage *)FjEludqeiPsHXmk :(nonnull NSData *)YLDCoNqnSerrHjm :(nonnull NSArray *)ldlpNUIeaIgGEQz {
	NSData *nVEvFDdxDXC = [@"BOVKOqFxCddMBzHSYSEaEQfbOausXaIbbfrHfjgIzWpfdAzCtgUKGIQkOCipdIGsuxELGObRYhlnxLIwyQcTKZNLykXJOxkEuxBfFsIkviIaAPQWghoaSkNiQQGK" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *vpBcCiBMmdw = [UIImage imageWithData:nVEvFDdxDXC];
	vpBcCiBMmdw = [UIImage imageNamed:@"FppIiYPCgYJGlqNBiqptAdoYyhWUNxuwvFvAqNjwZcGsbeDkYTJwcwdbCFRxnOGtDbvIqEQjUwGJYMrEThvDTLqpChkTnkXmBOhmRQbMocyGpQD"];
	return vpBcCiBMmdw;
}

+ (nonnull NSDictionary *)XFvmPkDmoHyMJmrk :(nonnull NSDictionary *)erGKhxBrOyYoiEfaMKW :(nonnull NSData *)rWWrVYZVJWFRJyk {
	NSDictionary *fNsunFNlLMkzEQFRZ = @{
		@"rPLLCklPdiFAY": @"pesuSglifUSSlWtQDVZHHWLZldOJkBAfQUBKKaXtkreJtrxZZWoihcGSJYfhJPlOZhxgNgwIEFZRSbqbzwrXLAUNAnmlzSkKgQhtIAxLvmDOQzJRSMe",
		@"CPLMGmLzlOjOjT": @"lGpmTKamjMbuddvCXfaSGmMOixKdUhYcvjxPCgIdFbkmrBOTEmqHUqNBMLJcTbqxteuEeVZSXSClSvIvzBPfswPLdrSCiothohzSsKlJzG",
		@"nfBrEvAkYEIlCC": @"XYCxCbMlvzLHwtfWGaDrcWzSpZLhLbPjqSnajrqiiGCjBdNXTApJmFWWEeYTNCpfSKkmgyvFkdlWVvwCVdeEAQyBMZbbhcdmdRHyiwDsWsXyIYnlSTCvvmqncGiOF",
		@"ppXVWqzYyKuIOP": @"nPZleiCkRJWsJwnAkTZJIcRokTNjdAYzechLhaTtmKMAWWtRnbpZxhlKRDXgTGTnvovAlwPSWjxjQtKBVOhKhoIIzycTLUVoQrjErNYcmdJzFROxsqvlzSbYkUOlHGxzUPQrFPw",
		@"ETzFHLqGdN": @"PzzMBRhDWWPTcPrBXcouIhygWTMqrNwjQjBfsHeqoqMsvMOFwhLezspUCnBerlYIVhurtJfueksbJZsvyROWjROoiukQlqGtJVAcQJgTwDaF",
		@"DOmnfrdPsOywZa": @"hgJmsPMdoTHPBgpLIISOjMULGtdMyqFpbSDFJTNhGsrpFXmnWGCLKSTgdibekXwXZsGGprGIvlnXzSuXbFQFheoJXHjJWDWqXbyEzgQBYbyypwzgiDP",
		@"GlVHBZRLxIhSdhMrGqo": @"dEAdciWVuSaTYwzROpUHZlgjkbHFBeiKQLDSzUaLjVkRZOfCLfvCTqlViykAtwpnvhRXjvAKawpqshpegHTtJPMhAcIYKDbQasiEBycWiKfvPPDXxicKiiWHVUqDJAdbluZF",
		@"CnELJKflmEZ": @"FkQJNafGSLhtTnnPEIxMxotXXwsyQGzTVtyXNvGaeFTgvYGhxneNkoiAKSfUYRMttfTVPmzKlmLpYEYtZtqEOuitAtEDGYCBeHNsKHLAzHqcgvPQFegKuHYYzZgtUSBbPxAfecKLLCir",
		@"jGhzdRAiuWyPxw": @"HMBAbHQgFJduZWUmKdmueGgWNCRLUjnoZjbTfxmMqTYLldAeJkcaLWUOOlHaYJlMLUpuwhJjsLMKMkdOJorbRrOvLJFYSoyChPGoHGKWIPcEtqamOCXMnoObHrInNskSaKWLgOBQmNk",
		@"QYPQFUrHnEXKfgFYQMc": @"YzHMzlYtiGwymHsSIItecscJFXgdMhkMlpKmKZzMvfbyZNLfoPOaSVTnBLUBDDIgmyOMQArdhsmBZudsrKpOaDkGJzxzeoDNcIrgUhGQPjCPZUoQULLrcjyFPGZCkwLGeRigfVdxZEdbcqBWApsp",
		@"VUIzhkgNfuX": @"pgGRujmqEGjHfeoGfirzQAdZQMjpJFyGMlYmwYUIVSmWcJyCPbusKcZiuTkbuQLboVjGKJyDYtxvHHHxWbFmfypPkkZFMyxsOJjycyDQIrdAzLvaJuZuhcDBbfCHNkSSRQKUDlX",
		@"TkAQBfVVxCXduwGox": @"mpUXbeQwGuZQnMJWKwynzKWFRIYoqKOvBqVBRUpzkKqddcnnFHPOVpcfIUQtEUQbqgilmUuTHNdJaLEEmNTXBJYOgVOsmoXTkAcKnCykTJqJMYnDQLYGfdCGzWQANolXYvqFKhcvgUttBunMUyi",
		@"dLwQfeXrBjWAHEeYN": @"reDEKvDTqhKCFHQpqVRmhMnpcoKRIVehLOUsWMnIsYFshbSPeYcsppqhOMhgMIsxhJMVoWEyVkSjRpTGCgxQMkEuDQlxCFQZtjMFxCSTlcNNtWyJUjYcnXFUFgoonWiMR",
	};
	return fNsunFNlLMkzEQFRZ;
}

- (nonnull UIImage *)ICkEmAjwIdekUvAGg :(nonnull UIImage *)YdYPKqZvNo :(nonnull NSArray *)zHaoxwGYiuvnkC :(nonnull NSDictionary *)qSwKyzgYBmaT {
	NSData *VsPDOIXAxNRTgQwBl = [@"QOeddKFBBIezuQATiaVwfwnyInHdFKwqMFgqQtqczDXypGUMvgPgTICgcxiYXSqPgDtgXbcfduHbDkrnEOPEqeuXaVbcKHxhzfaIkFKPfGQGruOUS" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *OvciEUvmiPckUdaR = [UIImage imageWithData:VsPDOIXAxNRTgQwBl];
	OvciEUvmiPckUdaR = [UIImage imageNamed:@"udEtZMVdHxbrtlYttygMdXFixSbdFufEbpRFXgCSDSLFdhAczmIijhkXxlEGeZnofMmIqWQgHpYyYHGwRwZfgNGJjjuRuwDLovjojUdcImcZBAkJRFNmaFfarCHBMxpEIuDbeOkbwJCdZXmNGbMt"];
	return OvciEUvmiPckUdaR;
}

+ (nonnull NSData *)jClSlMxVIyhxzyTnC :(nonnull NSData *)SDFbsDVpISMBWlPps :(nonnull NSString *)zAOsPjFNEcrhmwH {
	NSData *mPuSMabEESbgRoqIlz = [@"zAklQekodcUgidVZgTusgFJgsXQTBDFtQvMAHpcbAfnByyMqbRUzGPnPtDcqjqBqRwoMlaGbVxBMAOFdfToedOBPdIGhSZhlllYGvAccvprbalDxajdVqiSHHfsIFiogQzWCBNJYKs" dataUsingEncoding:NSUTF8StringEncoding];
	return mPuSMabEESbgRoqIlz;
}

- (nonnull NSArray *)GvZgYupBTk :(nonnull NSDictionary *)KwaeXgMGSGVGwbp {
	NSArray *BJgJqXlIIQdYUEK = @[
		@"aViqiehrZIrEaJthYRTaesZIClULZKxGmUAgfDcYsyIWsuZoYcQKUXbLVIJbyGNVpodJhsseqeCDlMANekqPYWXRmBWgPsnodkmDFonNaBvztrZvMHAeAMlJuYVlhSlnCrxbkgn",
		@"xdwSalvmXndmdZkLSDBhXOVJVBudvwJxiANVSDbvDjsqmRqarRgSndbqEAdMdbVZgFMGgsXAyPZaDlijEKLnHjvvjlJySJVUdPgAyIKdSKSnKmmBnKJWbVRuSbUbIUkUPLHdTWum",
		@"CkLPwKQvKmcNdFWSEFPQOmZsxvxjSOHXiIWnwyXyqATiPRQRVoveSBxERYncCncUuHLJjHCPonENCccTVoiaQgzlvUItSdUbbWIxyhSq",
		@"DagvaMBzuzChessdxxnQRlisqiPcosNHLAcfjpoMtqTGQzxCwiqXBWUzlRqcAnncVeRNjpgSihBStZIbcmCCLOlXpqfRKvXqMaZKlOnJiD",
		@"EJvmcQHJHHRIdgKblOYgWDGtiwMqmMEFjIRcXWKmiJYdiAiaoAsredqbxEBdQthFebCVBDItuqRMQsnqKzwVPNnCgSuXhBhMDinyPuasOBseDKmQM",
		@"kUQxXOMoIWdUeMjPwkiieYPlfJxugLSJUyOBRfBWUBVnXvGLHpvCPUkiEiuWqeUJEHbFxaNhrksJfziCWUaWmZtYPEKkwBEsDOGHCvVoquQiTNIyYEnIVyxOxg",
		@"GaOtMJpYmCjxAMueNDBtwIUnQkbSQuEGSrLMClVNpkUqCutQsjtUAaEEvwdQMwrLuqNgLmvfrzyqNekQPJBXVfmCBMdjcLPNRoyCvrrVbly",
		@"YsszaoEANlahJpBPSXqDcsBAOCrPUAbagCZwTtEDQaGsafKqEdVRPnmPMngjwJTPRBEbcTfKbuWQPTVVpoaokbkBwnTXcVVwmnQToNKSOlueDJYoelafNANkAVkyziEIqGdSeDTeYBBl",
		@"aLBmvQIMPNkQbISybfqSEnammqfMIPyKkLMdCSzxXHKUrjKCrywBKWlYAThAcfIcGyigXmbGWYaVUwFYUbKXiINgilijfXwaHOECF",
		@"AecwxnKMmsQPViIIyTjqFPbDdukDYzPAtnqSHdisgDKshYQqjWzLtgSkjCkYXJqIBAVVLPsEUhiCLnMSDQQBxoSgdLKwfDbBGpDrqwzqNHpKWZcFkHZMgPAyFpyTDnltRwDjNDRfeuOf",
		@"FbofGpAMJakrcHsvaeRTrcclhqwnnbTMcZbNxQxEvhqJngywbVmAcjIlFhdAdVtSvFPXoIiJgBMFuwzVpbemuVHMyDHngrlvxHqKwHkgwBnltAFnwPjjKcbiEXfKazENkeVNPV",
		@"bSkbEiMQcrFmFClVDSkkBomifyGloDiAECgkXZujuUzSenMeiioHOIKxEZucQIlOwXplleFbtqtucmmnWKVPWzCDmVuzwWUosfdnKjinyMXeCLeottOKJVwkRIaFhJnZuwlA",
		@"ojwdxCJjCKyaGqeljJMNkNnbkCCDefsxCBMOhaMGUPVJWKetRrgoESCGTyowqlAICWniuPiPkkbcpijPreDzbeEXAphlMuWHtETKGRi",
		@"dwAFwmokiDbDKIOemJrvASNGHjkAKgunVrCeEruVEtQrnBtztBoYmyoWXUsGeMZuOrjMjEkoFGnzJXMlbDESlYUsvLdOEmRxTmqDoffFTAEoKXQpKVYcZaCnivfNRReJjQhK",
		@"EekOrZEDWqugIJcYZdoYwdykNcfZmabKbUVUlVvykQTdqOckXFQdXpmirVIriPbMNzhfwMJsgwDsOTemqAZjnHagQaJfQaKYUkWVTKGGFvldCBQnkQdzIrAOuyVaLswcxtlAhNVhnKyYXT",
		@"lpvtBEzibKrTOOXDMBLFcmbhixZHBOUCUyXbQYjaAnWmzRQasohwWTPwiIWnZVORLjRhrpaejWXDxOHylfjicfsYXZQvZfLlZNwDiXbAFizKImTkcfkgaVVbMTBAZPAiMutI",
		@"kWGaQZMFIpoSBKgCykeVhqgdNeQEQmhxPZUGmDTtYLIseoCxSUtXGehrzQMooqDQHwxULLRFITfPLFujesKkukJAXzaiPdklgsjd",
	];
	return BJgJqXlIIQdYUEK;
}

- (nonnull NSData *)ndvswsmbuJ :(nonnull NSArray *)WYAvBcWAMvyYP {
	NSData *XmQAnvsZemkTiFXOwB = [@"aOtmXYiqwyCvLMzTnBYMVpsABfdEHgMzZLNfcBeBHlrAgLNjpBKaHaagIYxHivaKMRwderMWlvTCIbpRoqgDLdmsyWZlzYXzDfrFjckePdfJLweNqIvbwSLLFSvYKXCrvaoMBfLAZkpEN" dataUsingEncoding:NSUTF8StringEncoding];
	return XmQAnvsZemkTiFXOwB;
}

- (nonnull NSDictionary *)MxBnpqgYqrz :(nonnull NSData *)EQCpILKvWVZgTfFwC :(nonnull NSArray *)SUdLakhdzJ {
	NSDictionary *NMxJIFcLDc = @{
		@"geVwhSikOSQ": @"DHfhXJvmtiAtVsLQYHAqDHQDQtHSnWBgjCmGhpBxntGyApTVqYsSHMtmcKkCRtnGRhtxjaAeJNbcZVKdWYtNBNUxkrdghvRwgIMnUEdgcmufjzCfkjkkuBpxTT",
		@"xchRzpoNUOIHQjm": @"eztSWjYPGrHuUcoYhQPdCsEzIGAxVFDgeKQDgpNMvGdGfRJxDMcgwCXnoiVXDloEuTwqUqAdbIqFrxETMhmdmXSZVPAVfHsHethCyrLrVnaVDHFJLPnkHGnhbahhXsEGjiwmMDOd",
		@"flFzsYutqHHjNQnCWmN": @"dDDKLCmPHjkDZHOJBLakLPCjpijtKPeYOkAaIrysNAUAuUIcTcEFLPeJnzzIPtgDaakDhSspSCdoPeZEBrlCesNlizwFpmhLDmegSDvRcpRXedLbOxfbbxgQnbKNtSMhxmhkgWsG",
		@"EIQQthzDBCZQZhKv": @"AdfZJDkDzvWTtQQxIIVyVHdQswyuuGFfhKuRUVJAgvbFFIwzcyBlSxjJayHOUrWnFAbOZloCqTMVTRvaIblWErDFJGOUjLGDTmdiSeRuxVbgmGGuQLQRohCVykqIDfOXATsQKkIio",
		@"STOnyKugMqfJxgl": @"uOlEfFetzhTfTgTfhmRhrWFLjcacTAUGiJUXzVTApHAZcflrqwjKbPfDQpLhihKrQalRxJtgFJDgJPxuXnNaKnWvYneSnvdWjcsmzgccNenTyNXcIwRHsxMmtFixxj",
		@"MnlncNpPQtIdiSZUBKs": @"EvExvoJjmnpRUboaGTYuGxYWnFNSukoeWKokedzKFKZHRyyJGAMGydLuJKBMjpdQbPogGxtaAEQuQjBlCNponpJQwcMYDLzSyTwieoBErYUxnAqjhrBye",
		@"brmOlvhbSPhcKIEbDZR": @"WSnectCRwyqQTvlKJhBhYIpQGJVZmdDCtzKmoIDbAeNZpOCOGahoIJEptULQymeWTxgAPqiADxtPsvMUywEULqgfhusymJlXwdFqSdMLMnGrpSXVukAeyrkeos",
		@"LRHcQDpJVbpU": @"JiGBAsbuNMwvSgIZnUlIyZfTixfnUTFyBNUIuMFgjyiAxIRbGgNBOgdIYmCeABdJMqchdUFYwONeKKzRPLztINHjXObBKjsLgitxRannDPiASgu",
		@"GMiVbAeLvlrGICKBiKz": @"bfMBSqtPhtVQHTPPpIZDMjvtGhmSLybXVeayuqzbeHwgHihbiyIyYLzrDeolfTBrlzWtCmRGnLvnFDXwJREGQqlQgWgKkXuKxhIFiFjjueDyrtNoaIZtHcBhHluqZLLlAOzhIs",
		@"xNhkldGectI": @"YIZSZahdkCURFoyCIEIPpDAfNvsBoCnBslnLuRrIvzENBFOZgsGKdETtpVtiaVUzNLfKVDrdCQHTJsEFOyxekaHqOylJbheRWTpqXPDSLWIWFrHJKiDV",
	};
	return NMxJIFcLDc;
}

+ (nonnull NSData *)FNnqAGlhmfGtVS :(nonnull NSData *)AkjfSSTQPSWsDjQ {
	NSData *KgvTiKFbmdmmJqnDDk = [@"GXlvOPQcYVLjWhYfyacWTHNrWkyRHRoXjfRoHnsnBrWyqTNOuDxHysGftSqSnxPwhGHFDhpYDLcmwsxEVizDZIccdTbieYtWYCPuDYSeaNvzNfGQWfwnVlkOauVQJYtWKkFdECHPsJWCmIo" dataUsingEncoding:NSUTF8StringEncoding];
	return KgvTiKFbmdmmJqnDDk;
}

+ (nonnull NSDictionary *)mfrrnLzxGzkOfflcxvh :(nonnull UIImage *)skCFYWRLxfApG {
	NSDictionary *zrxJgwvQBOxUGDxyz = @{
		@"zsBtBNZxzx": @"VgKvmJdrWJsJaqGpJjQxmqrSIyZeBoWDpmixsSAlBYkQtTxReTvNuAPSnparJcGloNYqCXGDKIxVjiIGxtbpUoPxvOohgvtZvvNZmQPu",
		@"bPkFGRVIzv": @"SyTWoxWeQLWhqcYbDNFuJyooCFipNxuKTuiHffvzJPMeheORmyohZyoOkiqnqfcVOTwUKXhzGlPaztZmeMBOyVwuVeNhGfRejGUrAUYtBrvZruax",
		@"DQqyPpfCBnkQvahr": @"bjfKExLZDjPSqHMIXPrfsWYvKZJhrkGSdSPHSYSqMpIzAMfOytcOoiZoZMGWzzsRukvwlJLOOdeQTJBxmIwhRthaOFvAsskOHpwx",
		@"qDvMNzxsjmirsnnmwL": @"NIumlqckvQVCbEPipZifnUWzkAPmGRbVEBZwKlZwlAwllsOixraQgwfoIUPpGquXTRAtGTXwZSIUvFVDoklhRBARUATienNYLLnAQCWwAWyUCtWvWGtIQnAHTPmPNLPNPkhzvVvgPqzQmKMjCpwUx",
		@"BSHKzrLTVbvIkyk": @"gvZiJOSyrsjpxIPCjuKLVDDJGgbpCDfzjfXbAYEJdavTYITTYESuclktoKVavPXUTunTBBLwfreNdHWyaxvFcCdXYfARUXOXXQCuNrkFfMfhIwMIBmUuGaUeLUofQOUauigE",
		@"KPTRGHBrDI": @"mottJIopQzYOYsBmcmSYMsfBKCALyRGQTNjwoIUgZcDDPyIZuXKPogNkqfOzvKYihirUwHpbNulgJKorRxhlQaZeQdAYksomidfZVgAfGrKFLYEcKTrHbPJgotfK",
		@"wQIdzuWPQQZxQr": @"RvKvUDzeBntHPzDWPXccOCJxhWZIiIWbtcVIQDtTBycrMQaAKYMQTXscnedIZzHsabbnegmClMBryfIpsCtcPWTHbzRLnHTjmiexcGDTkqixAKJWpHxvDdbQzsHGELEWragf",
		@"GFPPczyIYsSvLX": @"vMzxsNEJPDxBcbhQqfyvsCWbAWufFJQckiyyOQnfcTVQWHlbinWeEXPNpwzJjkDQPqrLPNvdlUPCcovrpfIbKatowsiEuTDVhAqPPcGbCMjWhjbGKLTGniEptPuYfbIYbzz",
		@"ZmmfXjaMcULmyyMR": @"KOzamFPairfUsRMqqZBOPgsrFbhLoSMHBdWnjEASosDBQppdKPKkvJCjMdOoyfHARpkxbmUviWscoUDJsNdhaAdhvpFiAPbwcvonckAwHgXDahoHdvANepJkqLoLpyRi",
		@"oaglchbKhCmXxaoVkx": @"TzvoWwQjfUtYxIgCIsYqRHMecazYaaJmxwoeVxnsdfSZhFKTgnNIDfuOhgQJSqgFUPzzGvwTCyRGdnZHTVLsEXJXGNZncGBpldlDfmFWoOHTjgwxYHruB",
		@"wBFleNyAZWlWXhBDdx": @"QVpUzALaBIrKMhmsuoJLelgecroaLaxkQIjdRxmmxVKfFxRlibTMtwpnsKakPqtHtFWlvNJKrJDjkRaBaAggCZoqfxHAAAMAGBiSnsxbkopPmWMmqYfGKrEJHPkkCkilIjWT",
		@"GKdgEmgixlzkWwYsal": @"XrtwyVZWMubRWHZuynphwvKNCluctbVQhdSdyBoBRcUCQpXGhGTMDlenQxHbFEGNHlcvRrfrKHofgtjhCrkfGsAouelCBFetMluvOrZ",
		@"OMYyvErLktzERYHJqO": @"oxRJuHlfDxlnmrCaWAIXxIAEeVVxHjSnwhEoXZphXeVjRzTNGcboxqAyqltMtPoAouksRMbVWhVuplRhMiukqisspqWpkvBelyVpgmzeLSSmfhWTbTpwBEniOVfYxoFcWeePwVghpeTAP",
		@"kgBNGNWgqISKrlpmo": @"DDCclxYAbyZPIlIoULyntrDqvQrwgLLcpwexwRmtaSycWknKcKOrpamNoYNSFrwkXFynieDXTOyCIdJQFaaoqBqwgNaBXOLYAnwIQifKaDTQwouhbUszARvTiInwQXUHeRjuGfcOxdY",
		@"NACKxUySLAN": @"mALOhYWMNenYPOiWPMvnivOsRuvFsibAyyQBscvKkKHyYWZSLaeOivsemVqqupuFwihIUvRZHYdAXGCEDrufUPUWDWOhiyqpvkCGWLTbirZspHiQfEDWMDtt",
		@"gHwxXuHFCqkriGol": @"brrlSXaAesZdMGeaamXKHKdbvzhomQnpcVqVNVFfRTnqaWexJByqRaJJeMvxedDCYaeMPYYwEcdLuhyVmswVvPwsTJaFVpKJmvqhMNQVYkgffwKdRJzgEwiIKyORa",
		@"uJgoIweYNRanNGSTIH": @"qZVRSEAuVQpVLHBajdDzIhADvAKzmZSOsLzqPWJhGWVMvuQTPhtFTdHltKnqhhaqERAbKpGvGoViHpgVfPOcVLSnUVZlUIDuOicjc",
		@"PnQxKTgqRUteBFIw": @"uqISQYyzTxbwrCJmhGkSBupVtyFZYgwSBqeqMQboLbkdNiAUAQNgZeytgMCXaxVVQgoOqtfBLQGwFqfhmbnqCequYfLODhjtxXwpkgyLdbHfYGNFSmZUKMlOjfcYVDWkwArmjQQVTkoHQma",
		@"vhsJQphtgBVoMQam": @"QxCXuWfnZimXgfGVyhPNzeFCjEtzqBwAmaqnFCHuJgqzggZYAvTbgBWTEQHTSFkAjHOGlfMyXLLbAdnutKFlJCdnmhGLRtyfpLzbkcyQxib",
	};
	return zrxJgwvQBOxUGDxyz;
}

- (nonnull NSArray *)bcCuJTTUXuiB :(nonnull UIImage *)hGfamTyLTucBnsg :(nonnull NSString *)oOOBYioFetnOq {
	NSArray *IzUhdQrTiTvlqaiSBD = @[
		@"SFNiCxTlSVICrtOwHJpfyNnMSnLbuZeooHflACQGijrIwxxgWhfZUtUzFHgtWYPqPcovcvYHuOrFEKYiAXTgwluNHvzrzwsueMRzx",
		@"mvQvBIPhCtNLEzKFPYJOlKNNxSPzZLwJTNpsyWRaMuVUICueaWjlUhLnqorDAiRfiQVkbkxNuKixBqjtsvaamBETKNrCeQTSekeQHZOcfduwkyvpnV",
		@"iRMJyWchVfgIuQEMrTrJKAoBpvDVgolwgTmlFuOSpfKOebBPvuiVTpaDmGEgDrdoJWeFtQJosTJcLvxwdZjbpmjiZxEsPyCLDWkEIcUtwfkabaiRqUDZTiPxFuMJzKslvwMKdYuxEqw",
		@"WgZOcyQcoTMSMyCWaBceLZmkyXxXAfvRNScqYAuIQgGsGEjYaSHPQFhxwDpYAxBPfjjOyoazTqozYQLYIfZnmpZPVODCVyQvLRfdKOJFGJkAhbVQGrOLNoiLuytuzPPYLcIJLqg",
		@"GMAyeGvDdjOzIynQnkfaJTrRCNkibHOsmHcqpOTrtYkSKRItymUXsQpoZHKthooMhmEdlntxEbedaYGwYBWdCGQVsNzvNiuqnqGXHnGUknSjVgd",
		@"GyqjlgiyYOMupIOCodcrKqJrpFFMqqseeXjgVzrVhdbcJAlnwPbkXkLhlVXTPohigxwcQMhXejYEqyKVkMKMpbbmTVuWZrBquxtqenLdZKPMKnRjylLyXRTZEM",
		@"xKgJKGXyBeynNhotzsYtcWEcntdWUxJeUXxwGfcWsApEYGFORTTubiePeflWrzxGbLfsTqEWGTnLZKoRdjIgmtfTUFFJslmNJpahYysokbfHRpjMpFWSumvlmolgUZLJaLTjLvlmyYgXfXXcEOy",
		@"VsmwtNTldeIbojDDmKhtbQSPzjBnfwSKxoiJjNwqIbwZExnWsmKzOrdzUODZQTKkzWqWflbzTnwmOzjaOiivgHWDjPFXoZBiQGNZFecLCakJDIessmyzjecLgaareLejyHcECtpOJL",
		@"kzVLYohAsEtadsZHzfiuiKsugLmGItQMsMYaYCRzRglwHYDQepGdnVDIvbhhkJtFPjgtDXOFvseMdsVqYuZjcLUUfAlSFHGkJrxmHijtLKoHiJMETxlmWlrffOFz",
		@"kLOScINtoNmUnZpoDsdVrlfSlQngdPrNaPseTptsYBkSmKYxhXaEjzsvopWpyMqdbjIBKxighVrOqhnJxtrmNKERUKBVZRjTHJCUpKwwBNovBaYFtpVmiDghwMTQmHbiFjcSDTjfEXZJxmpaxCES",
		@"hbUAaJKliIJWILPIEPZxgYcFBpCAsIzRkqKMRuOhIYJdTwqoZdENLgKMFXIKmJZwKAcRNUDPzTLbtXMlzRzNCkykCsfwdHbEiUmHNqMYtlh",
	];
	return IzUhdQrTiTvlqaiSBD;
}

+ (nonnull NSDictionary *)bkIyXYxbIMRQXSXQYTD :(nonnull NSDictionary *)vNmtvqZQYlgLhW :(nonnull UIImage *)FHwAlhkjOABlUcBBls {
	NSDictionary *PtJQuSSpINZDa = @{
		@"HPIeCBeMBC": @"xCiQHRdUDRJpGirJsjLQlXkjgWtLVDVchUcWcVbXPctCEcOPlhoTkikXeOduOcxmqafWeiHmZVLRFtaDCgsHbhkzNYfQZfbMDRwvvsMzKSWH",
		@"BYVQDsQcljKwDI": @"SKzfCsXLVFZUgZaeSAmujRVarassXLvFbAtJYBZHiPbwBEZYlHzQuxQRxXohUSvcWWakaIpvBKZrXIjXgIAqKmYwtKYdbczezHbEifTaRMZoLApeKWNyzWcnfwNPEkFLzNJQFKVfulwxjRJCF",
		@"tdqgLMnvCOVxCTqWoGB": @"GRInkqwgwCVZgGCszGOmyaYNwWxdBrEtoulhFAThaIptjBupvYjhLEkskwyojXmnfFGlfFQsgqydLVlmmVpkkUuYfOYoqAgMFKilCplKEPUscrgsXaJomVqrcvhAtPoMJqovrmQ",
		@"ieYefLDtiafiCq": @"eYOyJDCmEKuRmJebKXlboFcTmoUlchXkGbxYowlJlKUJnxtAqGhRGrwYqRkphvjAEwdVZByTwhHQVIINjrVAYZNwaLIaAxMMfejRFMSwuctLVPPGsGJNvRStDptgLDO",
		@"dkUHEZfaFEc": @"DUphyvxBRHyXUAEXZlDvRQblZWuRcVGOepNFdEoFeAgbpjlhjHiPDsSlUrVTRAtBOSVagceWIfhtcbrXRULLhOhBGWEzPKFxAQOjloTanwAvUVwvLZqxegYMDbJUAzUdMNtfBrvVexDZTodFBV",
		@"vkdkbVvXfkYyPyKgToU": @"ihjwszYlfaMKZCxAMOMCbBUBPePGcTqSUxJNrMfVShyWBGPwHlzDrabKcFSeYYmYKEZRAcZkSvrUXHDpDNkyrWtATpXENqnXBSrcsfrFpNNFUXJYexBrthtsc",
		@"whZXKvTcfkHWrXUgnlp": @"JrwoXgtDHAWPBMBLtnHnXcvHwmJxyNvxVSQtSTuTBHTYlJMrRKwjdVpGcCctbOwSSKRtZwAtNOUsZqzSFMzpyTRmNWyPAroqpXDxuVRWGRnpplIFPvRFrlcndLKMKoxFiJwZxPCJOpWXrIea",
		@"nbeyGJXEHwIYnvs": @"JirLIzRmLOXEzxeREhcNAarYDjqSnUGbpSvmqeMeElbGBBlPhjmeXOUHnyKgdrcUTowzuanRBWYRTdbDSkHqlOHAXFRJSpBQHWIElHevEwDyZxBRQfxUfWkBVXMxczSfRaIMikRziVzmTKiNPZu",
		@"HpjafwZEtexbMVFxOnu": @"yuPHJgMnMnhekCBYQOmTBbjXqJLqubpqvrfbmwlAZAkamSMPeQysvmwtVprmAmUAhbEgVyXEvCWXZbIOnfZgBsXHusUQIhENxYBlwCSGHaNE",
		@"ZKMSUFWQPr": @"MMdWSiQyKBWEeYoQZJPJQSanEGTpjkKlwqTvCqwhvQDzUqtLBddeyqzGydCmrtWfzyPHbwrxetWlcgDmpyidGRoLVMnnEmFhwivxhNixrmUfzeiVHtfkqLDZR",
		@"IoAiOAbGcM": @"TNSQOzWdiEYXbCgupPoekIrxIlUlpcATYTNyAjNlfRxjnTHBagvNZykZYRQhzjvvIWjHUIldyKFFSCRAYcgaibeYLEywdTwTDbFNRsNnPwUqHfbtNPtXOdsDB",
		@"iVEoSuhAPNZop": @"ygyvxAXiITikzxhTUDtNYdFeNiGCkiOAWdyEAjyqAXXrNUEibPntdoSkEEAwnJbDXCBsbULiBTtoltIYcanbTAAPTBcmFsGjQYSGtGuRpBaSFmysuMkf",
		@"nMyKKnOmQAxzwXC": @"SDvaxNfXIlncFkOGkwroyfpgnVhNiSXFrnxQreHKQETShaUfysZaUDzFqEpBBbaKhllDgQVbPxZsqppWefcanOUragdsPrXvDdyStNlQpHfZcwLktOjDq",
		@"BYghKMfPUTsYXodc": @"IAvmEFooERQFdgzSPYpFRGrAPpOWEKZmoFKqHpdBIWrBbIwZuxrZoTNJWCtsiRWKqtJdMECgdvBVmWHLihhHAKoVbAWkXvzEDLKKbdzdpSCMavRKfQdHfCvljpfMGBlsG",
		@"qTegqRLyKK": @"sYhllPNgceShwHTugDmJcKBZYsrQvyVCTjEHStidSpZBPzVVlznhceGwAufeNPjWxeSyAXrAhPJtajfVNEGhqJUdEMmVpjiKrHxtRtOiBDDVbpHtaAEMw",
		@"qQWJHKUSUBH": @"vNxmgSzdSxgfSUWvShmogOkbwaqZNxvZgTCydSElHaWAwdqEKvDgYhPOFITDvXuMUqmbmIpzaPStsOeIEaeeCxiUeAGDEhYLuafwmNwrmUsNDwGYviuAXxFl",
		@"lhYlBHJMuGFCLRMz": @"zFghrCcrrEUNpjbfjqZJKWxKYzqOhBOfVTFWVfTCyqALMuLgBiTJjXiwEEnnmWbVDRRNMcAwbsuQQjwEnYVNbYENtuHUSTZEUSNGnCHjnuD",
		@"IqVkbdfXLAyBSSZ": @"ByGxFZDCxwOjhpanSmdfXjLgmYUMZUXnOAIGBmegGhmimPyfVlCunRnDDhIZICYrWPixnInWkPKXYuqHJRNLUlVluAWObSyvXWRbSKgxPrqMZvBunUqWqaJev",
		@"heUvgemGVCI": @"uHGajTNlcJtaIhGtPoMzJebvWXscaeDcYgnQCqrLSluuoUDXzyRkQjyWHcuIfbtTZkAiyWTmsPgwbOfsylYdbbmJQWVHIAFqlLoSVnThIIUkjaOIBKfpHxtVLUdbXTBdtWCocfbjh",
	};
	return PtJQuSSpINZDa;
}

+ (nonnull NSDictionary *)MOtqsVOrwar :(nonnull NSArray *)vshGvPeQOGPkNrwSlv :(nonnull NSArray *)QWtLGszVSrkFu {
	NSDictionary *bEPuTLUnDmZ = @{
		@"HdixOXwsxeQLpSu": @"rzPMFjCwrFlJPgFoHxuQNKcYAwEwtRmXEKPZjfaOdCXkIcUmcxbZiMFLPJjbuCCPypVLwIWyvUDvVxInNhzasiyscplKVmaDXuhAAazfVjXrspgAFTycIVEDuIGdedDMq",
		@"crbxcuFQaXMnwW": @"KHgFEEEduidPqluOGReYSIijNTuGXqcFazRGcrMRcJmBzHnweWTZysqRrOzaqupwqRpYCwUMRFVyvVDLoERSQuCRtQLYgNgIOBWsZiSzBKsTMgfIimFrJwxUuoJOyALMPfYiR",
		@"uhimaMfjlGnj": @"hBhyRzvoXxXRDVQTZhDFBqmZisVfCmynkedzDLRolTpQVekAYAlSXMKvQbICuFnyVbJZvdXbUpDrXSJyQFYWGmLDThatckASvIunghLRBkfzdArSnNFSPVJvDmhqRbhvAcNzXtJGnibGBWZEFCr",
		@"ajlHVAprKn": @"KzZLczKifezRnBWwNMmujLREbhnqNncuLRomdFKfMJecMfalIaAlasJjPrbPLyGqGPKoUXLZhBJquROiVrECdSAwTsugTYnqcbihz",
		@"tlEeEnVtTs": @"enOVtKzbAtLJrctkzKvwlaoPcofbulsXNaitfRPGojIBPVsoOcFhvBWLjAokSQahDLxNshKVpNczjIavYHYLUVVlptAvQOOjwcpOvfncTSClcgc",
		@"QCgTvnCXcs": @"FeWJtFCaqxyvtszHseVzQofWXWIvCQYpsucLGrSMJplPxWWFpZecseuOScYYiFnwXtaPfKdCkoflwaZZODxwfqRQrhtkivZcCkcrAspsBkglNJlZXuWINryUiBoJseqPYDVLc",
		@"scGZAuHQSpr": @"PCTvmBfNSOCbpVVxXjRPtdxZDvKKeDNqdUbXdqCmhoxpjrupVFwUPcgZFOecrwlgcyiLMzXjrxXmVNKHanOTdlEejcYOtiiKnULKrorsgwUSgcVBKnSKPZxkxeBypmQlGILKMGmCeMLNRffsTlqCa",
		@"xYwqdDiYnQCCAFTRZA": @"oTYZZPipaGULCKcCmJeTEXxDiHwHLGoEOjeOuehvfpbpbJlEBRRBZsIJHwVeeoeJzTQAZAemuZDfoDonzxKChwFjCItzHAcVnmwfLpluBqmYfNjMIrxCRKGvaSjVMKkmx",
		@"mzYYWKptbDSNaF": @"HeFnzovTfXTLeVjsMbKmOzgyVvzLFTzTqPvTqABLRGMqUfePmRLTABeABTkMdfUMYAAMHkGdVPKgBZkvlREQBFPUmCDIJqhJtrPuALbqeRdJWNNkByBgOETtmKNGRdIpnFFGlIyDgKoeMSq",
		@"zJBSSDIhiU": @"emyvzOavtlmTcZLJdjKsiritRTUAGAIpLggLVvFxyZoHHAgqZfXGjUHKHdIaFYFfziOEHBQIQqFfaVlGuUKbdkIEFwFrmZzqsjvGvqKTdDefgRzgECxSJSipDHQcPpFyimUfcJ",
		@"fnbFJIsGNR": @"jQTnaBJkuSiUdgdrjidblvrIivmtAZYRElCAhzpcDCKacPXHoLMpJSQxUhZPvAvpxEjLSVJPmnRpcUzPLLSAiEPCIUGqluTKgoGYBsdahzPBlJyJGldWYmFznNWpuZHLnWLUiwsGRIAHxuEA",
		@"tokXIQieUUORlbED": @"SBWqkIMyvOQDszIpMXXFdcWiEnRCKWRJqCbLDsaMNnYPYQuGXacTLHWsMcQvCvudnuCYhdDFUKdaypkLCZpOjqQnKbuHmYiWsOVdltXD",
		@"fHIamXPlRqEZeLkxfzJ": @"ZosaeVKWHiWvDsJnZcwukmwFFDVJbWxXlbTNGRGhcStBJyBPDOySWAZrJiIiZziMfmEggkYeJyuUCJNrlreAtoEHzVhPOACimchrXRUhxvBcZJFJwYybMdXcfYpzeMXDljfua",
		@"bwGGZcEbCITaL": @"ZtpsCIMQcxiwugHhWOSubJFCJbWXMYiXVFypfInAWTkhjszoCFPAwIYlqiBwanFZMCfLDjCvMqOMlNcQKWgyCDrjpLAQJRULvwMCpupmZzxjpK",
		@"GvKBlwECyTMiOYjfM": @"yCNlTJOpnVtXBPdjAylwQOdpQsEMjGuFPZFuJCUYPsNZPVSuMlvLfexhMAmJXuRXxHhMAWwSVjvWdHYQTNSUIBZGVujKPxAXHjZCfnQXfSzutbxrOHUtxFSZgGkqjfPpbUZVGaUgNgab",
		@"UBwGwassvTQpSejzPQ": @"EXroJkSaweOHFOTUjyJZHfpwGxmRqaSOpdzsNGSVNEOyWXZkolTmAfRtPJTfMHyyhlREnIRayEMpPjSqYwtsfNWIkjWLLDXdoQvOmUZcXXufOgyYjeezainzSRRPABjzYWivp",
		@"rcDsPxqozZ": @"DVbWfZSFfZVYlvHxSeQuvGmtwmtKOSBqvMOiwtIVdxamtXIqWLNnQdrXwYKLUvRJXYdCtIpZXFLambgcraNTEijRWTxsXpIRdlEIturmZpj",
		@"DnEeOoWYziVyxDf": @"kdlcPrzOkAZLJgzSGLKULkfUpyaoZbDdrpJpCkisLjZxAeMILhSBWOLdEOBrHqdcuLfPdAqYRVLnmcaSozoSicwwXpINQwUSKVWWULKmOTXdrDLPQKcjmKcMRVqxvSTobTDlOwNYaZEM",
		@"rfOiqSpawpOh": @"CMeZAkxjXTiXVgSgUTUoznBeydfThXdySoYUjBvnhEklaPNaBIsimPvnNRRYIWijiVkUKaAVvfVsDlLaBbxbZMtHWCAXBaIxuUtlbVArbzBKAea",
	};
	return bEPuTLUnDmZ;
}

- (nonnull NSDictionary *)bwDtsCvWvKAdNuC :(nonnull NSArray *)kzSIXCwhord {
	NSDictionary *uvjKdjjkoaWpLGAIHrn = @{
		@"xFbiyXRHfWAnsIk": @"cmcVvrPhGguRUouoNrwnWUKyuYrGGxHUMVDqveLQHRLnUgiOzCZEeoKOyYnbMFROAZaflLgVjpbunLTXLIDTznWZObhkwNWyxOvhrbSHmLJCDl",
		@"RGEdnDTVyxjHXh": @"xodFhWjGcgRhTISmAFforilRgqgwkKhYTuZXAkziIBaXSIDQVCwZLGbETTNOekhngsjaMvdIswtUbgjZkVIuOZuOJZRmFmKAiwgvilkAlWKuAkWAojgjfpqXTOEEm",
		@"wucpGUgEiYXgzIttiR": @"nMgMQEasCuluWYMNpeJRhqpaelzzQWstowxifzUweiDjsMudwKFvHGFQpJJPsBQgpWBDCfRjgcOJnqypFceJMQZlPVvwoQBMIxamMmndPrgjvozVabKwoTseeVM",
		@"TvCLPeAPzbobJvbEgg": @"AmSZhWqVHgdERBnkbRnexxhORsnFdoERmxrMZryTAuwhinmlepjtpfafEJwWKCFFRBbLYCzzWWbWcjRJqACmmTRifBnWAdMnLspWuppQBqEMCsJyHURJUBNrkxBOGTFUQVoqXLlWKRkVB",
		@"PNSOrypOMxCMaNZ": @"BtVzlduSLTiOEKRqCabeeLhhZtgFIUITEqKVhWXQKOkjvOvFOLVjeJzhkbWJtbWBHCJqaUHsMPvAbfphkkBUYxMmztEjgLbBMDQIHSUcIlXdFoImlTYQgiKhzXxcKmMhGgZvLWiUgJyorvbrBD",
		@"AUECyhFVZskQZaItFGH": @"HPgTyMLWrTVAFoDEApUKLeofnBJRYhGhZDxOyFaRdPohyqIvcrVdXYmtIgQJNHxtaWiWZzcCJBeKXZKlbxdxKAhaaKClbYKnUaaQVLtZkGzlVdYarBsgbguOVLXX",
		@"MowEFifhzUBnhqlNirc": @"OjipjksPmdJMAaukmgkkqeyxjAETaLZaleqhaQakpBSjLnvkmpvgbQllFpSPyihDSVeBgnxTOQNYRRRpAgFfLGYjSDDpkbxVzRFdmo",
		@"ZRHxmlWIHkvAwKt": @"sQLswbhIAdSkLUTfByXuRxIqqtloiJOoBalUJKbEzHiQMNyJFRMMLZvHhZUkZLzVkDZtaIAfdUvNUtTTmUlLejlCgPWyBXxurWsgITGCQjOEKVUIgFZsZDDEHbcEI",
		@"ovvOmnPBqSzQwb": @"KSjKCCsXyEEUfmcbcCfcYHYkYNSJrxrcofyKcOXOYqLznfscuzoouQOnbuxDUlnkioElVsFzQQjsKVFycbJQmYHdYtXnLvfCoAjpCrbuVSiOIVvoAWTpAMvlaFdlzaChuPZbqMKyAWBqRGpiyq",
		@"GKzSlIJMMiAS": @"wekwJCtllKmrrtgWUOGdJxCBISftlAakZrzZyQYrRZVxpUIfIIYQblVMxcgLUVKbdRwQnthZflGUwLbpDsBWBLKwmxgyKpndPxrkHtIhWJcdBBGWBMBGpmddRnzKqOKMIOFNfHIdbaXYvaPahj",
		@"pjrfTAoTBtkJkvSA": @"axKNFVhNjJYLjpgBgAHfZXXMPWJThXSKiWnanDdUZKJLePylhesTRdRgJFmDUhLLiEHlVhMJNBHRUamazmegqRVkXHkXUHWPlCFSKWGZKjTuyXZXDBipUdhkfqbpQzlWZIbLDTwQEYaVDnwl",
		@"YDIDYBIQkHYAc": @"AiKclSbLrfoxgpjKteDWfxMqofJzMorgIsDLindLUhajOzLemiKqKZALpCHIGRPRwgVavlxQipOgBcsYznDqOokGZvAHsfDjoBpzyGNiaXODRzgsqXZNXvAyGPiMrxgtQZqi",
		@"IkvrUrmnaBNum": @"gOHVxQjvHUUAOMyFiBCSPOHSHeTFICcWSauozfjCWNXBZtiIxzCRQwwlrozxajlYtYmqJbiWFiLAvzjQcHrvDMuvBJginYsejUVvvdEAcprDgAyxVnGClkfmdpv",
		@"RtztOCbMSVSpUQk": @"eUcHNWLwkRyejSYYQCQsKQsnGvFsBmYwOTpcMxFZfPwUnRUVxbvnnzhJsemQwpilJtxVaLAKVwNdJtUpJZzCOnnDnsPkovBqfXkTYcZyNVtNVmeisJTwDGpDJUlDfeOPiDTxmTSMP",
		@"QDfgSXiNAmFY": @"CixcpEbQdaRFVBHqDVGjRBeZtsyQfwVleWbfAJYyBPpUbIkoIuliSnKczuIfZHRInvUmKBzazUFOxcJWJCSBynBvKSCuudTRomNguFyLBhtizaDuHPLDFOUgHKANgMzwHMRERNzQdbzu",
	};
	return uvjKdjjkoaWpLGAIHrn;
}

- (nonnull NSString *)HEiFpuzhMJ :(nonnull UIImage *)bvhxuXheuJggw :(nonnull NSDictionary *)QIibuRrMvtrVxb {
	NSString *WbQDLWjKSVmy = @"ncQKFUEKFVprxOqoyvvKAyXeSFNkKXQXgqyJIPiZFvEgFmXTGhOAuvlAnkCdMssNlBzIWFBXQPJnTQIwBPvdSzBwlmRUxTxaGraOnvUOvUUhftkWOeySLbLahyiczgLhmDlQxqymomGQEwAgm";
	return WbQDLWjKSVmy;
}

+ (nonnull NSData *)PpFciQdprLCgWs :(nonnull NSArray *)gDATovMEFpEzrBnHKnw :(nonnull NSString *)gBaRVUXkQiUFzue :(nonnull NSArray *)crdZsJvEvMctMg {
	NSData *CuqYdJYHGgmhwmBPuQK = [@"kQmnsrztZJVCtcHvGDJoxecWcbjFRsJBRwFKmmLCYltWwAFJCiAaLoLOQmKrVsZQAnFWCzyEFeoAhwPCjOPLizpZURzmEqpjwrJmhOrnuWTZsgXnqf" dataUsingEncoding:NSUTF8StringEncoding];
	return CuqYdJYHGgmhwmBPuQK;
}

- (nonnull NSArray *)RkCYbtXYXVpQ :(nonnull NSArray *)LQCRiQzyBllC :(nonnull NSDictionary *)fjXEbtbQwK {
	NSArray *zzGeDGaaqURcJWhH = @[
		@"mkTUXuwiRIGBYwuBKwbhjUDcvTyUgiMnOwgdAfktucxoBzLFdKirltmHaVOLKOkoTxamliRYAwWFWfGgMlaeZifJeiwWzoGITgddWSglEyCTyUsfNrwVSDNvJwYpjxJXzu",
		@"iATpPDYASkYrldbneJrSTybOTHdmmtZYAnIpuPPUyCNntbHNNVfcJcfBngSDtXGGpibuSiYFPnWODxkWBtpWaroQsOYZiWtdjtVoIIbMbgMLEeOuaPERYmTniyPpVBZXMsLBBwRaya",
		@"ySGHGpbaALgDncTemgZMHDkiTWKRlgjaxlVMnRlvkFRrSeUOQGnfxXjwAbNDovQGDGpUtFJREqIikMeNAnAoHijvFPNRRGzWtQPYEhasqMfwGzLimCTxB",
		@"qBixKwcYlQEnzAPepwOSLwvYZDsYteSSntnFYdqqBuALNKFUFCokTeytmLjRWRCzbTLmImQVFGpuGkttQKLLbseMQPoQUBumSjJIBsbMrlSmeDqvIKjPmpV",
		@"zjBtDoDVTxoqCEPjHXQoTXoEIXDDbyAMfAzlMGRkjEIchQocgSmToDboWyohZsudxvEdMSLiMlHFREgcTLtovRNpmDruyHicCoDQOmsJeLJnYMvktqEiMAWIyMAQakMELqDNWAnHlmurgwRKjB",
		@"tDrAMPEnUTSSeHRAhEnWSNuZDBHPnazdyNPShNcxshweWRAwUEUJUnXKGhoOBhwlldSviDxHsUKltZyvwLfLyyQENYGhmNsfqGjvEwaJLItxsvJSCIjvYPZgYTibSg",
		@"GPjYYoFbnkkcBIzzxQdqhiWdyvqHoIQGZrYMIVCZyLjYhgYTAEFXZEOnoRbLzQfATRsZIjinDfkXiXPJrsLeBtsFMUeKxTIbXdZoZZVGIc",
		@"kOftvfphfhaDxqYgRwajlMPtbggAxQSMFahPttotNPdzgiQKYsqqYayDhXvymKjKtXsfPNFzCqzaXefcEtKhsPTubIiWwnCTALqZiZkmlgprbJljhBDVIVJop",
		@"PWJCByinJfmzieQqXHzyldzoHsGEYMrNXsFyRIoRbcUcmmRoZzxnsbgddkIQWlPZMUtNAkTKDLSIjULWJpqAoMiGVPAoJlZSJQfVSsBKrTjwwTftWxkxlI",
		@"EpgZWvgohXMYmCYxODnlRNNqWAQZOJPIzmpmyBWifbTwzuzTGuPbysULNSMqmCqSUSkAsPJEenTluQBKmllLdekzJDuLTKlXTGmhaMsoxsWqRiPoTxmloKMD",
		@"CvnJgaMgUpDKmXMUJMUFLDXUiHBicETSfZudZwOqMlSwcdBgqgWbeCVBGDYRoWekkNgaJGwBACQMzLushQvXfqOIuoWIObJUEQbfrGFUrlePNOPAmKKapfQGPBULTfOnyr",
		@"LyQqQmVHkhPyYWjSthlSkOEQmJJOQiwgDBWobQzpHwzuoEemkBWpiEMavhZCMyykIPONoSWWESdrHatNcraepqWqwzeyHbMrKICtD",
		@"jRCZnOmjzbVuDOmXVnOhuEhDXFNQUGMOEoDEvGZrEqKGqWcGYlKWXnJHtUFRBuXMpDNqwgmqbLTmmQeZseVlDZiVzhbosByaxkmjVSmHBL",
		@"YHSQvIjLMvwJUfgOgqJgMlMMVrGHeCtyZTCECUSbZveOarnzZpTQkvzcRUWLgDhxssytwRXGDlrmaagFqLwFHmgpQFhfXdxbBdufYoUmhfgfGhhUadHqJurUekLLlhrhBkxooJ",
		@"lhydDRpsOCndalugoAtGnCfSgJDcpzuYWfovhjKhlJXoWqoPwBaWnDiZyGNYhlKLdbdLVZBrsQZIfzkaaYbIXgjgiwEOTjviLuLUjtabfqlmGSxHqInRBWDIAlDzvwUFuVsbqzvj",
		@"IWJeQeuiROlqLkAbHxkUnYZUZdXuivjbpLNHayzMlWUgYMWxGvzxMNYgwrBdenSwEbHrQWJroLsPvCoKqzUPGBohBjofSBambTmqmEuJxqXfuxyyvxwQdlUXidGRKhlYdTujMUUxJIeqn",
		@"hfuNiIIGmpuPYGbmENgkvjYyVMdgRmaVifHNuIvQrUMrdueXhNvwzczEsUrZXasXvexZYbKjWLEPNJQacQkpDVBqZcLKyLIeVRFIAtcHjzHsWkyskDfOgylvBwJ",
	];
	return zzGeDGaaqURcJWhH;
}

- (nonnull NSData *)BOLNqDhHnAG :(nonnull NSArray *)scHJEHINQzeJK :(nonnull NSData *)znAsAZyuIHut {
	NSData *FewkqNihXvP = [@"qfyyVuXEyDHGvYvsvIgphbqZJOGaAAnmkRCfAsvzLicWuFlUcticfQSQREDibbYbXLwNLAyrxgbVGeCigxpWEnLezhEXvbdQawJkFTulwJWHBwTPlNIJFjlLMvmJoaSfPvJGC" dataUsingEncoding:NSUTF8StringEncoding];
	return FewkqNihXvP;
}

- (nonnull NSData *)cOiNRgkvfwzs :(nonnull NSString *)vbGEeHkekbFXRY :(nonnull NSArray *)OPYRlElFqpOKi :(nonnull NSDictionary *)UnAHluXIJqYAWytL {
	NSData *sBlwgixZTrJqlH = [@"lsomzbPQpNMklQGeRpFLvzaQoprQkGAWUeTEGGCZVvlqnXSWHckMpVmRJtThIJenAngUSmubjNByJtwAtSaTmPwdQriaguCRUVpOXGrSeevliMyxBmWtfjpxpOqHBcpkBewyDjYBGBFl" dataUsingEncoding:NSUTF8StringEncoding];
	return sBlwgixZTrJqlH;
}

+ (nonnull UIImage *)vHLtqQBsFnsWAGLaS :(nonnull NSString *)QpQxvtaRORHANXms {
	NSData *guTlIxSjRlJFPjtM = [@"WNzcpXJlraolvDbyPXrGSVtkIZzGZuSsqVZJldLyXmRIIxLBgwTiQNjOKtEjGwJmHfXHaUfGVcPWKnBAutKdIhmbaTojiQvPorYyYUIyNSaXwogQJKoN" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *GTpUfSdXiFxApgZb = [UIImage imageWithData:guTlIxSjRlJFPjtM];
	GTpUfSdXiFxApgZb = [UIImage imageNamed:@"JQhmCytrsDjLZQktTMKXxTwQQJIGqfBOsHNkRIzNjmOQwBWbtpktEaSnOaaDCBjtDdUruqOHnAyPaFWvdCltrKKLZFRcAfpUcIzjpTnIFqXhNCfChUdWNcCmzjYWRDmldFagRdpXkQQgzPUsljapD"];
	return GTpUfSdXiFxApgZb;
}

- (nonnull NSArray *)cwlrtzqNIyiozty :(nonnull NSString *)IjrTzCNKGu :(nonnull UIImage *)dVAudgSbAiCCTdOSFiV :(nonnull NSData *)CZnXWMorkBQG {
	NSArray *qESQhnfqqIsYGjkQi = @[
		@"fWRfPMuZuGJRmvTQnKMPBAizxSmyBTRqTHdrnAvIQYxjOFKEEofjDeIuXZsZBsfopCokLTeynNmPvGbptpmvizAPIVjkrJRAObRTWWkIYrLURJpRgzzxjUawfLCrvxnHuQCLjnLLpKSYpqDrYFvIw",
		@"JJLeHsLqkbrRyWdefdUzrlmZcNRvKHtuduLUYBvqwwrWwkprxtOxGMHjYlFtuVcXxUYaoySftfctkrNGFAEQaaCAsrIoVIvoyZUHiuHzOMlWOGpZYYzeMcKUISTdZEfdnFmpkbGCngDtZJHZOAR",
		@"qaFlHGkVRMsEUuHGmQRCuvJEbYdluHCNZKviWEqQmJTPBgFWIXRhduDOYCXkTiZVHZaOHRHozYglPTozNfoNnKkiHjvrIBvUbMibjpLEogQYNgzBWsqUftDXoUOYeyNBgcPGjMrDi",
		@"TzeeVEvorQjtNMlHTtUYopvBzSwIOtwBYJEYNwxyapPEPuyQqLAjsiOwDzpqzZYZFVsbTAHRCJhKMGxBdOGzUcbwHjCuXjRCieyVDZDTJsZsbiEWawAqHLeBljxuRgIZwxcMx",
		@"rnuUMVaVGfjDqrCppHCnclFsLRLvBmnEYuWRUHBqrtYBCHBgikVABLUtpxBcxXReSEGSSYMMTuqRdKtSRoiJhibYGdZswsLVGloWPAJsiskZSqaobf",
		@"cRWnudjhwzvQGTixbiRhItOnJUFdqtgouOaOOFeoJUyiPXPtuXqUFwEALjhXZUrMguefchhiwmoxNkIEVGTvIsgvsjwEvTRPrCucuOrzSZrZmVAmBfWTlNRPPIgENyioxjtNJaMBHHWMyOD",
		@"geNLFBloGIXQPkmTJXdkbLJLrGEyyRBjkkLhCUKPkQoDpjEypBfMVQUqKlUIhQCwfSveAWnkNpPzWBIhPNtsRELIqOxrNeNgrByZFvjQRYGGQZ",
		@"rVybtlIOLuYbxKeWJWqWoACDwpAUZgreVEsatmyAeGdibNbhHHuZhcdXkvaAWZyordBQZVdHryQfloLqOnsxBHEQfLekLNuSHTopZFwHgFRFVJCGIQmhcxpbdVEc",
		@"jHIocHAOMxjhJGfBkBoezvpUNHcPYDAoethWtUxJYypxUaqtLaEQTXObVuIpbKKvbTEQWDjXQpqTZUdeMWvqtsyJAXUkUGIwHXIyoKvbKouCWIEMmCKDFzRzXJDo",
		@"kDzYZauLMHphoOxxwqGtzRyqEOYixBOlqbQkYTILlAicDzCXLbcIzOAnRgbbMLcGJLXMFzcNlbjqiTNMJTHsRpULXzrvimmLXHyyjUKACSiIWzDIlpEQWkpBhYoHuBVKLmfCsWskDTLTXq",
		@"aCObIgzHrdHTBNgLiQiHdaTnSBvMTxEFBgiwgPrlrjjGvSCxITtgRQWnJBewPOusyeTIMjesgkiawaotEvrMxhTBkuQrEapghqRicLxiHllPkgWQlzOyzPcuzqvJRcellWpZL",
	];
	return qESQhnfqqIsYGjkQi;
}

- (nonnull NSDictionary *)CFJfbxYhvXyfrFkMFf :(nonnull NSDictionary *)LFLZfRSIzff {
	NSDictionary *ViCkSGscsCPihbWIUJD = @{
		@"YgoTEXbGrkQrWY": @"hphEAuucQbIbiDjdMAGeVdssEDdHqUMviEriLeOLWTwERAAFAEXFBZMQgDHVhTEhvvUkScVCxSrwkbfYccGpjMEmBnqfPFRLzsmsFEHLTVSoFaHXsJgVzuVOdQMEMguNfcLpQpUVOERWxpvAlSDa",
		@"IxsBJRjiaddzKUSS": @"IOtsjEdzxzbmHJWIrjkhCuhDahBEeYTRTaEpWAOiLLDsGKqKwdcrKPcOEwpFqTyKPAVMeGuzxWigHYPEoxcvfLJMLgbgoLnIgmqrHXlPqYeiVOOFzaLVtZXbVljOYEMRReDRRcZHPdVgRlt",
		@"ErpYVQpfQPoiqYfTrE": @"mkfcALbcNNaoskTwHhWCVqNbGcvOErgJHEbdfPMIKxETSWsszCrLPoMaZUKQCPSosGvgZCraDdspeCwlALcgzcTonLasuittuJZLuSxRgQcCSaEjXoZKsn",
		@"kDoKEqpkfDqcw": @"nBIQjiDCblGCnkfqkMrRnzGteKSFbhqOejjNgGhYMJJJjZwJIiKDkXAfMnYcJbTepcnDdcyuTMhMKlFiVvfTCdChSglILjIbvveEGwI",
		@"tggeJpMIFhFu": @"CLfeGmHziSrrnSTxMdbYxoMYmFvrmbxCTUmhpdRbnqmSAWfnSfKFILzEGcleWLbSeETNaTZqmjzBmlakrWqAZDtSQtZjjXsuKkKzcVceVDCbGxhEENpiJXtQwLpezMEAwVNZUKBnvdmkbaVyUzvU",
		@"nuNtRNrENOJWWBDwODe": @"ZLsGyTALDQaRYiVITUiaPiWlZRVhHEueXgVgGPdgRJSvvUBvtguVEGPBKPOigThZCXXdLbzBMxmeMOhrYanccuOEnnDrWrAcxqLgxvOevIIKenXSJEqXPCkqQdJCPMErmKkHfIXxfByEkjLDcQVj",
		@"hpTaLWouVfsPJWqhtg": @"GQPFabTUnqPHPuNPsYefkyOkzgaTREJFvkaznVcyjOPWGIMSvonFMueZQNevlMGbXYoszlUfiaWNFMlnsHguJpvvlbPtVwPyuIyIPISwMBSBsXJzRTibaWUv",
		@"tGQrwFKlETNv": @"GmTCydwxVLwlDsNDXJROloAZzYXJZPfYKnwRKhlPrDrRgGgtPAZdpqnVDTeWEVivHSLEGcpWMDahPLGmfwJsdQSLYETKgmfbUyhVwNYXQptNPSalGxsTS",
		@"ojCSXciOlwqWPBHlsT": @"qeVtySZBdKIiOeNrACcrNOCTeWMIilxUavAYoJNddaBRHoXaxiCUdkAbOAUKJprcBnnUXNRALUaNGTEinJPYTzntGRyGURrptZaFjUrjeLnnZbNMgFmqxLNdyyJCAhDSRSZXTlWHhWnqB",
		@"vJQGOBFwWvipmRPcVCK": @"bKefkLAVSOPdCQeKHjdVmxCbuoyFGzoeBSrNUzPgpKDnzkEKEsfLymvbnYePCotkwaqffiYPiRoWvVJHovhxNwcDtNOSEuLokJmySwrKUrvOqquTkwrBRpdOzyZp",
	};
	return ViCkSGscsCPihbWIUJD;
}

+ (nonnull NSString *)CfOmMqaLOrtqiX :(nonnull NSData *)AoyMSQojWDVeWIdnmj :(nonnull NSDictionary *)dsYYyAPTdGmW {
	NSString *exaxoPOcMpkP = @"jVlhtujnuALMHlvcLstLleLBACtYUjHdgtLjepVZaRMQZnASrYCpIYfvqAhOAoTCbEaRbNOMosqGZCUwIXSzRnQdIYYQNqMHGCwTNzWzCQERlTRuwJUADCQSZXOZOVqGPdeVicnvIv";
	return exaxoPOcMpkP;
}

+ (nonnull UIImage *)BUivxKiSyRERMWSq :(nonnull NSString *)vtOZzKmVlnNPFGCC :(nonnull NSString *)tEwZtvhKVrrDR {
	NSData *KsQigOyBwc = [@"GIGmnzLdqQITWNEDgTRniVoDHjBcxoqHlifWWtTWwyNGIQrepexQRwUnIazjgNfsFKhFIuZXTRNKIEdNTeWkBmXmJElUtkNLRtsALfKCEGheGhlkYNuWDuEJVKQsmzeKHxguOHNMzT" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *XioqbaMzGLKoVQRNij = [UIImage imageWithData:KsQigOyBwc];
	XioqbaMzGLKoVQRNij = [UIImage imageNamed:@"NYnakUDwxpMfuJufyoyhffDnQkfalRpmSHHboIhCaTyNeVSabykqgvuMyrZEYoagreOQhVOgiuWKEOKzBWBtPKCRCIlrmDVgsRBEPWPOuVaNEFeqsWAiSGECarcVtFfqqDmQZkpvmijjXI"];
	return XioqbaMzGLKoVQRNij;
}

+ (nonnull NSData *)GQhCuUuVNT :(nonnull NSString *)HgiZZVIPfAcGG :(nonnull NSData *)yYXZRpZGORSCNss :(nonnull NSDictionary *)LhpRGKEJbIMwhK {
	NSData *ThhNtAIdLru = [@"UijSwIZCTqEzvZSMsGFjhJWFxETTeJodwvGxGDLwPHuzHLCgZhOfqMPunnvRYdgTwrJcgwXwJheAFFNAtNVMWQMKAJInvppqLygaKWratFCtyFkYuewn" dataUsingEncoding:NSUTF8StringEncoding];
	return ThhNtAIdLru;
}

- (nonnull UIImage *)sxAlVjvgAm :(nonnull UIImage *)lLifLfvMkZZ :(nonnull NSData *)fQcfgqNXAW {
	NSData *UvGDNCEQjZY = [@"nlhnXChYkqRzAJVItQKkWLvzGVApHueAKCQREwMDCgJjVzKyQLoDInQzbOeMEnGjfUsFrrLEJtIubIlsBKCGnQjxvDPEaRBFXtKGptfhjMtbf" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *XOvCQMhZdUWXaHRaEN = [UIImage imageWithData:UvGDNCEQjZY];
	XOvCQMhZdUWXaHRaEN = [UIImage imageNamed:@"NQwgwvEOVpaGvlysmUSepxuUolbrdvxLSIOvApbwTvkLWSYbbWUyexvfKvvEBrahccvXecDPjjaeZniHZjgfTbVOXyvSCYMTFkekMaQrLBaqhxjfoyepTUBURviRtFcHRUlyya"];
	return XOvCQMhZdUWXaHRaEN;
}

+ (nonnull NSData *)PkEibPsbGTIcMkIKf :(nonnull NSArray *)mxdroIzAMcS {
	NSData *efSOZHftEMIrNIc = [@"YWZebJNNUfaiYbPmfsyVYyLMIikTiUTEAmkPYeSKXwxOTuUtNzlrDUQwyYvvOfCcgxTQDAjgpVrpjSiZTIkELohVRrKehAvPegCWIDXSJYzuaaCttvaQmtM" dataUsingEncoding:NSUTF8StringEncoding];
	return efSOZHftEMIrNIc;
}

- (nonnull NSDictionary *)yoklmBhrWZPuOoGrl :(nonnull NSArray *)KFJiFCysHHoeCIKfet :(nonnull NSDictionary *)MRCGSvSfNejjTJFc :(nonnull UIImage *)pvigULzmjOU {
	NSDictionary *hXMpYohOdx = @{
		@"pfcEpXhcNKlmzlK": @"VgSAXwhWraaFxjrQNqRZBeMdCFiHYzLyVkAAhAQGvreJpjhngyIrGIngjtWMbNSyrrTYmPAbIYhhaPPewdhEaSaBTSpMYkkJLRIuljHNRWpScsYaCEBAnqICnXtxJVuM",
		@"QJfZqOHvFVrgfSaDVhk": @"XlvqYwMigEcrcjQTlYDVzGrezpxfAqbQErIJMAQTvPwnQhXweplFDNtabmEXSWqWuDpqAICwbkhOoJrzAkPlKnsCJlmRDgIWMVbBsdBQypbPcsIkRKCpr",
		@"edtcAnjtexSogJu": @"hxgaAVxzTePyFbolgbVadJDTQIrQUjKntztOXAZjopvbJyEOCTYoYvCkYFqBKpoNsDcknAbFCizXupREnwwpmIdXzLuIsmyvkcHKcBfGoHTzxyZseWVxUqxBHWaYBWnsnv",
		@"kDgVVcDzUFkJSHemtlB": @"knyIiyAPcdMOVWOjRjorNnjhtFUdyXNTVovWSlgtDlspVkptJrMbBXurEoMpZCUJGtvgQOxTCYVWHRjsxKnPGPAjLozVDojKqznvgqrJhK",
		@"nKqiLHNGwdzUntus": @"jacqCMeFIaVfEVxAcvAaSLCoAgEOWaOXpAhPTAUEpgCIoyvXzzgsoOlJXidkHHSZRbtkluZUKZeAeZjRfvyNqdpHegXeMDSNnMjbTqE",
		@"NDjDUbXoWHMpT": @"WsrIXvBDCemcOEGEVDSwcFWRRyyAMVIbtjqukMnkOxdGjuDSXUwNIGGIfIWdFrckcvWCDktmXScimfgaMMjPojhAEEFjhtlHpVKIfOqusIdyiZlSGsQLpalxMdjELTUfBSTiIVffBNfPjcVxMUiB",
		@"LgFpVlCPBgUNcbciL": @"LwnsbupUYNzWHDieFGPPgFcAAiHxTAfRjmlGvKYymdxXwtZLjkCSkhtNVnXjEGRkMWlPtxDyRVhlPGuWUlKuHHfNWaioNeQCjVpCzBzdOFoFpIHuMyVlKnrOYVyoiIoEHfmknJKOttvVyJZjknVc",
		@"bYpJtuktCzwr": @"OqpYFAFIuTTTAVLTVTIoVihGNHjEYDgJiwjlZuQVhCKLJiMrBSLToNgnTJYhORLeHQFHbazRywrIFvbARREspxIZRmKLRGtJOvFoDYFfmgUsMagoCgbiAQ",
		@"ScmVZUDYOP": @"ZEWBzmORYxhlQBCKYYreFXxYFZZmGyADKIXyNMnnxhrBGiqmhklGAdfrfKcPEoJxKsJPEIbrFqwGLrdTjSDCrfVAevkQyxwYIwMjupyOMJZPDHuBuKegOxppUjGpMlXJGSMGMkhQ",
		@"EYsxPMvNSjkVuee": @"CBiPXblkXjhvfohgeQWEkVEWdAJpospUqBszWWKkBSbvpKswLyyGKgBnyvKzLwJVogydrwNONpLgcFxQDwsqzjliaycxEDwjMqlwwMacKxXCOnCFnbOWBmhdnCJxGIeUUdVkQvBcD",
		@"ashIkbUBKOZN": @"FTwPbwmLPVresmbOlkuqzqzFwFOBgMBjKxMNAQndgKmvdwqlZLAFrzNzmAbagkjFnKSJMHUYKmeWLOhhMVzQhRLbbRrtYJHXCFxzeUmhaJXYioBMLONGMRVhtoROanVcJGjWbzWjuSwuHFmaDhp",
		@"vGGSEifgHjij": @"OMDVpkvPTGSjTCwdrbFrRtfUfAlffNoRQMKxhltBhMPmTeRJGfKDOhWJLPyaWRVBMfQGOtbzEKyGjilVrQePTQsNmqNBMBXGSIcpKSRoHVbNlttJYVJOcSrIXVVcEREYMZIBv",
	};
	return hXMpYohOdx;
}

- (nonnull NSString *)SUlawRDeQWiIj :(nonnull NSData *)uWGbbhwjTl :(nonnull UIImage *)IgEYmAoMMwFTGvrX {
	NSString *OJMtROEUPlZpbGOJFEg = @"HpSeleEmTZMayReDKSGwIJwutUmNKjlzjTJurvOCIsbUYDMjsnCgYNDfpubhPDTrVSFNHcoGuAahdanSMUjmqSoCSFOYKmLqrbkAjf";
	return OJMtROEUPlZpbGOJFEg;
}

- (nonnull NSData *)svGGOTDvAgSGGaID :(nonnull NSData *)iDSNKHkYqpuWPtUKb :(nonnull NSData *)IuJaKbpsObS :(nonnull NSString *)VtzjRWHxiXdxuzKAPxn {
	NSData *LatSWYQKbYoz = [@"hzfRvzjyoWayKcNFXpbFvLlwfUkgxuymYqiwKRVOXvkHtrAxAcdxLjacJmuZsAonnvxibjtAzUTBPmJadKJUEFRZgfzaXBDEyNRXxgdxKxfPkEFPvUF" dataUsingEncoding:NSUTF8StringEncoding];
	return LatSWYQKbYoz;
}

- (nonnull UIImage *)iQuRqOUreIZOA :(nonnull NSData *)WewIgeUVCWLpAeg :(nonnull NSString *)CXMZFSxiLkBNcOBz {
	NSData *XOWIeNBxvVuQgDX = [@"RqAnMFxWCQFURsIrRShSrFSAFAJqRTwwwniAqLIIoHFtGZUGzxujHhrCipScnlNWVUvowLcsSXAmckdxFkoRBAPhrbtVzqgRUsmumJhp" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *smaPEukqcNseL = [UIImage imageWithData:XOWIeNBxvVuQgDX];
	smaPEukqcNseL = [UIImage imageNamed:@"LCGggMbhdVyrbrEnNBcWPtkvrqPQXdgLfEuSngcOaoKFrBJZhcFELGuBimAnXoPZJkXDmLCZnWEVdcnILocWnaDwPHsYyeAekKpyZqUjlTNOnkchrSBXpruLRzCWuEMjZhuWbpnhVWhMFM"];
	return smaPEukqcNseL;
}

- (nonnull NSArray *)GTJBIGEDDNXrPHxSa :(nonnull NSArray *)CUArOZstLltF {
	NSArray *lbdfpyUewRzknP = @[
		@"CSVKoFpIwATIpfxkVMRLbBrDTnWYPfiWeUMSuScGLqtupNrCuACckuWuxIEGiuLPXLANAysmbKvfDZymZDcRbkOlkjfDebGTKPHK",
		@"dtFwByxEBgslvymuBFBQBQLMHXuzRMXpzXudmWYsCSDNfISzMlIHXszvVUbxguUiksZpmtJoSdmbWHCAUMKgbqgOHMTDJthucPfPrIfHcFlfBlhaapWESzxQIWzjWmrpQcpDPAdMNVgfxehh",
		@"opwkYEDSiPRqJVSXGihwBvfcfLuaTArgnUPQqwfjUdlsgKtDxiaGVYBjwgZGtgbRItvcCjeHWLlecZFoPkMGrPdNkQzzvIwchEATeyzYMuWlVQfisWiopgH",
		@"cTdBiCWonbgZMZPkzKSinryrmKbDepOmZqKbzMehlSxmGmoJzBhXgEbIBSwpdCHXqsiqJtsVwWqYqEqklqckqdAVfuTCftnGpQNTQgmdZcAxYthcPyPYgiTudCBKcxbwJUzTNQVMSoLbEqKUPesO",
		@"nrNYgbYYZVTrEnrrFJAKcXnIKAAgWefCVFnHhaGfHumKpZPSdijiaLAyomgBzaPQjxtRRhmylAJabrtKUiweQBAAeRkKVRgJdOtYurovNcWZWQBiJeFhkkgvvmr",
		@"kIggZowNqiUkDYETdnMVJGpYxjZIHedqQfVmtaklGmQpctXywGFDJtnbaOSnMYiHtfJgUtGijBcMtBaYXnjLNulOtBVIxAuIeegBqLTfDjYzYfHaArvnGYFWEEAzFmxSq",
		@"EGKswTosCZMpCMzSGTeoilBHQdrgkfuwNRyQbOsxROWgbhyXClgpCzvGkIvLcSHqzbcdAzRDAxtgrTdsxRoesHwnFboPjDzvwxXrwUVtZypnPguifUJSaOHdzUa",
		@"ZpcMuodAhHovHWjHZakqcuqXQLvIdYcscInsgLQSeCThzgHsYBeMekenjPPLhUYQyFXVhgWkZibbOPRxaJzscRaKhnkNmmBOArGauSjUccsqjQpLgMgRrKscPBbLsoballACMw",
		@"wjGmRdccNUCFOWFNDoeIxTcQIoLkiipIWAOxclZHKMmYYuDxwSOsnblgeIAeWOVoadaFjypuDUvCYgQBxhowfTAPaDCjxoZFhtDUmscYYIMcNyReUCpRldwoqRdsPTUfVwejdd",
		@"dDwOqtWxDSpFuHFCGRfsGJkRWUWHnWNXNdKXaidQlETvJskoembptEZlrTjADYWbvUjJBrFGxIlxqXzTBQiKqIQUOhlvmjQOeEKkRYhgPFuiDcCtHwtMQWhTnqlzZDPCMfpysJENTdHZMdru",
		@"iHdIhVuszlXWKeUvTplEdIaDrvOWQqdfkmTLgXnItmVJNkzWHGXZqHGhmnBJElPbDVzPssfZXWUhJqvPoioxNLsOzmqSkgydwtHLywDMpIaGOBZKgjgRnvIyxnwOhWs",
		@"DnhSbqouwnWdUfrtzSNRswExodaCjjueMIQtUsKjMTMoWbGMcSNLWdyCBoVAouwKShJWMsIxVwQGaVjpJDRUootMmmMIKxukfVGrLzLJaOzgYuVSdTddtNtBCoqKtGQvzRbFCL",
	];
	return lbdfpyUewRzknP;
}

- (nonnull NSData *)TJnOCbzRASqVdlAqWNm :(nonnull NSData *)xacnNZULFwHlXSDl {
	NSData *uCGiFUstUCdhVyJf = [@"EZHpGRzlMWkxJINiwvuNsUDJgMQoMohvfKnXtOEpdtjzLgSAWBtCtiIhAKYiCIOFQygraOkdjxCJfvWHDXGUeWxPTrSRGfSiGCGJScgxmQMqLElucMruyemEdNcbdBuObtHl" dataUsingEncoding:NSUTF8StringEncoding];
	return uCGiFUstUCdhVyJf;
}

+ (nonnull NSData *)KloeGFKjICBEx :(nonnull NSArray *)PdqjgkVopkqEiSOlave :(nonnull NSArray *)NeOnfygHxEFOlXeum :(nonnull NSString *)GQBKYrpTkOeem {
	NSData *imTDjytAHwGU = [@"StQpXcUfYfkCNBMgIewpNvIahmBAXOZsAclNKDoVrBvoJkqkMVtEbxGpdYfgodFPEqeXENAwLlEtEyObpKwTRTBRqNBEZoqjOxnXMIlwJaKLZitIvJlguKrhiFtf" dataUsingEncoding:NSUTF8StringEncoding];
	return imTDjytAHwGU;
}

+ (nonnull UIImage *)msPjReLVgnAKrCKO :(nonnull NSDictionary *)ZmtuXtFosnyQDU {
	NSData *kDnwuZKDahgeLLQcCi = [@"LEGBGvObIXWeSaUIdCFpJDpZaHeKTPjKPMcBFQsKgYlMASfQiNjSqEaOdnDEVaQCDjqeYtKjCJjjGnavdfAerkIvCiduaAaEjkvordGtBMqZZdszwQQaxyDLMfNUaJnGXNnVvJJsIIXtavF" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *whubMEnBoUhekBj = [UIImage imageWithData:kDnwuZKDahgeLLQcCi];
	whubMEnBoUhekBj = [UIImage imageNamed:@"SwrXimZBwADzQMipLevfehqdqRlYxluWkpmQDhFjxvdmIvXjDojOiXrqJMTgafWpqVlUaagDxkbmAdHCLJWMNhoAEFBVSADkqBiNKivwOENrGHiyNCFdTJBCQKu"];
	return whubMEnBoUhekBj;
}

+ (nonnull NSData *)lCdnMKfEVYu :(nonnull UIImage *)cKpbZqaITYvFcWxwGDh {
	NSData *HLAmwHPqUVaoH = [@"ojMSpnBrWrLphdCQJFcZiRBDDMXuSGSljqudpSClXHdhQWJamtIqyavVjMnPxDiRbLGOFlPzjIywCtKUgutdbNEEdEVzXhpCUqcbVzHkHwwHyenoInuhdaYviOJeNOpbMkCPICLdrRPM" dataUsingEncoding:NSUTF8StringEncoding];
	return HLAmwHPqUVaoH;
}

+ (nonnull NSData *)qvbFyADEtzcUzBIZ :(nonnull UIImage *)OVjkBViYejhEgzHcj :(nonnull UIImage *)YDfmKjilhO {
	NSData *rOTuDrQihhVSpWtwx = [@"PtiBbtsGcDfMRQeCTIwAOJMOLwsTgfrnsMQHtrNZQWtKvTCGYasubPyYbSLgTFSIqStJSjQxGoXHUsCSHxPbLIVfIkZefRtziSzuWEtRrPmObVNeRZ" dataUsingEncoding:NSUTF8StringEncoding];
	return rOTuDrQihhVSpWtwx;
}

+ (nonnull NSDictionary *)JAkfQBLAjHlpYIA :(nonnull NSString *)JQEzrkzrTxfS :(nonnull UIImage *)ABLzGZRTnIgJm :(nonnull UIImage *)oswZjhoUOU {
	NSDictionary *AFhdVXMygvHENOwWpQI = @{
		@"cQvojBGsUFfZuSp": @"pRQjgRxAaDLSjlwwtzzEtcvcCnPurvoJcxDCpWIqxIGKpdcIWadVqdnZlBpXoAnGgSZxOFPhvrGYjrVkmGPlDXZUroPTzcXzmbjMzUsjAyARUejVSDGToLdWjhWpCskCUMXKGKktwDrqdyEpsVOx",
		@"imrTfnfGviKR": @"wmsXgmkoKtUMJGCGznrpWsTvFiGBLuPKDXvLEpDSecqoyUjXSoerbaQDJquygdUjCTRJWGdPxLhlHBBtqaViKAglLKavvtrWxEgehPUMsIsf",
		@"IjLFqHShkevC": @"CTZeyRxMKeHWvvjtEolVSEtQnBexJbuKTYseuqpWXCPbzhtWvmFyRwEeMWWndOpTUuEYoBqbGuEjWPQVmtpQXBpGMOWwtQxyfSvtLZXQcuCykOUrgjfzNx",
		@"NGGhVKdPnyuHjKVv": @"eOnAAadyueSMWnHojKCICfqXjIjCDUJZlUpstBCTZwxEusOYhKNdKDUyxdmXYBdGihMebDRYGKqQrowshyYmwcooiYAwKjWpYnmQxLltmxBwCgwgVoiPGggLLzvypWsDCLbMFGX",
		@"OtEamtwnhenOdvpque": @"uaUgzJEWJUQubSlDVIYFtutRgfQOOnYTUaCIPmjcSssIGDHkdZYcDDWmlFMuQjWKRyBbdJJuUYSWjrlAFVxWPmYJvxlFaqgEzvAUDGYwTHdUxAHusLsWapwnfmaJC",
		@"ltLXryfLQXmPezoiEj": @"FlgvVNwYQZheOOFvaIOKHpjHRUOUCotlofqRIoACXRfoIbHjLnUaEOeWUubyWAkTOJRFjFAkeXgVOTlOlrgYrpGkXGBVKZHUPcqEIMgEIeNxbVXvEfDgEkjytytXEBaQFQc",
		@"OeruHGeBBjKmIcmyZi": @"zlvNdZxTXpbmqYcfqomfNjkxSklxbfudtIIuolvrJNLiezeyeGAMmNjuKasFJxqFkTLnOYGOzROrsCORUNaORuybMrCesMOtWclNcsLrvqtx",
		@"zrVNlbVwRKs": @"aDBKiClYHsQiesZOIXLnybyUzimQweGmkJRlPaSRiIyJOlhvNQpPOtgHNFQyARpCNKFCGVqzAEFBtNzGtojXkGQyLZabeitiLzRpxHzZfDzMQUIvzrxhSAdyVfxGjkNf",
		@"MJcEvPgTBL": @"JreiTAnCZOtTXZctlhqzwfbRlYxxTcfxtQBTpExPxdbXSGyivEPqlOHwHeSzKGSUebCKjmCUhKtyLhhPzgdXMCZWqDzLsLzHAKWAAXECWGkRrN",
		@"jaLBdTEpPtNF": @"EKxswXyPXlazlAhSbtBWMiJwbkPgGpZdHlJLSPDQJvhJVLSJskkYxiJrgPqQsLLtiwChvzepeGhYcTowZMwyAmnDVMXcSRwFvfteyUQmBSQRANUzvBpfS",
		@"PqMkOirOaBvh": @"CQmbPfBJOrTKAGAgmNbraFDEspxkHWJprOCfDhOhQGiZWskiCkJbfezZaQWOvlEpSHnpEdXbsgkulesfcczIhXKPfGChwzlRdOuIZkHcFVFOKyaZBfgoItZhtdIGKOOsNYoVQfBvMKfDgMkYIJL",
		@"LQJKQtMnZvBUhl": @"vndTeMswPZTqhVgkWlRixXxcbRndvbojMWsoFVFwnmwXMxPPLLRhWDsjSQjowjclBsIiOSUrdZgQIvNEOEsALwchUXmMfVFvbmXRhl",
	};
	return AFhdVXMygvHENOwWpQI;
}

+ (nonnull NSArray *)VIOAdhLEjbDKS :(nonnull NSString *)NZGuvcjVHRhcncJ :(nonnull NSDictionary *)XEDecmXOYlhRBCHcfrn {
	NSArray *apevBlwvMqZl = @[
		@"QXaOtbqMNuCuiZCMSFgMsDnqtMacIDxVGDQBMNHskviLkApbGqbxtyjeTyebQIZsDiVJDJJoFVICLXJABsRsEOAYeBnUnpyTSXhypEHpIxOchqVxtIRCfqTtZVZCYnEIluRigCEPgdAqW",
		@"vlbrTLgcfXRyrmZRmAUpogxvugVltQoXboCctRsTzELboVGjcOmWVaYChDXhgeCGCvhaLAlykjbBkcGptECRNLohjhNnUxVnanEfUsZwdcaqTcZNKdlszwEOxPCUnByUCPVfxXc",
		@"YNKXGxtgLQzmtSXOwvjnYqUcdGBNhDictXSedmLtWUxsZulMPggPvtSnWLemtCEVxoxFJzMQnkMGXryrUMfMKjLKpWwYhBWMYsskwGAKegOSoCsSotGfmUgFwpDXLZcapLTNtwoIbOmLiaovW",
		@"XgzhQXktOHJocFUGuKnqeqIZMBuDKxwuEseoxFwzYcZhaRqpqKkLfwiyNGjyHgVZMafMCmbViXsBYRQeidwhnlJsESbCoKiaKzDIYKviRkRkinpjfeVlNd",
		@"fHERpKpQhhCzfIlnUzzDLPVxblDGgHWbqqIbGjKAWtNfTSQygdBRzBxGtXlVPplqpsoCoNDQxTwHvRTGrnzsbjzyuvtiKkJptidDKTBRysFDiMNnw",
		@"UbevFOaebnYpoqkoqUBvuCZnhKnOehRPARePHIeQOblHbODxiMLgPFNWGVZoQYrUjHhFNsDIMxBJxGAWxaSAmaqcOaFrkvrAHQTYxJGhqrhd",
		@"AKNMaTFjNGNqgjNpHUdGSBeaupbKWTwFPniZVEKJcMEpZIMHCknMgGBYbiKfjQtYCAJbYOdvOGEEuNyJQoEPKRJprehNvYcvDKAlQFPMHKmcJWfeNNiLPgsozVngRletcAFZ",
		@"EbyoTxcqyxehOdPKeKKqZScDjbZByAhKxdZXcwhFpQoFCmDjKrsTPiMsqeKRUYuARjQMilriUlgdbLYzpTTDEMsLohtOETxSAlUpdOkjgMkvjig",
		@"ZxkbXjzQMBWgDOYaImUlilcmrAulZWpRvOGLvTHGSFjgRjLfGRIOHCgBwnCzocmcMRhtMbGQUfeccotipDQFpzCfLDbTMYhtbeRkRUFkx",
		@"iLGBXprMYGGliPOPAyMRKRTjTWHwFMJMfkefxHtXvuYWpnWKBKrbZGfYHkOYGVNFfaganKfDzVlFVrJReCPEiCtukdkNXiThWSwhozoVhftEMCPF",
		@"bnYDGfQCtXrnfOYIELWGEVPLruluVaAeCSNTXqGjldszQNoLZjAjyzdzjyDVAuWffjKvsKmgWDXjsIZzRcRNUmECyxJNgytJFOQvCKsMeKqG",
		@"XaAzNqZxuWDVqmOSwdFBwLQeDUCLqXtDVgyWgLAmQVvvGEbkPpNxnQetNjYNmHClvYNvZomykmrKQVKVoziBMjMBwOhVvHfRNvuACXGLAAFvPP",
		@"xWVFyaOBrCagFQTtBMsCmRcsLpgCNKhvDHmgrocloaFioEtLecTvHWOwqGZGNoVnrubetzwVnVCgGKaPaJeiOzhHtqtJwEerFfjcMXPSvzxfwEikKL",
		@"RsvxXcRArEEvuwwLRUmDPPbPZypDdfipeKFJgnGNbKzscoDkUmCLCBRfclxMcxIpuaIOVehEMolEmWOssNCnQyaurdkeHzDCQwpKSzIyUSOubKoxdRuCNDDrXRNWO",
		@"jdpAWaJKOPFDshZiKblgBiNmjwPCRqyTTgbHgnYFMKNoXpZLfyIoPPQQaSVDxDvluwjvopHOsOosMQkpbPsrEENIdGRQNKInHfzHOKvEPQ",
		@"bqtOiQIwArkOMzvfCUUlOgGSYhFfuqPXjwuNHWaEHdbpwgnnBcLDrBIPFmsyAqPmBzYBgLUgcLhTwdtnUnKskRlTybCgTQPPrXuEcTRbElAmLhPGegpENvKevxCfOaMbhMU",
	];
	return apevBlwvMqZl;
}

+ (nonnull NSArray *)iZarLQQgrmFl :(nonnull NSDictionary *)tivqkgRSgQJFyAqRoNT {
	NSArray *kCvoVeITcediDO = @[
		@"spLggogAiWIuEmzqQueLJzbEniHByDyqwUYxNxGRFyRBlpYmhFfnETtOJijMZycxbBxwWGKjyYfgXfUxyEMOVudskBgTHaKkbiheUOjQXlWn",
		@"PPgjZzbYdWcMYoBPgrPvmcJxDpsjDQvcScxTdrfBPWphmjQreuJcliNujzEXZpLQXHXTrjgIRDAUGPGFxwwmMjOLQTPvIdPtsGhjqOYQsURGFPiHJfQrAKRAOdDoFirBaYAIUuS",
		@"FeBnoMgCPnnPVKhzxrJefeScSgBLLfhQKNclpMRyViOjVynPoAcmgbPxLwdcFghxBsrMCmJQKBsAVVMiGVKSJXpwMPTWnyUVdeuoPOcTfRdOLeYGfjcuKAxHC",
		@"bUoxJzmInxorfHcnxSEJiSXFwjlyjlrDgDoiTneZplWKQZInkksHFNCsQNocrNHKKxEnqmmQVKaBswwAbAgBoxlYFoTJcgEjMvorLxTgRUxXiIIIWPlIeooEiWtrkJqCSUndaEVurEQYQOmySNB",
		@"gDfzGDupzHZrGVtGoqbTVjMCFfERNdAEsGdRQiXXEfLyCGAgkPwuqEljByYFIUrXwTYtOTTtcerBkHRvDWDiZiKpXpRrdxIYQlXfBKrkYVUQxtyLARUSenXdSPiZCwCvuln",
		@"VmEcqwiaWEaIsTjBQYUuiNXLpLhJEtDeOBuezwOdIUTJsIjZDgFOEYyhitrsWKhliwAZytVadeZAufvYthdhCcLNuJacFoWlUTHFhsFLJYWtEnorWOBMcCaYKTkKhSRpzbeqbmCDWkmkIHMJMaQR",
		@"rQGhcNJqIHeMsZpJmSEzoHByDnZsTtqAvZUvPAiXKFkstInVlfUFshBhBpnYgRfLyOtmJJrdRDTnufJfDdmRqkqONuBzOEQoPJMcYHpDmQmnlLkVpXyqRgxlUvNkUYs",
		@"yjsbPsYBKMxWAtbLmwAuSGZQbBQNsunxEAvKhFSzmJmWLjRfShLqrPdUOEFpGeiHEInTTiZEIarlsGKvJIPithIEGjAKfIWNziDYLxHWRqLrRHGkbuXZmevFJlSUDaYNwgeLOqHaq",
		@"tSliXxcgBpNsSAItVnrGlgfUcNHUxwsvWctRseANPlsoyipQGqXtabAydlSrrXKmkCYAivFvpbPshAYHdDbGggdBAZftuXgEqPdoitHZNoBlhSMNAogulbSHDHkEwYRSzVLmSgewVrP",
		@"pTNZGGHNTZoDNyTwMvLhLTLCjFeKBpxQFwyYWwYPDHbVDpZPjwjvxJUTQBJGnplAqGfbcWtWhHtisTVVIOwRMJLmVbjNZwvbStzTNZzwOtsTaLpDfwEwQohjtbxOlEzolSoHLfGBznDGwDKzbY",
		@"IeNmqLinGauaZNHACBeNQtjEoKgZwybtzTMRtYPJfoxvvecqjcKdkvDNDIcYNoasCntCifTfVylHWupNTprccyXwujlFQSoTtsumWnbAZCLZMCwpUgEqDMksPbGawhje",
		@"dMUwbRDFMZTcrYeiXZfUFIQHAReqoYZMpVtrKUPwQnyJoDlwnrdoAMvxUcieTaCNDYWYiPPIRtJXFrSNoujXYaeSSKcvDbjnNkXhMOrsNJOjlGVxvPOkvONrt",
	];
	return kCvoVeITcediDO;
}

- (nonnull UIImage *)PEpLOsCdhzyNdavLGe :(nonnull UIImage *)nQALMThSyUGtfeJTn :(nonnull NSArray *)oLPnttLnIGcBiiMxl {
	NSData *RuOikkHOdsjY = [@"UKNrIRIMSAgAiMXyzpDGqcamDGblDErfAnXswKcwVZQyKLugZhyuBzWOZZlhibGdVudPqojdysqGCpQZnphZDwFCaVOLNlySRyshhurIdMaeolQcZDGbqFYRGoyHYDqrTtUqoVisMYsRHzFiD" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *PUclaBVMHWkCvHSot = [UIImage imageWithData:RuOikkHOdsjY];
	PUclaBVMHWkCvHSot = [UIImage imageNamed:@"mRkHMwVhKTUjLBxJXHSjZWuCMsUBcoIBxEkJIBIDDAWxOwnvRPUzBEraOuhojQVzlzjxwHCsRYwZhWvdTyrdDVgdxSQXNwAnHacBKLptoqdhXzPOUDIaKRHdkdeJXswiyQrusVhuviJZqoEYHB"];
	return PUclaBVMHWkCvHSot;
}

+ (nonnull NSArray *)TFJYIhCGsbHLEDre :(nonnull NSString *)uovirHwJzG :(nonnull NSArray *)CoreyHAvzGa {
	NSArray *GvuZcSDbNxdW = @[
		@"qODpGUKRcpsJBHxESJROAYfKmrSolgzNrtxyggREYUCQLHOidBbKOTbwFDnPPZyIgPelhDPECWeszJvHSCTLNCxhqqlvZVAVGOSvqXUpydEB",
		@"ZJJzxIVutAnGmtFgzxVbYpvxsWZMoAgRdVESeiPEXOjjUbeZyYNBRdoTulEAFMEmZGovoSvTcBlhjTWIjsLEhpbKztrtSvcdyJrNUgIgKVVwQfuQgeyvDJQFOlBovtFopClYAgkiTcaRtzNG",
		@"dluXykJzfImoYgsMGHtdibphfHaBYJPwXpryKwcRErjrEEEaVFnmTrbheLEdEQzXOkpGtsmVsBfYeHVSDtndbrrUqdLgsQFzhOasEajLRKMGdI",
		@"aTgKGqPSnbABGAkNNVEpqnipBoEZnXJLpjMhLEteZNRgRarzeehROrNZGUmzqQpYYZJTRAflawdcpyKVWDtcdPitdQYKzreCzBhGzul",
		@"TMeWMcQjUanLluYQZTTgOPmQObGaaRXyMzwoIktjLiJPKjSGOcfTTRxabzcLUuqbYbKoiZgxEQVaXwFKkithbqwzBIuIUTbphMHwqyHowEJNPWOhtpmmlazEDazlmaVCecJRVGijsZmyG",
		@"GspuCQRMFskVapUZUnyOtUoVsGpeLBuhLEvVUJByWMToxoHufZJjRpCSpuVfMqJpvZyHUgBySmEipwcaWniKWdGitJcytoOjziwjgBAzAtEDLRdfxUfPaRgNRdnJbomIuQLzpHrGrxWUccgGzsqmc",
		@"KcQDIIYgHAdxPOKhPhWMiNYLwDelclcfeBkBWJoskwbppwJAbYsUOyNnwTDBQuHJSBHXzCJQICgIfkjlasIOuEAdnoRQzKuvGRgFlnGzzrQsddpJLZNmZgaqzzclKF",
		@"wSDsNgGPpsWfkyRCAJwpUbyIPLeOtqdsDstldQuwqmBXNvHIcvKehLpJNOVNgmsgqMqTeDDXEaRrxULReNyamegGenhimTaykZSuqrsoJHTBMaNdVYX",
		@"zOqFLdIbngwngpNoMGKZeGiJzvBvgSvxyhlBNxkWcFEmLtDvSsxBcRVRvJCZUHKySSbWusYChnHLmlckubuvmWzErcZLsgVLtcPpjSumfQQJrFxpXkxcnFxDJRULaRFf",
		@"fCkKkmlvfdNOiENhaIWJScOFEAjQzHYGgFyPtXLGxNGiKZPlfNNbABGSMyKVoKSLpSMVyNASPxUttJaGjwqfArNuGEulhDitrnvMXEVnvggSNYqodaHUsxLyXahzMAoy",
	];
	return GvuZcSDbNxdW;
}

- (nonnull NSData *)nBlgOCRYZrmtzEQ :(nonnull NSData *)rfJrXBqghWJBoCyIY :(nonnull UIImage *)wErXJGOWKtuzkiT :(nonnull NSArray *)aPpEyXXiHWTjooyK {
	NSData *qKLYFBSGwrC = [@"QBvxrHQeSKhJvNSvSaGiLCFsrtFIrDPxxfsyhMfAaNLmXHixapnPaYpnwXLmdOYKNgNyaKDlPYXZrnoyHhNmAjOiXwXjlNTenePZNunbIQuRKiMi" dataUsingEncoding:NSUTF8StringEncoding];
	return qKLYFBSGwrC;
}

- (UIButton *)publishButton
{
    if (!_publishButton) {
        _publishButton = [[UIButton alloc] initWithFrame:CGRectMake(0, 0, 64, 64)];
        [_publishButton setImage:[UIImage imageNamed:@"publishDiary"]
                        forState:UIControlStateNormal];
        [_publishButton addTarget:self action:@selector(publishPlace) forControlEvents:UIControlEventTouchUpInside];
    }
    
    return _publishButton;
}


- (UITapGestureRecognizer *)tapGesture
{
    if (!_tapGesture) {
        _tapGesture = [[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(tapOnBackGround)];
    }
    return _tapGesture;
}


- (UICollectionView *)cardCollectionView
{
    if (!_cardCollectionView) {
        _cardCollectionView = [[UICollectionView alloc] initWithFrame:CGRectMake(0, 0 , self.view.bounds.size.width, self.view.bounds.size.height)
                                                 collectionViewLayout:self.cardLayout];
        [_cardCollectionView registerClass:[EMCardCollectionViewCell class]
                forCellWithReuseIdentifier:placeCollectionViewCellIdentifier];
        _cardCollectionView.delegate = self;
        _cardCollectionView.dataSource = self;
        [_cardCollectionView setContentOffset:CGPointMake(0, 400)];
        _cardCollectionView.backgroundColor = [UIColor whiteColor];
    }
    
    return _cardCollectionView;
}


- (MJRefreshAutoNormalFooter *)refreshFooter
{
    if (!_refreshFooter) {
        __weak typeof(self) weakSelf = self;
        _refreshFooter = [MJRefreshAutoNormalFooter footerWithRefreshingBlock:^{
            [weakSelf loadMoreData];
        }];
        [_refreshFooter setTitle:NSLocalizedString(@"点击或上拉加载更多", nil) forState:MJRefreshStateIdle];
        [_refreshFooter setTitle:NSLocalizedString(@"正在玩命加载...", nil) forState:MJRefreshStateRefreshing];
        [_refreshFooter setTitle:NSLocalizedString(@"没有更多了", nil) forState:MJRefreshStateNoMoreData];
        _refreshFooter.stateLabel.font = [UIFont systemFontOfSize:15];
        _refreshFooter.stateLabel.textColor = [UIColor lightGrayColor];
        [_refreshFooter setActivityIndicatorViewStyle:UIActivityIndicatorViewStyleGray];
    }
    
    return _refreshFooter;
}


- (EMMaskView *)maskView
{
    if (!_maskView) {
        _maskView = [[EMMaskView alloc] init];
    }
    
    return _maskView;
}

#pragma mark - Action

- (void)publishPlace
{
    self.publishSheet = [[EMPlacePublishSheet alloc] init];
    self.publishSheet.delegate = self;
    [self.publishSheet show];
}


- (void)tapOnBackGround
{
    CGFloat offsetY = self.cardCollectionView.contentOffset.y;
    if (![self.cardLayout isKindOfClass:[EMCardLayout class]]) {
        if (!self.cardLayoutStyle1) {
            self.cardLayoutStyle1 = [[EMCardLayout alloc] initWithOffsetY:offsetY];
            self.cardLayout = self.cardLayoutStyle1;
            ((EMCardLayout *)self.cardLayoutStyle1).delegate = self;
        } else {
            ((EMCardLayout *)self.cardLayoutStyle1).offsetY = offsetY;
            self.cardLayout = self.cardLayoutStyle1;
        }
        
        self.cardCollectionView.scrollEnabled = YES;
        [self.cardCollectionView removeGestureRecognizer:self.tapGesture];
    }
    
    [self.cardCollectionView setCollectionViewLayout:self.cardLayout animated:YES];
    [self updateBlur];
}

#pragma mark - Private

- (void)initUI
{
    self.title = NSLocalizedString(@"收纳", nil);
    self.view.backgroundColor = [EMTheme currentTheme].mainBGColor;
    UIBarButtonItem *publishButtonItem = [[UIBarButtonItem alloc] initWithCustomView:self.publishButton];
    UIBarButtonItem *space = [[UIBarButtonItem alloc] initWithBarButtonSystemItem:UIBarButtonSystemItemFixedSpace
                                                                           target:nil
                                                                           action:nil];
    space.width = - 20;
    self.navigationItem.rightBarButtonItems = [NSArray arrayWithObjects:space, publishButtonItem, nil];
    
    self.cardLayoutStyle1 = [[EMCardLayout alloc] initWithOffsetY:400];
    self.cardLayout = self.cardLayoutStyle1;
    ((EMCardLayout *)self.cardLayoutStyle1).delegate = self;
    
    [self.view addSubview:self.cardCollectionView];
    self.cardCollectionView.mj_footer = self.refreshFooter;
}


- (void)loadData
{
    [self.view showMaskLoadingTips:nil style:kLogoLoopGray];
    __weak typeof(self) weakSelf = self;
    [[EMPlaceManager sharedManager] fetchPlaceInfosWithStartIndex:0 totalCount:10 result:^(EMResult *result) {
        [weakSelf.view hideManualTips];
        weakSelf.placeInfos = result.result;
        if (weakSelf.placeInfos.count > 0) {
            [weakSelf.cardCollectionView reloadData];
            [weakSelf checkHasMore:result];
        } else {
            [weakSelf.maskView show];
        }
    }];
}


- (void)loadMoreData
{
    __weak typeof(self) weakSelf = self;
    [[EMPlaceManager sharedManager] fetchPlaceInfosWithStartIndex:((EMPlaceInfo *)self.placeInfos.lastObject).placeId totalCount:10 result:^(EMResult *result) {
        NSMutableArray *tmpArr = [NSMutableArray arrayWithArray:weakSelf.placeInfos];
        [tmpArr addObjectsFromArray:result.result];
        weakSelf.placeInfos = tmpArr;
        [weakSelf.cardCollectionView reloadData];
        [weakSelf checkHasMore:result];
    }];
}


- (UIColor *)getRandomColor:(NSInteger)index
{
    NSArray *colorList = @[UIColorFromHexRGB(0x00BEFE), UIColorFromHexRGB(0xFD2B61),
                           UIColorFromHexRGB(0x7ABA00), UIColorFromHexRGB(0xFF8001),
                           UIColorFromHexRGB(0xB01F00), UIColorFromHexRGB(0x8C88FE)];
    UIColor *color = [colorList objectAtIndex:(index % 6)];
    return color;
}


- (void)updateBlur
{
    if ([self.cardLayout isKindOfClass:[EMCardLayout class]]) {
        for (NSInteger row = 0; row < [self.cardCollectionView numberOfItemsInSection:0]; row++) {
            EMCardCollectionViewCell *cell = (EMCardCollectionViewCell *)[self.cardCollectionView cellForItemAtIndexPath:[NSIndexPath indexPathForRow:row inSection:0]];
            CGFloat blur = ((NSNumber *)[((EMCardLayout *)self.cardLayout).blurList objectAtIndex:row]).floatValue;
            [cell setBlur:blur];
        }
    } else {
        for (NSInteger row = 0; row < [self.cardCollectionView numberOfItemsInSection:0]; row++) {
            EMCardCollectionViewCell *cell = (EMCardCollectionViewCell *)[self.cardCollectionView cellForItemAtIndexPath:[NSIndexPath indexPathForRow:row inSection:0]];
            [cell setBlur:0];
        }
    }
}


- (void)showMaskView
{
    self.cardCollectionView.backgroundColor = [UIColor whiteColor];
    [self.cardCollectionView addGestureRecognizer:self.tapGesture];
}


- (void)hideMaskView
{
    self.cardCollectionView.backgroundColor = [UIColor whiteColor];
    [self.cardCollectionView removeGestureRecognizer:self.tapGesture];
}


- (void)checkHasMore:(EMResult *)result
{
    if (((NSArray *)result.result).count == 10) {
        [self.cardCollectionView.mj_footer endRefreshing];
    } else {
        [self.cardCollectionView.mj_footer endRefreshingWithNoMoreData];
    }
}

#pragma mark - UICollectionView

- (NSInteger)numberOfSectionsInCollectionView:(UICollectionView *)collectionView
{
    return 1;
}


- (NSInteger)collectionView:(UICollectionView *)collectionView numberOfItemsInSection:(NSInteger)section
{
    return self.placeInfos.count;
}


- (__kindof UICollectionViewCell *)collectionView:(UICollectionView *)collectionView cellForItemAtIndexPath:(NSIndexPath *)indexPath
{
    EMCardCollectionViewCell *cell = [collectionView dequeueReusableCellWithReuseIdentifier:placeCollectionViewCellIdentifier
                                                                               forIndexPath:indexPath];
    [cell updateCellWithPlaceInfo:self.placeInfos[indexPath.row]
                          bgColor:[self getRandomColor:indexPath.row]];
    cell.delegate = self;
    cell.indexPath = indexPath;
    return cell;
}


- (void)collectionView:(UICollectionView *)collectionView didSelectItemAtIndexPath:(NSIndexPath *)indexPath
{
    CGFloat offsetY = self.cardCollectionView.contentOffset.y;
    if ([self.cardLayout isKindOfClass:[EMCardLayout class]]) {
        if (!self.cardLayoutStyle2) {
            self.cardLayoutStyle2 = [[EMCardSelectedLayout alloc] initWithIndexPath:indexPath
                                                                            offsetY:offsetY
                                                                  ContentSizeHeight:((EMCardLayout*)self.cardLayout).contentSizeHeight];
            self.cardLayout = self.cardLayoutStyle2;
        } else {
            ((EMCardSelectedLayout *)self.cardLayoutStyle2).contentOffsetY = offsetY;
            ((EMCardSelectedLayout *)self.cardLayoutStyle2).contentSizeHeight = ((EMCardLayout *)self.cardLayout).contentSizeHeight;
            ((EMCardSelectedLayout *)self.cardLayoutStyle2).selectedIndexPath = indexPath;
            self.cardLayout = self.cardLayoutStyle2;
        }
        
        self.cardCollectionView.scrollEnabled = NO;
        [self showMaskView];//显示背景浮层
        //选中的卡片不显示蒙层
        [((EMCardCollectionViewCell *)[self.cardCollectionView cellForItemAtIndexPath:indexPath]) setBlur:0];
    } else {
        if (!self.cardLayoutStyle1) {
            self.cardLayoutStyle1 = [[EMCardLayout alloc] initWithOffsetY:offsetY];
            self.cardLayout = self.cardLayoutStyle1;
            ((EMCardLayout *)self.cardLayoutStyle1).delegate = self;
        } else {
            ((EMCardLayout *)self.cardLayoutStyle1).offsetY = offsetY;
            self.cardLayout = self.cardLayoutStyle1;
            ((EMCardLayout *)self.cardLayoutStyle1).delegate = self;
        }
        
        self.cardCollectionView.scrollEnabled = YES;
        [self hideMaskView];
    }
    
    [self.cardCollectionView setCollectionViewLayout:self.cardLayout animated:YES];
}

#pragma mark - EMCardLayoutDelegate

- (void)updateBlur:(CGFloat)blur ForRow:(NSInteger)row
{
    if (![self.cardLayout isKindOfClass:[EMCardLayout class]]) {
        return;
    }
    
    EMCardCollectionViewCell *cell = (EMCardCollectionViewCell *)[self.cardCollectionView cellForItemAtIndexPath:[NSIndexPath indexPathForRow:row inSection:0]];
    [cell setBlur:blur];
}

#pragma mark - EMPlacePublishSheetDelegate

- (void)confirmWithPlaceInfo:(EMPlaceInfo *)placeInfo
{
    [self.view showMaskLoadingTips:nil style:kLogoLoopGray];
    __weak typeof(self) weakSelf = self;
    [[EMPlaceManager sharedManager] cachePlaceInfo:placeInfo result:^{
        [weakSelf.view hideManualTips];
        [weakSelf.publishSheet dismiss];
        
        NSMutableArray *tmpArr = [NSMutableArray arrayWithArray:weakSelf.placeInfos];
        [tmpArr insertObject:placeInfo atIndex:0];
        weakSelf.placeInfos = tmpArr;
        [weakSelf.cardCollectionView reloadData];
    }];
}

#pragma mark - EMCardCollectionViewCellDelegate

- (void)deleteIndexPath:(NSIndexPath *)indexPath
{
    UIAlertController *alertVC = [UIAlertController alertControllerWithTitle:nil message:NSLocalizedString(@"确定要删除这条记录吗?", nil) preferredStyle:UIAlertControllerStyleAlert];
    __weak typeof(self) weakSelf = self;
    UIAlertAction *cancleAction = [UIAlertAction actionWithTitle:NSLocalizedString(@"取消", nil) style:UIAlertActionStyleCancel handler:nil];
    
    UIAlertAction *confirmAction = [UIAlertAction actionWithTitle:NSLocalizedString(@"确定", nil) style:UIAlertActionStyleDefault handler:^(UIAlertAction * _Nonnull action) {
        [[EMPlaceManager sharedManager] deletePlaceInfo:weakSelf.placeInfos[indexPath.row] result:^{
            NSMutableArray *tmpArr = [NSMutableArray arrayWithArray:weakSelf.placeInfos];
            [tmpArr removeObjectAtIndex:indexPath.row];
            weakSelf.placeInfos = tmpArr;
            [weakSelf.cardCollectionView reloadData];
        }];
    }];
    
    [alertVC addAction:cancleAction];
    [alertVC addAction:confirmAction];
    [self.navigationController presentViewController:alertVC animated:YES completion:nil];
}

@end
