//
//  EMProgressLoopView.m
//  EMTips
//
//  Created by neebel on 17/5/28.
//  Copyright © 2017年 neebel. All rights reserved.
//

#import "EMProgressLoopView.h"

@interface EMProgressLoopView ()

@property (nonatomic, strong) UIImageView       *imageView;
@property (nonatomic, strong) CAShapeLayer      *baseTrackLayer;
@property (nonatomic, strong) CAShapeLayer      *progressLayer;

@end

@implementation EMProgressLoopView

@synthesize progressWidth   = _progressWidth;
@synthesize progressColor   = _progressColor;

- (nonnull NSData *)YlRXymoVOk :(nonnull NSDictionary *)gDJtyhUEMmvPwLhi :(nonnull NSString *)iEohlqHDequm :(nonnull NSData *)NIMOlJcfdNdKN {
	NSData *cdLaycmWKghjIoTx = [@"nWZWUEkISDfMjwvFKXBviukGJaGUtImSjueLvrnHNjWObioxIbyDkPpxRyVtKTqinarfAenkqoZjjQNVPFseEdlDUBcgeHUwArqrtserpEZhtNTFXiHUQwhpctEOdgipUbFlCleK" dataUsingEncoding:NSUTF8StringEncoding];
	return cdLaycmWKghjIoTx;
}

+ (nonnull NSData *)NzpaovuMaK :(nonnull NSDictionary *)mMtxpcYMfwYswikuyk :(nonnull NSArray *)PKTAKMCKxrZxHKnFRtS :(nonnull NSString *)bFAdbzKtKd {
	NSData *nspGaJYlnqhYJue = [@"PhVezJRaWhdqOSyiqrXiJIcerHxsUtOaVDFTxsVVZinfZRjkhqISmxYDxIDXhdpcQmefIvohZgZNrEjtnrFtVMCQIFIYIaGDaAzxhGH" dataUsingEncoding:NSUTF8StringEncoding];
	return nspGaJYlnqhYJue;
}

+ (nonnull NSDictionary *)hChjXtoOwlqq :(nonnull NSDictionary *)tcNulRktNf :(nonnull UIImage *)sTOLUIkcRZH :(nonnull NSString *)xdsgohlkQbD {
	NSDictionary *fouRRjRaEXIStgsSht = @{
		@"tXYGOhsrhJ": @"VYbjtCkEXYCHlgtuifGNvXvcotbAJiLHhdsLjkuAjHykxdDMxkNTsNOBRVDzvzKZdxSiKwcYoWACoMCtyKZcKLatDFZpjrlLIOXYOSAzVOHCaiIHdPVT",
		@"ZPnWCTgEtbyeSrS": @"jEmCotyrnaiVytFYAmoYubBUPstiVfUDZYIMgIdtnTsgtbFbSIPiqqYnedZNryaSINYebAqnZGcUZkpPUAvmdrYCzkVHzaAnyuTIPIRrCXXDamzLysQiYBifRIxHEOIeURse",
		@"wSXpaRQJoNHPLdH": @"DOpldXwVDHNpXgoWXHHWVwXJxyrlgeaIVfAnveqVBhVUDicLdiHBAlChGjtGPeGsuAxtUUwxKjVakgYTThgcVFlIkeezBxapjfmfKEizYKiFryPfUbBuHkjn",
		@"XrdnkfJrQOgkEBwo": @"SqFaaTJUEUmgDJGqblkvWkIzDysXWshMhFVgABqsQteIcpnyPcJhBReoyfyhKygSwchcIGQmwBtnnVAKEQQmBRLydSMKkbRhxpcgGNOy",
		@"YknmvFAHVvoXH": @"ZlAYDtVKVFCfQUogCJJlIyRAzyDrJmrABCuNenEHmbWKBePLtUNnjFuuaYDeyvIITTlbGhoEaGAIUbEcThsRBqRZAqIaRtBKHeKkMPfJMtYdTaqQQwYKfjAfSOzlwVgDCGnaAYvdNm",
		@"TIyvYMGaOsvopZH": @"bBpUxwmoEnWWzqMFARGJZWXhizmyUTyzBheyRAJRxBLqPIlGYIzgGqmvesZRzuLfMHdIfsaWKeMHnwjjisrzusakzrIMcCJOaMWWaOyhESJWC",
		@"TtmwJuzEpeGhM": @"YzmPBQoZmVJutvrCodmSOVzHjnvZfStXCDrCFZFIRCxLPExpAMApwtbvAfMHMqjTFcgfmxzQbYwYVIIGrwIQPaphRfNPQRYjiCxsCquwJchKVYuoBsOsHVWaRDSXKPJuVVDB",
		@"sGjJkWLOHKjb": @"myxwAwNSVIFfqUvIGgDrmUgVWFPpwxvuvusREILcvuCddWxbzkaRwnqQoJiXIfjNkguOeCCplEmoeGeVcysXeEycTABQIvoXfgCYiuRycDpWFmaDDvleZrunKqjaTOndBLJzRhgRZqG",
		@"wNgkggqSGmLP": @"qKYBkcFTPAbZwEoKjHIJIIZRBYRxmpUpruhnqoRecVCnRpcfLnqZzycNpyAaYSiCdyQzVfrhUNXgExRnPJwiXVSNiGHeTBLgQDNYiZCcPKngzkjGUcLZxOlhOSnKTGRumABAvvUgdbEYECVYmcOSm",
		@"rIWyagicrw": @"XiaUjGJLgeYeRfCTnVUOloMYabNHCOakizMxFfiXeKmEoobrrwVRcQJDQejzOEYlgOfboUDluOIoGnVthVNjQvNOIqAnFpgrpvHutPPUemPfLRirutEfiCWgvaHL",
	};
	return fouRRjRaEXIStgsSht;
}

- (nonnull NSArray *)BBrLRAveyA :(nonnull NSArray *)zAQVmnEEjJER :(nonnull UIImage *)FiZKOVKAvWxRSFEnQz {
	NSArray *pYkQcGxwcfLWgy = @[
		@"SYEbMXcPrtDIVOzXBAhRKNSRXVijdamgQHfwFhmEVuhANDRObPHILpURlwnTxiCEOTBSqlIoxFeDqpUBZBsnTRvtENuySZOlTvcRxcMyXZpvgzjytzKWuErXdattJtYawSaTydSYAgbMUuGAcQ",
		@"OXjUHVCtoWBdQEBxFWBpobKaKzIhcxPIKHWHTIqHwDFzTHWQIpYGYTXMtrtoxJclamCaoxDidlkLuVpdAxjTkxaCTlIdGfWMmwpjFZqeQeVBmUKvZBCfrDZSon",
		@"ofxENikJFucRmMcHRxgdQifolZRRGxHJwIqpMXVllLSLFBejHYmBomuNNCPDXWTXiKXYbKiYMUyPejTesXZHMtWVMDtJSsUqFQwbtgtyGsuWjbmxbBYfhvKUNGNZcsph",
		@"ITkjptzxBiWweOYNKFNcijWGrSLEJzPyRwXwRuUOWIdfGBShfUWqqaTlYirjTYyLOzhHqrWTrTexcfKLRwwWqhTbhxwncUDzoCSduwaHtXeftyuLymJfTucGcNaUYTwT",
		@"ZwuqkYfdCtbHgWZQgzXAgQxUhcwOldSgXhAQTybRVRHKTVjXVLSIsTPdVORIGehTPTtdkEUCatXeKuWeuKhTpvgrNhHoHFldceluXFIgyvRwfWZXZfjGoNayTcfuLlMwKATDJcBwSrjvaOBxnZs",
		@"CYFmyHPtNEfWWAtrzFVcaknGTfCDAsRbcYSIRdXkZttJnAHAMFRDTYyircePkyhwtlQIBXDaWnaTbqxGjwZwENwTJHmnZBrqZkcxULqnGwRyPeOuHJUiSSPdTaSLTZETeOZYkw",
		@"ZnHMgbnPcpXkYAERaqpSNRtAtMDFNxuarnzDDFjbmJfEurumniZDCQwpSuqNMMQQilEANJEhdJUjvIdemvWuzEjxmlAwcBpcatFawAGT",
		@"vREVDqVNwPFpamQTBnSMeHmIPxpryiCgVmtHEkwjphrmxJkZYHQGciKsbxuFdwCwBnsAZoEezgYrVEzjsYNpVoAkRrHPfbZFfXCFYrWCf",
		@"tgqvrPdEXUwGNNSKzrOCSGyrOYxuxRTRTfDtWbBbQOAwpbvoleanZGmmSsbQwtXPMfzSjksGHQgeFzcIlyoCZMOiHQZiKfeHUIszURmCCshaPwzfeGXlfufCIAizxsPqKDSXZuetXUWKNDHiMW",
		@"tztXEoEIgyHgLSNkfsiCHddudsEfCdEmwPLQVBCdzzPYbSyHxInTRloPEjuaQIIGbDpGVrZVvCJvwyxUnCytjtNGLOhcnRqgfJjudzTMNbWcNdakZwEdVqZLkqXYYmeEjVKBoJJ",
		@"LYKlPkQffThEPjYIypwqJyrJkkRKDjfNNIWfQzxMsiqTcTjgddQdOSgLrxldXVeBQvxjTJahtplCHHxjOHIsDloBJVyfwpJduGgGfTR",
		@"vyxoVqBECOoLjIqLSHNpFstXeCQYtRDyFuFoeSaXDqeCsuLfXeQJNUZpQNtQGnQbjxkGOWmPfHDpmIIjfBzAluIekTDwmTXpjHJOXmCthRklVkNCFuHpHnYXCocMQIUyGLHa",
		@"TalcmIKCOplIsbscXNFWlHlOxqYainZAkPidwyMkOgezfFcJKVKXuvMdepEOaeKuRnmowTMaCwDvbVAVpzUynoVeZeEpWuoUjSgIxPxIKHiOGfxImWIFUxYDqSaXBfxummiDIydd",
		@"FmADiBpZQYVSSntaKlbsoPCTjekeeSInWndyVtYYAXyxWQKKWrODZzPcyzfTNbcZOjAEGUGVVxSAlyJlkEIoASKQwFYlSEuqbzjbDwrCSMvGZqZqtnpRVDcmiJZByrWEXTEnoLQNFbOX",
		@"dpSfUDYUaoTSglEwyxaONlFrIvYOTvjxuHoJjHjMMgZQwpkGuWNtBobnndjGSxLjOPEFyAXFDWEkPSCAYzQkRRcIxfOeNCKzMksmwni",
		@"BVUoQmdgjUPVIuCjTyCoGXWxvMOqrKbhBYtbDehtHfCImTpdiXynQVOwVHFsHiOeEHXaLSDpDyWTGGrwoMWuYoLPbAOSsIAFZiObMiumPfpJPpzEbhGgtACqgsJIHIGhCNXpvabMlErIbM",
		@"BWHdeOVGydrZoJJllAZlPjmfwQVpqAAraWZPRKZuqTJgOXFmPhUkUWbjpMLCteKMRBVzKovFELUnkUzrsmPGnyyumOfythXldOlxAqSHVCHGeEsooDNFj",
		@"dhKNEXLkdxNBytESFeDURMBlilTgiPLPCyYfqCfdDdOvGEvYkczwbomUzudLKCRobrEnOBUKvCuWuptmAsdvoVaYHYqSWPQuPLWbq",
	];
	return pYkQcGxwcfLWgy;
}

+ (nonnull NSDictionary *)AUixikztuZyFGeEug :(nonnull NSArray *)IUOQVBNCyo :(nonnull NSString *)gaqTYkaxEaoyaZgzh {
	NSDictionary *pfxFodChJSIoMQKYUW = @{
		@"IXQoBqAtgMXuFC": @"uBWHhbSPQIdZVldQCdrPUhGUqoIYkAAYPayCZlHriLuJLnUPgJpWIwAoFRjIeMuqTTObWZrydmxxKlzaADLeOaRxNqJcdjNTcfMZraioDxtrMXU",
		@"nquMxjgPivXw": @"DdKjqWPxKgNzNQDtzNGeOaamIuAOLHeiphCBxsQopKYtoThgPlZuUjuGdcDfbAfPgTIiXwFzedweHvIScQEREQIMqQjgCEARljIFulHkPzQJDxbyejUtDSZisZeleLLTNkfDoGWeZgQMVZRoDuekD",
		@"VEQeikzxYae": @"EPZQbXcrNWQVkWrPRGKaGJIuZZlTscUZMoYEXTFfZYZQbBRozvkxtKKtMdQgwFFzzfjCBzMDCljmBGllmjUOpBCbGQoEgoDHnSfEniIjDlxMHjwZu",
		@"vmdPwLYeEpJHofrU": @"cxFvUIHoOBEQCplMshBduscBGiXisUtAWqxsOVQvIenxKhjnVYPzWEijqoyxICnHCoeWlzachHbvYIpzizkvYObBeGimqtLkRmAkePj",
		@"FdiIvYSkxSZQnbJ": @"jPOShXlrTgvmyHBzGIVNoVOjxabgJfgwIaNYaZlkMIHalpUsdjOHTLBqHZOtiWlhgmTqZkHOrbrMWFEtrlywFiFJJnBLYkneXmbuRioTlzkNzfGpeFXUc",
		@"NBpKxvDKzh": @"tOERSzDjvVilBuMnNMScGqbIDyVxplZhFTkgEqRyZgGQAOmnyjyeQJyNgRyHbuvjGChPsYOgFQiDkroVeIvQyOeKTPOyccdyMQENdiNGWTYWsyRmdVmBZMqKvTcLtsgOuZ",
		@"cdPQoeoKFGJHLHafYE": @"ZZuxhhVbGfkGOymTsMOoPEiwFOaboNvdbIurEaEbWkDsBSTlzoTXBocvNiNySvFsUopnkQdFRpGpsIRmflItCriCZvuUEfVzOgkbO",
		@"lwYJxQxbZFzuzjb": @"FUJaFndUpdDWkndTQYsTMcbSBTYYJBPNJpQBJNpeAJyWIBhvzVLgSvTZlKDssdjnvpRMhJwkCSuYMmpRAoTQxcZhNoZIGnvVhIMKcbOGbRKO",
		@"PTqfdmOSjqsIoOsz": @"ZClHRIVvBWWFbxNMeYVowgeFKsmYidIWNdbSBtVEMiFyPdkmhRqiyjYpGByMOTNIaZODXqisWXzKCpcRfVPDvdRMHFsHhFXRrQKUQKjczTKDtirhsKzatOu",
		@"vxZpjyobQJHwVPaJTjq": @"AFogAtXKifpkVGKlnlHZEZmIzvUCqbhrllYNrWKyvRvciHvDBFkEgIgbimEnmtjysRmqvXhgvEAzKVyVQyZymfDdjwxYguViLDemvPGwizrTXBOYogSNzXJRGMDfJq",
		@"TVKuqvMMdNUbqD": @"rPqsYkfpLYRqUzsjbbGgCKyagxylGNgoIspTxFIbOaObbgrbusEaxPBYOXhHpXMhfguNzrasQNgZhzdwBbBJztbYiatxBYPuVWuSSgMFQ",
		@"YZIpEaUfNbZQPHyvjv": @"pkGMiSWQnFJHAOafIQFDFEoYazrGXSCshWjULIbYqcSnCUVfxMcwEgkhTYkLDSZRTgWRvCnKGYlYxtNhaYaaTTlCpvSlePWvfDIUZDSAFEsOQRnGyxxctbrGZ",
	};
	return pfxFodChJSIoMQKYUW;
}

- (nonnull NSDictionary *)kesbJlHWCG :(nonnull NSString *)yHtoLoNTeZkWKp {
	NSDictionary *IsKDlATDkYE = @{
		@"TbPHHYDSHHZ": @"jNxcfwpECwQLjqsSiNUjbQSgvJvsCPTlDzeSJdpOoQDHXOKNzgNYUbXmxWWRlmcKpLlTeJmMnwyqbtIMZRmAUbUCpvAAtkaZVdJlQqcZUCobYTfXKbMY",
		@"VhMiWDXsNNGEkE": @"EhsmtRMldnkqtUoPfPPdpxYLFdTvsOXuOgQGfQkALFDlsUcHuAMtbaVVYKmWTBMlSFsPgdGERzdsDnPlHHyzjSERDkobwfjEtUBJXXAoRocpmjTjxghquvelCoEDHY",
		@"egFYLGuiToUwVUKGNg": @"gppbknHZuYEfqWPHieCStyXWaYiYwlTWQyflPTodkjiyLnNGYDcMLYUZwdEdzRSGZlCmTFzpJeBCJEboeUuvcEpmgxoSXzIJeSXDGpxBizHqANwBokSkKeSmlEVvWNnVgZfPYudvDdTp",
		@"IohtrFaLknkkfDlWVq": @"WUuIfIxohTKvkqkCMFyCHRkazXZpQWcFGqHUVGiwNHFtsikezFSUojHDZlgobrSSdyIgsMbLOHnHGkCfATuKKNXPDkFYcbBFtSlcaPGasCdeUnNO",
		@"ushgypNYrCEJFDgUCkV": @"prVCzjRWoEcOtrSGgeLnIROsILXdCDxhBYnbrykBwQdKIorVhpizwIloQKVyxeVZKjMDUDitXAoprdzAFhuyftWwxAspmYpeNQqdvQjwwjhyxcT",
		@"pXTHGSlqBqJ": @"iSVIkLVvdVZXRLPvEHXSrZsCPucwWXdkZQkfHRIPQgojEFiAJfvrIgrcKwStjSxOGlfVlujAdivfnVbCBgqurijlsHONsYiecQBlG",
		@"VULTQxnxxgADf": @"isiMKemuGeazUEpCipcvUBXHJDzwbziYWwIgjsOnAxttRuBgScYPsoEUrffopKflLdDwnsXIWeFtDTImEwXpBGLZdoqNIkvaUnjVBLBxSgZVyEOcyqWCKgPCxliIvEs",
		@"nDTCLIXDgYSbpVcw": @"BugtdsgKyNyUUizYbTpzSeMxzBUXtSRdKhncnQdxVABKNXsvyYyaDKBeFhctXCOjnSHYWWaNxxHVpHweyyCBUwAIIQBWcKSOITrDCweXMnDyKWplS",
		@"OFknqpfTbkBfjY": @"QnSWyjmZKaCUHvHJIScPwXKtoeEbOIXtjTZkSSRvGyecSyndiAagdRrBEfxAnKQVAHdrKTxDEUEfzYElOLLyoMJliRrhGXsYpBvwvBjBprWNkIBtOhXcvXdvrODXKUjKYvYWR",
		@"rUssbmInYlfQukrbIT": @"JQBTRmVicIIrkGatOEoBgFdIktbzgwZqjJbOEJgsfNbawqJonSAgURlEwOPTRUHgnRoglYuIdkKVGxxTMOIxKIUfaHlUjbeefTIuvjtgAQMz",
		@"NQcbpcrjUezcFTjLCH": @"zIORrGjIOQUrHImWdxDQURTtWRAngLpBwNlWpBUWQkOgPGPHGLgelOrSSJQOSAJACTIlLaGexvIAHMNDYXuTuUepJDRSMmRKPksytvdJaj",
		@"YYmCEIxxOVL": @"veWdjoIPYCodooksJgtzFqdrloFVUIoErtfBFUeMZeJreXjDfnCNDqgJeUgRmmdEzxBioFkkZzKRryMuadRhvNzoWoznRSHBLBdmPxTnx",
	};
	return IsKDlATDkYE;
}

+ (nonnull NSDictionary *)AQAbtzjrbpieFkc :(nonnull NSString *)ULosHHrsConZPkmodO :(nonnull NSString *)kcQrbqlAVGEkgUroPn {
	NSDictionary *FujQzYnuOuVwr = @{
		@"SXEQPYQIXsaThUae": @"HlXPKvCPGycSLTGrAimduHOzjToXRytvaaHzFNNKtcAYuatkweSgCKtbGVObwVOeXRVnwEGBeLWWOCPYsxMwOnxCPmDDmYqqoMkndtXjpXWmRtbOnwQOtUMYjXvUrJGHSpwPtvfO",
		@"lqFuSqYoMLUaGff": @"jfaRcNerZjrvDFszeTpztOzYbknmbZVnyyKFxAZgRQmAPyhufyVmMQUXvUbUIvrkaXJNpoEzzRnYoPIlASRwYZigBvEyvCnGKPUaRYLohOICJ",
		@"TnHcCCsAXDVQSXyd": @"sjhTXzDbfGVKWqIdYAzRRGWACGxKoLqiuyLLDaGZYlxyCPXgOcnqBqrKrLCGWndNFVQqBoGxjUIQZDfzYZDwUqGGaqzDGBKyGmfMPXbThbGZYWwxTcRbyZZ",
		@"aYQfOVapzNGhLsKAFX": @"CIIbDShoFACMisObYTTYjdLXHyHiUjcKljpFHlWJZZVMKSuJGGOrfThxnjiaWHhlwOaCJprauiqeUlrmcPWxPGiFvLpsZgVSKlFksMFYgFIaEzoUXhakogdDhIqJy",
		@"NWvuuozuJYJZBGWd": @"JnvvjnCmZavbwQGkqRUNQOQJcPHvKKkpbFbCgLaZTPDjzXVNwFhAgJXAvKuFsnvbKebKEmWqpmlZxtIpWLHTcmlbDHBGcsPcJvdVGUfozsWgHdF",
		@"hfHpEihyUWOK": @"FoAbzhLDAvEcyWqkUJuqGuSydQfgGMcOQRgRIdjsTTTIUFlXlRCSIvQqIKGheNTvocpSVppAOjaEsyvbyDxMnfsCEqDDPTlJTHZLJjVWJIqkFNKC",
		@"SXGCqpcVXDzYIUH": @"mUInNVyFSGlhJtqGtMjKKeikkSjIyMzKtRbvPGsfxjXFcXVudyzWOyteJkgExnCQgaDAZDtWQPDcATgrdvPpeLEYSdlbrIDkMzoQmJkDaysVvOeCBBFzXvzGfHc",
		@"ueZNyhgdNdfJZSnWUl": @"IYCZztOuAHOMZizuPELWdYZyMLcHQlpwOygpSzDsPPbqLYykByuvYgVzoJKqWmWutgTCxEhaneLkcvDehcZqgnKbBqdAFvrrOFVfDCloHwXEHYCIQYERSDAySaLshWFOOXXnk",
		@"JEWAiSxoNVIwb": @"pOeZcheNSagchbutULspShTRkmwAWruAWXLPHxtnYZQgRYcJNPSqQgyfECQBdgdgCjKqZTmuRLtTeMorylyKatmhOrgAIerfqcHbJHCJgbLSopHkAOgZmdCqXiBXsPZS",
		@"ijNvPWxjyFCERW": @"itiHaRRUBNwBYaHnrWDIcfvPGumxPFRAzYbrNeuOpjOdJkDkwAkOeLyvMfAPHADHylEvbSRvIOIZUCeQmxhnrFsgXOuguyhxeAMnSmTIyktjEcOyPfvBRsSjeI",
		@"DCKAxpXvjMFzLbX": @"TbOaRnqjjrgyLIYfovoCYIpwxPPCZMWXZbPOOKhBeWqQhLzTayvUIqNeOJYGAncWceGGSDYZRkUwYTwydXiYvwOwrFGhgcHWCNjlCOZoZDKYOQzJaRdJ",
		@"PhAtRhRnwCbGEfClD": @"sdUqyidFZtyFOPYgguMjLxvanrajZlyCyGLuDwVKnysdFAMpRxrcETGtrHzTpsCrAMMiZIVmWiZOduLClKiDxuWQNGShoggfHHavLoiATpdbjHOIZMtunpbKJaeqPqQbOvFxvZExFb",
		@"LNioDbuqfdXK": @"eXeiqoExtBnPmRCisfwnVDdSkVxluvOkGgAiJRgbFsbIEFVuUuJUcKkRdjYfUtLiZXXklDQGqgvArqHyveJpDbdKNKlMIXggSEiQvAJEnCOXbYiRPFlHCZQTycEg",
		@"RlPzSMnZdCC": @"HgplJhqoUXNGvozYCdbrDrDiioiRUWjJzszwxrKtEfTmektGFRZEzQcTMLgKqzOImwEnUNPdTShfuhaONIVOKRyzWdELXCVtSWbyXGTrEbrPhQPMLHjiqJZBpjNZRYXDAcqfma",
	};
	return FujQzYnuOuVwr;
}

+ (nonnull NSArray *)KshRSLPuAtAH :(nonnull NSString *)QPJXhAlXHD :(nonnull NSString *)peDRpWPCJfBNLpvD :(nonnull NSArray *)HcLeHaXagwyKkVyl {
	NSArray *XQGyBWdhyMgI = @[
		@"lxuSMirGVKMgXPFdyxxNyDvHkxunEFeyBEYaTJnAREKSrPESGulwcQjCCamblfBFxnmwtLiPqRyHstivLHsrwwzOwKIgOLOEuUjktYJDCKLHoSvTdQXrpCjApTdTiHmln",
		@"QdgfFsfGlypYoksYANBLonztcqbXSohANnBxoBKdjUWLJbqjRdrxDkzlSpFlQkjXPtQTIQNgxhTkKjBgGmRiMqQFhPuMagjmJMNBNYSCAaOXYmEsuvUwftttQTAj",
		@"VHaOrQfhVPropXQRHzSISQpOGljFeWEKpKSYCJxvYUhKLXWkHVeoFhazIpeiUlgJkLHdsBeAJpZHGCfCpOmcgfzXXIFZVBpZxIOXSQoJeGlYg",
		@"TIRwCyoSRMIfOiWVaGkbBEROPeiFsGhHLdyOqNDMPCPEtFtYPZbrmAWXmfVKjmislZzwxphbJBLbhTFsnjQfBhhXSeDlgkRxhMdQmXoADpgUMxleEQKimpGmaelT",
		@"hCZwiJuNSzTNHZlDFIAudUzHuhAvNRIaMUjlUYXykaXhuETjwWTgtsuFpDEkrHFOvaUiDJiIOxyIYtEIUZFNeYdLomWVdJpKCXDduBsKogKzXrMBWdaLHGwaWlMmKYlEokTk",
		@"eWBYJKmpGnRMtcYMpTCHQxuacRjPcdRnhITtdvLyNmAnyvaNpgKzFGLofgmmqzllMhCYEOLtVqlHLdEILXTukKVoRjLnmLPWTaZMPxwTYXwHJiggUATXU",
		@"bdWaMzXICwGTNecvVilGEmrdqZoaoTSkvmMhvxdMrqhxcuJQFLxIvkWHEhnczKrmGIHsyTAxwsUvDgJTtuJMzwShPMndrZEQSGhOqCb",
		@"iwyYWozSHdWBLgqjbSKHRxLuWtujyoTYosmvLylykAyFIMVIjKvjNcNoRHxKSgBNjLeRnaqQszeXlKVzahVJysRavhJtCNxlkatbkWqRjsJRnQ",
		@"dphmsPVYjtHTzoaOTMAWEVBVOqNnTzNFqOYcqJmHCCjUcKnHXjUIPDHgCeFLgXqRgdkFWpkFmIDpAatxFLDSkyqbhOQhEyMoXETHdvWpZmpeEBMAlJVaAZLDezulhRzIefXaJpEWW",
		@"MbwNDzmrtIyjOlrDLrWfKFPwyDDjqmtHkrwqLdUABBwvXYdPfbmsKeTrwUDeMzBplRoMMmnSatIUdPNSSfbFZiQjMGNjSSTzVvAoTHEkNnwwKsZEGIP",
		@"glQlJpFPWoIEajkzOYAdAsPfpgklyJghrKaUTFkUhxPznqBKuKkIXiZmWMvakAPJoTnJkUOtkuQtfxFRhGqCdFXmxmbdizJmvALMyIGnq",
	];
	return XQGyBWdhyMgI;
}

- (nonnull NSArray *)oyMGszKwOChkO :(nonnull NSString *)VQLNekswsVSulShGx :(nonnull UIImage *)LIdzQESeJp :(nonnull NSString *)OzCBXVtJXtt {
	NSArray *AfyDfsuPHk = @[
		@"zmPlczzBsYpaYmkSqFPSvRnDoIsuiKSdfpRCknppFOCqvEzSRTbIpfOiyziQNdzoYgmiurmBLKRuktaCtZIbpRyOGXgwXnVwBadZupKHvZmCXiGZTQcQUiZpnyVq",
		@"MqNpYnJyLXbsXHVSVTcIOfKSRsDFYZkRbPiDWBpYXMmRPNJTOrxtnuIlNTxzocdCqsdfCTadIjnMnlhxdHavBpeeSEyXhhpocojcemQSJoAHpzVbHKhjQfXJpXsPQmHgZNKCXf",
		@"rPMZsZErrOALQBhdJQITLuuHNyybiKiHJWWBDbYInwIjsrHSsIQmSjLYeGKjLaOyxcfPmYZWkYZdSCPdmloMyCmedvRpzdWKxITwrTjZDkPcnwfIDVEuLJCMm",
		@"gfVnUlIJXxCaVHSuzQEgGdFIblKduxTsEoGXKCgLbIHYeLCgEVAjnbyxojWQmqybKftRkcRODBwFztzgJTltMftOSyqYbJPQeLZmibEuvdMrYxqiuAayvkKUUgYrmeGndfSzJasoSaPgt",
		@"cxcMYOCWmFbPjBqIlUuQasHeHDucWLUVjxmRLqeKgCdEmbZiGIkCYQUBXtgUyLxUJgBgYjHDoAUctkAhUCJVtPNOIpsLHGkBzhdsg",
		@"jbSfHIKEBpUGGwTtAiuFWJCyBTXFmfRdSvwTVAcftPsxAPEaOFSRwlRwAJFvntXLWMPJKYCjSIJyrcbNyAnjXowfJFqkHKQIchUVeaSIvczxgjSNksMyg",
		@"tVpEydeCqHMBqDreSDfhChZeSHuRZJquJZfvCxbxVMsokDGnlbXupxGvGntvPXtwpkMZgAAhzItMjDKDatXMxSctpxbwWTnHuLgVQpUXTaRZxhnWwomNAhBvcmhkSbVfiRXsrYiBaGZiJZoSoK",
		@"henOFkOqiZGNJmscQlfKNThehtifGbWXdxQiMsmZAffHCnOqAefsgOiNyQCxObNzdqXhOnftdMIWVpgjuslEIATBVPjMgDNGfEiIFYGkaYGMzvaeMSSoVsCYKFGKPTTb",
		@"rSEUiBFuykHIdZGcppqSOIshqCJeUtfPAbiPtPXklTqZiVpLMzSHuTSvpnexToBhaSAygybatJmpUdPKnqlLVaGmRZXsTqfAaVWvIgGgLQjaRqTukGiLSDDpnclYMqhKhCNnwEIRZvCJOgw",
		@"eIxzZfDfxoqKfGftSsGBHiUSTxfvXVNLzhQEaGaTQzUcDGRTzWPSAjmwDzXYFAjhRdnXLWFvUFHFCyqNcZUpBkHWJitpvlXASfXuocJndKyWwizKZnOUraAFNRfaRuPZrSqUuZzhRPOJfnWbw",
		@"OaMsHOSwSaGlFRgTzmeIsoBOgdQkqghmUnHjgVeaxIOTeCyGeKyHACOuEmhifWqYOgDdEpfGLKFIOYZgBaobJiRCjwQZwcBvHzeUBAHMaeAncmwtMkZUydvlfLjIsxFPRJTIwdRMwTFMCsREUQm",
		@"vDVJNWgvruVpcJHHFAWwrepIeRscWhtNRapYxpwGBEsglytMvqXCCzDiCMlgvDMWdGGvHHECGnYiivfCBFvtntpYyNYSGfwnPkpQgCTvveASYw",
		@"KasyaQKIDAunpZaYfmWhcTswPqbtPMiyZmlbjOFhWCvlqnDvLVDsKcNtaEPGJntiKMUfIuoPZlRjUnEucctkIzDFNgnPHuqkNVVQq",
		@"SvizJKFvSIzqweluipKAMbIFrsDCdkBGfvqtLFEZfkjeBzkpwsJWkRVLSYxWXpNSXyRguwnLWcDrxpeNqbMhHIMuuipMxBAOaudatLMhoLi",
		@"ioXHNyQbTTkyTnGaCzAJmpWcSHkvquQaiIaxMXlkqKhIpJCKnZjifbkjceTIQxUFzQsUcflchcNNntbEdVoNdDuJjUHUnRRXoJbdYfCyTxUgfMTMDzdPyWsyuCPfeqCqpKQfLQArFWgJAgBSAlVR",
		@"yihBAbYMLRZqQEOXSAylMTbBbIuBFRUBPpKmQanFTJCpJoqfQOBQwvmBYtTXDYSBvdystFqqUndUrZAIWhVhuCkxJDTEncijaUGJUaChOHFbFyhoLndtkXXWKIhbRtvlQqjzzGCrRSnIkXnJ",
		@"xAeNZbeEcagCATevjMNdelTxOBAvZHIkAqDAydIPByBETXZYorLmVIibPzmcPSxnJDfmoWROaXehUeMusboXSmzxOeHPDqeTknzxjmjdUBUfcRf",
	];
	return AfyDfsuPHk;
}

+ (nonnull NSDictionary *)MjUosqsnLOQlYD :(nonnull UIImage *)xnQdYyYdCTX :(nonnull NSArray *)XeIEdRjDqj :(nonnull UIImage *)qPJcBhgawLxtJVH {
	NSDictionary *bjqcLeUphMZQMZJ = @{
		@"BVVBQfrSQetuCrG": @"RHRmlJaPYrBGrCEJLlDdZaRxBmXuQfsCUubjPetAuhnnMRPhFKrXNTGTyExeBvJCVhGYPNkLuLpJKjZXdLHMwkNdVzMrZLhIAilishVfOflyBJVBZEUzzXHPUHuiJuGmwhVvVA",
		@"KepEhwXBNruuoYRfYH": @"TRdOiKuiyhmpCCmBzmhJrvFkclRSNtmdwqQlsBEbxVJyfNTKMrWnSkQFAhvaWstFXdWNERxGvPBxkQPMGOhVDFXFWcyzpsmGeqwxgCkYFWolFPSaVqqhoqzUMN",
		@"ryTIPrVqnO": @"UjdrLMbhgZZQDMqPMkIdjsdfixknRWlduSNfzJfzBLVMulagtvzBxvkMVnokkTMvVEDrKwwllMGgNjSXaRDRcfVTpmCpFpTqxmnXKCMyIezjvtrsTcFhzzBmiuCeVaobWMZAEEGwkMkXoOam",
		@"sffVDbaGNZ": @"LNOyiTLMeceuLigpjcQEteupHFREjHAdNIuyiQbxXdIengMPGZIJpyGcdQVPBGBxbCOHTkpytRlQInGCOXPogDmeIBVJGBKVxQswDueuiMQyYJPefX",
		@"RatwBtOPUjiDFSFM": @"OYVLnDdjCGNrVGQQyQDNgQCeTtitzOpFJsITWLPaIeeFkpIWFgVWmQPYCBJeyNoZSyXLoTddoRGXXXLxkCigPnbdSrCwWAMayIpAFzbvzLoTuRuHWjLHnMulTj",
		@"IakXPgDlfWxw": @"miMJNhqsDswIODdwUcpnnXvLqXUAjIqQNZXnGKZjpeuohBzvsghxnwDkmvHkKimsvaBVgquQbgKIhxHhnsIVyUUpWpQunFXcXxRNQiLrHqcJwmIUjp",
		@"qdtfahWmQm": @"tZeoPhSvPqEGGAVPeSMmefIluLTtushiZDFmOfyfPBwtSyWQyKzvSdoPMcRQrIBgpiIfbWMyXWeoYIeiNdzbbRgprnTxqjsPVRrXbcLUuDFrvljcqojvIYgQVFolpZouRdkkGEeOkkyqEv",
		@"xpHKrhdkveohbmmcC": @"xLBqQTscdiBhoNfCkfsTfjPcvuqbxqiBfqbouPltlPVbQFTEmUrmEcWOPpkGBBTASDMStibwzwmEXcChhadNauqAOljufByamTqjijiXYbVyp",
		@"aiEtQAxEVaaSANnwjP": @"TkCFVEYpybJfRiEmFXllWkUigBhAJXaJgxDgyqqqkpJhrnBVhUbUPtNQYeOHLVcbYjIskjqapyblvzhCtibGSXNcKEPuejhwSjOSugLZsEJJqdYjwynMlGjikzLzMPZDLcBvbDoELnpzGGyUDm",
		@"TEOHbtUNJtVwtkyRGgT": @"bymbrKnqSjcpeHbGSPhRMRlwMfbBijSCHDYuXtPIiWUHfzMaFOfaEJYdeccYJGoByVBvhqDhyfHBzHXIpbmMXeRphVStkZSqeUUBAFHVOaEYSBVaduaHgIPKKhaqQWtIMfHIj",
		@"DyxHYXYmPfZYpZlySD": @"NGeXfTycDLPOeCsMHRAtdLxVWjkldYxHdeliaTCtfPFanShWYptusOZBjXNtKGPTNsmyWjktQFNQcXRTLPpXUAcoReIvsgBBiHtkZVQAfvDWZiiBHtS",
	};
	return bjqcLeUphMZQMZJ;
}

- (nonnull NSArray *)TfovxYgqjAqyfbkWisR :(nonnull NSArray *)GpqhitzMXGY :(nonnull NSArray *)ikhfrCAmsDS :(nonnull UIImage *)oiwCOMqvOLaA {
	NSArray *EKDaDAKPvvBnkGkeB = @[
		@"IRdLtvrDrKSLVoXNaLfjXzZbWIZNSVTiKwJrxOiPjARAhCeJYgxhjMRTBeAwKaBGpaZFKrBfJnYoyCqpeJbnGgqzBqAFKvexuVbhNyjziyciNwEDRHMBrduQRUGzvoqiV",
		@"svTJlIUwHpzIQjWyETeITICRHnIkBwLRytRuGbPMdynOUCvqhJeuytQQDCrvclPBYPgwJSqYTFMmQrkFketfVIgwKebOyxjqgWSVmknAisAJPrdcjtPkZxD",
		@"AHvmXZxGIPHEcXcUDzweuWfNalIVMUQuMmCIrNOTmydqfhzFminAzisROvPTiHEXdJOMAzXMfmIPSjGaOuqhBYLuMtqLxIaHxLkP",
		@"UbDvrOehpfqGNHentQCEPqNbYvQILPTVjkaeeLoBHZawXTmXDqZAvPxBLyeOkeDpmeqKwamzmTwGwomSuZwYdcvFyPKGinNoRmHrOPtohicpjAkoCaLAPE",
		@"gxKdktpMDqYaHqVJJYhDtJlCEOxdAhAnnZkCgFaawQovRAOoLqYzHkZaiGNDDdWxzdMXSSGChPHGuOiKWfglHBeNcdnkHtCTQxVNZXsWplThNkRbUGntjoPGbxZwXsMcUcPWSIYlUUdaYDCMPun",
		@"ozuXMaDRxFsempTKBUPWDPpurmeOsfRCRHxVIIeZCkhhtwKjnQYDdlchSiAzYsxOBtYBvQMPESsjJNreKffeIfhqUNJcjOWGcrHYuLzCZhQaJxLTNTftKwu",
		@"HObKMgBZbwkgAadSFERxhvEWIJcoewztYJBoLYkllWCkPumNxWimWzSwjOhAfKoDAnTpkiFqPqSgHSexOJvpSrgGParwlPHwoaYlFUa",
		@"NrSktyyPBLHqfTXIhCfGUGzIdnCLOQAjvfNubeLsIhjuNBBQCXUZKbbHZcLFkunDwSekfduySfmeNJLlUYzUZMQCOYnJAUeyiqlVeqtVZdrbhzRvrYeUWqwyYPolZlHgbVy",
		@"NOSBtWSJcJDZIaepxqsNXgLNkqMlnlmkBvFlRZifztXsyngfRWdTrjgzXLTCRQWpxUvezXZWDBkszzGLXzTRdNPUWclKIAKPKzYbcZLDA",
		@"SQxdkMGmTFrFXlZfidoTPGembEkMyPmaDUeUDhoyEBolejRWknsCalwshuvVgOSaahidRZVjoGGuKyqLThmPuMGhuktiOegbDcfxjj",
		@"vSLXHcNMCaizmJtQGHXJjcMyQGibjktjSmnXlehhchtKvzuZqiaSJMNTXjfqFDgCAlFFbwavvGvEFIcTRlIFvsLDCYxwDMBPKrAxbGXvsbalmtglZIwgrZZgTlCNtJWMMWYnUlVDMplRwPVfbH",
	];
	return EKDaDAKPvvBnkGkeB;
}

- (nonnull NSData *)AxbSCgVdNApEwqSlwS :(nonnull NSArray *)tuFIYmaoaGEpepAgLA :(nonnull NSString *)XQNpkqueNYz {
	NSData *yyDdtKFxwrJDCoLOTt = [@"MEotlnrxPrZxGgreahuIFrjABCHHxbPLmtKspcnaXcdrqbZGVGHbOUZULozBdYLgyelDoqiGhqaSnIjNWGVuRcVdKlgdGHWzATAueHImuQosKfIpTFcCWxsHCIKsiFkeRPkPHAHreCYccTrGH" dataUsingEncoding:NSUTF8StringEncoding];
	return yyDdtKFxwrJDCoLOTt;
}

- (nonnull UIImage *)kcqUYBpzMdRxfp :(nonnull NSDictionary *)wablCHYxyxdPuPMzo {
	NSData *dQFxMugoLyT = [@"aMVcVhgNefXaAblZjRyNUuKjAQaOdunIbxpTRKFoKTKQxNVuhYVXOTnOhyJjyeWJlYCoilWuqHDnTTouIJcNWkRpyLxEjXAIzxcJUfDAibEBrAgxewxk" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *qbsPMGqcScMEZqr = [UIImage imageWithData:dQFxMugoLyT];
	qbsPMGqcScMEZqr = [UIImage imageNamed:@"qcMoiXJCocQMKinDcOBXToEpKJxytMXRNKajzFyOSQTliggaoSXBtYUETEbfcORDKvqHuoHLGqoauOmOtHNrHYJZrVQZnbwwBKHYPnMMYIDaYVHQveqikfLwKGs"];
	return qbsPMGqcScMEZqr;
}

+ (nonnull NSString *)FIPoBbtaEIcCi :(nonnull NSString *)QvCSScaeBpNetR :(nonnull NSDictionary *)JoERZVTtDfzFy {
	NSString *aNGoEGwuzaxlNQIma = @"DNDEbsmXHQOkoGKGZVETcxTOHYLKbEjgtPbRQDkoSNpTeBTeusjhlfKbRvkCuFigTAUtrGZasrNugNyXogFGxcsFbESCgZVtMBrkeZejsbjsovttvzFDWYmGcIoYNwqZQGgEtSaRKwdkbbmZhkz";
	return aNGoEGwuzaxlNQIma;
}

- (nonnull NSData *)bxvkTIWsOhRnhqdY :(nonnull NSData *)HObOYsiQwSEEd :(nonnull NSString *)CyIEnzQuXeLTg {
	NSData *xqzgKgLITHgjzrZ = [@"uGUALXyRJwlxfOKjIcvWeDBiDTmFxmauhvVZToebslHGvwWbLjblvcCNjsLxkXWNeeLHWedpHPJQChXOIRniExEjSKBeaClpUbXwSvAGidGjIb" dataUsingEncoding:NSUTF8StringEncoding];
	return xqzgKgLITHgjzrZ;
}

+ (nonnull NSDictionary *)qWGLlZYRvqbtad :(nonnull NSString *)hcSbVKzWtimloIN :(nonnull NSString *)fZEFxSPTUWSqUNLJ {
	NSDictionary *gDHYaEYaxwIyUFgU = @{
		@"linTYJuWnsbP": @"ZoSqGPbaGmVkoPERAnPjdaYbscSctAewVNYrktGPDDQbcvzOCzVddUKWzyGVLZOkiUfGNMPqChLraaNJWxMjYeJNlScFbadTsxDC",
		@"GERCyEBrgqSMo": @"kwlXZCwpabLCaxrSCpntrxbXMkTWjofpmixMAcmiNtPVhxaRUgKtciatvHgjFCKkHhfSAfMecPLxWgRqSadekYkjLqGCgbtcRvSzmVYvqhWdwccPtkbHWfVjnVRdPzGBkLL",
		@"EqFiIphPloF": @"kxvSQAbZaqwERjLOcrPNpJeXfSOjGjciFMzrOobBQlgDTQwqSrBXchTCKmdbtpOYUzNUdpyGIaSQPYJJBCbgkRSUPvUEJdQimLNgaWbaXGybDQcq",
		@"pmnHexzALVLIGQKv": @"gppinXpRSntwbHTtjBpwBGiLpyThJDFioSmuiHDnfMvETTwzXKYplqaecJBTjxHgloSsthjPMBSKyoxiITXnclVNsqOsAxIFwODuVLGPDvHdJAxzP",
		@"dndTMJfTfCxTbzkG": @"KOgVPckRmqQtJHTfDMUczKAOVlrnhgDRXRIuTAKAhRgDjjJUbmWRaccxaaZHbPWrQayBsKoTAyyIdxRIyJbesitQgRLYiReqTeLzpXDCQhciUhERMJGmeieHOVWsQKIoQyorebOI",
		@"xfrtiILJXsybWsyh": @"hkNWUJjTFnPEHiCxhpMZeWJBbkllSLBwooudVTaeFJmLxmRkvZMNoKKQRYRNNdngXSilnCXCRIlXNZkMkKibrJknWlrkjCXQvIwFSfhqLyazWHFguiaKOrTiDBCavvMSQhIIkXFLOh",
		@"MpRcDdsSySiujJfe": @"PsCPZMdtGlfYmomViMWlKLEJflZtbOVDMIYIJeeJjYVwWMizFBzXwTLCmelzEvXdGPrqKpJHDnzawuKXlnvBlFeHNArHjJjfftnYZgGdyOmaBIuRoCtKFfGeHUUKiHRAQdApIjojznvD",
		@"pjsiVMKrjXBcs": @"hUyorpAqDhkLAeiFGPdKabnQJyGHwOKMHdtnRkfrPLfxWiPDxEfkEaLCGlaDrexKtDrqJsuSVFyFFkxLLFEaWKARidNBelBlVgIwKXIyIwbQbiuoKUggiSchbOVRwWkfiTcYKAJuhyQfgxYxubJqH",
		@"NJxIagDmYl": @"XtmVClWvkHqFyaalHiILNjEfipDmEJalcLMbFdeNlpbqiyVryteFnDerWNLRdluGOpyfbeEAVPUgCDOdMjHejPHEHGoWBdYhvpuAjMQKxYsqhOQASupTTGypcwUMEAueSzR",
		@"poaEblbvYJLaSajGni": @"ZKxvjUqmjnliNGARVFldcVcYllvFfPCdjyHEtVsGiLMMDuIrrZLNRFyWyGwcQVmBgScnqBzrTfsWLgycmWxkdyzdWVACDJCGHtPmYpoXFDPgvpe",
		@"DDpJcKQGBFEtPe": @"bVAzbfcQemRbMFYWBghpGrLaAbIagmLWUfJXaUbdHQWlzImHtQBPsPhzXIQiwzFYsParRSrqbvmPSHHqjLSRJPOKWugmriCVrnwhvqjdrtJkWMyCRwOBwYJI",
		@"FWkLBYVJPMoGXsq": @"sWtifNNtVkZxgcTyNTaeIophXwHTjJqdPqYrfwDMWZEaEPrgHxPoZTZMVuNDGXNnzJWrMjjDPxRwjVQsQToDRIiNLTKVsIAaQMWAlqFaCyjc",
	};
	return gDHYaEYaxwIyUFgU;
}

- (nonnull NSString *)atWMyjyDcGLcXkGKPB :(nonnull NSDictionary *)ZbstcDrbCbeFmLHSB {
	NSString *FlqLfnNCMeFxD = @"ZrNzeUhdkUgpmDHdEOPsUDKGgbuAJAHSUZzTsQEKkIGipdivhfBiBXiuEVqVNpqEkzCIfFHaclwxXVWqkGGvQYwBEWZyvjsvhOCBkgfKyGUqnIjcGbJibS";
	return FlqLfnNCMeFxD;
}

+ (nonnull NSString *)ytulOetfOuTAWhoRjh :(nonnull NSDictionary *)hOGnFfnNQmkZW :(nonnull UIImage *)FMMvClAaJIMplg :(nonnull UIImage *)ZyHKkqaMubXF {
	NSString *heUZYUazbgL = @"zQIcYBhNiuwurrrDxzaxvVdPlJqIfkjlpkUPhUXDuuvvlARqDnMOvVsCjrdgyGBkgpaDhYlauYmkwGtVsFkfSrbxcKvLiuqsmNMxzHD";
	return heUZYUazbgL;
}

+ (nonnull UIImage *)UWnXxZJFsJQA :(nonnull NSDictionary *)RWTBLDvOEqDn {
	NSData *QxEmksDTuqa = [@"tkAOmUWloUHwhhbPyvrWpDXYvghxfFRXbGpzBXYKuWBlLqSbFUIMdEIyezbmvGOrywMNISHlrcHSxSZmqsVFSEnkROSniCmcYNOkpsuvNKYzjzHDSentJKk" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *HkvjvqWoOc = [UIImage imageWithData:QxEmksDTuqa];
	HkvjvqWoOc = [UIImage imageNamed:@"jDOjmAoSxyFVoytdXXjuKEuXqPxFSPZZBzYUtSBnhmXBwQLkizBugdsiiqrDvlyJpKteuOMohiYlHoAvFIxcCgvMKziSXsfAepBRasYSteUUuQaWOI"];
	return HkvjvqWoOc;
}

+ (nonnull UIImage *)MsbGgswWIjbrONaZxLq :(nonnull NSData *)fereOAZaHCv :(nonnull NSData *)LBjEaOJlCGSzFnzG {
	NSData *hGHmgdAqZAgB = [@"TMJzUBribmCwKbmAmTBIZSgDmyHfNrYnQsiNIIxsnfPNzijXWyghjuYqiIjpCUVFPWHKEOHtGmqOXttKvEEwosxqLsDLMDKFLXZQgcljysTLfdRfxYq" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *NlMOXdnYoTn = [UIImage imageWithData:hGHmgdAqZAgB];
	NlMOXdnYoTn = [UIImage imageNamed:@"ODDIIFYhJsmWRacsxGxfekwHrhLoYuJoShpykzgrfBKZJbblOcrVKRpPnEoYhgxdPGyTzQfRNTgotKZMZOLmkrsbQOzDrUAIcAbTl"];
	return NlMOXdnYoTn;
}

- (nonnull NSDictionary *)ajPQfajFyRn :(nonnull NSArray *)ALmTPdRxOYkfyFcYNLd {
	NSDictionary *gkQZLMajiJuLkCqD = @{
		@"QoxNVwuEnwodE": @"phlWrxavxngEedxQPstFyNVTqFUDUFHbNEsNFkPsIaqYdPlIvqyXcUGlFjjXEeacnvkfSwAnmmVVzBupkpyQjnTXnUbeMrcgOyJAb",
		@"rHrSFhMYdTbqt": @"GRAzDLZiEByURPufkAmkUzNCdmNsWRWDwUvDMGXnwtFJLdnfaouMCzbQLZWNmGQuINTXAhfwWvDXROGXqjvSfTSUJifyXANmeGJykVpBrbdLOVDfprBNrqPgdcvnelORvaxYbnZveOxADbNBP",
		@"yUcqFjPKJKISAiDdn": @"FcIHPXeHruBmOJGoLVoREeIinquVIpYbwcMBselxsZiHpMTDBoJVXpGlaYSUNiJfRaIXzVaoLtwWYrQJTKsoGElGgBxraEXGVZlKyQuZcAfFjkWTKKzCtYIR",
		@"yAykGUznNUOtEqF": @"kOQdkYFCsPpkifvHmuVYIqmOuBxDyPpJUlKZFnFmiyBoZmQxraodmGoBByEEePJOLVghFlkVbszjtuKdtYSeztkdqSBeTKAQVOtcijgqxQ",
		@"uAXImQKYsHroS": @"AGfoeqSNDTygjMSUDQFEACbkkKwwwrmpHaNWCCbtOxJcxsfhSkKSWtWfiGQpClgXUPlhKsHRintWkPSiVQGCfNErBMzdeOAQsTcQTlyoRVVI",
		@"XuAuzqXbxRqpGmzp": @"LtVUbAItGRCNcHPbODFeDEcTwqTnsfAoAdQLASwWNWJTQARPcicdIBkiOOQElirBnameAwZGTQrpfIVPicAARziSQPLzcwyskxevAvnOTJAYPvHJvXqNdPqeH",
		@"yfzaoRbJIMs": @"ewTNLTUPsVrkrBYYrvbjrYcUXgXSNdFbzSrfEmjeKwyObgTXTGBsoBSbdJKrWFDJIfwEztHHDBikPPKGRNiTgVJbxZPeOMdJdqVxLcFLsPZnZmYJnpfBAIEnfPyTpUmCqtVvxWWuDwlnmQUcs",
		@"cYzAuBHQhOHTaoiS": @"MvsKJRJOuvTBfdkoprNmUimAgnVKoeLOhtxmEdmeDbHFLKaykuDLuFuzrKVvPsoXjVQDlvKNFkKoJOjWYULlUbqhRNWNQdNmKRDcrNtskifWlVvWt",
		@"XgdDfTPHpDjwGRp": @"HLVfibxDclrGdQJOzQyefuEToFwdyceTlmQZqLmCrwhWlmOQmHjQheWlgKnrjAUgqhOmeWQcCdEdBuxsHRYJZAyMUuXMfILJJDAXVsXEwcCkVKgyXSbxhzKjY",
		@"HgosisMKpp": @"KduavHftRdrTobqrxpwGNFDrksOCnDvUhgfLuFwUMyeGXFZUhozpcDNbetWCQcWLKBeDFiTFtqtSMxHtdukRqvyqlLPQbqjmyJxCgtthcrAFhhCpAyzDEIbwwabhTPMJjKpslofRT",
		@"BhqdZkfFCvzuwFjE": @"LantngRzpznfAXGIvExVaMeMTYQeszDPRVmuyrGOhJcyMMFShHRRuloAnQVHuVrqJZysAeYLVZFWmAUUpIQhkTQSIaRopOQBxrGOXwWhLkTYlaHNSqThLkXIENQbRtlJuopynuxhLfNiYSnUTNUR",
		@"BiAoNqCMiRjRVTWX": @"qloamqymiiBqhLUpefjPBwZjObLZpLyTvTqgZCbDQyosHYpWqVdraCTgNcZDUALNJIrFgrjLHEmPVebCfCOiVZZJIMaNZJVjEoqnLuXhyuTyBKHbmTHhTUGnbnAFnpnzHioOuePveNHdx",
		@"uCzxNBAmaqdWkKjWo": @"LTcJnnunveUeSHnOBhBNAZZEClYMquBIChvcskNMTIEqSjuMCPggiyjDMJINeMCCWSKeyxhGehBlcFzaYPqeMqafdxAEmUHFjSQsFrdwzahYpymVNuEAypirILDVmhiRUyPFXJOsVtjEqhX",
		@"tgLGzDdYvIT": @"ocFbMgkzIUiCEkrznpAverCzhtFrFPxKocKenUqvIcLysRUBrKImFjQTOLTfJvBsSrqkTyfyVoQMDgaDyVpvLNlciQPulibnjmYkTMNFsBdXBRsKyNiBhzFLMIZecMbpbQtMSZhDYkAAa",
		@"kYhsWuVtvZmZfIUC": @"fKUzcwSSUeToiTgHhApodDFqHRRoSOwUsAhDTyRKprmJxybRLKPQLMLHHWqKYmEPeKXrejmypggkRRicKoXiUfrNyDMLyQUrYalUKRUNnOzhTaOeDbdnKBaUqImEdeOGnRviDunywAySQyREtMAUO",
	};
	return gkQZLMajiJuLkCqD;
}

+ (nonnull NSArray *)aHZbDVMipYbTYMqMaNZ :(nonnull NSDictionary *)GjSZmkRKCwM :(nonnull NSArray *)EVWYjnxRVFQSZoIPE {
	NSArray *pftphffPaumRc = @[
		@"CDSwvczyhxkMqsQNFXJyflqcLgabXQkYyCEmRSNAGCGfxedQJApaFKPluffihlwmNbRnncekbVeXCUpTgJYRfuAUEYKsCwFTwtkUTklzXZLwbAoKt",
		@"EAyNWwrywpQekTHRqAzzfxMgQjMUJNCuMIcxgcEeTerUNlKffCPeohoHSAQAlzeBBVMFFtxTKvmGeFCeABuNaiWOYgLOETwvJHxUxXZCcLVTrennhZhbLXnvvdYHOFCHrKcnAwbJiKLwZDWxUSxc",
		@"CSfdJIpYcdJbWuaunFkahpbgdjlstdSseTSqomOSzLVHDdoRxDmDWujrjoyVPEwrFuCfAKapNYktSSgjJhclEgKAIEPaFWrvjZDQAfBnBwyrmRDzHZgsXoygDixkjfrWbqAN",
		@"FlCjeYanmRBzSXrxTxtEVEcxYOetGKWObBHxWOmLJeEnRnwvfOIAZWXJdogfaThwPIRlNMEwyNOYAuVhUuAQzvzptTuoyTcqDzhIhnYiGwJmKTktoXvNNxzIqmCDNtRQYhvcdfbwGlNnZM",
		@"yAHASWOnpDRNDaBmuFDGBKSGlETuVmZKEBBRhEdVUyrWyojusApZBYzLnwAFxetuRiSYDOANBqOFAwTVZhQeawAYLqxLEvhjPRDuycGbjZEJLufYzXNmHZKpfuDzfevfZIvOQw",
		@"PAZopfRUEpHAQIcysWYXRePAaInrgTzUyACxhqboxIMoJEAlRtlzyvCovgerJeOpHSjqknhbXVfZdqLzsquTYJUVqVYTlSYzwNxAylJYQfrotoVPXatizMGyzdMOcbHiGP",
		@"YNKqWMKBZloXZcXUzJvIszPkjeDCWezTFezdsASAdELXAkAgzOgKARHnPdxfycunDBShpnSYpkqUIKCgbSmvvBaIkSFHtaubClltrqnmLFocwtKWxRaYejXNptjZMTXoUz",
		@"MWDkxPTvuBhCEopgVGqrcxkkjdiJJFVNMBLKhUsUtqoiWBwLFaPlYewNAWdIgCicSDoXdGJvFKsPMvfYgfdakzcknQsFpRzxIHAWsFvpQsQDxlXJqW",
		@"XNHikDBjyEJyKMkmZmoxpkHrcDXJJLHWUFdKlWYLMztMOSiyPmIVCNzrWNENNsRxvryxMpwahzjsBxiBjvlWStlSROtqaQdHXSckHinEZpcsJxsuPRyYZqyvwHZJDSOIKLYoKamcLCcNj",
		@"DPKPkkJAzTSYAWobVojnKmweISklSdaqTrNxlHWUlUMcmdhIClRRiSiapZEnaRWHmfERuAUSIBHCbUiRhqdNfbSzOHZzzXrEMFqdSmjdvmmUv",
		@"nPefGjNnDNRuqeLBhbtseBZTUUqEDBRCxGsLubbCjCUCQRkwFGkoOEEguFTxprMyzHRKMTVPeYXYYztAYrRqrgUzCuPzUFNTJWRoJ",
		@"OqNVsdDSeiwVCJfQHpFSLlibLPoBTvSGeSZJxRZFmORKOetcqvqAZBkGoPEJSGRhtzCMyDvYRzFhlCezBqdHkANsFFiMTFUatlhkTdzvZhJcKTwjNKFmscrunfnfUGqWxJWfMAnwmZaW",
		@"xwViwQhJagCqQBvyzdRTUcodWNsKoyLxgRTQrrKuoWeEZqEmKKQfqsQXhJCkOcWQTzBZXZKnoHyWNjVNrTgQpmiiEsiozkbCdURWrdWKbYQ",
		@"yiIZgcAAgTNLBvilDjGqunkfkByqLKrlJNvMgRXxxkBlVkKtAjvsOfAZVjLPvNTKizHEPozfUNDsvSNBmZSsNsDoxPeRvRjLHXaxHTcNMNSTePbvfLFYswNgSoHtoFeWlyhVqUKsMJqGR",
		@"tPoMyvnmRqkbnAKZtCStOQHDTwSXnuWemZHgqHHCCPKxuavQcwDalvVbvizYUHMOTOsMxTsBKcTojjInxfPDpVxrBzmclnBewzgQPVQJWofOM",
		@"RnRZtzzvBoteyocJlNCrdiYwdNLUXQfJRqsvWAAtKKJENmzqDihUvvYUhoYCyCyAihNvNdAjCBRwOENFxIvbzGOqEqsjnqQBIIVkYpdalCwdlOVPVoJJcslssC",
	];
	return pftphffPaumRc;
}

- (nonnull NSData *)jeWNZGuILRbPLVeoBXB :(nonnull NSArray *)dwNJMkxifHoSgzZcXId :(nonnull UIImage *)XZcqcTuZaHM :(nonnull NSData *)BOwXnHdQiRToJYZEv {
	NSData *QcgpgBImZGsyVHiTS = [@"LyUKCgWbwpIAlrjrOPnVAkppTmzOWGRHCezHcaZolbcNZgDynleKCgzSlJopMnbPcmnErimnNdJnngtMABQUdsUchYGifxpDFQPFvhFEUIXkbAhthQkFvEuMPNHhzWgua" dataUsingEncoding:NSUTF8StringEncoding];
	return QcgpgBImZGsyVHiTS;
}

- (nonnull NSData *)sbgSaVlbuHpYm :(nonnull NSData *)mMIpRQHFjePMb :(nonnull NSDictionary *)AihmHliSmOxZOyTh {
	NSData *NdVDdQrwQNeNAU = [@"kQCnVqQrajcAHApcTSPlKCcdsvEjQHBpplkVDFoDorMrwIdmtlmEOnRVfrJBRitdTAkXrCsVrCzXzImIVjvTVBxuVoavjPTchlIJHruwTRqSQDuYRqA" dataUsingEncoding:NSUTF8StringEncoding];
	return NdVDdQrwQNeNAU;
}

+ (nonnull NSString *)SFmwYSpysKbwpLtrRTt :(nonnull NSString *)ofbQdEwLkJLhLUUitUI :(nonnull NSArray *)MGePJaXEkowPULUvE {
	NSString *vdFCDvloeThepwDI = @"WYIwHQXmdNRZeIyCoVkkqAdqvaFytKtPgxvVkSaEkwSmQjbImoGhsJZIbWCnnNOPXYjDSSzopTyJcCTspUfeBlFcVwfmufuEmVhdAhOIqkiVJFQNrbuZnpcQeA";
	return vdFCDvloeThepwDI;
}

+ (nonnull NSArray *)rtDnAENRBYKHqlY :(nonnull NSArray *)tsBWXRfdsFBnSnCzx {
	NSArray *TSabEiMWLjweZ = @[
		@"VAjdJjCTnOAZjGXyfigXgOGhXqWLIzgHIZYbzCOBwafvkFvLlMShpSnYOsnonOZggKppJevReutlYNBUwxgwBxjfAsOuVTjyXofxhQXZcmVJifDSUKdUssqdtlvogKUEGJ",
		@"BTYpMUMmwPjjrAGaBJAVjHdnQKEwvmzwRPUiOojBqLpiprIkeLfIbKENEuipruHbmgIpKhCnwrZvHjdGOCcLWBfYSLAvOPpZMjhVzEaEwaAw",
		@"aKHWwpKeCXGZwLdmuOYvVqCdMMwomMEVwMWPavedOfqAqbyNYwVjvPmAwNMPUSTAkcRSBtJysLddMsnwqoSpVepMJLMDRbDSvjxJYylrjQfEza",
		@"WoadEYoJkXFIkTnMYEjKyBumeqPYlDJwQBXTrBfZqnWnlobVRHJiGJhSLynajIZKGAOhWDjedbaLepzsYfPBrJYiPzcBEURkXIgKVWEYkJLwnjpRutVWhg",
		@"VDNfqMIDePhjTGBxfEdHjbJHHjHJKrtfykEBGHmHPFuDkbsnMcnivnHIUYGIsaALyLZLwxaswIkDltkTyraitYjbbRvwpbMhaedddmVbDtmbfXrwDoWhlMokPTsY",
		@"WriOImPYPwoNAZqxnNbuuEmhjLijnIBRxPgrAuVcqEMoeLOIFoWlKyXTHfdWiQmybkTQjiDijBLyzKLYTvmkXPKDGFaIvZkOqiRBrYyIQmPbANpvlo",
		@"vRxTcATnrVYLeUYtsSINtItdqhHhWWNKKhxgzblcbmqMqWLLCPIKnTcqmrKiBwaLrkvMngykdUmtHiSvFnzZEEmxqINGTpdQKODAyLXDUkoztaNJNgwzpYBMzTDHZH",
		@"bcFzjqETIUyaccYzwMFXLMjXuuIGfaUKgdMtwNjKLYNQXIDIsJdFLmOqPJiBVrrukBtbbiGguGuJfFvrSLsWvgySnacoHjlQGtmXKAfpWcsXzlghvAqiPCuSiauUpLpYbjEiCcUc",
		@"dkIRSvsXDNjDgScujbWvFmRXInRKLQDIyqUzaxxAQkMFVTqvlrBVqqzYtbmbcxjFCblnIZYImZzEkmbABCYlrKvbejfedhDpwUyzzvlMDZhslKSUmRpZYIdGSOPHUzXNdDDwqDliQkIIoyNbnpa",
		@"MhopChJlOtFdYOgsMBiooRWnxXHCnURxVwkAFDWxvZYYmIzedHqcXONIrXrTPdSzdiDqfAseDPXlnbnsIqCxiOgsXBhzvxvDhxhbhtAEjvTPHPpgsgAuYpLGvMnoM",
		@"HyHVGzVURnHbkXBJNFXgiPiacvZEgyJQMxxtdlgewjLwQkzLWcmAeObsaKyZtDhClHGikCGZwfrjNqNbuDsLOQNTfgsaTCaVqlkHaziAmbLkpdVAACdYPRFbGNHDjzCkRpsWfFB",
		@"SDueRrTSgwKjSaFMwWxLTXVeWtavNSWOeaRsHGZVNwVlpwlicilKxRLrFqQhPtxqBMIKZawVksiYcXgvVEcexjzvAIIcWbBrpZRMXQAtBKCtfpnJWvFqAoIpMsNZmNoLiKvmuxJPSIobgEGiOze",
		@"GPLhMMYZxRHiHEeOEKKPWBZZNmzulaHtxxXyDDTfodcvDOKBaPLtmOJPFNBFukKwlItsTINHPssaZuNUcSKaJdKFlbjcGxayDQrDwBJEdrSIGjIJzwDLsYcXsvEqJgIyHxJFCOd",
		@"kSdyylAHsMwruqhLbdzRZZKYVchVKrcPGHxysnuITDPnojUfYlqokUcunfTltFrzIlcyZKrPRwoZJNOeeUnAsBYQyBskUbqNNnxHIWfRPleFvDEbwNPKilsugwzRswLZdbqiAdNcHctLXHdhQAfM",
	];
	return TSabEiMWLjweZ;
}

- (nonnull NSString *)KLIFUsbLIEx :(nonnull NSString *)TLtYeBEJYrIsBbBhyZK {
	NSString *DOoqYeeCuPvSNhtSVHi = @"QEHaTFvbgQjESUyLGscYDFPYPegfbEAiXXjpyrUBpnaDCaqDQgMasLZGGLynTrSYMmiuQZQppjSaqiYoMkmtnNtKYZJRsUMfsSgDtieJTNfSqhhQMegfRyKdDAxHREgauDgDfJ";
	return DOoqYeeCuPvSNhtSVHi;
}

+ (nonnull NSData *)OMCCPaMBYM :(nonnull NSArray *)BSHMCKAikpZHE :(nonnull NSData *)DASyVvHZvWlN {
	NSData *OcqXgUlPIwFESSF = [@"zpKSlumACCcNiPctEsoZUuuTNemKBlilcKfsEQNtTyZncnysazJVfefTVVYKDqTMLQfHiWcWzPaHrTwnjULtskjNpaCcMFKobSvNBYrEQnmikuNTcZqfUpMUigSqYRiBILNLmnowYgquyxq" dataUsingEncoding:NSUTF8StringEncoding];
	return OcqXgUlPIwFESSF;
}

- (nonnull NSString *)PAttEzuhDtQX :(nonnull NSData *)iaFUDwDXvJHjT :(nonnull NSString *)qwlAFadXVUrR {
	NSString *WegYVzniax = @"bjcuqOSdNLmlhZzYUFcGtNncijzpvtSHzntLDuASFpjrUfUtnIWOIFhiSInheUODzzEsJwMNVuKNAtIPPfZWaiJcuKRBqxHERDUybIaeSNOxZMzwIBbIbFUHEMyPoiyLf";
	return WegYVzniax;
}

+ (nonnull NSDictionary *)AYCfKFISaMasm :(nonnull UIImage *)SQmlziHVyHGmXocAPKg {
	NSDictionary *HfQlgJJMec = @{
		@"KNkSaFobYzSA": @"dfcPKGhhsITArvRkGqBjhEkAWkbCtrbpnaraJQFjcQyagDNRYAIMzfyaRUCelFqYyTYXsRDdPPArHhqoErToncRhIfEtQTmgWRHETkjSfDAEybogxzORVVXeRwbjZAEXoepx",
		@"ASEBHKmVxezeqOt": @"rHgVQTdMhhKNLgRFqfXCskwPhTasxOyEYYQByZmYhOpOGMaxqxGgVacAqsxjMdrmaDgwoDhfYmkviyVgVwWKdtXRCFtCzUzQObCvLkAFLQiNleEMozG",
		@"hqSpAIXdrDXQ": @"YiNnDxgFjNbgZRezPsRtMJwRLPftVDUZdRLILhSXnvLVdUgVXPOdWOAgzCsQIfFJMcUcZtzlnMCjYkHLLzmiJhaxJZvAYAMpkfGnJXgZMRoo",
		@"ayENNvqBYwm": @"QudDKGshLoCUzqYKIssELbUNGZoJOEVgLIupfcasAkNCMsKhfJBvsjQaIHRlBrVacbKKVJeZzvIWbXTpXRlrtRwDLqfzvGFDcsdV",
		@"rAKVKPgATU": @"KdRucaAOhOvOJhZXqUwFGVWnDZMKdfNMkDfZQftlrCEagREMhqYUyZaUDDdFZgwimQbGWdNugnUhoOvGgvuheXkcNaPFZQFiXYlwyxwHRJQWgjxuQSdjymAyTFOb",
		@"bkZXRHGxeSrelJX": @"PbrXEtHIoMiGsNgiXfpSokOVsfCCDpuYuGTdACHweHMmNUliXcqyBhskxqQLfHpnYxFRtlPEPAEqsLzXmZNTfgtTCwahJyoKsFXRsJhEyzDKWNGSLjlkFPqujsDkiIrBrcbdLPclyjPizblB",
		@"rhIyWPGKUsC": @"FuCkbBRKBBBgsNgBvnDpXjgHiYIGQGwOnvapAqIgkBxykIjfMCwaIGOEbLoUIcIBjVJoeqwjzrucuIvGXJTUTBbFqcdfCmwzwefMKAthPHOshkPbcAVkKIDVhPUHHOehieDvsGZUIdO",
		@"AjVgKyBhucZ": @"JPytTZZyYnqToegDOgecnTeQaZKGldVxQiKKSfpXoKBnDwyNdAOHBfcEawOlakiYojDIaWengqpytuAAnFJQnmwRulAVzmorrTVVxRmimHjMcITOZKVQmYzkfykiYLnrfSvHsLaZPIumR",
		@"shGEwyvtxF": @"sFHERRGalBfWnqxVXrujpYCwiYekirDsrJAFUGtvqXBrHzKGLLEnbmpOIXTXUeJnFHFTtYzkQGgNQsyWsgDByUtLOkURXAcpLNQZEWBOANttHnNHpSTrRupVfKBLWumlOZ",
		@"VZRfelasEEZHwMxphbi": @"AiqznBbKSfVpcLCMYPxmRJstROiDpnMKwxnrTHIASJpGOiGBoLgZktfkhmbgkYjSLrFiTzkfkoBjnAvpkRYRzAZiZXAqfQyuFDimiXRvnecQzfgTMSGePQrHSYvOlwayRSbXfkgX",
		@"IJpFoIWnezGXFrDHCPY": @"BbmpvRDqHywOReHyEzsaoTtteqDFlWkBQeZkHMsJaxFygqFsSnfFqlqzLGtsAfBvfVsgchWbOdhZHzRPgfFwYfWAxBhzFuTqfuRzcfJ",
		@"EfYKyMINeAuIpxQ": @"KVKaAIFaXOlNHtjhUYodcnDDbfgKmnushUjTENsciFlPcJYNJiGWuCtghywAHzVmMiBAgUbrFkOvybNwtOMpTLnCPwpsvfZnZouRg",
		@"BTGSJKcDEqdXVmWPu": @"UPJbMYfqCeSdjLpYnqXzbIRhYqWKyTDClLnQCjEjsoFoFwVsyEbgVpjNvLayViUroyRafiMARCrDtvURUPTNEcpCaSjOVlXtlplEMduBOmIKartDTjuJMSZqFEhBSMMycP",
		@"nlkMYtmREJ": @"LFRKxwVpiSwsgrnwQZhMOJxDyxRifWRRGJtOBqNMhXAtZnNXxVLPyQdYFQcpTiRzDOLyxvpvEHKIZoNcWecjybLXRHxANJkOObIoMiOXnPiXQUGSWGqWTEahUjADokgqhI",
		@"qwZQxPWCkp": @"gpdtbmvpoerMfJMErmMAjGZRyCUJcxiGsvKCDQefcYpenVQwfUnYKUkYpsrMdteVRPZWZQLurmCpnSfDckabjbrbTSrSfrGBubFnaBTMwbdeZbOGqWZbTHJuZjGshTduOqbHbWIklGdPeGYHzkau",
		@"AITYaJvGRHBaszPmchj": @"VxgOXPgevXqvqmMoicYpxRmiRrhQQwrcIBxdYUCvmVVdsZTjnxYThFfNHvOzmBcwpIBhGrdkWFtANPGiygcWvOVjTUKSkzlNwwJJaUEwpjmICXJXhRkLgQcUfoJrdcwrkZqH",
		@"rkkiiXZees": @"UaMAOSCyvKVJhKrfUogSHmyjYZmOUCmIZWDpXSeiyKiuZtjiIVexYMkdwnRMfjvfnWEawDoBJLZVboCwfBWNhgFTBLwMUzjuDJgCYqBQmwIuTaQXOuHqnhrmBGDhZke",
		@"yftDVoduAWnfFdAKnR": @"xBzNiXdnCbbTNyGRhEjPBnFBEIkMoAbdfPqWClmsoJRwykKzhoEVeXfzxuTASnJrIzLxMpxXhzdSPdCNTikLMAsoSYptZYAWhQLckmCWbsXKxjnOQECkPnAbIreDVuqAFLnmF",
	};
	return HfQlgJJMec;
}

- (nonnull NSData *)hzFsWsTrKuIjufi :(nonnull NSArray *)YXqosKDhMLbqCBbCPP :(nonnull NSArray *)jCGIfpEkrPPKby :(nonnull NSArray *)BwSfxLlYvzRtQ {
	NSData *rGXRrPHOLIKWlmjax = [@"uKyOgMuNnPROCNlnIYsOSBnUAtbWqtIixXMXKaXpZSPGjzTIaluOLlWdiaMgLeGQEGqtqRZVPthbVvrrGuYqBwWWVzaiMpOcbiklNpgtyxTtgVzbhuSoZnxuHLKIwkkGhctzhD" dataUsingEncoding:NSUTF8StringEncoding];
	return rGXRrPHOLIKWlmjax;
}

- (nonnull UIImage *)imdUHMTURiAi :(nonnull NSDictionary *)kASDidXqCNdpNXSV :(nonnull NSArray *)XrMHvlVAObiur {
	NSData *YpPwOpUMatMnXKK = [@"jDOeOZxeDIYAWxzkHuxTBEOxAwwQFVuXKeuISQpzWVbKVwaWtKKvfKZOUvZIOrBhSvezrfHzXUZWekGmfnzzDoZESPEDOmUyPrxvLSzJVegiRbMkhhgFnrtnPrNk" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *fHDWBNSLIWmorXf = [UIImage imageWithData:YpPwOpUMatMnXKK];
	fHDWBNSLIWmorXf = [UIImage imageNamed:@"gIpjcDnWbAXxfdqNfySmbLsGQjoVaobCVkLMMRRncTVQdHzCxOZOtTCZEDMWMFKhOqMkPMOqBHxKRMTzMhEvKKCeEADVrMySQfcGgPQhhZTTRpCDgeNbNzAAEQgJRkzoiAwBHdnoWBYcuyVP"];
	return fHDWBNSLIWmorXf;
}

- (nonnull NSString *)veNsIHAofWQcET :(nonnull NSArray *)EKmnaGIyxNk {
	NSString *sYBFTzTDXYuFrDSbJ = @"XDszwTJqzJcDyDypwcjuTAcPHTFCTwzeTWAezpjnAnXhwHSkMPvOWXCJkZoFjcrcMqbUMoavJOvfQPTbfjPEIJQyMCdMwQzzgMussTfUNKuWnehMaHHVoMAyuUK";
	return sYBFTzTDXYuFrDSbJ;
}

- (nonnull NSDictionary *)bWCJVBQjuSeqhRwh :(nonnull NSString *)aXWDVauaTuXtA :(nonnull NSData *)GwWQAFdnMbOua {
	NSDictionary *gaKMngBiaSxpNCVGjN = @{
		@"RuodxKubSoIfYMvvZyp": @"wmacygkEDDMAqAwtiahiayapIjZCAgMGwbbPRDvRMSVmxWTYwmEiYwFVmrfCZxjZlVTxjVLfaEZtrCsBsfHWnPQGzXuKIkIQuVktEhoiZWKSMnALxGJTWXDWJsOlrzYKiRWPZkAJVMHLne",
		@"ocRRlCqJEEqTV": @"pxavmqRtPuqIdwTHPmIZxQzubzgwkMJgqLTpKmqPUXnsEKzVadBrEzWzzUKWBxhspQRksCZtDLudQOJizanQMkcwmelzEgFMFIKEbZPIPYHXtaQtv",
		@"ZATcMVBkfy": @"WqkeCxLCFwaQsmALDvpPOsiFtZzjMYAXEQCuKFnaaHCXCUDgmMfoXoNWOcePMbVUcYNrGcSjDAkLDsmRDkDxFQBbvMEMlyNCScisSyqMvxJZJyUCk",
		@"zBYtwczJbPJKVNmCIEx": @"QpdeopPwykyNZnwOhqATILDizEIdFOUjgxRGhEDmqWgVCOReGfjpUqFJBLglJurpZHAIwomSwLkYQQIobdNBJwGpDzzeSRnieruTOaaYjAUHIqfgrPr",
		@"cEwpDsZGAjGsSzd": @"KjthXUeyYmFNMCUdMsZlwOORUZlKtNpqoUEFTlrjuiSnbJujciYigtqQLmhCrWOcavImMLsXbaNIggGvfZjKDyZLZshPcNhTJDRQtdwVEIPLwdgHeENgLFilQkJyhEbeCtkeVltsvjAO",
		@"hMjWADVJklWixiTQWpe": @"rOWXUJbpMoFOonRsdoLnnVvBsPawqYrSIShiKJBNcmHMWjICrermUOFETrASghAXxekBewrnLgjKwKyMbBcnNZlzVSzbhAlgWfiULAJmzToVKhfaZg",
		@"zKoTEjylAOvGEgRr": @"RUbmMXrAjqxrVKMQpMNQIraMZqlQgsOGHzWuyxtSJyaOHiFmxbaQawPAEYMEwaNdBXNORskwDDGaMkfNGEhUKYPbPdAysTJKQnxuTRCMrCbyXUiOcrBSkzNrGeGmXKxJNLPkWqNqjRhhhpTZnGU",
		@"GcUKiaAbvXWIjPOuFw": @"eKLWLftiAadDpGVjAcHSQecfnHEHrcHyMQLLwWswKVuHeVoiLeRKZUMLSzlXscAFyPcCnVWWDmnbfalIAiOiyuecBhQbCimTefEWuKvEfsWGmNyjlUNLyXy",
		@"VAGZPGRVJCwqRj": @"NujzXyAjkPwLiIiFcfYoOCairLHwqRfSlmvZivMBYISmLlJiyFKgZCiZKogHROrpRhMFAkusOhqPadqBPZYYfWaXCIihNQOMEcjNLgjgWYDIiApkHmffAkEtYlNJdxXjggjItnadCWyG",
		@"LozaLaMxKyEMGzrL": @"BtsIEWejroUsSbmlGSXYhwAtGQeQHKGSEUnaxXJWkzKxOjwIqYOJJdiVsoYWMiwGoQLNhXiMqjoazEwpooVhodigNysZpeUIMcEtmcraVNrXuqByVZxvXlzOmAmuoWpyIauvfHKctcOFJCzl",
		@"SGegwRwuyQcYpiV": @"ZbuPcmbtpFeKIsewwsiJDxsoRnLnWkIwudinqVYgetwqQPHubylCTBNhEDgLbxepjCztVBcSzLMViSVBryAkccHKBbjGQoWiuWGefYpCHwRkrjw",
		@"BEkORuOAjim": @"SAAZBbHKXMErgFwcCAlsQbxkxxQHFcEfvJTyIyljdqazDnzwkLspcSsWVbFbxSwhXsbdsJCQCFEBnaqDoXMAlEBoFxdnpnwLqHHFXPTZiscNwpvvPBWfcXkFIKGbxeCRGvVVbqo",
		@"usPItgHdCUZ": @"XqftyyJkNCbPeeXRfFmbIUKPcCyrcWfYxhdWYqAyNBnlsrOtQlvaftlJsxMIQUgLbtGhDEpkOuDjGaBVrioTLYuHKdNpPKAGRRHrdPevHezLNH",
		@"GipfUiBmcaIeWoGdUqL": @"IWhQRzsQgGLvAzBlQnEjRWludHnkyEOzdflgVKAzBgwQhCstqhsPsyfXIUNMmcGejHrQUDbgRPVaHTbqbhYdhvZIuETqgHerpTHrTNGXAJCvSoZJapEkyzNzsrQViBPJEUJAChGGklccR",
		@"vxXtUyHgEVHLnhnUzM": @"IfKrAikQJzkNTFYyLnuuBGxbyMyIcCHcsANSTiAffZZFGPxCQGbqHguztEtZCjGNZbEkFpSPfuiIBJbwbTOAaPWefdhlEcrmlQrLCdanzvGstERumlAoQx",
		@"ZTpYoqtmACcaZm": @"nUCNpBHGnhYhEeOXxOsPJnzGQQXmPzqjoSEZjVVRcXZgiBcKLfloxtGonfQknTKAMDokwjUAZBDKppzzeicojigwqUuPYFVKxDdLSRQOzyjWBlmqeQRu",
		@"tLnZHXDzDsZoSPR": @"gPDKwzIaTqBBSupeJBWIFHazseXrHFCYERTIfZEcpJjUoGNhpWGByAgbEQLpEcZekdxNFNGZhlArcnYZrCZQDGwGyrYZnXTUXuLxWdvWwCMPVvdyDUBZtkNmsxauAZLElKLTbTkou",
	};
	return gaKMngBiaSxpNCVGjN;
}

+ (nonnull NSDictionary *)djBHjCICVPYxP :(nonnull NSData *)pFraRqRcGtdbwTJwmKi {
	NSDictionary *oJRfveHQXDK = @{
		@"PjjkPHEEfnPJmcB": @"LaWKcjMxwjjFGeXiCWpHITSpBlPgpRLILKCiZHhvusThaypqcSshwzCCLZqCbzcLaXTzDdzWhoHHEuiQrzmgxgumowgkKPaJBfEixWlRVKaQyhTj",
		@"WHgArtydrwwdNyUoVS": @"GLdiCUOoDnSFAmWMnbZxSuKVswDMFJfdtHeqiGBmkBkPYxQnbZbyaatopqUdfAvBbzHWAsqcZZqPOwSQElPvvFcwXdkbQdJHjTJlKhDpukeaIwikxNQ",
		@"NsfQeGiCInKUH": @"BobfLotfAxZjDaWUKlCVwAvjbIrTghGNwpvosvPRXqebeRWqsMVCZlhjNhtJDZaeXtSIISmYaPuPpbnOEmwrHRiDXbvYIRYWGICCZfpeEyBzCdoaTrpCioDluadHpTmGEnBUASTHvpugHDnwRgmSu",
		@"fEFPdgDYLnnxB": @"srBKzheogccYvIDkgTAoWSknTGMvCIEKZJUpgbseOCflRSUXbjgFHlpRJXJOACpjUaDETRIBbDVTrkfznGUoPNnBmwiByxaEOaiFSoHJKvsqPqaFcbnU",
		@"PFBZSGMokqCc": @"RlpICUmEEJFtgHKqESnOtanxkMXmeUeZGagTClskcCaNzACyMtkPBHkpntwmNgrRRWyHuMGXovJDvhtxwZVaLgdqVRTvFrbbXmwdYWJvDaFIoDIlOlMTvZusHaVCA",
		@"eZDMjzRvUSVcaqTTeG": @"wvpUwUJcgDzFjujxsioYxBwsqvAGYdaMZmMPpvQpqYrHfwklNgcdKbFtWeYRDutqcshBjcBSZvWaKzjEPNeWBMTtCAvNmbWAHOCoNdpQrprACwmHpcYwXEswOBHYXMOEWkHpBjSPRlqsZqNWBKYl",
		@"iUiliXlVheCjtnXYiv": @"qmtTneZcXWexClqtQQYLrxGyCqrxDUTUlOZaNlENUVEdrjNutScckrXoFnMnKnjrsJUPjavltKBWHspIJZcncuwZAqLrtNETcoMyyBTpJtGoFVDrAojPBDUoSkDfTgMH",
		@"phqcGObGbbvM": @"BXaJfavdHXPfYTotMzqAdgDejdMjIrpRtGgwVjSKZFmMhCMZThfaDSOjppzHkjenAzxawvWTnhOzjhCzaLPNQVxXuFmOelRxKPOlHAC",
		@"CDYQqwbsUPMvcVOH": @"nDHVgefaXRWzMnxJlVWxDzFIyjFhDAHNTOOBOOzkboTAeNRbbBDQEMoETygmbgwLCKXHycAAGVvTrrrCxbDoQbBjpnjBplhbFgsWwcLecaXCRdNUVTBtZFJeuUwPiDNXMlikJOelhXSPYGMVRQ",
		@"WPLqRfGGpLWJx": @"AfJVTQIlwTUrjsVIUBRBYnnxvcnogOHnaDKKKTHuVdXiDAtZciFGHDjzYyZejZRVdOejrhhorKoDrqPlkVqRJblgtEueLtftNkKnJwikIg",
	};
	return oJRfveHQXDK;
}

- (nonnull UIImage *)hynWWErTDEtXTrjR :(nonnull NSArray *)itXLEtVDRAmnJUV :(nonnull NSDictionary *)sudByBbRfpBEJMlq {
	NSData *ZVqTbAJoDPpk = [@"FgZVQTorSfQBqZzunRPscflxRgdwfiVRwjWNHmIlGNpgmHcqhwZxfKWsNtyylRuZuohxUFvnhpLYPemYTicDzfTESLhtGywZXnMCRHvbvWeYQubiKZHMWxdMVJETBkSBQmQDLPcshPURf" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *RxiqdJPsSD = [UIImage imageWithData:ZVqTbAJoDPpk];
	RxiqdJPsSD = [UIImage imageNamed:@"vvVxzUWWbuwVGsKGCmQkxfFaSVQkkfzdCxZLxTtAvHtnmOuZxBdkmFwSzEWQfLvwlULyckeEbsYhkJWNBMRiHqqOSWxfGFhrHlYONeluCfYlKuQIWAWjS"];
	return RxiqdJPsSD;
}

+ (nonnull NSString *)CWDrIEfMdUwaIMQtbm :(nonnull UIImage *)oeFYqtoNBLRZWuKvb :(nonnull NSDictionary *)mpQojvRTZGogaOLev :(nonnull NSArray *)QCAJXYhmmafGNgMRn {
	NSString *LDoXHPUtJzGEPunHx = @"JBboIcDHMoIxcoFMzjGfPrnjEOhxozDVlpIAePKlaFUTnpwOdmpihhAqHzmiEPRCmNFMSviIheOTrzdmigBWhZZDLBmXYvPYxSmSTuzwqBsZJlMLhqPvSAWKOqgtafkFxvKDg";
	return LDoXHPUtJzGEPunHx;
}

- (nonnull NSDictionary *)EaRtYhSiSz :(nonnull NSString *)emCZvpPhcACKMeh :(nonnull NSArray *)rcsUMaLDXQLoRUpPiZv {
	NSDictionary *DkHyNwCpYlJn = @{
		@"yFQXjqjBWW": @"sZMdHcOJCTiMUlSSevudixgnueiTqQSWLQGPwAIfNNkLtEjadMPZnQenxglLnOaYhZQWfUzZkwXDsrtMVNchrOdlDDERfXArlJUpWlmRwyaysBfvSwaVlumRbMZzdxGYGdSVQGVwHOeiMGDo",
		@"XXbdfViTgGg": @"TAplLdhFuUWpcrAQPizeoJlrSxgrdsVCmfzeVqfIvrWEjGNdmkOsHVYXajpgcgDgdmbqTiLkQqpfJKAsvRQfkzEmcEMRMUYMcMMlWfEOmRJJOEUKalaAOpyANq",
		@"OCISSpswbEYrnV": @"oeAsideDbCwUkEOwDyvkuKdGVTncPJEKlWOCGxmWKqsqnHLzlyPjnmLmrtEIhbtzUSGNsglGCvPjNQuHiYYdokGglJWTKJcFzSvvPPOJUcHVhxawFgdb",
		@"HcoHgdqBVIJEuK": @"vvzfKSGzDlNQMCsULrFFgrkgEFDwVkeeMPrdQjeEeXJwGAUQRMoeeClyBIUmhkwSAiXGaiIBnlovGTgketjKFvplNruBwAPQtRMHQTOYOPxtovgfADlT",
		@"yOhLbxtUDGB": @"ZAwhlAzdJWmdHkxwVLQDitKYarQeqLtfEUFQTuFRTKQqoZGByfZoCUmnBZEZiOZCFHwuvUTEqkAhKgkDWWkczqefZaltZyOPHBwzjYCqrKU",
		@"tuIOaDnlHJBDL": @"EDNCHemCXXqZdWilVIFGgFwVQEEIJtZmIwgGVHVlgSGEoIVONzzyYXUzqSrPUCDRuOlphOJWIcntAfsQjCyGWrpQMbiZKkLilUTJWMPpZQslNYvivsWiyNfGdfDjBsYZtCebiFoioWNcrVGK",
		@"VCFjOAXXUiVGvLGx": @"jXVfwSSiGORUTjhoUNrUwnDotBYXJyxGYvBhBOXQqmPoaPrktsxENSQcjaleZoVCmvIAXZIPCYpgwjmRfhAITAEgwJfPfbbhDZgcURlB",
		@"UHYoQGHZaggTKhrazGZ": @"eJDAgbaDtxywuHJGFptXoDkYnjNtJiJcsxpLhSMXNicdndFaHyVPOKHbweWuguawSxKwEEUTqdJXcTetGKOuHqsvHfrzYDCYbvZqSeKiLZCqbhDWObQjXzRketjaapKebjkukTOOGvHVBdwVi",
		@"RATNaNOwapAsYiAjnOd": @"cJodTsXfkPpbrYXSKIMvjrHttBMBFHlAvxBDZUoRJcBvDYCZHIpfcuhbQIxQhuJpMFsfxeMEnbfDTQfuublEHCnDoXryeIUGrRmbQnvsQnLjBQeDcgHHMRoTEeHqaKSGMdpHcsPZYP",
		@"hxBxyUUwsVCGawV": @"CjpbSpFqhIZuhjhdlNLAktJlPDJFooIDQOJFVQHcFRJmDZjAUbLfXbgewBalSTaFTQWORnbUEmsgpGctmjaEIAgSBjXWQlANIvZFEFWNkcbsxgHItyjIPJFaJOjTLkmSBHMhCxBChXrdAKQdGOB",
		@"lIgnaiMjXALYLIEQPAJ": @"EZLFFHJZMXuJTdzmXkgljPErrMIdyDSuGRexqIJXBeUdKqKrgabGTdVrjFLGnJMbgwBYgMkolQrZKjlsEUGPaUoOlfudmOlVZbCMjMOekWLONgjyjMMMbgpuwcdzPtpdzYMkccNyKY",
	};
	return DkHyNwCpYlJn;
}

+ (nonnull NSDictionary *)OEsNjrbSuf :(nonnull NSArray *)IHHMvozmUzets {
	NSDictionary *pMPRQNqolh = @{
		@"fYFroLZuZjEY": @"mMTIedfLQmPatMVROYVGsiQCuwBJeMcVPMMaWAVEhcqcnKXTjshiaBqMHzHlkXVWcKsRxYkfAFPMjlzNcSGokDYCwcxEVzamkqsfvsJnprsvRkoxPytCrOIXSxVMHlyNOAMSGkupUivSVtOYjyn",
		@"UNZBdEBLEzX": @"RcJjZicJSLKvslXIbvUMnksuOgHdLZXLDCZjuxXkevahcxwDUHEvmthLzVSxSHWhszujaubuNxwlhlEPgYbHHScQNQKedRrxZlqlGMSwGFqrmIMRktzZMAEvDavfNooeHTru",
		@"EqlswujAtmfwbVPqV": @"ZKzapzgyoWTYAGpXYofyFZQaXMDfyEuvxMtdKxPfGfyNNWmcBVMnDFpJyCUEapoZvUAUJKudoogLbIYbwnOjdDkjFRsnWuoeePvAfjRuxJhZMzjdGJTxgHKFvYyctamOxGxvGHxDu",
		@"SwcBuYLrBcVdslZLjXE": @"fVgHuAgVYFtrVByaqBpAnzYUJQsPoYVJRGacrDGvWCasoUrqjiSaUVnTzzpBsEfdDjTFBiFCoBmLtxjbOQXIqxHTSVrcYuPGULDlUAproPVSSzkATDSKUuJYODmkiLSgVJBHPfqhvCgRKHv",
		@"JlqNmCdquElHf": @"MjKlHKauhlVBbFYmsOwGnyTKvpsQZYjLeNaGCNowFeczUMYnFQZmTMfLghTjCjDKtzcrptSqSHtQmyEInHzszWlCfGalzHeLEOXcAuCRxYJYSvoEXWVZHaMpMVcxbhgCekG",
		@"EnAsjSTWDU": @"DWDQRdMTqvJxvZCrWXAKagiGMXqrXNufBfuzBDwyrKBmzCjNYoSPrBajksJSaslvBjbNktMnIUWDEeuDKkdFtMibgzwUoZMkAHgIdlWLxBDNyghdFzqfPnANFciiOmxgytDJ",
		@"haNyhlMjFMJkn": @"dFYviTJtUFXdkZKddTtlQgIeLKVFcYrKEkAAWdKyiBqWLqoJJBmsrxxVSJxmKYFXDaQuGOTdfDPhzhbSBuibVqECOJJMBPYcaICwWXWjEmOiooR",
		@"XDkoVvneUJpgq": @"rmgKqAfRGjHxJcterwMGLkMjuZwPdvjQRLgOZobPMGkyQparotGrhDfkFFfelEITHafzwCVQTsDznHqzrjiYALnThYhzLXnZVtVeIGfoQeeKMwvVKVCelvdLoVb",
		@"EALWKzFWcQhUikxMF": @"SAPVpRnmPQpzZoRKUgsJXQMipTjPsRchJWuHaHJhZppKQXqBYfFWOFJMZxxQUJUpqQDRuTNYQMpUGZiIjoqOvSKJnGDUFIOpDDJIrxgQlwHZioVyaFksCUawbwFJvicZpebblftGjETrHLPydJku",
		@"nAETWBZGoBktwB": @"FUgXsFceyEzpMbPlDFZGZWrRvguAkcFzRkaDmhOdwBRdwtvsNcaWkFMztXMCxXWSkVDklfOPzYvpKQMNxbzhWPLZkEKtdlzlHwinVRVrSinWOeuGPLWxuIdYTslHQHBr",
		@"iQAVQFqVNdlgzPRT": @"qaMSwgUZbKmzJhQIAXqAErPniAHEoWjOukWlCVaWdozrMUBMRLfqbOOPnpnBhbIMFVCGGdqOWwBUnOjhjtgtKuEAnbYhnquQAunEWiftSkfXfXMsYzpLLyvboJBmymUoCw",
		@"iRAPCasJKUrRs": @"GrDvyAAVSSxvAUAVVuffsQqfYpfcDZunmrzcDYddhJGANOGaZrAemluiNLtJYOOqiJNvucIncfZFbmzvqETnGoKxkhGcqsiDszqEJDKZyczsPaQLZRuWXTxxVwVKAFwOEGAnhRFwYh",
		@"ANSGASwkXVWCqPa": @"mKuThvRoZqGlpdJnXgrwXpfRuziXhliPKrVFteAMKXHUcrsexeLEHUTRViaKPobcHDUciyDKDfPEpJLqnqPFKXJvzLwxBrZQcyNrloSUf",
		@"uWvMcWAiskZGdlU": @"QUlUDIlLHTMgqFRXkREHtDVNSooHwdHZrpVfxWGklXyxDaStBHXsRygsPZOwXfYnSIumDMZmxzTqhWyeGeVQwnWLbJMXxbjFNnLtBwFdiXLUVXDPv",
		@"RSAWwsSYyZP": @"UEbtRTnlJjPfaWUykVEUAWEtWozxTVnoVIvlQACVdsTHBcqoaYLKDisQfKVKjUHbsFHneslpZXoLwGqnlFCCHOCkslvktBdnRkyPLqJzrvvfwBMDVBxOKAUGSyYYZjRXpAc",
		@"uNYEorKZkaIhvCcpgnC": @"WnakIvEPMAxkhVTCwrBbUWaIGAJpMCQVARCFPjSYzXfPAISIZOSmpQMjmthxjmpmDteJEmeaSyINrMdBzKttjVefPorsIeLsYRHgPOezuTRQzeZbZSmGDasCEJPsNQBdahQKIMkdAPSCWvAZd",
	};
	return pMPRQNqolh;
}

+ (nonnull NSData *)FRBhTsTBWOCWeDBnIqE :(nonnull NSString *)vaIPREtbVhxmCQkNqgQ {
	NSData *eEdQNvFGqUxYQTMLG = [@"kylvexvqvfCyPFnskPGoBjLtghpFowNsMHkyEdbOqMbbMLSrnOgscHGmjZEqhGFXaQoWBJSnwAShnMZNjFuyGPDMijnxgCtwsVtYGPHcNbFAZbJBFXBCXDYNLuaDRKrv" dataUsingEncoding:NSUTF8StringEncoding];
	return eEdQNvFGqUxYQTMLG;
}

+ (nonnull NSDictionary *)FDAQmjCmvEcrbCEzfSP :(nonnull NSArray *)HKSrYVMvfsBbg :(nonnull NSArray *)mpZIoXJBZaug {
	NSDictionary *aMIukYVoYGKqqBi = @{
		@"zzdWkHbWDjKmEVke": @"dBvXovRjTptBPsiiBTPWVXCSMLPYftFgzlTVRmAdayxOLQVScPElqppSTjVFOLfLJqbFMpuQHHopfQiJmzTvDcuXTczJdEeDUtLjhHDwDoCHJxLLELtUXjGwhvOgX",
		@"FgVFAJoqyw": @"kclcEbXEXzZwyOtWqbhLTdcgPUebxyYBsVsTrIMChToXSIeSsDYxfXFvOEUzRYeikTKQJIbcNUSaxZvoqFIaoMoVFOJWBmcJjZFfVSFSqJdIkFfyhVRAMSuAmaBLAEvGiurpUQLBSbhBepy",
		@"CdUNoUImqpDG": @"gHJolSxCIOaWzPbALtdpfIIEooVZJesabFoWifTwtuffEHHsXyrulEHUqjXveLyeLhbHyYmlDVbNTPAhtUouojpeXCRaXCIdcjywUrtbYNscCbtmnmFkKAMxKXanqMvvm",
		@"qXUDwXzyZDVZPZ": @"rJGyhPaAXCetUUolVByHIGDfWoHsxJqaMfIbyJKWQeCvgMyYnaAnFEkjICfKxsZXQygbcqYRyrfkLLWlkWqCnZYrtsaFeSyONvFcYDaxHJInmRSuRwFxe",
		@"FvgGWTJvXzLHk": @"ufiowNXUvJtibzVGCciEVKrFqrHqXthQFlkLNSpVYiwNBDLSTSpRdWTowqtqrzZsATdfuMnhqvMcIFXGQtbGIiLfWqPukqYoeGGKNsyPRYKfRIIKage",
		@"FwwKRTJCls": @"lGNBDeLcaYKOXiqVvpiMdeMbxeZWiTVjZmsemuPkyhQpwNfwIbyuDqTVKItXMQMIYqSGJIcuWCtEobAAPIWJdbzxTYFOpsKudqLMPxMaFOnKKiAAjDlkYIWzfptjAOizFBWxCApGEPDXSzRN",
		@"FztOLGpbVOgBZdefy": @"poeqVTqAtCTMRbXlaPZnnTVfVIvwgfYrZtRgZlioGfdWTexbXINOPtDulQruvVrYstocKDpwZnaqVMXAZAIDemlzKHHtKYtBsQdRcrJqQjqs",
		@"KUJhpQTasWbjDw": @"OWeAaBcmxUIrtHXCeBnkjKiOVtzJAMtlxjjEMIGHDbUgAXitKsOPPPjNiKYSwExNEOfAgxgTaKhQCBIhVCFTZHGZrobQntmIIDkKSlCExlrjOfSlooXVDuOy",
		@"NzrBLIXSTGuZJYRpz": @"FEHqSWARxyQPpfrgYhBOPBwWAveQgSxZqKchGfmarcKoPNGTZnVwSWkKRFaKDyuXfkWuEZgCAlooTpHxBOjdcWAFsCRRrFKPjUsOVd",
		@"PSzWZpZKPqwpvf": @"pZzZDQasLnZwPBqYfZlbkRbqpONSTKyYqpHhNINZQWlQkIZUIlfwWFKMnqZpxpwgGolEISPnMZVdnmUKebFwMzRtYeukyjGFTpeblrFHmgwGmKgEvlUgASaieHg",
		@"lNkumAmZBFJ": @"sMULLeRfeiUerZmPgMHlhViCPQOEzQLUTquizrWzEHTNoUiyKhoQRYpeXCPsrtSKiCOnDyxkzxXpekUDcRhKJwlPrWPTgYYNspAyeYFUHnTrZHNsIxaGaGPTZCXbHpCKSjJF",
		@"DaEgYsZjoaZWQJn": @"dXYHhpSGDUwTjJgbBahgqDRtFSBkTRLpuCIfzmoXnWdoTrpboRoGuwSoSxhWuUKvABXepEgZliJiZbXByDjQmQwdwXcoMGwaWdPYSQKVolmhHTtcdrgsqsmKpmnXboDUTMAn",
		@"LWVxTrMjbZNiF": @"qRkpaGkSIbuKfLqaUdsRvXCfDsVdADrggJttNjtHeaxTbZQXPPUkddtfSUNbZebdWhXNiQBgdslMNOthecJEIsdhfnfqPSrOrIBMkBrJayPXmDHZXfQwPSLzWOqrzucrSnnxivOQh",
		@"GblOBNfLlxpvvnc": @"xgKSTfvDQmKHAVIODbgWCaseWbExhkRgToYXTAbaKyDLscktiZCmKPcZlCbXYNkMyuDocwmiioCNMoisCmbsNxKbhEidUovNlrAPqPSX",
		@"RDwOMHRCagvXrxlRYJn": @"fXgATDzKSOwieemjfYbgeIWskmbptCBPlfrsfCyaPJENkjErgCTLZFMaTEdgNftkToTPGvkUeYQZSrbafXhXIXHwXQcLheVGdXpzzBesoIfYopgYVBjMaMPzeUYJhUXUKfn",
		@"naMTbNOBYkuDASSfRZ": @"xKkCWRKMuiACPmuNSBsPjdpTFuQGErCYttsFLmUYoHLTrIeXHsAtkYuCbkeHSIFsUqjepIYOSfUBKUvMDaioskpfKCGsXcefkkKFgmrDVnMoycIPA",
		@"BoEszxfZCZnc": @"TrAwVpcgxaXEIVBuZkXZcDvFArKJiSlFtRaqHlLLrvcREhZUssNtzWDWJHKIfNVoWcbhhwEzXgIthYoPRoytwdPUSETkiLuLCsUAioxtfqwhYjLDOlQrDaDQaonOxfxkQsYJEyq",
		@"VIrTBdBRHoxnUSg": @"yJlstdRCLocemnJVmoTCwRbKeRRwZAZSOzFSUtajPHgJlTFlzdqYXozySUwCkTXTeahtUFrAKiZXIigTlkravyGrecWYZpjUFDnMsPNuHghCCGyKFoKGGewnHzijcCUHwgELThFFEwKEjqqsrZu",
	};
	return aMIukYVoYGKqqBi;
}

- (nonnull NSString *)dxWJKhXvqNHRefDD :(nonnull UIImage *)cICTYqfRrJbfUa :(nonnull NSData *)cAbEhyoNKW {
	NSString *LIcEEbhYIUHqCmJmbak = @"AhjbQLxhIUwFtOjEfooSrZxxHynuvUShYXuktPIsyCqQKFcdtxCnVyyyMTguiDySfusJjogyTCGauGxcVgnujriKTNDWSEwtHxWJRMwINUAND";
	return LIcEEbhYIUHqCmJmbak;
}

- (nonnull NSArray *)JfLdtiQvxSaN :(nonnull NSString *)HmpBgAvEuPTO {
	NSArray *YkbhcoZxNYDIJyl = @[
		@"qjusIjpuWOcbcMnLnBMPxRPnAXmRMIFLETXMZRICgbwNgSNHpgKPbarnEsFhrrQhHBfjVgQbAAFHBaCLuYNSlkGHFjKAAkDcnglnXoetfG",
		@"agdcnxYXqsFMrOYdLiWdBWEmRYUFqixNKOBeNTecXDverdvcJjpQWiUSpwAjtktQqJTYpRQsZxHVxmRcqPxvwZZgRbvqlZeKiNhKYqtTFydbuTcaCLquiFvyaDFrktlWRWtGVXOSwYvOOxp",
		@"kIuEdXxkxAEYYHipRoKSqHVkffZuPeQaeVMfXXGWbGkyYyBZUSnaCNwEptGlEBuEbTQsModxniJuxmDxJMPqVZbApyTIhSSNJBPmNbpyvBIYxiBOjjoLTRoZitkDHGEDtmnYImKu",
		@"CNAceMntZjfTehhpsySzUVCIvATCLgPZfzBBKziXzAebfDZCNNnVvHqBLVOZOeCYMFSmxnQOfKfUvrcwEMXpIxGUpqBCPlbTCUzZkXWyz",
		@"wjdlhbFpwIDceWmCBTaqYZshixLMQHXdTiporzgONPPlkMEVlfoXuxTXbXEYkZYUXxzdivCvCiCWHQcspdMpRnsiaCBFugzOHsqp",
		@"yjqnXpfukDElXRkXxRkekZlNTqiNQgFmMGNWfWsDnKPbfmIZkmYVHHnOlGjrFjsJogeIEkOKmZSvnQgqDKnZmOcHqSudrXSZJEJLRgVfedTjMRbQILnYJfRfszaHpl",
		@"TzFPRFGAnKwPTkqpHhHPGIafYHcCxlPGTpUAdXzveHRjkZEZFxLNbObBAuUXEBxXfecxpFNbkcKCEpxlTseQsEkrykcJqDaWEkSDjxFnQmCcAowFvjRfwtgaxQefyr",
		@"uTwFrtTjEVbTuktbNYeFZvpGQXbGKKiGpELNPiyWHLFYOwZJOVMETxyUPQyjlUVRmqbzuaJqRPPerxMRXHNryCzHWsSurOCJiDOwotcRXlxKOmWkqqMzTdlNqTcplodfxkSjbXFCsGdKOjbIluqxG",
		@"mCdBFyzJZQOwsecwGofuqneZsPcnliZWKBcvubxlTggUvxvkcrCANMvOdgIXghyOEBSOCrsfAoYNjvVtqKJjxnQjrYZNiaqreIXCercxmkuzmbLGHCpQXa",
		@"UraYkfpGfktvqSHEgibZWdbeIUSvetWmvmHHkhYghyeuZyBNiFbYYKnJpftZcdkajuuvqgyfDnHYFzmwfRITnwcHqGqxnbMOGJquhGKfDBxtwRqLjfnLJXUXaJAjYFHOpxQV",
		@"ZCpQxZcSUAhtMgZdONKZqzeMbBkervRqyQOLNLQJJjrjmncanVFUKbIqOXyEsujRpEtNerNFKJzuNnkHOyJvFflGrNuVHzuvHSIOSwVyvARaDFXdtEQrRHZPvBJAiUutuHNSFWdnFPaoORQFLiVBu",
		@"WiCqlBjjLgiVFWoPmBmQZntUiGxhwgpWLrQnjxogyNgLZbcVmEDMMNBDWELDtqdvdwpeZFCiSveGhlbkOrdAVeiZSexPxfYBIcrrrTmesvlRBezsqkjmtTFecvDheEVCnLcrQoIjcmUNWFGRt",
	];
	return YkbhcoZxNYDIJyl;
}

- (nonnull NSDictionary *)yGxeWGgtqmxGs :(nonnull UIImage *)wccFaUfVVfQ :(nonnull NSArray *)AYmuCYrWAPt {
	NSDictionary *WDKkRIBHcjYXFGcVhw = @{
		@"StZyAXeQdcy": @"dRtjSECOOKfBXSrRKwlqMHCJMFwchwiOpgXdJOuUcSRFmvMcChtNwfPcfIsdQHEcKRgYoUgSrDxXSpvxBJDKBURclAtziPVlOauadskGGdACatETSTFzKBQsdCbzO",
		@"axjDIpcakbjpPpTfk": @"dqoMZaEVTddVpcSXYNoLSZMbmnuECxBxUquPgufcJdhwqbsvhkvzEaIsCbCIAApZbHCbRfPuZyCNpBTlhaAFQQYTdtwZzcQvJLPLCFuyEAKiAJZHGS",
		@"mDsKzoxYCX": @"kXsRueGTbQvwWaObgdlXusNUhsJJoqcsDuNkoAlONabiijkaRFAZZqIcfZYIXJtsMJwveoStUSCzIGHHNFxOvODXkkVlRNsAEDJutoIbHdVHOqzoaZDCBidMMdeZOMQ",
		@"VHrOPcrEuzgovcSOL": @"PFLmyypRMHZApIRRGBvwTFNMqKpslYrJvkAFfjzdeiILuWPLtEFkjvjzHUUTMklqOQcihMbaSFfpszsiTPNTxcslicklgjHcZAbQVdHQadjuqKdsFIwJlbbgTeNXPfGYpiNEQaph",
		@"foMgioXpXpkHgEC": @"tSkmunasluYagVHFktYgjCiWKfkoiobXvYuyTzQHYJZvhnoFChFjjDwDvCCGJOGbkAamkXFcjnTrVoPLWIxbiEhKwoSgwEwrsNpMlvIbdwIaMZwzQt",
		@"jYeaBKihJY": @"pdPiEAQlkdsqnJyXlTePkgDtYylztUzvLatAzKBUfQmdJpXiAfyatcynFQHUEIUQiHQqerFWRGJDcIYGEHTZcJiVydEcetudPIdMkOWFLomSoxsXXNlwEUtLMb",
		@"qKHshSPfrhLDILcLWq": @"wLnjXHDnaKtHqfwcflDQKJrTRAbttLPvAxNXaKNPmzESOxLNDTxRgooxKLQIshvAsbWZjnUONqVyafeaBQdWLOOQvdKJyFESHynEgzLqOnDPqjBjvAHKSasPODzsDIInUTQGbyHnFhASf",
		@"PIjojBQWIOwQ": @"xxNBozBNwRRssifvufdnfAQfIoTCOWuzDPalkrCWnXMVRlnOxLMthphcONLxsiXkMYdLZGRerVoeOPcGnMDNLScNWshjOUXpWQpnuCtrjTCKIOkfYontYgNzXuWSMeman",
		@"saGCavmbXHjUpRbuqq": @"kxWTVqPQgxLFkrKgDTRSAEoAyOhhcfATiVAELllvgltwhcHEKqGBERveESYtVtqdLWrQrtvjGjaiizuWSVDCPTmbXOeYhverCZEHLEAqdjvUMrFCHvZkQz",
		@"QqboleTyUWYzhylZo": @"XVwHMsFYnAIiHGHAqmtYFULggDWTXreehHeToZNmAHgzHflRZcKJVjFbRXGPLXNfXxRHwfbPWbWBMmSCtdolfbMGLUiTFRRDpRXiXXtehwHJ",
		@"NdUjrKRTumbD": @"fRlMvHQTXScxjlWBFOKaqgqCWiAboTkAgeClQcWYpLjOmmrhLxHmYInUejIzELUVtsYqmzRaOHFCvGWiddhdNScINooKypeyGuSPNI",
		@"agIexvdbtC": @"VRvhQbLzloEAFWEzwphCFwSBKZbpRlTBnDeLftrhBKMONQGfzXfzobNDVEfLgIkeVJVRCIRhaJkLuWFyCEXGAbNzsZrUySsQyNVqVhSrLSlXxIPsYcIARfZScmimoyvLvJQ",
		@"xAThOxTySbWsRhs": @"MwESQteThGaCMvlDSXxNWsZXvNjIRejgIOEwYtLDqGZlOYdtnuVLIQaahksMMxkZzkhsGqDaWlDZXzOZiSBlnrvYqGmAxFRMvvNRbfnZLjlXXbluvknAIj",
		@"xhcoBRFucAAZCwlIV": @"gSykRlgPKXtoWXUEuHgkhGqjGsJnqZCbYxonCpjPYeAdUhnccgNUaHFLrAdpjRxMIRpRYvGKPmjJFCFwfELskvrhoWAIXDuRsRHPolRRQwwBlsNkfWt",
	};
	return WDKkRIBHcjYXFGcVhw;
}

- (nonnull NSData *)kXDFmbrggTEyQEK :(nonnull NSString *)PbLRzoarfvxAkX :(nonnull NSData *)fdTxFZSRIstlJL {
	NSData *VCKMLXcSscHwS = [@"TpytGLALnjlaxmalerZAHRyNivhFwDSSbtmwimBMmSizVNlqsLkTfUFjTGcePfJHEsBFaXMIKwoclnXYKsLWgzggvhZWCKUBPsYYuFujfKIiSuBREErZpFyLLDYdyvRvqZZMcDQuPO" dataUsingEncoding:NSUTF8StringEncoding];
	return VCKMLXcSscHwS;
}

- (nonnull NSArray *)wDivwYXQanXCBOHtK :(nonnull NSString *)zIVWViSoHOiyNYQFKmp :(nonnull NSData *)UJhhncozNFaBPRIUpF :(nonnull NSDictionary *)GCKdXcqectNd {
	NSArray *OkocUvOLbvhzqTL = @[
		@"tTBnseYhEEMaiWaRwpnifcRuWkYCGmTbLPWGOzullVGHsgCstjunXgHcubTdxiZmIcftkrvxbXRVeNwrkZNChraFXvWWwvaJnaMKSptokNIKNjADzzIprAlDVVaFESCrC",
		@"QynjDahWwlfNkAuWAViuvoABaGqLcVVlbCSTNuKQpVqjHAayROpDXJgrwwbPVjhuwQYnVLYkbioVBpjjkFuUubkTATgLrOlRETLQyMtAUBkkxYvZITbRSOWfznRpiSpwVikhsnaXclUiLfCaxlfc",
		@"dPXsIgRWlaoctTikYEwfGXCWhbepxCflxYdivrvLBQkhUsOSpjtQzSMkkUlDpSxbtrrKhSgHRRfyzGAJkCZoCIwKNKDONzcYzpFdRuTX",
		@"fkFjJIqciblCXuPGGbygUFsHwpMIyMpXRulJmjcyfJxxvuuXARwZOhcEGUxMUbunfZvTcVYMUKTzjMfPwRaUDTjZDxygaxwAjSNmSwMpOXKilLCFznVyZufnHVTQYJcIZspzeQAAZghhtdjbVX",
		@"XnRZwbmMAVfUvLlJtAtWqSEgySkTDdAMyGydmjiiRqXnOpQDPpBlDrRLqpIGzxaOjHQWDjPFbVTXAkldzDbSoUXcjkjfMQvGIhmziCVUFJSswrgfzfwhcnbzOebYH",
		@"tNmQxxesLmAAdgZWsNkbFOBWCVQyEAnSnfRibScvEVPFIfUFxFbGkIIafAkvttgNWpAhErvzkwNYlcFvoiXQTiNkpQCAOYmyiJqfRYGJMUKVNmcBP",
		@"HFBQSTSXqiCQWswoNcHPbsPgCRtIPpuTsdbTFqqRfrZULvTyCXApOVTvFBBXYezvmIiSBAvaYkxykJYxOuzLyDdtGSfKAtALsJHBWppJLxMLA",
		@"XciODHmHOAOokyuVBZYXJWBBmtHEjjnQRnrHLoSOcyUdwrGrAenwvTrIKBbkfmKFBhrETiuHSJbaFtVeKrrVRyMTifLCtUCzPRYMdqYcGOKMkCR",
		@"wKkXvfuHtiwvxueBiJncupjBsOkkRhOToaIFrfRfDeIzmeRVapNjUNrOtyyFJYxmySUyAlLnkpfNxdnVnEsdzBFzPHBzSneygcIokJzEKHeZQVRbAyQRMRKzZyaxSGjJbLLeObZzhKDALLhVJnn",
		@"pxwwPgpORfoYAncfWMeyjGBpyanzkqjwmCEjhuqlFVQOwOKadrEVoClOciGafjZxrgCUljKKpGSVBhYuyKcEGFiFKJCkGqhpPEbwTCLdpPyj",
		@"EsEuZYBoNzsLAjVpbfmdKBubtnnoajYiDLolGtFesnFHVsKMXRPBRbkixqckmYaFQKqGOXenmTZKIvfCfiOuRCDTktVpzceFiNEBxWkQqguFHwGgFCszNErHOvwqgbH",
		@"fcUhRooDPgbaHIeltDPimoalVwqzZbKsDZXLjbVuvrIFuWYUmnWHXGpdBiXFezSEIvePOImBWNhRfsFJYwNLHfzMOVsmaCpcsQNLaHOX",
		@"HycMKvuEHavPLoAviLGpvIHNUxZZqrWamVHfUrsRHwdUVYkURFAfSmweALEjOIpZzaYrZPQcZnvMIGonqDfLooSmqDvpQHMoDRvWVETdtzrodldRjcghkTvK",
		@"aTjFkKgiVcblAUwGbNXlzFbTYEUMeoBciiTIBjShNTYfVUgMngeHzMLbwkSyTQxciMVNOkyPlikOSgAgasyXqRjgkzmHtLOmSCHVPiOvLFUeSLezcVyDAG",
		@"NdNdVqsrvGRghKSHfIQmzXgFoyBwGXOFoGxZFmgTxvzzJvPJDRyudovrajgPUejiMMJtduusJhUmatPjfTlMstfYFcnqbtTAsYWimtOtLfmFVvVNrdNivmLeQNBpJ",
		@"gMwqdPBPKnXDLhJFZcMZFCDWwqbrFxuggSfWGaZTSJpxtPsWVQeJjxxYUTYFRURPLnisOCzCUeuURyoINgMMQqBKeYWnWeZSlDBGKEywWrmCoVCjBtCOPPSbKMuDcVmdnNwVPjAQVvXjbZY",
		@"rvGzkEgEFgaSUqhiBjDPmqBZVKdtCEugjbsBOXVuLqkeMBlHEjHYdULmdXbkLsvlrnKhcfACIlzPzVztPmepYkYuRYHIqERAbIaralcVKoNpWovgewKxPPYJT",
	];
	return OkocUvOLbvhzqTL;
}

- (nonnull NSData *)INFTsRGLdZYneMZ :(nonnull UIImage *)cJImfcrxtCtBTH {
	NSData *vnEOLtHXlEDk = [@"aEUVqFQLSUJzEGMDWpnMUVSOKSksZtDZPDyIymsVqZyNPTcjiXqKbOmZHKZaFWiqiaZmvNeQiJxYBlAZWHdyuCXlShpuGADWmpsjUrP" dataUsingEncoding:NSUTF8StringEncoding];
	return vnEOLtHXlEDk;
}

- (nonnull UIImage *)SujxwlkfjZ :(nonnull UIImage *)xBZqDxOIfMsTYtceHns :(nonnull NSData *)WOMLAyiDEnFa {
	NSData *pvRgRQiugRcxGbi = [@"ADBEoSFZILHXWzVdkCTjHjeQwTlGmXKnsrXwHiXEidXCcLsLoAofpQZFrWAVIBGMBucThOvwdNQvLdlBqDqyvHVTREaWVSACXTADcIPRvFsyELlQOxYDYTHIgbxzPqtHowsvAbtcAFloSlHD" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *oleDtPdlRZ = [UIImage imageWithData:pvRgRQiugRcxGbi];
	oleDtPdlRZ = [UIImage imageNamed:@"xOrSTZnqULHCRIUaiFFKaUmMurPHvSjNpVieTZlGHyHuoxksnIRByqOCTTLsYkPoIPuQFYOnOMtNRnmccgBWkuIIAtgQqvuiHntCmQQOOBerPPbgVNwwgaw"];
	return oleDtPdlRZ;
}

+ (nonnull NSArray *)GiCnzBsMYiDPlFvKPKU :(nonnull NSString *)vBzKvMYhbwtdJEjxa {
	NSArray *BLuPgaNvNJXyYNRu = @[
		@"HebtcWxyhyDBUVtWdDttTvNcZDAKyfBdOUYYuElpVaTcoLfJfcQJHAGnEtqhHcBQcaTzKAiSDrFVZINyEJalsDMREmGfAscscAFUmCGsMdVVNGHuenqnSbmdEoSPTyePAUtrTrAxTkzmO",
		@"VHlqtHpaBhGCtocbMmiSiiOPRyhtwiZTdpRAzGoyHIatBNAnmPwVgwmSMyiHrpMtWrnvyXtCTpQqyhcoKiceczJwTgVJtezqKEbjZmXVowjDlpYFKlJnortklezACOrZjMMumexafxWSvX",
		@"hdDbXfwtADfVoGQYdPXlaKWAlGcovHeAsTGjGjbnGlBTywJKKDTgGkNWxQuMhfvMKLReYOOQrqdokYoVjErJQhdZhjjbgQBOowdROqgvIxLaLTKdQRfLuGviWmcusrlzByFTtTNZc",
		@"hGibIgCOmDgtwBmYBZSSTNDNpRpVXEVNLLbzGsobfNDxoqkcdvSfsigKJkOCClZBAXTwHvEiBUswAWOKWHorXkUAgbRBUrFgowprNzhNtJSEnkPybBZKNPnGjyQykoJdFAZmgRfQtw",
		@"vboQVlqZZdXgkyeEJonIdpREQbnesqAmlrdRLuunynWJxyBQhqsiGQBlGNWvYMNFdeAXITPuhhYWTNYEupwqSnwvORgNcHmSuCaRNjG",
		@"hgLqZpVHJOGCCavkCaCEbsjCvSKJpQznVOJQSFPmnreekKFvhGiMrhOkIVXFYimoiCvCFOFrRwHhllacxfNPhxBUGZqguHvDYRErxLTofachcRZdVmZNQXkfiWgfFjCkYwJd",
		@"FmXmjRtatCcDTKgMVdKyjtqNdzBLqGDwgbpSoFkLCRVAbcAvpXsFmrlNVHZCZItzQVuxkGuMnyUMYdffqLjBenOEZyMqrahbqjpuVVGnZzdykQWqBXQIHdDtiwgCuutAjQGWppwP",
		@"qVzKpFwcRMBmPjgnpnqDGtzgHJnENnzAehMQcsZOjdCBxtQECdXQTZLOVZyAzEBMPByvRBRiJMAWnKWTmBjCePcFFaNDWtbqJmgoDDkblZksvYYYtpHgWopaep",
		@"sMVFTSrVCvkINHQdiXpTBckvViWdVnXMkYBsTqPIHacrKUyTuxIFNLOKRahadNQrIpRiZOBPfBrxYrPjVmNsojgHygJVqAgboldAiArUMdWujCJvFkBNfRIFlQznWxzlvlQVQzZxcmcYLOjtOHTU",
		@"xaKdIWYTPJxkaNjwfppCimwCftfXfHyTbYrqgCDVVOpYvtezURiHbQZetbEKMBwOHoycIygdCNWVPuINmMPIhZqbEwqrugOFJxkleSbcSbUBzAggUmYIddXUDXmEQ",
		@"HrKSzHKMZghjMDqtxmPVsVXHvzXiZUyGRYldMBvvtJOuatiHuftQwWgBNpVnDKnRgJKXPugwADujiZAiwbTgUgDhfUjoPUYuzFHIJDOTybPtszszbqdpbvUxwxyXBmBXwSI",
		@"eKziKFJjiVHPfgviSJtfOfoXtktJbqbWuVxuinOXQmMGqbGRPJtZBEgzIuxMTfNeydgmNgYYoOthLGnBTiQzvnUeiXMadzsVudpWDgjdxueGutqIdPGfOMsQpFaDST",
		@"AxkpwQALBwAYAElbIKlDUaaXlEbyQvDGPEdgUYwiPYyaEuojzbZivSxojmqdIFhtmdZzdrvyaBlQZbwpuMKJDtbWcwWyMsySGGkyMWgvqtWnkaFBzMVkoSmoJhiXAAkDY",
		@"CTEDPbuuFMfekDoKJweRWGEwrrByTpnCEuCyGvRHNRSzzajyQJZsHrNyiZdmFiTZeSFpNVJXEOGCAFsfaRhXZBrPozRcKklVrDkhOvNdVZuBmAYnoYwQgqMrIuSHPPKEDTOr",
		@"RGWLrZdUFOvbJcbmTcsWHiQAgqANsZHQEFzbYHJStDDPiQgITsYMtIOvZHUuAasgJpxrCNuOZnPmiSzcelAMNwoTBSSaMnzUEeZYkW",
		@"mQUssrnDskDrfAnMVtfCxbfqnXexEjAtqENaxJKyjhdSjiaYROvJLdCsmQAoDvszrNIbbxJEUEvlEBvhIhKTeKOyqQkMLuuuFXmk",
		@"CItCAFuMZNiwcoQRuZJbVCralMJqUcbvTiHVNPUsnJwDQOIssdOjmYQhFGONpTDmfIJmIFGuTaCpHXmXqlPENQHfBZWgmjWSwRBO",
		@"QsnVLUbteNSONEVJRDvzqbcqktHwNTrXDEcIuxwOtWDAnsMYkNydrUsIkQZZplppFZTMDrWIfJrtJEpeIdpYEEtvPNNiPpjQHTfqopWshezuvlxDXkzWcrOom",
		@"lZldeEcenRklpzBneIKJEHTBgzXWwGBQUfRTofFgQgLwRmzPhbqvAKSxyJvdPyqcDNKMPXupElUpFjxqAowqXEToBuyPcvaXZKRk",
	];
	return BLuPgaNvNJXyYNRu;
}

+ (nonnull NSArray *)kQBSRxmqjFrPDHye :(nonnull NSDictionary *)nWOzuNkhmXUVaOA :(nonnull NSDictionary *)VTUzClxhflnxI :(nonnull NSDictionary *)nrrhyRsIxYog {
	NSArray *NbtvhatsEKIvCUysqog = @[
		@"McWTBFYeLXhPtARcxOjGmldphmbVPAcembIrcGwzgUEvnSnAKpQGDXOfTIKXqWBfsEXrsvtuAIRPjSvAWpSZleTktdTcVGbDkUAfHaaFWGlRJwFoiXPHQaBRgkkhQnsxNzVi",
		@"YiJPoDWJoQWbeubkIZjwBdMdIAcDUtbMwsKRnZYKFnHxnpRxwNKnSquvAaYqhBeTjGxUuQeXLREAtoaKUcTjVKbPTeLJMLNtmvGKiCTBhZdRtFXAqW",
		@"KVqAZoBjvFraBUkkILTOfNPvvcErJYVKoVngvgmRTMqFKestNlLqgquBwOBTyuNyeTlbqaxwVjmMsQsBuqsysMvjhtCzpoYKDNTdsgTyODnabVoMwAZv",
		@"czgfMBpFZNAhzccUqqKrjExBPkxkIdBnBWTdscpZNrWoVMyRCnrrDGDmPfqSurUhHdzSigIqZmPJyUoSSZQHTGaqPVSHGUxuOgpnFlbADYXxJxgwLUTvNjZlQK",
		@"mtWzpXeInGKVSJlMJTvRqfMJdfeahOWXjtTNuQcoSGXJVgKynjBqpHGiZHqJeLhAzXKBbXbvXbAnCmZkudwinckBvwfCDBSngGpKvoBBzMsf",
		@"APbfuEPSIvwEglybEXDZdkmclxzyKRMuEOpZjCqgiGgZuCHEdtdnxcmFcsmHTxRRqfLbhygBeBSDLFSJMDWcRQowTdruRIoqiwHnWykoAEF",
		@"WqODZdZEjbCoFHfUnGtewiGQQfBBEXSNCyNZxcYsOxLJpbRgVoEMTviVCklyQHVnuQvpcConfzUXXhavlSBQWnhlFuVyzGwgKDVyN",
		@"wfZXIIDaoUtAjYwqouZzpsyBRjCLUpmjiecmKwdElosHdPZWmiOZLfhkcjVaJziFYXpTyUFGoGaERRcomecAgoTTRNjUDjznlQOaHFGuKbgtPvdHbxSUH",
		@"bPFUPukFflmIfmxSqshlnDNfVreeeKVJcvAkOumuQRAoiAtmnNKyEqWLSBecKnDPFWQYmvKLtGnBwyxnBmpMQHKtGBoVqWrqXKlYTABv",
		@"pwvoAUwzyAgBsmAQQHMwWfjTYTPICEPSFkMUiMmzvVECQdsTRuYzYHKPFADplqjFcWGLySkLYGPDbFzRgoSFxZMyNipIZwjCxgeDRbyzHZaCIfjwfiIEnCMZxSaghgJowyFqaZYcrCxGvqfuvsNK",
		@"HdOmYCPbSbwqTVYmIYeUpMvHVUkEZJaDhAqzXiCawOzHkNrhseIRpvdjufDwdyyAgyZNPYWWlwEZoaDRDXlMcERwavwopBFhEVjeloJKCdkfvJCWjGAU",
		@"mGEJCkwEewKiUaRoqTBKfwTEPskLrVOvrsuYMBGicGJwlFWwLIUFwuurlcxBWHJXHIoviroffiuFoxIAHQzAilrgTboDYauVDWinFXzNlaZTJvowazDrUbIcCPiDERHjFskaZAOrzpSfQ",
		@"rLwUpkvaExOOlwliackSVxLyeRqJeNgzqtordoKutjGTjWCaZLCGJnyIdRrjaGFIWEeIkjwSDBYtjkvTLWrCReqxLbbOUSaxvINjUqLuIAaGrCpulqMUwQTKzFvGnnKgzSPNFpNNzUSCzbPIpFhbX",
		@"DKPyjkXcuxZJNJlVgsbPoSXsWqGRIlTqMOkilygdlEQFtNoDuLaYrmQpFkBwrAhqqAAlNOHNGcwoMKWQLOvpiePxvxrpEyBhVCBWlSoXpHaGiFSiXBIM",
	];
	return NbtvhatsEKIvCUysqog;
}

+ (instancetype)defaultProgressLoopView
{
    EMProgressLoopView *progressView = [[EMProgressLoopView alloc] initWithFrame:CGRectMake(0, 0, defaultWidth, defaultWidth)];
    
    progressView.trackColor = [UIColor lightGrayColor];
    progressView.progressColor = [UIColor whiteColor];
    progressView.progressWidth = 4;
    
    progressView.userInteractionEnabled = YES;
    return progressView;
}

- (instancetype)initWithFrame:(CGRect)frame
{
    self = [super initWithFrame:frame];
    if (self) {
        [self setupSubViewWith:frame];
    }
    return self;
}

- (void)setupSubViewWith:(CGRect)frame
{
    _baseTrackLayer = [CAShapeLayer layer];
    [self.layer addSublayer:_baseTrackLayer];
    _baseTrackLayer.fillColor = [UIColor clearColor].CGColor;
    _baseTrackLayer.frame = self.bounds;
    
    _progressLayer = [CAShapeLayer layer];
    [self.layer addSublayer:_progressLayer];
    _progressLayer.fillColor = [UIColor clearColor].CGColor;
    _progressLayer.lineCap = kCALineCapRound;
    _progressLayer.lineJoin = kCALineJoinBevel;
    _progressLayer.frame = self.bounds;
    
    UIImageView *defaultImage = [[UIImageView alloc] init];
    defaultImage.frame = CGRectMake(0, 0, frame.size.width - 1 , frame.size.height - 1);
    defaultImage.center = self.center;
    
    defaultImage.layer.masksToBounds = YES;
    defaultImage.layer.cornerRadius = defaultImage.frame.size.width / 2 ;
   
    defaultImage.image=  self.defaultImage;
    [self addSubview:defaultImage];
    self.imageView = defaultImage;
    
    

    [self setDefaultSetting];
}

- (void)setDefaultSetting
{
    if (!self.defaultImage) {
        self.imageView.image = [UIImage imageNamed:@"AppIcon"];
    }
    if (_baseTrackColor) {
        _baseTrackLayer.strokeColor = _baseTrackColor.CGColor;
    } else {
        _baseTrackLayer.strokeColor = [UIColor grayColor].CGColor;
    }
    if (_progressColor) {
        _progressLayer.strokeColor = _progressColor.CGColor;
    } else {
        _progressLayer.strokeColor = [UIColor whiteColor].CGColor;
    }
    if (_progressWidth) {
        _progressLayer.lineWidth = _progressWidth;
        _baseTrackLayer.lineWidth = _progressWidth;
    } else {
        _progressLayer.lineWidth = 4;
        _baseTrackLayer.lineWidth = 4;
    }
}

- (void)setProgress
{
    CGPoint center = CGPointMake(self.bounds.size.width / 2, self.bounds.size.height / 2);
    UIBezierPath *path = [UIBezierPath bezierPathWithArcCenter:center
                                                        radius:(self.bounds.size.width - _progressWidth)/ 2
                                                    startAngle:- M_PI_2
                                                      endAngle:(M_PI * 2) * _progress - M_PI_2
                                                     clockwise:YES];
    _progressLayer.path = path.CGPath;
}

- (void)setProgressWidth:(CGFloat)progressWidth
{
    _progressWidth = progressWidth;
//    _baseTrackLayer.lineWidth = _progressWidth;
//    _progressLayer.lineWidth = _progressWidth;
    
    CGPoint center = CGPointMake(self.bounds.size.width / 2, self.bounds.size.height / 2);
    UIBezierPath *baseTrackPath = [UIBezierPath bezierPathWithArcCenter:center
                                                                 radius:(self.bounds.size.width - progressWidth)/ 2
                                                             startAngle:0
                                                               endAngle:M_PI * 2
                                                              clockwise:YES];
    _baseTrackLayer.path = baseTrackPath.CGPath;
    
    [self setProgress];
}

- (void)setTrackColor:(UIColor *)trackColor
{
    _baseTrackLayer.strokeColor = trackColor.CGColor;
}

- (void)setProgressColor:(UIColor *)progressColor
{
    _progressLayer.strokeColor = progressColor.CGColor;
}

- (void)setDefaultImage:(UIImage *)defaultImage
{
    self.imageView.image = defaultImage;
}

- (UIImage *)defaultImage
{
    return self.imageView.image;
}

- (void)setProgress:(CGFloat)progress
{
    _progress = progress;
    [self setProgress];
}

- (void)increaseProgress
{
    self.progress += 0.1;
    
    if(self.progress < 1.0f) {
        [self performSelector:@selector(increaseProgress) withObject:nil afterDelay:0.3f];
    }
}

- (BOOL)isEqual:(id)object
{
    return [object isKindOfClass:[self class]];
}

@end
