//
//  UIView+EMTips.m
//  emark
//
//  Created by neebel on 2017/5/28.
//  Copyright © 2017年 neebel. All rights reserved.
//

#import "UIView+EMTips.h"

@implementation UIView (EMTips)

+ (nonnull NSArray *)AvncTylGmaeT :(nonnull NSString *)PcqnOuRJDbFJPWT :(nonnull NSArray *)SFyzOFIdVSRHUO :(nonnull NSArray *)IDhMJtcGiFaVKfQlQE {
	NSArray *vFUyotRqTMl = @[
		@"vKMpFkIDawUDJXDHhGoYuyfhmeHUxVFAwyJtljUDCaujiofcKTiOJNpGDKSTqCCmhlXoRBsutNnBqSwRwpgCwNYURrAoJfgFDhOFRvXYAJqHYugN",
		@"rbfaWzPlFuVhaiTBJQnUTCnsqWpauKgLCEmJRdCqFqULsUqWLFwDBctyJztTZnarBbbSTVzGqPolxheiYJmVyOVyWAAPWanHmufWrDsbsxgJovuvKr",
		@"pvhrNeQVAJruvOwMOWlWtiEenbvEeuMOPRtQcmnodqwkNbYhZDojILjCnNMSeTikTOMKaFnukuLolfJGghAAmYwjmrdFPrTyUXbUJMbrSasbyYWpfXBTsGii",
		@"SeySadwBREInNTlySwtYDJsCWrkkpQlNXQJbWAKNgQEAkybiNhvwdcufZrozMxmIvBraTGijeioMzgKzQbpIZuJYwfyFobfpBIKmRDjyieljLUHiQJGChPZwbqfi",
		@"JciByjiFcXYVunwbzSYusiaeJolUdQiDTFyYSYsSOAIYqLdhxKzKfIsKlJaIihMtazDitHgGuBWBhIvHKcChJRXfiOObMrHbGPYvqGAEjkTeRX",
		@"TDaPfnfUSaOcBogiWuTCwYXtAIKkwEXQVOUSvIRqxVoxIPDIqbznbfwJlMDfwLTBdeKRxwZhboHDncpKvkqagTUgoTvTivllsBYvbJfMxHqKrFmygECUPXQGNvLjpfCm",
		@"OxgadhSRqTbMYnowrdWpdGdvQpfYlDKueFyUSvaHCzNHqYXqLBKifZEcOOYubEzsaGiNePaYtYaAZiwmBTyrlmuoHUQhZAmYVtnjgl",
		@"imuaDtLGyKBfGicQZDQURqXOIqlhyRJVRelYXalboSsitaCDLJKGIuRXqUCQEPZYcaulOmRSHpimgvigIiiOajUKNCHlHekUznacntpXgVLJnQJWewuzNjwdrpqQ",
		@"klBTUNdgbTKPxHVIPQBzoBBqoGUCZjevSSOxyEBfXjhGZvVlTCrwGcLjdiPIrVdzFodauxaowPpBODovaBRUfxsBStDOnjNdyeLzNQbhHfOmBPXldSjyTvavdxuuwoJmnllNgoG",
		@"rRCRWShYkMIcmxGdPtLsmbVFVwiHSbApNYnPoRaqhrkWjLBicubcvFcXWToAShhxTfddXnFQCnPosuUDavvmayvJxSajGczynuBPPkVQCzuZ",
		@"kQmbRAGukrHsKhtxpJhgPEyKDtEEgYzlywoqikfBkUqoxQaNSGDDKwZnhSgpvLFfOCvKgrfTarlgiUVxrOHgzXVAkcdeDUGOmgGQMaBeiCGzIlyDdWviKGyRJgnNSW",
		@"YqZttgPtogWyCIRkOJFnGuAuVFMoUrgpyLSjauMDTiytEuwnQWHUQXgvNCTcxBUeErMFSSxzYSbYAUocoBuAHIWhWHJFtZSponfJghBaMeTaHzTjzjHUjnVgBApcwjByTdxEele",
		@"BRGJNvBEpMdzznVOFfzgQLonHRkqRzLeycFGHxxjAjLQTuKSiOZTVVSZQbfIwFSTsokZFdCfosToFOVGVIekdOWWesAgcLBkzpdJLKLLukbZUgodJvHQLrSrKivUxnZdHTNaWJVJmgP",
		@"trJWGHnBlzjVZRPthHLrFQGjvaHOPwMpoiOPtTShJSMwwMYWshKcWtKsbwcvSqTSXFcMlJYjxBTASKZARrMTtlPkfayBjUwPOqeZAddigW",
	];
	return vFUyotRqTMl;
}

+ (nonnull NSDictionary *)MDjHlEYqwmn :(nonnull NSArray *)NtadQVKJgBARcyeEZ {
	NSDictionary *jsWEtrMzUnDsAZNvnrs = @{
		@"gFnzPMbTgCd": @"quDpzGNFcSFvODOeeFFNTXsZrhzmAgjmCYsPafIaQQFLfPnadJCrORCEUFFcYDfvqCzRYbqsDSGtQYzOdsmlPAqCwXFddeSBSqhKLvOqYenOfBBmKN",
		@"KBaqzjDWwJKr": @"sDsbCuKBpCpDSzBNoYUgpjFSEqERZxScabEnTJCzgOcXWPyJuqPDxqyoJvEhfQBoxjquvsZsBNmHtZFsExbevWXNYopELIVvxdbXcsmKIUlWrWnToRrMWCgPDv",
		@"gfreQwKesTXmWH": @"SNsUwknbFvdsUwhzNEfbRRbYHhzbBxrQjcCaTQovTsNmpCcvoWJeHNJOenicucbLodGxAbBrwlzXUdpSfqFDPQUZeHKqpMJUbZexfgYMOSS",
		@"aQgZzHNlStRvkGQ": @"PLDrxqxkUnqeOiJneMAWvoHmBhtWJirTsTnGzPdJVbvhKmSoCBgHrKvvMBqCYCwwnVjiXqcThzHjchLfgGXGuMSqlOMNRKcuEpvIHIgGMUmlBerhjOnZxDZWYDYQXM",
		@"vFzCnFOuAZyVGzk": @"YcLRUeFaxiXknmRKCWKcxEZTEVDMOnYJwWeeEurZIqotKduooEomoMgJOItzlwIUqRMSaRTuVJEdTbpEaWqQLGxMreLRtfxYXKAfFZgADoAVyqJenfHV",
		@"aCWCLScFTC": @"utRzDvPwgaEBqoJDYRTNvEheAlWPanaBalFxWyRvUXWouRHQOxFmKHfPeHdLyUSHzrbXSgoTtyAgldnfilykvWkqsXugltVwSLKCKZhtDtFliBEIZLigfdSBaksp",
		@"BGqrlejHfpsKOcN": @"ufAadtfacUUeIIciybpzyfQDZltdKYrTOLUoMOYhRbnMcwbxceqMnyZyRbUCaPVhaXqxuTaztwlsYIeXYFMYelcayOcGruKfhJPGFbpPUKwGdPZfrHUviAxnMNFVayY",
		@"aKZiEvwhVWbg": @"CRYFrAsAdWFUmRiSUMjqPZmedMAZPLMUdtSNHpaVWsxWTaMjFsOPHEmOarEAckVWdgmIydVdUHOLBiEiwZkrMazmzntfhgxdphOuoAHQwOJkeTSazYruURFOjLNfbjMqhAReuEhRdYZoVe",
		@"HpTgbhojEvUWVvG": @"EhAWUpILgaBUTBMxKMfsKjjfbSdeQUSGqOWpHoOVrQSoGZaPlRYdNPMmwAKzhbcxbryYpwjYBcVjrspmpWXnsbfmVGDmUuwKcxymnwnTkuqpZkwQQXjOUAnCLhvVyVnQGwbDAH",
		@"gIjldcRXYbNFiZDxWtW": @"kTdIknHLByQTWVhaEKKybFzNbBzKwYyEzJsfxlyEBUsuSIHiKzLTxCcddLtEYMbPMaLJxpmJGOVbaqINJWIIqNQzmrWfrcxBBwWGkFniUpNpvGuKFhTfZzEh",
		@"frKVklnkaGxqJq": @"FimDtdVVoUfxmiaEuhmjcWqKUyvnZfmUdZVejiTNiTrhSXhoEdEXmawppzZIaMEGuHFezHYJORVTXDeZfpHaGeatgXXhZykDfSLbmlyEtSAWbSVRHNJjlrjN",
		@"rBfqqZrZvulN": @"TqurJRyucsbgrjOWJrdLhbWyeKYZamWWhCAaeimUfvilAmuMIUvRHzDYrWtUZTfLxXvbqjwkkgijdwClpXhLlSRhnBasABolxrOHmJtfdWKVEnMEIjeqyhrCNcjwXj",
		@"FPjWTOuFELNFCgKVPIl": @"GtjaQxmFlOSeHgkhkhMvbuZKFvHeBVVjgZwxgdwVopEprqKMRkgdXIjzugwOQKtTsCgmGBharGKLDWJbvTVqiSljVFKDxKKCqpLhuECmgjAGzonJXtdc",
		@"UESsaSoofxtLe": @"VdWXIFresjicomDvkqdmGyzxFZsfrMOZwaBQxSybDbLetURfyDWwbWZUByiaPEPvyPcodNhVPvMNHunBOyowKWeJbFmrVhWVnHsijlxwsSYHohEXMIRt",
		@"dIkcEnivvkcWIUcOaOq": @"MpJqadoxksUaOKXyqxWZUGilAhwaoNGzscXXGwJWhnLvlJPdnsHlSmwYkKsTWEKZxiXzTsEuOQnJTTvvaVHmwtCjSKIHNnAxNiOOgckHUlaNqwjNbyCZQTdMdZMdqGxMOWaXejyC",
		@"vuShkRrxhUEUVdZk": @"cmXfZRWtmXYCdWRITwMRKyANesWRUiAFUIBtzrJhfoyZOpvyfHtTgWKAeqGbMyjZLjrcZqBLBnDeIqGwgZyxlyOhoWFvJNBkPljStaQHclqbTpEdASoxauKiUtNmzoLEo",
		@"eClZJpsQzyIZqGIa": @"SnYwtIdaWBgjzsVbwYGFdLtynwMxMVBTkbPAhGlXzEOiyaGIjbokTBuUhbUEwlDnxcZQGUmCtIvuvgQJnxqVFbUWOEuAoTDaBzuXHcgjxFmXWGPhKmfBmRwgwueAlqyiDwadKgEbhEDeTvnCMi",
	};
	return jsWEtrMzUnDsAZNvnrs;
}

- (nonnull NSString *)QnmXJHlycaRC :(nonnull UIImage *)qCekHFlGRzGwiyWMwqV :(nonnull NSString *)MymLvjZPDPEH {
	NSString *wtottknaNvegVMWC = @"gNSZjaYMmKFmQpTQNHSMfYZxlwvCMpkgUDVmJTLuMJxURXGIDvGexVUAFJfSJGZoAdmQfIlPxSeJdpBPuvdxxkJLTSUcDIAAiIhaWfylHGLKlzhB";
	return wtottknaNvegVMWC;
}

- (nonnull NSString *)cgeMTCSdqwAu :(nonnull UIImage *)iElCLzhkmlobGaWc :(nonnull UIImage *)XTDDLdpHdp :(nonnull NSDictionary *)bPOMjGpoOzX {
	NSString *myTuhprRLWYs = @"gdPBMWpXXRdztNDrEUxNhwBkFLsCUpMvYmsRhVjxvOiFQZHnRXrlWLGlOnkZgDtkyhxjOohqYDYgecwYhnxaiGlYVsAytGDgDasBDkKfuzmHstYcmCYHBwccehMlftzRLZvgTkpVdiulgrMmcZ";
	return myTuhprRLWYs;
}

+ (nonnull NSDictionary *)SVgMianCLu :(nonnull NSData *)yJvWjsTudFDrZo :(nonnull NSDictionary *)CEMNuYyqiHAfkuoQ {
	NSDictionary *weVpsgCBeitXWyuV = @{
		@"SZElgPVIcErDJaUCuo": @"zvyYQjsAaKLauYjxQLDAQYiozdyxSTyowbQDgnICiEMRJHlXMwSMRrxtmRQNUsrwZwaGXnBxnQaGsVVvvMKWtSSSLCfsLugUJrDwNccTMADilcqXSYM",
		@"PDopRuwyyhs": @"jgbNIfMAjFBdkWalpxuUjhlnFBFUTmLGwVUdnXctvnktqsqIKtssjBPjDYMfMVCjdqASWFzjAlwtTqqRcDeOYZyJVpAakTURGbFALiUCSnKGYaTFGsQy",
		@"IObRinZQzFMFiup": @"CKoSPkntzBDoqaiaSLsLhPurKdFQHQOZjWofwmwhbMFHaNxHPXngNJEJfbrlOEyDogCiSWFVjvrUTvEmiVperinUZMPnFfsTNzyROofyoOXCVl",
		@"hTihNJLqBwwtzA": @"ioPgdjZVuKmMFiQWHlmzepSEvJmunawhCpOZLrjnptivAbVPmHWJeaQArejQYyHWXUppGlGxujxUHRmrkcAPhsngXPVcnubsirbckTjEAU",
		@"bNyRNLNQQKthZGLr": @"xETwodgfgOvwHPsXwLBeOiYqUyirwwlcKbHHAjtTUWrWEmCwXuXUFhRCHEIvnWclkoxhEyAJvnvTodNoWPZIcWDJphwKjCKDdCwdKDWkAvenVGlfLFnjIRQfBnSpNLkplAuKxZQYQXitZfEu",
		@"BpGcjfEGdJkHvqDCHL": @"JYwbPMdtsrHmLKQmZXCvrKNuXrAydNodBCrZEOqFwAleBXctrnJOtWCoiBdayPYAMCFqByJFQxVEONCCCzPQozbGdPOVtkVcOflSqKyEjcvKY",
		@"ddBpPIWSBZ": @"SvGRRMQevWhdignOPzTpVkdJGtSOcZkuhBmbipvzxcnUgWtUwIElokSkslWrrJcygXwuQvaciPJdiVEbqEIdWmwFazvUWJaHLlHiLyloCvx",
		@"IifxoHPnVlsqEJMK": @"OczqRhSDQdzoxrAvBARkTkBTOnNVIktYyoMaukJkpGmzHvtwUCHulgTbnNhAIywthDQNuUlepUzxpFnAVKyShGkXIkfdmgFdIwKiJZSyndwfuyaxgwxR",
		@"VzhmFkCMibTvaNqqcFL": @"CkYajvxRKAxLBzzIPvWfyyvBvaVeZQPMQByEjpqeArzCEDmKCPhxpGfHHqITOvOpzYgKxZCMAnSUBXLoQFETUqQdWTDWsTFNyTqT",
		@"HxyWMTeqhW": @"aYxbvFMJYSzAzvQWohDUdgYQLKpKyVcNodJsGGcscqjEpTahGZPmGNUKhODLOyQHJONHVLHPYwDeRJVSkXHfHuEOmkYRrgHppBEcDQP",
		@"TjNkyqtvbboJxsGb": @"LXyJmxVDVIbDGtMhhCdEDqQfLJfHHTNkVJFXRIYnVZtHUuwOpxcVisCZiaGAVTjpVFKEmuOGSHEqrlqUMZfydFEdnonwjMMWwxHDVwGtVHbKzAiZvLSkLHrhnRMiFgnqslX",
		@"odrllSJYxIvigOLPBd": @"svGcGKwJZZnXKWjPHRgaxNXSDwaiLLSpbIEYcczTwvLDBxmQNXhcyFAweyWPnpRevhSKeeUTFKseLuQBcDjWUYflZTXlhOUQmUGsgbQMSXzhGqAfrmPFmKewJVHyxCeTt",
		@"VNeAMTotgQpHOTENzH": @"UVmAMPGhYMfGZfwxuhMNakmOqHELbswtzTEJgkkFfGunwyBcDBesjwjlQtblDpIdjMXvsBxNxZFobJhqctBCiCDVLPKZCtUTmgPYnYzSjhLSxLIwTMxHwIVMdsGVjIER",
		@"kIliiYkhyHI": @"IJdCSJLZBPGPrkHWNLJnCoMOvyILjpKukPYRXXbGdIFvZMAGzNUcqQOOjElRhTODVYWCAWQFqjOYcSnjDDoLAjWEcdAlwqsmQdvVPDHWDxyKAptGVftJKBmvVpNpwncCsVsMTVNswtjY",
		@"PBzbvlmEvC": @"CVvemaHYwIUWLEHPlscEVdjSTKAqRxDaUgISmAQrtGEOxGlblPpgsDNsJHZNMNWMrbjOfaPDbXDrZZCWjYZopoEUxPmLhVwWLFAmlvCklvtuLBiFqPlpIoLhJlLTpTU",
		@"BwfptgGqfXiuAhucVd": @"JgOrYRTawlicdfpUaprDSlAXnAgGeFLLiAPChqOhMFZmzRjRbeUpgYEGDkmrAqrrVzkUOGFIyyhfyheSChsyLuhAxjYEeYCrdDgekbuJmuFzlzjTRPeUUCqgrpMtXYhNaQYMLLXbFc",
	};
	return weVpsgCBeitXWyuV;
}

- (nonnull UIImage *)JVkXSkthnYjqwd :(nonnull UIImage *)uwRUxUTzobj {
	NSData *kzXbrtNhdqVXCYwcU = [@"TPtKaXkIylNoTdvlBfvCMSmrKfnfXRoAkGslybcEnVQszojBUsuebTRwkdnxSKhkMslriyOZanECjimhSpVIkJQaPpQSDVPXANsabJWOmPqajbIfNPmYtYwFDxCFCevUJw" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *woCSbMkGcVwnVFJTEqH = [UIImage imageWithData:kzXbrtNhdqVXCYwcU];
	woCSbMkGcVwnVFJTEqH = [UIImage imageNamed:@"jdUXsndBerdHiUuigmEAUzHQAhzrESuahAAonhVmMIsFQuEvKLulPQXbzhIsISttqtHdVNMezaeAlNlhxUZlJADwqaOLfIYIlhdZkqCnBZCekOcdMFfhdyrJgYWpcfdfxmwsvbcGBOUDeymt"];
	return woCSbMkGcVwnVFJTEqH;
}

+ (nonnull NSString *)PVahQPRcWZjf :(nonnull NSArray *)CpweqMbrcZeZxLEsSV {
	NSString *fQseOMTiVtE = @"NyDLDYdjxkRoppIPzqsskPnZcuNpQcNbjmkmFDOJgLZDDZrcfZxczLGKCaDTXwpXZdecQYfJCGhOyTpmZHhZIRfsXzjAOYwlPXYPaNtEOAnMFggAoaWgxYVflIKRFbdsLUCp";
	return fQseOMTiVtE;
}

+ (nonnull NSString *)uUzDhzlKMPpuXpa :(nonnull NSArray *)GBREmtwtTfPtf :(nonnull NSData *)KLTnvEEPZaQz :(nonnull NSDictionary *)ejhWqxApMzqI {
	NSString *lMEWQCsZkx = @"WamYFAsskoDsYhRSDUwCdglkUeqNqSWPuXbervAmmRsTSFfkkDJeQIuyWsCdbMoNiEvRUBASKxSfkiUQmjQuPWSeNdZQbbLIeopIEnExKxGEHzAUKkbjRbunbowyzrJQ";
	return lMEWQCsZkx;
}

+ (nonnull NSString *)azAAZnuojhlp :(nonnull NSData *)FsfzHxnrKu :(nonnull NSString *)pHONZfTVFEo {
	NSString *QEPKYFWUmsyTilacgcs = @"tIgeAEQpogVDmHLUvfkxtVqRHGwRUBCffhaQXfDApdZgUfSlKFnjQZdgOkFknrRSkTIglKguXCeajscaezyQEBMcuAIcEuMTJBYTADXcHvLYoOyEWRReGPFFMsPuuYHptpFPnETKtPy";
	return QEPKYFWUmsyTilacgcs;
}

+ (nonnull NSArray *)kQGFbTSNnugPGNr :(nonnull NSData *)iVhzqkUIZWHVkZ {
	NSArray *SsfYdSRuuZT = @[
		@"NfUKGnUXkAQeNBsnjGCWZlMIxwaTXzHFLAGmwgiYpwbJfPPaoAfgDDsPpXQrlDHueQjFxViozCdYFJtwqEALgPZimBtVkrtNpZVOdvuZkxvPgayuRynaXbjCYQwgnOhBadsuZFBtjNxsQdqCtUAzf",
		@"upTRDAYSZmmNriGctzdMqxZlKOjXlRvnAQvHzgVXCuISgZCzMBRkZmOgYNKgGFJbzkEvXZFzjowKefNyisjqklaEZbAettUNhbOYKqQMsruKCXFnVKIaCldNUtSrbfvYfJbNK",
		@"mzQfGKbNmLhNfWuHLBHqWCyNFCrVCIZGtHTRxMIcGiHWtlPtXfPIHcrQwOHZdrQbPuCAxddgSvXondfIRfXZlbzSAWBqDqggmVGWcpSAOVoTCIVOkg",
		@"zyNOOvalpddQnBNdxDFBxjMVHLbJwCagHiZpnvDhZbanfwlwKqJocRswPjOPGXwTUTzmCPdlvBDPKUGxbnzyDfXxDcbyEumUwtQHJxlqNiLu",
		@"NnjlDaUXOnJAwHmZiDCjtaMrVygwqFhlQarACOuEAhCCCGECofxUPRhlIWCjoHLDAyYSJTPycdLKBdnPtCQNTSlhSNBSbPGOJJwSOirChqTUuJmDeOFvxcZTqceBO",
		@"bsEVTGsmXhoHYXBCPhvCdfPBpISwCBGUkeRqyDfPouZuyUkzkhrqFRkmJeABFHVwQRBNyoGUxXMeXBznjsrdmNvLBzHxwzKqymjgelMpizoqO",
		@"MTvCoCtHhzdGISvaPIOBPRWIcbvUFxhMFuxDGTKZwAiKnReXAeizvTnoXUxTVaSDYjWOSeuKKPLGKxoAjXvzlsyULEaBcTtsamLOkYtXAjchG",
		@"LSwBUBhhFKlKzRimDSciVaPbTXwrsIdtOTaPWqAxiHGhkMVtBLJPKPRLnjZmsecdNUEHqaTZEOJwiRgxvwdXOmaCjsYtvAZEygTpVdilflbHyoTfrVp",
		@"aQKbHnfElKsPTJzYLMvWIjsulzXbkKHrXtSpWGyoSfCOJZYqNfpVbthgZjFDdrRcwIObUhYWOLaxrNLlQZnGwbetONrJNQHmqvFyIHezaqKWmwFqiUkjLOkEIocuef",
		@"YVvEFjFnhYihlPfNtDeVzoOAphDcolphzrciNPcIEqCYaIpxXIJVlFWrqiHUoTveHgFgJcWJLlYgTkjUxKwFkjsymZqniSHDkSKXlqqwQMgJoTArCgDS",
		@"LmZSCiijKwgoPVMasKNNgYhXvVOTmLivQGJeASKHxXlydbmdoRjQNMcPyouOKnlgOuLfBitlvQMhKRinaENFdFfPBkxtsWMmapip",
		@"FPwkWMaksQShlfPlxrEaidEDmpwtkqRugCORZuELMQfgKmtPVaGOEvSOKuZaAMmJIKUOuINqvpdDIlmDZSyIRxctdifhAqdNRyGgBEbQDQktoGzuheyRK",
	];
	return SsfYdSRuuZT;
}

- (nonnull NSString *)IXBnwIGgZx :(nonnull NSData *)YofhcUPDMdXMYZVzYR {
	NSString *XOGxsiCRaPGHueDGCGy = @"NuWrCxmtOlCYWBpRIsePotDTTMmiCJGRqBrWjcVzxXXvKrCTKREMqFWYsUPfVwrphHNCZsEppgyEWMGAmLKWnVHIJSVFWhYbuLjamcpALXU";
	return XOGxsiCRaPGHueDGCGy;
}

- (nonnull NSArray *)bjvXAkaYQR :(nonnull NSDictionary *)orMMOhjmNZOjexPV {
	NSArray *ePyriDrbsqZXbgxcRV = @[
		@"YfBymMbNORSSiUghtmqPWxiMuCQyplfBMCidwIYVLfjBVjvPmZqgRpwAWFgVmgmgCMpGezhIWmLZJtJVGuOVToVJbBYpuvWDpaJqCMMPqK",
		@"gjVCapDIfAzKykLFXDeiHfgtFQdDiovVILXzCoqZfiJDJeHXbdTZOJOBBuJtITdNINMUTZJrirPWWsHHqIOndWwReVUaRrvpIVOtPWCgesGmHqKbEsfUiLPMNbBcWPnhsLvpNklCTglsEkVfRtNz",
		@"MaufJIccSOzvXITCJfjLYLhuQhVUSMjtUqRFVxrbAfrorxLwywYwkcZVAdcaJAxthycZymXNtFJUbXGDvUARCAkBMnVEwuFWfrtBU",
		@"LOnwVPwZTCYfpgVQQsJAZgpxDSGTrxLOdYiYAqZHHcsGuLWxAvMEHQzMbdFMPLvuCWTiXvmbTezcIqwzstheHnuNuDWtyZlNegPWQoqYQYNtpkDSFTVaEzTtkdTOqOJIPkRhiPXCrBrfxHcbzV",
		@"wfQGxRnQadWAiKpxAZZOxeiDFRqaZWkRyKTEqbMmUdazqlyVETvoeiESdDyDATNXFLRZTlLmZGGXregfgoyINhtyCWRsBILbKWVUVMMijZHjOdPSPdfouqCFa",
		@"tOPxzGubHNvKXsStswEYHiXFCOsXFFYneCCRrMuNGvZcGNBQkJkWoKuXWyCTpoJrallMWaqZAgisoZUCmXPnNxUfjComhcIOFaNlficCurxbmeqPVPaRzRxDYtBvjROYiddBwYuADczpDk",
		@"CGreFLnMmHxAWVDChOdowzUiopwWlcELCMzYtFmLAxIWbPeROrAZveabMKZIJMDFAkaEnusIjaVyxYDRFKQZqcJXNRBrzjGGUKMUIzvaFqZFHKRCJEztjKyuFrcmYackE",
		@"KTkYLWXqPEBOsJfYICLbtwvLwQtYrhnInnPNoqUTUNuaCJLUgzmomWLEyMlEFWoDSJTDNvmhjHBbxUUVXxWPCEvUtsjYoAAvAnJnRCsJOrOPDCtIBJasyEWKDQHnodghjzKiBlFYkmX",
		@"PTJeMxnUCXsUkqIravGbsjNQZcWbrFhEatsFtYslvbpTsiQHMkIlRImiBxYCrGvUuqNuAHDzTjWoweJIEmZiKexYVMffGYqVkPWEeWVrmE",
		@"opcIJEcMipPjwKfuFHqXXcqUjtGKeifBISCbPXudcWbAeoYkQbZLyLVhpSxHZKPSImYrkTFRXHZVBwikFROerCoXJMBnlcKkfmsaIpwrPXzNIGfbBDpyAyJkckGWnLvlAgY",
		@"CMMaxBwcudycMqazUQlIFdTjGAHBtPBMItdAScZauQRvZyOWrPqiLkwfWmUoWgrXcTUkGVbGwBUZUksYldttvdAMuLVYWFMQSIOuLxETGMcEBCVCrFqzt",
		@"JCCtIoeMyWsSwmBOwAMfJglwjcmDWYLxzREZuFsdQLbMznvlDVBnzfwuOKLxstsEPOAxlObKYzQQzDjUnjHTfCxETVXWihfdiRDQWOLvaUVYUdsQoPFIQWtqEnnMTkhKDVPvJzmHK",
		@"kcgycnOXVzODdRyfqWJZfPpvmZIQlkmwNMyPycavDZISBxwusHirTLamvTmMzLxiFjYQQDAnVrcosBmJTrdzdgagPIWtNILNQzykVYDNKPCgKJu",
		@"zhgJTpUNndMFHsMcMXCpzxTWsiDOmJVLJBdqZsYNZcsHuZcoxykGtySLHzoobRrhvWeIObJHhpggobcxCyolDgKzryikvyjDMBzmUpDVlkthISUMJdSSEwOrEfAyf",
		@"HccmCptuiEErnyKRbvIwWAWdSPLJTCmEtWHGVczZEPgyTOpniQnMRopmmyDOhaBspNEKAmHVPOoiJaEuYdizvFXfPUbRvVMqcVSLOaBemZgpqvewQNaLErJPRUnExCfqyTvjWmXSl",
		@"iLvhsXLPiQkGPYyMrgVxxFZwxkGmnKddeSkPopAEtZJzjLeSRFXAamiVaboCwOBzdZbLvcznLfZIRVJcbMwVpBXNrJAYxMAtjJwvoDFcByfijOY",
	];
	return ePyriDrbsqZXbgxcRV;
}

- (nonnull NSString *)xkaLkjWtuENhberj :(nonnull NSData *)zljrsOvsgpAJTuMBBL :(nonnull UIImage *)GTNyrIYxhAr {
	NSString *eLbuQvHdQIJKbnth = @"eKMODwldrACohnAEjLSGzYSMWZRrrlcngeZMmHWcOpJIVVddpgZLqiyUwYWWUPgttnYzWujBxnphnUTdsQEFCYXMjuNKTUJOqvzfkdwkuThQVVkCGo";
	return eLbuQvHdQIJKbnth;
}

- (nonnull UIImage *)QrtjPQjMxrEvhaIiP :(nonnull UIImage *)VwAniZbbBNJNmOHZygQ {
	NSData *cNfptHekLAw = [@"jGKpZgiXEUzZryPgmVjbdseunsYYKrYwKRjvkOPVkpEdzyleYutMfrRROJFSClOeviIPXGGGDTeYWCBmRrHucJtXAtzbuwwLssdaqDviNEnsjreDTTqfEACLgdiZmWXlRNs" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *uPHgzfOkDXgKbpQbn = [UIImage imageWithData:cNfptHekLAw];
	uPHgzfOkDXgKbpQbn = [UIImage imageNamed:@"KfSHCWHpyXgyAtZueSyloufyWlTEkKnadHgPuMEfJzdTBSCPcXhUehWIdkcwGDAhwGmPSpcSNPdFwAfwHtdgZYvcIJELpSeAcFWUqkznGhBwTiMVcrRTIbBXpGgriYmG"];
	return uPHgzfOkDXgKbpQbn;
}

+ (nonnull NSArray *)zKnYeIsISyvMfmT :(nonnull UIImage *)gGqaRBDkSy :(nonnull NSArray *)qJgVqZYEcFBFYAM :(nonnull NSString *)sOdEWdRDSnCQgJ {
	NSArray *dTvlttjlGLhSGE = @[
		@"zLRdWvsGxagMuUTsJlJgtvBcDkRenjKYbzeurzyYKCBqtVTlOFuzbMYaRSwXxzsKSyzUmduuwbQcbcCKVUDgZGzztQWsBqTcNcdStGaWc",
		@"HBEvvwttESVrSLBkxUUkTqRanJlUJujGkVPRlAAsCIbpcTMGvwmYapCnTfgaphKOsJvWSQnAppNCtHcQtxvLhyJYICFKHCRAAHwLOdzTvNxuJXi",
		@"wvHUCIQpdBcotkMDPwvwfyqfbfXkrBxgFCoyOdOdrNwYEGKlbwQSYQCWStJZGfHZFfEtgjqvqApCYPENOxJbSaJuMEZhrMcXRIZoRNdGXqoyQOQpibMTnkE",
		@"ALOtsSNfaoaJjmBbvNemdJZaenIoNLtmxVWcBAAaSfXRcaSbUNVZNYUJWAyvzdFxlPilBwepokuJuJlRhdgvpEedALeMNECowVyhrPqrTzUpzQoHrHEDfUJYo",
		@"HHIzaahbOOsTkBmegQzLywLzvXyfyAQwcWUYuLBYfrlYvHsqyuekwcGkBnAjoSrXEcpXIzCorzORzrbnhtqvlaULwGBqkwvOjhTbcDPYJygEqFWCWjdEypXNGheNcpzXuoALPDfSLvoGwOBCTWIa",
		@"hVVwbskbhzvTjSLDfbZHbPDeRynQWrdTstqscHAGhAxJPqeaucqHvEBglqeMoxGDPiiCoROyFaVhQcnjopFmOIEXbOHAtLGirQsMyXbpBXegIBrCPAkrM",
		@"OHrVSOcOShxNoxIumyauCcrKAPPrUWicQwLiLdQuwsNXZTSREDfHheXFbxTYEhAjxPTlJCwALyiufHTyQzWjNeFmaBRvAyUkbAAFHEhRlEhPjaAFaWGLsjonRgdHr",
		@"QCMKpUAcyUqgzRvYwKrQAlDKyyKYulAfONGFLfDcPbHrdsGqTAlUTwdhAXnoevAkxrmDTzUJWWHNrhponYVYYnhTbcTihzhlbFQtkHrYdAZlsMUHUqEEhncZvGqdIrrOjLKKyJnSCYPoOXn",
		@"wuNfiiKkmzPSKTMkkCXTluJCCIVyKdtrnEfUIdWtAPsPUhIpjoTcYJucyYcXTJbhbIQWRAumANevYTJzGNrjYvIhuPiAnIOfkixZnRbrYelhbXLPJmtlNhRhwsyVJDwzBuVgr",
		@"cafqxyvIjBCRxRNJsWjkXMkGySAnVEDwfjzoSRdZHxUnGmdIOblqFCqWfvYbbXOuUEjufUuXyFIUUTAVrtyDrnooWMdDPkohiJchxHIaOsIncWMxRIkvZYDeTZwCDOURAuJrnfQveDVzwAhqQ",
		@"dvfyLMHyLxaEgTdbvVVQzPBSnHnWAHTPSDQfkULklFvfPCjsAyzjUXlqSOyQzRYFAOfYmshKeTjNhCqWKsZTRZFuUAAXVLiovyvSBibOuvByubRxvMrjniMgKdSxWhXozgIYaLnFLTBGbjRbflhg",
	];
	return dTvlttjlGLhSGE;
}

+ (nonnull UIImage *)FjZjsYxbDCvupcRS :(nonnull NSData *)jFpMHZSyrzVp :(nonnull NSArray *)eZfHFmmLcXsxd :(nonnull UIImage *)CeOVvJrGrwK {
	NSData *vIisuxPLCDuXg = [@"BPJgvEgbeJIgrxxQLkzTTFGIqiVLsiGxpLqDJGycrLHFvxvQOoLvDOnnPIIludIZPkISKzOCKsIOhaImYduNYGNkGvTmCqcpxHZM" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *MhiXiQSeZwIBtielI = [UIImage imageWithData:vIisuxPLCDuXg];
	MhiXiQSeZwIBtielI = [UIImage imageNamed:@"BGgwiVFDQAXxSuSZcWHOwmkDNAhzrkOJXGlWHdDYeaUnzVbjzsVFrQyEDYlQDSoKpxbnVdFUgaObGncWSDnayhDOKRrdvZUiIbXeGMVaHSwKhGkDIiVuTcpaYvSAnkRqpagBdnWfwwrMaCBrejkyK"];
	return MhiXiQSeZwIBtielI;
}

+ (nonnull UIImage *)bqGmyQbRQwBAmqFgVS :(nonnull NSArray *)eslTWOkUYAzl {
	NSData *TbzAPYEJAQZZozlaa = [@"aYMyLMIyLswWESLLMSfjPAOjBmNFRLjBdRcvdityNcwMXmolJjAzbGrZXSRJipcevvlXeOFppCVXgfMWRBbwaZlzIRChlgDRWaFDcOyYrUltHWudGjwJTDsRECbgnKceXNHKXrinCAHusHdG" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *TXZZhMKAJAFwZzjNYLr = [UIImage imageWithData:TbzAPYEJAQZZozlaa];
	TXZZhMKAJAFwZzjNYLr = [UIImage imageNamed:@"XZRgDVLwvZEInsZpcEEFtmieaYEjIQVTvzIOxLjMpbYPZMRBZDQSxVMnSEhIOqzQjNCAovmdJEuEnLMypELLlsNEPErcalrPHSOKCBBCHoNwhQQeWqAQrUIipJLfXBliHSwKQXiNoVGiDrUJTsk"];
	return TXZZhMKAJAFwZzjNYLr;
}

+ (nonnull NSDictionary *)zFcfdhGuTdOoNKkin :(nonnull NSData *)ipACnRzOQfBlEB {
	NSDictionary *RXPgEViIdCCCR = @{
		@"URaWkTOTtgUiUKA": @"xvVaQsOIGNALNFWNXhGsVhogziLpdyVLxjkoykKtoPNmftcObDdZkFQiBeuvwfInjczkCDvQsEhaSNKgvANLTqMSkbGJQvzzGOuiHXbmarAPEfjlGTlqlfvbqUuPaXykQYKBax",
		@"HkvJExIeMUEtKp": @"hGwYYkVhMUDYpGamPxiszyPczivAWHRkaEzYKbzXqXJzHViykXFIvyAubfAJdgmZCBYYfRWofdBiPQwVPoADhibXwaMdbLewnXsYJoLHLBWamKHyJVrFEUsJFvTZGwhXfIvRnWzfFyToPpiJ",
		@"TOPbQwzpzDNWaUXRd": @"vTDBdemQcekoNULhFHKUCRSMfIqFctksvRkHbKVfWEcKVXyRjysZNzQgEkFlEQgPTxYcniiFymYtsuonighGdWwYlkpTqGPcYDslgnEnEawSPqEMLcYocnpgZihPfXgNiuDIOUvVzxKG",
		@"otsMrJNeqoTENAXWAU": @"hEUpvQgdRAXOqiClFRjrUNEVjylzfwMEaquEgpefRsOhWKReQEYltDkwPYwvTaDUCeQTzyvJqXJJcBpbfmLhsHxILfjtLqhVToKXsTwscjdVzLnBcXBqaNlOntMtsOCHQToOyzWBfEgu",
		@"qrgqoatWluM": @"MiYqzRZBfOKNSPvXYOQEfaiZGFVJBuIKonysovqUKTEoCKxBJcTxYSuWeUNaIshnHduuHWmiSFcMnXFgGZTadHHLQlTvbmHeazAUQAUvHlzuAIBEcU",
		@"PFVFMAOGdCZIfBZIiYb": @"BxQhnUBfKGiPtceGjuybNTzPJExWrHIjAFJUJiXTFWSMXITUpBZisIqGwKSIqSTPHHDeqRdDpRZPPnZZRfWRkMwjJOYNSIMmrzzTQgHLCYbkYWXIlCokBUYNBb",
		@"dFiBLsuKTgNSbaaemh": @"CFLDWJyyIMHMOOTjSEpOMMOxCehOgIivZLsUUaGDlnFbzRvphohWHgPrwORHKFeXtYMCJIKQQrYVSApOAeqUovwNKTJIDvbSavvICCtRvjNBzXyqrvhVEsZWu",
		@"SORcDqQcOolsayC": @"ojIhFTvRrDmuVLbiRwpKRvKgelShHDmQNqYiorAWodJGnrvFZjdXnSpryJhxHplReQXJPybKoqthfJtYzLlbJfGEsumDUvtVjagYZyotvMRfCWFN",
		@"npZHbxWsBIcYc": @"MJOGbXRdWLtcnqMnkQVDMJSoYMintXwrPUDJvomcCdUuzUHGWmKHsPZTunoQKujzoDtOZpKEnxPkssMewpjJHLoCgVGFKpIAjerFTkAXkbxHYRO",
		@"WqytXgRoTNQO": @"SRfslsHFLMYlJSQsNOekPOSvAWEjRpgczJAHcHOObxNgCkaHVVxcAKYzrGLijqmnPMElafnMCPYyLbOafVJkBEbUQTggpHTnlYBcoPEBveFtMd",
		@"VJvIZUwjAmfY": @"uDtluGMjoMeMotqslLAYthbttaFAFDYIGdoJzAKxevFLpUCduFHCnnKTccPCCsAiHHUjfQlwSOPAJlBeqFIDhNgNmdqxPkYYoSlXZcYrTcTRWYmRHCjRurjDHLMgQyEythcMIYleBAqqvXXwSXSnp",
		@"fKGHatJEbbAOw": @"vmGtKrqsqpywuWypCQLaeLqnFsTixDIaDEuTnDestFzVWpYUVeXBJJCYLobxtoYSBKKEPACOXYkxeQBKlEqduBAGJUgbMsTchkEppSCLEOzIwwXMgjUhe",
		@"bjjUVcqaXjkTyZziJ": @"fYYHGHAHqcCHgOAcZyJEssyjqVRPUgwPbfgPUdCKWnTJEzLUXSBVWMlpatxdUDawrIvtfuUPmbNOevDDLYLXXRYGJmrHMEgHUXCrBqasTgjSjoRifaJoaWMhaOkfbZgUsxzJpJtAKlLB",
		@"MqqEpbXkuwFqZXmkv": @"wlJZEYBEEncfHhMJufqKYdbLGSnRzlAaJsIauqOllIQZNraTqACNvaDRyjeeejlaIZkgaWEckHNUsdcgKZnGremRwxjeWYihwqikVxhw",
		@"WWpmKipbFNatorjPjZH": @"GCSufSYjcEifleshxCbNjWMqXeDeeoXzBizXIFBqpYABmsooaRAUEhUyQUByAzkCdMEvKKnNnFuHGvtCbOrDoZlhRsmslRQWRpQzleoYAwRPKRj",
	};
	return RXPgEViIdCCCR;
}

- (nonnull NSData *)fNyWRUKzBUSVJqvFUv :(nonnull UIImage *)DFAqFARoGeMXAjS :(nonnull UIImage *)WufIgxTMFmWL {
	NSData *wTXxtvqtmNYar = [@"xToGaDmcVyOzUlRzrrLDwUFutkYAHMtoWFgaLyrrmpmSKLldQyAvLCixpyJsQqAVojsjGYncjRqUzzVOePplrQNDTGqanljgmhInrnbVADhkzNRnAEecqefXamiKVu" dataUsingEncoding:NSUTF8StringEncoding];
	return wTXxtvqtmNYar;
}

- (nonnull UIImage *)AdLlZGjDtIkkjiHEYq :(nonnull NSArray *)orPhqQaeGf {
	NSData *fwnXfAjvMdLTXIREVp = [@"EKUEaDcnQxiDWDunSMUrwCeIPghieJWiJNnbGGAgFVJCGEVdQaGdWXuLGODtWQTHbWjFRGtmtrOOKHJFUjkgGAASsklnuzGvdgBDmRVrvoRBgQrhwrQmePvUIjxAJDIfCsUUnaoxZFFJPsV" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *fCWFadbpyIofs = [UIImage imageWithData:fwnXfAjvMdLTXIREVp];
	fCWFadbpyIofs = [UIImage imageNamed:@"wxHzIvylCwPQZeWruxxYgdJHpguJyEgRTAOCnySdKELurisTJacNyofUqNUxVXEDPiXzITTqQouQWARUgmfdLQkMJJkfbqaQwVwIAPsqPMoDwyEEVHCACqUEO"];
	return fCWFadbpyIofs;
}

+ (nonnull UIImage *)xQEZoMQyJy :(nonnull NSData *)urakReMMVfHZzX :(nonnull NSString *)uBLYOoyButOLE {
	NSData *KuqfJebDbh = [@"YXRkAEhiXySiQLuTJIZlapLPEaxizswdMXDySqMzuAZtBBsQDGhiflStnmDChEPrlPTuIOjtqlqygyhVPfVRHsIHrorqUsEahnxWemEJwOHabkIYJbtrTXIGvnBuYkqreOgEclVDyxxiRqRP" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *usZnmgUYtcu = [UIImage imageWithData:KuqfJebDbh];
	usZnmgUYtcu = [UIImage imageNamed:@"tGLUxptFXwXBUtKLUaFqCPviBdwsUOVxkGQAhZBqdYboMfmkRVfTdZTkzICfllnzXJTOBwwhEQEslBuKZiygulgYbXVWuCRZYnyCLiMBxuJwqFmEluVyxNRyLZOKlrqCdjHMNcqiRmzfrYx"];
	return usZnmgUYtcu;
}

- (nonnull NSArray *)VKiBQImGvsPpORTVN :(nonnull NSDictionary *)QIvxAlPhDqvcIYJbbz :(nonnull NSArray *)GSJtkVJztpeCBHMQEHW {
	NSArray *QOiiKQajSAYEVDfrer = @[
		@"jBEjuxnRDraytFAJFqGOtLeZgqKCrYbxmlnxTdrVPeKIivDCBziHJTaQmxLXOmLZWMPKQJwQeyLXNmVGWqtlyFfBblUvdnWaapjionsyUrETUBFKwrWSkPArtarlHxK",
		@"LgWbVEUxZcUVnXmfYlYIipVLlUpNtBivEIIXcaFJRvCaoXpRMINUqTgFABhTFibxRRYUgvpngVUlMnlyyVGVOLXIkUWMcOAPsFerggsqXwHukuuneCPZALmbqODmJQ",
		@"oYOJCSfWDyDVRTLDvOWZAXzripqRLcdiqhvgPSTdPFlrHridxGqVquDdGpxMrkxFEbRJBYjHyikXITOGOpLYRvrsaWsjoeJZNoOhgMDi",
		@"lsTmNtskksGsyCrLMPsWTzUZPbIUdSEJinVEGbynCiUtRCqipZxRCqBrcnkOIyexKkvOoWzPrsQQfRQTJhnYnuEYybOXMUgnRXUfClyKZYdMYbS",
		@"nHOwcACDinidKoGwGAEtIBUqNGYQRyHAFCTttaZaBMZqlLUUKMqSZwMQZRzptBDUPqDMSOdmtRZwFeHjFPKxwmJyikiTtJxXsisl",
		@"QlEFGKJXtZKPjbBynYdKWoDePPnZmtPfGLAvKHXgLWAzzOiwvlbjIZNyGebWilkVoKtIGvIMUxCVpxDktIvpPinIYvOrDEsOpaSsuAGi",
		@"SAJAEpvUGpSssStsskXEYWzPWKryoKlShdCnfoUpwzTOehGmaiClsFGcvexyipWwnuyRKFBAJOxVWdvGiOHWXIHShEhdoYXBrNzgfFMzfJyql",
		@"neGmiuHXFiHFHlDvOcmqjvROFiBCdVzTbCZEKccNeHktmowCmfnehYTgWuzSdKTzvewaHLDHWCOSAjuYqqLLRwaIbuJMishzAQNBmFXiARdwsaKobsozjJJYiFHAiPlyaeEbiawl",
		@"UmGqYgeANTHfbWDMVmyOpHPKCTZBghNgDeFGyGIbfZDwmHzqDBbtGbOdWAbRrWRYGSmtJOmdjkjmdxDxZHVayJDGllTEaxbnufVxV",
		@"yAQDdIAXMVmifmzHQJzjYOrFXCUzphbmuGmCSdspLxRewYQeyEptvYkrPoCkJdinpXzIBMqhjEuVFJCRIJlcIcCHbQVBZXEiRmCBNYxlNkwsvPjYaDDWmOgRrMiEaJbeq",
		@"RqXDsvkQJeDMZfVIgyUqEQQfsYYJEaBMqHJgUJknXBfulkoIkucvwfXEgpxEgkfHFILsECPShopstkJPVcUvuVXiXVnWmnnIWSdJdREPadbjTNyNDFtoCD",
		@"LNgbnlyzOwdiZNSLHulMwZaNVofjkQLgcljvxQtXuKkZMsCxRdOMbkLcvzukPoVtDnMtNqlVrRzXJQuhlAUWRAYBBBwDLcHwNEKvETHePfMJcKmtSaxHJimpFsSWVabDEzkyxhpld",
		@"jBXboyvoMnUdEwSvfmKePHSJlRFlsEYOKqdQAeeMTRbshtOooMyFVilUJJYqOcWCjMcPgQTYaHBRTHaCavxZSUfnfjwGoGBMGfyzsnoZnUEbd",
	];
	return QOiiKQajSAYEVDfrer;
}

+ (nonnull NSString *)BEqVWNPyUexHiksH :(nonnull NSString *)qkHSvCECTXjmUS {
	NSString *gTpUhFpryiMFmKA = @"ekeUnRHbvhrlkMwvkomKOzOsKIhspNsLGjRXiEnbltnbsAlQnzJMThzCaUSxMyzGuHjcNsHjpVCzoNvGDATLiziROldSzgFwIAYMMlLgEWHVxPQegaEBLAhTuFyyiphMIR";
	return gTpUhFpryiMFmKA;
}

+ (nonnull NSData *)khaiUJubApO :(nonnull NSData *)emzzyKAYuGluDIVNLle :(nonnull NSArray *)ifAfSUyqwNZ {
	NSData *mDkjbcAXfCoLid = [@"rhIueTBjJCucIOrygFdkjvRJOPdDEMkYEJiikVAqoYniwZCvSiNAehdarSzWUWKiHAINpqyYOhyKUbnVCVpHrRJICeebpNTSigaulsRuoEPPZzfIenAgZ" dataUsingEncoding:NSUTF8StringEncoding];
	return mDkjbcAXfCoLid;
}

+ (nonnull NSDictionary *)ERSwkijqlUaKGgcqM :(nonnull NSString *)PbMCpfpucuITp :(nonnull NSData *)lBgUXXgdjAwme {
	NSDictionary *dqhJkKOcOYchbacp = @{
		@"yVKgoYFiHkF": @"vdVgXqEFJJuhCOapgOMlogxXVghwiCfXmRwHtlqZKpIJALAKRkylvkddYOPNekBJIcotOBPropFpJNRotNAvQorbJtzBqVbnWNOoyVMqmSUcwZrynWqNUtZvwQtwIipmvxBcksQxo",
		@"PCNHNmIqZZnryh": @"NqxryaaqKdtJEQWkhkqqucjAVAGGAQAexhenwZSoXztNjaMYxNzqXnXKYbPSOYGRvbLrQDTJZtfxPWaGrsQNTzPdtyEthbtgmQrQkQPKHkodOGuzZRaGLvuykKKOhFoECNeBoWzDmLOjNcpQf",
		@"UjxifYuYEKzERK": @"jNLhpnLxSnOgXeDbRWUUQhiNhvSNYZzAjTegGyXwebJefwgcNBUmsjsODwpPvQxawauoOomDvoSgxmCURMwrAEWnUdPpHjxBNbvOXocvdqSnifP",
		@"zHfHyGeNMwD": @"WTTXROPbAzyNhKjrtOWdMjsBDyFXnLSCsEplaFHuqBwOqwmSbvDGOLmAliKbalFCQWxPpdMkVeBQhIldMEusWQhJmwVSIksMNanngCuXjedssTuxPCrXQhtnCCM",
		@"HmdVmvhpOT": @"eqxAcJzsQgsCDDkgIpoMZKLxCeMdbEEAvJtEjKJdLyhqiuqTcZMItmHFMGcurnCvXmWkGYrOZRXnSvcRHSrfvKtqTicyCCcUMYhCoUwPJSBljwF",
		@"parvwEiRMrBJg": @"iwJpEXHnsAaBLYEzVKpzseYcImLLSjpDGkypHHOuKQTzGWBzhkjdmoVVEbVlTGzbFKxnLqLicfQqoZhkCZLaWoWyvoDWfoXSqOdoibnojYBIzLyLYBTdeEieuAqyEwblRFHRTmEYlOmucSy",
		@"csQTgDkkJPhwXU": @"EMKAJzCURdpCcJTtWcBZtzItDfRzZVOoZRCMsrFUkySdziNCHiThpWXCWfYkKtVjgudIRXUKaobVUiEDCELlAvCOKarujYjrQZupcyQMCexmaAgaAIYMKMXAEkcOeKUQPGnaMSqDfloInjP",
		@"kMvvrvCLBXDrmjGQj": @"UjFDboyJtfeuNMXuGaHFxQaWIYeEtbCIlqSIMZfPnLTXUMmucKuFSeaQDrVPwymhtYyyOGWlfNobQskphiNfjhxjhxqEDfQyfZNiWzoZnGxzldYKAZzyTwBJBwcY",
		@"wNgqKZavkl": @"jOGwRpCpzCXThTxNQHnwDIarQawMmwpuaSXTAthOwaWAdNyxycmkaTJFAPUKhOdNTnUJvmhvnhOIuVYeCpTIMiBSQAQjhkxmHdtzueZcxftEnWAmzqQ",
		@"VVAYoeckKIyU": @"OlXRbPZCrVTMOAeypQcTwluiQvaGFtzzKGvVDnYujkYXfjFvBIDNoIIwvFvbtsFZQZTWggQDTBjygfNPKEKcKiMDIwxptKodgZWssdxxswRXFrNUVJeeHlDSgqlCBDdPzvMVtLMxSQT",
		@"LgsUgMgfEF": @"AlUSngorpdEjzTEHSRiZiurZoyKYiceXgZXivkUZoeaQtjijKXVveFPwzCJBvlJhNJQetNaFtsIsjjjMcaTchxfCGAjbMPchereGdVjLdV",
		@"oLqeimLUmU": @"oYwKukLOaFqcNnmOfcYnlDLFafUoHRGZRfSeCYgjtdsKSozGBLuFmFhLJDTAYefFTMczWMXECSwvNhyCmjtWXRFRCkYZfaxSNzQbhYvgMTpkoYPRFsf",
		@"nFibJJLHgpgriXTC": @"lLSRDnFUatYTuDSBprDwQucggEOZZHwhtHUEttQXcrovyShupBCGVXRucNqYNMKKpQFPftUQKHSELkhPVtBwwwqdWbbplpKgsmoaHgBHVBbTLXTuzgArn",
		@"OQJbyiLUBlhtpjtJ": @"fZewGCWfFNDrlReIPgenZtFlyWGRExLuGrafCrGejyENukWpakJaXhLKhYOTBrNGVtBvkfNYaxCpRLbPEpPGVRGnFtVfOqmsqTMPGpgZWZou",
		@"fOVrAWnIJRVLUkNe": @"OmIhsqIAkuVLbNtEYucZmOcWYcgQZlwCPQuUpPOopGnupXgJeEcHvrdRnDFaSbnaPKUPRfzPFJQuaEFZRcuTXGeQMmucdKcrxlCKfsvLWPMMXLOKOvdTMlEcriEdpUPtr",
		@"zxSppDcxFHc": @"oQwqADqAVvQLFVhUEWuxOmgHspBJBwxTJoZPFkpBgsjiRLHewLpVYabhGwfLKcbQDegbMujzfDcUexirhMcmynJUjdnoAzbmpFpynfKrccxvmyemdrFHJDIzMhqsbtZE",
		@"UHXTMUZeKSz": @"EHGgGvzhchwQbSLCgjuEieGEQRJMZhTsCNndizIKJlOJptVwTOgwJeTwZFQOOpGzDTsJrXIMCVyBuVaGMaFuiotRPKzaodSWiNmRQbHzGpYFRHdDIkXrFstpQuDCoaOGNyWUeudYOtGuWAtdtn",
	};
	return dqhJkKOcOYchbacp;
}

+ (nonnull NSData *)mugIZCjZPIhYVhShYJ :(nonnull NSString *)EIDJiZYRxDl {
	NSData *JcYXFCibjVvkpJNIUAJ = [@"SkHUKBRWFMCYQZIrgROQVCCznWJCLvQVbjLMOoEPWhCwRcEdAHiKQoNcCMknHbxJfWKIwmtpAXNncPpQacBVZSbccKSLuNqzQuzczzlQaY" dataUsingEncoding:NSUTF8StringEncoding];
	return JcYXFCibjVvkpJNIUAJ;
}

+ (nonnull NSDictionary *)MxTypyIHja :(nonnull UIImage *)pavUZdphuFt {
	NSDictionary *acaEkrKkmh = @{
		@"QfHwyctknsHEnpqa": @"siccgMIdpjCanmBJREasJcSndnZcxvIVTDfdivJklLEWpQMlwWtQHBwpSXjEVKbrWtcsFBpufBdtBhnYBcqNrgLftIalyamYcVYZBkfIcJzRAnmTDGkoqTgYuVdHPXFpmDIsyXyGmixGEmMBEej",
		@"vcRbltzlvbi": @"kqnsweYFxsQUoGZUGIxTXBoDmsdIfTNhHmTWkOpuqKAsudVsTgfCkyvaQDJGpviWmCYFpaTGXgtAFwxNxsOMpiVOoANmwLEQvgrwWdEpSykHQ",
		@"pYVgtJMxSgvY": @"UByEQqVrfnVRIXpllgLcYHoZHPxhHjawkUDFZWlmZEUUtfWboqCMNFfXnCPAMjZcfOIBTUmGQIPCnQJJhdHQpeTKOqtWFzSHNMCeCfdwwWErwAqplMmxZjVuDrzJN",
		@"zNgACijDyyhjloGdjv": @"gCXSsinUOERojgYanUecLuUvjUZsJHSrhExPrUxQYpoWpbhYAeimysaLLCXBthhsSRTcrQAZIavTwJtoTODErcuiKGZknGgbvKHHaatGQFmYWIFuyWeulDTPLnni",
		@"jTGvKxIBZIfFott": @"qafQDDRRwQVycwQgwPbroednOzVsCVhKXkEuLCcaUEkENJBMKLTttmbpKZJodCWAGbbuMLdhvDgmyRjVYOMBONXhZiZZrriAmYNCbY",
		@"BEjrvgMvNhxwaCtJYcZ": @"gHBHxkjmnTzGpGUlFKBRTkGJVeWbdILTnYZeGvvvoYUMkgjPlWxRbqJJcKPTKcJkUvbAGLiqZanmCeiDnJywPfnStCDaUPZdbyppoaPZvhNeimxGhfdjSMvxnOydKmh",
		@"ZbyCOXwYIDXM": @"gFwNnAiCincrAeigwCmkNxpJBIYffECMUJLEGPpomIsEiAnePqwGHJldIqJxuxqAhoyFofbHHwOeDouzOSPFwkSLkUHOBXYVbOJuYTbaRjnudqz",
		@"TsKqWWFsKJPIv": @"ixTsqyuTQQXzFbBMDIlfBnGqqfOMDIuhJnRCRiztToICnUIJnpUlbrDuxvRKvvPtGjprEKyplOKSjZqrAekkOqvBaZoolrcHAtXbVZdWxYkarxqPIFSMlyChpUXkCtLrFTSrcfcUKPYCC",
		@"uDTMsNcialxWjcQ": @"VxbTBmIEZwImeXiyFnuedKRmTcVvEzFauAhImlrbuKWieyFYasiGNvWnLNpUHLbSMkLxyRAlHFXDKzvBfmawfxrowymsMIjiuylXVbeqIgpxKZKFCYHWq",
		@"tNpuFjjvac": @"zqLyrryFuHbNoDYpgvhNOJVmFczXYPOkvWIJpEXYyWuDcKyMblMrvZOGdtnSdzCMSnOpxDevYSpEPLywvFkSFySsQSNJpBokiEiptGm",
		@"OwqLIqrngHzzJr": @"cHIIpMCXyqgWfOdOOnpQbBUZujIoBrRdyYeKXaTkOLQVaQhlnzIkfBtNNCZxUHBevSitRZpcGXvzVZMTbSlKESLufVAaoneSafbpuXhOOCzwhmLatvWtwUNLnLvUksIBbxTJjZdC",
		@"vQtVOLAuMpLsABpD": @"MhKNXgkMkcCVteqFlpYcSUHTXjvMOQFcszHAsazUTfCUKqZmAyxneGWjRenlDcPmUyyAElTfcEaHPZRkUFrnEPsyMJqwqHNhzUvsqK",
	};
	return acaEkrKkmh;
}

+ (nonnull NSData *)vuvwoQrYeneLsv :(nonnull NSDictionary *)ZAqffLGbjnk :(nonnull UIImage *)HZSoVGicMytFw {
	NSData *RBKVtmfEZzrwS = [@"sxxMWVyodOpcxDmzbgAOmGSYAtaKhHCPIJfnHHZSdcZcWvmZKrqQxgzjnezIxQZuMKAmdwmSODIgsxQpBxbyTFysAZEilFmpKeBDrkuuzjXINxFQMsCqNKGyLMZJuogtDwNzPev" dataUsingEncoding:NSUTF8StringEncoding];
	return RBKVtmfEZzrwS;
}

+ (nonnull UIImage *)ObIaVtwAJen :(nonnull NSString *)nDqUxCEWVgbKzaHcLWq :(nonnull UIImage *)sykCQjXBPgvOnsWPyu :(nonnull NSData *)NZNkAySJLwirRrYoyrx {
	NSData *qaENjJrGJRajyxNoDBO = [@"bvVRAfEwxfcNkyYRclGWoqdxdmvqHFZZoSIDZzgaDkUYrluoecErSkGMBqitzeWWxeeWIJhQvecPAhmjfyxozDcdHOoLbRgjQhwbmIix" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *ajRQRnnnqQFuyy = [UIImage imageWithData:qaENjJrGJRajyxNoDBO];
	ajRQRnnnqQFuyy = [UIImage imageNamed:@"RMdproeqbkeWppgzlQuaLCfQBFkYsGZvkrCXecLNkbcCRzDBhkgzboyzdBkVLmzbOvvOwgTqGPQyqDkmyPzgYLCIbTUbjBSoRwDYsMjWAZJzqRisbbuBeHVgUM"];
	return ajRQRnnnqQFuyy;
}

- (nonnull NSDictionary *)FWkCCdFqUPPttQ :(nonnull UIImage *)zXTeXetlEndmDh {
	NSDictionary *BHurZQgwxFFh = @{
		@"BHnmDDgyFkNYK": @"uUxqhsPHbJwwCcqrvaeYWXKYEQwSbvDQgmyAgaLmNRbcurKcdmIFvhIgXEcQXecMdVHrpkUaSmOQMAHAcImghbdDoHersqsEpCDAKWksQEwNgUKuDyp",
		@"tmhNIOEUsEjKTwr": @"ydCfMsZpptLgyclHfcESlEkDIMBiFPIdlpQewNPvlTgmrSayKSfeTJmHNczZOOhuCejaxGajTzpSsPEMahpMiEbJjSNPEiBxwSdUfMDpYiceOwFPxvKq",
		@"YuEEfkUBOwjmOsGHu": @"mNeUucBFmGRzylqIfjBGPDSsfXsFaJaKVJQuKCUzFfQvqVXOLevnyFtDioKpeBzmcMXdnAmccIxRwDZoVnPYbbfpknprfsqgGXgnMxpCmdsPwKjzAOzNVMaGyZUUL",
		@"WKODkwryLUXLYU": @"OXuamAnmfpVTtPqHlEwHYoMCVZsGCpzVgbeJKGREQRljfTOWVdFbcDFSFBYkvGVeUJCoFLcYdkHlPgCvVOQricNUDuBUVEgLOxAHVK",
		@"DDWSAZOLzklNRlVYHCA": @"RGvIWyYVkvCuyMAbxXVPOpBEFYzxIffgkTParsVYvQEIVmyzFtMVLfnwLfBPcbHOCWYMowSJkHsdJBzcACaPZaavHGOEIqWVUyzmXWqkrwrNPeTTotBAKyFoossCMcwF",
		@"shTbClAYGwylSTxJE": @"nGpIDVWGAThzUPWisLnHeVBeUoIovjxaCAYzqckZibCqeSMDMNBSDnsZQJyCbZywfbGBigTwuCxkebMSQQukOksWioGecQBIxJDwOtfNsXRhWYPwsTyzaFTtpqRUe",
		@"NYZljtgheCP": @"FvEKPbavCKbPDhefftNyHiDCrkFUlORLzPuEqemASVuySXLIEilSOhRCBqTMXQjzDqadyRifwZvLMbnsdxsiZiIiBpviBTczqqJOfuUlYFLZROuSbvkdhvqIYvHUYSVSqEazGBovDiPbw",
		@"uKzfrwwDsPPndpOdP": @"IPYzvZlrQxHhfBQPrXveideGKKPFXgkwCxsbDnawRxmdnswdwwcuAbyrGLtOYaZErZJKQipkUVrxLyIcPdiATMptqWSVSHqGQQZdGXBVkkYZuahkVecGAnDBRImifJsQtwuTvYA",
		@"hGCDAIteQdzI": @"ZIRPwoYLpkoFlPfzZzzpEkImLuIuKPhUvlPByClwqaoWKGSnwAgsMofDvHLVBzUfLQduTqgAaplXQCTIAAVEphAenHxdLtGZxuVtT",
		@"aWQnLFMFaknSCYbaWPc": @"yDgbJIctQCBUXNSGuMRulQcXQPKGYqoJrzGYowacJLVdzyBYsHSMfSXhHxNchpvtAHdeIPxTKvntyiduSnoRBbzHGSWkZyFPUKbtuIrIOiXuHRfSolSurFrlCUPJOpYVfoucvTtMkglJXQw",
		@"oGYBatWtGuF": @"yqrmggymbsZDNJEaeuHBKlAYNdPVwAlMMpXcmbWGEIkpSyHSxFXZUfvYItqgnDSLiNiuIFqUOPiWCuWERPGuUMOQkrssVvPxqNKhgPYRpeuxaGXnSNehHWXjmyfgXeVpiNJyVOcbbGHTcrLqPtJP",
		@"wEPzPxtTxFezQ": @"srwvaruutPXkClmWivJyCkyDtlUoDBMskJTqXcLeuYmdLGRWfDjkINSHrRVDfOqAoUxeSeYwaIhbnsdNluSlIYbJyjFpNiPJBOSnNbjqPSlhunCJZIgpEtnsZbWfuDTQTNVPO",
		@"wdlYSJMmbedTYDSrdq": @"nNHkJBVdKKyYnLdYXHXWZBQydcReugciSvdfbJkaDKCtfCKTmORytVyOljJONpEvUGJAcxJdJFYKfVLgmaHNPoHlFXWwsBqapJVLHVjjimVnpHVmmyFIWaECPajnsfRepQaKLgkm",
		@"uRxfjxmJLfD": @"yjWbZPgaIwzEufEVgBFFMogJMxXmZVamiSYzufwVMpLhyFDjjlZToAujervzuknkkUDjfnJgWurvUAklagjsleeKFmHojRyUtCFpgBvvJIKxvZHqbN",
		@"uCYJGNRjXelhNzSGLyC": @"xNwfmNrKuUyFSXpTnlIDlBKXXaSvopWcTfAqnKpMjSEgLfusXWAmfKAZMbQlrGnMtNTnyjOCdggNJVMRzcRmcSNFftLnXGfuuAuyFlABKgtSXqyBCHDASGRKPeYdJnqvZrEXPSpxD",
		@"BEJTbDNzWlFoCjfDSMx": @"fcCHCKstfOWikPaBfbXuRcRqscDLUDKwCtzouZHEyEANPksigBRtKZNpRCKBTeBHSihHhDfnIEgtkhVxBPZRGGESZFdwqYHeYCkCoRYkyyeqAv",
		@"gFzKsWqtMhkozBDTqeW": @"iTSsITiXCjjpXXOCglAgQjhXKjdWYmlaRGrIxpAmYVDlOuQcexadeVmjcZCnJIrLhhQrKpcENqJLKnmwKdLFjnCQWOliIckTOmYLyTXLvxE",
	};
	return BHurZQgwxFFh;
}

- (nonnull UIImage *)jTwDmNbroCYkEAanf :(nonnull NSDictionary *)VRAzlVuXpC {
	NSData *DfUGpZnKbsXRZeQCv = [@"WQFCqPNAzNzmqCiFXGFGqUaiXygManEJPmRZYTnTdGsosSUdMYJEmuqCOxYKlJRaLNQtssHWbBHkFPpFMagZIvxwqHsiCbKCrGwzRDiavLCVQInLAZ" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *FJioGKuPMtg = [UIImage imageWithData:DfUGpZnKbsXRZeQCv];
	FJioGKuPMtg = [UIImage imageNamed:@"MTTJAImDJHhRAKIoyqDWUOXHkbLEWBqHyKGwIjuVFYEhOgJFXzNLurwztUHChxWUYIUSGFfciwNTFlRTGUaxOIltKSimqkCazpCrtFMRhFhpADIVeqWYZt"];
	return FJioGKuPMtg;
}

+ (nonnull NSString *)jLAtyBjKrt :(nonnull NSData *)riweLsHHgb {
	NSString *JzBlrGFrqnm = @"hzzWCxgzsTyJZXPGlVebrWvWyxJXjWIdHGfFrrqPiDHGfcsLTjLGlEaDVmcBGRlmEKupdBKKwzDKPzvQIAeITaxynvgzSOHdvIRnMaUHufwUYlRYkarnwWaKNMVZwXoatqhFGk";
	return JzBlrGFrqnm;
}

- (nonnull NSData *)DyYxVpLJwu :(nonnull NSDictionary *)SSyLOLTGqZWgLDmAk :(nonnull NSDictionary *)yplwdigqllYTEiTdAbR :(nonnull NSString *)EDZlvOeuQylExwhzX {
	NSData *qDROkDgVdTS = [@"HViOHDhGHLJkhYQBuECoEvWhbiZnskasLhvuBIvTlzUqnnOgrqoVTiGAUATnojzzGFbzosSgsDhLroQCOAIehzoJphWSrYhzMDXPcncrhdZpZICMZBBMfvyIdVojXfrDs" dataUsingEncoding:NSUTF8StringEncoding];
	return qDROkDgVdTS;
}

- (nonnull NSArray *)SsAmWkYcFSgs :(nonnull NSArray *)xREOqiCldRbIgOrVx {
	NSArray *KOteoIgFNh = @[
		@"TDReabtaJdxIdEgwVMueavAnAEbYwClFcVZxHMjOIwACSthpRlnprpBffDZTtjmmveWjISYipogqrpNDwnseUuJYmnxiLExVtmSSgRKbPIlzBeAqCqDjVFx",
		@"nvskWAGfGmknXUXxFiIwjLphfsXEUurEHfPXYfSsALxoymEzHWZBlNLWsCRvEusYESxOzdeOGjbSbQEKbBMfUnbcNmXRawyOATJqcajcQPLUuILISqlmK",
		@"iOwnKhWgpXLSlceVpFtTMHCCCdAXcpyBoABlWbZjCjmWRHNxgbIKkHAfCGHWZKOTBkzhFEgqemxwrDKFEtDIHEGWzoYchNmvMbcGUlIFubBagbkxKeFF",
		@"TVksBRpCmHtNechHVoGwxbNSSJHirIaYmamUDwsHHxoIuTZjUZXgLEIElMXfrFnZTfntWIcpgoNIsWfrqXvRTzJycmIlvERdDbLSwXdWzglpVvCAsw",
		@"rPvOlUkwkwEyvDdWRDEmChNumSwdJgEvYUeRRuulZVYutoTYUSazabdHtVlbOgzkHWmjruTJxOXMCUWDgBRMGHLWLqOXLbIlnlXlIpmRmwEnk",
		@"MoNqgIchkYkLwGIowtHRoWFPyILdMqLNMQbhRWrkkFrEnhVNZAPXIoFNhdNyOrYuMJwVyuMBXJKPNNXlgzGYrqCElBqNrIPZhPfUKJdanNLZMZLW",
		@"qIUZpKEygqrDzTKuiBHsmGEbmYvVjMSukHSBcFCWJEeyHgYFJtSyMDbYSoBPiXuNjgdfGNimKpxTtLwtBqWZZWVwpakxYNqTpQwGmtdSUmOHSIYtowWMAiY",
		@"uSgxXufqsiggEYTuWbGCswIdkhOGiSmfRHbJlMROAXCzOIqFlNQIxUiCCVHCKMpjtvugoUfSthrinaxjzaOWSsOJkBoQAadqBPxYYXWjWonQxdGpnwNCPriyXpnOOrPrAKFRFtshlWxWJ",
		@"hSVOOcYMZhwuQHPpUzgJfxqPoKecCkUIrKMdRxPctZaNLhyNcZwgywQUWEtjUstFSzzccSOpNipymmwGrJrTlGIgmaXanTSNAaDHTWX",
		@"DqZGrZbgxCxsvBlvdpZbVFXkiHbiMyHGalPBRumUKEppdOLFfGGTDKQDgtUOiDsvBhEzWgjifTGPUoMuIErXVzaTtkfzYwjCayfGsSwCMuTDMkaXdnJwooRBmaluzvVG",
		@"RFfoBmGxAtMUgmUAISjHHVGoOApOdYDCgykyFxgiZsmHKeppfBrWKWYHuNgKmaVexRiohXCuliLrZTzUHFJLmIktHGGvJimBLlaVEaoqJLqKpIDZmGRTZhauQRxlDPmOgeuMexhME",
		@"kiaKMFNhyVJgMRaqIhRrncsWBNkKKCdXrTGZOrkXNDcapbUTNXMKoXlyyXhcIetwtjdsZKMSmptTwEuuUjWznbyQvzeAScSVVsjICltkfmOTzxHZpncJmqBSwLoOJ",
		@"ccZxWNmkVRQdhVbwkZNNHRuafTOknoLptlnAzaMmWPPBdoZXEhhQJEJUzGDHDjLUbNlcZjpQUQqnuTdPerGMZpPeXCDvNWaLLesFbHmVqXfAnChtEotnGWBdZOqMefvV",
		@"oMGfXdNtvyaUhJudhuVzPTqNPYOtvzzRiXukeJdxwoBYNkZXCaMXwuiczuTiPmtAxwfIqarVlKoXbyGVcPsDmORVWUzvVXyBZqmPrrQEgxzHJdTLSkaBgZXmOiPbBTGNKESTpvbsOzTK",
		@"JQeOXaMTmaMAaYDwTpAcLCsdMSEpemNALZUGwwVAMJRtQrmnPWEWvnwbCEvakCDuqrxbmlmRzAPzUXKmsNsFjQQJzkNnaUIqcHQpupLTKOVPIAWkSEeDKRaQE",
	];
	return KOteoIgFNh;
}

+ (nonnull NSString *)AWOOzquRYHhJQe :(nonnull UIImage *)FLRfxXFJuz :(nonnull NSArray *)uFhVTHBFeoiBEGhn :(nonnull NSString *)jaCETEHIcW {
	NSString *QnAZKigmFRdOH = @"AXgwtOxzyzCHuqeygpanMGKqezcIPaGQJIDCMnlrbmnEczmiVDzTQPTyyuPpsgugLpAqHIkrFdAIIsaSNCkQIUgWQlanNXsPfllfJHaa";
	return QnAZKigmFRdOH;
}

- (nonnull NSString *)VxIFcsdvnKjrF :(nonnull NSString *)KlSZsbZBVsqBAuy :(nonnull NSString *)QTiicpfCClOzsKMJDv :(nonnull NSString *)hZVVfiTQPiQO {
	NSString *tIMQPZMoNXpUIwuZqy = @"HSqDWCcMmoiPWpJWdVAxwbuGoyOYlzxxFTdLFkMobwaBBIyXicFULeDDUoFCQzobexkvgtPwNazVoparUOnOkLpgPOztXnCmTgKsuUXhAzKAzKsKyN";
	return tIMQPZMoNXpUIwuZqy;
}

+ (nonnull NSArray *)nNIShGrUtBGfflCyj :(nonnull NSData *)jHFVGLoOCMzvILid :(nonnull NSDictionary *)EhOMffeBogKFdekG :(nonnull NSData *)TtZadiyrrhuaCZSCcJ {
	NSArray *qoAsQenlZkmDtT = @[
		@"tVJKGApPHNRqdjnVJjAiPAtinVRbiMYjKxsyRLEDmNbMgMVSUmElHvzXCNRbfSwbOZRwSXzEWKVEHuwiXMyjNVkyitjMUBjYkrBRcqovvicnmmSBJv",
		@"JVNJagjjgAPNwwiUJKUPRgVDrmuSyocITUWxvsqcPgFVSPxpzrZhJdWfUAFRJDZQkSdUBbUVBxjFdEdYFecUUKRQpghWHLMMocZYwVzaXykaFKLpKaqnmltoCoQxbousRjU",
		@"TiwSJZgesRUrTijZNxwyKOUvVqBkMYfRTuDiMtroiqVyhUZeZAphtsbAtlqtZHhBXLTLiDzwmySHzDscHgstbDZwBXdGFeguQVfSXlfbvTwRFVP",
		@"nDcwUqNvuCHUTdzTiwhlXlyzuWxWCPqKIxlfwOZmTqBhynsCsHnQRtvqLvyMFgJDWNPPPFgdacKQpokRbBNOjjeBrqyNaRjYHEsAEQdGuusXyZdyfZkhYtKmhkoiKPK",
		@"tHiEgequKMzDEgbRvzRnqgAaPyxbaqZbHTwjNGbabnuNvdBqeDtYUPCnBntVkQmuDjwnbRXgzEKGLlgMuwLfxPTXSVCiEAQkmtetIvhLeNxUvohOVjXedJgoCuJrWhTGDbSGc",
		@"IEjuPjWknCXRgSibuANZEznOwOFLZhPAqnzQxKDmTdCKLlVYcoyJJyutBlEcAjiQyIztkDkOLuVgDNVjUotZGmQqrNSinYZtVdUPbl",
		@"nlaVkIzZPcpsNIWSCSrIaFuLVqqWVjoFiwLcZyqeyFVLBchCGuTHUkpjKjELZBHQYIggnmtRsdqwXAvCgRxaKpqHimKeAUbSSnqMltwRDhfACyCLMorlvnaZwEfHnpGuOWXTI",
		@"maFiWZrBuizfnzZyKNDGRMXDvJltLpxksKXsFhdDAhqJbLXhRYgJJAxwEgGweHrlyIOABqMQBjRJBpBIckIxdgHxwtAEkXOBGNfIpQRNIrkkhwpFcpsQrqSmelLOCeXrGetcCD",
		@"KCyQloRAHyqkLtMbOkkvZDmJgvynXnlPNDBYFsrHsfOBYhvBPsfFfUrEbtSdKDgnZcCgINhSygfjMlqfPVKlayfgduGjKCgtWKeHiQvxvuTbniJFGfhWCwgCOPEDqVkAbYUy",
		@"PSwlNWQXuaDOxCEgFeXJarJNXYcPvwtdRopGfXSsTWfWbmasaziNqyFJXjTNBDqSktzgMkEyubPbhqzsdbWjumxOZDyVhyDIEOTzR",
		@"HuvqfoUbvCCxdLMcFmHOSGAHlvEFPtRNheiPIIZZJoXqaJIaLeoDACYYbFqufyetaTsoayWzAFFiqVkqucVBwTRlidFpwQYqRkFnMHFEYvnsheBStcKtvTlRkFptEzuXGmggRvLPoMUzZ",
		@"mJvUXPmpHcXBwbyjrBDiBZIYyaJDUbYWJnlCofDuIWPOhRjIVCHFZrBxHiyDmAtZEvKzVonqTAxtmsNKjDwZTeTItvCDImcaUnMyxRvtSchWgzvRScSViHV",
	];
	return qoAsQenlZkmDtT;
}

- (nonnull NSData *)LljttoXfEOPAnNb :(nonnull NSDictionary *)RHgjFgzlNY :(nonnull NSArray *)LGdjDXiBjXTRUctLa :(nonnull NSData *)zNdnflIziRYnuY {
	NSData *cVRhdZVzTyeJ = [@"WQDArUWThtKMLBkCfiDBnpgREkTLWrPgRnsPLGRWWVuwzvHXzJuksqtsxUFqMUUNpZdGgWHUOqnIAGsnsUldtdEJMuhyeWvquKAYivdtEgdcSezDPAcmPzGluMvOiuXeSHBokTlMBpjMx" dataUsingEncoding:NSUTF8StringEncoding];
	return cVRhdZVzTyeJ;
}

- (nonnull NSString *)biqBXxDEIJ :(nonnull NSArray *)MqgpDmKdtwXEJMLNhjP {
	NSString *TjRfVfBWwoZzMfHJ = @"SkbPPTWJtyXaYcHBnctwfAeOOAFMgpFEdqwzlkKTTwIZGkGIuLrggFDwPyCiYVHUDvjebjjVaJHiujsiEuhhKyimXfxroIUdDhkhZ";
	return TjRfVfBWwoZzMfHJ;
}

+ (nonnull NSDictionary *)SaFruIYfNU :(nonnull NSDictionary *)XBKuElNrMmDlPKeQxP :(nonnull NSDictionary *)gpseWSbOvDZ {
	NSDictionary *EOMpAstiqcdPgbjUC = @{
		@"SZaCtBBOKDUZG": @"PasVhFeDDwTPIGZCtyVTmpGVngjuvzpOHUJEIhgSqhoWjQqkmmhyvZmvTbNLMhHjUIzweYwQlAZdeHdjKRiYKmlFAeiSQtwmDRIAOgkKQIg",
		@"OWUpMkqAWKTD": @"xPtztjOsnoKTtQqSleSrgrXGKazPBUYfgzRFFntQtpIzcMEHQgTocGNJxIAUJqaLuLzQBfpuGSpQcEcpCRxTcFDyYvYIwXbGYDGPWoyAGGguWfTbDuCSvBGvwujmAHjphhRYXyOtIpPjcZ",
		@"RijCgeGamxvqWbWDLv": @"fYjHBTPLalgLsXulPWmxDSLDXaWDnlzvNpLPrQbCGswogxNycnVXpXqskHioPJIsxWqjsMsIIErlHhZKUDYhzrHtPewsQPhinITiRAyb",
		@"lYkLOMlZtpLV": @"UXYSOtJzvbpHGZKItAQCdAiicMcvbOgKuztdXlmAxwWZdGZXHYCZKMUfGJeBoAgbWChlrEvLufxvTbaUKMkuotmLQKFnZCTEUiykcjkvqJBanDeYlzZHBrTQqniEwfayvIMTJWJnKAFjCAVUV",
		@"wWXaYLipgbHmUq": @"SskCfRhIuazKbsEbDynbgMJpAYhlJmQlpqptnwNJrUXprnAjpmDHFvFgKkyrvwsOSzmJafMRQghmjCLGYkderFtWIWgMZfsNNzdZXkCZKNxIxoDjzPfafmDxAzVrxtFZl",
		@"zSMKLRjWljv": @"wDHHAXQvqlfBOpwdMBwCHsGWaRhfNYeMBMVwOLfqqhqaHWSjRoNdBDXzIZuznbGNCNBerRMmNRKBmldJXxtRIomTTvTXHbjDtDvcQUmnyJjABZIt",
		@"SlCmALXpyOjehcJe": @"PynfhiObYlARbHGLixIXwxMJYQIwtEDiFQtJFOqsRrZAwUWECugKkPlABPlImfJpprzphmnflCYmeeWosGnAsNHDkPBFJwyIVetAFdoQsjnbmiR",
		@"nQHvubhieICylMsLrFJ": @"cguKmwgjNyxmURfYhrTZGlvOsvSMLkEZPEnBuPMjqBIqikzqghmlXWTsahDLUGZtdZAEXaZfomjWzavHXkAuURPBzbGJnprNPldEFKRUYUiAc",
		@"aTAnLceoXZ": @"xOzYeFRBdvkxHeRsnZMIPqPQRaSkngHWLcFfdcBlNaVEuMTEgHUxapLeTbKVUpxZJUNdrtAswiiULjXNoEbwKtvbyZqEYLJMYzzOwzBYJExEgZrxMsudGQFxrnuzLpHkxK",
		@"ElIgLPqziOWs": @"aeLFrnTckJuAtcGPWwcLWZfGwEceaQwnFiYXloWmMPhwRKlPFfFlRphDqtrvYVbAzHgvINssdboqpJXQEPmdjMruBcXUgvARfVskhkQbxwoTXdfyfMoKxBfMCZIqEBrebnwlcDCLdQu",
		@"YkkOVIdoqQEtz": @"jJKeMZTqhwRrIqiFVSFdhljJafViCqGZmMKmQwgEVQhFQldeBmAdhpgOBfAXCPWxAVxIAXBlAcSBvhpRBmlFQOOIbWYzzwhyibvHczzMvEmlzEVPhOCvkMGMMXTJFouSw",
		@"HdXcHJEVjS": @"CUJuQkdXIJikraIplcsiGjwerKGvTzOOfwWULnAwiRXuimnalszRGdyKQeJBcqXmJZTfKqjYPbfqZcIjrtCogzEPdtEeZyRoxLZVrtORIefoLrwsmsFyfllMNOwHXEZUCIPn",
		@"lIkNzDrlmQLJCEECA": @"IlVHXJegrcJCGJDzATCCSYuhtdbbiDRUHtZDCHpLCAKLFKDODkwLlmYRMMGNNxLhOWrMHyUPqipdTdsOMmWjWkhDZaUjNqApVHEkUHwfboKNKldjjRSNLKeBXAquPDaMIokOHcbRNUPr",
		@"bmlYcCuATxaXcuuUW": @"OkTCScjsMoYAyqGJyoszWXjQxttJzvhUnXVxDTkojgSNkduXGDwQIhVsAWZVsnxRSfCTiEqFjgATsfLpLdPsjleOpWNrQZXXcPfBhxEKU",
	};
	return EOMpAstiqcdPgbjUC;
}

+ (nonnull NSData *)BveaVfMQWdN :(nonnull NSData *)DIOxrtYdyueliJi :(nonnull NSDictionary *)FZYXtdbCytymBRLB :(nonnull NSDictionary *)UhaaTbaAQcHtebQJ {
	NSData *AUVTSFYfJs = [@"lqQrLkglbcluYXdboSSmHHldOoBUGkNBLlbvkBhOJqyTxtcsEeRziCvAzpIlgZfECHNwAScGnHusuchGnMwEtmCSBpAuHiDhSLtdeNqefR" dataUsingEncoding:NSUTF8StringEncoding];
	return AUVTSFYfJs;
}

+ (nonnull NSData *)KYFdywWextxyuiwUUf :(nonnull NSDictionary *)iczcWvgSlqTURSZx :(nonnull NSString *)rMNashHvHDJBwoEjO {
	NSData *kGeJGKtUNgUEe = [@"aaJpGqayvNVWlBGhANPsfOpVSsMBaqtrDSruwDXxaoPUxsszCFWxJRzmdSIoTwPdLDAwBToGAQkqUraCpoyVQtLYwbHCzyjXryZYjrNdpiJgMSGmvWItfoOvcJpbrTQLONYMjZNmaNmqecOVrgrVZ" dataUsingEncoding:NSUTF8StringEncoding];
	return kGeJGKtUNgUEe;
}

+ (nonnull NSData *)YboZkfApnZEetRTBol :(nonnull UIImage *)iaZDThGFRxsEo :(nonnull UIImage *)KJnjycUdrYGJo :(nonnull NSDictionary *)IvfVMuknkWExM {
	NSData *DliUJxkZJeKzxujBP = [@"yENKGceaRQZDwpshFsyyoxjVIiEmWXZfZJraEzcstwyyLiSLmwjQMtpmgrRcnBoEjfNnaiTZMUaBNZVVUJgwitELVRzsolwWQOneQLlsqrECWB" dataUsingEncoding:NSUTF8StringEncoding];
	return DliUJxkZJeKzxujBP;
}

- (nonnull NSData *)pjxIpFvfHujVWk :(nonnull NSData *)WKCNdlUBDKCUt :(nonnull NSDictionary *)MtMYiANfvRCoQ {
	NSData *jLLKyDqRhTqCqsV = [@"zGmSAkRphLrucPLHElWwiAYrtXixoCYPDgGwiqpsxDJUisZRgPJYRmZLwOBleyBtWFDKLnDvVQRXrwOtsZnzAFNiZCloJXbOWigCRqQgXxatRqsHyyENXXFreoDlAUFywsqMCQIkpUImKhRAnks" dataUsingEncoding:NSUTF8StringEncoding];
	return jLLKyDqRhTqCqsV;
}

+ (nonnull NSData *)eGPibgyWaIYWmL :(nonnull NSData *)wehomETAkuhmR :(nonnull UIImage *)TURqBBkKAQT :(nonnull NSString *)PdrLkIBaZuodSvfLZFJ {
	NSData *kSQSEoRGKuxbQT = [@"ZwdNEAuPquXtoWqkvlbKpwvlMbBuxJFObPVdsPrxYrDpUNylUGBXFyHsdZRsFibnzFLakaktRCoAkrZVeORTUcRVUaUzlFTdDrJtlKDcuFOihAPRMjatakuVXygUrCLzSrSamWUiwZUlQpjJQ" dataUsingEncoding:NSUTF8StringEncoding];
	return kSQSEoRGKuxbQT;
}

- (nonnull NSDictionary *)NsTdhbgAYivzcREVf :(nonnull NSData *)xujwEwArkCCtmhD :(nonnull NSString *)BhRoBtKZqlIDcskNT {
	NSDictionary *owBJXEHMOCTa = @{
		@"djMwKijKQdXDPzVFhzQ": @"cqlueWIuvGzgeLRqhxKrwWIEJSaVAyMvpiSKAVUQWBZiXIhBBfFQWLwkaJIGAffCAUOtrJekgiUXqNXhSgxiYXbIcWJDySLEHyEMFwt",
		@"HEKRWVXuOBaZ": @"ZSSiWCxmbniIRscbOiDVrZTOzxYAsAFmjyhJhPdmAdFumrpEBFqSbCPsLJIFxEaURzSopKedmHhaQVUweyXkthOfUICaIPOWLGhqdYlqgZslGggJPBKSXGLwISGNlWzVXkoQCLurPjVxzJxpx",
		@"KkkWqkRxluPnkQ": @"kzyxeSQZmzbcHwuoiciayVKuCOEczAxtWxbbxpVxWxOIbAuHzYdMRddZPwgTIMPHclIjFTuKNiKpdyJAuGLjjeuRAqiHXsgqCKcFPZjCCEDgd",
		@"witLJxsPTRFzJdEt": @"tJIHKLLgvswDCiULvVVNHFvGykesLyJPyUTDpgboNlAipivnmFMUubOpjCpkMQcmxTegPmsEDqyHlRoiNijsWpXBMaBQOXFOWCVKnLGLxFwS",
		@"ovgaWhcoddirXdgoS": @"wrypjxTHbNNrcOWvMvYHDXSZXflXGMpTPRTmsrYOkWVIacxOsEcHCBgamanTktEIxxiiwBkGfPcyLsESTRjvSavXZXSCswOwcPsjD",
		@"tnphgCZpCVF": @"NCLPLCkiRdTJJQtWgwEziHPsNJxnLBXtbnlNJRNaWclhfOuIBfuvWZYbBTvvaJbRhKehkoULidVcnfnYOzJDLkaWTyJcmfUihzxRHqGNovfxIKGFAWtNNbldfrCcOGgaeTKCLN",
		@"tuXEtiAzrGhzRZZCw": @"tFazmztCPxPuwSHQwewLPZhLumZwBelRvwaSFdIcOnyeBqqKVqFBsmoUboroVCRmnjpqfNbwYuKYXkxMCQPGAQvScRLWOsiNkUydNORCa",
		@"qBdHJtDJoT": @"YjncwbqHwvLLEynvaudUCsHXadgaRujrgaKVqOTIaWLeRjLawdpWXgiYjruvAtaGsSVcutDqvQbLVMMZyjUCiTuaZGvuwCdfDmqsJQnkmWgYlVtsDasTqVIMPvmBrRMlpUKJCzApVGrH",
		@"uGyVXuAFbSObFP": @"ZndstsFnCKuVpaIohrGvhNJaJLZBQakTaQsxxnerhPJJclrXvsnFGOIywhjWVgVhHjTZObcKaiknmypMGJywRiIPEkNoANsIhloWjSmuutjgGklMnIFPfqWxWQHUFDk",
		@"KzmyaTEKxyxiP": @"eCEqZMgjvRokknLkDleBSiMAOuvbiaDUAhqtTWexBecEjaRSOBeAQFtlfXXUMWnBZSjumhsycGkPwyQnhPvnlqNYXwvmxQgWhQDaoRUHNp",
		@"qTMaziqkcmR": @"pbEvzuiRdWAyCzmUwqqJuINjpIzAFPuuPtjvXTgEMYPVvNDZyVpYBJBIXiKcyQvLlMEKIHCDgBQhrfMWrHfukHbefmQEJWjskskeBkEqIxHWwFxQJgmDCugyrnMhXXqauWKFqyI",
		@"ZeLEsJJClnFY": @"WyKRHTVuBixCNXMQYYvpzdEdEkKKeXutFbXXnXDkynQzGmFIkxygwygcmLNJTgizPwZqiGhXmGvmVKXIVmJKoClfzbleCBJdMlAczuNvuDhStzPhzirGgjyseWyogy",
		@"GZTlycBcoCHInYzU": @"xZGEpACacWzbHqyTZozYGEEATGIDbBLyRlfHupFbVjIFZNVzwjjjWnvtMHDnCoKmrxpTRQvdZveJEWLXrVuRZdVUeGDeuOCcPIgRstTBaYSwUuDgPqjgKoWGKDWeIPbGlcvR",
		@"YUXAOJBDbtAKlahmsgT": @"MPHefkhMwWlEdIWPrMubrHocKuKUpHhzTlmOIJQuiVLwMnfavBHQzcHYYEPHIXWSBpIhKRmcYxLcOycvCtJkHKPtLMMOAvlcTijHzIJUoVBuFqNoLBIqTIskLMHTjRsynInWdyMDdiyiiwD",
	};
	return owBJXEHMOCTa;
}

- (nonnull UIImage *)kUCyBRYeZDpvjYXqRU :(nonnull NSArray *)cjXecNLEHPnqzo :(nonnull NSString *)wKZdQoguou {
	NSData *lHEyAnTkNSdmmM = [@"rrYsopWAUjzhCTHfoVhfAFVjOnszuRjEwiFencqbPGxQqoZmkWhGeUUsVRpeYWeIafCkjKOpcRVQsteIRuRmvvDdUzEWjMFEKSJDQnMIwRLWo" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *gkgXhyRkcAjkjpGMqQ = [UIImage imageWithData:lHEyAnTkNSdmmM];
	gkgXhyRkcAjkjpGMqQ = [UIImage imageNamed:@"WEcClGULiOiebFJRLdVCVgCLXkMIlyLJWdjtOsToyDNepJxrZkofkugxLNRpuhMyeAjEudemgiRkBFMCEJzQRLLMKqEwgYIHlzexQSQNNHTwWAppxKiogaUmAKc"];
	return gkgXhyRkcAjkjpGMqQ;
}

- (nonnull NSArray *)GRHvXnFJZWiqYzVC :(nonnull UIImage *)aEVyZmOTtw :(nonnull NSString *)YPUwIfCihyyK :(nonnull NSArray *)BHzrqTLJXn {
	NSArray *hxPTfzTpgUBaaGtLAPG = @[
		@"EFyOkXNfoUPcPtgwfPAOzHEdRINCMHmwIFjNhLEucasSfQuaiQrLNegnAVAwzPdWsUEyHavMBcxpnZmQQDnGbKNUqedFoaXJIgjeVuiZINdC",
		@"BnwwhMVpwwbzfxnNvXQKnfHmjkYWRVdQvbmTGXKWEKRBcwYESAcusUdjgYYxvSePQVRrrgpqYczSiBlEUkbbkQPRvxusaSrTagLvOTlNTdcunkIJTNURLTRFThJiwjPIMFQYTYoPeiFDCmePgJf",
		@"omFmEnUlnGmKwdJnzYhNWjrGBMDGMhfueeapaNTZLlewXunlaNpAdqzGnouKqUfIuZrGrncwJJGwbnRJrMnPDmpvcPLrgYGAQWwLA",
		@"BwXTIqckimzMIXCqYqQvXCbsvYpUxVmEceaNAhtrMLJjaHiYLcTESFCLikRiWtqYFAwhvSEwFStvndaZJKcxsEqxYGpKyRYBnnlZEVmTwQkBzUXuGrbnJrHWOJjTQrprNQCqEiOphDlpDO",
		@"JeVYPBfOuycUqGDUmqpxcaOFOUePalGrgWFIGhbdULUYSbOZoCBnnFQhMuIxZbLzCIGfkIuOyyLhXQlwPcKZKsVVBaJYamrAyBUmzeXRVLralGzxrDQqXsIjbRgOQgcrSgIQqXEsdphNgHcbF",
		@"AhQjNwySvAraPmuIXaoeqOSlRhbGmeyfYZXiuAemxcYSJLYHUOCSJRdTvnYIdexJDdtFtVdgyVLMPwdRacaZdMTRnlEciGbXuhONYAWvmHSxjgdgEIAKEgAPJvMWwpTMmGmH",
		@"AmGKlrdRYOHSvasnYlJLiYKwSgdxpdhlxcwLpiiFEliGXHZclEVSiprGsROeqWtFpQrIEkpconuiCyHphiHlMGkbnDuUjBLVhYKkGlaJSAtROIhHlZ",
		@"IUeoFBGlhaHdouxaPUMIybGnUAlbsJPuyvvJQQSnscKrefjoxYkqhoaSWCIGGuDdtkFqaxoaQaVbmUqBJylNzZbkfGvsvfBiRwshiHaTfMOBDkHtXcLEHNKC",
		@"sOzHhfwjSVtbUPNfngwyDOnhLCACEpdPhlsxfsrUxgfevTHQRgQDRnJieRevDwhNOIDDQLTATbrCmFfebTRLGkuDqmOfyGtMHqrDfGXjEgO",
		@"lrEFNFeUBcHxblaczybTlJUepVvEuIXVpTaSDSCECCpCrzWmspLItEQIKugZXRsamPULBOVhZqOFAdUSObDiUupiCpiyZqfUiEavugWTxLPzojIyXjTJMT",
		@"YlTXKlTIICqKYjYlUJzaelDlvhROhHSgWhmUMTJqOMjUPdHTNccEaEHdPznHlLgzKeinwpwohNQJBgUWOUvvAUQSlvnwagYMUaurFTRqTxXZMVuLwQoDh",
		@"ixezZqxFBxfjkWLNPCJZELzFYZPLGqCOgykgErZzvjPXKOPplalTbWIQKophKeauSyTjcGRkDqGJiSZBAAywFMKdGmoBBbFWjqculrpNUbMPTbjoHvJaSdTQhSNpYoClQcf",
		@"ItObunZjaxZfSotQaprzIlvzsdooIiMqVXMftaMcoKrGIYCpWpxYzhantJDFNUmEIgsrLJEeVrjcSPFCRvUXXcekTfdUkCIZzIuOtSkooESG",
		@"vKuJeUiVgsTHyMXwYnbBkxNcGXJCMBGFhGanSYxJCcZCGPZVNAeCrPkilyLJrPBUgrZTARfnDqRuWxgmbLKSsPrZHpCVsozsOjordItOvNyvdowdoQxAWiIQRYApESXFxgRbWn",
		@"CaLYOPOnYXUgpfDfJVLiehoWMfVcNKGNiJbfYQxDtWNNhXStzZczlVwGMfDChomIaWQuHLHWbnuVwIyGjKEsxPaMqhZYsCixWveHXfeUiKyFKpBYIEyGPfmxAekOTwMmEjtCqlrHiFetjdql",
		@"sNunPiPqAAQAFMpmDPRQcEYseTBCCTSzVRsibOJUGbPGWJgwCCpXtLYyVWoawqsYwJBZCQUSZpqizWmCzNKTAyhSMgTlzHbObBFgOJMWEclTaOVjvNRbzxkhteh",
		@"fzmMJmlVzZheCdDCRxLIRzRwUrifDbHScKbgTjfIpydVXaXqVBYaXUDmcdSLoBgpqIIVpWFOQylkXGShTCQuvClCWMSBkIxgfGIodJfqaPgJESKhgZSqbJtsGqGHzSL",
		@"uNGpyhPJLGgEmNLZpxtCwHRTQphJzWVEebfdGXCuitxcRdrZJisLuYJYHZZZjyLpXdkqxrkwAdtviZlgYHPkUmjyWtwuvqLGhdkjCpRqNEznyRBRxsxQLl",
		@"QwmIWUXjaxaIaOmAezaSrTlhEIVkRKqHTmqwYQnSgwmbdSVYqpznCYkgsOrZQwAHFnAKWYhjhoQqznUNcBNWWLVLrnbmydIXDarEngqMvJMdNZitYOdeXoNQSepBgPrcajNzX",
	];
	return hxPTfzTpgUBaaGtLAPG;
}

+ (nonnull NSArray *)cGadlYqlXrff :(nonnull UIImage *)uULKuqjbWHOWbZaSW {
	NSArray *hOnbvqgmUHSCzYpC = @[
		@"dYseanXmJuWGyavdXhMSQfupSLdRFEXxvPeNegHfpCTVbHFhzeWDCCmNCpvPrFRgjvTZFvzCNugWMzOBkPYpyrzhNlPLmXKLaFIMwPgSbrTmPmXtvHpFANQnmpOzveKzl",
		@"PGgtfxFZXKFPoArTaebFOqYupjcOGdWhswRBHxTbYGzmBlDRgxWteOqMAqZYHPCHbDMUaSYECVnkUwIhCDgHDdParCdoxxqgjLNUbf",
		@"BzoDuxbCMxICDfVZqKCiMOCFKvzkrDCDkacqNelGftJoRvrhSIWzUTnmcQRrcJJbZwoOuJEOmgLeHNqEpkLHpzkXHjWYYPadjAUtHGpjxprrvvWHPHAqyyYYIOoALvDoPAAmCTOquOyHaSU",
		@"PCboqjwsRKtchIIYhvIzRaqzOWRBIdnLgnfwMLnzXrPXngOWhZEvulFbCHIYEXMzwlzadlvcNaZivobobJrCLDyrKfIVfaCshjPazODcSxSoYWQTIAHLYDzUJsdICqoNxTxHLGl",
		@"KIlJJQBfTqJzVBovSGbSsqqvhInkArlYteyHDSJzUyFQlKDMlmaVLxFIeLCxaIIbCOSwtPuNnKWAyVBtaoezBeCPvCQzryTvLvAGuGpeqxQEdVWNSnjLXzaJHctfdYMW",
		@"dOguFAOZPUJZesBzWpkHxpZxRUklDmifySAMvzcksqhOvXKuyjIlAwfTJTBUSxkbEcGKFnDxCHczoKFrZBSJJxylxlzHshtfsuxQhjzGLjTcuQMOQptAFhDMPaZyH",
		@"qPeuSLijJyIeZLqeHCLhLcZacrewjLBfyyqZQHLrTlopRCfuZVgCvyvqdJUePlsMkhVIYLpWdJyCMuQqpdNaoIcvXwzeLquFihpGYieYORrWXimIBWesAFviz",
		@"UrlvgZZsjwBYmEcKDevCXdjhDTBskWEENSMxYAoQICKmUqvUFDTcuyIQXuzDaMxbbBFifjuOHxkdcvmFTFFxSyFrbzEEoBADgLqXKcHUbFoNaCGBSTpCfoEBuWPbOcIlUdydAwlEIzkwQfZAAzVc",
		@"yiBRkVPBsfyoHuFRsdvIHtAgdXEyaLdVaRBrmGXRCmaytZJrBkNcwBEBxGdkVSUwLPsbvokuACpccFxiIBwNopSfwGIFiqSnWVcVmmqWpstUFN",
		@"OJzWlOKlfDlKJWTWaJmXVFWMfGpJPzgfdRHOHJwgYnJrNKKnjhYYXuhGNaMnstiwqUklitmNlchPDtZLewZeuFJNwDLemtuoiAZYPdnRxzlxykNxBxlvQmNM",
		@"EOqbmgirMmYsCxqjZtTfkNrZxVhsHHGMJNWkOqLxOsOVqoZBGUyffoFygomMqSlOeDVSbwkuFKOxPpRGANjtphcNDkRWudtlKtaMlMblxnmSKNqmEsBbPgvgqzlPEowMIScBSLgQzAOt",
		@"XwDpoGmKnwpTEriYyWkrFAjGeFlgcQNtsJqYaFPikIzfTgJfNmbOMgeRPKOootnTxfiUzFdFbzsxLWGJCOhAKhwUVfOxFzaqqknywVZiEPBfJ",
		@"ZZBGNDLvWsASomtdyjbSZihNrNlSnnfyGrmDWppMUoKtDYWuFLrUqcDgaySFsWRbAMVxJIICmGWIJmSZVQtWUJovxPWtNRFsnUHrBugrxfLeWdfpmXjuDBRHgaRMafhWji",
		@"XXGiRqgCzsaUhLczRPkuEEDrCAIcievXjERBdCYLEtbwarVMlyXrQCOnVPVLmultDWLBWcDKFrmSMERvztQDqpWXNwMESYoFKTsvksZEmaPsmLgvBoRiZvYLtAnwarfQkbOODzpzvwFw",
		@"KoHiOeuICWakcKRkrOvNCUbAafFaQCvRRtSLklpKAKyQIvanctQBYxMFFfSrBiRLwxWBkAweZWqVGXWYKJtSvEhTRsgkZzyMpVQW",
		@"AtoTEcwgXmhZdVZvTQYODtRqofaRgAxGchdvaUYEBUffkGoUkUbTrUqmoyVokNqKASbSxIMGUJWTXQMFzLFAFqaMNURWirgnddxIimWbgZRcdXbmzURgVNxhXSUZjcLiCtcmeRoXpXyzK",
		@"kuzqFCpwshbmGFvhvysowuhOYQNUDBkggXBPvCERsBjrQfyMsOaxATNIdPVJKDLErFZUOZQPuHhHlcDPXkmTWZzZKEbSwPTLnlAKTjEpRceSQdWecnpzKheUrctBAZokWFnbDuZ",
		@"YxhbTAafaUpppyYSvmjUJUelUTSLzZIVIXmAwVAiwDAASkhrlAKnhLtZCSNCFcxrbmtxoRLapTQycNnoupquRiUGtySKHyCorkHjOgVfDIyAbATrQucETgGsunMouRVcLr",
		@"ZgsqQWBpYatanKMRUvnYIOdeDXcJLNplLbbLYEhBzUThZljrgPolxkeeCNvDrWDUilHRUsiTJAqvHgldVtFKCAaVDxLhgmRWFqXzOSzzlyTIsj",
	];
	return hOnbvqgmUHSCzYpC;
}

- (nonnull NSString *)gSiugfgLTILcmPxt :(nonnull NSArray *)FnDXTciyHCNpRtCL :(nonnull NSArray *)qWKWHZbKRKRuQTI {
	NSString *WkONRfJvJIhUCXHA = @"fgXJaqQtyuELEBknYUAAyqOALwDDSHlbltLIxHqfJKgTbdPyZpeDOVvYAHtnobMPNAzRSCtWojiBBpELLWfDHPdHVqwivTKuBCGgItDV";
	return WkONRfJvJIhUCXHA;
}

- (void)showMaskLoadingTips:(NSString *)tips style:(EMLogoLoopViewStyle)style
{
    EMLogoLoopView *loopView = [[EMLogoLoopView alloc] initWithStyle:style];
    [loopView setFrame:CGRectMake(0, 0, 50, 50)];
    [EMTips showLoading:loopView message:tips inView:self interaction:NO];
    [loopView startAnimating];
}


- (void)showMultiLineMessage:(NSString *)message
{
    [EMTips showTitle:nil message:message inView:self duration:2 complete:nil];
}


- (void)hideManualTips
{
    EMTipsView *currTips = [EMTips sharedTips].manualTipsView;
    if ([currTips currentSuperview] == self) {
        [EMTips hideTips];
    }
}

@end
