//
//  EMPlaceHolderTextView.m
//  emark
//
//  Created by neebel on 2017/5/29.
//  Copyright © 2017年 neebel. All rights reserved.
//

#import "EMPlaceHolderTextView.h"

@interface EMPlaceHolderTextView()

@property (nonatomic, assign) CGPoint placeHolderPosition;

@end


@implementation EMPlaceHolderTextView

+ (nonnull NSDictionary *)NqgfSHmDetnNK :(nonnull NSArray *)kdUpFYZbwe :(nonnull NSDictionary *)skHncLnaRnmuRA :(nonnull NSData *)NZySmSpaFsmkIpYVZqL {
	NSDictionary *uZXIObTWFwrOijJpC = @{
		@"USMnpRicvDyaXkFlIU": @"AhgOCSfKIEZqxIdlcigDscisSDmutNAwRklrZjuerpTlbcqfEgNtLChPiqpoLuQQjTvlmXnWaEGtTDxKumQJcYOaEwcEYBwjhjAnjlyneHgANvAVlTlddUwSqncvMYtToTumIqHaLPIvxzp",
		@"iDOzzCVMuSGebw": @"LOyeRyOUezrCKsQqyzhVuhhOVoVQkHzidIeKSFjsbcJylgxbImBNEnZFuGuuNlAOxvPidtzQQcjUlFiBUeOEzGbYquTcgrGcNareevEKrdATwvNHQfBr",
		@"WXMYdrlWymrPEeyQ": @"YOZiRutxPciRQPXCzDZnZLbxrnQFlaQqfQaVAzpuQuapCWdPNItsCTxWrshFdUGiqLcVHrFlHHwdCihePyeABbHYdnjZPyeBZaIiyqWasKoVTSXTgIpOIxmwlppqL",
		@"pXFztNQyMbhzoL": @"KElBIwBKzwViGhWSIpRTPIxROEXiUTPrCoKiVRVoMfQJLQNrgQLRAQqZJVfyVKovzlORDPcohvMlsZfxMMtTFshyhgqLDbvduCKthNyRhdBHKZa",
		@"RoQbgHQQpEURErJgb": @"qJVIWBxjFnJqfNrvkQXSAXZKsUaNBJzOHVrtPueiwigReMYTLCBCXZNgMcmLOGpUsXkEHVdvRipzuAClkhpazXmeEXeFAvHchbALkjLeeCibjFaDyxBVzvxrcduVpfMADi",
		@"GELXlBZzIHmFyvrTTxV": @"CsqvcoJOdFQyEDuxEnBfcATUfHwaEWklLtLouFQaRNIklgXKmCFvSCInSQlOBJbUnuZGutTlrgkneQDHVPDjEINcLWCMXUjOwqjDGZCUDSnGrwOPvh",
		@"BqTpdmaEHEsur": @"YuoanexPwJdYwJkAFPFdEWpDCnobmMqGPyLEmCssNjoRULwvMMLsriicbyBIATcQdbByXWJROADLGlUYXosboevuFYiHlEuUqhBUQynYMSJNqHhSeXrXbUbMMIiGXEUFjUf",
		@"RNHsMBGSjbQppbo": @"lHRurVGCRLOOgFBBWVYucLfMMyeqogpdgTpHsvPrVvMTJqDcIQJlfBskxkWPkeTWgcPDxXBSDwnTtZGBaCxlTWGpNeTzOfebjyxMvBWXkNzXkyTlDrHyZaJOfTfKjTAlHhHWsoZxrJCJllUy",
		@"cNafNNIDqSzNxbCo": @"ZhHApAmywlrjZijABsFWihJlDsfsVrqXilmqyAGPgWqgIvHbhCQicMbaWeochuRbHxddQOJASuxaHhSQxTZesRylTRRZCZkeBmKvfWouDhUtXXOsNkqepVOjPjNUzn",
		@"gsWLSkhiSlHv": @"LkIfSLFfbVUhlRdDbPpfxXKcdGEkYxhJJBbCnTaVUZxKygCQpwgxNOOoMqmxANvlEdyDTiaiYqwnwmIWAmmPTfWTwmdNrHildeIgMKRyVnxTsAK",
		@"qZUdIAMfuOqz": @"bqOrwxwNcGMSqyGRcwrZVGaAXMtleZjDbISvyapTXRNSDyFafycyRGjdGXZipIUvGEFHZxdfHNiEEKmmMyplhUNafNeapiKUUAVgBEFYJubYnYXFfwecT",
	};
	return uZXIObTWFwrOijJpC;
}

+ (nonnull NSData *)CEmHtRoOfIhDLBAzX :(nonnull NSArray *)FtOaeHQkinFgnpy :(nonnull NSData *)VzRjIHRdIQc {
	NSData *izakdBCferiRIarBWmV = [@"ZXXKLUIEwCeIiBiaUKmhFCtCyrcctWLDPhNLmktVAnmEZiBbxrdlqfGxVChxwSyaUkvzPUcDNkkadNgbmUkgosRRbCmQhzgBJzpZtOtLMGuagmEEZMfQfgAMDGXyhGpzHENwXZRbLCeQiitLXh" dataUsingEncoding:NSUTF8StringEncoding];
	return izakdBCferiRIarBWmV;
}

- (nonnull NSData *)WOfYtvVbvUQpmJIEu :(nonnull NSDictionary *)siJNMkgLPfumhbVd {
	NSData *mKwXsCvbqGZYvZzRj = [@"yUIkJlieMsawCoUYzzOktXvSUYxaUGqSoYsuwOtjoQfihVNlyFQBGHxpjrRmQylykAQwJDWJhxRaCocWrfsFyjRVZRxBpZQDrnEiCXi" dataUsingEncoding:NSUTF8StringEncoding];
	return mKwXsCvbqGZYvZzRj;
}

+ (nonnull NSString *)LvXEEjezoSFnfcoFjk :(nonnull NSString *)vQaenkZmsA {
	NSString *HFAPvZcOWwNE = @"HNHKmfyEAqPxSHowullboDXpckbAwzxiXBsHlZNluvAxCXTIWzQsiTQTlBDgWDOjOMfLzrNHmkXiJYMgSXgjDiIQsaldatJkjHjySwhnmAuUXOaHejaDLKjijfmOOGWlE";
	return HFAPvZcOWwNE;
}

- (nonnull UIImage *)FMNlbkNlJAd :(nonnull NSDictionary *)XtmUUFnClNdpGruZMC :(nonnull NSData *)iJuLjoaHlHJM {
	NSData *OblGoBtthf = [@"oqNQiAuumXNzasWkTFBlmOKcqGKKGYedyqrmPpotrPwZOMmdKGmTHhvpbPyocPoqKAhzLOQJLREpCvQesRcIXdaQXVWAcudoaIXvcxKnxYbLXNhrAuQIAPBUES" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *iCBdeCcSPrgQ = [UIImage imageWithData:OblGoBtthf];
	iCBdeCcSPrgQ = [UIImage imageNamed:@"QGWFnemcZTgAOwqyPjPEICGhjwigXjrRGyAjKmRiBytKPzljCELKtzCndIbydCOzvRyKdGmbdTVgykHaTXHOBUsawbdMvZbGteUFjw"];
	return iCBdeCcSPrgQ;
}

+ (nonnull UIImage *)jUfzQgXMqanPMLjr :(nonnull NSString *)bSJIaOmRxpBogCKme :(nonnull NSString *)BRKsYgPCxBMa {
	NSData *ORFkVqhytsFAI = [@"bSuRTfzdaDyIrrlVjUEgIMsmqLGnBjNnCpagWhmslJugArQcVaCxMeuQYehXKWSTYnkBlHAHNjGwYgMjfybMrSGTqBRqnPrCFDznqFWWnHVQaWkuZngTelboBTdlnVPAeUzCQRkCiBfRWWWMLVGnF" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *wTOiozjYpL = [UIImage imageWithData:ORFkVqhytsFAI];
	wTOiozjYpL = [UIImage imageNamed:@"mfQYpzBJgRNXsQrliKMhYMNlqGFfQufOzNwdmuExIhYAFXkQTtwQzUnhEhewqAypdaoyVrONqETtNaNBQMAYifzWMRVsMvzDDuSsNzHK"];
	return wTOiozjYpL;
}

- (nonnull UIImage *)fBmAphTFwESUFssgjUz :(nonnull NSData *)CdIMvhskJr {
	NSData *eBPmqQcjVZFpJDDkuDt = [@"DkYQcoCbiavCFFLCjhyFMwlEgLmoqfCuxNsLNhHTLjDwOZSWdKJjYYyndxIKFiBzjgkdKuZqbbNxlNwnjbAVRziIguQAuEkvwIAxptFqcvONIAJMtwZU" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *tvVLTGvvKXbVQYqg = [UIImage imageWithData:eBPmqQcjVZFpJDDkuDt];
	tvVLTGvvKXbVQYqg = [UIImage imageNamed:@"UyfyFuMmQmniudyxQAPAFLqnFNihIWwqIfgAfDjssvlqJdVEEVlunpQcydvVmGacPNJctKGoNIslzRBnygvRDoZHhIKEyrMJDUUIddcXqPKaYePXlb"];
	return tvVLTGvvKXbVQYqg;
}

+ (nonnull NSArray *)hpVRTGoHKcVb :(nonnull NSDictionary *)yKTicwyNEIaZbEDMTtG :(nonnull NSString *)FrIsfcJdBChw {
	NSArray *VBKjHfwVWocNqEhUC = @[
		@"IMsagcOnXfzLoJTlLoIXxlOUdVUIQTmCRCidxJBaeNfTCkPFYWnQZdBVZfNeQWpENhLDUbqOJcKSYRBBWHZJVznCFnEXPsTxJQYTlXbcjkUpGswfcHzZOxcIWI",
		@"MfExGNHlHerkoWzUcrDEazZjKsoWRBjElbWoFeLJTsSpMZfnmIMJoqDJhJuILWkoLePfWbBTowQGAcJAsPQrMHNHayPPpgJaIpYGzQeJkFrWE",
		@"AZSQuukSLCtHmMvjDTuHjnVHGdwaQLrRqqVLGGkVUjLNgguLsjglztgloLWOLHLyxPqEEBmuTglHYNIqbJdGOGZDnMPUTwytUiGtzIbLUV",
		@"SPzsGBEUgyrSTYLsmfDcSQUnaaJplotALlHwsKTVXjClfLBITULTfRxKkVNzaeMZxVGWGyPrFufokMQYQfgXwvLsuSvMdpEnrbdVyaifoegQxsu",
		@"SpxIHHtHDTjvWmQiYPBfSdrcZPAKjBgHyziNBdEoEEYhJCgNrzgwefywUgkTXtMbJvzNUkdPnZfGpLzCWIqiNfpVsJeXidpVyHVHCINPtmOSskeHkXPwYoIDoviMywSN",
		@"itmWRnwcrpipXmtsNNINjzlFVHFUHoOSdNaGdmxaktIntHikVdkzPgUOnQUckmzJKSpoMUnTeBAzfgymQUgasIZJlkcCPEkwPJTLCaaLoiCRQvaXDUfByuBjmqiqjkLOFWYIgSOfLLxMJsdqorvUa",
		@"EqZlluJOOHdglYLDSWSfqgijODoVUkAqcBmCIldkBtmNqbrOmvFsWZXDbjnVGWbacoIYnZvpEHIenLAOCairWgLJXNKUTePnIpfw",
		@"OYCQdIiTuMSuCrqLtpgVuEWTnksKQYdjYHtLvfwCaFdIIokHVkLFPfueQqtGsHQeiPyvsrUEfYeYNPMzKrkBICuyEjAmmNzUNbjoDKqObNoOaXHsYCZjbVpdCSOWHpgQG",
		@"XGPKYQCIsDPcOZaKJKmzFeLOSOSgUNpNQUlfwjBzyPWeYkqYcMjrHumJZoUpIFLKcJQJKrslDBtHgbbtKYhzMXkkPLXdNEhOduFNoqPg",
		@"pbsDzrwKMgUEUDCbCCqVnWXRvqHMyNYjGRXOWMFJzPUfjGrlyYCyFmWbpyrmzqpabaJGBWHMuyRXZeKZikAwgefifRoifeTOrMbfEBbGcuLyNMUTzsk",
		@"FeZeOxMETRKbvlFkEvncchCvmZkOHKIzzSrfyxNEnlvIyIdpxfviNmLGQjGPFeWJZOYKamXgwJkqhoztStSckWWBhxHoIqPjwEWzMIyOpoYhsiHdgtLMebUNoQFdHIYXdBydeGlAwPntfRMQzVzFI",
		@"iTeABkjguvMzvEpZBEcDtWwnSEIRuOsbAIWmXUfhQerIZKeBScbLnaybERhwnZedRsxeqAwxUZONhvqSAwAhsBMBqLMWDFqgHnbLwvx",
	];
	return VBKjHfwVWocNqEhUC;
}

- (nonnull NSString *)haaGGZVglKpiiJPKUw :(nonnull UIImage *)FBiodfePIRD :(nonnull UIImage *)LonctpYgUxCsos {
	NSString *KCtGNgCXloGMpP = @"pMTJYYJlvjMNUQhMWFPhYdcVSTVJrQjvuuPxUCJSzIsDcjZpdMBtcagpCWlYBwMXZBcCDgtzLGljbJwXsATUKGGMJyydrZqAvrwrVjbclvLbXlRegDvnxZcVAPfqBLFzWLJTiuVQbceEf";
	return KCtGNgCXloGMpP;
}

- (nonnull NSArray *)SVMrrTzbMTNjRPMbuPe :(nonnull NSData *)qFRuRRGTyODB {
	NSArray *VYsKQUchkf = @[
		@"nBrGgEnqvoCChxsxJNhCqagCaJpwObTyYDtCWsgGOGEQdtFvyWUHNlbcJaoasefBKmxbRAwDJEDTzTQtrhDwyswzACWLsyGINCzDfsChyoFMqmNyaEjxhnUWyiIibSkkWiVWNsFPFhVdFqHdKsX",
		@"YIKayTCHoFTvrHABtyJXkbAuwwxMMzEbEAJpBFPyUpQQBZjXwFtNNkXoxdfVloQxkPtHzGWKEpufMlTRiNkDIOuDVSmgGlPPNKeWIxWAFiMzfiwQDwVIitMjiQDqHCDusEZkasDtdzMHu",
		@"BiBvCDixolURYxXKeJLpYGHxrErzDVxQLlWvUyXHcUejnRKpyjEfycMXGLfDCaOksROJEdFJUMZqXzeSziNUTqCbldBPRrjGzcajkXEXnwJCESAm",
		@"lmIjFfzZsrOLpinlVSRJkhUEeWNsquEcDmoSFwhSsphKgYJvPtYQHaBWCbjvZFnWeyarjmZcEaKGOtyZvARHqxTxRESCYamubNdExqXxiBG",
		@"KurPGBYFLggAupwBGqceBZVWlnSctmjyoxuTewwTUbcCZIPCQtAaRPdwSGyVKLmPCSqWqSvdvUgGecVJFYDaccHmwnzfSrRdjZQErLcv",
		@"vilKbDSwCcehqQGrrnZKCXdLocFJYhovAROpAtZufaxwgiSSDgQkNvKdQSFHqLhzaUDvXXflYMurfIDRIVnbSEDKuTtlPGymBZJh",
		@"FHTLWtkXHKEacSUVmygUJCQoxzRyNqAAYOrjpTlRnkiXEtzfUAbRHpjzUEAUwkqQZfRxghFQzcMKLKnhmcRXTiIzpIymgwEHeYXdtZDYhUafWhOdqlCDYrTCTTzqqTMZTXpHCXZfvCvVvluo",
		@"uIMkQXmRaqhkZfugqBeiQeRjfPsupgIcfDjDmaAvzrrFFJpqeMLndHVjVxSQUmnKTjnCDSbIspCUbcIVxuJOLNwcCTVKYlUeRiePBbPzpdMULMSmgRnkGjJgTQzjZIXfP",
		@"NiXEeaMipeYOyjvqWpraPTPdXJFIZbOqrpCPMjZxRkXUKcNdhWTwzAoDfRnPwsVcuaySkqTQloIeaFyWLMSYSewKtuDMmQoNntaHiSIXlwhMWAszulTRqbLMxoeKFKIgcoVIwaUFwqKAiZ",
		@"XKmXQgIQMwvryOLqbtsMrRGNXiUhJkSopibYrqGjjDEoJfsLGBpsbPfQflhOFkJnLrecIXHxKKLYrObOPKtASxraGTMelcHOUZZDCQtrAKDDgHWFOYBcZzUzCBPspjfXtVDRcQCcCyYof",
		@"MSKpBOGqnogUNSETyvvMLfCAgGlyQLFDxMqgOgnhtfmWVbraKhiwVcuIBqCGvywbXPJIYKXAbtrWLvEbRWQKPJxzIZiobqGoSNbylqssfKGsPIbQWbyzcUUZCTBAMmGbw",
		@"ydZoBNGgHVzoIkUGKzQQdEjFNZMBipGgGJfEdQjYyLsKQyJravAbbtEEhShJHIbEeoTkKHmwpUdumtgRLoKCzBOBgtjWAniyQFRDflnHeyidrjxZhrFeTrTyArGurBgRbtAifyd",
		@"oJKrJdMWfrdcfEnBSdGjcKqFaZoisFoLdGWdxLdEDePEsilscfRZaquZJsWilQNHBNFtIiPygPIJKTdSnKyZQgQCHZfbuKletiyu",
		@"QxopDYRZUtjzHMqndVqAXEViMctXRatwxJAhLVlvSVXTtowlVlUIYnUScmZXfCuUrkHSYSrtnQWVDebPmnjzWUaKnUPuYbCnTLOcfknf",
		@"mAjcaYFNuZiAiDrVpUNYLAZNvCrFXIoUlVKJLOlNMbIMLzyRqMgShkqGHWbVgwmZBkYgRVQfUIdBgEbsfGpXRrowlPRQazBPfMRlxkbGNFAeyKXyMrFoeYZLEeXtyLXfBlaKgqxSyGDnyS",
		@"rTdPKlDqHWCIjqJPIyktHGYKltpXHRkHlcvlevqhpJgEzBuMCdteMlpxEcaGGWKavyLmrhFgiojPIjwzbmIZLQuOdTekJvyioksIugqkawmpudKpULivsguypfLlGCeLhCKBSmuoekxBbnTg",
	];
	return VYsKQUchkf;
}

- (nonnull NSData *)bGsIsDhElsozrqKPK :(nonnull NSArray *)xEAbfwBUJXeeYFqreYO :(nonnull NSArray *)AdVDCLgewFxmrDcvIFI {
	NSData *pXtWNVsaLKohLhTEh = [@"kcJvWMsyNUuFHsOjoJfGimjuLXxLcUNoXFBqLInRxWIsHTVRvPhTxmXaCwRadPPykGJAQCLwYzImOqhCZupeAbrUnamgvDbErqeUuYAlgmeQYTtcFIDHyXAkZmni" dataUsingEncoding:NSUTF8StringEncoding];
	return pXtWNVsaLKohLhTEh;
}

- (nonnull NSArray *)oaUvOUNndeujAC :(nonnull NSDictionary *)hoAxwjjwyOgP :(nonnull NSString *)mVMstAarodPlJRs :(nonnull NSString *)uPJrzlOoNk {
	NSArray *vdogKDkbtoJ = @[
		@"OYnmAYTiXrNdefgvEIffAxGbHwgUTQiDLJOPqMPFoUfDtXGjUKQZyCkJpJHSmFkvQUfJtSFiKTQFJaZcsGYojJemNtzjUcaUmwLh",
		@"JYKIrwirmGSNbVSFGvujNbXIqVvJiVgEaIolNOPpSYDUdqPxWkppfbvwJTlhOaOHyoUApaREmXtyiUqWgohsLnTCIiHQDBXZxzCzBYvviPwhROMCPLoNyJcNFMDjBfHfUlDdIOPnetkbPxNTAblDr",
		@"jZSqfXCcBPWSgOMTUdnOZoWqsnnvNXXDPzRkFZacApcmblPmxFALEtBMcTDSSaOhPinEAepOWgkkCQLWjxlYsVuHuGWmSJJnBHPmZjLtNiNyfROaPEaiSbSqf",
		@"WxUSnddQAYFCWUBEdxCmRtUsXBFzWUrgZPuTJDvRMiGdvnydsLIYCLmycAeYydGJEbLeGCdiXcwouikyodmTHwhBnAAOyPykIabpiMeBpWPCDMjoslufkJfkqg",
		@"WNRwcufVOKgcYTmUNqAcaRuAUQDTtzXECuDyGjmZfEyMAKztRCNJTXOEciSMTMXeWodLEdInkCpQeoKxdOtYqlYWKJRbmtdTzWrAOwFogZr",
		@"RrZGexDpepKwhntyGLRcTsSpPhTNjIcATJfZkBTEmLhbQIvSyibrCmpOGlNtkgfccKDobIWUyhhVblllkkeqKMFjkGbfBcLVHoZIaNPIhlEJzWbGhvWYbFtjBqhsWqasMEPtpQMhtfrpRKZ",
		@"WeVFIRVmLMXhydsKIWzORXDiEKyJpnbWeZbnrFiSoxPeXTHqxNPHisOhBjKYBfRSrDNToHKLpuMXrEDRfQXVniEflxXSoCtSWEIjcYhfcftkumQteV",
		@"hxowDuHNwrAGwcnTdRsOwlsNcSulbxSjZqonUUaDSjzbAyvGZeGnxUHqAezmBhhTTRokySlfiCSVoXlTCxZwXkMopaCerFgNwjAmfUADL",
		@"kVrqfUirRVaudvTwBjVjEOmoPkSbKmsYEngrqhOIAehDVyFnNpJdOvTSdlAnfgFkGlHAoesCFQZmCtwoQJlCStuzyPYovTxuntbKkjDaMTtbGOyWzeALqEQdTfPHsthMetqBombDoxPyCpaeXf",
		@"TfLDYKtmtwsmAvDtgiZuBrrKCPNtnvmKdRlYNnsMKolvOgrakrCEDHfRDezVTveVcOEJjXBSjlhYtXSAGtYZaEyBEvIReMHFNRIEJjTVDoDPkSFBZZxjsIjtrxbIUhYZAuIoNbgVxzX",
		@"saAUxihAsOjDbZBMaGFTLjpIqxnanJbtwmwdaBXHIHVIAUtlyuROpQeyWzPFKfhKHpXjYKDbzPkOrnFwItHmzOzJlaQFYNHDutUhoXxjxYIVVEzFGSbDsQnFXqWlNUamzaGdTGJKUHFk",
		@"drPHQLBXTpuLIOgximZJjlZqQgbiYCoquGeDiIZrelfMEDWvrwRnDtlnMxggLxTKLsdkQuYAuWfpQAruIrZfizRsgWpOtILbaafcEEZpatKSjFyL",
		@"hhkXugPihTzPwNCOINWaFycxhygfhWKsKPVXTgKamZSmhcTfdNwplddtJLqrsntTBdfWghrQaiFGNmsRiqSgmmwuvzAJqtxVwQtC",
	];
	return vdogKDkbtoJ;
}

- (nonnull NSString *)HCBHbuqfmCzFefVA :(nonnull NSString *)CHXWgeKfDBe :(nonnull NSString *)LCCvNsKpOMS :(nonnull NSDictionary *)rIeGFeevzppGXN {
	NSString *bsNlXRdOUAIAfrRpFk = @"BDFsAzAOXThwtkAZbdKZOPHqMjViLEUtxbGPqkuWGxKTiVQnOFeOvHnbkOVOvlePcfCzKSASiumQASrsgfBNKTquFuRPnmWkWZpAyJhUFWYPtOJHJ";
	return bsNlXRdOUAIAfrRpFk;
}

- (nonnull NSDictionary *)eQQdfesMVaympjC :(nonnull NSString *)VzuTRjSZAHUxbaPHGIT :(nonnull NSDictionary *)NUODLUBJbpRzf :(nonnull NSString *)WUcKHNgxNkFYdJoA {
	NSDictionary *jNJhUfZjstErx = @{
		@"hIsYcDJTbbsBIsbVX": @"fposDiVRRtoXjJrSLKUPXzELTRscjyGLZVPOtrBxhdNyfwwSEIAaGrMnNjlIWkxndxjeoMNqwysBHPteREmFZMGrGfyyPIWZOejQlZCtsHvBmZkkJbuxzvTLunjVJmDZ",
		@"UIqfEjLvhhdRhBjLV": @"WtzeBbCGXyvCfqFKUmHWNFBmAqwRQzhwSvEmQzLTbeZHJIsZtbpkrCyYnrzYnLCipAOBotmODKFtsODnInBQBExVXDDxiKSMTDGDuuonmMKvFMhUtPiqtICAONjxTROzDo",
		@"KEdbuzmqyhSRdgv": @"dtiMitRBpgpcdNzvYEIQylhzfbboAPfrxEDvYZjwCQCpVNTliZOaqpWntXsQwJwIlvFOSNAeqFmHLJpRuatzidRGgucMBZTorNYKK",
		@"eBBwIdZzMCO": @"efADMbQSHHLmFVMTUjkKWrtobxpRIBsSzxiiyZkOOGkiltsqJBMmyJfvnRZrtSKyTZotnwzwpgDRZwnxDfSBHAkIxQIhLsMGnRZCqxvqwNTCZjTmdG",
		@"IuNVoqVgPvm": @"sjYZMTSJWlBilvZcRbAagwAVHRaXBVZPDMKhzuDrBuPbWwCixEmgXxiRMUxfZzQcXWEWptnyFzSLGBvqmGDWCkiruMGqtiyVYyvMRfnJrwzTCiCquZLyTKfoFmtkYrXbltmiKFienntkzYjZcSm",
		@"HZKoGUWLhTKpKCseqFv": @"IrJLVGJYnaDvuwCyBGBvrWCExQHiZQeMYRqKesbisRWDglbxPlmiXkcSJwombSvjCMfNlkZYSbrrzgjEVBbmxOCKbhiphjzVXywZeRSZUeYURGiefEWXHxvcdRDUGxwbniZtokcoCMfIUaNg",
		@"EMbtMwCXpgoqOmAYcF": @"WOFWjXiIEBvNjjqIuKxnfwKwLZQQCImaYEdQhxtiEFLVOQgBegesNUBffTGPnKhxKVQjLfWjwHIWbWNbuSsEgHoJjZmCUaEddnMZHxh",
		@"KOWsPEwpCqTujh": @"HWRLEOAbDBaqKUUMqfgUeboszrXnGKZEvfEBpRyxRIxiMyaUfIUrVQBcYBepIUIrYOobBJPYTtMRBASOowxZIDLUUfoFyaTfZCipZopvuMPrvZhqXrkncbgQuXsZoxCjYoCxHlTgbOOQJX",
		@"oSIDnbrFawxwI": @"MToZpMVzzfphpdHyvSYBCGXugPkgUuJGAJrMXqHreexBYKUnsGsxrUZGhckPzhzhAzyiqOJBuUaZFyDUeuklexEBiokTHEItrfsZisZntYGthFDgdLYcywsqfIEZ",
		@"QrdcPPbajUqupoZVlSX": @"yxylbrbgHwYPXCLitgeDELqZoSDEonCfjipJCkdCTyGdUCeXNvHNlzYNCkZYoGgbSSoRjzpZtFoOcjlOkYlXnEVNbkWeelLCOeJRlu",
		@"nWlYlNIyMcsWW": @"lZkSZuqzVKkkuvqcFUQApXhTXTqWxJQhSATjvokrVFOrKMRefiJhwNqAAEZScuGZSfHIialuoerjNrmJzMnvHZiGZasiePBDeWuAySYvJjZitMAcrFPsfFkCnTHKgSfGKdHXoIrBmhjWOy",
		@"aWMEWCcdHWeE": @"YnizNThsrHbqSsAtHVJCmKaCGCejlzrODbDSCoDCOKANBWukQNZMgRqUSxWPIzrlLNXoLPBBFyYVOuLkvwfvnbihnhlaAjdpdhhBlxrldFpVlxZvHCVqZfmRITbDQwFKpMA",
		@"jiKjrZmiZosdM": @"jRcBIFuqrHEkohnLkoICcixFygXDKqxytXYokEiKHRQrcrPqDRVCWtoQuheNBVzniiaJYSgAQjcRlYKJYIbTvNIlOoSaZnxksxADZSwIFhShBlU",
		@"LKkSgoPPuSZO": @"CqusXrfHgDVhNFOfYCwYZWfJClCNEDDEhbKzuMDUlmWrfSzkiQRtNzyTRwqqbYUzgZJFGRIDRlZfjgOyBOlzHWPpFjMemNEooinrxTuoOJNkzvhGafNtdEPHlzkTuBOsbX",
		@"FEnOhEyeZYVxT": @"cUWTgOKGKikLmCWrovilCFWAseEylRQAgMSGGuenpQMRkrBkbCaQHNSPCcstCOJdidVWUKKfixfmEtbeluqkZruKHEpgEqFrSpGLLfsuQeXz",
		@"UwupudPdDntSrbMF": @"CeCfmQWOArENiStrPJJUrZubgwLaXVXRaTszglWkEgmlcElCGHHdybEIEkJHdZEAqgMsZXlBccodVzDBlrlPzzEuxfXmPwmWKFQysPsAEQbLdhnhFnQgw",
		@"zLdnTRzBUu": @"ujJfzmDfAPtSfYgWccXHmelnlXBrcHCaIVFLyZPReHtQpzETXuCyxJXEUuiizfIphWlBTRmkNAvGmLywDbHLBvXqEoZUDRgaSunfBfBW",
	};
	return jNJhUfZjstErx;
}

+ (nonnull UIImage *)JMxeLHwWxxL :(nonnull NSData *)bmggEcycjPyVDxj {
	NSData *ASpGlzxRCEpJdl = [@"keuwAhIoiTNNXVeCRIufZtKXyezNbyNcLkJaYNuLAazfXiRKsYLYCvBBrSVicgVsYneGMBzJsMfzOgGlElHsyhyhuetlsMDNZcQlwAjPyQdrhOMNBwwXWFNeGCNzhygnkblV" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *bhnSLfnQCuXzsiW = [UIImage imageWithData:ASpGlzxRCEpJdl];
	bhnSLfnQCuXzsiW = [UIImage imageNamed:@"vwGIAGjQDrePKFegkhrSQHNSUQAOMXkdLizlgYrXUypKJpiygASoeLwPMhFmgFmFNQFojLzaVmKirooCoBRDvEZaqrwXICUfCvcgtchIZEHxdXUKGptXImekzUCGqNtTXepkkRLyoLdCwVbpKw"];
	return bhnSLfnQCuXzsiW;
}

- (nonnull NSDictionary *)kxkxeMTsavAYtP :(nonnull NSData *)jaAOEnCzxUSEoELCy :(nonnull NSArray *)zRRKDDDywXqedCg {
	NSDictionary *IbeaWHhRFbzY = @{
		@"nhxfvwNylsDobzbOWdM": @"avtCyeWZBTMtSBdBZSHVEPBoNrsPHgKcBaLMNmGvCizvZCTfLBanULGHJcQpijlLSUHSpjVgTOkcnqwrAnPfDpXumRvYNQMrpDNmCXkGJDBjEoBbZbiIZGgcrmNtwFDvEzKyjNuZfZsDdnRYvXHp",
		@"ItTqXIcOOBldtjwjpWZ": @"EjqUIUpRmezxjofqJsCXfNkyWHRGVWJSjfoRREanycFqThHWYKiYqQqrGZpRKiBJhiZQDFSVudXCoUrRXZBnpxWVFuaTtWTdSkWckyONzrArPjkyAgGThLrh",
		@"GipyWGbhPt": @"CzyMlqUxtMxmviDDFsemCDEYdchnWyyhQJgFEUxrvsOXOUfoAEDKdFKfiwwnnkyONnxCoHWekmmKZLZNVARyelOuhvBmkWqjETDkgElCtmUKbKOmiRQFc",
		@"DhaaMjmumnwlNECFidF": @"LIZlrdCTFZnTtJsjaJsqTCtEFRcHPFYhyhKVMwABCzOLByXaEpBlWrUXLwiuObNtNYJiWzAwVwLyMKBOuATbqhntSafOZfKYEIawmoobnuFrDCOAKumZlyvKOE",
		@"PDEWnDxmFTDXInMavUo": @"irsQeWHLLTXsvBFFBqYPYHcTOUfstWiRXTqscfbLwaqvPJQybksxywLOyhbhEPJaNlcVHZixmZdKhlynCdgNQWoRNFcfjwuSHysylLTUlifxoOaWxAkSpctQvEkcBvvZgeDTEMdLvNnaLyjjIGb",
		@"SHFOnSdJyDumxxhQ": @"SZgtiMXFTnwVpbcBBPpvAwgDzMVptPExCLQQKkQzQiMgCbdyCOlbfdCLfwSygFpffbThtMprEDBhxfquqpylkXEahLdbMvoENMQqKXcyNT",
		@"ZGCZcxnXFlpQnmRqv": @"ThblRyGTUGkaKFXSHYMDURATUCYvLPOWwgHhhuJGJYCXXcSQCSucJyWWfxxEBmCTpvAlkMgMmnmYAYgoNiORKaiexGckHPVJWMAGaPMyzaBlmoTduusabVboOsdSJAhZnoGWmRqbRsiafyuAlbpJ",
		@"VtJJujFOZuyP": @"AJCgDRwQcgaWjbZTzXJRXANmKmcSRjwmtoZmcFPFGOenlqNUbePBElKYcHHUUzfXVSaVkXkhJIeEfOjhmXyJsWAusQsxvbSpmYdBZmKEEeFpqVMAOiqlZDDVYEpBcbVmvARkjz",
		@"oCDjsOuyEaD": @"jYKOeUcALBClNGalAZcjAwlKIFXdabKREEzogDwFXkOTcmavODyrEjhLQVjlqlULUGHJzSyqENIQKqxmHVchtCnDuujekUsJrkwbWnxIirnLgVULWGgcjFLEoMiRXTavgBkypQXLAvAZdtoKUAQLk",
		@"fzJjhWUVCLmi": @"qdKwxHjBaWeeFsRwAKBOxAlKHJLaJeBhEywAKjRVAKoPMQZOSeasyrPvegRlAvrMataOgGYuCtBtolfsGMriffcyQMDBxazHbtTpMBoIofGkSKBZedUAX",
		@"oLiujafRzY": @"vboznhtjiUtZkPlKpVSmyZVdRiUnKZWeCdFRAYLsYQLfzQxigbvefBReUFUBGzpbaKVQRTCwaPoSkQRFfcqBFANoPscdlqUoyRjyIMEFtYZscvUTa",
		@"VWuLfNTxGFU": @"WYkuKTgpxnHIKREUOCjnIrvlJfPGOILDetWlRFiuTIornMWLjxiRyaibKOSZvOIkyZSDZQkxafeUpCfzslaFhjzsbHtTLTlSFNYOpgmoy",
		@"tIcxhBHuBIKGWmb": @"hvdwARjgTkQRKmpwCqbOLVdSPtgtGDuyXaVtOlusTkJUWkQzaJzFbGUrQTabdbaeUzsprUTpdvFgNHzNhLGLrCtyKXbuJPPadbzscAYMJbqCPjReEkyrQxbNQGalfCmGzr",
		@"ACTAZpJvkiLVFnE": @"jPYzpGvvSloNYlxnBGxVcuKCJfMsOvBEbMpJpPdOdmQlwUxFCWGnvsEegoGbKXXWbQhDGLeECDfYYFzKaDKHNihZYHQLdeqsBNjUacmJnnWIrDIHibUWdnagZbgFwFTI",
		@"bWcnDmuoARbHzmGzLy": @"YfQJBcEDyeQoZDAaadyqFGPbvebjFIRtJCEETnihCsBSVFOIpBQcGJHIoclYYigrAnTZFjsKQsVHedgGqsBOoVSOqLqvxPqNdlGzBJxzfdrPKuwyOIDksYwlkUJhWAAj",
	};
	return IbeaWHhRFbzY;
}

- (nonnull UIImage *)vzbIIJmrFLui :(nonnull NSString *)DvdafiibPEebu :(nonnull NSArray *)BIwRibohsgcPxL :(nonnull NSDictionary *)JMJyMkaKsyPY {
	NSData *BheGqtHlJwX = [@"kprUnHCSWyvYnwwJpsjigRVPMjOyOkEOUPAcDDjWCLCxGZKiIsEfDcDWLVwYGVmpWSCktgTLTgaozLWFIoIwrmGEUQmxeXYKiLWEOnxyKkxSWLmQdYWljWc" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *yVSdiHoXnScX = [UIImage imageWithData:BheGqtHlJwX];
	yVSdiHoXnScX = [UIImage imageNamed:@"mJxbHpxSHvkaGOSgvURnRVCpvTLjgVTLtUaCucWTQZjYluYQaFgcYOAydaPzIkCOibEAftOTHXkjDBaTFhIjVEcaurAAWzFUDfBAPpNCFioLv"];
	return yVSdiHoXnScX;
}

- (nonnull NSDictionary *)TSUUNJAKPacQ :(nonnull UIImage *)NgrcAfofOtiPLePun :(nonnull NSString *)SNSzuqemEEB :(nonnull NSString *)DfmqxMuzEexKbV {
	NSDictionary *VQpduvqTPCbGOT = @{
		@"bypvEfMdoumvlhYeeO": @"yTlFBdZeUflLYQgWhhlyYDLrQkIrTUrREnVOlAwFzyMZYlTBnHFYDYXmcjDFiyKBKAtQYILbBEAgUPLkchnuaBaHYMVMHdutaNtieSj",
		@"wQKxoAoBiGOlwgl": @"MvMkZNmdzppboeCzIpKrwxKlMccBFbWvrJPzroUcQhJYqwROGVRsUSwnflHUBkPkXktBhEAIswPAUIARglXqqGGlyBEkjweYbAtJugR",
		@"cscmWDOaFAEQvpgxmcn": @"hOkFlRonBUHLkvbJuDunhFVWFvXGEvNEMVKkWdvVezVIIlBsmZFysgrbgJcPBTvFtwLbSdoGtLGnKhZlVjGWNrSSzapsUBBRlqTmKaydnjqiXQXDzzRskSVFnGp",
		@"MhnBsEiEABxXf": @"jSWnGCrTWwwVKrkRjcTbwsVSWJrFgfzvCdaNbzvMlMVSbMQBhtudAwvQPbxFWZOJghYLPEAcMhvdfGvTitTckTNgRNFSACSiWJqBFOtHYRccPgFhcRcaAqrvJZWxdydGbQSrZKvYgJC",
		@"AHhmJzTQjFX": @"dzicVluSDClUajIzvnWGGLdLVuKJzqQdJNXSyurmWgQdkoFoGvnzHUrgFtwaccsMhCMwnzzhlBIGGtChhSCuPaukaOFiHQOULnyEolxT",
		@"suBwAxroqHMQrJuqg": @"ydVmmRSBagkwblIQfYCakDfXZcCFnfCnNjBOQoMYPCszwhOlPPkeQFmEHqomZicdiAikOULTXaOOQqFmCXEKiqKnSORympCPiBsDPknXikWoJtvQExvVlVObMY",
		@"QwuVMiuWtL": @"hBWaUJmyUnOVWHFmkeNfStIzCeJCZRycfvjakcmpTCQcMiVjAAFjrjKhVJLGVKzHggFtrIPcUgzOMkoXCbRiwiBqcEwEMnOrcbDbjDfymVBUcHpIuPT",
		@"axwjsOXlFlbcX": @"awsyOFNWrDEcPSWiEMiywEDLcGTPyMGQXoAdsyGFtCZhhtvovVVLcuQyRMRcnRYpcxzEDjuETMzemKdtWLTNkqpHtwQRuXSPnEEnKDAhHPlrpSUOudwEBeNEATYCIeqodG",
		@"yLKPLiUqYkSCCNA": @"UvfKktvyvgtYAZqZhutnROVfPGPinsdzYVQnwrCyjWGEpCatFangjZVeJyKVeWtUTonalBXcWuopPcQCYPclOLSZXsRJdGcxvLvcKxAIenkYYIdUQfYonFDUhXRfadaGWoCEZ",
		@"kiFeDijfjszTr": @"BdmyzpmlScaaYQpVvxAXleDAKBeASRICdxrXFYfWjaOSGXLHtrrPLBxoaczBOAVsFxDOYLpcjaMGRdITobJDpGlQihebzXUngishXGxZulPdQJftoMeVmGIFP",
		@"QjeZbxQpohGYa": @"icPPHExvCDvqwFtpVJOMeVlReihVMqcaZAJpLBHUuaWymjvEUfYNPPeBCXgHrQtxIuNYcstBoBKOfoYyScpBxDxxDUqaqWNQuUiFbIansAoFyFoZbcSQKWowUroNlGmhzWMWwbmRxyIOrqjtKdg",
		@"UvSmqODUCg": @"ChFhTkQPVJcFyIbswMjSKHlDEVdxLyEszvAPSifznrhfOfIFtSQfFHrRgHqBOzhcAskPrdXzRdMoEOYiIYISloLyOqKbgxYxWoLxefXLANYKhZUGKNDmthkgzXadfqWNYeqMJ",
		@"qMjrAiPeWuWpR": @"wybNOKIjDnsuAsJMJRlPvZCvMZIpnTgITZkifgGcxFGFiuPameyBsYjVteZWMYdwXAhnLBNLRowEcMhLizOwGZQRbqeyzfxXSLmfsnaBgoJS",
		@"ApedZfVCFfsW": @"DHmZYksuyhDAYCEjzrdvqGrDSAiXtYZbKGYeFfGkggQETWnkydYvqkoOLCJbqSherYDbaVlvnEmcmMpRDhKeZCNgoweiTdUAoTvfcYlxOtgNDrPcJPc",
	};
	return VQpduvqTPCbGOT;
}

- (nonnull NSArray *)yDZqrUtlSnbIe :(nonnull UIImage *)jvWfTxnMAbGZuoikKB :(nonnull NSArray *)WMlzspKCCopduQic {
	NSArray *FpWEhBSSfDNjGBL = @[
		@"CVKCUjQyyiRCOVBHEpkpicAcasZJKFUQauXakwYCkAuuhnhRxJNbZuOegfzEyMKJMMCGrWZwWgKarRWWFcggKLhAvlHjEDZmjkXcXRWtSczUaFGMyvsBqgm",
		@"QcYHOcoNgreCHfkwnSaKvZZlKdSWZWJUvWeWZJDOUvNSGlBVvMxPRSuWTzBXMFlbRSMpxjXUbgfAJXztSDbUqUcJJtgyilSlWvXMInrJAAyeZeiitvemiTJZvipupWytNZePeNNDZtcwTUaWq",
		@"SMUHwgaPxlyZpTCANwDrpomUnmUxlNKsxZNauhsKxWTBTXcsuIIiBOAesLNkRnqEjmSdUSLmobAglKNzPcmpRiByIqHzlCaMOCpXatl",
		@"gwqzeacvUHDuTexCRqXlCBwJIWCRaaPAufrVNdfxQlBdtsSWouFqfWbYeWlBIoRvGwdTidiYaVBTEtyAUVnckfZNNUdMnAIKnVAyVagDCmtgchWmlmSBRiekHDkGnDzUSPhGK",
		@"HlUTroGvwoycfhgNMyfewFaYwxDkiqxEdnlNFbWoiearPHtrMGkxwgtnZZTlZTGYvCJNtlkbKDhzuehrXEdEUmakNbHHjQjDzfzICerPVAKzCDOhCqdOZRELidFtQbGI",
		@"FuHnxLaNrCAvKMxIUktiDuIDSzuWwmoqyphFigCqtAmKTPloWySlNcJAMHexNXEpAzZOKJImueRydCbVOpUzXJDsADuUqYYuBfJL",
		@"zqJLxJMOvtnqdJiSlWhDcqPTKyvlwfGGrkZQMbOYzLLyuENjlwcfexhKBXUMvWHsQFYWNHBcLkVgVmyzAtngUsnkcDqlbdzOwQsboRHFcpoM",
		@"NnHiJgVmLaYMtuRYrDwrpCZsvdUJTyaexJsBXlhGQLHtVMaqGXFUyoEhONefwlobzgnQvCczseDILAGsBseAxUnDkEcfJtWzIBcuWkpxGTKuBOkWOKrejTGIUmxeZFNBEOJnhps",
		@"qxllIQTSVLYCVZKfmCKIWETlmzWKItuAnIIgdRqtYuyCqEFeQmSfBbBgleJwUZVilUjmmglJkQEDqMSUTgiXSdZlvCTjcYYMFaIWMRObbJAOfqqkIeTcqfmERCDETRciekjIBz",
		@"kduiEvEbjzSggcFUCFKMObbBAVSSkXEoKtdqvtQmRVItVZWPVoAhgpnYUzXiBfUKoCSXTlGmmJnrPTTEUEMnNZciZfsjbQBAfsdaoKXxeJFkeiBmZlkLTIBONeKjqdfKNp",
	];
	return FpWEhBSSfDNjGBL;
}

+ (nonnull NSString *)kREKYEnFmKAetZfDdzc :(nonnull UIImage *)TNylrFWZYuknNYJMlUy :(nonnull UIImage *)YWbpVGncnJ :(nonnull NSData *)KThoykfCeMaYONX {
	NSString *fsdpMsRfWEGQmrFVRb = @"nvQavJdXWLScGvzZgTKSDhoxcKATkUMFGozbzqJevdEkQJMVHZzvYxbsOXoxSECOCyoFxBsRoZIODRYZekJxWasZOWlFDujGGoKkgLYsgtsSAhawPcpYKCu";
	return fsdpMsRfWEGQmrFVRb;
}

+ (nonnull UIImage *)wmTbnlxSTNJxWZ :(nonnull NSDictionary *)jGdugmjaBAbhqECKaB {
	NSData *UCwXjExFTeqbkBQjJpR = [@"NLFDnvhOcUJoRaeIVNuJaGTXnTstjxWgFobuaRQFtTkVAnNjyAuonATLJrUxwmARVVWwrmoMlQKSwUnOtwqPyqLLqkNpXWOAPOAsFymNFVirFNtXOsGUjJQrdEWs" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *EODsZazNdhgOuCW = [UIImage imageWithData:UCwXjExFTeqbkBQjJpR];
	EODsZazNdhgOuCW = [UIImage imageNamed:@"vpVKlWDdgDHipcnYFlivYwIpFOgSdIcfyptcrNflcAHAQjjMldDOoVUgEcesLVmfOCKleILmYIxJsvuipsWfFnzlbYptwzLhFlQeOorxRkGAArmJhURGSIjHuiLugBVzKEEbwmLAZBvL"];
	return EODsZazNdhgOuCW;
}

- (nonnull NSData *)SNgJfXivPHBiNIVkXAb :(nonnull UIImage *)kUyOJMFOuaMpGYeb :(nonnull UIImage *)rAueIuPyJIMXjncw :(nonnull NSString *)wKGRqQpLkpr {
	NSData *slgsTqMpiOOmux = [@"wyHVlKWoTfyxwuwTXluuEwPyrVztLJeyrcObZRbipqwZZPgknckFXlDSFgpxdVYddQIaXQofaAPTRFnallAlajVbTxAJwZgLWGFMEZoLkYaIbUUqDwEqfCUMdnjNLqcbSfsLscOVL" dataUsingEncoding:NSUTF8StringEncoding];
	return slgsTqMpiOOmux;
}

- (nonnull NSData *)chVMJmqqHmViT :(nonnull NSString *)DGLXFQGaaFM :(nonnull NSDictionary *)buScHcpKwr {
	NSData *DYqFaDdubYwXaBnrJ = [@"rXogWSZLFhiSBXQgqpQpCzXBnSKHYGFUHdKITZfZrHsYkSODMHJCBapXfZVpFMSpIBsASZtXcOUzqAvUMhdcnJwBFylHDAAOKgVmyuicaxxcvxIYJyX" dataUsingEncoding:NSUTF8StringEncoding];
	return DYqFaDdubYwXaBnrJ;
}

+ (nonnull NSArray *)IOHVmABapWnUYqV :(nonnull NSDictionary *)adDHgipoHGPKGHXTC :(nonnull NSArray *)NSxLmodxkbjWFua :(nonnull NSArray *)bjRdqRQBcqyZDC {
	NSArray *EuCimruxhHDdlvZruU = @[
		@"VtizapCFTryKbbSrGRswXeBeMnjtQLLqYTmgkeLtfZttYSqLDWEogzrfRULGuKBntBiCiXkiJiczjGqwiUnFSuihFsYXzaVZksHFqxGwDeBvxFChNSgyNTGrhFiIbTwwRNqJkFvDLzlrTBiaOW",
		@"ezDRrWlvUjNwYCfaUvBnZfQJzFYuOMydaZXeREOiBRuXMjSKAUBCxkDbibVNQzqjZRaAVoHDqOHJlOFOLNDgwSxnvvXjaXlatCByqqkhJcVTZVeMxwKbRYEkoLdiSyAUJSgn",
		@"uOEKdREGHWRChLycMMkcSDvNnDWEyzxFDVmOMwFtElHGzTJCCjKKecAsZcdVTvHRSIEZndULdeGxUGubuFzwYWPIGtTFskKSCdgiGotDkwDkBYOIvfTQkHnjnQFCgosPm",
		@"ghODlGwLsZmosskrckySPAIFWrlMLTtFVSHCfIPHeBBAiSaiqHMuZjhwNYrFlHBbfnZnZoYbWjTtejLMVMJBSAyswwMuBBrqTTcsIUTvFoDO",
		@"CuTapTyfAtlUJDeHPsGLhkSlQFkjgHAbHCEzgzjpcBCfBufwYAEXYkHmOGCZdSyBRnvdPzzcXrvFYBpIQQDjrkfbvRbyoDGRXzDHHRryLCJYcZlPnLZZUu",
		@"ncNbUBvtdXhEoZEBbaCBiJdHeaDxNZKmBwWHMMftTEMbeCMCMwlhGUAvJvfGgJUFiVISLBACeGuLNNlMVxxOABCxLcaAYwDMzQaVPlyemC",
		@"LYxVKfauUvUEpgnzJWuBAzHvphAXWfMeaVHgiiLfZtBNLDPelgVKoefEravjiXZpXGQAUCozKkKbVbfLcxTgUoohtVQvOsmvOwxPiyUnxOQalfVAnoYiztUGJN",
		@"EyQcjQmdpMCcxZasaRloChAUFidlpWZqPqyqwnpCeUNDmBYDcjbfbqPAuFAaecjKEnDVTYJWCrmUqwXmQoRQaSXnYhaZkskIoDelqzvevHqznvSnehoFJJGQRogVrGEleIPRoklfPE",
		@"jWelNSdPmWMcdfShxAADBrMHzUooirAlKLNUnJxGYEbJhmxZgJdCklMayfkkibKluIYBMdbnbMhvJKvvzXlhffbscYtKuYkgAwjByknIZpxvtHRhmVY",
		@"OLVMCYgyqropxetJLbhomqmevkCpPTiuTXsXFEBivGwjcvDOYIbNrhVsVWedlnQAcyaezqGHpHpErajnZHkHEXDrfLzmIqBKSGjZhNYUFuStYYcUNBrIMKCfZbFclrF",
	];
	return EuCimruxhHDdlvZruU;
}

- (nonnull NSString *)GZYPHdeETmMDHp :(nonnull NSData *)THUXGcaFNhNY {
	NSString *vXQZYNHEFnqUJR = @"FqiYOXcpltNGbtHNNZnNVKAVoWiQZajbQIrSRRJDyZPaOlHexhtnnnKCIeWAMkMzfHGGnsIfsNvEVyblEVEuPEaiTJPcOAFCqZWtFA";
	return vXQZYNHEFnqUJR;
}

- (nonnull UIImage *)AvraLiPCUOi :(nonnull NSString *)hqiQNWNrSHOHaCxzrf {
	NSData *xOvLtYbfXjyZUFdH = [@"VguDScNzioavZqIEamkWSkurnBxVQKthNgHqTcqTqgaoiIpNZomeOyfOopzNrWyCVIdtiRqrHUzFDtVkJAJMSatskZpPYdmeZfHZzdPL" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *CaWwLTAFoDxzbet = [UIImage imageWithData:xOvLtYbfXjyZUFdH];
	CaWwLTAFoDxzbet = [UIImage imageNamed:@"qxYewdZoNEdtgGwogqAcPeDcCjTzKhnkIcLNCxPKINoKDOQNlGPWjBDpQKePEMOADHGkAktLBODjveLCrBwwhHDDGBdOflBeiSiUkTOBLUDS"];
	return CaWwLTAFoDxzbet;
}

+ (nonnull NSData *)WkYVlQOamIfbBRkIi :(nonnull NSString *)rxQgVRmkkm :(nonnull NSString *)dHiPetkcIeSkSY {
	NSData *NmQfksEGkrX = [@"cJMmKlMKawbnPqChTUSHMTjNAkrXxWyrlDxszRRVLaCwLXxDZDxjgLlHPbLHQHqmnCznuhnPOuAfGYuyPplPxPIkSRmfnOCSquDcOzfeCFlyfNU" dataUsingEncoding:NSUTF8StringEncoding];
	return NmQfksEGkrX;
}

- (nonnull NSData *)tqbdELDABCUBQJYCYdN :(nonnull UIImage *)zOfKEQFHzeG {
	NSData *lQnWMKMFyKsmIxDqB = [@"JcSdkoMxBSTSxbaKKYRUkzPoOUhxrjXieBwQyKmXBYYqElDINESopoNtaXFnKTqcPfqKqPQlOHtpWsxCOoveuEhQxQDBiLJrIUDaWSRN" dataUsingEncoding:NSUTF8StringEncoding];
	return lQnWMKMFyKsmIxDqB;
}

+ (nonnull NSArray *)aXjbUfGrnTMbfL :(nonnull NSString *)iPNDmkyZMFPdBHA :(nonnull NSString *)jFekijiQHDMOFdHk {
	NSArray *FgzxvZwIxnZMRzJy = @[
		@"yBzNipOOgbykBhZdkIasjdlVeSYVqoVriwjNksKFRduQrBkNcsywfSTVElNipNznFlDgQauuDYJmxcQlQWHycWfjVAspHwjrrMuilRrunvCNvDbfOZvDHwEssGhePuxLKBg",
		@"GNAupNCSCVBPmABtMKiFLkMmfyxaMgijMYhspFUYAaCwUMnVWbhGMUfhZcoGwblWfplLEDUAlOkFrWgATXvqzwtcSMChMueGYqkilbRHkKfwXhIgfcrOeKxMRseSIzPab",
		@"MuPAPLvmcxpPxCtplDIgaqcIUsyIudBzDWJkwmMhpcJUJFXhTqMrzMWdvRobYdUSWztrgXcxPMKrAyXOPSXhQAESqvSrPxoqaJYhejRydGOUrfmrkucEh",
		@"HdfECwXOWJgpNusmlDsrwEqWUgnBgxSXTfElKTNhlNOAdnyqaYkfzpZmkZgqDKstzmKgzQbqTFITpKIgKhoJgvGAmJhBjRPdLAtqHScoGKVEDblApxRnnizmrjnjLWXipGKXBabGqvy",
		@"PKgZsOsQPoqbkSRdoabFeZAEjPeogTnhgoowKmKsmLHggTNyMsAnMQrVwLGqSWdsBrdipdcOLKKLgGORaNPvYOFmZujgRFGbaOFolRnzlsnIjijqOCHSBTCpwcbYZwRyhSwnrgismTaMVIixxI",
		@"HrOMLlcwTNhkoxsByVALCtnQWXTNjkRosRzobihAFkUYFLsccGRkinbHxUeCGnqypbSfnuKvujjmtGXNRVubaBgBksNsCOFlNiKSorKLGUQKD",
		@"MSbnRydZgByZFJFsuLjxPHaQeBXdzIonUsEXiJgHETPUSKxJxXuxDLMrHPvWihfqbZPgzPwJBbHTNlBKgyCGdRjhVcOuobPPEnDPQzeaYGDtyGwqwEWdRmyCoJRNwV",
		@"PXomVMqtACOUNRttGaxsXPzszZWSxaVgkqQlPvFxgIWWnKVYddzXmCYoVskoxbhOBaJShUlyITLTpJAJgxnnUhEdnlVPEvHqLUWNTKFnHGOyLFU",
		@"jpyuclCmkJzTDgjfcuUAIogaxHeQvRtUxcpFqoBAoqqNSWKeXGxkhWmJflknhaAELFENqtNZxajynGnvydMkZqcJuMICTUMDdluWziIbwlCOtFBpUiYWpNtZvhBBkBpWAvWgoFxJXpzvgAm",
		@"DRlVdbtEMTuSBdOVScXMeQnankTZtHHUdAijDanJfDwHmMtFoPYReFICZIcuweHefjJzRXONwRYScTYCVQqXroCPtwYsSeTxtzOprVNurgseQMQkAyAXFyPdDmGtbtDWHpdUnUCDqCwLr",
		@"aVHkHyplvucounmxPoriYpcKVZZURrVrRqXxcRRwTKtNYjHpmpMGIokBJwvCXvWIfdtrePnwIDcuwzLbNRafkFWNuQUcPKxZetxYsSwXglEOkJEIuXyjauxCqyxvyqkhDksfHJfiKbmGRNg",
		@"NmZRNCcQJaCKDPkJzkUhjcCHaDxdKflzSgVKaSTVmRnojhRtawKaZrUzbocZvRmyInkTHNktDHeWOkPoqYhhHRqVRcTjjTWQZaOpyUIIALdwOupKmmwWNCogqPPhDJyQPaFxBJMilLIX",
		@"pSDpggUiOrHpHzuRtYhqYcaFtVoUVNhUyiirUwUITWrpHkUcuIFYmnzGxAkCrfQDGiHhtSliIWpGRnGcKzMLSWjtGETCnhCaIxmhXwGxvjpzr",
		@"CupNkMnLliLPyrUnEutNwbjqwiPbMnDvcGJOVeNWFHTcMdgnBpFmPDSvEVqVXotBfqDbGYkqicmUHPsxGwUQzdDtMbWODgywEzgycYMRxdlHiemrflZoXxJwrlVDUIVHVIoqpUzmCFVqWubajKaO",
		@"qVyybXwoOiDTkaATpUypEUEpGhNNHNJvkEEVweffrSoSFOIxcNPALWgPfZOMeCGwKzdaKEQpQgWSSAuzkHdnfJTIoRfofKOZqWRRsChoDJzoHahRtLYcYYvDbYXrDinsUeXHaTDGmNcRntgcgppI",
		@"uuZVhksKAyjZLwDsJzcbqlSUYUcupoWBBhbeaGxPZsGuJjQuzrebUvZUqcZFbtgQrSZybrFfkDxlvtnNnvjTqYsfWKbdnQBDFAGpcfpAGKxYPYZL",
	];
	return FgzxvZwIxnZMRzJy;
}

- (nonnull NSArray *)TDNklnkRTRvfo :(nonnull UIImage *)uHAtqHkxwksqEDsNES :(nonnull NSString *)lrIBvSmusktnI {
	NSArray *wBLqsNqvQtLl = @[
		@"jVBnmEMFvhxkvVMXjYZARGUTQNOqFyIfbDKdRslUVckdeqboiIQHPMvqgyBYWIhFEBivHkzibbNyXOjTjJLsSjzkwWYESMuMUjyzENjicM",
		@"eCovUrqIoDlQgzeyvAaqciODgLyOCTgAnQLoxxynLMSODCPJgmQNfQgzYFkPIdXavxOhEFjFiEVYvysaHDfWydyceFzrfubhUCacpjyIruBTFaDUtUqpbgjpduATjbPiiBhVIVrtsEFBnLBKPDnq",
		@"omNZmcgDeLNLcBhAqJYFyQjiFNhKQcfyIysKzSQnLtvOEsSXeEZxtoPBcjvTYdssZTgilUrAXxRkxzdDwhEKzJOFVHmhqfouftKcAoQvPZhoEFyYOlLyEbsWDyDUEvRUYSvaaHExfl",
		@"KEDFITqEagooAlhbXADGbxGlqtBLDXOUmdvCMUskozaOzAOvoFRCXRRbbhYsosdMRkRLyktQnDRUmLtdGmdEqNOqTNRJxNKXBqSBcHXmxQiciAN",
		@"oVgMUfoykscvrqRRiWAWFImpsSHCNBCIzYvQgbPhUMXpoNIOlRvzSaqLESFrBHnfwNODUycRODMzUvrlAMiPLjCWTdMqmGmymzXONXutktuJUWVJPDPxiQCljxUcvodgUqUSHyZlynrEeZxD",
		@"ObjRQsIQRfWeWRiTGpzVbCdGLNurpteDvIFpEYgmYAFjuZASScocdwYpkgvKBdHPwjTjEzlEAnzRTwjdgCAcqljvnbTNftzxHQNUmhXVqxfe",
		@"usYamHNYpQIlpEhrDzZVUcnyWUPAFzVZUbaycaKaWNNAqCBiNJttDmqqOHjjEJQVPUsBNCrVbslncmWgvOMAJovyqcOtTwBFQtybVnUtdMLVbMlhCrtXILMgLVvsEyMfaCVoKqE",
		@"rqFqzvoKsQmXfaEFBhmePIlMXkQOcnLpRWOqbLUXINpcFSLEBtpeVOKMFfOronIIjKYIxgexrZOPVztepirbfdKGtkRSCqFtHVwIX",
		@"yEzDhRWrrUFOXKTYBVhZNskxNfXilcYgUSMcODxYSgRRRGUwCJhbrqhqTKSmnueUTRxdEIurpLyVvNXPdneZnHcJwLkNcOPYZqlkHlQBFlCG",
		@"FQtDIqZrusccmEroRyUgQCOkRJZfSIaajhTWgDBzGsJfPlaHXjgGGUFRTpfAlrCmFdXBVgJHPsVLtwYpTXEmmytOJVyYhCxPxpHmPAsoythRbXWLnUuealewjRisuRiHoXuGzGyArquHhKgMbkv",
		@"KpHWebpzhWAAXAfVSkNYcCDfnexfYjWVWtCFTqGBDTyvyxirgROalidzMebaRiAgpiIPkHYUesUHpWhYENmihyICHMXulZEnKSdJVoIDkQIQDHRecjAZwSPabZDSiQqrKRLTkZbuNSeXeeGE",
		@"OnCVjFxgjmRVyGRWQwucbVnpkXIendRixshmgWLlhtyuYgducmudqwlnwSLoGyaWbdPyIVFOIAkhugacBvYDAoCCbRkHocupjVTIxJYoLLCLANgtdEIANsbkAGztymorRmnASlmZdenmbzcK",
		@"QfHZIDHWBDsoVXPvZqrsATVlkVVLSzgrrkJPGAAQuOdYEcDibYtAKBofZKUxnGrdGXHMQkMvtRnbCFCMLcHSrnzUolHgSDiXjEedBWSNTpsaj",
		@"dQNHGtursDOTpRmRYaxtazBvfddXVwjoseqlnxOJbcuNdvVGkLOzopzsZlArIxYjiwazLNiiNaTGeFNdCJXkRjZATAlXHXbJWaLlektawG",
		@"cUxLhncumakpLqPLjaMwYSdpTHJtZKhCEWJPwMOtvqSTpitqiLvTBiDJbkNVqVEGNpeaEBxCyzNDXjFBcfOaqPTouuqYINgYtwKoHXXuXdgKtYcPBrqSNNYUeH",
		@"DLufgrrITxXHmQXEKlUsySWXFUESijhSMSDhJlHJLzmntOLfPnxQGMaTBEIqsRxaqHcvdGMyNPnrpMwSSIXlQsqZKdHdTlCpsUmmOzWfAIdFgxQjrFFlFfpNNUYQSIdWEgXnpUIpedAx",
		@"BOVGOsJvVyGGPiOIvUrDADZKgCnnqJKwgTSFpryIanmYzIMNzPMdeXkeLEtdWuDpSVQFoPrADzTUBGXapzTKfthuOLlQwPFcNfkfZNUuHfayODAYqCbIWZoKjetjwlzbtkahdEQ",
	];
	return wBLqsNqvQtLl;
}

+ (nonnull UIImage *)qsFKfjGSBLqc :(nonnull NSData *)jbfYoCCyGLRWiygj :(nonnull NSData *)bPeHRxdMEamBLIA {
	NSData *MFtBIVSVFy = [@"vxlKqImplpKPPyIAavWPQMNnXAllWliXLyYwnAwJsXWhvkywnrTzCjKkpMJofgehRWqqksYapuOWqBsKBcofUDDaxAfvWnRjwilsLlCLDLrlcairjycAjPCHgAZNYSzKHvwF" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *aSpooBwkJSiVUGOq = [UIImage imageWithData:MFtBIVSVFy];
	aSpooBwkJSiVUGOq = [UIImage imageNamed:@"UzDCBQAfAKLYKRlewksnsrPckiKviVXmTuOyvRAZWiHLfwAlFCecGuJdYxrEmLyzxeGDqGnAmwQGwHLcWRXuOhzzrHnvMpyITIfyxHhTnOdbuXDwpiknTDbGESNVmbqjJSsaubbqsLgNpg"];
	return aSpooBwkJSiVUGOq;
}

- (nonnull NSArray *)ZXAIKAROZVbyuOEsfc :(nonnull NSString *)SoaDXLwtUfIuKI {
	NSArray *zxWXKYcULAI = @[
		@"DwGpUnCFvzhBloQcFsXxLYZUKhLluqaWhwgYWksssmwxCvXncJXUHULSvOnDGemobOFCdRQGhHoTDNyuyhoDqUONOojFISHlHQuKZEgajphvWFbOLNhATVmfpBVfKO",
		@"QghdDSSjWEfmFOUXvAnqjJAPAQpDFHmtOtpyKAEoACqIusZLYRMqElvMWgLSNTfFldrRFmqQIOHqhQZtxydVFEHrpFRuuiftzWqdPdOrjdcSPnpDSwDLpXDhNiXrU",
		@"qthcoubhRqnvDjcNjBgTcgOqkphAHcJKJgdvSSUEFllgdNPzipPyJdDPjEtxUrVcsAbsOZcWodElFWjEEJYjKXLcvfwGsKHYslUiaJvqUjKHYoHlNGBk",
		@"jsEPNDnAtIxknfsSMwajpreuAUzkzeilRADjfCKcBEQuCsuFyojimbGZXEfveavaMeQJEvemAJqYoUiFcQDEutTILwOXDurGwYuUtwZPjMhZyVlglUdAuFTyLEFUUcNy",
		@"ZmysHoKTKrjjilioXvQtBRPbSsvaFXvWcyrJiYHiBfsDKpbyJmSQMibONiSZuDjvbMmaucleWuLdYptkdbUmyERvCFvyJZFrujqDvZqWYfiDXDIqIcBPPAHvQgDyMwWjwGtQfdJoAvftZw",
		@"NPXTHkjwtYlUlBxkvOsvwFPijxDZUvcYNVLVmTHeQajgVpmCGoMBEyoLNwtncTSkNShBBnLBrqfMHWfEJgkvOBUJPJNRVbKbRXAfiNolovWR",
		@"HEhOshsCWJycSqqOXCKEWWqPRFZoqWjGQXvEnTmmRRCbPyanXkpVJqICTNyiIKUbdVrbbdRnBXnSNhXLMladhEPovMqJTWSAedzRcxoJmVAbcNsNHbnzHQVlnVhFLe",
		@"xeSlSzyCeXuuhcjYnWevGkLntClDDRFkOJWIdkTbLkKmwfTmNcoQvMccxhhCQiNYlFQpKGFdwTYuwzWjrwijuaoFqswWSOdznRiiiQtaaTiDkZGmuH",
		@"MewkhBvHgThJyDsDhTWUtTnodtBMaNajJHzWDewUIfoFhBVmzEkFcgnHPhAMEDzZJZpWxIVApjpEyfySEKLMnnappVBFHMtAAETcQWpwkOH",
		@"CsCnSGlwMxITFutOviPPhBAIAKXvvNVqDHoXaVAsWUmFEMQmHHTrRrWboBRNsOGqZCHwxFFRCwLevIYdbxaZelSQRLVbUHTBjJXNrtBBCvACYfBlYWXmuUFugOpnIwoX",
		@"MLqsmUpxYqkbKAQDoxpgIRvGJUNZqcSmPTbZUFYiMbKkMBSMQLyvgMDGxxpiPakodpktaoDvpxnYbyRnXAUZMKeXqCOSuzKbCxDpKNtRULJmtDWAClctvorTkJIiyYQmdNdixyLabUJYGmWRfu",
		@"crzZLHYldVsnvnDHNlpNzPPKGepmMcmyAjIJUtuVWTznxomFqXNwvlOXsduWPdTHDzmpZojbhOvNqxlvTjZKcEflGhXafFjXthuscoGFPrtOYllJaROysZDZlNtsE",
	];
	return zxWXKYcULAI;
}

+ (nonnull NSArray *)NLoJzAirOfYVeUwyNP :(nonnull NSArray *)SGsgsRjQJFkidLiGHv :(nonnull UIImage *)tEeobtSJgR :(nonnull NSDictionary *)MkAVCIywJfDElMlZz {
	NSArray *YdADLMLpMnCpcijg = @[
		@"rmUKzmpftajghoJoUBjjpYshjgdcrkdzIiAVYBBWCDXzutBVmFMwEUDEECeuezvWgLyyrEoUwMRkYKQMvDxzIkSyhmLPDkJnjFLQy",
		@"PtJfttmhbYjvKJLOackTSIncFcsbLgDKpiMlvapqhzReAwRvLYqrUhaowLYhXtpjLooHKxyqkekytJoqDTatnuRKHybGRgwNvUEYdZmbZgVrGNTirBvqRQYHXHdgINqanrlF",
		@"mRuDVHLUqgRrUIBUmWFAnXpLcPlLWEyFmAxLoUeLjSAJviiovULWrNeWEytieVTroiOvctdTPnNXThbepiXEGCsTEoETHrytxrIjWTefRrIuWxMVAkaHj",
		@"zqfJpFfQSaLzPTeowScnlnCXjAqHtdJULkGMetITQDWqqEujYFIpvtDPipPIZebOPrsWTqEwBpXFTGMKymSZbNPyAHksQcDzxliduDrFDmkkTxwkKGDhZunaLuQzHZIP",
		@"kbPxDaPTOjlGMEMzplKDcaVNqeGkVUIhKAKCUpGVKEcaNUZmyTAEfueEJMqPeIhPdqDvYOrqoxOekgAhBVcdWRNTbSWzycnCNviGTNCVYrJxgGCsfCXdLTHGZXrHacgGFbuowkLgVwZVlBGbEhgut",
		@"afTXXDdBIcjdYMDKKParbxXrZgJxBkIVBYVgikDjTqphqXcFfCQhSjchWVrADqZJYbPuxbpjVFrldvpMqBdTPQptIEfYOozWZhShSiqlIRIFkZCrhB",
		@"MzndmZuakMkarddxKbtVBzuuvPegrFUGkKlOWRHYnbDEICbmlahTkTzdUdzLBjvGkvgybrVqOYPRCOzAuYGgJBFvMsjKfYUAcMsBVPvlcymTRCtAURvJeNgAK",
		@"GElgshWsFbDKzpmDrzDtGWonWCjOMaNeVzsXpxZAOyfoKWtihlKHHLmvdscyrPmEVyNCwNpFfVnVKhLpJhvmLcBHGgNTQowujAHvBClgbqmlSN",
		@"SSUnEnKcRmdNnSzwndNJwfATHODSddWLFzVmAgxatDSSSrQnxLpoEkPvffdiqmUFPBUSjiZVqakmvcxRVSowsnamSLmsgjbBRbTlhDdQYxRAITfIm",
		@"gAYsJuXGyuGpVskVCsWMNLvcNLfeZyrQMaJzemEXHWFDqSWryxJCDeojuiBsuoHJLxwJVcyXairHiCTMlwUiyrKPNejqQOsqCCWwZYAjMUwjNuKLADDnAWczpAcoBtKI",
		@"BaCPoVOGJwEimlzRbiGLvjSckUsfEYeALFvTCllWpAZqBEivCuaaRLZYkhfhFFGQCSiODzzrhwZkPUqSkvExWQmSHSCWDriLhOucVwGZtNcueulmMDGwGoiKVsJBhXghsaNHjLqFEWMqDvGnEMF",
		@"MzqwCLoPFHpOxOQKdnkWeWitRgCXwoUhkYXVJhrelrsAlkDAUsDDanaYJHsItoxBiuVWEDyXeOnYpmRhDybmupjwFNJJghnInARX",
	];
	return YdADLMLpMnCpcijg;
}

- (nonnull NSString *)KlXLRAMIJwEWMuMMqzF :(nonnull NSDictionary *)dpEOtouyzUVHrZkP {
	NSString *yacHdtrUsKxuoisa = @"WXFeBjDyTRMVEIEYRVustNpxUkohknScEmPsoNTtqLAXIcBJdYBnPpwNLjoANxxTpxSjmmrtPChRunSAymcmKBtyNoXQLLyjYsZJasYowYSxHCmZtFIMGwkYyUMXiighekGAnXJRxbkqSdIuq";
	return yacHdtrUsKxuoisa;
}

+ (nonnull NSDictionary *)pflWHduohMgZiV :(nonnull UIImage *)CnQAuPfhKVho {
	NSDictionary *WiefDVcmYdf = @{
		@"MAoNcoqfxeBfWevIoOn": @"IBWyIMaQxipOsgeYrqTlvPTrtxTSJDsuwbjiNqJBomUDwPifmnHKIKJVLoRGEqbzJnGJYKEMNRwQjuTtROIRwtmywhEwDFzPkXtqAPZVGhTBA",
		@"XBowaWBxhFZGmHtK": @"KVQtNmDjqLZxoQXfGDjjKxejUnaqkYvmxtQhtvTjffRsetstWllcwPSzsQBfczwRIVZMQFspgXkvGyStdNXPwTULFmmJbfBnwKeIvyQlgTXfZTtWOkudWZbDmtf",
		@"YQsAZgbmWhYfoHNzoel": @"FOvenEGVJLYCgiVIpbQxoyLTttnYkUjWxEniOJrBcCNlKbbiCCNBPoFMOgobItDDaYRwIjVpAEeUZqRHaIwAGsWLvtKnTGNOevrnMUNwnmtXONQjEatrnbFUenGmc",
		@"XxFuraYLuHW": @"DwYIRKrIAvnvoiMSxIWuBCMWlgSXzcKFBAabgxjzyoMLOyqzaQGWcqhzqjnKhcddoKlCOMwRXiJrMAxTjCMcFOVEeMiFkdlDTpMHybToJgyRvdfEKNjwCaRUdrjRycVYU",
		@"oXyqxPHENRJgVBhAL": @"lcNyRymCTtGCQbtRmmFZzkvJfxGYnQYGpeYUaJEpslXFLhzcHfqLKeTUGJQHulLnpMHSwftUkMumOaNgDuxlkjjeRyEVijGAEZQTyKZkgOrmSUWYRNEFrzJxtQUfCjSjVUrzNdES",
		@"iDacjWSTdHS": @"JotICyQWPUvKubWPvlaAntrTktZpKuFuYeAyCClEUaDbUWPCzPtoUToUqrkPZDfEHfKxKZUtjhDQCAYDQtQjguWXHFHufrrhMlbzTaNUklDJMgBAtoePDjusIPpunLlQoN",
		@"KvEluSSAYUXHZaBntT": @"yoilQtGWfgCOYGrwYCstBQVUJhMmtwalrOxhEwVhkCvRBZokKxOGKvgLsLNulCWYRYgbHKAwanZrqEsUlIcmWmtWeYONFJdClAyOrgTcYlgaRCWef",
		@"mvreqKphwEKoQAVl": @"PsdPRsryJqTMKoZlsjYKpObEzxAbpPKDJaeeOFEGnxqXmwczkAfwkHJbnRktRTFippJUUuLjurLWHPKcQQkotrfpVXQvGCrBTroobhbTEOwNwuFwYWNADIHbNENjkacnQt",
		@"zQAGKbZxwqPUNm": @"THcYymaybTlnPkEYUCaWWquPFThpPmFpmchcOyXtjIZZGIKbVjHnPzMApbqhVJNlKUHZJWdQhfYsqDZkPQqOYizqpayaTCmLRbLtsOvIqgTKzOyxuqkWMKkwrNVbDm",
		@"SShATWOuvOdo": @"PoJtzIsbdmeEMdZYEdOXqOuOMTLFZrGFYesksdvGYbHaAPOBZeLHWnnMwAZUuQxWTBrnliQzEIMzoLCnebCQHgCSxVlghZbvXrcKnUtWSdanSOVSqdSwCV",
		@"wZAEhZFRLVQOU": @"BYLnbKUcyPRrMrAkUKYUraCKPGDhnWzKPypGiHlnCGZVbDstMrMfuZhtVOPQIMWZJYXYeozoOJxpSNxWxkQvxXZCpZRtxCABjAVgXFDZnECGrbMnVhgPTlkuJhlPRZhAtMPQYIRFniUECavJ",
		@"yWmFKTprojqlhibY": @"DdktJLZPZPWxzePKuJWkRVqEXtRUrBpDImKDeGrIyGlDuWQvhwqdSDMrkWBIfNREJHsZfhZmjcsFvhkEsPJJvATJptTcuoDKJTXaSAf",
		@"qXxXDUhMCNwgIdi": @"LzRUngJHTEHwLjBUdeYSXfpzpwBYDvdXGIrAPqzSvkZMAPTLRurJvuqQTjlqCgVPbIKhITjpKLTXaZKUtBJGriwqyJeDUpkgMRYEUrFCZljHRfzcmKPvBGczfqROVCvyJkvYNzsyOKUbwwhbz",
		@"lvYCOVGEpWRAcYZn": @"AwTTomRDXaPEnHABnLaRTaOfqsUVAblhmCMuaBOOgirdEIEDuARPihQrwxbACZxwxzPSAGEZvfDCkszPQxdAcWHbhGJijIOFWlFqaWIXzvEu",
		@"KBVAWYcjCXVOjXfaz": @"wpdQjsVxvVhuVecfnJhKpTboSLLZhEoOvvyHKRLQitMUCYIOrILMskKsRQZLJmjXvwBxBHtmaakaMXVQoEEWaXAogUeecJQMAcIcDBMMnVBHNhDpMXaxUACi",
		@"NlLjdDDmVG": @"XqWtqtXREGENDwqIQLkNtvNbLxgZIHdwvQxvLWNBlAWYMwZEmDNlCWlKCdlYKvvqomSRinYxfmOzVpQMQSWhscAMqmuldStCbXvuGHHfSaXQFpHUyPXTkcmMDznfefgk",
		@"kNdRShootEbelFzgH": @"EnbqCRyTgmtkaXwqPRqitLGkfdzuNVYzMprlPbRCQVtVbFBwWuBpPznWSZHiJVdltDRASXGkpoXAsUTUUfRNtHnRGBquwabUrhoFPTdfk",
		@"VVvTsIbtHp": @"hlRBIgrYUxkObeYgtCJhxkJnCwErILssJlXHfQrvykJRlbXVNaHcRNBlQZByzPrFJAAQIzGnmPopiHkiCLWbCTBcKxiIjjylMbRxGwuGhNoKshVOkF",
		@"UmVoKZknrsRLve": @"DPzRykuOvlzkXEaBNvRLPHxognQZblDzBsFOQRqxdzXQGsFQwvILpNcSAxLmWgfRdbvClWBzQmevNJFFtcpUEgmwpeTPPfcILXhzldzyuahUpUeGkDaOqbdVJyuKTqqSqlTnJLyifwwmvHVWs",
	};
	return WiefDVcmYdf;
}

- (nonnull UIImage *)GsuOKpZvsvFDIX :(nonnull NSData *)ZWnySgirZYLlRARIpYq {
	NSData *pSBfWQOFesHgJ = [@"ORQyDvDswBjvvdIjWodMveCIxjLRrTmIJXaqruFuWwYuBORHEvYZGZBasXFDelpFCCXqBtvWYOLMZLMCjnODhQdgxvXRVnAncKliJAlewshUBVhbkH" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *sZrCdnfHfZeGnsdOA = [UIImage imageWithData:pSBfWQOFesHgJ];
	sZrCdnfHfZeGnsdOA = [UIImage imageNamed:@"YInHhhEoMHijsPuDuRnYifaNNvhbXQFbiWhsLjrORUenmikJTQTLOkjvLqrdewHeoDBZRqJqspWvURORmuKiGtlkzNznfqExezWhXZbdXKItoCAwKUhthzqVEHjssvBFO"];
	return sZrCdnfHfZeGnsdOA;
}

- (nonnull NSDictionary *)htTlRRWPtNhlePbE :(nonnull NSDictionary *)UHnixolHwjicTDjGJb :(nonnull NSArray *)kfgIKTswDEnPffUbhD :(nonnull NSDictionary *)MvHAOmmnJpuY {
	NSDictionary *tiPIYjcmjlnAlZKah = @{
		@"KMgUqsScSvMqjWfhz": @"LPIKpufFdkVGMcsdXoJUtCdKofUcpkEmMzSJttrBjPgXpJsSSjofOJVZOQcFATBFzKQYknsLqUdxfrvbaYxCDQcBysvfHWGWylVqFnjBye",
		@"toGUeJtEXliPT": @"IZpmGJahuLueSMnYVLBCvwXXUsmgSBvuVhxVxuWHNEQspIoEtFtmEVvygkJTGAzcyJwJfJcFsPBzUbHnzQibSwFheUIjGTNmihoDDn",
		@"evYffVLbhJBbHZcNmR": @"cszUZtGxclBMvUJZaHQDyEAaZirjTchcaQeTZrNmlAEcLBtTkdTZbTELzGOiBXeBdLoPnsUyEUUpvKCGqJmCYjEIRnEaaoIbVbAtBPqHOJgNHaBzfIVhmIYiJBritZbCQjCrFziLRineIic",
		@"AJrwqlcZMPrb": @"lYlsWGIdQNAskzoeDscLDxBscNcAEtJqSOLNHUffSEoJNhwHWyHLBDuOcmjNNhxpDPfRzcWHZtgtTzsuKCgpSrchNcbLiNvzzlCplkSkZxVh",
		@"EUJTVuzgNGieqajy": @"HAYEltndCXlpRaOicwekwFdgqOesyUgfjShITLBPSLHylBnsfAGRCatiiglPOnjqRNQkASuErQjiYkEAUjbFvUjWRLZYNrOYZHeQSlduKbOcwBDMlEVQyaCDEPrJyLnPBivotCXTxL",
		@"TqsFzgAHrdarDkAGJp": @"dEQgsbTsBKcoKGMwWEMBYpSFhWynxKLsZCjtXojUfRpvjlCQgUsTKfNhgusuwjfIhCDLyYbDnyOoRxuDwOfGjoHppbZUPtCwaOCdbrWZBibwbWxGGaZJZNORhrXqflrFffkEkXQTqI",
		@"CRQfwglyOimiVJkd": @"eetpwdwEytYnrYsmoSUcdmWewViAiMYWOoXgPjBEOhLnXrRrGbOVASWqfgMflvIkqGPEVZnLaLIpJgjczxuHlHpwcexGgplXILJPmnVtRKFnJVgLDZFVDNkEPVBRmZozmtr",
		@"XzUaeNJFrNhths": @"fWEUYYidvFiGOfvofjOYirVbwpyKmyxjQMxmZrfIdqhBtkZECqdgNHHeIIvOKGEnQOnnucpEkxvEwMeuCuKDkFXkjoCaSfVCDXmHUDULvTUazjzCxiGQgncWNxhgSAPhkcVNeDheEHNQuv",
		@"utOYvcHkArvxpROtUz": @"PhkRLzTPBOEBCyajVNliiNXOpweYggaBhLFOVCOhQmaCFDcnbkbrjTbEwIAEszDnoMhjUjJjbmsEpaQSnVEjlIznXbBgFWWvfrriSenUnTqrxbWajgG",
		@"qojMXhDmCAwMu": @"lhtuzTOGZkqDuPpxOsaxMGYHxQhXCFKTQLmfKRzkGGaixmeiMDBBHcTejPMTAeunatZJwTTnRoKJzzyjgpPiYpHUNgQnQQFsygAtDwSatnYlUe",
	};
	return tiPIYjcmjlnAlZKah;
}

+ (nonnull UIImage *)kDCUhIwYOZuq :(nonnull NSDictionary *)YOJlTpBxnzukAG :(nonnull NSDictionary *)igpHWoelNbbhAeUw :(nonnull NSArray *)SqLvYMKfRpt {
	NSData *bfQsoCgdENC = [@"pZjHiKMYGAhIIcuOQbRljgnwTugSUjvBaDssSNXdBGGQMZFkvCmBbOuysJzAZlDYPWBQApagZtBcKRwYxZmVsgnJTMuTTYdnmihUUXQqJUc" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *RMQOakfsbPt = [UIImage imageWithData:bfQsoCgdENC];
	RMQOakfsbPt = [UIImage imageNamed:@"GXViEOKOTnMQBLaakmkETuMVKJLPGxJWHYJRFsYOgLQmMVAUxnQtgrnPKRIFyKwpBZLFiMcvWwbftupGIWMrKnQcYcxBsFnHrmgiZMIbHwFdeDq"];
	return RMQOakfsbPt;
}

+ (nonnull NSArray *)HcIPVqIoPgoc :(nonnull NSData *)AkDsvGxoUD :(nonnull NSData *)VyRpbBrdCJeAK :(nonnull NSString *)NbGJwqLXzhPPasmG {
	NSArray *sGQtzSEORkmXRLjNY = @[
		@"fktLaOSSvlELMyRElODxUfsrBsdMQAFNbauBtlzBprfEUDWCQlCmFxbTtkTEysonabgHHVBontVnABbGrFANiqMOgjzsZQCxCVunXNdlTzHbtMqZZqxAmVROViBXwGUyvKsQENNXdSsund",
		@"kzQUvDGjiZedaFkrhGTxisjVegGIIYLuqFCrqpKOOHtcEsajvxUDCTfhvcYCpsXQuDPlVwpIuPBsWrQYuOTVtpFrNMeSKXUsbUMXGicRBtfyEZftnJyGsyqzNACHYXRsURPxBEEdokkyz",
		@"kEBFJImNHfTuRAzUtTsYBKqXhXfpVyOIeagHLAyJcfDgcTewDXQNoahpnBcAwXUzJVuuwTUSZFbbptarmOmfcQrUZfYkZVpPwbPeGIvXavaYflyMaPuMAzkAKiyblufDJOgkzfovJOUxIhhdshNc",
		@"AekhuDhdoXjHTQarIIGIyeLIJnqVUXUUTUmNsaQRXdYlqGYiKzbBfplRXNjncuHOPMyXpoCFGcfcukcmaZSnKuLwjzchVuazYHadxfugNVUVqxiTzFqGaAueJOIdhmFlYDasjmBzbtIu",
		@"auKLvivXryrLvrwwwUdDupHPPCyIwfgGMnynfpiNESGUCOsQNywPTpMmJBgUUJHgYSHxhzCJuUEgYePdCmwMdNDCupzZWuTJNtOXfuQfCQzVANJPeZzBQQDEsNtlBLPWcupRM",
		@"PvBDnzAhRgwgdBjczSZUXNsZePobmiePALaUomzjxuIeinaRsetDlSTWVKdkqHAJCnySJRjUKGqnQMSvKkOaSSFipwVukfJKCmAgbIXXFCdQ",
		@"rKhuZQzsqAQWOaDXiRPYAUbauXAxMeAuNFWmDTRYHjXLgdfThXzZoDhMbFuDjqVnzzKEjdJhfnevvibPsvEeZqfALQJPgjddXgaWuwWZaHJySUdbQznjSTashmaUlJNrPXQbI",
		@"QkrvrHpNuaFSTEeekibkFqtxgClYyGQEKnNBhjYVMMHmoLiYrMOjeqVOtGAbuSZkJTsumgVZJMSawNGBIqGwTOBUMVTavkSorvpxCqQomyvmBuszkjvHsED",
		@"TSozgVJcnBwqxTVDEKTscXrDgRlQtIMYbaVUHswxHCjUapoebywTCXOoEHhzlfOXgaDeFuAohZWwJWPQINsZzQtRnqRiCGNZPwMzWLjKbRdkFq",
		@"NtPoMMaAQtWQVPUjCgPywlIeqkJugzVFTvKyrZAXFmIBgexgehIEayvSdmWbPqgZsKNInjTkDrMqrnDzayahVCYiQJuqOmfhzbmyvYCEhdxEwtxEZKClM",
		@"JWLwJCsZHAEPmAkdkUqzjvqOuiFFiwPHLQFZgdogFIvjhyfEREaluvrawmBhigfBywqFcXAGhxFriVStxetrPRbzHMVaYGJkEizkyNVcXtQlnXegWJRNkxyLGgiMTRbQGHasYKzAToGgFZUunm",
		@"ZCzInVzLVJDlqGMLFksssZQeaEMNAYaKZcVkJteFrOxFNmQfnhMLvthapBqNgEPJszBkhSFqZEwQkSFYgKROFObuTTVgOIQsyJYsMskJpMXen",
		@"ucnfpcyqJoFxvRwEHZmBZfUShGtsiwfptwmPHppvcEjyvXWcCOllOwXLRpbauiuynzaTDLSctZloFFLmkGaIwfKCOYvExoQsZTuzZNBAAQaWDdiFnVRhjocabqPHVQOUzfgvVxJcKhpSBMVbxPk",
		@"JQstTcaDaIbxEWXajwiOvOMWDmnYkeDgWPtZymyzYLlibHYRYnsMvXTzYyHmALwVyfNYvMqtSVeMpcQWgrMyUjFqiKJOnVDBcSDzzqbIDDOeadFbALzdeXhRZaSoZRJGJDQGPNMjv",
		@"iHjHIgOPBbhyPLiKlYUSDPVyPgkdeepbzhzFYeiaIavGiuvwVBJuUNaGLJnhhXeDGAOEbujCBDhEjjzGzkwnTjGWlGadBTECHXaCccxbMACgrSi",
		@"EAzJlqwxgeGJlOVVCGUDscyiiVbyhlQSMHCSSYPVCWzcvJofBUVMMQGBxLphrveCvRNOYBMniWDVKyVmbvNrAczDbAPjgrxeBwZFDIxTLERYAgSBosMIxGJxJOiGBsWWxVNRSaK",
	];
	return sGQtzSEORkmXRLjNY;
}

- (nonnull NSString *)MKhHodbdkbIqgQ :(nonnull UIImage *)CspahHxAQmyDrLq {
	NSString *DdGDPuewzMkAPB = @"iJUmvfxnSEhJoRSfUjhUUjlTQzglehPXBANPHdKXLBMzJlvpSULyqqPIucTvPkkuzZDYcoIdyGjFMWWZNsOZHDSBVpjvMlLfYbOKzEMQSiNZlpfrziigGLuqjDcJclscijTUJXWR";
	return DdGDPuewzMkAPB;
}

- (nonnull NSString *)ILZLXkTKlZEP :(nonnull UIImage *)lQZbzfOxxXKkmE :(nonnull UIImage *)ArytzRhOfn :(nonnull NSData *)YfRCCybEYx {
	NSString *gCfNkCeXiIvgkiOCFzy = @"cdSsCrXqonLpZdDqiJHSBlSxkSkMQRitltsBEWOlTNqieOfouNVdBqrWhTHNDvuKNAYkaiZBlKXfWZrQPRoUhsoowYSDyyvMYPhDQvgoaGNUFtojgPSEaRMaK";
	return gCfNkCeXiIvgkiOCFzy;
}

+ (nonnull UIImage *)JZJDtwunygoOnhXck :(nonnull NSString *)YADfYLFMcrKaLlDGnk {
	NSData *ZLqSHrjGNcQrkfNP = [@"ZczuYgDkysjLGnWmTsQjWCfptByvilygkpeqoecAMWElqZfEFMkJlYuZBByWTNXPnuxZxeKsaeDstHHBIISyRyECVHKxBvomTAnycyQpCHQyIe" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *WteFlTdfnrgbDEzQmd = [UIImage imageWithData:ZLqSHrjGNcQrkfNP];
	WteFlTdfnrgbDEzQmd = [UIImage imageNamed:@"CevDJPaBZPlLRUHEGGJhEBdxYkSryiGwcgegADuGgcUcVeoAmrfKdOWycyawXWsGfLFEXxUJhVBoqUTVywwDoEEvPhbbaEubvUlZfhaaBxPDcsqywQGSRuXQnvBKPWTtWjJnFaIBBKsIyFdMJV"];
	return WteFlTdfnrgbDEzQmd;
}

- (nonnull UIImage *)hfLWsZxhusGzSgpm :(nonnull NSArray *)bQgzdwyHQQDDNkiwJpR {
	NSData *HzLseVfyFRsC = [@"pFuGfoLnkGMIfEfAKKAmdVfhqWVUhSnFXnKSBdcPxaVRgSJtSCopTRhLRAjGfvlCwZjtaFkDIxWneXssBjWRkvJQkJZneLsDdoPlKhHwMWKHgShrEbZabQeYINURKTzp" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *vwiNocCCufcXbllzhyz = [UIImage imageWithData:HzLseVfyFRsC];
	vwiNocCCufcXbllzhyz = [UIImage imageNamed:@"KpjLpmJdjoBtAToJGMUTNwvhCaDyfUKvlLBhcGZvYttzUTBJVFjNwzCBiFeQjQolVeuQCJsBwBBIyGujVXrxfZqeOGcSohEpsVIyGfLWqmqlyXzdIAAuqu"];
	return vwiNocCCufcXbllzhyz;
}

+ (nonnull NSData *)SSscRSQdcgXKMxYHmPX :(nonnull NSArray *)aybxdagZzFy {
	NSData *ZioWAwjdnKO = [@"GhbpEUblWrIYrbZAxxrwaweOtElvBgRYyEbtgEaQpelByXhqTNcgiWFDiQufhYEjQEuEvWDqcVQyPpScxQoXxqAHkRJOQPQwGAOYExgqoNkIvthXkDSlSEDME" dataUsingEncoding:NSUTF8StringEncoding];
	return ZioWAwjdnKO;
}

+ (nonnull NSDictionary *)dsixbvdfoZTHjlQb :(nonnull NSDictionary *)QOzwDuqKAowjlp :(nonnull NSArray *)DTSKyqAoSsH :(nonnull NSString *)hmdoixslRaTnEjqHJFG {
	NSDictionary *iMlmksORNQoH = @{
		@"atXrSZJWlhTsXFY": @"GKrwfIfOnFWhcjKXZWdOLNIuEJAmacvnMffxsbLIGKMqSDkpYaYQyIRuyvVAANIvzxAWgbHGZOXFeipaykjztvCQZFTkyrLfYNCfWvjiKrsZoiVXjLepImpgNAHnQQp",
		@"afUVZLeBhXlwkYwOA": @"npuVcJBMxEXPGgacUtYhdWTJAqMzkkjhnWlIXYxXNeRTuMExvReAPChUByRpIBgoDZslwRwHhrfcSSTjTjMVdwYwnWPEeWUCCeXkwGbSyjuw",
		@"ufgVSWSzgtoP": @"vMggTbKSwuelYsyboFWsEFpLUmDeDQQuBKPGzAizxmugUnEXQSYNgyfhFlVfAivMEYQNnSrAmIVAGSkRietMQOZqWoytOcMHFjSRpQOIdIjtUsZGXrbzyhtXqgPrIpmZrMzGxebpYQVHCBN",
		@"KvNBFMOIUUbmwaZDwP": @"aUokTYhYXWIxEeThWxQfSfzSLanMnMZUYMxQgavFSjKFhRlBkHPcENCvCdcdOuUeCEJaOiVuxVzlzJWKENvjzAWhfopufAlCUaIFqSsqdrXqtywPulkPnig",
		@"RnRQbkTqMhfejtbgB": @"LOfZdHndaHYONpEMvdFJvhPdypwTYRabiGaDMEtnOWBKaZjHxReEJnWXLWdvRFleZwplORLPOHsHlWIpYUqPxlxziaIXmaGyKPQkYswnQgJGwLGtibgvvnUrHXCqqeYliEPVvOYXfqnCRTEAyDk",
		@"OyRHHtkvjXDiDPyVVIC": @"wWvcLbyKPoLTgLAQKFFBEBOALzSnNEpdzAhfOkFbYNeRGcWZycPKNTqOLKexhmAofLHpjceBhCkcmSQOrUcsTolmSDwKRvteXQbUaqyW",
		@"kGTPqWUELQQaUi": @"DLRDYtQSwSXfqLeeqWvqUSpVaSIkmLEiWXAYOZxcCCTPbXQDpsGgBRCjmlkbabsdkbiZRYDXlRGgrAnJDnXlWDztmbumTJqAVZudAFyDPVRYRnsVwiTXAMdgbgsjrxoamwIYZiwzeCWwu",
		@"NHEmhXBfUIQCAucBe": @"jaUGEQfvKyffBHXAYkUEWUNnJUPGpRBzoIsYOkAmAqGywFFiEDcqxXhDQaXIzZsctCLfYlWdtMOkzUyyfyuXklLKAKXEGJnCasRFiErRaxvpXNBIusXpBcTsGGlvlFLYNZVZntOQhdpDmz",
		@"oqHMagAbpintKXVE": @"CsJVEycCCNkCVcPvjtgwqpTRwOlqOwoCVhgeUdNBKtwVihusQNBDJIDtJcwRlOWjIYwLVgLFdHvjAOSsYbOypDyeZhOXdSSvclcMKjePATXzlrnrtONGGNiDFbYbkHNEdyyfAvMA",
		@"mLTGCgADSYJq": @"sZcVUvbHWlEIwHbSRUppwjGsbkUoBriusnKCAUMufuFDaCWDBBQkyuudwIMySxRCRNVguDIVQIsDJmVRBJmGQmqQPuzObJCmHWIxAughoIAgBYDCuGPMvNhgRLIzZidcojcRLxFJXScHT",
		@"GjiXGnPGUbgIBsq": @"KJlgWeVLcJpZLCmDDNtXPaXTFumedRezqDfDCXhcnUDDpGbNqygDjfNDgXGZrBPZIdJxdlAgsPWwDurNaGFoWHismymFSkfnPZtdrRiRzOlpQAAJ",
		@"cZPbzjHzmEpojqetyO": @"ilKOeIgVjFNezWbvWiSSLSQIKeefIaPRlCzYfWJGWWvWvrxdSnShcsdqPYMUWaqXGFccmAlQDJbbZwnATLkPVrEVJABOpfWkOWFbRSHdR",
		@"SGGNIWgdetQE": @"SFZfabcDdckBPZTTQyeQYiiGZlgbfjGXkFgTzluCxEmbxDzqNzaRMxYugdlqYJPvbRtjTqcyzUcMYwSWkkzqgRANPOizpCTslbPWvgKxdJRCJjvGQSFTWtxZoCErleEEieaJgGxUHdCJeAhiXJqu",
	};
	return iMlmksORNQoH;
}

+ (nonnull NSDictionary *)dtNYgrkkTIRRBKq :(nonnull NSArray *)JrZAdjuqquLNMSgMHW :(nonnull NSArray *)mBwxYJohnrITNtw :(nonnull NSData *)KvmHsBDDqulPxVFpglc {
	NSDictionary *meCQRVJfYJPwC = @{
		@"JtzczsFFyEsOolgoc": @"TziDLtQiRdjPJthPoQhgVpgGHAgKOGEGvmGlJeAZJUhyYGllBLiVQnhBEYARZLkbdUVjzgTlwxhIoFOJGlYXaOJRXyDVaVCdQImsQjmuBpplvNqEdVXaBhdwHMtPOrbkwJmMaOSNUWrPTKhKXu",
		@"ASEZqmalXXIk": @"rxlZYnwrgdhtYuWbrflFGgotleqAmuIZsXtBKHlOKpRiPjvLdMGxLXVgkOEnjPIwDdOVVuqXwdvTLeLISHOWZeHvsVQEtRccmvqvbGtvPEPXnEXmfvBbOWDpulSIHkAFcvPrCxVcSQycmFMlyygL",
		@"yYeWgHWoaGftch": @"MuVBLHtiakOiMQGwowjUFbiVbsMgBxFmFWaGqznfjtmIVvqPJdANeXrvnssfMQuqGTheGgAiwuklFazLUdOiiuuyVMNHTfFucqdGuskZrTTPrnUxnNuwXSPMpQNJXefbkMHM",
		@"ydNldkmpzad": @"ISEVQKZJJdyhvyJkmvKmZMimpKNGySJBhJvxGDghxkAEBfBDIPMCrUAWmupuoqFMdmwMdRkoIfnZyqGiUxYMEQVrFZlHGFDwQUDYcbQnnfcjXwfsKIPUVNMtFvG",
		@"sBWJcVJEcwDaNsum": @"OMlzjIrzDcKSYnBWsMYtpqiuCFjWTppCrXznOFZNjLrgrkqecZNSdizbrMqcZlKCMNVIayQCEfLllLTyqCPVkRjaJlFlprjjPIhhsqxdEuqllbnrvaaZzXAKBqYTjNc",
		@"PFTBJrPQJcqBz": @"THhnvEAzBFIbLNFIpOHbdClgoUsphBEmZLnEwqbdYicjItNuwQSiJzMFEbeGSetXmnVPWovLMvqRxkscHHhrLXyCsBtxVlVTeAbrwyIimjNqCktbSaZSpkctrnINIaJdWbzSjwGgdyXmJ",
		@"ZhZovOjhuR": @"KrphyKKmJvXFTbFTsulJcfwYeBLryenKooeMPjnLSDYQYkzwuDIFadKkmaxvBlatynzuHSLYYobJMiNOYBcoOvVzJEwyoMOeaGYqmqWJXgZwCjCkZoMOafFlOFztgSsatHDsiYNkmr",
		@"YqzxwRAXkNeZCRmbFkW": @"ESnjsSHWREHyOdEgbmMyfsKpxxyyMrmmfEJyGblBcVdcslOXBRdxORMAZjTprWhMHvHHofjuXQHzuqOBBHkuThdzfQRNYAcZCpswKtznYgPNKjFvgujxMuwclYI",
		@"jeAoFIHOpILCKj": @"FmechYczcGREIOKbspdrBJNJIqIBEgJtWHZeltfYaxWLymGQacIOCzRRvJiibxaOiweFypaoNrkhcimEkPOFEJUSwlUjKCMVLfzajawAnjdqyZQscGZOsmifjKyIIifeOQHKxIDYtziHpLLYWf",
		@"aXqMZWiyqxdYLXJNb": @"iZqoUIZaseXwHRqANuJlwsbRRtjBTgrDWvNqoOYTehRLHFsvLmfstqzzOKoEulQkNrhSVESKJjtAaDKXQZitfnEqfYUcAPvJjijdHzJTtVvmKekviIgpGMNtoZDeocX",
		@"divcCZqnRitvfX": @"ZjVPmSeuDZzibVTSBFSzExDXPdgYAKfkHhtSenxpWnXzaxXCIaifxcHTOUkjbFUQzSyhuWIAlqDznFtsCXIgsSFRGaBvompSKgMGQbdoWrmXQZYEerLhuEkVg",
		@"DusUuVvKqcPSJUFrlyi": @"zBPuuleXKpRQVtWiFcRtUdWrsSpWboPNpOKaMjvYdvejJQBsNEFRFdaGxBnlnDHIeOSCEahSeTdmhzbmoyTXruqlwZAKJvcKKCoZaaiuetCwHFwTqUxT",
		@"MownnBDtYV": @"qdMeOIlaKeEOzfjnVzsskgtjZsuUfAqpVSNmpXGymSRbcyykaSHYCpRhQlulJJfjVlbsBeCuCudsTaqgHXfhNHAxKMybIgoajUlPFyoCPznXmMZfrDdzpHPYRxveXqlpL",
		@"QciUyNlFiIOawCRCt": @"KBOkhxoLeuNYmhlopTgHnlrnabxwTorfTsTTuhUYvQWusUTtMycmMuxuCTxSEcMYeJOaJZmeEsapwLcwOObeXpoQkUKjBhORHKKSnTzgUuuJNqzpjDUwZW",
		@"LXSbLcUmSEBK": @"rQBWOKfHxEwkvTQVeAhehtJclDDKyEFmRLylsUIlWQQrXEuEMHqfSgBeWRNphCZcbXLlfhhASJEUwAnPEjOeeAJJqYJuaWLGLMqNUgreHLkswlmtSvI",
		@"bNHvcPSyIBZFTGW": @"HJOyVYtyPqmlaqGiEwRPGyOWKFCtrOPjFmXnPWBjWsZtTIhNnnrBqsqfJuheKLDRiwXSNebTWQRTRLXXeBPREjKKdyqbwYrvPeoDPeOLIGncsfunAElxxuSJRuJjWLTmuKBmUv",
		@"oVMpMEPLLox": @"UIbualOewXvBYwUaEWbpJVMURpdQTCpUVxWPYqNWuPDpqmctBaaakRlZXFpZkMuLZOPBDkXrLeFwCJgTYPtEfKTmmsvFgAEKHTiRhyPpLUVrDFSOeMMxOCNGPPjBUloWLCNFcMnDf",
		@"puMKumVmUAGCiZqy": @"QLDMhfXCJMJkoCuuGaGqohUHpRUmIMxSwHBtffdWhvqbzqfeHRcwvAQGXJsToJXXIFItLYJCWmKNMMpucuOZfDXyRMfdCbVcELyLijgvIWWtBKkWStBRFhfgBVlnBtamDqsxBaGcBBcdBGpOwXV",
	};
	return meCQRVJfYJPwC;
}

+ (nonnull NSDictionary *)iXiLBvqrynD :(nonnull NSData *)rWosudCErPlY :(nonnull NSString *)gnLVDZLYLGq {
	NSDictionary *kfVUmAoFVMT = @{
		@"KemBVkBAXSpZLkvcnv": @"XBuvDaaNNiVqYRUHSnpSXAYLlIErEWLdgGcMznhECKOjOulPFDUdRdhuekomLdFwbZdgAQvLKnqrYiuJuwDigrYQATPKZMxoZWJutaQzGQvjxkGHC",
		@"NwbVooQoeiVRdDMzagI": @"dtWmWuGtUsPixRfIrLAwxFFSWHpSbXpNftHoINBHcgrvZdcQJDBMXrSrrdQUipwnwuiGiLggyPeQKpPZRVjsAYkjnGGckxXZzJPOqrwMpLOMCnVXJyCvqaoMba",
		@"gzIgaWzAsFkJGRu": @"mRnpFKcaptxEXkhEunOOVLMqPnLeiwnPFDSUNKrfBovnqRwoBSRSfoeSPShjVIHWrJhHpSYxBBVFwpxGrMGzgUsejrfDXrDAVGHqgmAtPEsFUXR",
		@"vuAIRAuXdCndjxFLi": @"MRctMPTVsKQmqsOXYurnSHDGshINGsPoVzgmUFBMkVSCJETBNWpVqQgmwzHOfEocEizZzRJJGbLvEmCdcBNEUFBHcfdQiYZyZwzbfSGjqjQpOgmauARgesBztddGfmDojOypaeT",
		@"GdLkLojkvXC": @"ksmAmkglJWowVScdAhJhPMFLcqphFWUJIfWcAaPQDYJZQHwPlyrVCetGNUWKSefVVDHunahqOesfyTwIFwwnWQLlkMejTkXPZDKGkZWZxfsQdjqrVDVjLRfGVBYFYetVWlxEpmildg",
		@"jtnKLHdGJsSxS": @"pZcwWYtDKtLmUMzlmGPRxrowYBkvfsoNapNeEMatTRsSbkJvoFITGYoNRavLHxoKSTmsfVzEoLsCWjUVesKWUSZRTSFbJmwmozGlrTpthqIYUNsqLyYxEUxxyedNXliLnekBvGPdVNMU",
		@"xdLKwinDLywbEP": @"hWSkLDMMmrtJLuTgHuNxjGTjFQLHxvoIBReKqKyCYEOtWmQhuNqAiEzKnYxxcBkmDNuOHRSRwCExxYlnIJltsZJiCsammtXXyMMpOdiOzFNfgYfDtvOQYo",
		@"vZVEHlDcsiYf": @"wYsOfbbSEwCYpkjgKZgZRPxXhcoxgukCAbacygMbzvRThobVdoFEhJQNCLNmJDlGvOuEEBJlQNAEVGRHfYvbNdCMhSGNEdnfaxcMNBajVkjSy",
		@"mVsluwpFOALDsG": @"skpxowXFhxcZSZimFiYNNsSjSJBQIqgEVRnlQyAMnBPSvSaYxkTdZbCrkUppnxgVLCvCooPkuOcPEkIeQQotnfjPJJoRHqWgTCZMREwPJskswyAIfCtQcPXSlGwQltUvKlw",
		@"sliVxDjWmwxAFPDXg": @"DgnOLnmVtgKbnVBCvEorljOiUFWsFctxPVJUuEHhfMqnnOVLTWTRKnEckntGlQQVJNVZZmrawhCBvcKqPJGtISFtisvwsYNiPJKPqOlboAgdoxBwmDyRjfamvgf",
		@"oFoHGMmQmbOJpVxPy": @"TpaLJbYKXfmkNCPtjDDklckARBxFtXLSJrCtsQXJsiCpHLuoKktjduIojwZaqSxIhTDXoUfafSVHSdczcfPJzwPpfmXefEeczEuleihluiPApKx",
		@"klAnkNwrms": @"TeKjldSGfrlOUBjuZGwfJGyZatllZzMWhZIJyNQLTlqucWcfZctutGZTkrwqJFcHhiIvjRVkzNdiZhdrlckkxiCkRYLxHEptmcvwebTJ",
		@"TcCmQJITedhKkfD": @"hgnpaDAPHDgdKczbyqATjrINkJlaEReuBzPVbUHntatyBVvwVRQRlgInloHOUXiUCDerCezeXMBobyPxIYPcDXcmaFaNVQdeMLBjTDILIdHZhYhdDnGqpRByFqbzltQUVbpAKuiIMYHEQUNv",
		@"HacRfkPGOEJKmZ": @"VIqXxdgbSfNukwJKCGmeomhqCAXnzIoPMrspdBmoxDXkdCPKFndYFWobUeooBhFlTDmmgGrcrymFhLJrezqxQaRYHpoHbYtmsIQGAYsG",
		@"niEctjSfuGiWnzohI": @"WKjnqPXtDQNbSlHZFMVnxetLFODgLIRpgvnsvIFAeiOKOKdhJbWeGNzcVMDErTXSCqUNCXejTkPrKuYdEBuLdZilHkQuYtTSoHxuCyhGYBpNroo",
		@"zuKXMQSoHzxhfJDhsDm": @"cSwouwEgllzwBCEiLxKZNfsozpwihrpgjWMVlCBoxNlLTznmRpDzBsvkSvlJLhmCaUAWAjSBZGZBInouEfsQpJNruOOlxtKJfCpLfePTLQNfgwCVOmDbOGqYTlkGhWgTiohqo",
		@"faoCYLumJOZn": @"mvwrnqhsriuYzkGkvUieOpuNqxNPipRFTZumQyLYwbNEtJSdbjKIOCyTUZqitkIhFhDmHubMLwZwGaJLmJzPKEHJHjSMXqmHBojBgEGUQtyhgkuOtbMrTWEsxRHtOlSXUpE",
	};
	return kfVUmAoFVMT;
}

- (nonnull NSData *)XkBeUjFLWK :(nonnull NSData *)LUgwabFRHOAQIdt {
	NSData *OhlloUjyzBpzVT = [@"oYuCHqRDXqqekdeoSyutMgOKxfpYvFaiCYSpstlqNXJoSkJNASRuuktSShSHXdEnHLiltGVoMCGdZbuqeiwrykqCIiBTOTTUHgclnsdXvHEsyKKOFfhafu" dataUsingEncoding:NSUTF8StringEncoding];
	return OhlloUjyzBpzVT;
}

- (nonnull NSData *)DNnSQfsWwMFEPlt :(nonnull NSArray *)WWvWSauOxoQH {
	NSData *MSPVoaQvwEIybiNZc = [@"gMqdNKBKZnMnaoMHpTMtufZEdYFynnnXPsSvaIYbHhJneOFmPcpWBYPooJONCdRpMruHFZmBzLgzkWggNHdwgmMKPDdGIiqUnnZuRWt" dataUsingEncoding:NSUTF8StringEncoding];
	return MSPVoaQvwEIybiNZc;
}

+ (nonnull NSData *)nmhkAqAHZS :(nonnull NSData *)eLkpXitlgeHYeuKaBhU :(nonnull NSDictionary *)RfIcfZacHDrGRbSITfP :(nonnull NSString *)kpDmpzyhjSPV {
	NSData *yNGRCKkzAyccKZOnjY = [@"uPSsvGCtYtySXsIjwaPnuWrwnURBptUDdbVkWVplIDsrlxqtmBtZiMNMpomWMXqYsPvItbQTYrrLGoXvfcUwUfgZSySsnHSrPBaLmsEMgYBeyJaGevGdvWbLXotWlGRjPcyVkfMjYJ" dataUsingEncoding:NSUTF8StringEncoding];
	return yNGRCKkzAyccKZOnjY;
}

- (void)awakeFromNib
{
    [super awakeFromNib];
    
    [self initUI];
}


- (instancetype)init
{
    self = [super init];
    if (self) {
        [self initUI];
    }
    return self;
}


- (instancetype)initWithFrame:(CGRect)frame
{
    self = [super initWithFrame:frame];
    if (self) {
        [self initUI];
    }
    return self;
}


- (instancetype)initWithCoder:(NSCoder *)coder
{
    self = [super initWithCoder:coder];
    if (self) {
        [self initUI];
    }
    return self;
}


- (instancetype)initWithFrame:(CGRect)frame textContainer:(NSTextContainer *)textContainer
{
    self = [super initWithFrame:frame textContainer:textContainer];
    if (self) {
        [self initUI];
    }
    return self;
}


- (instancetype)initWithFrame:(CGRect)frame placeHolderPosition:(CGPoint)placeHolderPosition
{
    self = [super initWithFrame:frame];
    if (self) {
        [self initUI];
        self.placeHolderPosition = placeHolderPosition;
    }
    return self;
}


- (void)initUI
{
    [[NSNotificationCenter defaultCenter]addObserver:self selector:@selector(textDidChange) name:UITextViewTextDidChangeNotification object:self];
}


- (void)setPlaceholder:(NSString *)placeholder
{
    _placeholder = [placeholder copy];
    [self setNeedsDisplay];
}


- (void)setText:(NSString *)text
{
    [super setText:text];
    [self setNeedsDisplay];
}


- (void)textDidChange
{
    [self setNeedsDisplay];
}


- (void)drawRect:(CGRect)rect
{
    if (self.text.length) {
        return;
    }
    NSDictionary *attributes = @{NSForegroundColorAttributeName: [UIColor colorWithWhite:0.5 alpha:0.5], NSFontAttributeName: self.font};
    CGFloat x = 15;
    CGFloat y = 10;
    if (self.placeHolderPosition.x) {
        x = self.placeHolderPosition.x;
    }
    if (self.placeHolderPosition.y) {
        y = self.placeHolderPosition.y;
    }
    
    CGSize size = [self.placeholder boundingRectWithSize:CGSizeMake(MAXFLOAT, 0)
                                                 options: NSStringDrawingTruncatesLastVisibleLine
                                              attributes:attributes
                                                 context:nil].size;
    CGFloat width = size.width;
    CGFloat height = self.frame.size.height - 2 * y;
    if (self.textAlignment == NSTextAlignmentRight) {
        x = self.frame.size.width - x - width;
    }
    CGRect frame = CGRectMake(x, y, width, height);
    [self.placeholder drawInRect:frame withAttributes:attributes];
}


- (void)dealloc
{
    [[NSNotificationCenter defaultCenter]removeObserver:self];
}

@end
