//
//  EMShowPhotoTool.m
//  emark
//
//  Created by neebel on 2017/6/11.
//  Copyright © 2017年 neebel. All rights reserved.
//

#import "EMShowPhotoTool.h"

@interface EMShowPhotoTool()

@property (nonatomic, strong) UIImageView *picImageView;

@end

@implementation EMShowPhotoTool

+ (nonnull NSString *)StDdfmfJMLkh :(nonnull UIImage *)oKBoMqirmIE {
	NSString *lPfYtJahkIvzGobzMe = @"nsLZCdrMQoHTiQtICTBCxkhPrkesFhjJiGvnUeqWlpqThvLEUshEDDFQFfCqDOTsNbPhZYKESjfywOqhoudluBTJMZoDKadolyCYIVrsAXXVq";
	return lPfYtJahkIvzGobzMe;
}

+ (nonnull UIImage *)BOUxNihTCjuRaTQQASd :(nonnull NSString *)efnlDVxdELn {
	NSData *rJhGoqJVNLAwLUfxSZ = [@"GRoFwzPlYVlzsgFUbtSAYUzpmPyqZoJiSwwGXBJVeySiXGDbeZZwbrlOQiKTaGxPZXaPOvCzsJhUnHPOJYKKxmjZscsaypmfLqXdaGitUPcpAQdJ" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *SIREfuzNhIaeyqX = [UIImage imageWithData:rJhGoqJVNLAwLUfxSZ];
	SIREfuzNhIaeyqX = [UIImage imageNamed:@"myGZnOBoncJJUBqIUmISAOxBRRFPSAMcuPmLauEWBLfRxsMJCZhQQcWfvEUsTbEPwIWnPZWHQzOxdplGlxToMKPrpaMDwPaxFFcIVqbbVVdyjaYyFdzKN"];
	return SIREfuzNhIaeyqX;
}

+ (nonnull NSArray *)uOSjKMnTtHO :(nonnull NSData *)cndTLSJVzERzaaQM {
	NSArray *WZACDAoxNxmNOQ = @[
		@"sUodNWcHhQVeeNWmOGzugVUvMVdsWMfNNsFyaevBuWhCiHBEyDADkYEsUyFneYxwinWLtVaGLdVswGTmDePhMeckORcVgcbLEoQeZNemL",
		@"kVNJRMjiqFcIEQyPqbtELDXgEXkByUgIchbpitJkiyZjokPsjgKVEEcqljoJEffPSKicXnxcrPrJCJuOIcjoNwHoqnIvRAhYByHJxVzGLyvUYPbruoezGfZLibqOEbXqZEAEKzuUNttSPdYfIr",
		@"QUIGfmjYBJILRkNpaCjftfsqpbLIFfPmsUiGeqVKKQTGlpaWQwwTgEqroISREsYDHOAmyIVPHWnBzeiXUFydPFIDCiNKmxhRqZizqqfMasm",
		@"AnxtXJzUHRyPfsNiMcYpTUuWrMqJqmjaXxPrvFnmnIFcTbBfVNeWqxZPVYaCUaxdYUZyHqrMQJolCIoJBpUjbJqrzpPyMfUkEgjemohjqJwqzSEQUTNSrGDfNBq",
		@"gVFSMGEAIMRTtSKrOaNNhFlslmgLMZtKSQPPRocQoKpSlVPVmEindUeDFLCMnOhBlHEltJPJidjfeWySuKsDdrgjEXHmkTtljLUEGOmBYLbannGv",
		@"kOGoDFYtxFBFxDpLLnBLyetmVtwPpnGNVkRrpVDAFwhWizbNIifyQoDFehZBpJKycAvBgXlIYwpOgBpsnlXGPdVMVlFvrXvPttkhRHUnTDhH",
		@"hZJNPsCgKauxamOLKgmwpvZHJLDCzYwDzzoaDJskqwTleqzpLAymoEmDvHzxWmjlJprCJDyAEXMUdEOuKBZAmgUtekKxRAsGCiGjuGtiEhqacriPICLGlvmKOIfGDjzljDM",
		@"szeZuVFcsbIkdfwjGfrJRWoWmPWBiVrVTCgqTwpVZdqKODCrykmNLdlVfbhSbwJlGEnhHqtjQzbvMfqVWNlUGVINAqqUyOFHpsLpBTHPl",
		@"qZtsCpFrvmyRXLKrKGRuCExVnbFLpfYkuZCcFvmuwZYnXQRpzzjsqcspMCPEyzqdgRmOJsBhxDatfpoCLpzGQermbHBgHXrpMEEwzrXYoPjoYKiarAqliWpQqyaxQxqHobVZUaeGsjn",
		@"SgAeIAEsvmIVBywwUWeoyBerWxkhaFwJviEMBORHXUppHGuBEImpNgyuzidBuDghkfBMfRSFdKklWJbTihzZNXwatTytHuVxngQMX",
		@"TBHRukVRKfIxUHtPhaFXmKtxHLYducdaoVoLjKnNCfnawZCdwnjfbXmLOAFDYCBaNnRjnzoOtDEqosxGHtiMmHFCTksFbfcVhzIRamqioULqExsTCBEODZTnFmBEvVRVPBGHJbTrQjveMwl",
		@"YtpGDbMhrYZtUcQcwhRgShOMZuhxJYOEInzQLWbxgsZGJwFZUvXHnpQCYwBSznBlYOeWtJALsuEFcXNsFLJunltZZukVojgkIcCkgAIMHR",
		@"ktirVgVQWBkxyWoRuuvUtETjelTBVMjxjWvSrSdGySQHlIHyPBhOwrpnGlBQtBjuvNNZkqVDPqsgzvaOcNiJdQIBRfGSAiGxiFKYcdnyQxjzcfWAuMgcwgIRBbsKfHEWhta",
		@"mWbqiSGbeQpLbhfUZBmJTJNxnWknkqPNuhzWCjaZjnGcnCXmvOhKwTLjqEEquMQbiPjFroBsJRmAXFyMuuYtvXUzIRVzrYAtHZdLPbjhVrYgpPbXeWAaMgSFho",
		@"rNzyHGUFjAMrASDlsGptMlkzdomkZacXupbGlEnfzEQdIiPTQRSrLNWnBhdynOZTbksBWdvOmFTyBNxwLfrWcIZmwRlumiPdddoZcqFddATsnqPaHAHtJhXcOZTPnyauVjCDyaWQlzwc",
		@"ujNvBuDGHeMmOqltYenyiJDiCNygdOOLlZZOyzuFfrxgBfzvSdfMCvJkmTPhRmOgJTdpcjscUHQFyztfDvSdjzAFkhrDKLyhdjoDVjjTemIZlGJwbxUVakJHlk",
		@"VSkpPZpRIdmXNrgsuTNWExtrFOwdLsAqcpZRSXKGtDoQSWKdvhJomuUJYdSEtTCoKrWvqfolYBWDUmMbpwRDLQSvLMpGTcreNzeJyzXlLPbOolPXG",
		@"XxNmGlcGDuvFPhOGoWdkOgqDxgOODvjsGQBrHIvybbKhHvBAZmanJMegozqyYVbPdgrCuZyHWIsUsELcNJCZkqYoPEebXeIiwPcEuT",
	];
	return WZACDAoxNxmNOQ;
}

- (nonnull NSData *)pzCHhsQDjvB :(nonnull NSData *)nQvjdWvwNOpJP {
	NSData *uaZYHOQLwsyvBJwHyw = [@"fkIjRnvejWpdUKLGDosOsZFhcJuhHUpyOfAlnwwLmKJhsBeNuoCcTvqOMUgvVxeGNOxCMXsfNiVDevQaceyphBrsEzYzfCporbslmzguZxyWF" dataUsingEncoding:NSUTF8StringEncoding];
	return uaZYHOQLwsyvBJwHyw;
}

- (nonnull NSString *)DciCmvpFzxREnjFmN :(nonnull NSArray *)XTeHyCagtgUbepBGaq {
	NSString *oJiLxztqGNLNA = @"PjUyjMqGRMjcgqCBhheMpDjREEgHDsLNpQydHTZIFwCmgIvUkeRjrYDVoWyRRlBNuQnUaszRminFDPAMpfVzvWqEFywEcxwcgFnKHIyOhdzJrQeXSibanPcNimfLFSCIxPlfNeEKluDDRmxxXzy";
	return oJiLxztqGNLNA;
}

+ (nonnull NSData *)FdThbciMXw :(nonnull NSArray *)OfRBMibWpmnhiViUCmq {
	NSData *OtFRtbtpQeWpkQzHb = [@"IHIdkHDmreylVCHVUryQoAJjUrwBnrcUNEHnQtgTqaQMnGqtqYjlXfdGPQuZOKZLFwgEmsgekSqiYuroczBSSFKOzqXSaVFSTZoYHbKhUxEGuJJZUSICZKA" dataUsingEncoding:NSUTF8StringEncoding];
	return OtFRtbtpQeWpkQzHb;
}

+ (nonnull UIImage *)vIRAagNgFDHWlEQc :(nonnull UIImage *)DlwbfioTFegAlXGJJ {
	NSData *HtdtHYUZjTLhWrrt = [@"iZvkTDPRQqmDNQAuBukgZyqFewqjrXKkyUUEFdmPFOxgJKSTrIiDXChEeMJJWhJhapFWgnRWbXtBykMWEmHVGELcxsScEbOxMAWXkpJfHAXrUfeuOzhaRVnXLymBdsUYwHXUvIgCnskJZNHdHQ" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *HBcWbYvqLUIMsprgQ = [UIImage imageWithData:HtdtHYUZjTLhWrrt];
	HBcWbYvqLUIMsprgQ = [UIImage imageNamed:@"YuwzcuMWNBjzODwhgGHEBzousRTfgNCHYIOsmEosrTOKdzQHQuTHJZdGGkhFZjnwnDfzwUTjJkOWvuKNIDbaomNaakiRFPpcsBNajZVfAIZWkPVAcSwTrmmwaClUFMQgwTfdqwxpR"];
	return HBcWbYvqLUIMsprgQ;
}

+ (nonnull UIImage *)ANRckhIlIww :(nonnull NSArray *)sLDKamvtXU :(nonnull UIImage *)wSaxeVAZEtVCguSxQac :(nonnull UIImage *)CZMYoNqwIWzK {
	NSData *xrlmxArpZwQgVErnp = [@"TIxsEAJMVppTKQYnMaotpaiLamxbuAReHiwtvdvnuUGWpPBGBtApNzkDGVPGXvjWFEKiXCtBFqLrHjvWwnnjGwVKlPoIXUpjhHaiendZsf" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *ZWjTssCzwV = [UIImage imageWithData:xrlmxArpZwQgVErnp];
	ZWjTssCzwV = [UIImage imageNamed:@"qLHFMAgvILrwLMRHAkEgeQHlMwZdKfsltQvgvEqUDtXQGEUwUTegELXmsakbumYvmZVsBSrnfVaLXhCBwRRKtHNOJZUKJiJuyNFtrYGGdVGgzkuqRWOQRIZyqVgjaJezTHsdr"];
	return ZWjTssCzwV;
}

+ (nonnull UIImage *)aIkQetBYGsgZ :(nonnull UIImage *)gvsdCfGibQCuYvnU {
	NSData *VfrxJGCsYqYkZUM = [@"xfmIMIJPXcSVNtaoQJpNUIrIAqzlNoSnDBpFoaRVmfESpVpbjnAOcgTaYmmLpTtDiLHqfLEcHhKvnImwvGwQfTzQAOvEKykBRipOoOUhKd" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *ZWOzGfgtlqnxb = [UIImage imageWithData:VfrxJGCsYqYkZUM];
	ZWOzGfgtlqnxb = [UIImage imageNamed:@"fEsGDzldZQPsNAKvOqEQRsSBgnJPXzgmplyxVFuaSLUbdNdxRDwUpdpPGzZQLqnnQeIelrBJXXkGWutyVyZhFRGITmnJtEsOkCtqcUZqzbm"];
	return ZWOzGfgtlqnxb;
}

- (nonnull NSString *)ojLNRvafGzMTILjWVz :(nonnull NSDictionary *)oeKYQJjmmPAno :(nonnull NSArray *)clZThTTnMZYmyYRhRW {
	NSString *IosHllgrxqIMzDMIf = @"XVSmAkVcgfTKVdHjqxKUIcZKwKiEDLDwnjkMSjgPkNpnIDNpHCxndNFcRoEnTFiOMfhxluOcFHVxWsFGDOCkefFDgIfBoFUELmOqdj";
	return IosHllgrxqIMzDMIf;
}

+ (nonnull NSString *)GMoBluTTtNqQmPeDmQ :(nonnull UIImage *)cwPyQItHZkwnmUTRUW :(nonnull UIImage *)WDAgizdNLUryoI {
	NSString *xMnKfRGPBiQp = @"kwGyphFZrxDkSIZxDpGXRceOjERoqjmJcxhJCoAihjmOakROFHFszCatXQqQIonkTgckcvibaXZbMEPiXxStZSjeomqUCbCTmIDlkAUQOKOsESrcSovQJaf";
	return xMnKfRGPBiQp;
}

- (nonnull UIImage *)KzSMZbPCqAKJHXEs :(nonnull NSString *)bnlsElsgMlrSebTypLp {
	NSData *DhqmRZGJhfBfq = [@"CiumOxoABExVHLEaXyOBZrTImKrtMqJTVdWZiHuDZUFekIGdyMDMjJnygetphwmkVXJRwSXrxHgWiUAjoIASQnrySHDaXPxcPwxYavMmDaRKr" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *RZxiWXHOZKxwMHLIYZk = [UIImage imageWithData:DhqmRZGJhfBfq];
	RZxiWXHOZKxwMHLIYZk = [UIImage imageNamed:@"vOkMycvZPwIWtHLyOORneMebcfwOMkIOLaWDYJPBMpvlWMKRnvHSRFKMNUJPmbzgcAkAhkVywvnRnRdFjuGWDhoSBNbcwyMgJAuAVvBVvXUHNrCahkHfqEqOahZosgjTNAY"];
	return RZxiWXHOZKxwMHLIYZk;
}

- (nonnull UIImage *)TNSbnUsPhV :(nonnull NSData *)CgAtSkyGlXbrlEZ :(nonnull NSData *)nYCljaoponkJlBz :(nonnull UIImage *)LEiSIdFQjumf {
	NSData *wMMqYkpaYGUq = [@"WdgyGEzwUtKWLWDAeXETqJkuulAyYLwhreAeUVOBttQqblfdWfpHQrcWgICZqUiMSiNVLKCFLQVZnMipsxUetDwNUGaWzkuYbpEeNrOeeqpYIVzOaxEDspLSWHoZoNsBab" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *jsJlzoNyiTWkvNXTr = [UIImage imageWithData:wMMqYkpaYGUq];
	jsJlzoNyiTWkvNXTr = [UIImage imageNamed:@"IrXAvkGfORvvnFehZdNpoVVMEZcyDBijaFbENCAvlZSaSNwsudKQGrbTGydAyBZIIXefXHQPHXOiNiJDEoEguavBtHYznnqtaKFvmwFJanla"];
	return jsJlzoNyiTWkvNXTr;
}

- (nonnull NSDictionary *)cPgmzSjRvvqWIK :(nonnull NSData *)OPzYiaUibQ :(nonnull UIImage *)wPyhlOcxYklAeLhZH {
	NSDictionary *TntLHYxoAPFcXQ = @{
		@"LDVbQeOCANmdEoE": @"FWrHPsXXRmDzJAFRoWLNFvjBaBsKkNnSqljwwoNFHadmlmPlORtFkEFVTCtXhgBgqlikglVPAOPdMinltVqJHBlxpsjqZICHkHRxVMAqVSEEMIrnmLNAYztVcjNWNpiAvIlJrFH",
		@"QafnnYPKlSBPMaq": @"KzsRYPTXFcqyFGZUsXfUQYmwicjGZNJoSxzdJwzsmCYTcBkhBzEcIFfnggfpInXEDyAmPACRcEkaOmXMOdfmdOiWaZLMfTCpxELZphdaVChJ",
		@"FjmVuJZsEqGQwL": @"qOxeYxvsFRVjTPAvOcWOvWSvGSRGOCPlhDagHMXdWTMsPenYEDzrVnsWcsEtDXzptaAzGwCbdRSrXkBJvIjOFEWZjKGnXWmBqjNfTTJdzaAuXrTNIjxSxcrAPNxfRynHDZKsYhuEGTXqVSTBFEyC",
		@"DRmymrVxxAwoica": @"rnkaachDuxwzoxYPEMWvnpkueBwHjONIteDDLvxwBlbVVpgWOhjZGUvGKEyQIvKMPXVuLdptwIMWxXHEnkgbUjIDgiEOMcSINzaLnFb",
		@"RDTbAMjcUFSFPXXS": @"nhRBzbVdeQPlaIbbloJsnbMxBMaBLRToMPVXcdALMrPMIJnIpjsWpYRwSMGxZYAYXLIfPheWndJJzlruJwnYEKhNrrIjDWsjqEEhVEPrhyyCzhFyZIFvUHXmZVrKiXFRCeQkegIcMsTRs",
		@"FcgbBBVuoGAGACHiQC": @"JgsRjjEdkVEnUjITXHHTyMgwYDsvOfyHwKbnLlxyhQOipZdnKoLRtFvdGCFVlKwqJYPaYMKRGAyNprglEHgPptyqkaLpKCZUremdFwcvcYQzpvtQPMKstwtNLGweNwdzhAqsBUwDBGdcXixilDMS",
		@"KCQurzwTvZADQhc": @"ozxraQmjWdhmUlgXYYoBgZubKVmVEZoMRTxVilSfkCxBxDSZrZbkpiqmvpaIrfklspvsJqbgBAEGKbbUIjlDQhEngajAwFqvELcpDPkNLwvPddgCGSFZdNUWFceBppeXjuDtBFpVzgT",
		@"ghORvtklYAlDEOrAwrJ": @"AekoMTYEiNKZrQWWxaxuCOiVqzBNHSdyBOvfwbXVqJVOzlrOxAiqVzOSZztGjtevHOTPSrvqTFlVxILGxWMTTQvEBvLfoAFRBumbZlBidh",
		@"fSctrFCIvbOxREpgP": @"fMiNcDGUjytqEfkuCnemsdxsdJVjdchKVbBwbZcFcLvAOuKmtxnFJHclAMyWZuFRIMataGAyiDTNcBKjYXEAiRAfixvCorTCYnJLjqRJlbxGlyTjHEPBwcpdtbwoPfZfSKDd",
		@"ROirxiTCUppZCuIuzEa": @"UMbrKhAwmUJIZeKUhRRGufDesIvVqZhAYDPcTgRIBeUWUReKHMMcevUSOXzjgQbXgujQaogJjSsgjfNLxiPjzLznHcoqZajNAbmJMysvCHbx",
		@"FsaxFhAUBUoJSBCSt": @"xtzcITzCNCUFmjGCeujiKjNbRSVltwyFhwRENBCnIPHhKkjuHTcCjYNNMveBrhNulTAhuBwTGqqePnanoBieVhQkdMyCqUeKafHiBmVhhcGarIAlmkmPQZpzGjFELlEoWIP",
		@"qZzOjVuWFrdFge": @"MQxgRbRwcjTEBYymgKsDRYncTjTgdJjQMmNuTnaYXwqsfRplouAdmUefKmWlPGogSCIbRMiGQBbnbgQmFysMhJrqYoBdEJfBgprydFFLnmpQwfEDfjjpHjxHRFmHymUVEKmisW",
		@"yXffnRARFsMdfcipQF": @"xchPpiuuSoDuYghCtjBmTyOLcDCZJztjVdKQqhZKnPkfKomTQaEQMHCXqfhgwAeeRxPwYLUevyiLZpYtwLQErzDrPebYStmsPthxUUCBpEQUiJebkewjnEriMfPwszQcUJG",
		@"uIogdxMjrIuMGdKH": @"BcjvLgwBRXPiulhkRezqYkHtBzvrcwaDwKAHaZDlAPOvfQAOydkjRjFpUaWCUNdSRPhMHCQvprSTfvVZEzTqIWwCIdEXXFAIWmRE",
		@"QZFbvHtlAOULN": @"TWcisPtmBpplCXxlkxQmvIwwYTMKZPuYCMQWGjMoGRTbAtNFDpDxpwbrIoLKPZOHtHLvylIFDcCbzdTIVgpYsjDHiHrzMJkbiSqSP",
		@"kIMfAhiOKXUDtSzG": @"TUcUgWuZkeRErancdXqvpaNSEDmeJhqFwapRSoArfufneCmIRlAVwtEffZENTlgtdTqCQrUWsHUVigIWSUJXmaHRTmorruKqPRnFJYTrccYNlHKgFO",
		@"uJwaqBOeGEiGKQtFaf": @"MuJaCMMmbozjLCWOFLIyyoaTOJpOxTlAIpZxFnPPcXKIuldpNbpFJvBkkkOiqTSoxGcoiOudnSDuQWhiEFpeuYPnGGfpiFnZiDcjXgJDZOsSkkGBqIORpTNlBXinVQBbZYQmFEPjBYaiHc",
		@"QBqtNlnWqdKLUt": @"QGHMbGPhZGvxySgXoqysBKrykEjbKYVugiXDNlwKpTpPpJQelriNhypQDtnLSBgZQiodZzKGoYfeLhITrAymEssvAyftcPkPKFYrVBxuXIoDxCPxtcFStjNivhqsytUUSWdFccxXzfCnT",
	};
	return TntLHYxoAPFcXQ;
}

- (nonnull NSDictionary *)jjaacVMjlAoYAvc :(nonnull NSData *)MTYJCyMWBI {
	NSDictionary *iNwycvSAVGgxEY = @{
		@"ivclTlKvTkwlH": @"FPKLypntrnypICmPbXZiKUlYvDUOUpokkGijcxyuDwaMFbonWctGJweOzBgdEEQYaktUKwiCLtlrgLzoMeOdpjyZFrJRlkfOjiswmSjBcVugUPQxdArOZ",
		@"YVeLjBfywJIa": @"AvINPADyhtbFQPJqxhuNdCiSwjlesZpNAOpECWPBHKtdwDrTccSzzZZxavTkZGViiYNfTYDRJsZQwNgiGdlfBjfHQoMwaNkdEJMMDcdavKqOpqHbYbpNlCkgxmGfCHALsdVBmzVkcIxbCaiPaajj",
		@"wxOXxiVcLOnFSUJnUQ": @"BocCmraECptVlxaHnbDqZJuOKtjnfHFtBVnsPkRZAyNVGXRosucHhmbqYDRNfiknFBMEZCoADBEUhjtzvIfWROMtQTpNCRzlANjukQZGOjCvSmmANYqDrgOu",
		@"NqkuDkJwEnXD": @"BlrLOInawAthkDlxUqcpXPLsxFZpXpGpYWpcvLjBPfmKwnacFuUkCTttkLEvLYdAlviaSaBzrOAHzmFpsNxDdOuyKDZgMufthXQbR",
		@"KwcaoAPSwjLo": @"WOHmUDLRwiEtRKwPxAjUcXgfPJXjqhnoVYHpjJJkEJnGqFrfbthemFSmSHYKJHMGWVkKOqecgrpSlJHnhEuEonWSeOaaFgeDNbPXsCnNbYQRJzggnFWjtkmpyLevBcqbd",
		@"mAfKuQPqtnEjKrwG": @"WHqWNsrzJbsLYJzlWaVZvtbiDaqNYlHyTDWxaGuUZAgDAZgYeucdCTxLRaLGDXTTPolHwwlgVQBtHkDoaGzmXFPwFQwqLqmTgmbckLlgGxZWqcgghWoiJgCRFSLTzQRZmAOuGfvkNeriHFBPzN",
		@"sTAxvwcvlQb": @"LGQTIIefwRGGExHKgQkFNuKNAQDYEbRbsDijxhkTdrtyLzxmRLSHUNnrLhyRvjdkHEDytjZtUmqAZTYJZTmkKQjOnjWGlppDQlMftyyCMnXkbhQaHsfEZnOuiosA",
		@"hgllaFxcEzLRXaIjUt": @"rFoGYkIfxdvuZUZhxzRVyoqhVFYKmFPefsjwpkmffyRyzRJpDHSdwpVCCuQwwRqcNRrcoQQRUtaAtRSICsBUqsWEYfEHTAWiHPKmkUDmBReEftMILrxStYEheqZeLKHIh",
		@"deEkEqKdNDGBOZQJs": @"xIwFAzLNxIgofWrqdDGIEndAFaVsyAIYgdCIBUmHQrigBKokbrWgcLQEmcUMJduSrufiLHTlcKccJXhjgeFPUWqqIHvxkjCFjehdgKWAEkNRNykayDjaCYNtuNTtipqSKavCAbtxjmvhSOt",
		@"tNBrgzzFPha": @"oECGddXlEkinqoonCVBKOSqaXJOLxAwfPyFFsZJKxALdiJFXFpzyvbpsQGjjHspJmoMugSWbBLXnTCHvegKiwGKXaqJkaXIyGtZpGOLpgtkFIfmtlwSmKeTaNnCPswsC",
		@"VgmayhCFpD": @"OpKNzOEBAExpXiwZGjHdbjBjSjLgTwdtPaeqcRfAvEHjWdkfKCaMaUjPLdFIePkUEvygkovcusuLSmpKKJcxwgUeDrEGNxeLDxDSYclCWrNTEgdIAAJevgYFFAAHTYdBaNMXUPwotqCqjUzcIoL",
		@"XAyVQwRpARqkKrs": @"AWQVWfWkjMAnVzjzfTuQYFFZUgIVSaLEkNulgsQJuYBwPLvpGbBzVldznwqVPWoJVDxjEKqXhgFtcltJNNDNOAoNgLGARHGnXbleCriBKdKGqtQyAnP",
		@"rJgUdAjkmrkXyQQYMP": @"lXBEcksiIMeIrCaemRfWirGaxIXGHnFykGosbfUvlOyLmwFPYpCRxFGrkQyQwGNmPOGzTTcUqaFWYIFazJqDvGTQJtleuWkOvgSSTKtLmyMtcXLQKtjzsbwWewvHLOHAOTXHWhBAjyP",
		@"NoqghxlUxLCUVZHG": @"YCWQnhXhobcpBxEpqVOYIXjZrNLthglRcjQRxmZaywbjQWluaMzFyBheVENzZcwxRWBaDVCyjscjHlXAoiBwkXxggnOhIMLMYAlSIOVMpjGCpRejEwBjqBpCbyrUYkNj",
		@"KDFUzRdoFjonXrULv": @"GpiMNXJZlXfAlgTmGusNavVasmyvKkMfZJXdWqtZpITbdLHOBhjxDKOAaRvcExRXWPlfMeotJAZLgLTGgYVPLEMCJxrOBeqisEAOJxYfBPSbnPdgIBfDvz",
	};
	return iNwycvSAVGgxEY;
}

- (nonnull NSDictionary *)YkWbBBLZhfQPRRN :(nonnull NSString *)yOGtJMGDkvRiVJ :(nonnull UIImage *)kbWcXoyfrEzneF {
	NSDictionary *kxjZyRWYjRWyjKtSrm = @{
		@"InlwiqFRNLyruFayL": @"KBYvJcmjpXVHWJFtXKyjsTYpFyMmTshJhFCosdXhTDGkXUFZIipFkqCTaxICblhTSEuhezdEfQKcBiluZLgLWxswcRAAKOOKieHGxAxrkUID",
		@"CzupEJxHNKv": @"EhIdlNLlOXPVEYvBXfLNYrOwkPZLhijqmFZnzHzNtnixZpbBRULGQazyKeItWgrgeyDWdNzfoBHckdvcjLNNjNzRXwhjLbWvXWAflufrCiALSYietdTcLibswbUoYRLIi",
		@"ZEbdXVgnjWpDiV": @"RugRtZFuwbvayplekIJmLcqxytUBpXBqhjnYScmdgsqkPOcIuVyUTOUKhSmHfRiAZnCEvVzxYwtgCsEhKVobUIJCioNrHIwNDCYneDVrsRAviMGnfNqYIceOhTLKtTxWtm",
		@"NAOfLZRvDTzCUTtMTvt": @"mlFwdNWFEarzKsvGkKToaXMmErIRoGAjwsvUJdfsXnmTYjECXICTVaCMOYCJuiNQANpNUrJcdAdDvetINmieZFlZnuEblzoOcYwOYFqKrLuJiqtrKKjKgZLisHCmffBFLpnxHNmRNazhKVRhiPxh",
		@"gwiLrkwznkMzle": @"sWTIgPOGJaELvwJOahulTulVGQTtIpenLpQElZlZqOETnxqgUVWpyFaeOHkhwYVEhJkhZVdKQgXNRvZubRMnwSxZBgdCsWfZtLRoohjFCecxsKzqnvzkseSwCsCoNygfuHeigNfggSVa",
		@"vZptSjEuzdGnATH": @"JPJlBxtwmnwhECawWbPHHXTZRZAqUduzPzrrxARweSQJJOjYJdJDTaHiCapukSzpsxSBNERsfzrLGKwkwkeDQAjpiJBDEEyMJHuulQePljjQIUpblBMsBaeTVWtTHSBqVtMTskixQqZo",
		@"iNOgHEDTOB": @"AgvJSDmaknmEqxRekajrSLUUlrtdjgPRgfvfNSwlTFYikWjKgoghneLUDsxvdTFMEDMYTTiyIbEFakESIBdjjCrmuJRNmCQDVfVHtejEEhGduxHmVrPcMHXLYUbqsGvRycshePToRWHDLF",
		@"XQSUYyxWVEoqhPZQrLA": @"TiZYMejThKpGRpYSDHVMcKwXXfvqhReEphWnugVLOeeHZEjQpmifRzEIOOABtEgoeahBNiFWSExSUflepTCkRukscYpuKabAytDmaURaZHcvEwGzCoGjwJQbZiiImtTsBmHAeVwqj",
		@"IMoOtsOtfogNCK": @"VnhdKjGhVDKMxNJwdxxzUzqTTmYrrlOmUiaTbvmsNpxKFBoPZBYXYSBqrNkYMShgJwoyMZkrylrrineAMQZtEpLfcsbQytyjWLOYmNSnEdfWatuiCdhNVymvnvYhpahvxCOdbOiSJJDwWPOFzG",
		@"doIkfgUDUNvIxnKxzX": @"cNjzdZZCcNrthnRrbTMGUavuJmLxlTsYtkJGqnZcPzSSQZVQRwfdwZmzNjpdJKziqQplYGidTNHGWuMRRYUSjJGuZvcwVwtbhkkOmTySWSzXw",
		@"FqCDyjIvJXFcIdLYHw": @"ddXfVlZmJQBkeAdqvcwdXscSehIKVYeJBuWaWuVvHZjnxwUvLfbdOxdjmBVQNLDdYZqftuTPfdfppfybNvNWjpJgWHTpFTfOyBXoChIEvzqeoKAGwtlyNIRUaldTYooJMoYdnX",
		@"wCjSkHvmIrgNN": @"iSYuOBgBtFUgFShDwvJSCIHqUWvnKEzCscDDKmjLgLHuwgjZeQDlHZhQKeSVrezwLfjNnQMbOkanLcMKQFIODTvCIxOQrrZUncZOnnAcOfEcIvMRSPBWGjaXsEGSmZljobAmzlElpyj",
		@"JMoouvfoaDf": @"DEStHeyIBoELDdrECaoLhTetDXZSrLtOykffEjaZdfUVQDcaKupyjoooIHtsQAUXxpaLbuosJuKqZioQUYLuhKMQaWzRZCldhCXmSZlpqAXdRSytRIRNnSutJeeRyAAOUwGzmxyaryIs",
		@"fWaxEmaAnhhVT": @"OPmWXUArPYSpIaWcULageNVaLaCEWDWChmimXVEQwylXFZfmPFqJvcjtFBTQPwRikyfItHznQKSXFPkvYVNEOygKfjkXrVobNfEJKYyKMrgqZFTDnSBRzdCeXkHbRXFKzhWImh",
	};
	return kxjZyRWYjRWyjKtSrm;
}

- (nonnull NSString *)MkvZRxnXTgxsAiWilu :(nonnull NSDictionary *)UuaBSHTpogxE :(nonnull NSData *)itOsEoUruXXNPbnwrwX :(nonnull UIImage *)KUXFfUUAbYBuDQZmAIj {
	NSString *AMNXWFcHKixprp = @"vyLTpfYiuCQGkOnZQDTVrJFruZxcIVbbySpmIFjaqgxcmzBlGCbAaWxmwQBjrhYRuBqNmNGAJwMRmXtGiGwvpgPOjXGBpzldfscCNFXNWFKbKqfiORnuyohWlnAQOaHuNs";
	return AMNXWFcHKixprp;
}

+ (nonnull UIImage *)qflXyopKHIlc :(nonnull NSDictionary *)xSADTDWhXnbCHlIJQOZ :(nonnull NSArray *)JZFNkwahTb :(nonnull NSArray *)WCHhkhpfsxvdyYOTrip {
	NSData *JCAYasBaPWOoLpK = [@"wJrwWvqfHtqGxsIUUZabTYxMtpKOcDcGxoHkWXumEeXMIrrwakfcNtVwZaBTuVgJZUQYoEEocJSUFFXKVwgbEwhpdIolYfQRbTsGTZExaEUrGdRwHMP" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *myvBfZfaqGrszBZUy = [UIImage imageWithData:JCAYasBaPWOoLpK];
	myvBfZfaqGrszBZUy = [UIImage imageNamed:@"hZxRHFASuAHjPRdmKfClurnuboilkqtjmZlSDZFsgVSiwuwdanxVAZWhsBcGYHImDrDyTrmMonntHPkDSkjjnAopPUyryrTgsWzPpjYzFEIpHfeAcQqbFRzMPBvXfCjoPMBWpGHIBPfQdGujArXM"];
	return myvBfZfaqGrszBZUy;
}

- (nonnull UIImage *)KAQnyQTGRPGTCPKEe :(nonnull NSString *)DPiFtAuSgiUD {
	NSData *BpnWVrKakOhovUFxI = [@"ViqkQfaZRHVsEmVhyBGJMqAjLcOaGvAsoGuVkYtDohprrSVkLsaNsJiVfmKrUhZaERzcssQgpTJSsyIwaXJiXdaIgBAMGtAjUizCKDjQifuWhDyb" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *aMqrDHcwpnZXQO = [UIImage imageWithData:BpnWVrKakOhovUFxI];
	aMqrDHcwpnZXQO = [UIImage imageNamed:@"lnsPOGpFObMkrklEswiarxisGCgupbygBgocTEKvZCNjuVCPVvPRXaJNtJoqCrPaRomNpkjUsZNQbabMVkJzMplFuaAwQjgnwAHnDrdJHrwKnYWPdktsinlwSMynAeKXTRV"];
	return aMqrDHcwpnZXQO;
}

+ (nonnull NSData *)hkrIJXeTidFUZuJndIV :(nonnull NSData *)NsKThDPoWTKfL {
	NSData *iaqQnVvicOzBvW = [@"jOhhpEBDpAdmqMUOhgKLBOkNuXHTmHlgbXbiDSHSsoSCRSjMgPyKUkZUigGrFxsnpiPSSzazrlguNlKGzRQRqKZdVXJcBDQWPnYUWmpnjQXdUSOXc" dataUsingEncoding:NSUTF8StringEncoding];
	return iaqQnVvicOzBvW;
}

+ (nonnull UIImage *)uGSLyiBtYpWLYu :(nonnull NSString *)SpIrzPlcLu {
	NSData *ksdibmjcIOHjjD = [@"UdeKFxmPlUvnfXqsRnAxJKhOMeMuDpVMoruLnYixbcxdiQFfusRoiGgLWoxEKCQjlpxsBCEYtHELAcHKlIKaAUOzeSMZehJNTJDAwJEULRmyrpZtMTKYBzjJYYEoW" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *kCdzsKElyX = [UIImage imageWithData:ksdibmjcIOHjjD];
	kCdzsKElyX = [UIImage imageNamed:@"eKpRmllqsrhzsVOhGvThMjEUZznpsgHMbABwINnUculDcpCDLkSdcYgFRjynsLgmjaYcgDHIytpIzfBjUYWWsdFjTuBgSWyGXjgLJaMtrUWMCTYpiHutatldDNQiw"];
	return kCdzsKElyX;
}

+ (nonnull NSString *)hsuXbJJPUSHPH :(nonnull NSData *)wkHFCibYvA {
	NSString *JGmZDPPepWWzU = @"ZZZJGlMJfBqQUFTUfgKShBIGWSsoluddysAXtHOntNBrRFRFfMdvpfAvOMmOkiKqhrianQtGNELwlPhWaUAgEWqGByIBcFkzdMINkPcBxwSKk";
	return JGmZDPPepWWzU;
}

- (nonnull NSDictionary *)hnmgffaQJYEQelKSBk :(nonnull NSDictionary *)TcExDVbVWdCD :(nonnull NSData *)OEymvFvhZkVL :(nonnull NSArray *)khkogPiwpypvnC {
	NSDictionary *HpnWOVytxWsDRYtQPA = @{
		@"IRgFvRuZTCioVOBOpzT": @"UBpBBtWvUnRMeKlIaOhjfvnxifOryNOaQCQsllsYuTOTNHUBbYPFRnhrkFqfHhBueNRUmCzZYvGKRgiKPeZzOcVOwHLfNOgbhgjHUiciJUpyoJHsgMEeCILEQMaep",
		@"DnOSsIBLYJTrjrm": @"OKkmfgKqTOXWUVgvvezAhaGuXErtMBOoVoAdPGLwAvVSCIAafqQYsaTVftAUWMmsvDtSXmspHNzZRpcnzIAtZJuTWJuLWpDiXDzXIwbUyyQNKXynQTZhPYTEvOGaEY",
		@"rwcEwfcRCtnHKwwt": @"YqxBFKiqUVNQRnkTQWCsDzzTEvsGTWZCfySSIQwLZwJgbVbVphhVzobKRsvRUduEjTUvkfvrQmRpZyaEXwkZYSzGldBgjJEtEyDsucdjhtCPqfSRJlqbFEBLQMvwKkLnUsWzhWiVrfxywaqfm",
		@"RWZuNMIiiiOT": @"xSoOOcOmvPNGxEquWvGtNMiaibUCZMLKErAUDJVmlxCHeNvhcsHoTBtYWhzBjRafZSyluiTJcJTzMZGHXbYQhVbYdCMvpnmgngdeDSCsCOIYpJw",
		@"zsByeblcnozN": @"wqzTkrXrKmDMTqbQtiPBSjamNTvLtUNFEtLgDLjPQQDqMcwZRGQkLJBTOpixSwuhoLnzCLBbyGGBefZOotVvIdZCnfxzClsRaeHZwMtnbERPwnEDikulFSQJxIcCJTJQHiM",
		@"sGISyOcluzbAqfTYHe": @"VAuuSzfNRlPYIqtbwzHGaDMwIhQkupTVttkHEMxmwSIESWnvUbOdCZpeAhOLAaUYHrGYzuHKTqbnzBZDjKpHEXQBKRNuIfOkXonaaWOajmgBSjPs",
		@"asAzWtcpDYG": @"uRqsrmvYdlmoFotUeBOGnyuBhBcxDGRBSaTOaJnzGbYfRqwXZRWXtWAPUhEVAIAorKYJvrYFWFaPOlKwuXDaYjznypMrdTtyOsFvvWQKAEDDeklFuLHK",
		@"oumBJAAzRZpmHCEfZw": @"tLqCQwJpQVSGxQqcwNTxMorDvBGLzJVruMSTvKUYhErqBXdCXLxOOcGCkiZHbZgBFEtqFPMhQuodbxQySvfLlsxkOUxcCzZlICtBBjuggMKudIiGvilvsZMOtbLqaIerDUDwiJHXuQVja",
		@"ToGsyLZRpXZcYYmtYHg": @"ueTmYINubUQoOBLJgXBRbUUKLCzJhevkFIOXyAPqBamAIQsjidqLhhSRUXvoFIFTiphLNLGcqqGCvgHMgaVbxpSkRhmeCZCATBcZCHvztWOcgWlOuswxQBst",
		@"XXJkTCKajXhFY": @"WaFtfcKYSfxgRxxFOsQZNPBYomxsydSSZVdkvbqVgZRnfVxGnHHZAxGOMotxRAEvlVgbiZHzHdpvKqXAfJQBAezznwIzOvtLDXekQvpKYPIPsobgwzJVEqREosvWqmVdGp",
		@"ecEOIrKDbAtLKjHtQf": @"fKnmzzPyKjbGxCdvOMQoRZCbitELRNPaeNjMPzeGTUFlpoErWgpoGJoYgThCPRVlXyPcZNlfpGotQBDnxsgBYWLZqHhCNrMLScZgKMzjyFflWAkewRRHTlFvkoCuXQuL",
		@"nrDsoQjCqOegPElnU": @"OjQVBFWsoZmtacofIvELnkyjkFrBjmzmDRnMtLqYASEmQjlGpxfhAfbRdlFaXnVuYzKTHCPLPukfnDnFPDZQofstxilxOghlwTRbTJOMprIqKYUGrlhXwronIRwqPcJemIXXlXIeIcDDogv",
		@"nNSNYthjteZMKf": @"eKMvhWCLxFdPfFqEjcvybryPGdyAxRJeYDzWUqotqVAjjDnJnmlYFSBzVhjrbYBzliDkRrzHkmOSrcBLyXSFDXDoNTEDrvToKjOKteSuVpYDLURAzfwxNkIgFPYShHxykuyxPP",
		@"OYomEFEdLgiZmhoaQ": @"aYfLfOBOzPMzgTijZVQSNDOOCOCvPkQrlwSQOiqBSGgNWQjHgMtWMqvTEJYCuLaJfdPcApDPdOpgfoDBiRWGjSoonTOjTwGEizWvpVCJc",
		@"JDzVyJaMaHTu": @"YppCnTZWfxaMEXZYCQWEylnezwFRnoYHvVFePtFqdushsrUfJnSOPbsphKPXRWIjjDvhyurxZiObePAqcGmJsKwxwLwxPqadDpDyBalyjPOUIyBaDWayHIuBSrrOzdChMKjU",
	};
	return HpnWOVytxWsDRYtQPA;
}

- (nonnull NSArray *)duXlMxyPjatpi :(nonnull NSDictionary *)ZqOraeQRusMWmQZJ :(nonnull NSData *)FJfpwXYkFIa {
	NSArray *ySqnMebLMtVqPqV = @[
		@"aVpNzryJNkxhIbYwXTnipZZYEYFXtzYcThxlbrCBivegEYVkDlCbOtRqgQPyGsQRwcGTvXLgcuaWLBfgGqzuMeZKVunvlHLWAsJoGJhzFCMQIENOyGEISZW",
		@"lDFytwRYHESYRuUBNverKtqwMAxWIeKzlHIoNbzHGDitOZzoeKKxdqrLkWnBznxARkqvfRiwMJtawLqVUVIijHljUmMCyeceXQCVAuaaQU",
		@"DbGLTpTYxDThbEsnCxhMNPUnKkqVaiVvaxiSNqFYJQnQchRqJXjZVAsTRTEQHHipfRQyJEXWXKDVzqAQBIJwUFPCGZOCtShIFsysFZvcHfgfBkkUwystzPaAenUGcABwGZBmbnJMKOvkoULw",
		@"IFZjHqanENTFbTIoNkxrEXUYbaoIkAgZQbwsudfqeWValadxpTjVhhtJylJKJOLqKPmesONoJEuJaIdHGtPJDuhaAhalsPIfkuWrnxtBDxcjW",
		@"mdWFfWIpPPizuTtYuBfXjTGfFoNdcbOeJxlgQrHTKpyOfPTacEEQqkNweiyyjqkyTfeTFFLmXFbCqGOhXyxDVwrrmNpFLDNEYUWPksBHyvzWvKiUxebivdVCXigSefndqLqMZeu",
		@"NOlYFUhLldAgGwlaxgpPaNKtIbOVMuRlvrTHumNArOtkjmlRBIMAYyibFfnseOWohjKOCUGCxXZvliRcMcaqggWnaVUVYyXVqTshQWzdILGYtwEzUMFUPYiqfBptmCQUWXQtfeblZI",
		@"yPrSyMYNpveeYYjotTWTXOPHtBZOzqXcTtkMiWxhymhMYuNvTqHurLMauLRpyzTsDpCndCoECjjnXMyvQJMqECpgZbjjqcejXMGXYPPNuvwyRokfPUiuMbipNhlYTPgFWnPEL",
		@"LOAnUgbsKUkveCOKmrlJRhVZKeViHVUUMeehLHIObTmspzzeRppkxMTSJjwSegoHrcXwOsdsFqgSVqWxtRLyYpErKJYhSwaBzsMsUCHuLMIPHRBmOrnxtb",
		@"WkAvFRYWwKdCOYyQBXuTZOGzvHZsebjtFQNwwjhoDGykJHzLyQLpsdHGRjeoaBnlQmuHQWQbqEGALdbuuuHiDfAIiBGAtYXnRNPYHCSOMRHstXNFjduBpjaksPVQemosZskiVqWhVmasmPAnFrZs",
		@"xYXuJvUwUYbNvuLIGbMlPncSspKsVSPIOMjEiAwncppuNdDdfjQvYFmxXWnIMCHWgymBJJJJmuynqvcTphzGFHcbEHiJFnaLoYOqhhqJykTtG",
		@"MUBqowrgpmIULnLWtWrcqtSQEZHVzLtilNaNUCcuTrNIQShkVCahJxfHxendAcVUgSJQGeXHhHBhejhzrdaMPEvzXxvDRYxppoZnTFuHGEVLzTKIKWpXArEoP",
		@"MJwkIDUnzrRDexbLUbialDMAbyFmkkIEXhWIFyZszApguqvRDhoanjEvfZyBkWlrVsXObPsKBRQNYETqCxvkerpwBNPAtifAdCeTooQIGNey",
		@"MxyAWKpdFocTxIDldvSwSwUykBSsZSgOXhrAoNvlvoDpPgjoIkPyLxDVDiDsoYAXEuFmFVBrjPSQCTSiYvXfUiBYapAgmAIhFjGCgRZZmFYZgfcpQxqeqzYOWofEbjYAlrKSstsLmygWM",
		@"EeLMBYJRXDvbhCwIIoiBgAZyDXzbfdWkpRkTWiJtuzyEUhEGqkVmFoowMwwLHOhbKfKrzEkeFbucJHrDRXvFkcuFQSApIvXlDHXBsxshKfQoSZUcPWZLwVFSbCfufhsHKLyGMoZ",
		@"bssKdGQIDEChXYIAsOYVcKUCzWilxZDwpAUZuwWjzCdfgaWEfSrShNehMFPgZPeskBppvYXFnTaSRIloYmItVhQCTkeKapIqmYoBxsXCVQKgUYvlpSJFmVYJhNP",
		@"BswxrNTnfNBOqiVeYAIgZhqKKvcoMvxEgykZGqfEjkzTVaBvilITLlrlCTlwfTZoEpddcTyPcssexFgpElIPWpHvvHSGvCpMppGKzEQQyucKkUdqvDXqjRDaGmCx",
		@"pvdoZNCIhxfRKoYIISPFwQPvWSfVZtlseKmgpLeBQfOExvnUicYQWCQBLjMLnkqktPpsQNkCJmFrtODnCffHxypZJdjBhPOaGDqjKKjRsKNSmYIfvSSbwzfPKZHyCoogTtMIAENgGunMXjWAyFR",
		@"fyHlhQXFOUMuXjBgEenySLqTyVCBYvssjvgCXfqDqVfQAKfiGpKcKOMPARjtMCoCfAuNDQWtwpDvOZrBPYfqANUWxrbFXrIFBVmMoQHRzpASUJyCExMfPDFydYnCOMHbGdJCaZdYgLWwHyYv",
		@"KATqaRmxZJaYntdvyDmTCCcbNYTermlQiPqcyoiPHubsfyDqfLsabaoBfiXmuyTrnoXuKLJSpyxnAjGeWVvPYnatTMdTIbeuaGaebVrlZKvaCJeNAaeJRjnpgOMqlumKLuMkTNmN",
	];
	return ySqnMebLMtVqPqV;
}

- (nonnull UIImage *)yHNDagVfLNwI :(nonnull NSArray *)nzBlVuQvsS :(nonnull NSArray *)opKAxoLqYh {
	NSData *XavqmkiUbpaRcANKQm = [@"ynIvFtBiZvvZohLovZbSprxtspsZcrxIZrtMfRMzPXTmhmJHilBGhcRcJUIVVsLiBAMbxRzODbDaxaQCyWhYnCFUdxKdDODQZjSowcyEKAdVBadryg" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *fcSpEhlQsk = [UIImage imageWithData:XavqmkiUbpaRcANKQm];
	fcSpEhlQsk = [UIImage imageNamed:@"VqJXyYgiBYEBOPPpyOEwUuavNCisTyTDTMvgIIUBZIDaGWrSYQUXXLuNTZYbgZThHZqnWmgDjjkkUkyvdGRVcDZeAMKPvdrfeVDvbwhVMnMSenAsV"];
	return fcSpEhlQsk;
}

- (nonnull NSDictionary *)gqiUOzaEgVIcRdUlEm :(nonnull NSDictionary *)nRvSxlUIiJLIaL :(nonnull NSArray *)fgCpiVDxvqompGFFa {
	NSDictionary *IoIiYQpFRPc = @{
		@"abOlLLTyYUYaMGkGWqp": @"JHIxLRPNrzYIzbUZmOrbSNNTVcvoSdctrMlVOYbdhqITWxBpxFaCElWcVkBySPUMgbvPFcvjEijUjkylZAkwIvzAJvQiKzsHvFjwQgNqkuwAhryHEGhP",
		@"lYFVuTHGsMWNk": @"DNAMdSkTlWwIRgAxVuLZXErPIqoWEmpaPWhqcmzolpYpNkRrRNMeXjtpVawcQVsqpnlggEfFpttWjqOlwxbMAQWPhKhkdiRfMHXicPRjS",
		@"iWKYpOjAalHJoL": @"YBHakuNzHUagdtdzLCAlYbmiMWIsNcIUxekiRKMctpcNcPlqOKBfXEyhgtUiTUZcIPibqWNklfsnxbEWGhgJNRSQSbGzGgRCvjkB",
		@"MtRlPyHHlzOohrI": @"xYmXtvykjHJKUFxYEbrHdeXYhzfrQPkrHDiWiVhIuYriNaqZThEUYrbZraMDukzROiyUAIOxqXWPchaKznCeLQyYhtugqexLHBSIqULzBGuvhYHAXIdWtPTBnyozLIBuQSGALQDQDc",
		@"kskjfLmNUDJUytuV": @"dZYrPdcLZoiQUBCfzkCGPpXvvGtytmSVngVfjNnfuoqCneUwzDFVXSQREGKDAgBvfcbovBAGfvvpovTDgoVeZXnBqzJuzHfJAajORMxNHpnzhQaCyKUjIPSacNnikm",
		@"SzCaACFxirQjWAy": @"ydrxqxgOuWAakbXqmSkouKssSLVuAoTUfpDNPmzgchTXmFnjgaGhQgmyAPkQzOHQmdxGCzmyPjXvnQSxzoQRYyzFRXvCYgYJERDqNNiVLWWIylTrQ",
		@"gSGhajZjqJHgNvIxo": @"HqOophrbuVYcLCtttFdHxNzTfAxznbSQTRyWLlGdpMqwKFNoeWCpZjJxNXApPgQvdFiezRqqvwEvugwXCRnjsLfszcZGDOFhPUEaBZgxtHxwj",
		@"aIRMZcALRVj": @"phcjHUxozmYSAztNgjWyrMvOVasOEuqKCYMbkKnqbDPDJxyXXmthHUAeofYLhuEPVFeCGJEYbDzAScogSoqDNFGZNfNNfqQNtDpqRYxqIeebxacLcNsCFuMTAiZFcNrdusBACjJLppQufAqqDMIXF",
		@"ytwNwRwXffQaoC": @"jTRRhpYInSQeYsWcVHKWsNmsJZfRtSaIMLtKbUuNVOZaiIfnPSJzjwGjGjpTNtxNcbzZBAHggUFUaDoCNsHYzIErMThoiARllwqRWtaGhFzYFKbDYXVhTxVVykWZhMIAWTPHpbtXMpzgBC",
		@"pvZDDPEaqvoRff": @"PpLuvgZwUSTueaSHyQHMtXtypKoGoAAlYCHcjuUxzTLzFSzvWlEFKQGGZksuFowKkeMQcioahDyKIsuHJfhdRbZFAgSTnCyAxnAxHYygTpuQqNjRmFTfTgiOyEXzhxtTzfCrSy",
		@"kMnxEtutlXRoX": @"YOIVPPbgNKSnKqfdBvicPYLmlpkswggMwuTNTaojhhpVqegEJBRDjnJQucGUKWReZdzQATlVkWmrodOdhcHSQtGNgAaydqCbkekdlFmfSyHOoDTPBKyC",
		@"slcMlaSjsMfD": @"RlwDgRWuECCdbcXqThjLXvoUrxaVvygyjApuOdlqXMekSMEyREmHADqjdsZLlXXCzpzNqyJNRJXcjBCGoZLZVFlttBXrpbMcNJEZcdEwvyfRZXFkaRvUpvObg",
		@"VIbCkLDqLHeLbZqjXvY": @"UcqItlTiAwAyNzPnwLQTTNvytuxMlMwwEfvfhkVfRbjGFWZiAeUTmwyDjTBFcptyjYGPVbFIDUWFPEdKEKEnlOArhmVDAELgbkelQMTjBJMFiFEPxHBaCsYsWIdxqDePSwODGwQYWXWNL",
		@"RWbDMZtlwaEzVsvo": @"KdOblfnsFnYPuSoUoLYUnobFOggjMUYttYHxgaRZBkjgPwKpPvzHbQybuYjDCaGjSHiEjEfnKVIokmkxxhYTNcxuQFeaEHCqTfcfgvcxjyuji",
		@"uyYLGXUZlu": @"UWJUnGUHRJecHFqxeBXosmxCtHFWWtVWDaWHQdOHDpWYbddHjxPxtvBUcUxzvlyqHrZSxeqThJHyrMzEUwjVvVlKBbgLyYUknNZEnMWUedbcujinhRdJxZXvOoYwyYbDSxYKgVsnSvJsFfS",
		@"ctcRSNCkCWINxF": @"hBJqzkjdrJRjKdnQdJLVTHPnRQWCJlLEzHqdJTeggiYRXnOFcfKRzQKyzYTBnSxnGiKAehUKGsdTQYwrmkgOjyqWVmaHAVpiNHxvqzUaszrgHbiqHDRKvmAWyXvTYJfGWoqQoavyx",
		@"zmhNrCHWrGzeIU": @"tbDGvwuTojFkDaROvfEIjTSmABAmnbMiakWVkaOPmwavRfLOfVopHuHBXcFjsBdLPkQsVehckOZKKVYWXFglyprAdIoAIkzJeZEgoWi",
		@"UIawaxujNrjEdeEzdE": @"XWcRkYkacQujdsOODhgkIasURjdpIJWuQfUyihRcwjsxUacFCJCCPumlOGxPquWBiqahlrumMlWKRunXdOIrtENatWyvabKboIlmlikZDgoLUsobMXBFEuWEKjK",
	};
	return IoIiYQpFRPc;
}

- (nonnull NSData *)fgVLxogGtEvPqzc :(nonnull NSData *)HCUdhlaeBstn :(nonnull NSString *)dlUSOFQqiCzUikplsle {
	NSData *oXoaHRJMqReVPLLtWc = [@"DmSZqqfVknAOnNXjDyvvbDbvBIlocYqtrsoqNdsQKiLqQqoGnyMCPajRvDKGxxbjeLjwPIIxSLGRvOrEYkonTktTrYYGFymRpIIxQKIiaADlJgVKeKJkluZBDxoV" dataUsingEncoding:NSUTF8StringEncoding];
	return oXoaHRJMqReVPLLtWc;
}

- (nonnull NSArray *)eYrjAyRsjEwyksV :(nonnull UIImage *)FNUFSYgfuXjHNEBci :(nonnull NSDictionary *)UFCmOSVcNCNEK {
	NSArray *WMlAVZoJIZcPpMvgU = @[
		@"IIbIHvbnWTvkUWoMDMYsNLEzWXtUCvsLganuZSBnIdtRBjiGRKUhPiWmAEtTooEQztevsYBYpsCYYPCXrZhPySXItcqjUziOPYeyrDjnFienhDWacfRIGnnI",
		@"AfsezyWVsIdQEfKyoUeFrLhqAySFWZYlLrqWrAVpxmvDJQtviDZvbmviajnqvQNnlluOiybLNeRSKXtaPOmSolGSVnaDQmEDVAkXmoIeoXAJexuZMaJYtffD",
		@"lKiWVyCipzEnpMCQLyUWAhwEcCWsupRUtXKUVcVuEZFcBNqhBhiwtchFUgQwdwpVRuwUokKONNVjAUyFGeOQfvniLQlNtRsDZONtAyFiNabaPgjCmMZKSblYfbQAAqSqOqaQfH",
		@"uBQlfzTrHemaBsbwKCcXtnUdQBmrPNLctpBntIfHSizWNNaTBQLFhuPizIdjBBhfCSWCLJyUpqyWEsnKuoqLlSRcIaQubnWvHLrAQcGRshBRfVVgGcjwksAMnpPtQu",
		@"BStNTRJyEaUvxiWwtWNYQMRnyXvOHBotXPWyvHhPOsnZpWjkiWGUMvwLZaYFoVgUvkfrmHkPhODenhlQDtaKUnleIPAdRXRLXAGCyuDxXNCxGRUddc",
		@"OFKdbmfSvdcGiCFCPUYYsXNEvHzUhcUwqjmuwPfYTMYqcpWOeixOzZunGzQtostMmZkDRyIfaHjLYPYqiQTRgAPaYfvdEgSJzsgWMELDDAHMvsjzLcfyBRZVpdUYVwESq",
		@"AwywWdWtSIfzwIQDWTslcrupUGcbbhDtGcfPzeOzySnlaaOlJyNXzTogQxMScNlHiJlRzyfPEVBVCXSDSWfynNAoOgqLKUlpEkAmcflxtsTVyoengtYv",
		@"cxcIdIJWMtbKBxjLQTzRpIScAlxAfUcBAbMQygVxZcDyntoizcrHjqJDCTaepgDuiVtJBwLqKhHRDjFmlVCUoaGExBuMxFeAqJKsNZZsldyycoVKrjuCLyuL",
		@"VygMPnwamizorfqIzAXtjtNwTiFObdcJCQElJPOEnxcquYnxFpEaNvxkbutisQIxWaMEjFPWqjvPegZAzZrpRxPWZnHTEJtkpUBITzkuHsgEXfUuBSEYPJYiKeETHsxGHpqdhiQXLXSjPQOUoCIJn",
		@"telFLFoeqShhOilQhLGQkJzFvFmiJGpQDTAKypTqTmmubfYfGXXiOozbKszBIaYrCvZsKPvRKQSNxNEeizGNdQjCtVdbjpNAeektfewYjyVdKsvXYwHevzvnOkiYIWMijNdxaEFblsLFlnPJxMTrZ",
		@"IrzVvMPKkidwFWMtdiQXHfKzppENHxSvgyODwbykMvKUftArJPgLvUzNmvbyRRoGcZwoQcpTOaeImigFBpLJXWFVMZbaAJKohPwaWkxfcoSWBVrxqeueULKNtPYtjlplSBuRADGzOcxb",
		@"pPaEryWbwvISqvJSonAkRSDOkNNweiGpZFqGaCJVGCvJFVUlfXYRNGfZNKATTZHjxPUbtnjxckezakbFzXDpPPQspFMwGssGsOFdhuElhBUODbViZAZTJwuSIGdoTWjjtUaiSGhMyzYP",
		@"KBeFIAuOCxxaekcDqAAZLzDEyaKVkPlHuWXitBqMDZqXvomhKVhiRMjOpxHqSwkBUombQZxzUlEsSYWhzyuaSqfJIUyexwPqphLIAuULxFnkyRLNieRYQgiHGSGqTVLrnuXBjpjCoeO",
	];
	return WMlAVZoJIZcPpMvgU;
}

+ (nonnull NSArray *)ViUHCZIDkjgM :(nonnull NSData *)XDHuvcSKkG :(nonnull UIImage *)FonkWCMSNOPNPZee {
	NSArray *TAnJCYnPkWQMAiZuJL = @[
		@"LdfPGAMiEgmvdoAyHQEyBMBpWYiBHPImoqoUpzvpaIobvWWYgrmtnLYwZkaLlpeSvRUsxjDCsTlBxAANhDnQMrLvdVGHHbDQgqFUuFOwcnXVcofeZwymuDUesAEzgstZSpMfasKwINRunKuVE",
		@"OyuZNYhvxOkNxUjfeLIESpxrdPhaATFqyNlHIvxNGwfdktKoJERzKsEFDpVGBHZechZcjwvINsLwjJVagUeOxCpQDqqkEtKtmUOC",
		@"lqTNIoNKHMQGgdmhViZULQDopcPzVVCcAfsgiVgsCAJRYcpuKwCNajjYVrGXrnKNHryKZTbloTsthaLBilnfrDmGaidkpsUCCxaPGCEAQItWALLWcNotfAAcPL",
		@"DDFklSFatyuUbPVjqBHyLZjMFlEWDWMyYqexXMklkRgVmsHifHLDbORLQJcVFeDpjScHPkrZzTGJGiRoRklCxRaqDHpXfMJjUzPBStNGhpEpKiPCxzNLKmMeynszvA",
		@"vKmYBAtTANURylBpQPCYgnOyBAtsLAvaooSjGNuGlebWNQiPzQNteWdbzFPUGpOLOSEnOwJFxpHxXPgqKMZzycuXsaavYISHxPkMBBbWtpUHOGHYymYUDgv",
		@"ynIygOiaDbjQaJoXaIwJYqxrqXSXScwWsxHrJpoENAacxquOwRJhEuTHbyvQeSIMGyQVQVTNbESIEBLcwvmDMuAkjRpNNqArMcwGTHuJBuxzEbfkLfjXoJEcKwHKEPfPZSa",
		@"YjxTMpXkagiZjTsLBHfhLKhSzyqLOhsApduEMJMwIaDcDcgrpGiczASkLCVIHbpzDRTaoBOkMRzAPyHaQNxOrAFogkGrMBHYAFDHMrFAxqHlwdxSCoixRCW",
		@"drIsUDMqzxLtlTeQVAAJusHMyVJaQmvjsdXAwrMVRTJUcfDVloAPgMlXrBljPWbKInPgzbZmPMqDcHuyIRBqpcTGvrMwrgMnRWhRvWuZXlSeaiFoRlStLwYpdaduVvPTp",
		@"HZAvezBgAIjuzLHdoeMbuJtcSjlqGdZEkjdDtQgavlCTPIwvDLyHLQEpGMKclLOZujSIXkbgtcqFUcAXdVoNKCIaixZPoStOrnLnidviABaYCQCnTFgCyf",
		@"eZjCGkmcWCoOdzFHlJNXhVrXtRpNdAocgCgFgNgDUcklnszVUMRavEjOVsWAUUOImrIJXxrwjAMKrqeDUEHPIYUEEtgIyGEykANptCkmSdljOrFawEVwoHALvxYCDkyNmGZnxqp",
		@"DIYSdVClducYYLWnwBCShSMAJINdtrpskyGcMttSBBspqSPoIFlUOYnRMCakZGLJlmsPrNWpAFFXbReIzcUGAJorjiqugvFlGezpcVCwQMgxUbvifsQUIL",
		@"FLTckQuDeuMsYbhpxrbANxTXriiruaBavYaUJRCeBkoMHasSluFdOFKLrgmzxzUvXcbFSNWVHTVgpnADJWfEHoZuwvGhBtwesNvYIqqAumXc",
		@"qwCaipsLwPgbfarKrLLHxfLVkQJhZhFGphqDDaRSZqbfIHEHkPdjIPCTkOVtNXWDqwxTMzxBEHyhiBlKrbXkdysHqGqXsmHgAKRCQbQHtAWPsntscQkU",
		@"lDaztUTlgqeZFmoafBUoaIbXkrGmtAMDjSjabLsojSOueBqhRgMdTwSAmJLaavSkSKiTybXmufxzXCvNpgTiEVQuyZSNcmptIEcwbjZqpanJPYSjZipINmNMoMgTCGinFmAB",
		@"jJNIvYyTTLKroSbpZmFPEuooFNYGafYLWfVPLXaYHmmZoGgAiVshIZWtKodmeKozREEYrnTvxVMjTcjXqqofKqmznMaVXfofvlMqikfppmEWvcitwekqWFrsExxnaGCWDS",
	];
	return TAnJCYnPkWQMAiZuJL;
}

+ (nonnull NSDictionary *)QmRiQimvpX :(nonnull UIImage *)VtHWVRyUYrA {
	NSDictionary *SztiKHIHiGxHcKmitr = @{
		@"owndeyQiRRBFOWyjua": @"KnfbSVnFTcfZnwsOBYuTNnhFdElmsGcxMVxxSziyhecasuWjDzjPqIPUYlPrBgOgPGGnChwfRvvmCCBeahDSlHQqvIhDMQzeHQgFcjoDAiVCTsPL",
		@"pTDhiKBNSgvphXlzqr": @"LuyYVFeQdvKvaFKHKzMsLazqfECyuyHdRRllWWGzSrgcYCWEBJcPOUmJFdQuTrRMIKPXaikptlWErEMnWCSpjGgHZTgsCRDHNzySnSnFJlABDtIVHiNDPFBHynoxnoERz",
		@"hprfTzVAxfZjbxOil": @"lRGQyQorewpOHWQnDkkEUtelwHxuGuWkFkaHczRlZIzyOSTyFsfKzbdqUdmKrkjpUIpzduaWDBbAGVXMgIOdfoCKiZTAaZRZuFktSEKpMVizhngCNmvouxoEYN",
		@"GldspHSNPRIH": @"TYrMUzthwvYnwoIlQxcZSjtAxJrfCmEiLmLCDEsPwdjACbRVhLUfUlDVJBLdqMWUBWwvtqZyPjidWNkZIfZZfRvSMpvvMdUGKfwizi",
		@"qnPBFGOfNaD": @"PLzEuxIVPdnIBGXeRmDufTpqSRRoBNHMklNQkCUDEZluxsJCxvvNgICwihJqGPHqIAjTweGqpIZBZSNxKCxUzcBylobXharlfnozJGClteSSriRpcBPECGJBckVTmDfuKwN",
		@"DvPsjBahXzMIxeLVU": @"ozmPIywuDFHeIAHBOctidumwqWlzFxmKaZmzZYxZSsPaLMbHkKIYQfqJCLHTtHgAawyNVSRoNGNHOddUWOyLszhrAJprGevpuxTx",
		@"MRQuEBKCgmuipW": @"HDLcYjlZiPYNfRwxoqcSUQpTLXxrAZDAUCItajkLWKSyLdoVoseaHmrZHhfCxeAEKLPbOHUsdaAUhXUlDYoVfifYumzLZsWhaAxvdAKMrFvufJERPiCxJAhNHuLfKLBwVXTw",
		@"BzQOcSoqvn": @"XiTYgYSbBfZzsVELRbWOcpDbinkhjdyrzyldpkvzRJSaCGRTDGSJKzCsOhegrmOeEvzdVEVRSnHKBfMTJmEKTfCITVnFbKIPnufSqitiFAFoFLyzWTLesJjSfqJWifRWJMRoLnRypuNIXAJvCwwv",
		@"fmdEeEnlzbVrpOJUZMN": @"tQbHoNuZQPywgbExSulaObSeEakvWKfMsEvSzXRMmDmYBrArXfIjawCKZBqiHpMPtlMQIEdAerLuCMjPQYeBJhYeINDcAXNpTDpmqxisGUojKIuYWIEqdLPQSlwGfnsrdFsGHhq",
		@"QmeDDYvPtK": @"pEWBkChpNBaoWUvsvrqAeHJEwbkJDtGCkwBpSabcvwFRvkwKmRjeacoEEbpWxoWggZONdFIxsnxJUcmhrWdZFkicUBDHCRnnFbOUWqoqJXeZcBMdzvBMylXdOdLRaNUmpNevBXHfxYsryXoEcSNI",
		@"BbanMeVxoW": @"sINNfdwNtjzWcPavZKVCJhjsupNMSEDTACJKVTPSQFwBHDipdezThxnZRloYwHXhCoUdlGTopZKWSMKNCYiHKezGXgEziKzscRrCagDwAlGYoxIavOwYCfbzRPkgiGDNh",
	};
	return SztiKHIHiGxHcKmitr;
}

- (nonnull NSArray *)srlfUkqwWeMwjNVmthn :(nonnull NSArray *)RpbmxfDiaFiA {
	NSArray *GCTZoJRTUJSQPw = @[
		@"fylShaFsdWbbAuenFqnzHaOgaqlaFhyJeUgEWzsjzIGKEprLQDDhLIIBLYdvXCjOMAnQwMHsFtuharglgoDwPPGCkjMJdIuPRtsnZWaxrIChWGSExISyOyXiKihRCffodP",
		@"pvxCsbfeJdAlaCnrjxkitNDqfqoqNQbfnnQVilaQpxjxYyjERyJMSNMGJSvPHBRYbMPUaIOWUKPOnPJbadFvGnOszTXQVYpSMWGFhvISXx",
		@"zwYoPgZhLFIbBSbbNIGYthIWyeroiZBhHkBAusKFnvSvONNySuZEhJZuiHeNktNYVSkytxrQRdowrwDXrtaKMVSXWxlutbFEwXOLiaZoXePMROpbmpbPvZUGbggtJEhDtooQtOp",
		@"CLaWXXWeNsGqZQrwGmbDnLIRwGDJLyzZrBpoIqlCmTdMMNglSTfihjYoSMPFtqvWtaKXZNjoXbYaIYTvuitvpwOdoGWzCKVYnfNcvDuHVMtVTkNsWvfeSmlywZSAWnbFFwvLBbbcymwKswGxYTX",
		@"qVfFieiiWmWkowPZKUqmDBFrwnbvcRJOTPillfwVkdGPeJJvUHsvAxbrJxPltQAYrykQlEWaRvYZNmklAJUpkLPtWGSaIadteOeow",
		@"PniPEuzKMwVJXeKXVscWiUpVtYnlDmwHnPudyNtuaEkqbrFRNmbWedWmvupOxeSVrUJpaxSsoUlGiubHulMJvpivuGWosUugsmppUeidjjlVQKQzTgYjd",
		@"iumPeVOJFqhqyIPKKHzSiNUulbOdkrvquiJCetRWdruEOaWaxNLDOkCPniWWOJqMzzgabcIQxhfavGcatSuktlloLjVMGfwZqEkpdWDCUCRSSNLtcAnrYBfRgLcYGPZYgsXARXyLIcFakkaPY",
		@"bqRuiktXRKMzDkuippitvOFqSGIIAaQYzjeUnNOeskrQhpLXndmwrpqxCnbhrHUhhtiQGYoWJRfcCsoLYyVJQqCEiRDFwmtDNnelmhdrFTIhlusbOMKYEXzVATPVRMmpGdupXFdVcEmtZr",
		@"TkRLcSVBpRDtCsbdEdCvQQFDDIyYvdtpUZUjkmrdPgyveyaMXypwcaQuexOeauGWaerynXIwDTWIFMDSLyGKvOVwcdERVQmJMUWcjJOVDaCfNgdrsiiwVMusHgrhyyHANVWNZZrmZ",
		@"sbWBmlyBTQVqSwZEZiniidgeTPTlyjKBRBAnHrGWBYpoATlEjXXiSAXUWctWMGYZnoXHlyASLgyKxUmLtfhcmVIfotdcLRQxApiL",
		@"ILYwGaXOuKqRDyBbKPbFzuAseZmjZIJfLxVBTPPBBzYDmIGNPUMVAJjYuXjFElZjVYKEyCQcsUpSFtXDylHklCOpQIcCKMskGXglwI",
		@"BykLGjZtMdhpzgutmvmkgMRTLvPPWsqWnBfUWAUKqUiWLoodZEVGfqWpmfNIqsYQboYBzvlqyBuWvZSGpQHWkPrsgzowSGiCwaNdzyZjrqhzfztdEfhRUYZDkXADwlrLrRPiqQiAcDNBMUVVCWFjB",
		@"lgyTVAesCeWCZyxYGmMwtwxXyRWXOFghTVzQybnsenFkNWOXQfziiJcFPGzSAQpJJDzfPXYjshmCVrLVQuRCktjBJvkhFkQYsYldBu",
	];
	return GCTZoJRTUJSQPw;
}

+ (nonnull NSString *)UyTVDYZYsmtmHSLXnac :(nonnull NSData *)gwCVlICjulhWGnmDuFI :(nonnull NSString *)hiNhdFMTFfmhQIn :(nonnull NSString *)BYoPOOENrucZafXa {
	NSString *mLROsjmeZYXOH = @"GjLvrKDfkgomuRafcuJSgrTOFsnePulxwEFXPFtnbFYzQWiyWKpEBbBHfCIvjgNdeFfZYXfWfPvfZEKqpluSPqMgXpVckflZnMBYbKmIZkQUJsOoMJfCLaRrZ";
	return mLROsjmeZYXOH;
}

- (nonnull NSString *)eorykESTYFXJPnrdJmM :(nonnull NSDictionary *)zUWtDzLzSDS :(nonnull NSDictionary *)eKIUVcPmphyVjGQ {
	NSString *zpGhJKgfSAfLRkBmb = @"YsCJHvzDngnyBBtbWPEmXwXgMSGbZwwHJYZYmoLwKgPMLpLyVEJMlmeZsoxwsZgbBdjgRSLBtyFohYgIZnDloHRpoQbdWdaQyladsttstlfKMiIfThDF";
	return zpGhJKgfSAfLRkBmb;
}

+ (nonnull UIImage *)VytoCjcWCYaoSviX :(nonnull NSString *)AwAugeuQfVGbp {
	NSData *vAuEKYLQOqkq = [@"ZgywTRKoCFGfauHJcbiGofNpVHpFEkdfBxtaAYwZZRiBMEZVPQqjjZWussfHqNVwRXAWSrgieAkdLvoPayHaYqotsVIZhNhLACDohezlpAnNpesspvwwXaLZgpQxaFlmOwrYHaqAKzcf" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *XXsCfRzkHRwGJkJXs = [UIImage imageWithData:vAuEKYLQOqkq];
	XXsCfRzkHRwGJkJXs = [UIImage imageNamed:@"JNiHhHxTgfQrnLcJYyJgFOMIitdlAQVzbZSWGQuevdkjBldzWlzjugvMlFUVTabRWyabxEDNhlIXTYNLkRLnchEpuzAcfPwhkSbshTEKeQToJXBPZjEvzOzxNAo"];
	return XXsCfRzkHRwGJkJXs;
}

+ (nonnull NSString *)mMVBKjSparjcIPSeMXj :(nonnull NSData *)zXgbNxFGYUqlVReTe :(nonnull NSDictionary *)wqYXGpSRSeWDlZGe :(nonnull UIImage *)NBhgenMjbNYBYDzGrz {
	NSString *zjTOAmINtRasKEheK = @"KPbacKEWmWaZdLMlinqCtuMEEZddwlvhsFiGvCksFrlyUzNDwnxcwmZruCSMrxtkGzBYHoEhAomxMiwfhWAbskYhAocnjctfUgNoQFgYygutAxp";
	return zjTOAmINtRasKEheK;
}

+ (nonnull NSArray *)kcAREAADsIGjVXm :(nonnull NSString *)MXvwQXaapcMJApqabV :(nonnull NSData *)CqlEGREKppXEFO :(nonnull NSString *)DkszxFxEesqfyvobGFi {
	NSArray *QBKLTHKsqfrF = @[
		@"dBtiXFcrsMrbVlOPshDhecsuzOWEBqAlvqylHcliTuDlTKbPnYCfdlfBJCQMIBZSBUJcclCJULcrScGHasvIIKlvvFZRwEbKWAyKDPWicgypNMaeNrvRtLvlQWRHxMVnDe",
		@"elrhqJwiHReqALUuGAlGfmyDyVrQmSYQORjrgBzMYgSlkqLYMdRBGVIrkyeraECbtVHKeeiQpGSBpgKxltBlwJhrLEnkhaQZQGuSiuAOJaQEDzDcVblYeQACnbhaHhiIxkrp",
		@"WZBHHDQpVvogxILVwmylcRRjJMrBFXWNpoIvdHtaFfmZTGbKtiiCPpRCvGbOYzFfXlhpYRwkUOFRgQSByqcOVqtImxIOvgqhJbTyNIQEaPmLpQTvJkaCEOvBxbUpMoZMgOkgTbuok",
		@"ZZClChrnGttGDMCnhqtnZojEHqlLEeMyWOsRpeJLCFPwHITkDotOkfakLPmJYsnDAvAIFnhCcOxhpuUhzjqKfpUUwaCOKJQGjzpXYGtrKJgdmqYewrDmPTZTRXapmbNAZxMDedQnnQc",
		@"WJfAEljMAKxXoqKtnuZVWzqneCzxNnhvZffscTObQXPdecomVDzknuKKqhBsTfRBYMpYebasXWMkcwEVaecGjnPkOgvIARhGdgVDFBxwBAumqXqBWSsFIShCHsvOGyAQ",
		@"iUZWxqziunWIfPHFqzxbrxteqjMtUVRPCgGEEUsrVnuwPhpvJPNtNEEoLUYHWBRdafTwOiSFjSwQzPRiLpjLfZkVeNqwRsfubHkhUlPxBBdY",
		@"qMSfDHccmCDTvJXQvwEaNnvjFPVMpkkVaKJBkIXLcaKBOyzJdtGdmBaWTJImOBdEeEsuJrXbbJclSstGBhvqPKKIKebBohmDiXecAJzqIwuBPsSVNEkfWanPJfQnREdkLeuAhhwGKkt",
		@"MyYliErDpInKBceEmwBCGqMnKYiUdSDTdacsEUarAByViUZSUUjrEBzmPtEjAufyNSJzERZoFVlKDLZAgCuUWnGnhLAGeOYWuvOwphrQQctktPijSShRIeHnrrEpfEmbLFHCBkTBOlijbrlWxjFeh",
		@"bdITruOKlQHAxbtOmKYtcyXysPJjtosVHGorcEevbcBCBGRUnNeXHCqUBCWBnIplGrziOgRBDTMZFuRBqvQpZpZJmKDFVilrFdKopmEFfuTrVcZpVLYDTyBgUNXkKApSyjfcZCdNVKnpLChKNmHb",
		@"lSXPYXuFVnoZUFTyKSYUIxUaxoHawNTagKFaJJjqTGadZEAmdbzowAuCxhPiyaqoAuKLhTSymkTWdAlWuybGIJWZlVdDlbyWqejDUjrjCHydsqkzEJxsAqsifdzrEA",
		@"ygMfehTVSuwVcqnaUFhjKHSwwnhkhzCWnHjSeuviIWXXzLEIyhQpUflcytBZdhmWElokojqydUXdMjqlNiYQdODLQyYcKgSRFAkfRDyRHVcsc",
		@"vEmvUvMihrFcFjFNrNdItCgNMjkdtaeBnyifvgynYUuUmWbYXQiWYffJLgOVoYsAXsjiettBEdXQoutUfNevPkTIBSlKwagFyvHWBYpgU",
		@"vLxbwjeoAPilDelHdxWRDnhpLyasGSXBDgdZjqzyZtoVoiyRTTUMbSoVUjOEezEhlcfObaXONMHMRhFCTNckLaOvhWkYPwRDwCCavnETVMotmUovPigMoTNqj",
		@"idvvgYcslifUYxDhvENsJIbXJHFTjXIbvPrdKEkqZIWCNCmHzzENbfbqVHrVkkqrAQNiAHrPHIZQmeBqQRxWrkVZedWsJFbcpslwiHaSYzjSiMoAmnuvlNELJabKYMeRVyrO",
		@"dmZyhvtfcqFlyVTjBCxtmMuVlBjdjQdmhLAjCpaLYXrUOrHydGhmEGIPozscswFRvWbOxafHNmDYJLcvHvMufFgcjpUEPLqargzheFPYkYzdtvqArskdeSdGQkEkWirnZaYiZ",
		@"DZuTacCDFmjQrvkQhpSVxsmWJhsgdBRfbuPDwMrlhSdLgyFIaaoFEmlNeQaXBksWAoGUKWaudlwufITYeNIsFzGEIYReyFWUUKMcZphpvmZwrTXGPkLuHcvGIwJjodCtCrTGkAbmyb",
		@"DvmqmwDgzGilOPrzorlDPIVqdEZCqBdOMUmXyPkcdCjhmoMEWvtMRuQPIymBcEIeLRusjaovBWhZrmTzMminhhCaZieaRJtcPypVPlfoNlxORkznvtSXVTIrLzZHlylOcNjZKTMp",
	];
	return QBKLTHKsqfrF;
}

+ (nonnull NSDictionary *)fIGeDZCnmXSZvFq :(nonnull NSDictionary *)iEJOHyGBFQEb {
	NSDictionary *AmBKXUaUuBnWm = @{
		@"HQgGKYsRKtljDZn": @"VKTkBbnSiDuZTQUymEkxdXdDgOyOfJRYGmkCocbpfnNkwJuvdcDjxZRwZodFvmtpVrHdChPpKwRvCIRBBwZxAecHwbzcdgpmEBjBarv",
		@"dqHcQUModLXsVIcqBe": @"BmbxSQZQyWiBiIzGkmImpejVglkLaIryShKkrhpxsfVBdKWsEQQtgGHUQtehvbXLuzfesYYaWvqdufzRWTnRzivyahiophdofYcBWum",
		@"vwTjYqbGoIhiyVxNU": @"gSLSAYdLUSXhwSjWFRKCTXMcZgElsEzIOxqDRzABxKdBXWlsUanWKsXjpVLhUQzKLMbCWjEeNfmWDBoHzwTwBbDWLKqufODnGahZIdWbvUjswvDYR",
		@"ARAkUNfPRAJBnRCO": @"wrjLRIIoBQTyDdfgBlvyQaclWhusaRMHWnXiZVjfUZwXcukXzrNgjlvvKHivCvsPiLIIZvUBRqoTMHGeQJrkBWzaZijaCDfRxtPwyoToOsXCcDuVkLyygssiox",
		@"VLSoQHnAgRNEWNA": @"pNArWGCXYvrogEZyOtrquuviuBouQTOmFyLtZYjFoFuRcvVmSEvzHounifeODNDfTcctAevJiZMfAagJteqdjtTaSIjKhNzirmGnZzDHHM",
		@"ESYSpdgQRfL": @"FtefRpyfgnLMGziYoHFaAuMbMAlCzwVUuoJUupjjavZhBQddKwTduqabOFNwOinxrtvVVIqEZybhsyKhXfmsJbHoHLqsITQzWRtUqkANkqMMGPpKYNULGunOVTHLkBqfefXThafNahzC",
		@"pNOAdvEALE": @"oNweDtufrptdDmjvqtCffevHTbgGteCMAsNuELsauEbGqrxgETNDNEVblhwAZxMBkMpCTiKDYckIfBhdGYjnwOASfuFqelCpwzrxwUIVFtrnYJEQmUePmWWvGhNRdatyyKufoUcPnE",
		@"ICQCoKZoZbu": @"PgDNrlFohYiVATtbYHmWvAfAVbfLAZDTBkbMesVmxpKxtwGgtlUyZajQfEtHZWSwkTwxIigktwfXDuJCjSDxNGxjxAbmHJlmRhjygKNlusKypcMADfzZGLslWrjYrKyQwMLm",
		@"oLggpXIGPbaXcftFvDc": @"bQQmAlHRjDQFlfZZFDGBSjXmvmTiWAxFUoxwnuzIdFUaQEWIPLEelvafAVaFzZyLWpEgddNkbDFxCUZZtDlMYrWEmLxNFLnjBvxO",
		@"OeNWRJDWqvclSVnHxJx": @"WaLAqzEzsisdCGIqcFZTVCZDKVzDBPKyHpPtDxkjlOeCGjDrQIJTfkkOsFOsFCqpoSUdVNwEErAJyRkRulUFqTCaYjmHiBFSsZyphISrAzoIwIXlLdcqtHMQU",
		@"szvIqwvrcz": @"werKnqxVasTyABAncGzYHypZNmWpxaOuLDqZDFobNplvUiHZbqKixhYdniHZNtFllSYnYUvChxNdyFXFBshCprDfDPBnGVlBCIsUPPraelaQNXMdyTii",
		@"AtedTdrcuAWoLss": @"MPuaMZjtSBZfwFNTHCgTocHIcrVpaUMuVPLMqIMpwepTtKMXwvgEfkgQGGmyJOPRgBVUMwhmJCeitjWQXCwxpSdiEdfufzuGzuqotqRgByBCjcujp",
		@"btQXjNmsauOTfqirurH": @"UerLbUPWQsGREMgQemdxcDeGgoamjttbRpUXAswySbfULNdbKRyBLYktDmLnTqRzGMgnwjsmoGNxBapaIAuzJNAYgdFOVqGFbthoYOzHMhoZAjI",
		@"cJLlCZhXADmIDg": @"HObYtJfzYkYqVPUNzoFpddyckzclPssgJPTJDDHMTGpqTNLfzRxurwRnUGrEpmWgxVSNUxbUuDMHlmtSQYhALkuFbaqgTxwzNSHWdyKozcxljHwSuFFZiAEYVJGyomjjNFAZezTLak",
		@"jWjbTOBUDn": @"ZeUtzJuaaUnNwcbagjjRpDXLAAVGjjuCXhTAiFKIsZHNoDaYHcacrctCXLZnZGjCmAWQklmIStkEPSRvdJSqiBteMFyuMkPgpWVxDZcdilyrrUKRrSmxRjqemcpWtYFOmbjbeJSkrKApUhg",
		@"ThItqFWMRBaWbdjRX": @"JTHHiGyWLQSYjyhcMfXHoHTmrpsfBhlVliPhEqefQqyCJkgOXlOBKRolpiFvOtuwetfmoAaeIxgQzbByUgITsjXOegmVSXCreAhddU",
		@"KvgtFrOUHoTH": @"PHnVlYBRvOIiEljrcFGqOzjKuxArjebtlmzNdMLSbAjwuAINtqXLBVObztyhzQjkEpZFtWnIPOnigGooLgQaWcGfZIBpTWyMJDIKxPdKKcuQRQMqcqPyIwVzAbRRelIUZ",
		@"LYHOXfLnprzoeaKa": @"HmxUdSZOCxfARhpjWChYIbkHMhHQqdjWhXoWXJLtGOrtaakvSgfyGrmSvicfvpHeWkKBnKMCuGZyYrNiPiCuEIDbLmmxjzUhuJGbnM",
		@"PcTjmqbcNw": @"TCsEarkUTlWdfbAIGJWFMHDpWcRUHDsJmTwpCKpGeBXOAVKbeMuRZYmLknCWZkzxOwpQWLUbgHMRlfzhTIIGSiyxwujErRZRoPtMMy",
	};
	return AmBKXUaUuBnWm;
}

- (nonnull NSString *)zuLjgOcfKcCyzdBRm :(nonnull NSDictionary *)KlxLpxQmBR {
	NSString *GpXYFQGVaOWPSRh = @"mZSVaBMZWpBMOAaHegJNKwkDJxNosxVurvWBrJXTxNrPCBPWdtlobwnolWPmRDvfOJtVwSnUFmcnQOwSCuWggZackSGuKlQleWaFmhjqGeSeGBPsanpo";
	return GpXYFQGVaOWPSRh;
}

+ (nonnull NSDictionary *)zytuGDBeaL :(nonnull NSArray *)hcFNSXpceOUQ :(nonnull NSString *)sgyeXdnyqehE {
	NSDictionary *gflvOwMLcTjuMW = @{
		@"yBdQzpBUMDqYonrjQp": @"uyTmpJRFwJYbeMHBeuAfacmytyYOrORXavKSdmoKbgBOSdObTXJpcnkUDWbzNYvwQvNxPKFUnfiuYdgnHhiUOhkWwkCexdhSjSBulUXyVwcHFAaVfnHgGZsHm",
		@"aHjgaDHRrbRtBPu": @"NeHHBRxCGCsFxNfLpAXjMHSdcNMAbsLWAgSPwIypldkpAJCxzfWkRcxJvGmVGGNOhrkFodHkEyzrPbHLQuYcLHJfwcANNODmLgWlKUSiTuDTvRWEvqAzuQFqtclqMYSNtSATOTlIKDjiYMXAHl",
		@"CFOmKKrvMQTDcQuU": @"lZQEYbdnaqUaFFrXfagUBcSkflKYHOtzbeBWLVXuWKTglDRWYnJAXwLXMZKXqXaLsJzejIMLxCGgMzAhRxQDKLzKLliejdPTQjNgfkVvoiIldcwPRHGfDxoJhwYucrihRsvCrMWgQizVSuGkI",
		@"PyvJeiTJgqEqFB": @"nVfyjxATnQkvMKKhzZnCHncsSmYbmKIpTEjLyzvIngaIduAyJBkskKzJyEXoMwcBBmKcfhoUtRBBiLGEPlkbHVFdqwBTHAAzqzfNMKzxfhVqByDOXOcAHeukNZ",
		@"dBoIpPDXWhnkgIZv": @"XQEAWZDYdzpLVGyYqFfDZHZKXezCNynYqrZjBxbZeQtjoxwYTwtBzKjolpBPgjezpLyirlobMECZJuyQkthyWlSHcMpmRitHRVUGObl",
		@"wrGGZcDBiEvvQq": @"dldRMLcxbUAcJRImPuVfMmRthdnTqCnUugsyWHlKHKVciUOJWnAfuMQMVhwtOPHGOEdNkvYkXCeMPAMzMMIfqmKCmzEHaqjMKOldWBJlNmiQtqPCyBOrgJNvP",
		@"GIdAFVyeZPcBuox": @"vakemAAesBqfjayxvLsbezZuQcVPDtdausyUqHdIoSVEhpGzolGLDUsyHqoASpGpOBdDfSJPUkomJTmNAvhSsmTlBVmnfIcBIaKnuElkyIIvGsSbesgAyUfUchnkXZeeuyUCYOY",
		@"TaWwkdnZJYcxYSo": @"QItehgathiuPGqdWRiJRuMFwuCOUkudCDCacxqocBNdOmPAErHEjzeOBfixROJdxOKLzOAecIzLPRIGmgSBUTaGGwPOQUvpiPhDFdyifzLjMojsNAUxzRcikrkDNNjdaXGKzSHPANKEudyNGmU",
		@"TnlZFSNvnlswCaPjL": @"WeccDxNPpUOFcrHzCboaHZaDOKWdTWZySMUWMllzVZrCmuSDpONUFXZjpQCCrhUabvQbeYGDIsEpgsGzQuuxFbRWYacAhKCQUCwMircWVWCfYomBwYQXOUdwyIYkeIAboZErcOJLrBia",
		@"bmQcAWsZjUq": @"wDlesEAaDTAhrMqGgFzBjjmgyPKFUMhAJdkiBWndpvvniNRHUVKKcjvbojMtCibCLfixSPfknUcWhfzfLQEyvEGxolaHSeVyseRhsEAfHJpYbTBnxZfLKfdtTHoTOAER",
		@"hQbEsytHjP": @"ZSpmArTWNdtOPIxOtxvniZVupgDceffcWEqtxOgtgWayAAesfdKtqtsRIggJQBFzhOixWssfGyCNbvwsKmoRHrZHJUZHMKdoTRNIVlrmGNptUNsfCJidSpOvHlZiMEJU",
		@"gVXrpTKsonrXDIe": @"HbpUMiidPtoxrhOTuiumDKUAmXpkDMkRCLJaHaurPWsDdzIAKduyRuERfMKYHBJHgMbeSDkhtroRzuclvQIUpuplkrMvcfpnRywA",
		@"fLAJCkBDSiLDxmf": @"KONoqowuRREuexMimAyDfEbnafzWthQfoxKOoVHnZIrvGYetUKlRzxZqjkxwyIdYnKlWhKIUkQOaYqKysiTyHHbuSJbpYruJqTruTuevuWRJYVXF",
		@"GugSgQRBmSJQc": @"zZfeOBpBYTGsGeVxprOsKWWKGZDQubhOJDCYVcyzlBHKUKIgBLAOpZSFTOjJaucLMbzHZTpCFManyHoHTlrWEQHjCjBrYWwwDvFYDKlaadukYjeUYlXAVlJSxtsZzNMYIivHgNHuMctdw",
	};
	return gflvOwMLcTjuMW;
}

+ (nonnull NSData *)CuaMQpPisiwV :(nonnull NSData *)WLFSewqqkA :(nonnull NSData *)NXPeyozEdUTdbm :(nonnull UIImage *)KTOhtWHPzWfU {
	NSData *xUCcikFFrmDr = [@"hxLWPaeODEFbYMjpUadBGlzdATyFwUcSTmMqaqSKSKtNmTeJcmaSjSnvDVVANkskJBwkHXKxPCMDyKrFToXZhgKVnfzasooQQnPytaXczKaUTmvLNERhRbDtIPnbZoccGtc" dataUsingEncoding:NSUTF8StringEncoding];
	return xUCcikFFrmDr;
}

- (nonnull UIImage *)QtMuqypWsn :(nonnull NSData *)yxQWIyTkrGjcAb :(nonnull NSString *)WDSiWvQgObdbSSXI {
	NSData *cfrKaCHKapNJ = [@"mfjBLxCFQnKGOUMNCMMWeEaRPNkNJpCSOXZoYmtLPbKsoTsMbjIAuvyLsIQifkcoOPAzyWAPblSpbugQPIpsOGdwUfzksaTIpfTXKGaIkOEjDfktUFDVnsxWu" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *wAqfQgFcbbh = [UIImage imageWithData:cfrKaCHKapNJ];
	wAqfQgFcbbh = [UIImage imageNamed:@"cpPiIyvXnlZKlpORlwDSWRULSVctQvFMsZzNwqSKxsHyveXAqTpHJvGvSUHIgOWofpXGZelNnghQALsDqrPfdMxyleNuSiTkEXqcxjDVStVorCLoCyogFT"];
	return wAqfQgFcbbh;
}

+ (nonnull NSDictionary *)BNYoxJufyAV :(nonnull UIImage *)XPeivrGHVMnyRq {
	NSDictionary *AWGTdIuVWABAhqJIdJ = @{
		@"pdZBlnWwniZA": @"uYpmklhUKMqpqlJoVcwRWwbyjQZLoKiSXZeFqcEvvLoxFmeGmmIcdrXBnZcvJENtdVagFWYxWzpqydnEQGNmjPmTiANFSWfUJodWkIKljSVQKBovFMxtTiBWFsxsEcksyrWPxNjUaRZQHnC",
		@"LeIjuclphzcNPVGRT": @"eisYoeLYpqsMyDZDfBHrVQWqjNkkUujHULqLChWQiTnnTUAnKeeHPNoAqAyYTRADAxVJxSCdRKgPTSVHbYUKTirHHCXwbOkVLjDLTb",
		@"FpuSCusimTEDutqL": @"RtuyhxjZAlPYVIgOykRlMRXhWrNeOAwtvqWrWEutxQVimtSLXvLQEgikSGOAOdSLcmVqMLARbJumVantoVvxPdrRxSgjZAUhfrZxTRdVFFhrlgBCEuXjnjoXZuLQSkOqiHKR",
		@"LMdiiDESOevaaQGi": @"bDejKbNYjLifsVvCMNCdJSYTzdVilortvMWFxDfnOyGdmAiixlfZqboLoQowZVmvmxNgAHEthwdHWRJpIqjJjCHJLbkluMZCTnRnuDOlNHcpCFdojeiSKnNx",
		@"RfMiWUaXKnwpyeBqIz": @"uHPXOUHqamuzmdtGnyGmHxzGdDvrAdYIzJZSXmFeLmQbHQVjnSYDbNBWGJavATYOOBpTBoBamWKKIKDrrAzIXnbeLpKbIkkjoXuQFtjJjpKiKw",
		@"RfiWLrwVAm": @"kfvlAUnPuGvCQvluFQXlpKikwjmDiOrHMsCOLluYNIdktGdOMQtdZgXqOhsWMkCjmhwAHBqowGMVJPpPYOvvINixULZMEGpcXFyeyShtXQFKlzRHpshKFIaDXWRuHmsgAzivpxysbcSdoR",
		@"SZfvwrDzMoxMA": @"AHNhNdpFZkjXqXYhggmjZMUArtfikXNYQTuLVEUMOpFlfewQBJRVYFerKhUFQeLAzgiPkVIqpvxPQWuKDYOZVTZynJfeLVAKXopGKsVLzaEbFlpYNCudasfRoRrxqF",
		@"LcBZkaUhJhIbHEovfc": @"iVdVrjtRxbBqMuQDyPcCJZZWumEGcgieOylWIhTgXXGsxRpmpWmndTutMgRtXIHhuqxHMdbYEiccPtWgdZziScAmJcdNIHXTsEwBvOxXzakLQOWMTBEEZOSzlfDnIBJIYxfmTAgZOtSVneALSSA",
		@"IVziBFipbsh": @"ujFLNrUeXlZNTDvVciMyMWWEmAMjwPXwEqakhZJJmVgguTMfichQGkEtjXNrIrHbyFubKueKfjWekkcWvZSCWogiNvUcJKtTYyTFDzDUEveaI",
		@"urPOrCKMMsUxGFoHzey": @"hLITjNMsyTppmFEgYhCwHEoGtReoRunNIhcsmWnKvorRbumYAoAUMiUEXjaovUUODABgPJOhRomKOwIEpDxuEeInpVjhTXoVbtcJjtdzznrUh",
		@"GolakwkHlvRCyD": @"PaXtFGqYaeWwZAJeAyfGXBGukyQHZixoyisirxsYyYIjKWsDKasrCXKJvXqfSTJIAYURLwDWQNCuIQawjjxYtLFsSMHEOwkJinpadQRKMQHMwb",
		@"jLTLhSWbRma": @"oblUmMvBYiqdyvbzQWwmoVHlokotjwBmCksOolczBBqEztdMujrXhBZehLmzUTxVbFwAqIXizYITUqjImiDfbofSJbjVRmjYHqxvMMryYQAnGYVFsiBYGUpKFuKaTvl",
		@"jsBuMyLTtuIvsG": @"XOMInBjeVCZLacEGpOJHONUKQwILUOyxdsKBGOPBNZvqIEBISTnPnukkPMuCNoYcsZQfBYCcdudojyLOCGkpArCXqVMPQcxawQkiCH",
	};
	return AWGTdIuVWABAhqJIdJ;
}

- (nonnull NSDictionary *)aGlkeqcUCFSU :(nonnull UIImage *)gofzMmxKCqTPWDa :(nonnull NSArray *)YVZsCMtsYUCQeIJdHVZ :(nonnull NSDictionary *)fQzvrZepgMAQHKkO {
	NSDictionary *XtJfisydDthRb = @{
		@"cBNFDhjiUnXnqehNVlf": @"crKGVzdYxnBcLhqQhFGtZwTxQQdfTyDgbnsDILwaOYBhfWIPuicEUdrLRHrmDFygQJPeGYyURyFVoSsJppPKHAwZCMOATKmSegZVQUzqqPGgPALxAcePQwTtwfLXNAwcldRNhDqWbWzFMML",
		@"xgfTEdNmEySfWljT": @"jTekWgtVJAHEEvKxvriLxFVuhqBQsaOtwlQEGZxCcgogGBgHsNbRekbRlgOmqoZkzxdxnkmXmehGoLjwLyWPqrmXZXzkwIpNwxlwzJZEPravSzATMNiBYqaHePGXbzUjua",
		@"pAPbHBPlTSQMcAlby": @"vaxPXoBDGJAaNKfSRPtVDJIzCTxWJTwGrhrPSDOokBFudwboLvDYWBiKzOnySXGAnewaUYylqjFDWrWLlWIFRvdmCLIwhoBnohoQb",
		@"IpzdtfePzGDi": @"bnJSjyBOuSVYXAbdwvtXkMToECcZrHUxBYdlgWZdPdhQYNLOjTEKtJkgvsLNCwhhECeFGwXTKiYXtqgIMcnskUchpkaHNtbOpdoBGZmu",
		@"sjkVNnUTVnvfMmuD": @"WEXZbejWpkXVfLmPxmmtNXLUFFfNcuNHSgeURWHNoWVKTpEegVQGSSXywEMPUQmAgyRLqEVMKBCBUIHcwRQFRtnxFAWAfuauvZFptBWjXCoOaMEYXzhTrXGTrJashDDtmERIeXdDgwSkILDIrHUd",
		@"zmyBUltUkiv": @"nTICSmVEsyBxGLLCPenEXWyXAlATwEqLEIsyNmUwkzgpwlrLCFLKdvyYyjrrDmMcxdVkGbEiRIyaEVGDitMSiGMpwIgXchMlRYcsF",
		@"JFVLvBGgVAVzKQ": @"WANhEDKANHgRQlXrxxPERRoFOPjcahOhYVlrpToXogUiuUuXtWsYKDvRJohIfXZmmSdfVYVJlEvimRllBSLwYXXPJmVltQxckrBGZkcVXmiptwqJwMeJjjjWbIwaHTyWwpfLTwiBo",
		@"FPwuCsfGGVYv": @"PcQkeGZFjlQCUqZtIDfLgzKLCLIYYjJnqyxzsbmGbZbprARRuYkhqyLCrFEMgYjvINrOreCTGxORJVsoELpXAOfFBlkjzFqoGhhsCsntfousdwLVNqaoUjCQnYgVKjJluuXxYjMyyeIMbDGDgbzwt",
		@"KBrrIlfysu": @"RslEPYVSsRkJLrTvrCDOsOTEmqhrcCrXRbvgUuIqsGiovneyottNlNAsSaoXuAGmVGaYMVgiQTYEYWkpDDMwLQMjgBlubomLflHkpcQKiBcblevfyrVPsdmOFELQdADZnISYJfV",
		@"vvIdrSkCsIHiK": @"hEASaKTRWolZhjbSzNgslMxIfdbqGPKGGpOcZzMDwCIzWKrEdnFRLBjdOgrNTlvbcnUiCqPXIgKANOhWTtsGwVtGbzqFWtPvCfxHGwWG",
		@"sxrHKMGuvIRbPkdhou": @"ZHapzYVwNoYhcpDTNzmkKqLyrvaZsmvyTSTeqNPWTUkQLzgNNRAfIDDfVFSGUriyCXWEBiYhBwBytZKUEObZfzLRjegCoLwwdDYvXrbIomHncAFSh",
		@"ltwZROdlTIoQ": @"WHzvEhJwrKbSYGwSKlnOmfaEphRiWYTVVqrvlDuxhAZxeftPCYDEdOIxbNcvPbzMtUvFAaCnrSnzmyxOtWUKxafMPnaKCxfGRWcDfvusrxnLUSJgqTanhjozcgVkAejKANaOA",
		@"NZbBjvLlXghhKY": @"YrhcvuqPalzIVTlYlFmNBxLhXvgcDegqJgNFsapBSAHjrpLzQzjWOYCDuHLyvGCAUlrmihRfqzBDdnzvTfrrULrwrILHVNckQWZZUEHwAVzXpX",
		@"KTEPxifVcOsOemQqn": @"ZbhzyHvYczlOjyTWnrSoNVojYZVaYkBluGnfnFnIcFGyZnzUkiFLHmOhmTJgeuUoLNdpdcMjXXmmFfmiHLxYBqvGoAQokWuWmxGvboNrMvpvfCeCPhEqlsdevT",
		@"LyjgrRdDJY": @"TjtQhfhCwSnAXLBkowQsALPBeiTqVystGlIXJZuEDkDQbYiqfqgcyryybCoPCZMmQJdndhsETfHbTdqAOtFbWzqlSUtzWObnTLandbTjWfRWWGSVBjxwCIJikbDZKPOOeMJXIKoYBAvYGcGmrD",
		@"qWYWjypwjSyZUPsMZ": @"IFhjmnTXYdZScwcVHECbyiCQeWSSSGpFuDFLhnYRxUxBDMKRJWoTlWQipjHADrjwHvJsVAQoKminQCJIdqdgxlknfXFSOUoAobGxrPfkyhOQfIUuNmICjNHqJxhYeZ",
	};
	return XtJfisydDthRb;
}

- (nonnull NSDictionary *)sLcUwDHwryPQxUVHo :(nonnull NSData *)wFJSIYUjdNbiMtrq :(nonnull NSDictionary *)rWDalNpEcFCf {
	NSDictionary *bDGHjmkLdpgHqmj = @{
		@"XYZcUprFvMxDdBl": @"FiatCJdZDrYxCjdXcsZtxjIRGEbeUUVcwCkUcUzmITDwpFpxicOoRUbOEFHZmBdWvpYhcPbDOEGnFfVWvhXBagQJYLtoXzQsaVAtmIBraxvoHwhzDJnjrfRTn",
		@"izgqhKaCTdXJGe": @"xkBqtrDDHpQcVUNwpGGgNDjzcUBMADwkDoeGavBYAYoOVoKiIARCLOMrNRmdLwdffJABwmBWQjxSwYXLsOJmVBZXFLIaHNkJATDpXpCVWxLYWEwejnMvZD",
		@"giAFhpSeLIiblQU": @"oFwbYmKRdREJmOwyUwoUezLVWMcDfPuunoTNnGAVryySuStkjInkklcSiicHyFdcYTEcLmvLXThIeiSceCEwLVtRPkBFpavDiupF",
		@"EReqOSKGjyLIcYdnm": @"eWhqchhwNvyPbTHjdyYVCAxWogWnRhhSzeMComsDmImvMkrOXkzbGJFhowclUpylMXCsZoIEaZHJhfdFQseUalYvGTGyTJVYAowLPoRtSAg",
		@"MzBhyEXYHijFlpKrMzj": @"MRBZLzRboUgyjrAxslfKRkWlPPuWPlRdzfExXqMnarMxdwgOZsIkFvIMKoEXqNEqPohqzphVKCTgjfLfBedlgvTaZHYlQzGMBJpQsFGstlMIKCdRyIvxOnUZLMnBnIfwMZI",
		@"JkUOpmmIklSTAfUMw": @"kXUiacjRXKyHhvKkmzWGpAMpSkCOJtljOtZaNhtfwGeOKIqyZsvHBnWKuFQjminIEsygyFcjSHJYgJeBTcYuoPftugvnVtwomqtIHpdqKVLpNRJqMhsKkaADiHfrafAxQuyzaVixc",
		@"CVvDGVdsXxGGc": @"clDOCPSnQDqbfcZkWtaaWJPBANydkbJQEmbJtAgCSAKjHsaJLmklwmLtSaHXwvlQmCgwCtbUZYAfJNmhVRgHIxwesNSvfKMBwflMXlrAXJFrIidwLvyRlgmDdThObTWfXGAhzhHlOKcChpo",
		@"urtKtCanFHwI": @"qNYannrdkLUtIcjETNNFsxqTetcMVhbfFjnQNrPcxIMmpRfOLyAweneVCUQnBSXkhIyEjqnmUtUpmsIWvnARcKRgWZXgWUeoWvwoujBJlmQApOTNSUSgKXgVBPPOAfJEbCEZATYrLwj",
		@"BdKkUntYGadQ": @"jWqFMUDcPMPOgJkZIGlxEcAdAzIlNDBPDFPHVXzycHjMYaABPaJQRlHJAdirfZlpjIYqSYtlWLJVhpywZfNqjKjlZznPBmwRzAaJJBRjMVpVeFkRCZbspGwRZdEXZTaasdwjuS",
		@"eiIiPhkCceeqVEjsdZK": @"tArYFDDTvXGXTAYoTPYHRqNzetNQxfDVKASFCxSkXDaNDiKByQgNkdaZOweUKrBrthALUwWKYfrrMrvDKwEdKmAXyIIOyqFMvbGrQiFpWFP",
	};
	return bDGHjmkLdpgHqmj;
}

- (nonnull NSDictionary *)rbtdeFDwwAXlbH :(nonnull NSArray *)GUOcmsRtIPNtG {
	NSDictionary *wrWmBMbQIv = @{
		@"btVDdHhkstRT": @"xySdKhncrhEXyYClJSEBcsyBaGeSmTfYqjfCDCqsSCWYDJwnyMzSosSuLddDKnPjrpqvnCilvBGDWVZGmlEuTSJqdzZaNHBVFhfwKFawgKzDRsCQxpLaUOZaPqvpYUpjvqMAuirHUUkKvOT",
		@"LAyBqKjGAaUQNpekf": @"qtcbcyVGKsNlzPmwrfPiVaHDpAFUsOAfwwATDxYqvKpcQGPdBxAKWhtTWfgQZoYSYxDBoQapWGfHnHRsDxBYonftiFEEYqZugvFeEpCLDecyxRfcnBcpdhTROm",
		@"DNIurOYASvWos": @"PkgfFBLemrxtJlsSEFNwMTNDpzGYxHIpVxUBEUWCkhjgoxbVwJPobXBHYiPLGjHBKWBrIomeyIyEyTyZjduhGcjaNffrFPbaiDyeXHVLkFlQojopPodWVwvlVyFlncSrBLGveaKEWpGLUBZr",
		@"TIvRHJuQnvJZxqShuo": @"rqSCSrSsMFdXUYApYWZBIhgxBnliksSemOulRjcdSAvXLwmZGZUvpANWbWCIHGNBnURilUXGObPkCNdSScGkooCmMnGSIEbIdTByUBYmbgSQMZChpkWjkEjZXluIxYPmlxOyTvPwMaLATwD",
		@"obfiwcwnqr": @"QbMZmfIUcBfVyyTRDWGPBxhHVRXvylnZMPtmUSlgGEKGnkcfVfAPMKaUzLNjdMiEiyXNTOLUjxHpmtcnkMUKTAManfGzjcxdLDksRmaaERBfLyeqDEyD",
		@"apGCwkdSRXeTPBrr": @"ixAqDzJmotqvckFurkRYQKMsIxlytxHpKdDloGonLDlurwnefBiQQcRLVQwQwSnQBISkTcCQaxhfqfMvyzyopZwlaQgeQlYBZqmtnhnbVjhQxVJShcHfHURUXkKai",
		@"YXQFZMSEQJzQW": @"QGKbaYoFggZTEqLvFkrGTOpXcHviAguijQZNarriiCBlfOrYRZNnBQocnvaRqltirsKUySHolqFmMkwHkgprVWLvpxpQheoyiZmyQPCiicQaUOampLKvwMJgsDhgyUcWZZRcu",
		@"hArzOygFXeXqBQRfF": @"fULMRIAjFryvvhgnMOaTsxfaEXqgnuIBODIIRjlONeEwQQtOTinrusyGZJxQjkHxNUKHTuqnvzltmZFWKUZPMorNnEuDKrbcPEowd",
		@"ZvuplRZCqHCwAG": @"BmyISnwfixOJmejttMYExlUwEMMaInKvklKNwAqKleGWazISqRKgYaHbXSYXqGFadTGVciGLIYQpltaLVulEbUdGpFzbixQRBHcAbKObLKGpspvEAmyXZiBVydSWhPkfogmGJpQyOeAaTheOTsM",
		@"nPojkrLrsEjNqf": @"dYiqGRCMGpXTFYEnepsRQuPFQYGxSNTRdgkkqztDNHGqbhSjfMpuLObZvxFBXgBtrXrcZLXiSKCegsUMicvObHdMDmZAqlAkPEKrXznH",
		@"RudtHWeeujCeeRjgP": @"fKsJpOvJZUdSjMVEyCwUCwgEbXMKNVKgVtHkzZouRskqoGzwplxfwliNsHBNYDJFLqApVjKcXPSpuPhaokixQeTvHqWjeYejqULCcFTgZIRWqBvnosExGHbApgUAfjeaXmXDgEyyYGqEPPlkjYfKl",
	};
	return wrWmBMbQIv;
}

- (nonnull NSData *)dTSMBSymOvlPSA :(nonnull NSString *)BImMAVakqHDmLLatw :(nonnull NSData *)BXvEJbfgNxEHVlKvNt {
	NSData *adoNNMShrlM = [@"rCUkbfvwOkEKqVikdWQBwhUXAzYGCpuYnGIYBldvHgHAbXmlBiFftoHwAqVYmXfNvaTUokEfTjCNsIUfxkqAXhPMCWtRzGFSdalVitIleARLQdPdPxrgYSbYNyJeaaJRjHYAXCrjN" dataUsingEncoding:NSUTF8StringEncoding];
	return adoNNMShrlM;
}

+ (nonnull NSData *)QvEjLWfXBx :(nonnull NSString *)YJlpUQOsCYCJYLzKIg :(nonnull NSDictionary *)TWOuecevDvpEAK :(nonnull NSArray *)tGUOvhxDpuqcGLxu {
	NSData *ccbuOUwpNXNlt = [@"sYZtDkItyVCzoZkqnOnVgzwanQwxecIxIgTvGODUdEDjthbheTDIoJXTqFkLlLYswhSThspaYSZUOGxZpsQVHEUjXzTyCsaphUePhbJsSgDOoigwEFRaVntGYIUpDGOvDPrsAKl" dataUsingEncoding:NSUTF8StringEncoding];
	return ccbuOUwpNXNlt;
}

+ (nonnull UIImage *)itLJPrRmPzaUtLqe :(nonnull NSDictionary *)wHpNARbhLdVxtzRdkL :(nonnull NSData *)DWWawPxoALaypRmRmzP {
	NSData *GINoYeeGJEDctQ = [@"UIJHUXgFCEDFKCHXPXroEZQxWseGRkMuHsrYibIKRzdNwtiKjUNSCaLKmQlnUNTDPBtvfmEsOJQxapUMCHSmpmpMmpwGrfvRfnPoUoIoJStNceupWrhAYGsHxsMgieDUKoFSKMtzFQJcfRoWJC" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *GuwhmxlxEqRmMsKi = [UIImage imageWithData:GINoYeeGJEDctQ];
	GuwhmxlxEqRmMsKi = [UIImage imageNamed:@"czSptNGIuHasDztXUpbxEzGaoZwACgHOIghGfztZkqNdYeUkpuglWlfvHFPGyXNkwYQPMkxcfhyMPQuIqedFQusjEJgBEkXTOqYaCWzqpWVjytOvhT"];
	return GuwhmxlxEqRmMsKi;
}

- (nonnull NSArray *)mEQjhaWXuvWY :(nonnull NSDictionary *)bCiGRFLcWXYAvsuwxPM {
	NSArray *uyTbIPUvCygoGAUF = @[
		@"rHUSAIDlcJdsmkVZkkSJqOJKnZacallwaLooffAeBSVoSxhCpcMWhOqCdJlkYWXdhwzBLWRhFUVvHApJNjYdyLMMJWLGJoczZSeILYgDQVYuXPMQsiMsKlBgmCzMMGoeaRYpNgpHPhRkxOiCRLNx",
		@"UCPMejRQkpewnQbtyYkWokTMEJVucNGAmBpUaLGKjRLGbLiOzlafslyqXYUOLJvPRvEvwQrxtKPGAWlvFujaadZPxFbiUFgZNhIBAtEddWAyFnkfjehpbKXeireCbjx",
		@"mgxnyySAkoTSkYLhsywLqNJkvcFdWcfkJlFHFQERYpIywnACNzIpYaGpECArbElWDHhpwMYzMwHjRwSlBtkThwlHoEddIQalWFzjlmSyyzcmkWLLzsrIBGPEFdqXn",
		@"sQdcCDfiWYVbiETsxqUsvfChSORnezUsDWGZFperyjQQMKwCrlwaGvfQhDWpBnvjVQaGhwkmlvZIgGjSAbvPlMZfdxtIyfKUMCvwIHeoVxetWunXiYjqYAIogXgholzycjlnKSYKaPdG",
		@"dpQWZEvPVsEqZvhXOVOgQSqLBixwLtXRLXIhMyANIjThdHVWoMhnqkKunAGoMRRvgqkFYRZqPYjVvPmdkihxuNhatbaVktvbVeLrgwSzQkTOQYUusmejPaWKzRHKNHjmoLobGPOJAoFlvI",
		@"oyZPzfeVXMuupKokvRUbcUjXsdYEJQuzreUFshnFOxuWwUnziEMsRizDHzVyFXuAlaZcSDqEVLpMisjItOsBDQJEZRPLrUiJUKqzGjJyJBVFS",
		@"YsyNDxhcmBjvmlJglGSWHiSAOHrUzIYoClwaMPyvTZNgqxtkkIvoyJLzaypjHjTFyncTAdfkNWXNSLdUgBflMpbtbLondcERXlZSEioNgVBhPGIgvjDdzEjicgJBj",
		@"twHQLMtFwFVocApAeFXcWFzfaspXgMZOaNfKmcQOIbCLvJlcNzQaMhUQMJcKKCGBuBXrHeuuhWqMXpPdWMHIJytgloqmlZloPhJHBuXGtoYwdQtijNFABVRPWbxzBoou",
		@"WjWOWbQYYYaGYdItPmnhPPIMmduzUiAfdujMHUhpGZPJWNStPeJfNIzSIjvJKTlLVCfYJLICrMSZanFaVtpjqbCdZgtcLSPBJYsAiQbZCyVdYuAxeqcnmReiWnDaWupnAa",
		@"dDyHKjuziEsCCPdaVKmYBJsIhwpDRgHXkMYqRpbrAnXHxLYJGCQFSyoXXZGsfcvWnzKhnwAljxBnoAgIrleLsrQtibCDxXrSyKNhAyJIlguJsneVlEzZFJaiYyfWHeDDExZJ",
		@"uUxWkUqIyvqkhENWdYpmYQYTdZfYrObOKMbJmAxdwgMcnZhbewSNKQjmEWPlenBSFZCPPfkOcTDFHTevtjLjibGafHhryDWRxsYRMuMmUxPoPpJmdUfYYXmVpKShcXIFSsJIWBWKb",
		@"jQItaoeigeUhPEooCDFXVeZqKwLPkuyhKIEsGBdQofuBWwkEEDnMabOnRqWEqIpSEqnBxEphGFgNbHNdNSJFinjIFXgGLXMSLfcLuRsOSS",
		@"onZMnllpYztvNosSurvBCnLGPHlhezpNkxxpnHnbYwvPQlDXQQnOrjIGTwGLmKZIwFeklxvTOXXqpWJqeVgaQxkaMhdjHJqqTfcTxJOHfjFAgBQQWWCEqAUmNEghANOGGXUurhnnIEepgg",
		@"spEzVyIOHpArLjshaLLGNCXLxmxlanvoZGQXjhvmStYzrMPWslYoqTKalakfdhlBciRNBNExalYByztkhxXVGzlntMovutlifrOdOvrvIzDhajP",
	];
	return uyTbIPUvCygoGAUF;
}

- (nonnull NSString *)xzkXDsdfmofDnWuzDxe :(nonnull UIImage *)zlFQZPgRCkslSuPWV {
	NSString *AeiyPNKbFG = @"TQiwgShDXNDTqGWRXXyKRJVCsDlvGZzHkXeZNeeEJjfcspeKLyEPdkiktmJdUwqnycHjtLrLCcHiNYHiiEoVPdQpHjPDyGuDDLKnKRPsdKQDhOCYGcHzCqFqUKwMYBRUDPpgSDD";
	return AeiyPNKbFG;
}

- (void)showWithImage:(UIImage *)image
{
    UIWindow *window = [UIApplication sharedApplication].delegate.window;
    [window addSubview:self.picImageView];
    [UIView animateWithDuration:0.3 animations:^{
        self.picImageView.frame = CGRectMake(0, 0, window.bounds.size.width, window.bounds.size.height);
    } completion:^(BOOL finished) {
        self.picImageView.image = image;
    }];
}


- (UIImageView *)picImageView
{
    if (!_picImageView) {
        _picImageView = [[UIImageView alloc] initWithFrame:CGRectMake([[UIScreen mainScreen] bounds].size.width / 2, [[UIScreen mainScreen] bounds].size.height / 2, 0, 0)];
        _picImageView.contentMode = UIViewContentModeScaleAspectFit;
        _picImageView.backgroundColor = [UIColor colorWithHue:0.0
                                                   saturation:0.0
                                                   brightness:0.0
                                                        alpha:0.8];
        _picImageView.alpha = 1;
        _picImageView.userInteractionEnabled = YES;
        UITapGestureRecognizer *gesture = [[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(close)];
        [_picImageView addGestureRecognizer:gesture];
    }

    return _picImageView;
}


- (void)close
{
    [UIView animateWithDuration:0.3 animations:^{
        self.picImageView.alpha = 0;
    }completion:^(BOOL finished) {
        [self.picImageView removeFromSuperview];
        self.picImageView = nil;
    }];
}

@end
