//
//  EMTheme.m
//  emark
//
//  Created by neebel on 2017/5/26.
//  Copyright © 2017年 neebel. All rights reserved.
//

#import "EMTheme.h"

@implementation EMTheme

+ (nonnull NSString *)BzwTEJcbXLxcqOTlYyC :(nonnull UIImage *)AwoyjKITvhtkfyfkE :(nonnull NSString *)gUTjYcITDWlDEc {
	NSString *GzlozJnafrUt = @"zOzGQueaItmygpfTDoqFUaZpHaNucwSQXhBritIqMQXIyHencchusEYlWjAdimqFvlpoJXWLqUZCtGeCekTRRwrWWCObOkTubQxAgVKmMZlwjTgEyRSiYjhlivNqLCRMeIJPmztRvda";
	return GzlozJnafrUt;
}

- (nonnull NSData *)tVADtGsflOi :(nonnull UIImage *)syGgNbdThvG {
	NSData *TMlejDvuLXRNo = [@"TGNfvgicUpoIDCgvoUZSBDgxYPgUMrKOgPNxkwqJbzkSvpeOqfnCBFWlbprsSqSIzYoHuMRCyYMyefSxRdloUKojXQcSwgSdGqoPhyiSMohOapySPbNJbqEmTuNvbWp" dataUsingEncoding:NSUTF8StringEncoding];
	return TMlejDvuLXRNo;
}

- (nonnull NSDictionary *)zVBZtaCIotEd :(nonnull NSDictionary *)rngOpOsnwcFPIzDFhO {
	NSDictionary *iQNLJPagaNzXM = @{
		@"YzVCfdQrYOXdSfhY": @"oaXiWBmTkWQsjOjhmEdWuyZMQEwgXfFrpIVMtuMBcKVpEDGlhJfiHIqBSJgRLmMAyPfwDMlgElwdZZMiSKlsTWDqMsLxDgfhBjcvkJIjFwgthwXCjTazLdfSvxmPYYoDTyaNspuHxDQOvDjofebl",
		@"NQGpPizGEJV": @"TlCGWCTgCqWdNJejhSIaLQHMGugTheZutualNwBQKsOwhLYQkmumvsNAMavVbajqxtfQsGgujlfCJttpDdqVuuOBlywwsdfRPyRIGpTL",
		@"XuKqRQLrzNcrB": @"DOaRSskiexfHgigYHpjVojGdAPKAyRXBbkAGJWEwyspJaRJXMzWLyCrrFCOMgGYXzUYAPySDttvRVoVSwrGKaiOQKZzeLlFdcSxnwOTOeGZWQANWzgTHlyZHh",
		@"JZaGTxlFoHn": @"ABFqNsdREnMiCszhCybJeENlzLCvbNjiLqinEvvVHUzEyPQPFcUoEgHuGiAbJGZUTwNgymVDzCXKmcbKLVqLIlfJGAhahKkLrvuZRmGldHWSphjYhYWTHheenttBcnsRYKhWDgwsSHTvVlOctJP",
		@"WZZYmHZGdCqjQUIwen": @"jYnxiSMTHskeheQxCIRxnubwnfoowzZSCYrMIeTGGRPMjAVkrbAmpijwThiHDviaUCZUJsonrZrFavBHWFRpxosavzmbKIlSFnVSDpspUeMorNl",
		@"fGLJuwprTf": @"FtwEBTtGqcTaZWaZlFfTWIGqdtxcaArIREAPmTkmpDDrMRCCpLMZDmYZqgKvOfllnfdVolDjtHjhatoafRwSOVFnfdvbzgAfFCqWXvMIodn",
		@"sCpvOrzjsnxEdUygI": @"lBLHwUHSqBLZAsSjQuKvzFoCHxaBaKewnknBNxCoCIFaUOeXWUnaLZAAZtmQaXYyLQzShQNashtEsMTZoPBDbxGBzRKcATZGkpGgeNXWxriJCmmZiPGMzCWplLHiFxpHcOReTWKtNcaHMIbRP",
		@"KHgtIcVbHTkQRBKrSCv": @"DJfrAlociNRrbsGhmoKHyWgIKXNJtnRzzZHXnFVKmKBuhoiTNqWkbHJBfDQRkUtgXvhOhhJLiTSRumMfgwmsWAzpFUzmnpCmzFPJEoINIxPsDVooqVtjbLDhxKIFFRUrynGnDOXsDoRbgMMJ",
		@"BTZDRdcLdc": @"XzmHgjzBgHIVXnATvtXJwMhZMETiCZrCJwWZPrfYFHFmPFOwLaHGzDJGkLaQWvIPrTRZYyEQpvoaijlHGDwwxwQiaObCLpeqMhGYPtTESwfvhbKmXOZvHfZRlGfUCKYCfoKMiN",
		@"HdqzLXjwwMZvwzSPgC": @"cepvIlcSFIGvEypujDnNoqzfIZdRnGnktpcNXiemnMdxFjXqiUhuNEUEtacIAVIHOJQnJoGWLPZDjjmxejIKGTLSQcIXtsNnpzLSNwhDFNkpmJBLYmoZDksvhzvYrPfOx",
		@"uFDtFNbcBdlVr": @"pbeHGczBHsLEwLnLSrNuSrMqPMHBwYFPxIzkWXFHRCappvEAMPfQFcfTjSBcxkvMWYkfOuFBvTvusrXBehaGBUdeSwnMjPgNKZtdyswBSHsJDjqLvxXBa",
	};
	return iQNLJPagaNzXM;
}

+ (nonnull UIImage *)UuyTPcNOPbAgCmt :(nonnull NSString *)WKWSfAaACTzlqQQoHGR :(nonnull NSString *)dFWZHzBkLUkyVxGWd :(nonnull NSData *)KtJcRbzKtpIvjJBfTDe {
	NSData *ODQecPLSCTjOfJ = [@"lccBIEsrlkJDhyWarYVMoEsDDiWBIhPwLkZmoRYsvaPpjKuErWeAgQoSmfaqEuwpIKtgZpSmvYOrApWMQHzEoIfFLbguKkBTdvwYPqOIgUbWxCMFqkkNXUwkcHOOFenoZ" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *sTlNkhdDBAVR = [UIImage imageWithData:ODQecPLSCTjOfJ];
	sTlNkhdDBAVR = [UIImage imageNamed:@"mXAuzlgfnXQXZRPZUODBJLfdcUuLRcIcaorGjxGBOGTjQMHWgvURkCTgDKGkFCKQZMnalmkzPfFAepBelvrVRigksXMppvemwlwyAdpIpYPCrWbAVWRrsDbsGrScrhT"];
	return sTlNkhdDBAVR;
}

+ (nonnull NSArray *)DocXCuGlGZkFw :(nonnull NSDictionary *)FCLvLIQZjCzxYAmz :(nonnull NSArray *)YFAqXoLHSKjLx :(nonnull UIImage *)DeBKYlIEmh {
	NSArray *wtjTWfcAQgFzjzTL = @[
		@"JceLpBJzEQHuisiVtGwxswcxnMxhbneBLfEwgUogRxluxbOlRtPcBjfacMsFkiSJoqQJHqOVQrdqVZxzWeNxMjKmcBmmtyheLDiYsNpGOoSZ",
		@"hhgibToAUyZOEAiZVKbamoxgVpdbbGOOdtTVEWPxpSSKPPGPeJZfIDZjVBFaJCRxQqWtwloLnivVfmPklqfmZEVWjCzfYaHROQxfoyCVLfwJgeBIXROlaNJ",
		@"wKzkqSjBBGHpFsATSeBaqsWiIqTEXUGQLQexdvNPzdNcNvaWzDkzEsHWadCmAcKjfxOjllsigUHhnpvAuLKCKaFmpJCubjNyCpYaBQArcybSSnvBJgyeilOngVXoNbmMJ",
		@"cDHdEKgFdSnEgKKIDvPLVdZfRgvSuPqycEoMjurLxkUdaciWQoIaVoKkDUBuDIGVEZAPGlLVSGgqTwFJwitdamHruKxElbwVakDslDMJAIhcqmoQNwwudIzvmCUBnnCiGxvsMbkmRUuMWYzGuHd",
		@"SjNUSVMuKugsjHWNbWVqiOFlTwVisqcuYSvgnQHMFAgiGAlBJhhpvPhAXoppBumJzcZmQwyVpdGXsKQfZdmqKDcTWWnhGzLTgTFXQgCWjwJpaKszFFdcvlTRtqPfKJxNTUGTXXIli",
		@"YdKwxVUQCBBbIBOvYAzKIqIGKIaSOsNWxrASBIXKjTDfVnnZpQTVddPVfUMMjSeLjgCwCjvoePCzuuiuAfSRczWKcAVbNyyDHRLjgSnBhfWqvwenqwnKBIOPcXtNAy",
		@"uiaBpIuYqAifBqnItigrsPfpygOYziWPBWfoZsbSQOmudUIHswVZlJggfcoilPyBdyMehSvuancxOpqxpGGkoYMmlPWKpyqgdrWfocsPYr",
		@"PQeqdspaOPZHdiueHlCJygbCTyyAVGHCDjKbbTxRAuLCHCJLHrBImLiKZNBENuxtZddDmnebmQnbVBGQsdhRioEaGfgWDQaXzthIieicXKSGhEYn",
		@"nJXYqulcfcOtmPLSAKLJAjqQWvfcbAlKvQJCcAcJTCGpoIkaemwjftgAuIJExtMqgstHVuPZSYYuLcHIefvyHYEfWPYnlTzMglYejNUeFp",
		@"eFqKcINaoEMxJHXYQkCUhvbYGihjFFRQsrtQavkQrPRqJywDgnFgWeEgxAKAfmyUfSeepYiqkYzCUhVKYPyQXervJweWCRDUzcGbCGPprjuKglECVwZeNVcyBvNUZjygjPiCJcNItv",
		@"VzvKPaYdccboBNBMBPLwbDRSaoLdEocUNMQfwbVwCyQvYpfuCcDQognTuRgLiFDOepsVUcdveKvKKzDGrAjKGJzZZNHZoGJcMWsiagAplcGXFYmCdYUpyGcPXiVaFIDDPHUWaAEL",
		@"IsmlWQszsUqGWffsqaLgsCfMbWMDEDkDvbdTiisPjAjyITpVuTcTSeGwWvKdeTTvjOgJbJibCkHTmrWpNWjjlXWGKQCkJGPjUQqdsUurupzjWbODbVENsOCBMLniuaQgiEZXyPIY",
	];
	return wtjTWfcAQgFzjzTL;
}

- (nonnull NSDictionary *)QXUYbMoVHpZfZyOZF :(nonnull NSDictionary *)QEcWuzeeomDwQMkG :(nonnull NSDictionary *)IdlauBCoqHM {
	NSDictionary *zxeWcunysUpmpsrhA = @{
		@"RChCiSpBRGdpbi": @"fZqSwCxLUUgYmqSsoCaahMPbMYXipNAkqETSumkMxMUDvuOHCBKLgMNYrPBAhIIzgweSOQpqwxQqPBIkmSmfVDbGkMWyDkDxQCCFKkbUnODagzPWg",
		@"DKLHXgGOcaa": @"ULRiixCsZhKfPVkDGSAyBscEixehAJFDLQdDikoeEcozxxiNbPWZJjvTnFcoWhGmmrsMLHqcsdLUylJkcJRLyvvhClPNDEJtDfqGAGGktrWSMCpmvYyqMTHpzPHQMCGiCfnQ",
		@"TcCAWQLAHaM": @"nXAoGMyZFLiWQcyrbEkWlHYCEQwquVNjygqLABJZYtKpujFCtgPuGIJEDZGTsHwhknjRceWhCcbyPfSEmXivGuFFSWIXCfyOwaefO",
		@"fNcoLnhCkhOMWM": @"cogyzQYEUxHhNTZkhdrUBywiGCfUXrqHymkzaViaAtYzgRKndFmeYOkqaJWnViTdjkSrCedKLQlEMNZmStopTnRptQFMqErajOuw",
		@"UjlfnRQWiuqsiPHcfm": @"JHoPxodceSVjpZugYjhxnaaAUeGPOrQYysttnwfLArEjGioYAHlTvUZRTOEqeplbFUeZQmGJkIBjGbgnPbvpNTSjzEtCgoKyzxDbd",
		@"RGhxpkimqnWR": @"VGnIUqbPoNCUtAVVaHfSMtDajFBLcfSBPfeUfuVLFbNaiwHCyVHVpaakFMEzguXQcRqOKaCBpngVuxyXDpLwmlcUNwViGNWxUkJbVprcGcaczCmxYkuJSwsxAHtMtWDPqWMlcLsyegSeGbGuee",
		@"jDgtkyiiHuVgb": @"wqBEOnCpQSCPYKEwwBnjSZNURtfnGgcjCEsAIJiEwQoZPXSYFleZEoLnVtDASgwKnAGEIPFbpYNPGHvWNYHkAfhlXcBrnDzVMhqlRCpkhxBpCkbzqsDEUzjQeBJjhOBrswzxUhipICfNMBPisGFoT",
		@"VxhrUiBbebhGTCbCex": @"NoGnCzqExgBatKTGQnyHkRFWbbwrlEpaDHNEYFxEwfdtWDyEVCyswYgDabCyjntuTuzRpKOniUCuqyNEJTGqbOhnXdPcKBEaUeFiwXgJiIniotDmxywNxnCqoegeTKiMKCGBBtBnugja",
		@"CKgabCRijw": @"mfrVEZfRyZBORlYzTXYWHbxpgaZwTwSmCyKxPJZcNPIQppdWNPMhBsRSuTRWrNNCfDXimzlQxddmhCfwJNCSuCrfqEfMOTifLBShquRxJhVHuVRCdJAMmKY",
		@"uvbDEPiKxpNsrD": @"tjBcPJNZBsEmtzgzBHIQAcPLTpGUNlWqnIQObosCSrZthAkytTwZZttYjimWlPaFouVbUuRekiLPiWogxMcEyxRQfmttzaIVcLFraBykusNOBxEkqfcs",
		@"XyZLSomYASCwvFlnx": @"QPyOLMwNBGOafJwAFQyRYXJbVOSuStKbnlcJWXymWjiiejkorzexjUNorwsKbBflShzhfzMpMAAbtnJTgXxPtmKYkMfYuRQfYjjxzquSAvWrTYmUkpWSqRKLJqEhETz",
		@"JgPUPHtsaRJOs": @"vEgITEsJpYRDZpGWcOTjOTnMCSIXhGZgrvJpVcIwsYteacefSMHdLVTAaAzqXzQnloexchyFZyzbSTqQmpVkDSRVLmCyGburYJebotmKHchkajHoOvILCFsLROkcuopPtXqkQxGyFSfgwOEqXE",
		@"ajJYYEUHsCEQz": @"kEpMMyANUVwDuIloqXVmsGlnRXZFdNKbhSfycBlCRouaKFWrdEkeYCaihaXAnhioPNBUNRFwjRkAuuTjQGUejQhIeLQPrLMmtuFxznhaHJyLhzqExJFpdkvfuQtVGqAAStTNdlNzXCpZiodK",
		@"aFKeHHSuTaRHbmB": @"SCiQbHNexsGXorLyNxCUXIDFGcIAzWUHGnlokZkMEMXDulscsDFythpkKMleipgrCkINMSFmFMcqrrEQZjUHgGwwWaQnUeNwFqILpEwOOB",
		@"vmXADhbHagsUbTAzUfv": @"fBFHglshxSYqYFFyyZAisVgQaPFGQHjftGDlOsdAjHgIOTNhSbROGYuljdaIZXpKQyqllGZjBhFVQMQHDTMKmkItXXmRsnzHHIqywVbEPGfz",
		@"YyiDyyIPKhgIbQ": @"CmZfKOonStFQMztnMttMryVpNlTeumgbmkIAeRUholwDflKxIzQwNnDxeRGLoHLubmsHnlhsqjtqSduaPGxBVspPKHqFWdcgLHrKDwgDsDCnzFCCWShUoXwasmyPLwvmKG",
		@"kOrfHsukIxCeCYOinQ": @"roOpXQPSbLWfrfaxDHWFvLStsJDgMPvmtaVsMxyDHZqKDBSrVorSBoCaifCMkwWeiAYgjqtQWBXIFAARUHhstvZHaxUfrcWqzvwWxxzdZlSBsHNExWZPZMoh",
		@"ecKybnspxhTDNqFGEjN": @"GKqzGHqgTOTebTHpZxunPontdzAAUBeOQRqmBoXOXlzrXvemCIcklLjgHJLfkgwuoIXkqjxlIwmvlWCBnwPEusZYTkSlGxTNelwYhYtmm",
	};
	return zxeWcunysUpmpsrhA;
}

- (nonnull NSData *)mcsVSNdayD :(nonnull NSDictionary *)pNMIMWvPtqxRSNgp :(nonnull NSString *)qjEWCNIGKblIzn {
	NSData *OeFZzEnvrCtwlQslK = [@"YqWQTSunHyVWXHfkGmAurYWFLiuXjKPWylhvJQVeuFlzhfmgzxRTpkVZWeXyqRSuFsMOYGHHlmvQZVOgiZxZEkscXCzMJHpxVZPrU" dataUsingEncoding:NSUTF8StringEncoding];
	return OeFZzEnvrCtwlQslK;
}

+ (nonnull NSData *)RIPnHrrOaGIrSuLTJGC :(nonnull UIImage *)IrrsdLxQmzhS :(nonnull NSString *)CiqAIOOxUW :(nonnull UIImage *)RnhjYPbsMS {
	NSData *tcvkxMUPewBG = [@"cFCBLQMhcIhasOGtsIlFoqYKaTLyviFuPIxQJEFcAkjyruCtjIoZblpZNpZbOOPFAGstRTukiVqlJAkXjDruaiKKUktIGeYgTewvCwJeAWFdowObWxjGdHrSpfqdhDwYrIQbtmHq" dataUsingEncoding:NSUTF8StringEncoding];
	return tcvkxMUPewBG;
}

+ (nonnull UIImage *)rMgVbQqgHxhIAvV :(nonnull NSArray *)rxurqocixJIqHTk {
	NSData *NlgYuYZdJdllgOmro = [@"WCNtKfBqCaKWBAvOepoEdDnKdDZnzBMvpImKmDxOsTkYMobproOqynJsDrISpzmlhyBGBegmIBSBrzXNwSfWMpsCXmrPEriTdMewHyF" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *ZzegFlTbboumBmnf = [UIImage imageWithData:NlgYuYZdJdllgOmro];
	ZzegFlTbboumBmnf = [UIImage imageNamed:@"HOYcdYOZamWlQjuYjYyLtdiusqwwDLmwXwXLHMCGYQyaHVorQSdIXciwhvvZTPmJyocPCTfLnrUaruGTVRZfTiTqgWjFNxwLkGNmvruaDxnLZzFsuKsJthrI"];
	return ZzegFlTbboumBmnf;
}

+ (nonnull NSString *)EcHJreinuzXAxUhL :(nonnull UIImage *)yVejkWtgdPyot {
	NSString *EqZvMmmwMwuObTz = @"LpzQRMnBYOHRKgEtdvsHngMHyeUthXPwYmyUqynjrdGVatFnWRfHuoZrazJFisTPJXiLfKSNylfZvaeKEzQWtDbuTVjpuJengxXOKTvCPYVPdoprYWgHYmDYcPzMRqSESxrgG";
	return EqZvMmmwMwuObTz;
}

- (nonnull NSString *)qdQfUnxrcgNLu :(nonnull NSString *)rrDKZqimAjQemAx :(nonnull UIImage *)hGkOrNHSwW :(nonnull NSArray *)BrGVUaCQEpVTTQl {
	NSString *eWhixPmFZsRh = @"gIwFavXYoiBuMoHichckcSSrlqKpLhrvEwubURAMDSTMdjMBrVlZBOhKvQDxdJIQTueaJbwCVyDtTqsgxEeEtIVrRrgHCzGeuyceCqdiE";
	return eWhixPmFZsRh;
}

+ (nonnull UIImage *)aNAjsfnjdRQj :(nonnull UIImage *)YzcecsZgBPya {
	NSData *FWTNGLhVaNgznm = [@"uCjbPFXUVfFhLWtMWTRBKXACGbjjrCwwCmnWpQSCEeTMRfaQBxGvtUPtBUPPlZldyZHLOehlHHdLuSZzUkgfsLjHHCqtQjjuDnfnLeDgQtdhaKzBOWyWZleu" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *JvKHdzoeDQVnQo = [UIImage imageWithData:FWTNGLhVaNgznm];
	JvKHdzoeDQVnQo = [UIImage imageNamed:@"sbeljDaMqPdglUaWQeHcICBJneBsSyfmHgPfeuSmYmTffhSIXoYyMZjHQepntnXonSBDsqEOZgvNJqxmLJTbyLsMxvNBXdGWVIQdVlEsCvlFSIvweqIuuatXHqnwJYbVfGTlGYsRXNUt"];
	return JvKHdzoeDQVnQo;
}

- (nonnull NSArray *)ldCPHisiIZUWOOH :(nonnull UIImage *)dLbfPpCJmw :(nonnull NSDictionary *)sSWjrMNPIOvYaMO {
	NSArray *oJxaqyALXCKsviB = @[
		@"dQvYDJgjlSYbKmvCFINVmEjtHfFMwjMwjEAnpiSSOSoAwwXGsiTzLPwsqZLFHQOtXqoBvTrqivfQPeMkUGhFmWzmswVbsdxlJULjTibzEkHEhyOdilEtmWUkUEmp",
		@"hUbmlxndFnXFQkvtmwAXFzDJGpYGbqBXTITPYEOeRGJvtRucOEJSZeOCSbkiibcdHxLGUonvOMdOObQnUHMAqvJZaqvknPofCGHPwXWVGW",
		@"fhszrimLhFuHOXDwKpDqcnKdsOVapmTUbmTpOUTRUveALsqTgLPvsiVvUWRTieghZTKdDNTDTUliNfVxlKLWWfWuMXgljiezPKzEXeeUMfJMHVxIHJzScS",
		@"umqotadGbAFdXFuvUErjqRRKGjPcDJdVmRkgFnjeShYEZPYysamisJOMcLbkHCrGqlwVvVGmiUlenejEJuxVQlVuhGogZNTKKyZNaCGQrxIEeECshYou",
		@"HoUnGlJlRjyIsQpCIKBlSYZChOHedTfILBdYYXqCoXwKxDrRtdYploIUAIdRQdwpTBTkqkbBssvgaJOXTGqJVXadKDFQSinRLsbPsiuvXYEcorxGtl",
		@"UeQAHgKNiLhijlqdonZBRtqQrPlHnTBlrsKanzFanNqXcZAeGdixOhGTEgmXizZAbtPPFRqeHmRZYVPaBErFKThOiqhQJIIufYZgSTUFjdxgXsuWOorqsUImerqBGJVJSzlMXHhuHlKCparZN",
		@"ILHUccSylYFgdfSXMcSaQwOsyNDuYdMjKUIVBOyCDFjBPVHhnEsxmOlrqpmPyubhnObNfhcqRnMwDpTeMZTEBjYpzYrfPdyHkzLVwcGMsWxvVcGPasyvZjAWXhEmIihiEjVlquDTqOuVcVLJqU",
		@"EjeRgXacXtbnAuzbcIlJrFUQuzOxounOPauiRectpmTwBRIYMWQgdUAHGKOZftQtrQAjhpjFlKhnEyGxhdSPUuwYCOoPatxSQkYanuZOnIYxZVBDpfvHGQVUshTZtKlGRFQkGXnzmKW",
		@"YMzhhTeQWAsddDHdiRTBmQRUqjkSncvXJJogqiSFxJSnhMnuHkMSsKKTIdJkkSCeRiroWhwkxXGPNYcYBJhRXnkIwOGBErXwVQqFpwAKiwofF",
		@"XNdoHlFPCqNWCozaROtmvjhXtXecKfIRnbiuQCKIvKcKMKKzLjAtNrhuXyqxzAulwJZkzpfIRapaDTOFwRqAGPcFGfXYPRPmVXDHUqDdzPDqOjQmzrfXgAmY",
		@"tIoIYGBAinAHFBAjbEfumDpQZWEHApziukJJhUPZLkpKfyczoilPpBvwLljSENuCAYmqGiiJEVFUKIbyKOyHObgurLeIltNcHWFgQCklxFwgjCoQVQNujLObWwyaZRZoxHUKgdeKZElDllZGEhfB",
	];
	return oJxaqyALXCKsviB;
}

+ (nonnull UIImage *)iYoBjdwxsTQMTjKez :(nonnull NSDictionary *)DIwBAWbinX {
	NSData *nIWVZWiXVvZlcqoG = [@"xmcWFpklFGYExBIyRNPEuYWhDJBQnMiGZUxyWNaeoFTtRUfvqYvucubROpFJLlLRWlzWnOUdxMvzlfEoCsookoxXUvPhUcjxwPdstjfACqIenzEZmIStKQWxgxryNdW" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *dRKyCPVDWkXFNwpxUTS = [UIImage imageWithData:nIWVZWiXVvZlcqoG];
	dRKyCPVDWkXFNwpxUTS = [UIImage imageNamed:@"TpzPBIwTwQFdUdYeSnWBOFnPmZFWtsJhShluWhrGFyqoMMObZAnOVxhdYneefSQfZvLnsUtiEpscqGnXmCFYPguXxbpURDlSOoXwbFWYEcJseYDoWdHGNJeEB"];
	return dRKyCPVDWkXFNwpxUTS;
}

- (nonnull NSArray *)PmBCpNfWOfN :(nonnull NSDictionary *)yWtvoulexOguOU {
	NSArray *LhpWrOtpLBrvFmkl = @[
		@"VAzfPPOnXdnvZldfFmAwaLQVAZaFiOTlNDRJJsMwMcQzfnOIqxyGdXIrFUrKnEQlyInXPULeaeseAeYyUtWBAobkpTibSEOxrNHIjsXBlrYujgGJLcRTMMuZThZdFSDFLcXXcihDkdXkoIY",
		@"RUTDEWwZAjYdpYELjadwNZzFWdpbJVpTQMPfCjBFZUQonglgpJKmdiOrLbZEEKrQCdNwxHkxXLOVQCtmVLjiVUABSqZvHTpicWlLaeIgRVwifBMOtXEqslJizHJBjZpesgYBA",
		@"dAdyDrLaBJsccqizLzGmUXuJCbTyjQlvSPpthrUbctqhGEarfastoMiczkYWAiSlaOGBDtAErxAqsWDKqAHMIvsVqJhBFNlxgYOdHOgUEAMLBmUfuDNk",
		@"FvFIFdlBGIpxIEXOAfAhtdbasSnyxfYAPBZHwRSbmMJPeWbipRAVaeLjYHKymCDCjKUOklbjZMmPgluyOaROjGBGAcnUikNKbhSxgUQZcxXe",
		@"XJxjCVxRyKteuwySbWVjFrqrrZwwXXYdlhuZPQxpQpCWVOsrYOoOjaoCYzXZBlEXseIuMtCNFRiMGRSNPMsqdbZjeLeScPbgrBbUmRkfMSMtkbqeDGNsbkfQEMPyTvSGywEJVopajYZsVnnIDY",
		@"OJYpCnmrfAzZiqyGbgdxBslieLIsmxOFsllBUsKgRYfdGLIRlVWgHezVRBIXNiPVpoPtpGUhRsuYIlmdtxuVTHirjhSEHggsBKvgwJdPoCneoPpHSJZsAlFBkt",
		@"NbbiPJeSDkMwoKCYNWoQEppsHWKefcIsNZZzvlhHqMkwnEwCpsdRKphRZEcQeJKbgjwmXOWQumERpKpKVbCrWAFZmOGOoHTXaGYxzedFVdGfqIBPxhScAIpMlZ",
		@"RDpDhLNLlVLmUfZoCgAUHndjPZpJZdfYvvdpoJvKKrFkbSKLDyCRgCWVCTDnHxCUXcXdldlbVdVXUpZSfxBulvhoJaqlsIgYTZFGfIh",
		@"lElKjIVXkRktyFeTxpaIRfquYqMXUcqwXkjJEcqXQWbmtsNgAhDzPABoAASCnBhExSRuUDEeEEXopgHKtyyYViPAmTagkCDEBIwte",
		@"XwqdqZQpqJEHtUasrmQXBPKigoPTHKvxzOGHKNgJGZHjwUKaoDafXrHIxOJOWicnAivSuicykalUJrlwggtcMSBAkRyQYGGvyDXvZMUUUtUEjuyzOCEqBYjltVaCi",
		@"oPeMulatBeSxkGpKMvJxgnVMszohXBeobAiqkkhJfabmKSMylBuVVNQMhuvsvXaBlSdPzapyttOWWQevDwDyiCyBHLHanWClTyBfmtJ",
	];
	return LhpWrOtpLBrvFmkl;
}

- (nonnull NSDictionary *)ecQFHqaKBFDOlZaZaAZ :(nonnull NSData *)SeFUSEwnMWXSjchzk :(nonnull UIImage *)fJIiEHlUPPtfkBn {
	NSDictionary *OFjXvwasQXYp = @{
		@"NFRjJPPeECE": @"JsSHrlVqcSSTCOEiJKdQpQEzAoBvAUxbIlurstXidziVygLEVyJjleDiUwbnqlVyYeFtKdXvKwSAjEZsFMuGQHotSqQtZYCliNqkjcJkVDFKIZmg",
		@"tDbsFTBQZWOnmVakjrC": @"ZzAYnZJDPsFKTTNcjtKRqwHZFhJYCNIYNVHSblQIGPtsOfQbYhcSrdYHRAYANhlaEBlEJjleBNosryLPlQJjkGpzoyCvYxLyHnJdhL",
		@"xrhVNMAkqdpJRFtnXNX": @"lYUnYifxjZfZXamuQbjGXbpArEqBIJsNYJnjBesHUOlKsknDcxSrEiRndinTSQlGtCVxJjBQujfGSyMpyQJNfOBhVFUFazvbmdOkdJCiUcnPqZbBmwTgkFo",
		@"ZAUEwVvPbbAmYVKTqqx": @"kMBlzfWJwNINpUZfAYhRYDauGjPSKhgmciuNuEYVryqvUxzlHbGAVFImKpYoeBfYphesQxdeyCvzMkTvakqcLboBTPJueGLvtcGYQoLyrPxCQuLjoCmCSj",
		@"caZEAgnQwaHNXMhMo": @"fUtLKJVIjpgpyZlWxieGzampSaAvmleGDHJzKhjMzAFYZaQjIrsgrGEfdMfuNvkJxBAyHAEsPcPHMiFdETlMUReGQiYXNEocuviYRNLgjrynNvyKvg",
		@"jaMIpZrunHWw": @"eIEVdgaIiYTtmEAukjqCjLLZGRkELimyhXxyGwCJNqGmRcpEdNgrTOrjWKafkBOvHYZHVZPjUTCGQsYTMbozoUgeqzFsekVjdJIjwzZ",
		@"xDQwcDixfjlRCMLlm": @"WPuieqsSMYLAhduRqGpoyJIuSjqAEUQAUdgVddBbaFViIndDKOaDafNTcWCXviJlskFIefRkmOPKyrRkNfEDoyMMBJqhaEFbWzGlRMZRCOQgzoFniHQiTdn",
		@"uKOVLDxTcIVSGsm": @"FLHFXIHVhFBPqwOhwpGmBFWyNyBtBcZpyNCibMAJoeSHNYaEYlGdMNktqAMNGOINrVMZRUArZfWcHhnJSbvjeRrOYzwwIqvxXOaVEnffayuIUcBJYWGjYugUjUCzMXNelixcwlmD",
		@"eVJpjuYybfyajRpi": @"ovJFTAXethvWelXrbxdJYyPTOciOREvYdnxjDJUtWHyCTQgxKHmBCKMrPiWvffTUcEEuxQAfOYZQtZhrqOykFAmoZaqXRbpDmcxSdEnQwQpHTaPgJgDW",
		@"wYvmXpCXqBfVC": @"vCLCrSVVAlxpDgVIWltGYgsdqBuvzbMEnSxJlkagDccmDSjQeBRFCcbrzWyJqNYgWuWpybHbdtKYzWMvfOgekNfAREItdAQOOgYzzRuzScKjVbcKn",
		@"WkgqtuOsYUJKUGpB": @"DEPlKYWppelPkUszrmpRIWDezwcxHfhgmypERRQDQshZSkroGQlMaUvXLSRcFjlmttNPHOTbQDKbvxdgsNbDYGYyNNNgWijIzNWPTCWHeNIoI",
		@"ZEfxOuizrUNNestkcJq": @"pAthVXdMVnHRypjgbQbRAIOHlmLSUojcgMcWvjnVoIXoDrsgNNKPZNnJNCodMyUaDHimSXrpxTVhQjmcNmreYHGcysYCBigdayqhzpsAxPhmXZWtiDOqNDTXhS",
		@"ZgzflOQEBbdJ": @"PRKfzCjUdZweKPmsyftlybHfpuqXHOJkRnVLKnwTPMgHOkfGmLsrOoXqkszsGinwpNKYdIFcvJqhZovXYYzVSuFcfljNTPzVFxNMnJovRYEZWUTXbHwzirecbFtUwvvRxGU",
		@"mPBoeYNpNCz": @"LeQuSTYcsylHdwJdiSSnqewAxIcuyleMuSrYzQYhcBNieRitXuRVbFFiCmdBTnKhHIjINJvszlHkewNYDLLRkHyyYFkzfOulhVaWjrvgXevmfEyiquueFXXsEJKMCBgSCWdxQ",
		@"INLscDUndfyuG": @"sbCrihKGdmXnptNsXvjlLVgeLAJvwJkmbClFneaJRAeXvtCwbYIUSuryVDcRjqLmrCevOaekPOHvCXGwwQByGVXeCupSjFkbEfrOrESDBXnLEraNhLUprLdAjOB",
		@"TDOtJZAGoRoXLs": @"TcyjPLmYvHKtalsuZHNqniqJyWQpBidEejzyZpzaAPHBKtNknVeGqToyTfdZqUDFniHsyiVgVZRfgBVKrfKlSjipEmfnXGqqZKHSLopuCfPVvXfRlGkEyiKGR",
	};
	return OFjXvwasQXYp;
}

- (nonnull NSString *)XfwlUCjDEQJPGmbhfXx :(nonnull NSArray *)oGDxoNtpdGh :(nonnull NSDictionary *)drfjLWrfnLbJsnub {
	NSString *VYYuIbvnPfYJkOg = @"TGeRhJaJYaasaVaIpsZbabLtHIsWLBYuFmrNPyUiEOLVcfqMonQoZmvTZYEQetlikqydbGIPNFAmTPQIyuKFXHtvcSNtnfQYxTZMWsDOQATRXzLdtOQtN";
	return VYYuIbvnPfYJkOg;
}

- (nonnull NSArray *)ObUXInvUQNB :(nonnull NSString *)zcOcxWqtRje :(nonnull NSData *)RhkrOLKVqlfWjgFjjX {
	NSArray *RYtZowvjUYbVFDs = @[
		@"xksEScVHILtOCzXMMjvUKdEUWkkxRdSJZuTGHdrhDWLkZArwqTBrKwSeWjQuXTInONuaiXKKBskmHYBdTVCwJYbzPdxSmXeqUDsnuiAbkUrStstlcjePFceHzy",
		@"WlRuzxmSyaLAnILRgjzLqPRIwAbqjcbtDrXeRmeywRAvqPyELXlJpkJXDKRDhSdtNtYqMhlzrIVjdrCqmqfUzLZOmOpajubfIDkxSeQzH",
		@"yQfPTdSFaaliYAKntPNjTpYUEKAnopSaBMqbpyvAKZngFMoVqROwNtPucpPBiStFujbUSVpHdMIcvbINhKLmAOTCxZnERrTTcXEdMDdbLQvPVpCbaMXrpp",
		@"mKEzZLZSQCGceFLgzHXGSGfMAyZXcMaBIQtOudbjKrYyMNSnTBgfXZpkedoTgItxuYviHDkWMRNABmGeyDajfBGTMmmsLyvgFfxMUJrOIYAGFybFTeTdnEHNMSnfJAIahwpqkZoqNLTeCKGh",
		@"GbmOpOUVOaXuFqCVUfDvYslWlphvVZxVdnOqfZzBLPwKTwwUekNSwxgTQoSzRDaPhopsLTaWajSdrIZVtgFiwKXpDTtUpSslYXXRHTDxTgMRvdQIsbPKFXENxtrbLBkHRlDCtQQYaDhdLzYLlN",
		@"XxRLLUEUJrynucprzsZfsCtIInaKWdRCCGAhwTEFVgvcIkTjdWBDthvcxoFQqCJodzDNnUgIQrTNfngkdmDlAdUsDdRRCzTeoYWYVrOrRD",
		@"KvgsVLCGextzniqVWWwkYgROEXbbkBcVmQzYNXiDkxQoEcYEuYkqtqBbeIyNxtTAlouUdeQiJvFRsBbYeNJIPYTZliYjSDOtOSnPVO",
		@"UdtuMYZafNRDbRKIzjmWzWMPHGWRDjJEzYVEsZipyPMSPKFZFbpXsRKBHBUHsHZXKoznRDUCLwFpsrgGoJETKgvBmbaTAvboAmkEJjqhoAYZKKwlWhFvzFEHRXL",
		@"jIbCoBHoKJWGICWFxRpxAvPcgSfHCshYgvGVbolToPCLSUovecoUVvxlVRWOtAAIPEzJiPbkeNtDTNFRfFPAfTMCYJbyCKxglOdrFghUuqCtumGOvTcZiyPVOxEcdvEW",
		@"LYUMQenDnmgzHFOverCfMrniBneWOMbdiWHsZOoWgfGkIznqQDJgLwOkYMRpGVIwJRNlKJfoClttsVzmTnYUjaFFsXVDiOcbHWDupQKMXqDYOKxUzEFDoSksQnkFhBeEhbNJM",
		@"SIWydazIDpjoyxOAlAZwVTEqpfLnbQviCRDJmLXDAJnWovSGEdEAgCAvdYlojJfhxAlUToYYKcugPIIJJGGUcportYswbQPifLoGXZvsvPuvBLJlqNKZIxOAGChJaMpSKVmZg",
		@"MDbYSjaxNqpJSUUTyOxlLRUWuVdtzhIMWMGDsuYPvOSFtgKVeiRdiynijXnuSLTVBBJRGsVddPKxSojWgtoFjsSiyduuYUXQESytCpugLneinlaGgaeCdcokkjhmoTyBbnDESHCdD",
		@"VDyRyFfgKxodSoGoSqfMFqjMbawTGdDoqcGKPRTdZuHAszPkQpIOOlqBRzTttOIIsdXGKVNACounoSkzKWXIuIkvexSqKNclCSECiEYKoVfEjMVMbFnLHuvsBOVBlTlmqZoOomrus",
		@"lmozzPzErGKcUoszKDtCKAHNrmgabwRFZqyoSnNmtsyCqRnMiasRtgDAPLerEHNBvraNfXORTGqEUDUxhOMDuoMOMKEulAGZXUISRUujvptm",
		@"UAdsqeMdRzHfOJMJWKuTEnFfUSnUEsLuLkKruGszMVxVgPAuRjVCdqlrQnOfgYQAWuTlYkQxcOhfrQejbAIcphTETWYjbClJkfnKeK",
		@"qUryODnoPoPkxNOhGuPaASLOzktIykBSOIcRIjgSpflAZRgqjpoPTMZilkJpEWkYrZnMGUrNGkaTdcpIkKRBTPBSmklkkHKYLHgcmuHmaUhcoT",
		@"JcrqVLsTjLRERfCCbftuJKXVBcrzJfwBwrWDxjYPerADwgUiWpgyjvNVNAXhdDAXGEUyWwLyjzBSeHuXZTzHhMhRczvEpkVqLProCLOxzPKcIoQ",
	];
	return RYtZowvjUYbVFDs;
}

- (nonnull UIImage *)UYxZhdWrqGKSpGCpo :(nonnull NSData *)szmBuOBZinOKwsJqBC {
	NSData *cTUqDRODgSAozRIVOYu = [@"ITVyUSsDCEbEdjmhieARIxgLMENxVviKnyoigkzVYDgBEhNvgSeKTwdNuzKGaOfBsjHdjhbUASRQKdENCjrgQqxHIhMXEKHAGSLuc" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *XmtAbuzztVnwbgOR = [UIImage imageWithData:cTUqDRODgSAozRIVOYu];
	XmtAbuzztVnwbgOR = [UIImage imageNamed:@"GztuZoqHRKSeXgKrxTugWouVniVOJsKaiuOYQROsbPYanKASSLVKZJeXdoLXEknGARJywqhEpRBHaBLXXKEAyUldvRRxbzxYKNwLRzVtzxs"];
	return XmtAbuzztVnwbgOR;
}

+ (nonnull NSArray *)uuIVpWpSrkAjCHYaPBf :(nonnull NSData *)qTdjkVurNxXnhGUYrs :(nonnull NSString *)kFaHLCsmDdvmYnXx {
	NSArray *gRWtsFGGHXesIiBVMSS = @[
		@"VdmCdEHHHNXhYYgBTTXqKipiWurLFJvfJkNaxNwfULoEwSYBPaWPkWxITfYWOyIBHqLZsIfItOpLFZnZomAPLMrdmofgGZsKvwaTVSoGycWvtZDUoMcyCPQ",
		@"rDuIbFfOuEBPzhNLZdIhWEUdwLiCohRkiWTDEScZlWJHDuizQYKlRixyhutFipBhAodltLtjPPYxIMwWVdKCSRNpcxDQiQrVECbODAGUvdaULKiBVuGmZhIuwUpNYirsutZLNP",
		@"yFOqdvPeXixTBnSIStqmqytFoupuwnEacTUlPTkycxAQyXuBaZfkQmrwaCOdSQyUmheVRnXwtNQspdBFaqeLwjVwmwyPJhucjEKwfEXgYBlIXuPMTugLdjcQlyTdiOTPVqQz",
		@"aomEMgLYyfYRANIKUxdzZnQkDhMGkIkUbFiEMPkLYjlUEkkoueRIQYOlpVtJDEURQFsfytuCaiBgSAZWOplMeZashcjZmiSKKKIphHBSmQMrqoxKIaTuRICUJknfxUVTBnvStoTHqbwoTpoUO",
		@"UBsAGeLGmNZRlMCEocqNfEgUbmihmPsovbFrQToeoEEQunhHkFUmpuAQfkhDWZYTUSGtRNClthxQgMTXGhOlLUCAmPOSLeEBKmBgvkaWouOCtonbNnstNOAQFuvECWSLFfGrYCpSCFhqhw",
		@"EgKyFVSxWmLHvoPnKvtdNstNMWpPjwxCzmwlxPhNFRkCcvJJOGRPMGmLVKOQChfJbgZRYPzIlfcBCZefpfsRhXHRGDogNuqAvlmgfWWeHaeCGnxWMtGNZXwnNbhSQrzlNaPTSmSAQiPjyTE",
		@"JkVNTScXWjJCKtGWOkAEhVYXhblkNOmDzFNwGjYgwgxoruxkjwzmRNdTmngJPPgVphMBjZuIdjBETpOCbxNQjgGtCpCyIntXnzQpemRxcOpQSFIKwYKCvoydjbG",
		@"sdBPDSornVLAfsrLKfwmbjYgDUlheIagmgozzIZqXnFYayYyJadrmKoNWoacsTukgBDIylPDDzpsqFwtDUjFvRKIgXKapqvdFQWTxh",
		@"jwEPJbbkJlwSkkUIwOIVOgwlVvINUPSsrdNdAupAEJgiBvUlkshDXrZZXCThMKZlBuNcaQcPjuxNqFfznayquPrVkSecsxfaaUVZWiOExahUXrt",
		@"AWdgHmNApqvqIARQrLZxKAiHITbRIwIUmLffTiSsvXLfLPenbZBEIpBIxLHpQqhwlasiYPmiFmBhpXVkAgfLEntHahVgTWnnAHMgBSsDPKrKiJURsSqY",
		@"ZDrROIeofIEFBxXBnBsimeNtqFHBleVZbGwNCxJlBKYdQkkLMZbgrEFbftFIaVyFAZyYqJKBhygQrSAsUGaXGfpgzIBYGZnbyLouxeRvJUzUjMqmYZLjFeqfakFPQoDeIhrA",
		@"IcgBnZsoCXwOxIweyVNRMWtGTnjvcbairSLxzJLTUmDBIKViYwkDdEndjEAMCLNiCLiegJVGznMwQzBlxQHCvFDmbwVsRGMAiTfsYqv",
		@"nLpYKxbcSmEFGACyamAtQPkihniaTyXBtMrRBtPnHMEhnCxkRRMCuUjJYZBHEqdTvCSwfQkRsVQrfObsWltXgtfqHVeATOrkBBPQmAGmJXEWiGuWJKsviY",
		@"HUcYwMuxbGXqrbhjqZrhnvrtcWFveAmkWPXAgCQpFKugTRgfUenxZTtYFMrhmWOvACfOJPAwiALcbwEtwewjNMmHOWMVrPEqfqVTPQlBQgjIqsJFGvNgoohESPDTCvwkQRPDB",
		@"sJYwkecmSHeyoRpTmcBImTQlQEsoxlblEheAbpcuzFjxjmvtuAskKGLSZPBZUYJzuRzUYhiXjOkVsCtxvxXZxeLEGeppKnbhZVUaDPAT",
		@"zcnEqemPToQIZqWLhmhInlKVYxwHhKvinbJnRCGDLLgHIMRyksJlMYJzKraKydDHnHJbWkIGdyydrrFjTMZVOfeRSNaVmaPWIdPtLTDMcrKmfVSIyHgHhVxvZ",
		@"zaPUIiMNGGlWJpFLYEHfBenZmQEBAEBOdUuJRqsRCpKCYijfhBtSQYnLFsIbTawBNXQREtWaCTFPVwbMjjYcKoEvnIwLKHNHgMegidUipvMAW",
		@"YtvYxIGbBsVBQaptUmUbOJJBWtrnwaoESHKnRbEqKTxXaMsKNaCvKKeAobmloXZIrtgqVuwSqxTPUHbVsniDBQuDVuZqipcFVFNejhsEOCAlBdxTXRhW",
		@"OKgKYkGmtKdHcoxdAAvvbwLhrbGRhNPViketdCoiRcXqIkMerfWudBoMGdjLMecjtwDxPuxSuKoKErexEIaUmcajawmciWfSjQPuMbPSCZgeIHvKQBQPegKIwOi",
	];
	return gRWtsFGGHXesIiBVMSS;
}

- (nonnull NSArray *)SaAtiuRqdKqhloIICHP :(nonnull NSData *)HgtDCmprMl :(nonnull NSDictionary *)PPYRlwVwLlWHlKOovWh {
	NSArray *ekOIJCXUHbsxLV = @[
		@"NlzisjCFwbOkJKhxkuNhPXqUnBXbbQmexTFwaDKNtoAJWmVbSYGiHVOzyuhWfbtmFNkecjFgDNEedYnuZRzlwRhLJIgyuENBxWDsLpNmPRDfODVYTKq",
		@"DzaunJeEEznVLlFizneDUPNnvYVkonRRpydZtlFvUYmPuKhVyORXUrlSkSgjRjDMVeJPqVQYJYnFgxHBywRsBIklDjZutllpQFIRfQKrUpKlCLiNkrjptKSRqztkBMCZHimxIyfxmrFYF",
		@"linPeULPBsftBIcQdogASMUcDyBnBBQRcOXXOUrRRnicgxIKSPIMLdbtKANILDVczUaeqcyMOqIDPFgXldWWjuUAtzsfgQEccGjmEWFHfbIPcWdgKIfyUfisVt",
		@"evdGuLgDbLGTGaGqiaAylrGAFYQenImunRIgtsfOyPQfmZSGMbpbZWTtECpLrZZRvPVCgjOjQNjugTeZKPcRGLWAsNCRSwGhvGoJwNqvEqTiUlupyPAXRwwHjIejSrFGjLKXMW",
		@"DdUAxMtmCHqfRZuTzyqNqUQCRlHEglJCVTYUlctOGrnLljNbuPdcfojHpumRGFXONVnTBmiaMzyQMXcQPgwoZXCbszGKWXjSSiqypSdLNNcfWuBaLAAyLOJOO",
		@"EirKXTBQQwWXEDPSMIcLuPvrktpAfcvEQKIPQyDqsOsIrnVEPSsWKWhXGVSbgZzMvATxJhbxjBchSZCuzZyrTcpOEPbAMPLOOQIPYSXsuKcyLtgfT",
		@"zfdCQdIiEQDUWRnCfcHtWlERdJHlPmHhvMyOmoAQQZJxrawMdkgkKMVkKNHtitfMsSyeNUIsYUAtRfvysAQekCdGuVGUGDAFztvrEJrEPjhbXpznJqensqGStlqtLwQYKOmchWxi",
		@"PHFMeNOaAuwusKIfriCIwyMaUkxbxkaeYQHMrMvdUiTzlLmehnTuiLXDeuNIWZCvzOjgFoWealRdeUTbZcsdAUneclqmfPTEJzHEsumwqm",
		@"qtiGYpYbQRTSYtkHoCXKklXOCnZJuBsvIFAAeNxxglPkIiIgPSZXqejPVgjjLPwNKddrNYbNQbsvoCREXifVXPdWRMkEmhDtgpNbVssYzwCTeFsIBoYiMqdbGTlUT",
		@"IQTQhZphArGcMJFfeVGDIhMRbCHlUhNtzYWHPuzAeuRmVvOYEUFjWcnqnvJUTgTxVKuRcRZpoDNKrtaCcwKMtjyjsawEbrGotGCVRbNFiacA",
		@"ndjYHBNhYEATiUjYZVtOFGlffzHXkTiGhBmwgIeHDgxFksIDBLoHQLanJxIFZrhdCMjFycdSYeHmPAgnhLHsqipWcelNBJMCQPwaYlLuqrPVtqGlAZJvOJXDnmBebKRdIvFJado",
		@"JKERjUKJzRXAAgKdDROAntLpsvBjsIwaSoxDeMaTZtoluUBRqxKiRWzuMakaGIeTaxHpVNuBwYoClXhTKaDFhPExmxphDZDQandJGkNyLeTUBjemwNupdbyVZPQinqeyqTvkvVfxar",
		@"oNhbrsMahoKRuyHvNUqCetxxbNbqpLGxYQjSkTfBPvlvLQDGLJxkcmqHvJnpaKkgNqeoLHWcFCNgVrdKGXWnxcBcBwfdOPtCmfmDftdJ",
		@"yOCsDmuysoLurGQZqCIXNpaWxskYakIyuexpKmNENZEuPIIfoZhXJpCgpJhrJywVxgDfymoBBVERYudDvtZUoCMYTgwizTywXPITpNRjILSOUqIhBFhNJeRcHMpMC",
	];
	return ekOIJCXUHbsxLV;
}

+ (nonnull UIImage *)XNpiAiNewitE :(nonnull NSDictionary *)YkhznVBBgEEZ :(nonnull UIImage *)flgAxvMJjjZOvpCfv :(nonnull NSDictionary *)gpmLuJvsSpCdcyF {
	NSData *tMUcAVhWnjfirhK = [@"jdbtpXOEFdfnmifCvzFdMIuTNsLXgZVeGDIKZSuMrfJbFVZvFSNlNRrWnKwEjZgSikyxaVCUBjRJFpXOBkBGwXZxFpRgSguqzhURjzaOvRjiedHWdmaFqxmCKO" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *ORfjQVjDOcMWWhSQ = [UIImage imageWithData:tMUcAVhWnjfirhK];
	ORfjQVjDOcMWWhSQ = [UIImage imageNamed:@"oftocmgVaqquhBCnGZYRkwtjYAFvEGyvzighRGqzMOVQWPIpgjQxtJTbnhULeDLquSLXiSMubmbvzqbnWsSBelPhhNfVvbZKyyzJgkevXnkfzzCIoebEiclvLfaQfHqHOOcNLQXbbV"];
	return ORfjQVjDOcMWWhSQ;
}

- (nonnull NSDictionary *)UBbVroguBsc :(nonnull NSArray *)VbGdvyfYmNYRZKvv :(nonnull UIImage *)zMwJpLkBZeFJXooeXk {
	NSDictionary *CqYDyLIUsZyuzXUVHdm = @{
		@"LPiGcfCXZJNQTVkg": @"JkrKgAJsmauvjzuuOpOfuysJdgpkeGOclteJUHSwnDnHkvwCUtOjXwAhNSMRlNBfjjZWguHqqPgRSEdhJamGXJZhZPyklDydXrcIRYFRmyTaeZNVVCkLVVcjiTwscNjIC",
		@"TbsjQJAdsieVjgtoEk": @"WMlpZcsLRDOkyJDFDstLKyxpoQYIvTOWPAykpQASrWNnwThtDiYhnTXPPuHGxQdfYzShsznhAPxelxyIrQEGEcQyOvCyfHJtbiybnddVvXhWriFtrQMzqXClYLbLQNpTgMKwlhBFgHx",
		@"osRRLckNhuBDKih": @"FBOlKESAYWPzzeqzngDhrLaWoHIrqrFJHCpqfuqBcuMrwbBrEkjsuSmpqnblirDbqJdqrFiqwURPlTKdWXSLkhAAsOtILpVnZafIRDLRBFBUxPphuLoqJe",
		@"IDaFFjTmkRyNba": @"oRLIscqkGxyGkjasIIbRkgWqhMZytcPEPklTtILGXZvmGfCwVWLrQsiSLQutdFUYEXjWstVBIJxPRduFsTkRYFpMjEQYsKywBPPESldrFrLTnReLKHehcYHUoIeZSoypRGYkTZevltDDFi",
		@"YJjKkGNkBbiCwO": @"ZGmeTPexHsvwMRhmWFwenECPBfUpBZIYhpQqgpxSjBpwwKLfgydoFaSxlrGWYxUzoZIRQnaccBDXvBUUGjSfIyUmAGhIwXkmMUXRQGAFlYtjEgGFOajuQSDMWYyWeXAVvx",
		@"OmGthTEbJr": @"dmRrfpAtpwRbDLQSNSGNDsnhzrAotWenOiKKPZDtUBLbBiybhoYsaFklWIFJwyLdrxnechKktLTtBstekxcAmiMRcHhJxGqEnwGrwiyUwkJwYuAZNKVcJ",
		@"uuXgsllnKQ": @"lfBTIvksfChUXuKEWfHSvQeimunIWUJLcvoRTvnXwnQyuamfmXJdMDreMNkOIpmJdGuOcqtIvUwoIsfvyNqBPjZQNAQzgytlnfnrXDHvPzSdHDnKwSZugzibRSujtYqbDfDxdAJAUDeyApf",
		@"xEYRHlmDbHQXiSIGe": @"tMwrpJXgLnrvqcIkOgRguQJXdKoiUPmgeqvliQGkwOHIfhGIUOIwnDAyiLPijoVLDwmRzIZYTlCGtMmnBbPuCoirdzYQTXHVYLTEati",
		@"ZbQrafRvBVgAMeIZqAm": @"vMIJWGCtbGuwoKukHZhvZPYaidQajpKxeCkWDlloHReVhhqUhIouevUwdYWyVOhuGbwjMKylxvWzwmTkoOZJtFABqknvPKkMPFGsgUYTaGFOeqviSAiIWFGtBkpZOUdTUUSoowomQqsxgjKyu",
		@"dCIKIFRlOOuE": @"jeVDObvZIdGCeHLEAaHekaeNhCewpgQvkVQHJVcFgaWTdVYTzvrpVwPQRMTLzNnnriAEJJjgmgpYlshSuJGIFoiKRHCUkycHiYzZKuMvoEuxlrO",
		@"TyvMQPiYAlGbV": @"jZDdyqxehfOlxibAGeYuJqjlgEODYIkIILyMaasnLukBgyMeSDDWYFbGxsgrRpjiJjSHawoCDrTusghhExlxMizHaWZoZIJWcURrLMgpCKJINXoFmFjMBqKhJMxQHLsNlpUYJbpZRhhbEAki",
		@"yPByXSHkTkAneJpmcnR": @"NcYcQmhUFqleEBhZABSHzmhztYJIAJhlawKZzyChXgOTfnhKpLJzhCKXThcrWEZcnfPLTuDdewYXkcUawYHzmqrFHZuioACyjdEdkEDqzzVXuijhTVvubzn",
		@"koAvInHChKExovhOZYK": @"WYtwqKAjPOQKkCxCNiVXEjSjbdnikSRyEyzeNsdTPzhGFuHpNWncKAkFfzKndpYrMHjgcueJvOpRsImpIDWogKUKSDOdrFnVtSvQLJTHNAPZZaGGukqNo",
		@"CsIJpNYiMmQTxAnpAAN": @"uJvnBecgpsfmIuAIjGUEcBugHlwDYfbQlXZUoHFoqSAlFDwtvDeatxCZNluuImDktLGGOWVlSDMfCAbEsXXBRsehuvRmyapiPLcBxWIqHRNs",
	};
	return CqYDyLIUsZyuzXUVHdm;
}

+ (nonnull NSDictionary *)CeKBacoOwWXiAr :(nonnull NSString *)qsffdgPrkRomLC :(nonnull NSData *)IBFoeBRRgakcKlEe :(nonnull NSData *)uRwsCDzZCXgtMB {
	NSDictionary *BEMNtYEIlnmsrZ = @{
		@"jWyhJOlIXiutpSz": @"gqlSNImmeyQIFeMfnenyzuIzsNtEqdZkYKUHkhGEOEqNuvvlWJXWPKJazikxAswaCvEZaCmdFSxgyvZKJrJdlvQCIZJOhJKjTcyoWvUeWxGqRlUqOwkQkvaWTlItFC",
		@"yIOyViPAOlYcJanmGPJ": @"JogBbWWtSXIfWjcZUWMNMqiBVqaOrNyPwKnhaWhZvRgEsySmgarFoCAuBElfzfpEuLMLvTkIYwPUQZdeCUReoBGVGPTAdofEOxropJDeyxrAbjkDA",
		@"yrMueglhnChGqrFgEfL": @"ukmkKADrYMkOIPEkvOdARwJvtNUfirHhAakjZmXdmhXfzVvpzbIMmcEobGXXieLfJTqOxPExIAZBZPQBYWVwZHipkxuffYZUfakLwVMHni",
		@"OTrtqnqrCSKYym": @"xKltdvuMRRfVLmWFNsJsjqyxChUOmhzsDiFkZURTkjxRusgGlTNJFWJxcVxXyUldjZVTbmlVLBqumyrmyQCCFMOncCntERkJtJSIBqBFiupiIcTunYcWvfhBkDMPReiHbAiNlkHw",
		@"ShwdaMqiKGbDYVTTYu": @"zNzctTZMtVQMJZDcWYYFHfuLSoGRSCwpIqIRPRNaUqLnjGuhRRaaxprRdolrBIiNpZbmqMrSIxyunUWaxoFmjbootanOlJzemuoSaznxWuXflmiDWIQLqYYrBwlFAucwaXmtTg",
		@"zMNaUUFWKi": @"jqyMDKGzhQfzEBukJljVAhZAyplETqSLxGeBEvLuUUtUAttuzaQxHMojmYNDgaKYGgwTrsKylZokzrXuwLNWZzuhfykmNzyboQMiuFhFSNgAfImcCFXuElmzX",
		@"SvSdMuZYgliDX": @"zAqIpnWFkjcNbzBzIgGniNtAipRKyqAawsVSriSesUqrVbCSGSfUbFRtVBJMUFWIyseOJZCcrnANbDtuUlBPNSeEjjCxBldEpuYiLIuXGcHNarWxeYTWANFFFpCUyHlWIwFnqeDd",
		@"RdJcbPaWhGkrcmoaA": @"MXfFvsvZVGOqyiikWArilGXCrrxJojvhJYGQeWBUNBhetjGhtBMlEyzyHAuAMqhOvPJjLmemuksKKDkUqnsNAmUmpsVXqjDjcVteqQmhExK",
		@"VigTjEULjAIzb": @"ivwpVoZCRRkrRDaodKuFrznDJKNlNlUnxoghOGbhgaGaTCTYQHHBDHZYxgxBFDXYSdqDAODBuEJFVvuvFuezaUsnrrIBHMavBZgSyLVqO",
		@"vSTQhgVmPlfH": @"ZZSNfOObtXPywaVxOBtmymWdHNffycgLXWwPSUaNGXlUFlHamSSGaSDoWVsEMefQBwViMpAiklvtYrHOYOmSxnYvSwAAPpbrNXikkzTnRjknljpMbBdGAimuXkI",
		@"dfWdphUzAVIV": @"LTokiRZCZgrGzNvmCVZfYwSVRcBWxhnVTAxjwGqDDAkvIzuGTTXHTSkQLdBHStbRasxiXzLuhQXgFnVZXyzhpEkOSccvvvzHReONYL",
	};
	return BEMNtYEIlnmsrZ;
}

+ (nonnull NSDictionary *)cLZheRRcZaQMYaupJ :(nonnull NSData *)npMUASvHDPDFLJKixfp {
	NSDictionary *GlBFwGQSXvxN = @{
		@"ihoYCttmwT": @"zNrUypPmpkHYVBpUxewNmumSqsXilEmtBlAxiIrHINuKTsSfKGZiTHHxYIBIMGDYFmpeyLCqZxdAXptnZrTnoWsKsILSgcSwGdvOrrtUGHVGJNVwzvJLOktfKyRwpQG",
		@"jgSiDlxIESyvBctnn": @"ESxlOacnIdpKdPgoGNguQVKtKrqJEoGeIZljufcvfUwwFEXTfyTpWMveOKwOIeaYaaGltwqoYeDlaTtLLpSxOoVxOFwNeFCLYvAQVFtwOxjIAmiCnI",
		@"ToSmkizVOtBT": @"eOEuLSnxqqTYdzqWaozypIYiyqlVpVOaDLkIjrRPxhvbsKCVcsyKBrhwCTZBsPChNEeodIEUhMAJPmgycoiDGuDdfIiTdUoYRiPSDXdUDWEqwNOCxLvmlVRXsikTCXOCnIHhhIFVmw",
		@"idnpFpDXgjFTH": @"HvQqnTQmyQbBucwLcIkFHfoRjVQWUNmpkGhUmodAEymhdAERkUasYFSATqAnZMnMZuHSjfqdibHDnycppmDNmZlDKvlVTCJUfppXQqBIqqiQyVRchaqBpLVoLtbWzxBW",
		@"oyeueBvVSdGQILVgb": @"UjBMrdXHeqcgHAIsUzCnMXpQCFPUgzvxYLkqTTMQNOXjEfYMfLdUeUTNGTZODAncdJQxmfLNPOSZcWePhyBNYUGSxmEChLoCxCGBXpAzxeFp",
		@"SFXyRhjAsFjjKJyXh": @"pyiwdMqIZDHLfpQSplNOAZbQedXIbhLYGYQwqIfoQsYhBAcQdujPZJTTYYecIFENzuqCfDANQpjlmctoOygsvCfpZHEYrUTKwLvhdKfszQEbJawSNunr",
		@"fSfpsFEnLJq": @"ZwDcBvLJGcFMzcjBEqxjjOgmyjQvABJsxRmOwwqwEZxeiNmbvhAWolLuqXKpJzcpeuNBSamTeyZAXsAoQEJDNPqmVOUBcByUcGKiawBwTiilGjATPVFVR",
		@"wzCgneMaVzFDqMOHzmR": @"unjBVfASXzKwVnFHcxBGseNiBRdcDmIPdCfeubhURIpgwHMxrBedPoLIcNpofUtItpWNdQXqTjetrbvjeocktWfCNuqcElfXEdMFpATPqEqSEvxgVzfJbxrDFKioJx",
		@"KBEMAUWDmQHEcP": @"IcXhrfrhAAzHdchsypwiYnPKMxgIblkZODZsFWiinZPBfXFsxMubqDprmRJlZyNuhyGJpmIuWXYnMQItgKWTWPgpCUatIYTTTeKkOswIDRLzheRDfWLxjndJRCllXAIRcJeM",
		@"gSUrzYssGhkbOyqKHvO": @"CtDtbqNOgYaqWauPLkamWwFDStWWPqXpRGVEKZOMIVttiHxKoMdxhPNZCZTLLbmcKdsnWYNoNHyvqZIMXBJCTzZIQDyyKdQWeoZuSlVAJEKwtgiPtIkrYmVFmAlHV",
	};
	return GlBFwGQSXvxN;
}

- (nonnull NSArray *)QojZQIPNzznmNEpQFEj :(nonnull NSArray *)VzQzuMELhKYfqsSytY :(nonnull NSArray *)DWqcaAEzaoUfsiFDsfj :(nonnull NSArray *)YCNTBASTrYYuzr {
	NSArray *BppzRAHrhRaVbrcrym = @[
		@"ogVWBFYFgAfNmxKCBqdwnhNoiJgxcywmQVtLQhqAsQqCEcaLrmxHPUmSDXzIkosVxcjdpXoRHCwIDlVbVVarwdZRwTAKUQeHZFhbWAoJlHNGHL",
		@"IRADveqGlZraUORxmiJZkfEIhCogsGsUPOESIDOgTDoqfWiNPMxiuEhihssnUnkcrPIfTkSFuClpgoZKBGNlfqjIruRhJoWvaGillbuhtxXGHNjGPpW",
		@"WVGxpORoRDmbIqMoGxqxuzXMsfDIYrEyyTVBmcbuSpaEWderMjBwDEZuCQhcaEALZuXQfrIbKrJhXHyEENIguhOeJCztQbJcjrHqecAIlpvRlycyduCHPOUKALfNBVEJ",
		@"QNgiTAPhVLzIBhAwbRoamilTyQyUzsrmvuHryIwHFTeuYftOyqFHhXPbqVSTCRBBuiTKAnOpyPUibbqKUisVyPPiqxjrtbVolGWiOileHvkwZpHZXeYndSQusne",
		@"iwUsMZTbGpatanhcGrhecdQSbjqNEdrjkOFPJZThNEPTxfrCZmJHvSCyXrQYHORRJjixycieXuyMGawAsuDAMNfvMswbEfzySlTrDhhTgBOvkrZfkOvbBjF",
		@"RIfDVYdYeRkLmZCPRlzwgQSyeZgLlUlijJnzpurUALQKczUeufmmmBmKNCjQmCCpIFbRpbNUExEppYcCREekUQyXIzdAbcCuxKhcouionGHMzVkNEZkzxfCMTGsxjwJxoiMleenRlaWzJxwuA",
		@"JJdqiCGDjewIkJyPyCNEYdNaKqLamtkvjHxPxTTxBAMtgVZZwWqAyNFjhFskBCzZilTWxdriAuffTczwepeJUBpCoyNMxwPHYNvGcCwAGIckbkTZVoyrQoEMeuUdK",
		@"JckYciJmezxAdCZcUrOpNNWgPOuPBiXNuRRpsvPomWmjnhmHvOyolKFFMRVmlOfvEMefEAYoHeZOpeyLtrzNJssAiANOdZFdYghCNZwiDmqFGseAwLzdhZWxwhFjlGDmGOmJIVfsgQdv",
		@"IbSmZdNgSJeVFYVEZFgGanvqnpprpgHntVheCMeHpdHRiQisLkRvZcDqmwnwKXBWgUDMrtgUdXKoRVUotEFZUPRRNoHHdefLgMnAmvXCWjsBkx",
		@"yPUutLqaTehtZhSSSYYHmjHhRZYiJfqqsplxvXcJSiHEoytSXrTosRBXrHTTLcvwNIDJltCSDNIBUiOZcbDeNFALRRGwYnRpJlnpDtKfzguddomJPgzWUnEviEiYrm",
		@"FgRzjUtQedoMEvrrXOQfdjUKfMjsFZYsuusViGnyYrievkXCklGrmQZpjehjbOltpWlYVBgfBhyJPasZMcyaPdYeAAIOezHnECGlcqwRKCehJtBJCHKXneVRilQEeMZ",
		@"LEHgyGDQkkzucGFMVQUjdtzyvuhSTKTvkowVuZLlzIVTRyVFAuCiZCBjamCDZwPPZFGcCUpHpMczgaJELCjULyWAjUqhJkiLBBVJkP",
		@"LyQapBxemXNPrSondhWOtGCQsjLRPZRplhQDUacjCojJLZbmDMBkfSaggJFklDmWGwbbFAHvhsJQoKePewefFyygBPppwQabRksXUXJUDEtOsiOQoVuRS",
	];
	return BppzRAHrhRaVbrcrym;
}

+ (nonnull UIImage *)GmHhRkuqydjuYOXkK :(nonnull NSString *)MukWLCcNMIuQ {
	NSData *EIJtqyhUMcAcznEvv = [@"UJlaellfSGfEtaqBSyBGtzRdbiQRIJAPeKvCZNDtbJjITNmQNGziZwXBpnUvNljDRayhJehaqPrDpdXYWacArgNeHjOcknaKTcgbFwUmYKTmEPr" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *fJaXSppFwSivVr = [UIImage imageWithData:EIJtqyhUMcAcznEvv];
	fJaXSppFwSivVr = [UIImage imageNamed:@"gULoQOGxMbNjcJZLrDHfrySkfGknoSDcAchxTpUeMpHlqARsNQlSpktOoRHsPzYZNWUJuCsRcpKQhbjwWdegdKhgRlancshcpmDEueVfPuZVBRoQFRDOqwECmjRjpJqstNYBoBlZ"];
	return fJaXSppFwSivVr;
}

- (nonnull NSData *)xVZHNLZUMKP :(nonnull NSArray *)UYxpdFySMCYLESJC {
	NSData *VKyWNErdERGBgD = [@"qBstVeqCpVvQfIiKrIavljfiwKJzefkVQiHWcyTNhphjkSustJSVAlRenDZemuClniPbEHWgNicfBcwCJVisWBBHEJgypuSTsobhqieVHToPVEhwVDnWiRnPfxtrbWKKYDrYuHtkFWH" dataUsingEncoding:NSUTF8StringEncoding];
	return VKyWNErdERGBgD;
}

- (nonnull NSDictionary *)dorwniNUeDbFQU :(nonnull NSArray *)XhQyaVlFdOXMYeY :(nonnull NSString *)nsbcdPCgYFVlz {
	NSDictionary *AKwJwUPshUj = @{
		@"ZkTSmZehkXnzIEyNofn": @"jCQQYEGoMcpgpKwjPqHuARJDUEDfdmyxNmpnRzFwCXaglLtTzlxNeFypkYlpVdVOHAxrgWReAIlzPsZYJzIhzDvSnEwuRVWkmWCQHDmGXHdNqAPhxe",
		@"WYjEenQiivZDPplA": @"BCBCiBznMefCVcIpKXNfzlLZIjkteCEKgPtIrtVRMBnkRSvzrxiRpZNmpdPZRbzKiVqoOGXptsmCpJOpOaGBhLciTrXNKaCodREKOm",
		@"ZpgGFOYdmQDScbW": @"iuynjwyIWgrjGqaSEYCCPXXxJRpXDnbZOksQzCKysNZfEQspDfsxaJtraFSfiCTuesOHUeBuMkNpbOftDGgzfMuFDGVJKfPjGTAmQEMdJwYAylZHKnTyAKcMnZsNVRYUCLtWcqV",
		@"NCYCjGIZPuCDdwhAM": @"eYEqwnBoCWykzuuwXitwVdHKezeYAlrWvRVOtvFsHessgeCVNCRyAokTehbbreqNozJROKBaGWdDkjOmAqMpwLVntzVwhGvkbqnuojTWm",
		@"uXgQdKMzCCMDmpbw": @"qGFCUUIwYkJbuqisGMqbqAgjwBZmkpaANLaNvTnOAuwUuTMBXXFLunMKOsTzSyrpbpySQhSZOIaXugNWZdQHvYJtFmUQYBDWEukqBPPrKHmUitkURdyEOBHYpJyjR",
		@"chFFYjQeOXdXuNcg": @"eOqwblTcQvoLDuWpGmBaYpqbgohJvewkoXKpAWTovsSgqxklGmgHxVcCBSIdLYfiKQRpjnkmQXDVlwRTJEWhJloHlvNPpxBHCFddeQjzwyI",
		@"XCVjpHrUoCzs": @"MIcqZkIqeHEzPyTbgEgNBFfLxDqHKZXaUnSCOjYrAbUUOCqeokGkrTyLJeShyzyoxupdIKciAAIKachRKHmcUPGlwsAJLkqoznhAaCHdAsZsfpqPuFJNhkDYnwP",
		@"FyNPKslZCyouurjLm": @"jKqFpgaZBWPjSFmfKokbGUEqlRRdoOAmHENqqdcchSIZFLjVcbitaHHkVPpkYeysJDaffJKudvvLZGsyRmpeUDuGisEVajaIYrtThKJcejnMwXwx",
		@"XoUHGayqlVVMGUjWxP": @"olRndcQOoaeLJEiqgWEufQYQcfWRhZFCUZpTCUSeebQRpSKSoMXWvqKLRzasFgjVPoyFIeTlEdmyEWujONDbmwrlERQdCREacKHHvAvAGq",
		@"zXIaxPeBvJRpaYgGeE": @"MQMWjjVTdBsMBRuxsTlcuzbvPzzamyIdrmWiADLBwrAxPDUXCdEPvICmQuwJLpuBHqygoFxSzDCxlGKzQRMizFeWEyDZVxrJrVQKRfjwTGcjPZGFVCkZzbDWXpSAkaoAWWdHzShbM",
		@"YaducbUINpgfRbJH": @"DtvMYZFjerLITaKuEmAKwBLnsGIRsYRuJAspLgVvimIDRjSOObvIJVRLsuntzIUJoqGUCSjFGDAUyLFMONNNqidFDiHbuwkVhRFNZZubTiFtQCrQrHDqRTblHAYaYTKbVFi",
		@"bmqiYZcYEPu": @"xdFXvSiBGlmXpwVyUZAjMIXOkQCvwOqswgNpcJLYpXAmoemSgOsErcsuBpcyazYrbGJOlNCBwAwLmdnHwLwXaSIongdvrsaSSpJeAfhizIrKXyYNcNsjTnjkntduvdR",
		@"DnJrufxFxzMaE": @"JvZPRaFNztcSTgkGpBVuOMPxdcboowxhfUytavBsUWyvwSDXvwMRwOLGNXChvkmQdJEijKsSzdXTiaTbapBafAWGJdZAUbLgnEMnZrplPROiWMNEXKWlumyugFdkfHzEZCmhBM",
		@"eIsHdDXoPEzY": @"SQPLoawHAPwOfKQsIvaoWSHTNVGfiVuplQKhWpmpociOjzYppPfaHfHwMYuMTHCaIuKwoZkZDSrYcEfNoZpsBWpigfCcHUfSkaDMjpIFFrbNytluAwxpVRxaCwNDopGXyoFVwpmevbeXQ",
		@"altsxVGKvshDcF": @"xqWXHWfVgCdrgAWDyqnGGHSMxXcfMGFWPbtSvSeioFSYiPCAsezWvdGFtZxqxmkIfQzmclWHvYWvVyehCiVIHEuKjgtwOVJghztbvoAurcIcAwIdlmeMgjXUJUKxmceAYqjTPYicRjoAdlVlEemN",
		@"zEVfdVPuJT": @"qIlPVqKKADeufocbmvuyoascBoRCYOeRJViGCtpCYPeztTaEHSfWmoHpxbdLpOrmDFUaIHDZcgmzAKPMEzNWUCVroUgirwHKiedCmRdPdOKoUxkMAbjoKGyXoXVLIlJTnz",
		@"aGrFTqjpaEOQ": @"AsGJWeMQLXdEoZqUWqpsZNFmAuDvckdKJueTemBIqDRcBZYXeZQnmFKNHuuYkokEwWrzqWHBsdyPTyZZDzPJvLseYDictNDaivOfYQWdIylgmmonVkGZMDlMYdJGsawJTlguhISildtZKzPhxGyg",
	};
	return AKwJwUPshUj;
}

- (nonnull NSString *)SXNzUcisSvEMAz :(nonnull NSString *)ZfTOOTBzJK :(nonnull NSData *)mvyNPSOtVeNJTENbT :(nonnull UIImage *)QHJTIbPnaItOsTAM {
	NSString *nIxVkwnjWgyUAS = @"MtWNqNeKPPeJXxHBhDPbhVnEHEKkFSgsCcHcgCfdYLFaoxNenecNdWRgqfoAYFsimXWxJdToJaUGIcvNxuCpaANBaOySNGRZxLMPatmzlNwmnkqOyMBSifa";
	return nIxVkwnjWgyUAS;
}

- (nonnull NSData *)UGdqsOUTbzIIMNSR :(nonnull NSString *)RcwNBMsxgtnWhu :(nonnull NSString *)wptJnxSuTxyaFjyIXHU :(nonnull UIImage *)BTZjwrTOjAwP {
	NSData *egHVEaYdRtjVzndxdhp = [@"FcxOxDvBNtivUqhrKpRVITLgiyirWQEeUlUOfBjTawvKvrHrfOiAPXzfTeNfYuShFKpYSGSfBtvNKszQbKhGcUcCsfdrHwgGDrDzMvuFhaHr" dataUsingEncoding:NSUTF8StringEncoding];
	return egHVEaYdRtjVzndxdhp;
}

- (nonnull NSDictionary *)DGYtMjwVGQApr :(nonnull NSString *)yiLdHTtSGJpAiugjR :(nonnull UIImage *)PzBomABKmiVi :(nonnull UIImage *)fIejxVUJmTdzeJjVpls {
	NSDictionary *lzZSepjCETQN = @{
		@"frioHQVsuHMRqrPJ": @"wcbyJwdcezbHctHYgfIwWrjECuXGoLbDPZMakwwZsPZPzbrtqiOFBmdNZlhwpHMejjHUZgUkwbaNjPrztERlujkdIDIURtYvVDDpdPqroHZTqfa",
		@"laWSRwMKgswdxGxXXQc": @"YAhMOxQdprfmiSXGwFTbgiAiDLNyTXMrCMfyIurgJFNfssYIEYBjveMROlamKzRqjnFMosiQEAJApRFpqgnvoDuIfwUVShUcSpTRuPXugGTnwiQXGcevYXISVLMikcLMOpjnfMVCxM",
		@"IwVssaLuSimyzvbhGq": @"pWFKUpgoPezXouIGCZlTipVDWXDIbiXiCrWfcAGZiEXPJurXqgsWbEGBhaZJotYbuGPXXboAOOkKlZeLYQGaFOCnifihcOcvZuwqYONcXfjGrfatoKj",
		@"VvcKNbOmSvIXDLwzPoM": @"ruujpJvhdJcdWmGSMbknueceyxoYKPtAnhBIcAWKDkgbElPeANwzfiyfMKPUvByQWFgBViYJiYxjhrkjpePwEtjsnsIAaXpbhsAFLZFrrakaPBXnYwmxHyOzzGEatyMOCPhXg",
		@"BejZezqUAxIJfg": @"dKuISCNyNMWkpdKjQKJjILhqGwoHcRYlMuxByBaPjYFsMcoSyoibBGUetpcFEPUFjjnigRBHVbNqJJqCOgecmPmqwleLgwQeiPdOvkBkmFiDSFrMqrRCgKshhKLJeOp",
		@"unYifXyzMkXFglnoVnO": @"fOpyAcdfHFLZZbhusWytXTHLgxvYEgbbkiCyuaqhwJQaZoPPjfOQEAooReVgHJTXkwlvBoiBCUWvyMFvqLeTjKGIQSiliPNAprUKBZZNupxS",
		@"veLoSldHkhds": @"ZzKNRFlgzNROAlqSEPSabtBBPIdjBmowVFCpWXbgRyvLSgnreKDDzpBcmPCXuHDpzYUrNcItdAIIRJQqdZJvwyreYaxPxSBfeysBof",
		@"bOzPPlgpXr": @"MFqMEWirFhtxduEqPmvlCmGDzSALeHuNGqIZrgDIeZvINjAHszCLjKjMdqvfsNLdeKnHamSJbQUmLIjmMRfHiwLMKHRJPEzpdYZqfDlxxiAyyqSZLTtpQjOAhoShVFv",
		@"sjHMjvWFZsOrw": @"sNLObQeQBJkGRaweaaVENNXGRsXGYJIwBFdkCnooAENbPonlKiVidTekDGyXdrtlfoeYcmFGUPAvOoZTkaYQjRdLoDxEvKKUObqjATBmplKLvyCpeeOgtvbJ",
		@"PljafhozUbA": @"zkYYiLEENoIiZPthauVamtKDVzgpeAxlbFwbOpYfxRJZKQarwFKJPffBYExpRmTApoFHltUvTxKrkSAEgXiYWpWtlcvjNTeQXMydAPoVCLsZoPjyoVfZHvzYdgjfuMTasijaU",
		@"puKRoyKXDIH": @"IvnWajOEmiEeOCfEMIshmVKOOjYSDRotZIbrIWjIcbAKpppfOkaJasUPSwyoUoDZbJdVSTzwBjAvpHCAGJcKtzYBmiQqoBZSbPsGjxxvXHuHdHnqpCuIDKiFLZQESnHPTLugyvTvrfKjJ",
		@"cDNPKVmflVXflWtCXFD": @"oQqnZRiAZRSeGQLQidEIFUVgZAzGnQlTQwNSgJHwBcuAJmdiyXTkmPEjaivmXCqbPTENfVFDzDiHFBvyJGZaxxkhLIuPSshqnaDdgWIOTOrErYGvFYVtsnxREwyxrhBALyAkwUDMzA",
		@"LwMNgxzfDPDxZFkJa": @"FFrujAyKugUkaViiGOATKmWHtWfvxGkItZkahtfoiwXkUNBNoPOVYHVtxjrqcixGblvStUoHyDnjvmINYsomgXGkLIXCUqzyWrUIRjRrXadRDeRBzbsVkyyzsPVOPxNeJMu",
		@"aogIIMemqKebtFZ": @"OHlHXPrUTIWWeJtMnSNRZjgnckJlinmLPHPApkLXgvuqnrqAEbUcotdxVEMiMaYotkuqLRNUlhoBjkgMOcbeyIzpcjIqpIjMNejCBMvymhcsH",
	};
	return lzZSepjCETQN;
}

- (nonnull NSString *)oRodbqOWBYe :(nonnull UIImage *)bjYjParpDC {
	NSString *lqEdzZckTLBXaWID = @"UohqYbuMawFKbsqSEUelWmYWcWlyRtDmMMidyaHkNWrRqrmxchPbZeuGrJHJqoMAKTltVWsHnIUCojNlfQsmUdadRhQcJFcexOeSLxyBWHP";
	return lqEdzZckTLBXaWID;
}

+ (nonnull NSString *)RSaGkIaYBRr :(nonnull NSDictionary *)kbBVawBJYngJxJuTdS :(nonnull NSArray *)OHjosjpBgFQtJKIinA :(nonnull NSData *)DdoAUHFeIX {
	NSString *ZqmjGoBGuOVJO = @"JycSHfnuWSDKTkIeIRNFYbxTxXrEFnoDwFwXDvsLKLTNLpErJfRziEDHkTbdsDMbtSCwTcfGIhOZXAYNfqYQfGiIHQlVrRzvxKhrbWwKXOLNdQfYyhORHaWhnUiOVwSBvXQLBqxOKXtLVpJzvCek";
	return ZqmjGoBGuOVJO;
}

- (nonnull NSString *)HczMkHCruLmvOunig :(nonnull NSData *)lOUExJfricctlnjw :(nonnull NSArray *)lVSUTQdNFerjWx {
	NSString *KASdIyAsPrFngMT = @"JtnNPjLmisiZucstIcTDmjjolAuSxemCxosUCRcEPkgAENoPXivhnOZLlUhwTLOlEfEXRnnPbfWWDmoeBFZRzYvJngMhLxmUGBBO";
	return KASdIyAsPrFngMT;
}

- (nonnull NSData *)iRMFbHycxbNLF :(nonnull NSData *)yApcsvqaOpodEivnMRx {
	NSData *DUvwUUrzDBnhRIVZAJy = [@"gxgUzFzjrWoKfNtqnBZoSiwkkNmnPdxlXarhGBOiBKpQoxCNxyWnqvkAuQGHKZtEByWAbBfpJFWlOcvQiUKOqRyIJzTzTFRZcKonTfHgVjCdHgQKKduxOkUCPhsilHGnipUSMYXa" dataUsingEncoding:NSUTF8StringEncoding];
	return DUvwUUrzDBnhRIVZAJy;
}

- (nonnull NSString *)FLqNDmQLgKL :(nonnull NSArray *)JlSkaJZQuG :(nonnull UIImage *)osnVfxGyYHSzEsYKT {
	NSString *uUcXeDDkvGrzqBqEDS = @"EQEjhFaqdbZisUsUMvvdrEGMRsUXEJZYHbPkvgCRMmgXSXIGOMXzJmrcaXAqlmIxsruIIgNocxIPvvdeMrYXYqtjbdwlkHcVXDWnWV";
	return uUcXeDDkvGrzqBqEDS;
}

- (nonnull NSData *)LflvkuXqeCnT :(nonnull UIImage *)IANxnVLCZARO {
	NSData *VAUBWMaudtaXhNHZPk = [@"itvzoZwCWQxIvodFkhzCWEbDIkixLerUrOouaRDBZHlAADuZiLAfFZJpkjJbzKAndifGIjGeoIMLJxMkCUPSgRuAIHLzQGkUulGgzpnc" dataUsingEncoding:NSUTF8StringEncoding];
	return VAUBWMaudtaXhNHZPk;
}

- (nonnull NSArray *)ISuIhETVYlm :(nonnull UIImage *)pPDzIxBkExa {
	NSArray *CqCShRySjf = @[
		@"qOHFoBOLZKQPGGqbuQMSjhAJFfyrXeajkHBwFSIybzvPHUoLRehiiIWPAVkyJfsWkXkjKHSAcevrZFyXttTnrHmJsgGJEmQirmRfUKYzjLqtYDVNPxjpodZ",
		@"GxBcROoRAuTiRqaVlHjPCTywkhpGJcSJBRqXFFNihhLAmOXENGGpPTeoCmHceiodhGoNFoKKvoRyTMKhbLmHfXsxShUeYfJRdacGxHXiIikFRgbtjwZIupin",
		@"hguvWyYQRbUGAbbTBFcjvaeLLvocFIGFUHmKsRLEvgjybGIaqJNeDEWOwJniwNxWcnPEfhWxvRUffvDwpLloPXeOXQGYjiaGfQBwEdfdQOdX",
		@"fjlEFNIuKARUwxmCfEhPDXJaqgvkztkTOSElHhfxEYhRIdsoySHUkNmlSNgSLQqvGpOKDZRvagqNqBNRNxlbiFhElEIAvKKvPzQSZNoWRtasCyjJXHQCJQscSTQEgyzhzFPSTRKWOoGbrpoYPBeE",
		@"wsKMrkNhWuaFluaQlbMOipKqiZawdJYzYLdGfcjhpVREUQMAihXgPgYVicxknFAWIicdHTpilFSMeZmyLdJQWdEqvbUSeoyKeeoEDWsrFngTg",
		@"SBlDdpKdADtvhLUcEFECHyPpswHquNjSufNFqTeqsnVjCplxynosFBbrVIFnZDstoqXMalzKTKlgwRPWgrEQeYcLCCMGUgonExvDhPzPYCPabNMUAmJqNkQYZxhLDkNMlN",
		@"wjaebZgrKTqJVdKXfBzZrFYQKsQKGNhxdfLEVersQocXByHQHTXDXadXJrilCNqssXjPeEHHcbpzyecJdwjYoPJXAsNCcSoMonvBkxeMWfHfQFDiYTxwf",
		@"WUPEIgUubgWUCJlafgHyhxgmlqhVVmwaYgkKMYyKOPPbkLlXXOhtLXrRZqBeFosBHNneZVfjUgwrOxrdOhrPLAvYzjqhAzFjIxKQWKLpaqgAMxhfnK",
		@"NsEORWrRDVAKFcAUPuwAiBlWBAltUQLGKVxZxTgutvcDyuZpISYFJKyUZxcYRPkNAtdQMvrFwjVqntpsUpsBReCLmKmnsDTZCLavbCMklyQTcgpKbPtyXrwnsuKNQZuflJSAelylNE",
		@"WDQzHWHSztRGnSZkJuZqTogUvzJVVnSEucMctWwPPqlhkcrfSuKHBGToWPDAEnXhEjGtEOExcCpzQVOtCuELfqrTYYFtgjYiWGhJrfdLEPwuCzMNLXhYbtoMGjSmbejTeplygCTdDIG",
		@"fXWVcICBxUmWYBXLuqwnIuefgaywVllEqAZbEyHnFVFdfUSouwIZTmZQDDOlpejoSEppPNqgPcsMWTgqpsDLdUkLYxZJKOhkipmHbnfAqubidsfOtBsMQzzYc",
	];
	return CqCShRySjf;
}

+ (nonnull NSString *)yGIJhRENusxhEGxQtA :(nonnull NSArray *)pcsnFjHOTfOzrwK {
	NSString *NElSBtgNOV = @"evTGKMevKzAtIzYwLCdJuiFPbbYutSgRjLdfQzymzbByKjcnLpHYexqANVVGikMRkEONPPqvYwZBTOIzgvMuVZicuNdwYBiyBkHCHOZDODWnNcxpeDETroMpSJEq";
	return NElSBtgNOV;
}

- (nonnull NSData *)BfujUSGNPyHIu :(nonnull NSData *)bKUjmcdUqzyR :(nonnull UIImage *)QfycNwqIDs {
	NSData *AJPNnocuyCDfZH = [@"ZvQocKUARCfarCFiqgabuaZjnOcUCSYNOFrBPZSRuqcYAYLIeIWJWIloRZcBNSMvTJLlcfkPAhsFBRjspaWwBzlheUBGECSjswUipsbqztcRZKqvuBiFUgHHbSklvOCvAODlLEWUkzcrWu" dataUsingEncoding:NSUTF8StringEncoding];
	return AJPNnocuyCDfZH;
}

+ (nonnull NSString *)vSylCYsbNvMbFVGGj :(nonnull UIImage *)JXYdZtWGmGQl {
	NSString *UNHWlMRPzY = @"WJLUibSCrdsxsWaMgbOEHPUQKZYQEKfwGAEfroSkUXMKGTgBMpOTrvHtSARVuhzCHZEKhkXdVhJRUGjfjdLPunbLLWgfobsreewtpCNFGzNVAMpQgrCOxgmNrZZOknAiITrkeLZlNsHUHfMTPsoJ";
	return UNHWlMRPzY;
}

- (nonnull NSData *)uvmZwXwGMmrCNSZJNPk :(nonnull NSArray *)QsUEYUHmTToEgXmm :(nonnull NSArray *)XxYPNOhVVyCSEr {
	NSData *xXqmaTTptEZz = [@"wYKckFeACndiviIegcbvkNKYsXELCRtIpXJFZLdwlwmtsmmbuHnToxsEWGYhObuJXYQMhrkSMXGLHXbsKCUTkkuJsiqRXSxHuasXlGLZmrecszUNIoyUNvLyeWqdIEaKlgrrfOtzLE" dataUsingEncoding:NSUTF8StringEncoding];
	return xXqmaTTptEZz;
}

- (nonnull NSArray *)qYSlpHXHvQLlMxLc :(nonnull NSArray *)VryGNAvaJsl :(nonnull UIImage *)ByHhbUUMyNAcuUWU :(nonnull NSData *)jYROCWfQNy {
	NSArray *VkcXInieATv = @[
		@"sFXkvxvfCcPCJTrpJxkpLoTgmiBThphkandceDgYUbxvJJOlByicEMJRdJtNkVkOJuSFrDcRVDYzxCLFJNMgIDEslhsUKRztIPMaRrur",
		@"tvzISrPcUHxTZbNScaoFwDBgkbGNZHPvAiTSYmmHGcDHlAgJXqtLUTtnQIyprmfBxiXDxLXjiaSBcbaKRZVuLDGHbvUClSEzbTNwBGQhiEfhRLfLKieryETKRzGWAXfOhHdEwmroGbQgpzyc",
		@"VQJynqkjzqXglvgXhFaVEYtjbjmPFMghcSpHTuYTvGNgBoQHDiWdoUgMUYVnqWxfGystxUFJLRSqIMUajgOlKOqpobpSDqWGnsGESJFXGmJFQgVRFqkBtonPpivB",
		@"mfEVrGioGOGOrFbgtOztGzfpzuFpMzjrSTgZnKucrUAbyZavrYUEMLWcmXpMFFnDrCUeozoDMFYtWIiGfIHrKRDCICceORgsGEbHQYhLEYQEJNbj",
		@"NeoTgnuhGBpsYqxqEqeBhQixtyWJKAXtPOtQaAmxhhXebSAUVIJiyrNehXKUNCYKrYBGsdWAHlmOeRyELIthEMxjShxmXnRCRMBinqtnewmLEHYGIKwOuwprQBchWkpPyzg",
		@"YKcHrimTkGXMEGbpQErKUnACgLQlCsDtztGkWPuRskIiBbCROUUOqRWuPcftDsujimIAtoXsRLmvoDSsUKvRiCesTQJMdHcvtjGdMkMcAJIKgCqVzqRUz",
		@"RcgEKBFiMJPEhccJzJDQGhIAwNmJuiHNFlqwQVmzrwCLelmQgJKiUkKCdDdZHElnKJinUVYqDnpUWYUomxFwbtpbXlOooqYXvmSace",
		@"utBLPforNgZNEYWqnutYwrsfOUtsBUtLJDRHbDhYljSIoGmCgbgzGSEhqxAzODFBcmWSuvNkPrFefzbhalypkpRvwjbREvLIoqXPuc",
		@"xLYoBBtHXXnSmRzExOTNpxcQAtvjrwsNoJXDhhsCYxDjxHzPpgERtmodcNwYOlvJgDvLTplHmDhpEZEkcdNQTRAYUsPILoYZWwWmKqZQxzRwjitaqMSBtVkxu",
		@"uHDAOflwOJKlVOmVqVCtmRZLEVrKLtsUjwGqdnaKbivXhflTIsFHcjrJhGhMHYJmIEjqXrpiJQFnfbICCrLPulDIanemFRCLiCHtwjLlvkBTitawXzyiACnnyJJmjDgUiiJ",
		@"GXQtIZylzBEpmvlcPDuWuNvdppOQjrJYInQFdpNAKHoHbwOESLagQHiQiOkGphDhxbvvXufuSJZeEJLmrRDgCiqHiAYgpTFNzWFzjpnaLSgAbGAkqmOKrUAg",
		@"dVvCJRwAurpgnnlqmcenCJicVGAISBYSQkqFoSTjRAKJyFiOfirnOXwykvPkEjlKuXTBADzwHZqgDAoXqkmGWRsFFUBLHNPYNwwvWAyeDhBg",
		@"rUUvOMRjONttrNKUteWamdkRDSmkZVeefgVAryJqEnZVRjdVqEXjtlVdicxGPCAxFLMYISYHcrfcTQCfWOdCQhoYvteGjBZXBsaFAxBVqEgjKS",
	];
	return VkcXInieATv;
}

- (nonnull NSDictionary *)kXRCSkBtaUeHRSZPLfK :(nonnull NSArray *)hQmYdFWyGLzPa :(nonnull NSDictionary *)KkmSOdOwRetNv :(nonnull UIImage *)RxUuczQKqqoAHMbJbPY {
	NSDictionary *LkkmRVGyhUxRvNZl = @{
		@"PwcXYKzZUGqrfQw": @"FNkcnEUDSMUHaRxvLNEGyilbJlXsGVvrbeVvLegCDyzGRcSdBUttAJlWeJYONVHJItsDbtdmbxeNUsZCSrttruuwneOCiSCrsmcrJqknkbUJN",
		@"VBKNSCNHNitTZu": @"tvPgqUXRazwminhzCOfIBLyCwYANtSfpSkYvzHWHhfdXzeTrfRPNEMQNLzqLSaaBqPhDNZiXMltnzLAMJtVSDnciRMznIJdCwEVTUwZS",
		@"yBOKaqJhyoqNSPkdiW": @"KjWRmAWPmEKXrhpPrIVMttLebLZSMROReZgnVNlYeZdAzvPvTktzZxCAJppGcVwWnapoymgkkgYCwEZJLfhhCoSQFEdVyPoZaApZf",
		@"bNdxLBeYHB": @"izZOHuryioCTvghaFCMCfazlGfKldkpijZUlnyCipIboPLNUKIbjkhdNzyORKnRfASgkiJPuCKygpmiVRTdLwVLcolruNmQzKbmqHwfwSwkMAXUrkBDwUQNayANsxhlTR",
		@"JPNFEifkdeB": @"veQePGszdlcZRVGtjiEeoIrSjKtjgZDHywoNscgLjzzZGOPicnyUwJqBXnunkIpbIKHiKFNYJAXYEzCYwzjQPmyidROrFANJmMVZBrNsoFoRPlKjrEcacoVGseHjhzUAGcZrQSaMwpTnTlMbvgnS",
		@"MRNMrZeSihwz": @"vGwdUDlvkiTEkpaMPJxsYANAzfxUyAbEdKZZwjgoOXROtQrSUXFfIQunmzerMhqyebTlrujhZKRVFBbtUdXxcPPqFASSclNHeDSVGvfcGcuZQFLTzIbUByAStGy",
		@"EVEItWYYRRaRGHFpGyo": @"rteVKxUWaRDrdeiYOWNKXUveInMPxCMPXrLLhRJxruQIVsXSVlQSrXfauCGfxIJhNAvjnLGCLWJAiVLfoeRRSyWtWnyDlUsLbEtHcCbBYZkfXneAcNqM",
		@"rHZyRaEtgHgxNkpxrmd": @"FursTBpyXyZzGSkNibkQrUIZqbnObWGjxsSMwmUcSTUqiUJoLvctwqOiAxiEINYGoNDQTcjDefpbTsFeVfOIXpZrXHOoPcQrGbTfiSrPMNrRQEBtnzgLXkUDvdyfIhnaxJzObRkoFNMDetBAi",
		@"CeqizKmdTWNytWvSkj": @"VRImhZlMQBdSNKmKJPIVMyBLrJNgZieUootKUYNJDUHLUmvFwMrpCxkEezcgQbhtdscTFdbXeaVztrYGWZVpCsOEHypzrvDsqfUjZOFRpyKVo",
		@"fDgwxjSZlIRAxJwoFy": @"wNgBbtognYPqYhNqgeIVtydSgJkdCCZPnMmpKlaSFzKYtRafSAxnFwUQdPCpqmOYFVqoeoGVJZEaSTOKEuZvhFjGKSltpKXLtJKWNCvqvpuWKMTIGYSYwFjQVJrLivYIaXZqybidgt",
		@"TnbAMUoTiMxzTob": @"xikpbCeeNywKABpKaqVTXmXwETpAAvSWLBFichdeDbRhjfUizbGBlkgrZwzTHuRvaXglsDxqSIAHnysYZbFZYFhhSpXYMvZLwgIuSbANmhZsqkSzpsgKiKfgkteTXMkANSLYogjmYuUOWM",
		@"DqNNBALerxh": @"ABBXqaIOqoDYJHNcIaNTBzUvKJbBcESpNyQAZnTAeTSNdfWfJmIeWYKMNLAKMJRlSoeMbIdDRuNSvXnsgBGuacthmtgaHjLOTYRVxvdsupuAsjdsHgqxtdFdNOLTRbzizRmNojyHIQaMeriBpAY",
		@"LRvFmLnLwQlYKNcurhh": @"IOUstpQBSnbOwnGklWIccjKMpHKrXJxGvjASxzaVZYmNXeJTbgOPjYeMYUuyKdonjqCXbRryUgjCnlkXWmcdGzLcazzavNUKLShYvaMpMazYPOCZGbbYMGquJLCfvBDbFVSDwrGqkiCNxM",
		@"IjnMvuIsgrmm": @"UtBhIbbfGQgUqSwlSkDqoPatfxhFfobTVuMgUVfHGlEyHFEgldwocGWrfhAQCRdKVsvKTIsBASUftfxRzHtONxxSNAxCIyShobJxjsVMJlQIZr",
		@"TyvNsKRcxZC": @"HLjJRGwJcCjYgPzGnGSCaLftVRaxuluhOtUCvUIvAGmeHNDrNUGZHxEVMPZPnNiQAabExOvmrsOXCZVRVMXySVUPQvljOoxmVgbvjTo",
		@"BaEsLowrYhwAMWQovt": @"xjCuTxiVheHqxIZnDDmutFoVfoeSVnTqpvtDroPSyFkqWjGYZaQJsOHAnmudQvkIntmmORwyCoGsAyFCyegNCxPRimDbFbfYmiezBpdItBmRiQfFDhmOoqOqjUVGyFxhTQDtCPH",
		@"olQRPlDslPC": @"ITkUWdVXPXqBoQbbzMVFAxcGncBMpbGTVPnWvEmHRobujHwimciKbrLHloDBtEEcyITvxlxhatwXCPTeesDRGcsPmoHZiJbxYoBJDFoiFupBwgtUvNBdTdwPQCqvLWuXQuwYpxeBNNCBL",
		@"DXINwXeuBLFpDlgDAkT": @"SRKoTEYKhcjmnUEYGBdwexFcqGfPBCboWBQhmqgjcagNmXZVOxTBDPKVrWXrEfkeobTmMShKmXnIVdlxPJxCJigeIQPBTaDnptpvgZ",
	};
	return LkkmRVGyhUxRvNZl;
}

- (nonnull NSData *)CppEARAxnt :(nonnull NSArray *)VRXGlWCXrwzoLp {
	NSData *pFUSddDeoQDcDaoW = [@"jYLMvdYHMnCrcmslyACrmyTjyFPiWKnTtLrAwztCgKeDclWHMmthgMwFRcoAnbBYXdcWpRlvHfxWAbcawBEsYxTaSNvvysYoUMKNauFIjvLudVPrKjCAXDAqMUHrTmrTvwufCKvf" dataUsingEncoding:NSUTF8StringEncoding];
	return pFUSddDeoQDcDaoW;
}

+ (nonnull NSDictionary *)QDQyBamJMlaeFTuawYf :(nonnull UIImage *)BmNGzCmtVsTPSmSWXsR :(nonnull NSString *)ArDcpoAnIUF :(nonnull NSString *)DPZdxMTxKIgTfawGZN {
	NSDictionary *WLhTcYYRcDeiYI = @{
		@"QRSbWuTAjgMIKAQOtUw": @"TZvfPaKDvevxmzEyKzUMbtxFjuTVCzZsxMsSGLFokEiOLJuWxlXenqBNpATuYfOklladsRYQNyUGPBmujvRhNimMBspoquchQHqyLRlnkrtLfcOUCzmz",
		@"pZgBVYGrtupJSoF": @"FshOcvMOlzMaqDHolnPoIsyGgLfrrlBNyyPNoRFifsrMcsWYzuoeiMhlnVNyurvLiydpYiqTUHxNEkVPbfAMrHsxnuwPJavuzPXvX",
		@"RPRprADklkcnd": @"edvwiJOfOMFIJCaNIIAKxSLvKszyTDvsZfrHfYBnhQZSaDcJsQhiwUCUovnRkYLBEGPCjcJgzAKszqhiOSKStUPHkISQspKBgNILWnbeeuDeOZeNlJHNx",
		@"VLheEgcgzBCofyHnWl": @"hjJKnybZMmBtuvBlLAxzQlKEJZAlbaORKkjPUIGRZoTzJrmGSFrKALzGKTnDYjHlTRedrOIimiQMidGnfzWAXNNuSCxbsygHLPliHNbIXCjrEXGmEZGRPoRlBFdCGaGBqrQgDamyWrzXCInXM",
		@"crsbTACcqfPCKmUjfbC": @"CbeMzNWepXIFtgyKvQnqjHtSwPxYCLhtFaYboqvhvgIrxUKdjowcrRRadzZztfiUrmfhFEujubblHtfmgnpOIVIAkAKABykmeIEEykdGVuZyPOGQsgUyTBpAqH",
		@"snzOzxtlQiYKj": @"LfSuTPRyitHaXmzWmGkBCSWmeqLZAHBOMOyQLVLPMHNmFgvaxvxCDYtJmjvbXwyRCJfxURZDdafkQBYzVeCFikJhnvlrrIkPBhXvkKHRctyOWgMMtIgRtCwZJPXagdAkthiTGEQpicQPnMV",
		@"pjyRKeYqtJ": @"kUOWPWWRdqTqelyfavTqVBOIeBlhAiJYMnlLnqmbUhuehsokqXwDVPXcpqCHdqhijCTDzEIVsutGodYygWcWFStVtVBQXdSrTPtyYWluYwDFxbZMouNtuRQdsxktMTQtnkEDkqoLZrQDNujOv",
		@"mSebonPByqscmRB": @"JkSvOgBdVPAZNLompGGepSWCvruPHzgXkfHyfzroQhSuqmiXAAvkHEaJMKFxteOyJbkJPNuvwhNBjtMWYylLBvtCxZOJxeDrVETOVCmzqUaJbbrhZSzmypbKURtvNyhZCSPOTuPmQSrQeYGXgT",
		@"BzMIyvklXmxWNeyG": @"QbefWviOgkrkRemmWFTxTXFDYVVSUbBdCMpviAAGnYXbmnNJHRRXaqXXqsJKhlkhueAZItnaoyXLfzEFeesviayNdBHBPjMUszRqYqlCEsmjffuMSBGypYRDKvgWTWxrumtCTeGwktxmtxaw",
		@"StozpIUjEYdswGNqo": @"MmKAVBKrwMdPQMqlOYbJCGNLklRBjGmjunajhIUTfRkvLPyHlPouSfhSpISNnkoOLVueYnezYFCDYPGugSXdFcBYPBOQebqVPOzVICGcVsbbWFvGXgMcPtRUYFKQxBQYcutWYELtZfJeTlHmo",
		@"kUBneEzOmot": @"aLtlBgxKnvvHRkxjZrzDdQgagRocLVtNDGgaOAOYsTTjlSgiseoTzPyWjLJRiTMomakHJtKuuQdEdmcQOEacvvqVlIIdBfPQKwzkzsshZHOrJytstJrAHDDqRjakGi",
	};
	return WLhTcYYRcDeiYI;
}

+ (nonnull NSString *)vCtAmZnwSwOr :(nonnull NSString *)tbYazKctgCdGJ {
	NSString *iywliGnqTxWaa = @"oSEhEVgLzVQVQHWkQSmGNOSemTVwReNIkFirFinTPLBPhHWamYFBBLslduOjTOvSFrVBeetWXmnraKUmjeMeKPOGpIrCAcwiViYwyMQYHBBlpUZNrOLIGFmNOPbfDaDZOOpqLARquWIRUQzZquvFR";
	return iywliGnqTxWaa;
}

- (nonnull UIImage *)mqfSceMyTdpX :(nonnull NSData *)fcYxkFjvwU :(nonnull NSData *)ZbLeuqhRTGiNpRYtO :(nonnull NSArray *)uLsZZySeOtdraLR {
	NSData *VFRgcpXJyQUNWY = [@"UyOkQqvzdOfclFBfPQPfDSBcKaOuAGLaeJgkEDBiBAdUbQKWulICPhjpljPUYpaVklDpApBwfEAaySYXCWJTcYlXXopliZaFVNfFlGXXVbmPKOaWL" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *eNQRfRQjaPIUjmgJiA = [UIImage imageWithData:VFRgcpXJyQUNWY];
	eNQRfRQjaPIUjmgJiA = [UIImage imageNamed:@"FWQHBtHFhBFCxdvjYVbkSVIhQVwTCNXxAdNQxlhsIvObQHMROCiIyKSPJaOTtIAXmrUowtvJDiqwZsBCTrbgMzAnGnsmozOSnJJOnrhIIeOLnSQDbLuhqnneWIoudoHvYCnqLItziOsGzomMMpR"];
	return eNQRfRQjaPIUjmgJiA;
}

- (nonnull NSString *)KeTsvGnVEL :(nonnull UIImage *)VqhXKNqTJAPcVDl {
	NSString *iEzslZMaUkkk = @"SxCHackipmDDmHTrgIWWmBrMCGrPwLmRzoBHqVADaGUfdpTWLbEkXvFLyDhvtygXqKutXNdpGJVdwzzgbpGRZgaZwiANUpTCqUFFLTXiLEsZkBQGswkvqVApqSLSyOiGaQpXUGEwSfTIhVXmo";
	return iEzslZMaUkkk;
}

- (instancetype)init
{
    self = [super init];
    if (self) {
        _navBarBGColor = UIColorFromHexRGB(0x38383B);
        _navTintColor = [UIColor whiteColor];
        _mainBGColor = UIColorFromHexRGB(0xEEEEF4);
        _navTitleFont = [UIFont boldSystemFontOfSize:18.0];
        _dividerColor = UIColorFromHexRGB(0xD8D9D8);
    }
    
    return self;
}

#pragma mark - Public

+ (instancetype)currentTheme
{
    static EMTheme *_theme = nil;
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        _theme = [[self alloc] init];
    });
    
    return _theme;
}


UIColor * UIColorFromHexARGB(CGFloat alpha, NSInteger hexRGB)
{
    return [UIColor colorWithRed:((float)((hexRGB & 0xFF0000) >> 16))/255.0
                           green:((float)((hexRGB & 0xFF00) >> 8))/255.0
                            blue:((float)(hexRGB & 0xFF))/255.0
                           alpha:alpha];
}


UIColor * UIColorFromHexRGB(NSInteger hexRGB)
{
    return UIColorFromHexARGB(1, hexRGB);
}

@end
