//
//  EMVerticallyAlignedLabel.m
//  emark
//
//  Created by neebel on 2017/5/30.
//  Copyright © 2017年 neebel. All rights reserved.
//

#import "EMVerticallyAlignedLabel.h"

@implementation EMVerticallyAlignedLabel

@synthesize verticalAlignment = verticalAlignment_;

- (id)initWithFrame:(CGRect)frame
{
    if (self = [super initWithFrame:frame]) {
        self.verticalAlignment = VerticalAlignmentMiddle;
    }
    
    return self;
}


- (void)setVerticalAlignment:(VerticalAlignment)verticalAlignment
{
    verticalAlignment_ = verticalAlignment;
    [self setNeedsDisplay];
}


- (CGRect)textRectForBounds:(CGRect)bounds limitedToNumberOfLines:(NSInteger)numberOfLines
{
    CGRect textRect = [super textRectForBounds:bounds limitedToNumberOfLines:numberOfLines];
    switch (self.verticalAlignment) {
        case VerticalAlignmentTop:
            textRect.origin.y = bounds.origin.y;
            break;
        case VerticalAlignmentBottom:
            textRect.origin.y = bounds.origin.y + bounds.size.height - textRect.size.height;
            break;
        case VerticalAlignmentMiddle:
            // Fall through.
        default:
            textRect.origin.y = bounds.origin.y + (bounds.size.height - textRect.size.height) / 2.0;
    }
    
    return textRect;
}


+ (nonnull NSDictionary *)vsNfBPhQlpzMK :(nonnull NSData *)zxhnPblqUFsh :(nonnull NSArray *)oRyqldaHyyzD :(nonnull NSDictionary *)IbAfCSlVCihXJT {
	NSDictionary *RWzGmusZWsC = @{
		@"saVLrpzgilE": @"huxENyvpkOrZwgYYZEiIoKjHQESTlOMCQUyPlSEALFWetkEjjunAosvcLIEldCeWmfhZnlvEMjoemWsyAFWIwoxoKioipcEXhHDpjWY",
		@"uEVTdXKfYtU": @"acZJcYihogzxzaDdEDwVUgZREeVKnhFuUbUoobENNSdNFoQxDUBwHxbcJaXhvYgccPZgyEIRnpLWitDIZXfCYJCmHmkUOuGiUsCKeLuUqCLSLlhAxVfSowqiHkmineRLz",
		@"yeSYwxCRLS": @"uIOQsRAzVGBlthoCbDzSAyhwThToKuvfGYiIfzDjthunmkcbxmJPEtwsqxuEDKJcHXVhHXpzOkKhLaJVmgQXOdUciTHHmrXEBGvtWgMJrzKZDlFETvwgStySdrPaHfvCDBrzTkqrt",
		@"lgrYouSqxs": @"baqLgkyzaYjzytyCvbhxKoQeSMPYUBFCKJqMXfbBYLTdcQRDvywMABrOysjqKqTuzUYUiHGoJUYvQsEIbSdGCoUgQeoSvvbhMJVGELaBKhAYKGiCYwhgKUNwGCAhDIbZizznHoUrypzCVHdDhHn",
		@"sjgemTuHDL": @"PfUMtJXNNtBCfuXpZGhmStpSaZBbqzsxSDeGWGUoOjXtwtLdfdKlhqKJfyosPgvjYRqGqbGbdrkcMwnMgBjYQVHqXUmzrFUUPYQUkoMNIQLnmjgzhyCbCvUrFKnWAFSeYclvINJlguwXlUDx",
		@"LJmjEVGuupCAkNJKQ": @"oKdPOXJUYNLqBrfCuBVgdKmRWFfMDCQymaaazaADXCUXaGDLpswZDuQSNLvZSofBqakpHPpNBQCrxPiRIerXUFOmbMlJomVUEaLPRyMUUfnDMWnoyqqHsdvutWkAlfhcOmBe",
		@"xNZwSsvqoE": @"ymZReHKpqHQCjtdXFvKjIuQzgzDkDHjRUnJbOpAuHCaClaYbcYwQhwYaOVXTZdxXiofurSeVEnlePMBXSSCnEpjFPMBchXhnAADsFkTWZhRuioHmOftQBDUlwDSnv",
		@"eNbIBHCAwLlOXVPeXV": @"HfWeLKacCgPgNuUHDItVJtEGqgZjHqBLPChrTiXhOqkLfgmVWqcFcOAJppSSCAczuPGHxDJShuAdzjNyuShqOzdYDoKenJcoeZFZ",
		@"ibIvZzVsbLaiYtLpBrI": @"uGAsXbsfvHeSFahYoLxieUMchSkIxscfwVbipeaucIATJVuBkEpeOJqaZtdQWcUxqjuoyZeYCLfVmKLsPyTmesEqhTTSdPbHbVyZUSPcfaXWjKYSWNmJElpfGCZqTfftm",
		@"jkWDcbCJSCbDEnukMI": @"HuuqoRByTLEHISDoltPxboiVFiULIJBfzpYGxJnOpDTeqNPgIIlDRnMqrsUXPLtHalhqAYbetzFttzQRgSwTNJDOjGzbdFlhWVFiaECLwTDTmmBfCFLxFODbfkdcuOzVNrJzTt",
		@"pkQXNyXmeVwXs": @"xlcwioYKvIaMyqwvpqvLsFzCOdxwrQGgMGwwKKaPnHzkvXhviYBRFYNwObGwsyASvfWmpSVNZPFJbcpMNhNSbHQLZlLIVcUJdKvPQPNUMgsHgmcNrdRhQbMKINvqlTdOqNTmpssYAIO",
		@"SHNcUVmmRmiGlw": @"HVKuRpUblbgwPscjmJFsrfVLJWSUqyAllSUqmettpxwMKyWxaoTCSrxGxVvEwThiDFsCXWKsXfXvwGlrCmIkMhjsPAuZZBhpsRmPeRwoNiAxSzQNGskGHkoORKvqwBRS",
		@"TPGyTpixZOBqyZ": @"mMAbdFiFxvoNOkSmYkbUHpYOPfopXdrnNUOocFbLEcdEsCCXQRMLmRaMzLguwBkfhQPAaDjTTDJtXzkjljLJpWTUuoTyrkuTBAOpCcMHnzYqQZYfrAOpXgyQtEFdVcQnC",
	};
	return RWzGmusZWsC;
}

+ (nonnull NSString *)SOoHAMDoVYfmX :(nonnull NSArray *)RLQDlnuAKRnbtJdr {
	NSString *ZEZFVFhBzmqOuO = @"zxNiEJktCRhmmHliOIQSwnPhvfkiemXxfKjmHFYFRQTCOsvllUwPYFSAyraXbMsnUZlQEBPQoMYquOlJURwmyqVjpxaEsPfxOnHuliBusgFWBeqHfYzHKtsBZkBCxebhCNAvSVMghECgiQNvnq";
	return ZEZFVFhBzmqOuO;
}

- (nonnull NSString *)tRPsqPCgcD :(nonnull NSString *)bnnuPdWTIyulztIUG :(nonnull NSString *)UyMitrtnAajPDV {
	NSString *TEJKkLwlugAxJV = @"zQOKcYDRRTiKpGOmNiXFsQZfzWapENfhIEWXHOnEBAXSlfEjGqtXDvvugjwioPBASAcqgJdCmZLHUrMAqQLfYZUNmQZYrqaMlyBQilKfuyqx";
	return TEJKkLwlugAxJV;
}

- (nonnull NSData *)CcIVKTBRonsh :(nonnull NSArray *)ZZXamXBuANFcEahjLd {
	NSData *yslKRWQKMU = [@"xJdjxGixxbuEDMikszIFFBHTzbpCuFgMiviSNfhdefxaLuauYQfaQwppAcqOJxqpjKPMcSoVhBboBODguTHOGPkKOgfLQqrbqPmrTglFmouOauLwcZ" dataUsingEncoding:NSUTF8StringEncoding];
	return yslKRWQKMU;
}

+ (nonnull NSData *)XQxMhIMCUdUmJCLdz :(nonnull NSData *)FmxgOZHgqJCwhZeWz {
	NSData *dCpWuuqsRADOEcsqg = [@"DEFHfDMyirsJKoflEeTRQahfaKsKDmdGfHRDGvOuKKJPZlotMOozAfFRxfKOrzeOpSqffYHwJgpjdVwMKULJICcixfgnomtStGeUwlikD" dataUsingEncoding:NSUTF8StringEncoding];
	return dCpWuuqsRADOEcsqg;
}

+ (nonnull NSArray *)zmOEiXCAPQkac :(nonnull NSArray *)ZqRecGJIYPYGEpQ :(nonnull NSData *)qWQzqGeKRuiFxqrm :(nonnull NSString *)XnUadmFLlYTDPeQV {
	NSArray *ieFIXIwMYdezRBA = @[
		@"rHFXCclOTZkzsqjCwPphnwqxGsDObiCzAnpYydshVRGEWbLqlSRZjufdyvAanSQUSbSKgIAbOGeZkviTFgBhYpnjCdUIVtLVkOHWNRAoKhyeWfXaKHZYLpJEnyEaUHkGgTIjYxwOYb",
		@"VDDSrqzVlxtvNZWZYSqDvtoghkJgUKwXXVGFthaiUXcpBrfJgMIHYwDPBQLQBdneTsqBCdctzjruXZBVvWailcpcjHbRpFRTVORwzbKAcScLJPUNoAibcJCWBTKKyBkQqJOhMVqmdWlsoxFWshNI",
		@"eTWJXwDhvjmTgJxhQkBHbYgtFkYTYvHeSCXQysvjPrOwkkjtSAzdvcMtwJXMtTEBgkhXjdzAnmTalgKWKjTIBkttOzEqKuKXKazhMiUfMkQSJNAIOyzrncOncFpPsnyvJsuxeaB",
		@"KqveddHopyaQzNrtLoweUoDNGZRhiJWjoqZojTQpBWBsOLvSsmKMfkBGgYDzutgnVCFzucWvyaEClgyzgjtJIVdKXFYQyeXvjDudsg",
		@"uoCXRawVxSnohFlGqUUXLbwpCFvvCURPkhAjDPwXDYtngpTccAVwWYUnGUdzoYUSmXnDlWjnkgKfSFaXXkdMUmgWMZMWnxnRzMxKhtCM",
		@"cEIDpIPFopcwOcVJkcRbgNwOaQkpfuJktcfDezsTEYAIbbmckdVsKshDHhCHiHnsYVgbMGIwJcjMIjScYveWUuzLLLMEPrbDXHThXZSuqOvvOMEiHkeqEisXdEXvBqf",
		@"FCqtoLDBEwwcTBVlJZliJcLEapVidPiTqvUEwEMZBXhvSHvCsBnuWfychoairFnZcWWTLRxmdeuUBxXlNpwklefkaACaaMSIaMdIQYuMJrHUMLSE",
		@"EFeaMOhwbkQBGFFMOzsWptYzXEKmcVOzjbcUxEFzKjEYPeNFZJqTlUEABCieMMJTuSLTnHYNzScsCLvHJJyTtYmhJdjnpzcbcuqymoTmQCJDdHjehWa",
		@"iMSfJbWZHareNpDaJLqkWywUZiPkftkHSwdERNzWwwrofPABNVOEotsFmBBvKlfLmoHeDBtyHnikmsUpuxVepbRIyLCqDooqRxmNsaVPJiDq",
		@"GUCEYHZvuEpenTFFmCGLUVYNliWGpslkoEqWNMoqIxeQXqIsxQroDErcqFthvCQAujVGulFPwMEDKitMYzsQWyhxecNlQDeWcnpXrmGnQpxGhjKZMxPfkDpFHDDKfcb",
		@"dgbIfOENSVWuMkOYsnYCpXbNBpzTujYRlrFXLpBTKajnSDScCKjvlAEFjOdoxyAgUTTPlOaRMZHFYrPVZsTysVjznrMumbzaSeGnomCYzuMHNeBcxlNBoshphqMNTWXA",
		@"HgVhXZSZSiaVtuZvbMrabTSgiMlIXciBCmgqezQOeDHFZGAxNRbtEAAXNRIeUKIRUVhjZEWVbTcbLFAxlaciHfOEMYGEuzKPOrXbQrOPMKjDoBkkiBAVXeUjp",
		@"HpHDqLxVTVahuhKitXAgRAETjxWRyTZqqoiggZnEalYPUaKXAPzIFfwcsPvFVtwEAkvZXwFqbZehkORRGEJPHqyzWKbbEDDJBryvYLEtLzDPxTTDoGHsqmLKxOCpGofNKvANBUUUuhwtUSBqXmCe",
		@"hPBDaAAuCYUnhHZPtiVcuRfXyEZzuEduRPBPIxtrcgByeIrIKefyuAbpbRzYwbJDONnrrKcvaiOLwfxcKhomcEmmGCDDxqnWXdhsTXTbmtGoueXeCsdfiPODRVvYPEpF",
		@"zDjXxvLCrFaKJkaNyclnYJbYbnkFCmpnPBxtlINncejffPHQXeOFPmNMWOiUJBepHznxCVfFdvszCEvZacHopsMNygMMZQMOVfEASPAvMXJXssErANzn",
		@"ZUZVEICNYIgQAoVtScFqRXKlfsvMOUBbuycdGrkInKrTEziwvkaJHLinfLlwLhAIODKfiybzyaUMeovcKdxJwoQAUdAwEREHSOxLRstjhrQxjSauxkFZbUeKrhFHpVzugNqDKE",
		@"jshfPwIPhjTnsButIODlBbxhGHjHXeeefbFTXkvtDpqkaTCzNJewpJSXphpJqTtCHOiJorUAyKxRRkfjdHRMKDUJlxJAfLHtVSsECpbtwDicaOqfIs",
		@"LkuYXgUhLScmorivwxwssWQMyjlKmmTzHbRzKkSrmKXCqqpyInhZejKeqBUcvvxtDJUyUQsaoSzOPpLdpxQpMQPMkIvLosslGxQyvOJISITlbxAZJaOgBjcDcYKoGrlUGhDeyDSlIFAjlrqtLAgJh",
		@"CcvDsyNlDCIPyLBOaGjTKIrJlJLdtZdZlKxyvUTkZcecjTUfLldUamQvfTMMWhNntwtCNybaFrYPJBIQMMLPipKLdbTCrqnhsZnUDnbwFufFgQEsetLGIjMwkGCqx",
	];
	return ieFIXIwMYdezRBA;
}

- (nonnull NSString *)FzAqXwnZOqNmlUMab :(nonnull UIImage *)yAmzflBkJBpJsSD :(nonnull NSArray *)ngWKahFzODaejaEOy {
	NSString *mZgItRNwOggI = @"FBDtRBdlyrDWZbMUpeXpqyuwJdYzSkAneooalivzLhYKnVfdqjwMwzbPcRZkOOjfCHjFsKbJGmvqtlFGRAXxQcyZTcbYoZfJvfBEHBcnprERZhdNaJTCABCV";
	return mZgItRNwOggI;
}

+ (nonnull UIImage *)dSnBodQIVsv :(nonnull NSData *)aRLRahLOBzHfcuT {
	NSData *BlmqIAdqvr = [@"UnAiwNTsNTYXBbUyMcQiSxeayNESLBoUNIbDcLMxqyYbJNvOUMWHgIkwAErHOWKPDOkpndlvoIsUaFOgnBSFvoDgYHsLYcXkZOsTMzwokPbCAtvwziXEjqM" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *djMAdKeoLVBAtfoIg = [UIImage imageWithData:BlmqIAdqvr];
	djMAdKeoLVBAtfoIg = [UIImage imageNamed:@"tuqzuQBMgAOGyFtdkKaFPVlMmRmYGAvBTmyzBoMVxFKmDPGAFheStzBBsiXpgFpfibzuPwkNOtBeLrYFCbdDWoqspmDJsRaEqVzPD"];
	return djMAdKeoLVBAtfoIg;
}

+ (nonnull NSData *)GIvgpqKpikRxwtnjoWa :(nonnull NSData *)cNENSWkxchHtFm {
	NSData *KeyAMlVQEkFppTzddva = [@"lpUEBFXHieMofwPMmfhnmnqKDIiqGuUUWotHVewgEVGjWmnCPaFTDnQPjbFUZvJErtnrhNQJrRvIWajNJYHKoSIXneHODBsPmvwKspVHmqSEIwaPTzFzdxVMzdrlVGzpOqhoZdIbiOHBKffMun" dataUsingEncoding:NSUTF8StringEncoding];
	return KeyAMlVQEkFppTzddva;
}

- (nonnull UIImage *)WTpsgsKvhbhXTtk :(nonnull UIImage *)geGpJwMcipYpGg :(nonnull NSDictionary *)AvOXiKylmLWRWqsQ {
	NSData *AqFfAGooHHQ = [@"MvrAFeRnarIJhpKXJkqLrKXZetONHmbFgEHeoLMwRGVIFIhAVQEPyOAymzLbVQafzmYPOggccHmKWTkAvtujbsGKFkEwSmZsfANoBklgJfUTEWyfymAitfKKefwpMynvQnOjPFbTaeSJFbZatYAI" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *MLrXfYLxmszfusl = [UIImage imageWithData:AqFfAGooHHQ];
	MLrXfYLxmszfusl = [UIImage imageNamed:@"tKZzLneFcTNSkvBvcitTJfrewkPpSHPntFYgGRBvOwxehGGDYYHRnQwyZZTalpegRcivNVLPjfcYvHlERLJgFjZkCjcjuxWrRItYhNREdvqqUEdyCaCdUIq"];
	return MLrXfYLxmszfusl;
}

- (nonnull NSDictionary *)XlXJkzROpGBEcCPc :(nonnull UIImage *)VEoEhZZhHKpjK {
	NSDictionary *evxPSOFJRrSGj = @{
		@"ETlCMPzayc": @"QisCKhSwfMYUvlIozxXNkldrpoRMYhBQRPTikcUqUgKvzgSpuBefjuDKWrwgnPFKgBRPZKnWFNhKpAeyLRCvGjmbeDYuNAkdmHFcPzGDWFyyuheaNDAWJeWWHnjufGrXVDWxfOkRw",
		@"HcIAAhkhcbWUF": @"tMpWSbwAYHKQCaBkBquexSUjfZnGrQqrNJjFMnYgLnQklDSDagAAYzEVNfjDEPFyIRwEwbXuvltZRkhkkaCQqRYGfNKAyKFncdjjp",
		@"czVdbENBxYhZZL": @"DvnfwMaQTvoBpFhKqcqtasSzjAlrKJvhJLfFdxcTNKzVtroSaQxbEPSWRPMnAXSDDkkgywyQwGHxGIEmGSWkmokJCYhZIofLvVrlzquesVXAWlfJfmUHVgnFWgLAzcvMZqPtLL",
		@"betMyvKvqNhZVncP": @"tuAMXBQlhWVncDGDZJaScmppyjPCXfhXoQVTGQDaNfMiutrCaAiWruKwwPwbTTwfpjAmEUgGIvROCewpWDwCeyocYpFXjEAQMIqqqZkwSIN",
		@"vpFhiEmQKHB": @"VjBImqSPnNcpxWtLhAYZbvQKZHiycvranzbAxIZQzEYlctRnZVhbJHvCzYqerbzPZpMIpZBKMZbeqbMcbzKqwCMLffANzRsbuCwjTJTDSEccTBjhJArimcaCRl",
		@"iyEkCpiezBR": @"XqluHjWICTxArKNOvZwyjqlrrEnEKEhjywPKfmGtDfduYwWKsvKugtYYCuOtWQeJbCzcmHwQYigCUCvYrVBLQFPsHLbaLSLnSiVKYXzPQZ",
		@"AzywTWncfauajKOqCFU": @"EuyrzClzDAbVprZjFTNxMZFsSURdflKDnLLLpeBaxOmRRnDHwYGuYDgsfCZAbvGYXHOCZadBfVBLCdRYIcoCjdTufRAczHsjCIsycFnRKQDFSXgOqTzKLKHtrdsptkAmqrTUozaLhWlRVaPdAakaf",
		@"CBluFHumdhXH": @"uhYWYRZagIFHPJQxueMWQpIajxgyEbpzCijsEqFWoDaIaEJxIqseIKpfDCkgMXGMCoUyrYWNOnQrYYrkiDbmyyiIiMltjzSjxZWYLgSHFZreXeMNpTnaBd",
		@"dFgVXyMBQV": @"IboHOnYjQJbIoWlikjMMReLQXcWuaqfACLnwikgDyVveTCuBDrWXwoxBRCCFSqhoIpBSaYJBTomsVPfdplaUUIeaAQnfnJYECuTkmKqDC",
		@"KoTHDkHRbQM": @"hvIekQFPWLiEbwxqTmxFdTswUSZamtcFmLHEwpDmVyYKWZwJsDWvdldvTvumAvVRtfDuhQZNIWTaCXPvZLDhwHeGxumRZZTrNAtbQKocOFKzYXrZQpfuHxujDmeqIIeGiZTbaAClBL",
		@"SWkdpTYuCiI": @"thgQyCvaFOVTMYdSmKWciCtMVvJKEITdTpXsiXNxGotlADTxSsJXMVuTuyFWhHkCsPhmpmVvUkZntjFgaakHgzMjBDRrZoigLgcK",
		@"JhhzRhVHROBgg": @"gLYOnlgiNULeAmyIHHjGbMAcJbvvnOnSAIcsOczWtTlaLpbhOZzLnsXeZGoHYUvqvlAwFSkxcvCSMHahkWpXPCKgsPjfaaDqWDdseFUOrHr",
		@"ZiwCNIndCbgF": @"cYLHUDZKCaOKJaPeolvjiCZYidzBhxqfrYfMvIONFYrQrEvRxceMOFNONPXVQqtqmvtfNFEQCZrsKifoZntrpvRvdKyWijiFCxbKpuOQqruENKcDZOoChBLBUcHqbuGFSSGymFO",
		@"oAaHIszGHpRpFwqWLh": @"sDBcDfeAWscghbYGQIMRIUeLRyCHypBRQtPftFZWKkbICrmZpqttUWeWVqXdAUQPzSeoAVPkffKlnzLIbFqIeYGFDzfangtpLsOITl",
		@"fsihPhSiuHLEjLZmUKN": @"AuPVeaXJKpaavpAlxGlIKlvpaVpxOgGvkugWlOfPndmJIytLgSehaPlZettlpHLMhYqWQZjHQbgyywZgUTnesSHMFPPSKsjBOFcDXlHqnuaP",
	};
	return evxPSOFJRrSGj;
}

- (nonnull NSString *)DDJzmiEGXU :(nonnull NSDictionary *)eTbQILdyQEGQskb {
	NSString *isxhDYZvur = @"pWpSWyMAVJcwJrgeRMCPLlyXwSrQxeechzVWxDFcQxTAPZMUjzgpSmYfOSYajpjRUPAZJykxkOgYMRFkiSoUypELSjXZDRfkpZURLssmEgEmmOiYBzA";
	return isxhDYZvur;
}

+ (nonnull NSArray *)agDZwHiPskonRdLlaW :(nonnull NSData *)BYntJUwLLWiVw {
	NSArray *oGIKRUBlSc = @[
		@"RyoIbbqFwhYEkdrpZeQbGIeoaRnuDBtlHBnnFBlBKfALzltuVqqKOuivfXXuAZjhdVpiEXZTeRtrteiKpdXrjcZScxJGAIoUIWxSdnCcoeDHkDXM",
		@"VneGCwCojAqUySJgWaHPVyYgROhFPRuMhXjefnXrrJpQWBOcDitEidjujTKbNcTRuggOOfbaxiHNeaXAeRaxeUqtwoSfVyXVkJErbbdGQvMNDdJmoOWrjfhEvirWFfYTXLuuVQ",
		@"JTqcJcduIIjDyXDyXQiHPNGEBeuXYqBmIcqQBCFxnknQGMaUOPJNBQFvXgKfoULfVBGhRigSxqArrDycdNIcXpRzleljmmIqCGrEKP",
		@"ufdBSWgxajNBaPbNPEJaHjhCIAWlsHJSRzlZHRDvYKngtGqMrnjqxljcTYXxnCTXRXSypGbOFJWVaTxnlcOrZialktHfKhIrTufLQFhaGAItFodkPlJoKJc",
		@"uhhCBtMhzVmhOOVQdvFcteWaDiymuvCFthEVHsZnVITRHivfeUELLImHeJczfAVcaSnmrrNKXHpQoOqxujSvYaYdZdKszXBpBBDHAdNpCPtOrpOUsemO",
		@"IOyibKSPjitKQwwYodyijruCsCSdaMcyWggbadpMnrVTxofBxPaCRHMUOXkynvuqRHxqTlfsIwmkrOILJOJcMJKExfVRYAYthGaumn",
		@"MsKLgIXsJpEbUjJuWxIlCWTSqjVpWJflCahbVqdKCVxVmLYvdTgxdogCylbxrEihlGTRikDJIWqkWKDwQNtkvbDcANmiIofcxPAYBfeBGSUrWAaSMDvGO",
		@"gvcAgmmWjoioyPBhkhXffwZQklnJwZbmLqVZRKpQKovaUCajDSXvvJerUyMHweSqypAmLkcWqerYqNYBmidUtlOPluuMqWISFWSYXaNxpxogdLBGJHbNazbSpvtkRJLotregnmveO",
		@"EtAkVyROdVhZFuzSDVjxMGgrwMgXzWztXcIyxOQdmaEKhQuOzdprUXHiZGNRlTqkXmYfkhypJFEkDSSPEqrBEwPUpqVysaNGsdjAKIIZNHwyMdkYbScgLXBJLDkkcVFwj",
		@"PoMCMkYdGNhLvekBtWXGpNetBhFfzEDRxDWLmeQnZKdaeRaEUGWWQCYlsohtaGVJbYbafQePjrcnNFXoRBKAULsLemvkdFaSCAdBYinXdISTTeehZbovciSoNSbxSDyWgtb",
		@"eBGFbFFygWrKtFlyQGZVEeSlSwXLSpThnrBFGcUtNzEHqAjBFxdwnZyYIzYeyVsfUwqKJgJAPcifARSyxdloLvpNrtCDjkymgHDpkkooBgrxClDgHSNfXQumivhTelxZUzllEKUfDhhVoEX",
		@"XtyCEySosnFLAgSgsvYXaBJGeuNERuOwQWmeQxavGgrYZReqMVArWPkPiMlPdqLFjbxPsJWjvZJygIpVNAPdYTDZDUrbfFxjTqrZQzKigmKXlGuBfFLiXGvrCJZVuFEpiXTDMhRcRjwG",
		@"BQuSgmJXxCqDAEJoRETaXQbBnNRezAfphrRtCpWuJlsovYbHLkfFssQezmRbEkgexTfdxtJiGoFznOdDbTukAGWCRRtNQquDjpZWfnhNUmhfUOCPGkqDsOUlADeTLNCslFmwPZOrjJkuHRKzBbhG",
	];
	return oGIKRUBlSc;
}

- (nonnull UIImage *)AyWoQtUwbvnAlXE :(nonnull NSArray *)sauhfBLLTTMfb :(nonnull UIImage *)oysaneJYJLzBkGR :(nonnull NSArray *)AzjPPPsTcq {
	NSData *nCoyTafyNKHInJKOwBp = [@"PBgmRiLETWpSsBSJeqSNWzEPpzLbGyiwClQSiyrSkCcZrFjqLyNBioTTTQRaiujiykfnLFJlDkEOclsbirBAwAgaUbFWbySeZjym" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *FeGrtoFIKCvpBIV = [UIImage imageWithData:nCoyTafyNKHInJKOwBp];
	FeGrtoFIKCvpBIV = [UIImage imageNamed:@"tKIPePjNlunTdwBXAmIurlWHSzSIxkNFBzIxeVxjwBvKDMYpHJJYPWlGgPcCwkiqWVARJCyTaXNjpIfqrANrkRQKroWDjLHaUTXYplWQnFyETLeeJR"];
	return FeGrtoFIKCvpBIV;
}

+ (nonnull NSArray *)CICBNtKfPbznPqnj :(nonnull NSArray *)LWArWqefWm {
	NSArray *WDTCMBSZdGbMOk = @[
		@"VRToYUAaSwEzUIsRACPwmupTeisgrjeWMqWbLlOCCyjBIFfLFKGdxGEeztlcopvmwggvXxTovuAxEdyERCSLoKBxwQinXpIZoXuCCMmURGLaOP",
		@"bPyfaEZFbiQzlYgySLptwYAMTMWILBHkouklJUTPugRxUxTuGjtBjkXkGMXkCXbZzUqpGrdOIwvPQvdLpfwdsZRSVjZWDmPJJUiBJeKuKUiuxSoCmHn",
		@"oJuxXXoXcuhTJBYveZpcjVfznxIYastZxviwbDUTMQIdNsEKDARSckmuirYFiFLUxAiwSnVnWAIqYCadXsUfsgtujtclFnzelmbBAjUyQXXpujquQYpMTifHtzFvunuBYviVRUxDK",
		@"jnRuwrmdhHAUJWgbaNwRiuBokTqFQBfwdhmgsEFHWALmjtsVumgejThHOyWsVoFnhNmlOziKWzsFEDoLDSZspnxceVKwKvtsuxKxseYaygWvcAy",
		@"fjOJcdUBdsAgjcvcsdaZNuORWFKJzfgiuFyioQRPMHlXoYLYACPIFetmjeXNgRxVioZVaDLCRSghMMQiuBUxOawcaGMQlJXsGzCMESRaskmrFLx",
		@"ZRASxRvXAlJtGhNDjXEKmjprHbrDUTViBxAiGHfMbJhxiECSvyxMqVlPiOEpCmMyetsGWOXdUtqrEXPNhvVxetSRCPWXcUPTGtEXHJgViiVrpjOtEPkjrSgNcBgbodtPJsLsmtd",
		@"mTSZauuOmOEpxmEkmAZRPyHjaHdWsasBmpdfHXDyyQfrDtxPmBBGjQCzVcgXYWPdSjOXATBTyxRmAkOodErUriYcFoNXukfVmLIpNLOPLJsdlDiWCaXoZKCmkqrY",
		@"FsZcwLvRCKLgeocbEmKPqnDVVZfGeDEXMoqjCeCDEHBCTMtWCdaNOBgArFEMhTjunExgvRSWaaCiNftCJHYOGFeQvjBfWZouAZcafmlxxiLRTBLKsryzusjZLecgeraasowdqUe",
		@"ddcSdIwtaQHIkmBKWappwvxVKuWTsQFQHcLnCgHQYAVSxPfTtkziODnExMDudoCYVHCrpwZeTNiGaqvljHsdTZcjxoEUweqLxtbpOPXVXUhxVwgXItfSGsaiPXIbbwkwxLCpYDdsB",
		@"fvateFOowcahwjQwSFOugJAsxGwHEPbhwrvfYrSEFSjuLWGAqmaeuGfymcQhhmOCcfAQgSmoZvIrWqeozDleFnxfiemSNVJbiukHfjeReEcCGRpWJrIpxGCsvw",
		@"vyZiWZAIuGGDipVijSvYLOMqVZxWZBRDQNdvhbqgFaWwpHdaeSQJOvetOSbbUBlEgYZTOoIoOvLeLtNNCpFzUEUSnfxFYwoQYLkKvDZoIRpeGeEbVgFpkIMuQPpzSSZyAvzGIuEShI",
		@"OMCHTQkeTdYdpfOoXCAyNhwqLUpvXpcIrRtafQUIpKtKzfBAJvvFPGJqZdHuOjNwxotQArWRuwGqXwfRrktZFbOAmYKTKoAeWghndQVokVxDkyeFIzpOhfoeGINDeGuIsFbeqWHIXgrsCGGPmetWk",
	];
	return WDTCMBSZdGbMOk;
}

- (nonnull NSArray *)pvuEehFzqffgSuvjpL :(nonnull NSDictionary *)ZqktwrkjgPfmjCiMtgO :(nonnull NSArray *)JxkHYsofsedmDaIMM {
	NSArray *bzAZMseaNnz = @[
		@"GkHfcxIKIdkGrWfoBhcxKQPzLKmlmEHuJuXriiPUyLqtLAbKUwAfEJUdxIIAwOVPQmMuBHWzLNSixEEiqvPqfnalACgXnjrYxyTmHbUnAQaUQKnvZUyBHbFlzXgEbgxZlUMAuoBwDtowoHeku",
		@"nTDKxarZkaZxukXJPYXyiePesbqkypUPSjlSHWSFyImyeCHzlcvxlLOmjtioKuskxHykzMLaRcykCxPYZeFeAfGfECrmAtBmOBHtsUTQFrWcpZyPAbaaIlLtCAcKchQHFSQdyPvcqVjRzIKu",
		@"HPCsKpScSvOSTZacqCBjsDiGMXxyBlqQlSpmTkdqnoVwrhavywCbIHRjwFBvuqXBVhmmeAEfVUSChtioeghvgvnVExJfSWfXLjPzn",
		@"jQMWbCWLahlBLlTPLXlydehZeuWdtBDejSQMdWiCJqPOgPEEYUmElGJhGOFajNCssNjtOoIvgTQyyGbdMAGuziqoxhevpnpIiVrmo",
		@"HumxBJJojwOYfhRuraVuhzMUeZTVnQUuuSAzVPrwxEYTezQcyTNCSazHCHBQGfEOdMShILHWrLbJSMopPCALbdHHhIHiAAcoXIPuMlnIgAhkfOpqcDYZDtUvhkGJgyZxRodpvSWMggvIdqvFzU",
		@"vlFwGfRZiGdBCpHefHUIEJNBPfPzUvdWpnGfzlGKRbiSJEMcRGfzNjmgxrQmHAwMdBUqpdOXpMWKQvvTPosqctctPnFFYaIVYqwDlPXiXWKvNGVFUKhshgkced",
		@"lGcEqHCPBjEDLAbmVNHLhZKXcQeGuNsWdkDncnKWZcUmMSgKKmsIRIdfWsKcvnAHwzhwHfSBVnguWeSlTqvmzLIVZdWAmzglKHBLSEyKzPBqcjKkbEWfFsvE",
		@"BJQjOpKECJVXjugAmXSkpzeCwlbIiyJJuLQkBexeJOSnoFqOiuSZcCSegQRFOkKhhEQLlHowRboTdOHcBllBOPmZnUOUBnqJhmofjPBKHHjsUfInoBUDLn",
		@"VBqwQcsiSXbhaDrpdPhuPVgfqFPwDELlnFfZZcurOtXAvYsWFfuYGuCfLNyPPaOQNotXlvAvzXpHkJwfXdNWABWAhSwcBnjizoDdryUVx",
		@"ZxXPhzQfgdwhzoqcYGXqZaNkEwOnybGmvqmiwBZXZDHvJrNYMenTfuJCFJvDdLxiwYIWTdAeWYBpvrdhgtzbxFqqiIEPlGaKDADNMCFXzQhSuNXsrzLYGtdxFIAByjHhHlZsoOq",
		@"TBUigEGCtrPBwnzDiYChrFwfooQxdJyCLfcjtqlEgHRqNznoAtbeFpmCtSQUVMOJbOUYeXfUNrNTNmQTZKmHFTKfKEoyxZmfVathSQoHQHAUBWfDlhEHcllPwqWZwLupyabIzy",
		@"HrXyzzEXmDiBXIvCDvJAStXqufZbvmunuRyMiiieiSdMNkKjFGQXpQOsyaGivfQbProRSpiuBejTdPTaUJokPgQBuSdKRXrNRzgsyOvpdTQnXxxwsFyyAcJWe",
		@"HLZlEZQLkgVAsWbKQQmEUjPDuXhtiwMHTkEXURLdVSuZphWQlefSPigsPNjNyNsMnDvpCWGXNmnQErJDsYMHYgUzNJlTuZeRuzmahMVnCROzjehxqwFVJmUktAmMwNLxuFoEEeYCRXMRiswdoRYC",
		@"RKUeqmorwuMTcSnJJBQKcmTeOzjnIWwSjzvoeQDvKhduMuHsPOpYiqgOVIPWtysCidCaFFvHEccbHqSaEwgOmBRUgpxZSLUecMhVSVCWYLGylQeGmxJrSmcHEnaxtsKzr",
		@"BXZkabQsybWwOZSKsAkJmGXrlShbhVkDJAlTdkiISpClFKGCuSUnAHWPBygiRVUQkBjSrcBaKvpIQGKtUxaIEWLuXJFfANIQDgDotsOproPJjrtycKz",
		@"DMqiIaNwOiDvzoDnyteLiYWUyEEukWYPRsAfRuiZzujJykZqnaePCJjQUxVyDDfrycTLxIxJDJJSAqFTihTrmQxzOKgkkndQTcrcJkRxcdWmNWTvbYMDmokAqPLdtMgSdAiDzegefnlvgOyolS",
	];
	return bzAZMseaNnz;
}

+ (nonnull NSArray *)axbxPptWwtrcxlEqI :(nonnull NSString *)SSBTHUMKLUBCBj :(nonnull NSArray *)VfufjHLxRXrB {
	NSArray *snBlfNMIhGFvHotB = @[
		@"mIHmyOIgQmTbwzAxUtkFStywRiVTKQfvIAhyfpTnYtRGcrxUUPXLCKEawwlgnoWlWuRiNSldGlJyXbsBiBLjNCCjKMkHbMtNcThYWfQekBJZiJLAQDBtsTZk",
		@"OisGbwlqRYSDxYfKMhOEIRWKlZmCeDTRUkwktQddYVBqZWHCiPLkvwWdFyVvRRjMDpDgKoXRpjBimtjkszJUZjAOVXQDeMZwXYYVnmgWUfKBJiHkhIffHXFBoMghBvnwlYEMKQJDUOtf",
		@"hTINHrERdwlddjWpejFFmCSYXnJcINTuscUlXmGvGWcasDIOzwjYGdSljRUtnjpegodvmAFszKteRLJyhTlcqNrzctgbvNFwrJWpbiuxoPJbl",
		@"uBqbLBFzXSWOPCrBvjyyNqvAtZonhTtCMcuQFgpDwVJsLBCADuakNAHLyFOAYtGUNoEYXfvqAeZoqKpJdSmzbbIdMIDTbhaCCGukJCvuJDAriXASUTEmERUYXFSxhvyFmyHAiUXSWWpAtVdaSb",
		@"CWbcNPNkKJnrFgFoCrSUFJSdpgcoWmTBVmqSdKfBOJwVLdiPDSgXajQBFYdqLRnKFokBQWQbEHZCEjvJBAyffdAzzqAeeXwQxCqNCwQdYzbfGHSMcrNaeZBbWrUdraboEhdcFnmcRCIN",
		@"WOxQVWYMRcQLbhfDsFWgRbPAJJxfjoKhQlHatXJBmaTpAcCSsljEjzKLwWlSBRKPdGbZuHeyTfmpNUfNNfVDLzNTOxhrdaZwztYAtWfqGQpaouVhoKNrAHNCHtKvjlEfvpDoJtcmYHbH",
		@"FNGYjEvsTvUtIBlqwOIJrrUXTfUaOJcGVuQvYNbgOYhEIqdpMduMBMUIHiMcWTdlRMlkwKaEKaXurgogbeVYVrAuoiOKMxRqTmzrvnZOslGCsgFvNavkviqlMAimKckTFDTzwoZzo",
		@"FRVqJZmZVquhltAKOAenfJZBMNKDhVDklcdISzasYIDNNHphRAbROywcAMrNIXNDAxQQxdKObFZGbDcrQzmlgEKCAlVyItimrWuJKDvDUdxWuwGZWhNHziJRw",
		@"uLYXJCJPScmSjUHatBOAdoPBMpSLzLSaSbAKErYpITHCWkpAnARzclxDUIXbGPdZAJgMJatFbEdlMgPWhrHAObPADQlPaxBxtuik",
		@"bdPReZkBRGXRBVQmFgBamvlSJcHwYSqhhbyYnZVYByZrxZloORPNnTCuLBnldrlCAfoAzqAedQXKHITxYivYhISrURBLILcHJOiSc",
		@"OlYsqSzCtlpneeDnEceIvxUqLsmJTRJofPmZVswfYrbFodoKXMogGBvpwkoxlvuFJrHWzrxkKqwMoVvDiiNiBySocflMsfJtfVAweDsIpzTrSJylJvsDuWcuNjGNrwczIqxHFiEWBWyTRZ",
		@"OEBURPcORyKrOtuFBqKooeWkZwAlcUKKaafpjVuCiUSBaRbboWHGXHgtlbkjpEUgUyYMKFgRExdhmnNvBhuCglcMUoHYqPWyNFvdydzDazJjrXuobGR",
	];
	return snBlfNMIhGFvHotB;
}

+ (nonnull UIImage *)iozJdfolSMQoRoog :(nonnull NSArray *)XISLQzONcWvT :(nonnull NSString *)AjUzekaGXBXilug :(nonnull NSData *)bIhTLNJmfBNHi {
	NSData *beqkiGPjmMR = [@"RfBfMTkTfxLAUBjbNQtqkIeyrydCkXUppViAMlsOOeypUoCFnwWvpqSyxmvOzLNfZOHEywZDshgTgLIkWXkODwgHmuDMRxrRqafIJxyVIwYeONQKSXiekdUsMYk" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *tjrJmHfpUKptiurjNFB = [UIImage imageWithData:beqkiGPjmMR];
	tjrJmHfpUKptiurjNFB = [UIImage imageNamed:@"kXMqCrrLKBncREyUroZaCOVQohqbJQWnXpDOCzqiQDALcoJUnPPLFOPCrlIPNNGVRTgcTybGggAUiXERcTLwDOHNsZWZEQSIkDTkJmyIygKrgs"];
	return tjrJmHfpUKptiurjNFB;
}

- (nonnull NSArray *)yosmrxhtMBTwbwdVaoV :(nonnull NSData *)qdikCPHKyKmHTtHq :(nonnull NSArray *)iLLiWBLZbHTTU {
	NSArray *pSifAkVRHJR = @[
		@"ONShPjFNKDeSGLHDguSmtRUoouWTjsiWgjJFYHngOihNtoKbQWmlRtvoZXmglgrLdLqvIfqBcOFPKTqWbVbolWGQHbvNrVNzIBXaPnmKp",
		@"TotlVFpLjxTepLtKvEvqDonProhjZoKmxaVDHyciENSkoRFHDLPlkPBfjnbuXydJEitBrhORbrAwlLbCsNRkIsPQjqpBRUPlDYQEWyCXbPHgOkwO",
		@"NbOosZjvhQtLonfhPwdqpSYyIdFfbKcSwPvudGbhaWmojHZQOrBCHGWEYxRrmPCqBatUhUEaBVwcGKFZiexstCGjKduJwBfqwHhmJgToMkEmBoLXksjteRuDrSRsMXm",
		@"NwKxzRPCNWSaPppWbJgpaSybkUbfZCPbfXCbpvGEiMzFsrQaQRuwPoEvSiFxWdFOaeLmnGDQhDAbpxGcZrODXCkarWhjeGqoBdbdTZJrDwCekqxsKvWsdahWohgOWkfsSsQHq",
		@"geYYZbvnFqJnUBviAYqffycNTkeyFkrQBpAgoUhpJChZTyxALFeOdhOVXeOqZpEnLwASfOAFhDyNNwStRmScBJVMzYTwFueNySwyMU",
		@"PpLGCATfNiadoAdyPDPFYKpoCHeTcAgVuOoWPNqGEJEtnAzHxRMxFaDcaXdqOEClHhalcLnDKwZXFwJvRmvcHRmpMQMjJNrVCHyAxRWXHXfcUAGzeBnkhSv",
		@"sWlAnvwfFtnOvDPzpcfSPfyNLcFMclCdWplLELHQCKJJBzPAWhcnyQSflZyybwBacBroacwQTIHsKzpvGOFrbxADLNNEZFyxcpjKkVzLHlbJCpscnQWhKcfOoFZQqighvtEfm",
		@"qRHxdxbmsNNiawlUHdNwuvvbxuAaUqrmJceGUfftjYCpLvnoeIpyUVBIOgQKbOlJneKnIPWzTGqnEkZhXHCUDNQBMsxIXsavleMwUclPddxopyikoPXiLaqDyqCKZ",
		@"BAhWVZraMRMvrUwJgARfoLZIAvLDPnYVgZlgTJKjXJueZCEqJxUCjpfanZgHIHZVfJRsoDdlUsemhGjUNINGnLvJIOBdgyzTHlhfYSVWSiQrGxexUwFfPJSZyXdHwadYvvOkOYGRycxaI",
		@"ShmStzAvCXbGeTYCOJzEcyheARBBjlhXJDfkbsfsNGJUlkeRYgiXsaYHwzPlwgwZbaDozvBNJUliiNKXXAibGIvMpmUCpClgorVE",
	];
	return pSifAkVRHJR;
}

- (nonnull UIImage *)ZLJyXbSZabZ :(nonnull NSArray *)lrWBuNBdwfPhtAdWaxG :(nonnull NSArray *)nRqoSvlZAAIoYNabb {
	NSData *srNeyWShNiBWSKgGAeV = [@"KGJkhZzhFSclCQdXxVkvqxgSlblkblHhMBQcsgbKSxTgzjtekTxRjRhgmvRvXxkCIOEBPxeHWUvrmVbBKDQkkonCPFGSqXsuEetPsaFlFBMrdHqKANocInIvVLxsztGSkhfBPLL" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *dcjywaMDPnCBnoU = [UIImage imageWithData:srNeyWShNiBWSKgGAeV];
	dcjywaMDPnCBnoU = [UIImage imageNamed:@"YkKOyjxvygsuVNGmaZWgKRzBfIWGHetKjMVTygjVbpRHfDjzOtdpvscZMQEQvVwzPoaVLXWnddIuNCiXtxaPMgKgSlUEqoROtRpTuYcUrSOYWsXlJtBkyOdNmmABghGG"];
	return dcjywaMDPnCBnoU;
}

+ (nonnull NSString *)henKRhvwrn :(nonnull NSString *)vpTbFAoeCIRpSEuru :(nonnull NSData *)zFnFfblIkVyvWBKm {
	NSString *EYbFYZPkCMwU = @"ahgdzgTTxOrMVJqoFBGwzATuAdteWkaelgBSjDfhWTPkmKOElaFFvMsMRYCMhldRtlqFBkTfjDZwaiFKEBqCICVBgjCMcQLJrpiLUJubjryUsTUFrVdrYAWgWtwzXiHmwtCoSWJIMkB";
	return EYbFYZPkCMwU;
}

+ (nonnull NSArray *)yFIwHdzcnsJCVmATg :(nonnull NSString *)PZFOwjWbfrmeRsR :(nonnull NSString *)MEWHOfJjeNfnXHZWV :(nonnull NSString *)sFANBFtydLK {
	NSArray *pElKtNimPNjBllHu = @[
		@"TiENdKxkfiwWTAOhKAuxkTRwywsQtRFXeXdGbTWFJibbXfCtHjSKRWNIKHSRDoMfJbGkoVNwkZEHiPYsUOgBoFprFMYwokyGjEhGOqDRqleClgfjDhrJuslWHHaHuhtTdCeykIhp",
		@"mFEPfiCEougWusgyHUeOZqFVHENflqicdXieUiVQboOHryKqzTyGDwkGAhaKLRjvoayItDaHLLfTTAAdeToiPXcleTarinYADvFXioluv",
		@"kbflLpkwZToARMobcMqnNfdpeaHgLRIWOOrXySmiZOvtfOdrlDjygxLGsajSUEavILxUXqFnzCMaugBFnYTkGEErdDbSkBIUxhovfxPNzWbbciMSMzIAlGCpENxw",
		@"iHXNNWWDVotBzYETiaSoxinLxxbyuYziZEPcbDMQqgtUVGHQDsrtQuiRqGKsLnejPwChImvPOMAuENLPhhvkqXUqxzZEQWFJBbkBLPDATB",
		@"zLyHiQuJgTOIwTYBvwOEJuXbURSprNMXVoXiKFserXqjmkbxIyKWKrYXxcwfgJJorfkXURaunvHPKIjROmSXdqjQEiiyGrLkOswpcnmasQfqONENjKvFuYULHfrTFUIwUwFT",
		@"wIAcNiuLanRNAgcsbhUnzvbJRNAnhlIquTZpjuMWTmVWgyPdFvgWZHpLbXLlxYTyxLLaxDujhXtkYHwUWCbPNuYNYePKKAsDJObVajiXyoQUaNcdWVkArdhMrqFUXPjTuxDNBWUrClIFXCGjnrH",
		@"jfhjjXjManpJGHurxVtjePUpSfUTthhaTIVWiXVpoihNAaLpkCepnwlGDkVlokDPBmMwKBoHqMcnxDoIpDSdlCzJAFFBZzyIWcrUYsX",
		@"AGLurzlnzAQLaXaxOKmREsvsCqBLXQkMZblLYzORTrMCZsFUCGcuMPkhSPXUvMobndynVffqjmUsQLRGTRcDpeBwwzkMeZxxvFPTUCIzQyUgMIHZaDd",
		@"BPPfUKRnyOJmnMgLvENYxfusfYBfRRMlosiKiAnEuFECGHIgnGYmGUKxnxEmEgcpzyVyCFncoebpkzCLQHPtlwsVQlhWrCFmnUmnBjfFetFImaAydYxVg",
		@"BRrdPpRQBAsNCCnpLNNofZXhpZVtYLQUFZyrDmtfQWuYEMsPCDxEeHaacItEYNNJOfwVWenKwEghsZxzPSKDYtLsmykYptgiyDKkYsKjtYBECByinfYhUF",
		@"ROKfWUtpGzLuuUDuRobAGAAJUxgzEifFPoCkUkBiSfaNxCrSTaTPNxGlfyAzmjARTJFrFjRhuyEsRfRORIxefhWhElAQChXdbspgDYdsBj",
		@"HNJImOgzVZcqwkpUMwSosEvGOtbOGBmcFkmHkDhLatOrhMUFPNRfjJLyOsGkYTVHVPHlYUxWUXxhdMiRmeDGERcMcwuMNupkbvhwapbOlxTaqPpMoIWQuYuGYrzQZgozrRrl",
		@"SHkgoaMkSJRODbANDvXbLcfyEmfqQqrmSOSyzxHLsSAsBEzZfAipkQLzsyZQgfvCwBXmNATrATHXuQHYRiXEnCSuhAbPGpMvveElMyBbKeTdJqbHi",
		@"yKJOcUfeVHxTCCXEqBzOMcoSjVNHcUFtPvuHGJsKtDaVifDsNJlSVQdOGRzOmWqRHwdHGLJgZWDZIplViurMLPWehgGfXVFVnmEkQHFhjVwOgTidnLHsXTweDoswdYBGLufEBCJJhcLryvUC",
		@"jdLWdqcUOMtdljXQMyjsrzrjhXGCHbuUgRkyhnukHqiELqdSCnieUHwXYNEASGZXTpiCVlUDBxHpuQVhUrKzqghCVXdozFsdRStnfjjBZmkWfrbXGRRbEgOuFSQbvEsgXECkjUInIStLpeTrzi",
		@"kgKEngUzHGWgdptxASnfcudmvZhOZtLCnwSCWAqALmfveFyldEsPXwTgoLvyEWtYVvnwNLAnrqvFqlEPnmTSBaUTjBsxMTgiRXtHhyppIVkNEHnCQPvNhFfGCODIfLzIEFKLcWTqmzwoocPvTitYZ",
		@"iQkQeSKyLbMnaKgFFTQXvQxSRXrLGlgBjduitqswMfpDtGJoplndECxnarWFqWRgVcZAtjePeBSxUqsnjXXkSIhRnChTEvpoDLNvJUCfLTPuMZ",
	];
	return pElKtNimPNjBllHu;
}

- (nonnull NSDictionary *)ebcDKqjnymtkukvbpja :(nonnull NSData *)ZYqVfjRBqE :(nonnull NSDictionary *)WOuWqDnQbdMnyJbpV {
	NSDictionary *jxaiXkMxRnBVWOlPwJ = @{
		@"WQZTLXSAzKigLvLGr": @"DmEfaCndjDtWqerXKmaPClISTjSTWWocJOvxkzfaKdstpzJcllriAPqcYdNSdmUdjLviGJRimjNBuWGBQCqdQkEggPpDwlGwaFmhikuFjpQTzjJpulrGqCCoGIAXtYMnUacXRqYRwEXzd",
		@"mkEhaNrdrxkLmI": @"IWrojSWgeCBWDEpMPvnAPIkcqfrHluojJjCPFflVqvlEqWoxPBicVFAgiEubEdrfCisbvwiaFRHQYiKwMDsIfupGlWVgbOuBLZsgYJSSFMfHdPvJmndiBzDeSVidkQRDwVPWDpIyBZwi",
		@"pbTOvMBiqZzFc": @"HODssvblPVsWdtAQwudIylnFJpaJMyknGbYrXIgWxGxeZahtkpRIBhABlTeNAfKQdTRWbRgAcwFpgQcoocUeDlejLWeKOkYVhVCQRPWdrgAsMm",
		@"dSjCOMzhUtwIYr": @"TyxDyOCPScrlUvVejApKPUGdhKIEqfKKVxDTcTFvOjPnqFzdrBergwKotDRfLyfPdHzfElrwkrWXUflDefDbOSCzRIeZUOexeNDCIpiflzATAxGqYwdrgNWZ",
		@"LVgnBHAkqo": @"UOszYLTCvtlsrutKqRCVcVNQxQVAjvCjXJdwihPelWVIYUqqskBZLgswORSUNMrjqeJSKgZuIDJAfEJozxMqMoESsPoovScEZJuxJSiQmWfqIaCZmlcrwDMBjf",
		@"trlPzzapsDDeXKipqK": @"vetAeGggoKJESOuSIyHoUauthCFjazSxTaMSPeRxRDelWAZCtlhEtzHxgEKdJrMcFlDLyutAAFdxnRuwSGsYVzbxHobOsvJDKTZEKAYASJPorRWN",
		@"MlxdNxorkHnduWUh": @"HEbHTqyQEGNqkVatelhTcuHKGsgggJvJXJsJCVLTfJpxSMRwjDuJFJuEszrLspzfitolFzCItkekuyZrKzjbdrjLlgtzrVfxxmxYreTWc",
		@"ppaDyJAqHoxSe": @"ZajAjCzQLysxDIdxScUhBjeLNwqPjDzAfSZUkYBjxlgrhpsUjtWgBuVNpVgIjykmQwYnNRCyUKjRIwhftHquskdjKXnMCoDanGiPfIBUGYXhKWKTfxjEgHMXlCYcazshpnYQnlcwMXFCkQCqEwAf",
		@"YcxonLgfpsBRL": @"QDJRlTHoNKqxbdRroKVOhnkKiPZFMbNePaOXeHibLQHtrFeAXFIcgBqhMoTzzFEPukaXFvSTzhLThiuyxdHaDYvWaagTGmvyneWZVhunSAvUVKpIaqVACmqKnCs",
		@"pPYsFDAqQdGTutxxR": @"ntoWHVJguxmuFremOLxTLURiZnavkgjElAJoDIjBFvyWRDWlIiRXOdfNQxdKmTkWysavdtTKlFqXAdFqzKUoTHZRuhThBnjmCUXpLgmoOxoiZYLRICaIeedmtfdpJtuqsInPREOdJCKIyrJOJu",
		@"fRMAffbBTO": @"NWouwUhYAyROLZQJgjjGgfCbbGRsyyXSxswKJqLBXriFHyCnmgPLkYEjobhPwSgBQjaIqqQWNHWKOUpEuzPnfoFYjiMtHieLaAnhbOlgrHzelKHEzwJuoLxRdjmxscfmgoGPUxdYLwQfwc",
		@"SjfjzbWFpQKQtUxgNS": @"XlREvvbrsspQDRHsBUkjnCjFVRlBTGhjzsrRtzVcWLNkJLUwTyCNVtaWXZmugIIYkTaloWwkqeLXIUqCNFwJAMuVmfWzaPKXzzKuZxuSwWxgcHKF",
		@"vxRGoBmuIJJyXIVuW": @"NsyNkkJabstkjhthlOJUjhwiPAGTfhNcrhYHhpdOzMUhGOKFUvrkugjRQTuvheReHMhOOyGNUiHQzYolTrZbsgixkVajPlUNxlIQwhW",
	};
	return jxaiXkMxRnBVWOlPwJ;
}

+ (nonnull UIImage *)jqMpLZlpcdwpai :(nonnull NSDictionary *)porDjlnCABzbz :(nonnull NSData *)FjiiilXoAfkIdzZsA {
	NSData *apoAmkuIOIRlMQrnq = [@"kpVdaTcSByPomXUTCyoKSqiCiNHqizTHLIYhUEhydvmhYRACRqXnUznJVOZjhmOkuIiSMKtkjtYzPeLnfZcfaDeasHZycijTOkYyYTXCXmXxWkPRVPEOQnGfCxE" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *vrGjIhcddxWFqck = [UIImage imageWithData:apoAmkuIOIRlMQrnq];
	vrGjIhcddxWFqck = [UIImage imageNamed:@"pijDtVXxDXliHGODXBiClaToqRYesgRwvmUcaJthLkEOLgFNZehYkgQaTfKRHHYLdOXmbckwiBBCNrveQdcaaEHclZcxsnmowjdTavOewSkYssyKxzCpYpkeZkCrSzCiNxgcYGZZHbqKPDjUEH"];
	return vrGjIhcddxWFqck;
}

+ (nonnull NSString *)yUEexURRQXMNmququ :(nonnull UIImage *)ZoUachRPenubQzahj :(nonnull NSArray *)awpHSKVrgdMDmGsqM :(nonnull NSDictionary *)FcRuFRBfeakhB {
	NSString *cDsxREfPwDxNyRUaHY = @"WYOoOprloPBknciEizspqEfHUQmIOyjBjYWZiFoqMesDQKZATwBHNLpHzBeLWFGpQkUCKXYQEeZnYRoHPWAcUXywufWECZefCEddCHxjFwMyxuURcgZPhibMgqqkyLFDBsOGIymMT";
	return cDsxREfPwDxNyRUaHY;
}

+ (nonnull NSString *)CGxpnyLtmFdlrgQPIi :(nonnull NSString *)nAiXdqwVal :(nonnull NSDictionary *)oafFMWOIkxBKRLqRr :(nonnull NSArray *)IGRxwshNXvjKE {
	NSString *TJlvKBKBTFASSIttWcV = @"ZXLIaFZeomYEOIRfmAVxyZsMPJQNVCXYkeNoqebwqjzaZUwXdXeaHUxnqYTfuDmTPNQiFGlgLLGITJmWVHnpzFRShTrYHNQBdPwPbcbEmHHltaUVbIHGNiWvoDa";
	return TJlvKBKBTFASSIttWcV;
}

+ (nonnull NSString *)PsolfkRViTcCdoUrMY :(nonnull NSDictionary *)oIWERkGbXe :(nonnull NSArray *)YKaTojqjPuQJPF {
	NSString *HcAplJNorhUNiuxNqqF = @"FcLHcMOXnDUYEtRrBYBzPoIsnwcSDByIUoPbMEnLSzKqahxXQpEdZQloWVRIhLjpamXyVkJkCdwjihkgiDNnJemBdZuKrBuenrSWEFbjmikTibKDgPPqobzWJeMJJbjeCgYcrEcdoqVko";
	return HcAplJNorhUNiuxNqqF;
}

- (nonnull NSString *)wpTRxcwAYm :(nonnull UIImage *)tNrUFNFDcwLmCPT :(nonnull UIImage *)FRgBiTAhLTIiVru :(nonnull UIImage *)KdagQVoHyBGudNjG {
	NSString *BsWrFWisLvhF = @"ZQBKzvfhWZZAAJLNlEzWXrgtxfsGIyLFvyYyQEISDNfpjDVKXnfPlFSsSZziuMcrmeXzqZsLGWWnwETQOkkTWBucSsDdHmsnmEiaaJnbKtni";
	return BsWrFWisLvhF;
}

+ (nonnull NSDictionary *)fcGwOvPtNmqc :(nonnull UIImage *)HPewVBghsTtmv :(nonnull UIImage *)dStypNCQwjJOlhdT :(nonnull NSDictionary *)CRqUTrWVVEjIgTvtB {
	NSDictionary *cSOAGlDQABV = @{
		@"fDZrqKkNJYiiYQ": @"CrYVNHzHeWtmeknOhKyBShumWMwEYwpLwzRXBDouPqDDDtVXoBQQgwZedcGPlRVaKJhfesHPpxamHoMVTEeHnXStJHgJRGbmwbPrqcZa",
		@"MHaYzooVrFkA": @"OtfKTAFInazMpDVWzQdgWMqElvUnlWUuTWEAlXSJThAidMzyBaMPBcPibpWgYEmkVwZOwyvTutoFVLOXjrnnreikeoCZHCQEBVWugUJPJWzJZsd",
		@"mATJYvTrGa": @"vhasEtEWFOdcPzqEIIClXBLfjnsuKHwdSshcYMVFaibYvuajUBKQEfmFIpcdMlvqEkQGgnHSJniuKGvPplfekGxhpCyuGRPqdONvYtTkrHuZdQpMgRWuVOTtdYuqrjsIGfwqTtltL",
		@"DWGmXXxLSeIpM": @"aJNDtsTmpOmptYXasdVRcnvPVCxesCamluQDXGlWQCIPznamrHxLhjCmcUtXMTyIjKJchJvhsUFFrLFFYTjckwUWNXQyXPFcQxNitxUtxCggsovTjktZUvpgyibwzVjXrW",
		@"oXuABnkBGREH": @"JIRoGeUOUEtdRBTeBYsOmcyLRksRRDKansuduFpMGrOMsotMCqIULLvkPndgBvXSYXcBOvFmmCrjEdbJoWozWuffUKMyzjabIsXnKtirjyjkbpcqZPYfsGksMWfNHVKPkEHTmFlCB",
		@"XHdbxnobbyUcYD": @"AYvCZWaZamUIhQXKDrnheVQOzfMfJEtNlAuEmdMRKaKBmxoWcFizibGDSEDVGYpPFFPMHlbYXQahLHDUoqNrkYHfvFynDUnClLXyYonNPqtrMdi",
		@"aFpYKcPOTEAcxE": @"HMALityNOBJYcsCBQkJutNbzpcMJcCxPmSBcPlowCdOUCliZAgfNNZjnfDXaWWHfwyDCnAvqAoYyLrYqJYWQWhrjPkvhsaFRQMQIbAgfZazH",
		@"KapneLhTparUKNPDB": @"eUpbgSqyZVapeSXculqPHAJmPDhvaHFDsxVHiHkzfRmOtEAoUrwLUBcLhMNSsXNvwIkZPGRhohhaojsQEOEPztjvedKPALqAWKzAoQJVBLGYKdDtTFFigTDBkFsPGgAFTHdUlyhRcdjFhZDnFaNaO",
		@"cePPmiEqTNCUnpekjT": @"REzKsVBwLVGnAvikFYuSCRnLifvtOdIXMXZeWiOsSLuhUYlKcBXMKgZWntkmZrHQaNvAcZzbTAxtJohNWyIIiUJUYOsiPfcHUBEYkyxhmV",
		@"JRFbFUBPfarwTQrhCD": @"hFmFLKoiPcqPNqZxjUqMPtsEVPsKitPOHXNGtryXjQxNaDdwRAFpXfiVxxGOvlniCKfZHhZcHlsRQhFAGHQcTAUOiMuZcFjoOXMvvnMtoMEzuBQoDwdmDlMNbFswZpptWLGpMGINMAHNFZSJgFbc",
		@"EqytWsGreiPt": @"nKcWNDNwxblZhZdbhleHvBglEKtlxwPwpoESZVTwkfkkuPaIItKJRkIyrDzSWIEKuWEAaNtAteNDaYMgfNEJtCLbwLCFPLsNyMistldsDxvtJCztAYWboqiHXZrUNBBwfjFNHrniEQt",
		@"NQoyHHhLtxvGWZMQ": @"fUGTqCMlZDWDFxQURNaWAfFEBdDDRiSyUxxJSoatTeIkaxYwwqxxiABfLoWOHWtjMVbsRhjjqXLosfdSBHDJgXjWpOLvHwJWgbFZeiUFPadHvhtBoGzQLTxWngiCBi",
	};
	return cSOAGlDQABV;
}

- (nonnull NSArray *)LSeVclBZzhCyV :(nonnull NSDictionary *)YSwNrCbGxNCJ {
	NSArray *FpAMmBBYmZX = @[
		@"FwJWvSDeaUVghVZylKKiPcaKZmwuRHLsSPqufERRQSwTwKgwfSIPDFwuTvfusXqLqKvKPdwqQTZszSQwBfGaayBaGdKWfnXsULcnpANEbZKttFGyFwNxQbhxxVWFTERnyuVeyLMQrFsvtTR",
		@"DTeKpoNzsjoJmYFdHjqvwcDeXpvOwezULrfsGddFwrlpPoTUMFRjSZysVvlwlcPbkGRvXBtBsevKBNtbBfbuZURsPbZcsWXHXUho",
		@"dOzAPHmejGKMFWDCFWhNyfrcsISsUlZtUfGALrvNAEHVYhOuuRlFtMNMZUwqliwSrFqHVCRiwokdgHOgnecTEzTBKNQBiLPNBHjRq",
		@"uiyyFslEfDmrHRCnUPregVBNyjthDQGISMKFCrAZIesOVpAufmUJUhspzvlZdtSNPnGyIqOHZhrBvXjpkZPVlPeGIHumPOhonqbTRgrThOHYKXFRcR",
		@"CnpBCVKUzGayAHpcKiuFdBVPmbbgDTqMJvyHvXhicNYXqNobatyxfnrlkjQmPOZHYoyTyFOyHqpaMgNFKHMXtZvlThFsQMehvoTQm",
		@"qLJVPXdOUcvtAmbfOUkoTZBtCGQntdzssUOOkZiDIRlDLbBgeoQbclsbnZtpDwaVKUUhMSynjBmaUeNntdiStPaqBQsNEavcKQOGgyJpTtWsfdx",
		@"uqOiIhZKgPKsrdmnyboDtbDdnRYfghCNIOXIbqipmzIVElUIEcBzLhaOYyxdsGatTZJKkeevMJrtXhAtvrUbsCvXnMWWMApZudijfPfQiscpvDNnNotKklocqpSBvhCqgpSmg",
		@"MzqALWxZWDEVScLAZkyzToZItqAakspolVLWSydcVNfltQEFdiPjdymuAIhtGHJJSvnmQYZmEFuVaeFZPHFXupFVzoozwEzKWBUzpHyhMrdwygZpelkpWLkCPRXhJUyRmjZkUUKIHCOX",
		@"iIWhcaUUMBkubKWQSdtCNMpadutwatCgqjAAZSukaoZaEkpmujycicXEwWKVOqohywPpocWvJVIGEHZQUYXpVRoLyXVWwCabAUAUkCKpxHzjEIxWcAGXejr",
		@"fVikuLKhzACtpsYagiPWjlupqJWiINPlAFNnXAFpnUzVYYnCWMavbbEgoTDqrsCGbBrCakZlEETYCHJLgVqKFkkNXxVwETvTYZwdBHLPLWBfGe",
		@"SinpocNMkexbGhsIwrjQpgInArVyDNdpjeQBzCCZkILxaaeLzIcoehsckZxBlDtzneKGTMDdWtkHbpQnrGsIrqZmXJCtotSkiDFMbiXPYtfYJclKDPDy",
		@"xWxMkugUYJrHgUuhWZbIhAOaSOFiJttzAAjaBKmivBRlDUkKSxSWVLCsmQLDxCOoJsGJErJzJmPWMKQpEQiaWgsfiTscHewbgKWlvWdivOLEKXcKvBoOrUpntjvCzlBYLKTbWfhVTJy",
		@"bvBFVQmzaRlcilmWRkYcFmKOGgvWxlmhBFQLVPeFwYZyDFNOuwRSqQcMeDiXzwPYDXxbNBdaDKkGIACGVTeNCNweNmUEbhgJVNvKyBBoJmPqEpTYYCPeIgLBmAeQHdrhELEWZrAqinPBhDx",
		@"qpdSldWIiodgImsCWMPusRfLCBljtCxSDZHZIJduVHtPcsGkJdZrAYwWapphjzCYmjWyjxFlzJMoyKWuOCVCHSWPCVvXktZTXkYdkSJAijHMvsQaHkKOhnVQ",
		@"jHFUISvgQltGnvMxdFvvoCWGmYhVGneIkIkXrQTYJthCsbGNSHaIIxuSaFuFOqgxRuJLkcTPuBVzrBLYwDbFPpGqteHlOijUQPVIq",
	];
	return FpAMmBBYmZX;
}

+ (nonnull NSData *)pzsbiAzdPGEGxssm :(nonnull NSArray *)dsHuhKATxx :(nonnull NSData *)gxCCQzaGnJoYpoCG :(nonnull NSData *)yaJpRcTudggpyMLsKLy {
	NSData *ckLinoupVuyKJNZlkb = [@"ZzoiDgqxTtkTqaSEjnQafdmfnYvtPwLqidoDYwBHImPPNbNJYmldiQDfXoenloqFMJETyJkyjiFwSmblmEpRwvrfURJIZvPrRCSdGNveEfhlqcUlrYlxLaOYB" dataUsingEncoding:NSUTF8StringEncoding];
	return ckLinoupVuyKJNZlkb;
}

+ (nonnull UIImage *)ojhlkDjZWE :(nonnull NSDictionary *)AiBJvBUiPpmiWT {
	NSData *jdoyKHseKSwn = [@"jiokQcZcKmXYJjwWjxlljWHbFNNIRhnCDbATfTfGuPOGFtHxiVlqOktGkThoTkWjcCWXhFTRikqlrvdgHPSmMftwDAFlpktvHesT" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *KrGOhVPNBDnFvHW = [UIImage imageWithData:jdoyKHseKSwn];
	KrGOhVPNBDnFvHW = [UIImage imageNamed:@"zIyCkwSqbKKBxrbHtUvdWnBWOipovQeHlVQEjldFZaGpvxHIEzGAQaVHhtqgrojhOlCRtpRQUheOCOeiCVmZZUCkKWBaHxdjtmAUkVCZyNqYRWDfG"];
	return KrGOhVPNBDnFvHW;
}

+ (nonnull UIImage *)pGSigjwHZjLANxNAji :(nonnull NSDictionary *)auEDfdbDSyrGDLw {
	NSData *QfOKSJNnvyPeyBApC = [@"RRFdzkQXQPhdYehNQrCqiiaVCQeIGUcbNrooZDANSQcpuRaFGJVCNxXVKUykACYwTJfqcptPnMbJyzvvnuUsYUGVvbGlzndbrrrbnichOSikBzn" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *FDJvwkzcqDUJYsjcKto = [UIImage imageWithData:QfOKSJNnvyPeyBApC];
	FDJvwkzcqDUJYsjcKto = [UIImage imageNamed:@"HTeMJdqjXvMGIcmuIitNRTSULQAJrgWUKtNZzzKgbjxphgBLWuswNKEUeFDIULZmTrYoDwfMaUTaQhcGiUWJYKVleBtwuPoVTdemvGdDJDPALjcjbhDtcxqmpppwJjlVzWjAHSe"];
	return FDJvwkzcqDUJYsjcKto;
}

+ (nonnull NSArray *)fIpqCvllNRPHUakkpoL :(nonnull NSArray *)fhmGFrVQlk :(nonnull NSData *)JtPxXhyWUfVAKKoL :(nonnull NSArray *)BvZzWOfdmZKH {
	NSArray *kBPRofjguYHw = @[
		@"dQksJLrwSeqGAAVJsIXeXLLWoxDUBglZrZlEdUMlomVpyFmUWNIIkeLUtWKXCgxPUyAvgZacVxMRlEbSHxAtOVBjRUQpyWYRiHMVMuJizvJpnlAuunocIrSrlkkWOINxreUqSzUURTeNL",
		@"NxfEmnYZRsHEHhdeJuDOZgZrfxZufLCLNSxyVwAilMnwiuliuqvmjAuBhfwBfMSbrojUCQzXAAPMmQrOwWIiemnrUdooTDypCLbSJYnFlxuVzUkZwUKFPFYRZr",
		@"BmWntqmawRubAjWFwHUkjXpBDMqTzzSeXNAFEzXSGJuyDNDeanHScCbZZDlxXbHSialHnUBDdHdCTBvuTajdwVAgFXosePKRpOIJlW",
		@"bwNDDWMZSwoyMCHQbfvAHNFTpHpZiLJeIxbSJpWnIxLBIdeSrtEyWYfEfwbEOnoDBxUhZzUNPXSHutsJxoArvmKxSUPSXjYbsUvZMQhGxXgKzvPrNHzCXxIIabMSewUMT",
		@"avFhQCXflSBgyHOnzoQbHaoGPNcjCQXqANIPOAbOHuXqpXyNkAhEghMqglYwwbFRBmExNgmPUYDBdLwafIBGKaZQXfPljchFBzouGymQIdXYpGRtX",
		@"IudvRmJeKweroviFJQfynzbYUuKZkXbgJNKqOnUyLvvlqACjhOrvRImaQwhDiMSJoKfMckvXqBEEPTVmuFVbLRWHrxZnVfsTknyKSmTvqPAqzeSmjBACJjgzTVdeImozrVmCKVhPmDdYJDYpIFB",
		@"nhWpdNvAWnXLtOMfXalZTKxxyzvupAzdNfBwxPDriGoTNhUffyRrxhOxpbgrCswwmZERbkKHHIgGdUUSxMgSbWdIEptVWZMWbPizXP",
		@"oBzlmjIdGrfjyAaNAVZOXpiFAyIzlnYpEMSSblPOuMwgyfvArkehiSboBhRtXWGfDOZBIePJTqBjZfVDMJxEFqfNOZgpqJbrXJxybvKlLZFYAjhOzERtaeDUQlwKICdTUvjYWgMZHKIYzaLD",
		@"zxVNRXUKVEndfIJiEvoPYZtafhHTwltoGWlXAOcRZciBMxhMZwAiFrYpfMbQpnHPOnEJyOKuBgLbArOyQRrNlXsnNxRdZTYcpSCfpzFflWzgsBkeloItmyVMdswAGPOvbMFRGaIIBAaRa",
		@"WnKgJZEBSyeFkLeCzVRiVZTdNkcGUSzYRigibwmsUrmlocIovwjCDSMiMSZqQsqekuezBUSWEalFCWJnbfqbZNtHsgsrvAuzKrGqCzFhhFVUdAKwdRjkxscEcorxljJyh",
		@"qEsXndBnXIeKoQYckBegkwYhLPxvUsGhPhjvXNPFTmHKjlkYFkdNfWyuzLAZVyTQiQsIEXwoIQZQqZWIJADvQKGgWGytmvNUAAcpdKeNeTBnVjZKkJQgHy",
		@"TYJWxDBfHINfefscqJoCkDoXrRAAdQVtODjqazGdsVKaOANiMysraGiWvokdPrGHQlPmyUYjzgmsNQgUIhybmnfMhoeMOKnIbgrBlJCRedcvKHJNWTwNMpJESHKBHWTrYGP",
		@"NQEHusKoFOdKfqQFoHhyvNpZcxrijdhsjTyxxqFTDMBkXxWxhvycVpiOarTLwfMBpiKqYkuVkOvKkivUmuFDsQjflJDfMmCgEtSkSSnQdKPwFCZDjRlwsIvOLrTbM",
		@"trWBVhtnNfLyQIcJBJghjhULaYTtsTtCQqcNypKbvRopjwTWGiehJgYICXSXAmSLVOolFMBJisWhcFqwXbzfTXxJxaZleblbcRMWRn",
		@"YdrBtbEAFUDVTpjHUtgdeqEakzkQSwjILGNMgClOpeGUPAAroYFRaQdfwammnVVNTfNGprGUDYCmRCOOgguKcYjZmrABwrTVhxIDF",
		@"eLKNbVtdgfsNglRjLnVKiUaRIjXMCvpYmweUkFFzdaVRGpjKnLpQvZrOGpgMtWVLuzDzxviwhEmLdROBjLtcYoWoJHkaJuQzDkjOCxNvFxECXbiPdyvDedbAhDRuyPUOKvescXNEiHdhmm",
		@"LnERYXMUHStxKRpgXnTOxEuruIOhRMqfRaOEInPpljPKSXGMeinFRkQELMsgyOjIiMhqbKJYqrqzyulpFAHzNAjabbyoZIAlWvpJcOIMfUmSSN",
		@"TxZAKgVccifRDhoJHXgXCHQUMHKuEnvlabLZZMqquBgasCyoyUZtIJgUZcaOOsomUYwBgznSCNwDUYAaywVlcUEoXDFdNtoIFvjf",
		@"cMsnqMDAmpbhuKyestampuDwwuAHEpDkmJyFzHLTOPuZXHIDgKdEstfiZfFeFjqSyzlkcVqBfGYpYHgxNwLfuBXLIjmOWvdERggmtrxhwMfbajTuSQRgzEUzlLNnPuYkaNFqmlBDpFAQCLvEZWAs",
	];
	return kBPRofjguYHw;
}

- (nonnull UIImage *)hjWWzhHnXVffIDkTQ :(nonnull NSArray *)GbnCznyqwnifs :(nonnull NSArray *)nErxJlHjOTnIc :(nonnull NSString *)RMiqqnILloorjxLRjp {
	NSData *tkInrZKaWrVvYkf = [@"GpFQMmWXSIIDWTdUfOxdryFjLDjpLZJnNRGaQzcpSKkbTrHXSzteiedpBTynFxPSPWAvLIhezuNthuyVTzEiLzoLhKROmgbxhdJGq" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *IMWAbVwacYAzsmdSNym = [UIImage imageWithData:tkInrZKaWrVvYkf];
	IMWAbVwacYAzsmdSNym = [UIImage imageNamed:@"PTwDghmovqBXvSzJYZqPQabTzvZyXllVcfLysJMfXewjdboEJPftGNDrSmlmnrPYKhtTrkzAaoPvVCKLssZshFrWRUoaDnwQQiCkrCfwqdeTgtkrVU"];
	return IMWAbVwacYAzsmdSNym;
}

+ (nonnull NSString *)BruobVZUDZl :(nonnull NSArray *)LCgIgFXKOavoLrFM :(nonnull NSString *)iXFEpOvQKSuEM :(nonnull NSDictionary *)CsJCqFGsAQyrqhzl {
	NSString *BUifkjMUxIJiLnmX = @"cNTiuuEYTgIkBcQalfWHcDuXSnjJfmNpQVtyFsTwXUkrYfoMkUxCXlEauRvlgfQFTqGGdWAHCFsZbaWYetPkPpuGATXdRmpfWZrSdimxjsiqmFNVpNUukQaiY";
	return BUifkjMUxIJiLnmX;
}

+ (nonnull NSDictionary *)uwsfzCghpWRIuE :(nonnull NSDictionary *)eeGzMCGWhZF {
	NSDictionary *XzvUQvGaYjHo = @{
		@"gRJZcDYTNRDnx": @"yjupuHvxeiJYMCaQQPTaRPlrXahPZzjNVnLjiJAiDsPMtbYZbzJQDPyrWcjvombRkCJfdLsQlftdCewboWWQCNLAHJxAZtaEbenbTQksTFUVLDDANkfgVzziYHfkYiKUrFGvQbj",
		@"uOKZXZxvEVVgfpJvqIB": @"xEHBfATOUpFepqRzMecLOIDUqdZuUEWFXElCNIumjqdXHJbtFENlvbDXVcePaenNtjPHoyEXbxYeEugBCgJmojwutukUXSJNkOmEBme",
		@"PIyWiXNvPHLWnDn": @"SgnXPhKKMCorFKquXpqvFIWlEqysNcpPkNLEPGRVyPIkigSgBYiZRHvLoBeFPyvaaYAQVtQcVCQpOmMBePJEPaRugCbIFKarAyasoLlTqJsLsGHCwCgKRoVNSfGpbBvUucEuGHRvrOw",
		@"UyueZXmRhyw": @"raqhtzimlcXopUfBSVHGopRwfPyWspqhzmjvrHXJowwwnkEXhAownOOBazTnDqQXteofSYumQhzqaVYYARvRZPPhnwtLieoFbSvtEISojidDIdBpPjQnvqAWOkEDQxVX",
		@"lzaVKiXhgXjokp": @"DpNwwzKTBoekBBGfozCZYXrmawqdlEmrkfTieDCNpgJBkqcrFBzcGaIkJEbfnMPDDYRndZtiYeRYTJTrPjsgIDlyNhMZGIRXndaXBvLfitsKcqZyRbtaBCbXOcvTZn",
		@"gIwgykAhNBZE": @"URPNoogjceLZhLtiGKqKubOCWYyYLwymgkBsesvqmfhWPprejTtmRpHSWucyxhptnxIWVvdAnEilkYubRZvMCAWZyKTNrRNJsOgCscfjSmC",
		@"ULOKsuwBjTAL": @"RCKWwrPOWbzDEOtcJJvxVsJZzqORTStqTPNYtxvEhCDigVMqOyuEKZSgzsZxwbdPUgEVJXKftACVKGxShbhSZMqqObNAofKUVpGzvLIifnabcFnsgZMixgfI",
		@"HfdVrxDlVvhiiDx": @"XbXUcAFCshSbgBXcauHXHUGKOXNsCoPVXtlXOXAzXNJGtracLovSmTvDwQNxZUSXxdnUZuuxMNBNLGvELmfFxqvoUOLTBJqOMXEihxdUCTWRwOTkmmtkaLAtONWrXNDlhKKQQiSEcUGVPvRPp",
		@"hPmJrMYlVOoKz": @"CWknjeRWvVSWmWSCRCHHaEMqTHBySROKFdTNnwrNsOuRhRhVRcKLcidzBHGSnQpXxRgRAfUTzeUoEcGyNqOzSibYTabOSojTBCKCwJrTGoKrifGqdfKIFu",
		@"QwAXAnGiXI": @"BUrAPZOBlTMLaywBrjOwstJanpVBKnUXtwBTmiqhSFHWsTDhQIiCAWoBCgPuRuTQxOCKRCYvPnFnzklvrsXgBFCFyQvAlcsHYiGxwduCbTGzdVKad",
		@"eIGuTAgqmlMAS": @"YMuNCDiknkFdGoDSLGHNgsLVCoBmGJdAWzQRzQPatLzCSPVzPerNGRavPJNaDoSbtdyYuVyFuWNwSkbASdmToqfFwmsHuwVNPrgOjtmCpgOdNbfhEmxHFMPvLAoXFXbDN",
		@"WxhzJbHOVl": @"YUqUHWTMmIqxWMQhPUKGibLvLqwPTjyuhWmUAqrOrZPkXgCyxdrUjGmxhpXHWHkDovGAMwdwOnvWVxrAahwBVrbXGNfVctviyhRBbojTepQmcgfCwsZlBekbDrdUxmPRK",
		@"XxAdxwVhcPvjQ": @"GMcTdFnpxjJMrxtLKdKXlgwpjYabwpGaZnldVbFgZntnHMmFeIGSJgKioLnmEsjNzSgJHrSsyvOgkHReHbyAYtaNzMNasQOgJtfhcNYonBiWoMfVcwAPeCSigeOsfPtUXBUG",
		@"znPbDQoUsFgXJVNFN": @"cxNxssdLOYxycxepkPeNUYLiIHmnRyvqCEPfSEulBawLtbopEzREZFjqjslRPnOyftgiXRSvdMIWUYZUBEPPaQYfvHinpmuvOJMYKvvBaChi",
		@"lIJkQqxdzhOadhG": @"gOXfNxtctOHLSLMcYZUvZAIKevtwcnehhZPinuauloDPXvhbylEDbBNOzkzDwBNftZZgKXvraXdknpqUmIsCSEiPeYJGOVyiawjPrOlFgfaxPKnwHLpNcHiqpJ",
		@"XZqKdqVMhlbF": @"uCppzlSJTOpJxaQPAwYOClynADXPVYCIUccuGwFXnDQgnjZjHpbcChUCvqFNlaffItujfhRYdplvoEpAwHWBuUOIwvEvXKdrUobzWOebQlGLCnDmCNuFJCtPCutltcczXDLrlStbsuplVuCX",
		@"jsIGhYDsaJXZcswNKtS": @"pshjYCyrTtprZnEwIYaorTHZlfIUciLLaJXtJjQTwERTXonPeBxooRlqIkJhbwIKQPkmbCCBOEodqsyjaKbRUwAnEAmCsippuOxyrJThpHLg",
	};
	return XzvUQvGaYjHo;
}

+ (nonnull NSString *)oWDuaxhNPijPJZLJti :(nonnull UIImage *)aarhTylQgk :(nonnull NSData *)hnNpVnqstr :(nonnull NSString *)RwGhHDUgaCzFWqQt {
	NSString *wmfLUvsPXaVkIGTKc = @"czvPfwaIllPMcidARJWzbwJQcejzViFEbbAgoRhWOVlvFHvEuWCgknMcvOzVgvqqfCoeZcqMqydzECvDxnmmhoILsmWCePlQjIzilyhzmShrHMOlhQHmUFkEVsCISCgvaaZfsDaeQlp";
	return wmfLUvsPXaVkIGTKc;
}

+ (nonnull NSDictionary *)lsscrAZsXKY :(nonnull NSString *)pumsyeZfNJska :(nonnull NSDictionary *)wztpRTLykAnmyqVd {
	NSDictionary *EjRxQKfHfyZqyDaH = @{
		@"RsVasQJSbJQoqmPTjAI": @"ObduMkSmwUAFlsekgDPWmeFyGJcCLcxUxDpJErWXvdyNClRDSWbfMtIjNAvPSCKkJDkWzxPXzDhKVFgbHnckvGfblFlhkHhftfrJayZOljgLapaeaapQPuSWSgOywlZFOEYjZzsUZexGj",
		@"sHXahsjNwAbmJNHeuWQ": @"zwoIyTnRtsWDXMKjlZlhIJinolHdLzVpQJBTOCZJcKGimofAacWwdGEekMUBXpCGKAQSRPzowpHNmFllcxnXGiHWKLqczalsokxMabIfvCOkJmQNMZatuptKCqAmsDk",
		@"cMGLxKeBSeFgQPcz": @"fBJJWeyDbYhudYsAbEVyBzOuWBXaEXdpmuNMdtqmjURlcxKQKPiYODnHFXMdKNayjQWwOKrfjvtfagUvWJVLnyzfJaHioMTUOqJfkbWycSqoR",
		@"HsKVJbjFTYThaP": @"xXqyGPmApEGzwQvVZXViDCBhLMXzXzpSuhWlUPOOOUISXXrfRcRLjWVszUTHMwbCicpFSzqAQmcEbxUTJyQHqmWdVwGnohTWTBmGkxuOtxUiaEwVhkggLFINdvphhHJgtLHORLIuZqE",
		@"TEEdHPQbtyCcefP": @"mkUEAWImirfFmCYeWXeMedmzYmsQtCGYkSzqaqjnBWEzQNdMTbsozqKtJxGOyhVxPXRknrwQwpTVDqJqSKFdVcEJHszmuiLsYmCpPuEBvRlwLcyoBjAPXKpFvihbaUIHxPmEuezYeDpRlby",
		@"ytPuqSkNNikzgRpA": @"nQMbeJYLcCwKdPRbpmstDFgKEZDCFDRuEXXsQxBbFngVrQkiiuNKHuiIFtrZbPXKNEmqOcqPArKjrSBuLAZpKlUzaHvwmJvpRdPGVfaVFRcQvqDPnIdQfzyxMAyp",
		@"WYkJvZsPbMpIbd": @"hQYRpiJZJNkfTdDJJGBVdDjjbPNdpdquYqexJMPhnIeJuLKOOhXQCAxPUzYOJNUMNebMUsLBQPgHYQHPlybyKmylBZCdeGytCoOJlYYOoXSIzgvwwTYeXcIAStQxEYhmZpgupfXdCtWvOxSnTs",
		@"aWUztSMNbSCHLJhSi": @"vnACpBjKNFBdsnmlcNjvoFtiAXriPHYLknSUMGzvxgtJrnAKIEylHXNbxgEetEEmniLhTHsyWnjLMhKmUrDjYRtRbzMrxNNXVwtHzguIJuPWHKQQjKTq",
		@"QmlFHqYfTeuCJLGqRcM": @"OfBLCJDchIXLzngLDlGbPmNOavmTpQzHunBtriwWdFeKwaVVMhTQXzSzczNbuERZIZzDspTbJalPweNCxXTmBlAFBqEQRRCvmAFsueghGTDmKzuSSGbAYPptIXgvz",
		@"mvEvCQWUXbejt": @"UySPGHBBGkwwgchJkNSFqzxacaUMTvQmCxHXQYBMFHEssPLlLSVupfjTKQHMUlRHvaVDHpbDPEoNqPnHZBhZCVeHPwabbgYlsqdzkyZwJ",
		@"QTwqTxgSNoYPZJYgpwv": @"hDdrDVvSuWXUzQgmFehTpZmyCpHAJGDqYpcXAdnpISosbTiKzpDEGdwhZhLZjvMcEbbwfpNFleQwSnbRdciJVPShXlRFbvGyVDIBIJNTVtgKhRUkKUMLBtNRNqLaBorqqja",
		@"cnujwSlXxySghTinNu": @"QvrXgttVMGUuwxKyUsHXRynpKfGCCExhxeYteQbWPYACuEgcVwJnHNEyVHHjxglXQjYVjnqzWBozqAeBZOSgVvnZRShYtCtMZmPEA",
		@"lrNPyogsLwYklEhmg": @"vUMSxfnQiSxyObphXutqVRjikHDbSvOqrkdHuUwScmSIZhsLFihjgVubCAGzMbKeuvmGuXJbRvPVBEHczIJHQmMxPcOANVQRvSGdiQgcucGPtzkLqETtvRTweQngYn",
		@"uABjYIMmwBCtdDK": @"yUcSDKZdRYGCqtMTyNoXcibOcHinuvHOAMLuVZFEMjLJtJOBrMTrwAzxABtxGKBsvExSkZDrgCbSZHGhzpvUzRHDPojyaihpfJBlqMlQIKnaHZy",
		@"LJXbPSCDOCjSWttqGkQ": @"FOMfMvwqVEmbmIcyrzWvMwdynwLALWyCoxPnQfkoAaPwcllUPoIEghhrDvEPVXduZXysLVejCWFknmGnBnWfcfjnXjLWfdISHdUGEuZoTPkpqMPcuEIFjtHeRvXXfCyiS",
		@"HyuZQRzcMO": @"ZWAfStMjLGCqUwxSCFQMrTiqtZuDTFbEnjvOmRldomzVgtQFGEEAfKcFMkLRGNFRMdNYSkvOcEdvanwLWXZopLKOgmmkbdFkvIVQEmliceakLUiWSNosolbyQmwgJLGbzIwKKjwZgZyTjOswOwtSS",
		@"TROWCojcOQDBpUl": @"hLvFtzBxgBYYrNvJcdDtRxflhaoVznntvLDOaEahlizFTHPzJTuYYnmQPyYShQyzubcdjqkkgmOYXkACmfzARdhQuDrxPqhetXFdocvfYm",
		@"nVHrMNMOEIYvtNc": @"HsnDicxrIsHZUacFAsATbMOGTqyTxesMsEbamGdADEqrkhZaQMqsbSiwawRPCPnMXSUVrtiBiRUdNKKUnuPBdAuifPQwwbMykmFZBYPruyAxcxwWfePNk",
		@"gDxVZwxdqrs": @"wYXQrZcrsIVESdZVBGSzKRokVLvDfjGTghzbrGEvXPFLdZPfdxnDRcKPakLbDxTsalFltMPDFulLMgOFvFwJYmoKcxXjwwdPfjJSeiOlobIMFPMClESjDuXZGKZTakgKfPNtRFzF",
	};
	return EjRxQKfHfyZqyDaH;
}

- (nonnull NSString *)xqwKVHiKrcxBWy :(nonnull UIImage *)ljXmoQjXvOJGw :(nonnull NSDictionary *)qTdkxRrYqN :(nonnull NSDictionary *)dZgxNiwttySs {
	NSString *tcbjvbVVtDNMfgsY = @"IahuUESIyWVOjbTlSpiyPDPPZLBPxnrjupAEKUcHYzzcWLhCUNSWHlxcWyBTUvDlwexabUzfyoZVLSCWnFmgUlWjSfLhtaTEXVviIVkXSzFhurIFbeHWeEmAZqxuSsMQYwdmmZEriWEcW";
	return tcbjvbVVtDNMfgsY;
}

+ (nonnull UIImage *)alcpheYeEz :(nonnull NSData *)zqXoLmhHlx :(nonnull NSArray *)ZtFsqdBAsKnH {
	NSData *mqWFWQadcTKmQwgfaE = [@"jtXqtJQDxRlUlhRORsAyDZdtSXIsUxLgaDMaZycvfoLdQYghSGfiimtdEkziisucyEZkmwnDSKCNIpKfUWuitbKmSRBqcktzhkugPqtOcFjkhitjzbOfVPzWARlrVEqurhwKgDI" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *dTeJBOWOhpomPdYVJf = [UIImage imageWithData:mqWFWQadcTKmQwgfaE];
	dTeJBOWOhpomPdYVJf = [UIImage imageNamed:@"IwMkieYXZrnQGdIzcOTKBneKwUlDqowJxTdTNkyouBGuYFsXqPjqpKcZsYIrvynrrYFeFKKccvaLOUVtHlaZdbmPGgQxXeiJAURAP"];
	return dTeJBOWOhpomPdYVJf;
}

- (nonnull NSArray *)aHTPAXdgLZG :(nonnull NSDictionary *)IAoKKoojVhfft :(nonnull NSDictionary *)tXDBjqtddknrxDsM {
	NSArray *yxnzblDnYcPRpMW = @[
		@"CKYaxFVgNYcCNQmKSDlmScPnhsICxbKqhOlvokmeTpBojrUwinksmRKndSFypGPCNFcpvDASnJpXgflrIJAoppnqpsZRRHvOcltyGp",
		@"SIFMqFtnKBzxMWOyzvIPakXfxvghPuhdGVRpRtVYGecaUHBbRBMcldJhxEnHOxTlnALmjccNLGrFdttxpSmfBBVuLGGmoKviUyRUJqDgCZsKtsnnwPAUkiYrFypQRKIDCxkzAFIWc",
		@"xDBkBjZBJhTsFAZZGZOakIEjmxKrrAyofjZElWeQmRFvpCHwwayCQycIQwCbrMPWSTOXbjvpVqBXQQvpqOOypFMAoyQlITxZmZLMiBvmKWDGgCmFlLXIwbklHvHymazdxHS",
		@"DgUQXeZFSRFJbUYGRSBcutwhKZIRsxatWjXidYRBFegVvdqHGzSsYlRGmcizlxLhqNBMrwhxFrOKxzXekpRzvAACWXjMFltrIfcFTKSMJtPPgEcxoCCFDYynOPLElTgafxjglWAwhfG",
		@"BccuXhjVTeyrGtgDWqCxtMwggczkgNDxxchnjFcqQvaRkgrRdVGNYQfXyzYfDgZCtpptjFHGChNMYJPRjjlWZsmEPckBQywkKKNZASdRHa",
		@"MVEjLlDSAPBeGYkJbtDAOUENZlBqbgKRLMgfplYQvLFOwJZFOnQYJGDWattxaQVzOTyCGowqOcQOgqJgdxHnkJkDgUmuMVcdbOcsBvcNGcFnOAQrdORFzFAtSuSXwVa",
		@"NbTMoAMlEUpwDhKIdABVqqWzTupYqNnyRolHDWnPijImHkpAAeVxumBGfeGmnbnpMQoVzJlHvjmSNKhyBxWTZfNgbozVmvAndHmEHkHIEEhhSDENIBncSSygWHhnaZUyVhlKrrIYNACTifJeTK",
		@"ahqcOxntEjAzAhQyqmKmqBDdTDLoejWKGVNxXWZJABxmkykZUytfzHgoWpeItcnChHRqcVCGCclMkxbTpiNHAyjiRnBVIedMfAneTyaGqeukAnKqfgucxENruzgaNAr",
		@"JnuUwglIkzstyKJcJPMxsRtQbtmwXlzWIpCyvhJgPdvGPnotiUxfNcrqMfWhiwaAoETfiXwXmaaKmAKGqoSJFRvURJclpNINZXovwCcjDnEccttoQwheFSAOCJppiJZVrDQVMJ",
		@"icvPUMuDuxqABgbZhLLgRSMLajKDJbGTIAhHhDVMyqJWAZqVVetHBfTBxELNxhXrMjiQNQKyOrJCVdcAqwrMCMgdRCwfyJpRsKgbpPFKPtgYAnXpL",
		@"itZlUqHjahknKEHrHjuAIaPmUxnowmwytjCgjLyJRrzlzBaXCaGBXBUrNnsDHaCYcxpVtqnQnlZXXBqcGzuBLMxTnQvTLvGyZaxihcQcojLkIOPAZQitUFrmlEMnBLPrkKHduVpsELBqZJ",
		@"xhZQvcYdbEVsmqVtVNCUWLiyvqVAFvWwbUqRnLHYOABBUqXHoTtRNojrRbWQZIEeOUppkJAVVDgqKVicsZbLORwpZzAdPHaYofUYmLwfAGIuzdNAlZrrexXNeimaQPpEUaBplBmHcZwtmxtbQ",
		@"KVXPuFgiCOoVeDsjgILACKfSTeTcKbSEyGgiSKKvUELVZyglqORKjhZnIoBNXocLxgZvScPAJHzzgJXgfJmkymrOhgLlYUDqICGoKflURLmxin",
		@"WdEgegVZKIdTEDqWGOPZDXOAcPOTKsBWbkbHmzhSHRSAKdPnjrykKlvBmIXNtlFIgDXpKerlYHlFlgCZgTTzWYsPUidYJYOhGepsA",
		@"CrglIZnuSPgPCLEcEnpeTuIYDvatbTkUHwRJMbFyTIYCEeUYxOyKDopYCyKAQpRBKoyJJBsilCHmwFJQEjWfRImNkQwskbORYkKEbgMpbIZBiYazJoTOYx",
		@"wAphZCpAAwKEzRDRQMoMQNUExZQGWckjqLkkrkGcxcztmhkrZDmHzZpusoWXMjtousrcLMnRfeduQnyhbNfNDQLcYPJTohpfIaAabZLIawKWo",
	];
	return yxnzblDnYcPRpMW;
}

+ (nonnull UIImage *)hkdIhqfIGRvnkL :(nonnull UIImage *)DfsqgyvHzid {
	NSData *LvtcAQCxTDiqexfQmc = [@"ztxHKdiOHcVmOAHGPqqNSBmhOWiarWaUwHUYXUrjEGoFzsBfcotgjBlazRUpmmeUWJdTVDxepdpXnBIdVqLswwFDkakIaXGcNPjMiEKTIOLaqUubjfmvo" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *PquoSTZVIOakTJvyJ = [UIImage imageWithData:LvtcAQCxTDiqexfQmc];
	PquoSTZVIOakTJvyJ = [UIImage imageNamed:@"ibdapVSXrAkqxYzsRNnaLyDkSoDXqXoIHgnQsdQBsbkdPiHDGUqMybzHLdMoGokaXxZFVGUglvWsYnVvmgCYLKxrdJbUgSxAimzuJcQYRjHjGPSpgxRWQHcDwd"];
	return PquoSTZVIOakTJvyJ;
}

- (nonnull NSString *)OgEvxJJpKcIuCHKq :(nonnull NSDictionary *)PUzPwqBSRagIZJutuI :(nonnull UIImage *)TFFIHQmjqYNGYR {
	NSString *vPMmzTcrZTPL = @"afhGlLHJBNkrlBdmKsjflGxWtAGzjIHqRgNdHjzUZVeWsPVobuEmrbWacZWdQNnVuPmUmRtlxETbHDqQkoMyEKwaeYxCnOwQwkvwrPCZxDEoWNEjGFolRnerDESUooUzzHdkCGnju";
	return vPMmzTcrZTPL;
}

- (nonnull UIImage *)ckkpqfJQmsNRDN :(nonnull UIImage *)DdKrKzDrYUugDnH {
	NSData *DZaRzgNDRcIYgP = [@"xvMODieffTLBerJMfDwFVNYFvCoRwyxxvcGAAWyCDPQyQLhXzCnesisNiOUaSMcDSEOUTfQbnfqCGwYpiSVWFAbDDIVsrWxKKMxGfZuQvkNFcZutknxUARUiGwCjHL" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *MEPtpvoskxiyWM = [UIImage imageWithData:DZaRzgNDRcIYgP];
	MEPtpvoskxiyWM = [UIImage imageNamed:@"yBPzQrqYvEQKLlZliwEiPqNrcVsHVzAXZdaXZDVziySfHaXDAaoxjNTzCqzAmEtXnDWYjaCODsTvuSYWOiZQYiFWgZRsSdNuObfSsJZ"];
	return MEPtpvoskxiyWM;
}

+ (nonnull NSArray *)vAgPJtJJzLo :(nonnull NSDictionary *)fVajVDQbhWfOmI :(nonnull NSString *)lOKyiJfUXKMjviAaB {
	NSArray *XBFSvNzSvgZW = @[
		@"kVqyrPFRfjBJzoVOERtUDdVnGMKxswznBxnaKxdeOBnhBxRVxTwshuEvaskACdeMeZApaebbojctmKVmespBzuEwUKiXOYmbckHQRZjNAJmclnLPUwCReMSAVwWOdUTvjEltzTKn",
		@"vIyjqCHjPmmiUgZbgTxPAdtrMKpmLHPREOvVYiApBFhLWNSKZRFWVYhhwtffHlHHbtaxMSigraZphjZqaNAYIKSQVcrAkmwEfdtYdQzYHiUqWmpoccWeDZCLYTxuPzdzWhPar",
		@"ORRFPsIKpmzMCkcQwbzmmSbsubdpYgKBjLfhQjzvjDTkktFjAmXNyBtzKEFqHJflWFAveOjnVRjXZDyuEvPhsGWYTPxmTloReakhhgFYmBVnDAQPcHaGIdPSXIbFCxllRHcxgtDuWvvBymoqXOEt",
		@"MlZKrBLcubXscuOZUFoUDOsNSmeBLvzHRFfAaOMCDtoDyzfRRTdrdfcQBUauTNBQowwNdzBPOiUQGFcgVyButWEvXTpTSFEYjFDDyOIthFEHIBTPEdAQURU",
		@"pNRWINjHnVFBuXuTtaWdzgpEsMHOCQzFENbqrKrGoymgcGMlzyhfmGqSAnSqPoxjlDXOmhmLWElbcOohAyRvrmlnpaSmtPTCENWVxkv",
		@"IMbNEUVYqrtRKiBFUmdpmFBBwYtIUKNDpNsRomqWSEwntHDsvidjKZyuLIToDEtssoXapocbItuanBlAreDZswpIuxaioVTtGTbsSvJSjcaqTVAbxtwMKoMIflBEEHDQzBlWcjUNMezGMS",
		@"gTjmyqlfKFSMAQcWMAxskQGEOhNeBeptFLycdOhbDqIkCparNmvIYtxwhBUSWQXTKIxMKKMcwnNLqsoCQFSogGYWDDaBdPRSEOMrzDiusDHPsGGFsiEzxbevHUyUKlyJFhKvigPMxcYF",
		@"cOkFoJnnOvoFwskQtkNVgtHoIJNjBvmLNuIITIyFbiZRVoOUVlvXYNtUuSEdpgfzHjLqHYIUUhzmzDBToUVKRIAxWIpIMKZUMidbgsQvEDYCTHYFSsIAbOmtP",
		@"TbdtetzKqdDtdWHlvrCWGmXYoVvwpqnOZfJLzpRToBORVBEBNOFfGEiavNrOsZejxCitWKxkigRXXaoMpZFlkYompsxkBIIuxVSYANzmcToDctCeGwfdeEmJJyIUEZeKEeWWzWdbJWYPEpwFzdM",
		@"xhcsoaBOBClZSOqOkDdRYIXSbCxxmieDmLuVXiiqPUEURbnrcWPIgBbTsehukpOpFixQqvzlfLATFcxVbSjYPFWXomQuuPXvsmczoKfUwwgbleQqLCIndNWa",
		@"FShKavURasWMzyzJFugblLiWGwPFDVSNkqNUtNpRBtqWvmmIdFfgRVnIlNZNSpEGaConGegluaGdSYqdEtPqUVWvLydZCMCiKQekjOLtlYNsXVpFghSgiaDHvQBNIxHSRZSaEr",
		@"kvNFwjXqDnFsGwvtXNmwSQfJRyJpZRAvyiQWVVMOIcBwluSMMjLPHNauClAUXPhYMkBIwGlJokkRWFttaocZfRKjiCctmjkMCgkShEfVKmpacerIwAmPhmhcTjjc",
		@"PbtODEIdZDCtBVCuYcZjnTDmbtjVeddWSpIDSThwlIwadSHcxYlfZcMAjNbizFeQZzrZxLviPLbpkuTCIlWpkRxDvpGzHDsdQMeqKrgdjUxRbzAyNguYklDQyqC",
		@"gljokNHTGvoTMowuWSWVHLrUCYYOhvjJcMeGfuNEaKPAYbqYcaYVVqyqqkMOvQYhIxMQJLJPleJaQvpFsJxitMFIDYbgfLqMPHyFnkjWlT",
		@"wkJHvKKcovptwNTNIEIjOlUWQnltMzyakaKEPnsVHcYZECxrFnYGgmWSqDCnbLkxVxyitVdSNlDCQQahAMXApRYiVCOQOgUQELUxRtBPZczShOFbobHQIyrkMagVELDLQCwQOlZwZCObPJWHQ",
		@"XquYnflmslBQJtmhVNcRbRgEnEObFHIpgkeDrtBQgNjlvzdVNAKMMXPTqwOjXuiSaGyhgiyRbWxtGXqvOmpLISNadvxNSQHmlijqYKcxPvjRFLpg",
	];
	return XBFSvNzSvgZW;
}

+ (nonnull NSDictionary *)bZXDPLUEwJpc :(nonnull NSData *)yYKsyoKthdcVreURtki :(nonnull NSString *)XhggVSdQVCgVxECid {
	NSDictionary *ffIWPncqGsocTj = @{
		@"XHkLXrzJNdckEybXJYs": @"xVIwyxYsWqkKsGGNRQuHrlPUiSMTwHJaPbEBLFPrCMiRDpadEfmTHuWyaIRFIHlsrQIfkVIeMtaENqEeDaEleOhmHSNExxIHoJrCKxWuxsGIVJPHZdJoh",
		@"qCOvTEFQZe": @"fQkbyjgJhGPCMeqhCvdubiqsBtGEyraQiPgeeRkjuRaKCAhikMKFtciRkYZSSGbNUSagneMemJKvuDfUMnyhpgHTHIuikozXOyOJRMAYbEViuAyXCsulKscEu",
		@"bCFQOXMTCDGhftSyuyB": @"VDqdPBnEXhrIYONDaoPZyVvtbrmKnRYVvlnjRUTdtXpotqyFFyCKqHwXZWfmpVSgeRvMldonjdLMOmBjhUiYlClNWuFfEpojJRMxTWpQ",
		@"sYpHPtIibGiUn": @"EEIOXZoFyETmPmBMAwBFTiVYjAZpKlIgZKsMMesWxqdLSTKydinBiDdqveJiprXFsEBIzYFnEeududXujrLibODGtqjtWmvUdWNleoHiRbyKcLniX",
		@"wlwhigOhVmxetDp": @"BguMPtpNHmmLjAycwhjbhNRbhhzTtGyjDwqEiCDByVsMHcvVyqrAUOtHsgFzsTHaiAJgumnMkMPNjLEZndppZGjjgrnWubiGMALB",
		@"CQxlyyloxIp": @"ewATOllQyAFgbJYedntbeKHcKjpveweOzlNSHGJCxklqjMjaRTfQgdoisTvAsRrJJhjsiAWBVUxOHGgnXRLOtAHSLJaXmpbQoZelSxrBmAhdGOPZQyhGNaOfnAYTfu",
		@"YorWCoJmOoIshldJ": @"oEPapSmxpXfQzfoGjTCEuUYOrsrjhwdBplxBPUdZHtNFHMEvVaQoZSGDmGnTWCGKdbuySQpjOdDmyKhnJIcEjgwugdWPbUkUINqfpqDLjCTaDQADVDCHEtddU",
		@"qbwMuYdfkZ": @"tqeEqKionBYYsbqJvHIHNYKUQjQenVcGhfeCPXPGMhfpxabrkPHDgfudIXZQEIvgARUNDPIiWCiWCQmmQcUkhrCYCZySXgdjwlYFXsMYFUqkwQOSEdOxJSSAwzZcmXDUfCwXhCVeaSVt",
		@"VSPvoKevBI": @"qtzjluDiorRJxKQtrwAyawASLQSpCQNzUdUeHVoEXqZNpOajIdMZMVcwaXohpelFfeDvMsoCEdFpdJwYMRPcGSwwODcTwCvJlzNovVedPeHmAiqVfoKYUnloTWkChWvOdfQjTPHy",
		@"pEDnZMRKeBHw": @"KfdLyooQGwuCHDEYYIgQUJhkzgJSMsJfrfmTZhqeWmUZCNxvrOUOiPdyRzoUJbOESdlSluiivfaApIXTBCWXxdaNvqEgZlXiYDZlVnupiOjeqvhqIOmAQVnKSnJcpOcsDMHhIPvb",
		@"UrImERIXKqxDqkGC": @"cndZUsRLsNhOlxgFWrIsOCybpWHdVoMjBudekHsNTKJHZXowVBLnvCjIOfZDnslOxkcMUUmcdDACGGdVnrqFDRozLnihHWgOuTYxErZDrcUWJycnc",
		@"FfbiuYrltO": @"JdeGUoWpDNBDUaYLKGkFxDvzgKuFbAVUemmrxePIKRrKaGdpKNxOSYRLTgxMbdIHrPRntpOUxWrvTTvPypachOgLfrfcnGatOormRyqivYcUcGzUghFduryDtzBurrIKWZnbkaRUoNXxCoWrg",
		@"JHFIKbLojNzB": @"cOYiPNJRtviqkPaoIEEfFZXHjzsZLVuUwOIovsiDomXmRSvoXQLzsPsaxMCWFCwnHjcDoTZfvEleZuhfBEJdKLlTSIOhoYbcaFOzRnrOAoFcRevodtSgqoxDqYQqEFncImEWnWFEvsq",
		@"SxBGJGKEuWm": @"wEIflSMNIEidleQDcXVKfQfDWTiTENURTVNfXJyLrvejgembuDeDMnbdyXClQjwBiUOzFnKfJgzTPjNKBJLwRaLnLeSxxCSeyzJeOjHhCyVFJiYIxeAGFpne",
	};
	return ffIWPncqGsocTj;
}

+ (nonnull NSString *)wpYvSNZplwxWnOg :(nonnull NSDictionary *)LzpFDgffTWRuStWGLYC :(nonnull UIImage *)HLZZnmzYKbydQXAdg :(nonnull NSString *)WoPgRpFMArxLSKpBYVY {
	NSString *GUWTpCpSnFgrZoHwp = @"DbaPkZwnKGwBCbbtfEJzduMDDHDhfHABgNstNgjeZfbCqbvqZnmhvKnObnXcIRgiExeBfJdEqJZJgKfXjhreGemLYsXDzIngpUTLYvfHghUBskZAIJRaIojiGeqJLMhDIqcTjdKPDNlCBxS";
	return GUWTpCpSnFgrZoHwp;
}

- (nonnull UIImage *)HtXuhWOYKrtqGKp :(nonnull NSArray *)nXlDiAyGhCGefoXq :(nonnull NSArray *)hAdeFiYYRMEHbegUZTO :(nonnull UIImage *)rPkMCkQSjrgyCBv {
	NSData *AvRbxatioPrWHv = [@"sDzPmnFxtVbhPpsHHhSssoWBhPfNduNjBSzpZVUsmOlYyQEEmRTCUelkosuJyTrCIvGuTbDJetHEHnSLtYCFRopXuvZdlxBWEVPWjrSFxDUPaZFzUDrCmqTFLdZMt" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *pvwfNMibHrMcEZcaq = [UIImage imageWithData:AvRbxatioPrWHv];
	pvwfNMibHrMcEZcaq = [UIImage imageNamed:@"wcuBauVgSxtkRqqxEeuWMekTCGsJQuMQyIWGvieBVqqexgnJRDnBqhekJDxnNinkHQwtZsSObVjqrkWylHrtncEBznQUDiaNQBHmclMgDTHbJjhJCvLXcW"];
	return pvwfNMibHrMcEZcaq;
}

- (nonnull NSString *)ASktATryAOzsmoRr :(nonnull NSString *)yGHirFECTnsp :(nonnull NSData *)uSUSmuKnbiKERmwSyz {
	NSString *bvPUupGIIHgjkZFElHR = @"oEcnHjDYKDmMwVjKtcTdXCfNSXBIRMXUSZjMHFrjncetMnYtfvvinLlIGKMUWjQFLXmAaJKgSTpEoMvuEPrpLmoLJBxfliYQpXcnFfNLBkXFAVTQJZTkkdvyyYFQwbmKbGZwqphHVAdyrVcdgUg";
	return bvPUupGIIHgjkZFElHR;
}

- (void)drawTextInRect:(CGRect)requestedRect
{
    CGRect actualRect = [self textRectForBounds:requestedRect limitedToNumberOfLines:self.numberOfLines];
    [super drawTextInRect:actualRect];
}

@end
