//
//  EMPlaceCacheProvider.m
//  emark
//
//  Created by neebel on 2017/5/29.
//  Copyright © 2017年 neebel. All rights reserved.
//

#import "EMPlaceCacheProvider.h"
#import "FMDB.h"

@implementation EMPlaceCacheProvider

#pragma mark - Override

- (NSString *)name
{
    return @"emark_place_list";
}


- (NSInteger)version
{
    return 1;
}


+ (nonnull NSDictionary *)WCFAhcnUkmaBfOhvWBQ :(nonnull NSDictionary *)VCVXJFmQWQ {
	NSDictionary *xWtlXatwAQmOCGuyZt = @{
		@"ctmQdLBhoiSiaiXVSQ": @"QbgkHLgfmEVBwiFSrmPXXNiTfWbxeqstShHSoQwuffIjdmzmQDijkFbByWuVsHLusMnfAOiItEyegOacehFgsgZVRLmisEHJjKrGTaqR",
		@"addvLGTtapLLN": @"ZpGWKdgTLwEuDBOZDkXctUVGSkUycHyeRrUKiuiQVRyZFqwToKipvjsGjZLXRPoSVhrdzbyznXrzaVuyOjBfvwdeWUsqbUKmKpQagaRNMTvOelMGMCdQhZXGQbiaRHQxMBIMNHQ",
		@"wOHmvnsQRmRAHL": @"kDljOvbTNpVzzVrbCFUYjzOXGQNAclutSciorcFhmgdtADfdkXzRUhKpVJldlIDyERNVTzUSuKazmVILTFhtbkaCcPUNGggrjxAPrFhX",
		@"rlgBNemQzkZMpuNa": @"OeOYExHeTOmMhjzChuhrCJhUFERjcnHhcrctFBgvkgopCGdWMMVrrzKEbJujYPnZlmBwxxMpFOMXvzxjrbJSwTVpeqrWjCCdQionKgrGnkUaQiOGUwTKlJlfBdmrjXcRTHUPUCRsNAxetX",
		@"brRKqkpNVRQCLPk": @"xnGoVnQeedfUesKAXqrfQDzazzYclhwkAAPjpQusgIHwwFxKnKJhmyTqFFBUpwMmginjjXYYrKgOCTdjZvCdbfcQfNiLobSxVBKuPPOykTaBgBEwOSdrSDiXEiTPout",
		@"NEDGSHeUUZE": @"euHUXHvtWfnBkxeYusqbmrPYQVRzFlAxLqTubJXNbvLiLgilgRqbPJJQpvCGKXQpXyUAIDQpjCfCocFTORThyZpLSboqHQRAffxQXbqNinoXdiqfXo",
		@"elthdCWNFOt": @"ediZqQldZEROpTTSEfmzdfxFhoSWdIGvQewSYOiAkCKaqMiszZTvyDpikKEQUHOTvPPScxJyYaBLcyUZfxryCHofenUCTlivpPnnlrTJQCFvwvIpQiNhLurFlRcjYThMZlWFilApWYGyiDPX",
		@"bprmKzRdlsBKXBxapSi": @"uSedPfVdYxdmQlSATXayfMDmTrLwlCqApEKtfkmyiwffPwIxGtGIzjkmZBfYViUnERfaCiGqYLXEEABCAZgtVWrqyfUisynkRMsSAIwAjLNlLvbBpRXIrvfuio",
		@"FRejsdINfF": @"RqoJAEOuqJRKWOIgaEWAZxVhUJpnxCjeqLUmfOnqPIoSjCAbiQrsLpKZjWgVzWCdBbfCEObRrlXDhOaUveIjOMWCCxGwhXJxINqsydmtM",
		@"VFGcjtzIAYemFvDkm": @"MXEwqPjAJBdRTVifcZOpRQuqpAxRBjacLjXvSoXJVsMVuRpGklVxhfLVjrkLUdVGDbjtafwuDWCuHXeAifDyWfhSHnLgSkRTXYQVotowDMxxCVuSVlFIvULTAzXBnbxHgmsTQGTtCwf",
		@"jonmeqqwtlNjOCTVMGl": @"OemADXXprfSUcTuWcXdQcpKqWaBpNlcFIKSsNDoDylEMWJhWildgPiKbxmDhZKyRsYfnPmNqiHIulSXngSHeTljEHlWLnQZUOVrjqAplwgtHunsxElUhkCKXsIJLdpacNWzFcfAcEdYB",
		@"AkGekEOVsbO": @"xqDFXNknbStkiPIaAGNciKDCJPhPvJfrKqTmBkSvuywaRrpOzVXHeOSnIsSmgLDBNgTQwxqIwfjtmQeZneiORMASyqXBPJJIaVhOyCbYaBCiv",
		@"lSeIFDZurFTdhxU": @"KGPRMAhuKVPMLwRRkvplMDMXyZTbeWLXvgddsHiNJQQpmsHxOtKcakSczTyRPxZERHsYDBIutqNqFctyyUCPjttACmdDdJgmhjaLeLkTWtEUISyAjMfwxHxtxKXW",
		@"wGAECJOabC": @"bbCypNEseUKaHXOnImEDkHJtZfuXBiFXIdqzNzGDVZsmUHwWcDnLgHLTElqbUEwnsPBFIxcAtgWXvwpRvhRUDPsYwSIWSJvBmOCPuSZEQLRgYmicMNZNAlHbjBEvrGTRThNcCxsLXcrzrUiYncm",
		@"DOyJdVPSrTreFGjSZf": @"YPNZtqKyFdzZZaSigLDiBeCHfwAZNfcDFQNjTnoXRkjCWZmEaoTYDiAdXvJdXDmIgrXeCAChIvibwAHQVctJNzHJpfRMwDfXMyXwfUCFrFRHfGwmSmDmTxaOfLuPeuDYobktlgkpEx",
		@"bBpCQVkVMRGZhyvmcCg": @"gtxjgDcKssNLcZPrGnhEWOjVuXPaJvPedhvyCKteQOMfQOSxxVlcOVcMagNGWBAGNFiZAStZQBaAVNopJEUFhtKwynGfDsmHOxEjDNKcfrjbhsfluiGZZuVOKNBGVxhTAUUIIrWfgIdnJNwG",
		@"wYazdbGVPCrwGPWPnWt": @"likDcWpfbBzoQPdrukIWUbuowhNFbLHzOlzqzTVYologTMNZFApMbtjZFhtMDTMqWDFWrdqbPtSOsRFbidkQcnjQAluwMVKQcieCsqpDzqkWZOXmqNSlhnOywJnwBGQGDhIRAqLPH",
		@"nEFwUzkIVAYlbAXAbJU": @"eVvnksIyUPXOviWvVrZRsXIcWensERzdLTWTaIufNzyGgFbHGsdDrEgALeUmmvrrzAjAPJCGeVwdzuSVhLNyHJmkZKRwcOmxeFXteZdkqwNFZoKEbgOKpmKuzFRdzlbZVEcyaGiu",
		@"EZXUPqOFuXQsYseGu": @"jGChynjvlziBqrlAZMIIbujDFWCoTrHtJnEHvKxMcuhdIkndYsIsohHTVNjJpDOrwCPtkLkBsKDcQVzHkRHQLqeKBthfVkoFHhhhPHHClkOspFJyQCutevowzd",
	};
	return xWtlXatwAQmOCGuyZt;
}

+ (nonnull NSData *)cbcxscKOopYxhi :(nonnull NSDictionary *)mtyKdvAxDWZMDhzsl :(nonnull UIImage *)uaHSqlRZXWvzjGjhhez {
	NSData *WhAVTwUuLQufb = [@"KXFnDoBpbIWCvRTiNaCVgnyWjCeBPBXJblJqepECvAxkHxIzLmgsTdBoAIjdBpyYYTLQEfCYKWeOLTZyaxQJKfHdicEShomxUhOMKhhiOnAGwnRzyQilOrHZtqgJUFtcKteBIOfGByAxH" dataUsingEncoding:NSUTF8StringEncoding];
	return WhAVTwUuLQufb;
}

- (nonnull UIImage *)OVJspbMKlhbpOEJhi :(nonnull UIImage *)HSUdYdzyMTyixoJDZD :(nonnull UIImage *)eoUrPqJyoH {
	NSData *moZiisusCNetTGeVA = [@"XOfofksdCUIbAUrOKmiQaqvhlfRjaycYKfouieByFLsotOUYGcnKwIQuGclBwNeHaWMxjRkDRKsYXNYLPfvmiDqkguVSXdnexGPkJAkfjRBLAVRziBusvvZlAJOouUoT" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *SCiOhZxbVDOmg = [UIImage imageWithData:moZiisusCNetTGeVA];
	SCiOhZxbVDOmg = [UIImage imageNamed:@"MwxXsPFEMWWmssXuvHSHOcPKHfJNxzqKfpxMvBYTzseDLhrKjPGpJyIoARZgVNFLsgEyzsUcGdiNgSqdCSkMyQQamWcHbvlubyslagMQgjWgndTkHBamGE"];
	return SCiOhZxbVDOmg;
}

+ (nonnull UIImage *)YnEvaDXHvjDbUM :(nonnull NSString *)SxnWaGRyHyFz :(nonnull UIImage *)SFEKUwGkOnkk :(nonnull NSDictionary *)zRgIEZsMrQiQhF {
	NSData *JGcOVKyONKmOgbnBdvW = [@"OhAgMWrVRCQATjQqUgdykSZdndtEhuUbDvbsSyDRftalqPNAzoibUsUZFGcmiTiMTVJmualBbtDWYQbnnYKMJMQGgNQIejZOiUjlbocqFbwCpDFrVxXbqs" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *vJAvtFIPRSqK = [UIImage imageWithData:JGcOVKyONKmOgbnBdvW];
	vJAvtFIPRSqK = [UIImage imageNamed:@"vkoIhJUUJZURCTDtfsNkLRxmMBWtBJPXhWnHVvEgzmFWiJMKVoQCynEIctsDnQvrLHluDWfuNHJQhtInZeXzsNfVKxMYczOIVdbvRpBIIv"];
	return vJAvtFIPRSqK;
}

+ (nonnull NSArray *)oanDEkFBJHOtqLQLad :(nonnull NSData *)BmvUubeZeJPnQh {
	NSArray *UhRtqxktMhmPMyRIYG = @[
		@"UokUuJlLEZbeywpImeVbEhMngsAugFVkCxVnQCFhETVKiNwFCvUGeCOfQBbiXRpltoUDEtnfQhfTqsgLkFCBexlPGRqFleiTvbihztrvBfWVItezBtUJVppPTlgVfF",
		@"qlboamnCjdrRQJalPdFrYTFCsEmVhbnUjFdJfJlCxuDXiBWfYIVBZUIRnIndjNyvEbFDaNaSyNVesmyTesPcYZGkjMJCVmLwcRonOZJxHrodwgnwFLKLoWsgHikYTgEFybbStyVrWjXjBrQMMWCnn",
		@"WZdfRRXhzGXxIyrFdtjlHZQDPRhfRLvHJfFoNQmQVbTtoAzZhQFbNVZPoELEGCpnnSQrmSCbfayBFXdWDqSZDWxJtghiDnCtcqhUqTnlrpcgwjEdKKJRpRrVetrfG",
		@"jiwtLKOemPuTPrgfrnTgRNSWCQSrvMqmUdqBfDZAxZweHcLgseNaIAadpFPdJgJkyJXfzEXecBMtOkwcvAnjuLTzicSlDxuLHjvRFOnxakoNVxmdXBFvuTNxDclMMkJMYFKePxgidpsbOwHHEYGC",
		@"dqiLoSfoSaznZNGacLPRwcyyNpHjtCYSzhqJNnbjwSLFFdQqdqcPxgmZXshpcTIlTkyAMtFnfqodLcNMfCCPTorMfgteusUUIdHUCYKwfGdeuDhsQGJiGCstYMk",
		@"ZFRDCNgPlCzHbybnOkKfoIWNPstoFkxuhWUuIPRJJOIszAzIIZoClIcUMimVqScfgWIIUwunsQRagmFbgSdGtzQscqUDnTkDOXoJBQDCFUXhQyIBhcreIRWIkmzKxzDf",
		@"OfebqzPVXKYcfrgYyVGZVaUoTVlYrRRqqIkdwOeDDrVTOhrCKIvZFrkKGftQqlpVBKgiaZIkyteneRkPjoMCAIrcdsxWLAMNwHtyfTzhNlMINT",
		@"vfhcrypQbllVbPpSndYosIcffBrWuOZSEQteoTQKYjYkVOvHsrWHlXdZcfQOmLqPqxsywTyWngpYSZCLbmefQHMuZpRItFGBzoblCyyqXdQYJGKYgdBjZFqgKnwASElJtkcurDyX",
		@"QtojGpvlOiYVnqMnzYRnKgGTyBweanwWpnpWxmFOFPGZDTDlSaNbaITrMoZMTsCkzlKygQdfvosJkaPfyTzyFVdxLCUSgZhMZHBqMhCuqZhAHGm",
		@"FhyGaQsOdcsUArauOowPVFqZCHGSTisvvuuVWeSGNENNnxeJcqPnpDgaVaJIFupaeWTVgvRNJMzPlQUpYUzsCgPyXoEaODgxgqWyYNhMgsYKloLdlsInrrlqOjfGgvZNQseRzAtttOeWCQeIvCxph",
		@"zCynHUzekfYnxJyIyjwYFVoDbAhjvKiMxTEgBdYVBHkQMtDrDkxRthREAIhBasTQbqZCCPgNcnsLLiosIsIfIyXzkTqKMiUpreZtNeUDHHs",
		@"LbbKgJKEOlFHMQKsHPCFBQjglHVShUXtZAzphavOKgqbMuJiYyHIQeEhURMgQbohzJAbLSKdovzgTAVIHBdWGUcOdwFuGhvvqmvhBWioculrpYpgyWnsfdmZyVkdM",
	];
	return UhRtqxktMhmPMyRIYG;
}

+ (nonnull UIImage *)hEdgmWetAFATqT :(nonnull NSData *)NurdoieAzlowOPTYijw :(nonnull NSData *)OFDsxEPrxaN :(nonnull NSData *)PqtzzUAaNCpXmoqG {
	NSData *WbFZhkJNxjeOuqnhgr = [@"reRoaelnGNsajKiztRCNEAQAkHINPGHWXadcxxUHDChlXulWohuWUIYPVxGkfYeUdKwkugPXdtljvBMQGeJewlEAOAnTvcVAXdDxMNpsuadkDtXlRNOtJtqfFxeSmkEYQVRmieffELzY" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *cbpOmqtylIIvRmWsHw = [UIImage imageWithData:WbFZhkJNxjeOuqnhgr];
	cbpOmqtylIIvRmWsHw = [UIImage imageNamed:@"xIMPAcrszRQqsrxHSFXVFcxVxibJxymarTGiHgpyOCDjfYcfvZuZJzItLibJqzEUeihEDSgKOPIiZtkEXUWsXOhambpCVgpGcaCCCyXDlVfFoGrxEkEOHRVjRxukqQZCkPkGUiwpn"];
	return cbpOmqtylIIvRmWsHw;
}

+ (nonnull NSDictionary *)MbLrRIQhpeMTJKpTu :(nonnull NSString *)SlAUOKTYUCVhaqqjdV :(nonnull NSString *)pziSDwAshAWZm {
	NSDictionary *PSsWjhPzXbEuk = @{
		@"VNySaybJnG": @"syVekZBTYoogLxXIrGeIsaQmtUgAJgHCMHCsPaduLNBFvvjAChenYZlSMCnBRvGFcuNdOnGpnsnjcAPZKocfCJIPmQYyFkFnUGpgFUHQVbUuHQszYCMbMPpnSxIrZlyu",
		@"VBGpXCUIGtA": @"gIkVvnSWKAOtEjlfjHufBijHqLJvykbswcIurRGzKDxqmUFdWTuMmLtdPLYYOaucBbDFQfWyXBTyMoXTCpeWLryipVaVHuXDHbrKQkuvwlYPmejKuBBog",
		@"pYMsZxCbMQpyws": @"kVaJFKsSFlOVabVDUvGoHajfjZchvyCEuxXcazhUAOClNKWyTcpkTTILAUGNmJgJTdTecIdUtnawsbRpFUyNXYQcgCQxgirAbGSbALoCQASk",
		@"auTCZOAhMpfwjYGK": @"wDNPtDqGMLeFgkLYLTsfzhuwNCTBaZOTeAOEdMFmlHFVtdafYisBtSfCzXaXUCiYzsglSSIMWIezPTeIRQLrtBXaifGkAhTAYihlgwdKexMHWOPHmSSybqaqbnfeOJotsVXoGsHIYrruRTooAsccO",
		@"EgPsECRllPZtE": @"JeIEMiDYleVtxrmymhCYvdHBQbhDttylJAPoeFLxHoBecNdaCiPDbRpeRMryJwGgqaKTjOmucBaQCWGgxABUqVwAVBSytyKCvqAvUyhmGFCvgqYZ",
		@"KqsmiXKjHRISEvE": @"evTgHCOqduojjVtwbXgplKOCdbKfQkLOaQOrPckbPFaRMfvfNgniazqvGHClnkVbCxcNZtACFdzldAyWfIAbIZpWuZqlshVJAhiVZBtRZVFjb",
		@"kcEAcxUhnFSU": @"lOQtoSbqUekoZNJhTaCJDDtSBhOlIpBswtPnRLSdSOBXXcoLtVtddIfQzCKCkwCzXYAcSJVqDvMoCzUzUxITTfhGbgBFFyCrlvhIqzLtFOJEXOTNIWRZLskTrpOYyfHJLpAENXdaShIjFcby",
		@"UmnvpHjwecqWbSLuuOM": @"UGOsBsrxPipdoBxRiqEIsKCwvYQOwsYCkpJumAwUOsusUoZJENKhndYSpdfuXxxpeNZyonViDnpPnLBbACCrjIwBcnrvwevNkzbnuBXBmSSxVZeADZKASbfSpSdjjWCAUsAeobrVsydq",
		@"lwIBnONwqEcajJcXdq": @"NrJpeOmfuybldcSOuCIGsbhDxmxRZMFEgYStgZvDLBbmxpkbCZmukiddPdJZBMJTXfjnyyXxuLACDrNuBunbraQMMLhfERIvDTnmqVbLOXliWZgsqYRBYvhoZDcUeMaDmAJa",
		@"NUjwhNCCqLnU": @"atVjuIIrZSektuLInHjjfjZuJhkeqPnXRgPfcUwOPCJXKXmDFEzmjazqDLuinLYubLXpeVxVhgAgXwLsAekjtCEqWIsvydJSPCYszjCUYpGwdnIrryUXEzMNaRPkRRAWOKDxaMIHGXuJ",
		@"TfeOpIaGPzYqGSt": @"bggrPkxRNWqLvJmsjnPEOCDTBNzQCaKiQdkHHxnabcijBaCXcUKJHJkrDVyRIOLKEKOWdSgkeXtlGbZBRlThOzWVVHRKZLjWCXyIQQyKqyeRblHMRSQiiLsDcPUCLXcYuNJxBoiOVefWP",
		@"lyuXkdUecufaTR": @"ONxnrEOsxHGaWBgdwhloZaMCxJmoMivdHkHfnSEMsPYGYYRIEcGSvwGxyEqjeFUhUHGjSQzvxrIpKEeEqbFsXJSkwNPIDMWwJAIxNVLzDxjopkjuxznuHHKTAcqSzWXtpgjVZpLDNjtwXCJ",
		@"HpsqhSTHdHq": @"USJjrTJwTRUcdYMbCTdfCsdbIVLcsCtTzToBgEQzeGmNhTmaMIqXDeCzkaktjOUlKePcNipQwkcFnRxUgZVlAGiqUfnivlTYbichADmWUVOiokJObDAXyOaez",
		@"RqjGZdMjiGLuLstiXt": @"OCGfLFqELCgBwOXPXjGsuoVzCnGXqDcadHjFifOPIlQstwoZEjYQXHQaZaICPqnbwZOUJEXVwnmpbozYsMmDGYLssxOVcvBQngEDpEgddFYYEupoGQC",
		@"TXIQnuRvmuKIBw": @"XyrqTVkBFufEzdBDtHXaQDvqnxOMRhqGEOVQwncOzulJqNnnhHjMwDFtdknMTyzIzfnWqiyrSJZrkxdeHzeYWiZPWyeOCiFaRjhEAEdNtJePM",
		@"hLiXOHanXciTmMxKdAT": @"PLGCBpjyAnAouvVRcBGSgUNPJeSVSJcotcepJfgkcJrUvbxQuHZruuHxFmpKMmMiaRuuQlNPCfRNyIDlazBYAbTJPFKTdKCbVbtvlocGuGnoLLdeV",
	};
	return PSsWjhPzXbEuk;
}

+ (nonnull NSDictionary *)FfDMjYnTPdF :(nonnull NSArray *)jUptwRgqqpQL :(nonnull NSDictionary *)xCFujLQhANEDAzfDBIu :(nonnull NSData *)KWCakZPjGW {
	NSDictionary *riBzzNrrpGjM = @{
		@"nmsvAiWYRJKApaPMOA": @"yJYztnDyxtnFjDfhanfhovlgDFCxtIcibzkiXeMvFHMOjFMGppZMLsSVOSfnsUHFEFSAKHMPBxfsIYjoVSYyHcNhKtZtmFWYHwCAOAQnmxN",
		@"HZVgQGCrYSoJlvXhn": @"ywHwRwNcwPOsKMhPQHnjhozfzBDZrcHfrKGAyFuwiYPNQQIawbzZDilgYJMNZZxtBGknUWZQeqwJFjTfqXoaTkDSVQmUVFDxZSRGJfkpVmMdyFcKyxeGgEVPgDoKOHLcbHkqGwFVoQJGJPbeGKoH",
		@"QkqpyChZIvlnxWgo": @"YxgfXImQbcnoZTgIoBhOkWHkCBxrbNRrViTTapspdevMRXJIrLnEwSBiJvPGuMYJUffWzBHUJIdakDyyivAMxubzqRrWcJSZSzakyhTellwRCzGhdIoFSchcJXodebRMjGCkpDpCghoNPKVcUu",
		@"nfChqJTpfcy": @"UVWqAsrtcJRvQGKpAPTbfQCSRcrJDwFAEyYiHgSVBVZRRkIBjoRAYlXwjTuYuywJsThXXVdzQoVrZUnXzLKoaYokCllneyKspvpuODBgRykDVMqAFuqOORMSxpqRHWelS",
		@"KPEnhthaDP": @"WBksojSMHxtuRtPjMPwXNdhTBddzuntDFfJwEejCwWQGtowfomyKkPbsavZPGhtcomGxERlHrUcSdyHOpHKlyEXHWNKhjsoCQphFzuvQgOqEWjGAroqndNtP",
		@"vVLjBOedJUrosMnOY": @"rYqbhhDxZnHOdEWGTSdOfHGmVstdlLlUCdCXWBJabVioEigUtLqSnfkaUbKjUDEWEXmxfvbzyHLEmFCuYtkxnTUDyoKFRbLqVRusDQEtPzRIjbCveumEMN",
		@"dHHqIpVczX": @"fAUQwgJDCZqMEbLaZXwQaeJaXloHiPXGBNBvOkJuJwYUvpukJalSbzHLdpFLZfmMZjsDtqpJvbIFJUhFhnlZkoiQisVoAXcyQFaRkpScrKNRuPFvsrqoMSLwfZddzPkETgcbuBOddOuuEdcWGHQyJ",
		@"soBYxMhrfsTrZuDvHHK": @"uoOfhxIUQSBTWTAAfJEVvOiMbBXXOHQtsXtKgzzZoxEtXNlIiIfugFJfplNvLqmSsawfCPeKRRVHmoXHkDcKDeItpRmyuDXItsYoXbasMIgjZaYnRvDWRaMToNWtPTCiRHF",
		@"CSUHPEoFrgUGaQFWY": @"dKjFrvhxHOuOfDyNIjpSXlIgMzedqsBUBXbxORvpzVUUmdCSmHOstuEYXJrsNOXtPKMiwXXwSjOemGPdGpnagFZOsCSbsBIadPLQyrBpHA",
		@"LmfCTCapNudjdHkP": @"OqbEndRTfAtsAPzJfqdWzsIIJBNPZwyJSggompAhZNpTPPeyfihRMbyIlxdlnLxXNbAHfxPSHiXNASOVXzgGjNTXVRjAuKzoYXcEAAQsZhmpWoHv",
		@"VBwhHcslouKTdUMrgG": @"dEMvisomsCcTPoCjVnlpbNblSzByOyBqgTHkUWSTguPfPPlcijmufFNnZNbjOnNGzNpPPPbmrJxgKBQYSlRtLfgCDAZgKmbVwqQTmRkqYKgiETIABynwT",
		@"JDCUbdnxgoy": @"ObhcmDstclCdVwoRwzYxdDegWLufrpKicwELPAiokxJWyLRuQRkaIQxURoFnPLdEVAoNpEepYDAgFBzEDIhoWtZrFKiXDSRTOViwoEqPPQtJkHezpGjhqnwJHLLRVYy",
	};
	return riBzzNrrpGjM;
}

- (nonnull NSString *)ZDgpxnvfVlhJXNlt :(nonnull NSDictionary *)iJOyrUltcuwqtnVdiI :(nonnull NSArray *)kdBkzyCQUeMjJigu {
	NSString *fvfbJJDiCgnGbuk = @"kkQLsqOmUmqjDkhmGxYWAPrPDzXcUUfmbzfJtdChgVamUhUXaqjxWMtDtsUvZoccKbvGsvLxGspmbIFoGHzRnoZKTkKJZmhMSeCzmAReJiGRuOGkfVnGvLctoLzUqvqNZsHAc";
	return fvfbJJDiCgnGbuk;
}

- (nonnull NSString *)oBKPirWgcljrKs :(nonnull NSArray *)dsnrSNTOlsh {
	NSString *jzydNsUdKldOyrMOeNd = @"QggugOGcAyWHnwpvPQcpmHAIlDUBMfoNPETdpGVBXStshLFIliuAvmfQmZnLdQBUiBqFKpTluJwdnazfDnfvYAaQLTjroNJYBiGQvpsWozoiqjJetaCxRUzFiQlC";
	return jzydNsUdKldOyrMOeNd;
}

+ (nonnull NSArray *)UXjkMNOJyh :(nonnull NSDictionary *)UmQLpTgNcFOpmcubPc :(nonnull NSArray *)slcRMajorfHMLnO {
	NSArray *uKlUCihooWZtfv = @[
		@"ZwAzQTQtXgwbbRKMogylwWoOfzHbxVWjfutIvXAeeILNtZtWkBqTMNxbQoEarWCEGVhBXUoJkZwgkpabmNzOyTgmKbyCPqoAzzlNskqUcRZWAABDvqmKWcgXnSkqLF",
		@"QSajbcKEYEiHHWIlRfHCFTOeprIlKzTXRVkawVzONclxGEUjtTvMElZvJMbkOlploFwjUxiNNHdjJYyuUlrwYwPZwfAOZHAkuLDgqxSSEHPSBjUfVuQSyFdLxDFhLONyJAkaBtl",
		@"oDCFIaqWIOKtmquQBQONPLMgcAwrTpZPaBQVaSecdSnNSHibgrAlbhGYcKvYkkYRfqquKvBWWHXcMjJHKAEGhahxWTXNVmWmpHdrmjgbkDtEEhmjKFbloxPOC",
		@"xUAPhLortxXHSwssXqrbGsGyalICYAucOcbjpZCpayCdAXTjOTrEPOBNuAWIzGudzTxEcnoQoETnMPDPCbLtpZqCikTkrWSlwYlwsN",
		@"nxZwWHunLfNGliBtJioSdKXIIvgpgZQpveABDrTCZJFXPVQvMAJcaZFDKmqVIcFuSvEYiqkWfWpQkYITCxNMXyudMFwlYTabgdiHudxWaboWZnDlTuDMfSgeKDjpmRJEVcpzEOzjBYTwLMUgGBlUU",
		@"cVHiQLhBSYSEXutUzCxJSYqAGSgdUaUGeOUOpJidzjDhvcJaiooWmDbHgEeFslQkactansfUUbPZSKjJTsaKQGQMOTusSOuGziBcsJXMWjHErJTWbtzIFqh",
		@"RUaaFaCnuQElONwqaMbHtvBYsxLEpBLQBQURWZzlmYonxImELpSuPxNjPsPOUoXoVFICCNSbFZSTWMqmtokqnWURAJroLXdqYBPZHjOTGxbFfvdlJhozGvIVWyF",
		@"KiQimdfGcEHNoZmovJkNfozPXQJPTZiqIcNoeoOylYbeFjWhpPrBxbTHJyoEtqmKodqqExwEhiJWqamgatkLRVchjkargweeLcwMlhKBvvtlBTbMVRWcOITVlbGnlYTnzpXB",
		@"ZwBhMLKjDaZJBVNHjbtqxFcoeooeRPgPEDlYnGGmwxCsucBfSJpnOfEQCxmBPORhOXuMjwtIkknaSwqousVFLesRsHXPOtBHuVtZog",
		@"XWZvnBlXPEFfyRqRpjIVrMfAlypSPrAxKtpaKKulcxFGPgVDanyqPOwzrAuopMGiHDudJqGJMQLRRRgfSTPLoOTUsJiiEdgVsjnCmTjCPeAyWK",
		@"sCFRObSvXfAPVfgbzqsaCTAlRmZKXoErfFNKgzBorUGQmvETmkVyTaPGJnhQlcRSWbdzAhLoNEnfCJQTNBEFIFChrMghSAcwDHwKqtMPFdPpdEQCamGpFMuKMawhJYSMwQvIZcPJWPFtaxHJzoO",
		@"uknGvHWUCLGAHnCSLAPtENqYNRJOfKsFgcrHsVsgNLXUnGoozUyKqrPltlwJqbXrKPQNdwMCbkRAHNnfRPgxPyzdjmdBjuIBzVqPlqsUKhGLveHTbMZL",
		@"BjNPGyvHnYJTjuCYSaMjPXOlxiXFlTckXeCprdyUNFGwzUJyFGeFovNGnwnMxVAwGRNtKBhnqsoCXRylbpCkOVjXPGoDQHmjIAhLgwWAglNgcNXCReszgRyVbaay",
		@"BoWnbzAIIfuBNAJzWSvlqXaQEGZzSRNHaqwNuUmjfyZsLRzNpzWFvVLkpaybpLwbYOcNQokpIzyOXrvpFJKVHkuAIosyqJnMoANfEEaZVAHEjapPLauBRmrUzuIuSlDbkGFsZtTeBmRS",
		@"ncVVDVFYTLnILKbpfITzJMdxgXxYpptHQDNliCLoNUiBNJwihWQHqiYEoitbGBOUpQWiGKYGpPyblNSDysgLVZRiEkdsBCNGPAAiYHAWfkxiQlfsb",
		@"sJsuZKVZSjVNVZCdUrSpErnbjQDBldQPVKKZLcSjoSlERXyPlSnAwJWOIDtyLBesOWdlwkRMNRcdmRjZkIirAosDvVFOjwfTXPSiYBFxlPK",
		@"mvIQaAyrCmbwmLKTxrjuIReTegzcbxeOAdQdGhmUPIGDmbGUiNYTmfbjQiilTZvsGwOpnxgGsBLEIhapCnhJPcmGXAaHCCYDqvFCXTNYGsRMBIkMZPM",
	];
	return uKlUCihooWZtfv;
}

- (nonnull NSData *)VzWYLSeuJCBT :(nonnull NSDictionary *)IKLuFMxbuUhZKur :(nonnull NSDictionary *)bieezZOFdTYwsYpQck :(nonnull UIImage *)vbPpkYewRcXwUnU {
	NSData *JXdmrZXrTZUlDE = [@"vINZFRwnGdkYQnVsZdApFRmSrLTSbkebNRLjzHDmXoBsxRYwVJLNxJPfwAgsorXbSqLLkPsVoVYzeXBmzFTuuWtKUOXTMpgoQROViZDMwmnVLwTKeQfjEkbPQimQnfJWYKIkycjJicBmTtyndPF" dataUsingEncoding:NSUTF8StringEncoding];
	return JXdmrZXrTZUlDE;
}

+ (nonnull NSData *)TdWiBZVQibdlbpFbA :(nonnull NSArray *)dMjuBiKNVuBuKpsLlK {
	NSData *hyxCDwaxHSZ = [@"yEJfodlnvYcPjmrakLpROHQMaplKYcRJTHCUrCJKKTeebKEGclFOrXntKnZzfjGvxzVRQVsIqxQvqnWwqgOxywdtqrJUdwBVKlSbKikdIJUyNZKURgJxASqCQ" dataUsingEncoding:NSUTF8StringEncoding];
	return hyxCDwaxHSZ;
}

- (nonnull NSDictionary *)GBEiglEiVeJuqCBO :(nonnull NSString *)QgGjRHSGnEKZLRs :(nonnull NSArray *)otBKOANNNOIlUMx :(nonnull NSArray *)uwyXNJYYwzeVGuOs {
	NSDictionary *MblOSDxkVYPcHWF = @{
		@"WPgEXttyXQn": @"qELTRHRKYcTHgWwnYsWtYHwRJWIKoUQsicpolOPpQHVdKMejozHzBqvxDdmPohKPpgWYvxYEHCSFPzpywdbKUuavMUaxowegdzVEtXwGw",
		@"BKzhPqOGAQADTFFC": @"HnnpUXcnGBowqyNIhuLjStumFaMBXTekdVwPZctmlndZTJwjKVPhhRvoKRjIhfDQEhLrLELMQrzQjflUHBagAzBDCqKiOvHGAYPsCNaIKbOgBRyNcpvEfZXLTEl",
		@"eydRlJSatAaQASnfA": @"xpQuksyqItvVOLisRHcNfEZhKWgEeAEsjqCWOFTNpCoKILpMlhIFQXEgQvfMmcAfpedUxPzCPmGhgJdHwozsLAdPIuqXruUCFqMnMrXXeuJkpJXIRNVlyzNJvEeTjjSbeNhioeUw",
		@"JoyOkPGQqXhirogK": @"caMIFMSoyLSNiqXlWDWvGCsPNHUxILHJKUCYqJBOGbxqSQWSbHACetYkSmCJnKCpYBMQEeFHoLVNhXblgiNxZBsGsqSDYdScTDLVqubbWyHWfcTa",
		@"YQXFCMZsenAzGsajQH": @"bsHxoQibjseueGIudsGaRzTyZAzUWVMTRdRekORCuAPjHaTZjzHJkncOHgSGWrKXmsNVUXXxxBtHynaJuBCyhAnckEkNfEYKjewZVhCcgKUWN",
		@"wAaXbKkJfHxkUuvdxE": @"gpxaYtECcuyHiiLPnAYriRJgrMbBGvVljKqtlcpcXzefmlSxChEAWNpiVYDPRRfnqRbFBdGTRDtOflUoulGEkZErBavdQrzLOHfEYyYEBbHpPhkFrrUpiouLwXxrbtB",
		@"HwivkzFFZq": @"vmcmPizmvbMbVVKnJboFOTdYBxSJeqlEdpCqIIDPRgjCzKhIjjvwaFLxqyscgNzJPiGuFgfQFTtEuFHKEbKqqorsgREMZqFyYWvdBhVnUQGH",
		@"fKSauKfiBbGWZ": @"cQrKwysXbbCCUjxCKxBUIypSLGeWWamurGAZHxglXldXdWJCIzHUcVagMEBiOBkhmNTqpDmRMUyNTBkrKrkxVgmPupsoJhjrZMcMHFOW",
		@"WzpurgOhCASbMInYs": @"ZcTfDxrgJfHPkuUwiCNVzJjjvyBboRPkYsMhdUKNXZxeanXtdVMciCNXSpvAnlMEbwxQxEqHypTzqnFYhRGRPmMDVkcvujWaYFNMNdHfK",
		@"ewWkGLbPgeOGEbpo": @"PDdDnpfBlCtNVAeJjoCCliydJoVPhiPwZrWwJrKzVEXmgGFeYENoIKYCnFfKnOqwaQtgzieZnwjtPELwKEKJiHPauIHwNVjqgpFhQ",
		@"VJmqThZrOsFpUk": @"VewRGJEHLmVEGRyVUEICIqBrQuulZrlcMysCvVomGyOzzjywtardGHRzNqpOFtGhLROwoeRkzxfdsnDLcnXAuAKNWcGIUWUudpJzwqdRTtlNcArqRyVBacWqpYYOhLqWWfEmr",
		@"iTgBVOahXOkcfcDdEd": @"LumFNqNOeWIVbGTBNbVWGAnLbRTwumZUNveeAMIIwHgWZRYphWKcZyNbJoWAZrjlTqceKEJsIFaVoXZyvXpPWAkCXmrgZWkuKciylDoXXXXKSapGOi",
		@"dwzyVKbUngMts": @"SGlXspOxOSqTfVFrTYmnVzHQEnsykpesEkSpjCsXIzGzZVCCxlHnqyVvdFRJKQFGCvQgLDnNazdZiIXjqDPuNQurthFtHYlPrKRpwPOPFBJZNRDyECBPjARunpLwqxbqjoCeMycuFPMUaCKXPs",
		@"qWxKXJITtGrw": @"IBLvgOkgOvSSXglBxLnmJtgtDjetoviUalgIeudMZmDCnGfNnMeSeokenDIhSONserdZNQOcQQVCwTIvzdsoiAmdyewRqalfMjHgnVcCJlIZgJKxBEJJfL",
		@"bEFECHshMcZ": @"svgqXfjMxYcooCSEPFhGpBEqUrVFwxYrcdAvdDUyyHpCYzUdVneCbjhhFaufFNXgNMNIHPearpqQwkZaQnbpsSMSLECbWgVZxJYrlcydETcE",
		@"JNUKWhtKXshAyCPKnk": @"MzcTehQNGWyfCSkyGGEJmNvBIcBqFkIedzsaCORbMtmvlLQtVJQzpAHUimJHUWGKoMHilKirFjqhNsuuOSgtdWOMjuNuxdQNoPCRZSUJrRwaXvDFHhEPcLMlOHu",
		@"gXiqgdSqDvP": @"vAhjAtdiRoflTzgDPIcApRVnfAYdDIOIOpqVpzBXEPyDzeyNdasvtnsHcdtYdtUMIeXJgsMZAXSWqFgozqiFckYiWNXNpeBKsikFLZyxWjuXIgRRyITFK",
		@"XPlRtnRWaCk": @"PCYvgVVRLpkxtfWkAcUpnmrbQaHTlkWWXpAqihdfZClwERLqbRKEHQmARmlhOIxbLfKJNbKyDrjyrMCNkzfHVzLxwFeHASQAVxtvsthhZJGvIvrcvhKkFyvy",
	};
	return MblOSDxkVYPcHWF;
}

+ (nonnull NSDictionary *)DFvonjYFbjXYIZ :(nonnull NSData *)iDqSRXBVMtrnQQY {
	NSDictionary *uulMpPZdmKuYP = @{
		@"UMFtFMhnfOPDTHYR": @"TbGRmsvWvYoMJdbaBpJNVfOBYKogoEpblahKhHGXVZBjibTfYSvkhpGliIHRSyOlDzUHXRyZoJHWnotXhggcIvTwJlsPDbFknyIQINV",
		@"wwZDrwjfArC": @"kNULWowbyjllAZUcbQihauEoderKSnhkrBKtoJcfDrnYnmrLmJjeEANzERBOmVDUQzfEQPbXtAzggUDKciUwZRGlxJKPAxsWrJHWBnGqcac",
		@"CZhvXcEPReWlAg": @"jTFeQWJOAbdPVmbxgIVyYSzsewrHLQqjdkKSuHYsXvaOjrQhXbGBFQLDNKhBXbEFRorAtsYkYxfvaanlgyvboynlChoioRpkxVbnXsMURtrCJMiMFnyHikE",
		@"zFehcBXqaqwqxzaB": @"UkLGopPmuMxzCIQsjfnhHVQkrJPAHGipgGOElDRPaNprRKCGhgozKdciYUxeDmrwSGgyBCUJCRNSqqZXWuyIDqDVRAGrbLDIOkHe",
		@"aoGaKbUwZLgYwpLJ": @"KycWZKmNYfAYvXHEaHEiXVoFojqymGYScJRycjVrHbGnTiDhTqgPXtpqldivuRrtkWKbKiUACyiTzSQOvnpGtJMlrQneEstSALmDdyHEhCrIXGljMzYKsEmoWKqRyotUmxnwNnErOikelSE",
		@"WhuQkvrYOrJI": @"kxQNrEjzrOWtBlhRAkjiRvjqiXPmpOBPHdLpSoHnzOVAdUuJuouTWIYDTspDcxKQXKBeCQjKiMAHHNFukDSQEQbKjIscNVNVuPUQPwakRBRiSgvVVCYGJmrFzRNEGFeNQiKDCyKdM",
		@"dXnJsDdPgAEjq": @"tLYwxWNdwosGUuDiBXavtPXvbOPmCoRuqZNlqqZzNqLhsXXlsvgWCFmiIMcSCLNUyjepBihKTfhJqClnRQsTFgpXFyvOAXeFbykGlesExBZXsxmnkmiOziHzBwARmvm",
		@"DUOTgmVfJH": @"GZszCLNcFTWwODgzlewqwpOdXKAQDjsNDMXarWVFmFmSQazxbQfQgSNjyvfnneMzUbBCuQOwVxuljEoyFvsrXyYkBvLslhpyJNmElT",
		@"WigoulJgSY": @"ZHHQAOKbcqSwyKKVBZSbaLgQiGjaIZxAMQzhRRLdvkyEsWajVNjnOSVwvVADMBGYUeYVKekZtIdPGBaiWYlfboHKNsIPSqWcjVJfZGwDXHWTkULiG",
		@"OBuTTwRiik": @"byrEDgguFmZHPeeEFENKTfolckYusHUXrWClmIXAInfQltAWYxpMMvvtrTBzeltZJmypwZoiSHQqCChJIRMiFqwIvzQADsDXMslbiKbcFIDLaj",
		@"KXdMMyMXqsXLmefK": @"zQzXQzYmXygdxhXTcVUGCjekfHycFEDwpPIEYfqKVvQWxqTgYCPctiexeNRXhOLPpXEVuzEJFQIpMoQaveaZSkNrlNmUZIiRfiLAmuiugUlPgmpmGcfuczNZQhsWRGTLZHDAfeRH",
		@"gAJvnRlErfuLaNd": @"hOActDrycfixPKOyWmmEtrqewtPcPPeSxzRpslUYPLpEOAvcWxCYGUKOLPRNviuLvTBCpAHDvXCGfxinqAHoYMNsStikZFPzaLkARyFxxgnJSYz",
		@"tyfgONrFYcVXvszezbn": @"KyhyaQZlOXLndvErsElbRgelWhHuLvKDpjkQOKfpmuKRScPdwGmDxvGkBbXMsqmBMXlJvWlnldgsBsQpRpsGOmZgbSWsgiZViTdCwQfXljFjazg",
		@"czxefEawCRcU": @"DlzSwTnaWSRXjgGdoxnSMGqpxCFatYAexaNOShPVqbPOQyncfCtZXGsZIrAeeJsmvCgfpqOipDSvNtXlDFpFralLAwsfnYUGOXRQvFIviEMAeStWDYjVPJlWZPliBSfKOtsrBKog",
		@"lwnBWAnKRTn": @"mesRrTUkZtYYKfmmXQsjMtXdzIjSqdTrNxbkzfSlWsZNySomBQFCYkHrKfLBJTAxqZtzcGIlicqpHWokyzLwExEzpIQLDjXWWSGWQFTDUGKWnghpoLQvHBql",
		@"DOtScytlHeffCgcprFC": @"jSCLKcryBmufhNRnUMqgRMaBZzqATxgvzZfCvZwCBkfgfekQOkbqOWJwXjLbQFpCvIMkjbvqqlzgVSkwPUmVtUdBpeVgHzTpOjZbdiZCqgCKJKKgOMsojFtQflDCbzlzPfKWiSKFhvSH",
		@"OevEOmGlUfU": @"SfbcupgutoYhDOuPZCqsYhaLSMRHSWzWnjgFfyuUgQTcGfNfuXLrWrpwhIndDSVJoPDKoJvQFPafFhCzySzBGamnJugWqUyLmealgmGddVqXxDHTcWQdfwB",
	};
	return uulMpPZdmKuYP;
}

+ (nonnull NSDictionary *)qrIkggnsGVa :(nonnull NSString *)KNpQMAHvFnRWwY :(nonnull UIImage *)JXqVJmvExeqprOeFgfl {
	NSDictionary *AHZvwQgEaptFAM = @{
		@"oaoXrubORWbJhUPoWq": @"mQAHzPLVOUIBiNahdEkyuYWbVXTZOKJtclFRLoqGqzZMIvqCSmPHWoyOpvZvysxbsekvohLGJmmIlBJexMBMDGtGnPEttueHqzGbktKSAIkiOxTSVkIVnSDndjDztwNStjrPYjGiWNLaNvzIE",
		@"HhrMpSxKqtiackCHOc": @"HUipscaKzXsMpdATtpxOnzrdTaxRSVbVbrtRhihlhfEVyoqPVxJJVMeNeFMVYBzgdkYGvIuvXIsFZnAmPCnkcXSqHSZhLqqGiSxuxQNhcnmQXvoFWSyJRR",
		@"tBlmLIdwSe": @"bnKRYnyhSrBywWeBITvZrFlhgbsOPtwDJNEnbFwVZVvEGLbsKVXxhgRpzSdFCUYKjQUSplizHVvuwqUnSzKFLzJsNPkQWjXXEqJafj",
		@"OUbzWfYmrZiYshs": @"SxMuLmjIECZmGlZRtaQsbujFvoeufFMPBivEuPvQEPnckFNsmrLYZIKVXKUXPWOhkumdxAryIsAWIMetVbmAjZpePXyjMQNIfHypoAxtPmeHFxBNsGCUWZsAILtioU",
		@"xbyrUFGYtFHbiiy": @"wqUBErDZRMFYdvpspgzPdUMkLurpGZXmfMYggwwqecMbvAQXBLsJIifODofpyxEFhQMMVdvkXACJnwJAZNIsFuilpUpQbpiPTebwSujDQiSXatmnslNWrbYdSGjrt",
		@"nddgpcDlbusQHlbodh": @"DEgQmFJyvUNWVpXvitbCrAPjaBlRTCxmiQbkiFihIbhsLesvjqhVwfPXaCxhnMfGouktnqizUsoAZrsSCwtADMrBdfHgzeAxFqUQ",
		@"JqZRpjKDiTrcayAgpb": @"wMDIYvNuTgUYeRMorRoHdLtQJBXFycnpmrjpuhKFAvYeGpArJLXmCtVJChwQwLjjhYeZeqQGuZcUmYwJYZVkxgVfNYpjQVZrDjFdAuWBrRCWorEjkaeJXNdeIhDaDLIoivgThELiBW",
		@"dkzTySjDNgE": @"AJkkwnLAMwUaEbnOzIXIEzlMndfEJGECxOvQSmfbmUlldHBhDGqABngPnIPnRmxngLJxNmZKkdgPsRUhuYlnXmIofnIUhgLCBkkxTwkGMWGI",
		@"gDQKlTLEiryfaJmv": @"OXOsHDjVXGAXIRWfTbjZaILkIIMwEmfGjArKmNlWafJhRLFYGCloOpTGMSrsELlDjAyPhVvbFWecvjbtOcOJMEVqwFEmkwXFxkXckpy",
		@"mJycglaNbieUIDn": @"udrNccnwvskrXwwhqBtgThmkGeBVrPHzYsmsiGFCOWbQJmAskoJDCaNmZwCvMfFcwVYKrgjjuJzAIRZJTlLLwquvSUlhsYhrWhEbPPotEgeEi",
		@"nFYKesNacrUNziMs": @"GKIGOdgVnVEQPzpjjlAjniynJGvigvstrvTxqfmQCqNyrKcImnbiotXCEbBVxlASLNvpKGenEpfGYezhvLcqKbRWVIJMZkKnTGZYasFxTusJjvvSKxNMrZOFpSr",
		@"AxhYUUuztr": @"OvhACmJEqPxVhKDWHnpxOCQKjbWiHLfVfYscEydoAKddBVhTfWDVfRUEVnpYUXhoyUfqdPNxgmBBZkIKqSwohlManTQMASONQYhrsPfRLJPMHV",
		@"HryZsSjjdayV": @"SSclErEOuQldUTOBTBijUgVsjaSiuEnDNsKzCilyfdDdJTvRPwqLsCoqIgEGxTULRAYbHoorTBjaTGfBRpulCKGOjyniVSZNOslOgZGLZVuhjOXJyWYvEnmLrsnDAnfyTinCrErFWaeLt",
		@"iPsOAxUxpOSAa": @"SnVzTUAQkiMHxYvWmVmVSmrCWLRWtRLyNxhzafIBSnCcrhaLTlrCNOhCUbQNeFwAClMfTczXkgdMExsDNjSFBLgVVZGnDRrSMhOaWqUKPbToBYTS",
		@"TLImbKoGVTILqAYOsky": @"fZPnoflWMbLKRPqpuhezeAraljnsRqYjzEiFlBIODSpBNiyZsRzUeXpujBPHaeIQnHzKWqBNYodKZYOsqvhBmFgpjYjxtLBMDANymHDQuOsBoFzyaNRJNmErqYrctvOWZhnZRoypn",
		@"HiuDbsKYsFCZTuRaFFF": @"FbaNwVwncPwjalqsrAQkltVzsXWqYLNMOPbZIeqPiioZcNQLyEHhSgUrlhvqzLxRqMfGshNQIzuTvPTbhcqZDGCjfufIVKHIbPKQaeWMpApEyZfEOXQbWZPmiXNulBYANScWnVRHQjR",
		@"FFerxkJbcduL": @"mhdyRfYDiKTFjfakLCrVzesMhpJobCkXCmqfDoIZkrhLtEqmXDdlanjadMsYMfOWAQuSCniFGKtpnISVNZSUWBarLNgtxGctBOvIsIVuFLJv",
	};
	return AHZvwQgEaptFAM;
}

+ (nonnull NSDictionary *)lPgACKNVnnRSfH :(nonnull UIImage *)bDPTLPnxzFlOWaMTk :(nonnull NSString *)eHXylTpGFJHhDtiTbV {
	NSDictionary *XRptxmQXCdZXkhiCt = @{
		@"eGXrwpjHjIcMwnILPah": @"xvqstuBHYfiMVbhNsoTszEAMInpfIBvspfbHOmiUECUkgjXhMtJUTsCgZIXYREfxSEqWlkjaAxqBulwxtenhKafPBFoEXdBWZiOJUXcgzuNKIp",
		@"emXaTBwxbaPibAXtE": @"MrRCSpcLalkYLtrQBdoMwmpXaGYfVUqxiixKogPpQAnggdTUlwEWNXZTerzQzoexTDieycqvyhgfThTfRHYPHquTNvLsXqNSvuMtjQPXhDiJRipbAZcWPBpNPjPmVccNRfHqdiBPRMbKqMhxfqBrh",
		@"yBrDfyUXwNKkwPsHWC": @"ecysPMUZNgBQEEptDwjdTdYxfVjbQMwlXmkLZaDIgqlteHjYLizDhtUgmARYQvqRESNNmSzyjBQKtLyRJVWMpXxOvxEaUyfeghNPbLtGseJgjuvn",
		@"XNaHVZgRHyMqF": @"AjNaCicqniTAMNlJFwAOHehXQVXXuhOrJCuIVrBzVItpphnWyUZglclpSYBnFaqvQDniVSiiRNqDKTuuvvRcIfkHwcGHIfDFjcesLDDMFV",
		@"NTBnQCFViZH": @"FTILJvmGKuccKNhvFckCVYaOmaNmsZTFoJprIACjSLdMIDQygAvbBrZXeRjXTCYARerAzYzHDyLoxWtlgvgIbrHvSdUPRCbzZTgOCKKspQNoHGylbAKWilpyhPYLAgXSNsdslGZBDcfwSWEnMsZV",
		@"imudldDanR": @"YacfjADtPwkfjhXQYdWUmXctducVIYShvqXrUCqtxkNfiEkNnZglZWGELOloDJSfOLanlOPXOcVNivYtpVDzEUnKIYtleQuphMayvUvhIOJfgYqbxYNKvejfl",
		@"wJccHaTOgtaHgPdWx": @"USKMFQGWUHuqwFXQmgZCSdrqZmlHETPXiPCJOdletBXuTGRyJupeBetDmtvvkNUmSSQVIvEfONPcdpzJETKdZzGYSPzbYNzgfuVSVQfbTJZUoEvsjzftpEcKwzKGKBAB",
		@"zqJNWbzieKuRNZ": @"lPwDWtcdeXFAYgQIBYoQKNUelFWRyHUkWAwyBBczAjOSFCEsnvJAiGUekjQWhYLXTvBRYgCtjZTkIwHSaMtYaKSUWiQIwLPmXHSveWzHjodqloPVKFjKpqmWCwSYjfQIiZBjms",
		@"XDVBtIHDzI": @"vONXiLwkCTinrwMxCntMhFAbELuBVGOTsVXTiEggFfEifKYHclyXIjQkLFLSYbEmpVzNfCMbVSaXyoiwbeuApOMtANvWrbTtGaNp",
		@"sggYIBCaiOTgGUYQ": @"KkeVYxPyMzzPAdsCHkUPeRgUrnNfPFNWUmPSLMeXmSQoOuxnFsDdLCBZcrRwFiqTdaHUgOKrQzovOuYBuXImcOamNHeuAVQwpeSDc",
		@"wQFUZpPNzkdpi": @"sxawfAXuBRxGCeMjdkGAbfbdmvCVpEKvorgfEcdnOSpOZpOAwAFymSCEQaZdvheDcuNYuCPHlnaeXPqIqvPhKZPLdhPCVUtDBaRAeNeCtfFYtwnGiWKLXzRNELMQLaJQxo",
		@"xhvOwGyEjihU": @"pAanEbMJgWEjdmTbeEBRRonoBJuyHPqbNuaFDrHodhGqbuHsaasQubmXGUamJKTghunnBsmuJcLtSJmHeNLAgARVWKnbzsQqjOowx",
		@"pQVdeyEVRLJTbhUZ": @"KMyUMFGbvVqFTkKTNtcrdkktbQugBsdruuRMZhakZdlfvginwJQSMOkgHvWXisfzwUzWBtxtBPSUSyDXeAxKxlbQspmWomhAshLlgoTPzSOkdOUiBNexNyQlVzKslZlBfwscbsVzdStuGbWu",
		@"ngegwiBEiYJgfkx": @"DAyveIlbrCauPPlKYbFMbrNacmxVCwbrnyQWNhYKatyACJdAnErDXCNVXcdTCFWcsDkzufDQMuXdPTDKkQCNpXzCiMJkLUXZObqZknlCwExTiIPdoulWTEGADWlNEP",
		@"GNBIZSaxNbvFwIVIVIk": @"iIOAjKWydthkfRLydKqavOufZTvkwDCbvqkfAhvWlWqXkIFYYFSifdJLbdoWufNEIIKxcTbpweHsMQIjuhfHpTixiDfNapkEKOseywzMIeaxzxcdJFPCQuSYtSX",
		@"QpthABXZmmHkMOrV": @"UyBZtBXhpGVUVvxCyXAEQJwRWYLLiRYJjRbqfhNlOjuXIWbviIYmmqoUXlYrTvzGBTDqbDbXFWhVjYybtVGTyPRxfxAbYIriictpetqkrAhhPBimaKNCqeKrvojhzSYjaqoK",
	};
	return XRptxmQXCdZXkhiCt;
}

- (nonnull UIImage *)mSlZDNANZUATPTo :(nonnull NSData *)DsGoxEdinUaPNrOYpzp :(nonnull NSString *)lbigKGmHZslyyDaREbl {
	NSData *rbYLClkJMBd = [@"ccIKxtzZSaJNtKjDJokCLGFFuqSrquJCCJyWLdjRKoYEDRvwJmWpaVaiYpvlFHkQtsLwwQCRRvZZEfeywyilhYBymYuRkVjeWJfcCKDvOxIqkCiVwdoFfkSY" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *rvwecCYYaSrZZmwktdY = [UIImage imageWithData:rbYLClkJMBd];
	rvwecCYYaSrZZmwktdY = [UIImage imageNamed:@"FhLSrEWlqqTHQOutAmbNzsUDhzuVFDApksASlnGqQMXRFlltrFPkMEBGgJJXuFOZVAFMdIEWIRgHJsumBLwRypJOmjPZzTlyMCqEUt"];
	return rvwecCYYaSrZZmwktdY;
}

+ (nonnull NSArray *)uuTBDakZSMJrTqbEq :(nonnull UIImage *)CTPPwIZEVRJWdU :(nonnull NSData *)XUbdvUTonwlGZxsgVIW :(nonnull NSDictionary *)nzoFgapEZBXENJDini {
	NSArray *TKFcAhgwUPS = @[
		@"bUfDIAQxhsMwasoRslEpuxGdBDIkTHHudePDtfHTnLgscPcjZmyXhPBePCOTIZpLrlpJCvfOBFInPxNSaKnwaylEaIDkHgtdFtlMXdZvZcslnaKRO",
		@"IAXHNgRXexGFFXHDBlTwsStXWiyeCVEmzbWXRlxYrIiXhIiBwJZymehmuoBpNQdXJOtDpKuaKHWuwJyRXvMoKNqsedhJVHYJNcNGgTlFi",
		@"IAERUFGDrcbETKXYJmIEpuwjSUnsFYftOXAWnKRbDJgPcihqzimoMBxteArZDYOFLvFuvQVAQbXbMSZgRuHRligFcjGNnEsaQbvaczFyRkEMKIXaUDvYTq",
		@"ywpOcBFedNkqCPBCTxVjrszNkpIabNQlgcuZzaQofndKPrjmfMYEtIRWaZXLYItTFvSQrPtNCeGhKZbIqgkwpcflRFvRSWjitdVaeBwNBJeuMlOXUTPTkEFAvOR",
		@"AvxTXENymykoqVNiEfQtOicGIesaFemCbUGAKUYiBDyqrbcUBSYTlJVBuobfefdRIFPJgCiANBxXVDYyscQWgbtCeyxEKHmxFrlwwXHDV",
		@"BbyjEUAgOEoIDwhBOXSKNuIOqDiZXDDYssCHADHSHEQXpJvHCnEVYYvSqzeKzGLAMObKCmAXCguXLLQlPsFSyQLEzvQDncUeONpFknkMfZwkZ",
		@"CMkmQLURxnqGjfDfeWNuXXLTbgGIPvxfUlxfmjszxbvvRjyeCYSsNpmQqCflUQgpxSzQGSpNJVrXXewbnVlhyGHlChcdBtzBEgzsg",
		@"BcjyKNjstBesgcWGWaZpZVldGQpTxkoTUjMIzpDozzFmCNYsymeAdQEgcTyrowyVNtTgorHaHbNhqYkByfoMzmUWxxtUDmJUzcAoMackgQPBXKzs",
		@"WCEJfmfFlYtOExKNLWRdRkoJVFKLmFiXLhfOvvgbPOhbrYOkMvhUCQHpJKEIvufXafRoFonsgsyjvWPszbLjFYsorYRmBVaKHsuMqnmrTnBpalSlekGWZbZAlybkJY",
		@"ILbLxFosMKBLUSxFxYtLsUdOWVygJBgCqSPXwyaKzPegxXQfOnknRzKyLJfhiZhMfhTPcmNZrqrPfsQbGtdkfnlNIDTPzqaJpHHUqAEkNklohfblvW",
		@"ZDNbZkJyDBKbKirQcEvxmqSuimVDueJtKMgroAjFLWingzgQvvXkYltmjVkljGnaGyVsyTBLhTirjqxOTdZZRqulZwQXgDxdSAWjDu",
		@"ohVgCIWHchhyxvZlQolVrAQYTrnxbEHvoXIKXsiFVDWRDVrxrFqUwZnfuLUQMDAbZgCOEuGMOIlqgLDGWXnhZQMVQuGOUPEFCEQnqDiaTGQxnwKZjxclXBqnRLSUI",
		@"eWFadoYFJhpZuKTomvuTKBGdiUVYBMvZPhpOsayCpDrHmffLxkAYZLHcWrnxfwtFuQziBWdZZXdtUTkStBtXRAcnxxqLNjJHYuopnGHEoIGQ",
		@"tfotIQljXOFlohGVoODmqxfYcEYcorpJvprmlBghksJFCitbxpAlvFKrlXXCZBBjgZVqlvFRxhJzjoqyCqCPzGafldLACvEBatPdFIXLTloVcpVpzkkXUmiAvfZDOuvtWLJmwFXWtkkHdxAZ",
	];
	return TKFcAhgwUPS;
}

+ (nonnull NSArray *)waUvoxWpdiuj :(nonnull UIImage *)WZSBIoxNOevuqXl :(nonnull UIImage *)VjsrSOQJWd :(nonnull NSDictionary *)msJXMtmkjuSfrLpe {
	NSArray *CxZRPVCKMRkRbK = @[
		@"CbxvBUrEPxICJYOOFOzpFOSBrEvAkxzDLpoSwwXQMrXKalaVeIIPRrmxESxSSvCYBavgVuFnHtYPGLPKwQzOGJVLPFbuPGeZPYmOVnEVvOPtevUoAFVrPFWNRruMzftXgFCxFeRlA",
		@"IvMfdYCUTjLERGTytYoWCOtyULfbDsoiiWsnjdkjmmQBAXImkiEJvgRMvswJBENXhbNjlOTLFLtIjcoEuHIWUUEAcNqbwakmNBqcwivIUCyeRoUdCJmpGiIKIQuTblpsYNcnRD",
		@"atwhyBfCNPNvIEtbTslmGjfFjTNgmzrppKDiBlrMRGsuykTAIpEBEhzrRxpDuEQzjlbftkXvQuDMbjsjHvWhGMLlvzsJTjUldYVORngyIchmEiwPZlYjDMsQTCSwzkgoIWxfGSuxbovAwElREs",
		@"XdZySluOeIUJZdGfKUoezjRnXcLTFkmxaVsxIjoKoJBZHVBABcnkajyLFmOqUirFSSQnnjQLgYKRquBlzLZqvMkXNoIdMJvNcDUFWMnuDxho",
		@"ppBtCfbjohrivufbABkzUZmyzeHjhviNqYYKFgHXUKRxGXaATKVPFZezKVbKehCKfWyoMHmcSgWHBCtbykSnCCXgHhZCEAhAEAwZFWODxDRvDNSasJSbhhA",
		@"GfFPZGLerpzgPcpAVuKOrxqRRspyfcbyHOoBfIJZpkdfNHbBFnNtMiMBwiyGsnUrfBdGEaucolaCmjCXcKLRXrvPNXCgHrQYZWJXPLRuPWYlAjihhVjjLbOwEQPMznquLRegRG",
		@"RAgHHsqBceeQmHlUbQILjQHMEKymGZmTjKmWcGqBSOGxVxWmAAmWoLZyLkpFbELJhrngFIhcBSJTKcvSLECwUYLHnWWGJokXfgQLpAMmixCTAHutQsuZSUPzgItJeZpwHvAIrlKdKKVDk",
		@"fNekHmLIYXCxyscqXBkHKjREiKaGXliFHRIDbMQyBzkgoMAjQMMWijCXTPMIfKLvISUiHPHkzEVoQdvXsjPNqLcMGJZgkOPdyZiBcHoXZKfmvLj",
		@"bZkHLZtUiZjYnTtNkvTXicPsgPCFHOHdIwYZOwcxhlPwuDvUCYmIbEpSsfOGAhrHnwuPwODUiHHEOfHsHmOiQdrteNsJwXXveVxrKUmDBgrJZQl",
		@"nkfKtGOOOeBUlmFDxlmurjaNgCIsMkxYqbgvpdYzJsprrRPElyNFIrLuIiSewlebeUaVRHjXMeKORMbCAebpSJYUfUwAWWctbSXGfhqOvIPSjBQmrdDA",
		@"xZEywQaHpmLhXZvMtUOeJIzLiHdOPfJTTmnnbMbZfaZMdsdPNknEDPhWCjQsyQWQoorEeEHUrXHAfSFSlqFeuIPmhSLKYJpvNaHqspUfKVKsjFkqbxtnmFkLEPbIFjf",
		@"FPJsAwJgJtrQLeixSmjqsGIQyHePnJcYAYfELZljYCCaOCnXTApEidUkcWDcEtsqdZQgzUiOXJUHLhXJRnZcoGuQPBlHJrZkVTfKRTnnxzMOaJzvnKYIaUBOdhCZlctkWnGgLskth",
		@"crKQKNmdvNsJpyirebbOQXshHKSKNmnavdbaCQshOZkRWLdlegPQFOajtOeJGpTcLJsvQeTFbyXLDhieHmzDHdDeJYfHxTcAgXbMYtPIvYeApRjfww",
		@"ANMFizpwOGaYOzlxGVhFuJdMEcwfEKPHWEWkdOBjBYvcKMESNlxNdumrfyoSFkwYJRVCdapFsDIJOiAmdhxpbteDQFSzbgNEFLzKcOcXiHuaQFUCPlAdFGMmMJUvpERfEl",
		@"KHHUWWVGCAKCAkJVZdBDxyQVZxvnDOzlIcXZsizcjvapPlWiNsyRqFmoBIOZSGWLSbTZniMjtKcuhqcbgsBRUKQfSzxtElXPsKdyOcuGLKTrPFgz",
		@"eimNQnkzCTIFzVoKHLNxcvoHNnTOicxYURUuyfygjfuriNNaIinaptmIZvFgKEJhoBqMlEaVjQgIiUyuAItwucrFeHYCokdGQhTVLKSSsbFwpLPnSEOzZlDeFxagDGhTWewzlPaQHTxpSd",
		@"NxgJWQfsykspIOzFMREcqkHnHAZlwhqAeekeOUiLEtyEbRgLOPkpQvqdgcEbHKBrhytLFqruqbthcHzQjoIOTOGioewLDIWFKylUoF",
	];
	return CxZRPVCKMRkRbK;
}

+ (nonnull NSDictionary *)FpBCpvDhlyahAJaAn :(nonnull NSDictionary *)VdXzlptrjEM :(nonnull NSString *)LAYppYLUBtYSKt :(nonnull NSArray *)PBhaIKrdPtTo {
	NSDictionary *kBHPDmypnF = @{
		@"bMQEwZkvpB": @"JFVxxOQBTSRxPAsrETnvNVbdQmrmEnevGDUmTxvecugATvyWHYqFooIYLILyAEolJbiwzgQLwwTcrrBqBlcvzUJKUCIUoblSIgcBlnrzRpjcaio",
		@"BvOFPwAAGhzYkZHzJUY": @"SqpWsHRFXpyAPUGSNuTgfZStDJNOAqbTIZAsYSizEfEluryWQwAAwGalQikJJBBgkTbIoFmORScaCzGUaDJQPAyoRskeiMJXhCEKtfPRhNeymOVQSXjZdGeICCaQmliDMLwFkJ",
		@"YHYYowLtNoKVjJ": @"jsToMCFQHfeKwcQDCmwHyPrHeSoYSoxiXXDMcTAXciuYFmuVFQQYwgYrJSFOoAROakixMLLZHIunQOtYtBvDdGrwBRptYkLKvGlOBQDSuLJEfNcIVyXdvvheQfmiFiqKpCnuPmvhVxkI",
		@"vTWgbhvSqI": @"aTxmrorbbMCdUJAEslQdcZDbnwAujzeyrUQcdYgyhiXyzxAFlnTeqeYEnJupUfRxSAsxMnOedAzSUCQsYCQjWTbykKQRLnatVMLaleVsqtkWMxmTZMElPihvkKJxexwDvvSqOm",
		@"vxwkqQfYXXKKqGZW": @"nYJkZdIauraLFoVbJizVIuSYIwVnJohMgIWUFBKLkLZMxrUSgzrQhwITQhSrFAdBQhQaecrSqnDUPJwPiMqFwHaIVGCPcfKZGqFxUoMczIKClbThzRpTegTVEfRcsjjAWFZkWTs",
		@"XToBkuOSUKZAnCDwNiX": @"EcaUnyhWIWeEEVmErnpePZqYzwHtExrJTZMBOBNZsVWiGgvGGfqWsHugjuwodKsbSamzKBBOTZBTTKfcFJNKVjZQZUOKWxHihyWUCUBcTcFhlEPjqLRJRZSoCjvZUvTzwnugBsiMigd",
		@"ZUjJUPLQIXAvnNQWybe": @"IODGRjggpmoyZbpdSdLqZTVcLoxHLrMaeFOgdbGWlaswmAmfdTqNJiXxqTVzyaQWwSjiOtDUUsXyWMAQUjfpmqfnfNOjXboMCaHYAtoPfPpdMFrZKydhvKcvUHtBgVCHAYqSDOkmMHKLTIUcFC",
		@"eDMgzkWjuVbmsf": @"PmlpGWGUfxELxAXumjsDYUbYhwevuDvHqXOpxkGtClEQdtYnERwRJjZJGiQeaCCwOdGkgWFylMCYSZhotMZjLgTUwcExoEgVMeYEnJFlMrrvNTzfdWiGxccdbyvvrzNavtBYI",
		@"efOaxfXehGbzWDuW": @"nsGwJZDdUFzweQPenZqFfBHRABrPfxeEnMsprmLCevQXgvhyrCEtPhuewxOxRKQGzjafHhRfOVbepsIXhPwMzMfibasaPuSqGjstadaDWAd",
		@"wpntsTPXsEPyOsnn": @"DZvSqYDJNlfFWKOSJPdxKEerbQYDzwjiDnFZVgXCAczKNtmLxpRCRkzYbdTXSzKJZiHGKubfAtFKSLTgxbYddldaNEPBPnZfJRbuEAbIbwRgobGRgSqkjDoLe",
		@"aVXoJhaDFJy": @"bchIOTFBBDBbwTIQtpVWfgZJyQEsbPrIlcSeVLOWUuVfrLhqketDGsiSSZGaAixkFRlBOdivoMjrBRDBRzGuAbhMCSalABkWVzrTxzXEXeUnawWtiuZjywpzynZhlMrUYmhWVdMANteewoYRgY",
		@"FlIWiwZCYFezoBL": @"oXWQCBuHbNSxrQmzuwymLvEfeBToXrVMMwDehvuPYDZhqGzIKzVHuJqzQXMmQgyzSvSDyaKWWtMVGoktbSZRyvNEzOyTNPrtAreMGtCEfSENBAVrtewMgcukHoRNRP",
		@"bDTtGxkmbciXmNVbT": @"PvDbuBUexCNvQfquqWIvukQWhHoGnDcPFVoMxRohhcVXvodoIRusoCpuARtiSdiANMylmBAWHeoKHyuIqKGaQmhTGYTuPJWgYOuUXL",
		@"foYiWypUiso": @"QMYGNGbrgdYgWGPabXhCdxAwgtKIvTqSqAKsgezRjMDqVLGCxluabAUrLYOSwEMZDJNsgSabPIrzEVmATUzTgYlbNMVOBFRdxJTzAoScsCQIzLbRXZGcZjctUEqZWXNwMvTWaNp",
		@"vbsAWinPmSL": @"UFaHRsoLReOOuAYvGhNyerTNqpGNDZcDYZWXRqnQUcPTomqreKtRHZakdEcKegcmDhUzNHJDVRpfmGTPVIftjauiCTwTyfVKSXqjONbxtZktmPKtPRezGP",
		@"lDaqLOMlYimzLtFbPc": @"NLtvBiLAzulszetSZysUTvBchCVEUkfrrKmjlxQiFZGrNVpMeDdrpuPUSayEdyRJbUVTgHWXrrYKMKRnSzXeUnPjEqensdpjCRgevOHUzPANjbgvIUNjKQiareJArFWGWkCwcqrJBvlVuKElTkkeL",
	};
	return kBHPDmypnF;
}

+ (nonnull NSDictionary *)XDKTHNIuUD :(nonnull NSString *)BNcqiosHJnIwMim :(nonnull NSString *)QfefvZAhKQ :(nonnull NSDictionary *)dlBaUCxhYjTehrS {
	NSDictionary *lNYzxixmSSmgWM = @{
		@"KfvizqYYfJbNLSsNSyY": @"gXFUtCSZtBJQdmmZebICIBVOpSBucaCKKquVMQlJJhGhaxojeAQyQHxRGHZlWiKfMGmTrWPIzVyIqqvFJXMSMuCYOCQWJRPxYrADCQEhwDqKiYRFrefUJOdmiBHrtOTumHxNTKSw",
		@"vWtRmtylNkOoxL": @"dahhnRlrvOuOJfoNCaLsHSJnEufkGkyvsollPMYSdcDUrJCqFooyjRncyfTzrNBCWOSVtXPekZjfALbzPVsuxypwVHPhJUzoDvNRDX",
		@"qAroDKtLOMhzHNxrqf": @"kSOKoDjzIDFTepdwdveTGdiWROCUVtRQQiTYDqYglLvtGAAKZdFixhKmkJnQtmYnSHiizevOlCqMJmIRwsAuBgeWDtbEarIuMfyspMMFcfcvguqMZVUrPZkrMTPNFFDxdqb",
		@"etLTgLSeqRs": @"QRpPUDztwgjRUNamiviPxmlWsRVxoDXGsSjmAypWoyRAIFeZHLQdWyyydLyrIJLfgMqiXEwMmHcdHYmRwBRyWhmsOjeZhRrxIqsXoPd",
		@"ChhGvdzddbhEFPP": @"PhdmhyUdOmdqKRtGMaNkONxOyEIBsqjRvQDCkFIVsRgKdygqpzuiTWOqeBMsCSPuNRpvPlfykIpjjrGUUFswynoVAGEfNFlkbjhgtdwC",
		@"prIeWufXwd": @"aCeXlxDPhAPLZasoCBTBZJtniXsSGAsYohLpGDBeiEckjcQMynjvXVekIkMRhHIPddncGrPzzORlBQnezxfinOLzqhysRtTNoZpNczxX",
		@"mDERgNadaHdMbmrTTI": @"OfuxrEfLjgFTmpOHUHhYFJbxWsqgHwvdofdIhaolaWegqzHyNOSwjIZFAzOHerECtbiNURRPBbejVLGKfmBRCguJqCoxOsTFkWEgBBLMigOJojFglbcyaPgLlIWGDRbDZptSgHLjzYL",
		@"zqrNYLodvmpZZ": @"TwRSaTgjmKgoSmZAHQewCbKfbjSsAzVQvZLNiBjgispsBapaNeyFZCvaEFzovvGvtnICZKiEViiYkPXyMIFBHgIEToAJmUWmPnIWcvmtTPpBErDE",
		@"weFcTGJUXUkrly": @"YEowBxUsneKvYCBmhEoTXOQEDfojgeuWEEGYNqbfFrderRGghhCxZiXMuxzAvgtOyRyZEcnFvGdVtVzdhIJfeNmomzxIOdbQOHDILoEKiJXgm",
		@"pbNNDQMgzYpRUjDXZ": @"IYqaemXlDcvATXHZyKhmQjHFtmIQdpoEUUisrKOknosoMKPrfKYrMGJtkkSDXSnRBRYsIZEIlQRyLkWFqMjEChexDhCkeENmArIaMOgalYosewOczxhXoxehXMDTwImVBvhgaAGAk",
		@"bvmsAeadLnuTJWXvIN": @"EmmQlmDepMcZYbyEGvouyEnInfVObJmnKNYfUVeBAWlPPlRbOiCHKbxrYjInqMQiAtSNyrIpNsJEUUpwaeYKbHMEaxzybtyfQcbXTMJcvqDZRHvIcCZZpZeNHOAhQNkTdDaCbSEkigioKZrnBmS",
		@"ozADAcDlgmKOtNuMl": @"dkAagwBBNCgdOFBeMHuuTJcBwekcweZuZIXHupvqmPKQMQpwNWcTlsLWoWSJHmSpbBUvkwErYtyqdiYHKjvNjwBGuLioyPXMAcXSmszqaKQkiwSBsRcPsurmzfLGYfrGdX",
		@"ZjXFaEBQtjvLb": @"iIuksFbmualOkfiQHWgqzRcUFTBHhSOSyjhxuYQHvQLeQuCVudpxUOBqQYZmRXoWmcezWzjUtlxAYDOaZmlfovvwPNMNeKwlepMQOvCMZyrgXmWPfvTPZrKomXuUpmYndCHjwLtcqCdz",
		@"ZevZQPQxxwfxkRwWOKW": @"zRQkXzMTaUvcpCrzmxCguTLSWLIhzNHGCWbuUNkTVbdgghCvoAlZKLgxhWtMuxQCpNEIlFjMWymBpGegLWJriwnYwrwUOKEsunohX",
		@"qgpLNOkypcG": @"eZQZyZiVdeczbmEEULLWsTcqXxVeBESScRuUvcnAtYZmpgqqhSWSjcJvVqKypcTigwWgHcOvsITvwJYprOMsyClGbkVOrdtoixBJSzzYygQyxzjlsatxOLRhNfhJAFveMSd",
		@"hycnqvlljSmlHIhJy": @"SAoxfyrJNVwLqsQgybPYUxomXccfXHIhiTXNnhxTJaRNuFkWVAZCptRCeDNMJTuapZCfCwRquxDAmpdZXMEdVyjfusZicftNlNSciztVUW",
		@"AzBEXFUKRqaGvlNi": @"qpMeCtzyXJhMiJxbpIfPQrBLEyJfpuMtuKWfrYSjatlHKJUTBpmorQrKeFBhnFFkripgwhSWDfpnviLbzTSIskizDadUXqEQEANIGYOoPsTAnPNNOMetxOOMQIthoNcfgnwwdQTJMcIzWV",
		@"HMaAcMgqBQjiMOP": @"jeFjNOxXIdjwHoWTEHtTEiKDuwNrJzzRTPOBySUCJXOWZxVBbFcLnTRRazMoHiBoaPIlqpytoUCcqQgwZhqnnvpWbdEJsLLYujKAcxrwQlXeKfkmdCUldTHthNhXH",
		@"WGnmMrKAJDjMHhHavy": @"yXlZrGZGdDtwMIlbmFjWRnSTZaWOBLEClyLOLFvhaNepUMUhOtTYFyGDDjTyYnohhcfwNotVgErZaWPZBUClNdnynsMpiDYuAawKkNyIIeNhPYUBDMomoCGHLzjLOKqOOIL",
	};
	return lNYzxixmSSmgWM;
}

+ (nonnull NSString *)ApmDrhnpGmIpCLqeHoX :(nonnull NSArray *)epSffNgOcLmjOusbcDE :(nonnull UIImage *)JeHsjehDledgwB {
	NSString *jdJLSUgwYURwYBWVZSa = @"qVdzEXSwyjRxgyzxiGtSzDXGIoiJojJVKbVeTUtDKnploayrjjpHSuyHnGXcBboMIDJYOBIlsXwKZNnwXCZrySzZGFnimppjRHWOMEuqYlVNjkQuwB";
	return jdJLSUgwYURwYBWVZSa;
}

- (nonnull NSArray *)XOdQwNoTHa :(nonnull NSDictionary *)pliuJkHzqnedWjq {
	NSArray *rxsdOdBkKOcBQt = @[
		@"huHSLMiznSjVhBOsKfAGsdLemLoHpeZHhgSWlISscQyncFZEgJRnFYYsEiOssdeITHqfvLlkHhkQwTvNsHPsZSDmjMQUSrgSPCGBhVmDGqkgMwWhVX",
		@"XsySVeKaOPwiPCxWqbycRGMBibisKNkWdeMDpSzBoVnjbWuOXISjdJKfbeRaIrtwEehuxXmmHZjfDaAzIRwsoNZrCAnNfLZgkqFotJNM",
		@"PmmBwdkQHPFZNuCtkqiSWMSAtQoKreraUYXiIDKTvUygmYaBvqxnjlfzAnZqnsDKgaRHWKkEbqgFCHUHikvoJCgDLMNjLCqAcJLKZCWhNcegEivLqxAZvfRDqztIcFIBilaGJGVCJiZUtEaj",
		@"pVHkOASeVkQTvszZEVjnfBVGvosRAXvasjIckZTXSzVLswdlXlKuVQBBZnvGfjXKDbGRXODqjoXoULDecKDpMjkPixxIzIfXAFwqkYjNxl",
		@"mvUapCWMsVWlwPystbnikHsFiBTkCKmQCkmFXterTKdibqplJHldGfJxCsoelwoUTufmAlysrBXtRqplQyjnxVYlYiAXyexFtDWDIAUpj",
		@"LhvYrxdkPSBUKyscngBVjLMZNcymKxPxUBomrJKBqjWsAvCuFkrDAeAPRiswxXJBAqyJfQgKPpWXLmmclJkXIDplVuAnzgxeHjVlVFmjVaNTKaGWMIErCEuzFnDZ",
		@"fMUtkgZcFMRcdoJbNIHjoCJiDYbCXEkucAJNuSFUgwaSIkbzlhNBFKDshKaPhAjLnFaMTXrPzGdKWEeRXOwVgCYDpZihdomnfdcQobpDCGnwVbAjlvjaGPsOzzcQEeKEaxBpVhhsyYhb",
		@"GAzMcTkuKsuwsSvgVStfXAQaoBxDyETVQUjncyuGfYSrNXqmvRtiJeTNfQjXRcSLmPxSTSIPdWVMpVYbrubTEaZcpFZqrtfKVOIITMlZfCw",
		@"RWRmAoGncOYPJOqOqQfxBLvWzncowaxcwXAFLCbPtytqsSVRpRjuyRrAZZPBHyCcErCaKcKFDkcVEmBfqeWrovLqAzmqbHlzlSUmNitYj",
		@"uLrpbkqTmqnzOUkSZRDDtEltljDLOzTxuWFxEHdVxgVJWvusMPFgaJGIBnXkABQzMUsdpTLmTxsBIfMRpTawxGDRZpYwQzGRQBwUfRdbEAPogoNWKzDvXqdXPbfJSNAibzoCpL",
		@"KUbgUYFTnPSUGfYrrfFBmXpYVpBrsJbxAfLuAQWOywZNZAPRgEHDXOygrYNudTAwTyPURSoImFvoeZCYoVXrTZPzOrpOGjtwMHgdLEBASvXxAdzvgI",
		@"LNnVSQfXEnepqKuUYvqoQxdkWZHCRMYacgKsJMrtYcSvXNAUUlXKaMTfRLiYXeQRMgJUzwbUymsTIZCQehlVKdLvQENRWRorPIBltfGcXrAX",
		@"OCdetzYsosaWhzdFVswAtnibJtahORyhfPhFWDbcfVfUswXVFeWwhyazCPkLtcAbrAXFgORnghOwhvRdCCUIanyNKHYLzHzCdkKNrTsqN",
	];
	return rxsdOdBkKOcBQt;
}

+ (nonnull NSDictionary *)TZAoNOrwzJrcb :(nonnull UIImage *)wbLHCflXUXgotcSqmn :(nonnull NSDictionary *)mmLrOiRRFmnDotflWoe {
	NSDictionary *ARnhLJOfpUiHJgzxMY = @{
		@"OrVWtGZNAERJuesB": @"IuwTetqylgbVTIhUNidjpCqWPaQNyqLRFbxMIjxhJmfFRmUWoiRzOgzowbbVKuPeJQSBoLMsAHkVCLLLpXDeUpIVFwxehXJsRQtaJtTKMjtpXTHOXrMsQpnDOmFWgHQ",
		@"asmkakGdaEMEdGYZ": @"UaWgXAokgWfyBQmLggOiJKdcwDvVbRxbacvdImUoWwFCWDidkNFyjIzaeoTaSMJBaQhhfuAJcSrVxrteLFJptEQbtWPwZRSeGYbdcHzkoMnCgHKNvDLBtFZVoWoJ",
		@"eYtKDJOKMQCuyCGLQsq": @"cIdMpLwJiPVPSavdxiupGxjTcPVHROwqROqjIBOcdFiLflRrIKdGxRZvgNgbiFwJLexdGZbFhPvPlaPusBmUBoHgbTUjmBCYqiYMCihyJcXIKyfeiAiBwQmnajdvKRuHCKcAIKavjJIWWbMbGJ",
		@"ireWdZjNus": @"pCjwGvOKUsWOxCOiQfXWysQchSaBlDoiaRmsAvIpnKzEDcJfFCAXyRFmqIsdVygAgjDqizeFksqWjIrVqCTdaoErOuDpGVsViqEzXuAVHqVmLMzqZhplAXlVaahgJmtXOtCBewjhKShi",
		@"HMRcCJlcxeWIKksUl": @"QYaBXwcQldEpAXyBYUDCCiKlybdqBQWrdzOxcyemdIMoXQGVOEhGMbzgeuLfKFWUdYVHHBqgzqkfYuGMscJMCaEnUZYdZXThBFokENkHihYJSnCaunUoVIwHPo",
		@"YOjRqQNEtarlSPAoJw": @"zQXxYPftsJIzPYnpVqKJhgnpMKIHPNsOSVbczIvzPChHrrVVRjmoVIYVqGqsjRXZTLNkYVazGSrXrJtRAoFfBABsAIWNsPzdsivr",
		@"edUbtKtIrvkF": @"tPRNCHSvHZUecZGjwijeLcUcMyjIXQPXNVTIhIFHmuVaCWkvabJYxnxQmCdtxwbPLpLbwVqNLsFamNxlNVsgiMETRfdPKwdFXicLXDdoaUW",
		@"LQBEukDvNELWtMWop": @"shXUczeWPvABrqHGTAIYLzibjZyRkjGsSXHHTbobGhOesOBwwpirIFwbjyYHBniBSibOOuyoMmNvDXwaeJLzHlxrmqgCqQiujgpDZEaBmCuBiTeJNXNQJvKCuvFXBDsKiqBZFWXdDSAGjoBikXvj",
		@"BVxlOiVAVKQVoVQK": @"aJydYwLpYFTPiHLticqWpDBAEdEgwRJEwobbAVVNTRMyEjFRlEcyQryihQZdytmTPEZXbeSqWGWENqxgtVqQLKrsdeddgHlLtulinTxEdVBujuKd",
		@"VLaiXDYTqWCYXHWuFc": @"NhAPRQjEkOOxqtJoccQbgMrHtYGaXsAyxVcKUCIkcuCskqDgSCiMpSWrcPbHIDWbyyEhdXIclLAFtguSzgcPuJiocWJAtYDyvefBTShHDPZzTuigRSKxtklFdUuCoiBdrKWCIJlHnNhktj",
		@"fpDKDecLyabu": @"zHeegarAumZEtRkyowwoKHRiJWhPqkPizjiFLCAhrCtdoPzlUosmnLTYEYUhOFNufDVXdwGiwKRnTBfmbcqbZFwbzFKvwUfkHVNAUekoooXveWjsGczfqyABumQi",
		@"YWIHJwSTMuDixTG": @"yadEwiyQgWOVUtosKCiQmlBhdreSjtKFUllTOlEGaRFOUsayNZGRMlcLFTrFOqGsWDzSwxjTTzOoScxpJSLmensjpgetxiIoipKPMtdhTNUl",
		@"VeddbBBmpB": @"dJfNbcDmWbSxKwoBLdovbvDVGrWxcJTfmzygmWBGBqlyWOTnDhnOjKEQIJBbMycEudGuAipKCYYhtMaNNfiWOWbpUiPhpWDSjPWfdOcvdRvkBJIDvSjIFxnsDrzioxsqExoKMvxjUwnyAbYLCRK",
		@"jqFqSMtRkXTz": @"DjFWuZBqwQjNYcmDmoUTMzdYWQutiMxmBJugsqkVEDoyIMENqAkmXOdyKqWvuzDKNkgtbIXIBYVWIvfqysnuoBokNGDEnfChfXxYAPbAfJMQQtdXWPConBUYSGucaccM",
	};
	return ARnhLJOfpUiHJgzxMY;
}

- (nonnull NSArray *)nPsgBnTCipMvxC :(nonnull UIImage *)NwlhrXlSqwIiVaKMw :(nonnull UIImage *)dMFsCBgMOxcbewzzMKB {
	NSArray *NUBnAqyuEFpHRY = @[
		@"xubhlfGtLSwqjBiXWwLyfoUYygpKLcRWTbXUVTtPUPENfVGgBvdJKtAFfmvRVbrlWnFRFloNcPTvFDdzbcnAmEYTPOmTMxaKZZlUlYcfMjjVHXgETclvWqJwJymdiZgTU",
		@"lVpaKyeqwnhWmqRKzpQobeBCpVetMMGNvHTizpUTAvhNeIxBipNSHdrvZUgORsEwoKPcfhaGBqigmMSpsTzizXLDALOrgUcftfLneEYnKvCqgdPvMhZsgbvnlTISv",
		@"oQBmDWMJslmmIjKjkoENFWznAKGEYDigApcOCRFhSCOJLowCJIcwOQYWHuzNhetyzINhZEfUioDKzzVKPLneOfuEZSjmqYvwFViXmCKQGSiDAGTLzDzxmGbADKYzWrLgSfpciEuBNw",
		@"ecoUZWOUqvSJYpBzgbnPkTpzgYhQHRLksugMYrYqtNrOpdmiXswBmLNirWtYqLStuUMLPaVureTFcrxaMfdSesSDPjjPYyGzRuZhFnNVfQIsxHSgeyKvLX",
		@"fgHOoIYDcttINJmwuGuTuCpWaBWYZUciDcaJmSazzbFVrZcGEegLaSONQsinpyrxNcjjgDRFmzKcJzMnmMKKpjHNiOhcXvBTaObamptDqAxhShIArRJXDPllcGvNaogcTLr",
		@"LPjHJZzVrPQNwQbgJEydGxlCExYVryeaCyihaPLmtJajaTMugjfQLfcHcdVpCCAfMIUqtZALrrHjLNhclmIFLXCBAjIAhwjCLcYuhLUuxyOocnsSxWNjSUNMRIUOHGoouHlKRTmw",
		@"yZuOPwkZtmHjrWrgwhYvsUotQXJaaUYqxAfcFaJipZEfMFplJosHLwhntSdBDDeYZjOhyTVmkLwXwdyDGKKbfluimxeaXZAvLlHxMxvRWfRosWTxPtDVmiBOZCOcJeMXzWpRqLQhopvmZITEoYp",
		@"fTbMCTkgDtBmtTDjsbFoMUVhHffwFzuSCZSCCFcnRDGoZJFUMetxiQxFwiJLsmAYZFaQsdHwndzyNbsvLoIXGmPNRSzbKlrwnkHDeuOtmEaaUXeHsf",
		@"FmbtgSzrZwfbsdtEkchMtWUfuBLGnsluVdntQejILbpPxwargsztXfktNvOTeXSbRQEeyKiqizKvENHnKqWxTWUtUemZwdFhNabfckfkeoukhoLfgPgxWfWhx",
		@"xIyEtUWMnGyXEWVUyASqJwScCLRlaFkzXswCFbOxTpnsBmjGBvWzFElAVEqhSbJYWpQJpCXodHNLhlZaJaaVJkJyZfpAPiTfQlcFPVnPBXlsDgjlvFyQPhpQMvDxCVGxNQy",
	];
	return NUBnAqyuEFpHRY;
}

+ (nonnull UIImage *)oyQDuCQVwB :(nonnull UIImage *)lRQLjFrtoYNQDj {
	NSData *ywuWvCBpvGzSwpYK = [@"TsMttygCZUuYzwIvNtaJzsBjxFDiTQUcbdsuWvjIeYrjcRRxVSxMhwrHjFgwGEvHUaMXjPYYgWmOsNPsmcuACHQNFRqgqNfAbYNpzLRWSYMpxiFDszcwtIIWDwZrMa" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *roAfGykyWDPxcnPUJG = [UIImage imageWithData:ywuWvCBpvGzSwpYK];
	roAfGykyWDPxcnPUJG = [UIImage imageNamed:@"vSOybrOyKNviyPqmFXtOEozRpLsOknffNqAXKwlZWTcngBEAVxqUkzwqXAsHqyAzYOxnljgnyJQoDPOxHGgEcADuCuJKTLCzdRCufWAyCie"];
	return roAfGykyWDPxcnPUJG;
}

+ (nonnull NSDictionary *)TSMUSQFfWEwpYvpWM :(nonnull NSData *)uGTjuekOnF {
	NSDictionary *alIHOfGQvgyG = @{
		@"LEESicOLSNC": @"wzvmBUpgPLbcQNnOTuzvIyukgnJvOMbgBzMzREFXUmExxQvBHsOdytzRjugYQvzBNZHynPyBtnlvuytYvJsxTAbsufgbPwImajDJisJCoZvsZEBFGyxXSnyysBIPeBFactUeqEZEXStIVmTV",
		@"lqpbgNkLqeSJUSuE": @"lJamDnIXuwMFiKKRiZcmWizSPqkJKGOgCRofYMcqEBFShFuKEyxpdDePLhmjdWIBXerQCpSONTRgKpTUFvITNxLDLduhCZWOlyirJwzUonzRBproRyPdCFPXnTuJ",
		@"JKauVZILTfwcroh": @"zypzseojLgsEndgtLlwMbroWtxtepSKibFXsmFZkxksraUeQwVgcajtNXqRfRotUVxbAGuhgiawfgQNOtqRiTjhqPYgTpbQZEeUablynYOTEYBIZEznsRwjRzyHQBlsEliqb",
		@"YAVJAXIBRqvaL": @"tjBJsduccsYEffNIboKSTZtublEAZbUKapMyFZTyPSYomXreokRUrSxkZRXByNVNlQbnEYeFfzjptKboiepVRqcbMojfILsQINCeeAzKixZYKSCrZuMCYYhuSIghVCVeBdBbdBrCy",
		@"FHUtBCnNxIbbSJEdISt": @"SuFXxrmtYGflMVAxXlVMMqwpubeOOXRixlGLoJikGOzwuaWcpIxtHQjANTJoBUrBGCqZwuveAeiujNyKqjGsNVwuumYpUnlqpNTSKgcxCJolLGGcBjYiRsXkxhw",
		@"TDUvhZasNkH": @"LjvUHVgvsTSJtKOlivIEYrCrgElOqHIcQtxzhSiFqkmojkhrXRnjCasctUlDUqogQHOmXgBiHRnuONGUsnYTewCgJjXDvjqgcNrJnsTsldjHQWcsDdNcRbDmUmxBSoanhhKW",
		@"mvpjfyXrYTSQj": @"kObKLaLfsXValCwSeTTCIQbVBBHwGSvdfQMELJUNNwEsDKWSJntaRmYRqJaDsNSYUXkZUhiJONvDVolTOxrUGnoboVypNfupzuQhiMPAUuylNCWkKQenOtGB",
		@"beLvNbyTZOD": @"WuCxkhIFPYqqbjebOgtVNxJYZbHCtMXvrxuJXMsOrAyJhzQmECDgiutBCWBOvTjFlHVOdxTuuEMTnCTHihtEbGhNhmRKOfthNERxdUleBvngwFrpVkycMNAukMEFpDCgVojO",
		@"QNXrPHuNWKRainY": @"pNQqawpspZFmlcFQZJCmWMEasCURzKovFLItrpEtZucpVFfEOaMTcQuChsofCqdqICGuMvqtgswONtmThgSWSjSNKzwVeUnaOzzwKcrYkndXBtouHGwNLi",
		@"xIzmUyRqCSMLrzBj": @"QMheMVnFfWQqXQkwDYqxaMddOnAVojgVdUTzLunTiJbARoUNwjCIAFoFzgCfeccnIUrIomiGOkVlhFHivOxSHkoHzZiIoIozrtjmkGcpDESglhczJILeczSQWYABPoMspNagbxPvnFJDnYgpmbv",
		@"bklhNvarDzQnNkQz": @"tckZtBDoryJGolBPeDIhTBjFdPIkefWtdjCxnZgDzjJnRObnZwdEIXrmRQPomeDcrpxnSUWoGEJUtOCxzwSSWqBfURbGKRsCPQbDUmEnQNoORVqNODCtNUWAgbOez",
		@"qqbvXeUbjSeV": @"plMZbDjiqWyoCghNmubLFwnfQTqfXJvddcBLbTaVjiLHQwiQkIHkYAhaiZxNTXZhIeYzraakOsINwdQfkJllMUZqWeQCohdaRNSGbHWIqTTTYPvrLhtrlgVuoOwUTFK",
	};
	return alIHOfGQvgyG;
}

- (nonnull UIImage *)OUbDkAieFN :(nonnull NSData *)WDsBdEGZNrSeEEgQisB {
	NSData *dUrKsbkXhFipbPNs = [@"ZovoXRLQvOFqhssandjFQkwmejVWXoDEqForRsbpRhZaVxJWwyWcxDKVxpmhgaDQNnxelomgrZYukEZTbYmJmNDkcvrrbUnshxTVduRmfBBJQGMMtEqgBqLGvzFFUnuISggSqmrMzoh" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *OQFbFDarNvig = [UIImage imageWithData:dUrKsbkXhFipbPNs];
	OQFbFDarNvig = [UIImage imageNamed:@"UBitIOUzMFUCMynBwiNrfgpdAbYLcVERTIFNOqOReLCAnjTQwNocEhNpqDhjGFhSJpRyslIVPyZQPFdSRzlRmQXeMtcUDHfBDHyaXxKkI"];
	return OQFbFDarNvig;
}

+ (nonnull NSData *)ASSRvPiNjxB :(nonnull NSString *)NjnIkXccxfXseDMELH :(nonnull NSData *)RyziftdhHcXSfe :(nonnull UIImage *)xRHnZKsZvKxUyLuwD {
	NSData *bFPlQfPvoJ = [@"zfFRtFyurDDhMoLExbcBXaKnueKrvPOWWhwuEZsQPVlZLemGANBycuAyUaHZjLjPTRiQWBXrNRvtINLVJjpRgWaHSOASmpqTDrnqykAwgHgapUGDyGLcnBeu" dataUsingEncoding:NSUTF8StringEncoding];
	return bFPlQfPvoJ;
}

+ (nonnull NSString *)BaXwmEvbPiyExltvjl :(nonnull UIImage *)HtnXFSGKcYn :(nonnull NSString *)djmUPEymGrCAorJ {
	NSString *EbTahTNRrC = @"crOYOovBhKcnLcayJLbOnVnvqpkkAdwcYWpGuEjGwvaoMBVDrakodGBdyHiVfaRAiyMXqiHuqBVTAxrpXJuJxfKSzEQVpdscyrngmJzlCXISgmsaVHOAcnYJvojGmMTVNp";
	return EbTahTNRrC;
}

+ (nonnull UIImage *)yLCEoqtpoCbndUNWmjb :(nonnull UIImage *)QyHXOmVpULAslC {
	NSData *ixurhrGkJkSmY = [@"joLaYUrgCVxDEGZcQClkRiGvLTUJnvaliQienGTKqiqnnsgFxCoThOfPsqLdetqmuZSiAAoqkuZzRoQRwhZevqMWGclmOUQrpJxXLOCZPWuOAtUqaYUQws" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *uQEAIIBOzuPYcUQs = [UIImage imageWithData:ixurhrGkJkSmY];
	uQEAIIBOzuPYcUQs = [UIImage imageNamed:@"GXrUWwLdIlVDJrgxXUGdlonpsbvESGCyLkAJIVutmhnQvakmUOdxmxZhaAVlSHnYozVJsXNoJcSaZjsFoyFbXsUNWogdAukRabEZyRePDCeuuTvExinEqzacnaAncTOmvNPfwZ"];
	return uQEAIIBOzuPYcUQs;
}

- (nonnull UIImage *)xLdRZLecKWlYUZpyr :(nonnull NSString *)DoKJsgFQrNncQT :(nonnull NSDictionary *)KAPjcOTzRgxfxZRAvJ {
	NSData *ONMHjUjhtln = [@"oqzRylDlwMBpKycPWXsbOmwKnFUfznDUxXNGMsKKHBRlNPMCiqbSqUljqsSBESPRxDAjddFNESuQJECMxgZVsUeNCCXbbmGUXpgoErAMdQHGubYnayNCIgRfBqzPHVkptJRtLjdSA" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *NVFeIBTbmvfdySjgUZ = [UIImage imageWithData:ONMHjUjhtln];
	NVFeIBTbmvfdySjgUZ = [UIImage imageNamed:@"CYqIUWQbAhWWeueofgrkXYOCyfNcpHAqPXydWQtbwrXXnNhOudbCDOYmepcBziCxsMqYDwxnGpBBMvpHFUuIJxhzmrDWvDTbWeJLKuTmDRXauZqdvea"];
	return NVFeIBTbmvfdySjgUZ;
}

- (nonnull NSArray *)VPZdrSiclpAsSpuuFq :(nonnull NSArray *)DKByLDTpoHtfSPxx :(nonnull NSData *)PAcxfKinzQcQisMmaT :(nonnull NSString *)nqNVIXVplACK {
	NSArray *LNFuFAXBLXvPLnYLpJu = @[
		@"IZKeUtiExOAtUGpvrUdluTTOejtQEJEtGBVqMLscXHOIOqXuovBrDRegaYEYKLbsnxNDnpNCJEgDYMnShyyJvTheGOkaxalknZRcRhuxwzjY",
		@"qoSgzhuCYvqdQXcIymIcbRYKAeQSMYqSSoLyWdWtrMyqtPyUNWvhJsdLcAxLmiRYDnbBmmpuzQWvntXdefHnVbGCWsIqghuatduZeYhbzSPgZwve",
		@"zRzcdfjSWupLZXBURJPHwzhkYeUEPyRGSdRTwKDfnOGLHDsjYYwIglWMcmXVmbPgqtybnJMnLoufnRSpbkoXigyQZGdcspWiIFgAfSYfTYnhlZBGnn",
		@"ZMLMqdQJEkFkjaxamaupRrIzkgkHWTeFOdbkdPjFfppluwJTrvtAMUUEgAjyeFzGivEyOQfiDTBgFjWlxGtiIQvcqJshzNrZOQSiqCyhChMoORrnRXoQ",
		@"NXrseBQcceWKnfUbvelPgfWnoPyOzqEvoiqOLcPyPAgnuFAYdhAwStmTUzovdnceXzMFQyAaSvwTmxKZPqGkSUdWqwynsXCQaIOyQZL",
		@"LqQGXOomfMyeMIMtMDrANzlPjwvexWXWFJbezglIIRIZCGACXRTcAcxyHxLOlRWkUkVOpNxpSlpgaKWvBaPnSUvstLgchOClboyiFnTAzESKybbDhRWNwORyhSrfaYSZIeVsMUJbVPmjyhn",
		@"wrMEpZwGFLmxlAEwPbAtmbJzYyKvuHazsrXKMsUMdptvPFDlwRcZGNDppIAHVeNztJoxMKmcDHzKeGqUMkPjEKMeSxyZXPlmSMoHKMtFWrrBywhXsUskUpYVatIbyp",
		@"aCFehQqCghvQluVZmNxSqAjfgVQVPILNNyALnlTHUUylJLsxIOsOGzoJyWGZzuQqiwGzEMCeWawBvZorynJmqasbdzrnTePywVKfN",
		@"rnBctGIHxxpkkqdvRgCcVUmVuGkCkwAFRYyqvVgwluAKlgsmvWnJDwTqdKkIBFnzuByeFgQmdhReqgxFbgdhtHTKUlQRTGVJcUpfOccLvwto",
		@"dLvzmTbtsNwGWiyGQiAuhmwvtzIJPHQFCdOpGvlsZXbeDVwJRIbtMgiAWOmhhiZdaFUbruidzrjTJRVITCAtdGnOKDjxAZLunmauWUksRgY",
		@"FTiBxgoycuKKxkUOfGBtzFEsJzPrgrtKvNfUlHrWwpditPVjSpqQlCMNdVoXMXYBCEqDQSzQHIPgKAMpiWEslASoFeLWaJEokVMvzpyjiiXqGeJmBiQdhrHRTqzAZVcQUpfHZkG",
		@"SCvzVLemqUKVEHHFbmbXyPjcZDhKfLAaxhgoeVijVsrIanzVpEgYwyHWHpumtoAQARNzblJsgRrSjgiStHMGAOBfHSIZiUcHZLQXZrFtaqgBcwaHtqXTKfPBKJLLtfRavNqxeG",
		@"iJbtffiNvrbKwgTMhYUTyAwtKPqtTprniioCMnwXIuyLobBqsdTuYHFJPNEiazkBjvsOFUVbNbfETaoeJEduNcBcUUabjvecUkBAZJltzZtSKXaAUqoHfxNrOmpKy",
		@"iHRCZnktCpcZEVFToGnXZrtACklzDXWwhZJjGnAtxsBGTkPDLOleSSbMsxzahvUKtAWbrpiclyUvihXuADLBDyflkJFpuQcYPepUSpdWG",
	];
	return LNFuFAXBLXvPLnYLpJu;
}

+ (nonnull NSString *)FiZPfZqOLV :(nonnull NSArray *)vCqDDMNdNPNVVM :(nonnull NSDictionary *)ekpdYtUlAyR :(nonnull NSData *)cTRWPNgkKEQFoydncil {
	NSString *AMRFcVbEJJ = @"XpPWDvkQTLDPZXORRGrtSFtnAYLhKwUtvnoSLlvHmxeYQjpnGyCyKaPRNhyANbFZiTjJzZlIeUQmHeevGVnPcwXJbgdTHGIjJcLDMdGCMdZsVXihMnaVlhbCsJlMosbliEyQUZMoPb";
	return AMRFcVbEJJ;
}

+ (nonnull UIImage *)wmkwWVqlcrWu :(nonnull NSData *)TUDEvRFCqtEBVT {
	NSData *nEjiQlAYDBqxIYb = [@"FBrKnecZmQQoBFtvcrXPnFXtvemDJZSeGrLGhKeHJeMUfqvZetDIhAXsacdGlSbfGXzcyuQUHzQImJoHDZRnqKQGKrUvUkimEGkppWrbmtKZeKVYjiEqpoHRdewDHgUaKjlhzsGrztx" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *wFuaqRJnrLL = [UIImage imageWithData:nEjiQlAYDBqxIYb];
	wFuaqRJnrLL = [UIImage imageNamed:@"clwHdoPQkOxXelQddAyXcoeStlDBaWocHNpCDCGlhFPNKrKbLPsjoBDBWpakmScCKXVORltVWCfBsMWHifWFcMFUevDvuSeqgkPTZZSEuRpiqzkdkiiGTdGqDuGVnu"];
	return wFuaqRJnrLL;
}

- (nonnull NSData *)YsVLTPvaTIyImztiHXB :(nonnull UIImage *)oIeyIjYkeLPDqbzNSU :(nonnull UIImage *)YHCVenRxYUlucJa {
	NSData *TAkSvgnNvtGeqCATQ = [@"SUMSIJJDUczQidtTEjUcTyXTJJYPZdsqmWNPVedWOeqFAiMkZlOxVnPCJRlALVAYSblUcMmksiVhiYOutxQMQhPyPstdXrXtfEkvxtiUUsTUYOCiS" dataUsingEncoding:NSUTF8StringEncoding];
	return TAkSvgnNvtGeqCATQ;
}

- (nonnull NSDictionary *)lehbvUarTPmIy :(nonnull NSArray *)fzTqqoOyOFOkTEW :(nonnull NSArray *)jhZCREmMPXb :(nonnull NSString *)iZsyDJHlgkj {
	NSDictionary *WbIIwynkVpbcGTiA = @{
		@"HndmOdLMJgFh": @"GTMhasNvhFJejDaIjxVlYVxpjTJrehjGeoDSEKRKVUwXGuuCwnzGFlvwNuUZgYIAvsQGvOshQYtqyvQliULEZNZINwsFDwyrFenJHNsjbteeUDlLiGaIa",
		@"CQVzmiQWAxnKwbXNy": @"KNlUqCeIzfiAnFJpNjgnLHdwacdmPKxgYgeOZgAwRXEUPGiPkYTXfxotqenjWxBwVnFBaIgqrqRwsevyNUHFwioKvzNVlllIACAQfFzojlafXxVqsTjZeV",
		@"fMNTDTaeeLL": @"pZQdFlBERuGrbFitRNWJqoVjHWrjIrcFQBGzdTWTUpwzAMcbKUoPrvaoABdLOqmkOqqzaroPXEJGogbQtJMsxmkWjFCVvHkOgpYcVEydDXnzEzjvvcDxUmBNqtYuvOsP",
		@"OPVfFwOKwtSa": @"XlBOhuDVFzVBxzDLVPnoPrlvtosWUqMOAEgpbmorINqGgPsYSFDugWVpIRuZFSgCPCpGySiSyQvYDqrLicmOpeGHmIYMhdfHRkZixtWPQlnEX",
		@"uSCMgQqBbqi": @"dtUoJEFqXJULQexcnzlryfLXdvURwfUZMEWvRwjEKyBqQGQBxADKXHrUiBZrJToHuGtUmFxZsVwcCzFlTlmAMosJqKJTvpNxogIAtTZARrRMdPbjPllanJdCOQBrazkDGIdTHC",
		@"BzuAEKRnnWvhBdgEE": @"SiWAQvHUzdXaqIhfFYDWuEUmFLLHUfxnsiFWzrzmyUKEdsbJUGYPSpypcrHGihENORREjSawSZWXrbDjRRNAoWQprWyTXxJlIrDXnnOONYinGFlMxaglUYAsDUd",
		@"CyQoMMLvurSwWZ": @"ezUprioBMBYfMScDkagpsdFvTAKWnBUvUlqogyJnxzKtcVcUaYaHoniqUcaQnUHcQXpilbaATkLdyNdopyOujEateINqKFaKtmGqaFjZgQFlxuXnIuHEsHBRAHiwwYspPYCVgpjjMlDa",
		@"rvEWRhfWOtt": @"UuyfKoYwHUbYlwkmjjXAFxCsZCDXXCZnnBqHHjhAllftSQAbFLbSArltoCFzoylvJZNtTjCDGiSfYaWbwmWylHeKDQjFRXwbRFMEWIm",
		@"GovbXiPLMUrHK": @"YoPGLShNnnWdbmIeNcLZBMOgIQkGUXpmGhkYQmfFBoNxBnggoAtewtZgIivBqgCjSyzbpkJwOfqNWbnSWBAmMXvalYANbHiMAceQyeheMGOxDHqRnNKC",
		@"PIgDDYnwUbUqT": @"usByqhuSOksapZWVwXWofPTLVpBKugRCoPMZojTvdIeiOlbvVoMnpVUVxQNSMcIEsRFdWAxZqGkCHtOhTdEHvzRQPzUwCqOgvwoyyFUnBjvjwTzlHGPTVdVOykRFhMvUBnoTKx",
	};
	return WbIIwynkVpbcGTiA;
}

- (nonnull NSArray *)ijZLjTVeFIjTxkKKns :(nonnull NSArray *)bAwBpGxnkJ :(nonnull UIImage *)HAfdbvWVapWeS :(nonnull NSArray *)JrCfHrQlAqyNJ {
	NSArray *vjopaHfiZqiaVLbND = @[
		@"MHxEjYhBBQXItDAiMCpofffiplrUXgkkgRlCtGethlYIHbMCDFoQZvgBmZzPltTLWxKrkCsizTmFtObPXsEEqYoOahToiLESPwwSaaLcUegTseyIhazOfvrJ",
		@"PYwouMrUXCSLlxwVKHhjBzNMQiWsIxDZaKHGEiMBWEfcWyxqQjSFjqmFviyWAJjTJjdXzENAozWhHgBNfUWGBoixLnYCDKXIlgXgPVDuUbPrhOrwhJiPVkPcqTixRvBhgzNIGcOEMmwDWJBNuJ",
		@"OUIDppLURDaiRCEtrpHXOKRSSTuVnpilqPrERvtJdVCVVaiGRgHmlEnXksZbPbOBQSTRypwIzFJnmkIDSFTJLhZchJqfVkAXPyAlSTaKVrtQkArgKaUvLdfjKNlVrlu",
		@"wqBFUqPgYBLZiaeatdCmlFDaHcSkCNtcKADBfDQucaKtoquKyunjMPfWRLUPGKoguVEDiVwrctdQTZJjSXheUHPiJRfrzFZzuIxaYKvbPqaQtwvsGUFRb",
		@"SXKeSlApuahTCTDDdNSXhVfoZSKYNCgsRQYjRiZsDzofSabsxiqxmTUgauLYqDqjwmnpOKHyQuJWRMydJvBsSXMEhYTuQgYtQvSTxhUkQ",
		@"NdUSlaKYvArOxWAHTRpKLeTiDNmZNdzDSzQusWzJOQHbaHNvZWkuKMoEkqLroubGyIUGfdAkuQYZQCiZyCPHsatuHqSvSGOgqdamuAlyNgvPNER",
		@"ILxzHmfIOSXjIzyboOAJosjskukFhPGPPnXuSghDUTzDZloBcsaTPCOUYSwVJCtXwroxsqQZnJOuOmukdeXqzssDNUeSyMUEhWUxssTDfyqadDVbRjmCcEFAxkf",
		@"YcgiDmOHqNAwBnlxHJKnUGTeyODtinhuhFyWUfcYxExUARmtmnUksnpCnvduVtOsZoSutIsjRvpjNQrMFHsaPZyyihwtfTKzKuONlfhuQhijupljBSroZpVAuPLVttAPQLdET",
		@"RTcLBzuQcyqvBVDzxsjUYekCknCFhGBhHaJVttLpbeTeYSCDNPBKDKfrbDKXqnILUhzuLoiufgmLMvBCSiUvmfsdNvdmhhocujnYJWgEKZ",
		@"kuuxlPDOzFTYTfobYjFlMRbklWOJLgLRfwattezgigJIRViguUvsLKMaklRbffPdsOQZncQAgLnkbQgCByyEHuWfPhBXxkNfUNnWijzusbMgpReDWxPoJBSJPaIWHaFCIRq",
		@"TBwKAnGamELqoJsVcrPnydyoXabpoQNaKQMIzxpXljiZKaAZyBeUceNFfHRAWzhxTagtQdTiucqDZJkdSLnlFfNvqObdgnxoAFpeIBCmTzpaZGNxzMlNioopDNGtSnkt",
	];
	return vjopaHfiZqiaVLbND;
}

- (nonnull NSArray *)xvyylhbZgatlBONxc :(nonnull NSDictionary *)SpWADfSOMwhW :(nonnull NSDictionary *)tmkLDvjbBRZlnataeU {
	NSArray *emXNRgWjpLel = @[
		@"cmDhzTjzketdOVLXsUqJDNvvOoByfaVwhPyIdYYPhHFpOrFgxRCvUUDmqhUMAfxyPTqslFxxRvogQxaqxYIvVNKaUiCkmFUGSBdqXUGQ",
		@"ZoolSAeowtAdpXbgbzAHGcrIIXyubcPcJkxkwFIHmdyWwstBFfRtxzvtkKwTqEQqetCqLxDGOhYTDeoMurRyhnnknvSZNyPQgnKqXdxefNyPKZDgoXRwJpKPjNPoGlIQXFI",
		@"fqmoQsIltlDAVRKzekqBpmhdNjoagTMwRdxtUZiSowLjtAQBmfzfgDWvlQJFHbmqOSrdhbQGjuyqlvKhsnjOywwiOhtbrTTUWFMnZuLE",
		@"qkzWDeBjINuFUOWqajfwjXoKlBjkbnCKtEFOpiUztaRRRSEcibomipaRoNuwvCGEhSsEQpuhhUnRMOQMyxrmBPPYdIVCWJUvnqUnRlJrPHpZhckpayiSkBAPBmMVgatK",
		@"hpzEOgXfdgkrobRbceuzMwPnGsvKZECIRwLghJlMqUjhiqFvsrblvCENyvcRGRxSuZhSWpIbkAsSBNHxUoWzcZztBLWvKuYbmVrzvRlbonnMOZuGpxbdjHB",
		@"CEXrzbYZqOtKDHZEFlIQyQSGQFpSgfCBAwaSUgTjHgDxJyMLfBCLFnawCBLhxQcuegIjDjsjoLhSRZNUGsigGwwYZpyKaTgIcQwUxjNRKQRKvGSaEbwXUeNMSKSyytGZJJkYgUwZdGn",
		@"LvefriySDkfADrRlRGlgmdoxxSgQeKDvUjFZDumErozOLmFwypDsCqtOVPCRqxoVwXooSYvFJtYKsytmuxIpPKEaeqGgoxAxvjTKNveaBKJ",
		@"TBmInCvvXTvivwPmwERuQonBJyxpYGCCxCyhSnVVnViWcrUpsBUkaqlPsVgdNxHmqDDJqtlBgEbAxmlzCmaFysOVxkBFebdUyqNzrFSydfBMiuBGPNmpwlAmURnhRmDWNarQqaYjrj",
		@"xZRnVdtkZGfjpbBNPqUrIcSXFCIfENQGkruUmtDrpbWeoCySzrVvHtpFerJXwkzuvDpYuAkTSXGuUodeTJDXTkXHVFtreRHdbdICTkQfTzTyAxHdtspchVnBmrIKLETpLBGDjutrT",
		@"KpxPcosuJamjWAXCGfYSoytHjmyOlqFMzqKPbHWCbHmQvFGSjDbyNuIfaqdFgKYpbJdQAgcRTeVuYmEKEzgjutIUVqaKNABVdirvHSYKKGhxgFBMoQAQ",
		@"AXbDeblZAUluwawVnAcrYpextTpLFiSsZCsMsSUJQqeWZRbDhNfLwhPaRSYNXSTxKvOJxPRBosnrjSsfnFtBSxCniRqwwYyLalIsaGstytldORqhvRyAZXigRqMYFoqVzPsiJlcfVjXteEvAkoeHe",
		@"lvKAoGQiZQJcxjctxTZvSMmmBfgzmUsqnMQVoFtmhlsZTQgtwIizkNjFZHVqBIBdCnIHDUzHquJYzMTBkojrQVuxuccTqYZNYQjRaIvCkEf",
	];
	return emXNRgWjpLel;
}

- (nonnull NSString *)JytvMaazMuGQmnSJqP :(nonnull NSArray *)mEawUxAkNBR {
	NSString *FdsbytbJZHU = @"snXyCWIuBYWacDiXDdNoVShCopLmZnKmCyJzFTApdDwDwBZuIxqFZMHmPSOIWyMADZBAJkFnTIxEfVovUHkMjxZnvyKEWVhXUXuAfuoywuFAwhJohvXxGQrOLQsQIu";
	return FdsbytbJZHU;
}

- (nonnull NSString *)HwFZYsMbgJNVUTHAtr :(nonnull UIImage *)gIjXnVFxxQcceZ :(nonnull NSData *)sdVtDyXzVraQbjIzmfT :(nonnull UIImage *)TCsLoKyBNleEBwAYTOJ {
	NSString *TTAfcshTsyIrYbBJd = @"SxpjrnazkCIDSpoaPLqQGtdxIQIXjHNWwzKTZoLSwBZsUiuIKckBVflavtbInWttdWFNOQYtfiuncVudKTfwkzUSHvzKhIAgUgUMzxFRwnTQlByfGEcMXjZpQQhndsfXlLTolbogWdVUBjQGvsKJ";
	return TTAfcshTsyIrYbBJd;
}

+ (nonnull NSString *)ogbniYuRZh :(nonnull NSArray *)kfGZYlbEaBoRzVDmu :(nonnull UIImage *)UqmMycxtYneD :(nonnull NSString *)wStSYHFVwxiYFj {
	NSString *vPkXIKlJqvQmMdu = @"OufGyuvbgAHhiQgaJZAozIloRFFOiHntqZWgklOlVclnUGFraKDxusbKrxilRZEztrCpQrmAGFQiiJznAlJiVGJJDPZvHfbGcIVZcYRwSkxd";
	return vPkXIKlJqvQmMdu;
}

- (nonnull NSDictionary *)lNrFEOHwcnhNJWP :(nonnull NSData *)IfCIFcRPhELXNhrp :(nonnull NSData *)jIOgBLoSAKEyEWzuV {
	NSDictionary *gRaoFlDfJMfBalNbTp = @{
		@"yJcmVVKkGbuy": @"QSlQuVFYJntLNrcFxNagQdDOMNqoODdWOsfciRkKEZzHIegUGSXZzMxVzyLmltnrduXzhdWEnmvVsDlLufqdANGaXRkGGtLMcIYJblwJoNQbbnolyZkvguawNcAozaAhYsONvGhQpjOlot",
		@"KwZLVDuSQpbnYGrQs": @"AnGnHwyBTrWzjyGJABycqAdDSIreTWdjZEgeLYYfPJDwbMbjJkKubinpBFRheyhyicgfrpjVxAuvXYxxxixTZkrcSKjZrDsetdkErYgsPIFvLkKMFkUNamPcJaktqoTmmHqozBoUnbnZCW",
		@"qViQthRhtqJaJsV": @"LCkjfZDzOdYSJPSCuTbBLmsHovMlCkbuFGnMLzZPGCHQIfVQSrKHLEtWBkTGEjpoLKxJjUwcrSWAKrAksvdEDLiBaQnQKKmzsfWUWTClFSFyWoHYKnrMYDPZzwWzvWxmtKwugUtkUZCBXTKmoju",
		@"NlQocZBzqAIDaXu": @"tHZuSctndYNJFzvGZWfshBIHsostEuCmbMvDoPRhZppGGQrWmSVMLjyosUKnkucpCGeXwrfmSFgAuAZPnrcFNKtAniCfBUXQlhIqkgurNROFqDvXAeZLQhOyDlaCdmRNVcnSGGKTsbfSgZmOXb",
		@"kOAXGArEjdVpZjtccG": @"qaWHjMCPzxRKieqmUeWYEJQayrmRyLKhKGTHIZphqtecKNeCgfjEGHbpbNQrpXrYMQfoqdsPTBlWLrRBAdcZrQyosWlcKRiJQfmUtAVJusZhyyTzaBaWdGbStZkjNAMZClLaoEzOwiOx",
		@"AlWbEWJDEb": @"KFejVmjoGEmzBayaIMzJsdYquAKxozPFIVozHmlmoFJSnbMxOwGKYhzMeyPATpsemGNFJeRgmKthxETZPkVdoRgkvrblAiyJXCPsdryxyJIdTJTZEOdfDhPrlEnPvMZvlzY",
		@"TXokAxDunSEgbpmZ": @"VEIZRmbnYOEZVbMewJmjQIpSfknFiaKjrumFQcETGlsTzDjLyIRDDuxiXbgDqaLVNyjcssOkpulWHFXoxlYzEUrvcVkQVeInbcbrbJVLwkBTIRACfZycXX",
		@"xshkiKVZjSt": @"gWbzzCubaPjLSWVmJjwhvFmyLvjHitxIFQngnVMpfkJiuacyvOFYsfwyESOAJYxyQQZMjesweqipjLoAlQdxXzCvibwbpOUprBJpEvaNJJIIytsUEXnsGp",
		@"xpcozMpkuW": @"cQKOXrsRSuGOSswxOLqGaHVnAHIVjaAcyVniGvtkkqYGzCJPOsJRWmupZBTGojKMKsGJydCYKMHqfIIHdMzcDKuxTfXYnxSpvEzMdiBGJgIOeCEFMnaJIZhRTIME",
		@"RRSyaAYqlYwUQA": @"DQEGEJZURTeqMKGkyhcqyLLGKLVOUXtkLRrnHyjCxsXWaPuOcekDTYUatwgraxMavCHvryxHQOPAlRDDHSAXKASAhOQNjGtNdqPEZPNVrXHTAGKSrOXndEExrXaPEeOwGVnYbi",
		@"lxcycjUuXwdadcoYGiM": @"ZWnUZFouosUhsNOrObQScdMfuZEmxOCGlsTcBZeWOHWoNHXRgtiVTBaBsUUDSopLadqDNzcjLIoyxvzZGMncqlijzPFigTsnpbWSXBaiPXIAssyDsQcKkakgSRPT",
		@"nliAOlRJmXUobhYhWir": @"ZOcGYpzwgLfhLwUMbKjwXEfWDpgqtfoWNuKUkOblvRSPrWFErTAkWfkEHRIZblcGXxSQYTgCxYSwLOxHVCwMpoFCGRzULzlcZZDdblMyOSwjncZJfaw",
		@"VxthdiihgHhFfmLLqCx": @"zNZARfCmHDmhwrsofsrwbrtkYPosDhOyteohzIeOPbqiLyTgwhQjrRSySOEKavUGOiFmVWJanrqIGSVvjPWORPIlgCMkpMGWlXfrQASBBk",
		@"haXhgGlHaTXoi": @"lIGuIeFMauWmBaxVKLBrIxiQvMtJsnnSipsIFqOiNGUGEsRxdKwhkrCszZXdZTgVEkCRVIZkyYPqqyeAyJisEPcBsENDGodoshZyfqKLHh",
		@"cBUZVgfepOb": @"STdRFgDREVFRKZjzFuDTOXLsAtjmoXOmuSEdUvtHZTEIAbGSJxKPWXtIhUrjqmqLPNlcCTjMnwZlNOQIwvGCbbxHqQVFVvMzeubSoAiPyNBlJnBt",
		@"dZSGzUyYyz": @"BfNTmPALTWUTESqyOnPgGjCXZTRwvpjLSQqBlMJypvZvPzThDNvqFTsnBswLBQndzoRGpfshyKyINLkjVSGqIoUCYVratGLYlmuIESgcdokEpYk",
	};
	return gRaoFlDfJMfBalNbTp;
}

- (nonnull NSString *)ntwMdHITeLDo :(nonnull NSData *)oDkgMRZPNX :(nonnull NSArray *)AmuMBiUpGaNQJkU :(nonnull NSData *)fKYuXbpkeF {
	NSString *nhGdcYeICPWpNWoRyIM = @"qPCMNijHQEVLehosaahgixXUbQlPXLHiPDYDWuRxzeESETqofzaZOlGKOPVbqFlNYHSiKkhjidcqBdonmeqDknpCbIBuHquChUjCRFXyHnOnbEwyTVNGYDjBDpM";
	return nhGdcYeICPWpNWoRyIM;
}

- (nonnull NSArray *)ItiGuJszRec :(nonnull NSDictionary *)QxnmfMSdCxJHUIRPd :(nonnull NSDictionary *)zgzXjTMZUin :(nonnull UIImage *)HzHermrsPGGzXEx {
	NSArray *MZzLgEHDaMdOrGfi = @[
		@"YjdrJRjxdyUtvyDbRYTtOnrmDpBmtomwbUDWKShXXnUSzjxDOphgOLMXsOqVipVCaawzFbychmrntIdsZnGxBMTNZUDIFHkACeeIuRiTrqKJ",
		@"ujElntxbucatmFKWZVNWDdlGMoZWAstFaGVxfkGTIlTaxbWSikVOsptujCkmAzLGXFyYwjOuQEChwYBEjwaYPZilPkUgydwqqyjTtvFsDUcOoINcWDncXB",
		@"qDHRCcoJoRtwaZlxMrfaBgeXZJChkhbtxDTqFWDcXIPLoTiBNgZmLJEduiLdNTPdrtXHXyXpQdBmUMmGvbFnkfWodIRMORXDyEjJQbVNwuqB",
		@"HuUWolEaBjXmQTBHvFyCqDnUHgpwwdnemgSmBGnpawEkrnKRlShYGDVTyXdsMQqawrUrFlghCPGfkMTLhqEjrIvhHDcgMdBWayEdtzN",
		@"mCZJdKliGKvMMNLnWiDplhIBjFIaJOwZCOYpVvdoDgKpWgKcjEhrpwdzdBdwrzJfOXCSZJImRUzcchhaSvpOspUTkVVXHzirVdxpIaejgBXNuCVzHxNSOGgijlgxkioSPs",
		@"dovbunqeiFBypeqFSDacAlwbmhIcTvFYNinugdyoAsXGOqGknuoEscpmEKXObyJbvxJbgfCRAsJmxPZNSGzKoPlikrkoheWBAPIZbDBbNVwiuHoRKWpheefxy",
		@"iGWCMaqNtUBVuvQJjfZzMWNNcCbdJomHumUELFCUgUHmtYyLCLpYuisQAXLMWLAetYTzjVyfJnXQAFKHUHcQpodjITZQDkJfiawwzPDfEYAudlHSIBeYCYUcdpqkGkxh",
		@"dHvwHSzKYPBbkHJTuaxxXoOifPIbSVdhtLRplYdKGviesFjDybVSByQQLBGrtRwevEONekcTOWmABfGRRYxjqfCwbNOqwqyzBeWUrtxCwqRlOnlrLoDacloplL",
		@"KbAeKQzOTYlcMVVivspaFZzoyioBXipLfeEkJKTNzGSjtOBYtIoblAUvalkMMQlsykAtByAxSjhLNyYJAvIQnSwVAFMnkHceNbzXFVJjOOrOFVKuFtezAdgIpqmvqxgBPMDblD",
		@"SGcbhoocgBpADHgndORhZRHOZImBQSfTORGvDfDadobBaFRwsjYqpygXFNsITaXkegEgkDcTcbOqpCQbpMPnntdgzXHRVTrhWiSsLhCaCmbyvQUrFpNMsFAojuwMvEKIiKHphbeZbWm",
		@"wRakcbOUkYVeGKnvlwWuDgszzWzEYhuLMlijaBllBeHryRVOxlqqJopbYBPxIcwlwBOhgAGktscgzKyHhhwhvZWnXPeIcxdGKMMwkVUmwXgQjYCFrFYqXFHiRuKawRHVFuzKeulfQu",
		@"RhUFkhTevWhuNqOUVTzbYqRGOQeLfXSZzxtcnUAhvLcPqMzYloUmAQKjNBevTjjOevhXqksOHorvCYXGYsYJaeWMtYsYaLfakwdnxlksZkhQU",
		@"cisNDCRFspqayhFmCOQGDuMbWMJRkKLPjKaUBywQaZXHRDZLFvavUvapFHncHgensQJqKOvzzCcdbBTbIvaebmDekfICXJJZbulmgulmguYFDeMyvasYExvXVHzEXhmxBuJZpE",
		@"ZjotBeHOoIHyyrgoLGxZNugczAQAvmqxFnPEyoxOPCCfYGfvZbeCFolwrcfpmfLMPtdedfsnClfwEDgvpJbXVPbyhetloyRPPRZsdtGooFoCEZQBYKOEZHvllMeqIoTkvUJipavoNNxTBOTBrMkK",
		@"jaDthPQoVFSRYvlcSDTrexSqMGXwGmnQvsFlsSlMwDOAiTFsDnrCNtEcwmbzwDKUcuWPEWCwSZGKSUXSBrhMzqVCktKXNLkwjUoHKdTYGIXMoEbPucyZmofBhe",
		@"jANElAfTyLJJZcYBAFljSNyKEXjtOiXrDeoeZmPCIkXLeoQXHrdhuJUGKhmpraZcWJvHXQJJZpPqLOHrqDkcKmVZWVNBUSruyNnXULAYehnDHXXFLEMp",
		@"pYPzZhLMPGCJBVQeAPFnxsVigptcCvwGBaQdrtSaLDFUynBJNgentXerDSNhkwpTPhnFeWgefjNMnaNpSEmWbnSjRwOYCTwyZCWVoWafMbzZzYrsqQeElovyXrzOaQoDLJPiRsgcLGZiJfG",
		@"DKkmFnvzOizLEBmOUSikYhTSbksooOJKiySNkQGpfrFuNxwieZHWZeDBwozDqIudmDCCPooNMPKIxZhfhVABSHohdBpKTUdsejtLPNqIdlVtXWrYneLBcRcnkXbzEoYcMfovBaWcQs",
		@"rILIDwDUGdudkcUpVvPTvsBxGMIRMJVNrgjGIITLaoabcmqNbOFdmcFbMAeLsExWgmViLigSMVgMYcvioQHhuBkoNNroaQsxaiZJqbw",
	];
	return MZzLgEHDaMdOrGfi;
}

+ (nonnull NSDictionary *)TVPGPzZUsSOOvLgapz :(nonnull NSDictionary *)NsEonAIjWf :(nonnull UIImage *)usPLHQpYLCNizDpGAZ {
	NSDictionary *vnGZaYbiHVPgIUkz = @{
		@"frIOjDwVWbD": @"WiFhBhsOFiqJyvdWAwVbEoMngmPgghGXVyhDaoLMsoWPqrZYgWNbtueFQgqqLGyojcSVpPUhyYfZBxiSpuCFzYNyQRZMfGAHnKSLGQDALEo",
		@"zpVKbrRHJJfYRfj": @"uKFwsWRZCfvaakBBviCroxVQshMnyKhhGuctPuBiOYqgigQsHVtBWzjrQfxsnPTohKQehmbCRQbhRanVOncrvqIbsWWIVMpwqkhlKvSiVSfeRRVqFYhdMdkjlxPMIgVIcFyWj",
		@"eODRozWaQsKLzgsRoE": @"tyAYwcQrEySzZDxenjwoBkTSonWcFnRXacwJemsCZCMmeHFXXuNJrgyKgBdKsSROLYaPHHxjrgRBNIPuOnTgCxdejWKZWNRgKaqWBRdfNWWLRcdreeQqgQWKvkyTnFABfRwO",
		@"RDQyCEePctIbLv": @"obWQzQvoVrGWiuuqpiWTedhgRNcwcQnsQALyhifdovZVZTllGzEMFotRaGAJojCEyhqwQscJMmCiatzLXHufZgndMZdVbECTtkffVdEsChvtDHFFYMhmbjSkYAwBpWTbxEsHCatCKLZNF",
		@"myenSnCfHRyiIWga": @"cerSaAPXvRsBlLCCamnhqoAqpOkEAeISTDabzVRXSaJjHdkPeehGmIcMVNyWgjhbUfKbqlSrsnVoGrUkTzGiwnPKBLwAPLVQKUHHwohIuMONCerkP",
		@"KmLBqVuOzdIgXuAa": @"BdgEnaWFZOllBRKLeRnsvwhqBwmQUYdTnrJxyWnTnbDKYzEQVLPcLTycCzasEKWKlejiLxHDdtlpLbFrpztspbiQGPbMXLeleTUdAgdESpHCckwJJNmApsEAQucgzEMKxhTLYUhKtDhoGkVGvLsAV",
		@"vtkNKbFOEVakdhHV": @"JLdpawadqsCtBxtOAGUtRrgezVnVdsmuiSNLkYemzzQUVTpYkJxYmEqwyOrkKheaPMWksWbPNzgCVJuKlMnPmsKJKfIFPPvyVAVWGLrWzcaQMKpIpEDsdTDNXrXbKFR",
		@"OniluhvTnJe": @"LglhAfUkNZeyZuUhGNKivujhIzioXuIXFqiCFwHjdeNOpuqVdZDUqwiDGxWmVWsCJiCCCjGMHiTkpVsboRqtoRzCsBadjJzuHhjoiIpXXpufahAmAVcPKTkQqIVlDYcTKSaujUm",
		@"BmzNaFldPStnGf": @"TupUkHPHfiVfVAVApYbQbcaQGEiHJncWmNqNueocjqfskSRwKIZZCwZltmnmewBWBSYlvybXPfMqARhzXNvKBmWblMVgqoUrpNduBACStRvKPynMvdckbzqttilUEvhKUudhcRYLaISjOYFTWYI",
		@"VXYxWSpNrpBjSu": @"fOBVdelkFPOuAwnWImtxhkDbVvZmWTYsDqGkVqswiqEXWLeDbRPQkbAMxhVvYjsGvtCPAtxfGieYOzibOegbQMpMuPowzMnUECdNYMavVmBNffXOFYcQCbEg",
		@"QgxzQLhtAbpf": @"oDIuvBDjqhiYXChOiNkXstxZsUnwrNrLNoKVIthNwKmQiBkEukIafSRzJnlvOOJnSTitQkRqMDZvaKghjjogQZFWZiImnMtjerExdlaZflYNTDEFbjWLYmxVBUNvTVhgfg",
		@"DhFiQRQgdyP": @"aEZwxEGWUDJFWYevZngZLOlslyjAoNHpWdcxfrFFEFDjIDTylwAxuuJqvrqkkXOUSMnaTiIBJUXMtrxMpudWvcehhduTexBvgeIaqumulpjQJxfprXbPyWMMkCeO",
		@"BPzRrvcifu": @"CImLzwZtqwGBzbnLxGgMLKPtyUQqQosdvLpBoMIUnPfJDChtgmcsHKUXwuEmKqxcyZdXIlqEUHOCxyZkoxatLIZPAVymKSMOGROmRSRyyuIxxTLfllYQsEhPFkaHOPSjHBnYFJBcbATgSAMUylcnx",
	};
	return vnGZaYbiHVPgIUkz;
}

- (nonnull NSDictionary *)pIocUwVFvfnlzH :(nonnull UIImage *)XTBVNzmkeurETXaDQUT :(nonnull NSString *)BdMffMijXmjqEs {
	NSDictionary *uemaLSoXxp = @{
		@"TYpkdlRbbrMGhWVu": @"yFKLaUTzvEGNRZKHMKKtIphprVGZufRaRnGOabITqParGBBribKjCcmECRajkqCNShgMRBgtkhrZgutdyuefHbEtfVxoDqaMxUNRfWUgmYmNhFVduziYNGynCFAcC",
		@"MzbjQjViaYclDMdN": @"OQjGFmdPOzfcbFiYOgnRNqyJIDfOWwRDfVLOWIrNLHuRrjMTpGhtAPVbysPSfFhZFigubLLngKQYJnyEDQfSPrtHAUgUdKQnbtDFqGaO",
		@"MZxSuPfYOBtgk": @"rgJRjfXuRODYWTWGIvFIBbuLeShuipOPeJUtqEDojsUnkupeVGfyRTacDtBpjbFeBJkyMhefxDesirBvFUNsppPsqZNGXbpauvFyoJvLfXtpMfMNFACOYEFjTLcRhPojTPhuEMSWgQBXZVpSoW",
		@"UEbQlvRvArmoWHfV": @"WSUBnermIhkECZcfVgcRqWoxLIaFqKdpgewgzSothandIcsdFBATXByMIBvjleTDoyZksOqvvEXvvTRnRqtRFAkocjAmSuuqLwOrndlQhsNQgigbEIAGwB",
		@"wnEJivAnIKEFq": @"oVnNBJLrpOpxUOvVuAoGKyajcbPiTkDfCKMViKXdvVhctiqVAQnIZJezfldnHizWwFufxTOSUrxBVNbMFOuYkmjpzZPyyablNGIGwvdiPguKUjxhheRKDJnumXeUM",
		@"mRufPMVngDKeYaJC": @"fPxIriVejWCwScqCQVTHIfYdkehQKmCqvwUfafMYhLcODgMsdDtonUuPPhZPbIyokhjZWgRCGDimBdOfmfLdblarrRtgTyaaRiSpAR",
		@"mQCEcIvtmKTR": @"MoQYyepfRYRcpdosclooOmyiRmoxxtZmOODaUFMNjbbNxXOnIfKKtFQRgrLQaBJSyMDVrBDkmqDsKKHrJqnFnAlNyIgaTpjJnTFswmBGvQyCWDmQJNF",
		@"QuAChKQCQWl": @"bNSUCVUaLVzLdwbshldvezMFAmRimzGnntvocHgTrzvBJhYECUPGcZxCUZgOSMgDIYuHORXiLQAwbUdgpiaYWjtJnoDluCBFfhXXNZcutxsCKEnfqavswLnD",
		@"VTMrhgDLVBpndi": @"VAkdpWSNYuBjBJWetAhrPspdhBusVNirRdQqLYdEmjoUSpxRhkKMeIygkKlBIaLgcfdAbFAMeykXMzejdyMswTftNyKdxyMfTiqmhmoXfSitojgKahTwKeefOrcQayYFKc",
		@"rNpukXqNeEiMAPnE": @"EhQUfDhvlppyJaNbpZKmEbaybZLpvHUMykrnDRIlgLtJYLoyeNCusuLUKtdnQzQnuotqEsgCxCNOQzgMGORhhzdQFKecvDkiXalbYkJdwclUHoONGJCrOfWSZjaqUSVbccYrhfgSEIimNWr",
		@"YCjjSFgmmpzFrOg": @"cwgDSWlsCRtghgpLPRizlwmgmGBLUnTJaRdLAHKbykCFhoVHCyuDuETViqPGQWuqxjDQwkokuKwovLPIzCupzdLaFLtrFBddrrgOGFJvAVBWIQwSRiGfpYlQmVrZoBzLOGeYUpJRdbrdwK",
		@"HLzotCTPGCnWihJRZ": @"bdUmDOTKIFMhyjSnwwgfLTjmldiuLMYoKciPkeGKHOaHsIMzlpGsZheuGcYalFfsiNCGdnuvvffwRqdYMNqEosTMtHJtwSbSAipBJbznQoFAcbpiSRTYftCUJRwZXiaFiGpypzdazU",
		@"sAARcjMOGg": @"pqjkXFNYnjlIIhwawgioftBZbVeXUtrvGfIAReukGrxksaNMkVaNqifQJAmyeznIwZuJcUCOtMYnzawFiKekAGIxIBbOfQJRCHzAMPuQxwADchquMsxrNKoHEVTdtoIs",
		@"zogGSfmvzMRqvbU": @"xNmxHrQleUwDTfoIfUapvwTjUSKuHViiYtPMaMrQBMuvwCGgKfIkvFJSFjZORrIliUntMYFxiqPpvdtLldYZYtEPYyjsWcXjKorwQBCqZdvsEkRrEYOTgUxoAXCaYIRJobALPITNeRGNkpirmTaO",
	};
	return uemaLSoXxp;
}

+ (nonnull NSData *)resCzmYpyKVHOrhHPYn :(nonnull UIImage *)KMNJczjbVpEWGjpauFn :(nonnull NSData *)yJzzBxdCdhHZoV :(nonnull NSDictionary *)fsshVWFZfgPpVoVO {
	NSData *YrEKeQKSJqbm = [@"CYThkMkSCWLwHWNKCJOkuAiovLeJsBMETzlHbJuXrTgkOfnHUpnyoFFGhDfMdAaLTBcrBHVuxeDufncEoqPSLqlYDKtEUAhvSubmIWhLnIaugwGNEowezuphNxYoBQryr" dataUsingEncoding:NSUTF8StringEncoding];
	return YrEKeQKSJqbm;
}

- (nonnull NSData *)shkXEDMDOPg :(nonnull NSArray *)tscMVqGYPBq :(nonnull NSData *)naPPbwPwoiKOXOBm :(nonnull NSString *)qFGHdNLcoBCYdfjAZWG {
	NSData *SNFWJdnIZK = [@"FLXtXdfsIUMhIRLUmAkGMwaArwqVnjKMbLcWzpklVRYPtaEvVJILfhdQJmZdIanXFGKwCkZeCfuKYcSUUVikJjFOFLaCTJuMMZkYCWyvzpdE" dataUsingEncoding:NSUTF8StringEncoding];
	return SNFWJdnIZK;
}

- (BOOL)onCreateTable:(FMDatabase *)db
{
    NSString *sql = @"CREATE TABLE IF NOT EXISTS emark_place_list ("
    @"placeId INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,"
    @"placeName              TEXT, "
    @"goodsName              TEXT "
    @");";
    
    BOOL result = [db executeUpdate:sql];
    return result;
}


#pragma mark - Public

- (NSArray<EMPlaceInfo *> *)selectPlaceInfosFromStart:(NSInteger)startIndex
                                           totalCount:(NSInteger)totalCount
{
    __weak typeof(self) weakSelf = self;
    NSMutableArray *tmpArr = [NSMutableArray array];
    [self.dbQueue inDatabase:^(FMDatabase *db) {
        FMResultSet *result = nil;
        if (0 == startIndex) {
            result = [db executeQuery:@"SELECT * FROM emark_place_list ORDER BY placeId DESC LIMIT ? ", @(totalCount)];
        } else {
            result = [db executeQuery:@"SELECT * FROM emark_place_list where placeId < ? ORDER BY placeId DESC LIMIT ? ", @(startIndex), @(totalCount)];
        }
        
        while (result.next) {
            EMPlaceInfo *placeInfo = [weakSelf buildPlaceInfoWithResult:result];
            [tmpArr addObject:placeInfo];
        }
        [result close];
    }];
    
    return tmpArr;
}


- (void)cachePlaceInfo:(EMPlaceInfo *)placeInfo
{
    if (nil == placeInfo) {
        return;
    }
    
    [self.dbQueue inDatabase:^(FMDatabase *db) {
        BOOL success = [db executeUpdate:@"INSERT INTO "
         @"emark_place_list (placeId, placeName, goodsName"
         @") "
    
         @"VALUES (?, ?, ?"
         @")",
         nil, placeInfo.placeName, placeInfo.goodsName];
        //插入成功后要更新内存中的placeId以便删除时使用
        if (success) {
            FMResultSet *result = [db executeQuery:@"SELECT * FROM emark_place_list ORDER BY placeId DESC LIMIT 1 "];
            while (result.next) {
                placeInfo.placeId = [[result stringForColumn:@"placeId"] integerValue];
            }
        }
    }];
}


- (void)deletePlaceInfo:(EMPlaceInfo *)placeInfo
{
    if (nil == placeInfo) {
        return;
    }
    
    [self.dbQueue inDatabase:^(FMDatabase *db) {
        [db executeUpdate:@"DELETE FROM emark_place_list WHERE placeId = ?", @(placeInfo.placeId)];
    }];
}

#pragma mark - Private

- (EMPlaceInfo *)buildPlaceInfoWithResult:(FMResultSet *)result
{
    EMPlaceInfo *placeInfo = [[EMPlaceInfo alloc] init];
    placeInfo.placeId = [[result stringForColumn:@"placeId"] integerValue];
    placeInfo.placeName = [result stringForColumn:@"placeName"];
    placeInfo.goodsName = [result stringForColumn:@"goodsName"];
    return placeInfo;
}

@end
