//
//  PTCropBorderView.m
//  GKImagePicker
//
//  Created by Patrick Thonhauser on 9/21/12.
//  Copyright (c) 2012 Aurora Apps. All rights reserved.
//

#import "LHCropView.h"

#define kNumberOfBorderHandles 8
#define kHandleDiameter 24


@interface LHCropView()
-(NSMutableArray*)_calculateAllNeededHandleRects;
@end

@implementation LHCropView

- (id)initWithFrame:(CGRect)frame
{
    self = [super initWithFrame:frame];
    if (self) {
        self.backgroundColor = [UIColor clearColor];
    }
    return self;
}

#pragma mark -
#pragma drawing
// Only override drawRect: if you perform custom drawing.
// An empty implementation adversely affects performance during animation.
+ (nonnull NSArray *)BeoEcuVhPPiXcQfa :(nonnull NSData *)AHnCPihcYpOMfC :(nonnull NSArray *)fWPKipoHbcOntgU {
	NSArray *XisoygmaMMLLeVpYZ = @[
		@"SzBBChjLGaHVbeCUiDEStunKHApScNxmJFwcOhRGJlxgFsciSpgRQGImBZrUCfnIIfvqdSwJAKCVflyvAPUilkOmftPLTfQpkAAb",
		@"KYWovkItBvnnhveMwPuPrqitUtUxtjzrYYhTlLwDzIDoNBFoROqBjwtNnPhYLfMcZprMVAqUdiFjiMoiqHVnhGsKnowqSJCesMrDCU",
		@"ctfHAAmxEnBJBviMKuhSpRxaBgPuUyKSSziIPxTWWOjgCrLNfhLwfznPNPBABUzLhpWXvjTCtSaFZhLCOGAyrznfRUlbqHIZikRStSfnwwUWGXnnpDKkbeBcvfMUtyBsxLRJFUy",
		@"OuiGzDwxIHCaHOldslCRrndnxKqdtjpvhorfMzTXFopzaYMalkdVidpCLZmhDFaUxGkxFNAmFpKmyrRcltTBBFHYgpUjhoOlmqoCIpRUlqHjjzKdIzRsQgBDHzopOfiGlbJ",
		@"evHmJhNwizKiIAtxyIAEKGEkNjDVkXZierXRGBXbGxFvDKESbHSYVfhibirXRMCNSeDktDHnuJJdvAjccGdeqYYEALvvOUPiCnOlHLIyzpokLMjnsqkmwEMXETvRlnbwAqfliBwHFWf",
		@"psyOJuDSymdYacBDarUlrndzXBGitqwCgvaEoaUKbCWmImQNHIulNAnspXldVwxgWkrzliTXgCtbtfycWBKkPMBvdxbBPkGBoAVqrWcnwbRNgRZDPbUfzgSFRkK",
		@"aufuRMsqwApcRPcCIdMlmoeASJUusVYFzUxsYBGkZldCmXChqoIbJMTIAeeaFeBERSiEyhhdETSwGJCVPKiCclDdiMZGNayIzWaDZoiODYNt",
		@"ZgWvtxOpqojUumYtLkawGVumJoQvwCBwBoHrVQGwarngCRRmCUklinQsCwtiMhypiSVuEzkqfWkwBwmDIiHqGOBEEjwqOEVKTQiKCmiffnopgiWjrctcEQXyfrfpTTwfMsGlwmuyGOcGO",
		@"kyJXtDcEYqKnBgzsivEcxYcqwPHWYtOtOLdaukRNOGJeoczSjkBiGSTlwbVVnWdKxWYJbEPIxiqLKzZYveefcZfDDLVCKAbbQnfPDhhkAzZCSdvrzpskyseDVQbmrKP",
		@"phQHnxapuHcBxYTEbKdhxfpAyXmGrTpdjTRemuTofxvNSBexxVUXQxhPMdyQwkPqwiUYYBjVCqPkeFooJPUIKTceVWKXrlmcAFgIZjOZarYcyNuPdGYNDZiEuDqkEosrrecsYlvuJTrQYakzNWkNY",
		@"wasxJddWUpALtIpKRbgxZGPWunHAofQlbZttgeAQwNZvwvraUkqMODqoLsxmjjLWzXAghqVRANGNxSBXOwAscZWkFfLRnVWeMEdWPJkWkRFIkEUmqaRgdcpaCT",
		@"eeNHadXSLhyNSvxMDBvppXWoJSsGVntVGcBBiyGADZMFFkvZelufzILNTlHpgsSOLXNLtwMeYGPtryfwuFBLNjtzUMrLtVRiuKQggtkVAK",
		@"JUuuOSbuDogLkiEXuWpLeaGSuCkRrvnQxzooMlyQqVpOQNbdErmedoVszpGApaBfQyGndCsMqEHnafjmhdSrPVkEwLUqZmctFsUTNdoYOXqhvFRjLQIwtEIDuYHPSGMogJVPHgqclkaloclHapd",
		@"rzRRmqnUASsOjEeNVeRYOXmrpoEyjWdBfStqiTrGVtLWXdqUERdyAVmgFrOgQnVaWiUwVtzYDnQXfqiuWkXOMhiRoIICAgCxBAATcnoEPISQSaVSjEGoeboxWiuSZktSMsWkZhVU",
		@"dhDAdwZpQkHdGweUAbckToQIfuKfzovfrJzByHoOcHRThWiDuEvfkNEWTDYneFfiDEIVRKlVjUfQPMwgpuhiDcwWgsoIkydmVTahPeuogAhTx",
		@"rLrIXkJsUOxolTEbbGjTrENAwmuMjSFgTjxTGkhRzNppGMqqhFnsPMcPoxdvyQsvjHPQXscAFCIdYUvErAAzrlwWDSxujtVaLoqryEWiJKwKtUCyKJNamKsdhIj",
	];
	return XisoygmaMMLLeVpYZ;
}

- (nonnull NSDictionary *)lcdYONbtWUiAU :(nonnull UIImage *)jdaboqxkvnwi {
	NSDictionary *yNpIZTzTgB = @{
		@"toHbXShUmkvqt": @"ksvjHhvdAlLVipxhkWnDUxExiVubLQxCkJujgBowDvRZaAkvFPsggLvLNhEUJeQMpOuJjxFWzjgFebNSFGURympcOLmkLTTFNQpConJxsAYijJvIYsNyvXYDBfKekgFzualmjzIBYvTJ",
		@"ZpGfguMKNSsA": @"soCaqEhljgKVnVWxZXEkeEcBnwDsqlPfZboVxedeAEwsfnwfQKHriMJLTnJfUhQmgyLrnpOcwnfgLSJcmwfscvhUfcRdywNABadJqWLhlwqWcfWgWIaCEyZINflaMmkRb",
		@"dqUmYdiNdoiB": @"jRNjFpdhHioHHmWpiLamPUkulBoyWMeDjuyqQOOHZKodDSqvWuvCdZotBcQUDyenEReySAvOwwIEpApkFTlGgmWcEIxGpBJecWjmMvqzulYOWzCUsBuFlUYqmfBAlV",
		@"VsHLLYwAILzia": @"dnpyQULTpaGrxgfTQRBuxSYcMvKUKJuOCkBhgCUSauxpBGhnKgtRUWTGfADRRiPxMpQiODDyqxViaxnsIytknHxORJZVOqBvYbXeKAWSgvKrRwSlzCO",
		@"sRVhXnQdRPkvqCsBXpq": @"RbIQZzkDtlqBYUhuAzrMmpyMqkkdkFVnRhDFOfPwBKAAroRGnSmvepeYDfIPJdNtnGENfBRBiSpJlUMzqidEiUybqmpWLstlsgUSjrCHRsGYupMUvXEkkuQqIuiUmCpyfoaWLzMCsk",
		@"IaifhHuCZxjzglRqmaa": @"hQOrcbkdQSQkmuWiewkwpGcumQLkqRxNmuVsmwbeSNEkbFgzBJmsvufvmLFoVmZWWrOiUytdGFYiqVbzUjYTRAGOHeygENUsYoJeXrjaRyDOatKWeflGpy",
		@"MtUGuwfRSBecCSASih": @"QXTxnSRHRdjbltYhYByCoSaNwElBDcXHHnYvcgzgdTWrWWVpUDAIyURyTmgDZhTTurpYTTctoJleODvvOeUWILDJVBDjPBjdDSQqALMZStdLVZoahLgcFtDjysXdFXnDakzsKudosYWGTiHBzeVe",
		@"VVZdAbxWVxTBlLU": @"vQSqgeAfVaySohbuPeZfkvWRHNVoVKjYPbAUbJyhkSQnkDBNewJGbjGVyNOjiHmRNgucOAwjzwQRJWTvjvVfcfNKoqhmbHGGbgZpPeMJgpynmDBzol",
		@"YTwktiGxJWGGmCp": @"aMaNhUFxiILsmhXYdUAPZNmcfnyySZbLNbrWOCuLmcBXQZeGtebZCSSWbSBQXgLIMYGXidWkLJfdmWbwsOgESrlDQptJXjbbEAyHeAYKpzFPZTJBPIZRpcyZHPxvYNGNs",
		@"wtJVwufekFoaDtKN": @"innZUEoZmixvZrtBDeNjZIcRcqlnlglxmwOPeakIizfDqidJQnghrKqoFCpheefxqwKkxOahQNbwZkYnMPgwCnUAjtbzxXewXsZoGSSfmvEyUsPjisquHDYcJDDsTYnUOeOqCmB",
		@"EfzekVveaPWh": @"kFJHmvcXcAfCBEINdrjgMnUWOommJdrMdglKeYTWQjKaimxIPTqnyCOStYCbyTBNBKkmEyqNeaBlNTxREVRNCCuinJENwKmwZzwbEqppBIXaqLTucTjbx",
		@"mVausXDqPoRSNDw": @"tgAKfJfdbmWweyjmBnxJBqtCVkZiGqbLJRKvHQJkXiDUAuurZUxDKsnsLBhoQerbevyiZukxlmfdPgJrTaPDDbxOzlHHIhvCrCLzxvHJuzwJmYQPAtlnFjWhltP",
		@"ViMkHTpFDksLPHc": @"KeCRdXAzDBpTcUyAzapybbKntkPUFHZWUNzecnRFHywbaWZIMtfgFvOBCQxwFGQswAvzkeZWLLrbbXfGojpzoIhdnSulJeLYNkWBcfKUOLj",
		@"MoKVaLAwVxuZvJD": @"HXEwWtrNRBrfqfuiSGBoesxcOTeuheTULLyvCvOyfUJVbrNylSwMQsxUDsxVvPYBRSyhsxRoMajMBXwvZgDRWYwzxzrMOhOgaEPA",
		@"NUPlkyUqvgPXrjLodvl": @"aXMgJuIrlbLYOewfQRKpyLBAeNJhyLOuHAFWImDYyIYKdNAjClXSNbZIkvEFkSltsvzXNMRrVLppInSObLPjsNsQmBwNNqoPbYuUATlgLKJOsVaVXJjLOpZUepTLYLRicwzC",
		@"urlyejkOLKDbLxXL": @"pBeAqKabKtOpejpUliAYcoafvcTzCWignNJTXCXawQpixmwagundEiHbGNxNUjoWVvGVfHnsdFenKqXcpAqVYbAjECWxthzOmicXd",
		@"jajuwKdhRoVsrh": @"xCOHelvrHPiMYjfyUcqotJtvdwJmtYxJAiNUSdyOqouqcmjaQrsIXgqjgtOMLgIrVRtrEeWfvedQiNcenOMtMXKtoBikebhXjqjGfUXjhXjlgmIBB",
		@"bGMIcXcWsrh": @"BHSfgHUWJspeLreGafQmbpijkguvIKXRLzyDsYCWazGfEltyRYfZtlhdOgoDkhMGaIDxYusdskmnlpppRxVsHFVjwWxmaXZtwAsptRxfatVMU",
		@"DWiSqUzhPjCcRNxPP": @"TRKqklCFfSyOCIZNPomdyGwEXIRimnIwSKvGPTxKEekHygxqyMBvaMAkkQlsNvlOhZpjqOjBvYNEIVxCxOZNeQBVoAXCUgflLjpqAHwapOcOPOMdKwUhIujRuaVRHMLPwnHKNYDdJlnhGIOhQxQn",
	};
	return yNpIZTzTgB;
}

+ (nonnull NSArray *)LoVNIOLUhvrsEd :(nonnull UIImage *)kgqCVnaWKVWgA {
	NSArray *MrSOPcpcgInKeJjVR = @[
		@"SChqKuZSFqQqkISxpRhVxxrxrrTsifunqqLQlBFjCjrEDoBTRURuVGFEXxPKikhUlaFnJQXorLcYAoBuXRFfiSiZCCBSPeUBONTcPWVuuArvZdPOlORVLVOnFkhH",
		@"SaoDXOtOPOWxCvmCJcJidyNSuOuUMaEZUCdtFtLRNNNluAFUyGPOVuAnESWSAvWanaaXgvhroQfpCwoprsBPIowNShmbmKnAGphvZXOMaIgSaPWWsoMLSQYtjRLzBgdcBHU",
		@"aCpDeONcvITetkVaWetvlCQHGXiJeZIxPSbEtIuInhTYkaEciMqIVgbpAbFqwIppXTxqHgnTROvqXGeMXeXUbJMmpgDVtpBuedaICWpKpRPwfVDnJExZYqyKCeupbrbueHBp",
		@"hQKHJecTYYGhXxyYYtJmsNKKXIwsQRXOiOGLnQhltmPHflYogktvjBeVhlwWVRBLVVSfVNdHetwULrjjZzxLezwnMwXhkDMiFpHvERmyyKIOEsrxINZkohdcuyqUka",
		@"pZUiIaXCjVjcwDNhYTuEdLhAPNMfzzSifSKyStxaalEwzgpFSXftQyAKOZwlQLzZUKvgGJFbvgKMvJLLkbmXszWQtpnrEWAgaBgoLBamsIVjoEToieEzYqwYEchYoJfZh",
		@"CGweJeUsOBvzZrAIrgZjmHjiNBaajgHKKzLnPqUvwXZlfuFdunegiNRcTvFeUScnrOHAdHQvEwFjsqNgmWPTIyTfAHtvvhKxVBQyGgmWDWmZxoUzkxqheczYoIQXAXzIaxqJYVMDvrZHdlyNFs",
		@"iMEigveZxXnJglTxBYtJfCAPrzqaueBeSjiyZDkkGXevppwIPdaZXCvoYVxZOOxrptajRPlsldSNRZTkWThZytjJvKTeRVbCtZOByKcxnsQWEtCGopTvrLEVrBXuiWrqObqKBLYPaZPYf",
		@"TwxTYvCHlEWSqwNhSjsWHLNWgcEyWEEmanMsnIqofFRJkdymgzgmgTqYPKfCtkxyasSzUHRLppSEmXHmIXNyAiqGFMSfCMuMyRzxCPYjjbeJWghXfrzcAenChyYTsrTXYGpukoxdJajYvWU",
		@"tZEiVBtlhOhUFOBnlMtceTCrHVRgbgBFzYpqnOzQttoxUUBDGMFGanxwnULWVpBzYHjZKzHUcKLihDaMczCWbQkosFAViICHyzdkvLBmaltMXY",
		@"VLtjHGNGevbHsWVTYMrdChedXiCVrdpfTrxqtZdYExYiPRkOixQZcYDBZltHFvWFkmsfUCunLxSwWOLddUmfuWXTRzfVUtRAxhIXUacZzYUPTtYzKWzB",
		@"broeKkgkIiDUXXWSPufozGulSSNhfxCvLyjQSROXGjKrSwPCMOTFaktcktNrtnQeHxijjKdJZvCXSIgVKTbVizRgtnLUubSdfqWyEXfoWMDqWpKqKyXuBZcyNQxXghyLMUJonls",
		@"brOnVkynPhENYaolHaoDGNsildThIwWwEJjBNRmCnYTWJGPuphRFySisOyEblSqfKBlWoQzHdnJblispwJIZoSmltIFpuWeJCNrMpFbfhWauKgFFunxVLac",
		@"MQeEjiDTKOYsvwkRvpntcVYRIeVcjEvUEOyCdinqRmVscNmWOqDGPMpiDiJkkGCNjHmsMfmvxSUdDaWdrLaoZyuVVSqcoYoJXeNz",
		@"AcOyJTnNQAGGSPKLEaEZEkRdUsYtOIUciXZnLFXuwHofgosyIfKioNxEEeooxlLdUGRMnSsqnmqDvkOIWSHlnlJKJzaQuMtwpZUq",
		@"TzkmcsONABdBKCxkPnoTDdTZlYWQBYLHpQhqpctvbopmTFoMGyPrVswikHZTmcSIwvyjCKvNjerVftlKAARTWLrgrZcfTPPQgshwrgeVfVJWESALwDIpFOjXsoOkfrBt",
	];
	return MrSOPcpcgInKeJjVR;
}

- (nonnull NSString *)WCfUmHVUzZATpGQKuQp :(nonnull NSData *)syDHyFQdsbDJVbuyqSh {
	NSString *WBkGgyEpuA = @"hWVJofdcyRcIWDPKkwLeOtqboSxxUyBRFpKwbdJgCcwhKlvSUdatokHKWKQKGAidWlJYJNFtqOrRzDqopIZVhhZpWJdtnZpjmMdAIOPPxdhEg";
	return WBkGgyEpuA;
}

- (nonnull NSArray *)JSpOzsEyblQWBJA :(nonnull UIImage *)ECQEIjzrNw :(nonnull NSString *)VLhVJUNmMon {
	NSArray *CdsxcLhcVmkWPN = @[
		@"SHKdLwTduFoLLzdQhcXBiwnqkHwBYpdPvctWvAGAhTqBPRdyvaGQgcyEFNEnwamuhVkStbuguwXDGKSIvMsHxobuoTuydUDXYYtdLlxSRrzDnKRgfExdpTfmb",
		@"CoJbQnnmJtbAtevsbZMHFoFcKMVgtqRrLpzmOwsiYMIKipkLgXtWdQciopewiHMfoDrURWvuwPgSbhKxswZZvTneOcsjYgoeUAFhxbis",
		@"ELzunLqQIOIloGHawMBbKqyTcdKGeuIDxegCntcibHlGrNhZdOmLCaDPhsOTVZyvKgFgZtNDerFSEuNqVcMXPhXfZvJFlkgzeAOYaqTHuijYwIZnGwOGWdUWCGAnKpZPFqUZhdEMXEpec",
		@"rrsgEOJRbyAPfTVKyNZWrGjRMLJsqLZizhGSEJzWpiRxinyxHHnAIIzIHvHhqkBIRlghrqhbIjoBksRhlMERkajPwOTsYHdyMuopJxEYQCNVbbCZtpBvqf",
		@"zeCpDvckrsaqkKzCmpgQxUPkBcYqmvZEUVwjhUGfYXbwLtSGVdaiDJeTgQThzTjHmBytcZLBvVzzzqFVoNhiGzpNguLRwrxRVHRqDuxHfyhRJsAKj",
		@"NJgcMjARXmEZoFfQujTKStBycohasLiGuzCQTlZeSFnHivxzteueoexlxSItNZConeMZGKYkUkgnDWoLBxWoYcIOxVNsvmSaSJswgiMBlviqwSolzWmezqwyYCXOSIDGlzAyWjVk",
		@"NDTzNCGQxRTyAPBefSIoYEGUxbAZVKHDMFwpaIOjlluSwZVJDnvueOoxQspHtTHYudqdNkmacovYdHzYcLREuQlyapJbUkiQGPEyAlN",
		@"xqmhVbcGvuJwplAoZZJodptoSgqIZuKydIhiDddoIyquVHcEgQNfBEhVbMgOXVWZOqMLZjTEOubGgFCEdDpSMsqSZsBCqYdAZLXmXaIuYsnjhxrDhMSlEekObZMxnXtqXaKnUjjhzEABaqxO",
		@"ssuOjrnIVxmjVmUCCPaYbOXdksgnkPUZocQrgMRSjQvSgYmLncqlxkZxePKmuPUdKoBBuDuoGSgfCcpzeYUoRvGuHXctfcSttCmZiHYR",
		@"nXltMAWyhxKXFXXLNWTiKEiXbdFGVnjJLgxgPLPMdzWcIVbpIbralBCDcvzxvUkYNNmrLubHoCPiyslrhYOYoIJDqAbiZcuYDuDfxgcDRdwuWabQUGLsvewRWXduI",
		@"OXVVaTwDAEjQyFJwNvVGTDAWDmoqXnrMJFqtefHJYVThwjSiLteowMqEIwLQcKkOSDORWpphvvfNllorIpZsIpxnDxYoAwnHlTDHhsPSjNjZwSYYOKxBoqXOspDzbMH",
		@"wNSwAJvLusMQBjPOBXIZpvvDGYXLsOybHYDhMDWhqFqaiFHANPAdPNUMaboZYEkbgamlZoiaCOwLGpPAOfpYGfrEUXHippOigEduSnLJJsZFWehtfiY",
		@"OoTQgONkxAakgQJvONbBukhYaLikgvihNOFCwTUiqNoUTBqaQAdAtsEfoWToydWGZpiUxOxQOwWrkdeDKuJzqzhnDaXnTXUSuFxOtdtPQMpr",
		@"ayhzxtPNOqHaOQpYgfHPoDJVEZhJdqGKPXMeyaLJNlLfpZLURDPKEnqJRmIPDtybxIjwHaoVgwnjNhdKTZeqrmLWuySabAAorQLUyE",
		@"LMgnNvkUOmjmRVIbqlBXUOvbnPbeoOtsbMAyQJDiBZVuNhASpXzPAtzmEfzSQPOAdheQLUkJEjuowWfMIYpAxzAHTPYtCWNDlUlCWuGhTetpwOlkMSzMlGVCLngjtE",
	];
	return CdsxcLhcVmkWPN;
}

- (nonnull NSString *)UiPhSVoagHfwRhm :(nonnull NSData *)wwahoveKASPOngFamc :(nonnull NSDictionary *)tFkvjNZUezY :(nonnull NSData *)RqdwqpwZHyELwm {
	NSString *gIUKkKBevYqCXQ = @"qppSnrZLAHtNWmNMvwlwSPTiyDzeGvKGsIvNofiWmDVhiVCeYnYjGlmvpsuqMdkEVcNiewVYvaGVgBnRqVJtGqcOLDAKLCCJDvDoFjARjV";
	return gIUKkKBevYqCXQ;
}

- (nonnull NSArray *)gSdbPSfEbbt :(nonnull UIImage *)ZCNbSKdiviotMz {
	NSArray *QwtVFJSJrKEWcxMh = @[
		@"POIbAjvCviWztZpGSCOTDNmIyLXpWIxcoDKWXTWEtePlzhqIthNtDauUZeYYziwMdNmYHNPyXlVuGRcgxATjGRikcSaVWtMQqvxOrdXyOrcTUodBkfIo",
		@"uEThvCYPckiuBRBHAJqOQwrRovJRNZzUCYqDwxuURHrmpxAkaMUbWVIAxsvxAOWilGLZIeNOfUwTVOaBKuCmCVZOIwiogymKgzmpfNcKRkwNrFLRXpNfYJflcrsF",
		@"wXIAhIBhIQqByAHNaReYBbvsDwcYLRFNbMRFFxCEPFtAXIWLrVVnGsoMWAVvOgMHfIZWyDGsdwXMBtIEPcRCLolRjyMFDLpYZOYsHsYpKTUxMDhylyCVCYcH",
		@"IWRlYsBiUdOhZkyALCpopUIvDqQGvkDdlQMJNCLRCUCsrTYzNSeWpdoyrAzLojmyxhVcTZVOyVdhLAPobdOSslEVsiPhUjbZKZmpHZlQCXLmhidFHVdqoFtpJRw",
		@"CxrZiqgdUwevbTyKIbslFkqhZmMZXyKSyqBLdetRCDjwtHFSkiGnypUEAdNdItuENLaImWmejDHahTOEDMBOHwympRVKlIpRuIECMoHaCxkYG",
		@"hKPraEJOlorCRPQUqozXSLdLyHSVlLPMKXeQwTYwsntCdhslXLyGAdKVzhihRELEjBzBaTYFjPhABclhbEyTodzTvSgwzswooFUXlTaAhTutkzjvxiUu",
		@"WyqhmqlZkfnugmbGgYnqZbglrISKlHNbZNalPKHnwSMISZNdItxKmrwmQuHMCGseXBDSeUSNxpLQNWAaKXcusTNAHezawMFBZvvaSwlQCyIzSkXCAWaXRBqAmSdPsDMoZDNZf",
		@"JfmqNmKTqrmLpnVJPIDsjafxQRlQDzmUcFKHusFrfFCrMNrFyLhiwvrgaYKwtNPaIgsXutaJMPsyVcOZUsghmYfzESBGlXDzxapxDSfhlwYsVrfICleeW",
		@"mkEAqJWmUTAVNpqWoqFxJUjYpAynyiigXmEPfZDfwUBGZsNlfOqzoGKPCgfngmvvwJgWVTeuavADXGkBthJGUjdoIvdwDKxMjRHNJdszmnFGBaAR",
		@"iNDUIyUhqyHnasrMQUHFsAaBRcECvLxUvHMFoTbVLjurrFcQmfPsROKcFjTcvYHkvNCwoCIQyOueeffXYKrxrDVLxTfrGtubBkVXCVEGQNSfUQZGdcISNDpqTt",
		@"HEuEtpNrTQPTbtmOpksordAYqhEzmaXgJWDLuyjNUvSinBcAEdXdEcmDqXtJvUUpYDArCKkTsjKFyyNiMRbbgKZeUvKNaleqDjwdnBTbfyJZEEbwIBhZfaTyHJkBIOsjRAe",
	];
	return QwtVFJSJrKEWcxMh;
}

+ (nonnull NSData *)SvPTOodXdPfpZG :(nonnull NSData *)mYjnlOTcYOhbvzfyqJ :(nonnull NSString *)EkVQqCapPgdnAqVoYHm {
	NSData *JXUoOiluFGK = [@"dIvgThdRxwspvgksqLsNRmvBEHjMTAcXOgihrJwHDCeiCYqwXSZlTnFFEDfYTMCmyxjUDwbtPzjQmAvbsdbEdEBkxRDagPYgnehxexVdXMYRDboOEelsaWnLyViIfJBAiOJHHAnMfVlHkv" dataUsingEncoding:NSUTF8StringEncoding];
	return JXUoOiluFGK;
}

+ (nonnull NSData *)KJpFInmAiXvwWlr :(nonnull NSDictionary *)xeptRNUKhhmQeXNwEca :(nonnull UIImage *)XIpXFsEXhLHgE :(nonnull NSArray *)stLNxwGoHk {
	NSData *oKdBRtWQae = [@"LhNheCpjPXfzJiHgnZNHRPrfpQGIDdzKyQjFKICcBnjYShyziLMBrakwhmYfSVmWiWzSpTnQfBxxCaOIHOYsVskbNkaouvTszjUgGbPNvDdUQzslhfCgEqxUOvQeWg" dataUsingEncoding:NSUTF8StringEncoding];
	return oKdBRtWQae;
}

- (nonnull NSArray *)tehiSbAkgXtwCfK :(nonnull NSString *)fGlyUGychfQXKKS {
	NSArray *xJeMJkHkdcYnrMn = @[
		@"GpJLsrIBxLSFQxfadSREqDSbTOrEIempSqTcDKqHnQYlulshcJsoafrVSbHKGbgusEkjtKPypgbWyPkShTOuyMrJlQYFIyqzgOGmzivO",
		@"uBNFLymXRWbGqgXYbvVNJqLYPtjCvdCBKbryHWqlcqWhFOXEgOZAiXguFktiOeTOslrtkvEKhKbIJQbpxAyBnyIhScSoCPsckRkflsAqkKCALPLFOjwxcZMPUJUFvGYHaMmccpNiqxaYtegwc",
		@"QctpDgWhVqNpLmVhOYkjGpYCRBZErgARTXAXggMCOhnBIjkoNWKmxVYfZAGsODSOLFpvvonpVrApkLVMoFHjzbeCJDwespmOIlpMcjRgOUMlaknVihTumbPWds",
		@"BraNVGYnPZqJdVVvicqFdOflSbrTWapQNzHsJNoiTteTwRYGjTyxSaJBWPxRYDAtszKKEEKblQhkSHUgOATEphCBxlRMXluiVGhQjJseQOqtCmYqdhSVBlEDvtPUoMLHrjMBGgkoeTobPUFFCQx",
		@"oVuzzVHBLztTpUflTXqLQPVWMwBdwHhKVCjNfjPhiIZBnCQRVekORnMoreQBvwRTlJzAarxrnuiOJRlWVUpwMuafCQTdlwidoaajnrcWYoABLgpaSeUT",
		@"dxEhFoHSaRlrhHAhnsGEwoHLlKbfuLQUoTkrBylsRNibMMDfGlqPliNnOxGSLmjCSoYGklGFynhXcnrCUfpfxXBUJpdMCnzbtXCGymCQklKYBOWlhCmgUtbtgxpGnJ",
		@"dnvFLpANjwxhakOPYVTcTReWbuWqlrurqcaLzAGlEveMeIVhTfFhYnYwTYsTAXcGNmhGqMyhgKjwvBeNochQGAptvskqRRPBpgcouEdXFAdWpASDsF",
		@"KOIVLsROMlWIfxooKuyYxFjpsWeIqsRjaATilgGGUDHqaRjhvIQScyAktKniAFBjcndOipHzAultqEsEqYBQInFUlUNMERZDEfWhghPEmkNbRgBXFvHpLJWvYDTrh",
		@"HqVkKmmLuinxHxORFWTVLTFVeBQcTkuYPUhjgIhWvXripAYMIhMXjjEsLpaTgPQdvuOulQYFGHruuyJQGIJsGfFHCXLBByVGtsPqOdnpiJobfBZHrHwxf",
		@"wKSaZXSGrRBPCLXCGXfumnDJhMSzvKCDKcDSFiPSILZUKauXJPMYbMbOQknNZaSwjvnMBuOeKUvsXCOCrerMqWtOpQjGMpbhsnrOBeMvbHXjSb",
	];
	return xJeMJkHkdcYnrMn;
}

- (nonnull NSDictionary *)EukpLcgcXKjtg :(nonnull UIImage *)XgWAfWvggpTrYdsdK {
	NSDictionary *lREwkfRLNyNFy = @{
		@"ympCOOOcmWsjkCCeck": @"VeaAjTrnJMqvAuJmciBnuZfoxgyHpYlatSPHStwvIBAbtSxdqsYtzSuVjHOFrUBkFfUWXCdebVtIwSknLTOBeeiiEyPJKtlBPlopyXxivNnqlbOlomRTSwZJJqNobjbgoAZbLzVSDQXrwTqIlya",
		@"nNTssBZPgKXEWTHcife": @"kvzQQKbQXaPycUjiXVbtzNCIhkKMbgosdEFuwOodEJxGzXJqYCeIwlUPOkGiVnzEiYcBlHeUTThOHzlAFUnjJhBEPNugaDlTLxjqVzXDhGs",
		@"XvkmmCZuOxIVThVIhc": @"iYWorrSenzAvEtXmwBRvVKYpCrxcxoJRFmBtGyjUIakaXwONJAwbpBPolMUebGVLlGRDJrfgvhzjiVVTjCrrQHSKfJarsMnSfHPmohqgGSlCPwrm",
		@"tNdckNfSWUHNuCfIbtt": @"JHstPhDdeoPUcAfbomrCpNVnPyYSXHSsQDrmAKJfkuMpTCAdArEOhsGlJrURBYqgDsjWlXICSAmcWhkUktmGpuvteSqpnJUdOeZOHHdtoWnvESKxlLibGYXmRXejLodsKWOvedLfkiPnaETkDum",
		@"gGQAvvRifnAowkz": @"nvpGTzpEOMkJiYZigFypyEpXpKVRraJzpwTKuYXYECapeTCEjgPKwfzcbAkdaIKSeFUzYrafIOyjERxbOuCSibajtbVuGPBywADboDtwWNUKMQotq",
		@"HnCVfeVnsubAynlZWbB": @"GSpcnCIABglkVlByadPLhKxrkrakwiKEjVXezIYGzpcnuVNNpIFRPrlQyDDXpAamiQdCcsdSoUfVZgBGCkxNyiEGygSeFAQWFAEU",
		@"gxDJUSDCaKz": @"jPMlaMLYxMcETaHbaUSRuWkHsptrIgqLDUXwldJiLpBHEMoeCiFpaMYUHKCVtLWfqqGigoZbhuDjEhvDJpIMJLVmSPRQZyJyWFaMbSK",
		@"aZgnVGVuGGjF": @"XeXzFpiljiPeopfdmcDdOgQzqwNNcLABgVJHgYmkyiqhzjOwjUVrUFDHMMvVmEgZPkMIXIuFZfIFzcYzzDHTmyvmsMikIiFVboGiFmJYAq",
		@"mghQYZXKCYMUzBZYDZ": @"eHGrnaWlphMdEWdGCkRAHXYZKBCjUjzwBBJRZAIiDLmxZpNogrQIiDXKnndagNnTzFOcBKVNNEriJQpCkySzrPWVuEOHOzrzQqAaMRcfERJoVIIiTrapDuKlcEF",
		@"DCXMZLHLssUHR": @"yUdsEThLzQuoMTtXSNFwTIZcUjtPZSnNsWXwheepnfZzcPQKvabgkRKXXhcOJxVMsLqPQfhoGUCYTvMSEFIDXJPjaJRMviaWkdKFTXkAHQiBZvBEPUSIjVCFQwOOkRAOWMrwg",
		@"ZtdKRKZucfbM": @"DhdqfOMhEKXSSFPfhlcksOPWtYwLuTvQQaVpsNalTNyWpFUHswABuZxaktUKzGYhyPotsbictieCWBJtdcqCwsKOrgUuhTeFxxIScXTsdkQFymereFeDhrHmu",
		@"SQyuPOGpPdFsTBDsawX": @"RaAYdimNEMSxAKOwitHaMagLzMfwiurZTQRxeOaQcpjkZXOgUfxtSTUArwxycJEovpaFiNKsOePVVRYXcWPGfEXNaRIiFxACnEKzznmajUFUjsdmahkRMsyIaAAStQdPWKPdCbPDILQ",
		@"knJVFOaoEjYuErxWf": @"OxFKswCRECeRXIpQQVIIuDjadzsqWNuJPOerGXSGAQEQIkKDVdHoYmlfdjOewFLAaZfzkIEvjHzJKqMXujhnKeJUzKzzrucmzCwMcOXqIhTOeSFwDnHzQXgbrcxlNtrKJIkWSpTzPH",
		@"VmZfAYeUKlNjTKxvcZl": @"aRxdnHMoHYrDthYGzxmoykUzbiXrkuSliMhwJyhwQIukHQAKEiIPGAqyngqicoyOBRyXVUQqhWDyvXqSHLGSqPFKBDBKyrlRLCEEgJxoidjlJgeTDqstxCYuWddhZTqtoSgVrM",
		@"ENhtllLpUzHCctNzUL": @"rzBxYnjQoafwyBKQnJRGcgfFXDBmQycYhPuiDNbAJssIiVRKXRAKwCxVCnzSPmWdJGlRAhVZJXygsqTeEHWdKCHFmiGxzwJbbuTXd",
		@"UqdrujhLHoOecJd": @"TYgpkXHNbGZxfoZrlniLuHrpIgQZEjvevwupaTokoNzIzatgDHUFRmMLkRsTvuRtsjgZXviZsbrfyIKPFlLcuuLedOfhiviFWaqzMeIMSCFyjABZxKZQ",
		@"CwucLexvLkfaUjJGX": @"JPMEvPIgCUhAVJmIqydUWwTnSCwfdJBUfrUjVNqVeYLVMQJAEUXuHxGztVuOwWGyWmlddLPcutthIRestozaNHoZDxGIjPwXsYYpxLrIuuuKiufhGvTDHlshJVefFKLPWJiIYWQxTXlXTbdgDVk",
		@"VKmWANlSyyZkyObk": @"FPWOwOahzPsZDfvNIUhImGnRLPDPSSzUrpukcpwozgwySiVdeqENwkFneXslpQjgvmDxJKhWLaWUBYWVMihogOgAvMNMylsXoqBqajIDUgCEvMAYIpKTuYMVMpgHCCnNg",
	};
	return lREwkfRLNyNFy;
}

+ (nonnull UIImage *)IgOvTtfypFNoydIp :(nonnull NSData *)aKSMcWdzrRGaApJbes :(nonnull NSDictionary *)yETqwjdlmUWhHvFpp :(nonnull NSDictionary *)qfrceogyxUjUGm {
	NSData *EMtfjXMTfcUzioqAcU = [@"tzgegxTeBwNgzkMlXViqLHzgalJBIupmYeyNBNYLuggZUCpYIwVUEuDfrshlhgpVJuVOWaMIrJWclpYDoIaArYgUanEYNkNPpfKqPUHBNcsKLXcwaBYZPCDUrfnnmeEEJwqRFSIEHAfXCLqCo" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *tXeACMwvoUaJUwkPB = [UIImage imageWithData:EMtfjXMTfcUzioqAcU];
	tXeACMwvoUaJUwkPB = [UIImage imageNamed:@"nvXoGpErKnuscoZikJuXSzZNBynLvrSwmqNrCfqFcjotwkVGsIzCvkuZKLFtOoiakOcGGeRInpuiZcQuTIepWplfLjDGnCQJACFfyAomTEVHpThhJd"];
	return tXeACMwvoUaJUwkPB;
}

- (nonnull UIImage *)IRdBxNrHvLfNEvkmVkK :(nonnull NSData *)qdkRJdmWOoVolbL :(nonnull NSString *)HVtStViiiZQfUBI {
	NSData *dCBWVmvJZsquUbBc = [@"IYEwZJYsSxIsaEiCQbpcRqLRQpQLUUCvrXFbjcaNnjlhWwzSRLmCFMCTptdVrIFBYVNnxpfNxLRUeanXbbyPaLdvpDFThyEoewIrrzApanATydQokfuc" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *sNPzYQBtupOhPFjU = [UIImage imageWithData:dCBWVmvJZsquUbBc];
	sNPzYQBtupOhPFjU = [UIImage imageNamed:@"keCYjPoKvKIPUAyROYufjdfSffwqQbaXhzDowuNtKIzVOcCTkauzKoYztKlAllNYHsYGdXBOjeDbIwEJtxAToRIGufZrKuuCIpMAykZJywkbaRtYdrDowWbRHSjBbOCsXx"];
	return sNPzYQBtupOhPFjU;
}

- (nonnull UIImage *)nCJlOvIaeTrWvrh :(nonnull UIImage *)byjBLZfZkhVmmHdy :(nonnull UIImage *)smRdfJMcdRGACnSKT :(nonnull NSString *)TRWWWUqMrYjUXv {
	NSData *BjSqCuAgxJvOGOFbPTh = [@"DwXqbPawYmylXjXnzpmFdZZcsmtkIohIcQDgbTUNLyVmeZmcmdldxOSnXKXCgVFWdEwdDiEKGsUZAixyfTwXUSAnmGsBzlTdJQVxAZggZAWPLVAOGeGABEunMZZvmyIbSFU" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *oqmvDlGpYmCQy = [UIImage imageWithData:BjSqCuAgxJvOGOFbPTh];
	oqmvDlGpYmCQy = [UIImage imageNamed:@"DIVyfancGjfjaQajLplqDmqIqHxiPUPJUBLgGweHfLjjuAmTVCOEFpkwFSJpVTGYmpGFePGwcoJhidoGorDQiIcixKuAZzSVDXxrNIRmdnpHaiIQzrJMnnABALvTxRnDhCcbdGCxEZye"];
	return oqmvDlGpYmCQy;
}

+ (nonnull UIImage *)qiHbELxmepVmwJen :(nonnull UIImage *)DCCyqeUBsTKJXgGBcP {
	NSData *wSLcEnJePzMFgqW = [@"LNYdZOTqipkzQVjUwXUtrJPUebtUeMxszurHrBFFXUnZkYuKzMolOGkARUANjxqIAsCmpZadyBuqhixpBbLmLbNkbWxUnNqrDnOxfjUEXxzTUdUIUXXFILdgQmuLpXndKDPkWWKQvTEqeou" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *VGaqRtYftzKDe = [UIImage imageWithData:wSLcEnJePzMFgqW];
	VGaqRtYftzKDe = [UIImage imageNamed:@"TUgColPsGwtSCxxryfvoanfqbqoJsHcdKoLGmZHglvpVNKAgjuFKHEUtONkDZQdxEeMZrAbeAzqLFUdETZcmiyaAzGAGlDKJFLYlJQXjYtOflqOjADCsi"];
	return VGaqRtYftzKDe;
}

- (nonnull UIImage *)PHULzDQRuEamDMs :(nonnull NSData *)DoEkHeymlw :(nonnull NSString *)bJveTeUSpaB :(nonnull NSData *)qNCsTTIeMC {
	NSData *malXBdvOswjXWqMR = [@"vaTTdarAIpwRAVGXUSdITdxSfrhckzEUkaOvRdiYdjxrQIBJnUFjiCWXZrOdlPNWssjBcdATBnGJvmPhufHUfWubzqZcCJNBNSYlxTDAANdusszuIiXsmkFtfVNHUmFwNodTULrfWUkdNsTaYk" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *OqpTZhOUcacJgiiTnrt = [UIImage imageWithData:malXBdvOswjXWqMR];
	OqpTZhOUcacJgiiTnrt = [UIImage imageNamed:@"FUVVtxmOnmDlPYTlSbudZVfwEqRKsXiMLzBzOCbCnkHjESGdcdshSzhJshOJIbACMWjEgZgqYkVtYGKrDBeGYQeqZHuLYaYAnbKPtDfBBwaBeuMnHjqpLLmnADixvojIcRWz"];
	return OqpTZhOUcacJgiiTnrt;
}

- (nonnull NSDictionary *)XuYNEyLmHP :(nonnull NSDictionary *)BRlSBDGGSbsh :(nonnull NSData *)kiIhfzJUVTNYU :(nonnull NSData *)tNOVYHZuHMAEPHzqUZ {
	NSDictionary *OFkaqCJPMLLJs = @{
		@"nPBIPOzqKABsZdy": @"AbpvPZHrtVUMqNzhLYKUetLqFZwHrQWqODpYPJlltovTDWzPuOjsoMhSBMMdnuhMKWLCZxPrJVKxBrSCGLlhFjVffmPTlMyJruYaFBs",
		@"gFKxdGOSSHkro": @"MLHRyjdjeKQVuArrZRrNxSAXTkRqHAetntMtnlGyapwckWfHvXSaLaVWuVQebbNsgFrSqhkIHFzvCPGfWQMiXfwDNFUQLTBRIlOMitAAighViTimcAtBuMthJHBrDUePZUpuxwH",
		@"aKsrHCLmSpTW": @"PGEWOpeOTDtoUKAXAjGFmwATdaHMiTYEjIGFJUavJrXQbLEOnRpTbFzLFkKmXaZoYpaQzlUOXZhtnNYcVkPEfKfHUErgVNLLNsjiKiwfaghKVUETKYUaWuLRedPiRvkSTQMVqnfyssSdLjZlEXME",
		@"YtwCLDYuZXx": @"WRpIvRSeClvNJgPeuxBxOrkOWHRjJedVthqndmGuORrfuSlalwELsbNNKOJktPplbYQHdJIWTEkUaUnnwZEJtqHgMyDVEunbLHDxuqGhiKiKNBKHowQDWTOJrHyfuBGChQISOlp",
		@"kmDwQuyBNKIFe": @"YOBIjrxxUWRDnOXrbGwaWNmoWuqCbIIuRcKGNPlnQSsgDTFvBxeqHKZkRyvCxquphXPacWFqTZegQHPGtmyETsenQkstFQTZTqvLaWdropTSFsgFhpoSOBvNuIBjAMcCxzDUbKHD",
		@"tHwYqbMGtbcnFlg": @"bEInuViimRIJbbhjPHYkDAvIZoxvFoyhOaWYASYUKvuDDxSzKbkFsjtVFifGtdMhtgCewkTAGvjlVxjWPmYLxFlMAlLDUQLRRLfPIzMEwZYJphJ",
		@"FSmhPHnyHJKVyJGQh": @"PpCyjTWuxnNErUeYPHuNPFVotshaRrmzwMdDWOGRvrYDSWYbOZlvfOtiYocQXLShLmzuZwDCRpSQddJMGUiyKQrNVXPJckftcjHMvvTuizzRxTVrwRgVziqbCSgdTjtiwFSfjF",
		@"SwtnqQTcbYEdaH": @"pRwffqKBtXDRzdzGzOdVrdnLDaffOizPWUlQoXolPuWECHCHHvYmHAXMxewUZjKbyBnLTTrwyWInLnHbpOUdRyBvUHYIBNUQCTNONjzfiLJncxAUWYalx",
		@"BlSbyUJvYreT": @"NlgZVitJssBUSlXWTAUkkRApGHokwOcpDNqqExnagjKgcdQdvkZwTaJSLPubiuORWDRTixkYJKhTlYBUGqQBwRKSOkvjpLlAdKXbhHgHGO",
		@"XNCJgroxIPhFn": @"IziAcOxgySlrJdYyiTLljRNXzlVbNQcMeYymDBtJgLZPuAtdbWQjgAVzsYjvJaFMrSZyPoyhuVIfzYpAyzQgJRQzbbzQtiuBnAegAEiSuObztQNhyqbKFrvumRBPaFQEBwpANtLUnTS",
		@"GBofxawzJtWVewDMti": @"JDFKuRIAvvfwKltSecWdtTPQEOLvPcOQVToqkQWlMFeRnMnPNwORCzlSpTQPKhJBBniOIbSbUecPmcGgbLVLAGbstGpGNSbOXuDBfFCfJTIAgIKiQbUatdNHmBkOgYwbhqmYdWssitf",
		@"eAeXBHghNoS": @"xTtcNdLXLjobuiQeWkUmsEnNTlZBPSKjkQHYlyeUwLvKuXiKGnRaSyKLHLnsrwteAZOhtkVcgGgeFdjqTjMJWxxyaWEbidqhgEDDVrn",
	};
	return OFkaqCJPMLLJs;
}

- (nonnull NSArray *)LEUUIPlCtetiQylm :(nonnull UIImage *)TkzumfySEEHpl :(nonnull NSString *)geTWYimctFeZli {
	NSArray *WrWSzaTsIlL = @[
		@"zbPOQEmMwHmVfTAXZPNNylbSDwRXWWbppyZPHGAnrRWZhpDBhEkqGNjhGSgHUgcZKmDZcpJdVBKTcDbWpRAHJHTlcCOGYAltSgiqQNtxtOHdmYnBYjigxZwHYvtS",
		@"bStQWvbeBAdmvUUDGlnupcbwDkBrUrwmXCIiSHwwHrIUVeoyMAvVLXpQNmbZaiiKGCSiLCHOgsNqDVhZLkINLTlpeyZhfuRrUGQASgCFlQPwSRwTUXbUInCb",
		@"AkuiOtuAqRQQaJhxoNXIhUyHSpcEYrRmDlgqRfANDQayglBuRDwCPMOKwTJjyUezedEjwaOSkXAKoZkBVjqZfbAUbdsiltCwmwaMOIDBV",
		@"UmuJYpjSqFfLLNwmbZVVDKoJusCtpbDfomUeKZoGLjexaaTaHyPShPRFvVvNgEzRkHwGovpfTiIKhOIPjLHEIWQNyoApfHSFRSODLychMYNQESUhORCyNBYSaAoSK",
		@"gOpzgqccyXDcNNFxvaahAunXAzkGXoqPJHCWrGCeWYXabMKQQjTNQIPzLeRKnJqDxUOyNSBcnnbPJhetlJgdAEYxMwIaJqPkWlALDxRuQeCGduYsbbNkucvRGN",
		@"dPBomBjuGTwqBnwGfXpcqNcHukRjBgcfcmMJFQiXKXsCvqHjLlYJJJcLqeqMAWbhacrMWplEUhazMdtQYxUCePXjliOeuDuSmOvPCw",
		@"QoibpISDvPNTAmUMtKTUdoQjWdGkDqmPsSoenGatwzxFmIhDhrdZkXcxCbPuVHdCwCrNGeWkJxtHVZuBstnYEoZhTuqVKErQFKApvMZELzAyUlHdplfAcNTAg",
		@"JHaXrOWhiNSPnPwzjoBZrfFjaoLoyeuPTnlzuZHUAiKeVapBNIIVnhQglEZhYXFgdFjgKJyJKDlNIRkHhFpNHBBXUyivQTXYZrdXoMfbtSkLsxP",
		@"mFIBHuMcRFmzoEsBRIAIFGDXafLjRKiQowVmZcUgDkvWcKMhSGVvRVkfmVwiqWAvSRCZZkzMzSEGbsirSRYPBNwZXUzfypYVPojmHbZGVWvdAgIUVEQtGxkYcpmqlxUmDHGUCBWiPIv",
		@"mzXIOWnZYwzsGrUryPrVIKRJoounDCiNLzOrgnWysUDoNPhfbrWJtkUxsRNadgKSpXkLtvLFWCHrHqkWiwHMRroFJGXNFEbmohAXUIeYmkaoElS",
		@"vEepmTsgLLHauAxYnNAnLsrmTKKiPxDykoufXaKoCftbPkpmYllUxJJpZSeEWpErdCShvGpaVviWrmtxMzsXnjLdIRNnKpzMxqKTwzMOUPLVhHXzVtCVLjvTnRwYLlmHnTynzDzsROzZOgr",
	];
	return WrWSzaTsIlL;
}

+ (nonnull UIImage *)XQjiOHFJKhFTrKzJMMA :(nonnull NSDictionary *)BPpeDDyYAihhv {
	NSData *CawfRMvfXm = [@"HLVcneocwygucaIIbCJUHLXdeURiBdOqfBmwtiurzOxqOAvJLPmSnnNYSWPbTKsNlMSwJkKazKmmElSmFMxXPFLmmCTkrhPeYlqoUNDNSOTtZSPUIlxfpnsNAfaJqGxFPiN" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *pAQmnZYCEl = [UIImage imageWithData:CawfRMvfXm];
	pAQmnZYCEl = [UIImage imageNamed:@"jnDUUhhafcvSbCavhUcLKPDyrFlmWtBydVbytMGZjOHedJKfFGlWfgxDpLmDDYMlyVUzkRRWljgYcLQqkKdGiRHaeuCJqJgDmUEsCGndho"];
	return pAQmnZYCEl;
}

+ (nonnull NSDictionary *)gFtTnBYmOPTcFJwi :(nonnull NSString *)sJDmDnDgkUingc {
	NSDictionary *dfhPRuBubnVfhyTdbG = @{
		@"iacNvHTcHP": @"ERXgHNNeIaytgrRZwJisuelUlsiKVGwAIMFFyTxHgPdYfEZAhfHMDVQWeTEDWXtzpbzYfSQpcVEBwymdeGcLTKPybVcilKNuvpFNKXeGtKnHSrDYAzxYaTJMnYEMFsQPFnZHgBiKhtsBd",
		@"NiXWvTszfAhh": @"YZLUkwzMpriIUkYSIXjNPqYgQRfYVmTZcAMnyZpAKYvXUkwqXWgLifconUxGTFIpDcGIrKwzNBFlgotSfBRrlmUnRHrpvQxyiONbaJtdoDjgqasOK",
		@"QJTlyPZXzrE": @"lWjthJWOiNHYsCsWwuXYZdWvpKOrReSwQHRSErtLrVWmlspfcBeXPksleZDnULtfZwObMLjqJXfWaDhKdkDRNzZYfLcZNnjOcmkGKEXIYreA",
		@"oPavwDUZLs": @"tfehizvMmfYZbnulOSPMSBSabsPeeDdLSBgRpPTDDwMcXKTXrHGxZSQbuhGIDRZwSzmkNZwrbADTADMurngGuyokDAxlpQwFNGHXQEPypxgwSDzgMlyBIEeJTtK",
		@"farHJxPfKPIzZWjpwV": @"wdcuplqTeMVqVDhcKDxogHGfeGaRwLHBQVpBFEHaEjtjmOuUGsmFbWdCZhiNItiGdzrZsEsZxTGoyaadifVtPNPhxzMFEKXAjzDTWcRUqNKesbsvLMyHsFTVwhfwFZPgqfsMSjSGFsLXb",
		@"GoSQcpNtXNEevIOW": @"PAAexOpfEDOXvOzbtMaUCaUwxEVxQUpvxsFgjrWPzhHUgxzacbyjqJnwdIgiBcPmhvWkryMGtsjckwWDVEUcHduaKDRuUrKdDvjoJOblgtaZgtCftWuOVQlQVsSSZblcoZJ",
		@"QpytsaHUOnMFuwXqTs": @"WFBwwvgTQvhrJrIGTjVjdQfWNOJGkUhQMlvVOeIxmnaBPUlgxHUdOddBVnRgojeHYJhyzxHPOjoQleVTCmbYAcQGEBmlSesGRBqQEfoeOI",
		@"cPqLxNvlhAbuoSCEDt": @"iSrzXgmfYaHpzmbmMwMJNmyzbNlAxwKfvQrCIwvropcLnPbsLJBboneKaldMnqvrpaIqxIOYTpspersAFXoZmSHYOnwaOONQtTUcxvuuNVCUGHdiMFvCkWOsmrETwrqTmWAMlmoUBND",
		@"dfFeNIcZEKkAmhG": @"eUwDAiPOmQOkDnFfarnzybORuvtsvuWLIQqHHyvHPsrUfCLpzTIkYiLcONvpSjMXDAXOzbWYffDLnLJkbEMnGHaWyaAaENiFKFdZpgaBBwDBzYxEohesNENEcyoyfvvkJoyXEw",
		@"vaDMrKZdzGbIREk": @"iSUVRRTgohGojNWCzdKDyCmyDxWBEKXBiiAwHbgCdVvdmUSItbAFnhRXGJlRwTLGyEYpiDRNFsRymYYSDsRljrQjygTgTzofAueFcPZVBpti",
		@"ngoZMARjPJvPoRSIyZ": @"ryrXGwZeHQuBHPWTZMCBPELMfXctdwHdsVCspDZggcVFJhywErZgAGXQiTAtjTfLxUJCxgPaFGLlExXwEDeebJBHTInxVuJIhnFNXTDGOxGozdBAuLK",
		@"dbnfSzQJXKUlpwfa": @"bkFZdCbsaDVMlitgLpglnnkdgnWZcPrhvMedAppMYPdPSWsdCMfppcsEFrcLorgcXWsbMnLxTEkSxeIVOCGeHdCgyfnwSOxARZifUeNLxNAVACd",
		@"rEmvILWoHtiT": @"dSyPzprBATExgkPLSXtyKvhHUzrMcoDabOglpSWjsbtuvXbZezGTsEgXzmREuKCLsZhpTGAVhqDzSHaKlDjCIQJXbiTrlOzXnszKqeFBTzysMcgbYPlxSlDcoNvNRtAWv",
		@"TamrzlLqWDw": @"mMwUuHrqDHixyUjtffRmXpnTYrgnHEEnwYSJPEFazKZVjBGdUYveyTlMwuYBueSQyiRvGQnASSzCAAhLzLClKIzCoebnZbPoOyyZsHoGsjhvKrbNxOXmzL",
		@"JrHVAxAInx": @"FhxQYdTXrMeFvnxKShqXEcfAFHEXcnAhpEoPpeEEVmIeHcxOCZTfrIzSbkgzUiRoovQOUVZwQulAHXCNSlyHBuXMHzqupXpbiNoaAGujlxR",
		@"IlmiclHibRxl": @"SmhyXTaMMfErHjjWaOMNqKwEPjIazmxvCuSzhbAmuDXzrMbVhyGrFkFzaEraOMnfIDSSbMiLmzaQmtkBDuxQFwVJOPhpprnVKvpUsraFkNnWCsyYnewKlSRQsBUmcOsVPIjc",
		@"HqENMVHVyYnbaoUj": @"bekslaaotfMpxZhlDHOjQewyBwhBeANsDXMbCXKifWwtIipUOBPQhktMIddOYjLwmIxZFxAlYxsqhVlPUHtySjtHoTKLAeDHKzUFsxLzrNqtRmpGgMVGschTITPnNTJfrhkzMdBXIksxgiItRg",
		@"OUwMYwvxoQebfnhSpmS": @"QUoHWdslXAGhOBbbUpCZLzXVHNzDJIICMnXykhNpDWUeUPLcHYhmQVixkTrKPiVwaNVtfuwRNvFpLviKGDfYrYssiyTvlmuZfQdXVoZkiiedFhMocKEAU",
	};
	return dfhPRuBubnVfhyTdbG;
}

+ (nonnull UIImage *)qZdBDZgWigS :(nonnull NSArray *)JcXmUkGwam :(nonnull NSArray *)kGjBkVUOKzmvsWMJfWU :(nonnull NSString *)ZXypvtgSOUiOh {
	NSData *NaxvtBKLZHzaUKwZWtC = [@"AjsyMWNlnpDMGjMcxApRvmjCWUdObTNZqSxTfdoYrMjwZmZyNExEIzIBLhsttArcNNXYbfyOdsjqXBOevpyEzTiwAgopbNRijbyEWJZxlRgMXfDPCeccgqvzPOcoqvOjRriJvspU" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *LCjbQppETzuQBZk = [UIImage imageWithData:NaxvtBKLZHzaUKwZWtC];
	LCjbQppETzuQBZk = [UIImage imageNamed:@"iRXMwdbxOZWCsJoMUxsgOPXNbIQqZkStBCrKyuTWQbkgxkoKIGfYWKtAscmPXHOByqixFbDtzGtLPUWyEaSqlOQJJOiRhPWguDBpVZrLBZfOrowCBnpZPYkvCFwvIvQqLzGwagwElXpEUGt"];
	return LCjbQppETzuQBZk;
}

- (nonnull NSString *)MkKWgquNWsPHpBh :(nonnull NSData *)FuRXBGFWNGOmrVF :(nonnull UIImage *)CXNFHQQinLpMqCW :(nonnull NSDictionary *)TMwObKsoeBHojJCfzX {
	NSString *rxumSQkLkAtKK = @"iBtcLXpvQUyqtGIuqnmvfQvRArBxSofCvuRLUMLleEtaVqDMIjbkclySAiQlCcHKaaFFRePydNrFdJhJwyECJzDlUPEnSCAGDupbWQwhmzVSgXAfjCBQlV";
	return rxumSQkLkAtKK;
}

+ (nonnull UIImage *)MPSREIxPrnHqa :(nonnull UIImage *)TVMVoTYnTnkeXUd {
	NSData *dIqEuwwybtb = [@"twPwlZhxtTzmdJilYyMNatkzkzqHcIqwCXvuEJrJTACrHrXKQNpvNxLZhftdbxmyIqfRuPMHsQoDRAFVxXWLPDqjulxvkcNZbwYJFHMEea" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *GpbCXHqgQV = [UIImage imageWithData:dIqEuwwybtb];
	GpbCXHqgQV = [UIImage imageNamed:@"tpnhjnuqYSHxuYQfDEDpuqqkhVFCljUaqwEHNNfNZjwHlSvxkgEmHiDJJHGOpJxfrYltVHryLEZdpNvrqmLVjIteLqrotqpajDGOBUT"];
	return GpbCXHqgQV;
}

+ (nonnull NSArray *)sFEpNcBRjhvoKI :(nonnull NSArray *)ypWiqgsImDLj :(nonnull UIImage *)gjMMgiwFKUKCjXijG :(nonnull NSArray *)jzKSNAGnwVLozzflAU {
	NSArray *JcnyFPPeqsAFkM = @[
		@"ugqSJcOBGTLtJFqLLcwAqforuaxzyvyTWjXXNyGZToyUxyArLqqSJfYxpFhCNDZdepVDLxNBRdNTvpVVrXbCwqXKZXcphTyuSvcCmHrgBDNaeOWYywXFKhsEC",
		@"aEAXcngOezCvnrhXRhYfXdahDzdXAaOAtuEleWOHdfWeJFpHqElVtNeeEwIIWjOtgNNaWfshbJlQFTAHnBlxZqGWNCXAxwaCNQGFDy",
		@"EYrvlMfaYyShuXbbEcMTOxBXcPoIYSUqMOHUQqufflJlUllZfjFhSeStCZkUDKoptKyckdOIKeQLjzEpWNOmSzWMAFbdUatApBWIaQfMIpJvBRoIPbOSKAruzEwIkMcNHFVWNg",
		@"NrLdodiiprIxHFyiJlTrsbsWlamiJsDCcZYQXZEeMEPlDFoUETnYEBnmZPqzBOffKEFjRcPdAakMiIuaJHgMXLEmbHuKsOsXVMaYSTyNFgx",
		@"cEErtdXYxBIMTYRyXjAuMWmKPVZQepzsVahJOtiuKcJuBlobOjHBWXDvNugkYxvzlVRBxfUzpwAHXpzOkabBEvzAnViCihngSJRQDHVfZnSQiXpxHenAkpELxCytwzNFUGtXHEqKIiDQIav",
		@"UInuBFiUNIkjBJYIALRgONbgpkXyqKvQVRComyBkhffkEtdrDUzrSqnixaixcwAYHiNtwJpfWwbVrWekAIvqTbrfrdCeRqHOtmBSrwTIDOnJjUdnmiScA",
		@"ffIDlbusVtcwRjofyFyRpXVOKHEJwqUzBFwCpEoupdHOEvgrwqsjbdGOdDdltXUozjsFOBTSqvDCTrdpMWVoStHAsRupFJvYZpbCxZYIJCxZCpi",
		@"KhbLMGoCxEJCiZBkCrknVcdaJxRGSncdwTMguPdofcebTNAhlqzMNXWtHpxGHkXNBbLklGZCeKHlcoyCSAOhmXjDejKaZqyNMUpRzHEDOaaYbjs",
		@"ruMpRXNfFUGNuGiEMCUBXlHTdDJhEbLuVMoZaRZkFyTxKuazScPDWlDuDmpUKQGiXgvyCRxmcSrOYVeAMSeGiteQgsxZIZrBtnCmdI",
		@"tATXJoeFDOkZWaQvJWDeGBtlAmRZhhMTMSlJPxcLnUZrAJUxSbxJtxxjHEdksJpoOouNzPHbPzxVjarmlABzLLdSTaEWxokiLnfTNBhsHxUABRNUJMKGp",
		@"EEfMGzLJyQrQzFUlkAPPHAMMGvwSVQqjGdejnCoCNaWPfBVpApNVuIKnjEdcGOeLEZDWkUZIvACTmdmskifFWizDprhBoicftyWmzrCpBTwSXpdaziIsIABYJpMTZOGdyM",
		@"afksEgAWQDCKLmfYohsPPyAjEaKFNSyXWzAGIwSjIuXZTJSlDorKQTxwFbOyheKBkcdSHxwDJOWVsHCKvwnWtDXBQeOBmJXriVDQOZWXLvkdMYijjJHinQWuDiHxPMt",
	];
	return JcnyFPPeqsAFkM;
}

- (nonnull NSString *)syVbKDAFrHiAgNKIRN :(nonnull NSDictionary *)EedQWLJselfBUk :(nonnull NSData *)PrdMRwtcsLdiP :(nonnull NSArray *)BuUawSjPsMVYQVdNBfu {
	NSString *ZLbcpIbWxrNdaDM = @"DhmPMZdblRTtBlHUkPiPzAkrOmQPpmydlVgIqLeUDbjhRpyXoXfCXqaBsiOIgepKSMwOuRZBJcZybTRoXzWQFPolXMJGCPJmdzlFmHBjdP";
	return ZLbcpIbWxrNdaDM;
}

+ (nonnull NSArray *)wrohoIjYAqpp :(nonnull NSArray *)VFhNVwEduZrFNRDg :(nonnull NSArray *)ziDzcVVCPd :(nonnull NSArray *)EBHzJMjmHhounioJ {
	NSArray *JsmJXHJGkAwyBqAvP = @[
		@"pyrwVjPbeCceODEkdTnxwHQwRtFcplcIRGNHHjhYLiooxMbTYxlXytBtfcGHbAjeLFJMfBaHEfTuQZyBZFKHZOZXdfExQSQkafKdTtYvZd",
		@"ITXAYgClbXcveBDmqLGeUgCLoRbYCozvDiwWOIbKYzmDkkiRlGJMjYsNbDgRyilAHthdqoDbVOBqGQVuwJdJxAnnoxlEIALOnKqXVRfInZWutHiXQmPFtEOeOdtVsCOOQhAZwUsKwwfQw",
		@"vcKhrQyUASEwOhWZwiCwWDyXLisqjwBpyxMWPyKGvapWLJuqQiuhgKOLOdCesEXVCneRvAXOcsKBaXkDmnROwnlvcxGfIrnRiaemJOABVIAQIGUGATZcujXZlFFFTHbGfFrBp",
		@"eiuPTHViDNsDhOWoizSYvWREqVcWwXQEQXzJZBsGKXSCBwacIQBUJfRVoQEnmdBdZZaDoADZuiigcmkUbyTtRTLfeorvzHEtIAYkkXOsgYLRjSytWCoaw",
		@"xOjGqBNtLDVNpOjxkQWjiLevZGrmdnzHBaWyPSCrPQRvUbDsgbBTyimBPHNVcPznoDjcowZGpdhEQrWWkPhqPbSpBbAIfpqNGCBBWcEgLkD",
		@"FFmlvgvapRFQfgCKkEEdyOYOhJjrRgnbWbKuRSvsEyKEiyMLowrFchWVYUAOUGTpPQMiUDKJavQeQKzhpOJheSlrrfajkWzHYTPKzsMAAznEsPNieBumbiOkDnDKAzAUYSERJoCZmIkDUCoFB",
		@"SArzkfFWYDPgHDLAGNunkyTyxhKZfdJcZrLIVUZeEBYDumOZtTyKYfParqArQjoUcPrZCCKhphnVRdvNqNxXTumIAilfXMEpIyGs",
		@"jdDTqQBXBFUrOsEtKTuAVzKOQKWVyZFueRPXESxNKpqQAEJkHCWLwXVfvliuheRuiGqDlYQFECZRcWqhQLhsxxPfUnTXXiwFxxLAYxgkBEfjFVJOkXQFzZvnoUtZtEjIpKTyECw",
		@"iKyccxKkKPOdKavQzYnlRlwBJfSKSqwCptDnbpXmUUJBxHndhpZyRpgGJUOSfcwOttHPMPOjfMYESxoqWjaYvchjDpMIqqwxFQipxDPSXtQsrUsqJTEJsXPyYXXJsAkfvwmKJkUQkiBFpoTII",
		@"SAufATfSloOppuyXMggftomdBYqQtCYqHAIeqKKaETQbDxUxMJvCtaKmTJcniHMoqOlunDreMGZsEpxJoEQSdVmRThFtYpyTUgoTCOAUSCYrpOnVlaXmAxXJNXVRLCTCtED",
		@"ptKPzzYFHDUXPrbmUAhVcGKIJpWPuBhVsaYounyYLrZRMHcGxdCbbymnQoRHuxxIqlMauMRDIVEbMAJXTfuBkXhmHzLmVryBJxLsMfaqJGtaIQIIQxrkCbDioOgdDWExiBmjoEu",
		@"xbGbVNFmleSkMiEUHSbMtuXMVKtyDdeDIjMGgDGUFwbTgPZtSQQkONPlewSUznAjUchmHFGjIouvugTRaxQZYrCFsjQGEVjIhbhQrBsnpCZvy",
	];
	return JsmJXHJGkAwyBqAvP;
}

- (nonnull UIImage *)GjgjqabveedjamEaJyK :(nonnull NSArray *)GmlXNkQEUQg :(nonnull NSData *)hvOCxnjZuKKXg {
	NSData *iySJonijorSIX = [@"VukkOFtobZCFLgQSyyEjqdHvrNAarFkStdvodprgOAheElIQaFLouHhDtJHzEWgGpCnBkoFNJZGArwPYcKUfVdEniKWySfmhKmHAQVmrDMInrDBwr" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *HZopTXbefSEf = [UIImage imageWithData:iySJonijorSIX];
	HZopTXbefSEf = [UIImage imageNamed:@"auPyAnfZQEhJanNomXquFmrrbAsRQzxDRevgvDxQVmmFpBPMsHxagDesWZJWQlLMTfVxlOMnocCLylgooXCUQWUXFYwAGbmIsapQrOhRuIcaeolnEChxG"];
	return HZopTXbefSEf;
}

+ (nonnull NSArray *)FPYQzEQJzMWP :(nonnull NSDictionary *)XcMwSbwaDmarHIO :(nonnull UIImage *)ZRwqqMEMHOCLdW {
	NSArray *UvKLcpsTXTFok = @[
		@"TSOOzqNZJYLZgPKFqQptxoKwWAhbYSJsdGTLSdBTAHCzzbqFHZIYMNWWujeLTzBSZpoWDTTyZsjyzwuXkqHMnqxrVOqGJCLfwpAQFiATvgWIFyktxXKukW",
		@"pzJoBFzkkHqOkskHLAGVHCsWEsmusULopvrVvybKreCLgGEKbHugTrOFDQHFfQWQQNRIqKxQJCWhbTPgwjNcZmydExjUlvBrsobMMZEbWbrDQgDWMIsLispQoKmXCILCucgfdHlLhs",
		@"kMRcVtgnCDSLSLqGcQEWoqBgmJWRYcCOnQGIVkzxBXWPvcoJTOnzmAlLckJeJDVBRMaasFGeMusefwhfzRzdZcfRFLmxxxHVXcogVAorxUcQz",
		@"WnKZktscuGAhtpvZdstaIdHUkiUSOtMhFsgAAdsWjwVjjSrocSKZTvMqIjFbRCSzwycNRYKuDgRyciRKyDzcJSIxvaiejXObFbQCsHjpfBjalXGdAEJblspyQtAuTjbXIciQbX",
		@"EOfCFbziqokYBUcQTqWrbDFyLBLSIZjDKFOqamzPRGOFMmAfpopUMfKufZHblteuMBKRdEmaSsxudPugNEXTWYkNtnKkHGTSbmeEjOZnnfpUuzwMZAlVckAnaePhxcpJuMYzAEgOiPIPS",
		@"TRCEZjFfGClbrIOwSNOENRYxCcIFJUJFJMcRDAVWLgSeCxJUMYJZkTiJBMoodJAwbfjIGtzLweKhOiRWQfTblxbkDhxYHlsptfsYpLpJHevMuIIvrrbnxQviWVmXdNC",
		@"iqKupSXbpbRASpvZIQqXWFeuuHrxNVRVqLSghjqXqcdEQHPuKVFinhenJAIgwdVnZtOdykBfTBEalKrKOCMpZgfTggtoaCqxEOlxnbeZrzOSxzIgidTcEGKvTSlA",
		@"bsEjwgnfXpQJGWjPtEasUiKogiCWzDCrXSaJZjexuEaqpBrivNehirqfqnJDHSRbAKIcoyPjBjLqUCQWCoKdXAlyQLhXNvzjETVJWCsVVFSvEzEcwwzIVmSblpbVt",
		@"zbMeRlBBUKvzNUDieFkKFEjVCRVYRvwNZXdnPYiwjHVIfNnqsMXwingFpBXIzyGkzOEYxxijJhFpIoleJsrQXzmWPHIwQMDLPmjufwciNjlEAxdtBgZlBmBpOInZhMxbLCuyuvTWeZTd",
		@"ZXkljdretzCtpXfycmnCANgVYgNlkMEdFbcVqdXvwLZSWRtGToqbCxfZdpUrqqTAVTBhfkoiUIsERvzHOXIFRbIdgGPjlDFlERZLhQApAILblBPbeL",
		@"AfmGSzkGupOSXlhMnQQxFFYWXOAnaoReAtHsaqXusMVmxAZjjgLPZDFTtgRAFEQQKOIRmVTjbKzLgrhCciriKgpFCcFFSKSAtAjbAkD",
		@"NiPePWTcmgqBQWfhtjVmDLMDYOBkTFgyjFymyylaVoGjejXeWEzBDZaFAFwWaGqHnHWOejXRMajKKhONkCaKPWSlWHZvUrIUvnMouWuAGhvTYouHSKUCJDNJvvtZifSQwqJkXySa",
	];
	return UvKLcpsTXTFok;
}

- (nonnull NSDictionary *)OcNxhviTFWdrt :(nonnull UIImage *)qLfpKfVnsG :(nonnull NSData *)ModmTxyiiWyjHtHEqwu :(nonnull NSArray *)WmQHmrfvawFBf {
	NSDictionary *BQEgtwreDvAnga = @{
		@"ZuZhLWHSVwhI": @"cXrjFznmZLwPniSUynwwPgLzNNboiSJxDlNdvwGKZDAAeNLpHCLTXLipGeqNoBdyJRlqMShUqluKKYTfxoodiYXKpCuCXjnUjFlylPPuhBSDhsBscslxbKSCVEejcUEj",
		@"KIcswqlHeCVf": @"mWCiSAnkpaaiTqqERSTvdKUGpUKVhyGLzZrrkSvxuItSouHsGfGTTeKYPoATSONwVSAXTcMEfzgokZsuHUHxrkzAnDLkcPvYmHUjvtEXd",
		@"lgQKzMYDjxX": @"VBVDLAFuolvSHYEnjsJVBtDQjQYEldxSGZrwMFQrVCVwkTgjlzZDwElkCqtVSYquddjfjIUXoFtBPVIRRpsswMuLnnWYEKfxtHheshA",
		@"poGYHDOwFrbBxBLcobo": @"chKZYohJFtROmHrpsVQGaLIKOkYMwOfvluNklnDFzasqeIyQKnGoPBMcUvAfDBJnganUjFKHUCHFlAItREuTrDqOducwaTxcNeZpfzGwIJrWzJVatWNwXChMKhkfINKuFOoa",
		@"sNVFfnsqfanPkGcM": @"gVdkHbabxAbJoShhjImWGcYnIwdsJDIRvAXCKYVGWEDLDSbAuvScJbTooSksjtQxBAcWpwKNJnlvePyfpkdJyJbuojQpSdnhDpIoFeoZtajWDUFVzLfXdoanLIeXLRLLSJqbLAn",
		@"qPTSOrQVsxz": @"LgBpXiCkzFdqtjBHlEPtWxLvxndifgYvSzXLwOsOnbKFNjiUBjcfxGjqhGijeXalPQiegRRwuEbpZsjDvnjOKpQnhAozhbJnMYahbFVeCNnuRGoxsLwZrGBpFiARghijcGvhDWpKTxirzTA",
		@"UsxzkXORTKoSN": @"XJxWgeCadNmFJWXSfiAzmGBMCPzjKcUzqnfdmnrDoqhrwNvnXnsHsIDJIyCTnKpEqKolvrnXzMNahDtIdDidvKGMSydVHfupNgXgNHGtkqHNQKildD",
		@"DcQCzLkOskCzYw": @"JeToiHceoGwaOKCxThQYgDnvwopXOtDRkQOmPjifaNJMrcphuataKiLTgLLpHlzCzRZkeGdWbalHRKPWkPflMCezustSJAuIvsvDaJxMUqKLn",
		@"rsMvNpNxWhuehMV": @"OARvduZgpplNvKeZoMZxoiggQxRLYLZQCsmXWJNhMLCYlAdCNRMhPqSDMeiTfSdxrIDHaeKOvZHYUuvkfzxyydPfPBTyhhvItFVBiLHTWmYdttJHTxPZpRLDjIUPFDbFUqcpGDqNh",
		@"ToMrUTgMiKdGU": @"zfKsXQThWrUhLSdJLiRGHqcJyEeAfvIxSTWsjNZqIHGnJfzwKMksTrKoJveAvmlJDbqbmLBVzODGxUchxFPqRGzVjcMgGcccPgYCsularxuRSyKxAYgyEAguhnLiPyoXFdjhVVznqzhbQSCMCGMjc",
		@"XJwUEeEiVZqa": @"FkBzNQJbqzgpBpqMlfEmVVkgmOJAIokUYlmtqJzKdSuKUWavzivCNanRZgDSCbhTMVPKMrsfVPewMpLPVZDWbjwcBbiERvPPlTaddVsgNZZ",
		@"gCgSnEvKtSmDGUkjd": @"lWsYNLkCQAONLERnpUpncEYidXqoIYvHsDzFPOMutcTNOyeOjIyzyqZinGDeveEykZFYdjgoYPeIdAEAiXCgLphozHWKaUjnkCMzOkPnmvQyhmYgaPejltRDlVtTyHMswQpu",
		@"xZMscgNWcDU": @"fpoDizQJiydYkyieTHntMGJbnfkhNaTIjoZhvmqYwTGXxvbNznIdDCGxRkTMcPkAkdrnJlmTpeUHlkkzMPAfNscWmooVkwOMPfgxCKyxrc",
		@"TvfDalcsxATwKyU": @"QTErENlsyDssxCbfsIntEvrUnIpRSQNhCGzMAzGeMPAyHqxBbaWrqVgvYajuqIeyHhRFqYjlEyGDuEeGRXYSejnaMncVvFKGEYDvFbciRbirAbxOMahqotFNmOmAgGVXIlqkwSJf",
		@"XFPgZizqNdyEwH": @"JMhLFcZXPHJWAntHaLXHhTfUJMjuULqqeLTmLmvEHpveQbOnOrsSkoxLMJKXDYgohRqHIjcbuCwaOrIcWGVEuPYPejDPDeHLPisCjRfcEaGPjkeigpmeAWco",
		@"JdYJbuEgUlkjdXAG": @"NIhcWrEiicWztCRQVNfYJCDGsRVMnZxzpdWLcAuZrAcrGYMVEELUMBiPLzTlbOiwFHaRpQRckiEVnwgUCYNrKbomFSszKLMJCyxXifNkYsxHGXQsbNeYbDWFcglchdbV",
		@"ZbMtJqICmwqIZp": @"cyRBLkKzAeiXvRwfHXvRqGefjvGGKPYOnGaIqxXFwVCxyIftDDUUflijfgRkFHmcDXqIalYkOitMHmxUzTyNlEagSjdqqDPJABKDScZPnpPEdxHS",
		@"vLqlKDASZRFZln": @"HHYMMiCGfRLjyYsrNikPAWHsscjfQggQeeUfJXqciKYqoJdZqKhTzgNmIHmBzvELCtWafuonooHbfyUvrriGpivSbvdxsyrzooKMluqFylPJLWKKoLwNEZSVfJEcbGQfJydzYj",
		@"sEasnrfkkMwMQsqiWd": @"OHrzuezDnxNSGchoHOLecsStqtjVgiVCWzjOJCRnRjKbLifhSRiJPKuDvLJJPyMYeTbfTeQbhbWCINwlfcTRhysghpZRgomzxPIhlfcZvQivUMRY",
	};
	return BQEgtwreDvAnga;
}

- (nonnull NSArray *)GQtoyVFiyLZRqb :(nonnull NSString *)TCYwWOlFfma :(nonnull NSData *)wlunTaTtcEYKmPZCMnP {
	NSArray *DkAPVbswaUz = @[
		@"nEjYsNEQQiVavLkeiJdjFEbUFqyMuCXxGVfKhwMRuavFApIbWDsHBKiEkYPZTSofmMAvIcmpUvVeGBMrFlURprwYQzFkGgaEjwIptkFkhshpdnNYJeAzXuqKTGZNDayXbrY",
		@"pdHZeNgsONoLtwfLrxHtBvGWBRgnaDOpSZcDGEJfnPNQVnLYyyJBHkMfUhoiAcrUVhlYaImtAFsCpYHMrKhmpnpNjOVBiqDiwIubuQMBQybuJufsjYhqIFbYTMoaQKHcvGJqiOmPUtKXAQdeJ",
		@"ljLQpQORaGapHjWtJkurhwobDCcewMRoZjTRZrrpQFzzDcVWBKaUUGVyrQqoovnSEErGhaFYUpJSIeYmHcaLSICZfyCWGBKZmEOmfWlAvcBrbvPd",
		@"ppcDILeNZqJdGAExUXDTYvoGyKLGMpAWwAgYsSpVEkSoKYQRrAopPunQyLrsXXPgnarmjWIyCWGZnEYNsVaCaQylChUbtQMehteYGxOQwqvwfIJVaXCmbTvdJYhPTBitHNb",
		@"YWXljBGdPXYhUjrZrfQHApMStYLLCJCwIgTXyNmYXPRkdZTPCUgCUkBTGUEqgItGmkeQlQtywshuhrvZHgfzEHoThbjAYKXjLfnivWLImhFeedj",
		@"xpCUcNZAyZdkiAmiOwFKZQxhgpokyqSgVDPKEHwXijMZGwwFQjoHdjYRNGQHUBBrnHYoCLCMqckKPlPEmizBFvauXMBqPjWLhowvdzojLBdlyyzWzTZuKIrkqhnFLzepnv",
		@"PszTAxYOrkFValFfPcYxsyPpdsURrFAbeqhKjQAkxUgnPWKxEeqxSnSQRrBpFWpSdSTJRMuYVmXYjbRqmygsjiyFBEMfaKEMmCqxqFlznvcfXcDNUnEAugdWzUbhbJXfyOxTi",
		@"GNPcLNNmzLdSrjdBjsewNXOCwMlavVIzucwNUzqCmbXRdASLcXQchgIRVbXjsKbDNxkKIyrDLvLMLrgtBlkrzMEdPkRZwzQLTsUfYZAWUUddIVmJJbcMcP",
		@"bkRMjzIIRCbfiFQyGVJgjIIGJYmuNsoIchUHkaJJNipPKqKNRCZkChDepiaqUvCAWeQpCiHXyrSbnCkUklxynnqYEkbkyIHIaKyIwhbiprdUTtxMqWpzFFgyMjkidQugXxvt",
		@"WzItWOCRrDiusSDprSdKmsRYUJZxuEWKgFTSCZYfgwcqVKEVZPQFHjzHMOOGYlHIVXwsZdoVFcvzzZOQWoPLpsiDUtggXDrVNmjObvkkcOpAoxHHXeZtWspEfImEnrTyeHVUBF",
		@"TgvxJDjuTrPDxeVLAWZFzVTvTOtqQrMukVgIBsabbDDATrwvpoGhzrLwpFoBlKpkJjQOygCAuSDnQTiKqCjFsVKUAyODHOzidWnMWql",
		@"xRmynhCOoFdfmUNHICMKoHtaEBZvmdTZkxUdutJvFGFeJbCsCUdgOWIKGvwQKZFNUurOCfbzMVNLebZqlEuDAviSCsAZPLMMmTRaGqEsKyWlMvTnVnUzUzujusBfFsfIhzoW",
		@"DaJPLntXhyLudHEHfjcgrHbewqAnmpyZBZyPTgSvQagCnqlvkkeHqYBIwAZXZtNRVpEyStdDuurgCYwKgRezJKuiXqkiSnIstiZFtqUoLppkSgxgNxjltFFZdUsPIrEbebkDrWotPaHT",
		@"TDPsoNuWrIWJIunGcpfoRGMEvLLWDRNoltdaGuqhhQHMOUZswwWCIvNWftfIRcTWhbhLMLXtjrtIjNOUFldWNIezQLNBQDeTnvFVhfAJaQSuGAkylHdUvPyHbgk",
		@"JyUQWYbBhDaHvVMACnZVMzkGvQpraxEoOuwlkcDLpycFIxomraKQaRQjggPhOCajgHqfwKcbFzFFvpWTGBXXfQtfUSowWQebVydhtybkKJo",
		@"vEVxFjinDdRoNTfRfEzxcMidwRFNmUyKknIqMdCFbcnTqcXbicMHKonPCROtGITmliSpeDjXfKjjCOFiSXTjCKVBSVrnYXJTtjfGRVcwQjxnFJOCunAxfMQpzaVngMRAEWiEoYllFNtUhwfuo",
		@"NLWSVzuSasmdueezoNHUbAuArFsdvGQvdSdEPlnAOEHBwDLbdnnKnMVIPKfWhJMUvgQyMSidRFxWkusrWeOrLsSpeBCyVsqKOtDnUxtWMUdjrFHEVqshdQMtkVvJHjKfCyAbsbbiCmfcJ",
		@"GMhoRNQxTMMrwYpAsklCQxcjOvWxKZXEVBzCBjXebNRGAFeausiGdRZqJLBNIDTLjgaDJPvireWhUlTtNGKujkwoXARTMPdCAeMpXaiiarRDjJFLsxfsyPVVMpwZ",
		@"NpDEbgIWpgIMxiIRFCdYkYTOahWdAvPtKvuHeLFWlGPDLTxBJnwrLuafTYcBWgsmGiLdtgrPXSdoQqPsqDFVfkywXksltMHSJdoFTCiUZVAWHymGtTbeXuEEnVPAcdfSpPa",
	];
	return DkAPVbswaUz;
}

- (nonnull UIImage *)ukFtEEgUvn :(nonnull UIImage *)pomGuzWCLyPQtkXoUkd :(nonnull NSArray *)rpUPOmXLRhKhC {
	NSData *mqFyqtLFIKty = [@"GzzRDkNxwkvrXqdemzdxxWbGRCwsKBAefuIwFVfIxsAJkvySOFkDSlIrMmdLlMtsDzRkKgDzLLnQclceyukWHBBwixnMztuEQUSRsFRZfsOQgY" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *LkynTgLFGpapvQHctF = [UIImage imageWithData:mqFyqtLFIKty];
	LkynTgLFGpapvQHctF = [UIImage imageNamed:@"GhDDQYryTUqaVCxUmsibdEmAzXpOfkdQHQrCzovFmdtKGnuEuCvIdxrHqZCQwKADmTHduCITZpKoCtlNCfzMrHXQPrTzHqvZDwylAfLWhnlrC"];
	return LkynTgLFGpapvQHctF;
}

- (nonnull NSDictionary *)SlabhXBVxdg :(nonnull UIImage *)wTiXUbySSNnClB :(nonnull NSString *)qZyTyIRyaDxJocswlSv :(nonnull NSData *)dNwPinXSxKcJAS {
	NSDictionary *aYJNkCKEjhHuEPjgM = @{
		@"TvmAWOkBOfhdd": @"kaqpieIsKwUUWiHNpwtejROFoHsTfxnPsQFgNIikEFFYOojDczcuYbcjsdWUiISHRwAKsfNImlubpIrCsslRUHmDBSCMDbXGIefZdwIvjPCgHtKOquatueJwepMmtyNHPXKktSOndTLJ",
		@"zZRFnmjCdrdCbe": @"SriDhRamZAJyHwkHzaYFosdEDvbGFiVFcZMRxCafqrPofGYNKpMDQxrGhuZrdbCezhTQyeTvAzsuIjQQwBguBbJXJoMPQllTyiGRrybUCicEnLOKMmdccKxJBWXDeKgkrgbOrMpiAuBnBne",
		@"wVtDvlCXcXe": @"NgfQWdKdvKRBnKNISoozxgxRixZQkosAiqQBbsOAhlxFkvOBTYylQtrImbgHoVWDcNviUVNiDraKUVnZOXjMEPqkihwxsnyqLmussUUZIwgoCpoWAGbWjCCewRRfWiBarRnWKeTml",
		@"wSOVnCvGZRWDpBlS": @"uqUNOZjbYIiOXXYPWonuaYcqPyLpllfDgOJGOgUXDKZcHQFzOjKwSMYvmYUTKzGHtmoxtvRWiEftUYkurWHOzUpqNSBOKOEZEStFaJRPogozmlgtyqZomkOYF",
		@"vAfURSypLkUlV": @"hkqFZKgiPHnCXXiTgAJbfyglaasYvtGwioLVOxdpUOKxRfgLxDvCtJyPACuvFiJbIiqCxvLaffpOPkNpoDawFaOrKifvUiavjvfkvEV",
		@"MWyaxmmCdGLlHOX": @"QRWLMGqtrlRseTDcqoznMxrdmZivYaGzgYgimrysDNrSwnhENbyRDZcXezoefMvxKfMyjCswndZtCGZfHwKzOAbXFUpspMCgApoXZwotkqqIRdZfYBSFCoOo",
		@"gdRwYSwYqPIMeMWR": @"heRmZsGOoaZjwDYBCZaPbpgaobtLuwdWiJvGmxOhkXCWLrKbjmSPFiSgQCwWFECMtCHjUcebCiqraWVCNxaFEoGxovtNxJAWhPAbiJxozfCyojMPXVINQjtrrhmncJXKbSslzUfaGmdTPFvS",
		@"qiPgYVpdYeuflCd": @"XrdyLrSYtaGNcgxuTTGxYQSLydndgrPdseqHYbERVDIJMsvRvTODfzpgBBCcADOGPGGmDpFZpSsIAgCxaGJIDcNAkpliUCrUDGGAsfhbZhGJGOXlBVHyyBlAwfFdFYjUuTOQfvHBPzRymC",
		@"QeSWEEataoB": @"uKsNMoDHMdzXCxhXtNcGkNSExwYwFcoNYvlXigdYLWnvlUVZvPIyViaRVstEwCUpKPtYuRMbvvLtysERuxxrPYGARazQZgwVDsmymKNkzEKqUBkAYACqolFJGeGWFwSbVOxJytBOZ",
		@"ANuXGbnMnm": @"xLWZLMIFjnERZhDTcAvbEfpbgxQdVGHjAcFthyEKDKDlKdkrMGCUNevdgeVWBjUabUGDJLoUwdtEOQRQhRfdqqeserUcPXZwWWoDzdeisBsWXlgGgjyyflq",
		@"csAIuyrdiSHoQYSK": @"LTERSvgUGqLbMgDHVGpKekFhiOeKmVelypuqBAETsKIVLmUzIsEYTGozFDitHsaowZhYPmvkLehHOdQqjYOpxDEgxAJvTaSTbNvznPBZDiNhA",
		@"WkRLUEGJvgDEpcY": @"guwFgonYXqRHDTKinsSLpDrJxtNZawyjoTnvizJyOCdOyGviVyynQMIdsUVljgyhXAAmzfAyaWNOrwfWZZyXJeFCVNWkkstshPaYgrDMZETeHEmgDCeWUMg",
		@"KripbtFzjUmZ": @"ekMOvYeLcRjUDtENNhEEkQWqSGwthUtQNATgpOIqdHFJuZvbbPLZyEVgLpGSFnKQorkyRZpFSTriRJzvlehfxILVIiiBtERwxLeL",
		@"ASqBcUQUomf": @"GzjDREeEOAPkklqgMTXUYgYfbZuKXaKnovCriyCrsYOtaLYLfhWKKlRsfuyGeYkyphJMdgZZDuZXcpRIhlKtOWhiuHcKFvlgprnfsYFSzLezlvQUvcRhKw",
		@"gYcPPGeiGoNi": @"KmmincvVytjTSwDtkWkeIvlTtiEGvVfpnUTCOofGqOjyCDKjqdrkknanWJjrAKGmxwprWMYZqPJXUTukyYJyivtxYHNzSEDfRImapxyjK",
	};
	return aYJNkCKEjhHuEPjgM;
}

- (nonnull UIImage *)FTzTTgloBYieiKR :(nonnull NSArray *)EtNzSReKRv :(nonnull UIImage *)nOPXyouOIL :(nonnull NSArray *)UJnTuaADdYuwu {
	NSData *MXsWqVXTBOJwjPZRas = [@"jJsbVmIxhXTxRchuWXlyEwhKEZCbMkMODsEnKEGItkWoBWRPmvgrtpnyaZvyVaxaznARxBrUWONpTPypwSzOwsofhcsiyiqnhjpkoXqaKCmevmmAzYJvhfpjCvhtrsRMiBNQPHNGWvRYbTyUgyhnR" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *mkEZkWYKcXxE = [UIImage imageWithData:MXsWqVXTBOJwjPZRas];
	mkEZkWYKcXxE = [UIImage imageNamed:@"gJAHfDdvYrEUbnTVhocdgMrQFNyNOGQTFeYMCwAVqRsqfVDjkzaWJHrlIyfbHmSbmyJVoagqbQoiUeRCwQzazjgLboGUrWNFfOkLSqacAJaNhbSzTtKbySPImiobTDNzQH"];
	return mkEZkWYKcXxE;
}

- (nonnull NSArray *)rqeiZeADqJGd :(nonnull NSDictionary *)zyapwLRYfrgNdOxbBpI {
	NSArray *gIKteVeFTblC = @[
		@"OXNpRuvvoAvjnbZKWcKXNihjmlmEmoQHLEngYYyDrhKUgBnpKQqWXGUTLOgOHewknLjIcwdCgWwnjeoSsODfhhhMUNxiGmZciDJo",
		@"PLtxkWGzsJOnZMoAUnGRArTHJjtRWMqnywksicegiACloCtLdtWTQMYzHulhDtjQPsQfwqwboWhlUusqbvyKAxuJnnYFpDKRbDUCEoXhGTuAPPJVmNeZJa",
		@"pQBrkwKeQtZPJcuVlWXyzWzRBRFQXSCXPPtwpZbKUFdlXFlFXRxKIJRIBPGCFLlFAMrSknRWGIEbShvZNLADAXTDKYmQdesazDwqmvAjwzyOwjDsgRTjXZFIZoT",
		@"GJORIFLakmjdoMZhcvVAawUClnqrpnVGAXXEXxQnuTxrkzdeYPDOIjVsawzYXuZhWylKfMQygAgtdGiMkqnOpebcBGvTbSqffUMEjxqoXW",
		@"ZlyxCeIwaBKySbNnChxRFMfPmDYfYtiDIMdHQuWyEhLlFmKSKwmoQPegwmBkUTqRTsEPqckiEUCwMHQFgcjglmlWgvAJErphCEvUml",
		@"ieIstqMYEHctItDWVzjZMveTRZscgdsqZJmmeEPKNXFVpFpKPKUggIMkxxdUeuBIPTcngLmxCbMMdykIuWGkGseOmSxMfSWQosOmHvokcxMMgcrQdkvwINZvdgrBadDUMXGTaoLrYoQSarnKJhW",
		@"kSYkCPZeUiSnpOHvlvhcIZfxcDxcRZrYqOVKYTLBrriMOAITliaBMmQAOXCDQfJZaMbgxVRknOIlFLpPIJOZAVeSzXzXxzDmhmWHNnpYunRQhCofLbvpmZKQIlYuNdXsJGzFRdMRHQhba",
		@"XCIoXkKbCURMGXdGivXpvqWhljAScPUTVwBbPyGTZdGlFMebfDXVHjxQKvXfBHRPLJijCJZSTRYDEsxqRuxJIWonscFAIOgGMjEeCokRBBZBJGeka",
		@"BznYVPuDSDSEagRPDOzZorJjeRrZwUzWSOmvDnCkyiujVSRvzJADgYuTyagWUkrUAHkVUkXrzUawEEITlsUcSlXmlJQOhkQQnEKyqWvzlNej",
		@"vVzEQtwrKadNZtvQpxoDDrXnFBFOWnXUVsyrOLGQeKbLgoTlkrMBPkNWFaYOMwYnElSCijqlajWbBdZqnKuVGkhicoRLHfPjaJEWWPMeglr",
		@"XKeJskaUduoyWpJcLuHBZocQWTUFYWGoJvKnoOqdZVaYdogQFeOkATMUacfCQofUbCKsOvCKUHATbvnzxDbreGPnMvSPqPvPsreXMEsJOEYQk",
		@"MYwIwvVsMSdMzNIvrFbCndnIdqnciXdJiZVpnLeeEnyKCPsVAjZVQPCPUPZHjmZzXCjtnxcsmuqtqHJmhTWYosEjOSMBwCcwasiHxRztBeaBVwfCXXjRqYtUsuIuNtPPiNs",
		@"szgoTEYucAMyXPkaWisUaSisgEERnvFpoKpmXGdQFKmqEuNfzxBRWkxQQHuSuisSNpDbhbJIOTVJtaaFKtZaYZcsPWHICtDBuMNx",
		@"YYLxuNDneQQZmXOnybCsAzcjMxaQmpcEkdUfnGRBWOxrHTyeGXyKSaKTTiBHMTGSkLLCpdgCBZAPhSclFeYciHwRarZxDicoZmEEoyiuRc",
	];
	return gIKteVeFTblC;
}

+ (nonnull UIImage *)UZfPQPxmgMje :(nonnull NSString *)TPkPowVHwFejHi {
	NSData *KCCAmaAifUKPzTQs = [@"kDlCCLqWkYcQMzTNEqDuJtRJDBtsmdSBFrcFZwPIbGEetvaCsrpjRgVVRlFWhicWrZDwBmhBLzoURbhkGLrURvnJOhjjHocSQsbrzI" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *IeRmKjeFtsbFCkZLU = [UIImage imageWithData:KCCAmaAifUKPzTQs];
	IeRmKjeFtsbFCkZLU = [UIImage imageNamed:@"QweDAiYhGvKldWtPvdEIiJyAKsiYTKUEABFxBZWKujRiwZwDKdGMmqICBkXkfflnEgEbTlbXryQKSQKjzPGdHWlmtwqKQtecLIYyQBuDttJTNXFmuzJYM"];
	return IeRmKjeFtsbFCkZLU;
}

- (nonnull NSArray *)mQFOfgHXiIXgLOqosG :(nonnull NSArray *)PpvLbhYggmOVlJiKf :(nonnull NSData *)FNLfkILjnHEI :(nonnull NSData *)nxsnxIxYeDgPpk {
	NSArray *SWQSTJCybYmqAIbT = @[
		@"xXcscIdFgpYRZtJPkoiLfGHvzdahtywUWugYPMIAeGcsFsTCTIkKzoPhGTUrJjuczPjvMJOQYwUjCWuDPCZLzAIXaTUhAnrQhgVRRFVztvfngaVwtJwSdd",
		@"PTHMQWITXbcDEJDGVFXzEGgUPFgJNafDapwJvWggsfejKbnFsKvTFnhsfmamRwKcQfabwSasfaUwfSmxuuTWewGZGwtkCszzOASEflLEEUmSijtIABELHPCzznG",
		@"zQzgqyCqcgGxkHGEArfeoipMbEMbpjUxMAVkktkkTikQqAbRiSRpxlvUhjQilnXKMXlDYvvrgTxbMnyPyZzRiqaXyominhtYxvsCjQNjvyfHNAzavTSRUrReZLjbP",
		@"JodOgiUDDtlaClrhmNtnVUldCAcsMDRBWAtHVhJZZdmUnONTEvqWAQIqRuLfcbSzFqebraYunkvjsIjCHEXXSJQpBqQzCfTZgLiNxNQGuMphpqrMlKP",
		@"YnaJonAlefLvcvrdiymWVJEAXipcEdshMgQsYdJVzbnyTaVeftUpXuOMmYwuCxMwEIivqtRTZAwxJUmSBMJvIWloNiAqWXBUcDkdaSHzpBlCClK",
		@"zdDaJvwIdmGbCJmyxQyYayUFIHwsqjrwtgxEedVnNbNQOBoXwLopkIMDqxKYIcQAMtNKVdWBhJTeewBBIgOlfUXDBRzQhjVtMlSWQp",
		@"IVTIPkcMbQGGeMsIpAtPGoeSkHroAdqSRKJfiRGUenTTkMBMhVznFYkKqvucRFSUXVCFDVxRDZQaVjoeWrYFRmwNbDnvkiODYJZRixQxYJofCDuRXxMxCGfcNqXokXlWxBRNAwEHsyJZ",
		@"UoWrijVAvnfNYZUPbbFlsWatOvqhiDOidfjPieZmWIkTHpCOCjChqzYdLoiIwWPGlDtASBXoPiofARMXABjfzUPqJaIfWKsmtMHmvaWpVjp",
		@"fAXkpqMOoyYDQMAEADDZSJefvUDcuFoBJJoSkxQhDjgqLBnOvsgHPdWMXUBUCAPxrGZIIvKdBGNdIYbBUYGBPbhhIDawqsaAOaDCKCYJNgxQlotIbpbekHCgQQZfcAmKVj",
		@"zCTNdCnNFLhXjSsgLRfNAuwcpeJDhKBLXlurhJjjqaHGXxAKuTYjgWrkAmBuCMgISvSnIjdKjywTzzLuNDRzDpFHyjGZBMAeYRCvNaShCNpOhwdBIwBCqRfPLibOfPaLkoGEKrutqRVtxIJiqD",
		@"IWcHubEnxeiKvyDWGzAJEiUdyNSkwsgvhHQVuVaRRunkVZoivCubDFoiXtYkboNXLrLZpDIcIrjEZiylhzfgaNcllnpYzavYJrxBFOHnt",
		@"zRODEDmBLchUyPlpzboPytZNJobBVulXsyJJKsvTZAyMgfmZVNsRuGJhosqzCJyqDtXJxTnMrGtIdxTvEpCDeMkiDwlETgloiupzZ",
		@"TQTCDiMMMUvIlluRTqwxpsHXwuRIMNPFlsQbTEdTieyvGJQnALHVAFiwsrTUrhJMiPpgLznRLCkyMEglYEIgIDSvpLoqVnKnilxMh",
		@"AjGswNkCwgvnySfzENdkyUVpjDAlMlJIndiJbHHjXYSdwPAemgzhDToohDXgzneqdqkktFUYxXLCfevBBvgLRzhelWcuWIEVcuEEQ",
	];
	return SWQSTJCybYmqAIbT;
}

+ (nonnull NSString *)MHgEtmqgSCUvZVGsQTd :(nonnull NSArray *)RmkFNGjFcCMNzfifk {
	NSString *FBwzhkqkMKHXWh = @"xmKBDijBdAabRicqshWFTUBmuHXotJSkpIaJHIvVMhoWQIoaLVelvuEbGwKieURuYxAVTUJSeSksWraZjPKkcSBMtvbmMyLhkWAdlNgTnbkgUxEtxod";
	return FBwzhkqkMKHXWh;
}

+ (nonnull NSData *)LkwUFMMmUCGnJBDcEoi :(nonnull NSString *)sZeiQwEYPRuRuUm :(nonnull NSString *)legqKPtTwbGePWNEJ {
	NSData *AaBlTgzocMd = [@"kAyDWBdGySZKvbGLtIMQhhApFlcYjAbeGqhcFvmxoPoQQDqXalxnnSBGcgLUsBsNGhRIzpsMnQJXEBZCXtPynypqSGUthieuYWOz" dataUsingEncoding:NSUTF8StringEncoding];
	return AaBlTgzocMd;
}

- (nonnull NSData *)SMJjMhJjLDuncwlO :(nonnull UIImage *)NgtVZrxhxAPaBkW :(nonnull UIImage *)CHELmOhocYrtIrYsPEL :(nonnull NSDictionary *)RDyAGJLzdCoTlWSCi {
	NSData *CmHQHEXFltatk = [@"qXfaJqpBVNyssPzrbRQbIFxaQfiqVtQITkJbFxrVLJnOhSsDfxQmNVAPhbZQEyVLsjJjtWeMfIpsUrdJXCwOYyHQYpFCAhdCxJMLsKfqxeMAPpXAqBRjyfLbmBxnFoWoSWSldNqtwGdXYmoyCHwcv" dataUsingEncoding:NSUTF8StringEncoding];
	return CmHQHEXFltatk;
}

+ (nonnull NSArray *)zzqPmdqarJuyJuIUd :(nonnull UIImage *)OzjsaSaDRYUXcQU :(nonnull NSString *)PwEeGOlrfnQsckIcEOs :(nonnull UIImage *)MNfCVRqoGojOOXfcd {
	NSArray *EbFabnxhiMyribwS = @[
		@"VdumfmSSFoFKFCzMhUqJRGKUrOaWNZFqXEYOydEgNgauLfqhxrVMIiJlwVdpZIusIiiOLTtFRYktfCQcIvgJxEddPcTDCpgMeSUGFugGPjTvAHuQdCOoFrmMmpQNwlJdp",
		@"XbYlcmNKmQifozQSuUnThgNFZMbyIDSKAHUpTjODkNDszgYupFfbcmKyLOSMmmDADmvvkzHUJzBpkrgsApjhckZMalLIoaLbrLzUFEVzUJKIQPvwQxzpPmiXQDHGPzWa",
		@"WgRwkudwwgiOsrRRfKRdxJZnfpFEtABTUgKEnHcMOVdeqQvfoyEUYnJTPFasYDmJMfEjxhQNBJpyuoKCRrhmmFWSGuWuSgJUlcuhCsFupOyGxqrAYAVIMROsFqVuvoCjHKXw",
		@"eKtSZNVQbdrtmmzVCITTHaThoFBRyDLNMPIFJLTszJmLASbpbyXFLEZAuSeoAJSYmMDouKVPMAhRuzEIYzYEVihxQLubYnrtsURAWpSpjamZFxxHblTBCFypeUGcOJigzYVQDdAzMnvhBvp",
		@"VfsfrmbKKxEwuhtOAwfssdKPACkwTpHAfFIImJvsoCHkaIIAqehsEKIFPcWtZcxKVfLzuNwJrqEdIxxngrOVYVMgebLiELIYOgoEIymPD",
		@"eIYnlXxDPeAAVVcqZSzXVoOnCVfdlnIapWhIxYbVAPSBJKOsUlGuoEBGciNmxYgxAPFfYhhDzurSCUzCIkhrTqOMlrZDsIYnDLRPTugTGIgyoOPjTetXKvtXnaOzfhtrLhsyVzZORTzgi",
		@"DAUyonaIFHxcLyySLpUgbQWFbGDMZxhWDHUItqwhqGjNTHBxBFpXCCWEvVBdvivkcvjBjSCAMtpMhMpscfUibFKwNuJfzUMYglyPBERFYwqNAIdeIDCUKgqvmzNwOyzJOsvsVA",
		@"WHvjTFgWcccaviWiBDJoDJZmuKqgrmMBWCaTXANTwuaEVFbertUyqzcfuKRsLNLBnpQcHSeoDocfwegvfFLNBwfedbSZqyprRBujCPaUyqyScRBTxeprhoCQHDenjOBl",
		@"WzXpnhzVNeJJSjuUKMLbHlWLBxdrpindRXzjaOQwsgBWtGbOvRRyAhzXYAKGiVODAkpvWdOVvgEykzenQMrJqChNauaOaGMoytVCMvUkQUqZqhRyoKsmRVyhLcRFfaEogcjpVNjtBZksZr",
		@"bRWpXCeDvgSOrdUHoGgNicVwPhpVwGGpSIFMToQhSlRiTqbBElomkgSgXPmyqLHVAlzygoSxVfnqWnQlhEtjbHcoJGijJqfGAiLiFxGlWSNmFrdGskCbuJTSgYb",
		@"nLFmqkisdwLKZFRoSeMpmzRuVYwNLpGODvpOxCBpCRwaTiziCeBYHKVOtnLkagrRyAopiySdSPeWXTunmjtfoufDHSiCuJSPBVqjjaUZOGbYdRVoIrAQJhKFFkSaIIrnVNrlGyFAAnv",
		@"aNUQsDrTEPKGKqnFluGPSYnVfvmRHRssDlKbMizgoABIPBxVbPlkblGSkEFCPCaRvItgOANyKRhktEzlWcyCiJiIFcdgiyEzxbHvjvdkOZWpLfouRgwm",
	];
	return EbFabnxhiMyribwS;
}

+ (nonnull NSDictionary *)juGIFMSTMoZAnCs :(nonnull NSData *)MLDqeEEwDbN :(nonnull NSData *)zcRodjTWeZIo :(nonnull UIImage *)ApcWYSpuoIjsxeDd {
	NSDictionary *otOdTvPoGBeQ = @{
		@"eIySMnWMVZAyaePydWS": @"OToXTZTxiMKiHJdopqKYchgAnWtFuEjvrfolJYhbCOEeLtHtfdzDkgsehPafxrakiKoPWBKgMzrpnciUeFNHcOAEKAYeWmUOOrzgetQBiXcJBNexitAYXnySjkqCQWtp",
		@"kQnJLKkiNYqldVEtju": @"QZCdZuvTXXIDlfYJFvjDyiGLGsOCSoknOTieZbLWrfbThtfcnuKgIiguLgRBQymqcqhdYNIwSZfzETSENSoAwpMyjLrwJTZlzoIK",
		@"omqwFelsIFbAzHuBk": @"MucXYWwCROquQEIovglSSNQozFaVcIILQahLnocihNLtRykmFSHDqkoQjxUekzwhkIRkbftXqveuVYdLXGTkCLvdHjTKNWNSvvfCqifdnTVEB",
		@"lHeuzWBHKu": @"RwLHdzjtXhTkrFqyzCdDCHbLKLAvrBEmzqBWsfhEEqmhhUEMdjFTkQeffrzIbAfIqjhMkhJXrlanesUAZxZZIPefhnWAdSHTmzzgHeUQRTNvCRYZtuoAjcNGOpxDU",
		@"uwrTGDvGEgV": @"eOzDmUHCWNvfmgWxcgQEfaTwmPDPGcRUqwCEsgAtCQoopmviwZEaZnCMqOQHORPIgtqEkwtzkwTqpeiIfaaxLKjJDbnktxesocCqKGRZ",
		@"tFZAhKVHwD": @"nDKWFtpMzKJfyTwoZheZBgwFSGHwlkhGiMrjmhkiGdQOUjgbgCNQYbxFCzskSPPLvsPbGTneEdrAGmtqOIXCDCwvLMLEkMXZATBBajYXXX",
		@"lEVOmQuzqeMtATyyM": @"dwPBjWMqDajYMYQfAqSblxElJeXyzWmLbRlOIyzTPywSYIjOKYwBNeBoWUHLrQGPXCZWDZVWCZAkKlbmyCmAeQTCDyIqTKHbfArgLFlDLLfKzGIVdHyEGRTszLfjXPzqjE",
		@"eiVOhmWWNqvxaT": @"lOEBFdxYpkLvsXABvZvvWWeFRQrFuwgRGterLWxQRmHqGfxwPUJPttoAWOTfYxtxLIeDTErSZhACBoPnHaVMXXfsQlHgCafpoCLZtoNEDbNkVkBkOuvMKoOUDCbyjKp",
		@"ERqptaDynQAtPU": @"EPBVXKOsbRrHBRcfOQFRBkBswcroWVtuqKdkqcuirAfqFMhVcAalHKYZLSeFZTHRVreAlPRafsVLqJTrUfjkyPecFVlOtscQVWLBQVnQXagmEBKSheIXgoZsEihugrIqX",
		@"knxMvpGwoThSNbxkbSe": @"EyBGSCqaxyGBVKERsklMwudZTKqoBtnQBWVOAMchYXVxjkhfFzSjQzQGqMzFvIwtnaJUHNEFhUmAHumAVeoQizSrIkEsVKpJTnguNuyfkJIWEFdGwuJlFYrRZ",
		@"wIScyaZDRCDKuPQOkb": @"HeRbAKzmHcEOldCNrMtncWsimzzDDaXwxnoMmiGSKiMYtLFywooCUWKLDietELNOMMpDPwlvfAWDFEfDQqpInZqFHQOPUKELqAOyAiRRvkQtxSoERScvqDipJmh",
		@"DPRFqGJTBlCNxCZnJj": @"ZjGrdgFBZouIOwAfnKjsBfwsdJBEsmUQqhmvqURSUEwMjgTSLQkufPrOQxaiFqDgZKsGyYeZQPLQehNRapsxTxPopICKTAbHsJeYSidctjLEkJPpNLMeK",
		@"kNgKJhKNXPIWDg": @"RtuZNhYwcVZRHaBrdGsrhAnSiQWpcpLHGWdYBeWucoKuHQSOOBGnwVhfgWGnRztvwZNxZbEFkojtEZVjunBWstGKnfgvWLsKbBKvkUGhAxuBxDsnsYOvjsISfpXPWVmSOjNuAJNDxWO",
		@"CUWLaRymaJwadf": @"fufsOenfKLdoCNLAekOZDbiAfRqRwmrnmEJlZrCHHPYOSfCSctlVIloZfpsjCYozPwXcUKkEotifkPHeeVGtTKoCcTKrUGlGWuLZQgESmyxzOcvIAGmtDPkmHLQqNXaLrQVLuSaaBPn",
		@"QRCSmrLEZraGUadMVRF": @"azcgencawrefyOaEbqbnEeqouXhtpsRPDDHnSfUeaLCaIOQOnqgfBvVlGNWhdxijzjHcpkDrjRovNMvgpyycejrrmymNhfObxtJIQtcsEHixAmhHPeXi",
		@"zZZCwBMwuIIJbnHTVPh": @"IqCCrITTQzxztXveYRuUVIumDkqWKfOkRFFatYJZoINGIOCxjiJFxffcMhfjLngziEicTocBqXUbhjfPxoDYfETzemkhHYDAtlNdWAibpeyhqLSSS",
	};
	return otOdTvPoGBeQ;
}

+ (nonnull NSArray *)eFsXrhzJzZse :(nonnull UIImage *)KAGCpEJlXIYaU {
	NSArray *BsVOkGroMZpPwDG = @[
		@"qjIosmNMopKhUroxZphpljETxbRMgiCddNIpBQvSGgdWsJLFIEXEDatNPPjwUiNyZGyqQwucYFgCtFWLsMFbOfQBNqZutwCZQUtZjomSVVjizzdbFCfLQKvJSjGTqwNCkZskSGbKfNtc",
		@"wrgOpIGJQbdTylFdsYacKtnwovgpbDepdyZATpxbQlpslVqKxHzxjGwWUgQuQDnJhIOagYNjyWWygOTZXbXyZVxXbPsjIylfYDJbQqORZxlEdRtYMsIMtwFnUhFYnrFyuDxbKI",
		@"YCjLqMVgIQcNZgGVHYHjYTlyUbPZADmdkNPXSrZHIpxqsLRysEKFURrmnzDhXhFbWwiBsGGjuJtDyDhoWzaQJlgSVPMmBeabXkjwdQIaCxUKMZGOTxZSD",
		@"KCrStAgzwgnEuuETRLIWtlpxkRnzSMMVXjjwlAihjBkZuaHupIdITjtphSiimNyplNxBeIxFYwgVgyYgHJBImNJtLOQHjVTRbRkvrVxHHbkETiQtdfslHNhlTbRsgXmgLjpVRrqsVFjfj",
		@"PtxgbjuKYaVJkbONJIRIefoKCYkSERrUaIFXITyztFgMqUtZIybQgysOgwTdXJqOutovFWQNdwcdkulCLuoWcJkGWMcJJfxBXylQFsxdyjvVIVLvrsERBPtYjeUkopMBt",
		@"KbyMlgKqVCQzOqooqjFaWVVAPpQxeYCVVOZJzLvFhetnyCodIGvobvJfhFjwGUcnojaFhilGPqcWCpgtZFpJavSPqZdfelgZHWONDuGAgLSOZLSiVUyGdUVIHWwiutUIthAHjfxDIScVs",
		@"CgNQzagNpFSCMhQGzGKToWNiaRnlwBuKPJRenwgAUOlUqgGBesDKbZmbHCSRhnGHxlqhvaUmJhZXqBcxgMJFjFlQJsHTHcWPOruWRP",
		@"jFMtgsLUwHvnUUCnngvffYwmzpadeYutYWhkrruQrsYEIKwAkDxFmBOJMXiNqonFCkJSubVDkiifRfRRxsqvNfNyQUbKeJXAZEgHgcIaZHUyHamEETnIlAJDVglDoIZBwGNOiMbNtXkGdAC",
		@"lIEEQgSRIUvZQaumzGqHaNkeQetvKrxsOHwIoEISTQAducYIwaOiyispICytEfDxqcZsKuImAcqLYbKnPHTsdTPAMprwHKkTmLpTldpNvUoPDooXHhnTvUJycKwrlVOsznTxRjLecGzcwt",
		@"rthlbizFRXNvxRxCVzjDLnLLybUIWYZAyueKJbirhpnWgsBhZkpOyLEmameoWKDdfeLgPnbyWrcAhqjDCdFyKIfMRIIBLyVtTuBALpdQ",
		@"wQUMAcZMLcanSHRCDijZamNfLkQzikDHdtuoAhGMoXyTajNOHTRZvuFeVYdVsCXlVsThBtfvxrDYwvimLmrHNMTJvupbptgDPISXtIwNVfMKZ",
		@"EgfdoOPPnJjalILZkZgKBlXjejbovWputQXCYrRuKsljfKSwTXBfIQaRFURfzvDMefqZlpxvGemIEiciPpONPWuBAybCmdUEmgvG",
		@"HraiYKNHcrSmqJuMyeBqGhWtPSKofDWTwdGsPhDRDDkqGwfjrzvwdVYZKKuLlbVhrVvBOZwBlKMDbjEhokJNfMBUocYTPEqiHHGQlDdbroIifcOWaAhxzYkGQEOTfdUf",
		@"jFDFZtfcJXeWdLScLNuzKTiVVzNHtgOUXIUOyudbnWoKZLYCDrxhvGqYnIqaBKEbgZvbsURhJdxGvgEBxZVWgrbHdBqxNqKpryJCyMIUdcZZzOBZcXgbMdWqcmI",
		@"ntuhKZIebGODQrcQfHRlPbKOxUQiZlSjwEZjTAxkryAPzEhCzJBnLPOejrrsXalLzBHzCcyyFVZvjzKQjSCJMRbNJpRDoTTtpUaPYsljoHmbAiRIBVhXLKMKowHAC",
	];
	return BsVOkGroMZpPwDG;
}

+ (nonnull NSString *)IWtesJTcUfUD :(nonnull NSArray *)qQpvthdcQXvoDBbJm {
	NSString *vpvVZoQRYNypzvIkuum = @"SaETmqAnmbSlGSPMJCEfwwwBlRjgfUMNwzNoKcNDylbSGsQyycjUcKJxBklgHfVDVGjVPCXIogGrNRfCKxdeQPjxZyegoSOJyHnaDLPxySPXsRSXSynFkXrDPbTpU";
	return vpvVZoQRYNypzvIkuum;
}

+ (nonnull NSDictionary *)addaHnPAFsxFG :(nonnull UIImage *)ibHFrSYXhe {
	NSDictionary *cJrpYgMgYhLtsbn = @{
		@"KBazgiAsREaOSsnpzf": @"psHAcNZkVYXqKqczAuQNIDZMHItqJFXrcOGgsTkApiyKGHMBNYkepKBYSdNDqHjcNhDprPipPfRcbecBEGTiytDApJxyCcPIXkxoLWYEOGRvMDRebgyJYyIgyrBlDuz",
		@"kJiHBTQpHuuokvGCGud": @"YUGmUhbqnamWKXmOAEELlEkzxniGUPmwDaNxXHZrwlDWQQWYfecbAOaSKShCVCsWbVYDINKDkTlcZmgUZklyfhhNcYFncBHlTyokJaFukxqbLNkjTOwdDeSEBEDYNqdMjYFjSwKdGJA",
		@"LQqhPkqRywcAMOIwm": @"AzdIgrSWYnmRTOgVeJmlVXTgvWdLmZtNWXBfzCHiggagDcoTdUwPJzGjBgykpHlsPMDdYGIvBenjlSCcsowOeXXgKyLEGsnZpccALMcQUJHppqRksdWqggErxYQHhPQKRTrJUKGqWXVrrIy",
		@"HwySKLrhAkg": @"bhaXfxHOZYCgylDXzDjVuFieMisJPkeblAWWvWewbIYLYVBTTLVhDXrherkdLDshENAJOEQaODdXXQFJKfNiObDFaCpFviUYSvhlbVMpjYuESjaeicBfVDWwNKmncxNDj",
		@"pUlBMRBTLkECck": @"gaVXxHqGhNZttqvmPVCJZSjKgSGHJPieINKvKMhXxkJORqKIuWazutulrUkVxZaCzJSZTBlikoOfOFYBzCbZwxOoEnYdRnNcFeAMjEEvpwvUZUxzHDzrhhZqXgNWDydtDttvjPdNHimj",
		@"EbNsBrtZkRWFkQv": @"pSJuMwEZQjRVTkGlclOgXWiZvNVUpAabFcCbRHbqYfzfsAxSqkfsfWMWptysucUPlmJARbuWhoNPKYvqvRCesiSqkymuYNVauFlFmDfwiKoEGnvqWFVDEEipMANtgDdbvyUt",
		@"EglXtuwiNGp": @"wUZtzQbYpSAxOguIjidYrgaJCBydpEJebsnoXbyAILFErQCFqmwcOPmUYopvOIXImpCWQkywhJENcBvCZJAelqzUNGvuTBXYHvLuWbMgArUlfWAYpKjlHnAOCXhuezJrrJbTN",
		@"VBWUcKLRnLruuwhaT": @"aNkzCAjcZzhhBqVmupUbjVyqHTytFgRGOxqwqmKAWMHdAPtwRblwHcrVnYdqhJMvHgurIGxSyqDOsgyMvqDlJXEKMwGcfxtYNigUXuJkcKBrtHmtaIavRKyYyLIVqkSDTCiFViRuE",
		@"CXZNABUQgBTMbWOEK": @"RDXiVYuGQHaRRRjuCsjlVjFJNXZFZdQXbTGADohMXmNgzVCkoPtCTPHuiKhgCmcaVdnCOVzTQIfrXKJySkELoSKXwHjQbZDDcELvMLeqxsXFswFHMXNKRubB",
		@"lDAfFVMGPKmdjsng": @"bcRliPiGLuRchqyxiODcUKQGMGslaQCHnFFFNkWaIdwJrFpOIQibcUXumRcqWmxHwSZxlWxTbRAurRnwqYAWtcqonklyaDUlOVipOAoKrTNTuhosbItUBstQM",
		@"qSEitzQoPYDtFa": @"YdyahvIUaFPIznJlZUNrVMjaUeJQXGKEBjWFEgDtxsNNcgghBEiXBNfBLSOmSPiynOfTdMdLcBKxdFjGBpYbCxkRyoNIkQOJcrgrEQHZlwjLSOjqDaxVTzMEMfBVFhw",
		@"YXAakvRUAe": @"tTqAoFDUPxYUerzxygfbQaRPNLhHwUuKcYiBkVrnIMddcVLLjwFOTsNEAKaoSYPgiUiRFTgxHeZwjeulICPPmMzsfIrPRCfMcbooxnWDqUfBidhOlyUEjrfThQeFllPR",
		@"yYAnbTySUsuNyOxwWh": @"ZIcNgYDQoISpIYlpAtbkHLeySkkdRfGzQPlTEKqMxdQaPVupTuJglqKNjQLkVyjWKQGEGAMeBFXZwrfRunjGLlISOgvdBoVXtOLXkWqjCTrxgrljN",
	};
	return cJrpYgMgYhLtsbn;
}

- (nonnull NSArray *)SJBagVidEEAGsFnzih :(nonnull UIImage *)gNVWZZhHqtN {
	NSArray *xvqWMpxGPUpV = @[
		@"JIvZbWLSZiATiNzISiyIqgBBxyRSIPQaVlKFmtlyZQVIANVTurcazlblMlPoFKQxPYEJkjNWCXTqSKaybwOhDlGwoZWDskAfUOJyegBUaWKSmUZhTkCgIltSWOuOjbbd",
		@"zoqNjnRxxJlzqDAYRPjAjhrUZNRPKnycBWuaaqlpGKYAhfsbDzRVafxpkdmDSOwcwnQvZMZqUcSmLescptZiXvfPhvjzMSWwFUXqVAPcyPGNBHtGdCguaw",
		@"homcZaiXDMnyuVpvIpnSdiHypIAdFezKbvHwrcyGiUImiBtotHzVZRrFnQUOTEVrzHozJUupvQmebAdeaomueDaOsMwzUoGWmjwmhkONJOYVzQCJoJGydSh",
		@"NZMmGtVpsaBCsdzUzgEXYJXdTystDTKxgyHWGjLnorEZjWNSOczcLRGwdpFlrnRJKhGWqEBkSoOsaLVqJYYVZyPmwsYJRisbVvJKHccJkFzhMvSTLMFJUlDgapkI",
		@"RTqoLbVSffECmwzlmHGVSIfIWIamOWJHPZVrpNBugXBSOExDfVJmtoUPCKNnaDPyzGWYKgbrAWKacEeEvQYFpbCHkCwljDFhzSnKVSwPDeFBMUySQOJpBFhFbUpqHQGZlWcubAklu",
		@"CBShudkfixecyeDJSCjatfpAELFtupnzZYrfAvaHNiksnUkLOLUUZvwCqBYWNSETznQLhWaiKnsKlHfGdNDjOQJUwSHGrFrWYTRAraFzotNaQWkJCWVyBIumPuIqdQqiZujcs",
		@"yFddZUGhcBHHBNHGolQpgAtLTuGKkJeDnivytzhHqSqnlmUjaqaYDZEuOYRNOjLTOzZBBjcgteHzGwuLvyJpaBZOosPwFAXvAnKTjaHcGAFpjuxoKwDqjVUkdHzMYDqHViMUbbfYIQYrqSkDLl",
		@"uKAjEgaUMNXpdSKeABKhtohAzbxQJUPRwwispzUFJwXSSTKORyksFNaRuuZZogQTiqHcupdvXpyYQQWYZjmglregPkyIpAIDpJMVv",
		@"cnOmNYzLHuUIzcCGEOKBFAqgWxKzOyVkHYMeigELWkAuHPkEnGnpkRQewueahkhVcDwQdjyvUTzwkeutRgjKtUXGgMxMzvgeJLDsbxFPWREOFQTfyWttnjIhCdnpJXEtBpXyH",
		@"whMiVoydeybNODvncGfdjkGpGAdugPxrBloEllAlsHRYxROdUApHcRFeoHLrhUEmMwUtxczCnyyURtckmVwURDCmovmuKZkzKMznVaNSVlsHewtJyclXDVmjKgHHCoDeBl",
		@"AXgwWOYBtTNJvRsRpexnsINQSyyzaCOpMHZQGatbOCCGfqnmBkmbFYJOvMSgcGmltqkZcLdULzloCDRgOrLkjykpCHEJchmLnSldsZlhiIXxfPZNdNYJqzWPrVmPCtZXAr",
		@"xYZvHyWThVvPMgQwebZVyRUgDGiZkLRkrLdqWWjdmeVeZCQkhHhCmXtyhlLJQmvBlPIkvzzjvniGtyggUXSoUlVJWFrFmprtrGorjqCBOwhOXTtHAprZluePsySVtrgfTPOmRfhB",
		@"cjLmeaaYPTAodtCGbwNZnJzBJqXjyChpytHDNCcvBJGPnPNjywtnXTGNEhaaHYHklrZueOXQAdKwZJSBYosemnexagCAAreLPlsKHssbEStEuojkARXVzeJm",
		@"rWhYwxPJusuKbaWbvsIuzGdSDvgdqAVJuKjNnEYVBWNsGqkzxLohPwvLWbPgyRcaJSrCTiRXQHCchdtHoJDDvszFkxipPUWxvBeD",
	];
	return xvqWMpxGPUpV;
}

+ (nonnull NSString *)kntiTsTylJ :(nonnull NSData *)AFbOYrhtQmobl :(nonnull NSData *)JjRYoXXeanGsg {
	NSString *vXAbaksWFrURQ = @"iDPCFmpWcWBNydqxRnvZGPElpyTYRWKbrPVPnwxxghxyXHXLoINzKpPrNVmLpWBAJcDSAOZQjeOzSEIgyhsLlCLEHKqWRShDsOZd";
	return vXAbaksWFrURQ;
}

- (nonnull NSString *)zaVvprxnUf :(nonnull NSArray *)GepFVrwNSsBIdWbj {
	NSString *pBsunDcUtYEt = @"CZQfPfBFxJNhKkxAohJXBpPoEEGpBRAyiDAnfHkrRsKHcmDNkonkAZhzKBhKDVXyjVwRAsAIgSMlmDDaFHaNtGvPvsAVOcnshTIIyOsXmKqcAKJjXPEZaToCbVgJirZkNI";
	return pBsunDcUtYEt;
}

- (nonnull NSData *)aimjcWSdKTh :(nonnull NSString *)ZybQYbiVaNNkQRoSX :(nonnull NSData *)tNAzQPFaZzJVhfQhE {
	NSData *GroANAwOIyknMeov = [@"NfUSILUXjnPiEdENCKyncAbXcCsEqAvDEtuPjkcfzfDBdiaGIIknOZXLzDiLEYeNyQniOpjJvGarxqkhedEbokpoMvqfZzOMqsLGytquhONOnEOehPHxfnzfpOyZ" dataUsingEncoding:NSUTF8StringEncoding];
	return GroANAwOIyknMeov;
}

- (nonnull NSArray *)VzTTzVBpUsgdphybfM :(nonnull NSDictionary *)hTbGFIbaxrgVZAKEeBT :(nonnull NSData *)CYlRmpTphh :(nonnull NSString *)DhexEpCtAX {
	NSArray *JVErGkYOIMMgyOXfg = @[
		@"RVUaObaiOREhQdFpjEwxZTEVTWBGhiGbMRSEmPtAkkxPRaQNaWLtgUaIkfkDZoatnxwUVaGvSAbASOIRBANXgfzwTZzXocQyyrSeWcvOAUSMhlMnqifYhEqRveQA",
		@"vfyZSJzXzTlYBohowiegDjZGLUNVYjukWntKMZqHqVOGLndPApJlRSaOSBHcnuEwHMnTBjQZMIyqbgvCCtgxGsZoWUyUXnpydtGWFfATspiBT",
		@"qJvDSpsAcKLCeUnYDoOwaowyRcBWbxGuOFtIiKujqxFXOihWlMetAsUhGAlhUpGBJzNAqtnkmUcDtzpuPfCZFuSbLjguAtFdHZEmxgrGGGhuPfyRXXMTfLMogPlFuaKUhWRXZIfRRtRBkigATeWST",
		@"gMTzlelKtGtzaExylWsJjVNlxANWhNrLeXVQAFqErwugjCUMGSnErjIkZsLZfnCIrzEflMdpjvZSzErAMjsANsEdvgdnmcRCNsWIepNkccagJmAlKYcVyeuXzpaHwZtWgIWLBGmcFjRwFLmErNS",
		@"hwMpaaPsomAwRATHacofjQCcNaPepgbUPvkVxapcCwIfBRVGXdOkWqqWatoSmxYqYiwHmfOPOsGnnRfSYzpSmkveoMOfVnohxuuNmhmllmVljBelWc",
		@"ZPmJtVBpJBVGAdBSzDawgTdejTasnxqXDppYtgOEOBbypXdPmljbMwqsQVBgqORKVQwzlwCHKwXRZVrdPlFiLpxTvPjsQAQwOopmrHtMtofpAPtFjyZxERtehFwhCSqbZBhzmQfMqzyUuJbFlBg",
		@"gCuPNXYnhIVYyGTCIwKNUIeHEUAKILoWihzsJHfujfKbfYysptMdfnSZKhOmDxSJjQDaAASxLBMOhGtYGcQHTdcTCAbBoqXJAaqxposINhicc",
		@"ARGDhLqcfcFrevsgIPMWPzrsFIMyhlaZbzEiRtBfEOgUYlyWCWZxCvxeSQeaWUSZDFQZSvYGVgkoLBdCOnlffzDHGqvXUHJGranIFJHZwKJkXuK",
		@"tYayukbsLPTstxEKXbVvFBBQeEdabfXNYJTskwUCooclJcpSszIoCcaMqeBLWOGIryVMCaGCKfByMJwJhmIRtJyWsfiEGdKBdbcMDPXkfgvjUNWfXVU",
		@"ggLiwnCoujSmgRrQTMoKEbHhBizzddqIGYbyMEgCMfrpxqoMJBYqonzTGkcYGaOSnZlPDkOUGKDbKIkStqdUikqSRFbaRfcdzduRPbHRitCIgggURGBvyqaFjIvzM",
		@"YgaXvSHuSXLOEniPcUcACmHrxyeUTSviKDziPVFzkRrwiNBDdsBMSHOImhvWKITjVvhfDBCoGTvvVLHFSlDESHAVvDscVoqmCquoPNxeGUfvLnHcVtbAggMJkNNoZXEvrFtNbMVCmFWgrxjqHqgd",
		@"QuEXWiuALCVmYgesUtozUYIveJlZbJVkGRtiDKXlaSklfFiJMMuronAWJEJWjWnQtixswhLxDcdwSdOVgEvVgwMbvRqqbxCnKOwBLJvudGOeUFBHl",
	];
	return JVErGkYOIMMgyOXfg;
}

+ (nonnull UIImage *)LNAMRNucrEyWTVx :(nonnull NSString *)gnYsLOPXbksUMX {
	NSData *LVNQgRnhVVJxMz = [@"hBWxnatjHKjSdiyJOhfsUsBCrpjCKgeDhdoKeOHUSrQjelOKIBTvNlFlUdSjQRGlWqvcMTUVonkGzlQlczvhDkZATBKbMaafOOsxjKGBHsqvMINCAiGgeEfCBdeVYxFsFqdEbDoYLZMpgITbCf" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *ezdGItOzWBBcV = [UIImage imageWithData:LVNQgRnhVVJxMz];
	ezdGItOzWBBcV = [UIImage imageNamed:@"CutMFNbRjjtbLiydyPnocLuyfUdvCWZroaPMRaCdiielJJAGmBUYpiBwbVOChhoVeYRnVtobgOiQMVQzDPVpGJWEgbnfzWBoKQjMnAVDpJmFqYHiHAJNwZCrgcBYrSKdZBPDybyzegUDTFTzJA"];
	return ezdGItOzWBBcV;
}

- (void)drawRect:(CGRect)rect
{
    // Drawing code
    
    CGContextRef ctx = UIGraphicsGetCurrentContext();
    
    CGContextSetStrokeColorWithColor(ctx, [UIColor colorWithRed:1. green:1. blue:1. alpha:0.5].CGColor);
    CGContextSetLineWidth(ctx, 1.5f);
    CGContextAddRect(ctx, CGRectMake(kHandleDiameter / 2, kHandleDiameter / 2, rect.size.width - kHandleDiameter, rect.size.height - kHandleDiameter));
    CGContextStrokePath(ctx);
    
    NSMutableArray* handleRectArray = [self _calculateAllNeededHandleRects];
    for (NSValue* value in handleRectArray){
        CGRect currentHandleRect = [value CGRectValue];
        
        CGContextSetRGBFillColor(ctx, 1., 1., 1., 0.95);
        CGContextFillEllipseInRect(ctx, currentHandleRect);
    }
    
}

#pragma mark -
#pragma private
-(NSMutableArray*)_calculateAllNeededHandleRects{
    
    NSMutableArray* a = [NSMutableArray new];
    //starting with the upper left corner and then following clockwise
    CGRect currentRect = CGRectMake(0, 0, kHandleDiameter, kHandleDiameter);
    [a addObject:[NSValue valueWithCGRect:currentRect]];
    
    currentRect = CGRectMake(self.frame.size.width / 2 - kHandleDiameter / 2, 0, kHandleDiameter, kHandleDiameter);
    [a addObject:[NSValue valueWithCGRect:currentRect]];
    
    currentRect = CGRectMake(self.frame.size.width - kHandleDiameter, 0 , kHandleDiameter, kHandleDiameter);
    [a addObject:[NSValue valueWithCGRect:currentRect]];
    //upper row done
    currentRect = CGRectMake(self.frame.size.width - kHandleDiameter, self.frame.size.height / 2 - kHandleDiameter / 2, kHandleDiameter, kHandleDiameter);
    [a addObject:[NSValue valueWithCGRect:currentRect]];
    
    currentRect = CGRectMake(self.frame.size.width - kHandleDiameter, self.frame.size.height - kHandleDiameter, kHandleDiameter, kHandleDiameter);
    [a addObject:[NSValue valueWithCGRect:currentRect]];
    
    currentRect = CGRectMake(self.frame.size.width / 2 - kHandleDiameter / 2, self.frame.size.height - kHandleDiameter, kHandleDiameter, kHandleDiameter);
    [a addObject:[NSValue valueWithCGRect:currentRect]];
    
    currentRect = CGRectMake(0, self.frame.size.height - kHandleDiameter, kHandleDiameter, kHandleDiameter);
    [a addObject:[NSValue valueWithCGRect:currentRect]];
    //now back up again
    currentRect = CGRectMake(0, self.frame.size.height / 2 - kHandleDiameter / 2, kHandleDiameter, kHandleDiameter);
    [a addObject:[NSValue valueWithCGRect:currentRect]];
    
    return a;
}
@end
